### ISSUE TITLE
Change Sageo UI Images to white Font when Black Theme is enabled

### ISSUE THREAD

**Issue by christian-becker-ta** [MicrosoftDocs/windows-uwp#10]
Change Sageo UI Images to white Font when Black Theme is enabled.

Can't see the icons on black theme,

**Comment by mattwojo** [comment]
Hi @TiMeJuMp - Thanks for filing this issue. Are these the icons you are referring to in the black theme...?
![image](https://cloud.githubusercontent.com/assets/7566797/23191221/588b2a88-f851-11e6-9747-f677a54a027d.png)

I agree that these are harder to see in blue. I'll connect with the platform devs and see if there is a reason for not changing these to the white (or light grey) font.

**Comment by christian-becker-ta** [comment]
Hi @mattwojo 
no i mean the icons a few sites down. 
![image](https://cloud.githubusercontent.com/assets/6890804/23263710/5ad86618-f9df-11e6-84d6-f0e30527a6a5.png)

**Comment by mattwojo** [comment]
Ahh -- I see what your talking about now. Agh, not good. Let me see what I can do. Thanks @TiMeJuMp!

**Comment by christian-becker-ta** [comment]
Thanks @mattwojo 
This is clever :) 
![image](https://cloud.githubusercontent.com/assets/6890804/23738425/1ba8a2f4-0499-11e7-88b7-1925c0567c36.png)

**Comment by mattwojo** [comment]
Thanks @TiMeJuMp  -- Please let us know if you see any other issues. Closing this one out. 👍
