### ISSUE TITLE
paid apps

### ISSUE THREAD

**Issue by chrism9876** [MicrosoftDocs/windows-uwp#1001]
I have added payment info and a tax profile but i cant change from free to paid. im in the UK

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec06af90-a369-e18e-dffd-30443c415f33
* Version Independent ID: dae3fe06-e22a-7c3f-c0eb-03220929f0ef
* Content: [Set up your payout account and tax forms - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Please open a support request at http://aka.ms/storesupport so that someone can investigate further.
