### ISSUE TITLE
Windows 10, Visual Studio Enterprise 2017, 15.8.5 extra steps

### ISSUE THREAD

**Issue by NancyFolsom** [MicrosoftDocs/windows-uwp#1005]
Just to save people a little time...
The samples link goes to "Windows-tutorials-inputs-and-devices/GettingStarted-Ink/", but you want .https://github.com/Microsoft/Windows-tutorials-inputs-and-devices
I had to install and then update the Microsoft.NETCore.UniversalWindowsPlatform nuget package. 
Then I had to enable developer mode in Windows settings. (When I tried running the solution, the settings opened.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c640c640-4004-c313-c066-3d47c634778e
* Version Independent ID: b5c02659-7241-996a-8408-9fba83a755f1
* Content: [Support ink in your UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/ink-walkthrough#sample-code)
* Content Source: [windows-apps-src/design/input/ink-walkthrough.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/ink-walkthrough.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback @NancyFolsom! I've updated the doc to include your suggestions in the prerequisites section.
