### ISSUE TITLE
A gif in "Responsive design techniques" has a very tiny issue

### ISSUE THREAD

**Issue by KLszTsu** [MicrosoftDocs/windows-uwp#1007]
The gif in [Responsive design techniques#Resize](https://docs.microsoft.com/en-us/windows/uwp/design/layout/responsive-design#resize) is as follows:  
![rspd-resize2.gif](https://docs.microsoft.com/en-us/windows/uwp/design/layout/images/rsp-design/rspd-resize2.gif)

### What has happened
Pay attention to the 20th and the 21th line in the first half of the gif; It is too early that the two lines stop getting longer, and the issue appears oppositely in the second half as well.  

### What should happen
In these screenshots, I've roughly drawn the length that the two lines should be.  
![49](https://user-images.githubusercontent.com/12217600/45862353-db62de80-bd60-11e8-9d04-a4383625cd03.png)
![50](https://user-images.githubusercontent.com/12217600/45862354-dbfb7500-bd60-11e8-8310-bea9ea2e4349.png)
![51](https://user-images.githubusercontent.com/12217600/45862356-dbfb7500-bd60-11e8-8f3c-8ae1417eae78.png)

Thanks.

**Comment by KLszTsu** [comment]
It seems that the issue is too tiny; I shall close it then.  

Thanks.

**Comment by mijacobs** [comment]
@KuangLei  Thank you for your attention to detail--I'll share this with the design team.

**Comment by minah-kim** [comment]
@mijacobs I see it! I will relay the feedback to the motion designer and put this on our todo list. will let you know when it gets updated!
