### ISSUE TITLE
NavigationView.PaneFooter hittest bug

### ISSUE THREAD

**Issue by shithappens2016** [MicrosoftDocs/windows-uwp#1008]
```xml
<NavigationView PaneDisplayMode="Top">
  <NavigationView.PaneFooter>
    <NavigationViewItem Icon="List" />
 </NavigationView.PaneFooter>
</NavigationView>
```
**Look at this shit:**
![bug](https://user-images.githubusercontent.com/13523412/45873161-590c0600-bdc4-11e8-89c5-7e5f9e4bca0c.gif)

**Comment by ginami** [comment]
Hi @shithappens2016 -- thanks for your comment. Is this feedback on a specific doc, or are you looking for support help?
