### ISSUE TITLE
init_apartment() in the example code for "General-purpose collection, empty" section

### ISSUE THREAD

**Issue by soojinhung** [MicrosoftDocs/windows-uwp#1009]
what is the role of that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449f8eee-26f7-82fd-fa40-690b2c01d835
* Version Independent ID: 3431bcaa-7566-ca31-3d49-79a4773f845e
* Content: [Collections with C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/collections)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/collections.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/collections.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the question, @soojcho. The call to the **winrt::init_apartment** function initializes COM; by default, in a multi-threaded apartment. But you can pass an argument to init_apartment if you need a single-threaded apartment.

I've added that info to the topic, and that fix should be live on Monday morning.

Thanks again!
~Steve
