### ISSUE TITLE
Broken link: http://developer.microsoft.com/xboxactivate.

### ISSUE THREAD

**Issue by ericlemes** [MicrosoftDocs/windows-uwp#1010]
Tried to follow the procedure, but the link landed on invalid homepage. Couldn't find further instructions about how to create a devkit and associate my gamer account to the devkit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc064e49-5f24-ff80-d511-7f1947fc39da
* Version Independent ID: b8ad47c2-8264-c232-167f-b9ee69d6dce1
* Content: [Xbox One Developer Mode activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **scotmi**

**Comment by mtoepke** [comment]
Thanks @ericlemes ,  I'm seeing the same thing.  The product team is investigating.

**Comment by mtoepke** [comment]
@ericlemes , there have been some recent changes to Partner dashboard routing.  Try these links:
https://partner.microsoft.com/xboxactivate
or https://partner.microsoft.com/en-us/xboxdevices?activate=1

Also, to manage your devices once registered: https://partner.microsoft.com/XboxDevices

Thanks,
Mike

**Comment by mtoepke** [comment]
All links should be functioning correctly now.  You can also open a new InPrivate window if you encounter this.  If you run into any further issues, let us know.

**Comment by djarcas** [comment]
Looks like they're all broken again, and all redirect to : https://partner.microsoft.com/en-us/dashboard/directory

**Comment by MaxwellDPS** [comment]
Its still broken

**Comment by mtoepke** [comment]
The https://partner.microsoft.com/en-us/xboxconfig/devices link is the correct link and should be working.  Make sure you are logged into Partner Center with a valid, registered app developer account.

Here are some more detailed steps (particularly Step 6, to verify you are logged in with the correct account type):

5.	[Register an app developer account in Partner Center](https://developer.microsoft.com/store/register).  This is also the first step towards publishing your game.

6.	Sign in to [Partner Center](https://partner.microsoft.com/dashboard) with your valid, current Partner Center app developer account.  If you don't see multiple options in the left hand navigation pane, or don't see the **Create a new app** option in the **Overview** section, the following steps and activation links _will not work_; make sure you fully registered your app developer account from the previous step.

7.	Go to [partner.microsoft.com/xboxconfig/devices](https://partner.microsoft.com/xboxconfig/devices).
