### ISSUE TITLE
Not able to find "CheckedOutByYou12" Icon

### ISSUE THREAD

**Issue by swapmusale** [MicrosoftDocs/windows-uwp#1012]
I am not able to find "CheckedOutByYou12" Icon in mdl2 file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
I don't see this on the page anymore, might have been a typo that's since corrected.
