### ISSUE TITLE
UWP programming in C++ should focus on C++ WinRT, not CX

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1015]
This section about C++ should be using C++ WinRT instead of (or in addition to) C++ CX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d9dce9-1e73-1732-9b14-188a492ca396
* Version Independent ID: 03126c67-93bd-2e42-691c-94c7bf85f50d
* Content: [Asynchronous programming in C++ - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps)
* Content Source: [windows-apps-src/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hi ChrisGuzak - We do indeed have an entire set of content devoted to C++/WinRT here - https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt. This specific topic is about async with CX for those still maintaining code bases in CX, but for visibility, there is a note at the top of this topic directing folks to C++/WinRT and recommending C++/WinRT. Thx!
