### ISSUE TITLE
BundleMapping.txt is used to generate AppxBundleManifest.xml, this page should say so

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1016]
the VS tooling describe on this page does this for you, but readers will want to find the documentation on the generated file to understand the relationships created by them. this page should mention the name and link to the schema. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47d552a-824c-e79e-f673-fd2e3091bd5f
* Version Independent ID: 592317cf-65bc-b698-3332-1cd26d2255d9
* Content: [Optional packages and related set authoring - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/optional-packages#related-sets)
* Content Source: [windows-apps-src/packaging/optional-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/optional-packages.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay in addressing it. I have updated [the article](https://docs.microsoft.com/en-us/windows/msix/package/optional-packages#related-sets) with a link to the bundle manifest schema.
