### ISSUE TITLE
This page should expand on what 'tightly coupled' means for related sets

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1017]
I understand that a link from the main package to the optional (using the name of the .appxbundle file + version), and the optional to the main (using the version independent name) defines the related set. 

I also understand that tightly coupled means this:

versioning of the packages in a related set is synchronized in a way that won't allow the latest version of any package to be used until *all* of the related set packages (specified by version in the main package) have completing their install. Packages are serviced independently (atomically) but the use of the packages specified in the set may not be used until all have been updated.  The old version of the packages are retained until this state has been achieved.

Also, the part about packages with code needing to use related sets is incorrect. While related sets help maintain computability between components as they change their ABIs you can use a package with code without this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47d552a-824c-e79e-f673-fd2e3091bd5f
* Version Independent ID: 592317cf-65bc-b698-3332-1cd26d2255d9
* Content: [Optional packages and related set authoring - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/optional-packages#related-sets)
* Content Source: [windows-apps-src/packaging/optional-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/optional-packages.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay in responding. I have expanded the [related sets](https://docs.microsoft.com/en-us/windows/msix/package/optional-packages#related-sets) discussion with the additional info you provided, and I removed any text that indicates that related sets are required to load code in an optional package.
