### ISSUE TITLE
explain what OptionalProjects and ExternalPackages sections in Bundle.Mapping.txt specify

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1018]
The example Bundle.Mapping.txt file has 2 sections but nothing on this page explains how these are different. please update the page to cover this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47d552a-824c-e79e-f673-fd2e3091bd5f
* Version Independent ID: 592317cf-65bc-b698-3332-1cd26d2255d9
* Content: [Optional packages and related set authoring - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/optional-packages)
* Content Source: [windows-apps-src/packaging/optional-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/optional-packages.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay in responding to this issue. I have updated [the article](https://docs.microsoft.com/en-us/windows/msix/package/optional-packages) with more specific details and additional links to related blog posts for more background info.
