### ISSUE TITLE
AppExecutionAlias over SSH

### ISSUE THREAD

**Issue by aronyu79** [MicrosoftDocs/windows-uwp#1019]
I've been trying to run a console app with an AppExecutionAlias in PowerShell via SSH. It does not seem to recognize the aliases. E.g this would be perfect to create a unit-test app to run over Jenkins.

I ssh into my jenkins agent and start powershell. Installing the app works perfectly fine but when running it with the alias it fails with CommandNotFoundException. Anyone else have this experience?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18c877b-42e4-a463-8092-72520d8c8915
* Version Independent ID: b35cd713-4d41-f4c6-b559-84f8da3d14cf
* Content: [Create a Universal Windows Platform console app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp)
* Content Source: [windows-apps-src/launch-resume/console-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/console-uwp.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by ginami** [comment]
Hi @aronyu79 -- thanks for your comment. It looks like you're hoping for some dev community help? This channel is really for feedback specific to our docs...have you tried the Windows UserVoice? https://wpdev.uservoice.com/. If you do have doc feedback, please let us know.
