### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by LohanSolo** [MicrosoftDocs/windows-uwp#1020]
When I tried the above steps it says "No features to install.". No work around. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0553184-52d1-08d9-1ffd-ab80c14c559a
* Version Independent ID: a0f8735c-eea7-9c5b-0d07-52b0ed7676d1
* Content: [Graphics diagnostics tools - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features?f=255&MSPPError=-2147217396)
* Content Source: [windows-apps-src/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mtoepke**

**Comment by stephan735** [comment]
Same here!  "No features to install".  System setup is Win10 with Visual Studio 2017. Trying to run the performance profiler with the GPU usage tool.

**Comment by mtoepke** [comment]
Hi @LohanSolo and @stephan735 ,

Thanks for your question.  It looks like a few people have hit this issue; some Windows installs aren't showing those options (it's not specifically related to Graphics Tools).

Here are some solutions to try:
http://www.surfacetablethelp.com/2018/01/fix-no-features-to-install-optional-features-in-windows-10.html

https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/windows-10-optional-features-missing/c9555e72-11ed-416a-bc65-1a8372fc27ab

https://superuser.com/questions/1003359/unable-download-speech-language-in-windows-10

https://social.msdn.microsoft.com/Forums/vstudio/en-US/7afbaa03-fdad-41b6-8002-520a528f9647/graphics-tools-refuses-to-install?forum=vsga

If you still don't see any features to install, I'd suggest asking a question on one of these forums:
https://answers.microsoft.com/en-us/windows/forum/windows_10-update
https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=vsga
