### ISSUE TITLE
productTypes is required, and is not a string.

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/windows-uwp#1021]
The *Request Body* table defines `productTypes` as not being required. However, when left off, the request returns:

```json
{
  "code":"BadRequest",
  "data":[],
  "details":[],
  "innererror": {
    "code":"InvalidRequestBody",
    "data":["Required property 'productTypes' not found in JSON. Path '', line 1, position 1720."],
    "details":[],
    "message":"The request body passed is invalid."
  },
  "message":"The calling client sent a bad request to the service.",
  "source":"CollectionsFD"
}
```

Also, when passing it as a `string` (what the table defines) gives an error. The example code (using a string array) appears to be correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b95f043-9483-170e-3aef-fa675bfc0fb7
* Version Independent ID: 819f2b1e-a55b-7b05-bf54-111eed1a9916
* Content: [Query for products - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products)
* Content Source: [windows-apps-src/monetize/query-for-products.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/query-for-products.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for opening this issue. I have updated the productTypes description in the article (noted that it is required and a string array), and the revised article should be published to the live docs site in the next few days.
