### ISSUE TITLE
Incomplete example

### ISSUE THREAD

**Issue by Solrax** [MicrosoftDocs/windows-uwp#1022]
This example will not build as is. There will be numerous undefined types. This is very confusing to people trying to learn this for the first time.

I was able to get this to build by including the following include files in pch.h:
#include &lt;d2d1_1.h&gt;
#include &lt;d3d11.h&gt;
#include &lt;dxgi1_2.h&gt;
#include "winrt/Windows.Graphics.Display.h"

However I don't know if this is "correct" WinRT/C++, I could not find most of the missing symbols defined anywhere but in the standard include files, but not in any winrt/ files aside from winrt/Windows.Graphics.Display.h

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af9e408c-eb0e-ffb2-4aa2-be13f64efeef
* Version Independent ID: c9fa2a65-c043-b693-286d-005dc0697d2d
* Content: [Consume COM components with C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-com)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-com.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-com.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Solrax, you're right! I'll go ahead and publish this fix as soon as I can (early next week is when the next publishing event will be). Thanks for filing this issue, and for including the solution.

~Steve

**Comment by Solrax** [comment]
Thank you for the quick response!
