### ISSUE TITLE
Windows version support

### ISSUE THREAD

**Issue by chainhead** [MicrosoftDocs/windows-uwp#1023]
Is Windows 10 Pro recent compared with 'Windows 10 Fall Creators Update'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2254d309-a79d-b6ed-fb4c-73ef689b76ec
* Version Independent ID: 96fa695b-4f0e-4d09-4b26-f7a501a78c9c
* Content: [Installing UWP apps from a web page - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/installing-uwp-apps-web)
* Content Source: [windows-apps-src/packaging/installing-UWP-apps-web.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/installing-UWP-apps-web.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by ginami** [comment]
Hi @chainhead -- does this page answer your question? https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version
