### ISSUE TITLE
No links?

### ISSUE THREAD

**Issue by mmillmor** [MicrosoftDocs/windows-uwp#1032]
Why are there no links to the pages to do these actions? They are impossible to find, and a link in here would save hours.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec06af90-a369-e18e-dffd-30443c415f33
* Version Independent ID: dae3fe06-e22a-7c3f-c0eb-03220929f0ef
* Content: [Set up your payout account and tax forms - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for this feedback and sorry for the delayed response. I plan to add the appropriate links and will close this issue when that is done.

**Comment by piyushgoel1973** [comment]
we need to upload W8 for the payout, the dashboard is throwing error across all browsers.

**Comment by JnHs** [comment]
Thanks for letting me know. I've passed along the info to investigate if there is a global issue. In the meantime you might want to open a support request at http://aka.ms/storesupport - we can't provide troubleshooting assistance through these doc feedback comments.

**Comment by JnHs** [comment]
Getting back to the original issue, I've added links to sign in to Partner Center, from which you can navigate to these pages using the instructions provided. I hope this is helpful.
