### ISSUE TITLE
Need mentions about setting available tiles size in the Package.appxmanifest

### ISSUE THREAD

**Issue by Code-ScottLe** [MicrosoftDocs/windows-uwp#1037]
I caught myself questioning why I don't get large tiles option in the Start Menu even though I do send large tile payload through the app quite often , as I forgot to set the Large tile assets in the Package.appxmanifest first (and I don't think this get mentioned anywhere). Would be a valuable addition to the doc under Tile sizes section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3093664e-3597-0b6d-6042-a10d2f9d3fda
* Version Independent ID: 4ff76ce1-c7b9-5cda-7276-bdd7f57ca406
* Content: [Create adaptive tiles - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/create-adaptive-tiles#getting-started)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/create-adaptive-tiles.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/create-adaptive-tiles.md)
* Product: **windows**
* GitHub Login: @andrewleader
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Info about large tile sizes has been added to the Tile sizes section.
