### ISSUE TITLE
Failed to install app app package due to unknown error !!!

### ISSUE THREAD

**Issue by JD-V** [MicrosoftDocs/windows-uwp#1038]
![issue](https://user-images.githubusercontent.com/6457154/46397388-c0ed1580-c70f-11e8-8f3f-79d9e9715374.jpg)

unable to install app package due to **unknown error**,

**Comment by ginami** [comment]
Hi @JD-V -- this channel is for specific feedback on our docs.  Are you looking for support help or community help? Our dev support options, including community forums,  are here: https://developer.microsoft.com/en-us/windows/support. If you have feedback on one of our docs pages, please let us know. Thank you!
