### ISSUE TITLE
App startup time

### ISSUE THREAD

**Issue by mjmeans** [MicrosoftDocs/windows-uwp#1042]
I've read docs [here](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/best-practices-for-your-app-s-startup-performance). And have also watched the \build form 2015 on using the performance profiler. Neither give me sufficient guidance on how to diagnose startup performance for issues that the profiler can't find.

I'm having a major startup performance problem. Using VS 2017 Performance Profiler is shows about 56 seconds in App Code during startup where there is no CPU activity at all. The 56 seconds are in Layout of only 19 elements. When I expand the triangle to see what elements are there, I see only 2 entries, one with 9 elements and a layout time of 0.38 ms and the other of 8 elements with a layout time of 3.42 ms. So it lists only 17 of the 19 elements; the other 2 elements taking the lion share of the time are not shown! In my xaml I don't even see evidence of two other elements, so these must be something .NET is injecting somehow. Where and what are the two elements that are not reported in the profiler that are taking up so much of the startup layout time? How to I determine the cause of this poor startup time?

My app uses Windows Template Studio,
- Microsoft.EntityFrameworkCore.Sqlite 2.1.4,
- Microsoft.NETCore.UniversalWindowsPlatform 6.1.7, 
- Microsoft.Services.Store.Engagement 10.1711.28001,
- Microsoft.Services.Store.SDK 10.1705.16001,
- Microsoft.Toolkit.Uwp.UI.Controls 4.0.0,
- Microsoft.Xaml.Behaviors.Uwp.Managed 2.0.0,
- MyToolkit.Extended 2.5.16,
- Newtonsoft.Json 11.0.2,
- Prism.Unity 6.3.0,

![image](https://user-images.githubusercontent.com/3971751/46456538-18b56c00-c764-11e8-928e-6b435cb9a296.png)

**Comment by jwmsft** [comment]
See linked WindowsTemplateStudio issue #2621.
