### ISSUE TITLE
Document link broken

### ISSUE THREAD

**Issue by Tennyleaz** [MicrosoftDocs/windows-uwp#1043]
[Enter feedback here]
The hyper link in microsoft docs is broken:
The link at the end of page `GamepadVibrationUWP sample (github)` should be [https://github.com/Microsoft/Xbox-ATG-Samples/tree/master/UWPSamples/System/InputInterfacingUWP](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0555da93-c74a-9898-f704-9be6789c89b3
* Version Independent ID: a587d9fe-a991-8111-9be1-cefe4a41bc0b
* Content: [UI navigation controller - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/ui-navigation-controller)
* Content Source: [windows-apps-src/gaming/ui-navigation-controller.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/ui-navigation-controller.md)
* Product: **windows**
* GitHub Login: @mithom
* Microsoft Alias: **wdg-dev-content**

**Comment by mithom** [comment]
Where does this come from and how am i connected to this? Can you explain. I think i am missing something
