### ISSUE TITLE
Usage from a desktop application

### ISSUE THREAD

**Issue by shmuelie** [MicrosoftDocs/windows-uwp#1046]
Can a desktop (WPF, Win32, etc) application integrate with My People or only UWP apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f1ed66-689e-e446-7551-9795b6f6689b
* Version Independent ID: 5bed3097-b066-4b6e-d358-5b53106b26c5
* Content: [Adding My People support to an application - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/my-people-support)
* Content Source: [windows-apps-src/contacts-and-calendar/my-people-support.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/contacts-and-calendar/my-people-support.md)
* Product: **windows**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by GrantMeStrength** [comment]
My People has been deprecated, sorry.
