### ISSUE TITLE
Only show dialog to users which havn't rated the app already

### ISSUE THREAD

**Issue by christian-becker-ta** [MicrosoftDocs/windows-uwp#1052]
Is there a way to check if the user has already rated or not, before he gets the rating and review dialog displayed?

Because I don't want to annoy my users who have already rated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291dc819-9b43-818a-f839-f69d0a0b432e
* Version Independent ID: d6cfeb3b-dd87-e0df-95a2-8b1d282f24a3
* Content: [Request ratings and reviews for your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/request-ratings-and-reviews#)
* Content Source: [windows-apps-src/monetize/request-ratings-and-reviews.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/request-ratings-and-reviews.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
