### ISSUE TITLE
Five points for error 2001 when uploading

### ISSUE THREAD

**Issue by GeorgRottensteiner** [MicrosoftDocs/windows-uwp#1053]
I really wish there was more info on how to tackle the five issues for error 2001. I'm writing a C++/RT app, I can debug it on a Windows Phone fine, but getting the app package uploaded successfully is eluding me.

ILDASM fails to open my executable (says no CLR header found), I don't know how to properly check for mixed mode assemblies (my .exe doesn't open with ILDASM, so I'd say it's purely native). 

ILDASM can open the .winmd file (which is only 1 KB?), shows no entry point at all (which is set in the appxmanifest file). It only has this:
// Metadata version: WindowsRuntime 1.3
.assembly extern windowsruntime platform
{
  .ver 255:255:255:255
}
.assembly extern windowsruntime Windows
{
  .ver 255:255:255:255
}
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 255:255:255:255
}
.assembly windowsruntime HitBlockUniversal8_1
{
  .hash algorithm 0x00008004
  .ver 255:255:255:255
}
.module HitBlockUniversal8_1.winmd
// MVID: {7BEF2973-EDA4-49D6-93A4-2532FA2377B0}
.imagebase 0x10000000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x04BB0000

I'm really at a loss how to properly tackle these five issues and would love some more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0973c3-07c3-882e-46be-783dc13e575f
* Version Independent ID: 6877aae0-2aab-46f7-dd3a-16dd7d3bf842
* Content: [Resolve submission errors - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/resolve-submission-errors#windows-phone-8x-and-earlier)
* Content Source: [windows-apps-src/publish/resolve-submission-errors.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/resolve-submission-errors.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Please open a support request at http://aka.ms/storesupport for help with these errors. Thanks!
