### ISSUE TITLE
Worse than animals

### ISSUE THREAD

**Issue by OmPisit** [MicrosoftDocs/windows-uwp#1054]
กุเชื่อเลยพวกมืงนี่เลวยันเงา เลวได้ใจกุจริงๆ หมาข้างบ้านกุยังมีน้ำใจดีกว่าพวกมืงเสียอีก

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: ac89746a-7629-6a95-6c5c-9498a9d7989f
* Version Independent ID: 044558cb-9f69-42df-362c-6c35317c3411
* Content: [App icons and logos - UWP app developer](https://docs.microsoft.com/th-th/windows/uwp/design/style/app-icons-and-logos)
* Content Source: [windows-apps-src/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/app-icons-and-logos.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by ginami** [comment]
Thanks for your feedback, @OmPisit . Please let us know if you have any specific comments on our docs.
