### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by OmPisit** [MicrosoftDocs/windows-uwp#1055]
สัตว์ พวกชิงหมาเกิดทั้งนั้น เยดแม่เอ้ย แอพพ่อมืงหรอมี ปุ่มเดียว สร้างให้พ่อมืงใช้หรอ

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/th-th/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by ginami** [comment]
Hi @OmPisit -- please let us know if you specific feedback on our docs.
