### ISSUE TITLE
Account payment error

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#1065]
I want to open a developer account when I see this error:
"Error code 6152.
Your payment provider declined this transaction. Please use a different payment method."
And for that the payment subtracts 21,000 VND (0.90 USD) on my account. Can you tell me more about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a5c98-ba0b-38a0-d86e-2d5df4745d1a
* Version Independent ID: 643673cc-0b57-86f6-e00d-13aad2ef8d20
* Content: [Opening a developer account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account#closing-your-account)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I have not heard of anything like this before - please open a support request at http://aka.ms/storesupport so we can gather more info and look into this.
