### ISSUE TITLE
Unexplained placement properties

### ISSUE THREAD

**Issue by ObsidianMinor** [MicrosoftDocs/windows-uwp#1068]
There's a section in this article about "Placement" and it talks about how you can place the command bar on the top of the screen, on the bottom of the screen, or both. But it doesn't provide any example code or any information about how to adjust the placement of the command bar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98322266-0c75-2d32-6823-1f695b150ad5
* Version Independent ID: 71f91d0a-0b20-eecc-0889-a2d1828f2ad4
* Content: [Command bar - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars#placement)
* Content Source: [windows-apps-src/design/controls-and-patterns/app-bars.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/app-bars.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by ghost** [comment]
You can do it placing the ```CommandBar``` inside a ```Grid.Row```.

**Comment by QuinnRadich** [comment]
Sorry to leave this issue unresolved for so long, and thanks for your patience on this. As recommended by the above comment, I've added a notice to the page that the CommandBar can be embedded in a layout control such as Grid.Row.

Thank you.
