### ISSUE TITLE
Can you link to a sample project?

### ISSUE THREAD

**Issue by techjogger** [MicrosoftDocs/windows-uwp#1070]
Can you link to a sample project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9b1bd20-afd5-4520-2b3f-24da95525afe
* Version Independent ID: 1aa742aa-2bdc-c8bf-ee94-fbaeaa0558d0
* Content: [Interop between C++/WinRT and C++/CX - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/interop-winrt-cx)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/interop-winrt-cx.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/interop-winrt-cx.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @techjogger, I've now updated this topic with more information. If you follow the steps in the topic now, then you can create a new sample project of your own. You just create a new project, set a property, and paste in some code. The full details are in the topic right now.

Please let me know whether this new info is helpful and/or sufficient.

Thanks!
~Steve
