### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by hocalvin79** [MicrosoftDocs/windows-uwp#1071]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b08c6292-c94c-2d95-e800-b14d404879f9
* Version Independent ID: 83029484-dc65-6c17-80f3-e75a6bbc6732
* Content: [Display ads in your app with the Microsoft Advertising SDK - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/monetize/display-ads-in-your-app#step-1-install-the-microsoft-advertising-sdk)
* Content Source: [windows-apps-src/monetize/display-ads-in-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/display-ads-in-your-app.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by ginami** [comment]
Hi @hocalvin79 -- please let us know if you have specific feedback for our docs. Thank you!
