### ISSUE TITLE
Windows speech recognition show numbers doesn't work on it

### ISSUE THREAD

**Issue by sanjeev3094** [MicrosoftDocs/windows-uwp#1073]
When using windows speech recognition the buttons are not given any number, so no action can be taken by the windows speech recognition leaving me blocked once the content dialog opens.
Note: It works only for ContentDialog which is shown when App launches, but subsequent ContentDialog doesn't work. So in this topic, you should cover these aspects too mentioning the limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9ddfce6-8448-0c9a-8b1f-be4340f34163
* Version Independent ID: b40cacc2-ed19-190b-7a00-9d2075b74191
* Content: [Dialog controls - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@chigy Is this a known issue with ContentDialog?

**Comment by chigy** [comment]
@sanjeev3094, I just tested the speech recognition and ContentDialog does appear to support show buttons functionality so the control appears to support the functionality properly. Which particular UI are you having problem wtih?

**Comment by chigy** [comment]
Closing per no response. As far as I could tell, this was working properly on our ContentDialog.
