### ISSUE TITLE
GridView ItemClick

### ISSUE THREAD

**Issue by tnc1997** [MicrosoftDocs/windows-uwp#1074]
Hi all, great tutorial series! In Part 5 of this tutorial, I was unable to get the GridView ItemClick event firing with only `ItemClick="ImageGridView_ItemClick"`. I had to also add `IsItemClickEnabled="True"` to the GridView in order to get the ItemClick event firing. Perhaps this additional property could be added to the `&lt;GridView x:Name="ImageGridView" ItemClick="ImageGridView_ItemClick"` code snippet?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e1469e-467e-0a5a-9220-3878fa59e8a6
* Version Independent ID: 0f394306-66bf-7c45-07b5-16e92dc2f68d
* Content: [Create data bindings - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/data-binding/xaml-basics-data-binding)
* Content Source: [windows-apps-src/data-binding/xaml-basics-data-binding.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/xaml-basics-data-binding.md)
* Product: **windows**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by jwmsft** [comment]
Thanks for pointing this out. The missing code for `IsItemClickEnabled="True"` has been added to the tutorial.
