### ISSUE TITLE
Doc on package version numbers could be more precise

### ISSUE THREAD

**Issue by PaulCapron** [MicrosoftDocs/windows-uwp#1075]
Hello,

The documentation on what constitutes a valid UWP package version number is vague.

Worse, if you search on the Web what, for instance, are the minimum and maximum values for a version number, you may end up mistaken. All I could find were _official_ but _unfit/obsolete_ documents, like https://docs.microsoft.com/windows/desktop/msi/productversion which talks about non-UWP apps, and says that the maximum value for major and minor versions is 255. (This is _not_ true for UWP package versions, see below.)

https://docs.microsoft.com/windows/uwp/publish/package-version-numbering says:

> “The Microsoft Store enforces certain rules related to version numbers, which work somewhat differently in different OS versions.” 

Maybe that means that Microsoft is unwilling to set the rules in stone. Or maybe that just means that noone took the time to document these rules properly. Given that Microsoft does offer documentation on manual app packaging (see https://docs.microsoft.com/en-us/windows/uwp/packaging/manual-packaging-root), I’ll go with the second option 😉

So, from trial-and-error on manually packaging a not-yet-published app, here is what I found:

- **the major number cannot be 0**. This is actually mentionned on https://docs.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-identity but this info could be duplicated on https://docs.microsoft.com/windows/uwp/publish/package-version-numbering. Actually, I think the Identity element doc should just link to /package-version-numbering and omit this detail, because they are more details that are good to know:
 

- **the “build” number is reserved for Store use.** I don’t remember if I tested that one for real, or if I read that somewhere, or if I just deduced that from seeing that the “build number” input field is disabled/read-only on screenshots of Visual Studio (e.g. https://csharpcorner-mindcrackerinc.netdna-ssl.com/article/creating-app-packages-in-visual-studio/Images/image003.png)

-  the major, minor, revision, and probably build **numbers** are **16-bit unsigned integers** (so the minimum is 0, the **max 65535**). This I got from trial-and-error.

Are you willing to accept a pull-request adding these pieces of information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2cf9ad-4db6-ded2-1a9b-147920eb01d0
* Version Independent ID: a1e7f20d-b7a2-f79b-09f3-7873fca8a2e4
* Content: [Package version numbering - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/package-version-numbering)
* Content Source: [windows-apps-src/publish/package-version-numbering.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/package-version-numbering.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Hi Paul - thanks for pointing these out. We do mention that the last number must be set to 0 and is reserved for Store use in the "Important" note near the top of the topic, but the other points you mention would be good to include as well. I'm confirming that this is all accurate (and if there are any other caveats or restrictions to mention) and will get the topic updated once I do so!

**Comment by JnHs** [comment]
Thanks for your patience - I updated the "Important" note to include all of these points. Appreciate your bringing this up!

**Comment by PaulCapron** [comment]
Oh there was no hurry :) Thanks for updating the doc!
