### ISSUE TITLE
Submit presence

### ISSUE THREAD

**Issue by JulienVink** [MicrosoftDocs/windows-uwp#1076]
I'm here who else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127f67d8-f9fc-8ec6-4131-b4ba8a9c402a
* Version Independent ID: 9c4db5fb-884d-aaf5-78cb-b80e7a2089a9
* Content: [Engage with your customers - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/engage-with-your-customers)
* Content Source: [windows-apps-src/publish/engage-with-your-customers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/engage-with-your-customers.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @JulienVink -- please let us know if you have any specific feedback for our docs. Thank you!
