### ISSUE TITLE
Windows.UI.Xaml Package Default Templates

### ISSUE THREAD

**Issue by TyBarthel** [MicrosoftDocs/windows-uwp#1077]
Is there a place where these default templates (i.e. NavigationView) are available?  

It makes it much easier to provide a custom template when using the default as a starting point.

**Comment by jwmsft** [comment]
Hi @TyBarthel, if you have the SDK installed, you'll find the default XAML control templates in the generic.xaml file located at C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\<SDK version>\Generic. You can find more info in [XAML theme resources](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/xaml-theme-resources).

**Comment by michael-hawker** [comment]
It'd be nice if the latest versions were updated on the [Default control styles and templates](https://msdn.microsoft.com/en-us/library/windows/apps/mt299122.aspx) page, I think it was last updated for RS2.  It's a huge mess to crawl through generic.xaml.  And the individual pages I linked to nicely separated out the VisualStates for each control as well as the utilized resources.

**Comment by TyBarthel** [comment]
Updated styles and templates page would be great.  

I was aware of the SDK generic XAML locations locally, but I mainly wondering about the prerelease NuGet packages since they are shipping out of band from the SDK.

**Comment by YuliKl** [comment]
@TyBarthel, Xaml controls have been open sourced. You can find latest code and styles at https://github.com/Microsoft/microsoft-ui-xaml. Please let us know if you run into any controls problems by opening issues on that repo.

**Comment by michael-hawker** [comment]
@YuliKl what about the inbox controls that aren't part of that package yet?  There's also still extra info in the docs like separating out Visual States and Style Resources which can be customized above the style itself.  So, I think this work item is still useful about the documentation of the styles themselves.

**Comment by YuliKl** [comment]
@michael-hawker The overhead of maintaining copies of styles and templates and keeping these in sync with generic.xaml is prohibitive.
