### ISSUE TITLE
`key` in the request is required.

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/windows-uwp#1079]
It's pretty obvious that it would be, otherwise there isn't anything to renew, but I confirmed anyway that the HTTP fails if it is excluded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b504355-1c98-acbd-7063-273771028f26
* Version Independent ID: d64bd82e-67eb-a4ed-e0dd-cb67bf7ea0bb
* Content: [Renew a Microsoft Store ID key - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/renew-a-windows-store-id-key)
* Content Source: [windows-apps-src/monetize/renew-a-windows-store-id-key.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/renew-a-windows-store-id-key.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this error! I have fixed the article to reflect that the key is required, and this change should show up on the live docs site in a few days.
