### ISSUE TITLE
Xbox activate link broken once more 

### ISSUE THREAD

**Issue by djarcas** [MicrosoftDocs/windows-uwp#1081]
http://developer.microsoft.com/xboxactivate.
Tried to follow the procedure, but the link landed on invalid homepage. Couldn't find further instructions about how to create a devkit and associate my gamer account to the devkit.

I tried the links:

https://partner.microsoft.com/xboxactivate
or https://partner.microsoft.com/en-us/xboxdevices?activate=1

Also, to manage your devices once registered: https://partner.microsoft.com/XboxDevices

as suggested by @mtoepke but to no avail.

**Comment by mtoepke** [comment]
Hi @djarcas 

You'll need to first sign into Dev Center with your Windows Dev Center account, then you should be able to follow that link.

See https://docs.microsoft.com/en-us/windows/uwp/publish/using-the-windows-dev-center-dashboard for information on Dev Center and creating an account.

**Comment by djarcas** [comment]
Yup, I'm signed in, and it just takes me to the page, via 

https://login.microsoftonline.com/common/oauth2/authorize?client_id=4990cffe-04e8-4e8b-808a-1175604b879f&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dUoXOsjq34NGRskAl3KO2Chd5I3Q7l_MW8MC4unzlfUv53whRgmClZQAfjg61HFFQMkD2G4FjOwggbXe5DrgIxqoQSLqFcUkdrsdBpmlkwK5CvFX5lLxdZl8pGGIxvkqn2AndiRQcQ0FJlVgV9KK72eMM3RAtju1GWfNa0r4CjAQxKIfv9PVJJNlwVvGyYDTD9QdH03qtru8-d7ASAAl-9GUwlbU&nonce=636755358369051713.MThjZDAzZDgtOGQzZi00OWEyLTgwNDQtNzQ0ZWJkOWQ1YjFjMmZmNWY0NmMtMjI1MS00OTc1LWEzYjAtNDg5YjNlNzUwZGMy&redirect_uri=https%3a%2f%2fpartner.microsoft.com%2faad%2fauthPostGateway&resource=797f4846-ba00-4fd7-ba43-dac1f8f63013&mkt=en-US

If I'm not authorised or signed up or registered or whatever else the issue is, there's no error listed.

**Comment by mtoepke** [comment]
@djarcas 

Can you try in a new InPrivate IE window?  That worked for me.  And if that doesn't work, try clearing your cache.

Also, to verify your Dev account:
If you are logged into Partner Center (http://partner.microsoft.com/dashboard/directory with a valid Dev account, on the left side you should see something like "Partner Center", your studio name, and below that the 3-line menu button, and Windows, Overview, Products, Attract, Engage, Monetize, and Analyze options.
If you only see "Partner Center", the 3-line menu button, and "MPN", then the account you are logged in with won't work, and you'll have to registered for a Windows Dev Center account using your Microsoft Account.

**Comment by stevewhims** [comment]
Let's go ahead and close this issue now, since it's been dormant for a long time.

Thanks!
Steve
