### ISSUE TITLE
Link to File Redirection Fixup  == 404

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#1084]
Clicking on the File Redirection Fixup link routes the user to a GitHub page not found page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c064b714-da78-4e0f-c851-bb17c06bc553
* Version Independent ID: a99df892-16ac-3a5a-f241-f4d03a7e5448
* Content: [Fix issues that prevent your desktop application from running in an MSIX container - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/package-support-framework)
* Content Source: [windows-apps-src/porting/package-support-framework.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/package-support-framework.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by hickeys** [comment]
It seems to be working for me, so it's possible it's a GitHub permissions issue. Are you able to navigate to this link?

https://github.com/Microsoft/MSIX-PackageSupportFramework/tree/master/fixups/FileRedirectionFixup

**Comment by hickeys** [comment]
It's been a while, it seems to be working fine, and I haven't seen any responses. I'm going to close this issue, please let me know if it happens again.
