### ISSUE TITLE
ScreenCapture MediaComposition only shows the last frame

### ISSUE THREAD

**Issue by oliverluethi** [MicrosoftDocs/windows-uwp#1086]
Hi there

I'm using the ScreenCapture sample from microsoft [ScreenCapture](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture).

The capturing works as expected, but if I want to save the frames to a mediacomposition for rendering a .mp4 video, only the last frame is rendered to the video. But if I resize the captured application window all frames are saved how they should during resizing. I guess, recreating the framepool on every FrameArriving isn't the right way to solve this problem, it also completly blocks the application.

`private void ProcessFrame(Direct3D11CaptureFrame frame)
        {
            bool needsReset = false;
            bool recreateDevice = false;

            if ((frame.ContentSize.Width != _lastSize.Width) ||
                (frame.ContentSize.Height != _lastSize.Height))
            {
                needsReset = true;
                _lastSize = frame.ContentSize;
                _swapChain.ResizeBuffers(_lastSize.Width, _lastSize.Height);
            }
            Direct3D11CaptureFrame direct=frame;

            try
            {
                if (direct.SystemRelativeTime - lastFrameTime < TimeSpan.FromSeconds(1))
                {
                    MediaClip mediaClip =
                        MediaClip.CreateFromSurface(direct.Surface, direct.SystemRelativeTime - lastFrameTime);
                    composition.Clips.Add(mediaClip);

                }

                lastFrameTime = direct.SystemRelativeTime;
                
                canvasBitmap = CanvasBitmap.CreateFromDirect3D11Surface(
                    _canvasDevice,
                    direct.Surface);

                using (var drawingSession = _swapChain.CreateDrawingSession(Colors.Transparent))
                {
                    ScaleEffect effect = new ScaleEffect()
                    {
                        Source = canvasBitmap,
                        Scale = new Vector2((float) swapChain.ActualWidth / _item.Size.Width)
                    };
                    drawingSession.DrawImage(effect);
                }
                _swapChain.Present();
            }
            catch (Exception e) when (_canvasDevice.IsDeviceLost(e.HResult))
            {
                needsReset = true;
                recreateDevice = true;
            }
            if (needsReset)
            {
                ResetFramePool(direct.ContentSize, recreateDevice);
            }
        }`

`private void ResetFramePool(SizeInt32 size, bool recreateDevice)
        {
            do
            {
                try
                {
                    if (recreateDevice)
                    {
                        _canvasDevice = new CanvasDevice();
                    }

                    _framePool.Recreate(
                        _canvasDevice,
                        DirectXPixelFormat.B8G8R8A8UIntNormalized,
                        60,
                        size);
                }
                catch (Exception e) when (_canvasDevice.IsDeviceLost(e.HResult))
                {
                    _canvasDevice = null;
                    recreateDevice = true;
                }
            } while (_canvasDevice == null);
        }`

**Comment by oliverluethi** [comment]
@eliotcowley Found a issue with the same content #612. I need to save the video to a .mp4 file. I guess the workaround on issue #612 isn't the right way?

**Comment by oliverluethi** [comment]
@eliotcowley Any feedback on this? #1091 Has the same problem.

**Comment by sebastianzolg** [comment]
Same Problem here. Any update on this topic?

**Comment by eliotcowley** [comment]
Hi, sorry for the delayed response. We are working on a solution across several teams and will update when we have it. Since issue #612 is already tracking this, I will close this issue as a dupe.
