### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by ghostcaptain18** [MicrosoftDocs/windows-uwp#1089]
The link takes me the wrong page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc064e49-5f24-ff80-d511-7f1947fc39da
* Version Independent ID: b8ad47c2-8264-c232-167f-b9ee69d6dce1
* Content: [Xbox One Developer Mode activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **scotmi**

**Comment by mtoepke** [comment]
Hi @ghostcaptain18 ,

You'll need to first sign into Dev Center with your Windows Dev Center account, then you should be able to follow that link.

See https://docs.microsoft.com/en-us/windows/uwp/publish/using-the-windows-dev-center-dashboard
 for information on Dev Center and creating an account.

**Comment by ghostcaptain18** [comment]
@mtoepke partner.microsoft.com/xboxactivate aka.ms/activatexbox both of those do not work for me.

**Comment by mtoepke** [comment]
@ghostcaptain18 

Can you try in a new InPrivate or Incognito window?  Or after flushing your cache?

And make sure you are signed into Dev Center / Partner Center with your developer account.  It should show your studio name in the upper left, something like "Partner Center | mystudioname", for example, when you navigate to https://partner.microsoft.com/en-us/dashboard/windows/overview.

**Comment by ghost** [comment]
> @ghostcaptain18
> 
> Can you try in a new InPrivate or Incognito window? Or after flushing your cache?
> 
> And make sure you are signed into Dev Center / Partner Center with your developer account. It should show your studio name in the upper left, something like "Partner Center | mystudioname", for example, when you navigate to https://partner.microsoft.com/en-us/dashboard/windows/overview.

Still doesn't work and I agree in that the link seems to be broken. Any ideas? Has Microsoft cancelled the program?

**Comment by deandredublin** [comment]
I am having the same problem. Please help me fix this.

**Comment by reutann** [comment]
This is still broken. Come on guys! 

Icognito/inprivate don't affect the result at all. Navigating to https://partner.microsoft.com/xboxactivate and https://aka.ms/activatexbox redirect to the partner dashboard and there's no option for xbox.

**Comment by mtoepke** [comment]
Thanks for your report.

The https://partner.microsoft.com/en-us/xboxconfig/devices link is the correct link and should be working. Make sure you are logged into Partner Center with a valid, registered app developer account.

Here are some more detailed steps we've added to the docs (particularly Step 6, to verify you are logged in with the correct account type):

5. [Register an app developer account in Partner Center](https://developer.microsoft.com/store/register).  This is also the first step towards publishing your game.

6. Sign in to [Partner Center](https://partner.microsoft.com/dashboard) with your valid, current Partner Center app developer account.  If you don't see multiple options in the left hand navigation pane, or don't see the **Create a new app** option in the **Overview** section, the following steps and activation links _will not work_; make sure you fully registered your app developer account from the previous step.

7. Go to [partner.microsoft.com/xboxconfig/devices](https://partner.microsoft.com/xboxconfig/devices).

If these steps don't work for you, please let us know.

**Comment by deandredublin** [comment]
It's not working, it gives me a loop when I try to go to the next page of
registration.

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. It seems that it is resolved in regard to proper documentation so I am closing. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.

**Comment by RafaelOliveira71594** [comment]
Guys l'm Trying To Activate Dev Mode In My Xbox One But l Can't Because On My PC l Get Redirected To Patner Microsoft Homepage Any More Help Me ?
