### ISSUE TITLE
smbios

### ISSUE THREAD

**Issue by honorew** [MicrosoftDocs/windows-uwp#1090]
<rescap:Capability Name="smbios" />
This capability can not pass by .Net native Complie.

**Comment by ginami** [comment]
Hi @honorew -- can you please give me the URL of the page this feedback is about? That will help me route your comment to the correct author.

**Comment by honorew** [comment]
[AppCert_Trace_1810180911.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498793/AppCert_Trace_1810180911.txt)
[logotest_trace_10182018_211118.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498794/logotest_trace_10182018_211118.txt)
[post_process_trace_ApplicationCount_10182018_211216.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498795/post_process_trace_ApplicationCount_10182018_211216.txt)
[post_process_trace_AppXManifestValidation_10182018_211218.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498796/post_process_trace_AppXManifestValidation_10182018_211218.txt)
[post_process_trace_BackgroundTaskCancelationHandlerValidation_10182018_211226.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498797/post_process_trace_BackgroundTaskCancelationHandlerValidation_10182018_211226.txt)
[post_process_trace_BinScope_10182018_211218.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498798/post_process_trace_BinScope_10182018_211218.txt)
[post_process_trace_BrandingValidation_10182018_211221.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498799/post_process_trace_BrandingValidation_10182018_211221.txt)
[post_process_trace_BundleManifestValidation_10182018_211145.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498800/post_process_trace_BundleManifestValidation_10182018_211145.txt)
[post_process_trace_BytecodeGenerationCheck_10182018_211221.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498801/post_process_trace_BytecodeGenerationCheck_10182018_211221.txt)
[post_process_trace_CloseBackgroundTasksCheck_10182018_211144.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498802/post_process_trace_CloseBackgroundTasksCheck_10182018_211144.txt)
[post_process_trace_DebugAppCheck_10182018_211246.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498803/post_process_trace_DebugAppCheck_10182018_211246.txt)
[post_process_trace_FileEncodingCheck_10182018_211246.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498804/post_process_trace_FileEncodingCheck_10182018_211246.txt)
[post_process_trace_HighOSVersionLaunchCheck_10182018_211253.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498805/post_process_trace_HighOSVersionLaunchCheck_10182018_211253.txt)
[post_process_trace_LaunchAppCheck_10182018_211313.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498806/post_process_trace_LaunchAppCheck_10182018_211313.txt)
[post_process_trace_ModernCop_10182018_211146.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498807/post_process_trace_ModernCop_10182018_211146.txt)
[post_process_trace_PackageSizeCheck_10182018_211147.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498808/post_process_trace_PackageSizeCheck_10182018_211147.txt)

[post_process_trace_PrivateCodeSigning_10182018_211349.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498809/post_process_trace_PrivateCodeSigning_10182018_211349.txt)

[post_process_trace_RestrictedNamespaceValidation_10182018_211349.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498810/post_process_trace_RestrictedNamespaceValidation_10182018_211349.txt)
[post_process_trace_SpecialUseCapabilities_10182018_211350.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498811/post_process_trace_SpecialUseCapabilities_10182018_211350.txt)
[post_process_trace_SupportedApis_10182018_211350.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498812/post_process_trace_SupportedApis_10182018_211350.txt)
[post_process_trace_SupportedDirectoryStructure_10182018_211149.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498813/post_process_trace_SupportedDirectoryStructure_10182018_211149.txt)
[post_process_trace_WindowsErrorReporting_10182018_211355.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498814/post_process_trace_WindowsErrorReporting_10182018_211355.txt)
[pre_process_trace_WindowsErrorReporting_10182018_211149.txt](https://github.com/MicrosoftDocs/windows-uwp/files/2498815/pre_process_trace_WindowsErrorReporting_10182018_211149.txt)
