### ISSUE TITLE
Why can't i store those IDirect3DSurface ?

### ISSUE THREAD

**Issue by mdmozibur** [MicrosoftDocs/windows-uwp#1091]
I have a List&lt;IDirect3DSurface&gt; and I wanted to store those surfaces in this list. so, before calling the `ProcessFrame(frame);` method,  I just used `mylist.add(frame.Surface);`
But when I create a video out of this stored surfaces using MediaComposition class like this :

```
var mc = new MediaComposition();
mylist.ForEach(surface => mc.Clips.Add(MediaClip.CreateFromSurface(surface, TimeSpan.FromMilliseconds(1000 / 60))));
await mc.RenderToFileAsync(file, MediaTrimmingPreference.Precise, MediaEncodingProfile.CreateMp4(VideoEncodingQuality.HD1080p));
```

 it shows the first frame, and then that all the other frames are like the last frame.. so the video looks like an still image of the last frame. The in between frames don't show up, so I can conclude that the in between frames was replaced by the last frame somehow. 
Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#putting-it-all-together)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **windows**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by cjw1115** [comment]
Hi buddy, I just do what like you. only one same frame in my video. So I think it is befacuse of the api will reuse the buffer, so the second frame will cover the first frame. We need an interface to access the frame buffer and copy the data from it. But I don't know if there is such an interface. Maybe Microsoft guys can help us.

**Comment by mdmozibur** [comment]
I thought so.

**Comment by cjw1115** [comment]
I found a walkaround but I think it is not good enough.

We can save the surface to a CanvasBitmap, and save this CanvasBitmap to a temp file, then we can load it by MediaClip.CreateFromImageFileAsync.

And create a viedeos.
I have try it, it have a very high CPU and disk usage. But the result is good. 
I'm try to find out a better way. Maybe we have to use some cpp code I guess.

```
_franePool.FrameArrived +=async (s, args) => 
            {
                using (var frame = _franePool.TryGetNextFrame())
                {
                    var canvasBitmap = CanvasBitmap.CreateFromDirect3D11Surface(canvasDevice,frame.Surface);
                   
                    await WriteableBitmapToStorageFile(canvasBitmap);
                    
                }
            };
```

```
async Task WriteableBitmapToStorageFile(CanvasBitmap WB)
        {
            try
            {
                string FileName = $"capture{count++}.";
                Guid BitmapEncoderGuid = BitmapEncoder.JpegEncoderId;
                FileName += "jpg";

                var file = await Windows.Storage.ApplicationData.Current.TemporaryFolder
                    .CreateFileAsync(FileName, CreationCollisionOption.ReplaceExisting);

                using (IRandomAccessStream stream = await file.OpenAsync(FileAccessMode.ReadWrite))
                {
                    BitmapEncoder encoder = await BitmapEncoder.CreateAsync(BitmapEncoderGuid, stream);
                    byte[] pixels = WB.GetPixelBytes();
                    encoder.SetPixelData(BitmapPixelFormat.Bgra8, BitmapAlphaMode.Ignore,
                              (uint)WB.SizeInPixels.Width,
                              (uint)WB.SizeInPixels.Height,
                              96.0,
                              96.0,
                              pixels);
                    await encoder.FlushAsync();
                }
                QueryPerformanceCounter(out long qpc);

                var currentTime = TimeSpan.FromSeconds(qpc / performanceFrequency);
                
                mediaComposition.Clips.Add(await MediaClip.CreateFromImageFileAsync(file, currentTime-_timeSpan));
                _timeSpan = currentTime;
            }
            catch(Exception e)
            {
            }
        }
```

**Comment by cjw1115** [comment]
I find out another workaround!

good performance and good resources usage.

```
 public void CreateClipInMemory(CanvasDevice canvasDevice, CanvasBitmap canvasBitmap)
        {
            CanvasRenderTarget rendertarget = null;
            QueryPerformanceCounter(out long counter);

            var currentTime = TimeSpan.FromMilliseconds(1000f * counter / performanceFrequency);
            try
            {
                rendertarget = new CanvasRenderTarget(canvasDevice, canvasBitmap.SizeInPixels.Width, canvasBitmap.SizeInPixels.Height,canvasBitmap.Dpi,canvasBitmap.Format,canvasBitmap.AlphaMode);
                using (CanvasDrawingSession ds = rendertarget.CreateDrawingSession())
                {
                    ds.Clear(Colors.Transparent);
                    ds.DrawImage(canvasBitmap);
                }
                mediaComposition.Clips.Add(MediaClip.CreateFromSurface(rendertarget, currentTime - _timeSpan));
            }
            catch
            {
            }
            finally
            {
                _timeSpan = currentTime;
                //rendertarget?.Dispose();
            }
        }
```

And this is my project:

https://github.com/cjw1115/UniversalWindowsDevDemos/blob/master/MediaCompositionDemo/MainPage.xaml.cs

**Comment by mdmozibur** [comment]
Yeah, tried that, 3 seconds of video consume 700+ MB, and waiting more than 6-7 seconds almost hangs my desktop (4GB RAM). I wonder if there were any memory safe way.

I faced the same problem few months ago : https://stackoverflow.com/questions/52839957/adding-mediaclips-in-to-mediacomposition-eats-too-much-ram and looks like, currently there is no other work-around.

**Comment by cjw1115** [comment]
Yes. the situation is same with me.

**Comment by eliotcowley** [comment]
Hi, sorry for the delayed response. We are tracking this issue in #612, so I'm going to close this as a duplicate. I'm working with the feature teams on a solution, and I've forwarded them your work-arounds to see if they have any better ideas. Apologies for this taking so long, but rest assured we're working on it!
