### ISSUE TITLE
Bubbling Behaviour

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/windows-uwp#1098]
Hello,

I have a question. I have a Grid and a TextBox inside the grid (as a child element). The Grid listens to KeyDown events and all the handler does is set the event as handled (e.Handled = true). Why does in that case the "TextChangedEvent" not fire? I thought that event handling bubbles up from the child events but my app shows that the Grid handler is invoked first. Thanks for your reply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32569952-2610-a154-ae03-20dfdf09476a
* Version Independent ID: 857856a1-3984-ce9d-3aaa-d41fda28a845
* Content: [Keyboard events - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events)
* Content Source: [windows-apps-src/design/input/keyboard-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-events.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by StephenLPeters** [comment]
This sounds like a bug! Could you open an issue on our github? https://github.com/microsoft/microsoft-ui-xaml  Please include a simple repro app with the issue, it will help us tremendously.
