### ISSUE TITLE
Unclear Sentence

### ISSUE THREAD

**Issue by MetallicPickaxe** [MicrosoftDocs/windows-uwp#1100]
The two "should" with confuse meaning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4665391f-f838-ae07-8591-d8f13f41a027
* Version Independent ID: 38b6b8ed-c3d2-97b1-9852-e3779b3ea281
* Content: [Using the UWP XAML hosting API in a desktop application - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/using-the-xaml-hosting-api#how-to-host-uwp-xaml-controls)
* Content Source: [windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by MetallicPickaxe** [comment]
![tim 20181023160635](https://user-images.githubusercontent.com/9762353/47346036-c8845680-d6de-11e8-82a1-6ea417b8a037.jpg)

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. I have deleted one of the "should" instances, and the updated article should be republished to the live site in the next day or so.
