### ISSUE TITLE
game

### ISSUE THREAD

**Issue by moraeselisabeth** [MicrosoftDocs/windows-uwp#1101]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 03829a62-ce3b-910e-2738-917069fba449
* Version Independent ID: a18b2869-ea37-956f-bdcc-800ac52ae350
* Content: [Getting started - UWP app developer](https://docs.microsoft.com/de-de/windows/uwp/gaming/getting-started)
* Content Source: [windows-apps-src/gaming/getting-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/getting-started.md)
* Product: **windows**
* GitHub Login: @joannaleecy
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @moraeselisabeth -- please let us know if you have some specific feedback on our docs. Thank you!
