### ISSUE TITLE
/IndexOptions <OPTIONS> documentation missing

### ISSUE THREAD

**Issue by aelij** [MicrosoftDocs/windows-uwp#1102]
Please list all the options for the `/IndexOptions` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ee0ec88-9b18-fd4e-1d0e-c0e1cf304b10
* Version Independent ID: 3a9a55bb-4a39-5a42-4f81-85f029277aa6
* Content: [MakePri.exe command-line options - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/app-resources/makepri-exe-command-options)
* Content Source: [windows-apps-src/app-resources/makepri-exe-command-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/makepri-exe-command-options.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @aelij, thanks for filing this issue, and my apologies for the omission in the documentation. The topic is now updated with info about what the /IndexOptions option does.

~Steve

**Comment by aelij** [comment]
Thanks @stevewhims. Not sure if this is within your purview, but it would be also nice to add this to the command line help (`/?`).

**Comment by stevewhims** [comment]
Good idea, I just merged a change; should be live tomorrow AM. :)
