### ISSUE TITLE
"C++/WinRT is a new way of authoring ... It's implemented sole in" should be "implemented solely in"

### ISSUE THREAD

**Issue by charliearcuri** [MicrosoftDocs/windows-uwp#1103]
"C++/WinRT is a new way of authoring ... It's implemented *sole* in" should be "implemented *solely* in"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d4c0f3b-3038-ac66-dcf0-09f8a51ec211
* Version Independent ID: 98ae5219-0a0d-863b-d296-7d47510a7a0b
* Content: [What's New in Windows 10 for Developers, Tools & Features - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-17763)
* Content Source: [windows-apps-src/whats-new/windows-10-build-17763.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-17763.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for the heads-up!
