### ISSUE TITLE
The screen shot of the Nuget Restore task is not up to date

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1106]
Advanced does not show the path to Nuget.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c024acf3-a58a-74c8-25b1-e5c88c85583a
* Version Independent ID: 81403e1d-947a-1f7d-f4b7-898105abd745
* Content: [Set up automated builds for your UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
This article has been significantly revised since this feedback was originally submitted, and this issue has been addressed.
