### ISSUE TITLE
What does 'next major update' mean?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1133]
In the `x:Bind in ControlTemplate` section it says next Major update, but the timestamp on this article is from 2017.  This seems like new content though.  It'd be nice to call out a version number of when this is available if it's already in the insider builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d6d6ad5-49bb-32b2-3293-cf359ad1bce2
* Version Independent ID: e77529c0-c08d-3584-7fcf-88951cc0da5a
* Content: [TemplateBinding markup extension - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/templatebinding-markup-extension#xbind-in-controltemplate)
* Content Source: [windows-apps-src/xaml-platform/templatebinding-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/templatebinding-markup-extension.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@michael-hawker, thanks for pointing this out. The page is updated.
