### ISSUE TITLE
WNS and Store application

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#1137]
Can I continue to use WNS even though Store application name reservation is lost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58f9d7cc-e60c-be39-e8b5-b0cb935e1feb
* Version Independent ID: 3d3a5b42-6d68-0348-920b-d6c35aa4bf7a
* Content: [Windows Push Notification Services (WNS) overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@andrewleader  Can you forward this to the WNS and notification team?

**Comment by andrewleader** [comment]
@mijacobs done! I'll have them follow up.

**Comment by andrewleader** [comment]
@superkid200 the answer is YES, you can continue to use WNS even though your Store application's friendly name reservation is lost. WNS is tied to the package family name, which will be kept forever. No need to worry! :)

Please close this if that answered your question!
