### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by lionevan** [MicrosoftDocs/windows-uwp#1138]
helloWorld

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ed0b73-fe3a-e66b-307e-d4803731b708
* Version Independent ID: 9f027742-4b7b-24d6-f02e-5704d70e0f94
* Content: [App submissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/app-submissions)
* Content Source: [windows-apps-src/publish/app-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-submissions.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @lionevan -- thanks for your feedback. Let us know if you have comments specific to our docs!
