### ISSUE TITLE
Not showing ads after app published

### ISSUE THREAD

**Issue by yair100** [MicrosoftDocs/windows-uwp#1139]
I used the test unit ids and ads showed now when I used my actual ids and publish the app I get reports it does not show.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fd9d37-275b-9fd4-1455-345221f197b9
* Version Independent ID: 721e5075-0a0d-e3a2-7c10-d9ac9496a782
* Content: [AdControl in XAML and .NET - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/adcontrol-in-xaml-and--net)
* Content Source: [windows-apps-src/monetize/adcontrol-in-xaml-and--net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/adcontrol-in-xaml-and--net.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
