### ISSUE TITLE
Ads not showing after app is published

### ISSUE THREAD

**Issue by yair100** [MicrosoftDocs/windows-uwp#1140]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8590344-1b1a-feb6-49dd-f137568feadd
* Version Independent ID: 2b32c06e-41b5-330a-c89f-7d2f85397ac7
* Content: [Set up ad units in your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/set-up-ad-units-in-your-app)
* Content Source: [windows-apps-src/monetize/set-up-ad-units-in-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/set-up-ad-units-in-your-app.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
