### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by JustinXinLiu** [MicrosoftDocs/windows-uwp#1147]
1. Replace _next major update_ with _17763_.
2. `TemplateBinding` is `OneWay` while `<TextBlock Text="{x:Bind Content}" />` is `OneTime`. The code needs to be updated to `<TextBlock Text="{x:Bind Content, Mode=OneWay}" />` to act the same way as `TemplateBinding`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d6d6ad5-49bb-32b2-3293-cf359ad1bce2
* Version Independent ID: e77529c0-c08d-3584-7fcf-88951cc0da5a
* Content: [TemplateBinding markup extension - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/templatebinding-markup-extension#xbind-in-controltemplate)
* Content Source: [windows-apps-src/xaml-platform/templatebinding-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/templatebinding-markup-extension.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@JustinXinLiu, thanks for pointing this out. The page is updated.
