### ISSUE TITLE
This page is wrong saying that the developer gets to choose the category. Games are possibly rejected even if they are games.

### ISSUE THREAD

**Issue by CanisLupus** [MicrosoftDocs/windows-uwp#1149]
This page seems to be the only page we get that talks about app categories, but it does not tell us that our product can be rejected due to "wrong" categorization as a game. In fact it tells us that "You must choose the category that best describes your app."

We have an entertainment game made for young children to learn music. It is free-form and has no defined objectives, and we were told that it has to be an app because to be a game "The app needs to contain gameplay elements for example, competitive elements, mission or quests with story progression, leaderboards and achievements, ability to win or lose. Please either include gameplay functionality and resubmit the app or create a new app and republish in a different category."

We could find no such guidelines anywhere, and common definitions of "game" from the Internet yield descriptions such as "an activity that one engages in for amusement." or "A game is a structured form of play, usually undertaken for enjoyment and sometimes used as an educational tool.", which our product fits.

If this really is the definition that Microsoft Store uses, it should be made much more explicit, here and in the submission. We don't agree with this definition anyway.

Best regards,
Daniel Lobo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8e8f5e6-6bfd-c50e-b834-458aff1449af
* Version Independent ID: 8b7d0dae-e086-6190-27ff-74b0202b078c
* Content: [Category and subcategory table - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/category-and-subcategory-table)
* Content Source: [windows-apps-src/publish/category-and-subcategory-table.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/category-and-subcategory-table.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I’m afraid I don’t have any more details on this. If you need more assistance, please open a support inquiry via http://aka.ms/storesupport.

**Comment by CanisLupus** [comment]
Is this _really_ supposed to get closed?

We don't need further assistance, but thanks. We had a long back and forth with several people at Microsoft and had to create the product again from scratch as an app instead of a game, even though we don't agree.

That doesn't change the fact that there's just nowhere in the documentation or submission process that tells us what a "game" is supposed to be. The dashboard let's you create a product, fill everything in in several languages, upload builds, etc, just for the reviewers to then decide that something as hard to classify as a game... isn't one. Apparently according to rules that we don't have access to.

As if not enough, the literal _second_ paragraph of the linked page leaves it up to the developers and says: "**You** must choose the category that **best describes your app**. (...) **If you're not sure which category or subcategory to use**, or you can't find one that seems to be an exact fit, **choose the one that you think customers are most likely to look at when trying to find apps like yours**."

So this text is wrong, plainly speaking, and should be fixed. Sorry if I sound harsh, but this was really frustrating (and _will be_ for someone else, if nothing is done about it, as closing the issue seems to imply).

**Comment by JnHs** [comment]
Thanks for your additional feedback and I'm glad you were already able to get more assistance through other channels (we cannot provide individual support through this documentation feedback mechanism). I will share your feedback with the team to consider whether further clarifications are needed.

**Comment by CanisLupus** [comment]
Thank you. I appreciate you sharing the feedback with the team. We didn't intend to get help through here since we were already working with Microsoft to understand and resolve the issue, but I felt that feedback was needed regarding the docs.
