### ISSUE TITLE
App.xaml.cs

### ISSUE THREAD

**Issue by georgeLiew** [MicrosoftDocs/windows-uwp#1153]
In https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation

Windows.UI.Core.SystemNavigationManager.GetForCurrentView().BackRequested += App_BackRequested;
Frame rootFrame = Window.Current.Content;
rootFrame.PointerPressed += On_PointerPressed;

Can I know what is the 3 lines above meaning and where should I put it?

Thanks

**Comment by jevansaks** [comment]
I believe it should go in the OnLaunched handler. But this sample is confusing, I agree.

**Comment by jwmsft** [comment]
The "Navigation history and backwards navigation" article was updated recently. The updates should address this issue.
