### ISSUE TITLE
Any specific guidelines for IME icons (i.e. icons on the language bar)

### ISSUE THREAD

**Issue by ztl8702** [MicrosoftDocs/windows-uwp#1155]
There was a Windows 8 guideline for IME icons (including branding and mode icons)  https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh967425(v=win.10)#ime-icons  But that is outdated. Are there any new guidelines specifically for IME icons? Or can I design IME icons in whatever way I like?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac89746a-7629-6a95-6c5c-9498a9d7989f
* Version Independent ID: 044558cb-9f69-42df-362c-6c35317c3411
* Content: [App icons and logos - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos#customizing-asset-padding)
* Content Source: [windows-apps-src/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/app-icons-and-logos.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @ztl8702 - Apologies for the numerous delays in addressing this issue. I confirmed with various IME-related teams that this guidance is not out of date, even though the topics have been archived.

With that information, I pulled the topics out of the archive, rewrote to some degree, and incorporated them into the current Windows guidance. 

https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh967426(v=win.10) ==> https://docs.microsoft.com/en-us/windows/uwp/design/input/input-method-editors
 
and
 
https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh967425(v=win.10) ==> https://docs.microsoft.com/en-us/windows/uwp/design/input/input-method-editor-requirements

If still interested, please review and file a new Issue for any feedback/questions you might have. Reactivating this issue might not move it to the top of the more current issues we're trying to address.

Thanks.
