### ISSUE TITLE
How does Microsoft handle basic licensing functions for uploaded apps?

### ISSUE THREAD

**Issue by NISTabletSW** [MicrosoftDocs/windows-uwp#1160]
To Whom It May Concern:

Does the Microsoft Store handle basic licensing functions for apps that are uploaded to it?

IF I select the available trial option for 30-days when uploading my app to the Microsoft Store THEN will the Microsoft Store:

a) Automatically modify my app to timeout after 30-days of usage.

b) Block the launch of the app once the timeout has expired.

c) Prompt the user to purchase/validate the license.

d) Validate the license and NO longer block the user from launching the app, AFTER the user purchases the app through the Microsoft Store.

Thanks,

Sean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4c0541-1af5-8654-ad07-96b62933bf85
* Version Independent ID: 8c0ba5f6-134c-051a-d520-4c86f9ce1895
* Content: [Set app pricing and availability - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/set-app-pricing-and-availability)
* Content Source: [windows-apps-src/publish/set-app-pricing-and-availability.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-app-pricing-and-availability.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Yes, the Store handles these licensing functions. A, B, and D are accurate (I wouldn't say that the Store "modifies your app" - but it will enable the time limit for that customer's license to the app). For C, if a customer tries to open the app after a trial expires, they'll instead see a message with the option to purchase the app from the Store.

**Comment by cwey** [comment]
Since yesterday I am getting an error that prevent me to have trials. The error says Product with no package cannot have trials. Does anyone know what that means? I have always had trials, and I do have a current package associated to the product. Anyone can help me? My sales are plummeting with the lack of a trial

**Comment by JnHs** [comment]
You should open a support request at http://aka.ms/storesupport so that we can look into this.

**Comment by NISTabletSW** [comment]
To Whom It May Concern:

I am getting the following error when I try to upload my UWP app to the
Microsoft Store, "Package acceptance validation error."

Apps are not allowed to have a Version with a revision number other than
zero specified in the app manifest. The package EditRight.appx specifies
0.0.0.1.

I tried solving this problem by having my programmer change the version
number to 0.0.0.0, but my app when installing still indicates the 0.0.0.1
version.

My UWP app was created using the desktop bridge which converted an MSI file
over to a UWP file.

How do I solve this problem?


Thanks,

Sean.

-----Original Message-----
