### ISSUE TITLE
Are we able to renew Store ID from service ?

### ISSUE THREAD

**Issue by KoteKotlyarov** [MicrosoftDocs/windows-uwp#1162]
Docs stand for: The only way to *create/generate* a Store ID key is by calling an UWP API from client code in app.
But for renew process there is no limit. Also, docs give us a guideline to "create Azure tokens in the service, not in app", so I made decision that we *should* renew Store ID outside the app.

Am I correct ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b504355-1c98-acbd-7063-273771028f26
* Version Independent ID: d64bd82e-67eb-a4ed-e0dd-cb67bf7ea0bb
* Content: [Renew a Microsoft Store ID key - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/renew-a-windows-store-id-key)
* Content Source: [windows-apps-src/monetize/renew-a-windows-store-id-key.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/renew-a-windows-store-id-key.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
