### ISSUE TITLE
Is the Graphics.Capture API supported on Javascript UWP apps or PWAs on Windows?

### ISSUE THREAD

**Issue by shreyagupta-dev** [MicrosoftDocs/windows-uwp#1164]
I am working on a JavaScript based UWP app and a PWA running on Windows. I want to access the `Graphics.Capture` API in both apps, but none of the methods and attributes belonging to the `Windows.Graphics.Capture` namespace are available in either app.

Here is what happens when I try to access the `Windows.Graphics.Capture.GraphicsCaptureSession.IsSupported()` API in a JavaScript UWP:

![js uwp](https://user-images.githubusercontent.com/9092086/47466569-6d726280-d7b7-11e8-9c15-ff298f8cc08e.png)

Here is the `Windows.Graphics.Capture` API taken from the `window.Windows` object from my PWA running as an installed UWP app on Windows:

![pwa on windows](https://user-images.githubusercontent.com/9092086/47466615-a0b4f180-d7b7-11e8-9943-f598af39d68b.png)

None of the methods and attributes listed in [this documentation](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture) page appear. When I invoke the `IsSupported()` method inside the PWA nothing seems to happen - no errors/crashes.
However, other APIs like the `Windows.UI.Popups.MessageDialog` are visible in the `window.Windows` object and successfully callable from the app. 

My Windows version: Windows 10 Pro Version 1803 (OS Build 17134.376)

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by jatinmishra** [comment]
Hi shreyagupta995, were you able to solve the above issue? My requirement was something similar, if you were able to worked something up, please share. It would be great.

Also, folks from Microsoft (eliotcowley), your help regarding this issue will be greatly appreciated.

Thanks.

**Comment by shreyagupta-dev** [comment]
Hi @jatinmishra, I was not able to solve this issue, unfortunately. Let me know if you've made any progress! Thank you.

**Comment by jatinmishra** [comment]
I wasn't able to use the screen capture api but was able to get some result using the html2canvas library and working with some old school canvas and javascript. :)

Thanks.

**Comment by drewbatgit** [comment]
Hello, you can tell if an API is unsupported for JavaScript or PWAs if it has the WebHostHidden attribute on its reference page. The GraphicsCaptureSession, and other APIs in that namespace all appear to have this attribute, meaning they are unsupported.

https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession
