### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ErikOAndersson** [MicrosoftDocs/windows-uwp#1166]
The link to the AudioStateMonitor doc page is broken, should be:
https://docs.microsoft.com/uwp/api/windows.media.audio.audiostatemonitor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b25b952-2aad-4497-0232-a00a7c7a6d51
* Version Independent ID: b21ac101-7681-224b-ddf1-3a603b72f62d
* Content: [Detect and respond to audio state changes - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/detect-and-respond-to-audio-state-changes)
* Content Source: [windows-apps-src/audio-video-camera/detect-and-respond-to-audio-state-changes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/detect-and-respond-to-audio-state-changes.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by bartlannoeye** [comment]
Link works, issue can be closed?
