### ISSUE TITLE
No color palette?

### ISSUE THREAD

**Issue by david-osborne** [MicrosoftDocs/windows-uwp#1167]
There is no palette to reference in the Color documentation.  The Universal Color Palette used to be published, but was removed? 
(https://www.microsoft.com/design/color)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181b91e8-b61c-f32b-f59c-332db130d207
* Version Independent ID: ec8195d3-5847-e003-c8ef-bc3a6dfe069f
* Content: [Color in UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/color#accent-color-palette)
* Content Source: [windows-apps-src/design/style/color.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/color.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
What content was on the https://www.microsoft.com/design/color page you had linked? Was there something specific you were looking for?

**Comment by david-osborne** [comment]
There used to be a link to this color palette (see screenshot I took here:  https://drive.google.com/file/d/1_dWln5IKEG_EdN7Ep-7TMy-PYXOlhLfd/view?usp=sharing)

[https://lh4.googleusercontent.com/pD3KOStyubiBhfvl9aEM85g6L64tb36LhvpaeaCvytMwHNyl6E1lQeNMBm0=w1200-h630-p]<https://drive.google.com/file/d/1_dWln5IKEG_EdN7Ep-7TMy-PYXOlhLfd/view?usp=sharing>

2018-11-02 08_37_38-Color.png<https://drive.google.com/file/d/1_dWln5IKEG_EdN7Ep-7TMy-PYXOlhLfd/view?usp=sharing>
drive.google.com


Now, it appears the color palette is gone.
________________________________

**Comment by jevansaks** [comment]
Thanks. I'm guessing this palette isn't part of the guidance anymore but @chigy can you take a look?

**Comment by chigy** [comment]
I do not recall the color pallet John point out but I know we worked on the styling page and fixed some misleading information. Now we do have a similar to palette info but is in https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources

User is capable of creating any theme color.

@david-osborne , what are you looking for in particular? What information will help you do your job? Is above page sufficient or are you looking for something else?

**Comment by david-osborne** [comment]
As a developer targeting Windows, I want my application to match the interface guidelines of the environment, including the OS color scheme.

For example, if I am developing for Android - there is a color pallet for Material Design located in their documentation here:  https://material.io/design/color/the-color-system.html#tools-for-picking-colors

Of course I can incorporate my own brand colors into an application, but if I want to develop an application that has a 'native' OS look and feel - what color theme to use?

Unless the color palette previously available in the online documentation is invalid, I would like to understand why it was removed, as it was a good resource to choose from a predefined Windows color language.


[https://storage.googleapis.com/spec-host-backup/mio-design/assets/1wpQ-cJvJW9vxhgYs-wjSS6f_flVj8RcR/color-thumbnail-2x1.png]<https://material.io/design/color/the-color-system.html#tools-for-picking-colors>

The color system - Material Design<https://material.io/design/color/the-color-system.html#tools-for-picking-colors>
The Material Design color system uses an organized approach to applying color to your UI. In this system, a primary and a secondary color are typically selected to represent your brand.
material.io


________________________________

**Comment by chigy** [comment]
> Unless the color palette previously available in the online documentation is invalid, I would like to understand why it was removed, as it was a good resource to choose from a predefined Windows color language.

@david-osborne , as a matter of fact, it was indeed invalid.

**Comment by david-osborne** [comment]
and it was replaced with what?
________________________________

**Comment by chigy** [comment]
@david-osborne , the color palette you saw before was just a generic palette that is not tied to any platform offering that our design team may or may not have been using it. To avoid confusion, it was removed.
