### ISSUE TITLE
Isn't this circular?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1169]
"1) Test your app. Before you package your app for Dev Center submission, make sure it works as expected on all device families that you plan to support. These device families may include desktop, mobile, Surface Hub, Xbox, IoT devices, or others."

Don't I need to package my app before I can test it on all device families? Otherwise how do I get it on to the device I need to test on ?

[Update]
I guess I am meant to test by side loading... but it could be said more clearly.

[Update]
It can't be meant to test by sideloading because according to this link, I sideload by double clicking a package! 

https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#sideload-your-app-package 

Augh this link also talks about packages
https://docs.microsoft.com/en-us/windows/uwp/packaging/installing-uwp-apps-web

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1c88d-24b1-0eda-b458-105db02dca36
* Version Independent ID: c5d1634a-0ead-f68a-e5be-89acf0eef0a6
* Content: [Packaging UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#before-packaging-your-app)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by encrypt0r** [comment]
What exactly is the role of MSIX here?

We have always been able to create appx files, and it seems that it hasn't changed. But from what I've read, MSIX is for both UWP and Win32 apps. Can you clarify?

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I believe that the "1. Test your app" step you're commenting on refers to testing/debugging your app directly from Visual Studio, either in an emulator or by deploying directly to a target test device via Visual Studio, all before you package your app. I have expanded on this step in the article to clarify this point.
