### ISSUE TITLE
Whats new for developers in Windows 10 ?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1171]
Is there such a thing as "Windows 10 for developers" ? or should this read what's new for developers in windows 10 ?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d4c0f3b-3038-ac66-dcf0-09f8a51ec211
* Version Independent ID: 98ae5219-0a0d-863b-d296-7d47510a7a0b
* Content: [What's New in Windows 10 for Developers, Tools & Features - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-17763)
* Content Source: [windows-apps-src/whats-new/windows-10-build-17763.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-17763.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This should be read as What's New for developers in Windows 10.
