### ISSUE TITLE
When is the new non-game app revenue split coming?

### ISSUE THREAD

**Issue by dimitrijevic** [MicrosoftDocs/windows-uwp#1172]
There was word "later this year"(https://blogs.windows.com/buildingapps/2018/05/07/a-new-microsoft-store-revenue-share-is-coming/) around build conference time and it's almost end of year yet still nothing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36abe7f6-20c0-e1ba-d585-9630bcfdcc9f
* Version Independent ID: fd28df55-a61e-4742-37a1-b6691fd5fdf6
* Content: [Getting paid - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/getting-paid-apps)
* Content Source: [windows-apps-src/publish/getting-paid-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/getting-paid-apps.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Great question. This is still on track to occur by the end of year, although I don’t have an exact date to give you.

**Comment by dingsheng999** [comment]
This has not occurred now.

**Comment by aarefievit** [comment]
Later this year (2019) ...
