### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by vbandi** [MicrosoftDocs/windows-uwp#1173]
"... this more is called" should be "this mode is called"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918404cb-28b0-1624-da04-c992bfca4395
* Version Independent ID: 20df39b5-a4db-3065-a172-5a90d27909fb
* Content: [Data binding in depth - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-in-depth)
* Content Source: [windows-apps-src/data-binding/data-binding-in-depth.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/data-binding-in-depth.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Looks like this is being taken care of in https://github.com/MicrosoftDocs/windows-uwp/pull/1174#pullrequestreview-171748761.

**Comment by stevewhims** [comment]
...and that's approved and merged. Thanks for fixing this, @vbandi!

~Steve
