### ISSUE TITLE
Get All App API not working as documented

### ISSUE THREAD

**Issue by rfreytag** [MicrosoftDocs/windows-uwp#1178]
I have taken the MSFT Store Services API 'Create an app submission' example code [1] and from that made a repo that tests the 'Get all apps' API.   This call in the API does not work as documented instead only returning at most the first 10 applications in your Dev Center.  The variation that skips N and returns M apps also only returns the first 10 apps in your Dev Center.  Please see my GitHub repo here: https://github.com/rfreytag/MSFTDevCenterGetAppInfo.  

You will need:
- Azure AD Tenant ID
- A Dev Center with more than 10 applications
- Register a native program in your Azure AD Tenant/directory
- Granted access to said Azure AD native program in your Dev Center
- record your native program's 'Client ID' and 'Client Secret'.

NOTE: the README in my GitHub repository has a lot more pointers to documentation and steps.

[1] https://docs.microsoft.com/en-us/windows/uwp/monetize/csharp-code-examples-for-the-windows-store-submission-api#create-app-submission

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1afba821-9f64-035b-e8c3-f2abd41b2fb8
* Version Independent ID: f50cc88b-c015-ea07-244c-7a44b21870dc
* Content: [Get all apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-all-apps)
* Content Source: [windows-apps-src/monetize/get-all-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-all-apps.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thank you for this extensive research and feedback. I'll do some investigation and update the documentation as necessary.

**Comment by rfreytag** [comment]
I have also filed support request #618110891279430 ("SRX618110891379430ID - Dev Center API does not return listing of all store apps"), with the Dev Center team pointing to this problem in the Store API.  I mention this because it may be that your documentation is correct and the API needs repair.  

I will update here and on my GitHub repo if there is a resolution; including changing the code to a version that works with whatever solution is found.

**Comment by mhopkins-msft** [comment]
Great, thanks. I'm going to go close this issue since you have a support request filed.

**Comment by mhopkins-msft** [comment]
I recently got some info from the engineering team.

`GET https://manage.devcenter.microsoft.com/v1.0/my/applications` will return the top 10 apps. The default value of _top_ query parameter is 10.
`GET https://manage.devcenter.microsoft.com/v1.0/my/applications?top={totalAppNum}` will return all the applications in one page. This is at user’s own risk and is not guaranteed to work with a large payload.

**Comment by mhopkins-msft** [comment]
To summarize:

1. `?top={totalAppNum}` if the system can handle it.
2. `GET https://manage.devcenter.microsoft.com/v1.0/my/applications`
    Then recursively call 
    `GET https://manage.devcenter.microsoft.com/v1.0/my/{nextLink}`
    aka 
    `GET https://manage.devcenter.microsoft.com/v1.0/my/applications?skip=10&top=10`
    `GET https://manage.devcenter.microsoft.com/v1.0/my/applications?skip=20&top=10`
        Until nextLink = null or doesn’t exist in response.
