### ISSUE TITLE
Provide instructions to create packages from CLI builds

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/windows-uwp#1180]
Not everyone uses VS to produce packages. The packaging section should have instructions to produce packages from CI/CD scenarios using CLI commands only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 703719e7-1097-544a-1bb1-9007d2ca057c
* Version Independent ID: 36eac807-73ee-f3b8-b982-10865036be53
* Content: [Package desktop applications - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-root.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-root.md)
* Product: **uwp**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by hickeys** [comment]
There are links to non-Visual Studio methods of building MSIX packages in the article just above the heading "Build an MSIX from source code using Visual Studio." Command line instructions are included. 

Happy building!
