### ISSUE TITLE
Links are not working - Account section to upload document

### ISSUE THREAD

**Issue by piyushgoel1973** [MicrosoftDocs/windows-uwp#1181]
Errors on the Account page in Settings menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec06af90-a369-e18e-dffd-30443c415f33
* Version Independent ID: dae3fe06-e22a-7c3f-c0eb-03220929f0ef
* Content: [Set up your payout account and tax forms - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for sharing this. Please open a support request at http://aka.ms/storesupport so we can investigate further.
