### ISSUE TITLE
about forms

### ISSUE THREAD

**Issue by steve126** [MicrosoftDocs/windows-uwp#1186]
These specific two forms will be sent or some other? in what format will the files be? Will you send files by type 1099 form https://1099-misc-form.pdffiller.com/ or is your option?
By the way, the idea is interesting, for busy people just a godsend. Hurry they would be available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c2f2eb4-c27d-4ae2-a9c9-beaec617d245
* Version Independent ID: 14086543-611b-d6c5-4e47-c31fe9ed7668
* Content: [Understand IRS tax forms issued by Microsoft - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/understand-irs-tax-forms)
* Content Source: [windows-apps-src/publish/understand-irs-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/understand-irs-tax-forms.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
This info is provided in the "Availability" column of the "Types of tax forms" table (https://docs.microsoft.com/en-us/windows/uwp/publish/understand-irs-tax-forms#types-of-tax-forms). Let me know if anything is not clear. Thanks!
