### ISSUE TITLE
missing parameter in command line example

### ISSUE THREAD

**Issue by isi-dwade** [MicrosoftDocs/windows-uwp#1187]
MakeAppx bundle [options] /d &lt;content directory&gt; /fb /p &lt;output flat bundle name&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac171f83-bac9-f008-14e4-acb4e98f6770
* Version Independent ID: d89243a9-4ffd-ed02-11c2-d82fe86561db
* Content: [Flat bundle app packages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/flat-bundles)
* Content Source: [windows-apps-src/packaging/flat-bundles.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/flat-bundles.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for opening this issue. I have updated the article (adding the /p parameter to the example), and the revised article should be published to the live docs site in the next few days.
