### ISSUE TITLE
Provided guidance on error detection or validation that Writes are successful

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1188]
Here and in the accompanying API docs (like WriteTextAsync) there's no info on how these methods can fail, throw exceptions, or how to validate that the write was successful and stored to the file.  It'd be great to see guidance here and there on how to determine that a write was successful and recover from error cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b36404b8-4385-81d9-2ee8-486f0a55fc37
* Version Independent ID: 7b6ce4df-6ab2-3aa6-059f-b38aa9ea8062
* Content: [Create, write, and read a file - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
Thanks for your feedback! We are in the process of pulling together a lot of in-depth guidance about what the WritexxxAsync methods do internally, how and why various parts of these operations can fail, and what you can do in response to the failures. I'll update this issue when this new guidance is published in our docs.

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
