### ISSUE TITLE
Where is ExplorerItem defined?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1191]
I am copying the code into my project but don't know where to get the source for ExplorerItem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba995b-8bf3-407c-7b87-015d22d813f1
* Version Independent ID: 52c553b6-e94d-2810-4123-8ee215b002bf
* Content: [Tree view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view#interacting-with-a-tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MagnusJohansson** [comment]
You can find the source here:
https://github.com/Microsoft/Xaml-Controls-Gallery/blob/1ecd85c908a8a1cb9a8201e548f58db379801e69/XamlControlsGallery/ControlPages/TreeViewPage.xaml.cs

**Comment by kgreed** [comment]
@MagnusJohansson Thanks. I see a few of the links on the content source are broken. For example https://github.com/MicrosoftDocs/windows-uwp/blob/docs/uwp/api/windows.ui.xaml.controls.treeview.itemssource

**Comment by predavid-zz** [comment]
Thanks @kgreed for pointing out the broken link. I've opened Issue #1352 to track it.

**Comment by jwmsft** [comment]
Doc has been updated.
