### ISSUE TITLE
Requirements should be updated to account for the new "Make text bigger" setting

### ISSUE THREAD

**Issue by mcooley** [MicrosoftDocs/windows-uwp#1193]
In version 1809 there's a new "Make text bigger" setting under Ease of Access &gt; Display. The "Text scale factor" section mentions that this is a phone feature but I think it could be updated to mention that a similar feature is now available on desktop.

The "accessibility checklist" page could also be updated to recommend testing your app with this setting in addition to the current guidance to test with different DPI scale factors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88738f4d-68db-8ec6-3856-abf576bbc884
* Version Independent ID: 33aad254-2e21-6555-bc6c-a6afcbfdeb19
* Content: [Accessible text requirements - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/accessible-text-requirements)
* Content Source: [windows-apps-src/design/accessibility/accessible-text-requirements.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/accessible-text-requirements.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @mcooley : Thanks for the feedback both topics you identify have been updated with the suggested info (along with a couple of API ref topics). Keep the feedback coming!
