### ISSUE TITLE
Current month Payout(october 2018) not yet done

### ISSUE THREAD

**Issue by srirayavarapu** [MicrosoftDocs/windows-uwp#1194]
Team, for the current month oct 2018, revenue is not updating from last 10 days and also did not mentioned how many will get for this month.

**Comment by ginami** [comment]
Hi @srirayavarapu -- which page are you referring to? This will help me route your comment to the correct author. Thank you!

**Comment by ginami** [comment]
Hi @srirayavarapu -- let us know if you've got page-specific feedback for our docs. Thank you!
