### ISSUE TITLE
Does it make sense to link to Windows Community Toolkit solutions?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1196]
The Windows Community Toolkit has a workaround for LayoutTransforms using a control, documented [here](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/LayoutTransformControl).  Is that worth calling out here somewhere (like in the migration note)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ba33dc-8bcb-462f-0652-c0d9fff34f5d
* Version Independent ID: dbefc5fd-3e00-59f2-a463-bf2d5700f9c4
* Content: [Transforms overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/transforms)
* Content Source: [windows-apps-src/design/layout/transforms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/transforms.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Also suggested here: #1595, marking this one as dup.
