### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by jakehockey10** [MicrosoftDocs/windows-uwp#1197]
UWP keeps being mentioned when perusing these documentation pages on bluetooth.  Is it required to be building a UWP app, or is that just the suggestion as UWP is the newest GUI framework I'm aware of for windows .NET GUI application development.  Can I utilize this with WPF?  WinForms?  Does the operating system have to be Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62f0913b-a71b-c1b5-54d7-be0a6de61f98
* Version Independent ID: b8547e82-8c80-cf82-1219-ee517586387f
* Content: [Bluetooth Low Energy - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-low-energy-overview)
* Content Source: [windows-apps-src/devices-sensors/bluetooth-low-energy-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/bluetooth-low-energy-overview.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by EddieLotter** [comment]
See [this blog post](https://blogs.windows.com/buildingapps/2017/01/25/calling-windows-10-apis-desktop-application/).

**Comment by jakehockey10** [comment]
Thanks for sharing. I've seen this article and it unfortunately did not help

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @jakehockey10, these docs are specifically for UWP apps on Windows 10. If you need info on Bluetooth support in WPF, you can check those corresponding platform docs. Check this blog post about using UWP APIs in WPF applications: [Calling Windows 10 APIs From a Desktop Application](https://blogs.windows.com/windowsdeveloper/2017/01/25/calling-windows-10-apis-desktop-application/)
