### ISSUE TITLE
Clarification Requested re: BackgroundTask Registration for an App Service

### ISSUE THREAD

**Issue by BestTimeIsNow** [MicrosoftDocs/windows-uwp#1198]
Can Microsoft comment on backgroundtask registration as it relates to an app service? Registering, or confirming that the task has been registered, is not noted as needed or not needed anywhere in the app service provider or in the caller.

Clarification may be helpful for readers who may not be entirely familiar with the requirements around handling background task registrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by eliotcowley** [comment]
Closing as duplicate, please see Issue #747.
