### ISSUE TITLE
Missing ARM64 

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/windows-uwp#1200]
With RS5 we have support for ARM64, it should be included in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2975459d-0a61-a9ac-02be-5a1191254165
* Version Independent ID: 453681de-7ac5-c469-31c9-afabf4c8a930
* Content: [App package architectures - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/device-architecture)
* Content Source: [windows-apps-src/packaging/device-architecture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/device-architecture.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mcleanbyron** [comment]
This page has been updated with references to ARM64 and info about requiring Visual Studio 2017 15.9 or later.
