### ISSUE TITLE
Compiler unable to find get_strong()

### ISSUE THREAD

**Issue by JackDetrick** [MicrosoftDocs/windows-uwp#1203]
auto strong_this{ get_strong() }; // Keep *this* alive.

I'm missing something but what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1d40e59-b0fc-e95c-5c25-a933811514b6
* Version Independent ID: 7f28cd84-d6bc-6add-472b-8cd1c0ba08e6
* Content: [Weak references in C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/weak-references)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/weak-references.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/weak-references.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JackDetrick, get_strong is a member function of winrt::implements. And when you're implementing a Windows Runtime class, your base class is winrt::implements. So, the code is an abbreviation for `this->get_strong()`, called from within the member function of an implementation type. The get_strong function increases the reference count of the *this* object.

I don't know whether that helps. Please let me know, and whether or what I can do to improve the docs.

Thanks!
~Steve

**Comment by JackDetrick** [comment]
Steve -
I'm using VS 2018 15.8.9 and Windows SDK 18272.
When I add the following to a C++/winRT console app, the compiler doesn't like: get_strong();
My question - what am I missing

hstring m_value = L"Hello World"; //jd 11/11/2018
IAsyncOperation<winrt::hstring> RetrieveValueAsync()
{
    auto strong_this{ get_strong() }; // Keep *this* alive.
    co_await 5s;
    co_return m_value;
}

**Comment by stevewhims** [comment]
As long as RetrieveValueAsync is a member function of a class that directly or indirectly derives from winrt::implements, then that's correct. You should read `get_strong()` AS IF it says `this->get_strong()`. As long as your class has a get_strong member (inherited from winrt::implements) then the code is good.

Currently, the docs are based on the latest RTM'd release of the SDK (17763), rather than an SDK Insider Preview, although I doubt that's a factor here.

**Comment by JackDetrick** [comment]
The c++/winRT documentation section "Strong & Weak References"  contains an example on how to create a coroutine that uses get_strong().. The example is called from main(). My coroutine is called from a click handler. I replaced "winrt::init_apartment();: with - co_await winrt::resume_background(); //resume UI thread so that get() doesn't block it. It woks...

**Comment by stevewhims** [comment]
Hi, @JackDetrick, I'll go ahead and close this issue now, since it seems like we're resolved, and I don't see any clear action around improving the documentation.

If I'm wrong, and you can let me know how to what I can do to improve the docs, then please feel free to reopen.

Thanks!
~Steve
