### ISSUE TITLE
Asterisks

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#1205]
What do the Asterisk behind e.g. German mean? I cannot get any description of it here or do I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2ae8ac-9ec3-364e-8f0f-01513ee1a257
* Version Independent ID: dcd97213-e70f-91aa-57bf-93c3fce31a67
* Content: [Define market selection - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/define-pricing-and-market-selection)
* Content Source: [windows-apps-src/publish/define-pricing-and-market-selection.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/define-pricing-and-market-selection.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @arrangeplatform -- the page says "The markets with an asterisk support the Microsoft Store on Xbox One; you'll see Xbox next to their names in the Market selection popup window." 
Does that answer your question?

**Comment by ginami** [comment]
@arrangeplatform -- let us know if you have any further questions. Thanks!
