### ISSUE TITLE
The link to the Pivot control is broken.

### ISSUE THREAD

**Issue by e455a81e-d3ba-41a2-bc6d-7aafb1d9a5cd** [MicrosoftDocs/windows-uwp#1207]
The link to the Pivot control 404s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8bd2acc-d4c1-f645-a908-ed9f1592deb4
* Version Independent ID: 91326e94-3261-8fea-40ed-fc89e2d95b31
* Content: [Forms - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/forms)
* Content Source: [windows-apps-src/design/controls-and-patterns/forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/forms.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@LariscusObscurus, thanks for letting us know about the broken link. It's fixed now.
