### ISSUE TITLE
Writing to characteristic code block incorrect

### ISSUE THREAD

**Issue by jakehockey10** [MicrosoftDocs/windows-uwp#1208]
Hello,

I noticed that the call to WriteValueAsync needs to be WriteValueWithResultAsync in order for the result to be of type GattWriteResult (not GattReadResult like in the existing code block).  

https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client#enumerating-supported-services-and-characteristics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f89409a-b108-603f-9279-c59f5ae5d188
* Version Independent ID: 5bd07919-59ac-4fca-b997-a472ae24bfb1
* Content: [Bluetooth GATT Client - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by jakehockey10** [comment]
One could either write it this way:

``` csharp
GattWriteResult result = await characteristic.WriteValueWithResultAsync(writer.DetachBuffer());
if (result.Status == GattCommunicationStatus.Success)
{
    // Successfully wrote to device
}
```

or

``` csharp
GattCommunicationStatus status = await characteristic.WriteValueAsync(writer.DetachBuffer());
if (status == GattCommunicationStatus.Success)
{
    // Successfully wrote to device
}
```

**Comment by Karl-Bridge-Microsoft** [comment]
@jakehockey10 - your second example is exactly what is in the topic, so I believe your issue was addressed in a subsequent PR. Please reopen if that's not the case.
