### ISSUE TITLE
Creating a runtime component and calling it from Javascript throws runtime errors

### ISSUE THREAD

**Issue by re-jim** [MicrosoftDocs/windows-uwp#1211]
https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript

I attempted to follow the steps in this walkthrough, but I'm getting errors when attempting to invoke the C# from javascript.

I'm using VS 2017. You can find my project here: https://github.com/re-jim/UWPComponentSample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6c5dde-f52c-66ee-48ff-39a5c09e13c0
* Version Independent ID: 90c96795-0f58-b841-91c7-b5eefddd7804
* Content: [Creating a Simple Windows Runtime component and calling it from JavaScript - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript)
* Content Source: [windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by ajventi** [comment]
I am stuck at the second section, calling the component from JavaScript, because VS 17 didn't give me a default.js or any code at all in the template. Perhaps this needs an update?

**Comment by ajventi** [comment]
I just looked through the javascript templates and it looks like maybe instead of a Blank Project template we want the WinJS Template? It's the only template that has any code similar to the description in the text.

**Comment by ajventi** [comment]
Apologies for my comments, I have opened a separate thread for my issues.

**Comment by re-jim** [comment]
@msatranjr any updates or news?
Thanks

**Comment by regal60740** [comment]
I also am stuck at the second section, calling the component from JavaScript, because VS 2015 Enterprise didn't give me a default.js in the js folder.

**Comment by regal60740** [comment]
I used the WinJS Template instead of blank Template. I am getting some errors. I will try to work through these.

**Comment by regal60740** [comment]
I'm getting 54 errors now. I was getting an error for the project.json where it said I needed win 10 added but I saw all versions of win 10 in there? I tried to do an update for nuget for the UWP package hoping that would fix the error but I got an error saying the new version did not work in VS 2015. So I tried to uninstall the update and install the 5.2.2 version that was recommended and I got the 54 errors.

**Comment by regal60740** [comment]
I think I'm going to skip this Walkthrough. It is taking way too long so I will move on to something else for now.

**Comment by MDTeg** [comment]
Hi;
Ihave followed this walkthough too , and I have the same issue while trying to load the c# component.

**Comment by DexterWoo** [comment]
after RS3, these steps will fail.
however, if you switch the minwindows version to be 15063, it'll work again.
Not sure if that's a bug or something else.

**Comment by stevewhims** [comment]
Hi, @re-jim (and others). Thanks for filing this issue, and I'm sorry for the extremely long delay in responding to it.

I've created a task for myself to thoroughly revisit and revise this topic, and I've put that on my backlog.

We already have a duplicate GitHub issue about this same topic, with the same action plan here: https://github.com/MicrosoftDocs/windows-uwp/issues/1247. So let's consolidate, and I'll close this issue and we'll use #1247 for tracking and progress.

Thanks again!
Steve
