### ISSUE TITLE
how do you work out why company registration is always being rejected?

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/windows-uwp#1212]
we are attempting to register the company and have what we believe to be the correct information - but it keeps getting rejected...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a5c98-ba0b-38a0-d86e-2d5df4745d1a
* Version Independent ID: 643673cc-0b57-86f6-e00d-13aad2ef8d20
* Content: [Opening a developer account - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/publish/opening-a-developer-account)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
For help with this please open a support request at http://aka.ms/storesupport - under "Contact us" choose "Dashboard issue" and "Account setup & management".
