### ISSUE TITLE
Any document to use Microsoft Ads in Unity?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/windows-uwp#1213]
I'm making game for UWP, Android and iOS in one Project by Unity. But I can't find any docs and worked sample about integrate Microsoft Ads? May I give up UWP game?

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: b08c6292-c94c-2d95-e800-b14d404879f9
* Version Independent ID: 83029484-dc65-6c17-80f3-e75a6bbc6732
* Content: [Display ads in your app with the Microsoft Advertising SDK - UWP app developer](https://docs.microsoft.com/vi-vn/windows/uwp/monetize/display-ads-in-your-app#step-1-install-the-microsoft-advertising-sdk)
* Content Source: [windows-apps-src/monetize/display-ads-in-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/display-ads-in-your-app.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hello,

As it says on the [Microsoft Advertising SDK download page](https://marketplace.visualstudio.com/items?itemName=AdMediator.MicrosoftAdvertisingSDK), "All APIs in this SDK are exclusive to Universal Windows Platform (UWP) apps." 

Unfortunately, you will need to find another advertising solution for a cross-platform game or create conditional code to load different advertising solutions based on the different platforms.

**Comment by nguyenthanhliemfc** [comment]
I saw Unity can build a game out a Visual Studio Project with C# (Have a MainPage and MainPage.cs). 
Then I implement Microsoft Ads on it?

**Comment by mhopkins-msft** [comment]
The download page is pretty specific that it only supports the Universal Windows Platform.
