### ISSUE TITLE
AddOn Submissions can't really be managed through this API

### ISSUE THREAD

**Issue by johanlindfors** [MicrosoftDocs/windows-uwp#1217]
Since the API is not exposing the "Properties" | "Support Info" property set, there's no way to finalize a creation of an addon and a submission without first manually go to the Dev Portal and change these properties through the portal UI. These properties needs to be added ASAP.

Also, the Product Feedback link feels kind of old, or at least I couldn't login on the wpdev.uservoice.com web with my standard Microsoft account, doesn't even give me a possibility to insert password for login, using Edge on Windows 10 that is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7152857f-f15b-8a6f-ddd4-fd1fe4060c32
* Version Independent ID: 9c4aeb27-21fa-328c-6aad-c3e0d35d8fc9
* Content: [Get the status of an add-on submission - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-status-for-an-add-on-submission)
* Content Source: [windows-apps-src/monetize/get-status-for-an-add-on-submission.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-status-for-an-add-on-submission.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi Johan,

Thank you for this info. I have shared your feedback with the engineering team.

~ *Mark*
