### ISSUE TITLE
There is NO Developer Settings link

### ISSUE THREAD

**Issue by syncimprov** [MicrosoftDocs/windows-uwp#1221]
We are are Microsoft Partner with O365 (and associated AD account). We would like to use our company credentials for Dev Center. Can you please tell us how to do this? There is NO Developer Settings link under the gear icon. PLEASE do not make us sign up for a personal account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262768e8-ad91-7af3-1541-4f2d2f9de5ba
* Version Independent ID: cc035cc8-ce25-57c4-2d2d-389451442d98
* Content: [Associate Azure Active Directory with your Partner Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-dev-center)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-dev-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-dev-center.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Hi - I think you will need to open a support request (via http://aka.ms/storesupport) to troubleshoot this issue.
