### ISSUE TITLE
Incorrect restricted capability name for teamEditionDeviceCredential

### ISSUE THREAD

**Issue by yadavbdev** [MicrosoftDocs/windows-uwp#1223]
In the 'Windows Team Device Credentials' above the capability name should be singular like: teamEditionDeviceCredential 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. This issue has been fixed in the documentation.
