### ISSUE TITLE
appLicense.AddOnLicenses is null

### ISSUE THREAD

**Issue by omansak** [MicrosoftDocs/windows-uwp#1227]
i need check license to AddOn. I am using StoreAppLicense appLicense = await context.GetAppLicenseAsync(); -&gt; appLicense.AddOnLicenses but  AddOnLicenses gets null .Why ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6876f5-833c-935e-2fad-bc1cdb9df995
* Version Independent ID: e13e512a-27f3-f55f-e2bc-2e4e5f101009
* Content: [Get license info for your app and add-ons - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-license-info-for-apps-and-add-ons)
* Content Source: [windows-apps-src/monetize/get-license-info-for-apps-and-add-ons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-license-info-for-apps-and-add-ons.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
