### ISSUE TITLE
Databinding section might benefit from a primer on dependencyobject behavior

### ISSUE THREAD

**Issue by CheathamPatrick** [MicrosoftDocs/windows-uwp#1235]
The presentation of **data binding** documentation covers the various techniques fairly well. However, I feel that an extra several screens/pages worth of foundational principles to the operation of dependencyobjects and delegation would benefit the programmer in better understanding the plumbing being wired together by these various constructs laid out in the documentation. I recall formerly studying in-depth WPF and Windows 8 coding chapters in Dev Books, which went the extra mile in robustly developing the underlying principles. A better primer on such workings would serve the UWP developer with a stronger set of practices for employing the several data binding methodologies. Please consider an **interim discussion** of these old classic .NET UWP features, before getting to the complete set of coder methods. Thanks for considering this idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53846105-3eca-629b-29d4-3175fc0a98a5
* Version Independent ID: d9986a9c-3b13-b1fb-43eb-84587f5e7588
* Content: [Data binding - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/)
* Content Source: [windows-apps-src/data-binding/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/index.md)
* Product: **uwp**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The timeline in which this could be implemented may vary, so I'll be marking this as Closed. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
