### ISSUE TITLE
PowerShell module

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/windows-uwp#1242]
Is there a PowerShell module for makeappx.exe? If not is there a plan to make one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbb802e-250b-5875-5363-a63479a00cd2
* Version Independent ID: 2a240166-3532-5fbe-bd97-ce94cba7af1f
* Content: [Create an app package with the MakeAppx.exe tool - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/create-app-package-with-makeappx-tool)
* Content Source: [windows-apps-src/packaging/create-app-package-with-makeappx-tool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/create-app-package-with-makeappx-tool.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by c-don** [comment]
We currently do not have a PowerShell Module for creating Windows 10 app packages.

Our current offering of PowerShell modules that handle Windows 10 app packages are [here](https://docs.microsoft.com/en-us/powershell/module/appx/?view=win10-ps).

We would like to learn more about your scenario. If you would like to place a request for this module - please post the request on our [community ](https://techcommunity.microsoft.com/t5/MSIX/ct-p/MSIX) page.
