### ISSUE TITLE
About certificate signing for distribution

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#1244]
This page mentions that "it's recommended to sign your app package with a certificate from a certificate authority" to distribute an APPX or MSIX out of the Store, but if I distribute my app in the Store and outside the Store using MSIX, do I really need to purchase a certificate or I can get my MSIX signed by Microsoft for distribution outside the Store?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715b34c6-c615-4614-5263-c7ecca7c2151
* Version Independent ID: 5788dfe2-0396-40ae-24c0-c640e5e6d1c9
* Content: [Hosting UWP app packages on AWS for web install - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/web-install-aws)
* Content Source: [windows-apps-src/packaging/web-install-aws.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/web-install-aws.md)
* Product: **uwp**
* GitHub Login: @laurenhughes
* Microsoft Alias: **cdon**

**Comment by sylveon** [comment]
Also, if I need to purchase a certificate, would I need to sign every binary file in the package or just signing the MSIX will be fine? What if my app wants admin, will the signature from the MSIX show up? Or does signing the MSIX also signs all binaries inside?

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay in responding. Please see our main [packaging signing](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview) article for info about signing in general. If your questions are not answered by that article, please submit your feedback using the "Feedback" control at the bottom of the article. 

You can also try the following support options to get help with your questions:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
