### ISSUE TITLE
Not work. You waste my time. Next time focus to make working sample, not child "fashion" videos

### ISSUE THREAD

**Issue by AngelTs** [MicrosoftDocs/windows-uwp#1246]
Desktop, Win10Pro, 1803, 17134.407, VS2017.
The application "Update a live tile from a background task" totally not work - no tile updates, only success with compilation and start!
Can't debug!!!
Also in "Debug location', there is no "BlogFeedBackgroundTask"!!!
(just for comparison, I compile, run and debug successful "BackgroundTask" project from "Universal Windows Platform (UWP) app samples"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2136305d-9655-315a-0e2f-cdfeff173207
* Version Independent ID: e0b4b4fc-2acd-39be-2380-fb730a288a7e
* Content: [Update a live tile from a background task - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/update-a-live-tile-from-a-background-task)
* Content Source: [windows-apps-src/launch-resume/update-a-live-tile-from-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/update-a-live-tile-from-a-background-task.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by mbagattini** [comment]
This is way too harsh. Not the right way to ask for help, don' t be surprised if you're not getting some.
