### ISSUE TITLE
Error in Text

### ISSUE THREAD

**Issue by ajventi** [MicrosoftDocs/windows-uwp#1247]
Going through https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript I believe it needs updating. VS 17 does not give a "default.js" file in the template, the only file "main.js" is empty, so I don't think it could possibly work. I browsed the templates and it looks like the WinJSApplication Template is the right one, "main.js" seems to fit the description of "default.js" in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6c5dde-f52c-66ee-48ff-39a5c09e13c0
* Version Independent ID: 90c96795-0f58-b841-91c7-b5eefddd7804
* Content: [Creating a Simple Windows Runtime component and calling it from JavaScript - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript)
* Content Source: [windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by ajventi** [comment]
I should also add that the final link under "related topics" is recursive. I don't really think we need to reread the page for related topics.

**Comment by ajventi** [comment]
I've gotten further along, you definitely want the WinJSApplication template.

I've come across quite a few errors at this point, do you want to point me to where the code is in the repo (if there is any) and I can work on  a pull-request

**Comment by stevewhims** [comment]
Hi, @ajventi. Thanks for filing this issue, and sorry for the very long delay in responding to it.

If you're still interested in the PR that you mention, then please see https://docs.microsoft.com/contribute/ for instructions. The markdown file for this topic is here: https://github.com/MicrosoftDocs/windows-uwp-pr/blob/master/windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md.

Meanwhile, I've made a record of this ask, and put it onto my backlog. I don't have a schedule that I can share regarding when I might find time to revise this topic, but I'll leave the issue open.

Thanks again!
Steve

**Comment by stevewhims** [comment]
Just a heads up that I'm closing this GitHub issue because I'm tracking it internally in my work items (so that it's not being tracked and counted twice). You'll still be able to leave comments here. I'll come back and (possibly reopen and) comment when I have a resolution for my work item.

Thanks!
Steve
