### ISSUE TITLE
Need WPF Equivalent

### ISSUE THREAD

**Issue by shadowmage45** [MicrosoftDocs/windows-uwp#1248]
How to access an equivalent control in WPF?

(or has WPF development been dropped already in favor of UWP?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb31e7af-bc26-689e-6881-430e7bd9a8f7
* Version Independent ID: fa7d8401-dc0b-43c1-e3d0-5f3543d749f1
* Content: [Color Picker - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/color-picker)
* Content Source: [windows-apps-src/design/controls-and-patterns/color-picker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/color-picker.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@shadowmage45, you can use the WindowsXamlHost to use this color picker control in WPF. See [UWP controls in desktop applications](https://docs.microsoft.com/windows/uwp/xaml-platform/xaml-host-controls) for more info.
