### ISSUE TITLE
Which Privacy Settings affect failure reporting?

### ISSUE THREAD

**Issue by Heidelberger** [MicrosoftDocs/windows-uwp#1249]
"Most often, this occurs because of storage constraints, but it can also be a result of a device's privacy settings..."

Which privacy settings exactly? Please provide a link or additional information. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a91b3f4b-30e3-af2d-950c-38d5e63e0480
* Version Independent ID: 26779c86-2b4f-e741-0fdd-1e6c4bb22b20
* Content: [Health report - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/health-report)
* Content Source: [windows-apps-src/publish/health-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/health-report.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
This can be affected by a customer's diagnostic data settings (when someone chooses not to provide full diagnostic data to Microsoft). See  https://privacy.microsoft.com/en-US/windows-10-feedback-diagnostics-and-privacy_/ for more info.

**Comment by Heidelberger** [comment]
This is the correct link: [https://privacy.microsoft.com/en-US/windows-10-feedback-diagnostics-and-privacy/](https://privacy.microsoft.com/en-US/windows-10-feedback-diagnostics-and-privacy/)

Thank you!

**Comment by JnHs** [comment]
Thanks, sorry about the typo!
