### ISSUE TITLE
Grow Revenue

### ISSUE THREAD

**Issue by tolros1** [MicrosoftDocs/windows-uwp#1252]
Leverage rich commerce, capabilities and get insights into how your business is promoting on azure marketplace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91270efd-e009-5b09-a4c5-dc3675024fbd
* Version Independent ID: 9ab569b8-9106-1b68-d403-e885e9c8c84b
* Content: [Implement ads in your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/developer-walkthroughs)
* Content Source: [windows-apps-src/monetize/developer-walkthroughs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/developer-walkthroughs.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi tolros1, did you have some specific feedback about the documentation or are you just making a comment?

**Comment by mhopkins-msft** [comment]
Closing due to no response.
