### ISSUE TITLE
How is it handled when updating an app and simultaneosly change price from "free" to "not-free"

### ISSUE THREAD

**Issue by made1990** [MicrosoftDocs/windows-uwp#1254]
Meaning you have an app already published for free in the store.
Now you submit an updated version of your app and also want to charge for your app from now on.
What happens to those users already installed the earlier free app version? Can't they use there app anymore until they pay?
What if you enable a "free trial" version. Are the current users, the ones who got the app for free, automatically getting the "trial" status of the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4c0541-1af5-8654-ad07-96b62933bf85
* Version Independent ID: 8c0ba5f6-134c-051a-d520-4c86f9ce1895
* Content: [Set app pricing and availability - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/set-app-pricing-and-availability)
* Content Source: [windows-apps-src/publish/set-app-pricing-and-availability.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-app-pricing-and-availability.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Once a customer has a full license to your app, they won't lose that license, even if you raise the price or change it from free to a cost. Similarly they won't revert to a trial version even if you implement a trial after the customer acquired it.
