### ISSUE TITLE
As a develop do I have to pay for my own published app?

### ISSUE THREAD

**Issue by made1990** [MicrosoftDocs/windows-uwp#1255]
When I publish an app which is not for free to the store, do I have to pay for it as well when I want to download it?
Or is there some kind of linking between my Microsoft-account and developer account possible which prevents me from payment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca4c0541-1af5-8654-ad07-96b62933bf85
* Version Independent ID: 8c0ba5f6-134c-051a-d520-4c86f9ce1895
* Content: [Set app pricing and availability - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/set-app-pricing-and-availability)
* Content Source: [windows-apps-src/publish/set-app-pricing-and-availability.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-app-pricing-and-availability.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
There is no automatic linking, but you can generate promotional codes to get the app (and/or any add-ons) for free. See https://docs.microsoft.com/windows/uwp/publish/generate-promotional-codes
 for more info.
