### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/windows-uwp#1256]
The remarks section says "x:DataType value, as shown in the example below." yet there is no example below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27806783-e079-576b-6477-103b3582a7b4
* Version Independent ID: 6f94ae4c-9946-712a-53f9-4ea26a0b025c
* Content: [xBind markup extension - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension)
* Content Source: [windows-apps-src/xaml-platform/x-bind-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/x-bind-markup-extension.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@yowl, thanks for the feedback. The examples were moved to the top of the page. I've updated the text and linked to the Examples section.
