### ISSUE TITLE
This could use a serious refresh to current VS 2017 or alternate page altogether.

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/windows-uwp#1257]
Much of this is very dated information. In particular the current (15.9.2) tooling package.manifest tools have easier and better ways to edit the packages, and to get the various IDs needed. One thing still seems to require direct edit of XML is the support for multiple instances. Some people might not know how to edit the XML in 15.9.2 since it is not on the context menu, which is to right-click and choose Open with... then select the XML Text editor.
I have noted of late that documentation editors seem to be reluctant to update documentation to include current versions if it is not in error, just out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by eliotcowley** [comment]
Hi @laultman, sorry for the delayed response. I agree, this doc could use some updating. I will take that as a work item and update this issue when I'm done.

Re: lack of documentation updates, as much as we would like to keep everything up-to-date, it is a large documentation set, so it comes down to resource constraints and prioritizing :) But I will take that feedback and pass it along.

**Comment by eliotcowley** [comment]
Hi @laultman, I've updated the doc to make sure that everything works with the current tooling, and included the steps to edit the manifest file in the XML text editor. I also included the easier method of getting the package family name (copying it from the app manifest). And I passed along your feedback about the lack of doc updates&mdash;we're working on it :)
