### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by deskoh** [MicrosoftDocs/windows-uwp#1258]
Github link in documentation broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4665391f-f838-ae07-8591-d8f13f41a027
* Version Independent ID: 38b6b8ed-c3d2-97b1-9852-e3779b3ea281
* Content: [Using the UWP XAML hosting API in a desktop application - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/using-the-xaml-hosting-api)
* Content Source: [windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for letting us know about the broken links in this article. I have fixed the links, and those changes should be published to the live version of this article in the next couple of days.
