### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/windows-uwp#1260]
The section "Build up the heirarchy of services and characteristics" spells "hierarchy" incorrectly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43664026-c784-e891-bdec-3102f48ade77
* Version Independent ID: 4629d3c4-d850-d456-efe5-ba4c1d61c21b
* Content: [Bluetooth GATT Server - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-server)
* Content Source: [windows-apps-src/devices-sensors/gatt-server.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-server.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by jillre** [comment]
Thanks for the feedback, @EddieLotter! I fixed the typos, and the update should be live tomorrow.
