### ISSUE TITLE
Install via NuGet workflow has issues

### ISSUE THREAD

**Issue by the-jedi-code** [MicrosoftDocs/windows-uwp#1261]
**Microsoft.Services.Store.Engagement**

I've added the NuGet version to my UWP app. The issue happens when you create the store package and try to install the app using the powershell script inside the appxbundle you get this error.

```
Deployment of package Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe was 
blocked because the provided package has the same identity as an already-installed
package but the contents are different. Increment the version number of the package to be 
installed, or remove the old package for every user on the system before installing this package.
```

I ran a `Get-AppPackage Microsoft.Services.Store.Engagement` powershell command and found that windows already has installed the engagement package at the windows level

Name              : Microsoft.Services.Store.Engagement
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        : 
Version           : 10.0.18101.0
PackageFullName   : Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.Services.Store.Engagement_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

Need a fix ASAP this is critical to our QA/QC process which is broken by adding the store engagement nuget. We build the app bundle on jenkins and the QA/QC install the app using the powershell script. After adding the store engagement nuget no one is able to successfully install the app using the powershell script without hitting this error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ac044a-c64e-126c-5381-55fdd8856549
* Version Independent ID: df6632af-07d6-fcf9-9c47-ecd9a49c4a6f
* Content: [Engage customers with the Microsoft Store Services SDK - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/microsoft-store-services-sdk)
* Content Source: [windows-apps-src/monetize/microsoft-store-services-sdk.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/microsoft-store-services-sdk.md)
* Product: **uwp**
* GitHub Login: @mhopkins
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.

**Comment by the-jedi-code** [comment]
@Xansky Thanks i'll log my but over there.
