### ISSUE TITLE
Path too long on Azure Pipelines custom VM

### ISSUE THREAD

**Issue by bezysoftware** [MicrosoftDocs/windows-uwp#1266]
I got the error "Path too long" during a build on my Azure VM (run by Azure pipelines). The solution to add "repositoryPath" above didn't help, because the problem was with the global packages path - it was being installed into "C:\Windows\ServiceProfiles\NetworkService" and THIS path was too long. 
The solution was to add "globalPackagesFolder" into my Nuget.config and that fixed my build

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ac044a-c64e-126c-5381-55fdd8856549
* Version Independent ID: df6632af-07d6-fcf9-9c47-ecd9a49c4a6f
* Content: [Engage customers with the Microsoft Store Services SDK - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/microsoft-store-services-sdk)
* Content Source: [windows-apps-src/monetize/microsoft-store-services-sdk.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/microsoft-store-services-sdk.md)
* Product: **uwp**
* GitHub Login: @mhopkins
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for the feedback. I've incorporated your info into the article. It should publish tomorrow.
