### ISSUE TITLE
LOB App Submission

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windows-uwp#1267]
Is there a better explanation of why LOB app submissions are not supported? I've tried it, but it gets stuck at "CommitStarted"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368e3d24-23d2-9e46-3d58-3d328e917f50
* Version Independent ID: 15ddd09e-bf7a-21ed-b39f-300896186879
* Content: [Create and manage submissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services#not_supported)
* Content Source: [windows-apps-src/monetize/create-and-manage-submissions-using-windows-store-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/create-and-manage-submissions-using-windows-store-services.md)
* Product: **uwp**
* GitHub Login: @mhopkins
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.

**Comment by myokeeh** [comment]
Actually, to add to the confusion, it seems LOB apps ARE supported. All of my apps are for LOB, and the API handled them just fine after I figured out what I was doing wrong.
