### ISSUE TITLE
Instructions incorrect

### ISSUE THREAD

**Issue by Heidelberger** [MicrosoftDocs/windows-uwp#1268]
"If you encounter issues, contact product support. On that page, choose Ads-In-Apps."

There is no "Ads-In-Apps" selection on the linked product support page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552c0676-b378-929b-0882-4a8ce78d5c47
* Version Independent ID: 9dee3b2f-d6df-bbb7-7e0e-62dd19fc5e52
* Content: [Known issues and troubleshooting for ads in apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/known-issues-for-the-advertising-libraries)
* Content Source: [windows-apps-src/monetize/known-issues-for-the-advertising-libraries.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/known-issues-for-the-advertising-libraries.md)
* Product: **uwp**
* GitHub Login: @mhopkins
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi Heidelberger, thank you for pointing this out. You should choose **Contact us**. I've updated the topic. Thanks, again.
