### ISSUE TITLE
Define Dimensions

### ISSUE THREAD

**Issue by Heidelberger** [MicrosoftDocs/windows-uwp#1269]
It's not clear if the following are (width x height) or (height x width). They are, in fact, (height x width). Please state that in the doc. Thank you!

160x600
300x50
300x250
300x600
320x50
640x100
728x90

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff243ec-5cbd-fef0-006f-24498eb88468
* Version Independent ID: 1db6226f-8ff8-6994-20f0-0d8c2b7a5db2
* Content: [Supported banner ad sizes - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/supported-ad-sizes-for-banner-ads)
* Content Source: [windows-apps-src/monetize/supported-ad-sizes-for-banner-ads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/supported-ad-sizes-for-banner-ads.md)
* Product: **uwp**
* GitHub Login: @mhopkins
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi Heidelberger, the example images definitely look like the values are width x height, as I'd expect.

**Comment by mhopkins-msft** [comment]
Closing this since I haven't heard back.

**Comment by Heidelberger** [comment]
I didn't realize you were waiting for a response to your statement.

Yes, the images imply width x height.  Why not state it explicitly and avoid confusion?
