### ISSUE TITLE
Deprecated method in docs

### ISSUE THREAD

**Issue by AlexeySubbotin** [MicrosoftDocs/windows-uwp#1275]
In the "Get info about locations" section the deprecated GetLocationFromOffset method is advised to use. There should be the TryGetLocationFromOffset method listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2556060-087b-0509-0639-5ad36ce5a85e
* Version Independent ID: 47c9b210-bb48-c5f3-3cf5-08ff1a75662a
* Content: [Display maps with 2D, 3D, and Streetside views - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/display-maps)
* Content Source: [windows-apps-src/maps-and-location/display-maps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/maps-and-location/display-maps.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for the feedback. I've made this change in the docs, it should be published shortly. I'll keep this issue open until the change is visible.

**Comment by hickeys** [comment]
This change is now reflected in the page. I'm closing this issue.
