### ISSUE TITLE
Reading binary data

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#1276]
Could there be an example provided for reading binary data? It's not clear that the methods for reading text from a file are appropriate. Also, it would help to see some explanation of the advantages of each of these methods. Why should one choose the 4-step method when there are shorter methods, for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b36404b8-4385-81d9-2ee8-486f0a55fc37
* Version Independent ID: 7b6ce4df-6ab2-3aa6-059f-b38aa9ea8062
* Content: [Create, write, and read a file - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I am following up with the engineering team to confirm what improvements we can make to these docs, and will update this issue when I know more.

**Comment by stevewhims** [comment]
Hi, @jevansAN, I know you work with C++/WinRT so I'm offering a code example below for writing/reading binary data to/from a file in case it's of use. You could paste this into a new Blank App (C++/WinRT) project to try it out.

```cppwinrt
// MainPage.h
...
Windows::Foundation::IAsyncAction ClickHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::RoutedEventArgs const& args)
{
    co_await CreateDataFileAsync({ 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09 });
    co_await ReadDataFileAsync();
}

Windows::Foundation::IAsyncAction CreateDataFileAsync(std::vector<uint8_t> const& bytes)
{
    // Create a sample file; replace if exists.
    Windows::Storage::StorageFolder storageFolder{ Windows::Storage::ApplicationData::Current().LocalFolder() };
    co_await storageFolder.CreateFileAsync(L"sample.dat", Windows::Storage::CreationCollisionOption::ReplaceExisting);

    // Create a buffer from the byte array.
    Windows::Storage::Streams::IBuffer buffer{ Windows::Security::Cryptography::CryptographicBuffer::CreateFromByteArray(bytes) };

    auto sampleFile{ co_await storageFolder.GetFileAsync(L"sample.dat") };
    co_await Windows::Storage::FileIO::WriteBufferAsync(sampleFile, buffer);
}

Windows::Foundation::IAsyncAction ReadDataFileAsync()
{
    Windows::Storage::StorageFolder storageFolder{ Windows::Storage::ApplicationData::Current().LocalFolder() };
    auto sampleFile{ co_await storageFolder.GetFileAsync(L"sample.dat") };
    Windows::Storage::Streams::IBuffer buffer{ co_await Windows::Storage::FileIO::ReadBufferAsync(sampleFile) };

    // Encode the buffer into a hexadecimal string (for display);
    std::wstring hex{ Windows::Security::Cryptography::CryptographicBuffer::EncodeToHexString(buffer) };

    // Copy the buffer back into a new byte array.
    winrt::com_array<uint8_t> newByteArray;
    Windows::Security::Cryptography::CryptographicBuffer::CopyToByteArray(buffer, newByteArray);
}
...
```

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
