### ISSUE TITLE
sytax fault

### ISSUE THREAD

**Issue by spelbreker** [MicrosoftDocs/windows-uwp#1277]
public static List&lt;!!!S!!!tring&gt; GetData()
{
    List&lt;!!!S!!!tring&gt; entries = new List&lt;string&gt;();

    using (SqliteConnection db =
        new SqliteConnection("Filename=sqliteSample.db"))
    {
        db.Open();

        SqliteCommand selectCommand = new SqliteCommand
            ("SELECT Text_Entry from MyTable", db);

        SqliteDataReader query = selectCommand.ExecuteReader();

        while (query.Read())
        {
            entries.Add(query.GetString(0));
        }

        db.Close();
    }

    return entries;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback! The "Prepare the data access class" section of this article was missing an instruction to add a using statement for the System.Collections.Generic namespace to the top of the DataAccess code file. I have added this instruction, and this fix will be published to the docs in the next day or two.
