### ISSUE TITLE
Inaccurate explanation of accelerator resolution

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/windows-uwp#1278]
The documentation says:
A keyboard accelerator event bubbles from the element that has focus up to the root. If the event isn't handled, the XAML framework looks for other unscoped app accelerators outside of the bubbling path.

I just had the case that I let my accelerator bubble up (didn't set e.handled = true) and it then re-executed the very same accelerator. In other words, it's not "completely outside" the bubbling path. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@SilverSilence - can you provide more info? A sample of your code might help too.

**Comment by Karl-Bridge-Microsoft** [comment]
Closing due to lack of response.
