### ISSUE TITLE
Account Verification

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/windows-uwp#1280]
Hello team,

We received a notification that the verification process for Company account has been updated. Please remove the mention of Dun and Bradstreet from this documentation and the mention of the possibility of a phone call, since this was discontinued.

The standard SLA of the business verification will be 2 business days.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2099ff76-43d5-98fd-d8bc-66ccdc14c4fe
* Version Independent ID: 1c3f3863-5413-d58b-a0e5-81a6da6bccf2
* Content: [Account types, locations, and fees - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees#account-verification)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **jenhayes**

**Comment by JnHs** [comment]
Thanks for passing on this info, I'm confirming the current processes and what updates may be needed, and will reply back here after I've done so.

**Comment by JnHs** [comment]
@Nathan-Tarin could you let me know more about the notification you received - was this an email or other formal communication, or a conversation with support, or something else? Trying to understand the origin of this info.

**Comment by Nathan-Tarin** [comment]
Hello,

We received this notification from our SME for the Dev Center LOB (see attached).

Please refer to Ricardo Pabon (v-rpabo@microsoft.com<mailto:v-rpabo@microsoft.com>) for further clarification.

Let me know if you need anything else.

Best regards,


Nathan Tarin

**Comment by JnHs** [comment]
Thanks again for bringing this up. I'm in contact with the right folks and we'll update this page when we are able to confirm details - closing for now.
