### ISSUE TITLE
Incorrect New-SelfSignedCertificate example

### ISSUE THREAD

**Issue by shanepowell** [MicrosoftDocs/windows-uwp#1281]
The certificate requirements are documented here:
https://docs.microsoft.com/en-us/previous-versions/br230260%28v%3dvs.110%29

The example New-SelfSignedCertificate does not follow the above requirements so it doesn't work:
New-SelfSignedCertificate -Type Custom -Subject "CN=Contoso Software, O=Contoso Corporation, C=US" -KeyUsage DigitalSignature -FriendlyName <Your Friendly Name> -CertStoreLocation "Cert:\LocalMachine\My"

What is missing is the "Subject Type" requirement and the requirment that the certificate lives in the CurrentUser store location.

So an actual example that works is:

New-SelfSignedCertificate -Type Custom -Subject "CN=Contoso Software, O=Contoso Corporation, C=US" -KeyUsage DigitalSignature -FriendlyName <Your Friendly Name>  -TextExtension @('2.5.29.37={text}1.3.6.1.5.5.7.3.3', '2.5.29.19={text}Subject Type:End Entity') -CertStoreLocation "Cert:\CurrentUser\My"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77abe54a-8bb8-7f92-565b-e3647a93da8f
* Version Independent ID: fbc804fa-a529-8db5-3ef1-8d575cff3e38
* Content: [Create a certificate for package signing - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/create-certificate-package-signing)
* Content Source: [windows-apps-src/packaging/create-certificate-package-signing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/create-certificate-package-signing.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by JGFahey** [comment]
This might be the most helpful comment I've seen online on this... thank you

**Comment by maxkatz6** [comment]
I believe that issue is out-of-dated.
There is new docs page with fixed example:
https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing
