### ISSUE TITLE
Microsoft Store API Information

### ISSUE THREAD

**Issue by mnpoor** [MicrosoftDocs/windows-uwp#1283]
"Use the Microsoft Store promotions API to programmatically manage promotional ad campaigns for your apps. This API enables you to create, update and monitor your campaigns and other related assets such as targeting and creatives. This API is especially useful for developers who create large volumes of campaigns, and who want do so without using Partner Center dhboard." <===

Note spelling error 'dhboard'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842846ea-5a00-9921-3aed-7c725203f213
* Version Independent ID: fc3f8fdf-a74e-91b8-74a8-a7f0dcab88d9
* Content: [Microsoft Store services - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/using-windows-store-services)
* Content Source: [windows-apps-src/monetize/using-windows-store-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/using-windows-store-services.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi Meredith,

Thanks for reporting this typo. I've fixed the issue. It should be published tomorrow.

 ~ Mark
