### ISSUE TITLE
How to use Desktop Bridge in UWP Background Task?

### ISSUE THREAD

**Issue by urjapatel** [MicrosoftDocs/windows-uwp#1284]
I have a desktop application which I need to use and communicate from Background Task. I tried various solution but no luck.
Is it possible to communicate with desktop bridge app through App Service from UWP Background Task? And if yes how do i achieve that? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba89d6c-71c3-4583-8d7f-8db231a96b07
* Version Independent ID: ce5b525b-597c-0859-ed9c-aa3104498b8b
* Content: [Extend your desktop application with Windows UIs and components - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-extend)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-extend.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-extend.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
If I understand your question correctly, what you would like to do is not possible. IPC (Inter-Process Communication)is not allowed for Desktop Bridge apps outside of their app container to desktop components. [Please see here](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-desktop-bridge-app-tests#31-app-manifest)

If you'd like to continue to investigate your options, I recommend starting a conversation at [Microsoft Tech Community](https://techcommunity.microsoft.com/). As GitHub issues are only for feedback on documentation, I'm going to close this issue.
