### ISSUE TITLE
ProductId guidance is incorrect, should be the StoreId

### ISSUE THREAD

**Issue by billyrayxbox** [MicrosoftDocs/windows-uwp#1286]
This API (and perhaps the other Xbox One analytics APIs for XDP-published titles?) appears to require the StoreID, not the XDP product id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f41781d-fe03-611f-689a-f39f18299bb4
* Version Independent ID: bc2cdfdc-bdaf-f302-7ea5-a9e0d97aa494
* Content: [Get error reporting data for your Xbox One game - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-error-reporting-data-for-your-xbox-one-game#feedback)
* Content Source: [windows-apps-src/monetize/get-error-reporting-data-for-your-xbox-one-game.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-error-reporting-data-for-your-xbox-one-game.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi billyrayxbox,

The page says the API takes the _applicationId_, which it describes as the "product ID." Are you suggesting that this description should be changed to say "store ID?"

 ~ Mark

**Comment by mhopkins-msft** [comment]
I see it now, I'll make this update. Thanks!

**Comment by mhopkins-msft** [comment]
Hi billyrayxbox,

I checked with the engineering team and they told me that product ID is the correct term because it applies universally.

Thanks,
 *\~ Mark*

**Comment by billyrayxbox** [comment]
Hi,

Couple of problems here:

* The other analytics API docs use the term Store ID when referring to the applicationId parameter.
* ProductId is familiar to our Xbox partners as a big guid style Id they see in XDP.
* The documentation for applicationId tells the partner to go and get it from XDP.  This is incorrect.

The same wording as other analytics APIs seems like the right way to go, per this page:

https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-error-reporting-data.md

Although I'm not completely clear if the route to getting the StoreId is the same for XDP-published titles.

Thanks,
Will.

**Comment by mhopkins-msft** [comment]
Thanks for the info, I've updated the topic. It should be published tomorrow. Thanks!
