### ISSUE TITLE
Does not work (no sound) under Windows 10 1809

### ISSUE THREAD

**Issue by cwca** [MicrosoftDocs/windows-uwp#1287]
For whatever reason, using Windows 10 1809 from https://www.microsoft.com/en-ca/software-download/windows10ISO, built clean on a VMWare Fusion 11.0.2 Virtual Machine with the most current Visual Studio 2017, there is no sound from the speech synthesizer.  The VM outputs sound just fine (moving the volume control on the task bar results in a windows 'bing').   The exact same example run under a VMWare Fusion 11.0.2 VM Machine with the 1803 windows 10 build works fine - the speech works as expected, as it does on other machines I have around running 1803 (none has received the upgrade to 1809 from MS).  As far as I can tell this little sample app works ok otherwise - every press of the button results in about 3 MB of memory being used, with a garbage collect coming along from time to time clearing those allocations out.  Very much looks like a 1809 problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Interesting. Thanks for the report.

I'll investigate further, but I would encourage you (if you haven't already) to send a report to Windows developer feedback. If this is an issue that only exists on VMs running Version 1809 and doesn't have a known workaround, we can add a notice to the tutorial but probably won't update the code.

**Comment by cwca** [comment]
Had a physical machine update itself to 1809 today and tried out this example - works fine.  Only the VM version doesn't speak (but sound on the VM works though).  Perhaps some incompatibility with the sound drivers on the VM or other interaction.  Thanks for investigating.
