### ISSUE TITLE
Links to out of date content

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/windows-uwp#1290]
The following links go to content almost 3 years old.

See Universal Windows apps in .NET for an overview of writing .NET UWP apps
.NET Native - What it means for Universal Windows Platform (UWP) developers

Hard to believe content is still relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88c23e09-bb75-8b8e-0950-cb872194f1aa
* Version Independent ID: b331b47e-2f61-b1b7-b889-1b7fbb0d31ce
* Content: [What's a Universal Windows Platform (UWP) app? - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
To my knowledge, the "UWP in .NET" docs are still the most recent content in that area. I agree that the current .NET Native link is outdated, so I'll update it with more recent information.
