### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by khorshid-amazon** [MicrosoftDocs/windows-uwp#1294]
Typo: "indetermindate" should be "indeterminate"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4832355-0a00-8e3d-9e5a-1bfe4b2a915b
* Version Independent ID: 2b928728-705f-4dc6-1a5a-658d728ae924
* Content: [Toast progress bar and data binding - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-progress-bar)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-progress-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-progress-bar.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks, @khorshid-amazon ; I've fixed the typo.
