### ISSUE TITLE
Missing Credits on report

### ISSUE THREAD

**Issue by markseminatore** [MicrosoftDocs/windows-uwp#1296]
In UDC I do not see Credits Earned or Credits Spent on the Advertising Performance Report even though I've had a Community Ad campaign running for months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83096d8a-871a-3481-578a-e8f909468a79
* Version Independent ID: 3c352877-2aa6-3d50-d954-2bf12cdf8056
* Content: [Advertising performance report - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/advertising-performance-report)
* Content Source: [windows-apps-src/publish/advertising-performance-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/advertising-performance-report.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **jenhayes**

**Comment by JnHs** [comment]
Please open a support request at http://aka.ms/storesupport so that we can look into this.

**Comment by markseminatore** [comment]
@JnHs Sorry, are you asking me to open an issue at that location?

**Comment by JnHs** [comment]
Exactly, there is no way for us to look into your specific circumstances through doc feedback, so this is a way to get individualized support.

**Comment by mseminatore** [comment]
@JnHs This is not specific to me, no user sees Credits on the report screen in UDC.  I contacted support and it turns out the Credits Spent and Credits Earned only show up in the downloadable report.  The doc page should be updated to clarify to avoid confusion.
