### ISSUE TITLE
..

### ISSUE THREAD

**Issue by saidi6882** [MicrosoftDocs/windows-uwp#1297]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 94542e37-416b-d37d-b9a6-93fc343b1963
* Version Independent ID: a06bb01a-febf-350a-cfe7-e1cca85bf7d1
* Content: [Windows 10 Build 17763 API changes - UWP app developer](https://docs.microsoft.com/th-th/windows/uwp/whats-new/windows-10-build-17763-api-diff)
* Content Source: [windows-apps-src/whats-new/windows-10-build-17763-api-diff.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-17763-api-diff.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by ginami** [comment]
Hi @saidi6882 -- let us know if you have specific feedback on our docs. Thank you!
