### ISSUE TITLE
Adobe XD template still on 1806

### ISSUE THREAD

**Issue by WallSoGB** [MicrosoftDocs/windows-uwp#1298]
When it will be updated to 1810?

**Comment by ginami** [comment]
Hi @WallSoGB -- can you tell me which specific page in our docs you're referring to? This will help me route your question to the correct author. Thank you!

**Comment by WallSoGB** [comment]
Hi, it should be [there](https://github.com/MicrosoftDocs/windows-uwp/issues?utf8=%E2%9C%93&q=%22943e9c97-f223-4d3c-730c-a7f20cb04560%22&in=body), don't know why it was sent here instead.

**Comment by WallSoGB** [comment]
If you still need need a doc then [that's it](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/?ocid=cxfluent-v1Oct-fluent-get).

**Comment by mijacobs** [comment]
Hi @WallSoGB,
Our design team is in the process of updating the design toolkits, but I don't have an ETA just yet.
