### ISSUE TITLE
Unable to install the Device Guard Code Integrity policies

### ISSUE THREAD

**Issue by seanquijote** [MicrosoftDocs/windows-uwp#1300]
Hi,

I am unable to install the **Device Guard Code Integrity policies**.
I have already followed the instructions on renaming the desired policy file to **SIPolicy.P7B**, and copying it into the `C:\Windows\System32\CodeIntegrity\`.

This pops up when I try to execute one of the policies:
![p7b-installation-error](https://user-images.githubusercontent.com/13918341/49782989-3cdc8d00-fd53-11e8-9ac0-c4d852f8537a.PNG)

My machine's OS version is 1803 (Build 17134.441)

**Comment by ginami** [comment]
Hi @seanquijote -- I'm sorry you're having this problem! This issue list is specifically for feedback on our docs--for non-doc related issues, I recommend that you post your question on our forums or StackOverflow (linked on our [Support](https://developer.microsoft.com/en-us/windows/support) page).

**Comment by seanquijote** [comment]
Alright @ginami will do.
