### ISSUE TITLE
What's the OS requirement for Fluent design "Reveal Highlight" and "Acrylic"?

### ISSUE THREAD

**Issue by cindy712geng** [MicrosoftDocs/windows-uwp#1301]
We have tried that UWP that has "Reveal Highlight" and "Acrylic" implemented can't be installed on RS1 and it can't work normally in RS2.
What's the min OS requirement for these features?RS3?

**Comment by ginami** [comment]
Hi @cindy712geng -- if you give me the URL of the specific doc that should contain this information, I can route your question to the correct author. Thank you!

**Comment by YuliKl** [comment]
@cindy712geng You are correct, acrylic and reveal components of the Fluent design system were added in RS3 (Fall Creators Update, 16299)

**Comment by ginami** [comment]
Thanks @YuliKl! 
@cindy712geng I'll close this issue--please let us know if you have further questions. Thank you!
