### ISSUE TITLE
"get_unknown" no longer compiles (Win 1809, latest VS and cppwinrt) 

### ISSUE THREAD

**Issue by ShawnKendall** [MicrosoftDocs/windows-uwp#1304]
**get_unknown** no longer compiles (Win 1809, latest VS and cppwinrt) as per example above and in the example Direct2D app.

```
check_hresult(factory->CreateSwapChainForCoreWindow(
    device.get(),
     get_unknown(CoreWindow::GetForCurrentThread()),
    &props,
    nullptr, // all or nothing
    swapChain.put())
);
```

`...direct2d\app.cpp(130): error C3861: 'get_unknown': identifier not found`

Already had the the command-line options mentioned elsewhere (as was working before updates anyway) :
/bigobj /await /permissive- /Zc:twoPhase-

Thanks for any help!

**Comment by ginami** [comment]
Hi @ShawnKendall -- which page in our docs are you referring to? (This will help me route your question to the correct author.) Thank you!

**Comment by ShawnKendall** [comment]
Yeah I some how posted this here instead of the page. I xposted to the page and found a workaround so I'd say you are welcome to delete this issue. Sorry I don't know how but I'll keep looking.
Thank you!
