### ISSUE TITLE
What is textureData?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#1306]
Where is textureData defined here? How is it loaded? Where is it loaded? What data structure holds it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d54624b3-5d20-80db-2092-a8850ceaeb45
* Version Independent ID: 67dfbf9f-c38d-92e9-f421-d94d75571853
* Content: [Apply textures to primitives - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/applying-textures-to-primitives)
* Content Source: [windows-apps-src/gaming/applying-textures-to-primitives.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/applying-textures-to-primitives.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @KBarrDev, it looks like there's a typo in the code. I've just made a change to the code, which should be live today, but in the meantime, here's how the code should look. I'll leave this issue open, please let me know if you run into any other issues with it.

```cppcx
auto loadTDTask = DX::ReadDataAsync(L"texturedata.bin");
          
auto constructSubresourceTask = loadTDTask.then([this](const std::vector<byte>& textureData)
{  
    D3D11_SUBRESOURCE_DATA textureSubresourceData = {0};
    textureSubresourceData.pSysMem = textureData.data();

   ...
}
```

The function DX::ReadDataAsync, as you know, is a generic "read a binary file" function. It's used to read the compiled shader objects, too. So we can use it here to load a texture image file. The `.then` is a continuation, and it takes whatever the async operation (in this case, a call to ReadDataAsync) generated. The call to ReadDataAsync generated a vector of bytes, of course, containing the bytes that were in the binary file. So we just grab the data from that vector and use it to prime the D3D11_SUBRESOURCE_DATA.

Thanks! ~Steve

**Comment by stevewhims** [comment]
Hi, @KBarrDev, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
