### ISSUE TITLE
cant access textbox.handwriting 

### ISSUE THREAD

**Issue by SheheryarSherry** [MicrosoftDocs/windows-uwp#1307]
I am trying to put the textbox pro[erty that is textbox.handwriting but it is not available can you please explain how to add this property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efbfea7-c3c1-0e34-14a3-b96c8a4c51f3
* Version Independent ID: 2613d9b6-c11a-050b-ea28-f3669f20c564
* Content: [Text input with the handwriting view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-handwriting-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/text-handwriting-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/text-handwriting-view.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by chigy** [comment]
@marb2000 ?

**Comment by marb2000** [comment]
You meant IsHandwritingViewEnabled property, right? The IsHandwritingViewEnabled is only available when your app targets  the 1803 Win10 build (17134 SDK).  Make sure that your are targeting it at Project's Properties.
