### ISSUE TITLE
Bug in code snippet

### ISSUE THREAD

**Issue by XamlBrewer** [MicrosoftDocs/windows-uwp#1308]
I believe that the last line of the last code snippet should read: 
visual.StartAnimation("Offset", animation);

The target property of the Vector3 animation is the whole Offset and not just Offset.X 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd76f137-7acf-075b-2eda-fdc0b377c052
* Version Independent ID: 468ea2ed-216f-6b04-f81c-9cb78c05f386
* Content: [Time animations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/time-animations)
* Content Source: [windows-apps-src/composition/time-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/time-animations.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by XamlBrewer** [comment]
Same for the snippet before that, it should become:
redVisual.StartAnimation("Offset", animation);

**Comment by jwmsft** [comment]
@XamlBrewer, thanks for pointing out this error. The code has been updated.
