### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by ikhbarkhan** [MicrosoftDocs/windows-uwp#1310]
UpDate

---
#### Butiran Dokumen

⚠ *Jangan edit bahagian ini. Ia diperlukan untuk docs.microsoft.com ➟ Pemautan isu GitHub.*

* ID: 389b0b14-d267-2aa2-fa43-33d3ba813d5a
* Version Independent ID: 8cd6bccf-b426-a21d-13a7-6eb08fb1f235
* Content: [Windows 10 game development guide - Windows UWP applications](https://docs.microsoft.com/ms-my/windows/uwp/gaming/e2e#submitting-and-publishing-your-game)
* Content Source: [windows-apps-src/gaming/e2e.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/e2e.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by ginami** [comment]
Hi @ikhbarkhan -- please let us know if you have specific feedback for our docs. Thank you!
