### ISSUE TITLE
No proper or detailed message is provided if import fails.

### ISSUE THREAD

**Issue by jignesh-fandco** [MicrosoftDocs/windows-uwp#1314]
Below are some list or errors that are repeated for each language.  It make no sense from the message "The value you provided is not valid".  Cross checked many times, but The folder path is correct, Image File does exists.  

I'm out of ideas.  

and yes, forgot to mention, I also increase the size of image to 1366 x 768 (as recommended on store website)  still the same error.   Note: On the Store website when image is manually uploaded, Store does accept the image even if size of image is less then  1366 x 768.

Arabic (Algeria) ar-DZ
DesktopScreenshot1
100
The value you provided is not valid (20181213_142109/Images/InitialScreen.PNG).
Arabic (Algeria) ar-DZ
DesktopScreenshot2
101
The value you provided is not valid (20181213_142109/Images/ExampleOfRenamingProjectDirectory.PNG).
Arabic (Algeria) ar-DZ
DesktopScreenshot3
102
The value you provided is not valid (20181213_142109/Images/AboutToRenameProjectDirextory.PNG).
Arabic (Bahrain) ar-BH
DesktopScreenshot1
100
The value you provided is not valid (20181213_142109/Images/InitialScreen.PNG).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f3b82f-eca4-13e7-91fa-094976277e1b
* Version Independent ID: d600811c-5f35-e818-13de-881d39f41117
* Content: [Import and export Store listings - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/import-and-export-store-listings)
* Content Source: [windows-apps-src/publish/import-and-export-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/import-and-export-store-listings.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **JnHs**

**Comment by JnHs** [comment]
Thanks for passing your feedback along. We're looking into this to see if we can provide more details about these types of messages. I'll respond again once I have an update. In the meantime, you can always open a support issue via http://aka.ms/storesupport to get personalized support.

**Comment by JnHs** [comment]
Thanks for your patience. I'm sorry that I haven't been able to confirm what the issue is with these files, and that it's taken so long to respond again. If you haven't already, please contact support to get more info and help resolve the problem.
