### ISSUE TITLE
What exactly is the role of MSIX here?

### ISSUE THREAD

**Issue by mhmd-azeez** [MicrosoftDocs/windows-uwp#1315]
We have always been able to create appx files, and it seems that it hasn't changed. But from what I've read, MSIX is for both UWP and Win32 apps. Can you clarify, please?

~~Because if MSIX is the same thing as Appx, we have had many issues around its auto-update feature for self-hosted (on IIS) apps, because it doesn't update the app most of the time. We even updated windows to the October 2018 update, still no luck.~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1c88d-24b1-0eda-b458-105db02dca36
* Version Independent ID: c5d1634a-0ead-f68a-e5be-89acf0eef0a6
* Content: [Packaging UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps?context=/windows/msix/render)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Apologies for the late reply on this issue. MSIX is indeed the recommended app packaging technology for any Windows 10 application, including UWP apps and other types of traditional desktop apps including .NET and native C++/Win32 apps. For more details about what MSIX provides and how to work with it, please see the [MSIX docs](https://docs.microsoft.com/en-us/windows/msix/overview).
