### ISSUE TITLE
Second code snippet missing semicolon

### ISSUE THREAD

**Issue by tjmullen2** [MicrosoftDocs/windows-uwp#1316]
Second code snippet missing semicolon on the GetDeferral(); line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9daac3-b416-9a90-39ff-55ada1d9d461
* Version Independent ID: fecefe30-8a56-5da4-1123-7e822d96ae8a
* Content: [Create and register an out-of-process background task - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task)
* Content Source: [windows-apps-src/launch-resume/create-and-register-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-and-register-a-background-task.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by eliotcowley** [comment]
Thanks for catching this, @tjmullen2! The fix should be reflected in the live docs soon.
