### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by jakejgordon** [MicrosoftDocs/windows-uwp#1317]
There is a typo with the word "Fortunatly". Should be "Fortunately".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac89746a-7629-6a95-6c5c-9498a9d7989f
* Version Independent ID: 044558cb-9f69-42df-362c-6c35317c3411
* Content: [App icons and logos - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos)
* Content Source: [windows-apps-src/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/app-icons-and-logos.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks, @jakejgordon. I've checked in a fix.
