### ISSUE TITLE
 Operator '==' cannot be applied to Operands of type 'NavigationViewDisplayMode'.

### ISSUE THREAD

**Issue by Sikanderalikhan123** [MicrosoftDocs/windows-uwp#1318]
In the documentation I am getting issue in  [On_BackRequested()]. 
Here I am getting issue that Operator '==' cannot be applied to Operand of type 'NavigationViewDisplayMode'
 if (NavView.IsPaneOpen &&
                (NavView.DisplayMode == muxc.NavigationViewDisplayMode.Compact ||NavView.DisplayMode == muxc.NavigationViewDisplayMode.Minimal))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
Hi @Sikanderalikhan123, did you expand the "muxc" from the sample to its full namespace? That line should read ```(NavView.DisplayMode == Microsoft.UI.Xaml.Controls.NavigationViewDisplayMode.Compact || 
NavView.DisplayMode == Microsoft.UI.Xaml.Controls.NavigationViewDisplayMode.Minimal)``` . 

If you're getting an error, it's most likely the result of a namespace mismatch: your NavigationView control is using the **Microsoft**.UI.Xaml.Controls namespace, while your display mode is defaulting to  **Windows**.UI.Xaml.Controls.
