### ISSUE TITLE
Null pointer in "Did you mean to switch apps" system dialog

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/windows-uwp#132]
Code snippet below throws null pointer when.
```
// The URI to launch
var uriBing = new Uri(@"http://www.bing.com");

// Set the option to show a warning
var promptOptions = new Windows.System.LauncherOptions();
promptOptions.TreatAsUntrusted = true;

// Launch the URI
var success = await Windows.System.Launcher.LaunchUriAsync(uriBing, promptOptions);
```

Null pointer deals
```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
```

**Comment by TylerMSFT** [comment]
Hi, I am unable to repro the problem. When I copy the code above and run it in a UWP app, I see the dialog, as expected. No errors. Do you have more context about how you are running that code?

**Comment by ugreg** [comment]
Sure thing I am using this framework https://github.com/craigomatic/HybridWebApp-Framework
and trying to implement the dialog in a custom event handler below.

I'm also using, am I missing other usings?
```
using Windows.System;
```

Event handler below
```
private async void WebView_NewWindowRequested(HybridWebView sender, HybridWebApp.Toolkit.NewWindowEventArgs args)
        {
            // Set the option to show a warning
            LauncherOptions promptOptions = new Windows.System.LauncherOptions();
            promptOptions.TreatAsUntrusted = true;

            var success = await Windows.System.Launcher.LaunchUriAsync(args.Uri, promptOptions);
        
            // TODO: greg will replace contoso with uri from args
            if (args.Uri.ToString() == "www.contoso.com")
            {
                var newWebView = new WebView();
                newWebView.Navigate(e.Uri);

                args.Handled = true;
            }
        }
```

**Comment by TylerMSFT** [comment]
@gregdegruy 
>> I missing other usings?
No. It wouldn't compile, if you were.
I ran a version of your snippet against the Windows 10 Creators Update and it worked fine for me. I don't know what other aspects of your project may be a factor. Unfortunately, we can't provide individual support via the comment section of the docs. You might open a support request at http://aka.ms/storesupport so that someone can look into your situation.
