### ISSUE TITLE
Clarity + lack of example

### ISSUE THREAD

**Issue by anticoder69** [MicrosoftDocs/windows-uwp#1320]
Please be more specific on "namespace", give a concrete code example on how to retrieve the SecureBrowser object

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f88d8c5-5dcd-4cec-89b0-a30aab0f46c5
* Version Independent ID: cc634390-a145-90ec-c654-4b6fccd25f71
* Content: [Take a Test JavaScript API. - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/apps-for-education/take-a-test-api#reference-documentation)
* Content Source: [windows-apps-src/apps-for-education/take-a-test-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/apps-for-education/take-a-test-api.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The SecureBrowser object is defined as part of the SBAC standard published by the Smarter Balanced Assessment Consortium. There is a link to more documentation on the page, but documenting SecureBrowser itself is beyond the scope of this page.
