### ISSUE TITLE
inconsistency in recommendations 

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/windows-uwp#1323]
We mention: For Windows 10, we recommend uploading the .msixupload or .appxupload file here rather than .msix, .appx, .msixbundle, or .appxbundle. For more info about packaging UWP apps for the Store, see Packaging a UWP app with Visual Studio.

But https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps mentions: appxupload is the only type of valid app package for Partner Center that can be created using Visual Studio. Other valid app packages can be created manually, without Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0098ee34-7905-a879-190b-10f783f638a6
* Version Independent ID: beb7fc7d-233c-5a15-a9a6-ffe86639527c
* Content: [Upload app packages - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/upload-app-packages)
* Content Source: [windows-apps-src/publish/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/upload-app-packages.md)
* Product: **uwp**
* GitHub Login: @JnHs
* Microsoft Alias: **JnHs**

**Comment by mcleanbyron** [comment]
Thanks for your feedback and for pointing out the inconsistencies in the docs! I have updated [https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps) to discuss .msixupload as well as .appxupload. I also took the liberty to update the screenshots.
