### ISSUE TITLE
Wrong starting point

### ISSUE THREAD

**Issue by BMarques** [MicrosoftDocs/windows-uwp#1325]
The documentation says: "This means that the starting point for your game lives in the body of the implementation of the IFrameworkView::Run method, and in this case, it's the App::Run." 

This isn't correct, it should be that the starting point is the Initialize method of the App class, not the Run method, or did I misundersand? Because without Initialize and subscribing to the Activated event, Run is never called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2b72f7d-02ee-6da6-4da7-ef271f460a55
* Version Independent ID: 0b570656-c7b3-7c38-1ff9-27ae37c96816
* Content: [Set up the game project - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure)
* Content Source: [windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by eliotcowley** [comment]
Hi @BMarques, I think you're right, but I'm assigning @stevewhims to double-check me.

**Comment by stevewhims** [comment]
Yes, what I've found from experimentation is that on Windows 10 the methods of IFrameworkView are called in the order Initialize-SetWindow-Load-OnActivated-Run-Uninitialize. Calling CoreApplication::Run kicks off that lifycycle. So, yes, this topic could do with an edit there, I think.

~Steve

**Comment by stevewhims** [comment]
I've made a change/fix to the topic, and that change is now live. So, I'll go ahead and close this issue now. Thanks! ~Steve
