### ISSUE TITLE
Please correctly document which threads the Suspending and Resuming handlers are called on and also how a multi-view app should handle Suspending

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/windows-uwp#1331]
My app opens multiple windows, and I recently had a lot of trouble with the Suspending handler. To cut a long story short, I eventually found out that the Suspending handler is called on the same thread on which it was registered. This is important because it turns out that secondary view threads can be paused before the main view thread suspending handler is called, so trying to run cleanup code for secondary views via a dispatcher in the main view suspending handler will simply never complete and cause the deadline to be passed it you await it. So the correct way to do it is to add a separate suspending handler from each view thread (actually similar to as shown in the example above, but not as in the template code generated by Visual Studio). Can you be more explicit about this and document what thread the handler is called on?

Also, from my testing, the Resuming handler behaves in exactly the same way as the Suspending handler. Please can you confirm this and update the documentation for that as well (currently the documentation says the Resuming handler is not called on the UI thread).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b264496-f46e-d4d5-6ede-eb977669bfe7
* Version Independent ID: 7faa19a5-797a-c504-9a8d-e23129c11636
* Content: [Handle app suspend - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/suspend-an-app)
* Content Source: [windows-apps-src/launch-resume/suspend-an-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/suspend-an-app.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by benstevens48** [comment]
In addition, I guess this should also be documented in the Suspending - https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.suspending - and resuming - https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.resuming - documentation pages.

**Comment by arcturien** [comment]
Hi all,

Is it possible to prevent Windows from suspending an Win10 app, like VS debugger?

Cordialy,

Hervé Ndoguéfouba.

**Comment by fman028** [comment]
It took me days to realize my suspend issue was because secondary UI threads are already stopped.  Would be great to have this documented!

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
