### ISSUE TITLE
Missing MainPage.xaml creation

### ISSUE THREAD

**Issue by JackDetrick** [MicrosoftDocs/windows-uwp#1337]
MainPage.xaml is mentioned but I can find no reference for creating it via Blank App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Did you create your UWP application project using the standard "Blank App (Universal Windows)" project template in Visual Studio? If so, the MainPage.xaml file (and the relateed code-behind file) should be created for you in your project.

**Comment by mcleanbyron** [comment]
I am closing this issue for now. If my previous response did not address your issue, please reopen with more info. Thanks!

**Comment by awild-collab** [comment]
SOLVED

In Visual Studio 19 if your Mobile Xamarin project lacks a MainPage.xaml component, simply create it: In Solution Explorer <Right><Click> on the Project title and <Left><Click> Add/New Item.  Then in the Add New Item window select Xamarin.Forms and select Content Page.  At the bottom of the window rename the page to MainPage.xaml and <Left><Click> on Add.

You'll find the proper "Welcome to Xamarin.Forms!" code is automatically populated within it.  You may need to add a couple of missing lines in the top section for compatibility sake:  

xmlns:d="http://xamarin.com/schemas/2014/forms/design"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
mc:Ignorable="d"

Have fun!  'Alan
