### ISSUE TITLE
We need information about connecting to LocalDB

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1340]
Is connection to LocalDB supported?
I am experiencing all kinds of issues
https://stackoverflow.com/questions/53909226/why-cant-i-see-a-database-created-by-a-uwp-desktop-bridge-app-in-the-sql-serve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f63491-26ec-52f6-e124-dec2ecea8477
* Version Independent ID: 72aa55f1-766a-c015-a5f7-104359382d53
* Content: [Use a SQL Server database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases)
* Content Source: [windows-apps-src/data-access/sql-server-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sql-server-databases.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
