### ISSUE TITLE
UseOppositeRCRatio?

### ISSUE THREAD

**Issue by zenjia** [MicrosoftDocs/windows-uwp#1344]
What should we do to update the layout of the panel when UseOppositeRCRatio is changed later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4239a3c-6a26-3b05-4154-09df54bee5d6
* Version Independent ID: 1eb8acb6-1379-8df8-aef9-e858bf9c315d
* Content: [BoxPanel, an example custom panel (Windows apps) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/boxpanel-example-custom-panel#feedback)
* Content Source: [windows-apps-src/design/layout/boxpanel-example-custom-panel.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/boxpanel-example-custom-panel.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
I believe you would add a DependencyPropertyChanged callback to the DependencyProperty.Register and in that callback you would call InvalidateMeasure() on the target.
