### ISSUE TITLE
Trigger buttons after typing something with enter (toast notifications)

### ISSUE THREAD

**Issue by MarcAnt01** [MicrosoftDocs/windows-uwp#1345]
In a messaging app if someone writes a quick reply and wants to send it, has to press reply after having typed, is it possible to make enter trigger that button?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b559cf6d-7bd0-9e1a-8ab0-a389b01a20d8
* Version Independent ID: 7e9df100-79bc-20f5-a193-3194328b28bc
* Content: [Toast content - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts#buttons)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @MarcAnt01, 
 I think there are many ways to do this. One of the simplest ways is to register for the key down event on whatever element the user is typing into and testing to see whether they pressed Enter: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.keydown 

You can read more about keyboard events here: https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events 

I recommend taking a look at the section on setting up keyboard shortcuts, "Shortcut keys example."

**Comment by MarcAnt01** [comment]
> Hi @MarcAnt01,
> I think there are many ways to do this. One of the simplest ways is to register for the key down event on whatever element the user is typing into and testing to see whether they pressed Enter: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.keydown
> 
> You can read more about keyboard events here: https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events
> 
> I recommend taking a look at the section on setting up keyboard shortcuts, "Shortcut keys example."

That's not applicable to toast notifications

**Comment by mijacobs** [comment]
I think I see what you mean--are you talking about a quick reply within the toast notification UI?

**Comment by MarcAnt01** [comment]
>           I think I see what you mean--are you talking about a quick reply within the toast notification UI?

Yes and send it without clicking on one of the two buttons

**Comment by mijacobs** [comment]
I don't believe you can do that. Adding @andrewleader--Andrew, is there a way to let the user send a message in a quick reply block by pressing Enter?

**Comment by MarcAnt01** [comment]
> I don't believe you can do that. Adding @andrewleader--Andrew, is there a way to let the user send a message in a quick reply block by pressing Enter?

You haven't tagged him properly 😉

**Comment by andrewleader** [comment]
Hey @MarcAnt01!

Windows toast notifications use `Ctrl+Enter` to invoke the quick reply action. There's no way you can customize that (neither as the app developer nor the user).

Did you know about `Ctrl+Enter`? Would you still rather it be simply `Enter`? If so, please provide more info about your scenario and why that's important so that we can gather this feedback!

Note that this functionality depends on you using hint-inputId in your action to make the action button behave as a quick reply button

```xml
        <input id="textBox" type="text" placeHolderContent="reply"/>

        <action
          content="Send"
          imageUri="Assets/Icons/send.png"
          hint-inputId="textBox"
```

![image](https://user-images.githubusercontent.com/13246069/50613423-596f6f00-0e92-11e9-9989-963c64be6056.png)

**Comment by MarcAnt01** [comment]
> Hey @MarcAnt01!
> 
> Windows toast notifications use `Ctrl+Enter` to invoke the quick reply action. There's no way you can customize that (neither as the app developer nor the user).
> 
> Did you know about `Ctrl+Enter`? Would you still rather it be simply `Enter`? If so, please provide more info about your scenario and why that's important so that we can gather this feedback!
> 
> Note that this functionality depends on you using hint-inputId in your action to make the action button behave as a quick reply button
> 
> ```
>         <input id="textBox" type="text" placeHolderContent="reply"/>
> 
>         <action
>           content="Send"
>           imageUri="Assets/Icons/send.png"
>           hint-inputId="textBox"
> ```
> 
> ![image](https://user-images.githubusercontent.com/13246069/50613423-596f6f00-0e92-11e9-9989-963c64be6056.png)

I didn't know about it, anyway I asked the Unigram main dev to add it to his app and he told me that there's no documentation about how to add it. In Unigram to send a message I just type enter and having a different behaviour in the quick reply area is not good

**Comment by andrewleader** [comment]
Thanks MarkAnt01 for this valuable feedback. I'll close this issue and track this product feedback internally (since this is Windows feedback, no longer a docs question).

**Comment by MarcAnt01** [comment]
>           Thanks MarkAnt01 for this valuable feedback. I'll close this issue and track this product feedback internally (since this is Windows feedback, no longer a docs question).

Thank you for considering my idea

**Comment by MarcAnt01** [comment]
@andrewleader control + enter is not applicable to the template used by Unigram
![image](https://user-images.githubusercontent.com/43090263/50636243-a700e000-0f55-11e9-8258-432d9eb0ba20.png)

**Comment by andrewleader** [comment]
Thanks for including a picture of their notification. Indeed, in that case, there's no quick shortcut to press send. We'll track this feedback for making it possible for a developer to associate the button with an enter press action.

In the meantime, as a user, you can hit the `Tab` key twice to move focus to Send, and then press Enter.

**Comment by drewbatgit** [comment]
Doing a pass through old github issues. Since this seems to be tracked as a product feature request, I'm going to go ahead and close the issue.

**Comment by WisdomWolf** [comment]
Nearly a year after this issue was closed it still exists.  I'm not clear why it was closed in the first place since the product feature request was closed with a reference back to this issue.
