### ISSUE TITLE
missing IMR

### ISSUE THREAD

**Issue by linojon** [MicrosoftDocs/windows-uwp#1348]
Immersive MR devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2975459d-0a61-a9ac-02be-5a1191254165
* Version Independent ID: 453681de-7ac5-c469-31c9-afabf4c8a930
* Content: [App package architectures - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/device-architecture)
* Content Source: [windows-apps-src/packaging/device-architecture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/device-architecture.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. If I'm understanding your comment correctly, this is covered by the "Windows Mixed Reality and HoloLens" column. If I have misunderstood, please reopen this issue with more details.

**Comment by linojon** [comment]
Are we looking at the same page? I dont see a "Windows Mixed Reality and HoloLens" column.

https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/device-architecture.md

| UWP Architecture | Desktop (x86) | Desktop (x64) | Desktop (ARM) | Mobile | HoloLens | Xbox | IoT Core (Device dependent) | Surface Hub |

**Comment by mcleanbyron** [comment]
I'm seeing the "Windows Mixed Reality and HoloLens" column on that page now. Previously it was just "HoloLens" but I revised the column title to clarify the scope of what this column refers to several days ago in the copy of this file in our internal repo. That change was published to the public docs site yesterday, and it looks like that change has now made it to the version of this file in the public docs repo (the one you linked to).
