### ISSUE TITLE
The SetContentFromBitmapImage command in the Customizations section gives error.

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [MicrosoftDocs/windows-uwp#1349]
This line is good to reference, but if copy/pasted in doesn't work and crashes app.

e.DragUIOverride.SetContentFromBitmapImage(null); // Sets a custom glyph

All the other examples work just fine.

Tanks for the wonderful tutorial!
Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11b8e0c0-6835-070e-da44-b6e35a9f38cb
* Version Independent ID: 34b699ef-e437-2d70-1c6b-d530789a9cbb
* Content: [Drag and drop - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/drag-and-drop)
* Content Source: [windows-apps-src/design/input/drag-and-drop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/drag-and-drop.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jevansaks** [comment]
@RobbyRobbyRobby can you elaborate on the crash? Maybe provide the error message you get and the stack?

For product bugs we prefer to track them on our product GitHub -- https://github.com/microsoft/microsoft-ui-xaml.

**Comment by jwmsft** [comment]
@jevansaks, this is a doc issue. You can't pass `null` to SetContentFromBitmapImage as shown in the example. I've submitted an update to correct the code. It should look like this:
`e.DragUIOverride.SetContentFromBitmapImage(new BitmapImage(new Uri("ms-appx:///Assets/CustomImage.png", UriKind.RelativeOrAbsolute)));`
