### ISSUE TITLE
Suggested changes to the `documentsLibrary` section of the capabilities page.

### ISSUE THREAD

**Issue by ptorr-msft** [MicrosoftDocs/windows-uwp#1350]
Suggested changes to the `documentsLibrary` section:
---

The `documentsLibrary` capability provides programmatic access to the user's **Documents** folder, filtered to the file type associations declared in the package manifest. For example, if a word processing app declared a `.doc` file type association, it can open `.doc` files in the user's **Documents** folder. 

Generally, apps should allow the user to choose the location of their files, using one of the following APIs:
* [`FileOpenPicker`](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Pickers.FileOpenPicker) to open an existing file.
* [`FileSavePicker`](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker) to save a new file.
* [`FolderPicker`](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker) to choose a folder to open / save additional files from.

Using these APIs allows the user to choose a location that works best for them, such as a cloud-synced account (eg, OneDrive). Once the user has picked a file or folder using these APIs, your app can get ongoing access to the location by using the [`FutureAccessList`](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions.futureaccesslist) API. This API allows your app to access the files or folders in the future *without* asking the user to pick them again.

In cases where existing workflows assume files will be in the **Documents** folder (eg, interop with an existing Desktop application) or where you do not want the user to have to choose the location, you can declare the `documentsLibrary` capability for your application. If you use the `documentsLibrary` for your application, it is recommended that you also allow the user to pick locations manually.

The `documentsLibrary` capability must include the `uap` namespace when you declare it in your app's package manifest as shown below.

    <Capabilities><uap:Capability Name="documentsLibrary"/></Capabilities>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback and suggestions! I updated the description for the documentsLibrary capability and published the updates in the [live article](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations).
