### ISSUE TITLE
Doc bug: The itemsource link for TreeView is broken

### ISSUE THREAD

**Issue by predavid-zz** [MicrosoftDocs/windows-uwp#1352]
This link seems broken. Please fix.

https://github.com/MicrosoftDocs/windows-uwp/blob/docs/uwp/api/windows.ui.xaml.controls.treeview.itemssource

**Comment by ginami** [comment]
Hi @predavid -- thanks for letting us know! On which page does this link appear?

**Comment by mijacobs** [comment]
@predavid Can you add a link  to the page and then reopen the issue?
