### ISSUE TITLE
First code example doesn't work

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1353]
There's no `NavigationStrategy` property on this class:

```
    var options = new FindNextElementOptions ()
    {
        SearchRoot = TicTacToeGrid,
        NavigationStrategy = NavigationStrategyMode.Heuristic
    };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8acece5-c4d8-8247-49ad-93317d0de2d5
* Version Independent ID: ebe3f26a-5bda-296f-237d-477145eab671
* Content: [Programmatic focus navigation with keyboard, gamepad, and accessibility tools - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/focus-navigation-programmatic)
* Content Source: [windows-apps-src/design/input/focus-navigation-programmatic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/focus-navigation-programmatic.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by chigy** [comment]
@marb2000

**Comment by chigy** [comment]
@marb2000

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @michael-hawker - snippet has been fixed.
