### ISSUE TITLE
Desktop x86 / x64 Mixup

### ISSUE THREAD

**Issue by mthomason** [MicrosoftDocs/windows-uwp#1354]
It says Desktop x64 can run on x86 machines.  Says that x86 can not run on x64 machines.  Doesn't seem correct to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2975459d-0a61-a9ac-02be-5a1191254165
* Version Independent ID: 453681de-7ac5-c469-31c9-afabf4c8a930
* Content: [App package architectures - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/device-architecture)
* Content Source: [windows-apps-src/packaging/device-architecture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/device-architecture.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. If you're referring to the "Windows 10 devices and architectures" table, I think you might be misinterpreting the table. The first column is the index to the table, and it lists the different types of native architectures you can build against for UWP apps. This table basically says that a UWP app built against the x86 architecture can run on x86 and x64 versions of desktop Windows, but a UWP app built against the x64 architecture can only run on x64 versions of desktop Windows. The "x86" and "x64" sections below the table explain this in more detail. 

I hope this helps! If I have misunderstood your feedback, please reopen this issue.
