### ISSUE TITLE
Common Excepiton handling should be removed

### ISSUE THREAD

**Issue by jinek** [MicrosoftDocs/windows-uwp#136]
Comment inside is not true. A lot of exceptions not related to file can come here. Actually any exception can be received if default task factory was reimplemented

`   catch (Exception)
   {
      // Timestamp not found
   }`
Also was discussed here https://github.com/MicrosoftDocs/windows-uwp/issues/20

**Comment by jillre** [comment]
Hi @jinek - Thanks for filing this issue. Could you please tell me the URL where you see this exception and the comment? Thanks! -Jill

**Comment by jinek** [comment]
@jillre I think is was https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.ApplicationData

**Comment by laurenhughes** [comment]
@jinek I fixed the C# exception, the update should be available tomorrow. The C++, VB, and JavaScript samples are a work in progress and should be updated soon.

Thanks for filing the issue!
