### ISSUE TITLE
Missing / in self closing xaml tag

### ISSUE THREAD

**Issue by mhoelzel142** [MicrosoftDocs/windows-uwp#1360]
Under the "Create a menu bar" section in the code sample, the &lt;MenuFlyoutItem Text="Save"/&gt; is missing the forward slash to make it a self-closing tag.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd894ab6-9b28-956f-fd00-3d60de336045
* Version Independent ID: 5f80b19f-f8a7-4d66-bd46-2ba165f68c0f
* Content: [Menus and context menus - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus)
* Content Source: [windows-apps-src/design/controls-and-patterns/menus.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/menus.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@mhoelzel142, thanks for bringing this to our attention. It's fixed now.
