### ISSUE TITLE
Link broken 

### ISSUE THREAD

**Issue by matthew65536** [MicrosoftDocs/windows-uwp#1363]
Even though the issue is claimed to be "fixed" i still can't get my Xbox one s activated for dev mode. Seriously Microsoft you are better then this, get your stuff working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc064e49-5f24-ff80-d511-7f1947fc39da
* Version Independent ID: b8ad47c2-8264-c232-167f-b9ee69d6dce1
* Content: [Xbox One Developer Mode activation - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation#activate-developer-mode-on-your-retail-xbox-one-console)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mtoepke** [comment]
Thanks for your report.

The https://partner.microsoft.com/en-us/xboxconfig/devices link is the correct link and should be working. Make sure you are logged into Partner Center with a valid, registered app developer account.

Here are some more detailed steps we've added to the docs (particularly Step 6, to verify you are logged in with the correct account type):

5. [Register an app developer account in Partner Center](https://developer.microsoft.com/store/register).  This is also the first step towards publishing your game.

6. Sign in to [Partner Center](https://partner.microsoft.com/dashboard) with your valid, current Partner Center app developer account.  If you don't see multiple options in the left hand navigation pane, or don't see the **Create a new app** option in the **Overview** section, the following steps and activation links _will not work_; make sure you fully registered your app developer account from the previous step.

7. Go to [partner.microsoft.com/xboxconfig/devices](https://partner.microsoft.com/xboxconfig/devices).

If these steps don't work for you, please let us know.

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No follow-up from OP.
