### ISSUE TITLE
link is down

### ISSUE THREAD

**Issue by HppZ** [MicrosoftDocs/windows-uwp#1367]
"Windows Developer Platform features"
https://developer.microsoft.com/en-us/windows/platform/features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29449c0-035d-483b-d92e-fce0351fb9e5
* Version Independent ID: 5642c637-bf8b-cf70-7b41-8ca20a56d327
* Content: [What's New in Windows 10 for Developers, Tools & Features - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-17134)
* Content Source: [windows-apps-src/whats-new/windows-10-build-17134.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-17134.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by HppZ** [comment]
@mijacobs

**Comment by QuinnRadich** [comment]
Thanks for the heads-up (and sorry for a slight delay in the response). It seems like this handy link is no more, so I'll make haste in removing it.
