### ISSUE TITLE
Error in parsing the app package

### ISSUE THREAD

**Issue by KSib** [MicrosoftDocs/windows-uwp#1369]
I'm getting the following message when double-clicking the .appinstaller from a UNC path: "Error in parsing the app package." It works just fine if I create an app package to my desktop. It will also auto-update when installed via .appinstaller from my desktop. What could be the problem? There's no errors in the event log where this document says to check. The project is signed with a .pfx that's also installed to the current machine. I tried editing the .appinstaller file to change the slash directions, change the file:/// to \\\\ but nothing seems to work.

Windows 10 Enterprise Version 1803 (Build 17134.472)
Visual Studio 2017 (15.9.5)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c40c14-add5-56b5-2138-ed0805268b94
* Version Independent ID: faf5d307-7af4-27f7-2ce8-5745a2a57605
* Content: [Troubleshoot installation issues with the App Installer file - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/troubleshoot-appinstaller-issues)
* Content Source: [windows-apps-src/packaging/troubleshoot-appinstaller-issues.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/troubleshoot-appinstaller-issues.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're encountering this issue. The following threads are about the same error and have some suggestions in them:

- [https://github.com/MicrosoftDocs/windows-uwp/issues/609](https://github.com/MicrosoftDocs/windows-uwp/issues/609) (see the last several comments)
- [https://stackoverflow.com/questions/50485153/uwp-appinstaller-error-in-parsing-the-app-package](https://stackoverflow.com/questions/50485153/uwp-appinstaller-error-in-parsing-the-app-package)

Unfortunately, this docs repo is not a support channel. If the threads above don't help you resolve the issue, please see [this page](https://developer.microsoft.com/en-us/windows/support) for your support options. You might also try posting your question on our [MSIX and packaging](https://techcommunity.microsoft.com/t5/MSIX/ct-p/MSIX) forums.
