### ISSUE TITLE
Images disappearing in dark theme

### ISSUE THREAD

**Issue by ad1Dima** [MicrosoftDocs/windows-uwp#137]
In article ['Icons for UWP apps'](https://docs.microsoft.com/en-us/windows/uwp/style/icons) there are transparent images with black stroke. So they are invisible in dark theme.

**Comment by mattwojo** [comment]
Looks like this is still an issue as of 7/20/17

**Comment by mijacobs** [comment]
The article is being revised; the new version will fix the image issues.

**Comment by mijacobs** [comment]
The fix is live.
