### ISSUE TITLE
Make Selector class constructor public

### ISSUE THREAD

**Issue by mdmozibur** [MicrosoftDocs/windows-uwp#1370]
`Selector` - the base class for `ComboBox` and other `ItemsControl` with single selection mode,  has a contructor that's not public. As a result, it's being difficult or Impossible to create an `ItemsControl` that has only Single selection mode like `ComboBox`.

**Comment by ginami** [comment]
Hi @MuziburRahman -- thank you for your feedback. This list is specifically for documentation issues--are you asking to have a doc on this topic updated? If so, could you please let me know the URL for the doc? Thank you!

**Comment by mdmozibur** [comment]
Hi @ginami , of course, here is the `Selector` page: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Primitives.Selector
Thanks.

**Comment by YuliKl** [comment]
@MuziburRahman - Thank you for your suggestion. This isn't a documentation issue and feels like a feature request that belongs in the [Microsoft-ui-xaml](https://github.com/Microsoft/microsoft-ui-xaml) GitHub. Can you re-open your request there using one of our [issue tempaltes](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose)?
