### ISSUE TITLE
Ability to Embed UWP inside Desktop Application?

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/windows-uwp#1373]
Ability to Embed UWP inside Desktop Application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e5b22d-e803-5c0a-3e82-d08f59919ac5
* Version Independent ID: 85cb8283-4d80-b519-a03b-f3efab4f6d75
* Content: [UWP controls in desktop applications - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls)
* Content Source: [windows-apps-src/xaml-platform/xaml-host-controls.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/xaml-host-controls.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. This article provides an overview about the currently supported ways to host UWP controls in desktop (Windows Forms, WPF, and native Win32) applications. Unfortunately, it isn't clear from your comment whether you are asking a question about this feature, leaving feedback on the documentation, or something else. If you are leaving feedback on the documentation, please reopen this issue with more details. Thanks!
