### ISSUE TITLE
Provide examples for theme

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1376]
No examples of possible values for theme are given.  I believe they should be like `theme-light` and `theme-dark`.  Similar for contrast, but it's used in other examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f1d5c-9079-14c5-cbdf-20c7f067b3e5
* Version Independent ID: 0e8fb0fd-1330-c826-cb02-871aa1f3e473
* Content: [Tailor your resources for language, scale, high contrast, and other qualifiers - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/tailor-resources-lang-scale-contrast)
* Content Source: [windows-apps-src/app-resources/tailor-resources-lang-scale-contrast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/tailor-resources-lang-scale-contrast.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. I see updates have been made to the documentation since. Marking this as Closed.
