### ISSUE TITLE
Overlapped scope?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1377]
This document about loading images covers some of the material in [tailor resources](https://docs.microsoft.com/en-us/windows/uwp/app-resources/tailor-resources-lang-scale-contrast), I was looking for the latter, but found this one from search first (keyword loading).

It'd be nice to either better isolate the scopes of these two articles, or better highlight the other article with a link in the article above about the available properties and their values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff6b0a7-5664-e52b-c378-cd038aae2da5
* Version Independent ID: d5985816-e894-6950-cd67-ee2433efc5db
* Content: [Load images and assets tailored for scale, theme, high contrast, and others - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/images-tailored-for-scale-theme-contrast)
* Content Source: [windows-apps-src/app-resources/images-tailored-for-scale-theme-contrast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/images-tailored-for-scale-theme-contrast.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
The titles do seem to be lengthy and could use some enhancements. Will create an internal work item to drive that to completion. Due to staleness, I'll mark this as closed but will follow up in this thread when updates have been made.
