### ISSUE TITLE
Does conditional XAML not work for attached properties?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1378]
There's no mention/examples of attached properties here.  Are they supposed to be supported?  I'm seeing a `The XAML Binary Format (XBF) generator reported syntax error '0x09cc'` in VS trying to do it intuitively as `contract6Present:AutomationProperties.HeadingLevel="Level2"` but not sure if there's some other syntax for attached with `()` I'm supposed to use like in other binding type expressions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4adf9e3-46b9-732a-7659-07d34a9ff469
* Version Independent ID: 0dd55994-fed9-6d25-38c8-85e1ee2322ff
* Content: [Conditional XAML - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml)
* Content Source: [windows-apps-src/debug-test-perf/conditional-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/conditional-xaml.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by bezysoftware** [comment]
I'm seeing the exact same error for this code:

```
                            <Windows10version1809:Grid.BackgroundTransition>
                                <Windows10version1809:BrushTransition />
                            </Windows10version1809:Grid.BackgroundTransition>
```

Weirdly it only happens in a class lib, not in the app project

**Comment by jevansaks** [comment]
Sounds like you're reporting a product bug. Can you open the issue on https://github.com/Microsoft/microsoft-ui-xaml ?
