### ISSUE TITLE
Formatting issues in "windows-apps-src/input-and-devices/speech-recognition.md"

### ISSUE THREAD

**Issue by theel0ja** [MicrosoftDocs/windows-uwp#138]
https://docs.microsoft.com/en-us/windows/uwp/input-and-devices/speech-recognition

![image](https://user-images.githubusercontent.com/5832930/27909922-99d7f100-625b-11e7-9421-ed57b0b8f83d.png)

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for letting us know about the formatting issues in this topic. I've fixed the problem and the updated topic should be live soon.
