### ISSUE TITLE
Should show grabbing the 'SelectedTime' Property in Example

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1380]
I had to dig through the properties to find out how to grab the value from the control.  The sample should show retrieving the `SelectedTime` property from the control to make use of what the user has picked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ee0213d-5c88-91c6-f798-b958afa967f6
* Version Independent ID: ad70d5cc-b447-2ecd-08d5-04391b96043b
* Content: [Time picker - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/time-picker)
* Content Source: [windows-apps-src/design/controls-and-patterns/time-picker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/time-picker.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. The time picker doc has been updated with more information and examples.

**Comment by michael-hawker** [comment]
Thanks @jwmsft. Just for my knowledge, do these changes get done elsewhere other than GitHub? I never seem to see PRs or commits referencing the original issue when they're getting closed.
