### ISSUE TITLE
Custom ContentLinkProvider

### ISSUE THREAD

**Issue by al-n** [MicrosoftDocs/windows-uwp#1381]
Is there any info available for implementing a custom ContentLinkProvider for e.g. hashtags for categorizing items?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0863d9c0-9b9a-c111-74a5-8fcd04b31671
* Version Independent ID: 0fa5a148-a608-8b07-6a81-339f7a594597
* Content: [Content links in text controls - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/content-links)
* Content Source: [windows-apps-src/design/controls-and-patterns/content-links.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/content-links.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by al-n** [comment]
Any news on this?

**Comment by jevansaks** [comment]
@marb2000 this is your area.

**Comment by marb2000** [comment]
No, there is no plan for allowing creating Custom ContentLinkProvider. We are planning to deprecated this feature indeed.

**Comment by al-n** [comment]
No surprise after a year of nothingness...
