### ISSUE TITLE
The name XXX does not exist in the namespace ZZZ

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftDocs/windows-uwp#1385]
I am doing exactly as described in the article, but I always get the same general error message as above. For example
&lt;Page x:Class="KnO.Views.FoldersView"
...
xmlns:uc="using:KnO.UserControls" 
… &gt;

&lt;uc:TrailUserControl x:Name="TrailUserControl1"/&gt;

and then inside a grid I am trying to use a control that I am sure was correctly created in the namespace KnO.UserControls

Everything was working just fine for an older version of the project was targeting Windows 8.1. I am migrating to Windows 10 now and I am stuck with this issue. 

I did find some stackoverflow content about this issue, but all the proposed solutions, like deleting .vs folder, clean rebuild, etc didn't solve the issue. 

I am wondering if this could be a documented issue and I could get a link to  good article explaining what is the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faca33d5-5081-bef7-549e-490edaa0eaff
* Version Independent ID: b563b169-7e24-6857-6b4f-303adc8742ad
* Content: [XAML namespaces and namespace mapping - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-namespaces-and-namespace-mapping)
* Content Source: [windows-apps-src/xaml-platform/xaml-namespaces-and-namespace-mapping.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/xaml-namespaces-and-namespace-mapping.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
@NFGodoy - how are you calling the control inside the grid? Can you provide that code snippet?

Sounds like TrailUserControl1 is resolving correctly, is that right? Are you also using the uc: namespace inside the grid? (Is the grid you mentioned the direct child control inside Page?)

**Comment by NFGodoy** [comment]
Hi Yulia,

I don't think there is an error with the XAML because it was working fine when I was using Visual Studio 2015 and the project was targeting Windows 8.1
I could not automatically open the older project with VS 2017 and get it converted, so I started a new project and copied the files into it. I have a suspicion that there is something wrong with my installation of VS 2017. I will do an update and see what happens. Hopefully the problem could be gone after that. I will tell you the result later.

Thanks. 
--------------------------------------------
On Sat, 19/1/19, Yulia <notifications@github.com> wrote:

 Subject: Re: [MicrosoftDocs/windows-uwp] The name XXX does not exist in the namespace ZZZ (#1385)
 To: "MicrosoftDocs/windows-uwp" <windows-uwp@noreply.github.com>
 Cc: "NFGodoy" <nfdegodoy@yahoo.com.au>, "Mention" <mention@noreply.github.com>
 Received: Saturday, 19 January, 2019, 6:54 AM
 
 @NFGodoy - how are you
 calling the control inside the grid? Can you provide that
 code snippet?
 Sounds like TrailUserControl1 is resolving correctly, is
 that right? Are you also using the uc: namespace inside the
 grid? (Is the grid you mentioned the direct child control
 inside Page?)
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by NFGodoy** [comment]
Hi Julia,

Sorry for the delay. I was on holidays. Just returned.
As suspected after an update of VS 2017, which took more than 4 hours to complete, I just opened the project and those error messages are gone. I do have quite a lot to do to make the old Windows 8.1 app work properly with Windows 10 because it depends heavily on the Live api to talk to OneDrive which has been deprecated. So the solution can't be build successfully yet, but that nasty complain about the several user controls that could not be found is gone. 
Thanks.

**Comment by YuliKl** [comment]
Good to hear that you've made some progress. If you run into Xaml issues during your upgrade process, don't hesitate to let us know through the [Microsoft-UI-Xaml GitHub](https://github.com/Microsoft/microsoft-ui-xaml) page.
