### ISSUE TITLE
NavigationView doc: Settings item not always showing in correct position

### ISSUE THREAD

**Issue by YuliKl** [MicrosoftDocs/windows-uwp#1386]
NavigationView was update to always show Settings (the gear icon) as the last (bottom-most or right-most) item in NavigationView's pane. Images in this doc need to be updated to show correct order with PaneFooter content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#anatomy)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This issue is tracked with an internal work item.
