### ISSUE TITLE
Population of Layers after layer creation

### ISSUE THREAD

**Issue by gmgallo** [MicrosoftDocs/windows-uwp#1388]
In the example above, the layer is populated with:
var MyElements = new List&lt;MapElement&gt;();
If you add more elements to this collection they are ignored by the layer. To add or remove elements after layer creation replace List&lt;MapElement&gt;() with
IList&lt;MapElement&gt; MyElements = new ObservableCollection&lt;MapElement&gt;();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64118ca-f5a1-1172-8eb4-85938f2a8bed
* Version Independent ID: 105d3b3d-2e83-cae9-6977-0fe28925b03c
* Content: [Display points of interest (POI) on a map - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/display-poi#layers)
* Content Source: [windows-apps-src/maps-and-location/display-poi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/maps-and-location/display-poi.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The list of landmarks in this example is static, so the use of a simple List<MapElement> is correct. Your observation that for dynamic updates, an ObservableCollection<T> is appropriate. This is also demonstrated in the example for the LandmarkLayer collection, which is an ObservableCollection<MapLayer> object.
