### ISSUE TITLE
Example URIs display with HTML subscript

### ISSUE THREAD

**Issue by AdamWhitcombCAS** [MicrosoftDocs/windows-uwp#1390]
A few of the examples in the "Display known locations" and "Display multiple points" sections display part of the URIs within subscript tags.  I suspect it is replacing pairs of tildes with sub tags.

eg: Displays a pushpin named Caesars Palace and a pushpin named The Bellagio in Las Vegas and zooms to level 16.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00d038cd-707d-56ac-2621-b7d8125add0c
* Version Independent ID: ae3358cd-15fe-4457-9ef3-e28ef9a16bd9
* Content: [Launch the Windows Maps app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-maps-app#display-known-locations)
* Content Source: [windows-apps-src/launch-resume/launch-maps-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-maps-app.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by GrantMeStrength** [comment]
It looks like these have been repaired. Thanks for reporting it (all that time ago!) -John
