### ISSUE TITLE
Trial version selected in store submission but user can only buy

### ISSUE THREAD

**Issue by made1990** [MicrosoftDocs/windows-uwp#1395]
Hi folks,
I submitted an app to the store with a free trial version (for 30 days) but store users can't select trial version in app store, only can buy it.
What is the reason for that?

By the way - When I look on my submission the trial version section is greyed out and the time limit is set to only 1 day  although I submitted with 30 days.

**Comment by ginami** [comment]
Hi @made1990 -- sorry that you're experiencing this problem! Unfortunately this list is specifically for issues with our docs. Please see our forums and support options at https://developer.microsoft.com/en-us/windows/support. Thank you.
