### ISSUE TITLE
Add information on how to cancel direct manipulation after scrolling begins on a scrolling view

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/windows-uwp#1396]
Based on this MSDN thread: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/6d9abdb1-5d8c-4030-acfd-9a36ae6d3217/uwp-only-the-manipulationstarting-events-fire?forum=wpdevelop , it has been suggested that this document needs to be updated to draw attention to the new APIs for UWP UIElements to cancel direct manipulation of touch events. I cannot edit this document myself as I do not have permission. Here is a proposal for a paragraph to add to the "Routed events" section of this doc:

>If it is necessary to handle `PointerMoved` or other events on a `UIElement` when that element is in a scrollable view, e.g. `ScrollViewer` or `ListView`, then you will need to cancel the scrolling views direct manipulation, e.g. call `UIElement.CancelDirectmanipulation()`, when you want to start handling those events. When done, call `UIElement.TryStartDirectManipulation(Pointer value)` so the scrolling view can resume direct manipulation. See the documentation for [**CancelDirectmanipulation**](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.canceldirectmanipulations) and [**TryStartDirectManipulation**](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.trystartdirectmanipulation) for more details.

In addition it might be worth linking to the "Routed events" section of this document from the API docs for all scrolling controls that use direct manipulation, e.g.:
ScrollViewer and ScrollBar:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/scroll-controls

ListView, GridView, ComboBox:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/lists

ListBox:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listbox

FlipView:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.flipview

TreeView:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f7bde32-5114-a453-1e17-a858fa3276fc
* Version Independent ID: f3979786-383e-2f65-c5a4-19eca5d5bca4
* Content: [Touch interactions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/touch-interactions)
* Content Source: [windows-apps-src/design/input/touch-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/touch-interactions.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @jgold6. The suggested topics have all been updated.
