### ISSUE TITLE
UWP Sample code project does not build in VS2017

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/windows-uwp#1401]
Followed your this [Get UWP Samples tutorial](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-uwp-app-samples). Opened the `CustomEditControl` sample project in `VS2017`. But when I run the project by clicking `F5`, I get the error shown in the image below. I then followed the instructions from the error message to Deploy the project as `Build-->Deploy Solution` and got the `Deploy: 0 succeeded, 1 failed, 0 skipped` in the output window of `VS2017` but nothing in the error list to be able to see the reasons for failure. The last section of `READ.md` file of the sample folder gives the instructions as follows [that I did followed as explained above]:

```
## Run the sample

The next steps depend on whether you just want to deploy the sample or you want to both deploy and run it.

### Deploying the sample

- Select Build > Deploy Solution. 

### Deploying and running the sample

- To debug the sample and then run it, press F5 or select Debug >  Start Debugging. To run the sample without debugging, press Ctrl+F5 or selectDebug > Start Without Debugging. 

```
**Error**:

![untitled1](https://user-images.githubusercontent.com/10931726/51511998-9a8fda80-1dd1-11e9-9e81-afe009acf622.png)

Please help

**Comment by stefffdev** [comment]
See https://stackoverflow.com/questions/42016155/visual-studio-the-project-needs-to-be-deployed-before-it-can-be-started/42020537
Maybe that's the problem.

**Comment by YuliKl** [comment]
I would double-check that your computer is in developer mode (Settings app > Update & Security > For developers). May be worth adding this step to the documentation.

**Comment by QuinnRadich** [comment]
I'd recommend that you check both the proposed solutions to this, yes. If neither of them can resolve your issue, then let me know, and I'll investigate this further.

Thank you.

**Comment by saf-itpro** [comment]
[This ](https://github.com/Microsoft/Xaml-Controls-Gallery/issues/36)solution from @stmoy resolved the issue. Many thanks to `@stmoy`
