### ISSUE TITLE
Interact with mail app using URI.

### ISSUE THREAD

**Issue by czhang03** [MicrosoftDocs/windows-uwp#1403]
For example when trying to create an event or send an email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98f38c4-4a00-19b4-e813-bee6ffe03a9b
* Version Independent ID: 9a9770aa-8255-eeb8-7351-63b6ec712ada
* Content: [Launch an app with a URI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-app-with-uri)
* Content Source: [windows-apps-src/launch-resume/launch-app-with-uri.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-app-with-uri.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by GrantMeStrength** [comment]
Thanks for the comment, and sorry for the delay in addressing it. We do read bugs as they come in, but may not add comments immediately, which gives a poor impression - I apologize.

In this case, your comment wasn't immediately clear and so it wasn't assigned to an owner for them to address. Is there a specific problem with the docs we can fix?  thank you

 -John

**Comment by GrantMeStrength** [comment]
In the meantime, here is a link that might help: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app

Please reopen the bug is something else is required. thanks!
