### ISSUE TITLE
await error

### ISSUE THREAD

**Issue by MazenAlBezreh** [MicrosoftDocs/windows-uwp#1406]
Hi,
I did the mentioned example bu i got this error message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS4033	The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.	HelloWorld	F:\MazeN\source\repos\HelloWorld\HelloWorld\MainPage.xaml.cs	34	Active

Please help me to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by stefffdev** [comment]
You probably forgot the "async" keyword on your button click event:

private *async* void Button_Click(object sender, RoutedEventArgs e)

**Comment by MazenAlBezreh** [comment]
You're right, thanks a lot. it's working now

**Comment by stefffdev** [comment]
I think you should close the issue if your problem is solved! 👍

**Comment by QuinnRadich** [comment]
Thanks, stefffdev!

Closing this issue, as the problem has been resolved.
