### ISSUE TITLE
Event Handler

### ISSUE THREAD

**Issue by jawineh** [MicrosoftDocs/windows-uwp#1408]
After selecting 'button' and pressing F4 properties does not have the event button let alone a drop down. Boxes of Categorized, Alphabetical and Pages also contain nothing. Thus impossible to work on "Event Handlers".

**Comment by ginami** [comment]
Hi @jawineh -- are you referring to the instructions in a specific article? If so, can you please provide the URL? This will help me route your feedback to the appropriate author. Thank you!

**Comment by jawineh** [comment]
Hi Gina,
After the post I checked Tools and realised that the ' xaml designer' had not been enabled. Have corrected it and now the class elements and siblings are available in properties. Will keep in touch in case further difficulties. thanks.
