### ISSUE TITLE
Correct handling of non-supported OSs

### ISSUE THREAD

**Issue by toredk** [MicrosoftDocs/windows-uwp#1412]
Any recommendation on how to get handle non-supported operating systems?

The Wix installer code above results in a warning dialog with the text "Warning 1946. Property 'System.AppUserModel.ToastActivatior.CLSID' for shortcut 'My Application.lnk' could not be set.

In code I check against Environment.OSVersion.Version before triggering Toast Notifications, but there might be a more elegant solution.

Some Toast Notification features, e.g. progress is not supported on older Windows 10 versions. Any suggestions on how to handle this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53415734-dd31-7cf0-a82e-02566ed82396
* Version Independent ID: e5f82c08-6c9f-c628-9a45-5df000239ae4
* Content: [Send a local toast notification from desktop C# apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Adding @andrewleader

**Comment by andrewleader** [comment]
Checking OS version as you're doing works. After you know it's Windows 10, if you specifically want to check if progress bar is supported (since that was added in a later release of Windows 10), our progress bar code sample shows how you would check that: https://github.com/WindowsNotifications/quickstart-toast-progress-bar/blob/master/cs/QuickstartToastProgressBar/MainPage.xaml.cs#L94

```csharp
        private static bool? _isProgressBarSupported;
        private static bool IsProgressBarSupported()
        {
            if (_isProgressBarSupported == null)
            {
                // Progress bar only supported in RS2, only on Desktop
                _isProgressBarSupported = ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 4)
                    && (AnalyticsInfo.VersionInfo.DeviceFamily.Equals("Windows.Desktop"));
            }

            return _isProgressBarSupported.Value;
        }
```

**Comment by toredk** [comment]
Thank you for the code snippet and the link to the quick start examples.

What about my main question about the wix handling? I'll need to support Windows 7+8+10 so at least for Windows 7 I need to avoid the mentioned warning message box. I am not sure if Windows 8/8.1 supports notifications at all.

Btw. what is the difference in using AnalyticsInfo.VersionInfo.DeviceFamilyVersion or Environment.OSVersion.Version?

**Comment by toredk** [comment]
I managed to get around the installer warning on Windows 7 by specifying "{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}, 26" as key for the wix ShortCutProperty instead of "System.AppUserModel.ToastActivatorCLSID". This still works on Windows 10 and does not produce a warning on Windows 7.

**Comment by andrewleader** [comment]
Thanks toredk, good to know that GUID allows it to not throw warnings on Windows 7!

As for the difference between AnalyticsInfo and Environment version, you'll have to reach out to the API owners of those APIs. Try posting a question on https://docs.microsoft.com/en-us/uwp/api/Windows.System.Profile.AnalyticsVersionInfo

**Comment by toredk** [comment]
Thank you. I'll just use Environment unless I find a reason not to.
