### ISSUE TITLE
Content Repeat

### ISSUE THREAD

**Issue by amandeepmonga** [MicrosoftDocs/windows-uwp#1413]
The below para is repeated twice on this pagehttps://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation

"Title bar customizations will carry over to both the app tab and the system back bar. If your app specifies background and foreground color properties with ApplicationViewTitleBar, then the colors will be applied to the tab and system back bar."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab5201c-d8c8-1804-a225-4420f66d77ea
* Version Independent ID: 2d217eac-b2cd-553a-970f-32bb043fc353
* Content: [Navigation history and backwards navigation (Windows apps) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thank you, I just fixed the issue. The updated page will be live shortly.
