### ISSUE TITLE
`Hub` page has gone missing

### ISSUE THREAD

**Issue by bdbai** [MicrosoftDocs/windows-uwp#1414]
When I followed the link `Hub control/pattern` ( https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/hub ) in [`Windows.UI.Xaml.Controls.Hub`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.hub) , I was redirected here. The `Hub control/pattern` page is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1426ac-9a20-b0a3-0ebd-8ce4b2a50882
* Version Independent ID: 771f2efb-f781-ed49-5ff0-5c95f2bc4868
* Content: [Navigation basics for UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-basics#feedback)
* Content Source: [windows-apps-src/design/basics/navigation-basics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-basics.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @bdbai, we don't recommend using the hub control in most cases, so we've retired the hub overview article. I'll update the API reference page to remove the link. Adding @chigy  for awareness.
