### ISSUE TITLE
CancellationPropagatorAsync sample code is wrong

### ISSUE THREAD

**Issue by devhawk** [MicrosoftDocs/windows-uwp#1415]
CancellationPropagatorAsync should capture the nested_coroutine by value (e.g. use = instead of &).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a087153a-b34a-b9fc-0ba6-e96d14764455
* Version Independent ID: 4db9d519-6a9d-a8f9-bd58-f67b32cd8548
* Content: [Concurrency and asynchronous operations with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency#canceling-an-asychronous-operation-and-cancellation-callbacks)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, Harry, I just hit "Complete" on the PR for this fix; I expect it to be live within 24 hours. I'll close this issue optimistically, but we can always re-open it if necessary. ~Steve
