### ISSUE TITLE
Many important variable initializiations are not shown in the code examples

### ISSUE THREAD

**Issue by MegaMech** [MicrosoftDocs/windows-uwp#1419]
For example: "selectedCharacteristic", "characteristic.", and "service." Are important but it doesn't show where they come from.
This makes it confusing for people trying to use the API. It's like is it a misspelling? Or did they purposely leave out this important detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f89409a-b108-603f-9279-c59f5ae5d188
* Version Independent ID: 5bd07919-59ac-4fca-b997-a472ae24bfb1
* Content: [Bluetooth GATT Client - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @MegaMech. I've added a link to a complete sample rather than try to add the declarations/initializations to the snippets. We try to keep the snippets concise and to the point of the detail trying to be demo'd.
