### ISSUE TITLE
Is this really working?

### ISSUE THREAD

**Issue by johanlindfors** [MicrosoftDocs/windows-uwp#1420]
I have tried to follow the steps above with Visual Studio 2017 15.9.6 and even Windows 10 SDK 18317 but can't get the solution to compile.

Here follows the build output:

1&gt;------ Build started: Project: BgLabelControlApp, Configuration: Debug Win32 ------
1&gt;XamlTypeInfo.g.cpp
1&gt;d:\repos\temp\bglabelcontrolapp\bglabelcontrolapp\generated files\xamltypeinfo.g.cpp(146): error C2039: 'BgLabelControl': is not a member of 'winrt::BgLabelControlApp::implementation'
1&gt;d:\repos\temp\bglabelcontrolapp\bglabelcontrolapp\generated files\xamltypeinfo.g.cpp(20): note: see declaration of 'winrt::BgLabelControlApp::implementation'
1&gt;d:\repos\temp\bglabelcontrolapp\bglabelcontrolapp\generated files\xamltypeinfo.g.cpp(146): error C2275: 'winrt::BgLabelControlApp::BgLabelControl': illegal use of this type as an expression
1&gt;d:\repos\temp\bglabelcontrolapp\bglabelcontrolapp\generated files\winrt\impl\bglabelcontrolapp.2.h(21): note: see declaration of 'winrt::BgLabelControlApp::BgLabelControl'
1&gt;d:\repos\temp\bglabelcontrolapp\bglabelcontrolapp\generated files\xamltypeinfo.g.cpp(168): error C2440: 'initializing': cannot convert from 'overloaded-function' to 'winrt::Windows::Foundation::IInspectable (__cdecl *)(void)'
1&gt;d:\repos\temp\bglabelcontrolapp\bglabelcontrolapp\generated files\xamltypeinfo.g.cpp(168): note: None of the functions with this name in scope match the target type
1&gt;Done building project "BgLabelControlApp.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Shared a sample solution implemented as specified above here: https://github.com/coderox/BgLabelControlApp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a44d893-2ad9-830f-a4d8-908e725432e1
* Version Independent ID: 81a91de0-9c13-7d3a-c680-b45370be492e
* Content: [XAML custom (templated) controls with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by johanlindfors** [comment]
So the issue I was having was that I tried building the project before I added an instance of the control to the MainPage.xaml (and the MainPage.h) and then the compiler complained as above. However adding an #include "BgLabelControl.h" to the pch.h solves that as well. I guess this means that if I want to create this custom component in a separate compilation unit I need to add the inclusion of the header into the precompiled header. Maybe that should be added to this documentation in a note or similar?

**Comment by stevewhims** [comment]
Hi, @johanlindfors, yes I will go ahead and add a discussion along these lines to the topic. But, yes, you can either #include in the precompiled header, or else in each compilation unit needing it. I'll leave this issue open until I've updated the topic. Thanks! ~Steve

**Comment by stevewhims** [comment]
So, this topic is now live with the updated info that you suggested, @johanlindfors. I'll go ahead and optimistically close this issue now, but please reopen it if necessary. Thanks for filing the issue! ~Steve

**Comment by ghost** [comment]
I resolved the following C2039 error when using the C++/WinRT VSIX,
'Block': is not a member of 'winrt::AlphabetBlocks::implementation',
by editing the .vcxproj and the .vcproj.filters files and adding my Block class files. This gets the dependencies sorted and the Block files appear in a visual tree in Solution Explorer like that of MainPage.
