### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by srocdocs** [MicrosoftDocs/windows-uwp#1421]
Tried the example program but nothing happens. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d376e5-ada9-78e7-a7c6-028c8acd4e14
* Version Independent ID: 84bb5e64-fd06-7561-eea1-206ababc786f
* Content: [Get started with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @srocdocs, thanks for filing this issue. I just tried the example again and, while it's slow to get started the first time you run it (it is hitting the network), it does run and it outputs a list of blog post titles. I tested the steps in the topic with the latest public versions of Visual Studio, Windows, the Windows SDK, and the C++/WinRT toolset.

Would you mind trying the steps again, perhaps run the app more than once to see whether you get it to respond. Try changing the `rssFeedUri` to a different feed uri in case there's some issue with reaching that particular uri on your system at the time. I'll leave the issue open for a while.

Thanks!
~Steve

**Comment by stevewhims** [comment]
Hi, @srocdocs, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
