### ISSUE TITLE
cabId parameter name

### ISSUE THREAD

**Issue by tonylambert** [MicrosoftDocs/windows-uwp#1428]
I am trying to download crash dumps from the API using the https://manage.devcenter.microsoft.com/v1.0/my/analytics/cabdownload call for a Windows Desktop application. It requires three peices of information from me:

* An OAuth `Bearer` token in the `Authorization` header.
* The target `applicationId` in the query string.
* The ID for the CAB file to download.

From the [documentation](https://docs.microsoft.com/en-us/windows/uwp/monetize/download-the-cab-file-for-an-error-in-your-app#request-parameters) the name of the CAB ID parameter should be `cabId`. Additionally, according to the documentation I need to get the CAB ID from [failuredetails](https://manage.devcenter.microsoft.com/v1.0/my/analytics/failuredetails) API call. According to the [documenatation](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-details-for-an-error-in-your-app#error-detail-values) for `failuredetails` the response should have `cabId` defined and `cabDownloadable` set to `true`. However, when I get a response from the the `failuredetails` API I only see a `cabIdHash` value in the response details and the `cabDownloadable` item is set to `false`. Additionally, the documentation's [example response](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-details-for-an-error-in-your-app#error-detail-values) for that API call shows `cabIdHash` (and not `cabId`) with `cabDownloadable` set to `false`.

When I try to call the https://manage.devcenter.microsoft.com/v1.0/my/analytics/cabdownload API with the parameter named `cabId` I receive a 400 HTTP status code. When I call that API with the parameter named `cabIdHash` I receive a 401 HTTP status code.

Doing some additional spelunking, I used Chrome's dev tools to see what traffic I could see when downloading crash dumps manually from the https://partner.microsoft.com/en-us/dashboard/analytics/reports/desktop/health/details?productId=< product Id >&failureHash=< the-guid-for-a-failure > page the partner sends along the parameter as `cabIdHash` (to a different API, however).

Lastly, the user in partner center has a `Azure AD application` set up with the `Role` of `Manager (Windows)` which I understand to be of sufficent privileges to access and download the crash dumps. The line looks like

Name|Role
--|--
Microsoft Error Reporting API for < Product name > (< GUID-for-the-client-ID >)|Manager (Windows)

In summary. I believe I have sufficent privileges to download CAB files via the API, but I an getting either a 400 or 401 HTTP code from the API. Additionally, the documentation is incorrect as either the parameter name should be `cabIdHash` or the example response on the `failuredetails` needs to be updated and the API itself should return `cabId` in the JSON response instead of `cabIdHash`.

Another item of interest, the [documenation](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/download-the-cab-file-for-a-windows-10-driver-error#request-parameters) for downloading crash dumps for a driver error (that is deprecated according to the documenation) lists `cabIdHash` as the parameter for the API call. Keep in mind that *I am not trying to download crash dumps for a driver*. However, I thought it was worth mentioning that it shows the parameter name to the call to be `cabIdHash`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 873524f1-46a8-b1ef-8942-c83df2308aad
* Version Independent ID: a333fbe3-200f-23ed-df22-48ace485fd35
* Content: [Download the CAB file for an error in your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/download-the-cab-file-for-an-error-in-your-app)
* Content Source: [windows-apps-src/monetize/download-the-cab-file-for-an-error-in-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/download-the-cab-file-for-an-error-in-your-app.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thank you for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.

**Comment by tonylambert** [comment]
That makes sense. I will try one of the other forums you suggested. In the meantime, there is a discrepancy in the documentation that I called out in the original issue posting.

![image](https://user-images.githubusercontent.com/688221/52087035-60af9880-2576-11e9-84b4-00e2879f640a.png)

**Comment by mhopkins-msft** [comment]
Could you share the exact request you sent and the response you got back?

Thanks,
 ~ _Mark_

**Comment by tonylambert** [comment]
This is the GET request that was made:

https://manage.devcenter.microsoft.com/v1.0/my/analytics/desktop/failuredetails?applicationId=15787378977193230827&failureHash=f2dac845-961e-cbe9-6c3f-fba3693d2b54&top=1

(I only needed one entry so I added the optional &top=1 parameter, but even if I remove that I still see cabIdHash instead of cabId for the entire list).

with these headers (Note that < VALID TOKEN > was actually a real OAuth token when I made the API call):

> Host: manage.devcenter.microsoft.com
> Authorization: Bearer < VALID TOKEN >


Response:

```JSON
{
  "Value": [
    {
      "applicationId": "15787378977193230827",
      "failureHash": "f2dac845-961e-cbe9-6c3f-fba3693d2b54",
      "failureName": "FATAL_APP_EXIT_40000015_mfplat.dll!CAsyncResult::_CAsyncResult",
      "date": "2019-01-08 22:26:21",
      "cabIdHash": "5a027f8a-5908-44e1-8c61-1331144a0ecb",
      "cabType": "Mini",
      "cabExpirationTime": "2019-03-09 22:26:21",
      "market": "AU",
      "osBuild": "6.1.7601.24308",
      "applicationVersion": "19.1.0.2653",
      "deviceModel": "Dell Inc.-Latitude E5450",
      "osVersion": "Windows 7",
      "osRelease": "Service Pack 1",
      "osArchitecture": "Unknown",
      "deviceType": "Unknown",
      "cabDownloadable": false,
      "fileName": null
    }
  ],
  "@nextLink": "desktop/failuredetails?applicationId=15787378977193230827&failureHash=f2dac845-961e-cbe9-6c3f-fba3693d2b54&startDate=2019-01-01 22:11:20&endDate=2019-01-31 22:11:20&top=1&skip=1",
  "TotalCount": 9
}
```

**Comment by mhopkins-msft** [comment]
Docs have been updated. The engineering team says it is still cabId.

**Comment by rAndom69** [comment]
Ever managed to download CAB ?
Having same issue, with valid service-to-service token created per documentation.

**Comment by tonylambert** [comment]
No. I have been unable to and I have run out of ideas on what to try next.

This fails for me reliably but MS said it isn’t broken. I assume I’m doing
something wrong, but I’ve followed the documentation.

**Comment by rAndom69** [comment]
As I'm in same boat I do blame MS. Well, I'll see what our premium support has to say about this. I'll write result here for reference. Only thing which is not according to documentation is that I'm not global administrator of AAD when I create application account, however assumption is that this is required only for partner center connection to AAD.

**Comment by adammarks** [comment]
Repro'ed this with the following powershell

```
$tenantID=$env:DEV_CENTER_TENANT_ID
$clientID=$env:DEV_CENTER_CLIENT_ID
$clientSecret=$env:DEV_CENTER_CLIENT_SECRET
$appId=$env:DEV_CENTER_APP_ID
$loginString = ("grant_type=client_credentials", "client_id=$clientID", "client_secret=$clientSecret", "resource=https://manage.devcenter.microsoft.com" ) -join "&"
$accessToken = (Invoke-RestMethod -Method POST -Uri "https://login.microsoftonline.com/$tenantID/oauth2/token" -Body $loginString).access_token
$authorizationHeader = @{ "Authorization" = "Bearer $accessToken" }
$startDate = (Get-Date).AddDays(-30).ToString("yyyy-MM-dd")
$endDate = (Get-Date).ToString("yyyy-MM-dd")
$failureHitResponse = 
 Invoke-RestMethod -Method Get -Uri "https://manage.devcenter.microsoft.com/v1.0/my/analytics/desktop/failurehits?applicationId=$appId&aggregationLevel=dateRange&groupby=failureName,failureHash&startDate=$startDate&endDate=$endDate&top=25&skip=1" -Headers $authorizationHeader

write-host "Failure Hit - "
$failureHitResponse.Value[0]

$failureHash = $failureHitResponse.Value[0].failureHash
$failureDetailResponse = 
 Invoke-RestMethod -Method Get -Uri "https://manage.devcenter.microsoft.com/v1.0/my/analytics/desktop/failuredetails?applicationId=$appId&failureHash=$failureHash" -Headers $authorizationHeader

write-host "Failure Detail - "
$failureDetailResponse.Value[0]

# failuredetails REST API doesn't return cabId as the docs indicate, it does return a cabIdHash, so try that
$cabIdHash = $failureDetailResponse.Value[0].cabIdHash
write-host " Cab id HASH is $cabIdHash"

#  Using cabId param to cabDownload API says "Invalid or null value in cabIdHash parameter"
$cabDownloadResponse = 
Invoke-RestMethod -Method Get -Uri "https://manage.devcenter.microsoft.com/v1.0/my/analytics/desktop/cabdownload?applicationId=$appId&cabId=$cabIdHash" -Headers $authorizationHeader
write-host $cabDownloadResponse            

#  Using cabIdHash param to cabDownload API returns a 401
$cabDownloadResponse = 
 Invoke-RestMethod -Method Get -Uri "https://manage.devcenter.microsoft.com/v1.0/my/analytics/desktop/cabdownload?applicationId=$appId&cabIdHash=$cabIdHash" -Headers $authorizationHeader
write-host $cabDownloadResponse            
```

**Comment by adammarks** [comment]
The output from the powershell above shows clearly that -
1. The failuredetails API returns cabIdHash instead of cabId.  In addition there is another field returned that is not mentioned in the docs,  filename.   
2. The cabdownload API doesn't take a cabId parameter and if you use a cabIdHash parameter instead using the cabIdHash from the failuredetails API you will get a 401

**Comment by adammarks** [comment]
I'm noticing that we wrote this issue up against the UWP doc pages for these APIs whereas we are seeing a problem with the desktop versions of these APIs.   The Desktop pages for these apis more accurately describe what we are seeing( with the failuredetails API returning cabIdHash ) and we are using a desktop application but we still are getting a 401 error for the cabdownload api when providing the cabIdHash.

The desktop failuredetails API documentation page
https://docs.microsoft.com/en-us/windows/uwp/monetize/get-details-for-an-error-in-your-desktop-application

The desktop cabdownload API documentation page
https://docs.microsoft.com/en-us/windows/uwp/monetize/download-the-cab-file-for-an-error-in-your-desktop-application

**Comment by rAndom69** [comment]
Via ticket opened onto backend team issue with cabDownloadable=False and inaccessible cabs was considered a bug. (although it was a perilous road...)
Holding breath for a fix

**Comment by adammarks** [comment]
@rAndom69  Thanks for the update,  We also have had a premium support ticket open on this but you are making more headway with confirmation that this is actually considered a bug.

**Comment by rAndom69** [comment]
Update from Microsoft support. I'll post here once again when/if it's resolved.
"The root cause has been identified, but due to the nature of the back-end changes that will need to be made, it may be some time until a fix is available."

**Comment by rAndom69** [comment]
And the resume is, API was probably never implemented but is documented. ^^
This sadly makes entire Store Analytics somewhat useless to us and processing dumps in our infrastructure was only use-case for it. 
Right now I question competence and/or honesty of people I've been in contact regarding this. As ticket took two months to finish to this state, while adam had repro in 5 minutes.

"I have an update. Due to the nature of the changes that would be needed on the backend to enable the API call/programmatic CAB download, this is not supported today. We can evaluate for future releases as a feature request, however there would be no estimated timeframe on when this feature would be available. I am very sorry as I understand this is not ideal. I’m happy to note any feedback you’d like me to."

Yes we will likely be opening ~~bug fix~~ feature request as (aside from other functionality) kernel mode drivers developers we are actually pushed by Microsoft to fix our issues while on the other hand we have to pay for their services which don't work as advertised.

**Comment by rAndom69** [comment]
So, after some marathon of mailing with Microsoft, this works now and crash dumps are downloadable (verified for desktop applications)

**Comment by trijimonpr** [comment]
@rAndom69 - Sorry about commenting on a really old issue. I am facing the same issue that you have outlined. Unable to download cab files, for an account with Manager privilege, as the field cabDownloadable is set to False for all the documents returned by /failuredetails API (https://manage.devcenter.microsoft.com/v1.0/my/analytics/desktop/failuredetails). Could you please help with any suggestions that will help fix this issue? Thanks!
