### ISSUE TITLE
Reading Text Via Code Binding

### ISSUE THREAD

**Issue by jsmcneal** [MicrosoftDocs/windows-uwp#1430]
Would have been nice to have a blurb about how to get the text from the text box into Code Behind because it is not obvious to new UWP developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f75576-743f-742f-17a7-4db97dd52f2a
* Version Independent ID: ee00014e-f666-fb6e-d0da-29a38d6d2f00
* Content: [Text box - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-box#related-articles)
* Content Source: [windows-apps-src/design/controls-and-patterns/text-box.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/text-box.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
hi @jsmcneal : topic has been updated with a new snippet.
