### ISSUE TITLE
Check if notifications is disabled

### ISSUE THREAD

**Issue by toredk** [MicrosoftDocs/windows-uwp#1431]
Is it possible to check whether notifications is disabled (app or overall), so that I can skip the notification and do something else? I would prefer to be able to check before trying to show the notifications rather than checking retrospectively if the notification was shown or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53415734-dd31-7cf0-a82e-02566ed82396
* Version Independent ID: e5f82c08-6c9f-c628-9a45-5df000239ae4
* Content: [Send a local toast notification from desktop C# apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Hey @toredk, you can check the [ToastNotifier.Setting property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotifier.setting#Windows_UI_Notifications_ToastNotifier_Setting)

```csharp
var setting = ToastNotificationManager.CreateToastNotifier().Setting;
```

**Comment by toredk** [comment]
Works perfectly, thank you.

**Comment by toredk** [comment]
Hmm, might not be working as perfect as I first observed. Sometimes I get an exception when retrieving settings from the ToastNotifier:

System.Exception: Element not found. (Exception from HRESULT: 0x80070490)
   at Windows.UI.Notifications.ToastNotifier.get_Setting()

Any idea why this happens?

**Comment by andrewleader** [comment]
How often are you seeing that exception? Out of what percentage of attempts?

That exception indicates a platform failure, we've seen this exception before but it hasn't been high enough of an occurrence to investigate. So we're curious what percentage of your calls to that API are failing.

**Comment by toredk** [comment]
I don't have much data as the feature has not been used that much yet. However, when I experienced it, it seemed to happen 100%. I parked the development for some days and then tried again on the same virtual machine and then got the positive result so I thought that minor mishap in my first implementation.

**Comment by toredk** [comment]
I have looked a bit more into this and it seems to happen only/mostly just after install and then fail two times (during same user action) before it finally works consistently. If I uninstall and reinstall, I do not see the issue, however if I return to Hyper-V checkpoint and try again, I see the same behavior. This is of cause just results from a single (virtual) machine, so not that conclusive.

**Comment by akorneev** [comment]
Looks like this issue: http://www.rudyhuyn.com/blog/2018/02/10/toastnotifier-and-settings-careful-with-non-uwp-applications/

**Comment by toredk** [comment]
Yes, indeed :-)
