### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by mandalorianbob** [MicrosoftDocs/windows-uwp#1434]
Unfortunately this documentation appears to be out of date. There's multiple issues:

In the build pipeline section, the current pipeline is completely different, the VS task doesn’t work that way anymore, and setting “/framework:FrameworkUap10” gives you an error: 
 Error: Invalid .Net Framework version:FrameworkUap10. Supported .Net Framework versions are Framework35, Framework40 and Framework45.

It also doesn't specify where to put in the appxrecipe (and doesn't show a proper minimatch parameter) nor does it explain how to do non-UI UWP tests on a hosted agent or if such a thing is even possible.

Hockeyapp is being retired. 

Lastly, it should probably show using a Release Pipeline for deploying to App Center, instead of a just making it a build task. This is far more helpful for anyone that needs to have approval before deployment.

This page probably needs to be reevaluated from top to bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c024acf3-a58a-74c8-25b1-e5c88c85583a
* Version Independent ID: 81403e1d-947a-1f7d-f4b7-898105abd745
* Content: [Set up automated builds for your UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps#set-up-a-continuous-integration-ci-build)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting you're feedback. We are reserving some time to review and revise this article in February. I will leave this issue open until we have updated the article.

**Comment by mcleanbyron** [comment]
Last month this article was rewritten with assistance from the engineering team to capture the latest guidelines and Azure DevOps processes. If you still see issues in the article, please feel free to reopen this issue.
