### ISSUE TITLE
Incorrect UIElement.Translation link.

### ISSUE THREAD

**Issue by rawlinson** [MicrosoftDocs/windows-uwp#1435]
The UIElement.Translation link incorrectly goes to UIElement.Scale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e8ca0e5-8827-0b34-c582-47c196dc034e
* Version Independent ID: eab0e86f-49d7-43fb-1dbf-c33d94166b67
* Content: [Motion in practice - animation in UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/motion/motion-in-practice)
* Content Source: [windows-apps-src/design/motion/motion-in-practice.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/motion-in-practice.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stmoy** [comment]
Thanks for reporting this issue. We have fixed the link on the page. Closing.
