### ISSUE TITLE
Padding in the first screenshot to introduce XAML is wrong

### ISSUE THREAD

**Issue by nokola** [MicrosoftDocs/windows-uwp#1439]
Screenshot incorrectly shows padding as 16 on left and 24 on top, which happens to be how CSS padding works. Unlike CSS, XAML Padding="24,16" means "24 on left" and "16 on top"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e4eb9-1481-e2ae-3922-26799d2e6dbd
* Version Independent ID: 4ac739fa-45fc-651e-4c3e-fa77941655e3
* Content: [Fluent Design System for Windows - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/fluent-design-system/index?utm_campaign=DC19&utm_source=Dev_Newsletter&utm_medium=Email&utm_content=janctafluent)
* Content Source: [windows-apps-src/design/fluent-design-system/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/fluent-design-system/index.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks--I just checked in an update.

**Comment by nokola** [comment]
Awesome, thank you!
