### ISSUE TITLE
testing 

### ISSUE THREAD

**Issue by AdultChain** [MicrosoftDocs/windows-uwp#1441]
i SHOUDL SLEEP BUT NAAAAH

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6012862f-de3d-cff6-72e1-f2ea8a5db7a4
* Version Independent ID: c1fcafa1-7c75-9e83-de77-3f54f89a24da
* Content: [Enhance your desktop application for Windows 10 - Windows UWP applications](https://docs.microsoft.com/en-ca/windows/uwp/porting/desktop-to-uwp-enhance)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-enhance.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Excellent feedback, but I don't see anything actionable so I'm going to have to close this issue.

**Comment by riverar** [comment]
@hickeys Why does the Storepolicy 0431 update link to this issue?
