### ISSUE TITLE
ColorSchemeResources 

### ISSUE THREAD

**Issue by seanocali** [MicrosoftDocs/windows-uwp#1442]
"ColorSchemeResources is not supported in a Windows Universal project." Using 1809.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181b91e8-b61c-f32b-f59c-332db130d207
* Version Independent ID: ec8195d3-5847-e003-c8ef-bc3a6dfe069f
* Content: [Color in UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/color)
* Content Source: [windows-apps-src/design/style/color.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/color.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by kikisaints** [comment]
Hi @seanocali - that's because the official API name that we shipped with was Color**Palette**Resources. I recently made a [PR to change that](https://github.com/MicrosoftDocs/windows-uwp/pull/1429). Sorry about the confusion!

Also, please note that ColorPaletteResources is not in WinUI, so if you are using that nuget, you will not be access it there yet.

**Comment by pedrolamas** [comment]
Hi @kikisaints seems that your PR was incomplete as I still see a lot of references to `ColorSchemeResources` in [this article](https://docs.microsoft.com/en-us/windows/uwp/design/style/color).

**Comment by kikisaints** [comment]
> Hi @kikisaints seems that your PR was incomplete as I still see a lot of references to `ColorSchemeResources` in [this article](https://docs.microsoft.com/en-us/windows/uwp/design/style/color).

Wow... no idea how I missed this! Thanks @PedroLamas

I made [another PR](https://github.com/MicrosoftDocs/windows-uwp/pull/1564) with, hopefully, all the necessary changes to the color.md page to update that API's name.

**Comment by pedrolamas** [comment]
I was about to fix and send a PR myself when I looked into the history and saw your previous PR!

**Comment by thejimmyj57** [comment]
Still the same issue as of update 1903

**Comment by mijacobs** [comment]
I just merged Kiki's PR, it should be live shortly.
