### ISSUE TITLE
Bad Link "Fast Property Access Walkthrough"

### ISSUE THREAD

**Issue by Heidelberger** [MicrosoftDocs/windows-uwp#1443]
Under "See Also", the document link "Fast Property Access Walkthrough" doesn't work.  It's currently pointed at:

https://blogs.msdn.microsoft.com/adamdwilson/2017/12/20/fast-file-enumeration-with-partially-initialized-storagefiles/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b97057aa-f404-82d3-8178-8cb3af6835a0
* Version Independent ID: ee79a5e8-f627-271b-65be-141e179e08c5
* Content: [Fast access to file properties in UWP - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/fast-file-properties)
* Content Source: [windows-apps-src/files/fast-file-properties.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/fast-file-properties.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. Unfortunately, the blog article that this link pointed to no longer exists. I have removed this link from the latest version of the article, and this fix should be published to the live site in the next day or two.
