### ISSUE TITLE
Windows system bug

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#1445]
I was trying to help Microsoft but it was difficult, I need to install a lot of software and configure it as well. and I found out that id like to send a screen shot here but theres no option yet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443bc235-c1bd-4f01-f758-14575db6dbb6
* Version Independent ID: 9b2b7af4-870a-d423-f0d7-2f7a680d38cc
* Content: [Launch Feedback Hub from your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/launch-feedback-hub-from-your-app)
* Content Source: [windows-apps-src/monetize/launch-feedback-hub-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/launch-feedback-hub-from-your-app.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi TakanoriShimada,

Thank you for reaching out to the Microsoft developer documentation team. This mechanism is intended for feedback about the documentation. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

I can tell you that the engineering team is aware of this issue and is currently testing a fix.

For future reference, you may have success posting your questions in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
