### ISSUE TITLE
Regarding Windows.Media.Playlist

### ISSUE THREAD

**Issue by Varun9198** [MicrosoftDocs/windows-uwp#1446]
No class like Playlist is found. Do we need to add some api? If so, how to do it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca0819b-1bb1-d0f1-4ca3-3796afee158e
* Version Independent ID: 93929324-b162-6e88-b885-afd3b17215d7
* Content: [Get UWP app samples - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-uwp-app-samples#main)
* Content Source: [windows-apps-src/get-started/get-uwp-app-samples.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/get-uwp-app-samples.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
I don't see Playlist mentioned on this page. Is this an issue with the page itself, or with one of the samples you downloaded?
