### ISSUE TITLE
Document cannot be downloaded as PDF.

### ISSUE THREAD

**Issue by I-B-B** [MicrosoftDocs/windows-uwp#1447]
Here is a link to the attempt to download this as a pdf: https://opdhsblobprod02.blob.core.windows.net/contents/a39839aac94c42a38eee8ee304bde8c6/d98c1dd4008f04b2e9800998ecf8427e?sv=2015-04-05&sr=b&sig=hwbZPkMA1e3K2KIq03A%2FoXArL7Aq4ni7uxXjtF3wmRk%3D&st=2019-02-03T09%3A28%3A05Z&se=2019-02-04T09%3A38%3A05Z&sp=r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b30576-1161-8546-df9f-61de76e39fd1
* Version Independent ID: 7275be4d-3028-fbd3-ba0a-4f09491705e7
* Content: [Data access - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/#feedback)
* Content Source: [windows-apps-src/data-access/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/index.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. This is a known issue that is affecting the entire UWP docs site and we are investigating.

**Comment by mcleanbyron** [comment]
This issue should now be fixed. Please reopen if you still see the problem. Thanks!

**Comment by I-B-B** [comment]
@mcleanbyron Thank you, I have managed a successful download of the document. (It is fixed).
