### ISSUE TITLE
Ambiguous version availability

### ISSUE THREAD

**Issue by MichaelLHerman** [MicrosoftDocs/windows-uwp#1448]
Remove "Starting with the next major update to Windows 10..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e6de74-ed8f-c579-9f87-766a06efe057
* Version Independent ID: 543f6a62-4700-0774-8112-b288ffe7550b
* Content: [Functions in x:Bind - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings)
* Content Source: [windows-apps-src/data-binding/function-bindings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/function-bindings.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. I have removed the "Starting with the next major update to Windows 10" text from the latest version of the article, and this fix should be published to the live site in the next day or two.
