### ISSUE TITLE
Async assumed

### ISSUE THREAD

**Issue by Dowscope** [MicrosoftDocs/windows-uwp#1450]
While going through the step by step of this document. It was assumed (I believe) that you would be using a StorageFile in a async method.  Well when I did it the await command wasn't working for me until I made it an async method.  But it took a while to figure this out since it wasn't written in the steps.  If you double click on a button it doesn't generate the async method, you need to put it in yourself.  \

`private async void Button_Click(object sender, RoutedEventArgs e)
        {
            FileOpenPicker fop = new FileOpenPicker();
            fop.ViewMode = PickerViewMode.Thumbnail;
            fop.FileTypeFilter.Add(".xlsx");
            StorageFile file = await fop.PickSingleFileAsync();
            if (file != null)
            {
                this.txtBlock.Text = file.Path;
            }
        }`

**Comment by ginami** [comment]
Hi @Dowscope -- thank you for your feedback! Which doc are you referring to? When I have the URL I will assign this to the relevant doc author. Thanks!

**Comment by ginami** [comment]
Hi @Dowscope -- I'm going to close this issue. If you have the URL of the doc in question, go ahead and reopen and add the info. Thanks!
