### ISSUE TITLE
Cannot change payout account

### ISSUE THREAD

**Issue by sp-miguel-ibero** [MicrosoftDocs/windows-uwp#1453]
Hi, when creating an Add-on I get the message "You need to update your tax and payout information before you can charge money." And in "Finantial Details" I see the "Payout Account" option but I cannot change it although I have the correct permissions. What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec06af90-a369-e18e-dffd-30443c415f33
* Version Independent ID: dae3fe06-e22a-7c3f-c0eb-03220929f0ef
* Content: [Set up your payout account and tax forms - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
For help with this please open a support case at http://aka.ms/storesupport under "Contact Us". Thanks!
