### ISSUE TITLE
ToastGenericAppLogo  as SVG

### ISSUE THREAD

**Issue by marioelenajr** [MicrosoftDocs/windows-uwp#1454]
Can the AppLogo be an SVG? 
I tried with a http://..../.svg but it didn't render my logo. The size of my svg is &lt;7KB.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b559cf6d-7bd0-9e1a-8ab0-a389b01a20d8
* Version Independent ID: 7e9df100-79bc-20f5-a193-3194328b28bc
* Content: [Toast content - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
No, it cannot.
