### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by francisco-chavez** [MicrosoftDocs/windows-uwp#1457]
It's 2019 and VS 2017 has been out there for a while now. Not to mention that some of the updates to VS 2017 have removed some of the project templates, like the ones used by tutorials for building DirectX 12 desktop applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f6e4af-3499-d7ca-90ae-a36c539f7116
* Version Independent ID: 83f44c62-e3d0-e7ca-6581-2676f1b5661c
* Content: [Project templates and tools for games - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/prepare-your-dev-environment-for-windows-store-directx-game-development)
* Content Source: [windows-apps-src/gaming/prepare-your-dev-environment-for-windows-store-directx-game-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/prepare-your-dev-environment-for-windows-store-directx-game-development.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @francisco-chavez. Thanks for filing this issue, and sorry for the very long delay in responding to it.

You're right, this topic was out of date. I've updated it now. Please keep the feedback coming. :)

I'll go ahead and close this issue now.

Thanks again!
Steve

**Comment by francisco-chavez** [comment]
It looks like some of the child documents to this might also need an update. https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/user-interface.md .
