### ISSUE TITLE
http://manvip.club

### ISSUE THREAD

**Issue by thaimacao887** [MicrosoftDocs/windows-uwp#1459]
dailyso1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2099ff76-43d5-98fd-d8bc-66ccdc14c4fe
* Version Independent ID: 1c3f3863-5413-d58b-a0e5-81a6da6bccf2
* Content: [Account types, locations, and fees - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees#feedback)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Product: **uwp**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
Please let us know if you have specific feedback for our documentation.
