### ISSUE TITLE
Create Package, precompiled header files

### ISSUE THREAD

**Issue by timhirrel** [MicrosoftDocs/windows-uwp#1462]
Using vc17  i have created a project that doesn't use precompiled headers. The project compiles and executes successfully, But when i try create a store app package the build process fails with the message

"unexpected end of file while looking for precompiled header. did you forget to add #include stdafx.h to your source?"

no, i didn't forget to add it. i don't use precompliled headers  but the create package process refuses to acknowledge that. 

can anyone provide a work around for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1c88d-24b1-0eda-b458-105db02dca36
* Version Independent ID: c5d1634a-0ead-f68a-e5be-89acf0eef0a6
* Content: [Packaging UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#validate-your-app-package)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Hi @timhirrel - Unfortunately, this docs repo is not a support channel. Please see [this page](https://developer.microsoft.com/en-us/windows/support) for your support options. You might also try the following resources:
* Our [MSIX and packaging](https://techcommunity.microsoft.com/t5/MSIX/ct-p/MSIX) forums.
* Our [general Windows development forums](https://social.msdn.microsoft.com/Forums/en-US/newthread?category=windowsapps&forum=wpdevelop&prof=required) 
* [StackOverflow](https://stackoverflow.com/questions)
