### ISSUE TITLE
Microsoft Ads, interstitial requestAd crash

### ISSUE THREAD

**Issue by pozirk** [MicrosoftDocs/windows-uwp#1465]
Hello!
Changing `MicrosoftNSJS.Advertising.InterstitialAdType.video` to `MicrosoftNSJS.Advertising.InterstitialAdType.display` cause app to crash on requestAd.
Video ads are working fine.
Screenshot from VS debug.
![msads_display_crash](https://user-images.githubusercontent.com/1659590/52601846-499e5f80-2e2e-11e9-8143-09657efffdb0.jpg)

Any fix for that?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d995cd1f-b945-a9e6-9994-2b8458acd592
* Version Independent ID: 9d6e45a4-d582-b8b7-b9a1-229e1bcb0141
* Content: [Interstitial ad sample code in JavaScript - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/interstitial-ad-sample-code-in-javascript)
* Content Source: [windows-apps-src/monetize/interstitial-ad-sample-code-in-javascript.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/interstitial-ad-sample-code-in-javascript.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thank you for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
