### ISSUE TITLE
Typo errors occur when the website language is not English

### ISSUE THREAD

**Issue by dhssingle** [MicrosoftDocs/windows-uwp#1466]
Many pages have this problem.
e.g.
[design-and-ui-intro](https://docs.microsoft.com/zh-cn/windows/uwp/design/basics/design-and-ui-intro)
![20190212214553](https://user-images.githubusercontent.com/3339298/52640223-f6e9a400-2f10-11e9-9290-1be35e54e6a4.png)

**Comment by mijacobs** [comment]
This is known issue with our localization tools; the loc team is developing a fix.
