### ISSUE TITLE
Would be nice to mention

### ISSUE THREAD

**Issue by jhwheuer** [MicrosoftDocs/windows-uwp#1468]
It would be nice to mention in this docu that these methods need to be called from the UI thread...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23212d2-fccf-06d2-622c-544c333e6c57
* Version Independent ID: a258d712-d2d4-bdec-a77e-8a08b1031d0a
* Content: [Badge notifications for UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/badges.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/badges.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
All XAML APIs need to be called from the UI thread. In order to not clutter doc pages with this info, we include the opposite -- only the APIs that *can* be called off the UI thread are noted as such.
