### ISSUE TITLE
Settings Item is auto invoked when MenuItemsSource changed

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/windows-uwp#1469]
SDK 17763

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
@linhnddev - Sounds like you found a bug in NavigationView. Can you open a [new issue](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose) on the [microsoft-ui-xaml](https://github.com/Microsoft/microsoft-ui-xaml) GitHub so our engineers can investigate? What you're seeing doesn't seem to be a documentation problem. The best place to report controls bugs is on microsoft-ui-xaml.
