### ISSUE TITLE
How do I use this documentation for my developer portal?

### ISSUE THREAD

**Issue by mjangid** [MicrosoftDocs/windows-uwp#147]
Hi Team,

To publish my API I am using Azure API Management and want to develop a developer portal and use similar kind of documentation, do you have any getting started guide to create documentation?

**Comment by mattwojo** [comment]
Thanks for your question @mjangid -- this is a tricky one. 
@GrantMeStrength -- any ideas for how to address this or who should be assigned?

**Comment by GrantMeStrength** [comment]
Does this help? https://docs.microsoft.com/en-us/azure/api-management/

**Comment by mattwojo** [comment]
@mjangid -- Does the API management link shared above address your issue?  Please let us know in within the next couple of days or I'll consider the issue resolved and close.
Thanks again for the question.

**Comment by mjangid** [comment]
Thanks @mattwojo @GrantMeStrength all documentation of Microsoft is using DocFx framework http://dotnet.github.io/docfx/

I have started my documentation using this framework, Please free to mark as resolved.
