### ISSUE TITLE
Simplified Chinese Localization for Japanese Era Change

### ISSUE THREAD

**Issue by VaslD** [MicrosoftDocs/windows-uwp#1471]
It's sad to see articles in Globalization section stay untranslated.

I came across this article regarding the upcoming Japanese Era change on May 1. Since even machine translation isn't available, I thought I'd do a (Simplified Chinese)[https://gist.github.com/VaslD/a31e60de4d1c8c80ab400e82c89bf273] translation. I made sure all translated menus/controls match what will be shown on a computer with Simplified Chinese UI.

I didn't find the zh-CN localization repo for UWP so the issue was created here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678c458d-6ad5-f85d-bd56-9abf8760973b
* Version Independent ID: 839e1cfc-82f2-0be2-efc3-62cdb58cdfac
* Content: [Prepare your application for the Japanese era change - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/japanese-era-change)
* Content Source: [windows-apps-src/design/globalizing/japanese-era-change.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/japanese-era-change.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by eliotcowley** [comment]
Hi @VaslD, thank you for pointing this out, and for your work translating the document. This is very strange, as we actually got this localized into 10 different languages (including zh-cn) but for some reason, it's not showing up. I'll follow up and get back to you.

**Comment by eliotcowley** [comment]
Hi @VaslD, we've published the document's localized versions, [including zh-cn](https://docs.microsoft.com/zh-cn/windows/uwp/design/globalizing/japanese-era-change), so please take a look. Thanks!
