### ISSUE TITLE
Store Restriction still applicable?

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/windows-uwp#1472]
Does use of these APIs still preclude submitting the app to the Windows Store? It looks like it's been lifted in some circumstances - https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/9950598-exclude-suspending-in-desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f08a1cd-54da-9647-5f88-12ff5dcd9bab
* Version Independent ID: 1de44f88-2e90-cc63-9707-b415be120237
* Content: [Run in the background indefinitely - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly)
* Content Source: [windows-apps-src/launch-resume/run-in-the-background-indefinetly.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-in-the-background-indefinetly.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by GrantMeStrength** [comment]
Thanks for the comment, and sorry for the delay in addressing it.

The official guidance is that this API is a restricted capability, and can only be used in very few Store apps under specially vetted circumstances. 

https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities

Thanks for taking the time to leave feedback, and again, sorry for the delay. We do read bugs as they come in, but may not add comments immediately, which gives a poor impression. As this wasn't really a documentation bug, it fell through some cracks. I apologize. -John
