### ISSUE TITLE
IAP add-on gross sales

### ISSUE THREAD

**Issue by Evanjt1** [MicrosoftDocs/windows-uwp#1474]
Is there any way to pull gross sales in USD like is available on the Partner Center analytics dashboard? I've been all through the docs trying to find an officially supported way to grab sales data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a16c3ca-9b6d-74ba-48ac-79d8257644ba
* Version Independent ID: 595e593b-5e27-5935-95f3-d2bca468540d
* Content: [Get add-on acquisitions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-in-app-acquisitions#feedback)
* Content Source: [windows-apps-src/monetize/get-in-app-acquisitions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-in-app-acquisitions.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thank you for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
