### ISSUE TITLE
FIle name?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#1475]
In the C++/winrt example of a simple POST of binary data, there is no file name, so it's not clear to me where this sample data is going  - isn't it necessary to specify a destination for the data? How would one add a path to this example, so that the data being POSTed replaces the contents of a specified file at the server? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab6b70c-a112-963b-3951-b4fa958694a9
* Version Independent ID: a7d8ff19-bda3-0889-2051-6627e5d4b16b
* Content: [HttpClient - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/httpclient)
* Content Source: [windows-apps-src/networking/httpclient.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/httpclient.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by jevansAN** [comment]
Talking to someone about this I've come to understand that the script receiving the query will do the work of creating the file, etc. - so all I need is a standard way to specify that path in the header for this content. Perhaps there is no way to do that with HttpBufferContent.

**Comment by stevewhims** [comment]
I've updated the code here (it's live now). And I've added more thoughts (related to this question) to the other issue (https://github.com/MicrosoftDocs/winrt-api/issues/907). But, yeah, it probably boils down to how you specify that filename directive, and what path (if any) is meant to go in there. I'll close this, and we'll continue working on the other issue thread.
