### ISSUE TITLE
No Information on Binding

### ISSUE THREAD

**Issue by amartens181** [MicrosoftDocs/windows-uwp#1482]
If I want to bind formatted text in a listview, how would I do that? Is there a way to make textblock binding interpret bolds? Xamarin has the FormattedText property, but I don't see that here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32e59674-1a32-a0b7-41f7-b1157ff263e9
* Version Independent ID: 64ae3898-2f10-d240-f28e-6dd027bf7910
* Content: [Text block - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-block#formatting-text)
* Content Source: [windows-apps-src/design/controls-and-patterns/text-block.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/text-block.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
You can bind Run.Text property of Runs in a RichTextBlock. If you want to have the viewmodel offer up a formatted string like this that would be a feature request. You can file such requests at https://github.com/Microsoft/microsoft-ui-xaml.
