### ISSUE TITLE
App_id for another app

### ISSUE THREAD

**Issue by ashwinjam** [MicrosoftDocs/windows-uwp#1486]
How's app_id retrieved for another app? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24460ebf-4e79-a810-457f-538462186a0a
* Version Independent ID: 062493b6-0b9b-a8d9-7466-878a381be604
* Content: [App metadata API for advertising networks - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/app-metadata-api-for-advertising-networks)
* Content Source: [windows-apps-src/monetize/app-metadata-api-for-advertising-networks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/app-metadata-api-for-advertising-networks.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
