### ISSUE TITLE
THis does not work

### ISSUE THREAD

**Issue by eschneider999** [MicrosoftDocs/windows-uwp#1487]
I get the following error: 
Error	BC30451	'StoreContext' is not declared. It may be inaccessible due to its protection level.	ProcessManager	D:\Dev\FrozenElephant\ProcessManager\ProcessManager\FormProcessManager.vb	14	Active

And I do have:
Imports Windows.Services.Store

and a reference to nuget: Microsft.Services.Store.SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d672b6a3-7ac7-5175-cddc-d97802386585
* Version Independent ID: 7135a844-651a-1c92-e9a7-21865935a151
* Content: [In-app purchases and trials - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#desktop)
* Content Source: [windows-apps-src/monetize/in-app-purchases-and-trials.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/in-app-purchases-and-trials.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
