### ISSUE TITLE
NavigationView doesn't respond if NavigationCacheMode is Enabled

### ISSUE THREAD

**Issue by AlKau** [MicrosoftDocs/windows-uwp#1488]
SDK target 17763; min 17134;
PC: Win10 1809

Code Sample:
XAML:
```
<Page x:Class="NavigationViewBug.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:NavigationViewBug"
      xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      NavigationCacheMode="Enabled"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <muxc:NavigationView ItemInvoked="OnItemInvoked">
            <muxc:NavigationView.MenuItems>
                <muxc:NavigationViewItem Content="Page #1"
                                         Icon="Page"
                                         Tag="Page #1" />
                <muxc:NavigationViewItem Content="Page #2"
                                         Icon="Page2"
                                         Tag="Page #2" />
                <muxc:NavigationViewItem Content="Pane #3"
                                         Icon="Cancel"
                                         Tag="Page #3" />
            </muxc:NavigationView.MenuItems>

            <Frame x:Name="FrameContent"/>

        </muxc:NavigationView>
    </Grid>
</Page>

```
C#:
```
private void OnItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
{
    switch (args.InvokedItemContainer.Tag)
    {
        case "Page #1":
            FrameContent.Navigate(typeof(Page1));
            break;
        case "Page #2":
            FrameContent.Navigate(typeof(Page2));
            break;
        default:
            Frame.Navigate(typeof(Page3));
            break;
    }
}
```
When Page3 calls "Frame.GoBack();", MainPage is loaded and NavigationView doesn't respond.

```
        private void OnBackRequested(object sender, BackRequestedEventArgs e)
        {
            if (Frame.CanGoBack)
            {
                Frame.GoBack();
                e.Handled = true;
            }
        }
```

I can't reproduce it on PC: Win10 1803 or NavigationCacheMode="Disabled"
full project: https://github.com/AlKau/UWP-Samples/tree/master/NavigationViewBug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
@AlKau - I'm sorry to hear you're encountering this problem. As this is an issue in code and not in documentation, can you please re-open this issue in the [microsoft-ui-xaml GitHub](https://github.com/Microsoft/microsoft-ui-xaml) repo using the [bug template](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose)? This will give our engineers an opportunity to dig into and debug the problem.

**Comment by AlKau** [comment]
It seems, it's been fixed (https://github.com/Microsoft/microsoft-ui-xaml/issues/18).
