### ISSUE TITLE
Rewards Based ads

### ISSUE THREAD

**Issue by AwsomeCode** [MicrosoftDocs/windows-uwp#1489]
There is no example for Rewards Based ads & Unable to find API's for that as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49737ba9-1774-88fe-091d-e6a1e520290d
* Version Independent ID: 3125052c-9279-2d13-eb51-fda45883fe4f
* Content: [Interstitial ads - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/interstitial-ads)
* Content Source: [windows-apps-src/monetize/interstitial-ads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/interstitial-ads.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
The only difference between paywall ads and rewards-based ads are the way they are initiated. Paywall based ads are kicked off by your app based on a timer, the user starting or completing an action, or some other paywall at a point that makes sense for your app. Rewards-based ads are kicked off by the user in exchange for something, such as extra gems or access to a special feature.

**Comment by hkhmsft** [comment]
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback!
