### ISSUE TITLE
Incorrect Example

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1491]
To get this to function properly the complete example should be shown as the location of the VSM matters based on the rest of the tree:

```
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <ScrollViewer>
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup>
                <VisualState>
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="640" />
                    </VisualState.StateTriggers>

                    <VisualState.Setters>
                        <Setter Target="Associate.(RelativePanel.RightOf)" Value="Customer"/>
                        <Setter Target="Associate.(RelativePanel.Below)" Value=""/>
                        <Setter Target="Save.(RelativePanel.Below)" Value="Customer"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>

        <RelativePanel>
            <StackPanel x:Name="Customer" Margin="20">
                <TextBox x:Name="CustomerName" Header= "Customer Name" Margin="0,24,0,0" HorizontalAlignment="Left" />
                <TextBox x:Name="Address" Header="Address" PlaceholderText="Address" Margin="0,24,0,0" HorizontalAlignment="Left" />
                <TextBox x:Name="Address2" Margin="0,24,0,0" PlaceholderText="Address 2" HorizontalAlignment="Left" />
                    <RelativePanel>
                        <TextBox x:Name="City" PlaceholderText="City" Margin="0,24,0,0" HorizontalAlignment="Left" />
                        <ComboBox x:Name="State" PlaceholderText="State" Margin="24,24,0,0" RelativePanel.RightOf="City">
                            <!--List of valid states-->
                        </ComboBox>
                    </RelativePanel>
            </StackPanel>
            <StackPanel x:Name="Associate" Margin="20" RelativePanel.Below="Customer">
                <TextBox x:Name="AssociateName" Header= "Associate" Margin="0,24,0,0" HorizontalAlignment="Left" />
                <DatePicker x:Name="TargetInstallDate" Header="Target install Date" HorizontalAlignment="Left" Margin="0,24,0,0"></DatePicker>
                <TimePicker x:Name="InstallTime" Header="Install Time" HorizontalAlignment="Left" Margin="0,24,0,0"></TimePicker>
            </StackPanel>
            <StackPanel x:Name="Save" Orientation="Horizontal" RelativePanel.Below="Associate">
                <Button Content="Save" Margin="24" />
                <Button Content="Cancel" Margin="24" />
            </StackPanel>
        </RelativePanel>
    </ScrollViewer>
</Page>
```

I added a `ScrollViewer` too, as otherwise on narrow display the bottom boxes can be chopped and unreachable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b47dbb-38b5-9d75-8df2-2300cdc25bb7
* Version Independent ID: b204d881-3ca4-a7bb-87c3-0e91df704637
* Content: [Learning track - Construct and configure a form - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/construct-form-learning-track?WT.mc_id=windowsdocs-twitter)
* Content Source: [windows-apps-src/get-started/construct-form-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/construct-form-learning-track.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by michael-hawker** [comment]
Also, looks like you have a bug in the GitHub integration with the docs page, when you submit an issue there with XAML it converts all the </> to be escaped. :(

I had to come back here to edit it and repaste the XAML

**Comment by QuinnRadich** [comment]
Sorry to hear about the GitHub bug.

We've presented a truncated version of the full code on the page, with the hope that the user is progressing through the steps in order and the abbreviated reference to the RelativePanel will be enough for them to understand where to put the VSM.

Is the structure of the code presented in the "Make your layout responsive" section incorrect or unclear? Or is this just a request for the non-abbreviated reference to the RelativePanel?

**Comment by michael-hawker** [comment]
@QuinnRadich it's about providing a sample setup for success as someone coming to your page first without learning as much about VSM first won't know that they can't just copy/paste it anywhere.  For instance if you look at the [VSM sample on fluid layout page](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layouts-with-xaml#adaptive-layouts-with-visual-states-and-state-triggers), they show the page structure and call out the importance of the tree:

![image](https://user-images.githubusercontent.com/24302614/56549248-1ddadc80-6537-11e9-95a1-7595ad23a502.png)

So, it'd be good if the sample at least followed that example's structure for abbreviation.

However, by providing a full sample somewhere on the page vs. an abbreviated one.  It means that I can copy and paste that sample into something like [XAML Studio](https://aka.ms/GetXAMLStudio) and be able to play with it immediately and know that it'll work.

**Comment by QuinnRadich** [comment]
Closing this stale issue - the final sample was updated to align to the abbreviated format a while ago. Thank you.
