### ISSUE TITLE
Generated Markdown table errors throughout

### ISSUE THREAD

**Issue by FormlessOne** [MicrosoftDocs/windows-uwp#1493]
The Markdown tables generated for various sections, including **Request**, **URI parameters**, and **Status code**, aren't rendering correctly if one or more rows exist for most of the topics I checked. The [/ext/screenshot](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/wdp-media-capture-api) topic is a good example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1946cd5-a111-ba09-e226-e5614104e995
* Version Independent ID: 20d262f4-ddc0-afcb-28fe-2a3c564280ce
* Content: [Xbox Device Portal REST API - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/reference)
* Content Source: [windows-apps-src/xbox-apps/reference.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/reference.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by KevinAsgari** [comment]
Thanks for bringing this to our attention!  I have a pull request out that should fix the table formatting across this area.
