### ISSUE TITLE
Link for "Guidelines for tabs and pivots" is broken

### ISSUE THREAD

**Issue by Mehigh17** [MicrosoftDocs/windows-uwp#1494]
404 when trying to access the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be10565a-f999-569f-3314-f1691cfa3d6f
* Version Independent ID: 3e862b52-b135-e9af-5c13-424002f038d8
* Content: [Peer-to-peer navigation between two pages - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigate-between-two-pages)
* Content Source: [windows-apps-src/design/basics/navigate-between-two-pages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigate-between-two-pages.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The link is fixed now.
