### ISSUE TITLE
No error codes listed

### ISSUE THREAD

**Issue by GeertvanHorrik** [MicrosoftDocs/windows-uwp#1495]
After a submission failure, I was pointed to this document where I could find more information about error code 1201. Unfortunately I could not find anything here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0973c3-07c3-882e-46be-783dc13e575f
* Version Independent ID: 6877aae0-2aab-46f7-dd3a-16dd7d3bf842
* Content: [Resolve submission errors - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/resolve-submission-errors)
* Content Source: [windows-apps-src/publish/resolve-submission-errors.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/resolve-submission-errors.md)
* Product: **uwp**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
This error can occur for a number of reasons. Please take a look at the **Known Issues** section of [.NET Native Internal Compiler Errors](https://go.microsoft.com/fwlink/p/?LinkID=613098). If that doesn’t help, you can contact dotnetnative@microsoft.com for help troubleshooting.
