### ISSUE TITLE
delayInSeconds ignored

### ISSUE THREAD

**Issue by Micro-Muncher** [MicrosoftDocs/windows-uwp#1496]
I've added the screenshot URI for snip - but it seems delayInSeconds is completely ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c40df19b-d384-1d57-eb09-294b95952e65
* Version Independent ID: 112048ff-91e3-bd87-351d-4d1354731943
* Content: [Launch screen snipping - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-screen-snipping)
* Content Source: [windows-apps-src/launch-resume/launch-screen-snipping.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-screen-snipping.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by QuinnRadich** [comment]
I've consulted with the engineering team for this feature, and we've been unable to reproduce this issue. I'd recommend that, if you're still having this issue, that you file a bug report. Thank you.
