### ISSUE TITLE
Sketchapp symbols library missing

### ISSUE THREAD

**Issue by plexus-design** [MicrosoftDocs/windows-uwp#1497]
The sketch toolkit does not include the symbols library. How does one get access to this?

**Comment by ginami** [comment]
Hi @plexus-design -- thank you for your feedback! This list is specifically for doc issues--were you looking at a sketch toolkit doc? And if so, could you provide the URL? Thanks!

**Comment by plexus-design** [comment]
I am referring to the sketch toolkit that can be downloaded from here
https://docs.microsoft.com/en-us/windows/uwp/design/downloads/

I got to the github page from following the link at bottom of the above page


For reference
When the sketch app toolkit is opened - the symbols (referring to a sketch
app symbols library) is not linkedin or included in this download therefore
the toolkit cannot be full utilized

Thanks

Kind regards
Jenna Law
----------------------------------
+1 646 306 4482
+44 7771 78 21 79
www.plexusdesign.co.uk <http://bit.ly/PlexusDesign>

User Focussed. Experience Driven. Design Led
LinkedIn <http://bit.ly/JennaLaw-LinkedIn> | Behance
<http://bit.ly/JennaLaw-Behance> | Dribbble
<http://bit.ly/JennaLaw-Dribbble> | Twitter <http://bit.ly/JennaLaw-Twitter>
| Instagram <http://bit.ly/JennaLaw-Instagram> | Medium
<http://bit.ly/JennaLaw-Medium>

**Comment by ginami** [comment]
Thanks--I will get this routed to the page owner!

**Comment by plexus-design** [comment]
Thanks Gina


Kind regards
Jenna Law
----------------------------------
+1 646 306 4482
+44 7771 78 21 79
www.plexusdesign.co.uk <http://bit.ly/PlexusDesign>

User Focussed. Experience Driven. Design Led
LinkedIn <http://bit.ly/JennaLaw-LinkedIn> | Behance
<http://bit.ly/JennaLaw-Behance> | Dribbble
<http://bit.ly/JennaLaw-Dribbble> | Twitter <http://bit.ly/JennaLaw-Twitter>
| Instagram <http://bit.ly/JennaLaw-Instagram> | Medium
<http://bit.ly/JennaLaw-Medium>

**Comment by jevansaks** [comment]
@chigy who owns this tool? I'm surprised this page links to a zip file instead of a github.

**Comment by chigy** [comment]
@plexus-design , I don't quite understand your comment "I got to the github page from following the link at bottom of the above page" When I click on "download" link of the Sketch, it give you the zip file with the symbol file so I am unable to figure out what you mean by the github page. Is the zip file with symbol file not sufficient?

**Comment by chigy** [comment]
@plexus-design , as I do not currently see issues with the files we provide and I have not heard back with the response, I'm closing the issue. Please feel free to follow up if this issue is not resolved for you.
