### ISSUE TITLE
What about Platform::Array?

### ISSUE THREAD

**Issue by anhoavu** [MicrosoftDocs/windows-uwp#1498]
How do I port Platform::Array to C++/WinRT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d6decd-f437-6bf3-1f32-60cbcd2d0016
* Version Independent ID: bfbcfa81-2172-1a97-0e67-40d22f5e8b50
* Content: [Move to C++/WinRT from C++/CX - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @anhoavu, thanks for raising this issue. I've just made an update to the topic. You can see the new section here: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx#port-platformarray. Please let me know if the topic needs additional info.

Thanks!
~Steve

**Comment by anhoavu** [comment]
@stevewhims Thank for the support, Steve. I am trying to see if `Platform::Array` is interoperable with `array_view` i.e. if an C++/WinRT `AppService` sends an `array_view` to an C++/CX client, would the latter be able to reassemble the data.

**Comment by stevewhims** [comment]
Yes, that sounds good. Let's say you declare this (using C++/CX):

```cppcx
double Class1::PassArrayForReading(const Platform::Array<double>^ arr)
```

Then that's projected into C++/WinRT like this: 

```cppwinrt
template <typename D> double consume_MYNAMESPACE___IClass1PublicNonVirtuals<D>::PassArrayForReading(array_view<double const> arr) const
```

So you can call it from C++/WinRT like this:

```cppwinrt
MYNAMESPACE::Class1 c1;
auto sum = c1.PassArrayForReading({ 99.f, 98.f, 97.f }); // or any other way that uses an array_view.
```

~Steve

**Comment by stevewhims** [comment]
Hi, @anhoavu, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
