### ISSUE TITLE
Unclear about templates

### ISSUE THREAD

**Issue by hutattedonmyarm** [MicrosoftDocs/windows-uwp#1500]
This article is linked by the "Create data bindings" tutorial, but completely fails to show how one would add design time data in an UWP app with templates, like the PhotoLab example given in the UI tutorials

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51100eeb-4a55-5997-eee8-2ed0047be78f
* Version Independent ID: d9d5ad3b-4932-c02f-bac0-4dd5a9dd48fb
* Content: [Sample data on the design surface, and for prototyping - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/displaying-data-in-the-designer)
* Content Source: [windows-apps-src/data-binding/displaying-data-in-the-designer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/displaying-data-in-the-designer.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by GrantMeStrength** [comment]
Thanks for the comment, and sorry for the delay in addressing it. I completely accept your point, but I think that adding design time data is a little outside the scope of this topic, and if anything a new topic should be created. I will talk to the writers who work on that content, and get their input as to whether we can add that to our backlog. To be honest the team is focused on newer content, so nothing will happen in the immediate future. If you did happen to find an applicable sample that helped you, please do let me know and hopefully I can find a way to link to it. Thanks for taking the time to leave feedback, and again, sorry for the delay. We do read bugs as they come in, but may not add comments immediately, which gives a poor impression - I apologize. -John
