### ISSUE TITLE
The sample code for 'private void ContactsListView_Loaded(object sender, RoutedEventArgs e)' is incorrect

### ISSUE THREAD

**Issue by hutattedonmyarm** [MicrosoftDocs/windows-uwp#1501]
It calls "TryStartConnectedAnimationAsync" which doesn't work, because _Loaded is not an asynchronous method

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322c828b-f3a8-9556-1900-37e4f3c3d35b
* Version Independent ID: 24d328ed-89d9-0a9a-f588-f5dbb519c0b8
* Content: [Connected animation - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/design/motion/connected-animation)
* Content Source: [windows-apps-src/design/motion/connected-animation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/connected-animation.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This issue is fixed. Thanks!
