### ISSUE TITLE
Can't find the URI for the Sound Mixer Options

### ISSUE THREAD

**Issue by zersiax** [MicrosoftDocs/windows-uwp#1503]
I am trying to localize the URI for the settings page that lets you set input and output devices for any given app that is producing sound. You can find this page quickly by searching for "sound mixer options" in the start menu or Windows Settings searchbox.
Looking at this URI reference though, I can't find the direct URI for this particular subpage. Is this an omission or does it simply not exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a2ae18-080e-3470-d1c7-ab2990d4da85
* Version Independent ID: 3d0d02af-c1d7-e2e7-ba01-15e0904dc9a6
* Content: [Launch the Windows Settings app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for leaving your feedback. That's a good question. I don't know the answer, but I'll reach out to the team that owns this and see. In the mean time, another good resource to consult is the [Windows developer support center](https://developer.microsoft.com/windows/support). You may be able to get a quicker answer by posting in the forums there while I am working to update this page.

**Comment by knicholasa** [comment]
Hello again, I found the string you are looking for. It should be "ms-settings:apps-volume". When you search for "sound mixer options", the menu that comes up is titled "App volume and device preferences", which is an entry on this page. I'll see about adding a note to avoid future confusion.

**Comment by zersiax** [comment]
Hi,

I just tried this and for me this just opens the main settings screen,
rather than that specific page.
I'm on 1809 if it helps.

Op vr 26 apr. 2019 om 01:37 schreef Nick Adman <notifications@github.com>:

**Comment by knicholasa** [comment]
Ah, yes, I believe this URI was added with 1903.
