### ISSUE TITLE
Wrong Property Attributes name in XAML code

### ISSUE THREAD

**Issue by hadayago** [MicrosoftDocs/windows-uwp#1510]
VisualState have x:Name property attributes instead of x:Key in XAML code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69746a38-2c7a-45f6-765f-2c5801a27193
* Version Independent ID: 64ee3bd3-91f2-018a-8ea7-28ae91e109ce
* Content: [Create adaptive layouts tutorial - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-adaptive-layout#feedback)
* Content Source: [windows-apps-src/design/basics/xaml-basics-adaptive-layout.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-adaptive-layout.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Find/replace x:Key -> x:Name in the VisualStates.

**Comment by jwmsft** [comment]
This appears to be fixed.
