### ISSUE TITLE
Additional Dependencies

### ISSUE THREAD

**Issue by cardalex** [MicrosoftDocs/windows-uwp#1515]
Apparently, it is needed to add:
Advapi32.lib;ole32.lib.;Shell32.lib;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0faf0f08-2ef0-62e2-9a80-ca4f96c15b6b
* Version Independent ID: 29ffa166-ba60-7694-7574-7dac254338f9
* Content: [Author COM components with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-coclasses?view=azure-dotnet#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-coclasses.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-coclasses.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for raising this issue, @cardalex! I've made corrections to the topic; it should be published soon.

~Steve

**Comment by stevewhims** [comment]
The fix is published now, @cardalex. I'll go ahead and close this issue, but please reopen if necessary. Thanks again for finding the problem and letting me know about it! ~Steve
