### ISSUE TITLE
Create Your First App page - broken link

### ISSUE THREAD

**Issue by JonPerkinsOldGit** [MicrosoftDocs/windows-uwp#1517]
This page references the MVA. The link for "A Developer's Guide to Windows 10" leads to a page which reveals a banner saying page no longer available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5244e6a0-7a51-8eac-d776-193dc4368113
* Version Independent ID: cb6cf9cb-e235-9204-4c05-38e767d664ec
* Content: [Create your first app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/your-first-app#feedback)
* Content Source: [windows-apps-src/get-started/your-first-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/your-first-app.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by bartlannoeye** [comment]
There's a banner on MVA mentioning that the resources are boing retired and/or moved.

> To simplify your tech training journey, we are consolidating our learning resources and retiring Microsoft Virtual Academy in phases, with the next phase finishing on April 30, 2019. On that date, courses, learning paths and associated badging are retiring. Complete site retirement is scheduled for later in 2019. Check your MVA Dashboard frequently for courses you have started that are retiring. To earn your certificates of completion, be sure to finish any courses by April 30, 2019. For more learning options, check out [Microsoft Learn](https://docs.microsoft.com/en-us/learn/).

**Comment by QuinnRadich** [comment]
This link was removed a little while ago, thanks for the heads-up. Closing this issue.
