### ISSUE TITLE
URI for installing a specific language/region

### ISSUE THREAD

**Issue by kudobyte** [MicrosoftDocs/windows-uwp#1518]
When clicking "Install/Get" for a  Local Experience Pack from the Windows Store to install a language, it seems like a URI is used to directly bring the user to the language pack to install. 

![screen](https://i.stack.imgur.com/56fzv.png)

However I do not see any documentation on this. Is there an undocumented URI pattern for opening up the installation screen for a specific language/region?

More detail for this question on StackOverflow:
https://stackoverflow.com/questions/54973164/uwp-uri-for-installing-a-specific-language-region

**Comment by ginami** [comment]
Hi @kudobyte -- do we have related doc that touches on this topic? (A URL will help me route your question to the correct author.) Thank you!

**Comment by kudobyte** [comment]
@ginami -- This documentation refers to accessing parts of the Settings app:
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app

However, I was wondering if the Microsoft Store app was using an undocumented URI or any code a developer could use to launch the Settings app like in the picture above (installation of specific language/region). Clicking the Get/Install button for any Local Experience Pack in the Microsoft Store app brings up the respective language installation UI in Settings.

**Comment by knicholasa** [comment]
Hi @kudobyte, sorry this was open for so long. For these kinds of support questions, I route people to our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions), and it looks like you got an answer on StackOverflow. For those reading this thread, the answer was that there's no such URI for you to do it but you can submit a Feature Request on [WPDev UserVoice](https://wpdev.uservoice.com/).

However, I will follow up with the feature team to double check that we are not missing documentation for said URI.

**Comment by kudobyte** [comment]
Thanks! Added request on WPDev UserVoice: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/37013110-settings-uri-for-installing-a-specific-language-re
