### ISSUE TITLE
Just share the link of the Figma tookit, not extract it's version as a .fig file every damn time

### ISSUE THREAD

**Issue by Mancerrss** [MicrosoftDocs/windows-uwp#1519]
Figma is cloud based, so why not just share y'alls Master Figma file link to the world, so every revision or update it already delivered to us. Make sure to keep it just "view only", for us to be able to edit, and copy on it, we need to duplicate it. Publish also the Styles and Components in Team Library, so we can opt in and turn it on our own files, and use the styles and drag out components directly on our files without going into your documents first. Styles & components updates can be agreed to be updated once y'alls modified or changed it up a little bit, or ignore it for now. For whole UI kit updates, there's no real way for it to keep updated in real time but only keep checking the Master file (once the link is clicked and you're signed in on Figma, the Master UI toolkit file will automatically be added to your Drafts), duplicate it and delete the old toolkit file

**Please just stop sharing .fig file instead. And just share the link for all of us and utilize Figma's cloud feature**

**Also please keep updating the Figma toolkit, even Sketch toolkit is still way behind, it looks like y'alls are just no focusing on Adobe XD instead. Please close the version gap between those**
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fc7b1d-8b97-598a-f059-093d94972931
* Version Independent ID: 943e9c97-f223-4d3c-730c-a7f20cb04560
* Content: [Design toolkits and samples for UWP apps - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/design/downloads/#feedback)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by GrantMeStrength** [comment]
Thanks for your feedback!

As of last month, we share the library - https://aka.ms/figmatoolkit

cheers! 

-john
