### ISSUE TITLE
Minor typo in WriteTimestamp() method

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/windows-uwp#1520]
A minor typo in `WriteTimestamp()` method. I think `CreateCollisionOption` should be `CreationCollisionOption`.
Ref: https://docs.microsoft.com/en-us/uwp/api/windows.storage.creationcollisionoption

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9a5cd25-def9-18f4-71f4-ecdfa83d03d6
* Version Independent ID: acfde4a4-e53b-0adb-d1fc-179f9c055553
* Content: [Store and retrieve settings and other app data - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#feedback)
* Content Source: [windows-apps-src/design/app-settings/store-and-retrieve-app-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/app-settings/store-and-retrieve-app-data.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@saf-itpro Thank you for calling this to our attention! We submit public contributions--would you be willing to submit the typo fix? Just click the "edit" button on the page with the typo.

**Comment by saf-itpro** [comment]
@mijacobs I've made the change.
