### ISSUE TITLE
Closing a new Window created with WindowsXamlHost

### ISSUE THREAD

**Issue by chanallenk** [MicrosoftDocs/windows-uwp#1521]
I am trying to create a second Window also with another hosted control in my WPF app. I got the error about it attaching to a window on a different top level, so I created a thread to open this new child window. That solved my issue and allowed me to create a second WindowsXamlHost. 

However, when closing this new window, I get the error "Unhandled exception at 0x768E9931 (combase.dll) in MyApp.WPF.Core.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x171A21E8, 0x00000002)." 

This error occurs when using certain controls in the parent window, like a NavigationView. Once I exit the child window and return to the parent window, which holds the NavigationView, if I interact with it (like a mouse hover or click), an error similar to the one above will get thrown. This seems like a bug in the XamlHost itself, since I was able to reproduce it with a new project.

Below is the code I use to open a new window:

```
Thread windowThread = new Thread(delegate ()
{
	SynchronizationContext.SetSynchronizationContext(
		new DispatcherSynchronizationContext(
			Dispatcher.CurrentDispatcher));

	SettingsDialogWindow dialog = new SettingsDialogWindow()
	{
	};
	dialog.Closed += (s, args) => Dispatcher.CurrentDispatcher.BeginInvokeShutdown(DispatcherPriority.Background);
	dialog.Show();
	Dispatcher.Run();

});
windowThread.SetApartmentState(ApartmentState.STA);
windowThread.Start();
	
```
Here is the code for my first hosted control, which is under the parent window.

```
<uwpHost:WindowsXamlHost Panel.ZIndex="0"
    ChildChanged="WindowsXamlHost_ChildChanged"
    InitialTypeName="Windows.UI.Xaml.Controls.NavigationView"/>

```

Here is the code for my second hosted control, which is in the new child window that opens. It doesn't really matter what control is here, so long as I am using another WindowsXamlHost

```
<uwpHost:WindowsXamlHost Panel.ZIndex="0"
    ChildChanged="WindowsXamlHost_ChildChanged"
    InitialTypeName="MyApp.UWP.Views.Core.SettingsUserControl"/>

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4665391f-f838-ae07-8591-d8f13f41a027
* Version Independent ID: 38b6b8ed-c3d2-97b1-9852-e3779b3ea281
* Content: [Using the UWP XAML hosting API in a desktop application - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/using-the-xaml-hosting-api#feedback)
* Content Source: [windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
This sounds like a product bug. Can you open this issue in https://github.com/windows-toolkit/Microsoft.Toolkit.Win32 ?

**Comment by chanallenk** [comment]
@jevansaks Somehow this thread got copied over from the toolkit to the UWP. It has since been resolved in the toolkit so I'm closing this issue. Thank you.
