### ISSUE TITLE
URL 404 for "operator to std::wstring_view"

### ISSUE THREAD

**Issue by BarryWangMSDN** [MicrosoftDocs/windows-uwp#1522]
The following part contains a 404 URL:
But, again, being aware of that detail is optional thanks to hstring's conversion operator to std::wstring_view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e675be32-8d47-29be-435b-c430d81a9225
* Version Independent ID: 780ecdcf-c388-1b4f-6fe6-c02b44ba6e8a
* Content: [String handling in C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/strings)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/strings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/strings.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for finding and reporting this broken link, @BarryWangMSDN! I've just published a fix to the topic. I'll go ahead and close this issue now. Thanks again! :) ~Steve
