### ISSUE TITLE
C# examples are missing

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#1524]
You have C++ examples here, but no C#? How can I use DirectX interoperation from C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49b9ea5-88b8-588b-ad4b-8fc947824047
* Version Independent ID: 3d004427-c466-c760-f8e2-118ab08d0006
* Content: [Composition native interoperation - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/composition-native-interop)
* Content Source: [windows-apps-src/composition/composition-native-interop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/composition-native-interop.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
C# can't do this because it requires including native headers to interop with DX. The recommendation would be to have a native WinRT component in your C# app if you wanted to do that.
