### ISSUE TITLE
Should add link to Contract Version List

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1525]
It'd be nice to add a link in the Related Articles to the list of API contract versions [similar to this one](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk) so that it's easier to match up what version 'number' is needed and matches to which other features/sdks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4adf9e3-46b9-732a-7659-07d34a9ff469
* Version Independent ID: 0dd55994-fed9-6d25-38c8-85e1ee2322ff
* Content: [Conditional XAML - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml)
* Content Source: [windows-apps-src/debug-test-perf/conditional-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/conditional-xaml.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by jevansaks** [comment]
This is a reasonable ask. That's the first time I've seen that contracts page ... that one could use some help.

**Comment by jwmsft** [comment]
This link has been added.
