### ISSUE TITLE
Fluent XAML Theme Editor on the MS Store

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/windows-uwp#1526]
Is there any plan to make the Fluent XAML Theme Editor a Store app? Just like the XAML Controls Gallery? This will make it easy to share the app with designers, instead of creating a package to give them to sideload the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fc7b1d-8b97-598a-f059-093d94972931
* Version Independent ID: 943e9c97-f223-4d3c-730c-a7f20cb04560
* Content: [Design toolkits and samples for UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#feedback)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by kikisaints** [comment]
It already is! You can [install it here](https://www.microsoft.com/p/fluent-xaml-theme-editor/9n2xd3q8x57c?activetab=pivot%3Aoverviewtab).
