### ISSUE TITLE
Missing dark theme in Adobe XD design toolkit

### ISSUE THREAD

**Issue by svyatoslavdcode** [MicrosoftDocs/windows-uwp#1527]
Missing dark theme in Adobe XD design toolkit (v1901, January 2019). So, please, fix it, because it's hard to design something without one.

**Comment by Mancerrss** [comment]
On Figma toolkit too, which is still stuck on v1810, contrary to XD's version v1901, which is the most updated of all, still don't have Dark theme components too, it do have Dark color fill on Figma Styles tho

**Comment by chigy** [comment]
@Mancerrss , VD version does not contain any new information than Figma version. They are the same. As far as I am aware, there is no immediate plan to release dark theme design kit. Say, what is your reason for using the design kit? Are you using to see how the controls appear on dark theme or are you actually using these design kit to create design UI? If former, I may have a suggestion for you to work around this issue.
