### ISSUE TITLE
Error loading .SLN in Visual Studdio 2017

### ISSUE THREAD

**Issue by SheiksBeer** [MicrosoftDocs/windows-uwp#1531]
Hello
Loading Samples (.sln file) produces errors:
e.g. for the BASICINPUTS solution:
D:\PROJECTS\Samples\BasicInput\cs\BasicInput.csproj : error  : The imported project "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\VS17\MSBuild\Microsoft\WindowsXaml\v15.0\8.21\Microsoft.Windows.UI.Xaml.Common.targets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf00961f-a83a-def3-00df-0d4b117fa572
* Version Independent ID: 14aa80b5-bb07-b22c-3174-b2f9b7f66ad5
* Content: [Get UWP app samples - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-uwp-app-samples#feedback)
* Content Source: [windows-apps-src/get-started/get-uwp-app-samples.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/get-uwp-app-samples.md)
* Product: **uwp**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by bartlannoeye** [comment]
@SheiksBeer you need the 1809 SDK installed, see https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk
