### ISSUE TITLE
SVG is recommended for custom icons but no mention of how to embed SVG

### ISSUE THREAD

**Issue by radev8** [MicrosoftDocs/windows-uwp#1532]
'SVG resources are ideal for icons, because they always look sharp at any size or resolution.' Great, but how do you use a SVG file.  An example using a SVG file and how it is created as a resource and use on the page would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1666072a-88f4-45e9-ede0-414fe8ef61e5
* Version Independent ID: ed5e311a-c7e6-7eba-0ae6-48f3bbcb6b12
* Content: [Icons - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/icons)
* Content Source: [windows-apps-src/design/style/icons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/icons.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
@jesbis do you know who owns this?

**Comment by jesbis** [comment]
For more information you can see the remarks under SvgImageSource:
https://docs.microsoft.com/uwp/api/windows.ui.xaml.media.imaging.svgimagesource

We'll update the page with links for fonts and SVG.

**Comment by radev8** [comment]
Thankyou.  That was what I was looking for.  Also I was using windows version 1609 and upgraded to version 1709 which now includes this.
