### ISSUE TITLE
Order of capabilities matters and is not explained

### ISSUE THREAD

**Issue by pierresa** [MicrosoftDocs/windows-uwp#1535]
If I put restrictedcapability after devicecapability I have an error
 &lt;Capabilities&gt;
    &lt;Capability Name="internetClient" /&gt;
    &lt;rescap:Capability Name="confirmAppClose" /&gt;
    &lt;uap:Capability Name="picturesLibrary" /&gt;
    &lt;uap:Capability Name="removableStorage" /&gt;
    &lt;uap:Capability Name="videosLibrary" /&gt;
    &lt;uap4:Capability Name="offlineMapsManagement" /&gt;
    &lt;DeviceCapability Name="location" /&gt;
    
  &lt;/Capabilities&gt;
works but if I change the order it fails. Documentation should explain constraints or handling should be fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#feedback)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. You are correct, and all DeviceCapability elements must come after any and all Capability elements (including restricted Capability elements) under Capabilities. I have added a note to the "Device capabilities" section of this article and several other related articles to capture this requirement. These doc updates should be published in the next day or so.
