### ISSUE TITLE
"The size of the data you may pass is only limited by system resources."

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/windows-uwp#1537]
Limit is for single Value, or/and for total size of Values?
Is there any method to check how big data I can send?
It seems like limit is below 64 KiB; and this is limit for ValueSet. Although valueSet.Add doesnt produce error/exception, nor Request.SendResponseAsync - but on receiving side, AppServiceConnection.SendMessageAsync(oInputs) doesnt return.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edde9dbc-6e04-69cf-206e-123792666abf
* Version Independent ID: 9894e78f-3270-9485-4769-11050669b805
* Content: [Create and consume an app service - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service#feedback)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support. I will follow up about updating the docs to answer the questions you posed, but in the mean time you may have success posting your question in the [developer support forums](https://developer.microsoft.com/en-us/windows/support), where other developers and Microsoft engineers can be found. The community there is quite responsive.
