### ISSUE TITLE
Clarify of Contents

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/windows-uwp#1538]
Does this Example from https://stefanwick.com/2018/10/01/app-elevation-samples-part-1/ 
consider in this Package desktop applications &gt; Prepare to package section.

Does the following mean:
Your application always runs with elevated security privileges. Your application needs to work while running as the interactive user. Users who install your application from the Microsoft Store may not be system administrators, so requiring your application to run elevated means that it won't run correctly for standard users. Apps that require elevation for any part of their functionality won't be accepted in the Microsoft Store.

My Interpretation:
Apps that require elevation for any part of their functionality won't be accepted in the Microsoft Store except your declare it as the example from https://stefanwick.com 's App Elevation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af8cc5b-6a98-bd70-6b5f-97f9fbd6362b
* Version Independent ID: eddd9517-bbf4-456d-bb62-a615f821ff91
* Content: [Prepare to package a desktop application (Desktop Bridge) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-prepare.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-prepare.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Unfortunately, apps that require elevation will not be accepted regardless of how it is declared.
