### ISSUE TITLE
Windows version support missing - ms-settings: URI scheme reference

### ISSUE THREAD

**Issue by mfe-** [MicrosoftDocs/windows-uwp#1539]
Some setting pages were introduced with certain versions of Windows. It'd be nice for this "ms-settings: URI scheme reference" table to display the minimum version required to start the uri page successful.

For example: ms-settings:appsfeatures-app - as far as i know this page exists since 16299?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for the feedback. I've reached out to the dev team associated with this page to see about updating it with that information.
