### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/windows-uwp#1540]
&gt; Conveience vs. control
Should be Convenience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8132995-4d33-d547-f743-37cd3b3f15c4
* Version Independent ID: 19465bc3-648d-6576-ea62-5b23b50531d5
* Content: [Best practices for writing to files - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/best-practices-for-writing-to-files)
* Content Source: [windows-apps-src/files/best-practices-for-writing-to-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/best-practices-for-writing-to-files.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for catching that! I'll update the doc.
