### ISSUE TITLE
C++/WinRT

### ISSUE THREAD

**Issue by egyik** [MicrosoftDocs/windows-uwp#1541]
It would be really great if all these pages documenting UWP could show C++/WinRT sample code. Unless it's made easy for people to get going C++/WinRT takeup is going to be very slow and it may fail to take off entirely. Good documentation with code samples is essential.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24777eff-7485-a1ba-17b8-d56547bbd26d
* Version Independent ID: c5da8413-6441-3d07-4b84-02f145336771
* Content: [Menus and context menus - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus)
* Content Source: [windows-apps-src/design/controls-and-patterns/menus.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/menus.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @egyik, thanks for filing this issue.

We don't provide example code in every language, but the fact that you're asking in this case means that there's a demand, so I'll take that into account with my planning and my TODO list. 

FYI, the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) documentation covers all kinds of techniques around using C++/WinRT in general. Handling events, authoring and consuming APIs, asynchronous patterns, some topics specifically about XAML, and so on. There are plenty of code examples in there showing all kinds of techniques. And there's the [C++/WinRT API reference content](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/winrt), too. It's likely that the content there will be all you need to get started with menus. If you come across any specific scenarios or APIs that are challenging to use with a given feature area, then please let me know, and I'll see whether I can provide C++/WinRT code for them and/or fill any doc gaps.

~Steve

**Comment by stevewhims** [comment]
@egyik, have you run into any specific blockers with using the C++/WinRT language projection with these APIs? ~Steve

**Comment by stevewhims** [comment]
Hi, @egyik, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
