### ISSUE TITLE
Typo in "Horizontal slide"

### ISSUE THREAD

**Issue by BYTEzel** [MicrosoftDocs/windows-uwp#1542]
These lines throw an error:
// Navigate to the right, ie. from LeftPage to RightPage
myFrame.Navigate(typeof(RightPage), null, new SlideNavigationTransitionInfo() { SlideNavigationTransitionEffect.FromRight } );

// Navigate to the left, ie. from RightPage to LeftPage
myFrame.Navigate(typeof(LeftPage), null, new SlideNavigationTransitionInfo() { SlideNavigationTransitionEffect.FromLeft } );

In my opinion, the value SlideNavigationTransitionEffect.From* has to be assigned to a value -&gt;

// Navigate to the right, ie. from LeftPage to RightPage
myFrame.Navigate(typeof(RightPage), null, new SlideNavigationTransitionInfo() { Effect = SlideNavigationTransitionEffect.FromRight } );

// Navigate to the left, ie. from RightPage to LeftPage
myFrame.Navigate(typeof(LeftPage), null, new SlideNavigationTransitionInfo() { Effect = SlideNavigationTransitionEffect.FromLeft } );

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 276c7170-7ee8-4e86-302e-2b8e2a1303da
* Version Independent ID: a4dd6f9f-b368-462d-bdb6-6b73d6856e13
* Content: [Page transitions in UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/motion/page-transitions#horizontal-slide)
* Content Source: [windows-apps-src/design/motion/page-transitions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/page-transitions.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@stmoy samples don't compile, can you please fix?

**Comment by stmoy** [comment]
Thanks for reporting this. The typo has been fixed: https://docs.microsoft.com/en-us/windows/uwp/design/motion/page-transitions#horizontal-slide
