### ISSUE TITLE
Unable to download cab files

### ISSUE THREAD

**Issue by rAndom69** [MicrosoftDocs/windows-uwp#1543]
With method mentioned in pre-requisites (service-to-service accessToken) cab files are inaccessible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f2fb52-7ef8-f814-1b92-ce99f7e3207c
* Version Independent ID: 646c23dc-bf65-f574-4b24-e465ef1a9933
* Content: [Download the CAB file for an error in your desktop application - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/download-the-cab-file-for-an-error-in-your-desktop-application#feedback)
* Content Source: [windows-apps-src/monetize/download-the-cab-file-for-an-error-in-your-desktop-application.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/download-the-cab-file-for-an-error-in-your-desktop-application.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by adammarks** [comment]
Related to this issue https://github.com/MicrosoftDocs/windows-uwp/issues/1428

**Comment by rAndom69** [comment]
Per https://github.com/MicrosoftDocs/windows-uwp/issues/1428#issuecomment-496971460

Please document API is currently not usable as per MS statement so others don't spend time chasing non-existant functionality (or submit "feature" request). This holds for both UWP and Desktop, we don't develop for XBox so unable to verify.

Another edit should be in documentation where cabDownloadable is present. cabDownloadable does not represent "real" state, but only state of API (i.e. the cake is a lie). cabDownloadable=False could still mean cab is actually downloadable from partner center (although not programmatically).

**Comment by QuinnRadich** [comment]
Apologies in the long delay in engaging with this issue.

Investigating the linked and related issue, it seems like this functionality here has been long since fixed. I'll be closing this issue for now. If there are any problems that still persist, I'd encourage you to open a new issue that's up-to-date with those necessary doc fixes.

Thank you.
