### ISSUE TITLE
OneWayToSource

### ISSUE THREAD

**Issue by cpuwzd** [MicrosoftDocs/windows-uwp#1544]
This document does not mention "OneWayToSource". Has this feature been deprecated or deleted? I use this mode and am having trouble due to the nature of the "ConvertBack" function. I can't figure out how the framework sets the value parameter of this function. From observation, it appears to set this parameter to the default value for the Target type, rather than the actual Target value. This gets converted to the Source type by ConvertBack and ultimately results in ignoring the initial value of both the Source and Target objects. The documentation for ConvertBack, in fact, says: "Modifies the target data before passing it to the source object. This method is called only in TwoWay bindings." I suppose, by extension, based on the elision of OneWayToTheSource from the documentation, that I should expect it to also apply to OneWayToTheSource.

If the gist of my observation is meaningful, might I ask how this is useful? I have no idea how to decide which end of a TwoWay binding should the common (at least, equivalent) value to be shared after the binding operation, but I know that the current situation is dead wrong for the OneWayToSource mode.

Just to set some perspective, I am doing the binding in code, not in XAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f752d7-062a-4935-02c6-48371c208792
* Version Independent ID: daa135bb-7f77-3e62-05da-b18a9bfcdf12
* Content: [Data binding in depth - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-in-depth)
* Content Source: [windows-apps-src/data-binding/data-binding-in-depth.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/data-binding-in-depth.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support. I will follow up about that topic you mentioned that is missing from the docs, but in the mean time you may have success posting your question in the [developer support forums](https://developer.microsoft.com/en-us/windows/support), where other developers and Microsoft engineers can be found. The community there is quite responsive.

**Comment by knicholasa** [comment]
After investigating I have a follow up. This article is about UWP data binding, which you’ll find in the [Windows.UI.XAML.Data](https://docs.microsoft.com/uwp/api/windows.ui.xaml.data) namespace. The [UWP BindingMode enum](https://docs.microsoft.com/uwp/api/windows.ui.xaml.data.bindingmode) does not have the OneWayToSource value, which is why the article doesn’t talk about it. I'll update the language on the page to make this more clear.
