### ISSUE TITLE
Instructions do not follow the Partner Center content site

### ISSUE THREAD

**Issue by DarinMacRae** [MicrosoftDocs/windows-uwp#1548]
Several of the instructions say:

From Partner Center, select the gear icon (near the upper right corner of the dashboard) and then select Developer settings. In the Settings menu, select Tenants.

But there isn't any gear icon showing up on the Partner Center site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1603df77-580d-a332-ace4-10c4b6f1484b
* Version Independent ID: 7f70b8d6-5146-f327-86c8-9c17acbcac23
* Content: [Associate Azure Active Directory with your Partner Center account - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-partner-center#associate-your-partner-center-account-with-your-organizations-existing-azure-ad-tenant)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-partner-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-partner-center.md)
* Product: **uwp**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
You must be logged in to your Partner Center account at https://partner.microsoft.com/dashboard to see this icon. If you're not seeing it there, please open a support request at https://aka.ms/storesupport.

**Comment by DarinMacRae** [comment]
I *was* logged on. I tried multiple browsers. The gear icon never showed up until the owner of the PC account that my company uses added me to the account. The documentation does not explain this requirement at all and it cost me and my team quite a bit of time trying to figure out why no gear icon was showing for us.

**Comment by lauradolan** [comment]
Thanks for your feedback. The article does state "Any user with the Manager role in the Partner Center account will have the option to add and remove Azure AD tenants from the account.  We'll look into how we can make the doc clearer.
