### ISSUE TITLE
Self-signed certificate needs additional parameters to be valid for appx signing

### ISSUE THREAD

**Issue by mcooley** [MicrosoftDocs/windows-uwp#1552]
The New-SelfSignedCertificate example is not sufficient to create a key which can be used to sign a package. As mentioned in the [older documentation here](https://docs.microsoft.com/en-us/previous-versions/br230260(v=vs.110)) the certificate needs to have some additional constraints. Basic constraints must be unset or set to "Subject Type=End Entity", and the EKU extension should be set to "Code Signing". To generate certificate with these properties in PowerShell, some additional parameters to New-SelfSignedCertificate are necessary. This worked for me:

```
New-SelfSignedCertificate -Type Custom -Subject "CN=Contoso Software, O=Contoso Corporation, C=US" -KeyUsage DigitalSignature -FriendlyName <Your Friendly Name> -CertStoreLocation "Cert:\LocalMachine\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd5249b-0ba4-fa7c-af15-a6de69c8461c
* Version Independent ID: b4854066-e025-2cd7-0f2e-cd1be527374a
* Content: [Create a certificate for package signing - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/create-certificate-package-signing#feedback)
* Content Source: [windows-apps-src/packaging/create-certificate-package-signing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/create-certificate-package-signing.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback! I will investigate your suggestion with the engineering team who owns this feature area and I will update this issue when I have a resolution.

**Comment by mcleanbyron** [comment]
I confirmed your findings and updated the article with a more complete example and details about the -TextExtension parameter to add the EKU=code signing and basic constraints=end entity extensions. Thanks for your feedback and helping us improve the docs!
