### ISSUE TITLE
Advice regarding AlphaMode is wrong.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#1555]
Docs say "You can't set the DirectX swap chain's alpha mode to DXGI_ALPHA_MODE_PREMULTIPLIED.". This isn't true. AlphaMode for swapchain can be set to Premultiplied without issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b263a91c-cfc3-2457-196f-ab9c74b14a5f
* Version Independent ID: bc2cd244-bd4d-b294-c787-12fb2a2ad373
* Content: [DirectX and XAML interop - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop)
* Content Source: [windows-apps-src/gaming/directx-and-xaml-interop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/directx-and-xaml-interop.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams. I'm really sorry for the long delay in responding, and thanks for filing this issue.

I've contacted the feature team for confirmation as to whether, and when, DXGI_ALPHA_MODE_PREMULTIPLIED is supported for UWP XAML apps. It looks, from my superficial testing, like it is. But once I have confirmation I'll update the docs, so I'll leave the issue open until then.

Thanks again!
-Steve

**Comment by stevewhims** [comment]
UPDATE: The limitation was removed in the Windows 8.x timeframe so, since the current docs reflect Windows 10, I've removed that obsolete limitation from the topic. Expect to see that show up on the live site within a day.

Thanks again!
Steve
