### ISSUE TITLE
Windows namespace missing

### ISSUE THREAD

**Issue by profgyuri** [MicrosoftDocs/windows-uwp#1558]
There is literally no windows namespace, update required!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad92e4b2-c0cf-cb46-4eab-eabdea8ab0d1
* Version Independent ID: 1097c7e1-25aa-273b-5748-75d53e4eaae1
* Content: [Capture photos and video with Windows built-in camera UI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-photos-and-video-with-cameracaptureui#feedback)
* Content Source: [windows-apps-src/audio-video-camera/capture-photos-and-video-with-cameracaptureui.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/capture-photos-and-video-with-cameracaptureui.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by jaigak** [comment]
Try installing C++/WinRT nuget package for C++ apps or Windows.SDK.Contracts for .NET based apps.
For UWP apps, it is preincluded.

**Comment by bisdeep** [comment]
I looked for hours and I FINALLY found this: https://blogs.windows.com/windowsdeveloper/2017/01/25/calling-windows-10-apis-desktop-application/#vZiZ96PlZUqTduts.97

**Comment by drewbatgit** [comment]
Thanks for the feedback on the docs, and to the other users that offered guidance. These docs were originally authored to be targeted exclusively for UWP app development. As Microsoft is opening these features up to be used in more types of apps, we will need to provide guidance for other platforms. We are in a planning phase right now to determine the best way to do this across the docs. For now, there is high-level guidance about working with UWP APIs in desktop apps, here:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance

That article should be a little more up to date than the blog post linked above. Thanks again for helping us to improve the documentation.
