### ISSUE TITLE
Printing?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#1561]
The PhotoEditor seems not to include printing capability. It would be really useful to have available some example code demonstrating printing from a C++/winrt app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f730731-e97d-a8e6-a344-a4906980ad64
* Version Independent ID: 5d99f618-f4de-8ed3-46d7-634df5105228
* Content: [Photo Editor C++/WinRT sample application - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/photo-editor-sample)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/photo-editor-sample.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/photo-editor-sample.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @jevansAN. Rather than bundling that into an existing sample application, how would you feel about adding C++/WinRT versions of the C# in-topic code examples here? https://docs.microsoft.com/windows/uwp/devices-sensors/print-from-your-app?

~Steve

**Comment by jevansAN** [comment]
Steve,

	That would be helpful,, certainly, since C++/winrt is apparently encouraged for new projects.
	Though I”ve figured out some of this and may have an issue here that wouldn’t be covered  by that sample: I’m trying to print the content of a CanvasVIrtualControl, which forms the content of a ScrollViewer in this music application. The CanvasVirtualControl doesn’t seem to work as a source in the print document. The print preview comes up blank and VS throws an obscure error, 0x80040155 Failed to find proxy registration for IID: ...
	I’m wondering if perhaps CanvasVirtualControl is not a UIElement acceptable as a source. In which case I’d need a whole different kind of documentation showing how to print Win2D. 
	Surely there is a way to print the content of CanvasVirtualControl; I’d love to know if it can be done via the techniques in those PrintManager docs.

	Thanks, Jeff


On Mar 28, 2019, at 7:01 PM, Steven White <notifications@github.com> wrote:

Thanks, @jevansAN <https://github.com/jevansAN>. Rather than bundling that into an existing sample application, how would you feel about adding C++/WinRT versions of the C# in-topic code examples here? https://docs.microsoft.com/windows/uwp/devices-sensors/print-from-your-app <https://docs.microsoft.com/windows/uwp/devices-sensors/print-from-your-app>?

~Steve

**Comment by jevansAN** [comment]
Steven,

	The more I look, the more it appears that the Print-from-your-uwp-app instructions are almost completely wrong if the content is coming from a CanvasControl or CanvasVirtualControl. I’m trying to figure out how it would work; if I have any success I can let you know. But I think this really needs a separate set of print docs from MS.

	Thanks, Jeff
 

On Mar 28, 2019, at 7:01 PM, Steven White <notifications@github.com> wrote:

Thanks, @jevansAN <https://github.com/jevansAN>. Rather than bundling that into an existing sample application, how would you feel about adding C++/WinRT versions of the C# in-topic code examples here? https://docs.microsoft.com/windows/uwp/devices-sensors/print-from-your-app <https://docs.microsoft.com/windows/uwp/devices-sensors/print-from-your-app>?

~Steve

**Comment by stevewhims** [comment]
Hi, @jevansAN, I think the best way to proceed here is to leave feedback on the printing documentation. That way, the writer who owns those docs will see that and they'll be able to triage the ask. Then, once it's been figured out how to achieve the specific task you're doing, and if there's code for that in at least one language, then, at that time, I'll be able to drop in and port that language to C++/WinRT. ~Steve

**Comment by jevansAN** [comment]
OK - I’ve put a comment on the print-from-your-uwp-app docs. Maybe that can start something. Using a CanvasControl instead of a UIControl as the source invalidates a lot of that description.

Thanks, Jeff


On Apr 1, 2019, at 2:07 PM, Steven White <notifications@github.com> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, I think the best way to proceed here is to leave feedback on the printing documentation. That way, the writer who owns those docs will see that and they'll be able to triage the ask. Then, once it's been figured out how to achieve the specific task you're doing, and if there's code for that in at least one language, then, at that time, I'll be able to drop in and port that language to C++/WinRT. ~Steve

**Comment by stevewhims** [comment]
Great! I can see that comment, and it's assigned to the topic owner. I'll probably end up working with them on the C++ piece. I'll go ahead and close this now; I do think that making progress on the new issue is the right way to go about this. Thanks! ~Steve

**Comment by jevansAN** [comment]
Steven,

	I pretty much have the print and print preview worked out for C++/Winrt but there is a gap in the documentation for CanvasPrintDocument and those pages have no invitation to comment. Perhaps I can pass one through you?
	The problem is that the crucial end of a sentence is missing on the following page

https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Printing_CanvasPrintDocument.htm

	I’m trying to find out how to tell in the Print event which page is to be printed, so that the app knows to draw that page. In the Preview event the args tell the page, but the Print event args do not contain that page number property. The above-mentioned doc seems like it’s about to tell how this works, but the sentence ends at “using” :

The application can then draw each page in turn using

	Thanks, Jeff


On Apr 1, 2019, at 2:56 PM, Steven White <notifications@github.com> wrote:

Closed #1561 <https://github.com/MicrosoftDocs/windows-uwp/issues/1561>.

**Comment by stevewhims** [comment]
Hi, Jeff, since that topic is a Win2D topic, here's the place to file an issue with Win2D: https://github.com/Microsoft/Win2D/issues. I would use that same resource (the green New Issue button at the top) for issues with the content, too. ~Steve

**Comment by jevansAN** [comment]
Thanks. When I finally finish this I’ll have material for a how-to book. But no time to write one.

Jeff


On Apr 8, 2019, at 1:15 PM, Steven White <notifications@github.com> wrote:

Hi, Jeff, since that topic is a Win2D topic, here's the place to file an issue with Win2D: https://github.com/Microsoft/Win2D/issues <https://github.com/Microsoft/Win2D/issues>. I would use that same resource (the green New Issue button at the top) for issues with the content, too. ~Steve
