### ISSUE TITLE
Verb missing?

### ISSUE THREAD

**Issue by I-B-B** [MicrosoftDocs/windows-uwp#1567]
[It would appear that there is a simple verb missing in the phrase "ability to a Windows.UI.Composition surface." Is this meant to read "ability to _connect to_ a Windows.UI.Composition surface?"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e7d28c-129b-b640-7eac-f0c1807a346c
* Version Independent ID: 300d1f3b-a48a-e472-e100-97b21074585f
* Content: [Play audio and video with MediaPlayer - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer#feedback)
* Content Source: [windows-apps-src/audio-video-camera/play-audio-and-video-with-mediaplayer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/play-audio-and-video-with-mediaplayer.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this and helping improve the quality of our documentation. The correct verb was: "the ability to render video frames to a Windows.UI.Composition surface". This has been fixed in the source and should appear on the live site within ~24 hours.
