### ISSUE TITLE
Poster art aspect ratio incorrect

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/windows-uwp#1568]
The poster art section says 9:16 Poster art (720 x 1080 or 1440 x 2160 pixels). However, this is contradictory since the dimensions given are 2:3, not 9:16. I think the dimensions, rather than the ratio, are correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c806b00b-2775-bffd-54a8-8c564b80eb44
* Version Independent ID: 8b176274-ef89-ff27-140f-29a6193843a4
* Content: [App screenshots, images, and trailers - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-screenshots-and-images)
* Content Source: [windows-apps-src/publish/app-screenshots-and-images.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-screenshots-and-images.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I've checked with the team and will update when I have more information

**Comment by hickeys** [comment]
Thanks for catching this. The resolutions were correct; the aspect ratio was wrong. I've updated the docs.
