### ISSUE TITLE
Add VB sample to screen-capture.md

### ISSUE THREAD

**Issue by Nukepayload2** [MicrosoftDocs/windows-uwp#1572]
PR: #1571

**Comment by ginami** [comment]
Hi @Nukepayload2 -- thanks for your feedback. Which doc did you want to add this sample to?

**Comment by Nukepayload2** [comment]
@ginami 
I'm contributing a VB sample to https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture

**Comment by drewbatgit** [comment]
I just tested and approved the PR for this sample code addition.
