### ISSUE TITLE
Sample code, running this Screen Capture api from Visual C++ Windows Desktop Application

### ISSUE THREAD

**Issue by jtg-gg** [MicrosoftDocs/windows-uwp#1573]
I am trying to call this api from Visual C++ Windows Desktop Application
but having issue running it from "UI Thread"
any reference sample code for this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#feedback)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, there a section called "Programming with thread affinity in mind" in this article:

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency

It mentions calling UWP APIs on the UI thread from C++/WinRT. Let me know if this helps with your scenario.

**Comment by oldnewthing** [comment]
For Win32, create the `GraphicsCapturePicker`, and then use [the `IInitializeWithWindow::Initialize` method](https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/nf-shobjidl_core-iinitializewithwindow-initialize) to associate it with your window. Once that's done, you can call `PickSingleItemAsync`.

**Comment by oldnewthing** [comment]
A fix for this (and other classes affected by IInitializeWithWindow) is coming to the docs. Thanks for calling it out.

**Comment by jtg-gg** [comment]
Thank you @drewbatgit The "Programming with thread affinity" article is not helpful, for my case
@oldnewthing pointer is very useful, though I need convert my app into ComPtr style
sad think is, this api doesn't work on home edition :(

I need an api that works on both home / pro / enterprise capturing UWP apps

**Comment by oldnewthing** [comment]
You can use any COM library you like, you don't have to use ComPtr. And you don't have to convert the entire app, just the part that plugs in the HWND. You don't even have to use any library at all; you could just work with raw pointers if you prefer. 

(I didn't think this API changed behavior on Home SKU, but I'm not the expert for that part.)

**Comment by krenner** [comment]
Hello -  A quick FYI that WindowGraphicsCapture supports Home editions in builds 1809 or greater.  We should update the docs to note this addition.

**Comment by oldnewthing** [comment]
Isn't that already implied by "Starting in Windows 10, version 1803"?

**Comment by jtg-gg** [comment]
any official sample code to handle D3D device removed / lost during window capture ?
TryGetNextFrame is currently throwing an exception, I am wondering how to properly handle this
currently I can't catch the exception, hence it is just crashing, no way to recover from the exception

here is the log:

D3D11: Removing Device.
Exception thrown at 0x76C33572 (KernelBase.dll) in .exe: WinRT originate error - 0x887A0005 : 'The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.'.

Exception thrown at 0x76C33572 in .exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x3817F6A8.

Unhandled exception at 0x757EE6EB (ucrtbase.dll) in .exe: Fatal program exit requested.

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
