### ISSUE TITLE
Need different instructions for CanvasControl and CanvasVirtualControl?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#1575]
It looks like the above instructions don't apply in full if the source is a CanvasControl. Would be great to see a similar set of instructions taking that possibility into account for a UWP app - especially if it were presented for C++/winrt. CanvasControl apparently requires a CanvasPrintDocument, and the CanvasPrintDocument does not carry events like Paginate, etc. described here and in the UWP print sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e904e1-c37c-668a-12a2-1c723cb0ac09
* Version Independent ID: e704bc94-c2dc-7c99-0345-4d704194da9d
* Content: [Print from your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app)
* Content Source: [windows-apps-src/devices-sensors/print-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/print-from-your-app.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by StephenLPeters** [comment]
This is a Win2D issue, could you open an issue on their repo? https://github.com/microsoft/Win2D

**Comment by Karl-Bridge-Microsoft** [comment]
Per reply from @StephenLPeters, closing this issue due to relevance in doc repo, age, and lack of activity.
