### ISSUE TITLE
No toast notifications from Alternate Channel through a background agent?

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/windows-uwp#1578]
I'm a bit confused --- alternate channels say no toast or tile notifications, but according to the this page below, you can have it trigger a background task.  Couldn't you then just have the background task then show the toast/tile notifications?

https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/alternate-channel-vapid-webpush

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c77fc01-ab24-2953-72a6-fa877e526519
* Version Independent ID: f88aef84-b962-8f2d-9020-db634f99a91d
* Content: [Choosing the right push notification channel type - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/channel-types#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/channel-types.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/channel-types.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Correct, you can trigger a background task and then locally show toast notifications from that background task. Essentially, with normal push channels, you can send push toasts, push tiles, and push raws (which your push raws can then generate local toasts/tiles if you wish). With alternative channels, you can only send push raws (which can then generate local toasts/tiles), but you can't send push toasts/tiles.

Where specifically did you see this text you're referring to? Looking at the "[Choosing the right channel type](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/channel-types)" docs, it says the following, which seems accurate, but let me know if you think it's confusing and could be written differently!

> Apps cannot send toast, tile, or badge type notifications. The alternate channel limits your ability to send other notification types. Your app is still able to send local notifications from your background task.

**Comment by madenwala** [comment]
Ok, great!  I think for the line you quoted above, perhaps consider saying "Your app's cloud service cannot send toast, tile..." instead of saying "Apps cannot send...".  I think I was confused there because your app can actually show those notifications.  Also was thrown off by this page's Channel Type Comparison chart above which said no to these notifications. Perhaps a small addition saying no from [app cloud] server, but yes from background tasks triggered from the raw notification in the app.

**Comment by andrewleader** [comment]
That makes sense! I'll make those edits. Thanks Mohammed!

**Comment by andrewleader** [comment]
Fixed with commit e24cb950e13026563de289deb973f5f88187297a
