### ISSUE TITLE
Code for creating alternate channel

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/windows-uwp#1579]
The code to create an alternate channel needs to be updated...seems like this is the latest way to get a channel, not through the Current property.

PushNotificationChannelManager.GetForUser().CreateRawPushNotificationChannelWithAlternateKeyForApplicationAsync()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ea4ae7-43fb-17eb-8b05-bd037ac568a1
* Version Independent ID: cce897e5-f9d1-2751-5bb8-bede2e8c7383
* Content: [Alternate push channels using Webpush and VAPID in UWP - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/alternate-channel-vapid-webpush)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/alternate-channel-VAPID-webpush.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/alternate-channel-VAPID-webpush.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Thx, fix for this and the other clarifications is in pull request!
