### ISSUE TITLE
Code for alternate channels is incorrect

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/windows-uwp#1580]
The code to create an alternate channel needs to be updated...seems like this is the latest way to get a channel, not through the Current property.

PushNotificationChannelManager.GetForUser().CreateRawPushNotificationChannelWithAlternateKeyForApplicationAsync()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c77fc01-ab24-2953-72a6-fa877e526519
* Version Independent ID: f88aef84-b962-8f2d-9020-db634f99a91d
* Content: [Choosing the right push notification channel type - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/channel-types)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/channel-types.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/channel-types.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Thx, fix for this and the other clarifications is in pull request!
