### ISSUE TITLE
Sample for appServerKey to buffer?

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/windows-uwp#1583]
Could you please add sample code for converting your appServerKey from string to IBuffer? Would be immensely helpful. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ea4ae7-43fb-17eb-8b05-bd037ac568a1
* Version Independent ID: cce897e5-f9d1-2751-5bb8-bede2e8c7383
* Content: [Alternate push channels using Webpush and VAPID in UWP - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/alternate-channel-vapid-webpush)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/alternate-channel-VAPID-webpush.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/alternate-channel-VAPID-webpush.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Handling in an internal thread.

**Comment by SimoneBWS** [comment]
I'm interested to add support for push notification into LOB UWP (distributed outside Store). I read for [Alternate channels](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/channel-types#alternate-channels) with [CreateRawPushNotificationChannelWithAlternateKeyForApplicationAsync](https://docs.microsoft.com/en-US/windows/uwp/design/shell/tiles-and-notifications/alternate-channel-vapid-webpush)  api, but I don't find a sample that explain how to do it.

Do you have a sample that can help me?

Thanks!
