### ISSUE TITLE
An XAML example is missing in the Temporal Denoising section.

### ISSUE THREAD

**Issue by footstep002** [MicrosoftDocs/windows-uwp#1584]
There's a blank in example in the temporal denoising section. Of course you can guess what that code might be from the context, but it would be nice if this can be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9c13d13-aa66-a991-c111-f67dcfe4f4d0
* Version Independent ID: 2905ffc6-edd7-de69-a9b3-b95fa4f0036e
* Content: [Manual camera controls for video capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-device-controls-for-video-capture)
* Content Source: [windows-apps-src/audio-video-camera/capture-device-controls-for-video-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/capture-device-controls-for-video-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this. The XAML code snippet has been restored.
