### ISSUE TITLE
Problems with offline uwp app development

### ISSUE THREAD

**Issue by kaki104** [MicrosoftDocs/windows-uwp#1585]
Hello

I have been developing UWP apps from S Card in Korea since January this year.
S Card is a company that restricts the use of external internet from internal systems by Korean law.
There are various problems in UWP application development in this environment.

1. Problems downloading Nuget packages
By default, UWP app development is not possible without the nuget packages. So, when I started the project, I created a project using Windows Template Studio on a PC capable of Internet access, compressed all the packages in the users \ .nuget \ packages folder installed on the PC, copied it to the offline PC, I had to proceed.

2. Problems Compile with .NET Native tool chain
If I check the Build option, Visual Studio will download some additional files from the Internet, which I need to know exactly what files I need to use and I do not know how to use them.

The "ParseILMergeInfoTask" task failed unexpectedly. If an error occurs and I open the csv file, it looks like this:

3. I can not change the version of Dependencies appx files when I create a Store package.
For example, if I try to install by double-clicking the Microsoft.VCLibs.x64.Debug.14.00.appx file, the detailed version is 14.0.27023.1, but there is no way to downgrade this version.

In order for UWP application development to become more active, it will require a guide or tool for offline development.ex) 14.0.26xxx or 14.0.24xxx

Best,
Park

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89cc1b93-b31f-09c7-681f-02a43a5fc682
* Version Independent ID: 76d7a4eb-90f8-3501-3513-9637577dc999
* Content: [Feedback report - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/feedback-report)
* Content Source: [windows-apps-src/publish/feedback-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/feedback-report.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
