### ISSUE TITLE
Is there doc about "IoTStartupTask"?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-uwp#1586]
Hi,
There can't be used the "IoTStartupTask" in-process mode, is there doc about the "IoTStartupTask"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc4e874-3c89-c2df-c402-fd5005c08956
* Version Independent ID: 8af7f39d-d40c-d11c-9ea3-cecdc711037d
* Content: [Create and register an in-process background task - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-an-inproc-background-task)
* Content Source: [windows-apps-src/launch-resume/create-and-register-an-inproc-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-and-register-an-inproc-background-task.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, thanks for the feedback. Unfortunately we do not have a page on that specific API, and from what I know it is not available to UWP apps. You can find information on using **IoTStartup** on the [Windows 10 IoT Core Command Line Utils page](https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/CommandLineUtils). You could also post a question on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions) and see if anyone there can provide you more information about **IoTStartupTask**.
