### ISSUE TITLE
Broken link for NuGer build process docs?

### ISSUE THREAD

**Issue by MathiasMagnus** [MicrosoftDocs/windows-uwp#1588]
The link to the documentation of the NuGet build process seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8b1601-1a72-aa1c-9ba2-15c2e54e99b7
* Version Independent ID: ba32307e-0e03-4372-ab62-6fc2e57155b2
* Content: [What's new in C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/news#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/news.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/news.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for letting me know, @MathiasMagnus! Yes, that link isn't working any longer. I've put out feelers to see about getting it corrected. Thanks again! ~Steve

**Comment by stevewhims** [comment]
Ok, so the link has been fixed and published. Sorry about that, @MathiasMagnus, and thanks for letting me know about the problem. I'll go ahead and close this now. ~Steve
