### ISSUE TITLE
Resource not provided in example

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1591]
In the nested Items Repeater example (Display grouped items) there's a resource references `{StaticResource MyGroupLayout}` but it is not provided.  This makes the example less useful, there's also no picture accompanying it like the other example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ae7144-fa89-cd61-6ff7-8bb4a765e6f8
* Version Independent ID: 03f41125-77b9-5761-2aba-9b3eef17e121
* Content: [ItemsRepeater - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater)
* Content Source: [windows-apps-src/design/controls-and-patterns/items-repeater.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/items-repeater.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@micahl please take a look?

**Comment by michael-hawker** [comment]
@micahl @jevansaks any updates on fixing this sample?

**Comment by jevansaks** [comment]
Hopefully @anawishnoff can take a look?

**Comment by anawishnoff** [comment]
Thanks for bringing this to my attention. Working on a patch for this now!

**Comment by anawishnoff** [comment]
This has been fixed, and the doc is now published: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater#create-a-custom-collection-control

Turns out the MyGroupLayout was just a simple StackLayout.

**Comment by michael-hawker** [comment]
Thanks @anawishnoff! Can we get a picture of the expected result as well above it like the next sample has too?

**Comment by anawishnoff** [comment]
@michael-hawker After looking through the sample, I believe that the first sample under Display grouped items is more of a guideline on how to use nested ItemsRepeaters, and that second example goes into more detail with a full-blown example. The picture in between the two samples accurately reflects the basic layout that both samples would produce. I'll be adding in some more context to the article and sample to articulate this in the doc.
