### ISSUE TITLE
Provide link to Toolkit Alternative

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1595]
In the migration notes, it could link to the Toolkit helper (while not the same, it can be a stop-gap): https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/LayoutTransformControl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e595edce-cb07-0645-f1d6-1b51d0e6bcc6
* Version Independent ID: b1726951-106b-1e8a-7797-c3f2069a0908
* Content: [Transforms overview - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/transforms)
* Content Source: [windows-apps-src/design/layout/transforms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/transforms.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@michael-hawker do you want to just put up a PR with your proposed change?

**Comment by jwmsft** [comment]
This link has been added.
