### ISSUE TITLE
ทำให้ม่

### ISSUE THREAD

**Issue by Sufiyang** [MicrosoftDocs/windows-uwp#1596]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 4a5f48a1-c62a-9f8f-ab29-70d013346d2a
* Version Independent ID: 6ad201c6-ae84-5c10-0129-2cfa6f420cb6
* Content: [Screen sizes and break points for responsive design - Windows UWP applications](https://docs.microsoft.com/th-th/windows/uwp/design/layout/screen-sizes-and-breakpoints-for-responsive-design)
* Content Source: [windows-apps-src/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
We translated this as:
Title: "Make"
Contents: "[Enter feedback]" / "Document details"

Sorry, are you asking for the document to be translated?

Machine translation:

ขออภัยคุณกำลังขอให้เอกสารแปลหรือไม่
