### ISSUE TITLE
Page is inconsistent with what Visual Studio does.

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1598]
This page is already inconsistent with what Visual Studio give me when creating the project. I have no main.cpp; I have two cpp files, one called pch.cpp with a single entry, #include pch.h. Then I have Class.cpp which has some auto-generated class files in it as such
int32_t Class::MyProperty()
    {
        throw hresult_not_implemented();
    }

    void Class::MyProperty(int32_t /* value */)
    {
        throw hresult_not_implemented();
    }

Getting started is the hardest part. What's on this page is so different its going to be a lot of trial and error to get beyond the first step.

I would also add that there is an undiscussed concept in Visual Studio called an IDL file. It is, once again, another black box configuration files. These need to be clearly and thoroughly documented. Configuration files are not based upon logic; they just are. Get everything right to the most minute detail, or nothing works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @brianreinhold, there is a Windows **Runtime Component** (C++/WinRT) (my emphasis) project template, which does generate files and source code that are consistent with your report (including the presence of an IDL file). However, this Get started topic calls for a Windows **Console Application** (C++/WinRT) project. If you create one of those, then you'll see files and source code that match what the topic is describing. And there'll be no IDL file.

This particular topic doesn't cover IDL files. However, several of the others do, for example: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-property. That topic walks you through what you need to do with the IDL files for that particular topic. For a more general walkthrough and intro to the syntax of the IDL files that you use with C++/WinRT, see [Introduction to MIDL 3.0](https://docs.microsoft.com/uwp/midl-3/intro).

Thanks!
~Steve

**Comment by brianreinhold** [comment]
Steve,


Thanks for the response. Part of this was my fault for not fully understanding what all these new items (new for me) are. I thought the Windows Component template was for generating UWP C++/winRT libraries for C++/winRT applications; the C++/winRT analog to the C++/CX dll and static lib templates. I did not realize at the time that a Windows Component was a 'special' feature which after another week I have come to better grasps with. Since I did not find C++/winRT dll and static lib templates the only thing really left in the C++ library department that made any sense for UWP apps was this template. Alas not so!


Customers in the remote health infrastructure have become frustrated with the problematic Bluetooth support in iOS and Android and are starting to ask if there are any Windows solutions. We develop such solutions following PCHA/HL7 standards and that's what we are looking into. In the end we hope to have a 'Windows Bluetooth Adapter' that can be accessed from our Java implementation thus the choice of C++/winRT and a dll (access through JNI). The ideal dream solution would have been if there was a Java/winRT option.


In the mean time we are hoping that a C++/winRT dll and static lib template will be added. I am trying to create such a project from the C++/winRT core template which I have successfully made a simple BTLE scanner app from.


Thanks,


Brian


________________________________

**Comment by stevewhims** [comment]
Sounds good, thanks for the update, @brianreinhold! I'll go ahead and close this issue. Thanks for evaluating C++/WinRT for your project, and for filing the issue. ~Steve
