### ISSUE TITLE
Windows 10 notification listener for desktop app

### ISSUE THREAD

**Issue by anemomylos** [MicrosoftDocs/windows-uwp#1601]
Is it possible to use the notification listener from a desktop app (not bridged) or it is only for UWP apps? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7bf8a3a-3e67-f3b9-f63c-ca53383d7f19
* Version Independent ID: b64f8103-55c0-d8bd-52b9-b4b9f7b63fdf
* Content: [Notification listener - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/notification-listener)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/notification-listener.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/notification-listener.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
You have to be using the Desktop Bridge and UWP APIs to use the Notification Listener as the APIs require identity and an installed package.

**Comment by danielkornev** [comment]
Will this functionality be available to desktop apps given all the decoupling of XAML platform from UWP platform?

**Comment by andrewleader** [comment]
Hey @danielkornev, desktop apps can use notification listener as described above, they just have to be using Desktop Bridge so that they can access APIs that require identity in the UWP platform.

Learn more here: https://developer.microsoft.com/en-us/windows/bridges/desktop/
