### ISSUE TITLE
co_await on C++/WinRT projected methods fails to compile

### ISSUE THREAD

**Issue by daviddetweiler** [MicrosoftDocs/windows-uwp#1603]
Using co_await on an Async method such as RunIdleAsync() on the default Core Application template in the extension results in a compilation error asking for the header "experimental/resumable," after including this, it fails with `error C2039:  'promise_type': is not a member of 'std::experimental::coroutine_traits&lt;winrt::Windows::Foundation::IAsyncAction,const App::Run::&lt;lambda_ . . .`

This occurs on at least the latest VS 2019 Preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db952f42-9d6e-d30b-0aed-e7de64a89987
* Version Independent ID: bea24c9a-3e1e-405d-d7cc-5a080e62ece2
* Content: [Concurrency and asynchronous operations with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @daviddetweiler, thanks for filing this issue, and I'm in the process of updating this topic (and the FAQ and Troubleshooting topics). Btw, the breaking changes for C++/WinRT 2.0 are documented here; https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/news#news-and-changes-in-cwinrt-20. For coroutine support, you'll now need to `#include <winrt/coroutine.h>`. If you're using a range-based for on a WinRT collection, then you'll now need to `#include <winrt/Windows.Foundation.Collections.h>`.

~Steve

**Comment by daviddetweiler** [comment]
Thanks, the documentation can be a bit hard to grok sometimes, especially when I happen across it in the middle of a transition. One question, though, is the cppwinrt in the nuget package now the xlang version?

**Comment by stevewhims** [comment]
Hi, @daviddetweiler, yes, that's correct about the `cppwinrt.exe` tool.
