### ISSUE TITLE
How can I set the expiration time of Notification

### ISSUE THREAD

**Issue by eluchsinger** [MicrosoftDocs/windows-uwp#1606]
&gt;  By default, push notifications expire three days from the time they are received by the device. If needed, you can override this default with an explicit expiration time (toasts have a max of three days).

Where can I do that? Is there an example? I don't know how I can set the expiration time with `NotificationHub`. I only find a way to set the expiration time of a registration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce1599b-38fc-79e6-d29c-c8d81cdd30f9
* Version Independent ID: df2b1c9e-2d08-0654-1464-f88f9aafd9a6
* Content: [Choose a notification delivery method - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/choosing-a-notification-delivery-method#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/choosing-a-notification-delivery-method.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/choosing-a-notification-delivery-method.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Hey @eluchsinger, for push notifications, you can set the expiration time by [using the request headers](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh465435(v=win.10)).

To do that, you use the [X-WNS-TTL](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh465435(v=win.10)) header. The value is in seconds. If you specify it, once the Windows PC receives the notification, it'll expire it in X seconds.

So, if you wanted your notification to expire 1 hour after it's received, you would send the following HTTP request

```
POST https://db3.notify.windows.com/?token=AgUAAADCQmTg7OMlCg%2fK0K8rBPcBqHuy%2b1rTSNPMuIzF6BtvpRdT7DM4j%2fs%2bNNm8z5l1QKZMtyjByKW5uXqb9V7hIAeA3i8FoKR%2f49ZnGgyUkAhzix%2fuSuasL3jalk7562F4Bpw%3d HTTP/1.1
Authorization: Bearer EgAaAQMAAAAEgAAACoAAPzCGedIbQb9vRfPF2Lxy3K//QZB79mLTgK
X-WNS-RequestForStatus: true
X-WNS-Type: wns/toast
X-WNS-TTL: 3600
Content-Type: text/xml
Host: db3.notify.windows.com
Content-Length: 196

<toast launch="">
  ...
</toast>
```

As for doing that via Notification Hub, I'm not an expert there. I assume there's some way to set custom headers from Notification Hub to achieve this.
