### ISSUE TITLE
What OSS license is the sample provided under?

### ISSUE THREAD

**Issue by jeremytbrun** [MicrosoftDocs/windows-uwp#1607]
What open source license is this code sample provided under?
https://github.com/WindowsNotifications/desktop-toasts
Most other repositories under the WindowsNotifications account are tagged with an MIT license. This is one of the very few with no license currently specified. Can you please tag it with a license (assuming the MIT)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Send a local toast notification from desktop C# apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Sorry about that, just added the MIT license! Thanks for letting us know!
