### ISSUE TITLE
This page disappeared in the new dashboard version

### ISSUE THREAD

**Issue by nguyen-tam** [MicrosoftDocs/windows-uwp#1608]
I can't find any analytics about add on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8038cbf9-083d-e07c-97a2-0d0dd0e4edc4
* Version Independent ID: 8187ad11-23f6-2d93-2cb0-add22125562e
* Content: [Add-on acquisitions report - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/add-on-acquisitions-report#feedback)
* Content Source: [windows-apps-src/publish/add-on-acquisitions-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-on-acquisitions-report.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Hopefully back by now..
