### ISSUE TITLE
UWP Unit Test not working in Custom Agent

### ISSUE THREAD

**Issue by vishtahil** [MicrosoftDocs/windows-uwp#1610]
Issue: UWP unit test not running in Azure Virtual Machine (Win-10) which Custom Agent running in Interactive mode. 
Please note that the build in configured in Azure Devops.

Error: 
Failed to initialize client proxy: could not connect to test process.
Closing app with package full name '#####_1.0.0.0_x86__vsn28pm45h7sa'.

DEP7100: Failed to activate app ''#####ccc_vsn28pm45h7sa!vstest.executionengine.universal.App' with parameters '--port 1663 --endpoint 127.0.0.1:01663 --role client --parentprocessid 4292 --telemetryoptedin false'. This app can't be activated by the Built-in Administrator. (Exception from HRESULT: 0x80270253)

I followed all the steps:
Configure a custom build agent for unit testing

    Enable Developer Mode on your PC. See Enable your device for development for more information.
    Enable the service to run as an interactive process. To learn more, see Deploy an agent on Windows.
    Deploy the signing certificate to the agent.

Please suggest the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps#feedback)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by rido-min** [comment]
With the latest Hosted Build Agent with VS 2019, now you can run Unit Tests.

If you prefer a custom build agent, make sure you are running the agent with an account that is not the builtin administrator
