### ISSUE TITLE
XAML FlipView sample code is out of date

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#1614]
[Enter feedback here]
I'm looking into [Flip View](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/flipview) control, the code liked to [XAML FlipView sample](https://go.microsoft.com/fwlink/p/?LinkID=311760) is out of date, and can't be opened by Visual Studio 2017. So can you upgrade it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba6bc61-ac42-754f-7410-56e4a0c64a8e
* Version Independent ID: 53e11f76-e089-090e-1a8c-b53c6c9c9a1d
* Content: [Guidelines for flip view controls - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/flipview)
* Content Source: [windows-apps-src/design/controls-and-patterns/flipview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/flipview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
We have more up-to-date samples in the GitHub repos. Here:
https://github.com/Microsoft/Xaml-Controls-Gallery
and here:
https://github.com/Microsoft/Windows-universal-samples

@predavid can you fix the link in this article to point to a modern sample in the controls gallery?

**Comment by hupo376787** [comment]
Thanks. @jevansaks
