### ISSUE TITLE
These methods do not work on windows runtime apis

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1617]
This method, for example, compiles but does not work:

IAsyncOperation&lt;BluetoothAdapter&gt; WindowsBluetoothAdapter::GetBluetoothAdapter()
{
	BluetoothAdapter bluetoothAdapter = NULL;
	if (bluetoothAdapter == NULL)
	{
		bluetoothAdapter = co_await BluetoothAdapter::GetDefaultAsync();
	}
	co_return bluetoothAdapter;
}
The co_await does nothing. On return, a call to the return X.get() gives the classic ASSERT error on a UI thread that I cannot seem to avoid. One needs to clarify how one can use these coroutines on the runtime APIs or at least explain how one can make them synchronous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db952f42-9d6e-d30b-0aed-e7de64a89987
* Version Independent ID: bea24c9a-3e1e-405d-d7cc-5a080e62ece2
* Content: [Concurrency and asynchronous operations with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @brianreinhold, can you try this. Create a new Blank App (C++/WinRT) and then add these methods to MainPage.

```cppwinrt
...
#include <winrt/Windows.Devices.Bluetooth.h>
#include <winrt/coroutine.h>
using namespace winrt;
using namespace Windows::Devices::Bluetooth;
...

Windows::Foundation::IAsyncOperation<BluetoothAdapter> GetBluetoothAdapterAsync()
{
    BluetoothAdapter bluetoothAdapter{ nullptr };
    if (!bluetoothAdapter)
    {
        bluetoothAdapter = co_await BluetoothAdapter::GetDefaultAsync();
    }
    co_return bluetoothAdapter;
}

Windows::Foundation::IAsyncAction ClickHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::RoutedEventArgs const& args)
{
    BluetoothAdapter adapter{ co_await GetBluetoothAdapterAsync() };

    if (adapter)
    {
        myButton().Content(box_value(L"adapter is non-null"));
    }
    else
    {
        myButton().Content(box_value(L"adapter is null"));
    }
}
```

Thanks!
~Steve

**Comment by stevewhims** [comment]
Hi, @brianreinhold, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
