### ISSUE TITLE
X-WNS-PRIORITY values are incorrectly written

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/windows-uwp#1618]
The "SECTION THE PRIORITY" section says the values should be between 0-3 but the chart shows values between 1-4.  Could you please clarify which is the correct set of values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00495cf6-5df2-c85a-be4b-5af5ffb95acb
* Version Independent ID: 9234cef0-7a0d-7d2d-ef53-ed1df59ece26
* Content: [WNS Notification Priorities - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/wns-notification-priorities#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/WNS-Notification-Priorities.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/WNS-Notification-Priorities.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for your feedback, the answer is 1-4--we've updated the article.
