### ISSUE TITLE
No C++/winRT examples

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1619]
The C++/winRT is significantly different so examples should be provided. Also, it is not explained how one can register for the connection state changed events on the BluetoothLEDevice object when you cannot do that until you have retrieved the device. In the mean time a connection is ongoing. By the time one gets to register, the connection event is already over. Every other reasonable API I have worked with allows the application to set up all callbacks BEFORE a connection event is even thought about. There is something here that is inconsistent with the nature of transports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c57c086-3015-37b6-5318-b90a8e1fc0ba
* Version Independent ID: 94556012-dcdd-1dde-c8e5-147e1d05d5c0
* Content: [Bluetooth GATT Client - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by jevansaks** [comment]
Let's consolidate all the discussion into https://github.com/Microsoft/Windows-universal-samples/issues/1089 and re-open these issues when that concludes.
