### ISSUE TITLE
For C++/winRT need to document how one connects to a BTLE Device from the AdvertisementWatcher

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1621]
There is no documentation on how one connects to a device when the AdvertisementWatcher is used and a connectable advertisement is received.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c57c086-3015-37b6-5318-b90a8e1fc0ba
* Version Independent ID: 94556012-dcdd-1dde-c8e5-147e1d05d5c0
* Content: [Bluetooth GATT Client - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by brianreinhold** [comment]
Note that the approach suggested
BluetoothLEDevice.FromBluetoothAddressAsync 
does not work. It returns NULL (when using a co_await). So there must be more to it than stated above.

**Comment by jevansaks** [comment]
Let's consolidate all the discussion into https://github.com/Microsoft/Windows-universal-samples/issues/1089 and re-open these issues when that concludes.
