### ISSUE TITLE
Link to bluetooth.com is broken

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/windows-uwp#1623]
The final paragraph of [Bluetooth and Bluetooth LE services](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/aep-service-class-ids#bluetooth-and-bluetooth-le-services) reads:

> For a more complete listing of available Bluetooth services, see Bluetooth's protocol and service pages [here](https://go.microsoft.com/fwlink/p/?LinkID=619586) and [here](https://go.microsoft.com/fwlink/p/?LinkID=619587). You can also use the [GattServiceUuids](https://msdn.microsoft.com/library/windows/apps/Dn297571) API to get some common GATT services.

The first link forwards to the specification hosted at bluetooth.com. That link no longer works, and reports a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea99bd8d-03e9-0aee-defd-46380e2ca680
* Version Independent ID: 1c5c815d-d0ed-a6a6-4ec1-5d2a1435693d
* Content: [AEP service class IDs - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/aep-service-class-ids)
* Content Source: [windows-apps-src/devices-sensors/aep-service-class-ids.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/aep-service-class-ids.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been fixed.
