### ISSUE TITLE
Override pricing for single markets

### ISSUE THREAD

**Issue by sp-stuart-harrison** [MicrosoftDocs/windows-uwp#1624]
Hi, the wording above implies that having a market group with multiple countries in it allows you to set a pricing tier (e.g. in USD) and this tier price will be converted to local currency for each country listed (e.g. to EUR in Germany).
However, it also implies that having a market group with only a single country selected only allows you to set a price in local currency, not a tier price.  So, if you create a market group targeting only Germany, and set the price to USD, will there be a conversion to local currency, or will German customers have to pay in USD?
I'm asking as we are likely to add/remove countries to market groups and don't want to constantly have to switch currencies in order to make things work (we would prefer to specify all prices in USD).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a565dd45-6ca7-df65-2047-66012c28bd0a
* Version Independent ID: bb30cd84-9af9-0300-c450-936a20d73425
* Content: [Set and schedule app pricing - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/set-and-schedule-app-pricing#feedback)
* Content Source: [windows-apps-src/publish/set-and-schedule-app-pricing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-and-schedule-app-pricing.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The price will be in the currency that is local to the market region.
