### ISSUE TITLE
"アプリ ID の詳細の表示"ページ内の誤訳と思われる記載について

### ISSUE THREAD

**Issue by naiasin** [MicrosoftDocs/windows-uwp#1625]
[フィードバックをこちらに入力してください]
---
・パッケージ/ユーザー/名前
・パッケージ/ユーザー/パブリッシャー
・パッケージ/プロパティ/PublisherDisplayName
---

の部分の記載についてですが、
マニフェスト内のパスを示していると思われますので、
英語の原文のまま下記のように記載した方が適切ではないでしょうか。

---
・Package/Identity/Name
・Package/Identity/Publisher
・Package/Properties/PublisherDisplayName
---

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a03609b9-e26e-f6ec-fe69-73a7dde3ad4c
* Version Independent ID: bb662e79-89a6-0694-7259-c2ab0c677f26
* Content: [アプリ ID の詳細の表示 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/publish/view-app-identity-details)
* Content Source: [windows-apps-src/publish/view-app-identity-details.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/publish/view-app-identity-details.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by srvbpigh** [comment]
Hello, @naiasin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @naiasin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @naiasin 

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

#please-close
