### ISSUE TITLE
Code snippet not working

### ISSUE THREAD

**Issue by DerSIlent** [MicrosoftDocs/windows-uwp#1626]
The code snippet:
private async void Button_Click(object sender, RoutedEventArgs e)
{
    MediaElement mediaElement = new MediaElement();
    var synth = new Windows.Media.SpeechSynthesis.SpeechSynthesizer();
    Windows.Media.SpeechSynthesis.SpeechSynthesisStream stream = await synth.SynthesizeTextToStreamAsync("Hello, World!");
    mediaElement.SetSource(stream, stream.ContentType);
    mediaElement.Play();
}

Does not compile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6eac6fe-88ab-362f-2a6a-5edaeffce059
* Version Independent ID: cd7d245c-a7a6-4f14-4f46-d01bdbda9d3a
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal#feedback)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by DerSIlent** [comment]
The fix was adding async to the method!

**Comment by ghost** [comment]
Thank you for having the courage to point this out, finally.
Warmly and respectfully, Karin

Sent from my Windows 10 device

________________________________

**Comment by QuinnRadich** [comment]
Closing this issue, as the page already contains a reminder to add **async** to the method.
