### ISSUE TITLE
-Insert SKU here-

### ISSUE THREAD

**Issue by maexsp** [MicrosoftDocs/windows-uwp#1627]
What do you mean with -Insert SKU here- ? Probably a documentation mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb68dee1-01d8-94cf-976a-5dd31d408f4d
* Version Independent ID: 1deea8b5-5241-c349-0d17-3a6a55187e58
* Content: [Bluetooth developer FAQ - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-dev-faq#feedback)
* Content Source: [windows-apps-src/devices-sensors/bluetooth-dev-faq.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/bluetooth-dev-faq.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @maexsp, thanks for pointing this out. While an odd title, it is intentional. However, I've revised it to be less confusing.
