### ISSUE TITLE
Clicking developer verification email does not change status

### ISSUE THREAD

**Issue by bpwane** [MicrosoftDocs/windows-uwp#1628]
I have clicked on the verification button in the confirmation email sent to me but my status is not updating. It still says pending for email verification. What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f30d12-71bf-798e-731b-7d20ff618bf4
* Version Independent ID: 936a38a3-8e84-7a48-725b-b3eb3607ef68
* Content: [Manage account settings and profile info - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/manage-account-settings-and-profile#feedback)
* Content Source: [windows-apps-src/publish/manage-account-settings-and-profile.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/manage-account-settings-and-profile.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by MattRibeiro** [comment]
I had this issue. I used edge in an in-private window and dropped the verify url link in it, logged in, and it got me past that.

**Comment by MikeSifanele** [comment]
> I had this issue. I used edge in an in-private window and dropped the verify url link in it, logged in, and it got me past that.

This doesn't work. I even opened a case with Mircosoft and it's been more than two weeks now.

**Comment by applefanbois** [comment]
<<You can't submit to the Store until your account has been verified.>>

I have the email verification in the dashboard stuck on pending for the last 2 months. I called 4 different MS support department on the phone and opened 4 tickets. Everyone at MS are telling me to open a ticket somewhere else.

Every time I do a resend email verification, I receive the email and click on the link bringing me on the dashboard page but nothing is ever validated.

Is this dashboard connected to anything? Is the MS Store still opened? Is there anyone at left at MS doing support?

I am thinking about abandoning the windows port of our macOS app. No wonder no one is publishing on the UWP MS Store.

**Comment by MikeSifanele** [comment]
@applefanbois They finally resolved my issue after weeks of them responding by asking for PSRs. Open a live chat from the link below.

https://support.microsoft.com/en-us/contact/chat/66/?disability=false&mode=live&partnerId=devcenter&surveyType=NONE&appid=support-portal&partnerid=devcenter&sdk_componentid=f16423dda2294c101009d6fe6af33e54&sdk_targetorigin=https:%2F%2Fdeveloper.microsoft.com&sdk_sessionid=4840795d191d4a3bc0eeb1b79cd3b30f&sdk_hosttype=2&sdk_xframe=false&hascontext=true

**Comment by GrantMeStrength** [comment]
I'm sorry it has taken so long for us to respond. This issue was routed to the documentation team. I am grateful to Mike for posting a link to the Live Chat support window, and I recommend anyone with the same issue follows the same path. -john
