### ISSUE TITLE
XAML render performance is not good

### ISSUE THREAD

**Issue by asierpn** [MicrosoftDocs/windows-uwp#1629]
Despite you follow these guides there is scenarios where you need to display a complex visual tree, for example of 5000 items, and on these scenarios the UI freezes when loading the visual tree. This behavior should be improved, or we will not be able to design complex apps with UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd65842c-cc53-7120-2cf3-87bde4b0168e
* Version Independent ID: e34f3953-c43c-aa42-c161-6e07c268a5f0
* Content: [Optimize your XAML markup - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/optimize-xaml-loading)
* Content Source: [windows-apps-src/debug-test-perf/optimize-xaml-loading.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/optimize-xaml-loading.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by jevansaks** [comment]
Yes, this is a pain point but not something we're planning to address in the near term. Perhaps you could start a discussion on our product GitHub and see if others have suggestions for you? In general when we see things like this it's because the app isn't properly virtualizing lists.

https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by asierpn** [comment]
I will try to start a discussion in that place, I've been looking for a long time to a solution to UWP UI freeze issues. We are using virtualization, but we want to display a page with multiple tabs and a datagrid inside each one, a common LOB scenario that is almost impossible to implement without performance issues in UWP.
