### ISSUE TITLE
how could you guys publish the document "Package an app by using Visual Studio (Desktop Bridge)" without checking everything?

### ISSUE THREAD

**Issue by yaqinh** [MicrosoftDocs/windows-uwp#163]
This doc is a joke I have to say. So many obvious errors in this doc and there is absolutely no way you can package your app successfully using this method. I am so disappointed with this document, Microsoft. Wasted me hours of time. If you are not ready to publish this document, do not publish it!!!!!!!!!!!!!!!! Check everything before posting it. Anyone in Microsoft should read this doc, try it and see how bad it is. @zastrowm 's reference is better, Thank you! I spent hours to debug this manual and those people who wrote this should go back to school and learn how to become the qualified engineer. I usually do not leave a comment. I am always grateful to those engineers who write documents as detailed and accurate as possible. This doc completely destroys my impression with Microsoft. A wrong document is even worse than nothing. I am an engineer, so I know how hard it is to build something and achieve the goal. And before this, I always think Microsoft is a great company with a great number of highly skilled and responsible engineers. I am so disappointed to read this doc. Although I am still a student, at least I know whenever I plan to publish a product in the industry, I will check everything and make sure there is no obvious error. Because I know somebody will use it and I should help them as much as I can. I just found out the comment section in the following link is disabled? After I post this comment? Seriously? See the link: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net

**Comment by normesta** [comment]
Hi Yaquinh Thank you for sharing your honest thoughts and opinions. We're sorry for the frustration this has caused you. We've reviewed this doc and have made a number of changes that should clear up all of the confusion. If you have a chance, please do have another look and see if those updates have made a difference.

**Comment by yaqinh** [comment]
Thanks, it is fixed.
