### ISSUE TITLE
What’s new about cloud files API?

### ISSUE THREAD

**Issue by taoyouh** [MicrosoftDocs/windows-uwp#1631]
The link in “cloud files” says the cloud files API was introduced in 1607. So what’s new in this version? Can it be described more detailed?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5ade8bd6-7a05-1a6a-ea2f-b77798d4607d
* Version Independent ID: 6a2c0366-7b16-0bf2-f809-6521c3936886
* Content: [What's New in Windows 10 for Developers - Windows UWP applications](https://docs.microsoft.com/zh-cn/windows/uwp/whats-new/windows-10-build-18362#feedback)
* Content Source: [windows-apps-src/whats-new/windows-10-build-18362.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-18362.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
My understanding was that the Cloud Files documentation was introduced in this version, to correspond with the APIs being expanded and publicized.
