### ISSUE TITLE
Broken link above to: https://github.com/Microsoft/xlang/blob/master/src/package/nuget/readme.md

### ISSUE THREAD

**Issue by Oneibus** [MicrosoftDocs/windows-uwp#1632]
In the paragraph entitled "Changes to the Microsoft.Windows.CppWinRT NuGet package for version 2.0" at the top of the page above, a link to the C++/WinRT Nuget Package Readme.md is broken.  

It seems like it should reference: https://github.com/Microsoft/xlang/blob/master/src/package/cppwinrt/nuget/readme.md.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8b1601-1a72-aa1c-9ba2-15c2e54e99b7
* Version Independent ID: ba32307e-0e03-4372-ab62-6fc2e57155b2
* Content: [What's new in C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/news#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/news.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/news.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
@Oneibus, thanks for pointing this out. I've fixed the link now. ~Steve

(PS I'll go ahead and close the issue. Thanks again!)
