### ISSUE TITLE
Public + Whitelist

### ISSUE THREAD

**Issue by sp-stuart-harrison** [MicrosoftDocs/windows-uwp#1633]
What's unclear from this page is whether the combination of Public + Private is possible through the use of user groups.  For example, if you set the product as Public, but only launch in Austria, but previously you had been testing in Zambia with a Private group of beta-testers, will the Zambia group be able to access the product after it goes Public (in Austria only)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1cc4da-53ea-e79d-c59a-c213e75db486
* Version Independent ID: b56a46e7-785a-6bd1-030c-8c500c268bfc
* Content: [Choose visibility options - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/choose-visibility-options#audience)
* Content Source: [windows-apps-src/publish/choose-visibility-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/choose-visibility-options.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Answer generated by AI:

The page from Microsoft's documentation on publishing your app to the Microsoft Store doesn't explicitly cover the nuances of combining public distribution with private access for specific user groups, especially across different geographical regions. However, based on the general principles of how app visibility and access control work in the Microsoft Store, I can provide some insights that might help clarify this scenario.

Public Distribution with Restricted Geographic Availability
When you set your app to be publicly available but restrict its availability to specific countries or regions (e.g., only in Austria), it means that only users with access to the Microsoft Store in those specified regions will see and be able to download or purchase the app.

Private Distribution through User Groups
Private distribution, on the other hand, allows you to make your app available only to specific people, such as beta testers or internal employees, regardless of their geographic location. This is typically managed through the use of distribution groups, where you can add the Microsoft accounts of the individuals you want to grant access to.

Combining Public and Private Distribution
Based on these mechanisms, if you have a scenario where your app is publicly available in Austria but you also want a private group of beta testers in Zambia to access it, you can potentially manage this through the combination of public distribution settings and private user groups. Here's how it could work:

Public Availability in Austria: You configure your app's availability settings to make it public in the Austrian Microsoft Store. This means anyone in Austria can access and download the app from the Store.
Private Access for Beta Testers: You maintain a private distribution list or group that includes your beta testers in Zambia. Even though the app is publicly available only in Austria, members of this private group should still be able to access the app regardless of their geographic location, as their access is managed separately from the public availability settings.
It's important to carefully manage your distribution settings in the Microsoft Store dashboard to ensure that these configurations are correctly applied. Additionally, note that Microsoft's policies and the functionality of the Microsoft Store could change, so it's a good idea to review the latest documentation or contact Microsoft Support directly for the most current information and guidance.

In summary, while the documentation might not explicitly state it, the combination of public distribution in specific regions with private access for selected user groups should be feasible, allowing your beta testers in Zambia to access the app even after it goes public in Austria. For the most accurate and tailored advice, reaching out to Microsoft Partner Center support or consulting the latest Microsoft Store documentation would be the best course of action.
