### ISSUE TITLE
[LOC] "HKEY_ローカル_マシン\ソフトウェア\" needs to be replaced with "HKEY_LOCAL_MACHINE\SOFTWARE\"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1638]
https://docs.microsoft.com/ja-jp/windows/uwp/get-started/enable-your-device-for-development

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 54f67548-9361-beab-49f8-7d604651c6a6
* Version Independent ID: 6194efed-24aa-74f2-7687-3e368534b74a
* Content: [デバイスを開発用に有効にする - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/get-started/enable-your-device-for-development)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
I've made the changes to ensure that this command is no longer localized, and hopefully the change will go live shortly. Thank you for pointing this out.
