### ISSUE TITLE
Back-Translation "ms-設定:" → "ms-settings:"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1642]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-maps-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4baead54-3332-c579-f135-6464cc228be4
* Version Independent ID: fcf9e8a0-f10e-2fdd-a24b-212d3fc935b9
* Content: [Windows マップ アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-maps-app)
* Content Source: [windows-apps-src/launch-resume/launch-maps-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-maps-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/windows-uwp.ja-jp #11](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/11) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ghost** [comment]
#please-close
