### ISSUE TITLE
[LOC] ".html を見ることができます。" needs to be replaced with ".html "

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1655]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/reserved-uri-scheme-names

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3b7aff9d-497b-d2f2-79ec-fd017a5284c1
* Version Independent ID: 543a79a4-7258-36ea-0ffd-4ceda8655e4a
* Content: [予約済みのファイルと URI スキーム名 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/reserved-uri-scheme-names)
* Content Source: [windows-apps-src/launch-resume/reserved-uri-scheme-names.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/reserved-uri-scheme-names.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by ghost** [comment]
#please-close

**Comment by hyoshioka0128** [comment]
Close #1655
"https://github.com/MicrosoftDocs/windows-uwp.ja-jp/pull/16"
