### ISSUE TITLE
TransactionId and OrderId

### ISSUE THREAD

**Issue by aiiitm** [MicrosoftDocs/windows-uwp#1663]
How can we correlate the orderId/TransactionId in this report to the Subscription(https://docs.microsoft.com/en-gb/windows/uwp/monetize/get-subscriptions-for-a-user) fetched for a user which has an "id" field(subscription id). Secondly is there an API to download this payout summary on a server? We basically want to associate price info with subscriptions

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a40199-aaff-a750-b2df-cc8533606f0a
* Version Independent ID: 76160f31-f715-009a-e73e-202f8ed27006
* Content: [Payout summary - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/payout-summary#feedback)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn

**Comment by Rubiclers** [comment]
Hello, I have a question in my partner center, reach the threshold and only raw data for a year, how do I process it?
