### ISSUE TITLE
Code Snippet Says C# but it's actually C++/CX

### ISSUE THREAD

**Issue by the-jedi-code** [MicrosoftDocs/windows-uwp#1665]
Code snippet in this section is in a box labeled C# but the code in the snippet is all C++/CX
https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/host-card-emulation#receive-and-respond-to-apdus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3e9aa72-d6d4-1233-ed11-833bc84ebb30
* Version Independent ID: bfdc3cf4-67b0-009d-2fa4-595d2f255120
* Content: [Create an NFC Smart Card app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/host-card-emulation#receive-and-respond-to-apdus)
* Content Source: [windows-apps-src/devices-sensors/host-card-emulation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/host-card-emulation.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this and we apologize for the delayed response. This topic has been revised as suggested.
