### ISSUE TITLE
Cannot find a Resource with the Name/Key MenuBarItemBorderThickness error

### ISSUE THREAD

**Issue by yaugenka** [MicrosoftDocs/windows-uwp#1666]
I tried adding MenuBar to my C#/WinRT project as described at this page
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus#create-a-menu-bar
but got the following error:

> Windows.UI.Xaml.Markup.XamlParseException
>   HResult=0x802B000A
>   Message=The text associated with this error code could not be found.
> 
> Cannot find a Resource with the Name/Key MenuBarItemBorderThickness [Line: 13 Position: 44]
>   Source=Windows
>   StackTrace:
>    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
>    at App.MainPage.InitializeComponent() in D:\apps\App\obj\x86\Debug\MainPage.g.i.cs:line 33
>    at App.MainPage..ctor() in D:\apps\App\MainPage.xaml.cs:line 27

Using Microsoft.UI.XAML v2.1.190405004.2

**Comment by jevansaks** [comment]
Did you add XamlControlsResources to your app.xaml per the readme.txt instructions or per step 4 here: https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started ?
