### ISSUE TITLE
まだ配信されてないWindowsOSのバージョンを要求される

### ISSUE THREAD

**Issue by 77milkyway** [MicrosoftDocs/windows-uwp#1668]
GituHubからダウンロードして解凍し、Photolab.slnするところまで来ました。
しかし実行した後、最新版のSDK(バージョン1903用）のを要求され、インストールされているSDK(バージョン1809用）のに合わせてプロジェクトを更新する　をしたのですが「アセンブリ参照の一部がありません。」となりMainpage.xamlを開くことはできませんでした。これはバージョン1903が一般公開されるまでこのチュートリアルを実行できないということなのでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f181394a-13f5-ae4b-92a0-752015c8d4de
* Version Independent ID: e729b886-83bb-51df-c375-5e6950401228
* Content: [ユーザー インターフェイスの作成のチュートリアル - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/design/basics/xaml-basics-ui)
* Content Source: [windows-apps-src/design/basics/xaml-basics-ui.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/design/basics/xaml-basics-ui.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
### Machine translation:
Title:
Requested version of Windows OS not yet delivered
Description: 
I downloaded it from GituHub, unzipped it, and came to Photolab.sln.
However, after execution, I was asked for the latest version of the SDK (for version 1903), and I updated the project according to the installed SDK (for version 1809). It was not possible to open Mainpage.xaml. Does this mean that you won't be able to run this tutorial until version 1903 is publicly available?

**Comment by jevansaks** [comment]
1903 is required for this project and is now available through the Visual Studio Installer or from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk.

**Comment by 77milkyway** [comment]
I was able to get the SDK without any problem, but if I leave it as it is, the OS version is required to be 1903, so I cannot run it.

**Comment by jevansaks** [comment]
@stevewhims is 1903 required to *run* this sample now?

**Comment by stevewhims** [comment]
If you go to the sample itself (https://github.com/Microsoft/Windows-appsample-photo-lab), there's a **Note** at the top of the readme that's displayed.

"Note - This sample is targeted and tested for Windows 10, version 1903 (10.0; Build 18362), and Visual Studio 2019. If you prefer, you can use project properties to retarget the project(s) to Windows 10, version 1809 (10.0; Build 17763), and/or open the sample with Visual Studio 2017."

The TargetPlatformVersion/TargetPlatformMinVersion properties in the proj file are about SDK target version. You can change those to a different range. The MinVersion/MaxVersionTested properties in the Package.appxmanifest determine what versions of Windows the app can be installed onto. The values as currently set shouldn't limit you to 1903.

~Steve

**Comment by 77milkyway** [comment]
Changing the target version from Properties to 1809 now works.
Thank you!

**Comment by stevewhims** [comment]
Great. I'll go ahead and close the issue now. Thanks! ~Steve
