### ISSUE TITLE
Stubs (.h and .cpp) files does not update when i build

### ISSUE THREAD

**Issue by petrejonn** [MicrosoftDocs/windows-uwp#1669]
I am following the tutorial below but when i make make changes to my .idl file, the .h an .cpp files in 'Generated files' does not get updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd002fb0-9c40-6faa-9c83-b6cf7430bbe1
* Version Independent ID: 416d6f14-82b4-38c9-a8b2-2daf5cf2a37c
* Content: [XAML items controls; bind to a C++/WinRT collection - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-collection)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-collection.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-collection.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @petrejonn, they should be being generated in `\Bookstore\Bookstore\Generated Files\sources'? I'll make the topic clearer about the exact path. ~Steve

**Comment by petrejonn** [comment]
I guess its an issue with my visual studio. i will try try reinstalling it. Thanks anyway

**Comment by stevewhims** [comment]
Hi, @petrejonn, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
