### ISSUE TITLE
Desktop Bridge .NET Requirement

### ISSUE THREAD

**Issue by jonthysell** [MicrosoftDocs/windows-uwp#1670]
It says your existing desktop app (WinForms or WPF) needs to run on .NET 4.6.2 - does that mean you literally need to _target_ 4.6.2 or greater? Because then it says that your .NET 4.0 apps shoudl work but you should test them.

I've re-targeted some old .NET 2.0 apps to 4.6.**1** and they got on the store just fine.

Can I package an WPF app that targets .NET 4.5 for use with Desktop Bridge? I depend on third party nuget packages with PCLs that target 4.5.

**Comment by hickeys** [comment]
Thanks for reaching out Jon. Unfortunately, issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page.

That said, My understanding is that as long as you've tested your application on 4.6.2, you should be fine.

**Comment by jonthysell** [comment]
@hickeys This is a documentation issue. This documentation, right here: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare, is incorrect and ambiguous.

> Your application requires a version of .NET earlier than 4.6.2.

The _actual_ requirements to package and publish a desktop app using Desktop Bridge are:

- The entry executable must target 4.6.1 or later.
- Other .NET assemblies just need to be able to run on .NET 4.6.1, they can target any version less than or equal to the entry executable.
