### ISSUE TITLE
Missing sound clips

### ISSUE THREAD

**Issue by moshegutman** [MicrosoftDocs/windows-uwp#1671]
This page appears to be missing the MP3 sound clips. Like &lt;ElementFocus1.mp3 sound clip here&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f534f7-fff9-52af-1a90-e0ad23dc5e89
* Version Independent ID: 1e85662f-3f65-97ad-55df-e24678b625fd
* Content: [Sound - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/sound)
* Content Source: [windows-apps-src/design/style/sound.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/sound.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by kikisaints** [comment]
Are you asking to have the sound clips available to listen to on the doc site itself, or are you asking for markup explaining how to access the mp3 files directly in XAML?

**Comment by moshegutman** [comment]
Yeah I think the intention was to have sound clips embedded on the doc site to listen to. It seems like they are missing because the doc site says “sound clip here”

**Comment by kikisaints** [comment]
Oh wow! Thanks for pointing it out.

@mijacobs Looks like we have [the sound resources here](https://github.com/MicrosoftDocs/windows-uwp/tree/docs/windows-apps-src/design/style/assets/sound), but they're just not hooked up - do we have a way of embedding sound clips yet? If so I can go ahead and hook those up.

**Comment by mijacobs** [comment]
I just sent a query to docs support.

**Comment by mijacobs** [comment]
I investigated--to play the sound resources, we need to host them somewhere else, like we would host a video. Since the sound clips are a nice addition to the article but not essential to understanding the content, I removed them.
