### ISSUE TITLE
Policy Violations

### ISSUE THREAD

**Issue by RexfelisLOC** [MicrosoftDocs/windows-uwp#1674]
Policy Violations needs to be updated with something like:

*  Placing ads in a Viewbox to reduce the size of the ads in order to allow more ads on a page than normal.

Several developers are placing their ads in a Viewbox to the point where they can have five or more 728x90 banners side by side on a page when normally you can only fit two 728x90 ads on a device that displays 1920x1080 resolution (the most common for desktops and Xbox One devices).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62faa54b-1448-6c14-1252-14322f1b4ecd
* Version Independent ID: 08c8be67-8247-714a-6d17-375e82cd1746
* Content: [UI and user experience guidelines for ads - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/ui-and-user-experience-guidelines#feedback)
* Content Source: [windows-apps-src/monetize/ui-and-user-experience-guidelines.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/ui-and-user-experience-guidelines.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
Added, thank you. It may take a few hours to be published, but it will show up soon.
