### ISSUE TITLE
WebCam based Eye-Tracker

### ISSUE THREAD

**Issue by szydej** [MicrosoftDocs/windows-uwp#1676]
How to use webcam Eye-Tracker (GazePointer: https://sourceforge.net/projects/gazepointer/ ) with the Gaze Interaction Library ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cc2d6d6-2316-bb10-5dc7-12c0b97e02d3
* Version Independent ID: f4065046-8d78-785a-1369-40a749d63147
* Content: [Gaze interactions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/gaze-interactions#feedback)
* Content Source: [windows-apps-src/design/input/gaze-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/gaze-interactions.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @szydej - please see https://support.microsoft.com/en-us/help/4043921/windows-10-get-started-eye-control#supported-devices for a list of supported devices.
