### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gnmithun** [MicrosoftDocs/windows-uwp#1677]
`To create a fluid layout, use automatic or proportional sizing for elements, and allow layout panels position their children as needed.`

This should be 

`To create a fluid layout, use automatic or proportional sizing for elements, and allow layout panels` **to** `position their children as needed.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06eec92b-e1ef-945f-bc1a-0fa3e23c77de
* Version Independent ID: 50fbbe23-6e9d-d4a7-7242-b9e9c04fc0d2
* Content: [Responsive layouts with XAML - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layouts-with-xaml#feedback)
* Content Source: [windows-apps-src/design/layout/layouts-with-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/layouts-with-xaml.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for notifying us about this. A fix has been submitted.
