### ISSUE TITLE
Final code snippet in "If you're not authoring a runtime class" section (stack allocating an instance and passing it by value) may be wrong

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/windows-uwp#1678]
Here is the code snippet in question:

```c++
using namespace Windows::ApplicationModel::Core;
int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
    CoreApplication::Run(App{});
}
```

The type `App` is a class we defined earlier in the section using `winrt::implements` specifically so we could pass an instance of the class to `CoreApplication::Run()`. However, a Windows Runtime object is a COM object and so its lifetime needs to be managed by reference counts, as it may be live beyond the end of the function call in which it was created.

While I believe this example _might_ be safe because the `App` object is being created at the beginning of and will be destroyed at the end of the program's main function, I wouldn't really rely on my intuition here, and I wouldn't want others to similarly have to reason rightly or wrongly about this example.

Instead, I would suggest that the example code be revised to change `App {}` to `winrt::make<App>()`, using the [`winrt::make` helper template](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/make) ([source](https://github.com/MicrosoftDocs/winrt-related/blob/docs/winrt-related-src/cpp-ref-for-winrt/make.md)).

Incidentally, it appears that the existing usage I'm concerned about might trigger an assertion failure on debug builds since this change was made to C++/WinRT: https://github.com/microsoft/xlang/pull/150

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5961a97-ba23-0707-1a86-807084a97b31
* Version Independent ID: 5c1c753b-fe4e-0d58-f623-f7d43c166277
* Content: [Author APIs with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#if-youre-not-authoring-a-runtime-class)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-apis.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @metathinker, you're right, this is a mistake. I had already fixed this in another place, but I missed this one. Anyway, I just published a fix to it, so we're good now. Thanks again! And, I'll close the issue now.

~Steve
