### ISSUE TITLE
Cannot remove tenant

### ISSUE THREAD

**Issue by thepowercoders** [MicrosoftDocs/windows-uwp#1680]
I do not have the option to remove a tenant from Partner Center. I have logged in using a user in a different tenant to the one I want to remove, and the user has the Manager role. When I go to the Tenants page (in Account Settings) I see the tenants listed, but there is no 'Remove' option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1603df77-580d-a332-ace4-10c4b6f1484b
* Version Independent ID: 7f70b8d6-5146-f327-86c8-9c17acbcac23
* Content: [Associate Azure Active Directory with your Partner Center account - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-partner-center#feedback)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-partner-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-partner-center.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn

**Comment by thepowercoders** [comment]
Hi, I am not asking for technical support, I am trying to follow the documentation. It clearly says "Any user who has the Manager role for a Partner Center account can remove Azure AD tenants from the account". I have the manager role but I cannot remove tenants - so obviously the documentation is wrong. Are you saying I need to go elsewhere for support? - just saying 'ask on our forums' isn't very helpful and StackOverflow seems to be some kind of techie programming Q&A site??
