### ISSUE TITLE
Bluetooth ids seem wrong

### ISSUE THREAD

**Issue by GeertvanHorrik** [MicrosoftDocs/windows-uwp#1681]
The docs show this:

18160000-0000-1000-8000-00805F9B34FB

However, both the GattServiceUuids class as code show that it should be:

00001816-0000-1000-8000-00805f9b34fb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea99bd8d-03e9-0aee-defd-46380e2ca680
* Version Independent ID: 1c5c815d-d0ed-a6a6-4ec1-5d2a1435693d
* Content: [AEP service class IDs - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/aep-service-class-ids#feedback)
* Content Source: [windows-apps-src/devices-sensors/aep-service-class-ids.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/aep-service-class-ids.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by hkhmsft** [comment]
Hi GeertvanHorrik,

The GUIDs on the list are showing as "precursor" + "0000-0000-1000-8000-00805F9B34FB", which matches with the documentation guidance on the GUID naming convention. In this example, it would be "1816" + "0000-0000-1000-8000-00805F9B34FB".

Where exactly are you seeing the "00001816-0000-1000-8000-00805f9b34fb" format?

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/68012213-b641de80-fc89-11e9-8b99-968a39a5544f.png)

**Comment by Karl-Bridge-Microsoft** [comment]
Researched this a bit and the topic does appear to be incorrect in the way it specifies how the guids are constructed. I've revised to reflect your comment and the detail I found in my research.
