### ISSUE TITLE
Images in Overview section are small and inaccurate

### ISSUE THREAD

**Issue by YuliKl** [MicrosoftDocs/windows-uwp#1683]
The overview sections shows two images - the ribbon and a floating ribbon menu. The first, ribbon, image is small and blurry. 
The text above the images states "The following image shows two command interfaces (a CommandBar and a floating contextual CommandBarFlyout) that share many of the same commands." But that's not accurate. The controls called out are Xaml controls while the screenshots appear to be of Win32 controls. Neither CommandBar nor CommandBarFlyout look like what is shown in the screenshots. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9331458-c8a4-8936-6b4a-a58a8685cbe7
* Version Independent ID: c8be4bc6-bb46-244d-402b-8cba837e65d7
* Content: [Commanding in Universal Windows Platform (UWP) apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/commanding)
* Content Source: [windows-apps-src/design/controls-and-patterns/commanding.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/commanding.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @YuliKl. I've replaced them with images used in the menus.md and appbars.md topics.
