### ISSUE TITLE
Missing explanations for ClientIPsIPv4, CloudServiceIPs, ClientDNS, CloudServiceDNS, IPv4 ranges

### ISSUE THREAD

**Issue by jamesdooleymsft** [MicrosoftDocs/windows-uwp#1685]
Please add explanations for what all the XML document elements mean, and what the IPv4 range notation is. Here's how I've explained it to other:
See https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing for a detailed explanation of what the 64.4.28.0/26 notation means. Keeping the first 26 bits constant of 64.4.28.0 means the IPv4 range is 64.4.28.0 - 64.4.28.63.
ClientIPsIPv4 are the IPv4 addresses of the servers accessed by client devices such as Windows PCs, and ClientDNS are their fully-qualified domain name (FQDN) filters.  These must be allowed through the firewall in order for WNS clients to use the WNS functionality.
CloudServiceIPs are the IPv4 addresses of the servers used for cloud services to send notifications to WNS and CloudServiceDNS are the FQDN filters for those servers.  These must be allowed through the firewall in order for services to send WNS notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a4afa5-1a82-fa68-e980-2850af861b8b
* Version Independent ID: ed8668d1-30d5-3ba5-e519-e5ead846715e
* Content: [Adding WNS Traffic to the Firewall Allowlist - Windows UWP applications](https://review.docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/firewall-allowlist-config?branch=manoskow%2FEnterpriseFirewallAllowlist#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/firewall-allowlist-config.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/firewall-allowlist-config.md)
* Product: **windows**
* Technology: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Added this feedback to the PR.
