### ISSUE TITLE
Doesn't work for VS2019

### ISSUE THREAD

**Issue by Stuart88** [MicrosoftDocs/windows-uwp#1687]
Monogame doesn't have a VS2019 release yet, so the article is wrong where it says, "Start Visual Studio 2019"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b55ec8-00ba-dd3f-3fe8-dae000b588ba
* Version Independent ID: dd1b048f-b8c8-091c-8dcc-342a1fd75843
* Content: [Create a UWP game in MonoGame 2D - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-started-tutorial-game-mg2d#feedback)
* Content Source: [windows-apps-src/get-started/get-started-tutorial-game-mg2d.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/get-started-tutorial-game-mg2d.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for pointing this out.

The MonoGame article has been unlisted in our table of contents for a while as it's out of date, and I don't think we have the bandwidth to update it right now. I was already planning to remove the article entirely, and I think this just makes that all the more compelling.
