### ISSUE TITLE
[LOC] "XAML 諸島", " XAML 島々", and "XAML の島" → "XAML Islands"

### ISSUE THREAD

**Issue by tanitanin** [MicrosoftDocs/windows-uwp#1692]
Islandsはローカライズせず、"XAML Islands"を固有名称として残すのがよいと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e93ebf14-73e6-d1b6-0bbe-514390fd7be0
* Version Independent ID: 5ac137cf-59a0-f646-2379-202889b96143
* Content: [デスクトップ アプリケーションの UWP コントロール - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/xaml-platform/xaml-host-controls)
* Content Source: [windows-apps-src/xaml-platform/xaml-host-controls.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/xaml-platform/xaml-host-controls.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by srvbpigh** [comment]
Hello, @tanitanin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @tanitanin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @tanitanin,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/windows/uwp/xaml-platform/xaml-host-controls.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
#please-close
