### ISSUE TITLE
Link to source code DesktopNotificationManagerCompat is broken

### ISSUE THREAD

**Issue by NikulovE** [MicrosoftDocs/windows-uwp#1693]
https://raw.githubusercontent.com/WindowsNotifications/desktop-toasts/master/CS/DesktopToastsApp/DesktopNotificationManagerCompat.cs

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Отправка локального всплывающего уведомлений из классических приложений C# - Windows UWP applications](https://docs.microsoft.com/ru-ru/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ru-ru/blob/live-sxs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by hickeys** [comment]
This link is working correctly for me. I'm going to close this issue. If the link still does not work, please reopen.
