### ISSUE TITLE
Update version of VCLibs referenced in the docs

### ISSUE THREAD

**Issue by AdamBraden** [MicrosoftDocs/windows-uwp#1694]
The version of the v14 VCLibs at the download link is old. VS2017 Update 3 introduced a breaking change and any app built with this version of VS or newer, ie: VS2019, need to reference the newer package, or the app will fail to load. Unfortunately the web download link is not updated for the v14 packages.  VS changed the redist model from the web download to redist via VS and have the VS 2017 updates include the packages and install them to the "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\" folder. This is the v14 version that must be referenced in the package manifest or installed when sideloading:

<PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.26905.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />

We need to change the guidance from telling users to install the download links to instead install from the ExtensionSDKs folder, ie:

- C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop
- C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop.110
- C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop.120

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af8cc5b-6a98-bd70-6b5f-97f9fbd6362b
* Version Independent ID: eddd9517-bbf4-456d-bb62-a615f821ff91
* Content: [Prepare to package a desktop application (Desktop Bridge) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-prepare.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-prepare.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mcleanbyron** [comment]
The "Your app uses a VCLibs framework package" section in this article has been updated with more complete guidance and pointers to where to find the packages on the development computer. If you still see issues with the article, please feel free to reopen this issue with the details.
