### ISSUE TITLE
Download PDF not up to date

### ISSUE THREAD

**Issue by Phoenyx33** [MicrosoftDocs/windows-uwp#1696]
Clicking the "Download PDF" in the left side downloads a document that begins with "What's new in Windows 10 for developers, build 17763" instead of the new build 18362. Request that you update soon as many developers depend on the pdf to lookup whats new without having to access the internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ade8bd6-7a05-1a6a-ea2f-b77798d4607d
* Version Independent ID: 6a2c0366-7b16-0bf2-f809-6521c3936886
* Content: [What's New in Windows 10 for Developers - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-18362#feedback)
* Content Source: [windows-apps-src/whats-new/windows-10-build-18362.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-18362.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by bartlannoeye** [comment]
@dend this might be a general docs issue rather than UWP docs specific? Seems like cached output?

**Comment by QuinnRadich** [comment]
Agreed with the previous comment. This is a cached output issue that we don't have direct control over. I've raised this issue to the docs engineering team, but for the time being I'm going to close this issue as it's sadly out of our hands.

Thank you.
