### ISSUE TITLE
typo: ms-settings:privacy-phonecall

### ISSUE THREAD

**Issue by tgrisel** [MicrosoftDocs/windows-uwp#1701]
there is a missing "s". it has to be: ms-settings:privacy-phonecalls

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Starten der Windows-Einstellungs-App - Windows UWP applications](https://docs.microsoft.com/de-de/windows/uwp/launch-resume/launch-settings-app#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.de-de/blob/live-sxs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hello, thanks for your feedback! Looks like you're correct. I'll update the text.
