### ISSUE TITLE
Confusion about Discoverability Vs. Private Audience

### ISSUE THREAD

**Issue by TonyAshton** [MicrosoftDocs/windows-uwp#1705]
I have an app that is currently under test with a Test Group using the Private Audience.  I also have the Direct URL, and have enabled this option in the app's settings.

User in the Private test group can see the app, Users with the Direct URL (not part of the test group) cannot see the app in the store.

There seems to be a disconnect here, as I would expect the Direct URL to make the app visible based on the documentation.    This needs clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1cc4da-53ea-e79d-c59a-c213e75db486
* Version Independent ID: b56a46e7-785a-6bd1-030c-8c500c268bfc
* Content: [Choose visibility options - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/choose-visibility-options#feedback)
* Content Source: [windows-apps-src/publish/choose-visibility-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/choose-visibility-options.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I believe this is already documented in the first tip in the section: Make this product available but not discoverable in the Store

It reads: "If you don’t want the listing to be viewable to the public, even with a direct link, choose Private audience in the Audience section, as described above."

If that is not what you are asking, then it's possible I've misunderstood your question. Could you elaborate a little more?

Thanks,
Shawn

**Comment by hickeys** [comment]
Closing this issue as it seems as if the question has been answered.
