### ISSUE TITLE
Document winrt::capture, useful for COM REFIID/void** cases

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1706]
Kenny added `winrt::capture` to the recent version of C++ WinRT. This lets you replace
```
  winrt::com_ptr<IDWriteFactory2> dwriteFactory2;
  DWriteCreateFactory(
      DWRITE_FACTORY_TYPE_SHARED,
      __uuidof(dwriteFactory2),
      reinterpret_cast<IUnknown**>(dwriteFactory2.put()));
```
with this
  `dwriteFactory2.capture(DWriteCreateFactory, DWRITE_FACTORY_TYPE_SHARED);`

avoiding the dangerous and ugly casts and non-standard __uuidof().

Note, double check my example above as DWriteCreateFactory is an unusual case, using `REFIID/IUnknown**` where most COM designs use `REFIID/void**` (that I know works with capture).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a5b38aa-8df6-251c-6da9-3c2ce888c866
* Version Independent ID: 08f6669a-4dc7-ab0d-04b1-7125e809cd60
* Content: [Consume COM components with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-com)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-com.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-com.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, Chris, I've switched over to use winrt::com_ptr::capture in the topic wherever I was able. There are some places (as per the internal email I sent you) where it's not possible. We can continue the discussion internally and make further changes as we go. Thanks! ~Steve
