### ISSUE TITLE
Working with COM types, such as BSTR and VARIANT should reference the wil library

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1708]
this is a dupe of #1707 but linked via the doc page for reference.

This section should be updated to not mention ATL or the compiler support for COM.

instead use the windows implementation library (wil) https://github.com/Microsoft/wil

it has `wil::unique_variant`, `wil::unique_bstr` for managing resource lifetimes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a5b38aa-8df6-251c-6da9-3c2ce888c866
* Version Independent ID: 08f6669a-4dc7-ab0d-04b1-7125e809cd60
* Content: [Consume COM components with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-com#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-com.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-com.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, Chris, fix is live now! ~Steve
