### ISSUE TITLE
Debugging Package Updates

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/windows-uwp#1710]
Is there any guidance on debugging an entire app update workflow? Not just prompting the user, but receiving the progress. I'm on 1803, and `RequestDownloadAndInstallStorePackageUpdatesAsync` brings up a prompt "Download updates now?" with "Okay" and "Maybe later." Looking in the Store, it is attempting to update and getting error: 0x80073CF9. The app never receives progress information.

I'm assuming that it's because the Store won't install over the top of a debug (unpackaged?) build, but perhaps there are some steps to bypass this. Or even better, a sample app that shows this code in action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3aae6d8-4751-8713-cb47-180ca2a1af01
* Version Independent ID: e46c9be3-742b-a831-5b7e-8363cd61bba9
* Content: [Download and install package updates from the Store - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates)
* Content Source: [windows-apps-src/packaging/self-install-package-updates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/self-install-package-updates.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
To test your implementation of this code, you'll need to actually publish an updated package for your app to the Store. There is no test framework or harness for this. However, we do provide the [ability to flight package updates](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights) for your app to a specific set of users, and you can use this process to set up a private test for yourself or your testers. 

Does this help? Or are you already running this code against a package update you have already submitted to the Store and you're getting this error?

**Comment by adamhewitt627** [comment]
That does help. We've been using package flights, but for some reason that felt wrong to me. Probably because it means I have to actually submit 2 new builds. One to have this code, and another to be seen as an update. At which point, if it isn't working, I have to create & submit 2 more.

I think I've seen the Store update over a sideloaded build? Maybe I'm imagining that, but I was about to try:
1. Change my `appxmanifest` to an old version number. 
2. Build for StoreUpload, 
3. Install via the PowerShell script.
4. Launch the app and check for updates. (At this point, I could even "Debug Installed App Package")

**Comment by HppZ** [comment]
following those steps failed, OverallState of StorePackageUpdateResult is completed, but my app didn't get updated.

**Comment by HppZ** [comment]
@adamhewitt627 @mcleanbyron
