### ISSUE TITLE
Add Links for ARM64 redist and other downloadsa 

### ISSUE THREAD

**Issue by haripulapaka** [MicrosoftDocs/windows-uwp#1715]
VC++ Redist for ARM64

Direct download links:
•	2019 Redist: https://aka.ms/vs/16/release/VC_redist.arm64.exe
•	2017 Redist: https://aka.ms/vs/15/release/VC_redist.arm64.exe

Places for customers to download:
•	https://visualstudio.microsoft.com/downloads/ under “Other Tools and Frameworks”
•	https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
•	https://visualstudio.microsoft.com/vs/older-downloads/ under “Redistributables and Build Tools”
•	https://my.visualstudio.com/Downloads?q=Visual%20Studio%202019 under “Visual C++ Redistributable […] 2019”
•	https://my.visualstudio.com/Downloads?q=Visual%20Studio%202017 under “Visual C++ Redistributable […] 2017”

Remote Tools for ARM64

Direct download links:
•	2019 Remote Tools: https://aka.ms/vs/16/release/RemoteTools.arm64ret.enu.exe 
•	2017 Remote Tools: https://aka.ms/vs/15/release/RemoteTools.arm64ret.enu.exe 

Places for customers to download:
•	https://visualstudio.microsoft.com/downloads/ under “Tools for Visual Studio 2019”
•	https://my.visualstudio.com/Downloads?q=Visual%20Studio%202019 under “Remote Tools for Visual Studio 2019”
•	https://my.visualstudio.com/Downloads?q=Visual%20Studio%202017 under “Remote Tools for Visual Studio 2017”

Note: my.visualstudio.com refers to ARM64 as “a64”. 

Contact: haripul@microsoft.com or marcs@microsoft.com for more details

**Comment by haripulapaka** [comment]
this is the orig doc page: https://docs.microsoft.com/en-us/windows/arm/

**Comment by QuinnRadich** [comment]
I'd added links and instructions to the Visual Studio 2019 downloads to this doc page https://docs.microsoft.com/windows/uwp/porting/apps-on-arm . No further redundant links have been added, as I want to minimize customer confusion.

Thank you.
