### ISSUE TITLE
ManifestParseFailure when try to create AdaptiveMediaSource from manifest with long presentationTimeOffset.

### ISSUE THREAD

**Issue by StAI** [MicrosoftDocs/windows-uwp#1716]
[manifest.txt](https://github.com/MicrosoftDocs/windows-uwp/files/3252881/manifest.txt)
We are trying to create AdaptiveMediaSource by using "await AdaptiveMediaSource.CreateFromUriAsync(contentUri);"
My manifest is dynamic dash manifest.
But we've got ManifestParseFailure with ExtendedError "Overflow or underflow in the arithmetic operation." 
As I found the reason is presentationTimeOffset attribute in SegmentTemplate.
We have the following SegmentTemplate in our manifest:

&lt;SegmentTemplate timescale="10000000" media="S!d0FEQVNIQwB43LlEgOjcuZ8_/QualityLevels($Bandwidth$)/Fragments(video=$Time$)" initialization="S!d0FEQVNIQwB43LlEgOjcuZ8_/QualityLevels($Bandwidth$)/Fragments(video=Init)" presentationTimeOffset="15591168019808650"&gt;
    &lt;SegmentTimeline&gt;
        &lt;S t="15591168019808650" d="20000000" r="490"/&gt;
    &lt;/SegmentTimeline&gt;
&lt;/SegmentTemplate&gt;

If we reduce presentationTimeOffset to "155911680198" for example, AdaptiveMediaSource will be successfully created.
Other platforms, f.e shaka player parse such manifest without errors.

What is the limitation for presentationTimeOffset in UWP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba15ea2-27a1-78ca-7610-d2025f5aa5d3
* Version Independent ID: 1ff3ba66-c83c-ee09-efa5-f7ad2b5f950a
* Content: [Adaptive streaming - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/adaptive-streaming#feedback)
* Content Source: [windows-apps-src/audio-video-camera/adaptive-streaming.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/adaptive-streaming.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by dzianis-vashkevich-EPAM** [comment]
Hello @drewbatgit, 

Can you please perform assessment of this issue and provide feedback. It's blocks development of critical component for our customer. 

Thank you,
Denis

**Comment by drewbatgit** [comment]
@DenisV-E sorry for the delayed response. I am engaged with a conversation with the feature team about this issue. They have investigated and believe they may have discovered a bug that is causing this behavior. I am waiting for information about an ETA for a fix and potential workarounds. I will update the thread when I have new information.

**Comment by drewbatgit** [comment]
Hello, the product team has investigated and believe they have discovered a bug. The following are the details and a proposed workaround until a bug fix can be integrated into a release:

The issue is with the Period@start accuracy. It looks like the value of Period@start is PT433088H1.980S = 15591168019800000 HNS. The value of presentationTimeOffset is 15591168019808650. It will try and subtract the presentationTimeOffset value from the Period@start time, so since Period@start is smaller, we get the arithmetic overflow error. 

A work around would be to not round the Period@start value. For example, in this instance Period@start = PT433088H1.9808650S

**Comment by dzianis-vashkevich-EPAM** [comment]
Hi @drewbatgit, thank you for help ! We will try to apply this work around into our solution.
