### ISSUE TITLE
[Window runtime compenent]

### ISSUE THREAD

**Issue by Tan2NT** [MicrosoftDocs/windows-uwp#1722]
Hello, 
Is it possible to call a Windows Runtime Component (written in C++/Cx) from a C++ project? If Yes, could you please give us an example?
Thank a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2860140a-8b64-4280-3f5b-bb454d71def9
* Version Independent ID: 4af675f3-e584-5616-ac4a-335ecda5b4f3
* Content: [Creating a Windows Runtime component in C++/CX, and calling it from JavaScript or C# - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp#feedback)
* Content Source: [windows-apps-src/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Call it from a C++/WinRT project?

Essentially, you can write a Windows Runtime Component (WRC) in any of the Windows Runtime languages and consume that from an application written in any of the Windows Runtime Languages; the workflow is the same. Building the WRC generates a .winmd file. You reference that .winmd file from your consuming application and use its APIs.

This content shows how to consume a .winmd from a C++/WinRT application: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-events#create-a-core-app-bankaccountcoreapp-to-test-the-windows-runtime-component. In this case the WRC was authored in C++/WinRT but the workflow is the same no matter what languge it's written in, including C++/CX.

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now, since it seems resolved. Thanks! ~Steve
