### ISSUE TITLE
Automate store submission section is difficult to follow

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/windows-uwp#1725]
Would someone be able to add screen shots or a video of where to get or how to set up the tenant ID and other items? I'm also a bit confused as to why a tenant and client IDs are required in the first place. 

Direct link to the section I'm referring to: https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#automate-store-submission

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2832c544-fbca-e899-4be3-0aa567a0c6f1
* Version Independent ID: 42aa8e29-c5a9-8ed7-dd59-2c81d7072566
* Content: [Packaging UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback! I expanded the [automate Store submissions](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#automate-store-submissions) section to try to make the steps clearer, along with more specific links to the Partner Center docs for associating Azure AD and getting the credential info from the Partner Center dashboard (tenant ID, client ID, and client key). The Partner Center docs this article links to are the core docs where all of these steps are fully documented, so if have feedback on those docs (for example, you'd like to see screenshots), please submit your feedback in those articles. I hope this helps.
