### ISSUE TITLE
GetAppAndOptionalStorePackageUpdatesAsync Returns the Current App?

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/windows-uwp#1726]
When I call `GetAppAndOptionalStorePackageUpdatesAsync` while debugging locally, I am seeing one app update appear with version `1.0.0.0` which is the current app. Even more strangely, some developers are seeing the update appear with `Mandatory` set to `true` and others are seeing `false`.

![image](https://user-images.githubusercontent.com/2270364/59199204-4ec9ac00-8b8d-11e9-91e9-ea5c486c0d87.png)

All examples I've seen online assume there are updates if there is one or more `StorePackageUpdate`'s. Am I correct in thinking that this is just undocumented behaviour which is only exhibited locally and that I need to be removing any `StorePackageUpdate`'s that have a version of `1.0.0.0` or even the current app version?

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
