### ISSUE TITLE
New instance is created on activation

### ISSUE THREAD

**Issue by toredk** [MicrosoftDocs/windows-uwp#1727]
We are seeing something strange with the notification activation in case the application was started using a custom action at the end of the installation. Instead of just calling OnActivated on the running instance a new is started. Unfortunately, our application is dependent on a single running instance.

Restarting the application fixes the behavior so OnActivated is called on the already running instance.

Stranger still is that if the application MSI is run interactively (usually it is bundled together with other MSIs in an installer) it also works as expected.

I have experimented with moving the application launch to the latest point in the installer as possible, but this does not seem to have any effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Send a local toast notification from desktop C# apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by manoskow** [comment]
Hi toredk, I work at Microsoft on the notifications team. Any chance you could collect logs for us so we can understand a little better what is going on? 

Instructions:
1. from elevated cmd window run "netsh trace start wns_client per=yes"
2. start the installation
3. repro the activation scenario
4. when it is complete stop the log collection, "netsh trace stop"
5. the location of the files will be shown on screen, please email them to WindowsNotifications@microsoft.com

**Comment by toredk** [comment]
Files exchanged

**Comment by toredk** [comment]
I am beginning to suspect that this occurs because the installer starts the application elevated, leaving it in a context that the notification callback cannot access.

I see the same issue when using NamedPipe where the server does not receive messages when run elevated.

It would explain why restarting the application fixes the issues. Unfortunately I have no control over this as my MSI is called elevated from a setup.exe and there seems to be no (good) way to de-elevate an application.

**Comment by MatchaMatch** [comment]
Hi! The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers.html) should be able to help with this.

If you do create a thread over at Microsoft Q&A, feel free to share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open conversation for follow-ups.
