### ISSUE TITLE
Z-depth for Datatemplates

### ISSUE THREAD

**Issue by TheJimmyJ57** [MicrosoftDocs/windows-uwp#1728]
Since the Z-depth has to currently be set in the code-behind, it makes it very difficult to set for Datatemplated elements since they cannot be accessed by their name. Maybe being able to set it directly in the XAML would be good?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e564c0e-575e-516c-ff48-bd01656e9801
* Version Independent ID: eb4fafc4-66aa-5de1-0a58-2816919fe25c
* Content: [Z-depth and shadow for UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow#feedback)
* Content Source: [windows-apps-src/design/layout/depth-shadow.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/depth-shadow.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi there, thanks for the feedback! Would you mind [opening a new issue](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) in the WinUI GitHub with this feedback?

**Comment by chigy** [comment]
@thejimmyj57 , could you please [opening a new issue](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) in the WinUI GitHub with this feedback?

**Comment by TheJimmyJ57** [comment]
@knicholasa @chigy yep il do that right now
