### ISSUE TITLE
Additional HoloLens product documentation

### ISSUE THREAD

**Issue by tmlyon** [MicrosoftDocs/windows-uwp#1729]
Should we also be documenting which pages are supported on HoloLens settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi @tmlyon thanks for your feedback. I'm not sure I understand the question. Could you provide an example of the scenario you're talking about?

**Comment by tmlyon** [comment]
Hi @knicholasa, similar to the section showing which pages work on Surface Hub, HoloLens and HoloLens 2 run a version of the Windows Settings app with a slightly different set of pages supported. We don't currently have the set of supported protocol launches for the these pages documented, but some of the pages are listed on our [docs](https://docs.microsoft.com/en-us/windows/mixed-reality/connecting-to-wi-fi-on-hololens). I'm wondering if we should add callouts for the supported protocols in HL Settings to this page.
