### ISSUE TITLE
Set datacontext to viewmodel

### ISSUE THREAD

**Issue by mcalexster** [MicrosoftDocs/windows-uwp#1730]
In 'Binding to a single item' section in the code for MainPage.xaml.cs you say:
`this.ViewModel = new RecordingViewModel();`
Do you mean:
`this.DataContext = new RecordingViewModel();` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9882c8-2945-54d0-c418-72e5464229da
* Version Independent ID: debb8633-d2f4-bd60-7ddd-0e39d080e0f5
* Content: [Data binding overview - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart#binding-to-a-single-item)
* Content Source: [windows-apps-src/data-binding/data-binding-quickstart.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/data-binding-quickstart.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by MikeHillberg** [comment]
No, this example uses {x:Bind}, which binds implicitly to 'this', as opposed to the older {Binding} which binds implicitly to the DataContext property.
