### ISSUE TITLE
UWP JavaScript apps

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/windows-uwp#1731]
Visual Studio 2019 does not have option to create UWP JavaScript apps. Why was this feature removed and it is not documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcd2e7e-612d-29de-6b94-3bed0b772b16
* Version Independent ID: cf067679-95df-f7d2-17ec-d15cc18c0b4b
* Content: [What's a Universal Windows Platform (UWP) app? - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by Qws** [comment]
Any information about this? WinJS gone or something?

I have a webapp and I want to build UWP version.

**Comment by QuinnRadich** [comment]
Thank you for your patience.

I don't have specific information about why this capability was removed on Visual Studio 2019, but I am adding in information clarifying this when appropriate in this area of our docs. I believe you can still use Visual Studio 2017 to create UWP Javascript apps.
