### ISSUE TITLE
Please update with regard to C++/WinRT

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#1734]
You mention "Microsoft C++ with Component Extensions (C++/CX)" but elsewhere you say that you recommend C++/WinRT. Do you need to update the development options for game development or update this documentation to reflect what's happening elsewhere?

How would we go about using C++/WinRT with DX ?

And many people use C# to consume DirectX (I think using C++/CLI mostly) and some of us would appreciate some documentation on wrapping DirectX up in WinRT components for consumption from C#. Can we at least have some discussion, examples, performance analysis etc.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7eb3a0b-01fd-11fd-69f2-303cd5b436cc
* Version Independent ID: f3c3a88a-c66b-ac54-bfd8-f24f3b0da81a
* Content: [Game programming - Windows UWP applications](https://docs.microsoft.com/en-au/windows/uwp/gaming/)
* Content Source: [windows-apps-src/gaming/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/index.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams. Sorry for the delay in responding, and thanks for filing this issue.

You're right, this topic was out of date, so I just published an update to it, including a link to some code that I hope will cover the question "How would we go about using C++/WinRT with DX?".

As for content around wrapping DX up in WinRT components, I'll make a record of that ask, and put it onto my backlog. But I don't have a schedule that I can share regarding when I might find time for that, so I'll close this issue for the time being. We can revisit progress at some time in the future.

Thanks!
Steve
