### ISSUE TITLE
Hololens link broken

### ISSUE THREAD

**Issue by SoylentGraham** [MicrosoftDocs/windows-uwp#1735]
https://developer.microsoft.com/windows/holographic/using_the_windows_device_portal no longer points to instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f67548-9361-beab-49f8-7d604651c6a6
* Version Independent ID: 6194efed-24aa-74f2-7687-3e368534b74a
* Content: [Enable your device for development - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development?f=255&MSPPError=-2147217396)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
I've fixed this link. Change should be going live shortly.
