### ISSUE TITLE
Hit Testing

### ISSUE THREAD

**Issue by legistek** [MicrosoftDocs/windows-uwp#1737]
The article says "To do hit testing, you need to do bounds calculations by walking the visual tree yourself." That makes sense, but how does one do the bounds calculations for each visual - especially if complex geometries are used? There seems to be no hit testing functionality at all even at the Visual-level, nor does there seem to be a way to get an ID2D1Geometry from a Visual to use D2D for the hit testing. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8772b4-6bef-6ce1-7bdd-7e8b90321cf5
* Version Independent ID: 2fb81c9f-213c-8028-4ad0-e08c10bffd8a
* Content: [Modernize your desktop app using the Visual layer - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/visual-layer-in-desktop-apps)
* Content Source: [hub/apps/desktop/modernize/visual-layer-in-desktop-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/visual-layer-in-desktop-apps.md)
* Product: **windows**
* Technology: **desktop**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Right, I think the point is that the composition layer doesn't know the geometry of the elements in the scene, only the app/component author does. So on the D2D visuals you could do hit testing instead of asking the Visual layer to do it.
