### ISSUE TITLE
Cannot record some video

### ISSUE THREAD

**Issue by Almis90** [MicrosoftDocs/windows-uwp#1738]
When I was recording my screen while watching Netflix (the app from Microsoft store, not website) it was showing only the subtitles in the recording without video. I don't want to record Netflix, I just want to know why this is happening. Are there any other cases like that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#feedback)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The screen capture API does not allow you to capture video content that is restricted by DRM. This is by design.

**Comment by MattRibeiro** [comment]
I do not see where this is documented? It is an important design limitation - as would any other case where the screen capture API fails (i.e. is designed to fail) to capture the screen.

**Comment by ffMathy** [comment]
I agree with @MattRibeiro here.
