### ISSUE TITLE
ms-settings:display-* links incorrect

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/windows-uwp#1742]
&gt; Advanced display settings 	ms-settings:display-advanced (only available on devices that support advanced display options)

This uri actually points to "Advanced scaling settings", not to "Advanced display settings".

Also I would like to know the actual uri to the "Advanced display settings" screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by GrantMeStrength** [comment]
Hi - I believe this setting only works on devices that have the advanced display settings. in other words, if you have a system which doesn't have an advanced display settings option, it won't work.
