### ISSUE TITLE
CI instructions aren't updated for VS2019

### ISSUE THREAD

**Issue by adrientetar** [MicrosoftDocs/windows-uwp#1748]
The UWP CI instructions suggest adding TemporaryKey.pfx certificate to the repository, however VS2019 doesn't generate a pfx anymore, instead it installs the certificate directly on user machine. Here's a workaround to get Azure Pipelines working: https://www.edandersen.com/2019/05/27/missing-storekey-pfx-certificates-when-building-a-visual-studio-2019-uwp-project/

The instructions need to be updated to account for the lack of .pfx certificate in the repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this. The engineering team has confirmed the .pfx changes you reported in Visual Studio 2019, and they also confirmed that the workaround you provided does work but may not be ideal because of security implications. They are doing some investigation into new recommendations and we'll get this article updated as soon as we can.

**Comment by adrientetar** [comment]
Thanks, McLean. I'm thinking the engineering team should have provided new guidelines at the time they overhauled the feature.. spent a while trying to get VS to generate that certificate file to no avail.

**Comment by tim-weis** [comment]
I ran into the same issue after associating my application with the store in Visual Studio 2019. I solved this in a slightly different way, that doesn't require you to add the .pfx to source control or the *Secure File* library. Instead, I'm always creating the certificate on the hosted build agent, and then update the project file with the new thumbprint.

The following is a quick-and-dirty PowerShell script that sets up the environment. It works, but leaves much room for improvement. In case anyone needs a quick solution until the documentation gets updated, here it is:

~~~powershell
# Required to read the publisher data
[String]$PackageAppxManifest = "Enter path to your Package.appxmanifest file"
# Optional friendly name to use for the certificate
[String]$CertificateFriendlyName = "Test Certificate"
# Project file that stores the thumbprint that needs to be adjusted
[String]$ProjectFile = "myapp.vcxproj"

# Read publisher from AppX manifest
$xml = [xml](Get-Content $PackageAppxManifest)
$Publisher = $xml.Package.Identity.Publisher

# Create and install certificate into the local store. The certificate is valid for one year
$cert = New-SelfSignedCertificate -Type Custom `
    -Subject $Publisher `
    -KeyUsage DigitalSignature `
    -FriendlyName $CertificateFriendlyName `
    -CertStoreLocation "Cert:\CurrentUser\My" `
    -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
$Thumbprint = $cert.Thumbprint

# Update project file with thumbprint (should probably traverse the XML instead)
(Get-Content "$ProjectFile") `
    -replace '<PackageCertificateThumbprint>(\w{40})</PackageCertificateThumbprint>',  `
             "<PackageCertificateThumbprint>$Thumbprint</PackageCertificateThumbprint>" `
    | Out-File -FilePath "$ProjectFile" -Encoding utf8
~~~

**Comment by mcleanbyron** [comment]
Thanks @tim-weis. As an update, the engineering team is planning to revise this article with updated guidance in the first half of July. I'll update this issue when I know more.

**Comment by mcleanbyron** [comment]
This article has been updated with info about using the secure files feature in Azure DevOps to store certificates and with a note about the fact that Visual Studio 2019 no longer generates temporary .pfx files in UWP projects. Thanks for your feedback.

**Comment by adrientetar** [comment]
@mcleanbyron So I've looked at the new guidance but one thing that's not handled I think is when you export a certificate (with `Export-PfxCertificate`) you have to specify a password for it. And the new guidance does not afaict explain how to deal with password-protected certificate. The old VS2017 would generate a password-less certificate in the repository.

Relevant error message: `Error APPX0105: Cannot import the key file 'd:\a\_temp\DevCert.pfx'. The key file may be password protected. To correct this, try to import the certificate manually into the current user’s personal certificate store.`

**Comment by mcleanbyron** [comment]
Thanks for pointing this out. I followed up with the engineering team and added some further guidance about dealing with password-protected files (store the password in Azure Key Vault, map it to a variable group that you can reference in the pipeline, and specify the password via the PackageCertificatePassword MSBuild argument).
