### ISSUE TITLE
Runtime pin muxing documentation possibly outdated?

### ISSUE THREAD

**Issue by Googulator** [MicrosoftDocs/windows-uwp#1751]
Since ACPI 6.2, an equivalent of the vendor-specific MsftFunctionConfig() macro has been added, under the name PinFunction(), with an almost identical API (an extra optional parameter was added before VendorData). From my testing, this new standard macro seems to be supported and treated as an equivalent of MsftFunctionConfig in recent Insider builds.

It would be great to have this documented, with information on what minimal Windows version is the new macro available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a2e04a4-8907-8373-6d08-d7bf0db92e44
* Version Independent ID: 1505bdc2-54ab-1650-ca96-c1df5b482d18
* Content: [Enable usermode access to GPIO, I2C, and SPI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-usermode-access#feedback)
* Content Source: [windows-apps-src/devices-sensors/enable-usermode-access.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/enable-usermode-access.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Googulator - I believe this issue might be addressed by the PRs mentioned in this thread. Please open a new bug if that's not the case. Thanks!

**Comment by Googulator** [comment]
Just checked the documentation in question - it's unchanged. Also, no PRs were ever mentioned in this thread at all.

Reposted as https://github.com/MicrosoftDocs/windows-uwp/issues/2942

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Googulator, I'll check your new issue. Might need more info. There was a PR referenced immediately prior to my response that revised the topic significantly.
