### ISSUE TITLE
Code comment mistake

### ISSUE THREAD

**Issue by liam-tuite** [MicrosoftDocs/windows-uwp#1754]
"VisualState to be triggered when the width is &gt;=720 effective pixels"

Shouldn't this be 640 pixels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06eec92b-e1ef-945f-bc1a-0fa3e23c77de
* Version Independent ID: 50fbbe23-6e9d-d4a7-7242-b9e9c04fc0d2
* Content: [Responsive layouts with XAML - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layouts-with-xaml)
* Content Source: [windows-apps-src/design/layout/layouts-with-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/layouts-with-xaml.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Yes, I would agree. @liam-tuite you can submit fixes for these doc issues if you would like! Clicking the "edit" button on the doc page will take you to github where you can create a PR to fix these issues you've found. If you want to contribute that way we would be eternally grateful. :)
