### ISSUE TITLE
C++/Winrt Author Events needs an event_revoker example

### ISSUE THREAD

**Issue by stecrain** [MicrosoftDocs/windows-uwp#1760]
Hi!

I think it would be great to include an example of authoring an event with the event_revoker pattern on the page [Author Events](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events)

Just to make sure there is no confusion, I'm referring to the event revoker pattern demonstrated [here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events#revoke-a-registered-delegate) with a button's click handler.

**Comment by stevewhims** [comment]
Hi, @stecrain, you get default (auto) event_revoker behavior for free. In the [Author events](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-events) topic, in the "Create a Windows Runtime Component" section, in the listing for `BankAccount.cpp`, the necessary registration and (manual) revocation functions are shown. But, as the content below the listing say, "You don't need to implement the overload for the event revoker [...]—that's taken care of for you by the C++/WinRT projection."

~Steve

**Comment by stecrain** [comment]
Oh cool thanks for the response!

**Comment by stevewhims** [comment]
You're welcome, I'll go ahead and close this for now. ~Steve
