### ISSUE TITLE
Broken link "XAML Island"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1761]
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs
![dialogs_e](https://user-images.githubusercontent.com/40815708/59977059-91689b00-9607-11e9-8fb2-9610fbfbf36d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3361e67d-b904-0d10-42d7-abf317fbf0ab
* Version Independent ID: 993d923a-b11a-2f4e-6751-a0a266109e8b
* Content: [Dialog controls - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by marb2000** [comment]
The right link is https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands 
@jwmsft can you please, update the reference?

**Comment by jwmsft** [comment]
The link update has been submitted.
