### ISSUE TITLE
Import PFX password-protected certificate to be used for build

### ISSUE THREAD

**Issue by bertrandpons** [MicrosoftDocs/windows-uwp#1763]
Hello,

Question based on the following documentation: https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps.

Would it be possible to have more explanation on how to use certificate for UWP app, the certificate being supposed to be handled at build time?

So far, I use Secure Files, then use tasks _Download Secure File_ and _Copy Files_ to upload it in my UWP project.
The problem is that, as the certificate is password-protected, the build fails. 

Could you please indicate how to handle the password ?

Thanks for your help

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. The engineering team that owns this scenario is looking at updating this article. I will update this issue when we know more.

**Comment by mcleanbyron** [comment]
Last month we updated significant updates to this article, including new guidance about handling passwords for private keys in the certificate. Hopefully the updated guidance provides the info you're looking for. If not, please feel free to reopen this issue with more details.
