### ISSUE TITLE
Provide full source code or sample.

### ISSUE THREAD

**Issue by mitulsuthar** [MicrosoftDocs/windows-uwp#1766]
Being able to see the final code or how the above code fits into the whole application would be nice. I always get lost on these types of articles on how to make it work. I keep clicking on pages are after pages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8b97f34-8667-87fa-32d0-e1abfe285f26
* Version Independent ID: 9d8319c7-7d78-4ab3-a8e1-5a2b2d135f17
* Content: [Register a background task - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/register-a-background-task)
* Content Source: [windows-apps-src/launch-resume/register-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/register-a-background-task.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi @mitulsuthar, I found the following sample in GitHub, is this helpful? https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BackgroundTask 

If so I can update this page to contain a link to this sample.

**Comment by mitulsuthar** [comment]
Yes. That is helpful.

**Comment by Fieel** [comment]
Yes. It's useless here though.

@mitulsuthar is right, most of the microsoft docs nowadays lack examples and just show you a single line of code or a method without context at all. This whole article doesn't even tell you HOW or WHERE to register a background task, and the title of this article is "Register a background task". Should be changed into "Shows you how to create a generalized method that allows you to register a task, when called correctly (you'll have to figure this last part alone)."

Sorry for the rant, but i just spend a whole morning reading all these pages and i learnt nothing.
