### ISSUE TITLE
TreeView.SelectedNodes always empty when SelectionMode is Single

### ISSUE THREAD

**Issue by gregmeess** [MicrosoftDocs/windows-uwp#1767]
When the TreeView has `SelectionMode="Single"`, the `SelectedNodes` property is always empty. This must either be a bug, or there is a different way to get the single selected node that isn't documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245536a-3179-ff1e-dfd5-76898d07381b
* Version Independent ID: 145609fa-8e77-5878-3402-7bcc69df8ccc
* Content: [Tree view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by gregmeess** [comment]
Providing my related StackOverflow post in case context helps:
https://stackoverflow.com/questions/56766785/uwp-get-selected-nodes-from-treeview-control

**Comment by jevansaks** [comment]
Thanks for reporting! This is a product bug that we are tracking as https://github.com/microsoft/microsoft-ui-xaml/issues/124.
