### ISSUE TITLE
Broken link "XAML Island"  (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1769]
related issue: #1761 
![dialogs_j](https://user-images.githubusercontent.com/40815708/60379441-b3ca4080-9a6d-11e9-98f5-2b1784b458a8.png)
https://docs.microsoft.com/ja-jp/apps/desktop/modernize/xaml-islands
↓
https://docs.microsoft.com/ja-jp/windows/apps/desktop/modernize/xaml-islands

[LOC] Back-Translation "XAML アイランド"→"XAML Island"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3361e67d-b904-0d10-42d7-abf317fbf0ab
* Version Independent ID: 993d923a-b11a-2f4e-6751-a0a266109e8b
* Content: [ダイアログ コントロール - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Is this a different link than #1761?

**Comment by hyoshioka0128** [comment]
Please close it because PR was done.
https://github.com/MicrosoftDocs/windows-uwp.ja-jp/pull/18

**Comment by hyoshioka0128** [comment]
PR done. Close #1769 
https://github.com/MicrosoftDocs/windows-uwp.ja-jp/pull/18
