### ISSUE TITLE
Type of field of beneficiaries type is wrong.

### ISSUE THREAD

**Issue by bronze1man** [MicrosoftDocs/windows-uwp#1770]
The document of type of field of beneficiaries type is wrong. It should be List&lt;UserIdentity&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea910a17-224b-95a9-5baa-b119a9362764
* Version Independent ID: 407c87b4-7506-8b83-e646-012cc13948a6
* Content: [Query for products - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products#feedback)
* Content Source: [windows-apps-src/monetize/query-for-products.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/query-for-products.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by MoonCha** [comment]
I also found that if I put `UserIdentity`, not `list<UserIdentity>`, I get:
```
{
  code: 'BadRequest',
  data: [],
  details: [],
  innererror: {
    code: 'InvalidRequestBody',
    data: ['Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type \'System.Collections.Generic.IList`1[Microsoft.MarketplaceServices.Collections.Contracts.V6.UserIdentityContractV6]\' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath \'beneficiaries.identityType\', line 1, position 33.'],
    details: [],
    message: 'The request body passed is invalid.'
  },
  message: 'The calling client sent a bad request to the service.',
  source: 'CollectionsFD'
}
```

**Comment by hickeys** [comment]
Just made this change, it should be published shortly.
