### ISSUE TITLE
Publish to testers only

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#1772]
Is it necessary to Publish in order for the package to be available to beta testers? I've submitted a package that passed certification, put my own name on a beta testing list, and tried the download link provided for testers - but the link is invalid. As the package in question is not the completed product we don't want it visible on the store until it is ready, and the term, 'publish' might imply making it public.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88324ff2-c068-783e-95df-5e62675cbf53
* Version Independent ID: 011e0c45-77cb-a6bd-7eee-af11aa3f16a7
* Content: [Manage submission options - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/manage-submission-options#publishing-hold-options)
* Content Source: [windows-apps-src/publish/manage-submission-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/manage-submission-options.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Publishing your app will put it in the store with the visibility criteria you selected when you created your submission. If you selected a restricted visibility, only accounts you've listed will be able to see the submission.
