### ISSUE TITLE
Private audience

### ISSUE THREAD

**Issue by WinBase** [MicrosoftDocs/windows-uwp#1773]
i initially set my (new) app up as for private audience only as i remember looking at the list of testers, however now i come back into it to setup people i find its changed to 'public audience' and i cant change it back - WTF WHY !!!!. i dont remember doing this but maybe i did, however when i look here and search the web theres no info on how i can change it back other than a cursory 'you can't change it back' with no info on why. ive been growing ever increasingly frustrated with microsoft an the overly complicated ways of doing everything, and although you get pages and pages of info, its usually hard to digest it and get to the salient points you need when you have a 1000 other things to do in your day.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1cc4da-53ea-e79d-c59a-c213e75db486
* Version Independent ID: b56a46e7-785a-6bd1-030c-8c500c268bfc
* Content: [Choose visibility options - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/choose-visibility-options#audience)
* Content Source: [windows-apps-src/publish/choose-visibility-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/choose-visibility-options.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
