### ISSUE TITLE
Error in docs - "Update" no longer present

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#1774]
I'd like to update a package, but the above sentence, "To create a new submission for a published app, click Update next to the most recent submission shown on its Overview page" is apparently mistaken. There is no Update next to the submission in its Overview page. Actually I can find no way to replace a package without deleting the enter submission, which would mean filling it all out again at every update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354f0d4-e417-7896-6230-a5d7eee0fa97
* Version Independent ID: f544086d-b6f2-7e59-b099-b690eecb91ff
* Content: [App submissions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-submissions)
* Content Source: [windows-apps-src/publish/app-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-submissions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@jevansAN Can I bother you for some more information about this? 

- Is this behavior still occurring? 
- What sort of app are you trying to update (Windows app, Xbox app, Windows Phone app, etc)?
- Have you completed the account creation and verification process?
- Have you successfully submitted an update in the past?
- Is your app currently listed and available in the store, or are you in a pre-release or beta state?

Thanks,
Shawn

**Comment by jevansAN** [comment]
Shawn,

	Thanks - it’s been a while and I don’t precisely remember the situation, In any event I’m not experiencing it now - have updated several time recently.
	I appreciate the response,

	Jeff


On Jun 29, 2020, at 2:18 PM, Shawn Hickey <notifications@github.com> wrote:


@jevansAN <https://github.com/jevansAN> Can I bother you for some more information about this?

Is this behavior still occurring?
What sort of app are you trying to update (Windows app, Xbox app, Windows Phone app, etc)?
Have you completed the account creation and verification process?
Have you successfully submitted an update in the past?
Is your app currently listed and available in the store, or are you in a pre-release or beta state?
Thanks,
Shawn

**Comment by hickeys** [comment]
Thanks @jevansAN. Closing this issue since it seems to be working fine now.
