### ISSUE TITLE
Great article about making games

### ISSUE THREAD

**Issue by makerofgames** [MicrosoftDocs/windows-uwp#1776]
But why not just use unity? there are many gamedev tutorials http://bit.do/eYDXd like this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5873bf21-4560-102a-a9c8-2ad4e425be49
* Version Independent ID: dea02fb9-f0a7-739d-2926-f92d6d973026
* Content: [Windows 10 game development guide - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/e2e#feedback)
* Content Source: [windows-apps-src/gaming/e2e.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/e2e.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by jamesmcroft** [comment]
The documentation does provide information on [developing with UWP and Unity](https://docs.microsoft.com/en-us/windows/uwp/gaming/e2e#unity).

I think the point of the page referenced in general is to provide an overview of the many different ways that any developer can utilize UWP with game development.

**Comment by stevewhims** [comment]
Hi, @makerofgames. Sorry for the delay in responding, and thanks for filing this issue. I don't see anything actionable in the thread, in terms of changes that need to be made to this topic's content.

So I'll go ahead and close the issue for now.

Thanks!
Steve
