### ISSUE TITLE
No explenation of newly introduced term

### ISSUE THREAD

**Issue by capt-sms** [MicrosoftDocs/windows-uwp#1778]
WINRT_ASSERT macro used in the last example and it was not commented at all, nor any link was provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b97f1e3-af78-453e-6140-0fd37460d6c3
* Version Independent ID: e74f6cdb-2ac4-5a4d-8f73-0e97958f997b
* Content: [Boxing and unboxing scalar values to IInspectable with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/boxing#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/boxing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/boxing.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing this issue, @sm-sabat. You raise a good point. I've now updated the docs with more info.

`WINRT_ASSERT` is a macro definition, and it expands to [_ASSERTE](https://docs.microsoft.com/cpp/c-runtime-library/reference/assert-asserte-assert-expr-macros?view=vs-2019).

Thanks!
Steve
