### ISSUE TITLE
Please change Microsoft Store ID key valid time to 60 minutes or never.

### ISSUE THREAD

**Issue by bronze1man** [MicrosoftDocs/windows-uwp#1780]
In the document, Each Microsoft Store ID key is valid for 90 days. So I have to wait 90 days to test my application is correct? I looks like I will get an bug after 90 days after my application is release to product.

I will forgot this bug exist in my code.So I have to speed a lot of time to debug this bug.

Please change the Microsoft Store ID key valid time shorter, so I can test and  verify my code easier.
Or change the Microsoft Store ID key valid forever, so I do not need care about this stuff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-4)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
