### ISSUE TITLE
maxVersionTested triggers build warning

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#1781]
In VS 2019, when I add maxVersionTested to my manifest like instructed in this page, I get the following warning:

```
1>resources\app.manifest : manifest authoring warning 81010002: Unrecognized Element "maxVersionTested" in namespace "urn:schemas-microsoft-com:compatibility.v1".
```

I'd like to not have to silence this warning because it can be useful to correct mistakes - is there any way to fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d29a354-62d8-f881-7338-71a2fe60644e
* Version Independent ID: 234b48b4-9c6c-db8b-626c-0bd98d7a63a7
* Content: [UWP controls in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands)
* Content Source: [hub/apps/desktop/modernize/xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/xaml-islands.md)
* Product: **windows**
* Technology: **desktop**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're encountering this issue. I tested this out in Visual Studio 2019 version 16.1.3 with version 10.0.18362.1 of the Windows SDK and am not seeing this warning after adding the maxversiontested element to app manifest files in new WPF and Windows Forms projects. Can you clarify which versions of the tools you have installed and whether you're seeing this warning in new projects?

**Comment by sylveon** [comment]
Brand new C++ project using the Windows SDK 18362 on Visual Studio 2019 16.2 Preview 3.

I added the following manifest, copied verbatim from the docs:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
        <application>
            <!-- Windows 10 -->
            <maxversiontested Id="10.0.18362.0"/>
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
        </application>
    </compatibility>
</assembly>
```

and got the following output when building
```
1>------ Build started: Project: ConsoleApplication2, Configuration: Debug Win32 ------
1>ConsoleApplication2.cpp
1>
1>app.manifest : manifest authoring warning 81010002: Unrecognized Element "maxversiontested" in namespace "urn:schemas-microsoft-com:compatibility.v1".
1>ConsoleApplication2.vcxproj -> C:\Users\Sylveon\source\repos\ConsoleApplication2\Debug\ConsoleApplication2.exe
1>Done building project "ConsoleApplication2.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by mcleanbyron** [comment]
Thanks for the additional details. The engineering team has confirmed that this is a known minor issue. Given that it is just a warning that can be ignored, they have no plans on fixing this issue at this time. I will add a note about this to the article you referenced.

**Comment by mcleanbyron** [comment]
The article has been updated with the note. Thanks again for your feedback!

**Comment by sylveon** [comment]
Actually, this is breaking. `maxVersionTested` is completely ignored by WindowsXamlSource but `maxversiontested` is not, even though the guide instructs to use the camel cased name.

**Comment by mcleanbyron** [comment]
Thanks for catching that. The examples did specify 'maxversiontested' without camel casing but the surrounding steps/instructions showed it camel cased. I updated the text so it is shown consistently without camel casing everywhere.

**Comment by EatonZ** [comment]
Hi, may be slightly off topic, but what exactly is the benefit of setting _maxversiontested_ in a manifest?
The [documentation](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests) doesn't really state why it may be beneficial. If I were to set it in say, a WinForms app, what would happen exactly? I already use _supportedOS_.

**Comment by sylveon** [comment]
It's used for Xaml Islands, unless you use that it will have no impact on
your winforms app.

**Comment by osolo** [comment]
@mcleanbyron Is there any way to suppress these warnings?

**Comment by sylveon** [comment]
Using the ""correct"" version, `maxversiontested`, does not emits warnings anymore for me.

**Comment by osolo** [comment]
What is the "correct" version?  I have the following, using the release SDK version, and I still get a warning:

```xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <maxversiontested Id="10.0.18362.0"/>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
    </application>
  </compatibility>
</assembly>
```

**Comment by sylveon** [comment]
Oh yeah my bad I actually just removed maxversiontested from my manifest because I use the MSIX packaging format now.

**Comment by ChrisGuzak** [comment]
This is a [bug in mt.exe](https://dev.azure.com/microsoft/OS/_workitems/edit/21830973/) and has been fixed in SDKs 19508 and above (unreleased at this date). @GovM-MSFT FYI.

**Comment by GovM-MSFT** [comment]
Agreed.
Gov (Rhymes with Orange)

Work It Harder Make It Better
Do It Faster, Makes Us stronger
More Than Ever, Hour After Hour
Work Is Never Over
________________________________
From: Chris Guzak ***@***.***>
Sent: Tuesday, June 15, 2021 12:11:04 PM
To: MicrosoftDocs/windows-uwp ***@***.***>
Cc: Gov Maharaj (ORANGE) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/windows-uwp] maxVersionTested triggers build warning (#1781)


I suspect that the manifest compiler schema is missing this and that is the source of the warning. if so we should update the manifest compiler to fix this. @GovM-MSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGovM-MSFT&data=04%7C01%7Cgovm%40microsoft.com%7Cad49713d39a54c50b91a08d930315324%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637593810698664375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XADNBRzC0l1jrRqljF0XROS6Y48Jn5feGODrGhtAWzQ%3D&reserved=0> FYI.

**Comment by alecazam** [comment]
This part of the AppManifest is really unclear.  The docs state that you can set the minimum and maximum OS.  But supportedOS seems to be Win10, and not the 20 versions of it.  So is that my minimum OS?  But I want build 1903  to be the minimum.   I fail to see how maxversiontested is even useful, unless say Win11/12 want's to set some Win10 compatability checkbox.  And maxversiontested won't be honored until build 1903.

MSIX has a MinVersion and a MaxVersionTested which make so much more sense.  And they don't pull in bizzare GUIDs for the supportedOS.  You just specify the min/max.  But we're using Steam to install, so there is no MSIX installer.  So I assume we're stuck with just killing the app if we detect an older variant in the last 10 years of Win10 that we don't want.

```
<Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.21301.0" />
</Dependencies>
```

**Comment by sylveon** [comment]
maxversiontested doesn't do what you want anyways. It won't make the OS prevent your app to run on lower versions. It's merely to signal to XAML islands what compatibility level to use.

Neither does supportedOS btw - an app with the Windows 10 supportedOS GUID will still launch on Windows 7.

**Comment by alecazam** [comment]
Steam is sunsetting Win7/8/8.1.  And when Win10 32-bit OS, it will be a good thing, even though we don't support it.  So we just reject any Windows version before build 1903 explicitly in the code now.  I'd just hoped there was a way to say for a Win32 app to specify the minspec x and maxspec x+2 in the app manifest.   We do this on iOS/macOS very easily, and it also transfers to the App Store.
