### ISSUE TITLE
Private audience to work/school account

### ISSUE THREAD

**Issue by PatricioVidal** [MicrosoftDocs/windows-uwp#1782]
We are releasing to a private audience but some of the emails are work/school account. Those user can not see the listing. It works fine for personal emails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1cc4da-53ea-e79d-c59a-c213e75db486
* Version Independent ID: b56a46e7-785a-6bd1-030c-8c500c268bfc
* Content: [Choose visibility options - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/choose-visibility-options#feedback)
* Content Source: [windows-apps-src/publish/choose-visibility-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/choose-visibility-options.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
