### ISSUE TITLE
Broken link "Windows Ink"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1784]
![using-the-xaml-hosting-api_e](https://user-images.githubusercontent.com/40815708/60876231-6a9c9c80-a276-11e9-91dc-bae813773a2a.png)

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2fc66b-ffa8-5128-8658-a8ea1d064e47
* Version Independent ID: ce50830e-9947-ad68-709c-1e3fd049bb71
* Content: [Using the UWP XAML hosting API in a desktop application - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api)
* Content Source: [hub/apps/desktop/modernize/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/using-the-xaml-hosting-api.md)
* Product: **windows**
* Technology: **desktop**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this broken link. It has been fixed.
