### ISSUE TITLE
Typos in the Markup Extensions Sub-Header

### ISSUE THREAD

**Issue by TheFanatr** [MicrosoftDocs/windows-uwp#1790]
In the [Markup Extensions](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-overview#markup-extensions) sub-header, `{x:Bind}` is written incorrectly as `{xBind}` in the bullet-point list, and in the second paragraph after the aforementioned list, there is a grammatical error in the text `A markup extension generally return an existing instance ...`, where `return` is supposed to be `returns`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe863fa1-564d-ddfb-46b0-14fae5faf7d2
* Version Independent ID: b132ba05-3b74-348f-b5a1-30cf7401c5ba
* Content: [XAML overview - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-overview#markup-extensions)
* Content Source: [windows-apps-src/xaml-platform/xaml-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/xaml-overview.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@TheFanatr You can make changes to the docs via the "Edit" button when suggesting typo fixes. :)
