### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by MasterSU** [MicrosoftDocs/windows-uwp#1791]
应在开头提示需要在包清单-&gt;功能中启用相应功能才可正常使用。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6c57c086-3015-37b6-5318-b90a8e1fc0ba
* Version Independent ID: 94556012-dcdd-1dde-c8e5-147e1d05d5c0
* Content: [蓝牙 GATT 客户端 - Windows UWP applications](https://docs.microsoft.com/zh-cn/windows/uwp/devices-sensors/gatt-client)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by jwmsft** [comment]
Bing translation: You should be prompted at the beginning that you need to enable the feature in the package manifest-function for proper use.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @MasterSU. The en-us topics have been updated with this added detail. Localized versions will take some time to propagate.
