### ISSUE TITLE
Typo on this page

### ISSUE THREAD

**Issue by sudoJoe** [MicrosoftDocs/windows-uwp#1793]
In the paragraph under 'UWP', in the third sentence, a word is incorrectly repeated twice:

"applications that that require.."

The sentence should read "..applications that require.."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56f2824-b04c-1e07-2de1-2f78f84834d1
* Version Independent ID: b73656a9-ba3d-2411-dfca-031586aad016
* Content: [Choose your app platform - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform#feedback)
* Content Source: [hub/apps/desktop/choose-your-platform.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/choose-your-platform.md)
* Product: **windows**
* Technology: **desktop**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for catching this. This issue has been fixed.
