### ISSUE TITLE
Full sample code?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/windows-uwp#1795]
Hi,

I wish we could see the full source code for the [one column form example](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/forms#one-column-form-example).
Right now, only the details pane is shown.
What I'm interested in seeing is how you set and designed the master pane as well.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4880cbc-5a88-e2fd-ea54-23de0d3b9d8c
* Version Independent ID: 2526993f-b1c3-ea37-a54e-d237a7540360
* Content: [Forms - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/forms#one-column-form-example)
* Content Source: [windows-apps-src/design/controls-and-patterns/forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/forms.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
I believe the master pane is from the "master/details" scenario which has a source code sample: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/master-details. Is that what you were looking for?

**Comment by weitzhandler** [comment]
I was referring to the one in this image, I haven't been able to find it.

![image](https://user-images.githubusercontent.com/2716316/61274165-e4231600-a7b3-11e9-8842-2c03b5e5788e.png)

I was specifically referring to the middle column, I wanted to see what you used to create the search box, add button and `ListView`.

Feel free to close this issue, but it'd be nice if the samples for the screenshots are included in the page or linked from it.

Thank you Jevan!

**Comment by jevansaks** [comment]
I don't see a sample that produces exactly what's in that screenshot. Maybe @micahl can help find it the source?

**Comment by micahl** [comment]
Sorry, I'm not familiar with this.  @serenaz do you have the original (full) source from when this doc was originally authored?

**Comment by weitzhandler** [comment]
WOW, it's gone way further than I'd thought, thank you so much for your effort folks!

**Comment by serenaz** [comment]
I don't have the source on my current machine, but the example uses a NavigationView control, which allows you to add a search bar, add button, and ListView.
https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/navigationview

Hope that helps!

**Comment by weitzhandler** [comment]
K tx guys I'll do it myself
I was hoping to do it the same way u did with fluent design styles, but appreciate the effort!
