### ISSUE TITLE
Javascript UWP template prerequisites

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/windows-uwp#1802]
> (If you don't see any Universal templates, you might be missing the components for creating UWP apps. You can repeat the installation process and add UWP support by clicking Open Visual Studio installer on the Create a new project dialog. See Get set up

I have about half of the VS workloads installed, including node.js development and UWP workload. I have C# and VB.NET UWP templates, but no javascript UWP template. What do I need to do to get that template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b996558c-4643-b37a-5afb-9cd14369b8bf
* Version Independent ID: de5b8514-6616-11ee-7725-c9456bbd8689
* Content: [Create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-js-uwp#feedback)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-js-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-js-uwp.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by zivkan** [comment]
After some web searches, I found this: https://developercommunity.visualstudio.com/comments/533695/view.html

I believe this docs page should be deleted, or changed back to say VS2017, because this project type is not supported by VS2019.

**Comment by amcasey** [comment]
Another customer identified these pages with similar issues:
https://docs.microsoft.com/en-us/windows/uwp/get-started/your-first-app
https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-js-uwp

**Comment by QuinnRadich** [comment]
Clarifying remarks have been added to this topic.
