### ISSUE TITLE
ToggleButton should be documented in this page?

### ISSUE THREAD

**Issue by chigy** [MicrosoftDocs/windows-uwp#1807]
There was no mention of &lt;ToggleButton/&gt; in this page which I felt should be there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6e57c0-4d39-7608-e535-f3bf35d3f7a2
* Version Independent ID: 826f8e2b-b5be-3c62-6bb6-85abea1bfba4
* Content: [Buttons - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons)
* Content Source: [windows-apps-src/design/controls-and-patterns/buttons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/buttons.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Maybe just be a mention in the list, then link to [Toggles](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/toggles) page, which should be updated with more ToggleButton info?

**Comment by jwmsft** [comment]
Doc has been updated.
