### ISSUE TITLE
Packaging Project Build Failed

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#1811]
I was ready to build the packaging project when the project threw an error:
MSB3030	Could not copy the file "&lt;path&gt;\ContosoExpenses\&lt;compile path&gt;\netcoreapp3.0\Microsoft.Toolkit.Win32.UI.XamlHost.dll" because it was not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7844818-d0b7-f502-3a07-a4970401fdcf
* Version Independent ID: 1acada53-18fa-68a2-4211-c4c3236c856e
* Content: [Package and deploy with MSIX - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-5.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-5.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this. We are investigating this issue.

**Comment by mcleanbyron** [comment]
The engineering team has published updates to the XAML Island-related NuGet packages used by this tutorial, and we have also revised the instructions on this page. I have tested everything out and confirmed that everything works. If you still encounter issues with this tutorial, please feel free to reopen this issue or open a new one.
