### ISSUE TITLE
Python for scripting of Windows

### ISSUE THREAD

**Issue by tonybaloney** [MicrosoftDocs/windows-uwp#1812]
Thanks for putting this useful resource together.

For beginners, I think they could benefit from some important information around PowerShell, and the exposure of APIs via Managed DLLs.

For example, many of the system configuration options in the Windows platform are only available via managed DLLs, using a PowerShell CmdLet or using the native management tools.

If the users were coming at this from a *nix background they might assume that they can automate the OS using flat-file configuration and shell commands, which they can't.

If someone wanted to setup a web application, they would use the IIS cmdlets, not edit the IIS XML files by hand (I hope!) https://docs.microsoft.com/en-us/powershell/module/iisadministration/?view=win10-ps

The examples in the page are great, but perhaps a caveat a the top about would save people a lot of time in future.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5009df67-94f4-00b3-3ffe-67801622f152
* Version Independent ID: 35d84635-3e48-afe0-d2ae-79202497d64a
* Content: [Scripting and automation with Python on Windows - Windows apps](https://docs.microsoft.com/en-us/windows/python/get-started/python-for-scripting#feedback)
* Content Source: [hub/python/get-started/python-for-scripting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/get-started/python-for-scripting.md)
* Product: **windows**
* Technology: **hub**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks Tony!  Appreciate the feedback!

Do you think it would be more helpful if we set the context at the beginning of the article that we're not really doing special Windows-specific stuff... rather just pointing out some of the helpful libraries in Python that can automate tasks across platforms... like searching your file system, accessing the internet, parsing file types, etc... but from a Windows-centered approach?  

Maybe with a link at the end to https://docs.python.org/library/ctypes.html and https://docs.python.org/library/winreg.html for more Windows-specific operations?

...and to https://pypi.org/project/winrt/ for Windows Runtime API calls? 

Is that the sort of caveat that you mean?

**Comment by tonybaloney** [comment]
Yes, this is exactly what I mean. thanks.

**Comment by mattwojo** [comment]
Took me a while to get to it (sorry--got focused on a new project), but finally got a note about this is in: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/342 

Thanks again for your feedback Tony! Closing this out.
