### ISSUE TITLE
Screenshot of the dialog is outdated and should be updated

### ISSUE THREAD

**Issue by chigy** [MicrosoftDocs/windows-uwp#1813]
The screenshot of the dialog is outdated with the accent color border. We replaced it with shadow and no border and should reflect that change in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3361e67d-b904-0d10-42d7-abf317fbf0ab
* Version Independent ID: 993d923a-b11a-2f4e-6751-a0a266109e8b
* Content: [Dialog controls - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/dialogs.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Images are updated.
