### ISSUE TITLE
Too limited usage makes this almost useless for many apps

### ISSUE THREAD

**Issue by dingsheng999** [MicrosoftDocs/windows-uwp#1814]
For example, a photos app usually needs to list all photos of a folder but for many cases the folder is not indexed. As a developer I cannot rely on this. There is an obvious performance gap between Win32 application methods and this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 118371e5-b7e2-febe-b88f-bdeb068db567
* Version Independent ID: 237eeb03-4115-2226-ff7b-d84208af6883
* Content: [Fast access to file properties in UWP - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/fast-file-properties#feedback)
* Content Source: [windows-apps-src/files/fast-file-properties.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/fast-file-properties.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi @dingsheng999, this is good feedback, but it looks like it's product feedback rather than documentation feedback. Please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and up-vote it.
