### ISSUE TITLE
Screenshot Out of Date

### ISSUE THREAD

**Issue by scottkuhl** [MicrosoftDocs/windows-uwp#1816]
The screenshot has not been updated for version 3.3.  It is missing the sections for Services and Testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 267c2143-4e40-fce9-97b8-8b3ebb10e555
* Version Independent ID: 7570c8f4-d0fa-bdbc-4ac6-71821b1a11eb
* Content: [Windows Template Studio - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/windows-template-studio/#feedback)
* Content Source: [windows-apps-src/design/windows-template-studio/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/windows-template-studio/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by kmahone** [comment]
@LucasHaines please take a look. It looks like it might have been fixed already. Please close if nothing further is required.

**Comment by QuinnRadich** [comment]
Apologies for the longstanding issue. Closing this as nothing further is required (and the Template Studio docs have been unlisted from the table of contents, anyways.)

Thank you.
