### ISSUE TITLE
Please help, I can't update my payout assignment

### ISSUE THREAD

**Issue by namlgiang** [MicrosoftDocs/windows-uwp#1819]
https://i.imgur.com/PlVQBmh.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [Set up your payout account and tax forms - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thank you for logging this issue. 

In general, GitHub comments should not be used for logging bugs against products; they are only for documentation issues. However, I happen to have been working with this team on this exact page for the last couple weeks, so I've gone ahead and passed this along to them. I will update here when I hear back from them.

**Comment by hickeys** [comment]
Hello namlgiang. 

The dev team would like some additional information from you. Could you contact me at hickeys@microsoft.com?

**Comment by hickeys** [comment]
Closing this as it has been inactive for quite some time.

**Comment by dpanov76** [comment]
I have exactly the same issue. I an trying to create consumable IAP product but have error message -You need to update your tax and payout information before you can charge money. Despite I have already have valid tax profile. Please sort this out for me. I can't list my game otherwise
