### ISSUE TITLE
Use Graphics.Capture API without GraphicsCapturePicker

### ISSUE THREAD

**Issue by nadavisr** [MicrosoftDocs/windows-uwp#1820]
Hi,
Is there a way to capture the screen without displaying GraphicsCapturePicker to the user?
I want my program to capture and record the screen without user intervention 
Thanks,

**Comment by drewbatgit** [comment]
The picker serves a dual purpose, to allow the user to pick the capture target and also to ensure the user has provided consent for the capture operation. Therefore, there is not currently a mechanism for capturing without this picker.
