### ISSUE TITLE
Missing Instruction for Required Flag

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/windows-uwp#1824]
When following these directions, you'll end up being stuck with a compiler error stating that you can only have one "entry point". To avoid this, you need to set a flag to tell the compiler that the Program.cs Main should be used instead.

This is done by disabling XAML generated entry point using the `DISABLE_XAML_GENERATED_MAIN` flag in the csproj property groups:

Before (incorrect)
```xml
<DefineConstants>DEBUG;TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>
```

After (correct)
```xml
<DefineConstants>DEBUG;TRACE;NETFX_CORE;WINDOWS_UWP;DISABLE_XAML_GENERATED_MAIN</DefineConstants>
```

![image](https://user-images.githubusercontent.com/3520532/61910801-99b43e80-af03-11e9-97f1-47942d218d2a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c161a2e-d9f4-466f-5a63-5e25648a1779
* Version Independent ID: 6032f644-b69d-622f-73df-bacebdfc4509
* Content: [Create a multi-instance Universal Windows App - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by dpaulino** [comment]
@LanceMcCarthy thank you for this. Saved me from pulling my hair out!

**Comment by gilebert** [comment]
Thanks for this info.  Useful to know.

**Comment by GrantMeStrength** [comment]
Documentation updated.
