### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#1825]
the link to XamlApplication.cs on GitHub is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2fc66b-ffa8-5128-8658-a8ea1d064e47
* Version Independent ID: ce50830e-9947-ad68-709c-1e3fd049bb71
* Content: [Using the UWP XAML hosting API in a desktop application - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api)
* Content Source: [hub/apps/desktop/modernize/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/using-the-xaml-hosting-api.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by asklar** [comment]
actually a lot of the GitHub links on that page are broken

**Comment by mcleanbyron** [comment]
Thanks for reporting these. This page has been revised and all of the sample links updated to point to the latest/current samples. If you see any further issues, please feel free to reopen this issue.
