### ISSUE TITLE
Doesn’t specify which asset is used in a window title bar

### ISSUE THREAD

**Issue by matthewpaulthomas** [MicrosoftDocs/windows-uwp#1828]
The page begins “Every app has an icon/logo that represents it, and that icon appears in … • The title bar of your app window”.

The following table of where each “Icon name” “Appears in” specifies many different places in the Windows GUI — but unfortunately not the window title bar. Nor is this specified anywhere else in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc48efcd-ad3f-1b01-6a6a-a6865b4b7624
* Version Independent ID: 84184d50-3c9b-cce9-6007-3ef2e954cdf5
* Content: [App icons and logos - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos#feedback)
* Content Source: [windows-apps-src/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/app-icons-and-logos.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
UWP apps don't show the icon in their title bar, we should update the docs to clarify that. Thanks!

**Comment by chigy** [comment]
Trying to locate area experts for outside of UWP.

**Comment by matthewpaulthomas** [comment]
I had assumed one of the assets was used in the title bar because I was looking at a WSL “distro” — which is an .appx in the Store, and therefore follows the UWP asset behaviour in other respects, but also _does_ have an icon in its (console window) title bar. I’ve since discovered that [this icon is from a separate .ico file](https://github.com/Microsoft/WSL-DistroLauncher#getting-started).

Since this page is specifically addressing UWP, I think just removing the “title bar of your app window” list item would resolve the issue.

**Comment by mijacobs** [comment]
I've submitted an update to the article, it should be live shortly.
