### ISSUE TITLE
How to show Lifecycle events toolbar

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/windows-uwp#1830]
Hi, it would be nice to see steps how to display Lifecycle events. It's not very intuitive, hidden under Debug location toolbar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b1d81a-323c-259b-d74a-146543a751b7
* Version Independent ID: fb01280b-8799-cd35-48fd-33976b841804
* Content: [Debug a background task - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/debug-a-background-task)
* Content Source: [windows-apps-src/launch-resume/debug-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/debug-a-background-task.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by jamesmcroft** [comment]
Is this query asking how to display the toolbar? 

When reading the docs it reads well in how to active the lifecycle events through the toolbar with a screenshot of Visual Studio showing the options available.

**Comment by viktorszekeress** [comment]
There is a screenshot of the toolbar. But this toolbar is hidden by default in Visual Studio. This toolbar has quite un-intuitive name - Debug location.

There is no mention of toolbar name "Debug location".

**Comment by jamesmcroft** [comment]
Ah, I see. I thought this was what you were meaning and completely agree that it needs more info adding 👍

**Comment by knicholasa** [comment]
Thanks @jamesmcroft for the contribution! Closing the issue.
