### ISSUE TITLE
Image needs to be updated

### ISSUE THREAD

**Issue by chigy** [MicrosoftDocs/windows-uwp#1832]
There is an image that appears to be of a Sets feature that is no longer pursued.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9faf87c-bd56-99da-70ed-07c68f9118a5
* Version Independent ID: 713b5c24-d710-303f-620e-9c7735797907
* Content: [Acrylic material - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic)
* Content Source: [windows-apps-src/design/style/acrylic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/acrylic.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Which image?

**Comment by chigy** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/style/images/maps_in_app_acrylic_1.png and https://docs.microsoft.com/en-us/windows/uwp/design/style/images/mail_transientcontextmenu.png

**Comment by hickeys** [comment]
Thanks for catching that. I agree that it should be updated, but I've lowered the priority to reflect the impact more accurately.

**Comment by gus33000** [comment]
Is an update to this image still planned? I saw someone today be confused when viewing this page viewing the sets feature, was about to create a new issue but found this old existing one.

**Comment by jwmsft** [comment]
@gus33000, thanks for pinging this issue. I've published an updated image to replace the incorrect one.
