### ISSUE TITLE
API being deprecated... more details?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windows-uwp#1833]
I can't get the feedback widget to load on the doc page, but it is https://docs.microsoft.com/en-us/windows/uwp/security/companion-device-unlock from https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/companion-device-unlock.md

It says:

> Note Microsoft will be deprecating the API for the Windows Hello companion device framework in the first half of 2020.

Does that mean that the API is being deprecated from windows, or just from windows 10 iot?  It's a pretty big difference.  MS continuing to abandon windows 10 iot won't make much of a difference to most people, but removing part of the authentication framework that many enterprises and partners are actively using and building solutions for is a big deal.

**Comment by hickeys** [comment]
I've checked in with the devs and will update when I have more information

**Comment by jordanmills** [comment]
Thanks

**Comment by Mindstyler** [comment]
Are there any updates on this topic?

**Comment by hickeys** [comment]
I have not heard back. I will reach out to the team again. In the meantime, I'd like to clarify that Windows Hello is not being discontinued, this deprecation notice only applies to the companion decide unlock feature. Does this answer your question, or are you looking to run companion device APIs on non-IoT devices?

@jordanmills @Mindstyler

**Comment by Mindstyler** [comment]
I am looking to use a Yubikey / similar Fido2 keys to authenticate users during login to my application. I did extensive research on this topic and only found the Companion Device Framework to make this possible (to even read information from the Yubikey). If there is another solution that I am unaware of, please point me in the right direction. @hickeys

**Comment by hickeys** [comment]
@Mindstyler 

I still have not heard back from the team. I apologize. It might be faster to post on a Microsoft forum such as the below. 

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

I realize this is not a satisfying answer, but I can't do much beyond pinging the team again, and that doesn't seem to be working.  I'll continue to try, but hopefully you have better luck following the links above.

**Comment by hickeys** [comment]
@Mindstyler 

I received a response from the engineering team. The framework is being deprecated on all Windows platforms, including IoT but also all non-IoT versions. The team also mentioned that instead of using the yubikey directly, you may want to use SSP and use the yubikey for FIDO2 logon. I don't know if that would work for you. If not, please let me know and I can provide more resources.

**Comment by mrjester888** [comment]
This API has been deprecated for nearly a year now.  What replaced it?

**Comment by Mindstyler** [comment]
@mrjester888
I don't think anything replaced it

**Comment by psyspy1** [comment]
@hickeys I have a companion device with Bluetooth that I am planning to use to unlock my PC. That device has a button which should unlock the PC when it's clicked. The companion device framework would have perfectly fit my needs. What are the alternatives?

**Comment by skannan89** [comment]
@hickeys Could you please take a look at my comment above?

**Comment by avielc** [comment]
I'm looking for alternatives too, if anyone care to update here what they have found

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes. The documentation is correct, as the message has been updated to reflect that the feature was deprecated in all versions of Windows 10 starting in version 2004. You can pick up the discussion to talk about alternatives with the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). They can offer timely answers to a multitude of technical questions surrounding Windows client app development.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
