### ISSUE TITLE
German translation errors

### ISSUE THREAD

**Issue by MB-Atos** [MicrosoftDocs/windows-uwp#1835]
The following MS Build parameters to "renamed" in the german translation:

"PackageCertificateKeyFile" got "Packagecertificatekeyfile" (loss of CamelCase)
"PackageCertificatePassword" got "Packagecertifialisiepassword" (???)
I do not think, this is the way it should be.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Einrichten automatisierter Builds für UWP-Apps - Windows UWP applications](https://docs.microsoft.com/de-de/windows/uwp/packaging/auto-build-package-uwp-apps#feedback)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp.de-de/blob/live/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Assigning to David Prioni for localization triage.

**Comment by CeciAc** [comment]
Hello, @MatBenAtos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MatBenAtos
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/windows/uwp/packaging/auto-build-package-uwp-apps#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

#please-close
