### ISSUE TITLE
Unclear documentation regarding PackageCertificatePassword parameter

### ISSUE THREAD

**Issue by MB-Atos** [MicrosoftDocs/windows-uwp#1836]
During the explanation on how to integrate a certificate for package signing, it would help a lot if you could state that the "PackageCertificatePassword" Parameter is ONY for the private key, if it has a password at all. The refernced / used PFX file must not be password protected. Or is there another way to pass this password in as well?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/packaging/auto-build-package-uwp-apps#feedback)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. The engineering team has confirmed that you are correct - the password is only for the private key, and a password for the certificate file itself is not supported at this time. I have revised the related guidance in the article to clarify this.

**Comment by sirredbeard** [comment]
Windows requires .pfx to have a password when exporting, both the GUI and Export-PfxCertificate cmdlet. VS 2019 doesn't build a temporary key we can use. What is the easiest way to generate and bundle a key to use here?

**Comment by MB-Atos** [comment]
I don't know whether it's the easiest way, but I simply build my pfx container by use of openssl.

**Comment by skolbin-ssi** [comment]
To export a certificate to a .pxf container file without a password, pass an empty secure string object to the cmdlet:

Export-PfxCertificate -FilePath C:\temp\mycert_nopw.pfx -Password (new-object System.Security.SecureString)
