### ISSUE TITLE
Missing translation for Description column for local fr-FR

### ISSUE THREAD

**Issue by AurelienS** [MicrosoftDocs/windows-uwp#1837]
there is only few icon that have a french description. for example, 'Forward' button is not translated in French but 'Back' button is.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Recommandations en matière d’icônes Segoe MDL2 - Windows UWP applications](https://docs.microsoft.com/fr-fr/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp.fr-fr/blob/live/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by srvbpigh** [comment]
Hello, @AurelienS
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @AurelienS
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/windows-uwp.fr-fr #1](https://github.com/MicrosoftDocs/windows-uwp.fr-fr/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @AurelienS 

Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one.

Please review the status of this issue here https://github.com/MicrosoftDocs/windows-uwp.fr-fr/issues/1

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
#please-close
