### ISSUE TITLE
Setting the title bar text doesn't work as expected

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#1838]
My title bar shows "Samples". If I set the title bar text to "Engine Samples". The title bar shows "Engine Samples - Samples". I'm working in CoreApp style. And the purple box here suggesting that the code be placed in OnLaunched is wrong for CoreApps, there is no OnLaunched. I have to place the call into either Activated or Run. And both are too late as the window already has the Assembly name which then changes to the configured name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c220453a-d6f1-4e9f-4f2d-9dd366f91d31
* Version Independent ID: 16284cd7-f1b5-f43f-c7ec-7ffa1f4ef3f2
* Content: [Title bar customization - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar)
* Content Source: [windows-apps-src/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/title-bar.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@Gavin-Williams : I'm sorry, I don't know what you mean by "CoreApp" style--I'm not aware that it's an option for UWP apps. Can you confirm that you're working in a UWP app?

**Comment by Gavin-Williams** [comment]
Yes, it's UWP, The CoreApp style is no-Xaml. I implement .. [Windows.ApplicationModel.Core.IFrameworkView](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.iframeworkview) interface. 
This application model is typically seen in C++ DirectX applications. But I use it in C# when I don't want the Xaml layer, using my own rendering and UI layers. So there are some slight differences between the two models.

So I'm just trying to get access to that base title bar text - It seems the assembly name is always there and I can't get rid of it. And I would like the title bar text to be already set when it appears rather than appear with 'Samples' and then update when the Run method calls.

Here's how I change the text ..

```csharp
        // ==================================================
        // Event handlers for app lifecycle management
        // ==================================================
        private void Activated(CoreApplicationView appView, IActivatedEventArgs args)
        {
            Debug.LogMessage("App.Activated");
            ApplicationView.GetForCurrentView().Title = "Engine";

            // Run() won't start until the CoreWindow is activated
            CoreWindow.GetForCurrentThread().Activate();
        }
```

**Comment by jwmsft** [comment]
I believe this is a limitation of this feature, as parts of it rely on the XAML framework. The first purple note in the article states:
_Simple color customization is available to UWP apps using XAML, DirectX, and HTML. Full customization is available only to UWP apps using XAML._

If you set the Title property, the system always appends _- DisplayName_. This name comes from the DisplayName field in package.appxmanifest. Can you get the title bar to display what you want by updating this value to what you want in the title bar, rather than setting the Title property? (open package.appxmanifest, Application tab, Display Name field)

**Comment by Gavin-Williams** [comment]
Yes that is exactly what I'm after. Thanks for your help.
