### ISSUE TITLE
Strange description of "userPrincipalName" capability

### ISSUE THREAD

**Issue by DarkWanderer** [MicrosoftDocs/windows-uwp#1839]
The userPrincipalName restricted capability *allows apps to modify and access the thumbnail cache from photos.* - this doesn't seem right

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#feedback)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for catching this. The description for this capability has been fixed.
