### ISSUE TITLE
XAudio2Create returns bad code when called in a Hololens app.

### ISSUE THREAD

**Issue by scorkla** [MicrosoftDocs/windows-uwp#1840]
Our call to XAudio2Create in xaudio2.h:1321 is returning a bad HRESULT of 0x88960001. We are running remotely on the HoloLens.

This is happening in version 1903 (build 10.0.18362.0). It works fine in the previous build 10.0.17763.0.

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
