### ISSUE TITLE
Missed symbols

### ISSUE THREAD

**Issue by tulnov** [MicrosoftDocs/windows-uwp#1842]
Symbols EDE0, F0EF, F354, F87B(Spelling), F87C(SpellingKorean), F87D(SpellingSerbian), F87E(SpellingChinese),  F89A(FolderSelect), F8A5, F8A6, F8AA, F8AB, F8AC, F8AD, F8AE, F8AF, F8B0, F8B1, F8B2, F8B3 are missed on page with description, but presents in font Segoe MDL2 Assets version 1.78.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by hickeys** [comment]
Thanks for logging this issue. Those symbols may exist in 1.78, but Windows 10 uses 1.75. Until that changes, this page should continue to document 1.75, not 1.78.

**Comment by RehanSaeed** [comment]
What version of Windows contains 1.78 and where can we get it? I'm looking for EC4D and F077.

**Comment by tulnov** [comment]
1903 build 18950

ср, 7 авг. 2019 г. в 14:55, Muhammad Rehan Saeed <notifications@github.com>:
