### ISSUE TITLE
@ is not ampersand (content link doc)

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/windows-uwp#1843]
The second paragraph opens with:

> _When the user prefixes an entry with an ampersand (@) symbol ..._

But @ and ampersand are different things (the "ampersand" symbol is &).
The @ symbol is informally and widely (but not universally) known as the at sign. As there is no formal name for it in English, I would just omit the name of the symbol entirely and just use the symbol itself:

> _When the user prefixes an entry with the @ symbol ..._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef2a71dc-50b1-5f99-7a22-c7854253ea2e
* Version Independent ID: e869333a-1bef-0f5e-7e40-516b31b13367
* Content: [Content links in text controls - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/content-links)
* Content Source: [windows-apps-src/design/controls-and-patterns/content-links.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/content-links.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by hickeys** [comment]
Thanks for logging this issue. I've fixed it in our repo, the changes should be published shortly.
