### ISSUE TITLE
A UWP example would be appreciated for this section

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#1847]
The section Landmarks and Headings contains good info, but it would be easier to understand with a concrete example with XAML code. The example would includes LandmarkType, LocalizedLandmarkType and HeadingLevel. Thank you

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d135d1fb-1bcc-2f55-fad9-05bdcf193256
* Version Independent ID: 7b720c16-ce38-197b-e936-5404a878d7d6
* Content: [Landmarks and Headings - Windows UWP applications](https://docs.microsoft.com/en-ca/windows/uwp/design/accessibility/landmarks-and-headings#feedback)
* Content Source: [windows-apps-src/design/accessibility/landmarks-and-headings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/landmarks-and-headings.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

I've updated the topic with a couple of links to sample could that might address your issue. If not, please open a new issue with more detail.
