### ISSUE TITLE
This statement is confusing

### ISSUE THREAD

**Issue by chigy** [MicrosoftDocs/windows-uwp#1855]
This uses so many negatives that I do not understand if I should or should not use reveal. I am assuming menus do use reveal.
"If your custom control is a single interactive element and doesn't have similar controls sharing it's space (such as menu items in a menu), it's likely that your custom control doesn't need Reveal."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78173569-1e8a-76bf-98b2-e4f845b7632f
* Version Independent ID: 0bea815f-46fc-b46f-db69-af8b45f8360d
* Content: [Reveal Highlight - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal)
* Content Source: [windows-apps-src/design/style/reveal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/reveal.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
There's an example right after those bullets:
For example, a button by itself shouldn't use reveal, but a set of buttons in a command bar should use Reveal.

**Comment by chigy** [comment]
We have other discussion around reveal document being confusing. And as I read it, I was confused...
https://github.com/microsoft/microsoft-ui-xaml/issues/995

@kikisaints
