### ISSUE TITLE
Exported transaction history report missing a column and has invalid data

### ISSUE THREAD

**Issue by kinex** [MicrosoftDocs/windows-uwp#1860]
Old report contained a column "Country / Region", but it is missing from the new report. This column is mandatory for reporting sales to tax office (for example sales in EU area must be separated from other sales).

In addition the column "taxRemitted" contains invalid data. There is just some text (e.g. "AGENT_MS_REMIT") and not the actual amount of tax as expected (and as documented).

Both of these issues are showstoppers and prevent me reporting sales to tax office as they require. I will get a penalty if I do not deliver a valid sales report by 20th August.

Could you please fix those ASAP?

**Comment by hickeys** [comment]
Country information is provided in the PartnerCountryId column for the earning partner, and the CustomerCountry column for each the customer.

Are you still seeing the invalid data in the TaxRemitted column? If so, what program(s) are you using? (i.e. are you selling an app in the Microsoft Store, a VM image on Azure, a texture pack on Minecraft, etc.?)

**Comment by kinex** [comment]
Are we talking about the same report? Here is the current list of available columns (copied from a report downloaded today):
`earningId,participantId,participantIdType,participantName,partnerCountryCode,programName,transactionId,transactionCurrency,transactionDate,transactionExchangeRate,transactionAmount,transactionAmountUSD,lever,earningRate,quantity,earningType,earningAmount,earningAmountUSD,earningDate,calculationDate,earningExchangeRate,exchangeRateDate,claimId,paymentId,paymentStatus,paymentStatusDescription,customerId,customerName,partNumber,productName,productId,parentProductId,parentProductName,productType,invoiceNumber,subscriptionId,subscriptionStartDate,subscriptionEndDate,resellerId,resellerName,distributorId,distributorName,agreementNumber,agreementStartDate,agreementEndDate,workload,transactionType,localProviderSeller,transactionCountryCode,taxRemitted,taxRemitModel,storeFee,transactionPaymentMethod,tpan,purchaseTypeCode,purchaseOrderType,purchaseOrderCoverageStartDate,purchaseOrderCoverageEndDate,externalReferenceId,externalReferenceIdLabel,licensingProgramName`

I guess you mean `partnerCountryCode`. It is my (developer) country so it is quite useless column for developers (I already know where I live). 

I have not seen a column named `CustomerCountry`.

Anyway, a couple of weeks ago a new column `transactionCountryCode` was added. It was the missing column I requested. Also the `taxRemitted` column was fixed, it contains now valid data. So those columns are now ok, thank you for fixing them.

Only remaining issue is that it is not possible to convert monetary values to my local currency (EUR in my case). Current report contains columns `transactionExchangeRate` and `earningExchangeRate` but both of them contain always the same value and it is the exchange rate from the transaction currency to USD. 

My best guess is that `earningExchangeRate` SHOULD contain the exchange rate from USD to my (developer) currency and not to always have the same value as the column `transactionExchangeRate` as it currently does. Or then one column is missing. In the old report there was this column named `FXRate`.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
