### ISSUE TITLE
Code samples should include rescap namespace.

### ISSUE THREAD

**Issue by jsuddsjr** [MicrosoftDocs/windows-uwp#1861]
Since rescap namespace is not in .appxmanifest file by default, you should mention that you will need to add it as a namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee37beb-26fc-4eca-d48e-08b4c1563b2f
* Version Independent ID: 2cf94c45-f764-78fc-f72b-ea35a09ba066
* Content: [Run in the background indefinitely - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly#feedback)
* Content Source: [windows-apps-src/launch-resume/run-in-the-background-indefinetly.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-in-the-background-indefinetly.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
