### ISSUE TITLE
API Rules are a pain, that makes it practically useless.

### ISSUE THREAD

**Issue by jignesh-fandco** [MicrosoftDocs/windows-uwp#1862]
What the point of using such api that has a funny rule "If you use the dashboard to change a submission that you originally created by using the API, you will no longer be able to change or commit that submission by using the API."

I don't understand if I want to programmatically do some changes in the pending submissions, Why I am restricted to do.  there are multiple stake holders who will do changes to submission, marketing team wants to set prices, developer team want to upload application, language team wants to set contents for each language and it takes a number of days for each of them to make corrections, before finally submit. 

This is a serious defect in your API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45cb01d3-5d6e-1817-438e-91210f4589e8
* Version Independent ID: 05bd1ace-01ff-ad8f-a07a-fa841650c2df
* Content: [Manage package flight submissions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-flight-submissions#feedback)
* Content Source: [windows-apps-src/monetize/manage-flight-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/manage-flight-submissions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
