### ISSUE TITLE
RemoteCameraPairingHelper sample throws exception when new camera is plugged in

### ISSUE THREAD

**Issue by AdamSzofran** [MicrosoftDocs/windows-uwp#1863]
The `RemoteCameraPairingHelper` class in the sample code on [this page](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/connect-to-remote-cameras#remote-camera-pairing-helper-class) throws an unhandled exception when a new camera device is plugged in after the initial enumeration is complete.

The exception is thrown in the call to `MediaFrameSourceGroup.FromIdAsync()`. The exception is `The system cannot find the file specified. (Exception from HRESULT: 0x80070002)`.

This appears to be due to a race condition. If I set a breakpoint on the `FromIdAsync()` call and then step over it the call succeeds. In fact, if I do something gross like let the first call fail but catch the exception and then try the call again it succeeds on the second call.

It seems like you can't call `MediaFrameSourceGroup.FromIdAsync()` too soon after the `DeviceWatcher` raises the `Added` event (after the initial enumeration is complete) or you'll hit this apparent race condition.

I'm running Windows 10 Pro 1903 build 18362.295 and compiling a test UWP app in C# with Visual Studio 2017 build 15.9.15 and targeting Windows SDK 18382.

(Edit: I also filed a bug against the relevant Windows Universal sample [here](https://github.com/microsoft/Windows-universal-samples/issues/1131).)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0acb2900-f433-7899-c86a-a2cd8aba2143
* Version Independent ID: 55138f0b-e0a4-a4aa-437e-f693b2e70e3b
* Content: [Connect to remote cameras - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/connect-to-remote-cameras#remote-camera-pairing-helper-class)
* Content Source: [windows-apps-src/audio-video-camera/connect-to-remote-cameras.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/connect-to-remote-cameras.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. This was a known bug and the feature team has implemented a solution in newer OS versions. For earlier versions, the recommended workaround is retrying:

```
private async Task AddDeviceAsync(string id)
{
    for(int i = 0; i < 5; i++)
    {
        try
        {
            var group = await MediaFrameSourceGroup.FromIdAsync(id);
        }
        catch(Exception ex) when (ex.HResult == 0x80070002)
        {
            Thread.Sleep(20000);
        }
    }
    if (group != null)
    {
        await _dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
        {
            _remoteCameraCollection.Add(group);
        });
    }
}
```
