### ISSUE TITLE
New types of Visuals are not described here

### ISSUE THREAD

**Issue by vturov** [MicrosoftDocs/windows-uwp#1864]
I guess we need some info on new types of visuals: LayerVisual, RedirectVisual, ShapeVisual.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11c9da9-8225-47d8-f992-d4fc9bce807e
* Version Independent ID: 615e410c-1635-cd98-c078-1a1424956c93
* Content: [Composition visual - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/composition-visual-tree)
* Content Source: [windows-apps-src/composition/composition-visual-tree.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/composition-visual-tree.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Links to new visual types have been added.
