### ISSUE TITLE
Add reference to the Include prerelease in "Call UWP APIs in desktop apps"

### ISSUE THREAD

**Issue by crramirez** [MicrosoftDocs/windows-uwp#1865]
[Enter feedback here]

Here:

In the NuGet Package Manager window, select the Browse tab and search for Microsoft.Windows.SDK.Contracts.

Please add: Be sure that **Include prerelease** check is enabled.

I had many problems because I didn't realize it and I finished installing them manually

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Use UWP APIs in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting this great feedback. I'll clarify this in the article as soon as I can and update this issue when that is done.

**Comment by crramirez** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/8397379/63431874-2decc500-c420-11e9-824b-85e8fcdde477.png)

Thanks a lot
