### ISSUE TITLE
Typo on Process Media Frames with MediaFrameReader page

### ISSUE THREAD

**Issue by AdamSzofran** [MicrosoftDocs/windows-uwp#1868]
There is a typo on this page:
https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-media-frames-with-mediaframereader#initialize-the-mediacapture-object-to-use-the-selected-frame-source-group

> Next, create a **MediaCaptureSettings** object that will be used to initialize the MediaCapture object.

Instead of **MediaCaptureSettings** it should be **MediaCaptureInitializationSettings**. That word is a hyperlink so the link will need to be fixed too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db4165a7-748e-e566-3b38-21ad71a76489
* Version Independent ID: d8762b7e-22b0-cfd6-25b0-5e2a68cdea9f
* Content: [Process media frames with MediaFrameReader - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-media-frames-with-mediaframereader)
* Content Source: [windows-apps-src/audio-video-camera/process-media-frames-with-mediaframereader.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/process-media-frames-with-mediaframereader.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This typo has been fixed. Thank you for reporting this issue.
