### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by roghib** [MicrosoftDocs/windows-uwp#1869]
Not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@roghib Can you please elaborate? Was the article giving you a 404 error? I'm able to reach it.
