### ISSUE TITLE
Where can you find the default styles to edit a copy from?

### ISSUE THREAD

**Issue by pdecostervgls** [MicrosoftDocs/windows-uwp#1872]
Since the XAML designer has been reworked in Visual Studio and Blend, it is not possible to "edit a copy" of a controls style through the UI anymore. How/where can this information been found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71085aa7-f688-0f7f-af84-431742ca7a2a
* Version Independent ID: 181f13bd-fb4e-3e43-398d-8a2f6e981035
* Content: [XAML styles - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-styles#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/xaml-styles.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/xaml-styles.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Edit a copy should work in VS, if it doesn't that is a regression. Please file a bug in VS using the "send feedback" button in the upper right of the VS window.

![image](https://user-images.githubusercontent.com/20667023/63453171-e6087680-c3fc-11e9-8fc6-b6f2859cbe95.png)
