### ISSUE TITLE
FileTypeFilter unclear

### ISSUE THREAD

**Issue by BoomRaccoon** [MicrosoftDocs/windows-uwp#1873]
Looking at the documentation the Properties look optional, which is true for Location and ViewMode, but trying to omit the FileTypeFilter leads to an error.
So either state that it is a property you are required to set or fix the implementation.
A tip on how to show All Files/no filter would be really helpful. Figured it out myself after quite some search
FilePicker.FileTypeFilter.Add("*");

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f98368cc-a7d2-6770-7c8f-3cb2f500676f
* Version Independent ID: 88e3393d-38a9-5737-89e2-85543d52dbfa
* Content: [Öffnen von Dateien und Ordnern mit einer Auswahl - Windows UWP applications](https://docs.microsoft.com/de-de/windows/uwp/files/quickstart-using-file-and-folder-pickers)
* Content Source: [windows-apps-src/files/quickstart-using-file-and-folder-pickers.md](https://github.com/MicrosoftDocs/windows-uwp.de-de/blob/live/windows-apps-src/files/quickstart-using-file-and-folder-pickers.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
