### ISSUE TITLE
Duplicate link to PointerWheelChanged

### ISSUE THREAD

**Issue by sam9116** [MicrosoftDocs/windows-uwp#1874]
slightly confusing to read

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbac8a8-2d6a-7d77-9fef-5b37fa68a70f
* Version Independent ID: b260cd4c-ef7a-3e56-31ec-1a9705525c08
* Content: [Mouse interactions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/mouse-interactions#feedback)
* Content Source: [windows-apps-src/design/input/mouse-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/mouse-interactions.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@sam9116  - thanks for pointing this out. Dup has been deleted.
