### ISSUE TITLE
Custom cursors docs are missing

### ISSUE THREAD

**Issue by adrientetar** [MicrosoftDocs/windows-uwp#1876]
What's missing:
- Guidance on how to create custom cursors (there is a blog post that explains how to use C++ dll resource file to do it [here](https://blogs.msdn.microsoft.com/devfish/2012/08/01/customcursors-in-windows-8-csharp-metro-applications/))
- Recommendations for what size bitmaps should be provided in a custom cursor

cc @michael-hawker
cc microsoft/microsoft-ui-xaml#506

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbac8a8-2d6a-7d77-9fef-5b37fa68a70f
* Version Independent ID: b260cd4c-ef7a-3e56-31ec-1a9705525c08
* Content: [Mouse interactions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/mouse-interactions#feedback)
* Content Source: [windows-apps-src/design/input/mouse-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/mouse-interactions.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by michael-hawker** [comment]
+1 That blog post was the only reference I found earlier when I was looking at this as well.

**Comment by adrientetar** [comment]
Some feedback about the article itself:
- The "grasping hand cursors" that are mentioned don't exist in UWP (aka [CoreCursorType](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corecursortype) enum). [They're also absent [from win32](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setsystemcursor), not sure where this is coming from.]
- Unfinished sentence:  
  > Samples: See our BasicInput sample, for .
- > Specify a cursor image through the PointerCursor function.  
  
  _function_ should be _property_
- nit: the cursor screenshots seem to be from Vista/7, which UWP does not support

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the suggestion @adrientetar. I've created in internal work item to track this.

**Comment by michael-hawker** [comment]
@Karl-Bridge-Microsoft can these internal work items be synced to the GitHub issues? It's a little confusing when these issues get closed when the docs aren't updated yet. Plus it makes it harder for folks to find this issue if they're looking at the open issues against this documentation (it's already been made hard enough now that they're not automatically bubbled to the pages anymore).

**Comment by Karl-Bridge-Microsoft** [comment]
@michael-hawker - I included a note to update this issue when the work item is completed and closed.
