### ISSUE TITLE
Windows.ApplicationModel.AppService.AppServiceConnection incorrectly listed as supported only in packaged apps

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/windows-uwp#1877]
https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appservice.appserviceconnection has the DualApiPartitionAttribute, so according to the "APIs supported in both packaged apps and desktop applications" section it shouldn't be listed in the first list, right? I haven't tested this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909f1773-1e55-eb5a-206f-b32ce6f9dd9d
* Version Independent ID: 24ea5c87-1c21-884d-f05f-833bbd894ba9
* Content: [UWP APIs available to a packaged desktop app (Desktop Bridge) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for the feedback. The AppServiceConnection class has been removed from that list in the article.
