### ISSUE TITLE
There is no explanation of how to make a custom time picker like the one used in the timer selector of Windows Alarms&Clock 

### ISSUE THREAD

**Issue by MarcAnt01** [MicrosoftDocs/windows-uwp#1881]
There is no other choice rather than writing one from scratch, being a beginner I'd rather have at least some examples on how to make one
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d61d8e1-c0c9-e605-8ddd-714ffa400204
* Version Independent ID: 6d753cc1-93a9-adf4-00bf-1b967df8b7c8
* Content: [Time picker - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/time-picker#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/time-picker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/time-picker.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by kikisaints** [comment]
@MarcAnt01 As you've stated in the title, this control is custom and therefore there is no standard way to document it.

I would suggest that you file an issue here: https://github.com/microsoft/windows-universal-samples

Where they might be able to make a sample that you can use in your app.
