### ISSUE TITLE
Add Option to disable Xinput control on UWP Apps

### ISSUE THREAD

**Issue by joaodforce** [MicrosoftDocs/windows-uwp#1882]
There are many applications that allow users to control their computer using their Xbox Controller, Like Gopher or Joy2Key, binging controller buttons to keyboard and mouse gestures.

Later Windows 10 builds added support for controlling UWP Apps using Xinput, and this conflicts with such functionality, there should be an option on windows to disable such controls, that or maybe proper System control using xinput, because allowing control only partially on the system is not useful at all.

As seen on many threads before this breaks many system control functionality.

https://steamcommunity.com/app/367670/discussions/0/2828702373004583436/?ctp=3

https://github.com/MicrosoftDocs/windows-uwp/issues/622

https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-completely-disable-xbox-controller/b4f63e59-f1a1-4b75-9525-c39c94468a66?auth=1

https://superuser.com/questions/1173133/disable-xbox-one-controller-in-uwp-apps-like-windows-store

**Comment by JoshWobbles** [comment]
I cannot stress this enough, It's a nice OPTION to have for some users, but in other cases it completely breaks system usability.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the suggestion! This is a product suggestion and not a doc bug, so please consider posting the issue at https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose for the product team to track publically.

**Comment by JoshWobbles** [comment]
@Karl-Bridge-Microsoft  Except this needs to be an option FOR THE USER, not the developer!!! Not every person who uses a Microsoft PC is using it to play games.

**Comment by joaodforce** [comment]
> @Karl-Bridge-Microsoft Except this needs to be an option FOR THE USER, not the developer!!! Not every person who uses a Microsoft PC is using it to play games.

I think you did not understand what @Karl-Bridge-Microsoft meant.

He just said that this issue should be posted on https://github.com/microsoft/microsoft-ui-xaml

Because this is not a problem related to the documentation not listing this feature, its a matter of this feature not existing at all. So it should be placed on the microsoft-ui-xaml repository where this feature could actually be developed for future Windows Versions.

**Comment by JoshWobbles** [comment]
> > @Karl-Bridge-Microsoft Except this needs to be an option FOR THE USER, not the developer!!! Not every person who uses a Microsoft PC is using it to play games.
> 
> I think you did not understand what @Karl-Bridge-Microsoft meant.
> 
> He just said that this issue should be posted on https://github.com/microsoft/microsoft-ui-xaml
> 
> Because this is not a problem related to the documentation not listing this feature, its a matter of this feature not existing at all. So it should be placed on the microsoft-ui-xaml repository where this feature could actually be developed for future Windows Versions.

I got that, but that isnt any better of a place than here because that is for the developer libraries, this really needs to be an end user opt in "feature", and not something that should the responsibility of every UWP developer to make sure they add the correct meta to their app to disable controller input.

**Comment by Karl-Bridge-Microsoft** [comment]
@JoshWobbles - user settings provide a way for Windows feature teams to expose options for their features to users. If you want a user setting for a Windows feature, you have to address it with the feature developers. This is why I provided a link to a more appropriate product feedback forum.

**Comment by james28909** [comment]
Sorry for the double post. A developer in know that manages multiple other controller/device input projects has taken their time to help me figure out how to disable this for DS4 v1 controllers (ds4 v2 controllers, that have the light bar in the touch pad, don't have the issue of ui navigation input).

The developer that figured it out Is located here - https://steamcommunity.com/id/FirstPlato/ and here - https://forzatools.weebly.com/about.html

the developer is very knowledgeable and manages multiple projects regarding controller/device input and feedback. It is working great for me and works fine and doesn't require you to run a fix every time you reboot. It is a simple reg edit. And I REPEAT IT IS FOR DS4 v1 only (ds4 v2 doesn't have this issue).

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005]
"Disabled"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\Gamepad]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\Gamepad\UINavigation]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\Gamepad\UINavigation\PrimaryUp]
"AxisIndex"=dword:00000012
"Inverted"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\UINavigation]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\UINavigation\PrimaryUp]
"AxisIndex"=dword:00000012
"Inverted"=dword:00000001
```

just copy paste the code into a .reg file named whatever you want, like "ds4_ui_fix.reg" and run it. Then unpair and reboot and pair and try it out.
