### ISSUE TITLE
Mysterious error when trying to create a WinRT project

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/windows-uwp#1885]
Tried to follow the instructions, but got an error when creating the project about trying to invoke a universal template something... (sorry, forgot to take a screen shot).

On a hunch, I looked in the VS installer, and it turns out I didn't have the UWP workload installed, just desktop C++. This caveat might be mentioned in the docs and/or the extension itself.  Worked fine once I installed that.

VS2019 Community 16.2.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Good idea, I updated this section: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package, and then I linked to that from the topic in question.

Those changes are live now.

~Steve
