### ISSUE TITLE
Lots of failures using the Submission API C# sample code submitting apps

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windows-uwp#1887]
I've been using the C# sample code provided on this page to submit apps to the Store. Lately, however, it's been failing a lot with the following. To be clear I've been using this code for months, and have only seen the failures in the last few weeks.

> System.Exception: {"code":"InvalidParameterValue","data":[],"details":[],"message":"Please keep all file entries for existing packages. 
If you wish to remove a package, mark it as PendingDelete. The following packages are missing in your update: 2000000000030494274","source":"Ingestion Api","target":"packages"}

and/or

> System.Exception: 
{"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: 
"},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ac48f9-fd0e-0f1e-fc75-f28cf0b83f57
* Version Independent ID: 9bfcea4f-a9cb-ab64-df07-90512002d80b
* Content: [C# sample - submissions for apps, add-ons, and flights - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/csharp-code-examples-for-the-windows-store-submission-api#feedback)
* Content Source: [windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by myokeeh** [comment]
@hickeys, at this point, I'm convinced something on the server side has changed. It doesn't appear to acknowledge "PendingDelete"

**Comment by hatasum** [comment]
I also have been using the C# sample code to submissions app.
At "Create a new submission" step, the server return the following:
{"code":"InvalidParameterValue","data":[],"details":[],"message":"The size of Listings must be 1 or more","source":"Ingestion Api","target":"listings"}

**Comment by hatasum** [comment]
Does anyone have the same issue? Thanks.

**Comment by hatasum** [comment]
Is the server blocked now?

**Comment by myokeeh** [comment]
I've since resolved the "Please keep all file entries for existing packages." It's due to having more than one package in the submission and the other ones not being marked "PendingDelete" by the sample code.

The server errors seem to still be a problem once in a while. I've since added retry code to account for server errors that may stall submissions.
