### ISSUE TITLE
Examples given DO NOT PASS store certification

### ISSUE THREAD

**Issue by rashid241247** [MicrosoftDocs/windows-uwp#1888]
The use of OpenCV.Win.Core and OpenCV.Win.ImgProc should carry a big warning; as these libraries DO NOT PASS the windows store certification tests. 
Microsoft should ensure that the examples outlined in thir documents actually work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7bdbdb-5662-4757-438b-efeabfa94d12
* Version Independent ID: 0718d58a-20d7-ffff-9863-fdf42b044e77
* Content: [Process bitmaps with OpenCV - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-software-bitmaps-with-opencv)
* Content Source: [windows-apps-src/audio-video-camera/process-software-bitmaps-with-opencv.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/process-software-bitmaps-with-opencv.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The two articles that talk about OpenCV have been updated with notes that these packages do not pass Store compliance and are therefore only intended for experimentation. Thank you for bringing this issue to our attention.
