### ISSUE TITLE
Resource Installation

### ISSUE THREAD

**Issue by rmill777** [MicrosoftDocs/windows-uwp#1890]
Took me 2 days to figure out you have to follow "Getting started with the Windows UI Library" to install Microsoft.UI.Xaml using NuGet... There should definitely at least be a warning at the top of the page. Although, I am not sure why treeview is not included in the default XAML controls. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245536a-3179-ff1e-dfd5-76898d07381b
* Version Independent ID: 145609fa-8e77-5878-3402-7bcc69df8ccc
* Content: [Tree view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
TreeView is in the platform SDK as of 1803 but we are doing all new development in WinUI and won't be investing in the platform versions going forward so the sooner you can migrate to WinUI the happier you should be. Please let us know if you run into any other problems using the library.
