### ISSUE TITLE
C# WRC docs need updating

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#1891]
This page opens up with "Starting with the .NET Framework 4.5" and continues to talk about framework. What does framework have to do with WinRT? This article is surely written incorrectly? UWP does not use .net Framework, it uses .net core assemblies. And why no mention of .net standard which I think is best for a library/component? Is this documentation just not right or outdated?

If this page is right .. why would you make WRC construction require Framework? When UWP has moved onto .net core and .net standard? I really don't get it. Further down the page .. ".NET Framework functionality that's allowed in a UWP app" - there is no .net framework in UWP! 

The last thing i expected to see on this page was .net framework.

I don't understand looking at this page what I'm meant to do, I haven't used framework for years. I consider it legacy now. Can't i write C# runtime components in UWP (.netcore) or .net standard? Windows Runtime Components are a UWP technology. This is all really confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38866694-667e-1774-623e-39d8c7341dd7
* Version Independent ID: bc65b6f7-0eb4-0108-d3e8-940bac513543
* Content: [Creating Windows Runtime Components in C# and Visual Basic - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic#feedback)
* Content Source: [windows-apps-src/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Gavin-Williams, the topic was indeed out of date. I've fixed it, and made a set of other changes/improvements. I'll go ahead and close the issue now that the fixes are published. ~Steve
