### ISSUE TITLE
no VideoDeviceId property found on DeviceInformation class

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#1893]
This page is misleading there is no **VideoDeviceId** property to be found on **DeviceInformation** class so we dont know how do we determine our camera barcode scanner device from the collection, and even if we somehow determine that, how do we convert the DeviceInformation object into a **BarcodeScanner** object? because remaining docs use barcode scanner methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72178625-3c29-9fa2-b23c-3cb3402d95cc
* Version Independent ID: 55d709c4-13b4-db4f-ecbb-e7f4562051ba
* Content: [Getting Started with Camera Barcode Scanner - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-camerabarcode-get-started#feedback)
* Content Source: [windows-apps-src/devices-sensors/pos-camerabarcode-get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/pos-camerabarcode-get-started.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @touseefbsb. Thanks for the feedback. I've added a few more code snippets and a link to the official Barcode sample to the topic.
