### ISSUE TITLE
Tables columns not shown on table

### ISSUE THREAD

**Issue by David-Tennant** [MicrosoftDocs/windows-uwp#1894]
The text implies that the table below will have the following columns, `Payout and Paypal` but doesn't.
![Screen Shot 2019-09-03 at 15 15 42](https://user-images.githubusercontent.com/40059359/64176566-fe957980-ce5d-11e9-80f2-f89f73b76666.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9d4d96-2865-5f2d-8737-66fe44db7cce
* Version Independent ID: 239560a3-7506-bb73-b436-6eec162e5196
* Content: [Account types, locations, and fees - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/account-types-locations-and-fees#feedback)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
great catch, thank you. The information was moved to another page a few months ago, and I apparently missed this page. I've updated this page to no longer reference these columns. The information you're looking for can be found on this page.

https://docs.microsoft.com/en-gb/windows/uwp/publish/payment-thresholds-methods-and-timeframes
