### ISSUE TITLE
Unprintable character in Package.appxmanifest sample

### ISSUE THREAD

**Issue by kk-code-lab** [MicrosoftDocs/windows-uwp#1895]
`&lt;rescap:Capability Name="extendedExecutionUnconstrained"/&gt;`  line has extra unprintable character at the end. If you copy and paste whole line into the appxmanifest file you will get cryptic compilation error until this character is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee37beb-26fc-4eca-d48e-08b4c1563b2f
* Version Independent ID: 2cf94c45-f764-78fc-f72b-ea35a09ba066
* Content: [Run in the background indefinitely - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly#feedback)
* Content Source: [windows-apps-src/launch-resume/run-in-the-background-indefinetly.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-in-the-background-indefinetly.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for your feedback. Could you provide the error you were seeing? I can remove the white space from the end of the lines in that example, but seeing the actual error would help me pinpoint the issue.

**Comment by kk-code-lab** [comment]
If you copy-paste this line then this error appears:

![Annotation 2019-09-03 205339](https://user-images.githubusercontent.com/9204950/64200704-58f9fe80-ce8d-11e9-9a37-4c0c400d0f3e.png)

I re-tested it and i think there are more of these characters before first < sign:

![Annotation 2019-09-03 205801](https://user-images.githubusercontent.com/9204950/64200849-9e1e3080-ce8d-11e9-9908-dbd33bd980f4.png)

3x "e2 80 af" after first 20 20 are unprintable and causes this error i think.

**Comment by knicholasa** [comment]
Okay, thanks for providing that information. I'll follow up with my team and update the docs as necessary.

**Comment by AtosNicoS** [comment]
This issue drove me crazy! Please fix it!
