### ISSUE TITLE
Links go to .NET instead of UWP

### ISSUE THREAD

**Issue by guybark** [MicrosoftDocs/windows-uwp#1897]
Some of the links on this page, (eg the ones relating to AccessKeys,) go to .NET documentation rather than UWP documentation. Shouldn't all the links go to UWP documentation given that this content relates to UWP design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23a4e47-e29c-2851-b349-06745ec240a3
* Version Independent ID: 737958ac-bf24-3e7b-0e91-f41b6626ab74
* Content: [Keyboard accessibility - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/keyboard-accessibility#feedback)
* Content Source: [windows-apps-src/design/accessibility/keyboard-accessibility.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/keyboard-accessibility.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@guybark - thanks Guy. I've revised topics.
