### ISSUE TITLE
coreTitleBar.Height = 0

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/windows-uwp#1903]
You cannot do "AppTitleBar.Height = coreTitleBar.Height;" in MainPage constructor. It always returns 0 because the title bar is hidden
You have to set it in LayoutMetricsChanged to get the right values if TitleBar Height and Left/RightInset

Please fix it to not make developers confused and cost time to debug!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c220453a-d6f1-4e9f-4f2d-9dd366f91d31
* Version Independent ID: 16284cd7-f1b5-f43f-c7ec-7ffa1f4ef3f2
* Content: [Title bar customization - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#feedback)
* Content Source: [windows-apps-src/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/title-bar.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
The full sample has the correct code, the "simplified" sample seems to have been over-simplified.

**Comment by jwmsft** [comment]
@linhnddev, thanks for pointing this out. The code sample has been corrected.
