### ISSUE TITLE
Edit Tax Profile Page (This Page is not working)

### ISSUE THREAD

**Issue by infoviewmo** [MicrosoftDocs/windows-uwp#1904]
Hello, Payout and Tax Setup indicates Partner Action is required (Edit) Tax Profile. When clicking on the link to do so receive "This Page is not working". Appreciate assistance. URL received is as follows"https://payeeportal.trafficmanager.net/bEU19SPXZDdm81nSKW6tjOOgT=.=T9viYRGLLXVFkIT=.=TSU1M=/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [Set up your payout account and tax forms - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on [our support forum](https://developer.microsoft.com/en-us/windows/support). If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
