### ISSUE TITLE
UWP Platform link is not clear enough.

### ISSUE THREAD

**Issue by hanrai** [MicrosoftDocs/windows-uwp#1909]
When I clicked UWP Platform link. I was expecting a description for UWP Platform, not for UWP App. They are two different thing.

I think windows/apps/desktop/choose-your-platform should be a good target to link. That is what I really want to know when I clicked the "UWP Platform" link.

I used Qt to develop programs for a long time. I have little knowledge about new windows platforms(Windows 7 or later). Before I read "choose-your-platform", I just know that UWP can develop apps for all devices. And I don't know the difference between .Net, WinRT, WPF UWP clearly. I thought C++ language projection is the good way to access .NET.

When I want to develop a UWP app, google bring me here. I can't figure out what UWP is, and the questions above can't be clarified. Then I start to make mistakes.

If I saw the "choose-your-platform" document before I start my project, all those mistake will not happen. That document will save me a lot of time and effort.

So, my suggection is, when we talk about UWP Platform, we link it to "choose-your-platform"; when we talk about UWP Apps, we link it to "universal-application-platform-guide". That will help developers to clarify the questions I met before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 833143df-a76a-b714-956b-dab2be749ffa
* Version Independent ID: 39ca0eed-5f1d-1870-59cf-0460d40e8f7a
* Content: [Create apps with the Universal Windows Platform - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-uwp-apps#feedback)
* Content Source: [windows-apps-src/get-started/create-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-uwp-apps.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by hanrai** [comment]
I open a new issue, not a pull request, because I think this is a big decetion. It will affect all UWP releated documents. According to the Microsoft Docs contributor guide, I should open an issue to talk with team first.

And I choose "choose-your-platform", not wiki style UWP description nor UWP App, because this document will lead developer to a right way to develop a UWP app. Developers will understand the various concepts clearly before they initiate a new project. So they won't mess with a lot of things like me.

I don't think UWP App is the right document to link, because when I want to know a platform, I want to stand higher than app, so that I will know if I'm doing the right things.

I think it is very important to figure out concepts in different platforms clearly before, not after, they initiate a new project. "UWP Platform" link is a good place to do this job. Give developer a clear viewpoint of knowledge about UWP Platform and difference between other platforms(include difference between tools and languages they used, what they can do, and what they should do, and what you should expected from a platform, etc.) will be great helpful.

**Comment by QuinnRadich** [comment]
We're already aware of many of these concerns you raise, and have been assessing how to provide the best entry experience for new and existing developers into all of our Windows app development.

That being said, we expect that users in our UWP documentation are interested in developing UWP apps. The Choose Your Platform page, while useful, also has a great deal of information on other app types which isn't suited for this area.

I agree that adding a link to the page on the UWP Get Started landing page is a good idea, however. Closing this issue, and going forward with that suggested change. Thank you.
