### ISSUE TITLE
When title bar customization that how to settings title text ?

### ISSUE THREAD

**Issue by ProJend** [MicrosoftDocs/windows-uwp#1910]
like to Microsoft Store UWP.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c220453a-d6f1-4e9f-4f2d-9dd366f91d31
* Version Independent ID: 16284cd7-f1b5-f43f-c7ec-7ffa1f4ef3f2
* Content: [Title bar customization - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/design/shell/title-bar)
* Content Source: [windows-apps-src/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/title-bar.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
I'm sorry, I don't understand the question. Can you please provide more details?

**Comment by ProJend** [comment]
![image](https://user-images.githubusercontent.com/55018532/64845217-2776f500-d63c-11e9-9cd2-136e46148ccf.png)
Hey! I made a new UWP, but I don't know how to plus the title header. Check the picture. how to do to make the effect look like Microsoft Store.

**Comment by ProJend** [comment]
> 对不起，我不明白这个问题。您能提供更多详情吗？

![image](https://user-images.githubusercontent.com/55018532/64846307-f0eea980-d63e-11e9-87cf-1c731c220832.png)
![image](https://user-images.githubusercontent.com/55018532/64846474-4f1b8c80-d63f-11e9-994e-25c4b6377007.png)

Hey! I made a new UWP, but I don't know how to plus the title header "True". Check the picture. How to do to make the effect look like Microsoft Store?

**Comment by ProJend** [comment]
> I'm sorry, I don't understand the question. Can you please provide more details?
Hey! I made a new UWP, but I don't know how to plus the title header "True". Check the picture. How to do to make the effect look like Microsoft Store?

![image](https://user-images.githubusercontent.com/55018532/64846665-c51ff380-d63f-11e9-95ea-654b389dba14.png)
![image](https://user-images.githubusercontent.com/55018532/64846660-bf2a1280-d63f-11e9-9ae0-a4ea74837bdf.png)

**Comment by jevansaks** [comment]
Did you try cloning the repo for the sample referenced by the article and looking to see what it's doing that you're not? Looks like you aren't setting the titlebar element to a XAML element.

**Comment by ProJend** [comment]
Yes! I am looking for this. How to make the titlebar?

**Comment by ProJend** [comment]
> Did you try cloning the repo for the sample referenced by the article and looking to see what it's doing that you're not? Looks like you aren't setting the titlebar element to a XAML element.
Yes! I am looking for this. How to make the titlebar?

**Comment by jevansaks** [comment]
Look at the docs?

https://docs.microsoft.com/en-gb/windows/uwp/design/shell/title-bar#full-customization-example

**Comment by HppZ** [comment]
set ApplicationView.GetForCurrentView().Title does not work when titlebar is customized.
