### ISSUE TITLE
Promo code for subscription

### ISSUE THREAD

**Issue by lostmsu** [MicrosoftDocs/windows-uwp#1911]
Can I create a promo code for a subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd51f81-44ab-9838-a22c-d044107ee279
* Version Independent ID: 44d59c98-b60e-c5ac-0718-ac19f829d566
* Content: [Generate promotional codes - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/generate-promotional-codes)
* Content Source: [windows-apps-src/publish/generate-promotional-codes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/generate-promotional-codes.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
As stated in the article, "You can generate promotional codes for any app or add-on (with the exception of subscription add-ons) "
