### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by andrewbettany** [MicrosoftDocs/windows-uwp#1912]
Here are some examples of how to deploy from the command-line using the sytax for WinAppDeployCmd.exe.

This should read:

Here are some examples of how to deploy from the command-line using the syntax for WinAppDeployCmd.exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 551b46e5-5098-ae96-de48-dee2aeca2b8b
* Version Independent ID: fe46b952-d438-94b1-4a60-a00013f539d6
* Content: [Install apps with the WinAppDeployCmd.exe tool - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/install-universal-windows-apps-with-the-winappdeploycmd-tool#feedback)
* Content Source: [windows-apps-src/packaging/install-universal-windows-apps-with-the-winappdeploycmd-tool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/install-universal-windows-apps-with-the-winappdeploycmd-tool.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this typo! It has been fixed.
