### ISSUE TITLE
Could not download pdf of just this section

### ISSUE THREAD

**Issue by timwright314159** [MicrosoftDocs/windows-uwp#1914]
I clicked Download PDF and it downloaded all 8K pages! I just wanted a PDF of this UWP section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcd2e7e-612d-29de-6b94-3bed0b772b16
* Version Independent ID: cf067679-95df-f7d2-17ec-d15cc18c0b4b
* Content: [What's a Universal Windows Platform (UWP) app? - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This is standard behavior for the "Download PDF" feature on docs.microsoft.com. Apologies for the inconvenience, but it's not something we can fix.
