### ISSUE TITLE
Can't find template

### ISSUE THREAD

**Issue by itskdog** [MicrosoftDocs/windows-uwp#1915]
I have JavaScript (Node.JS) and UWP installed in VS2019 as requested by this article, but it still isn't showing in the templates list.

How do I enable this to show up? As it appears impossible to make an app that hooks into Google's APIs with C# or VB, I need JS support to create my app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b996558c-4643-b37a-5afb-9cd14369b8bf
* Version Independent ID: de5b8514-6616-11ee-7725-c9456bbd8689
* Content: [Create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-js-uwp#feedback)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-js-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-js-uwp.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for the heads-up.

This page was mistakenly updated to refer to Visual Studio 2019 along with many similar docs pages. However, as you discovered, Visual Studio 2019 does not support Javascript UWP app development. You need to use Visual Studio 2017 instead.

I'm making updates to the page, which should be visible before long.
