### ISSUE TITLE
Add CompactOverlayButton icon, also known as picture in picture, plz

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#1917]
Add CompactOverlayButton icon, also known as picture in picture, plz.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by hupo376787** [comment]
But this icon exist in system app "Movies and TVs", but that icon can't fully express the meaning of "picture in picture".

**Comment by hupo376787** [comment]
It seems that MS has add picture-in-picture mode into Calculator, that icon looks good. So will you add to segoe font?

**Comment by MuleaneEve** [comment]
I don't know why this issue was closed, but I also need this icon. I really wish it was part of the Segoe MDL2 icons.

Here are two possible workarounds: (Compose it with two icons or import the "SegMVR2.ttf" font)
https://stackoverflow.com/questions/45692232/w10-uwp-compactoverlay-button-icon

**Comment by hupo376787** [comment]
Yeah, I closed it manually, cause MS doesn't care it at all. SoI took the icon from new `Calculator` app source code, and made a special font just for my app.
