### ISSUE TITLE
Add SkipForward10 icon plz

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#1920]
SkipForward30 exists, but no SkipForward10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
Is this a missing codepoint in the font or one that exists but is undocumented?

**Comment by chigy** [comment]
Checking with icon contact.

**Comment by hupo376787** [comment]
`SkipForward10` icon is a missing one.

**Comment by v-nihar** [comment]
Thank you for your feedback. Icons are added to Segoe MDL2 based on internal business needs. Currently our product teams do not have an need for this.”
