### ISSUE TITLE
What is EF in example and where take it?

### ISSUE THREAD

**Issue by fembiba** [MicrosoftDocs/windows-uwp#1921]
What is EF in example and where take it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16fffc35-1544-c8dc-2f78-47944c6a0ac5
* Version Independent ID: 9e5fbdc9-cbee-5a34-6820-e5e075a65e99
* Content: [Pointer-based animations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/pointer-input-animations#feedback)
* Content Source: [windows-apps-src/composition/pointer-input-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/pointer-input-animations.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by embender** [comment]
EF stands for EffectFactory which sets up the acrylic brush in this sample I believe. More can be found here:
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition.CompositionEffectFactory
