### ISSUE TITLE
Aspect ratios incorrectly documented

### ISSUE THREAD

**Issue by SvenEV** [MicrosoftDocs/windows-uwp#1925]
I think the aspect ratios for the different thumbnail modes are incorrectly described on this page (at least in the case of picture files).

According to section "Recommended thumbnail modes and their features":
PicturesView: Uniform / SingleItem: Uniform

According to the examples:
PicturesView: Original / SingleItem: Original

Actual behavior:
PicturesView: Uniform / SingleItem: Original

The actual behavior is correctly documented in the API reference, though ("ThumbnailMode Enum").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdd46748-ab87-89ce-8038-bef45e951e16
* Version Independent ID: 63e7b2c9-7302-458c-a2bf-d1bf921ac487
* Content: [Guidelines for thumbnail images in UWP apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/thumbnails#feedback)
* Content Source: [windows-apps-src/files/thumbnails.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/thumbnails.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by GrantMeStrength** [comment]
Thank you. Finally got around to correcting this!
