### ISSUE TITLE
There is a small typo in this page  (Destkop instead of Desktop) in the links page

### ISSUE THREAD

**Issue by arulfrances** [MicrosoftDocs/windows-uwp#1926]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/7755566/64934254-24138180-d867-11e9-877d-73ba827a139f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491f5924-85ab-65ae-ab10-3bb691d38eba
* Version Independent ID: 19bba932-fb1f-1db1-d457-73719340b504
* Content: [Toast notifications from desktop apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-desktop-apps#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-desktop-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-desktop-apps.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
I sent out a PR to fix this.
