### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by petrspelos** [MicrosoftDocs/windows-uwp#1931]
Lol you put XAML comments into your C# code. git gud scrub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69449df-a1ec-70dd-e563-0ad508733c47
* Version Independent ID: dc0e0acb-d92a-a039-5c16-f54a4b71d954
* Content: [Navigation view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by petrspelos** [comment]
I was joking, didn't expect it to open an issue on GitHub. 😊

**Comment by jwmsft** [comment]
It's a valid issue, thanks for pointing it out. The comments are fixed.
