### ISSUE TITLE
Please state that custom capability must be declared before all others

### ISSUE THREAD

**Issue by oduis** [MicrosoftDocs/windows-uwp#1932]
Since there are no working samples it took me a long time to find out that the custom capability must be declared BEFORE the DeviceCapabilities. Otherwise there is an XML structure error message during compilation.
This important info is missing on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#feedback)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. I added notes to each of the capability sections on this page to clarify any required ordering of the elements based on the schema requirements, and these changes are now live. If you you have any further feedback on this article, please feel free to reopen this issue.

**Comment by oduis** [comment]
That was quick! Thanks for handling this so fast.
