### ISSUE TITLE
Unclear if grey +Z axis lines are pointing into or out of the page

### ISSUE THREAD

**Issue by davidljung** [MicrosoftDocs/windows-uwp#1940]
The diagrams above (on this page) show a grey +Z axis arrow - but since the screen is 2D is isn't clear if the arrow is meant to indicate the axis is pointing out of the device screen or 'into' it.  Please annotate the image or note it in the text.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b263c037-c41e-3389-d556-4b2a3fb9602d
* Version Independent ID: 1575e125-abd0-82ee-15ef-8190620ae7c7
* Content: [Sensor orientation - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/sensor-orientation)
* Content Source: [windows-apps-src/devices-sensors/sensor-orientation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/sensor-orientation.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@davidljung - thanks for the feedback. I've updated the topic with more detail. The +Z-axis is pointing out from the device.
