### ISSUE TITLE
Critical issue not mentioned in Page

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#1957]
There is a critical issue in the page that is not mentioned and I was not able to solve: what if the data in the SQLite is critical and should not be bound to the sandbox but must survive the App?

From all the test I did I was NOT able to create the SQLite database file in the "Documents Folder" of the user.
Reading from MS documentation UWP application should NOT address directly the files/folders but use StorageFolder and Storage FIle
(references: [https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder)
[https://blogs.msdn.microsoft.com/wsdevsol/2012/12/04/skip-the-path-stick-to-the-storagefile/](https://blogs.msdn.microsoft.com/wsdevsol/2012/12/04/skip-the-path-stick-to-the-storagefile/))

Even if I've configured correctly all the File access properties and bindings 
([https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
[https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-capability](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-capability))
In fact I'm able to enumerate and read the file in the Library I'm not able to perform the SQLiteConnection

`Using db As SqliteConnection = New SqliteConnection("Filename=" ...))`
No matter what I try to do there.

I've found a document "Using SQLite Databases in Any Folder in WinRT" ([https://www.codeproject.com/Articles/879846/Using-SQLite-Databases-in-Any-Folder-in-WinRT](https://www.codeproject.com/Articles/879846/Using-SQLite-Databases-in-Any-Folder-in-WinRT)) that explains it is not possible from SQLite3 but has to do with custom/not supported code.

If this si true is a critical issue as my application handles very critical data that must not be deleted in the case of an app removal.
So I must be able to have the db file in a statefull storage outside of the sandbox and I would even put it in an OneDrive folder.
A workaround that is not feasible in terms of performance would be perform a file copy from the sandbox app storage location to the documents folder.

On the other side I tried to use SQL Server LocaDB ([https://blogs.msdn.microsoft.com/jerrynixon/2012/02/26/sql-express-v-localdb-v-sql-compact-edition/](https://blogs.msdn.microsoft.com/jerrynixon/2012/02/26/sql-express-v-localdb-v-sql-compact-edition/)) but I received an error that is NOT supported for UWP. In fact this section only mentions to connect with a SQL Server.

So how I can I solve the critical issue I face?
Am I doing something wrong? is it possible to have a code sample of an UWP app opening the data from a file in the User/Documents folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859b309d-ce6e-b518-75fa-54122d43f00c
* Version Independent ID: 1eee31ea-4e11-02e3-a9f4-c2c352d3f8c6
* Content: [Data access - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/#feedback)
* Content Source: [windows-apps-src/data-access/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/index.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by msavazzi** [comment]
Also note that several articles mention that LocalDB is for single use only and not production and that for real app SQLExpress should be used... but this raises the issue on how to distribute SQLExpress within an UWP app or automatically install it as prerequisite in the distribution via marketplace.
So again is not a feasible solution. The best is to have SQLite with the DB file in a user folder.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
