### ISSUE TITLE
Storing DateTime in local app settings causes exception

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/windows-uwp#1959]
According to this [section](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#settings), I should be able to store `DateTime` in the local app settings. However, when I try to run the following code, I get an exception.
```
Windows.Storage.ApplicationData.Current.LocalSettings.Values["test"] = DateTime.Now;
```

Am I doing something wrong? Is there an issue with the document? Or is there a bug in the platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340f7839-6454-f1b5-ced5-5000964efc2e
* Version Independent ID: f83df5c8-e149-df6e-243f-07311caab297
* Content: [Store and retrieve settings and other app data - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#related-articles)
* Content Source: [windows-apps-src/design/app-settings/store-and-retrieve-app-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/app-settings/store-and-retrieve-app-data.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by dpaulino** [comment]
Here is a screen shot of a blank UWP app with that line of code added in the MainPage.xaml.cs constructor

![image](https://user-images.githubusercontent.com/7649589/65812543-4669a100-e17d-11e9-9b7c-65a4b9451b9a.png)

**Comment by dpaulino** [comment]
Here is a repository that you can clone and you can reproduce the error: 
https://github.com/dpaulino/datetime-local-appsettings-uwp/tree/master/LocalAppSettings

**Comment by dpaulino** [comment]
Figured out what went wrong. I created this PR to help improve the docs https://github.com/MicrosoftDocs/windows-uwp/pull/1971

**Comment by jwmsft** [comment]
@dpaulino, thanks for the PR. DateTime is tricky because it shows up differently depending on the language you're programming in, so I also added a note that DateTimeOffset is for C# and .NET languages.
