### ISSUE TITLE
Referenced documentation no longer uses XAML content syntax

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/windows-uwp#1962]
The [XAML content properties](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-syntax-guide#xaml-content-properties) section contains the following:

> For example, the [Text](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.textblock.text) property page for [TextBlock](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.TextBlock) shows XAML content syntax that has an inner text value to set **Text**, but the string "Text" never appears in the markup.

The referenced documentation, however, doesn't use XAML content property syntax. It apparently has been updated to use attribute syntax.

This topic should be updated to match the referenced documentation. In case content property syntax is no longer recommended, this should be mentioned in this topic (possibly in place of a reference to documentation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 204cc15e-149d-caf0-48a7-86b29d39e8f7
* Version Independent ID: c13c7269-ae0e-5422-ef19-30ac90d1d6d6
* Content: [XAML syntax guide - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-syntax-guide#xaml-content-properties)
* Content Source: [windows-apps-src/xaml-platform/xaml-syntax-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/xaml-syntax-guide.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
I don't think so? The sample right below that text shows:

```xml
<TextBlock>Hello!</TextBlock>
```

**Comment by tim-weis** [comment]
This issue was referring to the [Text](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.textblock.text) property documentation. The quote in the issue report implies, that that documentation were using XAML content property syntax, but doesn't.

**Comment by jevansaks** [comment]
I see. The example below the text is correct and shows the usage but the linked page doesn't.

**Comment by jwmsft** [comment]
This is a known bug in the rendering of the XAML syntax block. If you click the Edit button on the Text property  page to view the [source file on GitHub](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.xaml.controls/textblock_text.md/#L0), you'll see that both forms of syntax are there. However, only the first one is rendered on the published page. We have not updated the XAML Syntax Guide page in hopes that this bug will eventually be fixed.

**Comment by jwmsft** [comment]
Syntax blocks were updated awhile back to show all forms of XAML syntax, so this issue is resolved. Thanks.
