### ISSUE TITLE
XAML type documentation doesn't contain ContentProperty name

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/windows-uwp#1963]
The [XAML content properties](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-syntax-guide#xaml-content-properties) section notes:

> For example, on the [Border](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.Border) reference page, you'll see this: ContentProperty("Name=Child").

That information, however, isn't available. The class documentation lists the attributes, but doesn't state the name for the ContentProperty.

The class documentation should contain the name of the ContentProperty for all types that have the ContentPropertyAttribute, irrespective of the Windows Runtime language projection used. Please make sure to not ignore C++/WinRT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 204cc15e-149d-caf0-48a7-86b29d39e8f7
* Version Independent ID: c13c7269-ae0e-5422-ef19-30ac90d1d6d6
* Content: [XAML syntax guide - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-syntax-guide#xaml-content-properties)
* Content Source: [windows-apps-src/xaml-platform/xaml-syntax-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/xaml-syntax-guide.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mijacobs this seems like a general improvement to the docs that we would need. The Metadata has this information, we would just want the docs pages to include it. Does WPF already do this and we could just extend that logic to the UWP pages?

**Comment by mijacobs** [comment]
The information is in the WPF docs, but it's manually added. For an example, see "Content model" in the remarks section of the button page: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netframework-4.8 

We have a work item open against the engineering team to add this info.

**Comment by jwmsft** [comment]
This information is now included on reference pages.
