### ISSUE TITLE
What is FixTextureContentType supposed to do?

### ISSUE THREAD

**Issue by AnFunctionArray** [MicrosoftDocs/windows-uwp#1964]
Title basically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66a42e61-d1f5-e3e8-8d62-69c6fb0c7461
* Version Independent ID: 646c03da-f399-02f8-6075-85bd96519703
* Content: [Generate a 3MF package - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/generate-3mf#feedback)
* Content Source: [windows-apps-src/devices-sensors/generate-3mf.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/generate-3mf.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@bsld - thanks for pointing this oversight out. I've added another snippet to the doc for the referenced function.
