### ISSUE TITLE
cgminer win IoT

### ISSUE THREAD

**Issue by wendigo75** [MicrosoftDocs/windows-uwp#1974]
is possible to build cgminer for Windows iot ?

**Comment by mattwojo** [comment]
Hi @wendigo75 -- the short answer: 'No, not supported'

The longer answer: it would be helpful to have more context about how you're interested in using cgminer with Windows IoT. I don't have a deep knowledge of Windows IoT and a more appropriate place to pose this question is in the Windows IoT issues: https://github.com/MicrosoftDocs/windows-iotcore-docs/issues

If you decide to repost your question there or a request for support, it would be helpful to have more context for why Windows IoT should support cgminer and a use-case.

Thanks for writing to us. :)  Closing this issue.
