### ISSUE TITLE
Cleanup of event handlers

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/windows-uwp#1982]
The code on this page does a lot of adding event handlers (+=), but does not show where cleanup should be done to remove event handlers (-=)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e904e1-c37c-668a-12a2-1c723cb0ac09
* Version Independent ID: e704bc94-c2dc-7c99-0345-4d704194da9d
* Content: [Print from your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app)
* Content Source: [windows-apps-src/devices-sensors/print-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/print-from-your-app.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jamesmcroft** [comment]
I think that there is just a code block missing from the documentation as the current docs covers what needs to be registered with an indication to register in the OnNavigatedTo method, but then explains that they should be unregistered in the OnNavigatedFrom method without showing what to unregister.

**Comment by bartlannoeye** [comment]
@Karl-Bridge-Microsoft this issue has been solved and can be closed.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks!
