### ISSUE TITLE
Good, more is wanted

### ISSUE THREAD

**Issue by JorgenSandberg** [MicrosoftDocs/windows-uwp#1983]
Very good instruction on Hello World app.
I wish there were many more examples like that using various Window controls and events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cf8f2c-dd46-4884-1e5c-a5014009db88
* Version Independent ID: 198bea04-c4bf-efff-c810-e6e5ef7c4bbd
* Content: [Create a Hello World app in C++/CX (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cpp#feedback)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
I'm glad to hear you found this article useful.

If you're interested in checking out more tutorial-like content for Windows 10 apps,[ check out our modules on Microsoft Learn](https://docs.microsoft.com/learn/browse/?products=windows&resource_type=module)

Thank you!
