### ISSUE TITLE
Documentation on tax information on Partner Dashboard is incorrect

### ISSUE THREAD

**Issue by sirredbeard** [MicrosoftDocs/windows-uwp#1985]
Under "Types of tax forms" it says to go to "Account settings" and "Tax profile" in Partner Center.

The "Account settings" page is now under "Developer Settings" and there is no "Tax profile" page, it is now "Payout and tax profiles".

Also there is are no tax forms. It is unclear where the tax forms went.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6e24fb-fe26-9a5a-6e57-7dfb1028ccf5
* Version Independent ID: 4f4114a9-71fa-7616-937e-dc6cadfad470
* Content: [Understand IRS tax forms issued by Microsoft - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/understand-irs-tax-forms#types-of-tax-forms)
* Content Source: [windows-apps-src/publish/understand-irs-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/understand-irs-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by andrewleader** [comment]
So where are the tax documents located @lastnameholiu ?

**Comment by Karl-Bridge-Microsoft** [comment]
This appears to be resolved. For instructions, see "In the Partner Center dashboard, select the Settings gear icon in the top-right corner, then Account settings." in the https://docs.microsoft.com/en-us/partner-center/set-up-your-payout-account#tax-forms section.
