### ISSUE TITLE
didnt work right away...

### ISSUE THREAD

**Issue by delly47** [MicrosoftDocs/windows-uwp#1986]
took me forever to figure out that you also need to check off Internet (Client & Server), Internet (Client) and Private Networks (Client & Server)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92140a3c-b33d-6aa7-a904-d03c8122fbdf
* Version Independent ID: 90a33ee7-ec4a-2bcc-b776-530a1c3014fd
* Content: [Use a SQL Server database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases#feedback)
* Content Source: [windows-apps-src/data-access/sql-server-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sql-server-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by ghost** [comment]
Thanks for the heads up 😊 jensocan.

Sent from my Windows 10 device

**Comment by AgmundrTerr** [comment]
it is still not working for me. In a console app everything functions just fine.

**Comment by QuinnRadich** [comment]
Thanks for the feedback, I've added this disclaimer to the instructions. Agmundr, if you're still having issues after following the updated steps, I'd encourage you to file a new issue here.

Thank you.
