### ISSUE TITLE
Access Denied for country/region codes used by Microsoft

### ISSUE THREAD

**Issue by JosephMart** [MicrosoftDocs/windows-uwp#1992]
In the note on the page (inserted below), the link takes you to a `Access Denied` page one I login with my Microsoft account. Is this doc page not public?

> For a list of standard country/region codes used by Microsoft, see the [Official Country/Region List.](https://globalready.azurewebsites.net/marketreadiness/OfficialCountryregion) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daefed41-a007-30fb-d7b2-79836132acb2
* Version Independent ID: 5033b6cf-55e3-9368-711f-bd2f3f229fab
* Content: [Globalization and localization - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/globalizing-portal#feedback)
* Content Source: [windows-apps-src/design/globalizing/globalizing-portal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/globalizing-portal.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jamesmcroft** [comment]
Also gave this a try and cannot access it. Looks like it's a link to an internal Microsoft SharePoint site.

**Comment by Karl-Bridge-Microsoft** [comment]
@JosephMart - thanks for the head's up. I've revised the link. Hopefully, it's more helpful.
