### ISSUE TITLE
Can't get notifications working with clickonce app

### ISSUE THREAD

**Issue by gwynjudd** [MicrosoftDocs/windows-uwp#1995]
This issue seems to be similar to the following two, which seem to be closed but there doesn't seem to be a definite resolution:

https://github.com/MicrosoftDocs/windows-uwp/issues/976
https://github.com/MicrosoftDocs/windows-uwp/issues/361

Having followed through the document faithfully, I was able to get notifications working successfully in my classic desktop app, if launched in the normal fashion, with a ".lnk" shortcut installed by WiX.

BUT, if installed by clickonce, I found that although the notification appears, when clicked on, it does "nothing" (doesn't call my notification activator). In addition, the notification appears in the action center, but goes away when the notification hides.

I think what is needed is some definitive guide on how to get notifications working with click once.

Is it necessary to create a ".lnk" shortcut to the clickonce app in the deployed location? This seems concerning because it will skip the usual start behaviour of clickonce e.g. security checks and startup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Send a local toast notification from desktop C# apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by rdnlsmith** [comment]
I am encountering this as well. I was able to get the ClickOnce-generated AUMID [via Get-StartApps in PowerShell](https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app#to-find-the-aumid-by-using-windows-powershell) and register that during the app startup, and I am now successfully sending notifications from a .NET Framework console app. My notifications do persist in the action center until I clear them, but clicking on them does not trigger the `OnActivated()` method in my `NotificationActivator`. I'm thinking it has to do with the CLSID, but I'm having trouble finding much information about it.

**Comment by hickeys** [comment]
It looks like when this issue last came up, a colleague of mine was in contact with the engineering team. I've reached out to him to get caught up on that conversation, and I'll update here with there's anything to share.

**Comment by andrewleader** [comment]
Hi @rdnlsmith and @gwynjudd, we've dramatically updated the way non-UWP apps can send toast notifications! The Start menu shortcut is no longer required! If you try this out, please let us know if you have any feedback or how it worked for you! It should hopefully work very easily for ClickOnce and any other types of apps now :)

See the new docs here: https://docs.microsoft.com/windows/uwp/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop

General steps...

1. Install the latest 7.0 Toolkit Notifications NuGet library: https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/
2. Send a toast using the code below!

```csharp
new ToastContentBuilder()
    .AddText("Andrew sent you a picture")
    .AddText("Check this out, The Enchantments in Washington!")
    .Show(); // Not seeing the Show() method? If you're using .NET 5, your TFM must be net5.0-windows10.0.17763.0 or greater
```

See the docs for instructions on how to handle activation and more!

**Comment by gwynjudd** [comment]
thanks @andrewleader this is actually amazingly good timing for me because I'm just starting a project relating to this. I will try it out soon

**Comment by gwynjudd** [comment]
@andrewleader  OK just to report back, it's been a while due to various issues I wasn't able to follow up on picking up this new release until now. I just want to let you know it all looks good. I was able to get rid of a great deal of work around code with the latest UWP modules and everything looks to be working good, including toast notifications for click once deployed. Thanks for this, big thumbs up from me

**Comment by andrewleader** [comment]
Wahoo! Thanks for confirming @gwynjudd, I'm happy to hear that! 😊
