### ISSUE TITLE
Mention how to make ListViewItem stretch horizontally

### ISSUE THREAD

**Issue by adrientetar** [MicrosoftDocs/windows-uwp#1997]
By default ListViewItem is left-aligned, which means that Grid columns won't stretch... I think that this non-obvious snippet of code should get a mention:

```xaml
<ListView.ItemContainerStyle>
    <Style TargetType="ListViewItem">
        <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
    </Style>
</ListView.ItemContainerStyle>
```

(taken from the WPF docs)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9e528879-9c1d-ec7f-70df-f69ee3def630
* Version Independent ID: dc9677a2-bdc9-e820-b919-cbc4adffc319
* Content: [Affichage Liste et affichage Grille - Windows UWP applications](https://docs.microsoft.com/fr-fr/windows/uwp/design/controls-and-patterns/listview-and-gridview)
* Content Source: [windows-apps-src/design/controls-and-patterns/listview-and-gridview.md](https://github.com/MicrosoftDocs/windows-uwp.fr-fr/blob/live/windows-apps-src/design/controls-and-patterns/listview-and-gridview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by anawishnoff** [comment]
Hi again @adrientetar. Sorry about the delay on this, and thanks for opening up an issue here. I'll work on getting these changes into the docs this week. :)
