### ISSUE TITLE
Improper exception handling

### ISSUE THREAD

**Issue by jinek** [MicrosoftDocs/windows-uwp#20]
There are several catch(Exception) blocks that just swallow an exception.
For example, StartPreviewAsync:
catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("MediaCapture initialization failed. {0}", ex.Message);
            }
First of all, this exception is not always related to MediaCapture. It is possible this exception to be OutOfMemoryException or any other (like DevideByZeroException).
From debugging perspective this just does not make sense as any unhandled exception will be put into debugger output by itself.
From the user perspective it is unresponsive solution: user presses - nothing happening.
According to c# best practices: https://msdn.microsoft.com/en-us/library/ms173160.aspx better to remove this catch block, or if we expect some errors there should be also "when" instructions that will expect some exact HRESULT codes.
If we want to prevent application from crashing it's better to submit to Application.UnhandledException and put e.Handled=true. Anyway there is no reason to catch "everything"

**Comment by mattwojo** [comment]
Hi @jinek - Thanks for filing this issue. I'm helping to triage these issues to the correct teams so that the issue can be addressed. Could you help me to understand which documentation page addresses the exception handling issue that you are pointing out? If you could share a URL for the page you are referencing, it would help me to assign the correct person for investigation. Thanks! ~Matt

**Comment by jinek** [comment]
Hi, this is it: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/simple-camera-preview-access

**Comment by mattwojo** [comment]
Hey @drewbatgit -- looks like this is your page. Could you take a look at this exception issue that @jinek shared?

**Comment by drewbatgit** [comment]
I am investigating this issue.

**Comment by mattwojo** [comment]
@drewbatgit -- any updates on this issue?

**Comment by drewbatgit** [comment]
This code has been updated to check specifically for the FileLoadException when initializing the camera preview and using the new CaptureDeviceExclusiveControlStatusChanged event to listen for camera availability.
