### ISSUE TITLE
Segoe MDL2 License

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/windows-uwp#2006]
I have searched for information about licensing of the Segoe MDL2 font, but I was unable to find any information about that. Is there a possibilty to add this information to [this page](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)? 😅

**Comment by hickeys** [comment]
I'm not sure exactly what you would like to do with Segoe MDL2, but perhaps [this page](https://docs.microsoft.com/en-us/typography/fonts/font-faq) would give you the information you need.

https://docs.microsoft.com/en-us/typography/fonts/font-faq

**Comment by marcelwgn** [comment]
I am thinking about applications that use the icons as resources to use e.g. as an icon creator or an app to combinate and overly multiple Segoe MDL2 Assets icons (as outlined [here](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#layering-and-mirroring)). Is it allowed to export those, and if so in which format?

**Comment by llamax1** [comment]
For your reference, the following is from the Segoe EULA, included with the ZIP file on [this page ](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#layering-and-mirroring) (go to  "How do I get this font?" > "On a Mac", or go straight to the download ([aka.ms/SegoeFonts](aka.ms/SegoeFonts))):

> You may use the Segoe MDL2 Assets and Segoe UI fonts or glyphs included in this file (“Software”) solely to design, develop and test your programs that run on a Microsoft Platform, a Microsoft Platform includes but is not limited to any hardware or software product or service branded by trademark, trade dress, copyright or some other recognized means, as a product or service of Microsoft. This license does not grant you the right to distribute or sublicense all or part of the Software to any third party.  By using the Software you agree to these terms. If you do not agree to these terms, do not use the Software.

On other platforms, there is an open-source drop in replacement [here](https://github.com/microsoft/fonts). I do wonder why they bothered providing a macOS download link if you can't use it on a non-Microsoft platform.

**Comment by marcelwgn** [comment]
Thank you so much @llamax1 for sharing those information with me! I'm also a bit surprised as to why they provided a download for Mac if it's prohibited via the EUAL. I can only speculate here but maybe Office 365 or Sharepoint count as Microsoft Platform here so you would be allowed to use them in there? But that's just a speculation so.

**Comment by hickeys** [comment]
I'm going to leave the page as-is. As @llamax1 points out, the EULA is included with the font. Legal documents like licensing agreements require specialized localization, so I'm inclined to stick with the existing setup.

**Comment by marcelwgn** [comment]
Alright, thanks for the update @hickeys !
