### ISSUE TITLE
hello!

### ISSUE THREAD

**Issue by krunch3r76** [MicrosoftDocs/windows-uwp#2008]
From the Note at the start of this webpage there is a link to which the reader is referred in the following line: "For more background, setup, and support info, see Getting started with the Windows UI Library." This should probably be emphasized as pre-requisite reading to building/running this hello 🌎 example. Specifically, the includes from that page's section: "Additional steps for a C++/WinRT project" are absolutely required and a hello 🌎 single page example is not complete without at least a mention of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb0978bf-4d67-556c-b6c6-87b360d446c8
* Version Independent ID: 6fe15723-a3a2-9a7c-1720-ef4194f5ed70
* Content: [A simple C++/WinRT Windows UI Library example - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/simple-winui-example.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/simple-winui-example.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @krunch3r76, thanks for this feedback. This topic (A simple C++/WinRT Windows UI Library example) contains everything you need to create and run the code example. The other topic (Getting started with the Windows UI Library) doesn't contain any prerequisite info, nor any relevant info that's not already in this topic. The info in that topic's "Additional steps for a C++/WinRT project" is present in this topic's "Edit MainPage.h and .cpp as necessary" section.

I just re-confirmed that I can successfully follow just the steps in this topic, and createa and run the code example. I'll go ahead and close the issue, but please let me know if you feel there's still an issue with the docs here.

Thanks!
Steve
