### ISSUE TITLE
Why suggest using a Windows Insider build if the audience is "beginners "

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/windows-uwp#2011]
I like WSL, but suggesting a beta OS build and an unreleased WSL2 build for beginners doesn't seem to match the audience of the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811fa359-feec-10dd-544c-881982b25138
* Version Independent ID: aeb2c4e1-28d2-65c8-06e7-b63a3233c5e2
* Content: [Get started using NodeJS on Windows for beginners](https://docs.microsoft.com/en-us/windows/nodejs/beginners)
* Content Source: [hub/nodejs/beginners.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/beginners.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
In my opinion, we need to start beginners off on the right foot... from the beginning. If we have them install Node.js directly on Windows, the initial set up is simplified, but the tools, workflow, ability to implement the commands found out in the wild via courses and tutorials... it's all _slightly_ different for a direct Windows install... thus the frustration we've heard from folks using Node on Windows in the past. The WSL path gets them on the right foot from the get-go.  Adding @fiveisprime, @shanselman, @indierawk2k2, @yodurr, for their insight on this. 

For a bit of context, @nschonni is responding to my request to add a link on the Node.js downloads page: https://github.com/nodejs/nodejs.org/issues/2684

Thanks all!

**Comment by mattwojo** [comment]
After some further conversations, agree with your assessment @nschonni and have updated this page to represent the more straightforward install path directly on Windows. Thanks for your input and contribution. ~Matt

**Comment by mattwojo** [comment]
Updated in https://github.com/MicrosoftDocs/windows-uwp-pr/pull/515
Closing.

**Comment by nschonni** [comment]
👍 thanks, looks good
