### ISSUE TITLE
Listing a known issue here without any kind of date doesn't give the developer hope

### ISSUE THREAD

**Issue by JerryNixon** [MicrosoftDocs/windows-uwp#2017]
Attachments that you add to an email by using the EmailAttachment class will appear only in the Mail app. If users have any other mail program configured as their default mail program, the compose window will appear without the attachment. This is a known issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffe51be1-8221-ad14-2397-4ae701590449
* Version Independent ID: 8226d57b-7826-bebc-1961-8f1d8a24d440
* Content: [Send email - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/sending-email)
* Content Source: [windows-apps-src/contacts-and-calendar/sending-email.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/contacts-and-calendar/sending-email.md)
* Product: **uwp**
* Technology: **people-and-places**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by luminixinc** [comment]
This issue affects our UWP app(s) where we need to launch the email app with attachments.  Some of our customers do indeed use Mail.app, but a lot more insist upon using Outlook.  We really hope Microsoft fixes this soon, so that we have a single API that works pervasively with (at least all Microsoft email clients).

**Comment by luminixinc** [comment]
Here is a link to discussion of the same issue in MSDN forums.  This "known issues" apparently has quite the colorful history!  https://social.msdn.microsoft.com/Forums/azure/en-US/5a539ff6-ce81-4f05-83a0-8bf430d827f8/uwpwindows-10-c-universal-windows-app-email-with-attachment

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback. Unfortunately, the scope of this feedback channel covers specific documentation fixes, so I'm unable to get an answer for you. The best approach would be to file something over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) for higher visibility.
