### ISSUE TITLE
This does not work with media playback list

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/windows-uwp#2018]
See https://social.msdn.microsoft.com/Forums/windowsapps/en-US/6a8b41ee-71ad-4e83-8e76-f25ba8de327a/uwp-any-special-considerations-when-using-ibasicvideoeffect-with-mediaplaybacklist?forum=wpdevelop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4621527-e2b3-58fc-5291-3be1b7598be4
* Version Independent ID: f0d715d2-afc5-9e2f-8a9c-b36cddd87dda
* Content: [Custom video effects - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/custom-video-effects)
* Content Source: [windows-apps-src/audio-video-camera/custom-video-effects.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/custom-video-effects.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@mcosmin222 Hi, issues in this git repo are limited to documentation-related issues. We aren't able to provide tech support here. But I can see that you are waiting for a response on your thread on the forums. I've sent mail to the relevant product group, including a link to your forum post, to try to raise the visibility of your issue.
