### ISSUE TITLE
convert_from_abi helper has unnecessary cast

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#2026]
windows-uwp/windows-apps-src/cpp-and-winrt-apis/[interop-winrt-abi.md](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/interop-winrt-abi#convert_from_abi-function)

this helper can be written without the cast like this, please update the 2 occurrences on the page above.
```
template <typename T>
T convert_from_abi(::IUnknown* from)
{
    T to{ nullptr }; // this is a winrt projection type
    winrt::check_hresult(from->QueryInterface(winrt::guid_of<T>(), winrt::put_abi(to)));
    return to;
}
```

**Comment by stevewhims** [comment]
Ok, this fix is published.

**Comment by stevewhims** [comment]
I'll go ahead and close. Thanks, Chris!

-Steve
