### ISSUE TITLE
Add information about showing Recent files in the JumpList

### ISSUE THREAD

**Issue by adrientetar** [MicrosoftDocs/windows-uwp#2027]
Basically add information referencing https://docs.microsoft.com/en-us/uwp/api/windows.ui.startscreen.jumplist, and describing how to get recent files to show up in the JumpList.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea426a20-ab2c-38a1-2394-f0c45b7f07a6
* Version Independent ID: da36c626-4a6f-bd65-ca6e-fa2e97aeb7a9
* Content: [Track recently used files and folders - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders)
* Content Source: [windows-apps-src/files/how-to-track-recently-used-files-and-folders.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/how-to-track-recently-used-files-and-folders.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
