### ISSUE TITLE
Variable length of UTF-8

### ISSUE THREAD

**Issue by veawor** [MicrosoftDocs/windows-uwp#2035]
I suppose it's 1-6 bytes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a28119a-77f2-160c-a4f1-f90ef9153423
* Version Independent ID: 28b24e82-f0ef-cceb-2136-f8dbfabfcadc
* Content: [Use the Windows UTF-8 code page - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page#feedback)
* Content Source: [windows-apps-src/design/globalizing/use-utf8-code-page.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/use-utf8-code-page.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@veawor - Can you clarify? Not sure what the issue is here. Thanks.

**Comment by uecasm** [comment]
Presumably, in the second paragraph where it says "1-6 byte variable-width encoding", they thought it should say "1-6 bytes variable-width encoding" instead.  However I believe that the former is technically more correct, although as usual I don't think there's any formal rule on the subject so either is probably acceptable.

**Comment by wronso** [comment]
> Presumably, in the second paragraph where it says "1-6 byte variable-width encoding", they thought it should say "1-6 bytes variable-width encoding" instead. However I believe that the former is technically more correct, although as usual I don't think there's any formal rule on the subject so either is probably acceptable.

I suppose you are trying to say the biggest code point of Unicode only takes 4 bytes. "1-6 byte variable-width" is technically correct to me because the UTF-8 specification says so. Perhaps, we may rephrase the whole paragraph.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! I've updated the topic with additional detail that I hope clears things up. Please re-open the issue, if not.
