### ISSUE TITLE
Asynchronous is misspelled multiple times on this page.

### ISSUE THREAD

**Issue by SamPavezaMS** [MicrosoftDocs/windows-uwp#2036]
Search "Asych"  to find them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db952f42-9d6e-d30b-0aed-e7de64a89987
* Version Independent ID: bea24c9a-3e1e-405d-d7cc-5a080e62ece2
* Content: [Concurrency and asynchronous operations with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, the fix is now live (thanks to the contributor of that PR).
