### ISSUE TITLE
I keep getting the error code 500 when accessing: https://xboxone:11443/#Home

### ISSUE THREAD

**Issue by mrsupaplex** [MicrosoftDocs/windows-uwp#2040]
I keep getting the error code 500 when accessing: https://xboxone:11443/#Home

**Comment by hkhmsft** [comment]
Hi there and thanks for reaching the documentation team. Would you be able to point to the document where you found this link?

**Comment by mrsupaplex** [comment]
its just the xbox server being unstable.
keep getting errors when trying to upload a package with chrome.

**Comment by hkhmsft** [comment]
Sorry to hear that. However, this feels not so much like feedback specifically about the documentation but rather like a support request. There are some support resources I can provide that might help find some answers to your issue:

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

Hope everything works out.
