### ISSUE TITLE
USB Printers support

### ISSUE THREAD

**Issue by jupagose** [MicrosoftDocs/windows-uwp#2048]
What about Stationary USB Receipt Printers, there is no update about it ? 
There is no plans to support it ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be30771-0778-ee6d-5b5f-ec931705af27
* Version Independent ID: 224b4d4c-bd10-5e81-2412-fd12d36369c4
* Content: [Point of Service Hardware Support - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-device-support#feedback)
* Content Source: [windows-apps-src/devices-sensors/pos-device-support.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/pos-device-support.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! However, this appears to be a product issue and not a doc bug (at this time), so please consider posting the issue at https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose for the product team to track publicly.
