### ISSUE TITLE
Workaround if you're getting "unable to open database file"

### ISSUE THREAD

**Issue by nahrens** [MicrosoftDocs/windows-uwp#2049]
In UWP you're limited to a handful of folders for file IO (outside StorageFile anyway).  This works:

```
string path = System.IO.Path.Combine
	(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "test_sqlite.db");

//get our sqlite database, or create if none existing
using (SqliteConnection db =
new SqliteConnection())
{
	db.ConnectionString = "Filename=" + path;
	db.Open();
	//... do stuff like creating tables
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by mcleanbyron** [comment]
Thanks for your input. We have revised the code examples in this article to account for this behavior.
