### ISSUE TITLE
Missing API's

### ISSUE THREAD

**Issue by PonchoPowers** [MicrosoftDocs/windows-uwp#2057]
How do we add the following...

Windows.ApplicationModel
Windows.Management
Windows.Storage

See
https://github.com/cairoshell/cairoshell/issues/283
https://developercommunity.visualstudio.com/content/problem/446490/visual-studio-cant-see-winmetadatadirectory-in-cwi.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Use UWP APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#feedback)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Assuming that you're trying to use APIs in these namespaces in a non-UWP desktop app, you can use one of the options provided in [this section](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#set-up-your-project). The NuGet package option is the easiest. 

In the forum thread you linked to, it sounds like the problem is that developers were directly referencing libraries in C:\Windows\System32. This was never a supported scenario. If you are unable to get one of the options provided above working, please reopen this issue with details about the error you are seeing.

Thank you.

**Comment by PonchoPowers** [comment]
Microsoft.Windows.SDK.Contracts doesn't contain the namespaces I need access to. I did try this, and even mentioned so in the github issue I linked to this issue.

There are no docs on how to get access to the following namespaces:

 - Windows.ApplicationModel.Package
 - Windows.Management.Deployment.PackageManager

Yet your colleagues are directing us to the instructions you have linked to. It was also Microsoft's decision to restrict access to the folder containing everything I needed.

So I'm really looking for some information on where to go from here to be honest.

And for the sake of clarity, the Microsoft.Windows.SDK.Contracts NuGet package contains API's with the following namespaces:

- Windows.AI.MachineLearning.MachineLearningContract
- Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract
- Windows.ApplicationModel.Activation.ActivatedEventsContract
- Windows.ApplicationModel.Activation.ActivationCameraSettingsContract
- Windows.ApplicationModel.Activation.ContactActivatedEventsContract
- Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract
- Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract
- Windows.ApplicationModel.Calls.Background.CallsBackgroundContract
- Windows.ApplicationModel.Calls.CallsPhoneContract
- Windows.ApplicationModel.Calls.CallsVoipContract
- Windows.ApplicationModel.Calls.LockScreenCallContract
- Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract
- Windows.ApplicationModel.FullTrustAppContract
- Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract
- Windows.ApplicationModel.Preview.Notes.PreviewNotesContract
- Windows.ApplicationModel.Resources.Management.ResourceIndexerContract
- Windows.ApplicationModel.Search.Core.SearchCoreContract
- Windows.ApplicationModel.Search.SearchContract
- Windows.ApplicationModel.SocialInfo.SocialInfoContract
- Windows.ApplicationModel.StartupTaskContract
- Windows.ApplicationModel.Wallet.WalletContract
- Windows.Devices.Custom.CustomDeviceContract
- Windows.Devices.DevicesLowLevelContract
- Windows.Devices.Portable.PortableDeviceContract
- Windows.Devices.Printers.Extensions.ExtensionsContract
- Windows.Devices.Printers.PrintersContract
- Windows.Devices.Scanners.ScannerDeviceContract
- Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract
- Windows.Devices.SmartCards.SmartCardEmulatorContract
- Windows.Devices.Sms.LegacySmsApiContract
- Windows.Embedded.DeviceLockdown.DeviceLockdownContract
- Windows.Foundation.FoundationContract
- Windows.Foundation.UniversalApiContract
- Windows.Gaming.Input.GamingInputPreviewContract
- Windows.Gaming.Preview.GamesEnumerationContract
- Windows.Gaming.UI.GameChatOverlayContract
- Windows.Gaming.UI.GamingUIProviderContract
- Windows.Gaming.XboxLive.StorageApiContract
- Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract
- Windows.Graphics.Printing3D.Printing3DContract
- Windows.Management.Deployment.Preview.DeploymentPreviewContract
- Windows.Management.Workplace.WorkplaceSettingsContract
- Windows.Media.AppBroadcasting.AppBroadcastingContract
- Windows.Media.AppRecording.AppRecordingContract
- Windows.Media.Capture.AppBroadcastContract
- Windows.Media.Capture.AppCaptureContract
- Windows.Media.Capture.AppCaptureMetadataContract
- Windows.Media.Capture.CameraCaptureUIContract
- Windows.Media.Capture.GameBarContract
- Windows.Media.Devices.CallControlContract
- Windows.Media.MediaControlContract
- Windows.Media.Playlists.PlaylistsContract
- Windows.Media.Protection.ProtectionRenewalContract
- Windows.Networking.Connectivity.WwanContract
- Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract
- Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract
- Windows.Networking.Sockets.ControlChannelTriggerContract
- Windows.Networking.XboxLive.XboxLiveSecureSocketsContract
- Windows.Perception.Automation.Core.PerceptionAutomationCoreContract
- Windows.Phone.PhoneContract
- Windows.Phone.StartScreen.DualSimTileContract
- Windows.Security.EnterpriseData.EnterpriseDataContract
- Windows.Security.ExchangeActiveSyncProvisioning.EasContract
- Windows.Services.Maps.GuidanceContract
- Windows.Services.Maps.LocalSearchContract
- Windows.Services.Store.StoreContract
- Windows.Services.TargetedContent.TargetedContentContract
- Windows.Storage.Provider.CloudFilesContract
- Windows.System.Profile.ProfileHardwareTokenContract
- Windows.System.Profile.ProfileRetailInfoContract
- Windows.System.Profile.ProfileSharedModeContract
- Windows.System.Profile.SystemManufacturers.SystemManufacturersContract
- Windows.System.SystemManagementContract
- Windows.System.UserProfile.UserProfileContract
- Windows.System.UserProfile.UserProfileLockScreenContract
- Windows.UI.ApplicationSettings.ApplicationsSettingsContract
- Windows.UI.Core.AnimationMetrics.AnimationMetricsContract
- Windows.UI.Core.CoreWindowDialogsContract
- Windows.UI.Shell.SecurityAppManagerContract
- Windows.UI.ViewManagement.ViewManagementViewScalingContract
- Windows.UI.WebUI.Core.WebUICommandBarContract
- Windows.UI.Xaml.Core.Direct.XamlDirectContract
- Windows.UI.Xaml.Hosting.HostingContract
- Windows.Web.Http.Diagnostics.HttpDiagnosticsContract

**Comment by PonchoPowers** [comment]
In the following page there is a different list of namespaces:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api

And in this list, the namespaces mentioned are supported.

So either I'm doing something wrong, or the docs are wrong.

**Comment by mcleanbyron** [comment]
Can you clarify what type of project you are trying to use these namespaces in and what errors you are seeing when you try to write code in those namespaces?

I just tried installing the Microsoft.Windows.SDK.Contracts NuGet package (version 10.0.18362.2005) to a basic WPF project on Windows 10 version 1903, and I was able to successfully build code that uses the Windows.ApplicationModel.Package and
Windows.Management.Deployment.PackageManager classes. I was also able to build code that uses APIs in the Windows.Storage namespace.

**Comment by PonchoPowers** [comment]
I've tried it on two different computers now.

As you said, create a simple WPF app, install the NuGet package, same version mentioned, same Windows build. I end up with an error when trying to do the following:

Windows.Management.Deployment.PackageManager pman = new Windows.Management.Deployment.PackageManager();

Error	CS0234	The type or namespace name 'Management' does not exist in the namespace 'Windows' (are you missing an assembly reference?)	WpfApp1	C:\Users\MatthewB\source\repos\WpfApp1\WpfApp1\App.xaml.cs	16	Active

I will package up the project if you want and stick it on github so you can see what I've done?

**Comment by mcleanbyron** [comment]
If you go to the Installed tab of NuGet Package Manager, can you confirm that the Microsoft.Windows.SDK.Contracts package is installed successfully? If you can share your project on GitHub, I'd be happy to take a look and try building it myself. 

I just tried the steps in a WPF project again (both full .NET Framework and .NET Core) and was able to compile your exact code.

**Comment by PonchoPowers** [comment]
It is installed successfully.

I downloaded a project from some Microsoft samples and it built ok, I compared it with my project and I can see the difference.

The problem is that when using NuGet, it adds the following into the project file...

```
  <Import Project="..\packages\System.Runtime.WindowsRuntime.4.6.0\build\net461\System.Runtime.WindowsRuntime.targets" Condition="Exists('..\packages\System.Runtime.WindowsRuntime.4.6.0\build\net461\System.Runtime.WindowsRuntime.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\System.Runtime.WindowsRuntime.4.6.0\build\net461\System.Runtime.WindowsRuntime.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\System.Runtime.WindowsRuntime.4.6.0\build\net461\System.Runtime.WindowsRuntime.targets'))" />
    <Error Condition="!Exists('..\packages\System.Runtime.WindowsRuntime.UI.Xaml.4.6.0\build\net461\System.Runtime.WindowsRuntime.UI.Xaml.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\System.Runtime.WindowsRuntime.UI.Xaml.4.6.0\build\net461\System.Runtime.WindowsRuntime.UI.Xaml.targets'))" />
    <Error Condition="!Exists('..\packages\Microsoft.Windows.SDK.Contracts.10.0.18362.2005\build\Microsoft.Windows.SDK.Contracts.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Windows.SDK.Contracts.10.0.18362.2005\build\Microsoft.Windows.SDK.Contracts.props'))" />
    <Error Condition="!Exists('..\packages\Microsoft.Windows.SDK.Contracts.10.0.18362.2005\build\Microsoft.Windows.SDK.Contracts.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Windows.SDK.Contracts.10.0.18362.2005\build\Microsoft.Windows.SDK.Contracts.targets'))" />
  </Target>
  <Import Project="..\packages\System.Runtime.WindowsRuntime.UI.Xaml.4.6.0\build\net461\System.Runtime.WindowsRuntime.UI.Xaml.targets" Condition="Exists('..\packages\System.Runtime.WindowsRuntime.UI.Xaml.4.6.0\build\net461\System.Runtime.WindowsRuntime.UI.Xaml.targets')" />
  <Import Project="..\packages\Microsoft.Windows.SDK.Contracts.10.0.18362.2005\build\Microsoft.Windows.SDK.Contracts.targets" Condition="Exists('..\packages\Microsoft.Windows.SDK.Contracts.10.0.18362.2005\build\Microsoft.Windows.SDK.Contracts.targets')" />
```
And for the project that I downloaded, the project file looks like so:

```
<ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.18362.2005" />
  </ItemGroup>
```

I'm not sure why this is, but at least I know now where to start trying to resolve the issue.
