### ISSUE TITLE
certificates problem

### ISSUE THREAD

**Issue by JanabiSoft** [MicrosoftDocs/windows-uwp#2059]
the link above: https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing 
show how to make a password protected certificate which is not supported by azure pipelines, how can we make password-less certificates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps#feedback)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by davidbaberowski** [comment]
you can use a password protected certificate under VS2019 with azure, but you have to install it to the certificate store of the VM. you can do this with a powershell script

for a detailed sample have a look here: https://damienaicheh.github.io/uwp/azure/devops/appcenter/2019/09/18/install-pfx-certificate-of-your-uwp-application-on-your-azure-devops-en.html

**Comment by JanabiSoft** [comment]
@dizzelowski thanks, I will try it and let you know.

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback on this article. and I apologize for the delayed response. 

Although the procedure referenced by the previous commenter works in your scenario, note that step 5 in [this section](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps#add-your-project-certificate-to-the-secure-files-library) indicates that using a certificate file that is itself password-protected is not currently supported. 

As for creating a password-less certificate file, see [this section](https://docs.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing#export-a-certificate) about using the ProtectTo parameter.
