### ISSUE TITLE
Docs for BluetoothLEDevice.GattServicesChanged event fail to show how to correctly handle the event

### ISSUE THREAD

**Issue by bkromhout** [MicrosoftDocs/windows-uwp#206]
The [BluetoothLEDevice.GattServicesChanged](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice#Windows_Devices_Bluetooth_BluetoothLEDevice_GattServicesChanged) event's documentation provides no information about how to properly handle said event being fired. The only thing stated is _why_ the event would ever be fired.

What's worse, since the event's second parameter is an `object` (rather than a class), developers also cannot _infer_ how to handle the event. Referring to the APIs source code (through decompilation or otherwise) in order to determine how to handle the event is also a no-go since the UWP APIs are native code _and_ closed source.

With this in mind, I would greatly appreciate it if someone could inform me of exactly how this event should be properly handled, either here or by updating the documentation.

As an aside, I feel it's worth noting that the UWP Bluetooth LE API docs don't feel very fleshed-out in general. I've been working with them closely for about a month, and this specific question showcases one of the more severe deficiencies, but there are plenty of areas across the [Windows.Devices.Bluetooth.GenericAttributeProfile](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile) namespace, as well as the BLE-related APIs classes in the [Windows.Devices.Bluetooth](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth) namespace, where improvements could be made.

**Comment by mattwojo** [comment]
Thanks for bringing this to our attention @bkromhout. 

@msatranjr or @sapaetsc-msft - Can either of you help with this?

**Comment by bkromhout** [comment]
Not to be bothersome, but has any progress been made internally on this? I know it probably got lost under all of the FCU work, but I'd still like to see it addressed.

**Comment by msatranjr** [comment]
Thank you for the feedback @bkromhout. I have added some remarks to the event page explaining how to handle this event. There is a slight lag of this content going live on Docs.Microsoft.com, but you can see the change in the markdown file:

https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.devices.bluetooth/bluetoothledevice_gattserviceschanged.md/#L0
