### ISSUE TITLE
UWP APIs in the "Win32 API Reference" Section

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/windows-uwp#2060]
I noticed some Windows Runtime APIs are grouped under the "Win32 API Reference" section. Also, changes that appear to be for Win32 are found under "WinRT API reference."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bdb5007-8cda-76f2-6ba3-b198d7c2c9f4
* Version Independent ID: cb299507-7c92-53ee-4b45-a0ef14384f96
* Content: [Latest updates to the Windows developer docs](https://docs.microsoft.com/en-us/windows/apps/whats-new/latest-doc-updates)
* Content Source: [hub/apps/whats-new/latest-doc-updates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/whats-new/latest-doc-updates.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by GrantMeStrength** [comment]
Thanks, I'll try to do a better job categorizing them in future!
