### ISSUE TITLE
A link to authentication in UWP is missing

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/windows-uwp#2061]
There are several technologies that one can leverage in UWP to handle user accounts / login, like WebAccountProvider and WebAuthenticationBroker.

It would be helpful if there would be
- a link to that documentation on this page
- documentation and a sample for writing a WebAccountProvider (https://github.com/MicrosoftDocs/windows-uwp/issues/671)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 4f89c315-e5e9-14a9-5f3b-b1fa55ea6cfe
* Version Independent ID: 1402f7e3-14ca-92c8-ed02-3a4e46466562
* Content: [Features and technologies](https://docs.microsoft.com/nl-nl/windows/apps/features-and-technologies)
* Content Source: [hub/apps/features-and-technologies.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/features-and-technologies.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay in responding. I have added a new "Security" section to this article including links to the [Web account manager](https://docs.microsoft.com/en-us/windows/uwp/security/web-account-manager) and [Web authentication broker](https://docs.microsoft.com/en-us/windows/uwp/security/web-authentication-broker) articles. Hopefully those articles have the additional information (including links to more complete code samples) you're looking for. If not, please feel free to file further feedback against those articles by using the "Feedback" links at the bottom of those pages.
