### ISSUE TITLE
How do I...

### ISSUE THREAD

**Issue by Retne** [MicrosoftDocs/windows-uwp#2062]
Hi there.
It would be great to continue this with a link for the Adobe XD resources available for a non-UWP app (i.e. desktop). Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Design toolkits and samples for UWP apps - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by StephenLPeters** [comment]
@Retne this page is specific to UWP. Can you clarify what improvement you would like to be made?

**Comment by GrantMeStrength** [comment]
This is great feedback - I agree that resources like this for all Windows dev platforms would be great. I will pass this request onto the design team. I fear they are focusing on WinUI, and so this might not get a high priority in their work list. But thank you for the suggestion!
