### ISSUE TITLE
Example sources use inconsistent and confusing naming

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2069]
There are two separate things that are discussed for configuration video playback `MediaPlayerElement` and its `MediaPlayer` property.  The sample code inconsistently names things as short hand of `mpe` or `mediaPlayer` when referring to the actual `mediaPlayerElement` instance, this is confusing as some things need to use `mediaPlayerElement.MediaPlayer` instead.

The samples should be cleaned up and audited to use the proper naming of an instance so that it's clear which properties are part of the `MediaPlayerElement` class vs. extra settings on the child `MediaPlayer` property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c64813-0b24-5043-d5d6-7e62ecc84fdd
* Version Independent ID: c2020bc2-57f3-9d3d-97fb-1254dc586ef9
* Content: [Media player - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback#resize-and-stretch-video)
* Content Source: [windows-apps-src/design/controls-and-patterns/media-playback.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/media-playback.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@Austin-lamb who owns these doc pages?

**Comment by jwmsft** [comment]
Thanks for pointing this out. The page has been updated to use consistent naming.
