### ISSUE TITLE
Half of the snippets are shown in javascript and the rest in C#

### ISSUE THREAD

**Issue by Kumara-Krishnan** [MicrosoftDocs/windows-uwp#2075]
Please add option to choose the language for the snippets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be69d7e-349a-eddc-6cfa-115c2714bc3e
* Version Independent ID: 71ba81db-c429-133a-50b3-060fab53c2e6
* Content: [Background transfers - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/background-transfers)
* Content Source: [windows-apps-src/networking/background-transfers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/background-transfers.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Kumara-Krishnan, thanks for filing this issue. I'll need to put this work item onto my backlog and get to it in due course. I realize that, ideally, we'd provide every snippet in both languages, but if you could have all the snippets in JavaScript OR all of the snippets in C#, do you have a preference for which one?

Thanks!
~Steve

**Comment by Kumara-Krishnan** [comment]
I would like to see all the snippets in C#.

**Comment by stevewhims** [comment]
Thanks for the info!

**Comment by stevewhims** [comment]
Hi, @Kumara-Krishnan, thanks for the info! Sorry for the delay in working on this. I do have an internal work item, assigned to myself, to take care of this issue. So I'll go ahead and close this and circle back when the changes are live. After closing, I'll still be able to see any comments added to the issue.

Thanks again!
-Steve
