### ISSUE TITLE
Show how to bind to an IObservableMap with C++/WinRT

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/windows-uwp#2077]
I'm having trouble binding to an `IObservableMap` instead of an `IObservableVector`, which works fine.

Binding to a single element of the map with indexer syntax in XAML works fine as well, but when I try to bind to the entire collection, I get `HRESULT: 0x80070057 (E_INVALIDARG)` when the `ItemsSource` property is set on load.

The documentation is contradictory here; the `ItemsSource` [property page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.itemssource) says:
```
The ItemsSource property value must implement one of these interfaces:
IIterable<IInspectable>
IBindableIterable
```
and according to C++/WinRT headers, `IObservableMap<K, V>` implements `IIterable<IKeyValuePair<K, V>>`, where `IKeyValuePair<K, V>` is an `IInspectable`, yet it doesn't work.

On the other hand the [C++/WinRT collection docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/collections) say:
```
If you want to bind a XAML items control to your collection, then you can. 
But be aware that to correctly set the ItemsControl.ItemsSource property, you need to set it to a value of type IVector of IInspectable (or of an interoperability type such as IBindableObservableVector).
```
According to my experience so far, the C++/WinRT docs are right and the other page should be corrected.

On the other hand, I've tried doing the same with a C# Dictionary and it worked without a problem. I know the CLR is doing a lot of interop magic, but this shows me that it's indeed possible to bind to a map, so what exactly is going on there?

**Comment by stevewhims** [comment]
Hi, @Holo-Krzysztof, you're right that the solution here was an update to the [ItemsSource](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.itemscontrol.itemssource) topic. I'm waiting for my change to make its way through the publishing pipeline (when it goes live, it'll be clear about which variant of C++ it's referring to, and the info will be up to date).

I would say that your instinct about CLR interop also accounts for differences you're seeing between C# and C++/WinRT. For the product feedback, I notice that the product team is already engaged with the other issues linked above.

I'll close this issue when the doc fix is live. You can always reply to a closed issue, or even re-open it if necessary.

Thanks!
Steve

**Comment by stevewhims** [comment]
My updates are now live, so I'll go ahead and close the issue.
