### ISSUE TITLE
他人がここを見た履歴が出た

### ISSUE THREAD

**Issue by ShuhjiKaya** [MicrosoftDocs/windows-uwp#2079]
このページを見ていた時、このフィードバック書き込みのあるあたりに誰誰が閲覧したの履歴が出てその誰誰のリンクをクリックするとGitHubのページに飛びました
多分GitHubのアカウントのある人間がここを見たデータをとっているのはいいのですが、それが外部の人間にも見れる状態になっていると思います

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8731a612-b63e-55c4-b7d7-58c9e4b92448
* Version Independent ID: 1fc9f5e5-2b51-0b59-2419-ae428d98d737
* Content: [アプリのストア登録情報の作成 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/publish/create-app-store-listings#feedback)
* Content Source: [windows-apps-src/publish/create-app-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/windows-apps-src/publish/create-app-store-listings.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hello @ShuhjiKaya , Thanks for submitting your feedback. You might be seeing the list of authors, which does point to the GitHub page for the article. Let us know if you are referring to something else and if we can address this.

こんにちは@ShuhjiKaya、フィードバックをお送りいただきありがとうございます。記事のGitHubページを指している著者のリストが表示されている場合があります。あなたが他の何かを参照している場合、そしてこれに対処できるかどうかをお知らせください。

**Comment by hickeys** [comment]
Closing this as there is no actionable task and it has been inactive for 20 days.
