### ISSUE TITLE
Out of date info on referencing the .winmd

### ISSUE THREAD

**Issue by Code-ScottLe** [MicrosoftDocs/windows-uwp#2080]
Under Create a Core App section, there is a mention about this path: `\BankAccountWRC\Debug\BankAccountWRC\BankAccountWRC.winmd` , however, the latest version of VS 2019 is not giving any winmd files under such path (there is no BankAccountWRC folder under the debug folder).

![image](https://user-images.githubusercontent.com/10987612/68841142-ec636300-0678-11ea-8af7-8e91e00e00de.png)

There are 2 BankAccountWRC.winmd files however, one in Merged and one in Unmerged folder , under Debug. Which one is correct to choose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565e1bd5-9e15-fc88-8ccc-05d09cbde209
* Version Independent ID: 63b7ce5c-d2e7-d742-4fbd-b9729595a797
* Content: [Author events in C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Code-ScottLe, sorry for my delay in responding. I have the latest version of VS 2019, and I just ran through the topic steps again. I am seeing the winmd file in the expected place.

It looks like you're looking under `\BankAccountWRC\BankAccountWRC\Debug` (which does have the merged and unmerged folders there) instead of `BankAccountWRC\Debug\BankAccountWRC`.

Thanks!
Steve

**Comment by Code-ScottLe** [comment]
@stevewhims Can you please fix that to be `{projectroot}\Debug` (with `project root` being where the solution file lives) rather than just `BankAccountWRC\Debug` ? Because many people might not name their solution/project the same as BankAccountWRC (I certainly named it differently). 

In my case, the solution name was "TestWinRT" and here is my folder architecture:

![image](https://user-images.githubusercontent.com/10987612/69326486-ba19ae80-0c00-11ea-925f-26bbbf58f628.png)

**Comment by stevewhims** [comment]
Thanks, @Code-ScottLe, I've published a change with your suggestion.

I added more info around the name of the folder that contains the built `.winmd` file, both acknowledging the possibility of a different project name, while reinforcing the suggestion to use the recommended name.

I'll go ahead and close the issue now.

Thanks!
Steve
