### ISSUE TITLE
ImageUri doc is incomplete

### ISSUE THREAD

**Issue by marcpems** [MicrosoftDocs/windows-uwp#2081]
ImageUri does not define the bounds or colour space for the image.
No other documentation provides this information either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41740ef-87bc-0eb4-214a-2f847b9ad948
* Version Independent ID: 8b90529d-f872-a6a3-1089-c317dee5c005
* Content: [Toast content XML schema - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-xml-schema#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-xml-schema.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-xml-schema.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@marcpems I'm not sure exactly what you're looking to have added. Can you elaborate a little more about what you're trying to do and why you would need to know bounds and color space?

**Comment by marcpems** [comment]
Already fixed by this: https://github.com/MicrosoftDocs/windows-uwp/commit/aba9b9dfb748a29c67c54a14ee4eb077c170e7f1#diff-e3a9280c88464e762a9f31f5ee81c6bb
