### ISSUE TITLE
I feel its not quite complete.

### ISSUE THREAD

**Issue by Dmferret-code** [MicrosoftDocs/windows-uwp#2085]
As a complete newcomer I followed this excellent guide and was able to fully understand it; but for me it fell short of completion. My whole object of doing this was to end up with an app that I could transfer to any windows device and run it. At the point where this guide ends I have a .exe file but it will not run on another PC it will only run within VS. I have finally discovered that what I needed to do was to deploy it and or publish it. I strongly feel that a guide or link to how to do that would make a useful conclusion here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cf8f2c-dd46-4884-1e5c-a5014009db88
* Version Independent ID: 198bea04-c4bf-efff-c810-e6e5ef7c4bbd
* Content: [Create a Hello World app in C++/CX (Windows 10) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cpp#feedback)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thank you for your feedback.

We're in the process of revisiting our Get Started section to reflect the latest Windows Developer experience. As part of this, we also want to refine these tutorials and the messaging around them - I'll be sure to keep this in mind when I cover these, and make sure we reflect the deployment and publication steps for new devs.
