### ISSUE TITLE
How integrate uwp app into context menu of windows explorer for jpg?

### ISSUE THREAD

**Issue by mfe-** [MicrosoftDocs/windows-uwp#2088]
Short:
This is a feature request for UWP apps.

- Please make it possible when the app is not the default for the associated file type to allow context menu entries in windows explorer as well.

Please upvote here too: https://aka.ms/AA6rmrk and https://docs.microsoft.com/answers/questions/10732/how-resize-a-batch-of-pictures-just-by-marking-the.html

Long:
I repost this because UWP uservoice is closed and I was directed here:

I want to integrate my app into the windows explorer. The users should be able to select more than one image and call from the context menu the option “resize”. Therefore I created the following windows.fileTypeAssociation

    <uap:Extension Category="windows.fileTypeAssociation">
      <uap3:FileTypeAssociation Name="bla" >
        <uap2:SupportedVerbs>
          <uap3:Verb Id="Resize" Extended="false" MultiSelectModel="Player">Resize</uap3:Verb>
          <uap3:Verb Id="Edit1" Extended="false" MultiSelectModel="Player">Edit1</uap3:Verb>
        </uap2:SupportedVerbs>
        <uap:SupportedFileTypes>
          <uap:FileType>.jpg</uap:FileType>
          <uap:FileType>.txt</uap:FileType>
          <uap:FileType>.banana</uap:FileType>
          <uap:FileType>.foo</uap:FileType>
        </uap:SupportedFileTypes>
      </uap3:FileTypeAssociation>
    </uap:Extension>

If the user right clicks on a .jpg or .txt file the context menu doesn’t contain the menu items “Resize” and “Edit1”. It works for files with the extension .banana and .foo. The banana file typ extension is associated with another uwp app named bananaedit. The extension .foo is only related to my app. Why can’t I associate or integrate my context menu items with .jpg or txt filetypes when my app is not the default app to open .jpg files? 

Setting my app as default app for jpg is not an option, as I don't want to replace the photos app!
Please make it possible when the app is not the default for the associated file type to allow context menu entries in windows explorer as well.

See also: https://stackoverflow.com/questions/50664134/how-integrate-uwp-app-into-context-menu-of-windows-explorer-for-jpg
and https://docs.microsoft.com/answers/questions/10732/how-resize-a-batch-of-pictures-just-by-marking-the.html

**Comment by hkhmsft** [comment]
Hey @mfe- , thanks for reaching out with your feedback. We really appreciate your take on product improvement. I also understand that user voice was deprecated... However, you can still submit this through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app), where you can lobby for a change, a feature, or to make a suggestion like you did with this submission. I hope this helps!

**Comment by mattwojo** [comment]
Echoing the thanks for raising this issue Martin @mfe- . 

I see that you've already posted this feature request in the Windows Feedback Hub. There's one additional Q&A resource where you might try sparking some discussion on this topic: https://docs.microsoft.com/answers/topics/uwp.html  It's new within the past year and the docs platform team is feeling out whether it's useful and gets traction.. could be worth a try (?). 

I'm closing this issue as this area is specifically for docs feedback, not product feature suggestions.
~Matt
