### ISSUE TITLE
Could not find a recipe file for the reference d UWP application on desktop bridge package

### ISSUE THREAD

**Issue by pducolin** [MicrosoftDocs/windows-uwp#2090]
We recently added a desktop bridge app to our UWP solution, having an UWP package as target containing the original UWP app and the Win32 app as applications. Since then, we could not build our app from command line, so on the CI. The error we get is `Could not find a recipe file for the referenced UWP application at ''. Please build the project`. I tried [this workaround](https://stackoverflow.com/questions/51892208/uwp-with-desktop-bridge-package-build-automation-with-msbuild) with no success.

**Comment by dpaulino** [comment]
does your desktop bridge solution have a .NET standard project?

**Comment by pducolin** [comment]
Yes, you too?

**Comment by dpaulino** [comment]
Yes, me too. I had this same problem when trying to build via Visual Studio. I mitigated it by building the dotnet standard projects first, and then building the Package project.

I'm unsure how to enforce the sequence of builds in command line though. Do you know how? Perhaps that could solve your issue

**Comment by Trolldemorted** [comment]
Any updates on this? What exactly should we do to mitigate this?

**Comment by mcleanbyron** [comment]
I'm sorry you're running into this problem. Unfortunately this repo is intended for feedback on the UWP docs, not for providing technical assistance or product feedback.

Here are a few resources that may help:

* It looks like [this issue](https://github.com/microsoft/msbuild/issues/4930) in the MSBuild repo was opened to track the same problem with the product team, and it looks like someone eventually found a workaround. 
* If you're using Azure pipelines, [this article](https://docs.microsoft.com/en-us/windows/msix/desktop/azure-dev-ops) may provide useful info to you.
* Finally, if you want to post technical questions regarding building MSIX packages containing desktop apps (a.k.a. the "Desktop Bridge"), please use the [MSIX tech community](https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX).

**Comment by barnabas90** [comment]
Hi guys! I had the same issue and I found out what causes it and how to do the build right. Check the solution, at first I had the same 'recipe not found issue', then what I posted.

https://developercommunity.visualstudio.com/content/problem/891689/uwp-vs-msbuild-build-issue.html
