### ISSUE TITLE
Using Grids with Images

### ISSUE THREAD

**Issue by CpBobette** [MicrosoftDocs/windows-uwp#2091]
Images do not seem to render when inside a grid. The images will show up in the editor but not at runtime.
Using an image in a RelativePanel or on its own will work.
I am using the latest VS19 SDK.

   '''
 &lt;Grid x:Name="Grid" HorizontalAlignment="Center" Height="1060" VerticalAlignment="Center" Width="1900"&gt;
        &lt;Image x:Name="Viewer" HorizontalAlignment="Left" Height="712" Margin="10,10,0,0" VerticalAlignment="Top" Width="1890" Grid.Row="1" Source="Assets/horizontal.png"/&gt;
    &lt;/Grid&gt;
'''

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c8d6075-564f-b3f9-a8e1-44ccb515f77a
* Version Independent ID: 63e08188-34b3-3233-2b74-428de37e5960
* Content: [Layout panels for Universal Windows Platform (UWP) apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layout-panels)
* Content Source: [windows-apps-src/design/layout/layout-panels.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/layout-panels.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
It sounds like you might have a question about layout. Consider asking it on the Q&A site? (https://docs.microsoft.com/answers/topics/uwp.html)
