### ISSUE TITLE
Command line application runs from Visual Studio, but fails to run from PowerShell

### ISSUE THREAD

**Issue by panicz** [MicrosoftDocs/windows-uwp#2094]
I have been working on a command line C++ application that connects with Bluetooth Low Energy devices.

While the application works when I push the "Play" button in Visual Studio, when I try running the generated .exe file from PowerShell, it fails silently.

I recall that at some point I managed to run it from PowerShell successfully.

I also tried running it from the Command Prompt, but this only causes two pop-ups to appear, informing that the code cannot be run, because the objects MSVCP140D_APP.dll and VCRUNTIME140D_APP.dll could not be found.

Is there anything I could do to make the console app actually run from console? (Perferably from the Command Line prompt, but Powershell could also be acceptable)

**Comment by mattwojo** [comment]
Hi @panicz - I'm not sure of the answer to your question. I would recommend posting your question / issue over in the PowerShell docs repo: https://github.com/MicrosoftDocs/PowerShell-Docs/issues

Closing as I don't believe anyone on this team will have a good answer for you.
