### ISSUE TITLE
Type of field "tags" is wrong on Query for Products Collection API documentation

### ISSUE THREAD

**Issue by pavelkouril** [MicrosoftDocs/windows-uwp#2096]
The documentation states that the type of `tags` field is `string`, however the collection API returns an empty array (as can be even seen in the sample response, `"tags" : []`).

I'm sorry, I screwed up the issue submission, and now I'm not sure how to assign it for the given page. I'm talking about the https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products documentation page. Feel free to close the issue and I'll resubmit it directly through docs.microsoft.com.

**Comment by hickeys** [comment]
Just merged in this change. Thanks for the PR!
