### ISSUE TITLE
Beta Testing using Company Accounts

### ISSUE THREAD

**Issue by balanced-RedJay** [MicrosoftDocs/windows-uwp#2097]
Users with company Azure AD accounts that are in our internal testing groups and who have logged into the Windows Store using their work AD account, are unable to access our apps for testing prior to their public release. For obvious reasons, it is necessary for our internal testers to be able to access these pre-release builds. If this is possible to do, the method should be clearly documented. If it is not possible to do, this should be clearly explained in the documentation and reference the expected method for internal company access to pre-release packages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17105757-d0a7-1427-6461-0c98f1a6ffa2
* Version Independent ID: e6f704bd-5b5e-d601-81bd-c92e1301bdd8
* Content: [Package flights - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights#feedback)
* Content Source: [windows-apps-src/publish/package-flights.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/package-flights.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I believe the information you're looking for is already documented [here](https://docs.microsoft.com/en-us/windows/uwp/publish/beta-testing-and-targeted-distribution). If you still believe there is missing information after reading this, let me know what you'd like to see added.

**Comment by balanced-RedJay** [comment]
> I believe the information you're looking for is already documented [here](https://docs.microsoft.com/en-us/windows/uwp/publish/beta-testing-and-targeted-distribution). If you still believe there is missing information after reading this, let me know what you'd like to see added.

I am unable to find any reference to work/Azure AD accounts in the linked documentation. I do not believe the use-case for testing non-public builds within a corporate tenant using Microsoft "work accounts" is addressed anywhere and I am unable to find it in the linked documentation.

**Comment by Ruud-cb** [comment]
Same here, would be great to test with AD accounts.

**Comment by hickeys** [comment]
In that case, I think you're encountering a product issue and not a documentation issue. This seems more like a larger conversation and less like a GitHub issue. I'm going to close this issue and contact the store team for more information. If, after I get more clarity on this issue, there are documentation updates, I will make them. I suspect, however, that there will not be since this sounds like an issue with internal Microsoft accounts for testing.
