### ISSUE TITLE
Windows Forms "Create your first app" links to WPF walkthrough instead

### ISSUE THREAD

**Issue by kkaja123** [MicrosoftDocs/windows-uwp#2099]
The link to "Create your first app" under the Windows Forms heading links to a WPF walkthrough instead.

Links to: https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56f2824-b04c-1e07-2de1-2f78f84834d1
* Version Independent ID: b73656a9-ba3d-2411-dfca-031586aad016
* Content: [Choose your app platform](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform#feedback)
* Content Source: [hub/apps/desktop/choose-your-platform.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/choose-your-platform.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. I have fixed the link: [Choose your app platform](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform#windows-forms).
