### ISSUE TITLE
Table is not rendered in Launching and resuming apps

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/windows-uwp#2102]
Table in this article is not rendered on Microsoft Docs site, raw markdown is shown. It is rendered correctly in Github and in VS Code preview, so i'm not sure what's the reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a0a656-5e0a-e0b6-19bb-cd94a6cc1425
* Version Independent ID: b5ede982-acb9-8c82-eeca-77f750e29b74
* Content: [Launching and resuming apps (DirectX and C++) - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/gaming/launching-and-resuming-apps-directx-and-cpp)
* Content Source: [windows-apps-src/gaming/launching-and-resuming-apps-directx-and-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/launching-and-resuming-apps-directx-and-cpp.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @MSDN-WhiteKnight, thanks for finding this issue. I've published a fix now, so I'll go ahead and close the issue.

Thanks again!
Steve
