### ISSUE TITLE
Compiled data bindings - missing example

### ISSUE THREAD

**Issue by samyun** [MicrosoftDocs/windows-uwp#2104]
I was reading through this, and I noticed that in the Compiled data bindings description, it says:

"You can also use x:Bind to bind to a method, like this: For typical binding scenarios, you can use x:Bind in place of Binding, and get improved performance and maintainability."

It seems like there's a missing example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785df148-f148-9823-0266-7fd8fed8a2c6
* Version Independent ID: f4f7d0b8-ac9e-390f-1e62-1fa95ae8e019
* Content: [What's new in Windows 10 build 10240 - July 2015 - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-10240)
* Content Source: [windows-apps-src/whats-new/windows-10-build-10240.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-10240.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
That is a mistake, yes - it's an artifact of how that very first What's New page was put together.

We won't be adding an example here, but I'll go in and remove that line which suggests that one  should be there. Thanks for catching this.
