### ISSUE TITLE
InjectedInputPenInfo.Pressure generates an input with a max pressure of only 0.25

### ISSUE THREAD

**Issue by Ryken100** [MicrosoftDocs/windows-uwp#2106]
Setting the `Windows.UI.Input.Preview.Injection.InjectedInputPenInfo`.`Pressure` property to 1 generates a pen input with a pressure of 0.25. This value scales, so if `Pressure` is set to 0.5, the generated input will have a pressure of 0.125.

Setting `Pressure` above 1 seems to cause the `InputInjector` to stop generating inputs, so it's not possible to get generated pen input with pressure higher than 0.25 by setting the `Pressure` property greater than 1.

Additionally, the documentation for `InjectedInputPenInfo.Pressure` states:
> The pen contact force exerted on the digitizer surface, normalized to a range between 0 and 1024. The default is 0.

However, this is not correct, as pressure does not take values greater than 1.

**Comment by Karl-Bridge-Microsoft** [comment]
@Ryken100 - Thanks for the feedback! I've confirmed the correct value range and updated the topic.

**Comment by Ryken100** [comment]
@Karl-Bridge-Microsoft Hi Karl, thanks for the response! Unfortunately, it's a little bit ambiguous, does that mean you're updating the documentation? Or does it mean the issue where injected pen pressure is limited to only 0.25 will be fixed?

**Comment by Karl-Bridge-Microsoft** [comment]
@Ryken100 - I've updated the topic to correct the valid range for the property value. The .25 scaling of the value seems odd. I've notified the feature team of your experience. Waiting for a response.

**Comment by Ryken100** [comment]
@Karl-Bridge-Microsoft I see, thank you very much! The 0.25 scaling has been a blocking issue for me, so I'm looking forward to their response :)

**Comment by Ryken100** [comment]
@Karl-Bridge-Microsoft Did you ever hear back from the input injection team about this issue?

**Comment by HugoRomat** [comment]
Any update on this issue? 
I can still see the same problem after 3 years..

**Comment by alkeryn** [comment]
Any news on this ?
it's been years.

**Comment by Karl-Bridge-Microsoft** [comment]
There was no response from the team. I suggest you log product feedback using the "This product" button in the Feedback section of this topic.

**Comment by alkeryn** [comment]
@Karl-Bridge-Microsoft yea i just used InjectSyntheticPointerInput from the win32 api instead.
it does suck that we use screen resolution for position (as tablets have a much higher dpi) and pressure levels are capped at 1024.
so i'm just gonna use it as a fallback if users don't install a more precise driver.

**Comment by Karl-Bridge-Microsoft** [comment]
Your follow up is much appreciated! I've pinged the team again, but you might wait another few years so wanted to at least point you to a resource that might help. If there any gaps in the documentation that you feel need to be addressed, please open another Issue (or PR) with as many specifics as possible. Thanks!

**Comment by alkeryn** [comment]
Hey, any news on this ?
it has been another few years lol
