### ISSUE TITLE
リンクがおかしい

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2111]
[フィードバックをこちらに入力してください]
「適切なコントロールの選択」の「例」の項目で、リンクが「アプリを開き、NavigationView の動作を確認」に設定されているのがおかしいと思う。
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e69449df-a1ec-70dd-e563-0ad508733c47
* Version Independent ID: dc0e0acb-d92a-a039-5c16-f54a4b71d954
* Content: [ナビゲーション ビュー - UWP apps](https://docs.microsoft.com/ja-jp/windows/uwp/design/controls-and-patterns/navigationview#is-this-the-right-control)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
The machine translated question was: "I think it's strange that the link is set to "Open app and check NavigationView behavior" in the "Example" section of "Select the right control"."

And this page seems right to me so ... I don't understand what is confusing/strange.
