### ISSUE TITLE
Although the Desktop Bridge can help bring existing (Win32) desktop apps to Windows 10 and the Microsoft Store, it cannot create apps that run on HoloLens or in Mixed Reality at this time

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/windows-uwp#2112]
Starting from Windows 10 version 1903, Desktop Apps (Win32) can run on Mixed Reality headsets but not HoloLens.

Please update this article the reflect this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a3a77-0b4b-387c-fe07-1c13c1bbd2d0
* Version Independent ID: 7fbaf386-4594-d23c-d360-30a5816c36c4
* Content: [Designing for Mixed Reality - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-mr#feedback)
* Content Source: [windows-apps-src/design/devices/designing-for-MR.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/devices/designing-for-MR.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I just checked in a change to reflect your comment. Should be published in the next docs build/publish.
