### ISSUE TITLE
翻訳で -A が消失

### ISSUE THREAD

**Issue by ufcpp** [MicrosoftDocs/windows-uwp#2115]
翻訳で `-A Api` の `A` が消えてる。おそらく不定冠詞扱いされている。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8a28119a-77f2-160c-a4f1-f90ef9153423
* Version Independent ID: 28b24e82-f0ef-cceb-2136-f8dbfabfcadc
* Content: [Windows UTF-8 コードページを使用する - UWP apps](https://docs.microsoft.com/ja-jp/windows/uwp/design/globalizing/use-utf8-code-page)
* Content Source: [windows-apps-src/design/globalizing/use-utf8-code-page.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/windows-apps-src/design/globalizing/use-utf8-code-page.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by nokura** [comment]
@DavidPrio please move this feedback to Japanese repo and fix it. We have to restore "A" in -A, which might be removed as it is mistakenly regarded as Indefinite article.  

Current: "Unicode"-W のバリエーションを Api 経由で強調してきました。
Change to: "Unicode"-W のバリエーションを -A Api 経由で強調してきました。

Current:  Api は UTF-8 で動作します。
Change to: -A Api は UTF-8 で動作します。

**Comment by ufcpp** [comment]
Don't you have any annotations/mark-ups like "`-A`" instead of "-A"? This kind of machine translation is very difficult without annotations.

**Comment by ufcpp** [comment]
If possible, I'd like to feedback translation issues directly from [the content page](https://docs.microsoft.com/ja-jp/windows/uwp/design/globalizing/use-utf8-code-page) to [the ja-jp repository](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/)

**Comment by ufcpp** [comment]
Feedback link under `Windows-uwp` is the original repository:

![image](https://user-images.githubusercontent.com/3760955/70107632-5f656580-168a-11ea-929d-b40e8757b212.png)

On the other hand, that under `docs` is the translation repository:

![image](https://user-images.githubusercontent.com/3760955/70107598-4957a500-168a-11ea-8e80-bd8071e09c05.png)

**Comment by DavidPrio** [comment]
> 
> 
> @DavidPrio please move this feedback to Japanese repo and fix it. We have to restore "A" in -A, which might be removed as it is mistakenly regarded as Indefinite article.
> 
> Current: "Unicode"-W のバリエーションを Api 経由で強調してきました。
> Change to: "Unicode"-W のバリエーションを -A Api 経由で強調してきました。
> 
> Current: Api は UTF-8 で動作します。
> Change to: -A Api は UTF-8 で動作します。

@nokura In order for our system to pick this up, the ticket needs to be assigned to my account. Unfortunately, I don't have rights to do it myself. Can you please take care of that? Thanks!
@CeciAc @SunnyDeng @Gonzalo-Salines FYI

**Comment by CeciAc** [comment]
Hi @nokura 
I moved this manually here: https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/102
you can close this issue, will work it from there

**Comment by Karl-Bridge-Microsoft** [comment]
Closing as requested.
