### ISSUE TITLE
Static UI elements

### ISSUE THREAD

**Issue by Aaron216** [MicrosoftDocs/windows-uwp#2116]
The paragraph stating that "In some cases, there are UI elements that should stay on the screen the entire time. Design the UI so that the form controls are contained in a panning region and the important UI elements are static." does not tell the reader how this can be achieved. Is there a parameter that can be used in XAML that causes elements to resize when the keyboard appears, or must it be done programmatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd52e375-ff83-a6f0-aa09-f94682e661d0
* Version Independent ID: b74138f8-8401-04ae-b8b7-0643a7c9ba02
* Content: [Respond to the presence of the touch keyboard - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/input/respond-to-the-presence-of-the-touch-keyboard#feedback)
* Content Source: [windows-apps-src/design/input/respond-to-the-presence-of-the-touch-keyboard.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/respond-to-the-presence-of-the-touch-keyboard.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Aaron216 

The recommendation is for the panning region to resize based on the appearance of the touch keyboard. This must be done programmatically as stated in the previous paragraph:

*When customizing your UI, provide similar behavior on the appearance of the touch keyboard by handling the Showing and Hiding events exposed by the InputPane object.*
