### ISSUE TITLE
Missing URI setting for privacy-speech

### ISSUE THREAD

**Issue by kcicc** [MicrosoftDocs/windows-uwp#2119]
The URI for "privacy-speech" is missing from the documentation. 

Allows option for online speech recognition on/off

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @kcicc, can you provide more detail? Which topic are you referring to?

**Comment by kcicc** [comment]
in the list of URI settings for the group policy "settings page visibility" the documentation is missing the one called "privacy-speech". We have some locked down computers that are used for Exams that needed dictation available to them. 

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#ms-settings-uri-scheme-reference

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @kcicc - the topic has been updated as requested.
