### ISSUE TITLE
rescap does not work

### ISSUE THREAD

**Issue by dlatikaynen** [MicrosoftDocs/windows-uwp#2121]
When I add the parts to appmanifest.xml as indicated in the sample (additional namespace, additional ignorablenamespace, and the prefixed capability tag itself), then I get a compilation error "The element Capabilities in namespace... has invalid child element Capability... &lt;drones on for 10 more lines&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b665f33-4a40-510a-86d3-019ba9c79c44
* Version Independent ID: df96e262-813d-9143-9d91-a29c49a01b4f
* Content: [File access permissions - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions#feedback)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @dlatikaynen , thanks for pointing this out and providing feedback. I'll go ahead and take a look and troubleshoot the code sample. Once this is resolved, look forward to updates on this thread.

**Comment by ArchieCoder** [comment]
There was a regression. Remove uap5 from the namespace and it will compile.
