### ISSUE TITLE
inputObservation/inputSuppression totally undocumented

### ISSUE THREAD

**Issue by RosDevil** [MicrosoftDocs/windows-uwp#2123]
inputObservation/inputSuppression capabilities are impossible to implement. There isn't any reference to the classes involved in these topics.
You never get access to inputs (keyboard, mouse...) outside your window, no matter what.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for providing your feedback. The product team confirmed that these capabilities (and the APIs they govern) are only supported for use by certain Microsoft partners, and as such are not supported for use by general developers. However, we do include the capabilities in the public documentation for completeness. I added a note to the capability descriptions to clarify the scenario.
