### ISSUE TITLE
There is no way to use "broadFileSystemAccess".

### ISSUE THREAD

**Issue by DkmS1953** [MicrosoftDocs/windows-uwp#2124]
The MS Store returns the app without a clear explanation of the reasons and with the requirement to remove broadFileSystemAccess from the application's manifest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b665f33-4a40-510a-86d3-019ba9c79c44
* Version Independent ID: df96e262-813d-9143-9d91-a29c49a01b4f
* Content: [File access permissions - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions#feedback)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @DkmS1953 , thanks for bringing attention to this. I'll go ahead and investigate and make some necessary changes. I'll keep this thread open for updates.

**Comment by ArchieCoder** [comment]
In order to be allowed to have this capability, you need to contact the Support team. Not every app can have this capability.

@lastnameholiu what did happen with the follow-up on the 2 tickets from the same doc page?

**Comment by DkmS1953** [comment]
Tech support can't clearly explain why not every app  can have this
capability.
Kindergarten, not an app store.

Wbr, Dyakov K.M.



сб, 11 апр. 2020 г. в 06:18, ArchieCoder <notifications@github.com>:

**Comment by ArchieCoder** [comment]
@DkmS1953 When an app goes to the Microsoft App Store it has to give trust to customers. Since the capability of broadFileSystemAccess gives the freedom to modify 99% of the files on the system, it opens a door for malicious devs to do bad things.

Microsoft certification team checks the nature of the app before allowing an app with this capability.

I'm surprised that the tech support could not explain this.

**Comment by DkmS1953** [comment]
All described was done, but permission to place the program in the store
was not given. There was no explanation as to why my program could not use
broadFileSystemAccess.
All I wanted was a text-based data file processing protocol in the same
folder as the file itself. 😢

Wbr, Dyakov K.M.



вт, 14 апр. 2020 г. в 03:50, ArchieCoder <notifications@github.com>:

**Comment by ArchieCoder** [comment]
@DkmS1953 could you paste the message you received from Microsoft? I will follow-up with them.

**Comment by DkmS1953** [comment]
In attachment - all our correspondence about this.
As a result, I spat and did so, as I personally uncomfortable.

Wbr, Dyakov K.M.



ср, 15 апр. 2020 г. в 00:30, ArchieCoder <notifications@github.com>:

**Comment by ArchieCoder** [comment]
@dkluemke The attachment didn't went thru. You can contact me at sebastien.lachance AT hotmail.com

**Comment by hkhmsft** [comment]
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. For support related issues, your best bet is over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). Thanks once again for submitting your feedback!
