### ISSUE TITLE
Is recurrenceId unique?

### ISSUE THREAD

**Issue by pnico** [MicrosoftDocs/windows-uwp#2126]
Regarding the "id" field here in the returned data for an item, which is also used as 'recurrenceId' when changing the billing state of a subscription: https://docs.microsoft.com/en-us/windows/uwp/monetize/change-the-billing-state-of-a-subscription-for-a-user

Is this id unique across all subscriptions for an app? For example, can we safely use this value to uniquely identify a particular subscription for a particular user across all subscriptions for all users (including, say, if there are actually two different subscription addons associated with our app, one with a free trial and one without) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9625f407-7adf-256d-fa24-2d96c7c86f51
* Version Independent ID: 07159310-27c7-3eb2-761f-42798740c9a1
* Content: [Get subscriptions for a user - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-subscriptions-for-a-user)
* Content Source: [windows-apps-src/monetize/get-subscriptions-for-a-user.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-subscriptions-for-a-user.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I'm not sure I understand your question. To confirm, you'd like to know if each individual subscription in an app has a unique id. That is, a particular subscription id maps to exactly one user and one "type" of subscription (e.g. annual vs monthly, standard vs pro, etc.). Is that correct?

**Comment by hickeys** [comment]
As there has been no response on this issue, I'm going to close it. Feel free to re-open and clarify your question.

**Comment by pnico** [comment]
I would like to know if a subscription id is unique, correct. For example, if it is safe to assume that if two different users (with different StoreIds) have a subscription to the same or different item, is it 100% guaranteed that the subscription ids returned here will never be identical. I was asking this question while implementing this feature, to verify I was doing it correctly. When you answered this, 10 months later, I was already on to other things. However, I have now encountered a case in which two users, with different StoreIds, are apparently sharing the same subscription with the same subscription IDs (different value for "beneficiary" yet all other fields are the same including "id"). It was my assumption that this is not supposed to happen, but this is probably the kind of thing I was worried about when I filed this ticket over 2 years ago, and without an answer I guess I just had to go with that assumption.

Since I feel my original question should still be answered (and ideally, the docs for this feature should clarify this so others don't need to ask), please reopen this ticket. I'm not actually sure I understand what your re-worded version of my question would be asking, but sure, answer that one :) anything would help at this point. I will also open a new ticket, describing the behavior I am now seeing with the duplicate subscription for different users/StoreIds.

**Comment by pnico** [comment]
After looking at this new issue more, with the duplicate ids, I believe they are the same subscription - but the user was allowed to "purchase" it twice in the app with differing storeIds (using different beneficiary ids as different user ids in our app). This is not what I would expect - this could allow many users to share subscriptions with each other and only pay once, which is generally something that you don't want in a subscription service. This means including the user id in the store id is meaningless, and we can't really trust it.

But back to the initial question: please re-open this ticket, so I don't have to open a duplicate one. Thanks!
