### ISSUE TITLE
Undocumented asset image MaximumFileSize limitation

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/windows-uwp#2129]
There is a practical file size limitation of 200k applied to asset images by _ValidateAppxPackage target, see https://developercommunity.visualstudio.com/content/problem/650470/icon-size-problem.html for example
This limitation is documented in older https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh781198%28v=win.10%29?#general-image-requirements
but is not mentioned in this here article for UWP / Win10.

There is a possibility that this is not a documentation error, but rather an irrelevant check wrongly inherited from prevous versions of tools, because:
1. Asset images produced by the official Asset Generator in Manifest Designer are reported as "faulty" the same
2. Scaled varieties of assets do by design go up to 1240x1240px @ 32bpp, and can easily have a file size of 1mb+
i.e. there is nothing wrong with the image files, they are just naturally large. With compression format, dimensions and bit depth all locked, there isn't much anyone could possibly do to "fix" this error.
At any rate, this calls for further investigaton and coordination inside Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287ed7e0-5cbc-bf87-360c-5c5a47b451d0
* Version Independent ID: 87cd355a-d27b-47cc-1be5-951653cf52f1
* Content: [App icons and logos - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos)
* Content Source: [windows-apps-src/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/app-icons-and-logos.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
There is no such limit for UWP applications. The link you reference is obviously encountering a limit, but I think you're correct that it's "an irrelevant check wrongly inherited from previous versions of tools."

In this case, the documentation is correct, but there is a product bug. Usually I'd direct you to the bug reporting site, but here the bug has already been reported. Because the documentation is correct,  and the bug has been reported, I'm going to close this issue.

**Comment by avakhrushev** [comment]
@hickeys Where can I see the bug report you are talking about?
If you mean the discussion I linked to, it has been waved off and closed then already. Which is why this report been created.
