### ISSUE TITLE
Article lacks context / introduction

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/windows-uwp#2130]
It starts "The Packages page is where you upload..." , but what is the Packages page; page of what? Next section similarly speaks of "upload field", as if some particular tool or web interface is being described, but it is never actually explained anywhere in the article.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a172fd27-14e7-d680-cb42-809f407acd16
* Version Independent ID: 9f263fd7-570b-efc3-5eab-7e4de037ad0d
* Content: [Upload app packages - UWP apps](https://docs.microsoft.com/en-au/windows/uwp/publish/upload-app-packages#uploading-packages-to-your-submission)
* Content Source: [windows-apps-src/publish/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/upload-app-packages.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for opening this issue. This page is meant to be a part of a larger series that walks a user through the process of opening a Partner Center account, creating an app entry in the store, uploading the app, setting the price, and getting paid when a user downloads the app. That said, you're spot on that this page, viewed on its own, offers no context about where it fits in that larger process. I've made a small change to indicate the context. It should be published in the next docs build.
