### ISSUE TITLE
Adding a control from WinUI library to a UWP custom control gives 'Catastrophic failure' compile error.

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/windows-uwp#2133]
**Environment**: Windows 10 Pro ver. 1903, VS2019 - Version 16.4.1

All steps in tutorial: [Host a custom UWP control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands) work fine except step 6 of the section [Add a control from the WinUI library to the custom control](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands#add-a-control-from-the-winui-library-to-the-custom-control).
Step 6 reads: `Build and run your app and confirm that the new rating control displays as expected.` But when you do that you get the following **error**: 

> &gt;&gt;Error	XDG0062	Catastrophic failure
> WindowsXamlManager and DesktopWindowXamlSource are supported for apps targeting Windows version 10.0.18226.0 and later.  Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7ec471-9257-39ba-173b-eb7973f4c360
* Version Independent ID: 3e07d5f0-8b19-2ef4-dc2a-48659f42c12e
* Content: [Host a custom UWP control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands#add-a-control-from-the-winui-library-to-the-custom-control)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I am not able to reproduce this behavior when testing the steps in the article. Do your projects target Windows 10 version 1903 or later as specified by the instructions?
