### ISSUE TITLE
x:Key vs x:Name

### ISSUE THREAD

**Issue by ThomasPe** [MicrosoftDocs/windows-uwp#2135]
Are the code samples here still correct, setting x:Key for VisualState instead of x:Name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cef1216-cac2-23c6-b76e-d1e4b565f508
* Version Independent ID: 6f27fa70-da48-85e6-ce25-b50bf8b4c309
* Content: [Create adaptive layouts tutorial - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-adaptive-layout#feedback)
* Content Source: [windows-apps-src/design/basics/xaml-basics-adaptive-layout.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-adaptive-layout.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
You're right; x:Key is for dictionaries, and VisualStateGroup.States isn't a dictionary.

**Comment by jwmsft** [comment]
Fixed
