### ISSUE TITLE
Wrong title "Drag and drop"

### ISSUE THREAD

**Issue by JeremyJeanson** [MicrosoftDocs/windows-uwp#2137]
The title "Drag and drop" is wrong.

I think it should be "Set content".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed70f5b-8ede-03e4-fe8d-15f710288dd9
* Version Independent ID: a1225888-45e3-f2f6-bfe2-ab679fec7953
* Content: [Copy and paste - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/copy-and-paste?source=docs)
* Content Source: [windows-apps-src/app-to-app/copy-and-paste.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-to-app/copy-and-paste.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I have updated this heading to "Set the copied content".
