### ISSUE TITLE
"See UserVoice" link should not be there anymore

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#2138]
Microsoft WinDev took down the UserVoice channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48168c03-36df-a7cb-baeb-49bd31589260
* Version Independent ID: 7a17333c-9eee-d327-73aa-49fdbc2f4de2
* Content: [Extend your app with Windows UI and components](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extend)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-extend.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extend.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for notifying us of this issue. I removed the obsolete UserVoice link from this and other articles in the same section. The standard Product Feedback link at the bottom of each article is correct.
