### ISSUE TITLE
no New button in VS2019

### ISSUE THREAD

**Issue by OZ1** [MicrosoftDocs/windows-uwp#2140]
There is no New button next to DataContext property for Page element in Visual Studio 2019

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 64d8500f-a77e-00eb-c179-b72209f25949
* Version Independent ID: f4b970f5-af50-d626-68de-2c8b39140687
* Content: [Демонстрационные данные в рабочей области конструирования и демонстрационные данные для создания прототипов - UWP apps](https://docs.microsoft.com/ru-ru/windows/uwp/data-binding/displaying-data-in-the-designer)
* Content Source: [windows-apps-src/data-binding/displaying-data-in-the-designer.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/windows-apps-src/data-binding/displaying-data-in-the-designer.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by QuinnRadich** [comment]
Apologies for letting this issue stand for some time.

I've made the necessary changes to this page to account for differences in user experience, and to clarify steps for Visual Studio 2019.

Thank you.
