### ISSUE TITLE
An adjustment to the instruction.

### ISSUE THREAD

**Issue by shmohajerani** [MicrosoftDocs/windows-uwp#2144]
I believe this must be added to the instruction on this page:
For a .Net Standard Lib to access app folders and assets files of UWP app, you need to mark it as "EmbeddedResource" and "Copy Always" in its properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by QuinnRadich** [comment]
Thanks for the information. I've updated the docs with a note containing this information.
