### ISSUE TITLE
Scale factors for UWP apps are restricted and need to be documented

### ISSUE THREAD

**Issue by marcpems** [MicrosoftDocs/windows-uwp#2145]
windows-uwp/windows-apps-src/app-resources/tailor-resources-lang-scale-contrast.md

The range of asset scale values that can be provided to MakeAppX for a UWP app is limited to 100, 125, 150, 200, 250, 300, 400 and 500. 

There is no other documentation to describe this limitation, and because of this doc https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Display.ResolutionScale
there is partner confusion.

The request is to add the above text (or equivalent).

**Comment by hkhmsft** [comment]
Hi @marcpems , thanks for bringing this to our attention. Before I go ahead and create a Pull Request, you'd like to see this note on [Windows.Graphics.Display.ResolutionScale](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Display.ResolutionScale)'s Remark [section](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Display.ResolutionScale#remarks)? Or rather, on the [scale](https://docs.microsoft.com/en-us/windows/uwp/app-resources/tailor-resources-lang-scale-contrast#scale) subsection of the [Tailor your resources for language, scale, high contrast, and other qualifiers](https://docs.microsoft.com/en-us/windows/uwp/app-resources/tailor-resources-lang-scale-contrast)? 

Let me know.

**Comment by hkhmsft** [comment]
Changes have been added and pending our build systems, should be live shortly.
