### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by wjvelasquez** [MicrosoftDocs/windows-uwp#2146]
Frame rootFrame = Window.Current.Content;

Eso genera un error. De donde se puede descargar este proyecto completo para ver si de verdad funciona?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3db3df4b-39b3-74ae-6cea-ffe2b3f52df3
* Version Independent ID: f75fe3ae-e7ed-1441-3cc5-5c59bf9cbde2
* Content: [Historial de navegación y navegación hacia atrás - UWP apps](https://docs.microsoft.com/es-es/windows/uwp/design/basics/navigation-history-and-backwards-navigation#optimizing-for-different-device-and-form-factors)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp.es-es/blob/live/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This code example has been fixed. Sorry for the inconvenience. The line should be 
`Frame rootFrame = Window.Current.Content as Frame;`.
