### ISSUE TITLE
Update instructions on how to use SQLite in UWP apps

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2154]
Since the walkthrough in [Getting started with EF Core on Universal Windows Platform (UWP) with a New Database](https://docs.microsoft.com/ef/core/get-started/uwp/getting-started) isn't available anymore, this is the only official documentation on how to use SQLite with a UWP app.

These instructions, however, doesn't work. Since the `DataAccessLibrary` is a .NET Standard project, it can't use `Windows.Storage`namespace, used in `InitializeDatabase()` method and others. In this way, the project does not compile, making the entire process unsuccessful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#set-up-your-solution-to-use-the-microsoftdatasqlite-library)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by ghost** [comment]
I have found how to use this walkthough to use SQLite in UWP:

1. Forget create a .NET Standard project in your solution.
1. Install `Microsoft.Data.SQLite.Core` and `SQLitePCLRaw.bundle_winsqlite3` packages.
1. Create `DataAccess` class file wherever is convenient and insert on it the code in the walkthrough.
1. Call `DataAccess.InitializeDatabase()` method in `App.xaml.cs` constructor.
1. Modify `MainPage.xaml` to use your database as in the walkthough.
1. Hit `F5` and see the sun shining upon you again.

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
