### ISSUE TITLE
Please, please set the size for the character images on this page

### ISSUE THREAD

**Issue by ReflexiveCode** [MicrosoftDocs/windows-uwp#2157]
Currently, scrolling while images are loading results in terrible jumping.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The width and height are already set. It may be that this issue was fixed between the time you opened the image and now. I'm going to close this. If it continues to be a problem, please reopen and I'll investigate more.
