### ISSUE TITLE
Glyph Icons randomly 404'ing

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/windows-uwp#2159]
this page has many small icons and a random number of them are 404'ing
https://docs.microsoft.com/en-us/windows/uwp/design/style/images/segoe-mdl/f847.png
works
but when loading this page and waiting for it to download it timesout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 icon guidelines - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
There isn't much I can do about this. This page displays all of the Segoe MDL2 Icons, so there are going to be a lot of images that need to be loaded. I'm sorry your connection is timing out. Perhaps you can view the glyphs in some alternate way, such as using character map?
