### ISSUE TITLE
Finish button does not work in Ukraine

### ISSUE THREAD

**Issue by stremovskyy** [MicrosoftDocs/windows-uwp#2160]
"Select Finish to confirm your registration. Your payment will be processed and we'll send a confirmation message to your email address."
NOT WORKING IN UKRAINE FROM ANY COMPUTER!!!!!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4ddd610-d6de-7a7c-2d59-fdc08dd98371
* Version Independent ID: 1ed74795-fa40-80a5-4fc2-6f4e87efa594
* Content: [Opening a developer account - UWP apps](https://docs.microsoft.com/en-gb/windows/uwp/publish/opening-a-developer-account#feedback)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by abler98** [comment]
I have the same problem

**Comment by tsenekov** [comment]
Same problem from Russia. Even from androoid devices.

**Comment by orlax** [comment]
Same problem, I developed a small uwp app and now looking to distribute it to beta testers, but the form for the partner center is not working, it charges my creditcard the 1 usd verification fee each time I try but the final submit button does not get activated. 

I tried to just remove the disabled label and clicked anyways but them it complains about the checkWithPS2 function not existing. 

I am in colombia.

**Comment by aaddnik** [comment]
I have the same problem in Russia.

**Comment by orlax** [comment]
> Same problem, I developed a small uwp app and now looking to distribute it to beta testers, but the form for the partner center is not working, it charges my creditcard the 1 usd verification fee each time I try but the final submit button does not get activated.
> 
> I tried to just remove the disabled label and clicked anyways but them it complains about the checkWithPS2 function not existing.
> 
> I am in colombia.

just tried again using firefox (was using google chrome before) the problem persists. 


I ended up just porting my application to html/js with electron, it really sucks that even if we want to pay to be able to distribute using the windows store, you are unable to. So yeah, very frustrated about that. You should not be dropping the ball like this.

**Comment by specinov-antoine** [comment]
Hello, we have the same problem in France to create an Enterprise account.
Please keep us inform

**Comment by akumagamo** [comment]
Seems to be a Problem with the language. I change the language of my Browser(chrome) to US and in My MS account and it worked. Hint I saw in the Browser Console the error Message : "expected number" but the number had a comma "16,000", not a dot "16.000" (for the decimals), in the Javascript.  Hope this helps.

**Comment by tsenekov** [comment]
It's worked! I change regional settings (set a dot) and go to: https://partner.microsoft.com/en-us/

**Comment by stremovskyy** [comment]
> Seems to be a Problem with the language. I change the language of my Browser(chrome) to US and in My MS account and it worked. Hint I saw in the Browser Console the error Message : "expected number" but the number had a comma "16,000", not a dot "16.000" (for the decimals), in the Javascript. Hope this helps.

THX man!!!!

**Comment by wdk0294** [comment]
I need help, when I want to buy a subscription in Microsoft Partner Center it throws the following error: Error code 6168.
Please try a different payment method. Note: Prepaid cards are not accepted.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
