### ISSUE TITLE
Czech Republic is now Czechia

### ISSUE THREAD

**Issue by MicrosoftComments** [MicrosoftDocs/windows-uwp#2166]
I mean, officially it has been for years but in the actual Partner Center options it now appears as 'Czechia', not 'Czech Republic' as listed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379c0973-6812-4fc7-d53c-9383fb1e44c6
* Version Independent ID: 3a7d1d55-bb6f-3545-73af-01aee1c69f07
* Content: [Define market selection - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/define-market-selection?redirectedfrom=MSDN#feedback)
* Content Source: [windows-apps-src/publish/define-market-selection.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/define-market-selection.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by bartlannoeye** [comment]
![Capture](https://user-images.githubusercontent.com/5115577/78587067-b8adf300-783c-11ea-9377-afea0e4ddbce.PNG)

@hickeys confirmed that Microsoft Partner Center uses Czechia as issue describes.

According to the [UN country name list](https://unterm.un.org/unterm/Display/record/UNHQ/NA?Id=4275087d-4018-4082-899d-95f37efeda65) it's either "**the** Czech Republic" (long) or "Czechia" (short).
According to [PCGN](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/554812/Czechia_Information_Paper-Updated_September_2016.pdf) the short name should indeed be used as of April 2016.

Will send a PR to correct all instances.
