### ISSUE TITLE
Page shows HTML entities: non desired characters

### ISSUE THREAD

**Issue by shogerr** [MicrosoftDocs/windows-uwp#2167]
Looks like the metadata for the doc got lost.
page is https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development

It looks like we have an encoding issue on this page. One offending example below, where `&gt;` has not been decoded to `>`.
```
To enable developer mode, run this command:

PS C:\\WINDOWS\\system32&gt; reg add "HKEY\_LOCAL\_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock" /t REG\_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
```
It also looks like something funky is going on with escaping backslashes. Maybe this could be updated to use `New-ItemProperty` or similar:
```
New-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock -Name AllowDevelopmentWithoutDevLicense -PropertyType DWORD -Value "1" -Force
```

**Comment by QuinnRadich** [comment]
Apologies for the late response on this issue. The encoding problem was solved a while ago, but this issue was never closed. Thanks for letting us know about it.
