### ISSUE TITLE
PowerToys Suggestion

### ISSUE THREAD

**Issue by jt-github** [MicrosoftDocs/windows-uwp#2171]
It would be so awesome (if not necessarily easy to code) to be able to pick and choose areas of ANY application that you wanted to make acrylic.  For instance, you could "acrylicize" Outlook so that everything but the list of messages and the message frame was wonderfully transparent with a blurred background to help focus the user on what matters (just the next evolution from using the dark theme with it).  Such a PowerToy would allow selecting an app, then choosing one or more areas to modify, and then remember those changes across application close/open and system restarts, of course.  Extra credit for an option to let the desktop background "shine through" to the top application (rather than showing underlying windows as would be the default).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9faf87c-bd56-99da-70ed-07c68f9118a5
* Version Independent ID: 713b5c24-d710-303f-620e-9c7735797907
* Content: [Acrylic material - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#feedback)
* Content Source: [windows-apps-src/design/style/acrylic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/acrylic.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by crutkas** [comment]
Great suggestion, can you file that against the PowerToy repo?  https://github.com/microsoft/PowerToys

**Comment by GrantMeStrength** [comment]
Clint Rutkas would be very grateful if this could be re-created in https://github.com/microsoft/PowerToys

**Comment by hickeys** [comment]
I see that this was created in the PowerToys repo. Closing this issue since it's not needed anymore.
