### ISSUE TITLE
Article date is wrong

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/windows-uwp#2175]
This page received important updates after the listed 10/17/2018 date https://github.com/MicrosoftDocs/windows-uwp/commits/docs/windows-apps-src/publish/payment-thresholds-methods-and-timeframes.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801e8a2c-1bc7-1abc-3c36-de1da74eb77b
* Version Independent ID: 2482d516-3b32-3068-a038-ccdc3f94d7fb
* Content: [Payment thresholds, methods, and timeframes - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/payment-thresholds-methods-and-timeframes)
* Content Source: [windows-apps-src/publish/payment-thresholds-methods-and-timeframes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payment-thresholds-methods-and-timeframes.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks. The changes you refer to appear in that article, but you're correct that the date was never updated. I've just merged in a change to the correct date, it should be published shortly.
