### ISSUE TITLE
Mouse Cursor always captured

### ISSUE THREAD

**Issue by jtg-gg** [MicrosoftDocs/windows-uwp#2176]
Sorry for asking this again. We've just released our app to public, and our customers asking about this mouse cursor issue. 
It will be great if the API can have parameter / option to disable the mouse cursor capture

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - UWP applications](https://docs.microsoft.com/en-sg/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by jtg-gg** [comment]
According to this https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/
There is an api IsCursorEnabled, but I can't find any documentation about this api

**Comment by drewbatgit** [comment]
The new isCursorEnabled API is a part of the Windows 10 April 2020 Update. But you can go ahead and experiment with the API by downloading the lastest [Windows SDK Insider Preview](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK). You won't be able to submit apps that use the API to the store until the April Update is released.
