### ISSUE TITLE
Step 4 of 'Package the app' section breaks the build

### ISSUE THREAD

**Issue by r2d2rigo** [MicrosoftDocs/windows-uwp#2183]
Project info:
- WPF app using .NET Core 3.1.
- Using the latest XAML Islands libraries (Microsoft.Toolkit.Wpf.UI.XamlHost/Microsoft.Toolkit.Win32.UI.XamlApplication 6.0.0).
- Packaged as MSIX.

By changing the splash screen as indicated by the instructions, the build breaks with the following error message:
`Error APPX0703: Manifest references file 'Images\SplashScreen.scale-200.png' which is not part of the payload.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7ec471-9257-39ba-173b-eb7973f4c360
* Version Independent ID: 3e07d5f0-8b19-2ef4-dc2a-48659f42c12e
* Content: [Host a custom UWP control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands#package-the-app)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this. I wasn't able to reproduce the error you're seeing, but I went ahead and removed the instruction to change the splash screen image file name in the manifest anyways. This was a workaround for an issue that no longer seems to be necessary with the latest versions of the NuGet packages.
