### ISSUE TITLE
Toast Does Not Persist

### ISSUE THREAD

**Issue by mltf** [MicrosoftDocs/windows-uwp#2184]
This is required for your toast to persist in Action Center (since the toast could be clicked days later when your app is closed)

This statement doesn't seem to be true.  

Downloaded the C# code from: https://github.com/WindowsNotifications/desktop-toasts 
Rebuild the application
Ran the application and clicked "Pop toast"
Checked the action center, say after 10 seconds.  
Toast doesn't persist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Send a local toast notification from desktop C# apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by hickeys** [comment]
I don't see the referenced text in the article. Between that and this issues age, I'm going to close this. It seems the issue was fixed already. If I'm incorrect, please re-open and point me to the correct page.
