### ISSUE TITLE
rvalues alone are do not solve the forwarding problem as implied.

### ISSUE THREAD

**Issue by kurt-krueckeberg** [MicrosoftDocs/windows-uwp#2185]
"This section introduces the syntax for a reference to an rvalue. We'll have to wait for another topic to go into a substantial treatment of moving and forwarding, but those are problems that are solved by rvalue references. "

Not to quibble or split hair too much, but...rvalues are only _part_ of the solution to forwarding. Without forwarding references that can bind to both rvalues of lvalues, rvalues alone don't solve the forwarding problem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339317c-7463-d28c-c34e-b1f20791bcdf
* Version Independent ID: acb6ecae-3986-b31a-53f5-875367c2f855
* Content: [Value categories, and references to them - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/cpp-value-categories#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/cpp-value-categories.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/cpp-value-categories.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kurt-krueckeberg, thanks for the clarification. I've published a fix to that sentence now. I'll go ahead and close this issue, but you can still reply (and re-open, if necessary).

-Steve
