### ISSUE TITLE
Official Country/Region List link leads to none-running website

### ISSUE THREAD

**Issue by riesm** [MicrosoftDocs/windows-uwp#2187]
The link to https://globalready.azurewebsites.net/marketreadiness/OfficialCountryregion does work, however, the website is stopped and not accepting any requests. Please fix that or change the link to a functional website.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f1d9ea9-447b-dc45-bad2-92e6ddb67529
* Version Independent ID: 9a5afa79-8c8f-02ba-d39c-bf05a3a06ac8
* Content: [Understand user profile languages and app manifest languages - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/manage-language-and-region#feedback)
* Content Source: [windows-apps-src/design/globalizing/manage-language-and-region.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/manage-language-and-region.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by riesm** [comment]
This link for instance would be great: https://docs.microsoft.com/en-us/windows/uwp/publish/supported-languages

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @riesm - the topic has been updated.
