### ISSUE TITLE
Add info about TabView

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2190]
Looks like the link to the [TabView guidance](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tab-view) is missing from the navigation options.

Additional: [TabView API link](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.tabview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054a2d98-05ac-9f54-de84-3e7e14e1269d
* Version Independent ID: 7302ceaf-a1aa-0427-2233-5a7237aff043
* Content: [Navigation basics for UWP apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-basics)
* Content Source: [windows-apps-src/design/basics/navigation-basics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-basics.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by StephenLPeters** [comment]
@chigy I think this makes sense.

**Comment by chigy** [comment]
@stmoy , could you please open PR against the windows-apps-src/design/basics/navigation-basics.md to add this info?
