### ISSUE TITLE
Not clear and confusing how to get started with XAML based project

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2191]
The XAML based project is from the "Blank App" project template, which isn't clear at all.  The "Windows Desktop Application" seemed like the more natural starting point from the choices available without looking at this documentation and digging into the XAML templated control doc.

Suggest that:
1) XAML be added to the project template name
2) The documentation should have a new page that calls out more clearly/explicitly a document for getting started with a XAML based application for C++/WinRT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a5ba76-77cf-1233-2903-fd3c34b5044c
* Version Independent ID: 163d07f1-7860-cd16-a572-ff429cdf7008
* Content: [C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/index.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @michael-hawker, thanks for filing this issue. For #1, that'd be feedback for the Visual Studio team. I'd recommend looking internally for a contact in DevDiv, and passing on that feedback. For #2, there are several topics in this section that begin with a XAML-based project template. One example is https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-property, but there are others (look for topic titles beginning with "XAML").

Thanks!
Steve

**Comment by michael-hawker** [comment]
Thanks @stevewhims, I guess since the articles call out other scenarios, it's not clear that they also contain instructions from the beginning.  Maybe having a 'Getting started with XAML in C++/WinRT' page near the top intro ones and linking to it from [this section](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md#xaml-applications) in the intro doc would be a good way to pull that content more to the top, and then have the more detailed articles for more XAML specific scenarios like there are now.

@LyalinDotCom for 1) above do you know if the general [xlang](https://github.com/Microsoft/xlang) repo that the Marketplace page links to for the templates is the right place for that feedback or somewhere else?

**Comment by stevewhims** [comment]
Thanks for the issue, and feedback ideas! I'll go ahead and close this issue now!

Thanks!
Steve
