### ISSUE TITLE
Link to XAML accessibility sample is broken

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/windows-uwp#2197]
Can someone please update the link for XAML accessibility sample? Clicking on the link today leads to this site: https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples

I am desperately in need of finding that XAML accessibility sample. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1539930a-aff8-2262-5fe7-205c8a79c467
* Version Independent ID: d4750140-e094-9621-585e-0a83b10e0f2d
* Content: [Accessibility overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/accessibility-overview)
* Content Source: [windows-apps-src/design/accessibility/accessibility-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/accessibility-overview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @dpaulino. I'll fix this topic ASAP. 

In the meantime, this sample is archived on GitHub at https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Platform%20Sample/XAML%20accessibility%20sample. Hope this helps!

**Comment by dpaulino** [comment]
thanks
