### ISSUE TITLE
Supporting assets for Windows mode Light/Dark

### ISSUE THREAD

**Issue by ngducnghia** [MicrosoftDocs/windows-uwp#2198]
On Windows version 1903 and higher, the windows have different mode setting from apps. While my toast is only load assets appropriate for app mode, how can I have it load assets according to windows mode?
Thanks,
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae640d6-c949-e74b-cc0b-9c2d92b1e64f
* Version Independent ID: 5f2ece68-7e11-eee2-f6c6-0a78a5af6203
* Content: [Tile and toast notification support for language, scale, and high contrast - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/tile-toast-language-scale-contrast#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/tile-toast-language-scale-contrast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/tile-toast-language-scale-contrast.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by QuinnRadich** [comment]
Thanks for taking the time to let us know about this issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, I'd appreciate it if you can link it here, so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thank you!
