### ISSUE TITLE
How to know if a control is being shown in the visible area on a ScrollViewer

### ISSUE THREAD

**Issue by JoseEduardo7** [MicrosoftDocs/windows-uwp#2199]
Hello,
I have a ScrollViewer that contains a Grid. This Grid has many UserControl that are aggregated dinamically.  I would like to know if it´s possible to know if one of this UserControl is shown on screen or if is not visible.

Thanks.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. Unfortunately, the scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there!
