### ISSUE TITLE
Published Articles are Stale

### ISSUE THREAD

**Issue by EisenbergEffect** [MicrosoftDocs/windows-uwp#220]
Today I saw some feedback on twitter where customers were getting upset because they didn't see their contributor avatars on articles that they had contributed to. I looked into it and saw that it was because their contributions had not been published, even after 5 months. The article in question is here:

https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-extensions.md

It would be great to look into seeing if you can update the published content.

**Comment by normesta** [comment]
Thanks EisenburgEffect. I see no pull requests on that topic ( https://github.com/MicrosoftDocs/windows-uwp/pulls ). Can you direct me to the specific requests?

**Comment by EisenbergEffect** [comment]
I'm noticing that there are items in the history for this article (not PRs) where the content in master doesn't match what is published on the site. Do you know if the content has been recently published? This could be a bug in the publishing engine as well. Are you all using VSTS paired with GitHub?

**Comment by normesta** [comment]
Thanks. Can you direct me to a specific item that appears in the master repo that does not appear on the public site?  If there was some contribution in the past that got overwritten somehow, it could very well be some sort of bug in the system. RE: Pairing. Yes with use VSTS paired with Github.

**Comment by EisenbergEffect** [comment]
I found the PR actually: https://github.com/MicrosoftDocs/windows-uwp/pull/91
That change doesn't appear to be live on the site.

**Comment by normesta** [comment]
Clear as day. Thank you. Looks like a member of our team accepted the PR and for some reason that accept doesn't appear live. Definitely a bug somewhere there. I'm reaching out about this right now. Stay tuned. Thanks again

**Comment by normesta** [comment]
Ok I've asked the contributor to submit their edit again so that I can accept the pull request and get their avatar added to the topic. I have no way to manually add their avatar otherwise I'd do that and just make the edit to the doc myself. I'll give the contributor some time to respond to my comment before I intervene and make the correction myself. The doc will have to be corrected at some point as the typo in it still exists.
