### ISSUE TITLE
Need promo code for individual account

### ISSUE THREAD

**Issue by anant-svc** [MicrosoftDocs/windows-uwp#2200]
Hello,
Since childhood I have used Microsoft Windows and other products.
Can you please provide me a promo code? to register for the extension developer account as individual account.
Or what to do? to earn a promo code from Microsoft.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4ddd610-d6de-7a7c-2d59-fdc08dd98371
* Version Independent ID: 1ed74795-fa40-80a5-4fc2-6f4e87efa594
* Content: [Opening a developer account - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account#feedback)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I'm sorry, we do not distribute promo codes through GitHub issues.
