### ISSUE TITLE
Setting remoteId from Toast Content

### ISSUE THREAD

**Issue by ngducnghia** [MicrosoftDocs/windows-uwp#2201]
Hi,

We're sending Toast Notification from backend services, how can we set the remoteId on the Toast Content XML so that it can be universal dismissed across devices?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df20e709-807d-c9e6-1c45-d9009928f8b4
* Version Independent ID: 0a7e4d68-f080-b88b-9be9-256850cc9173
* Content: [Universal Dismiss - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/universal-dismiss)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/universal-dismiss.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/universal-dismiss.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by QuinnRadich** [comment]
Thanks for taking the time to let us know about this issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, I'd appreciate it if you can link it here, so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thank you!
