### ISSUE TITLE
Can you please update this doc with other device targets like HoloLens 1 and 2?

### ISSUE THREAD

**Issue by pampas93** [MicrosoftDocs/windows-uwp#2204]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 770616aa-f26a-4e26-03ac-2f2061702e21
* Version Independent ID: 7be0a48f-1ab5-77c1-d9e6-0f0abcbda165
* Content: [Supported codecs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/supported-codecs)
* Content Source: [windows-apps-src/audio-video-camera/supported-codecs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/supported-codecs.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, sorry for the extremely delayed response on this issue. I would suggest that you make this request in the Hololens documentation repo.

https://github.com/MicrosoftDocs/Hololens
