### ISSUE TITLE
Cannot add Windows.Networking.Sockets.WebSocketKeepAlive as background task entrypoint to manifest

### ISSUE THREAD

**Issue by hez2010** [MicrosoftDocs/windows-uwp#2205]
I followed the sample and added code below to package.manifest:
```xml
  <Extensions>
    <Extension Category="windows.backgroundTasks"
         Executable="$targetnametoken$.exe"
         EntryPoint="Background.PushNotifyTask">
      <BackgroundTasks>
        <Task Type="controlChannel" />
      </BackgroundTasks>
    </Extension>
    <Extension Category="windows.backgroundTasks"
         Executable="$targetnametoken$.exe"
         EntryPoint="Windows.Networking.Sockets.WebSocketKeepAlive">
      <BackgroundTasks>
        <Task Type="controlChannel" />
      </BackgroundTasks>
    </Extension>
  </Extensions>
```

However I got a compile error:
```
error APPX0501: Validation error. error 80080204: App manifest validation error: Line 52, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="Windows.Networking.Sockets.WebSocketKeepAlive" without ActivatableClassId in windows.activatableClass.inProcessServer.
```

My project is a UWP project which referenced a Windows Runtime Component as its out-of-process background task.

I also try to downgrade my min target version to 16299, it still doesn't work. (Some dependencies require 16299 such as Windows Community Toolkit as min target version so that I cannot downgrade to 15063)

A minimal repro: 
[BugRepro.zip](https://github.com/MicrosoftDocs/windows-uwp/files/4123777/BugRepro.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227e2d0-68e4-10a3-4866-4ac2146997f1
* Version Independent ID: 9238bd8f-94bc-5dd9-9bd7-17f93472c00a
* Content: [Network communications in the background - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/network-communications-in-the-background?redirectedfrom=MSDN#feedback)
* Content Source: [windows-apps-src/networking/network-communications-in-the-background.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/network-communications-in-the-background.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @hez2010, thanks for filing this issue (and sorry for the delay in responding). I can repro the issue, too, so I've reached out to the product team to see what we need to do to fix the documentation here.

I'll report back when I have more info.

Thanks again!
Steve

**Comment by PrinceCharles23** [comment]
so what's the story here? 3 months since this got reported and no update?
i am having the same issue

**Comment by hez2010** [comment]
Ping! Any updates on it?
This problem exists since Windows 10.0.16299.0 and now has passed 3 years.

**Comment by stevewhims** [comment]
Hi, @hez2010 (and others). Again, sorry for the delay. We've been discussing this internally since my previous comment and I now have info to share. An update to the topic is now live, with the following info in the **ControlChannelTrigger with WebSockets** section.

The feature described in this section (**ControlChannelTrigger with WebSockets**) is supported in version 10.0.15063.0 of the SDK, and earlier. It is also supported in pre-release versions of the [Windows 10 Insider Preview](https://www.microsoft.com/software-download/windowsinsiderpreviewSDK).

-Steve

**Comment by hez2010** [comment]
@stevewhims 
> It is also supported in pre-release versions of the [Windows 10 Insider Preview](https://www.microsoft.com/software-download/windowsinsiderpreviewSDK).

Which version of pre-release sdk? 10.0.19041.0 or 10.0.19624.0?

**Comment by stevewhims** [comment]
Hi, @hez2010, in this case, please download the most recent version.

**Comment by hez2010** [comment]
Hi, I've verified that this issue has been fixed in Windows 10 SDK 10.0.19624.0.

**Comment by stevewhims** [comment]
Excellent, thank you, @hez2010!

**Comment by PrinceCharles23** [comment]
since i am not part of the insider program i cannot download this preview version. i also do not feel too confident in using the preview in a production setting.

so, the next question is: when will this be available for common folk for production?

**Comment by hez2010** [comment]
@PrinceCharles23 Since 10.0.19624.0 is the SDK for Windows 10 21H1, it will be available for production in 2021 April or May.

There's a workaround for temporary, you can create a class to wrap `Windows.Networking.Sockets.WebSocketKeepAlive`.
```csharp
using Windows.ApplicationModel.Background;
using Windows.Networking.Sockets;

namespace BackgroundService
{
    public sealed class WebSocketKeepAliveTask : IBackgroundTask
    {
        private readonly WebSocketKeepAlive innerTask = new WebSocketKeepAlive();
        public void Run(IBackgroundTaskInstance taskInstance)
        {
            innerTask.Run(taskInstance);
        }
    }
}
```

Although WebSocket connection will not persist after App closed in this approach.

You can see further discussion in https://docs.microsoft.com/en-us/answers/questions/9794/how-to-persist-a-websocket-connection-using-contro.html.

**Comment by PrinceCharles23** [comment]
well thanks for the info but i only get exactly the same error but i am not using any web sockets. i just want a background task that is not audio related.

**Comment by hez2010** [comment]
@PrinceCharles23 You also need to modify the entrypoint in your app.manifest to reference your warp class instead.

**Comment by stevewhims** [comment]
> when will this be available for common folk for production?

Hi, @PrinceCharles23, I'm sorry not to be able to give a definitive answer there. I can talk about the documentation as it relates to the version of the platform that's currently generally available (GA), and as it relates to version(s) of the platform that are currently in Insider Preview.

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close the issue now as it feels resolved, and there's no further update needed to the content.

Thanks!
Steve
