### ISSUE TITLE
IsCloseable

### ISSUE THREAD

**Issue by kurema** [MicrosoftDocs/windows-uwp#2206]
IsCloseable→IsClosable at latest version.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f18f00ea-66b6-827a-0aa5-2dc93465288f
* Version Independent ID: 1afcff76-c66a-f6f3-098f-12446d6b20df
* Content: [タブ ビュー - UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/design/controls-and-patterns/tab-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tab-view.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/windows-apps-src/design/controls-and-patterns/tab-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This has been fixed. Thanks.
