### ISSUE TITLE
Pathless cast syntax

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/windows-uwp#2207]
The [Casting](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#casting) section should explain one more detail about the syntax: you can have no path but still have a cast, both for property bindings and function bindings, which enables passing the data item to a method.

[More detail](https://github.com/microsoft/microsoft-ui-xaml/issues/1868#issuecomment-579578777)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd64d43-7b7b-abed-ff27-fafa2b82df0f
* Version Independent ID: 6c349724-5273-3463-7d7e-b685a89f093f
* Content: [xBind markup extension - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#feedback)
* Content Source: [windows-apps-src/xaml-platform/x-bind-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/x-bind-markup-extension.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
A section has been added for pathless case syntax.

**Comment by Felix-Dev** [comment]
@jwmsft I think we should also mention that you can pass "this" as a parameter [here](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings#function-arguments) as well.
