### ISSUE TITLE
Incorrect Shortcut for Narrator Developer mode

### ISSUE THREAD

**Issue by keparanj** [MicrosoftDocs/windows-uwp#2208]
This is what the page says on how to turn on Narrator mode:
>Turn on developer mode when Narrator is already running by pressing Caps Lock + Shift + F12

Upon pressing those keys on Win 10 v1909(build 18363.592), Narrator speaks "Not a narrator command" out loud. I then pressed Caps Lock + F1 to get to the Narrator help screen. This is what I found after searching for Developer mode:
![image](https://user-images.githubusercontent.com/59984314/73406490-6637df80-42ab-11ea-8881-a805e507f1d8.png)
(Now Control + Caps Lock + F12 did work but it took me several bing searches to see what's going on). 

Thus, we should update the documentation to echo what the Narrator help screen says, especially since the "Narrator" key can be different [as this page describes](https://support.microsoft.com/en-us/help/22806/windows-10-narrator-keyboard-commands-touch-gestures). (Or use the "Standard" shortcut if we're going to assume that most folks update their systems or provide some sort of hint/link indicating that there might be other key combinations)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e908c6bb-72f1-b125-2822-e045951c0f67
* Version Independent ID: c2ac959c-12b8-f17b-3383-ef73c613ecaa
* Content: [Accessibility testing - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/accessibility-testing#verify_main_app_scenarios_by_using_narrator)
* Content Source: [windows-apps-src/design/accessibility/accessibility-testing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/accessibility-testing.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @keparanj. Topic has been fixed.
