### ISSUE TITLE
Change detection doesn't perfom when the object changes to null

### ISSUE THREAD

**Issue by jess-rod** [MicrosoftDocs/windows-uwp#2211]
If we have the following:

&lt;!-- Xaml --&gt;
...
&lt;TextBlock Text="{x:Bind ViewModel.DoSomething(ViewModel.SomeString), Mode = OneWay}" /&gt;

// C#
...
private string _someString;
public string SomeString
{
    get { return _someString; }
    set { Set(ref _someString, value);  // Observable property
}
public string DoSomething(string value) =&gt; value ?? "It's null";

Then it happens as follows:
- DoSomething is called for the first time.
- If SomeString changes to, say, "First change", DoSomething is called.
- If SomeString changes to "Second change", DoSomething is called.
- HOWEVER, if SomeString changes to NULL (SomeString = null), DoSomething is NOT called. WHY!? A bug?
- If SomeString changes to "Fourth change", DoSomething is called.

On the other hand, if we have the following binding:

&lt;!-- Xaml --&gt;
...
&lt;!-- We're not binding to a function anymor --&gt;
&lt;TextBlock x:Name="ExampleTB" Text="{x:Bind ViewModel.SomeString, Mode = OneWay}" /&gt;

Then it happens as expected:
- ExampleTB shows the value of SomeString.
- If SomeString changes to "First change", ExampleTB shows "First change".
- If SomeString changes to "Second change", ExampleTB shows "Second change".
- If SomeString changes to null (SomeString = null), ExampleTB shows nothing.
- If SomeString changes to "Fourth change", ExampleTB shows "Fourth change".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fdf7014-70bd-f562-046a-432f5f5caf11
* Version Independent ID: f45e3d08-66e0-1b74-2c0d-595345e7f3b1
* Content: [Functions in x:Bind - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings)
* Content Source: [windows-apps-src/data-binding/function-bindings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/function-bindings.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by tesar-tech** [comment]
I think, this is related to https://github.com/microsoft/microsoft-ui-xaml/issues/1904

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
