### ISSUE TITLE
There is no Windows Application Packaging Project template in my VS2019

### ISSUE THREAD

**Issue by RoyceLithgo** [MicrosoftDocs/windows-uwp#2217]
As per the title, the Windows Application Packaging Project project template is not there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7844818-d0b7-f502-3a07-a4970401fdcf
* Version Independent ID: 1acada53-18fa-68a2-4211-c4c3236c856e
* Content: [Package and deploy with MSIX](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5#feedback)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-5.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-5.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us. Can you confirm whether you have the Universal Windows Platform development workload installed with your version of Visual Studio, or that you have the Windows 10 SDK installed?

**Comment by RoyceLithgo** [comment]
I am developing WPF on Windows 8, so no I don’t have UWP installed.
Is the process for packaging MSIX different for Windows 8?

Regards,
Royce Lithgo
IT Manager

[image002]Moregate BioTech
PO Box 654
54 Banya Street
Bulimba QLD 4171
Australia
Direct:  +61 7 3555 8175
Main:    +61 7 3399 7000
Email:   it@moregatebiotech.com<mailto:it@moregatebiotech.com>

This email and any attachments to it contain confidential information intended only for the user of the party to which this email is addressed.
If you have received this transmission by mistake: (1) Do not copy it or communicate its contents to any person; and (2) Please inform Moregate Biotech of the error by email or by telephone to +61 7 33 99 7000.

**Comment by mcleanbyron** [comment]
Thanks for the clarification. The Windows Application Packaging Project for packaging .NET and Win32 desktop apps in an MSIX package is only available in the Universal Windows Platform workload or the Windows 10 SDK. Please see [this related reply](https://github.com/MicrosoftDocs/msix-docs/issues/101#issuecomment-584889458) for more details.
