### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by ZOulhadj** [MicrosoftDocs/windows-uwp#2222]
Under the section Hardware vs. Software Vertex Processing there is a small spelling mistake. "Software vertex processing is done is software." should be "Software vertex processing is done in software.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a85f10f-4db8-a2f4-13f4-bae21093af01
* Version Independent ID: 48342ab8-5365-30a9-9e05-02bd1f203d8b
* Content: [Device types - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/graphics-concepts/device-types#feedback)
* Content Source: [windows-apps-src/graphics-concepts/device-types.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/graphics-concepts/device-types.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @ZOulhadj, and thanks for filing this issue. The fix for this issue is now live, so I'll go ahead and close the issue.

Thanks again!
Steve

**Comment by ZOulhadj** [comment]
No problem, happy to help!
