### ISSUE TITLE
The documentation could use some code samples. I like to use MSAL for client credential flow

### ISSUE THREAD

**Issue by mahoekst** [MicrosoftDocs/windows-uwp#2224]
To create those 3 tokens in .NET this is the code I use

using Microsoft.Identity.Client;
using System;

namespace StoreServicesSample
{
    class Program
    {
        static async System.Threading.Tasks.Task Main(string[] args)
        {
            string token1 = "";
            string token2 = "";
            string token3 = "";

            string CLIENTID = "CLIENTID";
            string TENANTID = "TENANTID";
            string SECRET = "SECRET";

            Console.WriteLine("Hello World!");
            var app = ConfidentialClientApplicationBuilder.Create(CLIENTID)
                .WithAuthority(AzureCloudInstance.AzurePublic, TENANTID)
                .WithClientSecret(SECRET)
                .Build();

            string[] scopes = new string[] { "https://onestore.microsoft.com/.default" };

            AuthenticationResult result = null;
            try
            {
                result = await app.AcquireTokenForClient(scopes)
                                  .ExecuteAsync();
                token1 = result.AccessToken;

            }
            catch (MsalServiceException ex)
            {
                // Case when ex.Message contains:
                // AADSTS70011 Invalid scope. The scope has to be of the form "https://resourceUrl/.default"
                // Mitigation: change the scope to be as expected
            }

            scopes = new string[] { "https://onestore.microsoft.com/b2b/keys/create/purchase/.default" };
            result = null;
            try
            {
                result = await app.AcquireTokenForClient(scopes)
                                  .ExecuteAsync();
                token2 = result.AccessToken;

            }
            catch (MsalServiceException ex)
            {
                // Case when ex.Message contains:
                // AADSTS70011 Invalid scope. The scope has to be of the form "https://resourceUrl/.default"
                // Mitigation: change the scope to be as expected
            }

            scopes = new string[] { "https://onestore.microsoft.com/b2b/keys/create/collections/.default" };
            result = null;
            try
            {
                result = await app.AcquireTokenForClient(scopes)
                                  .ExecuteAsync();
                token3 = result.AccessToken;

            }
            catch (MsalServiceException ex)
            {
                // Case when ex.Message contains:
                // AADSTS70011 Invalid scope. The scope has to be of the form "https://resourceUrl/.default"
                // Mitigation: change the scope to be as expected
            }

        }
    }
}

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
