### ISSUE TITLE
Out of date links

### ISSUE THREAD

**Issue by jdormand** [MicrosoftDocs/windows-uwp#2228]
iot/samples links are out of date - now located here: https://github.com/microsoft/Windows-iotcore-samples I believe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a2e04a4-8907-8373-6d08-d7bf0db92e44
* Version Independent ID: 1505bdc2-54ab-1650-ca96-c1df5b482d18
* Content: [Enable user mode access to GPIO, I2C, and SPI - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-usermode-access#feedback)
* Content Source: [windows-apps-src/devices-sensors/enable-usermode-access.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/enable-usermode-access.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been revised.
