### ISSUE TITLE
Windows App Certification Kit version 10 link broken

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/windows-uwp#2230]
'Windows App Certification Kit version 10,' to https://go.microsoft.com/fwlink/p/?LinkID=309666 redirects to generic Developers page https://developer.microsoft.com/en-us/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea36edd-22d6-7d1e-73c3-63d8f276d679
* Version Independent ID: a50a03aa-e89d-55da-43ba-b23155b9bbaf
* Content: [Windows App Certification Kit - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit)
* Content Source: [windows-apps-src/debug-test-perf/windows-app-certification-kit.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/windows-app-certification-kit.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @OzBob. The link has been corrected.
