### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by keparanj** [MicrosoftDocs/windows-uwp#2231]
The [XAML user and custom controls sample](https://code.msdn.microsoft.com/windowsapps/XAML-user-and-custom-a8a9505e) link at the bottom of the page is dead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf035b98-e0c9-50c2-45ad-1dd37b4f31b0
* Version Independent ID: 4434d33d-7a43-8181-26f2-414ac194c272
* Content: [Custom dependency properties - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties)
* Content Source: [windows-apps-src/xaml-platform/custom-dependency-properties.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/custom-dependency-properties.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by bartlannoeye** [comment]
@jwmsft confirmed that link works, can be closed.
