### ISSUE TITLE
String.Format example is impossible due to how overload resolution works.

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/windows-uwp#2232]
The provided example reads:

```
<TextBlock Text="{x:Bind sys:String.Format('{0} is now available in {1}', local:MyPage.personName, local:MyPage.location)}" />
```

But that could never work because the first overload of String.Format with 3 arguments wants an IFormatProvider for the first parameter, not a string.

So this would just result in an error along the lines of:

> Invalid binding path '...' : Invalid or mismatched parameter at position '1'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fdf7014-70bd-f562-046a-432f5f5caf11
* Version Independent ID: f45e3d08-66e0-1b74-2c0d-595345e7f3b1
* Content: [Functions in x:Bind - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings#feedback)
* Content Source: [windows-apps-src/data-binding/function-bindings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/function-bindings.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by sukesh-ak** [comment]
Hi @kmgallahan  and @lastnameholiu 
Any reason this is closed? I hit the error and a search got me here.
I am trying to use 2 tokesn {0} and {1}

Example on the doc page still is the same I guess.

**Comment by kmgallahan** [comment]
@sukesh-ak I don't quite remember why I immediately closed the issue after opening it, but it was most likely because when I actually tried out the demo code using x:bind it just worked anyways, and I realized some magic was happening. You might try to repro using XAML and x:bind, rather than just C#.

**Comment by sukesh-ak** [comment]
@kmgallahan Thanks for your response 👍 

Here is a sample and it still fails. Just tried again.
If I remove {1} it works fine.

```
<TextBlock Text="{x:Bind sys:String.Format('1st Gear : {0}{1}',gearing.FirstGearSpeed,gearing.UnitType), Mode=OneWay}" />
```

**Comment by kmgallahan** [comment]
@sukesh-ak does it work if you remove `Mode=OneWay`?

Is gearing.UnitType a string?

**Comment by sukesh-ak** [comment]
> @sukesh-ak does it work if you remove `Mode=OneWay`?
> 
> Is gearing.UnitType a string?

Nope. In UWP without Mode explicitly mentioned nothing shows up even otherwise. I believe WPF has OneWay as default.

**Comment by kmgallahan** [comment]
What about gearing.UnitType? e.g. swap the 2 params to see if 0 fails. I wish I could rewind back to when I opened the issue...

**Comment by sukesh-ak** [comment]
> Is gearing.UnitType a string?
Yes its a string.

> What about gearing.UnitType? e.g. swap the 2 params to see if 0 fails. I wish I could rewind back to when I opened the issue...
No luck. Maybe needs to go back to using Converter.
