### ISSUE TITLE
Instruction's above dont work ... caused my Partner Center account to not work anymore

### ISSUE THREAD

**Issue by msanders59** [MicrosoftDocs/windows-uwp#2233]
So I was attempting to associate an Azure AD with my Partner Centre account, as described above. The process failed, with an apology message from Microsoft, saying it had failed for unknown reasons.

Now I can no longer see anything about my Windows Store App Deployment anymore in the Partner Center (it used to be called the Develor page a few weeks ago, but has morphed into the partner center). When I log in and click "dashboard", I just get a  page comes up saying "Windows Docs", that doesn't give any useful information. 

It would seem my developer account has become dis-connected from the Partner Center ??

I can't get any support anywhere and the Virtual Assistant is completely clueless.

Who do I contact to get this problem fixed.. which was caused by following the steps listed above on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1603df77-580d-a332-ace4-10c4b6f1484b
* Version Independent ID: 7f70b8d6-5146-f327-86c8-9c17acbcac23
* Content: [Associate Azure Active Directory with your Partner Center account - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-partner-center#feedback)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-partner-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-partner-center.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@msanders59 I've engaged the feature team to help investigate. Once we understand what happened, I will update the documentation. I will also let you know what the process will be to fix your account.

Thanks,
Shawn

**Comment by hickeys** [comment]
@msanders59 

The team has requested more information. For your privacy, I'd rather continue this conversation over email. Can you email me at hickeys@microsoft.com?

**Comment by hickeys** [comment]
As there has been no reply in months, I'm closing this issue.
