### ISSUE TITLE
Unity UWP -> XBOX info is outdated

### ISSUE THREAD

**Issue by OranguTech** [MicrosoftDocs/windows-uwp#2235]
Screens are much different, and no mention of the (so far mythical) XBOX One platform installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feffb01a-0cd6-0407-3892-04ea7bc28c2e
* Version Independent ID: 78347be9-2be2-ea2e-b626-9d057363df4b
* Content: [Bringing Unity games to UWP on Xbox - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/development-lanes-unity)
* Content Source: [windows-apps-src/xbox-apps/development-lanes-unity.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/development-lanes-unity.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by GrantMeStrength** [comment]
Thanks for the feedback. Yes, this topic is very out of date :-( We will close this issue, but make an internal bug to track updating this topic, hopefully in February '21. Thanks for bringing it to our attention! - john
