### ISSUE TITLE
Where is the complete sample project?

### ISSUE THREAD

**Issue by PaulaScholz** [MicrosoftDocs/windows-uwp#2236]
[Enter feedback here]
Where is the complete sample project that shows how to implement device orientation changes with pane selection and back-button display?  These code snippets are fine, but not enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e47560-871f-79a8-be5b-aa0d6fd9a0ae
* Version Independent ID: 6d370bc0-6e96-a177-ebbf-27020c0307fb
* Content: [Two-pane view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/two-pane-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/two-pane-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/two-pane-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
As indicated in the header, this article is about technology that is currently in public preview. We are working more samples and they will be linked here when they're ready.
