### ISSUE TITLE
Unable to download UWP Documentation as PDF

### ISSUE THREAD

**Issue by anuragyayhdapu** [MicrosoftDocs/windows-uwp#2237]
On clicking of ‘Download PDF’ button at bottom of Content List, it redirects to a Webpage with ‘404 Error - Page Not found’ message.

https://docs.microsoft.com/hi-in/windows/uwp/opbuildpdf/toc.pdf?branch=live

**Comment by hkhmsft** [comment]
Hi @anuragyayhdapu , thanks for bringing this to our attention. I'll take a look and circle back when there's a fix for this.

**Comment by anuragyayhdapu** [comment]
Thanks @lastnameholiu 
Checked now, Issue is fixed. I am able to download latest UWP docs.
