### ISSUE TITLE
The "XAML accessibility sample" link to https://code.msdn.microsoft.com/windowsapps/XAML-accessibility-sample-d63e820d is broken

### ISSUE THREAD

**Issue by guybark** [MicrosoftDocs/windows-uwp#2238]
The "XAML accessibility sample" link on this page, (to https://code.msdn.microsoft.com/windowsapps/XAML-accessibility-sample-d63e820d,) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58e91f4-3217-dc9d-4c9a-a5c1be56673f
* Version Independent ID: 957fb065-e223-b686-beaa-c96727b90b29
* Content: [Expose basic accessibility information - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/basic-accessibility-information)
* Content Source: [windows-apps-src/design/accessibility/basic-accessibility-information.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/basic-accessibility-information.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @guybark - this link (and similar links across the UWP accessibility docs) has been fixed.
