### ISSUE TITLE
Cannot complete MS Developer Account sign-up

### ISSUE THREAD

**Issue by koen-vissers** [MicrosoftDocs/windows-uwp#2239]
I'm at the last step of signing up for a developer account (Microsoft has even billed me for it already)
https://partner.microsoft.com/en-US/dashboard/Registration/Agreement

I check the box to accept agreement, click button to finish.

I get a 500-error which shows me the "robot in the rain page".
You're able to leave a message there...I did that twice already, but I was not contacted in any way.

#2160 describes some workaround...although I'm not sure is they are in the same stage of the sign-up procedure. Also, I not see the reported message in console and this workaround does not work for me.

I've been trying to sign-up for months now...first with my Azure AAD account after with my personal account. Both do not work and MS is not responding to me. It is really becoming ridiculous. Hope my message is seen here!

**Comment by hkhmsft** [comment]
Hi @koen-vissers , thanks for bringing this to our attention. I apologize that you have experienced a delay in responses. Though it's not within my bandwidth to provide the support you seek, perhaps you will be able to redirect your request in the [Partner Center Support Site](https://partner.microsoft.com/en-US/support)? There seems to be a support channel [here](https://partner.microsoft.com/en-US/dashboard/support/referrals/service-health-status) with service updates as well as a [social media channel for support](https://twitter.com/MPNSupport).

If you find a solution that might be helpful to include in our documentation, feel free to share with us and we'll include it. Thanks once again!
