### ISSUE TITLE
Extending acrylic into your title bar code must not be in the constructor of App.xaml.cs

### ISSUE THREAD

**Issue by Vijay-Nirmal** [MicrosoftDocs/windows-uwp#224]
Issue related to [Acrylic material doc
](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/style/acrylic.md)
```csharp
CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = true;
```

If we use the about code in the constructor of App.xaml.cs then the `System.AccessViolationException`

> System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

So we should ask devs to use this code in `OnLaunched` or `OnActivated` method

The line of issue: [acrylic.md#L242](https://github.com/MicrosoftDocs/windows-uwp/blame/docs/windows-apps-src/style/acrylic.md#L242)

**Comment by mijacobs** [comment]
Thanks, Vijay-Nirmal--We're updating the doc now.
