### ISSUE TITLE
Spurious backslashes in some of the code snippets

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/windows-uwp#2240]
What the title says, really. Several (but not all) of the XML schema snippets on this page have backslashes before quotes, and at the end of lines. This causes issues with the syntax coloring, and is just plain weird to boot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2615c586-d3ba-fa6d-c7a2-5126c31143e5
* Version Independent ID: d655b786-0c08-fa4d-3fce-b40cb5d5e6a7
* Content: [MakePri.exe format-specific indexers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/makepri-exe-format-specific-indexers#feedback)
* Content Source: [windows-apps-src/app-resources/makepri-exe-format-specific-indexers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/makepri-exe-format-specific-indexers.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @wjk , thanks for pointing this out. I will go ahead and take a look and circle back when the changes have been made.

**Comment by hkhmsft** [comment]
Hi @wjk , I went ahead and fixed all the additional backslashes and the changes are going live soon. Really appreciate you bringing this to our attention. Be well.
