### ISSUE TITLE
incorrect translations

### ISSUE THREAD

**Issue by hhoouu89** [MicrosoftDocs/windows-uwp#2245]
for example: "конвертерлангуаже"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 58a59ed8-aaf6-99e0-a8d2-7162d178274b
* Version Independent ID: bd1ee3de-43b9-afb2-f91d-1f3aa93c3e74
* Content: [Расширение разметки Binding' - UWP applications](https://docs.microsoft.com/ru-ru/windows/uwp/xaml-platform/binding-markup-extension#feedback)
* Content Source: [windows-apps-src/xaml-platform/binding-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/windows-apps-src/xaml-platform/binding-markup-extension.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by CeciAc** [comment]
Hello @hhoouu89

Thank you for your contribution.

Contributions on translation problems against machine-translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

#please-close
