### ISSUE TITLE
Invalid ApiInformation.IsTypePresent check

### ISSUE THREAD

**Issue by Sylvain2703** [MicrosoftDocs/windows-uwp#2249]
In the "Custom acrylic brush" section, the code sample is not correct and cause application crash on W10 Creators Update.

We have to test ApiInformation.IsTypePresent("Windows.UI.Xaml.Media.AcrylicBrush") instead of ApiInformation.IsTypePresent("Windows.UI.Xaml.Media.XamlCompositionBrushBase").
Even if AcrylicBrush depends on XamlCompositionBrushBase, they weren't introduced in the same version: XamlCompositionBrushBase was with Creators Update and AcrylicBrush with Fall Creators Update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9faf87c-bd56-99da-70ed-07c68f9118a5
* Version Independent ID: 713b5c24-d710-303f-620e-9c7735797907
* Content: [Acrylic material - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#feedback)
* Content Source: [windows-apps-src/design/style/acrylic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/acrylic.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Sylvain2703** [comment]
Fixed with #2250

**Comment by kikisaints** [comment]
@ranjeshj looks like the #2250 commit by sylvain2730 has fixed this, what did you need me to look at?

**Comment by ranjeshj** [comment]
Great. Thanks!
