### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by 1TheMuffinMan** [MicrosoftDocs/windows-uwp#2251]
I've gone back and followed the steps about 15 times. The shortcut has the necessary matching info. No errors, no notifications.

Why is showing a toast so complicated? It's a bit embarrassing that the creators of this API came up with... this.

Ultimately, do you have a sample I can download to test? The process is entirely too complex and error prone to try to slap together using code fragments.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Send a local toast notification from desktop C# apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by tommed** [comment]
Why was this closed?
