### ISSUE TITLE
No window can be captured.

### ISSUE THREAD

**Issue by singhwong** [MicrosoftDocs/windows-uwp#2252]
`var picker = new GraphicsCapturePicker();
    GraphicsCaptureItem item = await picker.PickSingleItemAsync();`
In Windows 10 Pro Insider Preview, there are no windows that can be captured.

Edition: Windows 10 Pro Insider Preview
Version: 2004
OS build: 19569.1000
Experience: Windows Feature Experience Pack 120.2901.0.0

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
