### ISSUE TITLE
MainPage.g.cpp and winrt folder not generated

### ISSUE THREAD

**Issue by kxxchoy** [MicrosoftDocs/windows-uwp#2254]
I followed the steps on this page trying to create a simple C++/WinRT. However, upon adding Microsoft.UI.Xaml from NuGet, MainPage.g.cpp and the winrt folder under the folder "<project folder>/Generated Files" were not generated. As a result, the Microsoft.UI.Xaml header files were also not generated. They were still not generated even when the solution was built. This resulted in build errors like "cannot open source file MainPage.g.cpp", "cannot open source file winrt/Microsoft.UI.Xaml.Controls.h", etc. I believe there might be one or more missing step in the page.

My Visual Studio is Community 2019 version 16.4.5. From Visual Studio Installer, under Universal Windows Platform development, these are included:

- C++ (v142) Universal Windows Platform tools
- Windows 10 SDK (10.0.17763.0)

In NuGet, thee following two packages are installed:

- Microsoft.UI.Xaml (v2.3.200213001)
- Microsoft.Windows.CppWinRT (v2.0.200224.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb0978bf-4d67-556c-b6c6-87b360d446c8
* Version Independent ID: 6fe15723-a3a2-9a7c-1720-ef4194f5ed70
* Content: [A simple C++/WinRT Windows UI Library example - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/simple-winui-example.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/simple-winui-example.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kxxchoy, thanks for filing this issue. I apologize for the inconvenience, but the `Microsoft.UI.Xaml` NuGet package requires TargetPlatformVersion >= 10.0.18362.0. You'll see a build error to that effect if you don't do that. The latest released SDK version is at
https://developer.microsoft.com/windows/downloads/windows-10-sdk.

For more background, setup, and support info for WinUI, see [Getting started with the Windows UI Library](https://docs.microsoft.com/uwp/toolkits/winui/getting-started). There's a link to that from this topic.

Thanks!
Steve

**Comment by kxxchoy** [comment]
Hi stevewhims, thanks for your reply.

I had Windows SDK 10.0.18362.1. Anyway, I downloaded it again from the link you provided and re-installed it.

I went to Retarget Projects. Window SDK Version was already "10.0 (latest installed version)" and Windows SDK Min. Version: was "10.0.18362.0".

In Project Property > Configuration Properties, Target Platform Version was 10.0.18362.0 and I changed it to "10.0 (latest installed version)". Target Platform Min. Version was a version before 10.0.18362.0 and I changed it to 10.0.18362.0.

Then I created a new blank C++/WinRT project again to try it out. Unfortunately the same problem persisted.

Should we at least find the Microsoft.UI.Xaml header files (e.g. Microsoft.UI.Xaml.Controls.h) in C:\Program Files (x86)\Windows Kits\10? I have searched it through but none exists.

**Comment by stevewhims** [comment]
Hi, @kxxchoy, regarding your question about the WinUI header files: because WinUI is independent of the Windows SDK, you won't find it at that path (which is the SDK path).

I've worked through the topic again to confirm that the steps are correct, and everything worked for me with the latest versions of: Visual Studio 2019, the 18362 Windows SDK, the C++/WinRT VSIX, and the C++/WinRT NuGet package. However, I found a few ways to make the steps a little clearer, so I've published updates to the topic.

I can't reproduce the issue you're seeing, nor can I see anything remaining that's wrong with the topic, so there are no additional changes that I can think of to make to the topic.

-Steve

**Comment by kxxchoy** [comment]
Hi stevewhims, I've found the reason. It was because I deleted the whole member function MainPage::ClickHandler in MainPage.cpp. I should have just deleted the content of it.

However, I've found another way to make the build fail. The following are the last few lines of the build messages:

1>Processing input metadata file Debug\Unmerged\App.winmd.
1>Processing input metadata file Debug\Unmerged\MainPage.winmd.
1>Processing input metadata file Debug\Unmerged\XamlMetaDataProvider.winmd.
1>Saved output metadata file winrt_demo.winmd.
1>Validating metadata file Debug\Merged\winrt_demo.winmd.
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(308,5): Xaml Internal Error error WMC9999: Name should contain ::winrt prefix
1>Done building project "winrt_demo.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

It is related to the name of the solution. I've tried a few solution names and here is the result:

HelloWinUICppWinRT >> success
HelloWinUI_CppWinRT >> success
HelloWinUI >> success
WinRTBlank >> success
winrt_blank >> fail
winrt_demo >> fail
win_rt_demo >> success

It looks like the solution name must not start with "winrt". Perhaps it is something you could take a look into.

**Comment by stevewhims** [comment]
It's great that you've found the reason for the issue. And, yes, I've forwarded your info about some project file names failing on to the product team. It looks like it has to be "winrt" (lower case) followed by an underscore, based on that experimental data.

Thanks!
Steve
