### ISSUE TITLE
Why is this document under the UWP controls

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2255]
This is clearly the description of a WPF Button.  The UWP button doesn't support content.  Why is this help page under the UWP tag?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6e57c0-4d39-7608-e535-f3bf35d3f7a2
* Version Independent ID: 826f8e2b-b5be-3c62-6bb6-85abea1bfba4
* Content: [Buttons - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/buttons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/buttons.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
The UWP Button supports content just like the WPF Button; both derive from ContentControl.

**Comment by ghost** [comment]
My mistake.  I was looking at a Xamarin button.  The documentation is correct.
