### ISSUE TITLE
Toast notification with WinRT instead of WRL

### ISSUE THREAD

**Issue by fjch1997** [MicrosoftDocs/windows-uwp#2258]
Since the WRL documentation recommends WinRT instead of itself. I am wondering if it is possible to use WinRT to send toast notification and register the INotificationActivationCallback COM class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74f1f732-1dc0-a940-e85b-7559d268f09e
* Version Independent ID: f563b790-3236-3f2a-1f02-a46b47ee469c
* Content: [Send a local toast notification from desktop C++ WRL apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#step-7-send-a-notification)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by QuinnRadich** [comment]
Thanks for taking the time to let us know about this issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, I'd appreciate it if you can link it here, so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thank you!
