### ISSUE TITLE
None of these examples work!! Where is a sample of animation of a brush in UPW???

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2259]
I've spent the entire day in Google Searches.  Scanned everything I could find on Stackoverflow.   Then I get to these pages, cut the examples out, paste them, and....NOTHING!

Where is one example of animating the color of a solid color brush in UWP?  Just one working example, please!

**Comment by MikeHillberg** [comment]
Do the samples [here](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Animation.ColorAnimation#examples) work for you? Another sample is in the [samples repo](https://github.com/microsoft/Windows-universal-samples/blob/fe8567faf2efdea3672c2ba642ba7b925ff6467e/Samples/XamlTransform3DAnimations/cs/SectionView.xaml#L49).

**Comment by ghost** [comment]
No, I'm trying to use Compositioning, not Storyboards.  My understanding is that it's supposed to be a faster, more direct line to providing effects in my app.  I'm just looking for a simple example where I can draw an XAML TextBlock (or anything that draws text) using a composition brush.  That's all.

**Comment by MikeHillberg** [comment]
Xaml Storyboards actually create a Composition animation, so you are getting one. I don't expect you get much benefit from hand authoring it yourself.

But you can, and another reason to create one yourself is to get CompositionAnimation features that aren't available from a Storyboard, such as an [ExpressionAnimation](https://docs.microsoft.com/uwp/api/Windows.UI.Composition.ExpressionAnimation). 

To do that you need to create a custom Xaml brush that derives from [XamlCompositionBrushBase](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.XamlCompositionBrushBase). There's an example on that page of how to do it. That will then allow you to use a [CompositionColorBrush](https://docs.microsoft.com/uwp/api/Windows.UI.Composition.CompositionColorBrush), and there's an example on that page of how to animated one.

**Comment by ghost** [comment]
> Xaml Storyboards actually create a Composition animation, so you are getting one. I don't expect you get much benefit from hand authoring it yourself.

From the documentation at: https://docs.microsoft.com/en-us/windows/uwp/design/motion/xaml-property-animations

> Using the visual layer provides better performance than using the XAML constructs. But using ElementCompositionPreview to get the element's underlying composition Visual object, and then animating the Visual with composition animations, is more complex to use.

So, yes, I'm expecting this work perform better once I learn the API.

**Comment by ghost** [comment]
> To do that you need to create a custom Xaml brush that derives from XamlCompositionBrushBase. There's an example on that page of how to do it. That will then allow you to use a CompositionColorBrush, and there's an example on that page of how to animated one.

Yes.  This turned out to be the way to get it done.  However, you're expecting a lot if you expect someone to pull together all those pieces from that documentation you reference.   I spent a day researching this when a simple, complete example of an animated brush would have done the job in 10 minutes.

**Comment by hkhmsft** [comment]
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback!
