### ISSUE TITLE
Windows.Graphics.Capture isSupported

### ISSUE THREAD

**Issue by martininguyen** [MicrosoftDocs/windows-uwp#2260]
Hello, I remember this functionality was only supported on Pro/Enterprise edition of windows. Is this still the case or has it extended to home edition now?

**Comment by MikeHillberg** [comment]
Do you mean [GraphicsCaptureItem](https://docs.microsoft.com/uwp/api/Windows.Graphics.Capture.GraphicsCaptureItem)?

**Comment by martininguyen** [comment]
GraphicsCaptureSession @MikeHillberg

**Comment by drewbatgit** [comment]
@martininguyen - Do you remember where you saw that GraphicsCaptureSession was unsupported for Home edition? Is this stated in the documentation somewhere?

**Comment by drewbatgit** [comment]
I have confirmed that GraphicsCaptureSession is supported for Home Edition as of Windows 10, version 1809 (10.0; Build 17763)
