### ISSUE TITLE
Issue in TraceProcessing blog posts

### ISSUE THREAD

**Issue by kant2002** [MicrosoftDocs/windows-uwp#2262]
I found library TraceProcessing via link to blog post. That blo post does not include sample, so I go to earlier blog post versions[1] . And samples was broken. Only via indirect links I reach this repository.

Can somebody update samples in blog posts or link to that repository or docs website, so it can be understood how to use package.

- [1] https://blogs.windows.com/windowsdeveloper/2020/01/28/traceprocessor-0-3-0/

**Comment by mcleanbyron** [comment]
Thanks for your feedback. You can find guidance about using the TraceProcessing API in the docs here: https://docs.microsoft.com/en-us/windows/apps/trace-processing/overview. If you have further feedback or issues to report about this API, please file an issue in the [eventtracing-processing](https://github.com/microsoft/eventtracing-processing) repo. Thanks!
