### ISSUE TITLE
"Guidleines for tile and icon assets" link is broken.

### ISSUE THREAD

**Issue by payneio** [MicrosoftDocs/windows-uwp#2269]
"Guidleines for tile and icon assets" link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1666072a-88f4-45e9-ede0-414fe8ef61e5
* Version Independent ID: ed5e311a-c7e6-7eba-0ae6-48f3bbcb6b12
* Content: [Icons - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/icons#feedback)
* Content Source: [windows-apps-src/design/style/icons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/icons.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just merged in a fix for the broken link. Should be published shortly. Thanks for reporting this.
