### ISSUE TITLE
Xamarin Audio - I don't understand a word.

### ISSUE THREAD

**Issue by Johnvan** [MicrosoftDocs/windows-uwp#2274]
All I want to do is generate an Audio Tone when an event occurs, but where ever I go to get information on this I get hit with GOBLY GOSH, explanations that are in an over the top language that I have no idea on what is being said.
I can follow all the other subjects in this tutorial except AUDIO.
AudioGraphs and AudioFrames - no idea on what is described.
What about    tone(1000); equals an output tone of 1000Hz.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e2eda-b495-126e-553d-65ebee87bd3c
* Version Independent ID: a850ef9a-9d08-64a2-dd6b-584d2059f392
* Content: [Audio graphs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs#spatial-audio)
* Content Source: [windows-apps-src/audio-video-camera/audio-graphs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/audio-graphs.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, the AudioGraph APIs are intended for more sophisticated audio processing applications. If you just want to play a sound when an event occurs, I recommend just using MediaPlayer. It requires your tone to be in an audio file, but you can play a sound back with just a few lines of code. For more information, see [Play audio and video with MediaPlayer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer).

**Comment by Johnvan** [comment]
Thankyou **drewbatgit** the Play audio and video with MediaPlayer is just what I needed. Thanks again.
