### ISSUE TITLE
There is no "Universal Windows App" for "Application  type" field

### ISSUE THREAD

**Issue by mauler2025** [MicrosoftDocs/windows-uwp#2275]
The screenshot for creating a new key is out of sync with the current condition. There is no "Universal Windows App" for "Application  type" field.

Please update the screenshot. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1326ab8-50fc-edaf-6f91-591b6b813213
* Version Independent ID: 6cfd2845-011b-4b84-ed53-b8bc94b9c8d5
* Content: [Request a maps authentication key - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/authentication-key)
* Content Source: [windows-apps-src/maps-and-location/authentication-key.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/maps-and-location/authentication-key.md)
* Product: **uwp**
* Technology: **people-and-places**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just checked in a new image. It will be published shortly. Thank you.
