### ISSUE TITLE
Screenshots out of date for developer settings page

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/windows-uwp#2276]
As the title says, the screenshots do not seem to be up to date. Comparison between the docs and settings app on my machine:

![image](https://user-images.githubusercontent.com/16122379/76428180-9f389900-63ad-11ea-9ae0-2dd0eea94a1e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f67548-9361-beab-49f8-7d604651c6a6
* Version Independent ID: 6194efed-24aa-74f2-7687-3e368534b74a
* Content: [Enable your device for development - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by HappyNomad** [comment]
@chingucoding  What Windows release/build do you have?  Even after I installed the latest feature update through Windows Update, I still have the old way.

**Comment by marcelwgn** [comment]
I am running Windows 10 Education insider Build 19582

**Comment by HappyNomad** [comment]
Ah, an "Insider" build - that's why it doesn't show up for me.  Actually, I don't think they should update this doc with a screenshot that only applies to an Insider build.

**Comment by marcelwgn** [comment]
Oh that difference is just because of using an insider build? I didn't thought that it would make such a huge difference.

**Comment by HappyNomad** [comment]
Yea, it's not clear when/if the new "For developers" UI will go mainstream.

**Comment by marcelwgn** [comment]
I guess in that case, it doesn't make sense to keep this opened much longer. Thanks for your input!
