### ISSUE TITLE
Add note about codec support

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#2285]
AdaptiveMediaSource only supports H264 and WVC1 for video playback when used with Smooth Streaming content. Other manifest types don't have this limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba15ea2-27a1-78ca-7610-d2025f5aa5d3
* Version Independent ID: 1ff3ba66-c83c-ee09-efa5-f7ad2b5f950a
* Content: [Adaptive streaming - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/adaptive-streaming)
* Content Source: [windows-apps-src/audio-video-camera/adaptive-streaming.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/adaptive-streaming.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for the feedback. I've added this information to the section about smooth streaming support.
