### ISSUE TITLE
My Windows Mail On Android phone and sync with Opera

### ISSUE THREAD

**Issue by zavedctg** [MicrosoftDocs/windows-uwp#229]
As I don't have access to both of my Yahoo and Nokia account and lost access to my recover phone, please import my login pass key for my own good to get listed as service providers at Chittagong.

**Comment by mattwojo** [comment]
Hi @zavedctg -- I don't quite understand the issue here, but this does not appear to be the correct place to seek help. I would recommend trying https://support.microsoft.com.
