### ISSUE TITLE
What if I need to select a date and time together?

### ISSUE THREAD

**Issue by Licantrop0** [MicrosoftDocs/windows-uwp#2296]
Since the DateTimeOffset data structure holds date and time together, there is no guideline in this article on what to do if I need to bind the date part of a DateTimeOffset to a CalendarDatePicker/DatePicker, and the time part to a TimePicker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f5e4bc-a261-ffe3-6c44-19bd53d4166b
* Version Independent ID: 3cc76f2f-cd62-1705-0007-0378181b1cd6
* Content: [Guidelines for date and time controls - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/date-and-time)
* Content Source: [windows-apps-src/design/controls-and-patterns/date-and-time.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/date-and-time.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. I agree that this documentation needs more information about using the date and time controls. We will look to improve this in a future doc update.

The API reference docs for [CalendarDatePicker](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendardatepicker) and [TimePicker](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.timepicker) have additional information that might help (also see the Date and Time properties). The [DateTimePage](https://github.com/microsoft/Windows-appsample-lunch-scheduler/blob/master/LunchScheduler/Views/DateTimePage.xaml.cs) in the LunchScheduler sample also shows how to use these controls to set a single DateTimeOffset.

For further assistance, here are some developer support resources you might use .

- [Windows UI (XAML) GitHub repo](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose)
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) 
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by jwmsft** [comment]
The Date and time controls article has been updated with this section: [Use a date picker and time picker together](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/date-and-time#use-a-date-picker-and-time-picker-together)
