### ISSUE TITLE
When will the changes regarding sideloaded apps come into effect in normal Windows builds?

### ISSUE THREAD

**Issue by HappyNomad** [MicrosoftDocs/windows-uwp#2297]
This doc notes changes regarding sideloaded apps that are part of Windows Insider Build 18956.  My machine has the latest feature update but it lacks these changes.  Are said changes still slated to make it into normal Windows builds?  If so then when can we expect to see them?  If the changes have been dropped then please remove mention of them from this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f67548-9361-beab-49f8-7d604651c6a6
* Version Independent ID: 6194efed-24aa-74f2-7687-3e368534b74a
* Content: [Enable your device for development - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development#which-setting-should-i-choose-sideload-apps-or-developer-mode)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
The changes should have gone live in the latest version of Windows 10, build 19041. I've updated the documentation to align with this.
