### ISSUE TITLE
"Get started with app deployment in Microsoft Intune" link is broken

### ISSUE THREAD

**Issue by HappyNomad** [MicrosoftDocs/windows-uwp#2298]
Clicking the supplied link leads to a "404 - Page not found" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f67548-9361-beab-49f8-7d604651c6a6
* Version Independent ID: 6194efed-24aa-74f2-7687-3e368534b74a
* Content: [Enable your device for development - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development#which-setting-should-i-choose-sideload-apps-or-developer-mode)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Link has been revised and fixed. Thank you.
