### ISSUE TITLE
Keywords for searchers

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/windows-uwp#2306]
A lot of people don't know what the System Media Transport Controls are called. Adding keywords like "Media popup", "Media pop-up", "Media pop up", "Media overlay" and "Media controls" would help searchers a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c756203f-fa1e-c530-7827-96f1325f91a7
* Version Independent ID: 86dc190a-3c44-e3bf-6b3c-3207dca7c371
* Content: [Integrate with the System Media Transport Controls - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols#feedback)
* Content Source: [windows-apps-src/audio-video-camera/integrate-with-systemmediatransportcontrols.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/integrate-with-systemmediatransportcontrols.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by Poopooracoocoo** [comment]
and this also could apply to https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols

**Comment by drewbatgit** [comment]
Unfortunately, according to our SEO team, we don't have a mechanism for adding arbitrary keywords that influence search results. And we have decided not to add additional terms to the text of the article at this time. Our intent is that people who are new to the platform will search for "media playback" and related terms to land on our main [Media Playback page](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-playback) that describes all of the playback features supported for UWP apps, including SMTC.

**Comment by Poopooracoocoo** [comment]
@drewbatgit 

Sorry for going off topic but do you know if they'll be updated on Windows 10?

They still use the Windows 8 icons and have only been updated on the lockscreen. They don't show the app that is playing. They can be quite annoying and there's no way to turn them off. Some may only want it to appear when they pause or play, or skip forwards or backwards and not when they adjust the volume. Some may want it in the volume flyout (which makes a lot of sense actually).   

I'm sorry if you don't know and it's my fault for asking something like this on a documentation issue.

It's not just UWP exclusive developers that want to use the SMTC. There's Chrome and Firefox.

The word pop-up could be used like the following sentence: "The SMTC is a pop-up in the top left on Windows 10 and is in the Guide on Xbox One". It doesn't have to be in some hidden place. 

>And we have decided not to add additional terms to the text of the article at this time.

Well alright.
