### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/windows-uwp#2307]
It's a bit hard to understand that it's something in Windows' UI.
https://visualstudiomagazine.com/articles/2016/10/01/universal-windows-platform-media-app.aspx
![image](https://user-images.githubusercontent.com/51363864/77247553-71ddcc00-6c86-11ea-9c20-32b836f7a74d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c756203f-fa1e-c530-7827-96f1325f91a7
* Version Independent ID: 86dc190a-3c44-e3bf-6b3c-3207dca7c371
* Content: [Integrate with the System Media Transport Controls - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols)
* Content Source: [windows-apps-src/audio-video-camera/integrate-with-systemmediatransportcontrols.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/integrate-with-systemmediatransportcontrols.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by Poopooracoocoo** [comment]
and this also could apply to https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols

**Comment by drewbatgit** [comment]
I've added a screenshot to this page and updated the description of the SMTC to make it more clear that the SMTC is system UI: "The system transport controls enable media application developers integrate with the built-in system UI to display media metadata such as artist, album title, or chapter title. The system transport control also allows a user to control the playback of a media app using the built-in system UI, such as pausing playback and skipping forward and backward in a playlist."
