### ISSUE TITLE
Stanislav1975

### ISSUE THREAD

**Issue by Stanislav1975** [MicrosoftDocs/windows-uwp#2309]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1941542a-d86a-6520-00c3-e47300f02796
* Version Independent ID: d48e3258-5e2f-65bf-cfa7-2f1f3d0e94f9
* Content: [Fluent Design System for Windows](https://docs.microsoft.com/en-us/windows/apps/fluent-design-system)
* Content Source: [hub/apps/fluent-design-system.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/fluent-design-system.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
