### ISSUE TITLE
Should Windows Runtime AudioGraph be considered for a game?

### ISSUE THREAD

**Issue by BMarques** [MicrosoftDocs/windows-uwp#2315]
According to https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs, this is a fine replacement for XAudio 2, but I don't see any mention of it here on the Audio section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9008e09-1fd4-41d6-6265-0f48c84a21ec
* Version Independent ID: f8cdcb5a-32de-a0a8-6c1d-7d1ad5f4b8ff
* Content: [Game technologies for Universal Windows Platform (UWP) apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/game-development-platform-guide#feedback)
* Content Source: [windows-apps-src/gaming/game-development-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/game-development-platform-guide.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @BMarques! Thanks for this suggestion, it's a good idea. I've published updates to this topic (and to [Audio for games](https://docs.microsoft.com/windows/uwp/gaming/working-with-audio-in-your-directx-game)), and those changes are now live.

So I'll go ahead and close this issue.

Thanks again!
Steve
