### ISSUE TITLE
Add a page which specifically details the Windows Runtime (WinRT)

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/windows-uwp#2316]
With the rise of newer language projections like C++/WinRT and eventually Rust/WinRT, it has become increasingly useful to explain to those interested what the Windows Runtime actually is. It would enable more developers to make educated decisions on what technology to include in their apps.

![image](https://user-images.githubusercontent.com/20365014/77560664-23058180-6e94-11ea-8ddb-850f38f2ab6f.png)

**Some questions to answer:**

- On what layer does does WinRT sit compared to Win32, COM, and .NET? 

- What problems does the Windows Runtime aim to solve compared to calling the Windows API directly?

- In what cases would it be appropriate to write an application purely using the Windows Runtime? Although it's difficult to generalize, I assume it has better performance than managed code like .NET

I noticed @kennykerr offers some courses about the Windows Runtime Internals, maybe information can be provided like that?

**Comment by lukeblevins** [comment]
I just discovered this section which was relatively hidden at the bottom of a page: https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide#how-the-universal-windows-platform-relates-to-windows-runtime-apis

Maybe this can be expanded and promoted more heavily

**Comment by lukeblevins** [comment]
@lastnameholiu Is @QuinnRadich planning to work on this, or someone else who is active be assigned?

**Comment by lukeblevins** [comment]
@QuinnRadich @lastnameholiu Any update on this?

**Comment by QuinnRadich** [comment]
We're currently working on larger updates to the Get Started section of our documentation, and this precise messaging on WinRT will be part of it. No timeline yet, but rest assured that it's in the works.

**Comment by lukeblevins** [comment]
@QuinnRadich Wonderful! Thanks Quinn. I'll look forward to seeing the spec for this!
