### ISSUE TITLE
Could use a bit more work

### ISSUE THREAD

**Issue by Melsvik** [MicrosoftDocs/windows-uwp#2319]
These examples can't compile:
Just take the method IsCompatibleVersion as an example.
This should be an async method to use await.
not all code parth return a value.
+ spelling mistake in BluetothCacheMode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8000cb47-cefb-cdad-8c56-bf30081e50de
* Version Independent ID: 8c486745-ec87-b5b6-11f2-03409f585dcf
* Content: [Bluetooth RFCOMM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/send-or-receive-files-with-rfcomm#feedback)
* Content Source: [windows-apps-src/devices-sensors/send-or-receive-files-with-rfcomm.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/send-or-receive-files-with-rfcomm.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @Melsvik. C# code snippets have been corrected to build cleanly.
