### ISSUE TITLE
Please clarify whether folders in the FutureAccessList also allow access to nested folders

### ISSUE THREAD

**Issue by BenJKuhn** [MicrosoftDocs/windows-uwp#2322]
This should probably be clarified both here and in the API documentation pages.

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
