### ISSUE TITLE
How do I exclude directories/resources from being piped to MakePri?

### ISSUE THREAD

**Issue by hawkerm** [MicrosoftDocs/windows-uwp#2326]
It seems like there's a [custom configuration file](https://docs.microsoft.com/en-us/windows/uwp/app-resources/makepri-exe-configuration) that also doesn't call out how to exclude files.

I have other external resource included in my UWP Windows Runtime Component library project which use '-' in their filenames (either as other names or other locales from another language - TypeScript); I can't change these as they're an external dependency pulled remotely, but MakePri still generates PRI249, PRI257, and PRI263 errors about these files.

I just need to know how I can configure my build to suppress these issues in a way that makes it so that other folks who pull this nuget package which includes these files as part of its content won't also have to receive these warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8ae3b2-f95d-1444-b0c0-0c34921f861f
* Version Independent ID: c1320023-527c-8056-d34c-ef387e8dc298
* Content: [Compile resources manually with MakePri.exe - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/compile-resources-manually-with-makepri#makepriexe-warnings-and-error-messages)
* Content Source: [windows-apps-src/app-resources/compile-resources-manually-with-makepri.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/compile-resources-manually-with-makepri.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by hawkerm** [comment]
@lastnameholiu sure there's a technical question here, but this isn't documented on how to use the tool properly; there's still a documentation gap here. If this was documented, I wouldn't have had a question.

It isn't helpful to redirect me to another place when I've already filed an issue here on GitHub. Why is there yet another forum to submit things on?
