### ISSUE TITLE
Useful information

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/windows-uwp#2327]
Very good documentation. It helped a lot. I ran into an exception and I wish you guys had talked about including the resources to the application; 
"&lt;XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /&gt; "
And about the namespace "muxc:"
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dc1e36-575b-1941-9251-fab0e99a93f0
* Version Independent ID: ef45ab97-5bd2-1202-87f6-95d29774b659
* Content: [Teaching tips - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@rogerms, thanks for the feedback. We've updated the Teaching Tips page to include the missing information about using the Windows UI Library.
