### ISSUE TITLE
Javascript?

### ISSUE THREAD

**Issue by dchstudios** [MicrosoftDocs/windows-uwp#2330]
In "Creating a JavaScript client app" there is no option of choosing  "Blank App (Universal Windows)" under the Javascript refinement (when adding a New Project). All I get is a bunch of Node.js template options. Maybe there could be a list of all the installs necessary for that list to populate properly? Then again, I consequently had Visual Studio install about everything possible, still to no avail when I get to this part of this tutorial. No general Javascript anything apart from the Node.js options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2860140a-8b64-4280-3f5b-bb454d71def9
* Version Independent ID: 4af675f3-e584-5616-ac4a-335ecda5b4f3
* Content: [Walkthrough of creating a C++/CX Windows Runtime component, and calling it from JavaScript or C# - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp#creating-a-javascript-client-app)
* Content Source: [windows-apps-src/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/walkthrough-creating-a-basic-windows-runtime-component-in-cpp-and-calling-it-from-javascript-or-csharp.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @dchstudios, and thanks for filing this issue. Note that UWP JavaScript apps aren't supported in Visual Studio 2019. Are you using VS2019? I've published a change to this topic to make this clear, and to recommend VS2017 for that particular section of the topic.

Thanks again!
Steve

**Comment by dchstudios** [comment]
Yeah I installed Visual Studio 2019... It'd be nice to not have to install more than one version to be sure.  Although I did install Visual Studio Code too, but had yet to launch it. After going back to read up on what does what, it looks like Visual Studio Code is supposed to support Javascript And C++ too...  That's just really strange that Visual Studio would neglect Javascript. But stranger yet that MS would need to make two different programming apps to begin with. Why not just have One, and then have it have an option to have fewer features or streamlined like Code is supposed to be, according to the description? It'd be like choosing Dark Mode vs Light Mode or something.. Choose what windows and tabs in layout you want out, so then you can choose your own complexity on the fly, pending on what your current project is...? Anyways, I guess now I'm off to see what Visual Code has for tutorials. 
OK thanks for getting back!

**Comment by stevewhims** [comment]
Thanks for the update, @dchstudios. I'll go ahead and close the issue now.

If you'd like, [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is a good channel to lobby for a change, a feature, or to make a suggestion.

Thanks!
Steve
