### ISSUE TITLE
What about Desktop Bridge apps handling activation?

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/windows-uwp#2333]
There should be a link or some info on how Desktop Bridge apps should handle activation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6579b616-2bc6-9a98-f30e-efc0c538f303
* Version Independent ID: 1fe1d869-7eec-2f98-5d5b-b4e6cd294dd6
* Content: [Handle app activation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/activate-an-app)
* Content Source: [windows-apps-src/launch-resume/activate-an-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/activate-an-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Thank you, I'm investigating! :)

-Steve

**Comment by stevewhims** [comment]
Closing, since we're discussing this over email.
