### ISSUE TITLE
Dead readme link for Microsoft.Windows.CppWinRT NuGet

### ISSUE THREAD

**Issue by JosephMart** [MicrosoftDocs/windows-uwp#2334]
The `readme` hyperlink in this snippet on the page is dead.

> Alternatively, manually add the following property to your .vcxproj file using the C++/WinRT project property page in Visual Studio. For a list of similar customization options (which fine-tune the behavior of the cppwinrt.exe tool), see the Microsoft.Windows.CppWinRT NuGet package readme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853d8f9e-c1eb-7fe8-4ce2-a476d8cb1fc9
* Version Independent ID: 924da36c-5517-190d-edda-5bd500830d81
* Content: [Move to C++/WinRT from C++/CX - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JosephMart, and thanks for filing this issue. I've published a fix to the topic, so that's live now.

I'll go ahead and close this issue.

Thanks again!
Steve
