### ISSUE TITLE
Proposed ListView filtering approach looks sub-optimal

### ISSUE THREAD

**Issue by jehumb-havok** [MicrosoftDocs/windows-uwp#2335]
Does the filtering approach on this page really constitute the recommended approach? I find it very hard to believe. First, because the "filtering" here is arguably not a filtering at all, it consists in making a copy of the data and rebuilding a collection each time the "filter" changes, which may work for very small collection but doesn't sound like it will scale at all. Second because -- and I am no WPF expert so I might be wrong here -- but I think that each single call to Add() and Remove() on the ObservableCollection will raise a collection changed event, instead of batching all those changes (which conceptually are a single change, a change of filtering) into a single event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a9f9e2-b0e9-097e-69b9-4b3f4e682dc5
* Version Independent ID: 7d26a4de-6138-e16f-c4c0-23e02f1e896b
* Content: [Filtering collections - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/listview-filtering?source=docs#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/listview-filtering.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/listview-filtering.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by anawishnoff** [comment]
Hi  @djee-ms, this is the recommended approach for a ListView. @ranjeshj, our dev lead, may be able to back me up here. Another approach that we explored (possibly more intuitive) was to use an [AdvancedCollectionView ](https://docs.microsoft.com/en-us/windows/communitytoolkit/helpers/advancedcollectionview)from the Windows Community Toolkit that has "built-in" filtering capabilities. We did not use this in our example as we wanted to rely on external/other libraries as little as possible. 

Filtering is much more intuitive and performant when it's done on an ItemsRepeater, as you can implement interfaces such as [IKeyIndexMapping](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.ikeyindexmapping?view=winui-2.3).

Let me know if you have any specific suggestions that could improve this sample. Thanks!

**Comment by jehumb-havok** [comment]
Hi @anawishnoff, thanks for the reply. I didn't know about the `ItemsRepeater`, but looking at the example in the XAML Controls Gallery (which is very useful by the way!) it seems that it's doing the same kind of "filtering" by rebuilding an entire collection. In any case my current use case is a small list so performance is not a concern. Thanks for confirming.
