### ISSUE TITLE
MonoGame build Error

### ISSUE THREAD

**Issue by lukasstauffenberg** [MicrosoftDocs/windows-uwp#2336]
Here is the link for the Monogame build error (sprites, jpg, png) in Visual Studio 2019:

https://www.microsoft.com/en-us/download/confirmation.aspx?id=40784

If you cannot open the Content.mgcd via the Pipetool you have to add a new source (  path of the Monogame App).

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 43b55ec8-00ba-dd3f-3fe8-dae000b588ba
* Version Independent ID: dd1b048f-b8c8-091c-8dcc-342a1fd75843
* Content: [Erstellen eines UWP-Spiels in MonoGame-2D - UWP applications](https://docs.microsoft.com/de-de/windows/uwp/get-started/get-started-tutorial-game-mg2d#feedback)
* Content Source: [windows-apps-src/get-started/get-started-tutorial-game-mg2d.md](https://github.com/MicrosoftDocs/windows-uwp.de-de/blob/live/windows-apps-src/get-started/get-started-tutorial-game-mg2d.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Apologies for the delayed response.

The MonoGame tutorial is no longer being actively supported, and has been de-listed from our table of contents and from internal links for some time. In fact, the page itself will formally be removed shortly.

I apologize that you ran into trouble with it, but I'm afraid that, as it's being discontinued, we won't be applying fixes to the content.
