### ISSUE TITLE
Unable to facilitate x:Bind between scopes

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/windows-uwp#2337]
Hi,

I used to set the `DataContext` to lower scopes whenever necessary, so I can use shorter binding expressions: (`ViewModel` is of type `ContactViewModel`, that exposes a `Phones` collection property):

```xaml
&lt;Page DataContext="{Binding ViewModel}"&gt;
  &lt;ListView ItemsSource="{Binding Phones}"/&gt;
&lt;/Page&gt;
```

I'm trying to use the above with `x:Bind` as follows:

```xaml
&lt;Page DataContext="{x:Bind ViewMode}"&gt;
  &lt;ListView ItemsSource="{x:Bind Phones}"/&gt;
&lt;/Page&gt;
```

But I get the following error:
&gt;XLS0432: The property 'Phones' was not found in type 'ContactsPage'. | MyProject.Client.UWP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd64d43-7b7b-abed-ff27-fafa2b82df0f
* Version Independent ID: 6c349724-5273-3463-7d7e-b685a89f093f
* Content: [xBind markup extension - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension)
* Content Source: [windows-apps-src/xaml-platform/x-bind-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/x-bind-markup-extension.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
x:Bind on a Page (or other x:class markup) binds to properties on the backing class, not to the DataContext like {Binding} does. So if this markup is for a class named ContactsPage, `{x:Bind Phones}` is looking for a ContactsPage.Phones property. 

So your best solution might be the more verbose `{x:Bind ViewModel.Phones}`. You could also suggest this as a new feature by [posting an issue to the repo](https://github.com/microsoft/microsoft-ui-xaml/issues).

**Comment by weitzhandler** [comment]
@MikeHillberg 

>You could also suggest this as a new feature by [posting an issue to the repo](https://github.com/microsoft/microsoft-ui-xaml/issues).

Done: https://github.com/microsoft/microsoft-ui-xaml/issues/2237

**Comment by hkhmsft** [comment]
Thanks @MikeHillberg for the answer and @weitzhandler for filing the suggestion. If anything else arises, feel free to reopen the thread.
