### ISSUE TITLE
Doesnt Work and Incomplete

### ISSUE THREAD

**Issue by deanchalk** [MicrosoftDocs/windows-uwp#2338]
This example code doesnt work, with a variety of build errors as soon as you add the idl file. It seems that there are steps missing. Also the code is incomplete - the BgLabelControl.cpp boilerplate is still missing implementations for the default generated members. I was hoping that this example page would allow you to just do something that just works, but it seems that you need to do a lot more than what is described in order to achieve anything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a199ae-561b-98b6-8cf0-101aedbfe599
* Version Independent ID: a8091c04-868d-51aa-f4d1-207c5c795235
* Content: [XAML custom (templated) controls with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by deanchalk** [comment]
Closed because t was not an issue, my mistake

**Comment by stevewhims** [comment]
Thanks, @deanchalk! However, I have updated the topic (so that the code listings are complete and can just be copied-pasted). Previously it was necessary to see where in the file to insert and delete methods. That change is live now.

Thanks!
Steve
