### ISSUE TITLE
WinUI + Custom UWP Control?

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-uwp#2341]
I followed all the steps above and it works perfectly (thanks for updating this article) for standard custom controls. However, my custom control has controls from the WinUI library. In my UWP application project, I tried to include my XamlControlsResources under the XamlApplication tag in App.xaml, and placed WinUI controls in my custom control. (CustControl.xaml) The solution compiles fine, but throws an exception during runtime: 0xC000027B: An application-internal exception has occurred.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62891dc-cad0-0ea2-66c3-a5b58d9e3f9a
* Version Independent ID: 911ab9f0-1c11-b2bf-9ecf-9fbed29df211
* Content: [Host a custom UWP control in a C++ Win32 app using the XAML Hosting API](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us. A couple of questions for you:

- Which version of the Microsoft.UI.Xaml NuGet package are you installing to your UWP project where you define the custom control? 
- After installing the NuGet package, did you add the projected headers to your pch.h file as directed in [this WinUI article](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started#additional-steps-for-a-cwinrt-project)?

I'm following up with the engineering team that owns XAML Islands functionality to clarify some details about mixing WinUI controls with a custom control that is hosted in a XAML Island in a native C++ application. When the investigation is complete, I'll update this walkthrough with additional steps for hosting WinUI controls. 

So far, it looks like this should work in the following scenarios:

- If your application is packaged and run from MSIX, this should work with the latest release version of the Microsoft.UI.Xaml NuGet package (2.3.200213001).
- If your application is unpackaged/not using MSIX, this should work with the latest prerelease version of the Microsoft.UI.Xaml NuGet package (2.4.0-prerelease.200322001)

In my testing, I am seeing some issues with the first scenario and am investigating with the engineering team. I will reply back to this issue as soon as I know more.

**Comment by AzAgarampur** [comment]
Hey mcleanbyron,

I am installing version 2.3.200213001 of the WinUI Library. Also, I did add all the header files to my precompiled header file as the article you linked describes. My application is unpackaged;it is not using MSIX packaging.

**Comment by mcleanbyron** [comment]
Since your application is unpackaged, please try using the latest prerelease version of the WinUI NuGet package (in the Nuget Package Manager window, you'll need to select the "Include prerelease" checkbox to see the prerelease versions of this package). According to the latest info I have from the product team, right now it's by design that unpackaged applications that use XAML Islands must use a prerelease version of the WinUI NuGet package (due to the differences in the ways that prerelease and release versions of NuGet packages are deployed).

**Comment by AzAgarampur** [comment]
Alright, it works perfectly when I use the prerelease package.

**Comment by AzAgarampur** [comment]
Hey mcleanbyron,

Sorry to bother you once again, but I noticed a small problem while using the prerelease WinUI package. Most fluent design styles, like `ButtonRevealStyle` are unrecognized by the XAML editor. In addition, most fluent brushes aren't functional anymore. For example, reveal highlight and Acrylic always use the fallback color. (For Acrylic, I have tried both the platform `AcrylicBrush` and the WinUI `AcrylicBrush`). This was not a problem when I was not using the WinUI package. However, if I create my `AcrylicBrush` or `RevealBorderBrush` from my Win32 HostApp (not the custom xaml control), the brushes work properly.

If I add the same WinUI prerelease to `C++/WinRT UWP` app, all fluent styles work properly and fluent styles are registered in the XAML editor.

**Comment by mcleanbyron** [comment]
I'm sorry you're running into this. Unfortunately, this thread has grown beyond the scope of issues with the docs. For product feedback like this against WinUI, please submit your feedback to the [WinUI product repo](https://github.com/microsoft/microsoft-ui-xaml). That repo is managed by members of the WinUI product team, and they should be able to triage and respond to your feedback.

**Comment by AzAgarampur** [comment]
Alright, sorry about that. I'll go ahead and submit my problem to the WinUI repo.

Thanks.
