### ISSUE TITLE
Using IL2CPP the correct keyword is ENABLE_WINMD_SUPPORTT

### ISSUE THREAD

**Issue by wagenheimer** [MicrosoftDocs/windows-uwp#2344]
On Unity using IL2CPP, #NETFX_CORE does not work anymore.
The note here says to use UNITY_WSA_10_0, but that is wrong. The correct is ENABLE_WINMD_SUPPORT as you can see on the following Unity Documentation :
https://docs.unity3d.com/Manual/windowsstore-code-snippets.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73baa8e9-fc26-107a-0f84-aa40e41fb0aa
* Version Independent ID: 011e4152-4342-f79f-0405-54520683eddf
* Content: [Missing .NET APIs in Unity and UWP - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/missing-dot-net-apis-in-unity-and-uwp#feedback)
* Content Source: [windows-apps-src/gaming/missing-dot-net-apis-in-unity-and-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/missing-dot-net-apis-in-unity-and-uwp.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the heads up, @wagenheimer. I have an update going through the publishing pipeline now. That should be live by end of day tomorrow at the latest.

-Steve

**Comment by hkhmsft** [comment]
Thanks @wagenheimer for pointing this out and @stevewhims  for the speedy fix.
