### ISSUE TITLE
getStartTime syntax incorrect

### ISSUE THREAD

**Issue by urdaalex** [MicrosoftDocs/windows-uwp#2345]
DateTime SecureBrowser.settings.getStartTime(); should be changed to SecureBrowser.security.getStartTime()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75a82cd-e530-bc8e-b822-04cd0138dfd1
* Version Independent ID: 89efbaaf-77f3-6fbe-0616-29c129b4f475
* Content: [Take a Test JavaScript API. - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/apps-for-education/take-a-test-api#feedback)
* Content Source: [windows-apps-src/apps-for-education/take-a-test-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/apps-for-education/take-a-test-api.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just checked in a fix. Should be published shortly.
