### ISSUE TITLE
Please explain that broadFileSystemAccess requires Windows Settings level Permissions

### ISSUE THREAD

**Issue by trainingmode** [MicrosoftDocs/windows-uwp#2348]
After a few hours of debugging and an endless amount of dead ends, I finally found that to debug an app with broadFileSystemAccess, you must set the app's permissions from within your Windows Settings while the app is actually running.

1. While the app is running/debugging, navigate to your file system settings by opening Settings > File System > Choose which apps can access your file system.

2. You should now see your app. Tick the setting to allow access and your app should close.

3. Rebuild it and your app should now have broadFileSystemAccess.

If the app is not running, there is a good chance that it will not show up here. I've also had to reload these permissions during a random amount of builds by having to run the app, untick and retick permissions, and then rebuild the app.

![appaccess](https://user-images.githubusercontent.com/52793789/79028869-b4d4e600-7b46-11ea-8c43-6061566d8914.jpg)

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
