### ISSUE TITLE
MessageWebSocket description

### ISSUE THREAD

**Issue by arcadiogarcia** [MicrosoftDocs/windows-uwp#235]
In the [WebSockets page](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/websockets.md), MessageWebSocket is described as being "similar to a UDP to datagram socket". I find that claim surprising, since it literally it is built on top of TCP.

I understand that the goal of that table is to point that it is intended for frequent, small messages, as opposed to StreamWebSocket, but maybe there is a less confusing way to word it? Readers who are not familiar with the WebSocket protocol might understand (incorrectly) that the MessageWebSocket is not reliable, does not guarantee same order reception or does not include congestion control.

**Comment by stevewhims** [comment]
Thanks for the suggested revision, Arcadio! The change is now live here: https://docs.microsoft.com/en-us/windows/uwp/networking/websockets.
