### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by carltonsmith** [MicrosoftDocs/windows-uwp#2350]
The mongodb install didn't work, and there is nothing to do with Node.js in the article. The postgresql install worked, though

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08481e1e-9a3c-35f1-874a-a1d77e5b64a6
* Version Independent ID: 5ebf0c79-5675-e869-35fb-f71b91db08b0
* Content: [Get started connecting Node.js apps to a database](https://docs.microsoft.com/en-us/windows/nodejs/databases)
* Content Source: [hub/nodejs/databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/databases.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@carltonsmith Sorry that you've had trouble. Could you help me understand what didn't work for you in the MongoDB install process and determine whether this is an issue requiring an update to the docs?

**Comment by mattwojo** [comment]
Closing this issue as the install appears to work fine for me. @carltonsmith -- If you have a chance to provide more details about what's not working, I can do my best to help and make any necessary update to this guidance.
