### ISSUE TITLE
Adobe XD kit for Win32?

### ISSUE THREAD

**Issue by bhekking** [MicrosoftDocs/windows-uwp#2353]
Hi, will there be an Adobe XD toolkit for Win32? I do UX design for Win 32 apps, and we don't have any plans to use Windows 10/UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Design toolkits and samples for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#feedback)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
We have no plans to offer a Win32 toolkit at this time.
