### ISSUE TITLE
Documentation for IAsync* Links are leading to 404 page

### ISSUE THREAD

**Issue by namar0x0309** [MicrosoftDocs/windows-uwp#2355]
IAsyncActionWithProgress<TProgress>,
IAsyncOperation<TResult>, and
IAsyncOperationWithProgress<TResult, TProgress>.

Respectively, 

https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncactionwithprogress_tprogress_

https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation_tresult_

https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperationwithprogress_tresult_tprogress_

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db952f42-9d6e-d30b-0aed-e7de64a89987
* Version Independent ID: bea24c9a-3e1e-405d-d7cc-5a080e62ece2
* Content: [Concurrency and asynchronous operations with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @namar0x0309, the fix is now live. :)

-Steve
