### ISSUE TITLE
WPF app that has multiple targets

### ISSUE THREAD

**Issue by mylastsong18** [MicrosoftDocs/windows-uwp#2357]
I am trying to package up a WPF application I have and I have run into a wall and can't figure out what to do next besides give up. My app targets .Net Framework 4.8 and .Net Core 3.1 and 5.0 Preview. When building the package project after adding my application to it I get an error message that "Project targets 'net48;netcoreapp3.1;netcoreapp5.0' and it cannot be referenced by a project that targets .NetCore,Version=5.0. 

How can I fix this? Is there a way to tell the package project to create a package for each framework? Does this only work if your app targets a single .Net?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7844818-d0b7-f502-3a07-a4970401fdcf
* Version Independent ID: 1acada53-18fa-68a2-4211-c4c3236c856e
* Content: [Package and deploy with MSIX](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5#feedback)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-5.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-5.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you for reaching out to us, and I'm sorry you're running into this issue. Unfortunately, this repo is set up to track feedback and bugs on the documentation, and it is not an avenue for technical support requests. To get assistance with your issue, your best bet is to post a question on the [MSIX Tech Community](https://techcommunity.microsoft.com/t5/msix-packaging-and-tools/bd-p/MSIX-Packaging). Members of the product team that own the MSIX and desktop packaging technology monitor this community and respond to customer questions.

**Comment by mylastsong18** [comment]
> Thank you for reaching out to us, and I'm sorry you're running into this issue. Unfortunately, this repo is set up to track feedback and bugs on the documentation, and it is not an avenue for technical support requests. To get assistance with your issue, your best bet is to post a question on the [MSIX Tech Community](https://techcommunity.microsoft.com/t5/msix-packaging-and-tools/bd-p/MSIX-Packaging). Members of the product team that own the MSIX and desktop packaging technology monitor this community and respond to customer questions.

Thank you for the link and sorry for creating the issue. I've seen the docs feedback used for questions before so i thought it was okay. I now know its not meant for that. Thanks again and sorry
