### ISSUE TITLE
incorrect mention of std::function

### ISSUE THREAD

**Issue by rectified95** [MicrosoftDocs/windows-uwp#2358]
There are a few places where std::function is written instead of std::future, when discussing the asynchronous behavior provided by coroutines (eg. when talking about the wait_for method)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [More advanced concurrency and asynchrony with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rectified95, thanks for the heads up. I've published a fix, so that's now live. I'll go ahead and close the issue.

Thanks again!
-Steve
