### ISSUE TITLE
Hey, Is that possible to run DRM over PWA app inside UWP?

### ISSUE THREAD

**Issue by mr-pinzhang** [MicrosoftDocs/windows-uwp#2359]
I'm currently trying to integrate PlayReady DRM with XboxOne, our app is a web app inside UWP. But we are facing a problem that it said 'Not Support' when about creating media key. So is that possible to run PlayReady DRM inside a web app?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acfa12d0-f1bb-f4e7-39de-2f827319eb6d
* Version Independent ID: 09e5c000-6f7e-b79c-5e34-1f04ede0320d
* Content: [PlayReady DRM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/playready-client-sdk#use-playready-drm-on-xbox-one)
* Content Source: [windows-apps-src/audio-video-camera/playready-client-sdk.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/playready-client-sdk.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
PWAs only supported Encrypted Media Extensions (EME). More info: https://www.w3.org/TR/encrypted-media/
