### ISSUE TITLE
Description for documentsLibrary is misleading/inaccurate

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/windows-uwp#2360]
The documentsLibrary capability is said to provide access to the "user's Documents folder", but it does not.
It looks like the documentsLibrary is intended to access the Documents library (hence the name), which may or may not be a virtual location with no particular filesystem path, and not the Documents folder in the sense a normal Windows user would expect.
The "access to the folder" is also not the access to the folder, but instead some specific subset of programmatic abilities, like creating and enumerating files inside it, using specific API.
The use of Documents might be discouraged and restricted; it needs not be cryptic and misleading.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Good catch, and thank you for the feedback. I updated the row for the documentsLibrary capability to clarify that it controls programmatic access to the Documents library (which is a virtual composite of multiple folder locations) rather than the user's Documents folder.
