### ISSUE TITLE
How to use Scenario3_ServerForeground.xaml.cs 

### ISSUE THREAD

**Issue by githotto** [MicrosoftDocs/windows-uwp#2361]
Although the UWA BluetoothLE example seems very interesting, its solution does not work on my setup, and I'm missing a specific example on how to use the Scenario3_ServerForeground.xaml.cs!
Would love to download working example code for the Scenario[123] files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434f7419-559c-2f95-b39e-49f28da77ebe
* Version Independent ID: e7b0c356-b3f5-859f-96e0-5379eb2cae5d
* Content: [Bluetooth Low Energy - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-low-energy-overview#feedback)
* Content Source: [windows-apps-src/devices-sensors/bluetooth-low-energy-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/bluetooth-low-energy-overview.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hkhmsft** [comment]
Hi @githotto , thanks for submitting feedback. Could you please redirect your ask to the samples repo [found here](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BluetoothAdvertisement)? You can file an Issue, reference the sample name, and restate your question. The sample owners should be able to have an answer to your question.
