### ISSUE TITLE
Great tutorial so far

### ISSUE THREAD

**Issue by flotsam7jetsam** [MicrosoftDocs/windows-uwp#2363]
There seems to be a barrier in creating LOB apps with UWP. This tutorial is a hidden gem for getting started. Now I wish RadDataGrid would be opensource for Xamarin as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4973ee6-8a33-75d3-f942-129628377fdb
* Version Independent ID: 0c933c8f-6dbb-cb14-fce3-9ca724b18d82
* Content: [Create a customer database application - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/enterprise/customer-database-tutorial#feedback)
* Content Source: [windows-apps-src/enterprise/customer-database-tutorial.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/enterprise/customer-database-tutorial.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
We're glad you found it useful! Let us know if you discover any issues with the article.
