### ISSUE TITLE
Clarify ToastGenericAppLogo icon sizing and supported formats

### ISSUE THREAD

**Issue by stevennyman** [MicrosoftDocs/windows-uwp#2364]
The ToastGenericAppLogo part of the "App logo override" section of this page states that "Image dimensions are 48x48 pixels at 100% scaling". Does this mean that we should try to provide a 240x240px PNG to provide a full resolution logo when displays are scaled to the current Windows maximum of 500%? Would providing an even higher resolution image be beneficial?

Also, is there a list of supported image formats for icons delivered over HTTPS?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a230de61-3424-1cfc-2556-d0ae6c29448b
* Version Independent ID: b30f9eb9-0f2f-178b-3b92-deca4d466588
* Content: [Toast content - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts#app-logo-override)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by hickeys** [comment]
Thanks for pointing out the lack of clarity here. I've added a note about the scale factors we recommend supporting. These changes should be published shortly.

Regarding HTTPS icons, they can be of any format that a local icon can be.
