### ISSUE TITLE
Windows.Foundation.EventHandler<Object> is inaccessible due to its protection level

### ISSUE THREAD

**Issue by radujipa** [MicrosoftDocs/windows-uwp#2373]
Please update docs about Raising events in Windows Runtime components (https://docs.microsoft.com/en-us/windows/uwp/winrt-components/raising-events-in-windows-runtime-components) to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32e7021-a1d2-5375-f01b-fbd6547e85ba
* Version Independent ID: 6c3c12a7-1998-b8e4-213f-19a54fd67770
* Content: [Raising events in Windows Runtime components - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/raising-events-in-windows-runtime-components#option-2-use-eventhandlerobject-but-lose-type-information)
* Content Source: [windows-apps-src/winrt-components/raising-events-in-windows-runtime-components.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/raising-events-in-windows-runtime-components.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by MikeHillberg** [comment]
Specifically the update should explain that this cannot be used from c#, where it gets projected to System.EventHandler<T>, so that should be used instead. (It _is_ accessible in the c++/winrt projection)

**Comment by stevewhims** [comment]
Hi, @radujipa, and thanks for filing the issue. I've published a fix, and that's now live. The topic still has a couple broken links to event handler types (I fixed the couple that I spotted), but those will be fixed in a different work item. So I'll go ahead and close this issue now.

Thanks to @MikeHillberg for the info!

Thanks again!
Steve

**Comment by radujipa** [comment]
Spotted the note in Option 2 section. Thank you for the clarification!
