### ISSUE TITLE
I could use more guidance on recommended spacing

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/windows-uwp#2374]
I could use more guidance on recommended spacing for at least the following points:
- I see there is a gutter size recommendation ( = horizontal spacing). Is there any vertical spacing recommendation?
  - how much space should I put before / after headings, other content?
  - are there recommendations for spacing to put between the levels of the typography hierarchy?
  - at page level?
  - at section level?
- spacing can be done using padding or margin. When to use what? Is there a recommended approach? Do you start with the page size and work from the outside to the inside? Or do you start with the smallest control and build around that?
- I find there is a lot of topic overlap between this page and https://docs.microsoft.com/en-us/windows/uwp/design/style/spacing#fluent-standard-sizing

Could you please add guidance for that to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ce8de2d-cfd8-202a-87a8-14d67ef7a328
* Version Independent ID: c6ed23c1-f6e0-1433-e90f-7f539e3e3060
* Content: [Alignment, margin, and padding for layout - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/alignment-margin-padding)
* Content Source: [windows-apps-src/design/layout/alignment-margin-padding.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/alignment-margin-padding.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by hansmbakker** [comment]
Also, on https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/forms#spacing there is written in the text what size elements should have and what margin they should have.

I would find it much easier to digest all information if there could be (more) visual schemes with recommend sizes & margins in these docs. It is very difficult to keep an overview of spacing recommendations as it is now, and a lot is unclear.

Besides, it seems that there was information in [this UWP design guidelines PDF](http://download.microsoft.com/download/2/4/A/24A81A29-77CF-4AA5-967E-64E42554F21B/UWP%20app%20design%20guidelines%20v1509.pdf) that is not available anymore online in the online documentation.

**Comment by hansmbakker** [comment]
Please also see this older Reddit thread where people ask for the same:
https://www.reddit.com/r/WPDev/comments/6x0m97/uwp_design_guidelines_with_control_dimensions/

It would be great if you could somehow address this need.

**Comment by mdtauk** [comment]
Spacing between controls, similar to internal guidance for the Settings app.  Your Phone is an application with inadequate vertical spacing between elements.

![image](https://user-images.githubusercontent.com/7389110/79978465-e24f5700-8497-11ea-89a4-4be6f3832669.png)

![image](https://user-images.githubusercontent.com/7389110/79978593-1296f580-8498-11ea-9a43-d9c2bba24c00.png)

**Comment by hansmbakker** [comment]
@chigy this is the topic that was discussed during todays focus group on design systems. Could you please share this with your colleagues?

cc @niels9001 @hickeys

**Comment by ejlayne** [comment]
@hansmbakker thank you again for this feedback from the focus group, and we are indeed passing it along to the Fluent UI team.

**Comment by mdtauk** [comment]
Material Design's documentation includes redlines and values for sizes and positions.

WinUI could do with some of this, included in it's controls and layout sections.

For things like app settings, I would like to see some guidelines, matching those used by the Windows Settings app.

**Comment by hansmbakker** [comment]
Is there any update to give on this?

**Comment by hansmbakker** [comment]
Also: I see that for Windows 8.1 there was [more guidance](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh872191(v=win.10)?redirectedfrom=MSDN) on how a application page could look like - e.g. how to position a page header, where to put content.
For windows 10, there seems to be no such guidance (there is guidance on typography but not on the margins/padding of common elements).

On https://blogs.windows.com/windowsdeveloper/2013/11/11/xaml-text-improvements-in-windows-8-1/ I see more details about how to properly align text, which I cannot find in the [typography section of the UWP documentation](https://docs.microsoft.com/en-us/windows/uwp/design/style/typography).

**Comment by hickeys** [comment]
Thank you for this feedback. I know this will be an unsatisfying response, but the scope of the request here is too large to be tracked via a GitHub issue. I'm going to close this issue and track this request via an internal internal work item.
