### ISSUE TITLE
Simple app using the example provided seems to lock up (Picker freezes without allowing any choices.). 

### ISSUE THREAD

**Issue by jpcoates** [MicrosoftDocs/windows-uwp#2379]
Simple app using the example provided seems to lock up (Picker freezes without allowing any choices.). Currently testing with Microsoft Visual Studio Community 2019, Version 16.5.4.

**Comment by GrantMeStrength** [comment]
Hi - I'm sorry that it's taken so long to get to this issue. If this is still an issue, could you provide a link to the topic or sample in question so we can check if there is a problem? Thanks! -john

**Comment by hickeys** [comment]
Given the age of this issue, I'm going to close it. If this continues to be an issue, please reopen with a comment regarding which sample you're using, or file a new issue.
