### ISSUE TITLE
Is the guidance up to date? 

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/windows-uwp#2380]
Microsoft has recently been using icons without a backplate.

My opinions below:
Android 8 and above force apps to use adaptive icons. Android 7 and below have "shapeless" icons
iOS and iPadOS have "shaped" icons 
What's the deal with Windows 10? 7 has shapeless. 8-10 have shaped. How about now?
Adaptive icons wouldn't be particularly bad, as long as the user can customise the OEM's default and if users could make an app ditch the white background.
I've mentioned it, now I have to talk about it. yeah nah, i'll get someone else to do it for me https://medium.com/swlh/let-s-talk-about-white-app-icons-ce2e83b9eb86 
Google and Apple both are guilty. Google especially though. Google made a shapeless Maps icon and on Android 7 and below it has a white background lmfao
then again, there's mobile vs desktop (iOS vs macOS) but Microsoft and other companies make icons for both anyway. 
all of the apps that have these new icons have hardcoded blue splash screens except for OneNote too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287ed7e0-5cbc-bf87-360c-5c5a47b451d0
* Version Independent ID: 87cd355a-d27b-47cc-1be5-951653cf52f1
* Content: [App icons and logos - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos)
* Content Source: [windows-apps-src/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/app-icons-and-logos.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mdtauk** [comment]
Icon and Tile asset documentation should be refreshed and updated

**Comment by NickeManarin** [comment]
They should add guidelines or tutorials for people trying to design icons using the fluent design language.

**Comment by hickeys** [comment]
Thank you for the feedback. I agree that the icon guidance needs to be updated, but some of the comments in this issue are beyond the scope of this repo. Issues here are for documentation changes only.

I've taken the feedback here and am tracking it internally. I know that isn't the most satisfying resolution, and I'm sorry. The core issue here with respect to documentation is valid, and it will be addressed in future documentation updates.
