### ISSUE TITLE
What about WinRT runtime components?

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/windows-uwp#2381]
Would be good to a have a section on those.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889d5484-0d90-b525-fa3c-69d8f6c9bb0b
* Version Independent ID: f49ccb81-5569-afcf-779a-aab24b1c4c3a
* Content: [Windows Runtime components - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/#feedback)
* Content Source: [windows-apps-src/winrt-components/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/index.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @fman028, and thanks for filing this issue. I've now updated this topic (see the **Note** at the top) with a link to content that guides the reader through using C++/WinRT to create a Windows Runtime Component. The target topic in question is focused on authoring events, but it so happens that the walkthrough involves creating and consuming a C++/WinRT WRC. So I felt like that covered the scenario adequately. After following that walkthrough, do you have additional specific tasks/scenarios that aren't covered and are unclear?

Thanks!
Steve

**Comment by fman028** [comment]
Oh wow that was fast!  I ended up figuring out WinRT WRCs this morning :)  It looks like that events walkthrough seems to cover the main points I got stuck on (adding a reference to BankAccountWRC.winmd and the .h file include "#include <winrt/BankAccountWRC.h>").  Thanks for following up!

**Comment by stevewhims** [comment]
I'll go ahead and close.

Thanks again!
Steve
