### ISSUE TITLE
Missed a step

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [MicrosoftDocs/windows-uwp#2382]
Between step 8 and 9 there should be the following command. You can't even run step 9 without it.
$ nvm use 12.16.2
Or whichever version you have installed.
Thanks for the tutorial though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2657da-0749-4fec-ab1d-2f04828e57a6
* Version Independent ID: f4541fe1-5c0b-3d6c-b122-363a383b12f2
* Content: [Set up NodeJS on native Windows](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows#feedback)
* Content Source: [hub/nodejs/setup-on-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for the contribution @xCONFLiCTiONx! Resolved: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/691 
:)

**Comment by xCONFLiCTiONx** [comment]
Sorry to bring this back up but just a minor issue with it. Again, sorry, I'm not trying to be one of those doosh bags that troll. I'm just trying to help.

**You have:**
_9. After installing the Node.js version numbers you need, select the version that you would like to use by entering: nvm use <version> (replacing <version> with the number, ie: nvm install 12.9.0)._

**It should be:**
_After installing the Node.js version numbers you need, select the version that you would like to use by entering: nvm use <version> (replacing <version> with the number, ie: nvm use 12.9.0)._

_**Simply just change the last part "install" to "use".**_


**For consistency you might consider changing:**
_7. Install the latest stable LTS release of Node.js (recommended) by first looking up what the current LTS version number is with: nvm list available, then installing the LTS version number with: nvm install <version> (replacing <version> with the number, ie: nvm install 12.14.0)._

**To:**
_Install the latest stable LTS release of Node.js (recommended) by first looking up what the current LTS version number is with: nvm list available, then installing the LTS version number with: nvm install <version> (replacing <version> with the number, ie: nvm install 12.9.0)._

**_Thank you all so much for all your hard work!_**

**Comment by mattwojo** [comment]
Thanks -- good catch. Cleaned those up: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/694
