### ISSUE TITLE
Change  hierarchy structure in the RootNode property after first publication 

### ISSUE THREAD

**Issue by KusiTec** [MicrosoftDocs/windows-uwp#2383]
Please have a look at stackoverflow:
https://stackoverflow.com/questions/61428921/reload-treeview-with-new-root-nodes-and-new-item-source

Thanks much for answering

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b245536a-3179-ff1e-dfd5-76898d07381b
* Version Independent ID: 145609fa-8e77-5878-3402-7bcc69df8ccc
* Content: [Strukturansicht - UWP applications](https://docs.microsoft.com/de-de/windows/uwp/design/controls-and-patterns/tree-view#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp.de-de/blob/live/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by KusiTec** [comment]
This issue is solved. Dynamic building of the tree through binding data source by the item source property in the tree view control, without node operations.

**Comment by hkhmsft** [comment]
Glad your issue got resolved! If there are any suggestions you'd like to make to our documentation, feel free to contribute to our public docs.
