### ISSUE TITLE
How does one contact support? My developer account is stuck at verification process.

### ISSUE THREAD

**Issue by vlad-ed-git** [MicrosoftDocs/windows-uwp#2387]
I really have to say this, I have never encountered a more frustrating app deployment process in the 7 years of my professional developer workings! Like wtf! You ask for developer info (work account), I submit the info, then I get a "failed to verify message, update your info" , which just takes me back to the same form that asked the initial info. What kind of service is this ?! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f30d12-71bf-798e-731b-7d20ff618bf4
* Version Independent ID: 936a38a3-8e84-7a48-725b-b3eb3607ef68
* Content: [Manage account settings and profile info - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/manage-account-settings-and-profile?redirectedfrom=MSDN#feedback)
* Content Source: [windows-apps-src/publish/manage-account-settings-and-profile.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/manage-account-settings-and-profile.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Sorry to hear this. Here are all of the developer support resources, for completeness.

[Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by vlad-ed-git** [comment]
This is the exact problem. You did not even read the issue. I am asking
about developer account verification process! You gave me a bunch of links
for support "resources"! The very first line on my report says "contact
support"! I don't need a bunch of documents to read through, I have already
done that! And you have the audacity to close the issue! Not even waiting
for my response. If you hate your  job or don't know how to do it, just
quit.

On Tuesday, April 28, 2020, Alexis Ho-Liu <notifications@github.com> wrote:
> Sorry to hear this. Here are all of the developer support resources, for
completeness.
>
> Microsoft Q&A offers relevant and timely answers to your technical
problems from a community of experts and Microsoft engineers.
>
> For community assistance with development questions, there are our
forums, and StackOverflow.
> The Windows developer support site explains other support options.
> The Visual Studio developer community is available, and responsive. The
former User Voice feature is now there on the Suggest a feature tab, if you
want to lobby for a change, a feature, or to make a suggestion.
> For developer issues, or suspected product bugs, there's Microsoft
Support; a support engineer will look at the repro and see whether the
issue is a Microsoft product bug, or something else. If it's a bug with a
Microsoft product then the ticket will be free of charge.
>
> If you receive assistance via any support resource, and you believe that
information would help us improve the docs, we'd appreciate if you came
back and let us know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/TdzYU1eIe33-ma4e3sNqqdLdn0W0MFLOuqIWcmFovvyGoK38CMVPTppDmxHg76kpm48dwajMGQ1pzjzi2Me-8oSUhFqAieCrrut8RfXSnohJXzU8KCv7cGz-x7JVUGwpqVaZEZMenIoGLIDRJU5JUSrWCJ1MogEYLT0X9JxzheghB-QOGl2zQnRoqRFzHJcQUL8PKv_LlGsra2ltfU25iVL6-eaQfSBYdpCSeqKvuA=s0-d-e1-ft#https://github.com/notifications/beacon/AJGBW6Z4OMQJW3M5XSI37TLROX5SPA5CNFSM4MRG54GKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOET4F6TQ.gif>

**Comment by hkhmsft** [comment]
Hi @vlad-ed-git . In this case, could you restate the ask that you have requested in your initial submission? It seemed to me that you had encountered an issue submitting your information, which would fall under a support related question, not a documentation fix. 

Your initial ask was contacting support, and the resources I provided are meant to help you redirect your question to an appropriate support channel such as [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all), [Developer Network forum](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required),  [StackOverflow](https://stackoverflow.com/questions), [Windows developer support](https://developer.microsoft.com/windows/support), [Visual Studio developer community](https://developercommunity.visualstudio.com), and [Microsoft Support](https://support.microsoft.com/contactus).

If I misunderstood your question, let me know.

**Comment by vlad-ed-git** [comment]
Let me elaborate then.
I am opening a Microsoft developer account using a company email. In order
to publish an office add-on to the Microsoft Store.
This process requires a verification step which goes like this.
I got a form to fill some info, which I did, with accurate information.
Then I submitted that info.
Waited a few days and got back a message that says the verification could
not be completed. The options given are a. update info, which takes me back
to the same form, asking same info!Perhaps the logic here is that in case
someone had provided wrong info the first time, cause apparently we are
liars. But well, I gave correct info, so this option is just an endless
loop for me.
Option b. is to contact support. which is in form of a link, that when you
click, you are redirected to some documentation page, with zero info on how
to actually contact support.
Support is not the same as documentation! Support is I text or email or
call a group of helpful people, who then help.
So, my issue is, where is the link to a)support email or b)support live
chat or c)support phone numbers or even d. support p.o.box to send a letter
to, cause I honestly wouldn't be surprised by  this.
Sorry for my tone. You are probably not responsible for this so please re
direct me to those who are. Thank You.

On Tuesday, April 28, 2020, Alexis Ho-Liu <notifications@github.com> wrote:
> Hi @vlad-ed-git . In this case, could you restate the ask that you have
requested in your initial submission? It seemed to me that you had
encountered an issue submitting your information, which would fall under a
support related question, not a documentation fix.
>
> Your initial ask was contacting support, and the resources I provided are
meant to help you redirect your question to an appropriate support channel
such as Microsoft Q&A, Developer Network forum, StackOverflow, Windows
developer support, Visual Studio developer community, and Microsoft Support.
>
> If I misunderstood your question, let me know.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/ip4lt260myjfX9pXZuHWnqfma39W7h5uj7t7M9oYu42ROPjdQbLrV1mto78kicNZHwYHAzg49kHMsthXGr4yHtqd1JEM3vZ2Yr4FVxK0-tIt48rDeqJ0HaIhh5knSBHclizO1wiIeSo5qrL5MDaKsKmJ5cxEayC-1oyP40p4uuMVD9Yvqvz9F7aE1F7Xu875xsogHpCxdfvFpg8wCUFKuNzfnSXYciao6GiHbrVUTg=s0-d-e1-ft#https://github.com/notifications/beacon/AJGBW67TKILTRDBM7RU3QSTROZXUZA5CNFSM4MRG54GKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOET5JK7Q.gif>

**Comment by vlad-ed-git** [comment]
Your response better be a link to customer support for microsoft developers
or related support people, OR please, don't waste both our time, and just
dont respond。

On Tuesday, April 28, 2020, Alexis Ho-Liu <notifications@github.com> wrote:
> Hi @vlad-ed-git . In this case, could you restate the ask that you have
requested in your initial submission? It seemed to me that you had
encountered an issue submitting your information, which would fall under a
support related question, not a documentation fix.
>
> Your initial ask was contacting support, and the resources I provided are
meant to help you redirect your question to an appropriate support channel
such as Microsoft Q&A, Developer Network forum, StackOverflow, Windows
developer support, Visual Studio developer community, and Microsoft Support.
>
> If I misunderstood your question, let me know.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/ip4lt260myjfX9pXZuHWnqfma39W7h5uj7t7M9oYu42ROPjdQbLrV1mto78kicNZHwYHAzg49kHMsthXGr4yHtqd1JEM3vZ2Yr4FVxK0-tIt48rDeqJ0HaIhh5knSBHclizO1wiIeSo5qrL5MDaKsKmJ5cxEayC-1oyP40p4uuMVD9Yvqvz9F7aE1F7Xu875xsogHpCxdfvFpg8wCUFKuNzfnSXYciao6GiHbrVUTg=s0-d-e1-ft#https://github.com/notifications/beacon/AJGBW67TKILTRDBM7RU3QSTROZXUZA5CNFSM4MRG54GKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOET5JK7Q.gif>

**Comment by hkhmsft** [comment]
The links I provided are support links. I'll resurface them for your convenience. [Microsoft Support](https://support.microsoft.com/contactus) and [Windows developer support](https://developer.microsoft.com/windows/support).

**Comment by shoptool** [comment]
I had encountered an issue subm[i](https://shopfortool.com/gmail-sign-up-free-gmail-login-account-gmail-sign-in-on-www-gmail-com/)tting the information. It does work for me on the first stage
