### ISSUE TITLE
Transactional model diagram is not readable in dark theme.

### ISSUE THREAD

**Issue by ssyrell** [MicrosoftDocs/windows-uwp#2389]
The diagram in the "The transactional model" section is extremely difficult to read when the page is rendered using the dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8132995-4d33-d547-f743-37cd3b3f15c4
* Version Independent ID: 19465bc3-648d-6576-ea62-5b23b50531d5
* Content: [Best practices for writing to files - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/best-practices-for-writing-to-files?source=docs#feedback)
* Content Source: [windows-apps-src/files/best-practices-for-writing-to-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/best-practices-for-writing-to-files.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Corrected so that the diagram - although bright - is legible.
