### ISSUE TITLE
Trouble compiling "broadFileSystemAccess"

### ISSUE THREAD

**Issue by elielson-anjos** [MicrosoftDocs/windows-uwp#2392]
If you're having trouble compiling, put '&lt;rescap:Capability Name="broadFileSystemAccess" /&gt;' on top of all the other capabilities.

Someone forgot to tell that the order matters.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9b665f33-4a40-510a-86d3-019ba9c79c44
* Version Independent ID: df96e262-813d-9143-9d91-a29c49a01b4f
* Content: [Permissões de acesso a arquivo - UWP applications](https://docs.microsoft.com/pt-br/windows/uwp/files/file-access-permissions#feedback)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp.pt-br/blob/live/windows-apps-src/files/file-access-permissions.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by MadamLaunch** [comment]
I've tried that, and I'm still being told that it's an invalid child entity. Builds go through, but I don't have the access.

The element 'Capabilities' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' has invalid child element 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities'.

The warning message then goes on a tangent about every other namespace that has "Capability" as a child element.

**Comment by elielson-anjos** [comment]
@MadamLaunch Here the warning never went away, but I was able to build, and then read/write files system wide without bumping into "non authorized". 

Since it is a special feature that you need approval to use, maybe thats the intended behaviour.

**Comment by chausner** [comment]
It's worth noting that the file access must happen through the Windows.Storage APIs, e.g. StorageFile.GetFileFromPathAsync. The older File APIs in System.IO will continue to throw access denied exceptions.

Finally, file system permissions must be enabled explicitly by the user (Windows Settings -> Privacy -> File System). By default, it is disabled.

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
