### ISSUE TITLE
Add HoloLens-2 hardware acceleration support for H265.

### ISSUE THREAD

**Issue by payyavula** [MicrosoftDocs/windows-uwp#2394]
Could you please provide details for HoloLens-1 and HoloLens-2, its support for H264, H265 on HL1 and HL2. also clarify which has hardware acceleration support for encoding and decoding.

**Comment by drewbatgit** [comment]
Hello, sorry for the extremely delayed response on this issue.  I would suggest that you pose this question in the Hololens documentation repo. 

https://github.com/MicrosoftDocs/Hololens
