### ISSUE TITLE
Can't change tax profile

### ISSUE THREAD

**Issue by suxoikorm** [MicrosoftDocs/windows-uwp#2398]
I need to edit my tax profile. Im click on the edit button and have error. 
![image](https://user-images.githubusercontent.com/17691118/80508208-6d40bd80-8980-11ea-88f6-a773d00b77ad.png)
![image](https://user-images.githubusercontent.com/17691118/80508236-7762bc00-8980-11ea-857d-f85d12aaadab.png)
How can i edit my tax profile?

**Comment by hkhmsft** [comment]
Hi @SuxoiKorm , could you reach out to either [Windows developer support](https://developer.microsoft.com/windows/support) or [Microsoft Support](https://support.microsoft.com/contactus)? Unfortunately we only handle documentation fixes so I'm thinking these channels might help get an answer for you faster.

If you receive assistance via any of the support resources, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by suxoikorm** [comment]
The error went away when I did it through Edge, and not through Chrome. Thanks
