### ISSUE TITLE
Returning C style arrays

### ISSUE THREAD

**Issue by tewarid** [MicrosoftDocs/windows-uwp#2399]
I found this page lacking in information about how to return arrays in general, and C style arrays in particular. Unit tests in cppwinrt use com_array. I couldn't find a mention of com_array in this or adjacent pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d6f6d3b-a97d-3660-fde8-cebf73ef7968
* Version Independent ID: 8ff1309e-962a-d21e-7936-d2038c5839de
* Content: [Passing parameters into the ABI boundary - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/pass-parms-to-abi#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/pass-parms-to-abi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/pass-parms-to-abi.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tewarid, do you mind taking a look at Raymond Chen's blog post here (https://devblogs.microsoft.com/oldnewthing/20200205-00/?p=103398). Does that contain the info you're looking for? If so, I can see about working that into the topic.

-Steve

**Comment by tewarid** [comment]
Hi @stevewhims, thanks for the quick response, and for indicating that excellent blog post by Raymond Chen. It does cover what I am looking for.

**Comment by stevewhims** [comment]
Great, thanks for the confirmation! :) I've added a link to the blog post, so I'll go ahead and close.

-Steve
