### ISSUE TITLE
Backwards example regarding by val vs by ref?

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2400]
The documentation currently says:

&gt; You can accept a copyable parameter by value, instead of by reference. For example, change ```SomeClass``` to ```SomeClass const&```.

But I think it means the other way around:
You can accept a copyable parameter by value, instead of by reference. For example, change ```SomeClass const&``` to ```SomeClass```.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5961a97-ba23-0707-1a86-807084a97b31
* Version Independent ID: 5c1c753b-fe4e-0d58-f623-f7d43c166277
* Content: [Author APIs with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-apis.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @davidmatson, and thanks for letting me know. I've fixed that now, so I'll go ahead and close.

Thanks!
Steve
