### ISSUE TITLE
Broken API doc links

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2402]
In the [Delegate types for asynchronous actions and operations](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events#delegate-types-for-asynchronous-actions-and-operations) section, the following links are broken:
* [AsyncOperationProgressHandler](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.asyncoperationprogresshandler)
* [AsyncOperationWithProgressCompletedHandler](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.asyncoperationwithprogresscompletedhandler)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a5d7765-efa0-3077-7c2c-5e9b8341a340
* Version Independent ID: 4e73db08-5398-9416-d20e-0680ceb5e429
* Content: [Handle events by using delegates in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events#delegate-types-for-asynchronous-actions-and-operations)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/handle-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/handle-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @davidmatson, and thanks for filing this issue. I have a fix in the pipeline, and I'll track that until it's published. I'll close this for now.

-Steve
