### ISSUE TITLE
Floating point types should not be used to store currency values

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2403]
Floating point types can't store all values in the range x.nn. Using a float to store a bank account balance is an example of what not to do. See, for example:
http://wiki.c2.com/?FloatingPointCurrency

It's just an example here, but example code is often how programmers learn how to write production code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565e1bd5-9e15-fc88-8ccc-05d09cbde209
* Version Independent ID: 63b7ce5c-d2e7-d742-4fbd-b9729595a797
* Content: [Author events in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @davidmatson, and thanks for filing this issue. I've sent you an email, so let's work on this idea internally (perhaps you could submit a PR using the instructions I sent).

I'll go ahead and close this GitHub issue, since we don't need it to track.

Thanks again!
Steve
