### ISSUE TITLE
Typo -> "is not" should be "is"

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2404]
In [Awaiting a kernel handle
](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#awaiting-a-kernel-handle):
```c++
IAsyncAction Async(winrt::handle event)
{
    co_await DoWorkAsync();
    co_await resume_on_signal(event); // The incoming handle *is* not valid here.
}
```

I think it should say just "\*is\*" rather than "\*is\* not".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [More advanced concurrency and asynchrony with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#awaiting-a-kernel-handle)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @davidmatson, and thanks for filing this issue. I'll go ahead and take care of this, and I've emailed you internally, so I'll go ahead and close this issue for now since we don't need it for tracking.

Thanks!
Steve
