### ISSUE TITLE
Nit: historic should be historical

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2405]
I'd suggest changing:
&gt; because of the historic design of the framework
to:
"because of the historical design of the framework"

https://www.merriam-webster.com/words-at-play/everything-youve-ever-wanted-to-know-about-historic-and-historical

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3f98fd-a779-924f-02d1-18762114a7af
* Version Independent ID: 34cec207-abe4-0ee0-72f4-1f9b8e6cae91
* Content: [Strong and weak references in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/weak-references)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/weak-references.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/weak-references.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @davidmatson, and thanks for filing this issue. I'll go ahead and take care of this, and I've emailed you internally, so I'll go ahead and close this issue for now since we don't need it for tracking.

Thanks!
Steve
