### ISSUE TITLE
Debug/Test information is missing

### ISSUE THREAD

**Issue by ZodmanPerth** [MicrosoftDocs/windows-uwp#2406]
Information on how to debug/test the protocol launch needs to be added to this page.

Something like this answer on StackOverflow: https://stackoverflow.com/questions/23110487/how-to-debug-windows-store-app-onactivated-event

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efc62851-f8af-dde5-2e95-03d59a25ad81
* Version Independent ID: bf635b1d-f0b7-1fad-2445-ef9044e65a10
* Content: [Handle URI activation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation#feedback)
* Content Source: [windows-apps-src/launch-resume/handle-uri-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/handle-uri-activation.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
