### ISSUE TITLE
Adperformance not updated since 02-21-2020!

### ISSUE THREAD

**Issue by Martin-Stein** [MicrosoftDocs/windows-uwp#2408]
Hi,
my adperformance is not updated since 02-21-2020!
Please fix it, so that I can see my actual data.

Thanks,

Martin

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7361de4b-d8ca-fcac-b7e2-5b4d014e3daf
* Version Independent ID: 06dd75a0-a983-7059-01e6-f7e27f2e7ef5
* Content: [Analysieren der App-Leistung - UWP applications](https://docs.microsoft.com/de-de/windows/uwp/publish/analytics#feedback)
* Content Source: [windows-apps-src/publish/analytics.md](https://github.com/MicrosoftDocs/windows-uwp.de-de/blob/live/windows-apps-src/publish/analytics.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi @Martin-Stein  and thanks for submitting your issue through our channel. It seems you have a support related question. Unfortunately, that's outside of the scope of things we can offer a solution for. Here's the link to [Windows developer support](https://developer.microsoft.com/windows/support) and [Microsoft Support](https://support.microsoft.com/contactus).

If you receive assistance there, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
