### ISSUE TITLE
Long longer works with WIX

### ISSUE THREAD

**Issue by tommed** [MicrosoftDocs/windows-uwp#2409]
I've tried creating a WIX installer for producing the Shortcut necessary,
https://gist.githubusercontent.com/tommed/07aada312a1bf27cfcf67e16331be149/raw/e640eb74c01b1e280b33ef4bfb7df8e4091323e1/Product.wxs

However I get the error during installation:
Warning 1946, Property "{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}, 26" for shortcut "MyApp.lnk" could not be set.

I've also tried with "System.AppUserModel.ToastActivatorCLSID" but it doesn't like that either.
Also, read this page and tell me that this isn't the most over-the-top, complicated way just to get a toast message to appear from WPF or WinForms?!?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14e9484a-4921-2ee3-c93e-787a7b104f61
* Version Independent ID: 9e3db713-1558-7297-ef6d-53e5d87d4757
* Content: [Send a local toast notification from desktop C# apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by hickeys** [comment]
It looks like there's no actionable feedback here, so I'll go ahead and close the issue. Please open a new issue if you have feedback about the documentation that you'd like us to address. Otherwise, you might try contacting the WiX team if you've found a bug in their toolset.

Thanks,
Shawn
