### ISSUE TITLE
Links To How to Consume Toolkits

### ISSUE THREAD

**Issue by keithnicholson** [MicrosoftDocs/windows-uwp#2410]
I love the list of toolkits.  I've glanced at a couple, but I'm unsure how best to export items from toolkits to easily be used in a UWP app.  I've been searching Bing and just not finding the resources as I would expect.  Could you provide some assistance in this article?

**Comment by QuinnRadich** [comment]
The Design Toolkits are intended to provide templates and examples for combining controls within your UWP app. There's not a direct way to, say, export the visual display from a .psd directly to your app.

For information on how to implement these design ideas, see the rest of our design docs. For instance, you can find a specific control within the https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/ section and review the detailed overview there.

Thank you.
