### ISSUE TITLE
Upgrade installation script in instructions for setting up

### ISSUE THREAD

**Issue by alvarezskinner** [MicrosoftDocs/windows-uwp#2411]
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2#feedback)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Done. Thanks @alvarezskinner :)
