### ISSUE TITLE
Registering layout with built appxmanifest.xml crashes app

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#2413]
C# UWP hello world type of app. If I do `Add-AppxPackage -register` and  give it the path to the built appxmaniest.xml (not the one in the Appx layout folder), then the app installs but crashes on launch because it tries to use the full .net framework instead of .net core. Need more clear instructions on which AppXmanifest.xml file needs to be passed in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ee9c97-d766-6c25-eb40-0c7a2a41f908
* Version Independent ID: d17a0a28-ce1c-dd24-6b2d-05083a6e2809
* Content: [Deploy an app through loose file registration - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/loose-file-registration)
* Content Source: [windows-apps-src/debug-test-perf/loose-file-registration.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/loose-file-registration.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by asklar** [comment]
Fix is to follow the instructions in https://github.com/asklar/RegisterFromLayoutUWP.net

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @asklar - this seems like a product issue rather than a documentation issue. Do you agree?

**Comment by asklar** [comment]
Hey Karl !
The doc page says to register with the appxmanifest.xml file, but there are several, so my request was to update the doc page to clarify which one to pass as a parameter (since passing the wrong one will crash the app)
CC @srdjanjovcic to keep me honest on the details

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @asklar - Having another look at this and I'm not sure how to incorporate your instructions in https://github.com/asklar/RegisterFromLayoutUWP.net. They refer to a different topic (https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps). Can you create a PR on https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/loose-file-registration with your specific updates?
