### ISSUE TITLE
Should add a link to the WindowsCommunityToolkit control

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2414]
We have a MasterDetailsView control in the toolkit that can be used for this scenario: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/masterdetailsview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd4b0df-4564-2c87-4ed5-ea40bde54918
* Version Independent ID: f8caabee-0fa1-e02b-11b0-79d0cfd8b973
* Content: [Master/details - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/master-details)
* Content Source: [windows-apps-src/design/controls-and-patterns/master-details.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/master-details.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@michael-hawker, thanks for the suggestion. I've added the link, and the update should be live later today.
