### ISSUE TITLE
[c++/winrt][get started] add a note about #pragma

### ISSUE THREAD

**Issue by profnandaa** [MicrosoftDocs/windows-uwp#2419]
I was getting errors when building until I added `#pragma comment(lib, "windowsapp")` on `pch,h`; that I found on the [moderncpp.com site](https://moderncpp.com/2017/11/01/cppwinrt-in-the-windows-sdk/)

Could we have note about this in the getting started? Can be a huge stumbling block for someone just starting on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @profnandaa, and thanks for filing this issue. You don't have to explicitly link to WindowsApp.lib if you set up C++/WInRT in the recommended way. For more info and links, see the section in the FAQ about [WindowsApp.lib](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/faq#why-is-the-linker-giving-me-a-lnk2019-unresolved-external-symbol-error), and why you (nearly always) don't need to link to it. There are very corner cases where you do need to link explicitly, but those are extremely rare (often internal Microsoft devs do), and not recommended for customers. :)

The blog post you link to is a very early one, from 2017, so you don't need to do that any longer.

Thanks again!
Steve

**Comment by profnandaa** [comment]
Got it, thanks!
