### ISSUE TITLE
Very helpful documentation but  it is missing more info on customization 

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/windows-uwp#2420]
How we can change selected item highlight color for example.

I didn't use the Nuget package and I got this error:
The member "IsTitleBarAutoPaddingEnabled" is not recognized or is not accessible. 
It looks like that property doesn't exist anymore. I think you guys should add some notes about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69449df-a1ec-70dd-e563-0ad508733c47
* Version Independent ID: dc0e0acb-d92a-a039-5c16-f54a4b71d954
* Content: [Navigation view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#examples)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. We've added a note that the IsTitleBarAutoPaddingEnabled property requirtes WinUI 2.2 or later. It's not available in the non-WinUI version of NavigationView.
