### ISSUE TITLE
Learned a lot

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/windows-uwp#2421]
Very useful article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d04b1b4-83bd-b54f-8009-969ac052976b
* Version Independent ID: 921b50c1-a8aa-27d6-b1a6-fe6f2fdee07c
* Content: [Color in UWP apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/color)
* Content Source: [windows-apps-src/design/style/color.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/color.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks so much for the feedback @rogerms!
