### ISSUE TITLE
"uap3" namespace not specified

### ISSUE THREAD

**Issue by yoshiask** [MicrosoftDocs/windows-uwp#2422]
In order to use this, you have to add `xmlns:uap3="http://schemas.microsoft.com/appx/manifest/uap/windows10/3"`, which the docs don't mention (and requires either some prior knowledge or a bit of digging). Failing to include this namespace understandably prevents the app from building.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e251da-3cab-4aa0-2915-21189cf71bef
* Version Independent ID: b244b311-a0e5-185d-df82-1dadf3fe6416
* Content: [Enable apps for websites using app URI handlers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking#feedback)
* Content Source: [windows-apps-src/launch-resume/web-to-app-linking.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/web-to-app-linking.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for filing this @yoshiask. I've created a work item to include this information in the documentation. I will circle back once there are updates.

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
