### ISSUE TITLE
Inaccurate or out of date documentation

### ISSUE THREAD

**Issue by uallmight** [MicrosoftDocs/windows-uwp#2424]
The example for how to use the file picker shows the ability to use `await` however source code itself does not able such action. For UWP build 1809 (10.0 build 17763)

The only path forward appears to be to use the picker like so.

```csharp
            var picker = new FileOpenPicker
            {
                CommitButtonText = "Select",
            };

            picker.FileTypeFilter.Add(".json");
            picker.FileTypeFilter.Add(".xml");

            picker.ViewMode = PickerViewMode.List;

            StorageFile result = picker.PickSingleFileAsync().AsTask<StorageFile>();
            if (result != null) {
                ViewModel.FilePath = file.path;
            }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98368cc-a7d2-6770-7c8f-3cb2f500676f
* Version Independent ID: 88e3393d-38a9-5737-89e2-85543d52dbfa
* Content: [Open files and folders with a picker - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers#feedback)
* Content Source: [windows-apps-src/files/quickstart-using-file-and-folder-pickers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-using-file-and-folder-pickers.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for submitting this @uallmight. I've created a work item to look into this and make any necessary snippet changes to reflect the most current code. I will circle back here in this thread with any updates.

**Comment by alvinashcraft** [comment]
#reassign:alvinashcraft

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this @ualmight, and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

The documented code is currently working in both UWP (with minimum SDK target version 1809) and a new WinUI 3 project. There are no errors using the await keyword with these pickers so long as your method or event handler are decorated with the async modifier.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
#please-close
