### ISSUE TITLE
Awesome and simple example

### ISSUE THREAD

**Issue by ghd796** [MicrosoftDocs/windows-uwp#2430]
Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43a6232-d7f2-2600-20bb-2f26da456628
* Version Independent ID: 9fde14b7-b11b-97bc-f6f9-3dd9219b3f9a
* Content: [Launch the default app for a file - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-the-default-app-for-a-file#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-the-default-app-for-a-file.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-the-default-app-for-a-file.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
@ghd796 Thanks. We appreciate the feedback!
