### ISSUE TITLE
Payment Fields in query results need documentation

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2434]
The following field is in the output of the payment data query results. However, they are not documented. Can you please include the definition for these fields in the documentation?

CurrencyCode

Docs: https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary#payments
https://apidocs.microsoft.com/services/partnerpayouts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a40199-aaff-a750-b2df-cc8533606f0a
* Version Independent ID: 76160f31-f715-009a-e73e-202f8ed27006
* Content: [Payout reports - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
This item was added in an earlier update as part of a transition to a new report format. Accordingly, I'm closing this issue. Thank you for reporting the discrepancy.
