### ISSUE TITLE
Payment Fields in documentation don't appear in transaction query results

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2435]
Transactions: Microsoft Store Apps
The following fields are documented, but are not in the output of the payment data query results. Can you please update the documentation if this is the correct expectation?
earnedCurrencyCode
paymentCurrencyCode

Docs: https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary#payments
https://apidocs.microsoft.com/services/partnerpayouts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a40199-aaff-a750-b2df-cc8533606f0a
* Version Independent ID: 76160f31-f715-009a-e73e-202f8ed27006
* Content: [Payout reports - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
These items were removed in an earlier update as part of a transition to a new report format. Accordingly, I'm closing this issue. Thank you for reporting the discrepancy.
