### ISSUE TITLE
Some text is cropped from left.

### ISSUE THREAD

**Issue by jonitis** [MicrosoftDocs/windows-uwp#2437]
Starting from TappedEventArgs section there are lines with missing leftmost characters. E.g. "ichEditMathMode" is missing "R", "nagement" needs to be "Management" etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c68dc509-816d-26b2-4e61-c87e52171b6b
* Version Independent ID: 7d8d4517-28f1-19e5-a102-6bfa4ce21173
* Content: [Windows 10 Build 19041 API changes - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-19041-api-diff#feedback)
* Content Source: [windows-apps-src/whats-new/windows-10-build-19041-api-diff.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-19041-api-diff.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by Gavin-Williams** [comment]
Also, some of the previewteamview api's are in the section above where they should be.

**Comment by QuinnRadich** [comment]
Seems like issues related to a scripting bug. I've resolved them for now, and have trimmed out the truncated entries. I'll evaluate to see if they should be re-added in fixed form. Thank you.
