### ISSUE TITLE
Режим разработчика

### ISSUE THREAD

**Issue by fancat-programer** [MicrosoftDocs/windows-uwp#2439]
Могу ли я войти в режим разработчика, не имея аккаунта разработчика?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1c1ccf0b-ef01-030b-73ed-f1c52bcfe379
* Version Independent ID: 537dc92f-e701-42c1-d0a6-e6f285d2994d
* Content: [Начало разработки приложений UWP на Xbox One - UWP applications](https://docs.microsoft.com/ru-ru/windows/uwp/xbox-apps/getting-started#feedback)
* Content Source: [windows-apps-src/xbox-apps/getting-started.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/windows-apps-src/xbox-apps/getting-started.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by drewbatgit** [comment]
(Использование онлайн-перевода) Для преобразования розничной консоли в режим разработчика должна быть учетная запись Центра партнеров.  Процесс активации описан более подробно здесь - 

https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation
