### ISSUE TITLE
Confusing with two "advertisments"

### ISSUE THREAD

**Issue by buildYourOwnGolfSimulator** [MicrosoftDocs/windows-uwp#2441]
I can use the GattServiceProvider and have several local characteristics added to it. I call the method serviceProvider.StartAdvertising and I can interact with the GATTServer from e.g. LightBlue on my phone. So far so good, but I fail to find anywhere to specify CompanyId and ManufacturerData. The GattServiceProviderAdvertisingParameters has a ServiceData of type IBuffer, but I can't find any examples of what to set it to, and experimenting gives no visible results in LightBlue.
I then find the BluetoothLEAdvertisementPublisher where I can add CompanyId and ManufacturerData. So I try that one and tries to start only that one, or both the GATTserver and this one. No difference. Really confusing to have two "Start advertise", I don't quite get the difference.
I even tried to download the code sample for BluetoothLEAdvertisementPublisher, and executed that one. To my surprise couldn't I see any service in LightBlue (or two other BLE scanners tried) with that program either. 
Seems like there is missing some information here (or my bluetooth chip in Intel NUC Haydes has issues...?)
Anyway, great if the difference between the two "advertisments" could be explained, and the ServiceData explained a bit more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb68dee1-01d8-94cf-976a-5dd31d408f4d
* Version Independent ID: 1deea8b5-5241-c349-0d17-3a6a55187e58
* Content: [Bluetooth developer FAQ - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-dev-faq#feedback)
* Content Source: [windows-apps-src/devices-sensors/bluetooth-dev-faq.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/bluetooth-dev-faq.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Likely an issue with your bluetooth chip. Closing due to age. Please open a new issue if you still have concerns.
