### ISSUE TITLE
RHPROXY Enabled, but no I2C Controller device

### ISSUE THREAD

**Issue by vlsireddy** [MicrosoftDocs/windows-uwp#2443]
HI Team@Microsoft, Experts,

Statement from Michael XU-MSFT "The Resource Hub Proxy driver service is a kernel mode driver. It exists in windows 10 only(Home,Pro, Education, or Enterprise)"

NT Core - > Windows 10 Pro, Home editions.

I am trying to leverage RHPROXY to access I2C/SPI/UART.

[1] First, i ensured that Microsoft windows PRO, Enterprise [NT Core] has RHPROXY.SYS driver in it.

[2] Changed ACPI node and i got till devcon.exe and i find 1 device.

[3] then later, i see that I2CTestTool.exe shows "No I2C Controllers on this system". 

[4] Upon digging,i found that RHPROXY is dummy/useless on the windows NT Core [which does NOT expose User mode access to SPI/I2C/UART via RHPROXY]? please correct my understanding.

please confirm the following.

[A] In NT Core based windows 10 Pro, Home Operating systems, the RHPROXY is just dummy if present [since I2CTestTool.exe returns back NULL].

question: -  Why would MSFT confuse by having RHPROXY in Windows 10 Pro, Home edition, when it is dummy [since I2CTestTool fails]? or am i misunderstanding it. Please help on how to move on with I2CTestTool.exe returning NULL.

Thanks

**Comment by hkhmsft** [comment]
Hi @vlsireddy , really appreciate the detailed scenario about leveraging RHPROXY to access I2C/SPI/UART. Could you submit this to our [msdn forums](https://social.msdn.microsoft.com/Forums/newthreadcategory=windowsapps&forum=wpdevelop&prof=required) or to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all)? The community of experts and Microsoft engineers there is pretty active and may have better answers for you.

If you receive assistance and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by vlsireddy** [comment]
Hi,
     Once i get answer. I will reply back, if anything need to be changed in docs.
Thanks

**Comment by hkhmsft** [comment]
@vlsireddy Sounds like a plan. Thanks once again.

Closing the Issue for now, but feel free to re-open in the future.
