### ISSUE TITLE
Missing documentation.

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#2444]
I am currently going through the process of migrating a project.

This page misses relevant information regarding other WRL types like the wrappers namespace,

https://docs.microsoft.com/en-us/cpp/cppcx/wrl/microsoft-wrl-wrappers-namespace?view=vs-2019

No guideline is provided for which classes exist as replacement, either C++17 based ones, or C++/WinRT alternatives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501cc763-bd26-f5cd-9608-400b8d9bc25e
* Version Independent ID: 73e89a04-bd7b-7ea1-a9b2-7a846b6daafd
* Content: [Move to C++/WinRT from WRL - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-wrl)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-wrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-wrl.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @pjmlp, and thanks for filing this issue. I've added a work item to my backlog to address this.

Thanks!
Steve

**Comment by stevewhims** [comment]
Just a heads up that I'm closing this GitHub issue because I'm tracking it internally in my work items (so that it's not being tracked and counted twice). You'll still be able to leave comments here. I'll come back and (possibly reopen and) comment when I have a resolution for my work item.

Thanks!
Steve

**Comment by stevewhims** [comment]
Reopening now that I'm working on this issue.

**Comment by stevewhims** [comment]
**UPDATE**: This is now resolved. Please see the new section https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-wrl#porting-microsoftwrlwrappers-wrappers.

(I've also tidied up the noise in this message thread.)

Thanks again!
Steve
