### ISSUE TITLE
Examples does not compile in VS2019

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#2445]
[Enter feedback here]
The examples does not compile in VS2019 and there are no instructions on how to have them work.
I've created a sample empty UWP app single page.
Copied the XAML in the page (fixing the name and minor things), copied the code to cs file

At runtime I get:
Windows.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key TabViewButtonBackground [Line: 83 Position: 31]
  Source=Windows
  StackTrace:
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at App1.MainPage.InitializeComponent() in E:\Users\Massimo\OneDrive\Development\Source\App1\App1\obj\x86\Debug\MainPage.g.i.cs:line 41
   at App1.MainPage..ctor() in E:\Users\Massimo\OneDrive\Development\Source\App1\App1\MainPage.xaml.cs:line 20

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245536a-3179-ff1e-dfd5-76898d07381b
* Version Independent ID: 145609fa-8e77-5878-3402-7bcc69df8ccc
* Content: [Tree view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@msavazzi, which example in particular are you having trouble with? These examples use the WinUI NuGet package. Are you using the latest WinUI package?
