### ISSUE TITLE
Request to update examples from {Binding} to {x:Bind}

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#2446]
As per Microsoft documentation UWP applications should use x:Bind and not Binding as x:Bind is quicker, strong typed, etc. The issue is that the examples here use Binding and converting them to x:Bind generates several errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245536a-3179-ff1e-dfd5-76898d07381b
* Version Independent ID: 145609fa-8e77-5878-3402-7bcc69df8ccc
* Content: [Tree view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@msavazzi, thanks for the feedback. The examples have been updated to show x:Bind instead of Binding.
