### ISSUE TITLE
TreeView example does not behave correctly

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#2447]
When a folder is selected it is expanded (and this is ok) but then the selected item is random. 
Is not the folder that has been clicked. Also very often it goes out of screen.

The correct behavior is that the folder is expanded but the focus and selected item remains the folder!
here the project: [TreeView-SelectionIssue.zip](https://1drv.ms/u/s!AohVtHaw3aCiwaE8ADrS0bbIbs6vkA?e=DaJGvn)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245536a-3179-ff1e-dfd5-76898d07381b
* Version Independent ID: 145609fa-8e77-5878-3402-7bcc69df8ccc
* Content: [Tree view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
It looks like this is a product issue and not a doc issue, so I'm closing this. Product issue is opened at https://github.com/microsoft/microsoft-ui-xaml/issues/2463.
