### ISSUE TITLE
How multiple default languages work exactly?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/windows-uwp#2449]
What are the uses and effects of specifying multiple default languages? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd95236a-2f7c-213b-924c-a8aad87fe576
* Version Independent ID: 7b1bc7f5-452d-aa59-ac84-a71644539f49
* Content: [Specify the default resources that your app uses - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/specify-default-resources-installed)
* Content Source: [windows-apps-src/app-resources/specify-default-resources-installed.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/specify-default-resources-installed.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
