### ISSUE TITLE
docker context ls not showing wsl in list

### ISSUE THREAD

**Issue by og-neth** [MicrosoftDocs/windows-uwp#2450]
Hope someone can help me here, I followed these instruction for a Nuxt.js app, I have installed everything and have docker desktop etc, however, when running `docker context ls`, I only see the classic docker daemon in the list. This article seems outdated so not sure if that is accurate anymore, since it seems now that the Docker Desktop enables WSL 2 integration out of the box.  My question is am I suppose to see the wsl daemon in the docker context still? I am trying to figure out why I can't see my nuxt.js app running on localhost to confirm that docker is working correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef79f545-54e2-f3bc-44b0-9ec7d0263e76
* Version Independent ID: e8351bce-c027-2355-8cc4-f16b53ca3687
* Content: [Get started using Docker containers with Node.js](https://docs.microsoft.com/en-us/windows/nodejs/containers#feedback)
* Content Source: [hub/nodejs/containers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/containers.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @og-neth -- I'm looking into this. Thanks for bringing this issue to our attention and sorry for the trouble. I'll get it sorted as soon as I can get some attention from one of the devs or PMs.

**Comment by mattwojo** [comment]
Sorry for my delay on this -- WSL showing up as a context with `docker context ls` is now deprecated. You can read about it in Scott Hanselman's blog post here: https://www.hanselman.com/blog/HowToSetUpDockerWithinWindowsSystemForLinuxWSL2OnWindows10.aspx

I'm working on a bunch of updates to these docs now. :)

**Comment by mattwojo** [comment]
Just an update that I published a new guide for using WSL with Docker Desktop: https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers
