### ISSUE TITLE
Still no api for keeping playback rate speed when changing media source

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#2451]
Still no api for keeping playback rate speed when changing media source

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c68dc509-816d-26b2-4e61-c87e52171b6b
* Version Independent ID: 7d8d4517-28f1-19e5-a102-6bfa4ce21173
* Content: [Windows 10 Build 19041 API changes - UWP applications](https://docs.microsoft.com/zh-cn/windows/uwp/whats-new/windows-10-build-19041-api-diff#windowsstorage)
* Content Source: [windows-apps-src/whats-new/windows-10-build-19041-api-diff.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-19041-api-diff.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
While we appreciate your feedback, this doesn't seem like a documentation issue. I'd recommend reaching out to [Microsoft Support](https://support.microsoft.com/contactus) or other developer feedback channels to make this request. Thank you.
