### ISSUE TITLE
Error in manifest example

### ISSUE THREAD

**Issue by jpopeneng** [MicrosoftDocs/windows-uwp#2452]
The following URL does not exists:
http://schemas.microsoft.com/SMI/2019/WindowsSettings

In Visual Studio 2019 I get the following message:
`manifest authoring warning 81010002: Unrecognized Element "activeCodePage" in namespace "http://schemas.microsoft.com/SMI/2019/WindowsSettings".`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a28119a-77f2-160c-a4f1-f90ef9153423
* Version Independent ID: 28b24e82-f0ef-cceb-2136-f8dbfabfcadc
* Content: [Use the Windows UTF-8 code page - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page)
* Content Source: [windows-apps-src/design/globalizing/use-utf8-code-page.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/use-utf8-code-page.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@jpopeneng - Please install the latest Windows SDK from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/. This might fix your issue.

**Comment by Karl-Bridge-Microsoft** [comment]
Closing due to no response.
