### ISSUE TITLE
UWP not stable to deliver applications

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#2453]
Team, the page is misleading. I've opened several issues and bugs, as of today the UWP UI libraries are not usable. Something it could be done in couple of days with Forms of WPF like a very simple app that reads some data, shows a treeview and sorts the data... is simply impossible in UWP. Looks like controls are not stable enough to build apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ce3af4-0615-86cc-9d03-6cfee2e29f16
* Version Independent ID: 62c5617b-2ddb-c45e-41ae-8dc3eb82c01a
* Content: [Get started with the Universal Windows Platform (UWP) - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/)
* Content Source: [windows-apps-src/get-started/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/index.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
While we appreciate your feedback, this seems like more like a feature request or bug report than a documentation issue. I'd recommend reaching out to [Microsoft Support](https://support.microsoft.com/contactus) or other developer feedback channels.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
