### ISSUE TITLE
XAML Controls Gallery Link Incorrect

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftDocs/windows-uwp#2455]
The link you have for the XAML Controls Gallery preview branch is incorrect: &lt;https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3preview1&gt;

This is the correct link: &lt;https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3preview&gt;

I tried to edit the page on GitHub, but the edit button also points to a dead hyperlink

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3.0 Preview 1 (May 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#feedback)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by RealTommyKlein** [comment]
Looks like this is now fixed.
