### ISSUE TITLE
Misspelling and  Redirection error

### ISSUE THREAD

**Issue by Reset816** [MicrosoftDocs/windows-uwp#2456]
Misspelling in [command](https://docs.microsoft.com/en-us/windows/package-manager/package/repository#feedback)
<img width="670" alt="批注 2020-05-20 024851" src="https://user-images.githubusercontent.com/40438607/82366502-dc23aa80-9a44-11ea-90a6-a94d510a8cf2.png">
which should be **validate** 

Besides, I wanted to edit this page directly and open a pull requests. When I clicked the Edit button, this appeared and prevented me doing furthermore about the repository.
![image](https://user-images.githubusercontent.com/40438607/82366820-6cfa8600-9a45-11ea-9d0b-e0746ae96a9d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30002562-8d98-050f-eb56-f484c11f37ad
* Version Independent ID: 12fc6af3-ae25-f845-05aa-9b84878fd33e
* Content: [Submit your manifest to the repository](https://docs.microsoft.com/en-us/windows/package-manager/package/repository#feedback)
* Content Source: [hub/package-manager/package/repository.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/repository.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @denelon
* Microsoft Alias: **denelon**

**Comment by mcleanbyron** [comment]
Thanks for reporting this typo. I have just checked in a fix for it, and the fix should be published to the live site shortly.

That's strange that you're getting the 404 page when you click Edit. Can you reach this source file directly? https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/repository.md

**Comment by Reset816** [comment]
> Thanks for reporting this typo. I have just checked in a fix for it, and the fix should be published to the live site shortly.
> 
> That's strange that you're getting the 404 page when you click Edit. Can you reach this source file directly? https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/repository.md

It's seemed that I can open the link now. Two days ago I tried many ways even clone the whole repository and searched the file :)
My pleasure to get involved in this project.
