### ISSUE TITLE
Should we have a section for currently compatible libraries with previews?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2457]
Like the XAML Behaviors and the Windows Community Toolkit (https://aka.ms/wct-winui3)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3.0 Preview 1 (May 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @michael-hawker, can you clarify what you're reporting here?

**Comment by Gavin-Williams** [comment]
SharpDX - not compatible.

**Comment by Karl-Bridge-Microsoft** [comment]
@adambarlow @MikeHillberg - do you want to review this suggestion?

**Comment by MikeHillberg** [comment]
Yes, I think it's a great idea to keep this list in the release notes.

**Comment by Karl-Bridge-Microsoft** [comment]
@michael-hawker - has this issue been resolved to your satisfaction?

**Comment by michael-hawker** [comment]
Sorry, somehow I missed the original ping.

@Karl-Bridge-Microsoft @MikeHillberg based on some community feedback ([for example](https://twitter.com/josefajardo/status/1268133005920354304)) and discussions with other community members (FYI @nickrandolph), I think maintaining an explicit table with information of known supporting libraries would be a good idea.

E.g.

| Library | Preview Version | WinUI 3 Desktop Support | WinUI 3 UWP Support |
|---------|---------|--------------------|--------------------------|
| [Windows Community Toolkit](https://aka.ms/wct-winui3) | 8.0.0-preview1 (MyGet) | ✔ | (Future) |
| XAML Behaviors | ? | ✔ | ? |
| [Uno Platform](https://platform.uno/blog/announcing-uno-platform-3-0-support-for-winui-3-0-preview-1/) |  3.0.0-dev.22 | ? | ? |

Obviously, we'd need a bit more help from the other project owners to correctly fill in the table.

**Comment by Karl-Bridge-Microsoft** [comment]
@MikeHillberg @anawishnoff - can you help provide the requested detail?

**Comment by anawishnoff** [comment]
I like this idea of laying out all of our supported libraries for WinUI. I think this would be a great addition as a permanent table to the [WinUI overview article](https://docs.microsoft.com/en-us/windows/apps/winui/), and would also be good to have preview-versions of the table for each preview or other release of WinUI 3 in the appropriate release notes article.  

@stmoy, would you be the person who holds a lot of this knowledge as the ecosystem partners area driver?

**Comment by stmoy** [comment]
Between @michael-hawker and myself, I think we have the most knowledge about what libraries are supported. I've got a table internally that tracks a bunch of ecosystem partners. I'd imagine this table could be posted alongside the release notes as @MikeHillberg recommended. 

@Karl-Bridge-Microsoft - how do you want this detail provided? Right now, a lot of the columns are ❌ for support when we'd love them to be ✔.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi all - I just checked the https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md topic and the table has been added there and is being maintained. I'm going to close this issue, but have restarted the conversation with the WinUI team on whether we want to include this detail in the WinUI docs.microsoft.com.

**Comment by michael-hawker** [comment]
@Karl-Bridge-Microsoft I don't see a table that contains this information on the roadmap... The only table I see on the roadmap is the feature roadmap; not a list of third-party libraries supporting WinUI 3.

**Comment by Karl-Bridge-Microsoft** [comment]
Ah, sorry @michael-hawker, my mistake. @stmoy - can you recommend someone on the WinUI team who can provide this info?

**Comment by Karl-Bridge-Microsoft** [comment]
WinUI and WinApp SDK docs heavily revised from time of issue open. Closing due to age. Please open a new issue if still a concern.
