### ISSUE TITLE
The page is not up-to-date and I can't find it in docs repo

### ISSUE THREAD

**Issue by boltomli** [MicrosoftDocs/windows-uwp#2458]
InstallerType now supports: exe, msi, msix, inno, nullsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b884a25-4155-ac22-67b1-afb6d81d9751
* Version Independent ID: 2b7bd115-a4d9-17c7-0e21-6d23a0774af6
* Content: [Submit packages to Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/package/#feedback)
* Content Source: [hub/package-manager/package/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/index.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @denelon
* Microsoft Alias: **denelon**

**Comment by denelon** [comment]
If the installer is a .exe and it was built using Nullsoft or Inno, you may specify those values instead.  When Nullsoft or Inno are specified, the client will automatically set the silent, and silent with progress install behaviors for the installer.

**Comment by mcleanbyron** [comment]
This information has been added to the [manifest article](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest).
