### ISSUE TITLE
Misspelling in validate command

### ISSUE THREAD

**Issue by TEitelberg** [MicrosoftDocs/windows-uwp#2459]
The correct command should be: 

winget validate .\&lt;manifest-file&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30002562-8d98-050f-eb56-f484c11f37ad
* Version Independent ID: 12fc6af3-ae25-f845-05aa-9b84878fd33e
* Content: [Submit your manifest to the repository](https://docs.microsoft.com/en-us/windows/package-manager/package/repository)
* Content Source: [hub/package-manager/package/repository.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/repository.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @denelon
* Microsoft Alias: **denelon**

**Comment by dlemstra** [comment]
Related to #2456

**Comment by mcleanbyron** [comment]
Thanks for reporting this typo. I have just checked in a fix for it, and the fix should be published to the live site shortly.
