### ISSUE TITLE
Add source - example, source properties

### ISSUE THREAD

**Issue by jirir** [MicrosoftDocs/windows-uwp#2460]
There is no description or example of what properties a to-be-added-source should have.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: d5a5e2ab-44a7-a652-d3d4-c7e0bfa246ab
* Version Independent ID: bdbeae08-947d-2413-3053-ca66f0a9d90e
* Content: [source Command](https://docs.microsoft.com/cs-cz/windows/package-manager/winget/source#feedback)
* Content Source: [hub/package-manager/winget/source.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/source.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mcleanbyron** [comment]
Thank you for your feedback. The 'source' command is currently intended for internal use only, and we have added a note to clarify this in the article. If this policy changes, we'll update the article to provide more prescriptive guidance about using it.
