### ISSUE TITLE
Humm.. noise when changing mp3 or mp4 file

### ISSUE THREAD

**Issue by kishorpise** [MicrosoftDocs/windows-uwp#2461]
has any one used this ?
I build simple media player with this control it looks every thing works well, but when song changed or moved next.. I hear tick sound. this tick sound comes very poweful on external speakers where woofer is connected. please note conf as below.
RP 3B + win 10 IOT core + External speakers on 3.5 mm jack. Code c# as mentioned in example.

Thanks ..
Kishor

**Comment by hkhmsft** [comment]
Hi @kishorpise , thanks for submitting this. Could you submit this through [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all)
 or through our [forums](https://social.msdn.microsoft.com/Forums/newthreadcategory=windowsapps&forum=wpdevelop&prof=required)? The community of experts and Microsoft Engineers over there will have a better answer for you. If you do receive assistance, and you believe that information would help us improve our docs, then please come back and let us know.
