### ISSUE TITLE
Switch options need to be documented

### ISSUE THREAD

**Issue by pivendren** [MicrosoftDocs/windows-uwp#2462]
Can we please list the switch options with descriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657479f-c0b7-6358-c7d0-0402215edaa5
* Version Independent ID: 8976699b-cdba-5206-bdb0-8a0875acfe45
* Content: [Create your package manifest](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema#feedback)
* Content Source: [hub/package-manager/package/manifest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/manifest.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @denelon
* Microsoft Alias: **denelon**

**Comment by pivendren** [comment]
Hmm, not sure this was meant to land here. Is it possible that the feedback flow is not setup yet for Windows Package Manager yet?

**Comment by mcleanbyron** [comment]
Thanks for your feedback. We have updated the Switches description in the [manifest article](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest) with this information.
