### ISSUE TITLE
Typo in first sentence

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/windows-uwp#2463]
"UWP app that uses th Windows"  

Need to change th to the.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21a59145-2721-5b06-eb10-6b2e6d5af7ac
* Version Independent ID: 0f10e286-8759-cc74-dcef-aa7c1334607e
* Content: [Write a custom plugin for device portal - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-plugin#feedback)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-plugin.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-plugin.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. The topic has been updated. 

For future reference, you can use our Open Publishing system to submit PRs to fix issues like this. Just click the "Edit" button near the top of the topic to open the GitHub editor.
