### ISSUE TITLE
mosaic wonder

### ISSUE THREAD

**Issue by id-strange** [MicrosoftDocs/windows-uwp#2464]
there's a picture with mosaic in this page and it looks SO cool, so i wonder what's the name of the tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23257172-281d-1069-0db2-d63d72d3d8cc
* Version Independent ID: 0810ba9a-254a-073a-8a86-a5f750fe9ae4
* Content: [Web development with Python on Windows](https://docs.microsoft.com/en-us//windows/python/web-frameworks#feedback)
* Content Source: [hub/python/web-frameworks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/web-frameworks.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Sorry - I'm not sure what picture you're referring to. Closing this, but if you want to attach a screenshot and re-open, I can do my best to help.

**Comment by id-strange** [comment]
![image](https://user-images.githubusercontent.com/44487584/82718213-b6600500-9cd3-11ea-83c5-8e53abb2c010.png)

**Comment by id-strange** [comment]
this pic, in the center of it
