### ISSUE TITLE
Add "No Visual Basic templates" to the "Preview 1 limitations" section

### ISSUE THREAD

**Issue by Nukepayload2** [MicrosoftDocs/windows-uwp#2465]
The vsix download page said "C# and C++/WinRT are the only languages supported at this time". But this limitation was not listed in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3.0 Preview 1 (May 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#feedback)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @Nukepayload2. The topic has been updated with the suggested detail.
