### ISSUE TITLE
WinUI Alpha call out should be updated to Preview 1

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2466]
Also, the docs link from https://aka.ms/winui goes to the 3 page instead of the stable 2 page? Is that expected, especially with the call out box here to the preview page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51f403c4-0dc2-86da-8992-ae026577c843
* Version Independent ID: 6283b0fd-909e-06e0-eb92-a8c2a57b361b
* Content: [Windows UI library](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/#feedback)
* Content Source: [hub/apps/winui/winui2/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui2/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@anawishnoff - do you want to address this feedback on the aks.ms/winui page?

**Comment by Karl-Bridge-Microsoft** [comment]
@michael-hawker - feedback has been addressed (along with a few other related issues). Thanks.

**Comment by anawishnoff** [comment]
Thanks both - I'll update the docs link on the website.
