### ISSUE TITLE
What are installation instructions for Windows Insiders?

### ISSUE THREAD

**Issue by aruproy14** [MicrosoftDocs/windows-uwp#2467]
If I'm already on an insider build, when should I expect winget to be installed? Is it already being shipped with the latest insider flights? Could we get a min build from which you should expect winget to just be in the path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Greetings.  If you are a Windows Insider, then the Windows Package Manager is available to you.  You can go to the store and check for updates.  The Windows Package Manager is included in the Desktop App Installer.  https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1
If you are not an insider, you can join our flight:  https://aka.ms/winget-InsiderProgram
