### ISSUE TITLE
ColorPicker and MVVM using Converter: Unexpected COM Object

### ISSUE THREAD

**Issue by SuperJMN** [MicrosoftDocs/windows-uwp#247]
When using a `ValueConverter` in a Binding to the `Color `property of this control, the incoming value in the `ConvertBack `method is a **COM Object** that cannot be casted to a `Color`. Please, check this question in StackOverflow to see more details (and snaphots!) https://stackoverflow.com/questions/47398653/colorpicker-uwp-com-exception-in-converter

**Comment by ginami** [comment]
Thanks @SuperJMN for bringing this to our attention.

@jwmsft , can you address this?

**Comment by chigy** [comment]
Please open this product issue to https://github.com/Microsoft/microsoft-ui-xaml/issues so we can take a look.
