### ISSUE TITLE
Image is misleading?

### ISSUE THREAD

**Issue by keithnicholson** [MicrosoftDocs/windows-uwp#2470]
The top image of this dock shows annotations on a document.  But nothing in this or related articles show how to wire that up and persist the ink for editing later on the text.  Can you guide a Dev to another related article!

Peace, 
Keith
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d1a037-b3ed-4c55-5a95-ee96e6cb90dd
* Version Independent ID: 0eb4ed53-0ba1-09de-0139-842649ba1ceb
* Content: [Pen interactions and Windows Ink in Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/pen-and-stylus-interactions)
* Content Source: [windows-apps-src/design/input/pen-and-stylus-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/pen-and-stylus-interactions.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @keithnicholson - Sorry for the delayed reply. If you haven't found any official MS documentation for the annotation scenario you describe, please take have a look at this sample: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ComplexInk. 

If this still doesn't help you get started, please open a new issue with more detail on what you'd like to see.

**Comment by keithnicholson** [comment]
@Karl-Bridge-Microsoft Thanks for responding.  I'll look at that example this week. I appreciate it.
