### ISSUE TITLE
Programming languages.

### ISSUE THREAD

**Issue by dalek09** [MicrosoftDocs/windows-uwp#2471]
Where are examples in  a programming language other than c# - for me specifically where is c or c++?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340f7839-6454-f1b5-ced5-5000964efc2e
* Version Independent ID: f83df5c8-e149-df6e-243f-07311caab297
* Content: [Store and retrieve settings and other app data - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#feedback)
* Content Source: [windows-apps-src/design/app-settings/store-and-retrieve-app-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/app-settings/store-and-retrieve-app-data.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback about C++ code examples. We are working on bringing C++/WinRT code examples to more articles based on priority. In the meantime, please see the [C++/WinRT documentation](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) and [C++/WinRT API reference](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/winrt).
