### ISSUE TITLE
schema "URL" is wrong

### ISSUE THREAD

**Issue by dingyx99** [MicrosoftDocs/windows-uwp#2472]
In "Minimal required schema" and "Complete schema", using `Url` instead of `URL` to avoid errors when validating.

**Comment by hkhmsft** [comment]
Hi @dingyx99 , could you point us to the page you are referring to?

**Comment by dingyx99** [comment]
> Hi @dingyx99 , could you point us to the page you are referring to?

Sure, I'd love to.
The page is https://docs.microsoft.com/zh-cn/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. We have fixed it in this article you specified.
