### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by mark99i** [MicrosoftDocs/windows-uwp#2473]
AudioPlaybackConnection link get error 404

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1636774-f1b5-3f09-49d1-fd6fab03e2d9
* Version Independent ID: 8a9ad5cc-e61e-936c-3f73-d8330ec0b619
* Content: [Enable audio playback from remote Bluetooth-connected devices - UWP applications](https://docs.microsoft.com/en-au/windows/uwp/audio-video-camera/enable-remote-audio-playback#feedback)
* Content Source: [windows-apps-src/audio-video-camera/enable-remote-audio-playback.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/enable-remote-audio-playback.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this issue. It was caused by a build issue that has been fixed. The link resolves correctly now.
