### ISSUE TITLE
Issue with installing packages with similar names.

### ISSUE THREAD

**Issue by GeneralConfidential** [MicrosoftDocs/windows-uwp#2474]
I am having problems installing applications where the name of a package is a subset of another package name. I get this problem when trying to install PowerShell from "winget.exe". 
The following is the command I entered for installing PowerShell.
```
C:\Users\namehere>winget.exe install Microsoft.Powershell
Multiple apps found matching input criteria. Please refine the input.
Name               Id                           Version
---------------------------------------------------------------
Powershell         Microsoft.Powershell         7.0.1
PowerShell-Preview Microsoft.PowerShell-Preview 7.1.0-preview.3
```
I can not find any way to install Powershell (not PowerShell-Preview). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac54ebce-b330-44e7-4052-cfbdb878df19
* Version Independent ID: 805fc71b-6b54-3b09-95ef-4254de5e0036
* Content: [Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/#feedback)
* Content Source: [hub/package-manager/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/index.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @denelon
* Microsoft Alias: **denelon**

**Comment by coldKingdom** [comment]
You could install it by running:
```cmd
winget install Microsoft.Powershell --exact
```
```help
--exact or -e for short
```

You can find the switches by running:
```cmd
winget install -?
```
Hope it helps!

**Comment by KevinLaMS** [comment]
Thanks coldKingdom.  That is correct.  But I will file an issue to raise this so we can look at improving in the future.  Kevin.

**Comment by hkhmsft** [comment]
Thank you @KevinLaMS  and @coldKingdom for the answers. @GeneralConfidential , if there's anything else we can do to answer your questions, feel free to re-open this thread. Many thanks.
