### ISSUE TITLE
Link to "app services" does not work

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/windows-uwp#2475]
Last sentence links the "app services" text to address https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-services.md

This link does not work and returns 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a7e980-cfd8-6d9c-6cc5-0ca6763fd327
* Version Independent ID: 5f59e641-6576-e10e-99c0-794907285580
* Content: [Modernize existing desktop apps using Desktop Bridge](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#start-your-application-by-using-an-alias)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-extensions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extensions.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this broken link. I checked in a fix, and the correction should be published in the next hour or so (there shouldn't be a ".md" extension in the link).
