### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by eluchsinger** [MicrosoftDocs/windows-uwp#2476]
This documentation is outdated. You have to use App registrations on the Azure Portal now. Please update. 

PS: Even the Notification Hub resource on Azure is outdated and links to the partner portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1500dd-1909-34d6-d67a-8ae2dc5393db
* Version Independent ID: 490fe0f3-6dbf-93a6-e0c0-c3ea51f5cbd3
* Content: [Windows Push Notification Services (WNS) overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. This article was updated several months ago to describe the current process, and it now points to the Azure Notification Hubs documentation where appropriate.
