### ISSUE TITLE
Remove "continuum" tip

### ISSUE THREAD

**Issue by smurancsik** [MicrosoftDocs/windows-uwp#2477]
[Enter feedback here]
Maybe the "Continuum" part can be removed as the whole Windows Phone project has already been cancelled among with the Continuum-supported devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5f48a1-c62a-9f8f-ab29-70d013346d2a
* Version Independent ID: 6ad201c6-ae84-5c10-0129-2cfa6f420cb6
* Content: [Screen sizes and break points for responsive design - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/screen-sizes-and-breakpoints-for-responsive-design)
* Content Source: [windows-apps-src/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@smurancsik, thanks for this feedback. The obsolete information about Continuum has been removed.
