### ISSUE TITLE
Adobe XD tooklit outdated

### ISSUE THREAD

**Issue by fahdriyami** [MicrosoftDocs/windows-uwp#2479]
The Adobe XD toolkit hasnt been updated since October 2018/January 2019. Can it please be updated to have the latest WinUI 3.0 elements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Design toolkits and samples for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
Hi - at the moment we are focusing on the Figma toolkit over Adobe https://aka.ms/figmatoolkit
I will make a record of the request to help us judge demand.
Thank you!
