### ISSUE TITLE
Need to update sample code, has typo and does not compile

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/windows-uwp#2484]
Code needs to be updated as does not compile.

This needs to be changed from:

        res.Content = new HttpStringContent(con);
        res.Content.Headers.ContentType = new HttpMediaTypeHeaderValue("text/html");
        res.StatusCode = HttpStatusCode.Ok; 

To following:

                res.Content = new Windows.Web.Http.HttpStringContent(con);
                res.Content.Headers.ContentType = new Windows.Web.Http.Headers.HttpMediaTypeHeaderValue("text/html");
                res.StatusCode = Windows.Web.Http.HttpStatusCode.Ok;

Need to add this into the code too so customers know that this is needed to be added:

using Windows.System.Diagnostics.DevicePortal;    //added
using Windows.ApplicationModel.Background;       //added

 public sealed class SampleProvider : IBackgroundTask
 {
        BackgroundTaskDeferral taskDeferral;   //added 
        DevicePortalConnection devicePortalConnection;   //added

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21a59145-2721-5b06-eb10-6b2e6d5af7ac
* Version Independent ID: 0f10e286-8759-cc74-dcef-aa7c1334607e
* Content: [Write a custom plugin for device portal - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-plugin)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-plugin.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-plugin.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic revised as suggested.
