### ISSUE TITLE
Node about nvm version is in the wrong place / no upgrade info

### ISSUE THREAD

**Issue by Pawper** [MicrosoftDocs/windows-uwp#2486]
Please move the note to right after the command to install nvm, instead of quite further down the page. Please add instructions on how to upgrade nvm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @Pawper.  Good recommendation - I just moved the note directly under the install command and updated the command to represent v0.35.3.

The change should show up by tomorrow morning.
