### ISSUE TITLE
How to use the winget when there are more then one results, syntax of -v --id is unclear

### ISSUE THREAD

**Issue by aavdberg** [MicrosoftDocs/windows-uwp#2493]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73bd6478-de0f-6aa9-fb31-0818abdb7f68
* Version Independent ID: f5ff6ecd-0231-d438-7301-6eb20863ec50
* Content: [install Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/install)
* Content Source: [hub/package-manager/winget/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/install.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. We added additional examples to illustrate these arguments [here](https://github.com/MicrosoftDocs/windows-uwp/pull/2499/files).
