### ISSUE TITLE
Consideration to add more info on install usage when multiple packages match

### ISSUE THREAD

**Issue by ShaneC** [MicrosoftDocs/windows-uwp#2496]
When installing in winget, if your install query results in multiple matches you receive an error "Multiple apps found matching input criteria. Please refine the input."

The docs mention this case but don't give a prescribed way to get beyond it (i.e. "winget install PowerShell -e").

I've noticed this to be a pretty frequent case on most apps I've installed, as many apps have multiple release channels (beta, stable, hyper-stable).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73bd6478-de0f-6aa9-fb31-0818abdb7f68
* Version Independent ID: f5ff6ecd-0231-d438-7301-6eb20863ec50
* Content: [install Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/install)
* Content Source: [hub/package-manager/winget/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/install.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by renuac** [comment]
$#root✓

**Comment by mcleanbyron** [comment]
Thanks for your feedback. We added some information to [this section](https://docs.microsoft.com/en-us/windows/package-manager/winget/install#multiple-selections) of the docs to help clarify this.

**Comment by renuac** [comment]
#TODOS
CONTRA814714
CPRONA VIRUS.



-- 
Renato Nunes Achkar

**Comment by renuac** [comment]
Thanks
 'claro.com.br'

Em sáb, 27 de jun de 2020 12:31, Renato Nunes Achkar <renuac@gmail.com>
escreveu:

> #TODOS
> CONTRA814714
> CPRONA VIRUS.
>
>
>
> --
> Renato Nunes Achkar
>

**Comment by renuac** [comment]
'APACHE 2.0'='2020-06-28 55.55.55.55.55.

Em sáb, 27 de jun de 2020 12:33, Renato Nunes Achkar <renuac@gmail.com>
escreveu:

> Thanks
>  'claro.com.br'
>
> Em sáb, 27 de jun de 2020 12:31, Renato Nunes Achkar <renuac@gmail.com>
> escreveu:
>
>> #TODOS
>> CONTRA814714
>> CPRONA VIRUS.
>>
>>
>>
>> --
>> Renato Nunes Achkar
>>
>

**Comment by renuac** [comment]
Em sáb, 27 de jun de 2020 12:38, Renato Nunes Achkar <renuac@gmail.com>
escreveu:

> 'APACHE 2.0'='2020-06-28 55.55.55.55.55.
>
> Em sáb, 27 de jun de 2020 12:33, Renato Nunes Achkar <renuac@gmail.com>
> escreveu:
>
>> Thanks
>>  'claro.com.br'
>>
>> Em sáb, 27 de jun de 2020 12:31, Renato Nunes Achkar <renuac@gmail.com>
>> escreveu:
>>
>>> #TODOS
>>> CONTRA814714
>>> CPRONA VIRUS.
>>>
>>>
>>>
>>> --
>>> Renato Nunes Achkar
>>>
>>
