### ISSUE TITLE
Incorrect path for windows.winmd reference

### ISSUE THREAD

**Issue by elyoh** [MicrosoftDocs/windows-uwp#2497]
The documentation for adding the reference to windows.winmd appears to be incorrect.

It states that the file `windows.winmd` at `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\<sdk version>\Facade` should be used.

However this causes: 
`Error CS0731 The type forwarder for type 'xyz' in assembly 'Windows' causes a cycle`

Adding a referenc to the file `Windows.winmd` at `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\<sdk version>\` appears work correctly and does not cause the type forwarder errors.

Please can you clarify / update the documentation as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Call Windows Runtime APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us, and I'm sorry for the delay in responding to you. I just tested out the "To add the required references manually" instructions in this article (including referencing windows.winmd from the /Facade folder) in a Windows Forms project that targets the .NET Framework, and I am not seeing this error; I can successfully call a WinRT API with the current instructions. The engineering team that owns this feature area also confirmed that they are not aware of any changes to this experience.

If you are still seeing the error, please reopen this issue and provide more details about your scenario, such as the specific type of project in which you're seeing this error, your Visual Studio version, and the specific type mentioned in the type forwarder error (whatever 'xyz' is in your scenario). 

Also, please confirm that you're only following the instructions in the "To add the required references manually" section (that is, make sure you're not also installing the Microsoft.Windows.SDK.Contracts NuGet package).

**Comment by elyoh** [comment]
This was in a WPF application targetting .NET 4.8.
Visual Studio 2019 16.6.2.  
Windows SDK 19041.

I just tried to produce a small repo of the issue and it seems a reference to `Facade\windows.winmd` gives the errors I reported if references to `Windows.Foundation.UniversalApiContract.winmd` and `Windows.Foundation.FoundationContract.winmd` are **not** included.  

So from that angle, the instructions do work, although it was not clear to me that all three `winmd` files are required.  If I explain how I came at this in the first place, you will see why I had not expected to need to include every reference in the table.

A couple of years since, I had successfully used the approach in the [DesktopBridge samples](https://github.com/microsoft/DesktopBridgeToUWP-Samples/blob/master/Samples/WPFasShareTarget/PhotoStoreDemo/PhotoStoreDemo.csproj) which references `Windows.winmd` in `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\`. There is no reference including a 'Facade' folder or the names `Windows.Foundation.UniversalApiContract.winmd` or `Windows.Foundation.FoundationContract.winmd`.

Therefore it seems clear that some changes have been made in more recent versions of the Windows SDK.  I had done a clean OS and VS install with the latest Windows SDK and this had broken earlier working references.  I found there were 5 different files named `Windows.winmd` in the `Windows Kits\10\UnionMetadata` subfolders and I was not certain on which one should be referenced or that `Windows.Foundation.UniversalApiContract.winmd` and `Windows.Foundation.FoundationContract.winmd` now need to be referenced.

Referencing `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\<sdk version>\` did however work perfectly without the extra `winmd` references.

A pointer in the docs that all 3 `winmd` references are needed would be useful (especially as references to `System.Runtime.WindowsRuntime.UI.Xaml` clearly aren't unless you want UI stuff).



There is also a minor typo in the docs though when compared to the 18362 and 19041 versions of the Windows SDK.  Reference paths for `Windows.Foundation.UniversalApiContract.winmd` and `Windows.Foundation.FoundationContract.winmd` are missing the `\` preceding the `<version>`.

**Comment by mcleanbyron** [comment]
Thanks for all the additional info. You're correct that the intention is to reference all the .dll and .winmd files listed in the table, and I have updated the language to make this more explicit. I have also fixed the missing '\' characters. 

If you haven't tried the Microsoft.Windows.SDK.Contracts NuGet package yet, you may want to try that out in the future. It provides a much easier experience compared to adding all the references manually.
