### ISSUE TITLE
Truncated text

### ISSUE THREAD

**Issue by dubeg** [MicrosoftDocs/windows-uwp#2504]
A portion of the text is truncated. E.g. below:
```
ichEditMathMode
ichEditTextDocument.GetMath
ichEditTextDocument.SetMath
ichEditTextDocument.SetMathMode
nagement.Core.CoreInputView.PrimaryViewHiding

nagement
nagement.Core.CoreInputView.PrimaryViewShowing
nagement.Core.CoreInputViewHidingEventArgs
nagement.Core.CoreInputViewHidingEventArgs.TryCancel

nagement
nagement.Core.CoreInputViewShowingEventArgs
nagement.Core.CoreInputViewShowingEventArgs.TryCancel
nagement.Core.UISettingsController
nagement.Core.UISettingsController.RequestDefaultAsync

nagement
nagement.Core.UISettingsController.SetAdvancedEffectsEnabled
nagement.Core.UISettingsController.SetAnimationsEnabled
nagement.Core.UISettingsController.SetAutoHideScrollBars
nagement.Core.UISettingsController.SetMessageDuration
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c68dc509-816d-26b2-4e61-c87e52171b6b
* Version Independent ID: 7d8d4517-28f1-19e5-a102-6bfa4ce21173
* Content: [Windows 10 Build 19041 API changes - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-19041-api-diff#windowsui)
* Content Source: [windows-apps-src/whats-new/windows-10-build-19041-api-diff.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-19041-api-diff.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Well, that's a fascinating bug. This file is auto-generated by our scripting - clearly something broke right at that last part of the page.

For now, I'm removing these malformed entries. I'll go back through later and determine whether the fixed versions are supposed to be present, and re-adding them if they are.
