### ISSUE TITLE
There is an error at step #2 - Section:Instantiate the XamlApplication object in the entry point of your WPF app 

### ISSUE THREAD

**Issue by LiviuSosu** [MicrosoftDocs/windows-uwp#2506]
[Enter feedback here]
we will get an error on this line:
  app.Run();

The method is not defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba9095f-57b4-267d-8896-5375c68b01ee
* Version Independent ID: 514d7e51-6f16-8199-aabf-26ee901a6ed3
* Content: [Host a standard UWP control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. However, I'm not able to reproduce the error you're seeing. Here are a few things you can check:

* When you copied over the code snippet for this section into your project, did you replace `MyUWPApp` with the namespace of your UWP app project and replace `MyWPFApp` with the namespace of your WPF app project?
* Did you do into the properties for your WPF project and assign the startup object to the Program class from the code snippet in this section?

I hope this helps.
