### ISSUE TITLE
Direct2D example with C++/WinRT no longer compiles.

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#2507]
I have tried to compile the Direct 2D example listed in

and got the following set of error messages

> 
> 1>------ Build started: Project: Direct2D-Demo, Configuration: Debug Win32 ------
> 1>App.cpp
> 1>D:\Direct2D-Demo\App.cpp(137,20): error C2039: 'get_unknown': is not a member of 'winrt'
> 1>D:\Direct2D-Demo\Generated Files\winrt\Windows.Graphics.Display.h(1483): message : see declaration of 'winrt'
> 1>D:\Direct2D-Demo\App.cpp(137,31): error C3861: 'get_unknown': identifier not found
> 1>Done building project "Direct2D-Demo.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The same error has been documented  as https://github.com/MicrosoftDocs/windows-uwp/issues/1305, however using the latest version of Visual Studio 2019, the same error is present.

> Microsoft Visual Studio Community 2019
> Version 16.6.0
> VisualStudio.16.Release/16.6.0+30114.105
> Microsoft .NET Framework
> Version 4.8.03752
> 
> Installed Version: Community
> 
> Visual C++ 2019   00435-60000-00000-AA764
> Microsoft Visual C++ 2019
> 
> ASP.NET and Web Tools 2019   16.6.936.3669
> ASP.NET and Web Tools 2019
> 
> Azure App Service Tools v3.0.0   16.6.936.3669
> Azure App Service Tools v3.0.0
> 
> C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> IntelliCode Extension   1.0
> IntelliCode Visual Studio Extension Detailed Info
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> Node.js Tools   1.5.20317.1 Commit Hash:3e70368beb9630c811076c051f4c9a59b45d7c10
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   5.6.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> Syntax Visualizer   1.0
> An extension for visualizing Roslyn SyntaxTrees.
> 
> Test Adapter for Google Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> TypeScript Tools   16.0.20417.2002
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
> Microsoft Visual F# Tools 10.9.1.0 for F# 4.7
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Tools for CMake   1.0
> Visual Studio Tools for CMake

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a5b38aa-8df6-251c-6da9-3c2ce888c866
* Version Independent ID: 08f6669a-4dc7-ab0d-04b1-7125e809cd60
* Content: [Consume COM components with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-com)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-com.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-com.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @pjmlp, did you see the paragraph that begins "Open `pch.h`, and add `#include <unknwn.h>` immediately after including `windows.h`."? I can repro the build error *only* if I omit that step.

It's possible that that paragraph wasn't drawing enough attention to itself, so I've made a change to the topic. I've used headings to make it clearer that there are two steps: edit `pch.h`, and then edit `App.cpp`. That change is now live.

I'll leave the issue open for a while to confirm that (with that step) your project builds.

Thanks!
Steve

**Comment by pjmlp** [comment]
@stevewhims Thanks for replying. I did indeed miss the description you mentioned.

I guess my error was that I have long experience with Windows development and while trying to find examples how to port C++/CX code into C++/WinRT did not read everything with the right attention.

I am closing the ticket, given it was a mistake caused by my lack of attention.

Thanks for the support.

**Comment by stevewhims** [comment]
Thank you, @pjmlp! For the porting work, hopefully the [Move to C++/WinRT from C++/CX](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx) topic is helpful.

-Steve

**Comment by pjmlp** [comment]
Thanks I am aware of that topic.

C++/WinRT tooling still feels quite rough versus what C++/CX and it isn't
always clear what the replacements are, even with that guide.

That belongs in other tickets thought.

My endeavour started as an attempt to port the Simple 3D DirectX sample
from C++/CX into C++/WinRT.

Steven White <notifications@github.com> schrieb am Mi., 3. Juni 2020, 23:07:

**Comment by stevewhims** [comment]
Thanks, @pjmlp. Getting that Simple 3D DirectX sample app (the target-shooting game) ported to C++/WinRT is something that's important to me, too. I have a task on my backlog to do that.

-Steve
