### ISSUE TITLE
Make Acrylic guidelines more clear

### ISSUE THREAD

**Issue by rhjanssen** [MicrosoftDocs/windows-uwp#2509]
Hi,

Please be more clear in the intended use of acrylic.
On one hand you say it should only be used in transient UI where you can click out of.

Right-click menu = Yes
Pop-Up dialog = No

But acrylic is used on static navigation menus.
Those are not transient.

And if they can be used for a navigation pane I would assume it could be used for, let's say the lint UI in file explorer or Word.
But you describe those as part of the content area of the app. I would think that at least the blue part of the lint UI in word (or orange in PowerPoint etc) Would have acrylic applied.

I hope you can do something with this feedback.

Kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9faf87c-bd56-99da-70ed-07c68f9118a5
* Version Independent ID: 713b5c24-d710-303f-620e-9c7735797907
* Content: [Acrylic material - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#usability-and-adaptability)
* Content Source: [windows-apps-src/design/style/acrylic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/acrylic.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I don't know if that pun was intended or not, but if it was, _well done!_

I completely agree with your feedback; there are inconsistencies that _need_ to be addressed. I will be addressing them as part of a larger project, but in the short-term I don't have any specific guidance updates that I can make at this time. I'm going to close this issue, just know your feedback has been well received and will be addressed.

Thanks,
Shawn
