### ISSUE TITLE
errase cockies

### ISSUE THREAD

**Issue by youceflabed** [MicrosoftDocs/windows-uwp#2510]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac54ebce-b330-44e7-4052-cfbdb878df19
* Version Independent ID: 805fc71b-6b54-3b09-95ef-4254de5e0036
* Content: [Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/#understanding-package-managers)
* Content Source: [hub/package-manager/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/index.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @denelon
* Microsoft Alias: **denelon**

**Comment by denelon** [comment]
Hello @youceflabed can you elaborate on the issue with the documentation?

**Comment by mcleanbyron** [comment]
We're closing this issue due to lack of information. Please feel free to reopen this issue with specific details about your feedback.
