### ISSUE TITLE
Does 'two-pane-view' of winui still depend on OS version

### ISSUE THREAD

**Issue by rahulkps23** [MicrosoftDocs/windows-uwp#2512]
It is mentioned that 'two-pane-view' uses WinUi and hence not platform dependent.
But when i use it in my project having minimum target verson=1703, it is throwing error saying 'two-pane-view' is available in 1703(note: i used winui 2.4 and using that i am consuming this 'two-pane-view' in my xaml
 eg: <muxc:TwoPaneView> </muxc:TwoPaneView>).
What does that mean, if it is from WinUi it must be independent right. Why is it still dependent on OS version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4e47560-871f-79a8-be5b-aa0d6fd9a0ae
* Version Independent ID: 6d370bc0-6e96-a177-ebbf-27020c0307fb
* Content: [Two-pane view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/two-pane-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/two-pane-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/two-pane-view.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
The WinUI version of TwoPaneView will work on Windows 10 Creators Update (version 1703, build 15063) or later. If you are using TwoPaneView in your code-behind, be sure to use the Microsoft.UI.Xaml.Controls namespace, as shown in the C# examples.

There is a non-WinUI version (_Windows_.UI.Xaml.Controls.TwoPaneView) that requires Windows 10 version 1903 or later.
