### ISSUE TITLE
What exactly does the deprecation warning mean?

### ISSUE THREAD

**Issue by artemious7** [MicrosoftDocs/windows-uwp#2516]
The warning says: 

> Feedback report deprecation on April 15th 2020 This report will no longer be supported after April 15th 2020. Data on this report will not refresh after this date and the report will be removed in future without further notice. You can continue to view feedback received from your customers directly in the Feedback Hub.

What does it really mean? Which report? Does it mean that I should not ask my users to leave their feedback in the Feedback Hub? Is this whole feature being deprecated? 

I came to this page to learn how to use this feature. I can use this code in my app

`await Microsoft.Services.Store.Engagement.StoreServicesFeedbackLauncher.GetDefault().LaunchAsync();`

that will launch Feedback Hub, where user can leave feedback about my app. Is this now being deprecated? Or is it some other feature that I don't know of that is being deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89cc1b93-b31f-09c7-681f-02a43a5fc682
* Version Independent ID: 76d7a4eb-90f8-3501-3513-9637577dc999
* Content: [Feedback report - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/feedback-report?source=docs)
* Content Source: [windows-apps-src/publish/feedback-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/feedback-report.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I'm a little unclear on what you're asking. It says in the deprecation notice that "You can continue to view feedback received from your customers directly in the Feedback Hub." The report itself is being deprecated, but not Feedback Hub. Can you clarify your concerns?

**Comment by artemious7** [comment]
I just don't know what "Feedback report" is. I have never used Feedback Hub to collect feedback from my users, so I am now unsure if I can even begin using it, because the message says that something (I don't know what) is being deprecated now. Please, clarify it, if you can :-)
