### ISSUE TITLE
a suggestion to change a sentence for improved clarity

### ISSUE THREAD

**Issue by krunch3r76** [MicrosoftDocs/windows-uwp#2520]
I constructively feel that this page can be enhanced by changing the language concerning this sentence as follows: 

"In BookSku.h, add a constructor that takes a winrt::hstring, a private member to store the title string, and another for the event that we'll raise when the title changes. "

"another" appears to refer to that which is "taken" by the constructor, but in fact the constructor, as per the ensuing example, only has one parameter added. I suggest clarifying the add-noun clause to act on the two private members more directly as follows:
In BookSku.h, add a winrt::hstring to store the title string along with a constructor to input it and another private member for the event that we'll raise when the title changes.

Thank you for considering my suggestion.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a199ae-561b-98b6-8cf0-101aedbfe599
* Version Independent ID: a8091c04-868d-51aa-f4d1-207c5c795235
* Content: [XAML custom (templated) controls with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @krunch3r76, I completely agree, it's ambiguous. Note that the topic in question isn't the custom controls one, but this one: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-property.

I've published a fix, hopefully that removes the former clumsiness. :)

Thanks!
-Steve

**Comment by krunch3r76** [comment]
thank you, the new language is definitely coherent with the example to a reader who is new to WinRT/C++ (RT class event-driven paradigm). Thanks for recognizing the correct page to which this feedback belonged and addressing it without fuss!
