### ISSUE TITLE
recommendation to remove a superfluous/unclear statement

### ISSUE THREAD

**Issue by krunch3r76** [MicrosoftDocs/windows-uwp#2521]
Dear Microsoft team: I constructively feel this Content's readability can be enhanced by the removal of/elaboration on the following statement (**boldfaced**):

"In \Bookstore\Bookstore\MainPage.cpp, call winrt::make (with the implementation type) to assign a new instance of the projected type to m_mainViewModel. **Assign an initial value for the book's title.** "

URL: (https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#add-a-property-of-type-bookstoreviewmodel-to-mainpage)

Background:
This statement alone is confusing because the "**initial value for the book's title**" is _already assigned in_ the "new instance of the projected type to m_mainViewModel" (upon implementation/default construction) and is _not assigned_ elsewhere as in the associated listing (MainPage.cpp). For reference, it is "Atticus".

Suggested change:
Remove the sentence or refer back to the previous clause, which instructs implementation of the projected type, to clarify that the initial value is concomitantly assigned (which seems to be the intent) as in:

In \Bookstore\Bookstore\MainPage.cpp, call winrt::make (with the implementation type) to assign a new instance of the projected type to m_mainViewModel, whose constructor raises an event to assign an initial value for the book's title.

Thank you for considering my suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47016328-dadb-a583-bba5-f60b907861f4
* Version Independent ID: 8d21db48-d9f0-91ae-d25c-762b2b2f9cb2
* Content: [XAML controls; bind to a C++/WinRT property - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi! I'll take a look at this soon, and make fixes. Thank you for filing!

-Steve

**Comment by stevewhims** [comment]
Yes, you're right, that sentence was unclear and out of date. I've published a fix. Does that look better?

Thanks for your patience!
Steve
