### ISSUE TITLE
Developer forums links update

### ISSUE THREAD

**Issue by BMarques** [MicrosoftDocs/windows-uwp#2523]
Hello,
Half of the developer forums are either redirects to pages that are unrelated (specially the first ones with the filters), or the pages are now dead. Can you update it please? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5873bf21-4560-102a-a9c8-2ad4e425be49
* Version Independent ID: dea02fb9-f0a7-739d-2926-f92d6d973026
* Content: [Windows 10 game development guide - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/e2e)
* Content Source: [windows-apps-src/gaming/e2e.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/e2e.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @BMarques, and thanks for filing this issue. I've updated the live topic with fixes to the links. I think they're all ok now.

Thanks again!
Steve

**Comment by stevewhims** [comment]
The fixes are now live, so I'll go ahead and close the issue.

**Comment by BMarques** [comment]
I'm not sure if it was this change or not, but the page is considerably broken in some parts, I think the headings in some parts are wrong, for example  #### MonoGame instead of ###MonoGame
