### ISSUE TITLE
Needs valid example, first example is wrong and leads to copy-paste problems

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2526]
> Follow-up from an issue [filed here](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3345), this is a doc issue not a product issue.

The document doesn't provide a proper example of a dependency property (the `propdp` VS shortcut should probably be called out somewhere too):

```cs
    public int MyProperty
    {
        get { return (int)GetValue(MyPropertyProperty); }
        set { SetValue(MyPropertyProperty, value); }
    }

    // Using a DependencyProperty as the backing store for MyProperty.  This enables animation, styling, binding, etc...
    public static readonly DependencyProperty MyPropertyProperty =
        DependencyProperty.Register(nameof(MyProperty), typeof(int), typeof(ownerclass), new PropertyMetadata(0));
```

Even worse, the first example is incomplete/invalid for the normal use-case, which appears to be what may have led to the problem in the linked issue.

The example should be updated (and it's not about it being a bad example should be removed).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a6b32d-01cb-f866-8e4e-3b444b7d2996
* Version Independent ID: fc6a226a-e603-97c4-6c99-a00a0e3d4ea1
* Content: [Dependency properties overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/dependency-properties-overview)
* Content Source: [windows-apps-src/xaml-platform/dependency-properties-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/dependency-properties-overview.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
The code has been updated.
