### ISSUE TITLE
Outdated developer mode docs

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/windows-uwp#2528]
I believe this content is outdated.

I looked but the sections I'm finding in settings don't talk about Sideload anymore. I only see two things:
1. Update & Security, For developers, has a single Developer Mode toggle, not multiple options.
2. Apps, Apps & features, Chose where to get apps has a Microsoft Store only option, but I think it's no longer on by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f67548-9361-beab-49f8-7d604651c6a6
* Version Independent ID: 6194efed-24aa-74f2-7687-3e368534b74a
* Content: [Enable your device for development - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Indeed, these options have been changed in the most recent Windows 10 release. I've updated the alerts on the page, removed an outdated screenshot, and slightly changed the order of contents to reflect this (though the sideloading section is still present, for users who are not on the most recent version).
