### ISSUE TITLE
Content is a link

### ISSUE THREAD

**Issue by yoshiask** [MicrosoftDocs/windows-uwp#2532]
The entire second half of the page is a hyperlink
![image](https://user-images.githubusercontent.com/7549325/85096409-16e64300-b1a9-11ea-92ab-53a849ab71a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for bringing this to our attention @yoshiask! I went ahead and fixed the documentation and the changes are live. Thanks once again!
