### ISSUE TITLE
Missing templates for DirectX tutorial

### ISSUE THREAD

**Issue by benjamesward** [MicrosoftDocs/windows-uwp#2537]
The very first step of the first part of this tutorial doesn't work when using the latest version of Visual Studio 2019. The DirectX templates don't exist any more, and there is no guidance on where to go from there. I eventually figured out that I needed to install something extra from some guy on Github (https://walbourn.github.io/direct3d-game-visual-studio-templates-redux/), but it's not flagged as an official repository or something that I should trust. Yikes. Please update the documentation to mention that the user will need to install some additional stuff to get started, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa02bcc-0841-3108-8f7e-47abbe6850a1
* Version Independent ID: 91c62675-45a3-5cc6-7d4a-55fbf511ad8e
* Content: [Set up the game project - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure)
* Content Source: [windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing this issue, @benjamesward. I'm working on updating this topic right now because I want to change the language used in this series to C++/WinRT (from C++/CX). I'll update this thread when I have something published.

Thanks again!
Steve

**Comment by benjamesward** [comment]
Great, thanks Steve!


On 23 June 2020 at 02:08:50, Steven White (notifications@github.com) wrote:

Thanks for filing this issue, @benjamesward
<https://github.com/benjamesward>. I'm working on updating this topic right
now because I want to change the language used in this series to C++/WinRT
(from C++/CX). I'll update this thread when I have something published.

Thanks again!
Steve

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MicrosoftDocs/windows-uwp/issues/2537#issuecomment-647846587>,
or unsubscribe

**Comment by stevewhims** [comment]
UPDATE: So, I've published a fix to the issue of the Direct3D project templates not being available for C++/WinRT. And I've updated all of the code snippets to show C++/WinRT instead of C++/CX. I'll go ahead and close the issue.

Thanks!
Steve
