### ISSUE TITLE
Docs are out of date

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#2538]
This doc describles how to add taskbar control buttons like below.
![image](https://user-images.githubusercontent.com/14960168/85269042-eacd0980-b4a9-11ea-9b14-962f1d86a31d.png)

But now the doc is out of date, we can easily achieve this by enable the `Background Media Playback` capability in the `package.manifest`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca196e4-ff02-559e-10fb-cb48b8a5b56e
* Version Independent ID: 486b72b5-05db-3fd9-796f-17c8253d6774
* Content: [Manual control of the System Media Transport Controls - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/system-media-transport-controls)
* Content Source: [windows-apps-src/audio-video-camera/system-media-transport-controls.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/system-media-transport-controls.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hi, thank you for your feedback. This article is intended to support legacy apps that use the old way of integrating with SMTC. As it states in the first paragraph:

"Starting with Windows 10, version 1607, UWP apps that use the MediaPlayer class to play media are automatically integrated with the System Media Transport Controls (SMTC) by default. This is the recommended way of interacting with the SMTC for most scenarios. For more information on customizing the SMTC's default integration with MediaPlayer, see [Integrate with the System Media Transport Controls](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols)."

The linked article [Integrate with the System Media Transport Controls](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/integrate-with-systemmediatransportcontrols) has the most recent information.
