### ISSUE TITLE
downlaods typo

### ISSUE THREAD

**Issue by dustinsoftware** [MicrosoftDocs/windows-uwp#2539]
Typo: "Visual Studio downlaods page" appears twice on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c920a34-495e-ae99-365a-f6bc0afa2052
* Version Independent ID: 1e3c088d-3ca5-7f26-b1f6-23d9c97918e7
* Content: [Windows 10 on ARM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm)
* Content Source: [windows-apps-src/porting/apps-on-arm.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
Assigning to writer-owner.
