### ISSUE TITLE
Some inaccuracies

### ISSUE THREAD

**Issue by ET3D-ET3D** [MicrosoftDocs/windows-uwp#2541]
[Enter feedback here]

There are a few problems with this page. I don't remember all of them (read it about a month ago), but here are two:

I won't suggest using MonoGame with VS2019 currently (version 3.7.1) because it only installs extensions for Visual Studio 2013 to 2017.

The page says that the Agency font comes with Windows. It doesn't. It comes with Office.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b55ec8-00ba-dd3f-3fe8-dae000b588ba
* Version Independent ID: dd1b048f-b8c8-091c-8dcc-342a1fd75843
* Content: [Create a UWP game in MonoGame 2D - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-started-tutorial-game-mg2d)
* Content Source: [windows-apps-src/get-started/get-started-tutorial-game-mg2d.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/get-started-tutorial-game-mg2d.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Apologies for the delayed response.

The MonoGame tutorial is no longer being actively supported, and has been de-listed from our table of contents and from internal links for some time. In fact, the page itself will formally be removed shortly.

I apologize that you ran into trouble with it, but I'm afraid that, as it's being discontinued, we won't be applying fixes to the content.
