### ISSUE TITLE
Unclear "out from the device" axis

### ISSUE THREAD

**Issue by hadess** [MicrosoftDocs/windows-uwp#2542]
While trying to verify whether Linux' IIO subsystem and Windows used the same axis references, I found the page in question, and the description of the Z axis wasn't clear.

Linux says:
https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/tree/Documentation/ABI/testing/sysfs-bus-iio#n1638
> Z is perpendicular to the screen plane and positive out of the screen

The Windows docs say:
https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/sensor-orientation
> with the positive z-axis extending out from the device.

Does "out from the device" mean "out and positive out of the back of the device" or "out and positive out of the screen"?

Using dotted lines rather than grayed out lines in the diagrams might make it clearer which part of the arrow is behind the screen, and which is in front of it. A positive Z-axis out of the back of the display would appear partially dotted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b263c037-c41e-3389-d556-4b2a3fb9602d
* Version Independent ID: 1575e125-abd0-82ee-15ef-8190620ae7c7
* Content: [Sensor orientation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/sensor-orientation)
* Content Source: [windows-apps-src/devices-sensors/sensor-orientation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/sensor-orientation.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hadess** [comment]
I found those pictures in the [Integrating Motion and Orientation Sensors whitepaper](https://docs.microsoft.com/en-us/windows-hardware/design/whitepapers/integrating-motion-and-orientation-sensors):

![image](https://user-images.githubusercontent.com/769861/86244548-6ca6ec00-bba8-11ea-9131-d36af00d6c15.png)

and:

![image](https://user-images.githubusercontent.com/769861/86244804-cd362900-bba8-11ea-80d8-203c59f3fc61.png)

which clearly show that the Z axis would be "positive out of the screen".

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @hadess - the topic has been updated with additional detail.
