### ISSUE TITLE
Fix Links

### ISSUE THREAD

**Issue by juvtib** [MicrosoftDocs/windows-uwp#2543]
Many of the links in this document appear to be badly broken. They extend through entire paragraphs and code examples. Please review this document and fix the broken links. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a7e980-cfd8-6d9c-6cc5-0ca6763fd327
* Version Independent ID: 5f59e641-6576-e10e-99c0-794907285580
* Content: [Modernize existing desktop apps using Desktop Bridge](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#add)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-extensions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extensions.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us about this issue. The anchor links in that article have been fixed.
