### ISSUE TITLE
App overlays cause Windows DWM to fail.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#2551]
When running applications in HDR mode ( Settings / System / Display / Play HDR games and apps ) any overlay being rendered on screen such as TaskBar, TitleBar, Volume causes the DWM to fail - the screen goes black for a second or two. We think it's because with this setting enabled, applications are running in HDR and Windows Desktop is still running in SDR, so any attempt at rendering overlays (which is a really common and unwanted event in games) causes the DWM to fail because it can't render both SDR and HDR at the same time. 

// removed suggested solutions - really need to know what the issue is first. we think we know, but...

Can you please tell us what the problem is, what is Windows doing behind the scenes to break the graphics stack when these overlays are rendered? And can this be fixed. We are paying for HDR displays and the feature can't be used on Windows. That is a real cost to customers. I think HDR has been around long enough and there are enough HDR displays on the market now that we can expect these issues to be resolved.

Here are some mentions of the subject...

2015 November / probably not HDR related, but could indicate a deeper problem that has just been coded over.
https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/windows-10-volume-control-triggers-screen-to-flash/e2977765-49e5-4525-88d2-83194dce879f

2018 May
https://answers.microsoft.com/en-us/windows/forum/all/hdr-fullscreen-problems/33e7e516-3364-4949-bdb0-6dfac9745fdb

2019 June
https://answers.microsoft.com/en-us/windows/forum/all/hdr-issue-playing-games-or-fullscreen-youtube/ca061cc9-09b0-4424-9cbf-45111a9719ad

2019 November
https://answers.microsoft.com/en-us/windows/forum/all/black-screen-hdr-after-adjusting-volume-1803-1903/ae7ab44c-a8c1-40aa-a28d-6e3bad15ad3e?page=1&tm=1593014549203

2020 January
https://gaming.stackexchange.com/questions/361167/black-screen-for-1-2-seconds-while-alt-tabbing-a-fullscreen-game-or-using-a-wind

2020 February
https://answers.microsoft.com/en-us/windows/forum/all/issues-when-playing-games-in-full-screen-with-play/56d2b240-0856-4c12-a653-f454b13c8c0f

2020 April
https://www.reddit.com/r/Windows10/comments/fsvec7/windows_10_2004_hdr_any_improvements/

2020 April
https://answers.microsoft.com/en-us/windows/forum/all/hdr-on-black-screen/783633cf-3149-4c78-a44d-3ccdb76677c3

2020 April
https://www.nvidia.com/en-us/geforce/forums/g-sync-monitors/7/377104/hdr-off-and-on-after-adjusting-volume-windows-1803/

2020 June
https://www.reddit.com/r/Monitors/comments/gzcytz/hdr_causes_black_screens_in_games_with_lenovo/

2020 June
https://www.reddit.com/r/ASUS/comments/hdixlp/support_asus_vg27aq_black_screens_when_changing/

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. I'm afraid we might not be able to provide an answer as the scope of our feedback channel here on GitHub covers specific documentation fixes. However, I can help redirect you to the right channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. It seems the scope of this covers many areas as you detailed in your feedback.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
