### ISSUE TITLE
restrictedcapabilities URL is missing

### ISSUE THREAD

**Issue by Druffl3** [MicrosoftDocs/windows-uwp#2552]
[Enter feedback here]

The namespace to be referred to enable restricted capabilities is not valid anymore.

The url:
`xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"`

Error received:

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee37beb-26fc-4eca-d48e-08b4c1563b2f
* Version Independent ID: 2cf94c45-f764-78fc-f72b-ea35a09ba066
* Content: [Run in the background indefinitely - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly)
* Content Source: [windows-apps-src/launch-resume/run-in-the-background-indefinetly.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-in-the-background-indefinetly.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
