### ISSUE TITLE
Indicate roaming data is deprecated

### ISSUE THREAD

**Issue by soumyamahunt** [MicrosoftDocs/windows-uwp#2553]
[The deprecated features documentation](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features) describes roaming to be deprecated and will be removed in future. Indicate roaming is deprecated in this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340f7839-6454-f1b5-ced5-5000964efc2e
* Version Independent ID: f83df5c8-e149-df6e-243f-07311caab297
* Content: [Store and retrieve settings and other app data - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data)
* Content Source: [windows-apps-src/design/app-settings/store-and-retrieve-app-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/app-settings/store-and-retrieve-app-data.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MarcoEnxuto** [comment]
So Roaming settings is really deprecated am i right? I'm asking because the doc it's not updated since june. @jwmsft

**Comment by michael-hawker** [comment]
@jwmsft can this be raised in priority? The other [API related docs](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.roamingfolder?view=winrt-19041) don't seem to call this out either?

There's been more recent [articles](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-10-roaming-settings-for-remote-work-scenarios/ba-p/1544100) that are still writing about these features and pointing to these docs, so it's important they reflect and help developers migrate off things that will be removed in the future.

I believe these might be other effected docs as well:
- https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles
- https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/folder-redirection-rup-overview

**Comment by jwmsft** [comment]
@michael-hawker, thanks for the reminder. I've added warnings to this article and the API docs.

The two Windows Server articles you mention are owned by another team, so I've opened a new issue for those docs to be reviewed ([windowsserverdocs issue 5250](https://github.com/MicrosoftDocs/windowsserverdocs-pr/issues/5919)).
