### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by molikmiah** [MicrosoftDocs/windows-uwp#2555]
There is a minor typographic error within the sentence below which appears in Walkthrough Section 4. The value of "PoinerLockControls.js" should actually read "PointerLockControls.js"

The **PoinerLockControls.js** library uses the mouse to rotate the camera in the direction that the mouse is moved, allowing the player to look around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb09e22f-06a2-2d33-79f7-2772cf054ede
* Version Independent ID: 81b93e62-e49f-9dba-481d-2ddad712ad11
* Content: [Get Started Tutorial - A 3D UWP game in JavaScript - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-started-tutorial-game-js3d)
* Content Source: [windows-apps-src/get-started/get-started-tutorial-game-js3d.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/get-started-tutorial-game-js3d.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thank you for your feedback. I've made the noted fix, and it should be published shortly.
