### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by 4epos** [MicrosoftDocs/windows-uwp#2559]
The section 'Render the composition to a video file' has a typo in the code:
if (results != TranscodeFailureReason.None || status != AsyncStatus.Completed)
should be
if (results != TranscodeFailureReason.None || saveOperation.status != AsyncStatus.Completed)
Cheers,
Chris Ian Burkinshaw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716a3759-283a-0e9b-9f36-0720f2541a9b
* Version Independent ID: 7dbd0441-0676-0c05-b574-c96a5511ca30
* Content: [Media compositions and editing - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-compositions-and-editing)
* Content Source: [windows-apps-src/audio-video-camera/media-compositions-and-editing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/media-compositions-and-editing.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hi. The code works the same either checking the Status property of the Async operation or capturing the status value passed into the completed handler. Can you share any info you have on why using the method you suggest is better than the code as-is? Thanks.

**Comment by 4epos** [comment]
Apologies, it was just in reference to the example code given at
[https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-compositions-and-editing](url)
