### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by mediagatewizard** [MicrosoftDocs/windows-uwp#2561]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c07ba9-8f4f-c051-c945-16742c7fe409
* Version Independent ID: 61c4da19-8278-4764-05a4-000653932b83
* Content: [Provision Device Portal with a custom SSL certificate - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-ssl#create-an-ssl-certificate-with-the-root-ca)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-ssl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-ssl.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**
$IssuedTo = "localhost"
$Password = "PickAPassword"
$OutputPath = "c:\temp\"
$rootCA = Import-Certificate -FilePath C:\temp\WdpTestCA.cer -CertStoreLocation Cert:\CurrentUser\My\

# Create SSL cert signed by certificate authority
$IssuedToClean = $IssuedTo.Replace(":", "-").Replace(" ", "_")
$FilePath = $OutputPath + $IssuedToClean + ".pfx"
$Subject = "CN="+$IssuedTo
$cert = New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -Subject $Subject -DnsName $IssuedTo -Signer $rootCA -HashAlgorithm "SHA512"
$certFile = Export-PfxCertificate -cert $cert -FilePath $FilePath -Password (ConvertTo-SecureString -String $Password -Force -AsPlainText)

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @mediagatewizard - can you clarify your issue? You can also use our Open Publishing platform to submit PRs with your suggested updates. Just click the Edit button near the top of the topic and you can use the GitHub editor. Thanks!

**Comment by lastnameholiu** [comment]
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback!
