### ISSUE TITLE
'Complete Schema' misses 'Switches' keyword at root level

### ISSUE THREAD

**Issue by jakopo87** [MicrosoftDocs/windows-uwp#2564]
`Silent` and `SilentWithProgress` in the `Complete Schema` produce a warning during validation,
they shound be nested under `Switches` at root level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657479f-c0b7-6358-c7d0-0402215edaa5
* Version Independent ID: 8976699b-cdba-5206-bdb0-8a0875acfe45
* Content: [Create your package manifest](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema)
* Content Source: [hub/package-manager/package/manifest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/manifest.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. The article has been updated to fix this issue.
