### ISSUE TITLE
Using InputInjector to generate pen inputs incorrectly scales pen pressure by 0.25

### ISSUE THREAD

**Issue by Ryken100** [MicrosoftDocs/windows-uwp#2567]
When using `Windows.Input.Preview.Injection.InputInjector` to generate pen inputs, the generated pen input's pressure will always be 0.25/one quarter of the value you specify in the `InjectedInputPenInfo.Pressure` property. So if you set `InjectedInputPenInfo.Pressure` to 1, the system will generate a pen input with a pressure of 0.25. If you set the pressure to 0.5, the system will generate an input with a pressure of 0.125.

If you set `InjectedInputPenInfo.Pressure` to a value greater than 1, an exception will be generated. So you cannot set the pressure to 4 and have it be scaled down to 1.

I've created a repro in [this repo](https://github.com/Ryken100/UWPBugRepros), the VS solution is in the InjectedPenPressure folder.

Once you've built and launched the repro, there are two ways to interact with it. The first way is to click the top half of the app with pen, mouse or touch, and it will inject a pen input with equivalent pressure in the bottom half. The second way is to set the pressure slider to any value you want, then click the "Inject an input" button which will inject an a pen input in the bottom half with pressure equal to the value of the slider.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. Unfortunately, this feedback channel covers specific documentation fixes and not broader product feedback or questions. 

May I suggest that you direct your question/feedback over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
