### ISSUE TITLE
What does "0}" mean in XAML

### ISSUE THREAD

**Issue by nxtn** [MicrosoftDocs/windows-uwp#2571]
*generic.xaml* and *themeresources.xaml* are mentioned in the docs as reference sources. Could you explain what does `"0}"` mean in these two files?

generic.xaml Line 11697

```xaml
<SplineDoubleKeyFrame KeyTime="0:0:0.167" KeySpline="0.1,0.9 0.2,1.0" Value="0}" />
```

generic.xaml Line 23325, Line 30724
themeresources.xaml Line 9282, Line 12717

```xaml
<SplineDoubleKeyFrame KeyTime="0:0:0.167" KeySpline="0.2,0 0,1" Value="0}" />
```

#### Version

C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.19041.0\Generic\generic.xaml
C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.19041.0\Generic\themeresources.xaml

TIA

**Comment by MikeHillberg** [comment]
@ranjeshj - this looks like a product bug

**Comment by ranjeshj** [comment]
Agree. This should be fixed in the product.

**Comment by ranjeshj** [comment]
Moved to WinUI repo.

**Comment by nxtn** [comment]
Thank you!
