### ISSUE TITLE
Mixed Reality documentation is missing in Device Portal Documentation

### ISSUE THREAD

**Issue by Filimindji** [MicrosoftDocs/windows-uwp#2572]
Hello,

With Windows 10 2004 now released, Mixed Reality documentation is missing in Device Portal Documentation.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606c1247-47ba-a3fd-3abc-c072336bf019
* Version Independent ID: 729ff3d9-ebe0-bf23-605c-1ea1b0f2d3bd
* Content: [Device Portal core API reference - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core?redirectedfrom=MSDN#feedback)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by mattwojo** [comment]
Thanks for filing this @Filimindji and apologies for the late reply. 

For HoloLens, this is the documentation for Device Portal: 
https://docs.microsoft.com/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-windows-device-portal 

Windows Mixed Reality runs on regular desktop, so it’s the same portal as desktop.

Does that address what you're asking for?  I'll get the documentation updated to reflect this.

**Comment by mattwojo** [comment]
Added this note in the docs: https://github.com/MicrosoftDocs/windows-uwp/commit/a19fab216bb7701c2ce3c03701ff11cebba3b1f5

**Comment by Filimindji** [comment]
Hello,

I was referring to this page :

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/device-portal-api-reference#map-manager

and specifically about the buttons (Reset System Map, Anchors Export System Map, Anchors Export System Map Export System Anchors, Upload a map, Upload an anchors file) that are not documented in the API.

**Comment by mattwojo** [comment]
Thanks for clarifying @Filimindji -- I've opened a new issue on the Mixed Reality docs repo for the MR team to address as that Device Portal API Ref page is not a part of this repo or our Windows Apps content -- so I'm not equipped to address, but the team over there should be able to resolve this. Thanks again for raising this awareness.
Link to the new issue: https://github.com/MicrosoftDocs/mixed-reality/issues/536
