### ISSUE TITLE
Chromium Edge does not support web-to-app linking

### ISSUE THREAD

**Issue by mcdurdin** [MicrosoftDocs/windows-uwp#2573]
Chromium Edge does not support web-to-app linking and from what I understand there are no plans to do so. This content in this page should be marked as deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e251da-3cab-4aa0-2915-21189cf71bef
* Version Independent ID: b244b311-a0e5-185d-df82-1dadf3fe6416
* Content: [Enable apps for websites using app URI handlers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking#associate-your-app-and-website-with-a-json-file)
* Content Source: [windows-apps-src/launch-resume/web-to-app-linking.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/web-to-app-linking.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
