### ISSUE TITLE
WinUI 3.0 and with webview2 with support yo xbox one? 

### ISSUE THREAD

**Issue by darkxex** [MicrosoftDocs/windows-uwp#2579]
Is possible add support to xbox one with webview2 and winui 3?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3.0 Preview 1 (May 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by mdtauk** [comment]
I think I heard that WinUI support for Xbox Series X wont be there at launch, but would be coming in the future.

I would assume the software platform will be shared, but I have not heard for sure, anything about what is to come for Xbox One.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @darkxex, I'm closing this issue as it's not a documentation concern.

However, the WinUI team welcomes feedback, suggestions, and issues at https://github.com/microsoft/microsoft-ui-xaml.
