### ISSUE TITLE
Excellent documentation

### ISSUE THREAD

**Issue by gotdang** [MicrosoftDocs/windows-uwp#2582]
I'm a fairly experienced Windows and Linux user, and this documentation, explaining how to install nvm, nodejs and npm was outstanding. I love how the links go right where they should. It was easy to read through the text, clicking the appropriate link, running the appropriate command and so on. There were no hiccups or snags. Absolutely wonderful!
Thank you,
    --dang

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Wow! Thank you so much @gotdang. We don't get very many of these sort of encouragement issues being filed and it's much appreciated. I hope that I can continue to offer this sort of value in the upcoming articles I'm working on. (Currently an expansion of the Docker tutorial as that's already growing outdated).
