### ISSUE TITLE
Need Mixed Reality pages detailed here for portal

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/windows-uwp#2584]
From referral page, Mixed Reality is listed as shown on page in the list:

      https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-desktop

This page needs to detail out the Mixed Reality interface as well.   This is a gap that is not filled elsewhere and needs to be part of the details for desktop portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bbcf84-953d-9f5c-0c48-a5f1bdb7507f
* Version Independent ID: 8ba7dc0d-40be-daa0-4e11-d514e36a852b
* Content: [Windows Device Portal overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal)
* Content Source: [windows-apps-src/debug-test-perf/device-portal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by mattwojo** [comment]
Hi for raising this issue @snakex2000 and appologies for the late reply. It looks like this same issue was filed in https://github.com/MicrosoftDocs/windows-uwp/issues/2572... so I'm going to close this one if you wouldn't mind moving any further replies to 2572.
Thanks again!

**Comment by mattwojo** [comment]
Added this note in the docs: https://github.com/MicrosoftDocs/windows-uwp/commit/a19fab216bb7701c2ce3c03701ff11cebba3b1f5
