### ISSUE TITLE
document: Show multiple views with AppWindow

### ISSUE THREAD

**Issue by dscavezze** [MicrosoftDocs/windows-uwp#2587]
The document "Show multiple views with AppWindow" at https://docs.microsoft.com/en-us/windows/uwp/design/layout/app-window should be updated to tell users that it is important to keep the code in the AppWindow OnClosed handler to a minimum.

Here's a link about a difficult problem that could have been avoided if this "rule of thumb" was more widely known and observed.
https://stackoverflow.com/questions/62879584/when-i-close-an-appwindow-why-cant-i-open-a-new-appwindow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4f7b2c-c4ba-5910-6bf8-e07236db6fc7
* Version Independent ID: 3bc5bd9f-5233-222a-ad17-3b7266331f79
* Content: [Use the AppWindow class to show secondary windows for an app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/app-window)
* Content Source: [windows-apps-src/design/layout/app-window.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/app-window.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for this feedback. A note has been added to the doc.
