### ISSUE TITLE
Non-encoded angle brackets

### ISSUE THREAD

**Issue by paszklar** [MicrosoftDocs/windows-uwp#2593]
In the section [Iterable parameters](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/pass-parms-to-abi#iterable-parameters) template parameters of IIterable use non-escaped angle brackets, as seen in the page source:

> &lt;p&gt;In some cases, the object that you have may actually implement the &lt;strong&gt;IIterable&lt;/strong&gt; that you want. For example, the &lt;strong&gt;IVectorView&amp;lt;StorageFile&amp;gt;&lt;/strong&gt; produced by &lt;a href=&quot;/en-us/uwp/api/windows.storage.pickers.fileopenpicker.pickmultiplefilesasync&quot; data-linktype=&quot;absolute-path&quot;&gt;&lt;strong&gt;FileOpenPicker.PickMultipleFilesAsync&lt;/strong&gt;&lt;/a&gt; implements &lt;strong&gt;**IIterable&lt;StorageFile&gt;**&lt;/strong&gt;. But it also implements &lt;strong&gt;**IIterable&lt;IStorageItem&gt;**&lt;/strong&gt;; you just have to ask for it explicitly.&lt;/p&gt;

which renders them invisible:

> In some cases, the object that you have may actually implement the IIterable that you want. For example, the IVectorView<StorageFile> produced by FileOpenPicker.PickMultipleFilesAsync implements **IIterable**. But it also implements **IIterable**; you just have to ask for it explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d6f6d3b-a97d-3660-fde8-cebf73ef7968
* Version Independent ID: 8ff1309e-962a-d21e-7936-d2038c5839de
* Content: [Passing parameters into the ABI boundary - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/pass-parms-to-abi)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/pass-parms-to-abi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/pass-parms-to-abi.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @paszklar! The fix is now live, so I'll go ahead and close the issue.

-Steve
