### ISSUE TITLE
The base unit is 4 because it's the only integer ...?

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2598]
From the page's content:
> The base unit is 4 because it's the only integer that can be scaled by non-whole numbers (for example, 4*1.5 = 6).

AFAIK, this statement isn't quite correct. What about 2 (2 * 1.5 = 3), 6 (6 * 1.5 = 9), 8 (8 * 1.5 = 12) and all the other integers that can be divided by 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05005ba0-1609-f4e1-16e2-47be162453e8
* Version Independent ID: 61bf242a-12ad-606f-e125-83ed6cb72fd7
* Content: [Introduction to Windows app design (Windows apps) - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro)
* Content Source: [windows-apps-src/design/basics/design-and-ui-intro.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/design-and-ui-intro.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This statement has been updated in the documentation.
