### ISSUE TITLE
Meeting The Needs of THIS Customer

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/windows-uwp#2601]
For a long time I respected Microsoft.  It delivered reliable operating systems and a really decent IDE.  Respect ended last year.   Today the IDE is okay if overly complex and underexplained.   Windows 10 and Office are shipped before testing.  That is completely unacceptable.  But the rule is that Microsoft is earning for investors.  And that is where responsibility ends.  There is ZERO contact between customers and Microsoft executives.   Probably a good policy to follow when the corner office occupants want to avoid conflict and exposure of their malfeasance.  When I was a Univac front line employee the company provided detailed Product Descriptions and detailed operating instructions in volumes entitled User Guides.   Microsoft cannot be bothered to produce those things.  End users ask each other how products can be worked.  No Microsoft employee or contractor need dirty his hands with customer contact.   Microsoft provides PAID support.  The customer pays Microsoft to get Microsoft to discover product defects and fix them.  Microsoft pretends to teach the details of their products with their education department.  I've done that.   Not exactly the last word in instruction.   The textbooks are ground out by technical writers who barely understand the material.  But, heck, investors are happy.  What more work is there to be done?   Have a happy day.  And wash those hands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 303c0261-7ad3-cac2-33e1-ca459aef2bf2
* Version Independent ID: 8f9841b2-ab09-6f80-3b42-3ef590923af3
* Content: [Build desktop apps for Windows PCs](https://docs.microsoft.com/en-us/windows/apps/desktop/)
* Content Source: [hub/apps/desktop/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you for taking the time to share your feedback with us. Do you have any specific feedback on Windows as a development platform that we can pass along to the Windows engineering team, or any specific feedback on the Windows developer docs that we can use to improve the docs? For example, specific features or APIs that don't work the way you expect, or specific articles in the Windows developer docs that have content issues.

**Comment by mcleanbyron** [comment]
Thanks again for the taking the time to share your general feedback with us. If you have more detailed feedback about specific issues with Windows as a development platform or the Windows developer docs, please reopen this issue with the details and we'll do what we can to address them.
