### ISSUE TITLE
Sample code not working: XLS0502 error

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2609]
The sample code provided at paragraph "[Option 1: Add Items through XAML](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/listview-and-gridview#option-1-add-items-through-xaml)" doesn't work:

```xaml
<!-- No corresponding C# code is needed for this example. -->

<ListView x:Name="Fruits"> 
   <x:String>Apricot</x:String> 
   <x:String>Banana</x:String> 
   <x:String>Cherry</x:String> 
   <x:String>Orange</x:String> 
   <x:String>Strawberry</x:String> 
</ListView>
```

![XLS0502](https://user-images.githubusercontent.com/9283914/88570087-c54c9600-d03b-11ea-82c7-d9dcd4531574.png)

Please verify and correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e528879-9c1d-ec7f-70df-f69ee3def630
* Version Independent ID: dc9677a2-bdc9-e820-b919-cbc4adffc319
* Content: [List view and grid view - UWP applications ▷ Option 1: Add Items through XAML](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/listview-and-gridview#option-1-add-items-through-xaml)
* Content Source: [windows-apps-src/design/controls-and-patterns/listview-and-gridview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/listview-and-gridview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@SetTrend, in your screenshot, it appears that you have a Xamarin.Forms app. This documentation and sample code is for UWP apps, and won't work in Xamarin apps. For Xamarin documentation, see https://docs.microsoft.com/en-us/xamarin/.

**Comment by SetTrend** [comment]
I didn't realize there were differences in XAML between UWP, Xamarin.Forms (and WPF?)

Thank you for enlightening me!
