### ISSUE TITLE
Old PowerToys icon

### ISSUE THREAD

**Issue by niels9001** [MicrosoftDocs/windows-uwp#2611]
There's a new PowerToys icon. This page still shows the old one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7779352b-7b4e-dad8-7c1b-b9aba2c5e561
* Version Independent ID: a5b81b80-87a1-b6e2-8936-baf6c1a0b9c5
* Content: [Set up your development environment on Windows 10](https://docs.microsoft.com/en-us/windows/dev-environment/overview)
* Content Source: [hub/dev-environment/overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/overview.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @niels9001 - found the new icon and fixed it. 👍 
https://github.com/MicrosoftDocs/windows-uwp-pr/commit/1e06168ada5ce6013b1d07c428548f084464a286
