### ISSUE TITLE
Packaged process loader search path override needs clarification

### ISSUE THREAD

**Issue by chitturs** [MicrosoftDocs/windows-uwp#2613]
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#place-your-dll-files-into-any-folder-of-the-package

This section is confusing. Please indicate EXACTLY how packaged process loader search path works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a7e980-cfd8-6d9c-6cc5-0ca6763fd327
* Version Independent ID: 5f59e641-6576-e10e-99c0-794907285580
* Content: [Modernize existing desktop apps using Desktop Bridge](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#place-your-dll-files-into-any-folder-of-the-package)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-extensions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extensions.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. This section has been updated per guidance from the engineering team that owns this functionality.
