### ISSUE TITLE
Some links on "Asynchronous programming in C++" go to the old VS 2015 documentation

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/windows-uwp#262]
Relevant page "Asynchronous programming in C++":
  - [Source](https://github.com/MicrosoftDocs/windows-uwp/blob/8846d7a870eabd0246e3e0e6b3b206becbb71b0b/windows-apps-src/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps.md)
  - [Doc on MSDN](https://docs.microsoft.com/en-us/windows/uwp/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps)

For example, if I click on the ["task class"](https://msdn.microsoft.com/library/windows/apps/xaml/hh750113.aspx) link or the ["concurrency"](https://msdn.microsoft.com/library/windows/apps/xaml/dd492819.aspx) link near the top of the page, I'm brought to the old VS 2015 documentation. Instead, I should be brought to the latest VS 2017 documentation.

### Additional Feedback

Frustratingly, clicking on the ["Visual Studio 2017 Documentation" link](https://docs.microsoft.com/en-us/visualstudio/) on the ["task class"](https://msdn.microsoft.com/library/windows/apps/xaml/hh750113.aspx) or ["concurrency"](https://msdn.microsoft.com/library/windows/apps/xaml/dd492819.aspx) page just brings me to the VS 2017 documentation homepage rather than bringing me to the matching page in the VS 2017 documentation. Then when I try to find the "task class" page by using search, it has a default tag of "VS IDE":

![image](https://user-images.githubusercontent.com/199935/33508921-3e7ac28a-d6b2-11e7-9175-8578e900b478.png)

I'm not sure what that means but it doesn't sound relevant for the "task class" page I just came from in the VS 2015 docs. I searched for "task class" using that tag but I didn't see the page I was looking for. I tried removing the "VS IDE" tag and searching for "c++ task" but this surprisingly returned 0 results. Next I searched for "task class" with no tags and found "task_canceled Class" which is not quite what I was looking for but it's close. On that page, I put "task" into the "Filter" box and finally found [the page I wanted](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/task-class). It's frustrating that it took me a couple of minutes to find this page.

On that final page, I noticed that searching has a tag of "C++":

![image](https://user-images.githubusercontent.com/199935/33509115-bec65f98-d6b3-11e7-9291-aa749fdb971a.png)

How can I set the tag myself? For example, maybe I want to switch the tag from "VS IDE" to "C++".

Adam Comella
Microsoft Corp.

**Comment by normesta** [comment]
Thank you for pointing this out. I'll update each outdated link in the topic and close the issue once they are all addressed and live. As far as search experience, I'll reach out to the relevant contacts on our side to see how we can improve that. Thank you.

**Comment by normesta** [comment]
Ok. I've updated the links on that page to point to the most current docs.microsoft.com versions of those topics. As for general search, I've learned that you can't manually modify the search tag. the "IDE" tag is the default tag. To get a C++-related ref tag in the search box, you have to click through to Languages->C++.  The right folks are aware of the less than ideal UX flow, but it's the experience that we have today. Thank you for your feedback!

**Comment by rigdern** [comment]
I never thought to try going to "Languages->C++". Thanks for fixing the links and for following up on the search UX.
