### ISSUE TITLE
Uno Platform

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/windows-uwp#2625]
You add Node, Python, and Android, as the first 3 options, when these are not even Microsoft technologies.

The [Uno Platform](https://bit.ly/2PsphTB) however, although not a Microsoft technology itself, takes the superpowers of UWP and WinUI XAML & C#, and makes the same code base run on Android, iOS, Linux, macOS and even web (via wasm).

I bet it deserves its badge on this page.

If you give me a greenlight I can PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7779352b-7b4e-dad8-7c1b-b9aba2c5e561
* Version Independent ID: a5b81b80-87a1-b6e2-8936-baf6c1a0b9c5
* Content: [Set up your development environment on Windows 10](https://docs.microsoft.com/en-us/windows/dev-environment/overview?ocid=3017123&MC=.NET&MC=Vstudio&MC=JavaScript&MC=Windows&MC=CloudDev)
* Content Source: [hub/dev-environment/overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/overview.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by bitcrazed** [comment]
Great suggestion @weitzhandler - we'll carve out some time to create some guidance for Uno developers.

Do you have any favorite resources, blogs, sites, forums, videos, etc. that you think we should link to?

**Comment by mattwojo** [comment]
Thanks for filing this @weitzhandler. I added a link to the Uno platform in our article about choosing an app platform in the Windows Desktop docs as that seems like the right audience: https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform

https://github.com/MicrosoftDocs/windows-uwp/commit/c764be208d9a1e346de9eb691c60928757a7733e

**Comment by weitzhandler** [comment]
@mattwojo, although I was hoping for a banner at least the size of Python and the rest of the services, thank you very much for what you've done.
Would you accept a PR if I tried to add a banner/shield to the general page with a reference to Uno Platform?

**Comment by weitzhandler** [comment]
@mattwojo, although I was hoping for a banner at least the size of Python and the rest of the services, thank you very much for what you've done.
Would you accept a PR if I tried to add a banner/shield to the general page with a reference to Uno Platform?

**Comment by mattwojo** [comment]
Thanks @weitzhandler. 
Which general page are you referring to?

**Comment by mattwojo** [comment]
Oh, looking back on the thread I'm assuming that you mean: https://docs.microsoft.com/windows/dev-environment/overview

From what I understand, the target audience for Uno is Windows/UWP devs looking to expand the devices their app will run on. I'm hoping to continue working with the team to find a better way to organize and display the various paths for Windows-focused devs, but currently the Desktop platform area where I added Uno seems like the right place. 
It's not a good fit for the Dev Environment page currently, but I'm still working on plans to exapand the paths listed there and will keep Uno on the radar.

**Comment by weitzhandler** [comment]
> Oh, looking back on the thread I'm assuming that you mean: https://docs.microsoft.com/windows/dev-environment/overview

Yes exactlty. Uno deserves a banner alongside UWP/WinUI.
