### ISSUE TITLE
Article should link to main x:Bind document

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2626]
There are important details to how x:Bind works in the [main article here](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension); however, this article is not linked to in this document.

It'd be great if there was a 'Related Topics' section pointing to the main x:Bind document.

For instance the "Path to function" section could also link to https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#property-path and 'indexers' to https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#collections.

I'll try opening a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fdf7014-70bd-f562-046a-432f5f5caf11
* Version Independent ID: f45e3d08-66e0-1b74-2c0d-595345e7f3b1
* Content: [Functions in x:Bind - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings#path-to-the-function)
* Content Source: [windows-apps-src/data-binding/function-bindings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/function-bindings.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Changes implemented here: https://github.com/MicrosoftDocs/windows-uwp/pull/2627
