### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by ET3D-ET3D** [MicrosoftDocs/windows-uwp#2629]
The UserGamepadPairingUWP (GitHub) link is wrong. It should be https://github.com/microsoft/Xbox-ATG-Samples/tree/master/UWPSamples/System/UserGamepadPairingUWP 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d869e8b-376a-bde0-ebca-3a67bf38f1f2
* Version Independent ID: 3e36f4d2-2549-8266-a7ec-8cbf2fe121b3
* Content: [Input practices for games - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/input-practices-for-games#tracking-users-and-their-devices)
* Content Source: [windows-apps-src/gaming/input-practices-for-games.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/input-practices-for-games.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @ET3D-ET3D, I changed the link to point to the Samples Browser rather than directly to GitHub (the Samples Browser has a link to GitHub).

-Steve
