### ISSUE TITLE
sample for c++

### ISSUE THREAD

**Issue by putrasurya** [MicrosoftDocs/windows-uwp#2632]
Please provide C++ sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95021810-7343-a4d1-0830-4704290195b3
* Version Independent ID: 2b1f6eef-4879-475b-c8fd-fa6e01670d1e
* Content: [HttpClient - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/httpclient)
* Content Source: [windows-apps-src/networking/httpclient.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/httpclient.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @putrasurya. I've added C++/WinRT code examples in every section now.

Thanks!
Steve
