### ISSUE TITLE
BluetoothLEDevice will not disconnect

### ISSUE THREAD

**Issue by Resultfactory** [MicrosoftDocs/windows-uwp#2633]
We connect to a BluetoothLEDevice successfully, but it will never disconnect, not even after disposing referenced objects. We use this in an IoT UWP C# application running Windows 10, version 1903, (10.0; Build 18362).

This is a small piece of code that demonstrates this:

```
BluetoothLEDevice bluetoothLeDevice = await BluetoothLEDevice.FromBluetoothAddressAsync(ear.BluetoothAddress);
// This command connects because we set Uncached
GattDeviceServicesResult result = await bluetoothLeDevice.GetGattServicesAsync(BluetoothCacheMode.Uncached);
if (result.Status == GattCommunicationStatus.Success)
{
	var services = result.Services;
	foreach (GattDeviceService service in services)
	{
		Debug.WriteLine($"{service.Uuid} is in session {service.Session.SessionStatus}");
		if (service.Session.SessionStatus == GattSessionStatus.Active)
		{
			service.Session.Dispose();
		}
		service?.Dispose();
	}
}
bluetoothLeDevice?.Dispose();
bluetoothLeDevice = null;
GC.Collect();
```

Can anyone tell us if we are missing something that causes the device never to disconnect?

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation, but rather like a support request.

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
