### ISSUE TITLE
Broken link 'Windows on Microsoft Learn'

### ISSUE THREAD

**Issue by robertyoung2** [MicrosoftDocs/windows-uwp#2634]
Link under heading '**New to development?**' for '**Windows on Microsoft Learn**' is broken. Correct link should be:

```javascript
//docs.microsoft.com/en-us/learn/browse/?products=windows&resource_type=module
```

Note the '?' in front of 'products'. This is reflected in the Markdown file [here](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/index.md).

The generated code on the page replaces the '?' with '%3F', resulting in the url:

```javascript
//docs.microsoft.com/en-us/learn/browse/%3Fproducts=windows&resource_type=module
```

This does not work correctly and causes a 404 error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ce3af4-0615-86cc-9d03-6cfee2e29f16
* Version Independent ID: 62c5617b-2ddb-c45e-41ae-8dc3eb82c01a
* Content: [Get started with the Universal Windows Platform (UWP) - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/)
* Content Source: [windows-apps-src/get-started/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/index.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
...Huh, that's interesting. Thanks for bringing this to our attention.

I'm currently testing a few solutions to this problem, to see if there's anything we can do to fix this, or if we just need to link to something else. A fix or redirect will be live by the end of the day.
