### ISSUE TITLE
Content of ToastSelectionBox and ToastSelectionBoxItem mingled

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2636]
The schemas of [`ToastSelectionBox`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.notifications.toastselectionbox) and [`ToastSelectionBoxItem`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.notifications.toastselectionboxitem) are intermingled on this page and currently make no sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ebc794c-dad4-28d6-b799-19b2daf922f3
* Version Independent ID: 95d05b52-288a-1c6f-760a-0b57f3b115b2
* Content: [Toast content schema - UWP applications ▷ ToastSelectionBox](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-schema#toastselectionbox)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-schema.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-schema.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
