### ISSUE TITLE
Missing prerequisites to utilize Action Center in the Cloud

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2637]
There is not explanation on how to enable **Action Center in the Cloud** in order to utilize any of the features mentioned in below section.

I.e.:
- Is a Microsoft account required?
- Is it required to enable Corana?
- ...?

How do I test _Notification Listener_, _Notification Mirroring_ and _Universal Dismiss_?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7bf8a3a-3e67-f3b9-f63c-ca53383d7f19
* Version Independent ID: b64f8103-55c0-d8bd-52b9-b4b9f7b63fdf
* Content: [Notification listener - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/notification-listener)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/notification-listener.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/notification-listener.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f801a6-3a5a-4094-cedc-7e7dd492bd91
* Version Independent ID: 599a7640-51af-e327-93b5-dc9dde7ae5b6
* Content: [Notification mirroring - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/notification-mirroring)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/notification-mirroring.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/notification-mirroring.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df20e709-807d-c9e6-1c45-d9009928f8b4
* Version Independent ID: 0a7e4d68-f080-b88b-9be9-256850cc9173
* Content: [Universal Dismiss - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/universal-dismiss)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/universal-dismiss.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/universal-dismiss.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
