### ISSUE TITLE
XML attribute value missing

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2638]
None of the XML column entries in all the tables on this page seem to contain any value.

This is probably a Markdown to HTML conversion error. The generated HTML creates an unknown `<badge>` HTML tag attributed with a `value` attribute:

```HTML
<td>`<badge value="attention">`</badge></td>
```

The `<badge>` attribute isn't rendered by browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c2e97a2-3727-fcfd-2a0d-392e31f36e06
* Version Independent ID: 17fc0652-884d-cb87-dfe8-c4e6760a5d97
* Content: [Badge notifications for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/badges.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/badges.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Jay-o-Way** [comment]
@hickeys this seems to be good now. Issue can be closed.

**Comment by SetTrend** [comment]
Confirmed.
