### ISSUE TITLE
Ingestion API can only update, delete, and commit submissions that are created through the API. Please delete the current in-progress submission and create one using the API

### ISSUE THREAD

**Issue by AndyTianDevOps** [MicrosoftDocs/windows-uwp#2641]
Any ideas about this problem?

[Enter feedback here]
![image](https://user-images.githubusercontent.com/69619680/90108307-af014280-dd7c-11ea-8d80-97297b92509a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ac48f9-fd0e-0f1e-fc75-f28cf0b83f57
* Version Independent ID: 9bfcea4f-a9cb-ab64-df07-90512002d80b
* Content: [C# sample - submissions for apps, add-ons, and flights - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/csharp-code-examples-for-the-windows-store-submission-api#create-flight-submission)
* Content Source: [windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by AndyTianDevOps** [comment]
we try to use the https://docs.microsoft.com/en-us/windows/uwp/monetize/csharp-code-examples-for-the-windows-store-submission-api demo to delete the submission.

However, there is an exception pop up

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation, but rather like a support request.

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
