### ISSUE TITLE
Manifest instruction gives confusing results

### ISSUE THREAD

**Issue by worldspawn** [MicrosoftDocs/windows-uwp#2642]
Step 1.5 asks to modify the manifest adding:

```
"identifierUris" : [                                
        "https://onestore.microsoft.com",
        "https://onestore.microsoft.com/b2b/keys/create/collections",
        "https://onestore.microsoft.com/b2b/keys/create/purchase"
    ],
```

This doesn't work. If I include the first entry `"https://onestore.microsoft.com"` I receive the message
```
Failed to update drawboard-accounts-store application. Error detail: A conflicting object with one or more of the specified property values is present in the directory. [5rjSw]
```

All appearances in the UI indicate this save did not complete.

I exported my applications and the identifier uri's shown for my app in the csv export are 
```
[""https://onestore.microsoft.com"",""https://onestore.microsoft.com/b2b/keys/create/purchase"",""https://onestore.microsoft.com/b2b/keys/create/collections""]
```

 When I go back into the application and open the manifest I see:

```
"identifierUris": [
		"https://onestore.microsoft.com/b2b/keys/create/purchase",
		"https://onestore.microsoft.com/b2b/keys/create/collections"
	],
```

which is what it was before I tried to save with `https://onestore.microsoft.com` in the list. Seems broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
