### ISSUE TITLE
Spelling mistake in example toast notification

### ISSUE THREAD

**Issue by thomasguillard** [MicrosoftDocs/windows-uwp#2651]
Hi there

One of those :)

The image under [1. Actionable notifications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-ux-guidance#1-actionable-notifications) has the word "niece" misspelt.

![image](https://user-images.githubusercontent.com/22102173/90763792-3a2f8a80-e2df-11ea-9778-692d128b91fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c53ac4f8-c2d0-67c8-586c-0de353fcefbd
* Version Independent ID: 877f6f16-1978-455b-3f1e-a7e4cd6f8121
* Content: [Toast UX Guidance - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-ux-guidance)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-ux-guidance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-ux-guidance.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
