### ISSUE TITLE
You never used property change event declared in view model of 3rd example. Why did you put it then?

### ISSUE THREAD

**Issue by Path2Freedom** [MicrosoftDocs/windows-uwp#2652]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9331458-c8a4-8936-6b4a-a58a8685cbe7
* Version Independent ID: c8be4bc6-bb46-244d-402b-8cba837e65d7
* Content: [Commanding in Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/commanding)
* Content Source: [windows-apps-src/design/controls-and-patterns/commanding.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/commanding.md)
* Service: ****
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback. An update to the topic should be live soon.
