### ISSUE TITLE
SystemBaseHighColor

### ISSUE THREAD

**Issue by jayypee13** [MicrosoftDocs/windows-uwp#2654]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cea7f12-8e6b-a35f-5f1d-1a4fd952894b
* Version Independent ID: bebe9ecb-6618-48df-7edd-b5d512986800
* Content: [StaticResource markup extension - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/staticresource-markup-extension)
* Content Source: [windows-apps-src/xaml-platform/staticresource-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/staticresource-markup-extension.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by hkhmsft** [comment]
Hi @jayypee13 , it looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed. Thanks!
