### ISSUE TITLE
docs: 'Design and UI' link not working

### ISSUE THREAD

**Issue by robertyoung2** [MicrosoftDocs/windows-uwp#2656]
On the page [Get started with Windows 10 apps](https://docs.microsoft.com/en-us/windows/uwp/get-started/) under the heading "**Learn about Windows 10 Apps**", the link for **Design and UI** appears to be broken. On click leads to the link:

```
https://developer.microsoft.com/en-us/windows/apps/design
```

with the error message: **"Content is Offline"**. This may be a temporary service down bug, but worth raising and noting as an issue.

**Comment by QuinnRadich** [comment]
Thanks for bringing this issue to our attention. I've applied a fix, and it should be live shortly.
