### ISSUE TITLE
update docs for consuming winrt apis

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/windows-uwp#2662]
The doc provides details on the tool, but I'd imagine that the 95% of C# apps don't need to use the tool. They have a PackageReference to the `Microsoft.Windows.Sdk.Contracts` package and need to know to remove the package reference and change their TFM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afe5c59-cf07-82d5-5259-c751d48abadb
* Version Independent ID: 8b35d1e6-fc3c-e490-2768-1c5e113e0820
* Content: [C#/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/?source=docs)
* Content Source: [windows-apps-src/csharp-winrt/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/csharp-winrt/index.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The guidance about how to call WinRT APIs from .NET applications is in [this article](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance), and we recently updated this article with instructions for using the new Target Framework Monikers for .NET 5 Preview 8 and later.

**Comment by mcleanbyron** [comment]
Thanks for your feedback!
