### ISSUE TITLE
No info provided about how to integrate config file into VS project

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2663]
If I want to modify the configuration file created with makepri, then there's no info here on how to specify as part of my csproj file on how to integrate it back into the build system to be used as part of msbuild.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011ebf05-6a55-1ba3-c951-48717d12d15d
* Version Independent ID: 3854898b-aee8-c08c-e7cc-dc08465a3218
* Content: [MakePri.exe configuration file - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/makepri-exe-configuration)
* Content Source: [windows-apps-src/app-resources/makepri-exe-configuration.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/makepri-exe-configuration.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
