### ISSUE TITLE
[WinUI 3 Preview 2] Docs - Outdated SDK Links

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/windows-uwp#2664]
The install links for .NET5 Preview SDKs incorrectly download the wrong version (preview 5).

![image](https://user-images.githubusercontent.com/3520532/91459156-5473e600-e854-11ea-9e6a-8e07c2aa0380.png)

It would be better to use a more generic installer link that always gets the latest version (currently preview8).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3 Preview 2 (July 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @LanceMcCarthy - these instructions are constantly being updated as WinUI 3 matures. I'm closing this issue as I believe the topic has been revised and additional topics added that cover these details. Please open a new issue if you find this is not the case.
