### ISSUE TITLE
How to change orientation of radiobuttons?

### ISSUE THREAD

**Issue by sukesh-ak** [MicrosoftDocs/windows-uwp#2668]
The documentation talks about different orientation with samples but no mention of how the orientation can be changed. By default, the radiobuttons are always in vertical orientation and I need in horizontal orientation including the Header.

Example:
Units : [x] Kmph [ ] Mph

```
 <muxc:RadioButtons Header="Units:" SelectedIndex="0">
   <RadioButton Content="Kmph" />
   <RadioButton Content="Mph" />
 </muxc:RadioButtons>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d56b7d5e-8ac1-6be4-6017-d4bf2ad02f5e
* Version Independent ID: ebb92a1f-f9d1-cdcc-5a3d-6a1b53005f40
* Content: [Guidelines for radio buttons - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/radio-button)
* Content Source: [windows-apps-src/design/controls-and-patterns/radio-button.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/radio-button.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to your issue. The feedback channel you're using here is for feedback about the documentation in this topic. For time-sensitive questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question.

Horizontal layout is covered in the [multiple columns](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/radio-button#defining-multiple-columns) section of the doc. To have items arranged in a single horizontal row, set MaxColumns equal to the number of radio buttons. However, there is no way to include the Header in the horizontal layout as in your example. For that, you will have to leave the Header property empty and use a separate TextBlock for the label.

**Comment by sukesh-ak** [comment]
> Hi, sorry for the delayed response to your issue. The feedback channel you're using here is for feedback about the documentation in this topic. For time-sensitive questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question.

Thank you will do so in future.


> Horizontal layout is covered in the [multiple columns](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/radio-button#defining-multiple-columns) section of the doc. To have items arranged in a single horizontal row, set MaxColumns equal to the number of radio buttons. However, there is no way to include the Header in the horizontal layout as in your example. For that, you will have to leave the Header property empty and use a separate TextBlock for the label.

There is by default too much padding so its difficult to bring it closer when only 2 or 3 items are there. This beats the purpose.

**Comment by christosk92** [comment]
Maybe im a bit late, but for anyone who is wondering:
override the RadioButtons style as such:

```xml
      <RadioButtons.Style>
                                    <Style TargetType="RadioButtons">
                                        <Setter Property="IsTabStop" Value="False" />
                                        <Setter Property="TabNavigation" Value="Once" />
                                        <Setter Property="Template">
                                            <Setter.Value>
                                                <ControlTemplate TargetType="RadioButtons">
                                                    <StackPanel>

                                                        <VisualStateManager.VisualStateGroups>
                                                            <VisualStateGroup x:Name="CommonStates">
                                                                <VisualState x:Name="Normal" />

                                                                <VisualState x:Name="Disabled">
                                                                    <VisualState.Setters>
                                                                        <Setter Target="HeaderContentPresenter.Foreground" Value="{ThemeResource RadioButtonsHeaderForegroundDisabled}" />

                                                                    </VisualState.Setters>
                                                                </VisualState>

                                                            </VisualStateGroup>

                                                        </VisualStateManager.VisualStateGroups>
                                                        <ContentPresenter x:Name="HeaderContentPresenter" Content="{TemplateBinding Header}" ContentTemplate="{TemplateBinding HeaderTemplate}" Foreground="{ThemeResource RadioButtonsHeaderForeground}" Margin="{ThemeResource RadioButtonsTopHeaderMargin}" />
                                                        <ItemsRepeater x:Name="InnerRepeater">
                                                            <ItemsRepeater.Layout>
                                                                <StackLayout  Spacing="-60" 
                                                                              Orientation="Horizontal"/>
                                                            </ItemsRepeater.Layout>
                                                        </ItemsRepeater>
                                                    </StackPanel>

                                                </ControlTemplate>
                                            </Setter.Value>
                                        </Setter>
                                    </Style>
                                </RadioButtons.Style>
```


The default padding still exists, to get around this in a hacky way: Set the ``Spacing`` property of the ``StackLayout`` to a negative value.
