### ISSUE TITLE
Order of Sections change suggestion - for https://docs.microsoft.com/en-us/windows/uwp

### ISSUE THREAD

**Issue by CheathamPatrick** [MicrosoftDocs/windows-uwp#267]
Hello and thanks for considering my suggestions. I find that while using the UWP documentation, the structure of App basic considerations is difficult to navigate, unable find what I need to know about "under the hood" issues of a UWP app that would be the bare basics of knowing before laying out design and playing with controls. I feel that somewhere **before** _"> Design and UI"_ there should be several sections of basic **"App Structural  Essentials"** (or something like that) to alert the new UWP developer, reading through and expecting to get to know essentials right away and before diving into control design, of key things to know to make just about any App work properly. To find this information now, I must scour through such sections as: _">App Resources", ">Data Binding", ">Debugging, Testing, and Performance", ">Launching, Resuming, and Background Tasks", ">Files, Folders, and Libraries", and ">XAML Platform"_, as well as a few other sections. The idea I am getting at is like from an old Metro programming book for Windows 8 Runtime, whereby the authors usually ensure to layout some of these basics at the beginning, before going into design methods and philosophy. I was thinking that **not all** the content in these sections I listed need go into some sort of "App Structural Essentials" article, and maybe just links to key parts of these sections I mentioned, as sort of a primer of basic links to your more detailed references, and I would place it just after ">Get Started" and before ">Design and UI". Or alternatively, just some introductory touch of discussion of such things as data binding, local and remote storage, and other issues every new developer would be well served to at least be alerted to (if not explain it all) right at the beginning. I wonder if anyone has delved into the UWP user's guide and found themselves designing an app, and then later wondering why all the wasted time of starting over or revision, and why it was due to things like data binding and event handling were tucked away in sections low down the docs tree, and with titles sounding much like esoteric advanced issues, when in fact the issues are crucial for any developer to apply to his or her coding, immediately. Thanks for reading, and please know that overall I think the personnel writing this documentation are doing an absolutely excellent job, and putting together some of the best-written coding discussions and examples I have ever seen yet in any documentation for any system, and I have been at this since QuickBasic and Visual Basic version 1.0. 

**Go Microsoft Windows! -- Life Without Walls!**

**Comment by TylerMSFT** [comment]
Thank you, Patrick. Your post is timely because we are thinking about this issue right now. The points you raise validate ideas we have about improvements we'd like to make. Give us a little time and we hope to smooth out the issues you raise with the introductory information.
