### ISSUE TITLE
The keyboard events page should mention keyboard accelerators!

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/windows-uwp#2678]
I am trying to write some UWP code that has shortcuts for common actions. I started off by searching for KeyDown and KeyPress events, like I'm used to with web development, and I wound up on the Keyboard events page.

I read up and found the events I thought I'd need.

Later, though, I independently discovered [Keyboard Accelerators](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)! They fit my needs for hotkeys *much* better, and they have good accessibility benefits, too.

Is it worth leaving a note on the Keyboard events page about keyboard accelerators? I wouldn't have discovered them if I'd just read that one page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97da3a39-065c-bc6f-353a-66d55ac69b07
* Version Independent ID: ebe22051-3829-90ec-ce52-a99deac67089
* Content: [Keyboard events - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events)
* Content Source: [windows-apps-src/design/input/keyboard-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-events.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the suggestion, @citelao. I've updated the access keys, accelerator keys, and keyboard events topics to hopefully address this issue.
