### ISSUE TITLE
possible errors in WSL when running python3 -m pip

### ISSUE THREAD

**Issue by nobodhi** [MicrosoftDocs/windows-uwp#2679]
In this step:

`python3 -m pip install flask`

You may encounter an error such as this:

`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f655471da30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/`

When researching this problem you may get led down several rabbit holes, none of which are particularly productive on WSL Ubuntu. (Warning: on WSL do not try editing resolv.conf, that file is a symbolic link and modifying it is a can of worms). Unless you are running an aftermarket firewall, the likely solution is to simply re-install pip: 

```
sudo apt -y purge python3-pip
sudo python3 -m pip uninstall pip
sudo apt -y install python3-pip --fix-missing
```

H/T - https://github.com/microsoft/WSL/issues/4020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23257172-281d-1069-0db2-d63d72d3d8cc
* Version Independent ID: 0810ba9a-254a-073a-8a86-a5f750fe9ae4
* Content: [Web development with Python on Windows](https://docs.microsoft.com/en-us/windows/python/web-frameworks)
* Content Source: [hub/python/web-frameworks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/web-frameworks.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for posting this issue @josebrwn. Sorry for my slowness getting to it, but it's on my list to add this to a troubleshooting section of the docs. I'll post an update once it's in.

**Comment by mattwojo** [comment]
Thanks again for this @josebrwn - finally got it added to the FAQ. Your contributions are really appreciated. Closing - resolved with https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1111

**Comment by corneliusroemer** [comment]
I got a similar but slightly different error just now after installing conda. In my case  I got Errno -2 "Name or service not known".
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f81caa39bb0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/qiskit/
```

It was enough to update/upgrade the distribution (WSL Ubuntu).

**Comment by xuancong84** [comment]
I also encounter the same error as @corneliusroemer using WSL2, so pip cannot install anything, totally broken:

```
Requirement already satisfied: pip in /home/ubuntu/miniconda3/lib/python3.9/site-packages (21.2.4)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbd3e3d1dc0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbd3e3d1280>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbd3e3d1610>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbd3e3d1430>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbd3e3d1250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pip/

```

**Comment by PortugalNeto** [comment]
Hey guys, do you have encoutered any solutions for this issue?
@xuancong84 

My problem is when I use wsl and the error is as follow:

Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f767f07bb38>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pip/

**Comment by xuancong84** [comment]
@PortugalNeto Anaconda's `python -m pip install` works while Miniconda's `python -m pip install` does not work. So you can install your package using Anaconda first, then copy over the package folder to Miniconda.
