### ISSUE TITLE
docs: All 'Sample' links for 'Holographic face tracking sample' result in 404

### ISSUE THREAD

**Issue by robertyoung2** [MicrosoftDocs/windows-uwp#2682]
All links under Samples on document page: [Holographic face tracking sample](https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/holographicfacetracking/) result in 404 errors.

The format of the current generated links lead to 404 errors. For example, the sample 'BasicFaceDetection' points to the url: https://docs.microsoft.com/en-us/Samples/BasicFaceDetection.

The correct url on the Microsoft documents page is: https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/basicfacedetection/

This applies to all three links under Samples for:
* BasicFaceDetection
* BasicFaceTracking
* CameraFrames

**Comment by hkhmsft** [comment]
Thanks for pointing this out, @robertyoung2! I went ahead and fixed the links. The PR is pending approval, but once the changes are merged I'll make sure to update this thread. Closing in the meantime. Cheers.

**Comment by hkhmsft** [comment]
Hi @robertyoung2 , I received word from internal team indicating these links are relative to the GitHub navigation experience. If you click on "Browse Code", you'll be taken to GitHub where the links will work. Hope this helps.

![image](https://user-images.githubusercontent.com/55564399/103571229-5fccc300-4e7f-11eb-8c31-866c9cbe13d9.png)

**Comment by robertyoung2** [comment]
That's great, thanks for the info. It was more to make sure the broken links on the Windows documentation were fixed as it seemed odd to click on them and get 404 errors without being brought to the GitHub repos!

I can only assume as I raised this issue 4 months ago it got fixed in between now and then :)

Thanks for your help and feedback!
