### ISSUE TITLE
Missing class definition: XamlMetaDataProvider

### ISSUE THREAD

**Issue by twhall-umich** [MicrosoftDocs/windows-uwp#2683]
The sample code makes references to a XamlMetaDataProvider class (note without a leading I) -- in app.base.h and in app.manifest -- but never defines it.  I presume it should derive from winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62891dc-cad0-0ea2-66c3-a5b58d9e3f9a
* Version Independent ID: 911ab9f0-1c11-b2bf-9ecf-9fbed29df211
* Content: [Host a custom UWP control in a C++ Win32 app using the XAML Hosting API](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. You are correct that the walkthrough code doesn't define the XamlMetaDataProvider struct. Instead, when you build the project, this struct is defined automatically in a generated header file named XamlMetaDataProvider.h. You do not need to define XamlMetaDataProvider directly in your code.

**Comment by twhall-umich** [comment]
Thanks for your reply.  Building in CMake, without the behind-the-scenes magic of a typical Visual Studio project / solution, has been a battle.  The midl, mdmerge, and cppwinrt tools are not well documented for that use case.

I have obtained the NuGet packages for Microsoft.Windows.CppWinRT.2.0.200729.8, Microsoft.UI.Xaml.2.4.3, and Microsoft.Toolkit.Win32.UI.XamlApplication.6.1.2.  I have experimented with the tool command-line options and quirks, "projected" the SDK and my custom classes into C++/WinRT v2, generated the files, compiled and linked without errors.

Now debugging, I'm trying to resolve a REGDB_E_CLASSNOTREGISTERED exception in the construction of Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication .  I've following the advice at https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq#why-am-i-getting-a-class-not-registered-exception and https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#opt-in-to-uniform-construction-and-direct-implementation-access but no joy yet.

**Comment by mcleanbyron** [comment]
It sounds like you have questions about the functionality of the Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication class that goes beyond the scenarios covered in the docs. This repo is intended mainly for reporting and addressing bugs in the docs, not for assistance with technical questions of this nature. If you haven't done so already, I recommend that you post your questions to the [Microsoft.Toolkit.Win32](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32) repo. This is the open source repo where these APIs are developed, and the engineering team that builds these APIs watches over this repo.
