### ISSUE TITLE
"Call Windows Runtime APIs in desktop apps" doc samples still make use of C++/CX, despite advice for C++/WinRT.

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#2686]
Page tells that C++/WinRT is the way to go for C++, yet the examples still make use of C++/CX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Call Windows Runtime APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback, and good catch. I added a C++/WinRT version to the notification code example in this article.
