### ISSUE TITLE
Update documentation on "Detect faces in images or videos"

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2687]
Quote:

> 02/08/2017
>
> [Some information relates to pre-released product which may be substantially modified before it's commercially released. Microsoft makes no warranties, express or implied, with respect to the information provided here.]

Is this product still preliminary?

I propose to finalize this page after three years of Beta state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43011566-eda2-5292-5239-d62782adb6b6
* Version Independent ID: ebf8566a-d12d-3760-e2ef-26048833e95e
* Content: [Detect faces in images or videos - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/detect-and-track-faces-in-an-image)
* Content Source: [windows-apps-src/audio-video-camera/detect-and-track-faces-in-an-image.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/detect-and-track-faces-in-an-image.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The prerelease note has been removed from the page. Thanks for helping to improve the documentation!
