### ISSUE TITLE
Screenshots are out of date

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/windows-uwp#2688]
Screenshots are out of date. Windows 10 20H2 updated toast notifications to be more* inline with the notifications that appear in the action centre (which were changed with Windows 10 1709).

*I say _more_ because they're still not the same lol:
![image](https://user-images.githubusercontent.com/51363864/92299852-8b0ad880-ef99-11ea-8c71-de952b01592b.png)
toast notification is the image of the action centre notification. the app icon and name are not centred in the toast. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a230de61-3424-1cfc-2556-d0ae6c29448b
* Version Independent ID: b30f9eb9-0f2f-178b-3b92-deca4d466588
* Content: [Toast content - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts#sending-a-toast-notification)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Poopooracoocoo** [comment]
@andrewleader sorry for the ping, just thought you might wanna see the bit on the inconsistency :)

**Comment by andrewleader** [comment]
Hey @Poopooracoocoo, are you reporting a bug in the platform about the display of the notifications? Or you're just referring to inconsistency of the docs having an outdated screenshot. Kinda sounded like you were pointing out two issues... if there's a bug/issue in the platform, could you clarify a bit as I'm not fully seeing the issue (usually I'm very good at noticing small things, but I'm sorry I'm not seeing it!)

**Comment by Poopooracoocoo** [comment]
@andrewleader 
I meant on the platform. My screenshot wasn't too clear anyway. 

Toast:
![image](https://user-images.githubusercontent.com/51363864/92541985-e46d5300-f28a-11ea-8d49-225552f29e3c.png)

Banner in action centre:
![image](https://user-images.githubusercontent.com/51363864/92541989-e7684380-f28a-11ea-8ade-f06789604d0e.png)

And I think the arrow icon on the toast was a good idea (as opposed to the close icon). I remember seeing a Windows 10 news site say that the 20H2 builds let you immediately close/dismiss notifications from the toast, but when the update actually came, I realised that is was just a visual change and that the article was wrong.

The app icon and name are not centred in the toast. It's not a bug, just a minor inconsistency. 

And then there's this:
Toast:
![image](https://user-images.githubusercontent.com/51363864/92542398-fbf90b80-f28b-11ea-9061-22b4e00e6559.png)
Banner in action centre:
![image](https://user-images.githubusercontent.com/51363864/92542389-f8658480-f28b-11ea-93c8-d1d2c862a07e.png)

The button that opens a menu to control the notification settings of that app are in different positions and have different icons.

Oh and I hope you guys will finally switch to WinUI 😉

**Comment by duke7553** [comment]
@Poopooracoocoo They'll come back to this issue after 2 more months (when you've forgotten about it) and close it because this is definitely the wrong place to report bugs about the Windows Shell UI. Currently, Microsoft has no place to report bugs with the Shell UI of Windows desktop because they couldn't care less about their 1 billion Windows users, and are focusing on Windows 10X and Azure at the moment (the past three years).

We have no real reason to believe the Feedback Hub is anything more than a joke, so I understand completely why this was filed and look forward to the day when Microsoft becomes more transparent about improving their core experience.

**Comment by duke7553** [comment]
@andrewleader Can you let the Windows Shell team know that the current design is very inconsistent with some apps having rounded corners and Fluent typography while the Shell doesn't?

Also, any updates on the "acceleration of innovation in Windows" which clearly isn't happening?

**Comment by Poopooracoocoo** [comment]
@duke7553 couldn't have agreed more lol. I don't know why I tried. I guess part of me still hopes™
