### ISSUE TITLE
Cannot find app feedback submitted through feedback hub

### ISSUE THREAD

**Issue by jjouppi** [MicrosoftDocs/windows-uwp#2689]
Hello!

I followed these instructions here so that users could launch the feedback hub from within my app. However, I cannot find any feedback for my app despite having submitted multiple tests. It seems there was a feedback report available within the partner center but that was depreciated in April. When my application launches I'm hoping for this feature to serve as bug reporting for my users.

Where can I now find submitted feedback and how can I respond to user issues now that the feedback report is depreciated? I'm not finding anything within the feedback hub and when searching nothing is coming up.

If this is not available what is the best way for users to submit bug reports for UWP applications aside from reviews on the Microsoft store page?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2bdc2e7-dd4e-723d-ed1e-bd9cdcb503ee
* Version Independent ID: 6510f160-a666-0942-8180-e7ba71a3bfe5
* Content: [Launch Feedback Hub from your app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/launch-feedback-hub-from-your-app)
* Content Source: [windows-apps-src/monetize/launch-feedback-hub-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/launch-feedback-hub-from-your-app.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by MatchaMatch** [comment]
Hi! The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) should be able to help with this.

If you do create a thread over at Microsoft Q&A, feel free to share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open conversation for follow-ups.
