### ISSUE TITLE
Add persistence information to FutureAccessList/MostRecentlyUsedList

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2691]
The information on the [FutureAccessList](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions.futureaccesslist) and [MostRecentlyUsedList](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions.mostrecentlyusedlist) properties from all below listed pages doesn't explain whether items added to these lists are persisted by the system after the application closes.

It lacks an answer to the question: "Is an application required to manually persist and restore the tokens returned by [StorageItemAccessList.Add()](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist.add) or is it sufficient to just open a corresponding [StorageFile](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageFile)/[StorageFolder](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageFolder) when the application is relaunched?"

This is particularly true for the `FutureAccessList` property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea426a20-ab2c-38a1-2394-f0c45b7f07a6
* Version Independent ID: da36c626-4a6f-bd65-ca6e-fa2e97aeb7a9
* Content: [Track recently used files and folders - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders)
* Content Source: [windows-apps-src/files/how-to-track-recently-used-files-and-folders.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/how-to-track-recently-used-files-and-folders.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1ef7e7c-2f41-624f-95bb-f6ad569fd83a
* Version Independent ID: 4a619d60-9419-38af-9704-392b83c419d2
* Content: [StorageItemAccessList Class (Windows.Storage.AccessCache) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage.AccessCache/StorageItemAccessList.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.AccessCache/StorageItemAccessList.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e7379a-623f-ad01-9a39-cd417f8fe985
* Version Independent ID: 4b209cc6-7a16-252c-9830-e2effc336c84
* Content: [StorageApplicationPermissions Class (Windows.Storage.AccessCache) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage.AccessCache/StorageApplicationPermissions.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.AccessCache/StorageApplicationPermissions.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
