### ISSUE TITLE
UWP and SQL Server product.Add error

### ISSUE THREAD

**Issue by BigRedCaddy** [MicrosoftDocs/windows-uwp#2692]
Using this code sample, I have an exception for the product.Add.  It is missing the method for this line of code.  What is the proper way to append a record to the Products table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92140a3c-b33d-6aa7-a904-d03c8122fbdf
* Version Independent ID: 90a33ee7-ec4a-2bcc-b776-530a1c3014fd
* Content: [Use a SQL Server database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases)
* Content Source: [windows-apps-src/data-access/sql-server-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sql-server-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
