### ISSUE TITLE
M12 and M21 are swapped in the Diagram

### ISSUE THREAD

**Issue by groovykool** [MicrosoftDocs/windows-uwp#2694]
M12 and M21 are swapped in the Diagram.
Should be
M11 M12  0
M21 M22  0
OX   OY     1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e595edce-cb07-0645-f1d6-1b51d0e6bcc6
* Version Independent ID: b1726951-106b-1e8a-7797-c3f2069a0908
* Content: [Transforms overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/layout/transforms)
* Content Source: [windows-apps-src/design/layout/transforms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/transforms.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@groovykool, thanks for reporting this error. The doc has been corrected.
