### ISSUE TITLE
sharedFonts capability requires approval

### ISSUE THREAD

**Issue by qmatteoq** [MicrosoftDocs/windows-uwp#2697]
The sharedFonts capability requires to complete an approval process, in order for the Store team to validate that there are no conflicts between fonts installed by the app and the OS. As such, before submitting an application which uses the sharedFonts capability, you must contact the Store team through the support to get approval.
It would be useful to add this information in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a7e980-cfd8-6d9c-6cc5-0ca6763fd327
* Version Independent ID: 5f59e641-6576-e10e-99c0-794907285580
* Content: [Modernize existing desktop apps using Desktop Bridge](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-extensions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extensions.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback! I added a note about this to [the article](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#share-fonts-with-other-windows-applications).
