### ISSUE TITLE
App

### ISSUE THREAD

**Issue by kgirmal** [MicrosoftDocs/windows-uwp#2698]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56f2824-b04c-1e07-2de1-2f78f84834d1
* Version Independent ID: b73656a9-ba3d-2411-dfca-031586aad016
* Content: [Choose your app platform](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform)
* Content Source: [hub/apps/desktop/choose-your-platform.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/choose-your-platform.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
