### ISSUE TITLE
MicrosoftDocs guides -which are the goto for information on how to configure our windows 10 devices -

### ISSUE THREAD

**Issue by realwyatt1** [MicrosoftDocs/windows-uwp#2700]
is so poorly written and overly complicated and plain ridiculous it helps no one and it is so fucking outrageous that that is what you geniuses at microsoft have given us plebs as our source for information its so sad and frustrating - can you all provide us with something we CAN UNDERSTAND ON HOW TO USE OUR COMPUTERS THANK YOU FOR NOTHING

**Comment by GrantMeStrength** [comment]
HI -

I'm very sorry to read that our developer docs didn't meet your needs. Could you tell me which topic in particular you are reading, and what you're trying to do? I can try to make sure we do a better job of explaining what you need.

Thanks for taking the time to create this feedback. Every item of feedback is used to make our docs better for the next developer who reads them.


John Kennedy
Senior Content Developer Manager
jken@microsoft.com

**Comment by GrantMeStrength** [comment]
Hi -

If there is something specific you think we could improve, please re-open this issue. In the meantime I will now close it. Thanks,

-john
