### ISSUE TITLE
Documentation references obsolete information

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2702]
The [Connection quality](https://docs.microsoft.com/en-us/windows/uwp/networking/which-networking-technology#connection-quality) hyperlink doesn't point to .NET (UWP) documentation but to some obsolete JavaScript documentation.

Same for [Near field communications](https://docs.microsoft.com/en-us/windows/uwp/networking/which-networking-technology#near-field-communications).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc6fe7fc-701a-54ef-dbaf-eadc7c7d3164
* Version Independent ID: 173b69f0-1cfa-a5bf-6861-11a615247bb9
* Content: [Which networking technology?' - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/which-networking-technology#connection-quality)
* Content Source: [windows-apps-src/networking/which-networking-technology.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/which-networking-technology.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @SetTrend, and thanks for filing this issue.

I've changed both urls so that they link to the XAML variant of the topic (rather than to the JavaScript variant). Note, though, that both those variants *are* UWP topics (they're not .NET topics). But we  link to the XAML one by default, and we weren't doing that here.

Thanks!
Steve

**Comment by SetTrend** [comment]
Thanks, @stevewhims!

Yet, it's not only the other programming language, it also seems an issue to me that the corresponding documentation is outdated. It bears and emphasizes the following warning message, right at the top:

> We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.

Clicking the _Recommended Version_ hyperlink of that warning message leads to nowhere.

So, shouldn't the links rather point to current versions of the product?

**Comment by stevewhims** [comment]
Hi, @SetTrend, yes you're right that those topics are in the archive. But if we don't have anything that was written more recently, that we're updating regularly, then I think it's ok to link to the archive; those topics will still contain valuable info for Windows 10 devs.

Thanks!
Steve
