### ISSUE TITLE
Pane width of NavigationView doesn't match Windows 10 style

### ISSUE THREAD

**Issue by Path2Freedom** [MicrosoftDocs/windows-uwp#2703]
The pane width of NavigationView control is lesser than other Windows 10 apps like Micorosoft News app or even Start screen of Windows 10. 
In addition, even the text and icons appear smaller than other Windows 10 icons.

Someone should provide a workaround. This was not the issue with Hamburger button control provided previously.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69449df-a1ec-70dd-e563-0ad508733c47
* Version Independent ID: dc0e0acb-d92a-a039-5c16-f54a4b71d954
* Content: [Navigation view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, you can adjust the pane width by setting the OpenPaneLength property.

If you'd like to engage with the XAML product team or file a product bug regarding the design of the control, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing. I don't see any doc issue here.

For general questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question.
