### ISSUE TITLE
Update sample that uses std::shared_ptr/make_shared to use winrt::com_ptr/make_self for correct lifetime management

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#2707]
The XAML compiler was fixed to use the correct lifetime control of the XamlMetadataProvider. When `WINRT_NO_MAKE_DETECTION` is used incorrect lifetime management is allowed. The code on this page needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62891dc-cad0-0ea2-66c3-a5b58d9e3f9a
* Version Independent ID: 911ab9f0-1c11-b2bf-9ecf-9fbed29df211
* Content: [Host a custom UWP control in a C++ Win32 app using the XAML Hosting API](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. The app.base.h code in the article has been updated to use winrt::com and winrt::make_self in the following section:

```cpp
    private:
        bool _contentLoaded{ false };
        winrt::com_ptr<XamlMetaDataProvider> _appProvider;
        winrt::com_ptr<XamlMetaDataProvider> AppProvider()
        {
            if (!_appProvider)
            {
                _appProvider = winrt::make_self<XamlMetaDataProvider>();
            }
            return _appProvider;
        }
```
