### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by TheRealBard** [MicrosoftDocs/windows-uwp#2710]
I came here looking for this: or whatever is in the community sample that is in the Store.

https://techcommunity.microsoft.com/t5/microsoft-bluetooth-blog/introducing-bluetoothlehelper/ba-p/278219

Where is it, and exactly, how do you download the project.

**Comment by GrantMeStrength** [comment]
Hi! That blog post is over three years old, and sadly things move around over time.

I did find the helper here: https://docs.microsoft.com/en-us/windows/communitytoolkit/helpers/bluetoothlehelper

The link to the sample code requires that you have the toolkit sample app installed.

The second link in the blog post is still good: https://blogs.windows.com/windowsdeveloper/2017/07/05/announcing-uwp-community-toolkit-1-5/#0l7WLJ4lxo3yX1KU.97

and that contains the bulk of the BlueTooth code. 

I will follow up with the original blog poster (if they are still around) to see if we can update that link.

Thanks for bringing this to our attention!

-john

**Comment by TheRealBard** [comment]
Thanks Grant,
Before you go, see if you can point me in the right direction.  I ran into trouble because the BluetoothLE sample included in the Windows SDK worked for me with a popular device on one PC, but fails others (including a Surface no less).

The sdk sample is a bit of a black box when it uses Gattxxxx methods.  It just returns 'Device Unavailable' with no reason why.

I am looking for an alternative app which can Pair, Connect to a Service, Subscribe, besides the SDK version. Maybe it will have better luck or at least more information about what's going on. That's why I went looking for this code sample.

Thanks
