### ISSUE TITLE
WPF entrypoint calls undefined InitializeComponent method

### ISSUE THREAD

**Issue by LuKePicci** [MicrosoftDocs/windows-uwp#2712]
From the referenced example for hosted UWP custom controls, it is said to override the default XAML entrypoint with this one:
```csharp
public class Program
{
    [System.STAThreadAttribute()]
    public static void Main()
    {
        using (new MyUWPApp.App())
        {
            MyWPFApp.App app = new MyWPFApp.App();
            app.InitializeComponent();   // <- there is no InitializeComponent() for System.Windows.Application
            app.Run();
        }
    }
}
```

Maybe it was intended to call the method on the UWP XamlApplication instanciated in the using statement like this:
```csharp
public class Program
{
    [System.STAThreadAttribute()]
    public static void Main()
    {
        using (var xamlApp = new MyUWPApp.App())
        {
            MyWPFApp.App wpfApp = new MyWPFApp.App();
            xamlApp.InitializeComponent();   // <-calls Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication.InitializeComponent()
            wpfApp.Run();
        }
    }
}
```

The same issue exists in the other [hosted UWP standard controls](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands) as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7ec471-9257-39ba-173b-eb7973f4c360
* Version Independent ID: 3e07d5f0-8b19-2ef4-dc2a-48659f42c12e
* Content: [Host a custom UWP control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by LuKePicci** [comment]
Relates to #2506

**Comment by LuKePicci** [comment]
Ok, I see InitializeComponent is defined in MyWPFApp.App class as an auto-generated method when App.xaml (the WPF one) contains StartupUri="" attribute. The auto-generated Main is also automatically adapted, it contains no calls to InitializeComponent when StartupUri is missing and so that method.

**Comment by mcleanbyron** [comment]
Thanks for your feedback. It sounds like you figured it out - yes, the code is correct, and it is supposed to call the generated InitializeComponent and Run methods of the default MyWPFApp.App class.
