### ISSUE TITLE
Misspelled word "Inlclude"

### ISSUE THREAD

**Issue by AndrewMore1** [MicrosoftDocs/windows-uwp#2714]
Misspelled word "include" in this sentence:  "For example, to use the C++/WinRT projection for the Windows::Foundation::Collections::PropertySet runtime class, inlclude the winrt/Windows.Foundation.Collections.h header."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @AndrewMore1, and thanks for filing this issue. I have a fix to the typo going through the publishing process now. I'll monitor that change, and make sure it goes live. Meanwhile I'll go ahead and close this issue.

Thanks again
Steve
