### ISSUE TITLE
Constructor > winrt::make

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#2718]
This document mentions the use of `winrt::make` to consume a type implemented in the same project, but it should prefer the use of normal constructors, since the use of `winrt::make` in this situation is rendered useless by the addition of [projection optimizations](https://kennykerr.ca/2019/06/07/cppwinrt-optimizing-components/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbed06f8-9ce1-f057-e391-80ab68ccdfc0
* Version Independent ID: 565fb22e-e508-4bfb-84d8-bba71032498d
* Content: [Consume APIs with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis#if-the-api-is-implemented-in-the-consuming-project)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-apis.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @sylveon, and thanks for filing this issue. You're right, the section was missing important info. So, I've published an update to that section showing how to do uniform construction, as well. I think that it's useful to know both techniques.

Thanks again!
Steve
