### ISSUE TITLE
Grammar error: "it's" vs. "its"

### ISSUE THREAD

**Issue by ralph-snart** [MicrosoftDocs/windows-uwp#2723]
On this page, you have a number of instances of "it's own".  However, that should be "its own", as you are not saying "it is own".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b92f5-7f7f-cc94-64b9-69462979fe0f
* Version Independent ID: 5096d0ec-24fc-23ae-b2ec-aa21acf273d5
* Content: [Web development with Python on Windows](https://docs.microsoft.com/en-us/windows/python/web-frameworks)
* Content Source: [hub/python/web-frameworks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/web-frameworks.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Good catch. Thanks Ralph.
