### ISSUE TITLE
Windows Community Toolkit Icon Incorrect

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2727]
I don't know where docs.microsoft.com received this toolkit image, it's not our official logo.

Ours is this toolbox as seen in our social preview image here:

![Social Preview](https://raw.githubusercontent.com/windows-toolkit/WindowsCommunityToolkit-design-assets/master/Logos/GitHubSocialPreview.png)

We'd like to know where this image design came from though?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Design toolkits and samples for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@hickeys, @chigy - can you help with this?

**Comment by Kyaa-dost** [comment]
@hickeys @chigy  please let us know once you have an update on this.

**Comment by chigy** [comment]
@michael-hawker ,
What are you looking for us to do? Do you want us to replace the image and if so, please provide the image to replace with?

**Comment by michael-hawker** [comment]
@chigy we have an SVG that can be used from our design assets here: https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets/blob/master/Logos/ToolkitIcon.svg

I also just wanted to follow-up on the scenario of how it came to be generated as part of the process for this page. At the time it seems like it was just done to try and align the style between the three things, though WinUI has a new icon now as well as seen from https://aka.ms/winui. It's just a mystery, as it keeps getting taken to be the Toolkit icon when folks are searching...

I'm happy to submit a PR and try and update this page as some of the descriptions could be improved as well. Also happy to add a link to our Sample App for the Toolkit as well to complement the XAML Controls Gallery.

**Comment by chigy** [comment]
@michael-hawker ,
I do not have any issues with the icon being updated with the official one as well as you submitting PR. @hickeys , thoughts?

These icons might have been created by design to align but don't have specific knowledge where they came from.

**Comment by GrantMeStrength** [comment]
I have updated the image with the correct logo. Should be live very soon.
