### ISSUE TITLE
ElementCompositionPreview.GetScrollViewerManipulationPropertySet typo

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/windows-uwp#2734]
[Enter feedback here]
Typo:
`ElementCompositionPreview.GetScrollManipulationPropertySet(ScrollViewer scroller)`

should be

`ElementCompositionPreview.GetScrollViewerManipulationPropertySet(ScrollViewer scroller)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42309e21-798a-7a98-f7d1-2c5f999ceeef
* Version Independent ID: b7bb8a7a-155f-37f7-938a-ce47cb35668d
* Content: [Enhance existing ScrollViewer experiences - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/scroll-input-animations)
* Content Source: [windows-apps-src/composition/scroll-input-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/scroll-input-animations.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for noticing this. I've submitted a correction the the doc.
