### ISSUE TITLE
ExpressionBuilder.ExpressionFunctions is in different namespace

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/windows-uwp#2736]
There is a note explaining what the EF shorthand is for

> EF is a shorthand “using” notation to define ExpressionBuilder.ExpressionFunctions.

It seems that at some point in time this changed to `Microsoft.Toolkit.Uwp.UI.Animations.Expressions.ExpressionFunctions`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859dcabb-2805-6fd7-2816-22eb0f8e8a48
* Version Independent ID: 569050ed-7e91-680a-6992-0e4cf7145dd5
* Content: [Relation based animations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/composition/relation-animations)
* Content Source: [windows-apps-src/composition/relation-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/relation-animations.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. I've submitted a doc update to reference the Toolkit version of ExpressionBuilder instead of the stand-alone version.

**Comment by wldevries** [comment]
Am I supposed to close this ticket?
