### ISSUE TITLE
Please add examples with C++/WinRT. Only C# examples are available

### ISSUE THREAD

**Issue by arrudi** [MicrosoftDocs/windows-uwp#2737]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01ed7d6-f106-570e-48b4-173d5ad1dfe9
* Version Independent ID: 898104f4-382a-60ef-90af-f9304e89640e
* Content: [Enumerate devices - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enumerate-devices)
* Content Source: [windows-apps-src/devices-sensors/enumerate-devices.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/enumerate-devices.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @arrudi - thanks for the feedback. This is an ongoing effort and these docs will be prioritized when possible.
