### ISSUE TITLE
Creating Scheduled Toast Notifications

### ISSUE THREAD

**Issue by derrickberg-dev** [MicrosoftDocs/windows-uwp#2739]
If the first toast notification that you attempt to create, is created using a Scheduled Toast, it doesn't work. It will only work after you have created a toast notification that displays immediately, CreateToastNotifier().show(). 

Either this is a bug, or it should be mentioned in the documentation because I wasted quite a bit of time trying to figure out why my app wouldn't launch a scheduled toast on other machines but it would on mine. That was because while building the app, I had created notifications that displayed immediately and therefor my app had been properly registered.

For example, this will not work when creating a scheduled toast notification on Windows 10.
```
public void ShowNotification()
        {
            string xml = $@"<toast scenario='reminder'>
                      <visual>
                        <binding template='ToastGeneric'>
                          <text>hello</text>
                        </binding>
                      </visual>
                    </toast>";

            XmlDocument doc = new XmlDocument();
            doc.LoadXml(xml);
            try
            {
                var toast = new ScheduledToastNotification(doc, DateTime.Now.AddSeconds(5));
                DesktopNotificationManagerCompat.CreateToastNotifier().AddToSchedule(toast);
            }
            catch(Exception ex)
            {
                MessageBox.Show("Toast Error..." + ex.Message);
            }

        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d21520-412a-6dde-9991-8e52e2791913
* Version Independent ID: 92953a04-13e4-0b65-5331-8adb0fa85d2a
* Content: [Schedule a toast notification - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/scheduled-toast)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/scheduled-toast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/scheduled-toast.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
