### ISSUE TITLE
URLs to download .Net Preview 5 point to a server that is way to slow

### ISSUE THREAD

**Issue by Rand-Random** [MicrosoftDocs/windows-uwp#2740]
Downloading from the EU.
The produced URLs
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.5.20279.10/dotnet-sdk-5.0.100-preview.5.20279.10-win-x86.exe
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.5.20279.10/dotnet-sdk-5.0.100-preview.5.20279.10-win-x64.exe

Give a way slower download speed, currently it saying it needs 7-10 hours to complete the download,  as the URLs you can find here:
https://dotnet.microsoft.com/download/dotnet/5.0

https://download.visualstudio.microsoft.com/download/pr/6163690f-c627-4063-9229-fed74d955402/e33f89f431867b98e1a74297fe73cc7f/dotnet-sdk-5.0.100-preview.5.20279.10-win-x86.exe
https://download.visualstudio.microsoft.com/download/pr/38c82743-6223-4a51-a424-ac79a4db189b/5c88aa3116df3b81564077fe49a83c7f/dotnet-sdk-5.0.100-preview.5.20279.10-win-x64.exe

Those download in mere seconds and not hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3 Preview 2 (July 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I updated the .NET 5 Preview 5 download links to match the ones on the [https://dotnet.microsoft.com/download/dotnet/5.0](https://dotnet.microsoft.com/download/dotnet/5.0) page.
