### ISSUE TITLE
"C++/WinRT Visual Studio Extension (VSIX)" is deprecated in Visual Studio 2019, but still recommended in doc page

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [MicrosoftDocs/windows-uwp#2741]
On that doc page it says:

> For new projects, you can install the [C++/WinRT Visual Studio Extension (VSIX)](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264) and use one of the C++/WinRT project templates included in that extension.

But if we head to the VSIX package we would find that it recommends using ["Microsoft.Windows.CppWinRT"](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/) NuGet package for Visual Studio 2019!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Call Windows Runtime APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#modify-a-c-win32-project-to-use-windows-runtime-apis)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you. for your feedback. When you say that the VSIX package page "recommends using "Microsoft.Windows.CppWinRT" NuGet package for Visual Studio 2019", are you referring to the following text?

"With Visual Studio 2019, MSBuild support is no longer built into the C++/WinRT VSIX, but is provided by the standalone Microsoft.Windows.CppWinRT NuGet package instead."

I don't believe this text is saying that the VSIX is deprecated; instead, it's saying specifically that the MSBuild support for building a project that uses C++/WinRT is now in the NuGet package. I believe the VSIX itself is still required if you want to use one of the  C++/WinRT project templates. There are effectively two pathways to using C++/WinRT in Visual Studio:

-  Install the VSIX, and then create one of the C++/WinRT project templates provided by the VSIX. When you create one of these project templates, the Microsoft.Windows.CppWinRT NuGet package is automatically installed in the project, and this package provides the runtime libraries, MSBuild support, and other components. For more info about the VSIX, see [this article](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package).
- In an existing C++ Windows desktop project, you can install the Microsoft.Windows.CppWinRT NuGet package directly. For more details about this scenario, see [this article](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started#modify-a-windows-desktop-application-project-to-add-cwinrt-support),

If I have misunderstood your question, please feel free to reopen this issue with more details.
