### ISSUE TITLE
Update step 7 instructions

### ISSUE THREAD

**Issue by eavonius** [MicrosoftDocs/windows-uwp#2743]
I believe you meant #7 to be `nvm install node -lts`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2?source=docs)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @eavonius. No, the current command is correct: `nvm install node --lts`

See the NVM repo: https://github.com/nvm-sh/nvm#long-term-support

**Comment by eavonius** [comment]
Ah so you fixed it then. It said `nvm install --lts` (missing node) last night.

Glad you got it sorted.

**Comment by eavonius** [comment]
Actually I checked - it still says `nvm install --lts`

**Comment by mattwojo** [comment]
Oh no! LoL. I was totally fixated on the single vs double dash on the lts flag... now I see that you're pointing out that it's entirely missing the word "node" in the command... DOH!  Thanks @eavonius!! Fixing now.

**Comment by mattwojo** [comment]
Just filed a PR with the fix: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1076
Thanks again @eavonius!! Especially for the follow up... can't believe I just totally didn't see this.

**Comment by eavonius** [comment]
No problem, thanks for writing all this documentation :)
