### ISSUE TITLE
Cannot set `identifierUris` as documented

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/windows-uwp#2744]
I can still request tokens, but configuring the application manifest as documented is failing.

### Within the portal:
![image](https://user-images.githubusercontent.com/3036550/95377188-13c9ac80-0897-11eb-8315-6985b5e193c6.png)

### Using the Azure CLI:
```powershell
PS> az ad app update --id '<redacted-id>' --identifier-uris 'https://onestore.microsoft.com'  --verbose --debug
...
msrest.http_logger : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Application alias
'https://onestore.microsoft.com/b2b/keys/create/collections' value is invalid."},"requestId":"52909bed-5699-40c7-b308-
b797b3b770ee","date":"2020-10-07T19:12:50","values":[{"item":"PropertyName","value":"identifierUris"},
{"item":"PropertyErrorCode","value":"IdentifierUriValueIsReserved"}]}}
msrest.exceptions : Application alias 'https://onestore.microsoft.com/b2b/keys/create/collections' value is invalid.
...
```

I can include more of the output, but it looks like it would have credential tokens that shouldn't be shared. It appears the important part is `IdentifierUriValueIsReserved`. Does that mean these URIs don't need to be set anymore, and documentation should be corrected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by adamhewitt627** [comment]
Correction, I can only request keys with `resource = 'https://onestore.microsoft.com'`. With `https://onestore.microsoft.com/b2b/keys/create/collections` and `https://onestore.microsoft.com/b2b/keys/create/purchase`, the token request fails.
```json
{
    "error": "invalid_resource",
    "error_description": "AADSTS500011: The resource principal named https://onestore.microsoft.com/b2b/keys/create/collections was not found in the tenant named <redacted>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: a2acdc97-c557-492d-9e05-20b769286801\r\nCorrelation ID: 887e0f92-6c8a-4d2d-8c0a-7aa5cf2981cc\r\nTimestamp: 2020-10-07 19:25:37Z",
    "error_codes": [
        500011
    ],
    "timestamp": "2020-10-07 19:25:37Z",
    "trace_id": "a2acdc97-c557-492d-9e05-20b769286801",
    "correlation_id": "887e0f92-6c8a-4d2d-8c0a-7aa5cf2981cc",
    "error_uri": "https://login.microsoftonline.com/error?code=500011"
}
```

Although there does look to be some helpful information there. I will investigate the authentication issues it mentions.

**Comment by DmitriiKh** [comment]
I am getting this error as well. It says "Failed to update PdfOnlineConvertorServiceAD application. Error detail: Application alias 'url' value is invalid. [95Rhd74KVtnJBw7SyhbTCP]"

**Comment by DmitriiKh** [comment]
This problem is holding back our development for four weeks now. We would appreciate it if someone could fix the issue.

**Comment by adamhewitt627** [comment]
To be clear on my end, this used to be possible and I had an application set up with it. This failed when we moved to a new tenant.

**Comment by combinatorial** [comment]
I think this is related to: https://github.com/MicrosoftDocs/windows-uwp/issues/1717

**Comment by adamhewitt627** [comment]
Yes, that is exactly what I was experiencing, and I'm glad to hear reports it's been resolved. I am no longer with the company that I needed this for, so I can't personally confirm. Given the reports there and this being a duplicate, I'm closing this.
