### ISSUE TITLE
Tap1

### ISSUE THREAD

**Issue by iggi88** [MicrosoftDocs/windows-uwp#2748]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c07ba9-8f4f-c051-c945-16742c7fe409
* Version Independent ID: 61c4da19-8278-4764-05a4-000653932b83
* Content: [Provision Device Portal with a custom SSL certificate - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-ssl)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-ssl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-ssl.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by iggi88** [comment]
=)

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
