### ISSUE TITLE
Links under 'Examples' not clickable + layout issue

### ISSUE THREAD

**Issue by PieEatingNinjas** [MicrosoftDocs/windows-uwp#275]
I noticed that some links are not clickable and that there is an issue with the layout (I think the two things might be related). 
If you go for example to the [Command Bar](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars) page and scroll to 'Examples', the links 'Get _the XAML Controls Gallery app (Microsoft Store)_' and '_Get the source code (GitHub)_' aren't clickable. Also the link '_open the app and see the CommandBar in action_' is not clickable from time to time. 

On the [Buttons](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons) page I see the exact same behavior. 

However, on the [Checkbox](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/checkbox) page all links in the Examples section are clickable, although I don't see any differences (at first sight) in de md files.

I've seen this on different PCs on Edge (Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393), in Chrome (63.0.3239.108) and IE 11.

When I look closer, I might think this is related to the alignment of the first element under the 'Examples' _table_  :
![alt text](https://blog.pieeatingninjas.be/wp-content/uploads/2017/12/Screenshot1.jpg)
![alt text](https://blog.pieeatingninjas.be/wp-content/uploads/2017/12/Screenshot2.png)
On these screenshots, you can clearly see that the alignment is a bit off for the first element(s) under the 'Examples'. And it seems to me that every time there is an image underneath it, that the links above it aren't clickable.

**Comment by ginami** [comment]
Thank you @PieEatingNinjas for this helpful feedback!

@serenaz, can you follow up on this issue?

**Comment by serenaz** [comment]
Thanks for pointing out the issue! It should be fixed now.
