### ISSUE TITLE
Can we get a sample uwp app for this doc page on XAML property animations?

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/windows-uwp#2756]
[Enter feedback here]
Can we get a sample uwp app for this doc page on XAML property animations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db3fa053-4f42-e3ad-575c-52c6620d5f57
* Version Independent ID: c4335958-d82c-5bbe-4490-8d220a05a77a
* Content: [XAML property animations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/motion/xaml-property-animations)
* Content Source: [windows-apps-src/design/motion/xaml-property-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/xaml-property-animations.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@dpaulino, the Examples section of the page has both [Microsoft Store](https://www.microsoft.com/store/productId/9MSVH128X2ZT) and [GitHub](https://github.com/Microsoft/Xaml-Controls-Gallery) links for the XAML Controls Gallery app, which has a page for Animation interop with animation examples related to this doc page.

If these examples don't meet your needs, consider opening an issue on the XAML Controls Gallery GitHub repo to request a new sample.

**Comment by dpaulino** [comment]
Ah, I didn't notice the links to the xaml controls gallery app. Thanks.
