### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by mneitzke** [MicrosoftDocs/windows-uwp#2757]
When I get to part 3 step two, I get the exception
System.ArgumentException: 'An item with the same key has already been added. Key: Telerik.UI.Xaml.Controls.Grid.RadDataGrid'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4973ee6-8a33-75d3-f942-129628377fdb
* Version Independent ID: 0c933c8f-6dbb-cb14-fce3-9ca724b18d82
* Content: [Create a customer database application - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/enterprise/customer-database-tutorial)
* Content Source: [windows-apps-src/enterprise/customer-database-tutorial.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/enterprise/customer-database-tutorial.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback. May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If this ends up being something regarding the documentation, let us know.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by BrianBalke** [comment]
I used NuGet to uninstall the Telerik.UI.for.UniversalWindowsPlatform package and then re-installed it.

**Comment by Dour420** [comment]
What’s that do

Sent from my iPhone

On Apr 7, 2021, at 3:41 PM, BrianBalke ***@***.***> wrote:

﻿

I used NuGet to uninstall the Telerik.UI.for.UniversalWindowsPlatform package and then re-installed it.

**Comment by BrianBalke** [comment]
I would infer that there were multiple references to the Telerik namespace, one coming from Visual Studio and the other from the GitHub project, which is not necessarily up-to-date. If so, uninstalling and reinstalling would bring the project reference up-to-date.

I do note that upon first build a number of older .NET assemblies were downloaded, which is a little irritating, but tends to confirm this theory.
