### ISSUE TITLE
Typo in `winget source remove` section

### ISSUE THREAD

**Issue by shamilsan** [MicrosoftDocs/windows-uwp#2758]
Now: 

> Usage: `winget source add [-n, --name] \<name>`

Should be:

> Usage: `winget source remove [-n, --name] \<name>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5a5e2ab-44a7-a652-d3d4-c7e0bfa246ab
* Version Independent ID: bdbeae08-947d-2413-3053-ca66f0a9d90e
* Content: [source Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/source)
* Content Source: [hub/package-manager/winget/source.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/source.md)
* Product: **dev-environment**
* Technology: ****
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mcleanbyron** [comment]
Thanks for reporting this to us. I have fixed this typo.
