### ISSUE TITLE
System.TypeInitializationException: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.'

### ISSUE THREAD

**Issue by mneitzke** [MicrosoftDocs/windows-uwp#2759]
I get an error upon running this.

System.TypeInitializationException: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.'
EntryPointNotFoundException: Unable to find an entry point named 'sqlite3_win32_set_directory8' in DLL 'winsqlite3'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
