### ISSUE TITLE
Sqlite DataAccessLibrary - Embedded prevents using

### ISSUE THREAD

**Issue by kmcbarne** [MicrosoftDocs/windows-uwp#2760]
I've tried to follow the directions for the Sqlite tutorial several different times, and always get the same resulting error.  One of the purple note boxes on the page says to mark the DataAccessLibrary (DAL) as Embedded and Copy Always, but when I do, it then makes it so that I can't access\use the DAL from the UWP application.  It gives the error "The type or namespace name 'DataAccessLibrary' could not be found (are you missing a using directive or an assembly reference?)".  I can get rid of this error by switching it back from Embedded to C# Compiler, but then I get this error:  "'IAsyncOperation<StorageFile>' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'IAsyncOperation<StorageFile>' could be found (are you missing a using directive for 'System'?)".  using System is at the top of the code document, and adding using System.Threading (which should contain the GetAwaiter definiton) doesn't fix it either.  One way or another, there is always an error.

Is there a way to resolve these issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#set-up-your-solution-to-use-the-microsoftdatasqlite-library)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
