### ISSUE TITLE
Where is the BarcodeScannerInfo class?

### ISSUE THREAD

**Issue by mneitzke** [MicrosoftDocs/windows-uwp#2765]
Not sure what the BarcodeScannerInfo class that is referenced here contains.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72178625-3c29-9fa2-b23c-3cb3402d95cc
* Version Independent ID: 55d709c4-13b4-db4f-ecbb-e7f4562051ba
* Content: [Getting Started with Camera Barcode Scanner - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-camerabarcode-get-started)
* Content Source: [windows-apps-src/devices-sensors/pos-camerabarcode-get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/pos-camerabarcode-get-started.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @mneitzke - thanks for letting us know about this doc error. There is no such object and the code snippet was incorrect. I've updated the topic and added numerous links to relevant API topics.
