### ISSUE TITLE
Please elaborate on irritating statement "the JIT will fail"

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2766]
On the below mentioned page, below the example, it reads:

> The reason the call to `CoreApplication.EnablePrelaunch()` is factored out into this function is because when a method is called, the JIT (just in time compilation) will attempt to compile the entire method. If your app is running on a version of Windows 10 that doesn't support `CoreApplication.EnablePrelaunch()`, then the JIT will fail.

Please elaborate on the following issues:

1. Why is "JIT compilation" involved here? UWP code is compiled and packaged before it is deployed.
1. What exactly happens when "the JIT" fails?
1. Why does "the JIT" fail only with `CoreApplication.EnablePrelaunch()` when `CoreApplication.EnablePrelaunch()` is not extracted to a separate method? Why doesn't it fail for any other version dependant WinRT function when such WinRT call appears somewhere in code, not being extracted to a separate method (which I'd suspect to be coding hell then anyway)? 

I raised a [question at StackOverflow](https://stackoverflow.com/questions/64344156/why-is-this-winrt-function-required-to-be-extracted-while-others-are-not/64348318), but the answers there couldn't shed light on this description yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b28257b-4928-0d9c-b291-1e3a0531fc08
* Version Independent ID: 31a240eb-93ab-f7f1-2f32-3d5f5f995bab
* Content: [Handle app prelaunch - UWP applications - Detect and handle prelaunch](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-app-prelaunch#detect-and-handle-prelaunch)
* Content Source: [windows-apps-src/launch-resume/handle-app-prelaunch.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/handle-app-prelaunch.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Hi, @SetTrend, and apologies for the very long delay in responding to this issue.

Yes, with .NET Native being used for UWP apps, you're right that JIT is not involved here. I've published corrections to the topic in that regard.

Many thanks!
-Steve
