### ISSUE TITLE
Remove references to pre-release

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/windows-uwp#2767]
The documentation instructs people to "In the NuGet Package Manager window, make sure that Include prerelease is selected."

This is not needed anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7ec471-9257-39ba-173b-eb7973f4c360
* Version Independent ID: 3e07d5f0-8b19-2ef4-dc2a-48659f42c12e
* Content: [Host a custom WinRT XAML control in a WPF app using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. I have removed this from the instructions.
