### ISSUE TITLE
Tables faultily rendered at "Move and draw commands syntax"

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2775]
The tables in the "Elliptical arc command" explanation chapter are rendered faulty:

![Current](https://user-images.githubusercontent.com/9283914/97124078-f7e75700-172e-11eb-8f01-f4b4b5f58dca.png)

1. The description of the `a` draw command option is missing white-space.
1. The Term table isn't rendered as a table.
1. The subsequent "Close command" header isn't rendered as a heading.

While all of this is rendered correctly on GitHub, the Microsoft Docs parser seems to have difficulty recognizing the table.

I believe issues 2-3 exist because the final pipe character in the table isn't preceded by a white-space character.

For issue 1, the author simply forgot to type the white-spaces.

I suggest to apply the following changes to the corresponding Markdown file:

![Difference](https://user-images.githubusercontent.com/9283914/97124303-d89cf980-172f-11eb-966f-640c6f16ed73.png)

```md
| Syntax |
|--------|
| `A` *size* *rotationAngle* *isLargeArcFlag* *sweepDirectionFlag* *endPoint* <br/> - or - <br/>
  `a` *size* *rotationAngle* *isLargeArcFlag* *sweepDirectionFlag* *endPoint* |

| Term | Description |
|------|-------------|
| *size* | [**Size**](/uwp/api/Windows.Foundation.Size)<br/>The x-radius and y-radius of the arc. |
| *rotationAngle* | [**Double**](/dotnet/api/system.double) <br/> The rotation of the ellipse, in degrees. |
| *isLargeArcFlag* | Set to 1 if the angle of the arc should be 180 degrees or greater; otherwise, set to 0. |
| *sweepDirectionFlag* | Set to 1 if the arc is drawn in a positive-angle direction; otherwise, set to 0. |
| *endPoint* | [**Point**](/uwp/api/Windows.Foundation.Point) <br/> The point to which the arc is drawn. |

**Close command**
```
<br/>

PS: I've seen this issue in other UPW doc pages before. Perhaps it makes sense to have a Find In Files search performed on the resulting build artefacts using this search term: `"|--"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176ffc17-d205-bfd5-e2fe-4bf483bf293b
* Version Independent ID: 0679a6f6-aa43-2217-3aa4-e95375b78d8f
* Content: [Move and draw commands syntax - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/move-draw-commands-syntax)
* Content Source: [windows-apps-src/xaml-platform/move-draw-commands-syntax.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/move-draw-commands-syntax.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The doc is fixed now.
