### ISSUE TITLE
Wrong information about C++/CX

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/windows-uwp#2792]
This page mentions managed C++ and there's nothing called managed C++ for UWP and C++/CX is not managed. Also, C++/WinRT specific information could be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95021810-7343-a4d1-0830-4704290195b3
* Version Independent ID: 2b1f6eef-4879-475b-c8fd-fa6e01670d1e
* Content: [HttpClient - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/httpclient)
* Content Source: [windows-apps-src/networking/httpclient.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/httpclient.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Jaiganeshkumaran, and thanks for filing this issue. I have a correction in progress, so I'll leave this open until that's live.

I'm adding info about C++/WinRT, as you suggest, correcting the term "managed C++" to "C++/CX", and mentioning that C++/WinRT supersedes C++/CX these days.

Thanks!
Steve

**Comment by stevewhims** [comment]
Just FYI, the fix is now live.
