### ISSUE TITLE
Uwp?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2793]
[Enter feedback here]

On the desktop tutorial, I select desktop app but am prompted for a uwp version to target, why? I do not want to target uwp just a plain old desktop app that  does not have the restrictions that a Uwp app does 

Will all apps that use winui3 need to be defined as UWP apps?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6a5c75-6cdc-a97f-df50-938ac5534e28
* Version Independent ID: e7195fca-7687-4296-6aa8-638ce198d549
* Content: [Get started with WinUI 3 for desktop apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop)
* Content Source: [hub/apps/winui/winui3/get-started-winui3-for-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/get-started-winui3-for-desktop.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for sharing your feedback with us. I'm following up with the engineers who own this experience, and will respond as soon as I can.

**Comment by mcleanbyron** [comment]
In the context of C#/.NET or C++/Win32 desktop project templates for WinUI 3, the purpose of this dialog is to indicate the min/max versions of the OS that your app is compatible with. This information must be specified for any packaged desktop application, not just desktop apps for WinUI 3. 

The project dialog you're referring to unfortunately currently borrows the same UI as the existing related dialog that is used for UWP projects and [Windows Application Packaging](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net) projects. This does not mean that you're creating a UWP app - instead, you are creating a .NET or native C++/Win32 app that runs in an MSIX package. The product team knows this is confusing in the current preview, and may try to improve this experience in a later preview. 

I hope this helps.
