### ISSUE TITLE
windows 2019 ?

### ISSUE THREAD

**Issue by kishorpise** [MicrosoftDocs/windows-uwp#2794]
How to apply on windows 2019 server ?

Same user interface, but it does not work.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb82418-b583-7023-f2e3-c3dca7d3245c
* Version Independent ID: 0a65ac0a-9884-52a8-6485-c2825b1fb4d9
* Content: [Enable your device for development](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development?OCID=WinClient_Ver1703_Settings_DevMode)
* Content Source: [hub/apps/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
HI - I'm sorry, this doesn't appear to be a documentation issue. Please either re-open the issue with more information so I can help, or visit the Microsoft Q&A Forum which is a great place to ask questions. https://docs.microsoft.com/en-us/answers/products/
thanks, -john
