### ISSUE TITLE
Apply accent color in custom title bar according to Windows settings

### ISSUE THREAD

**Issue by pi-dev-nr** [MicrosoftDocs/windows-uwp#2795]
Good morning,

I would like to ask you, how to implement an event to this custom title bar, when the user check/uncheck the option 'Show accent color on the following surfaces: Title bars and windows border' in the Windows Settings -> Personalize -> Colors.
When this option is checked, the accent color is shown only in system buttons like minimize, maximize, but custom title bar follow only dark/light theme.

Thank you

**Comment by hkhmsft** [comment]
closing due to duplicate https://github.com/MicrosoftDocs/windows-uwp/issues/2796
