### ISSUE TITLE
PlayReady EME don't trigger renewal license request when license expired

### ISSUE THREAD

**Issue by sigmadrm** [MicrosoftDocs/windows-uwp#2799]
Hi brother,
Currently, I am implementing Playready License server. But i get a issue about EME does not trigger request license event when license expired. It is only pause video player.
I check MediaKeySession, and i see that field expiration not set in session.
Please help me resolve it.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab8e8fc-b846-6075-41b0-f44c990b1002
* Version Independent ID: 5f6dfdd9-ff24-7f11-240a-174dff73bd96
* Content: [PlayReady Encrypted Media Extension - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/playready-encrypted-media-extension#feedback)
* Content Source: [windows-apps-src/audio-video-camera/playready-encrypted-media-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/playready-encrypted-media-extension.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
