### ISSUE TITLE
Uwp?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2801]
[Enter feedback here]
Why is UWP workload a requirement for visual studio? Ithought wi ui3 was breaking away from the UWP requirement 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3 Preview 2 (July 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @johntheisen9 - Both WinUI and this topic have seen significant updates since you reported this issue. Because of this, I'm going to close this issue. 

Please open a new issue if you find that this topic doesn't provide the details you need or it contains info you feel needs clarifying.
