### ISSUE TITLE
Keyboard accessibility discrepancy

### ISSUE THREAD

**Issue by davidbritch** [MicrosoftDocs/windows-uwp#2804]
See https://github.com/MicrosoftDocs/xamarin-docs/issues/3127

The **TL;DR** is that https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.tabindex?view=winrt-19041 says the default value of `Control.TabIndex` is `int.MaxValue`, while https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/keyboard-accessibility says that "UI elements with TabIndex equal to 0 are added to the tab order based on declaration order in XAML or child collections."

@johnshardman indicates in https://github.com/MicrosoftDocs/xamarin-docs/issues/3127 that UI elements with TabIndex equal to int.MaxValue are added to the tab order based on declaration order in XAML.

**Comment by Karl-Bridge-Microsoft** [comment]
Topic was updated a few months ago with additional detail re. this issue.

Closing this issue, but please open a new one if the update is not satisfactory.
