### ISSUE TITLE
Reports data range is very limited

### ISSUE THREAD

**Issue by jignesh-fandco** [MicrosoftDocs/windows-uwp#2806]
Its very disappointing that report dates for store reports like "Reviews" and others has a very limited date range (30 days max).  What if we want to see a complete list of feedback from the start ?
This needs to be changed and complete report from day 1 should be made available or older then 30 days review reports should be archived and made available for download.

Regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66ea6ad-8d3b-5388-a4c6-9911970ca591
* Version Independent ID: 39419d19-1f49-c232-89c6-491edd3f0e8c
* Content: [Download analytics reports - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/download-analytic-reports)
* Content Source: [windows-apps-src/publish/download-analytic-reports.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/download-analytic-reports.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. I don't have any additional content for your scenario, over and above what's in the documentation. So it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback.
