### ISSUE TITLE
Video link leads to nowhere

### ISSUE THREAD

**Issue by karann-msft** [MicrosoftDocs/windows-uwp#281]
On [this doc](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/update-a-live-tile-from-a-background-task), the user expects a how-to video, instead sees a lot of white space. The link in the iframe is broken.

**Comment by ginami** [comment]
Yikes! Thanks @karann-msft for letting us know. We'll get this taken care of ASAP!

**Comment by TylerMSFT** [comment]
Thank you.  The fix should be live tomorrow (1/12/2018).
