### ISSUE TITLE
Start coding / "get set up" link broken

### ISSUE THREAD

**Issue by matth1j** [MicrosoftDocs/windows-uwp#2810]
Not a good start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 833143df-a76a-b714-956b-dab2be749ffa
* Version Independent ID: 39ca0eed-5f1d-1870-59cf-0460d40e8f7a
* Content: [Create apps with the Universal Windows Platform - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-uwp-apps)
* Content Source: [windows-apps-src/get-started/create-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-uwp-apps.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for bringing this to my attention. The broken links have been fixed.
