### ISSUE TITLE
Why Acrylic can't apply on inactive app window

### ISSUE THREAD

**Issue by wenyizou** [MicrosoftDocs/windows-uwp#2812]
Can anyone explain the reason why Acrylic effect can't apply on inactive app window? From design or OS limitation perspective?
It will be nice to see Acrylic effect remains on inactive app window, especially under multi monitor scenario.

**Comment by mdtauk** [comment]
It's currently a design decision made to balance performance.  I personally think this decision should be reconsidered, Apple's use of Vibrancy materials in Big Sur should make it clear there is an expectation of translucency being ever present in the UI.  And maybe an option to only use Acrylic for active windows could be added if users wish.

The Windows Terminal repo is having to deal with people confused about Acrylic behaviour, and wanting it to be always on as well as non blurred transparency.

**Comment by wenyizou** [comment]
That's what I am thinking as well. Windows terminal turns black when out of active is just not... pleasant. 
Do we know how we can do something like a poll to see how many of us want this feature, and submit our request to Microsoft OS team?

**Comment by mdtauk** [comment]
> That's what I am thinking as well. Windows terminal turns black when out of active is just not... pleasant.
> Do we know how we can do something like a poll to see how many of us want this feature, and submit our request to Microsoft OS team?

I don't think the OS design team are present on GitHub, but people like @chigy @YuliKl @anawishnoff would be the ones who could pass on the requests.

There is a supposed design refresh going on, code named **Sun Valley** so maybe (hopefully) the rules on Acrylic will change.  If macOS Big Sur can use it's Vibrancy material consistently without Active and Inactive changes - No reason Windows can't.  Especially on a decent Desktop PC with discreet graphics and AC power

**Comment by chigy** [comment]
Acrylic provides attention to user, so it was a design decision to turn it off when we do not want to attract user's attention.
We are constantly evolving our design and we will keep your suggestion/proposal in mind.

**Comment by wenyizou** [comment]
Thanks for all the replies and help ;). Wish some coming next OS release can have the evolving design.

**Comment by chigy** [comment]
Closing the issue as we concluded the discussion.
