### ISSUE TITLE
OnSuspension should be OnSuspending

### ISSUE THREAD

**Issue by fmccown** [MicrosoftDocs/windows-uwp#2816]
[Enter feedback here]
The text "OnSuspension event handler" should read "OnSuspending event handler" since OnSuspending is what the default App.xaml.cs file calls it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c975971b-da48-9959-c006-6184817cb944
* Version Independent ID: d9cdd29d-6a5f-278d-53d9-7e02278fe5af
* Content: [Windows 10 UWP App lifecycle - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle)
* Content Source: [windows-apps-src/launch-resume/app-lifecycle.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/app-lifecycle.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for pointing this out, @fmccown . I went ahead and updated this. Changes should be live soon.
