### ISSUE TITLE
WinUI 3 Preview 3: Project Name (Desktop) => Replace Screenshot and adjust description to use MainWindow.xaml and App.xaml

### ISSUE THREAD

**Issue by thomasclaudiushuber** [MicrosoftDocs/windows-uwp#2819]
The bullet point 6. on this page talks about App.xaml.cs and MainWindow.xaml.cs, but totally forgets the more important files App.xaml and MainWindow.xaml. It should be described that the .xaml files contain the UI, and the .xaml.cs files the UI logic.

Also this screenshot is broken. It doesn't even show the .xaml files in the Solution Explorer.

![image](https://user-images.githubusercontent.com/7116546/99550101-a0997700-29ba-11eb-8eb1-a367617e0617.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6a5c75-6cdc-a97f-df50-938ac5534e28
* Version Independent ID: e7195fca-7687-4296-6aa8-638ce198d549
* Content: [Get started with WinUI 3 for desktop apps - WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop#feedback)
* Content Source: [hub/apps/winui/winui3/get-started-winui3-for-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/get-started-winui3-for-desktop.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I updated the screenshot and related text to include the XAML files as per the latest support in Preview 3. These changes are now live on the docs site.
