### ISSUE TITLE
Typo in page "Templated XAML controls for WinUI 3 apps with C++/WinRT"

### ISSUE THREAD

**Issue by leejy12** [MicrosoftDocs/windows-uwp#2822]
[Enter feedback here]

Under [Add a templated control to your app](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3#add-a-templated-control-to-your-app) section, there is "C++/WinRTmimplementation" which should be "C++/WinRT implementation".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aad2d1a-fe9c-04ed-2fae-545f071c1f46
* Version Independent ID: f8d878ef-1d8d-9b12-5ac9-f7b936916fea
* Content: [Templated XAML controls for WinUI 3 apps with C++/WinRT - WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3)
* Content Source: [hub/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this typo. It has been fixed in the source and should be updated on the live site within a few hours.
