### ISSUE TITLE
IInitializeWithWindow incorrect for .NET 5

### ISSUE THREAD

**Issue by trympet** [MicrosoftDocs/windows-uwp#2824]
The current documentation states that the IInitializeWithWindow interface should be used the following way:
```c#
StoreContext context = StoreContext.GetDefault();
IInitializeWithWindow initWindow = (IInitializeWithWindow)(object)context;
initWindow.Initialize(System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle);
```

This will throw an `InvalidCastException`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e80e2c-f648-2232-eda5-dbf60ed3c45f
* Version Independent ID: d3341110-0411-f7df-3191-a700d5a814f4
* Content: [In-app purchases and trials - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#desktop)
* Content Source: [windows-apps-src/monetize/in-app-purchases-and-trials.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/in-app-purchases-and-trials.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by trympet** [comment]
For .NET 5, the IInitializeWithWindow interface should be used like this:
 ```csharp
 StoreContext context = StoreContext.GetDefault();
 IInitializeWithWindow initWindow = context.As<IInitializeWithWindow>();
 initWindow.Initialize(System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle);
 ```

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. It looks like somebody has updated the example on this page to work with later versions of .NET. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
