### ISSUE TITLE
Sample Json for windows-app-web-link is not formatted correctly

### ISSUE THREAD

**Issue by aleibhardt** [MicrosoftDocs/windows-uwp#2830]
The sample json for the windows-app-web-link is not formatted correctly and fails when running the AppHostRegistrationVerifier.exe tool.

Here's the current sample:
```
[{
  "packageFamilyName": "Your app's package family name, e.g MyApp_9jmtgj1pbbz6e",
  "paths": [ "*" ],
  "excludePaths" : [ "/news/*", "/blog/*" ]
 }]
```

This fails in the tool with the following message:
Failed to validate: Invalid JSON string.

This improper formatting is due to the colon being placed without the proper white space between. Here's the json that passes the validation tool.

```
[{
  "packageFamilyName" : "Your app's package family name, e.g MyApp_9jmtgj1pbbz6e",
  "paths" : [ "*" ],
  "excludePaths" : [ "/news/*", "/blog/*" ]
 }]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e251da-3cab-4aa0-2915-21189cf71bef
* Version Independent ID: b244b311-a0e5-185d-df82-1dadf3fe6416
* Content: [Enable apps for websites using app URI handlers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking)
* Content Source: [windows-apps-src/launch-resume/web-to-app-linking.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/web-to-app-linking.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks so much for pointing this out, @aleibhardt . I went ahead and made the changes. They should be live soon.
