### ISSUE TITLE
The text following "Order of events:" is mingled

### ISSUE THREAD

**Issue by rlaf99** [MicrosoftDocs/windows-uwp#2833]
[Enter feedback here]

https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators#the-previewkeydown-and-previewkeyup-events

The text following "Order of events:" is mingled:

Preview KeyDown events … App accelerator OnKeyDown method KeyDown event App accelerators on the parent OnKeyDown method on the parent KeyDown event on the parent (Bubbles to the root) … CharacterReceived event PreviewKeyUp events KeyUpEvents

Suppose there should some linebreaks in between.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d15a60b-7f90-38b9-18a2-a4437628e67a
* Version Independent ID: cb3c6a7a-c3df-1599-fe25-681ae66e0f49
* Content: [Keyboard accelerators - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators#usability-affordances-for-keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! The topic has been updated.
