### ISSUE TITLE
"Get set up with UWP" leads to 404

### ISSUE THREAD

**Issue by 0x08088405** [MicrosoftDocs/windows-uwp#2834]
So you have this part on the page:

> Check out **Get set up** to download the tools you need to start creating apps, and then write your first app.

Unfortunately, I cannot even see what getting set up would look like, because that link leads to a 404.

The problem seems to be that (I assume) it's generated from markdown, but the actual URL doesn't end in `.md`:
```html
Check out <a href="/en-us/windows/apps/get-started/get-set-up.md" data-linktype="absolute-path">Get set up</a>
```

A quick search through the page reveals this mistake appears earlier in the page too:

```html
To download the tools you need to start creating UWP apps, see <a href="/en-us/windows/apps/get-set-up.md" data-linktype="absolute-path">Get set up</a>,
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcd2e7e-612d-29de-6b94-3bed0b772b16
* Version Independent ID: cf067679-95df-f7d2-17ec-d15cc18c0b4b
* Content: [What's a Universal Windows Platform (UWP) app? - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide#feedback)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for bringing this to my attention. The broken links have been fixed.
