### ISSUE TITLE
retrieve_properties async should pass by value

### ISSUE THREAD

**Issue by mziller** [MicrosoftDocs/windows-uwp#2838]
The prior example just finished stating that guidance was to pass by value and then the example comparing passing vectors of hstring vs wstring passes by const& (and std::moves the 2nd parameter passed by ref, probably not what was intended):

IAsyncAction retrieve_properties_async(StorageFile const**&** storageFile, std::vector<std::wstring> const**&** vecW)
{
    auto properties{ co_await storageFile.Properties().RetrievePropertiesAsync(std::move(vecW)) }; // error! Can't convert from vector of wstring to async_iterable of hstring.
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f49f4be-1a20-b442-369f-2d51c0a025ed
* Version Independent ID: 638c0c06-3834-74d5-d346-7c47e988ac44
* Content: [Standard C++ data types and C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/std-cpp-data-types#standard-arrays-and-vectors)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/std-cpp-data-types.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/std-cpp-data-types.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Great, and thanks for spotting those mistakes, Michael! I saw your mention of this issue on the discussion alias, so I was going to come fix it after seeing that. The fix is live now. I'll go ahead and close this issue.

Thanks!
Steve
