### ISSUE TITLE
Mismatch between text and illustration

### ISSUE THREAD

**Issue by JVimes** [MicrosoftDocs/windows-uwp#2840]
Under [Combining Structures](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-basics#combining-structures) it says:

> Consider the adjacent illustration... At level 1, the peer-to-peer navigation element should provide access to pages A, B, C, and D.

"D" should probably be removed from the text since it's not in the illustration:

![image](https://user-images.githubusercontent.com/6148201/101067780-2be74080-3555-11eb-8b1a-29b13feae3aa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054a2d98-05ac-9f54-de84-3e7e14e1269d
* Version Independent ID: 7302ceaf-a1aa-0427-2233-5a7237aff043
* Content: [Navigation basics for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-basics)
* Content Source: [windows-apps-src/design/basics/navigation-basics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-basics.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. The article has been updated.
