### ISSUE TITLE
C#?

### ISSUE THREAD

**Issue by aaroncarrick** [MicrosoftDocs/windows-uwp#2841]
Will we be getting a C# version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac4115a-6482-734f-15cd-4601ffafa4df
* Version Independent ID: 37664920-b9b0-1457-1711-b2ed848dd8fb
* Content: [Multisampling in UWP apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps)
* Content Source: [windows-apps-src/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @aaroncarrick, and thanks for filing this issue. For Direct3D code examples, we provide them in C++ only.

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now.

Thanks again!
Steve
