### ISSUE TITLE
Broken link to developer account information

### ISSUE THREAD

**Issue by jeubank12** [MicrosoftDocs/windows-uwp#2842]
https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees.md is a broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6fd76a6-722a-1fb3-e9d4-441155de3816
* Version Independent ID: e990aa35-b577-3586-c4dd-8b78aaf6e64e
* Content: [Create a developer account - Windows applications](https://docs.microsoft.com/en-us/windows/apps/get-started/sign-up)
* Content Source: [hub/apps/get-started/sign-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/sign-up.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for letting us know! I've corrected this link.
