### ISSUE TITLE
HTML a tag in markdown make the whole block show as link

### ISSUE THREAD

**Issue by hachiang-msft** [MicrosoftDocs/windows-uwp#2846]
[Enter feedback here]
Hi,

There are some html tag in markdown. 
i.e. ```<a id="template-studio" />```

This would effect the header and block content on web page.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e714a91f-14d9-21ed-ce3a-8263bf9a5e8e
* Version Independent ID: 226b6de7-efca-38c5-2992-f27274382b9c
* Content: [Enterprise - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/enterprise/#feedback)
* Content Source: [windows-apps-src/enterprise/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/enterprise/index.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. I have fixed the anchor link formatting so the article is now rendering as expected.
