### ISSUE TITLE
Taskbar pinning is not working on Surface Go device

### ISSUE THREAD

**Issue by AkshathaSP** [MicrosoftDocs/windows-uwp#2850]
Taskbar pinning is not working on Surface Go device.
It does not prompt for user action and is also seen to auto pin the app.
Is there any API issues with surface go or any specific windows version ?

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. I don't have any additional content for your scenario, over and above what's in the documentation. So it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback. Alternatively, you can direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html). The community of experts and Microsoft engineers can provide timely answers to your technical questions. Thanks!
