### ISSUE TITLE
Install nvm 

### ISSUE THREAD

**Issue by TheLoop705** [MicrosoftDocs/windows-uwp#2853]
Install nvm, node.js, and npm
after the curl you have to run: source ~/.nvm/nvm.sh otherwise command -v nvm wont output anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
This hasn't been forgotten -- I'm just working on a bit of an overhaul of these docs and need to do a bit more testing to see how to word this exactly. 
Thank you for the feedback and pointing out the issue. This could be frustrating for folks thinking that their install didn't work.

**Comment by mattwojo** [comment]
Resolved.
