### ISSUE TITLE
npm not installed

### ISSUE THREAD

**Issue by catreedle** [MicrosoftDocs/windows-uwp#2854]
I followed these steps and successfully installed node with nvm but npm is not installed.

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js

anyone knows how to solve this error?

**Comment by mattwojo** [comment]
Hi @catreedle - Could you provide a bit more info? Which steps did you follow? (Could you share the URL to the docs page?) Did you install NodeJS directly on Windows or on WSL (the Linux subsystem)?
Have you tried entering `node --version`? Which version of NodeJS is it reporting that you have installed?
: ) Matt

**Comment by mattwojo** [comment]
My best guess is either that this is an issue with pathing for where NodeJS was installed (https://stackoverflow.com/questions/24721903/npm-cli-js-not-found-when-running-npm) or maybe that a version of NodeJS wasn't run when you installed with NodeJS ---  I think that using NVM, you may have to confirm which Node version you are installing --- you may've seen something like: 
```
>nvm install 4.4.7
Downloading node.js version 4.4.7 (64-bit)... Complete
Creating C:\Users\myusernamewithoutspaces\AppData\Roaming\nvm\temp

Downloading npm version 2.15.8... Complete
Installing npm v2.15.8...

Installation complete. If you want to use this version, type

nvm use 4.4.7
```

It can be easy to miss the call to enter the command `nvm use x.x.x` which defines the version of Node that you want to use... if you miss this then node isn't actually installed... and neither would npm... so if you tried to do an `npm install ...` then you would receive an error.

**Comment by mattwojo** [comment]
Closing.. but if you continue to have issues, please feel welcome to reopen. Thanks!
