### ISSUE TITLE
Resource keys are incorrect.

### ISSUE THREAD

**Issue by bkaankose** [MicrosoftDocs/windows-uwp#2855]
Minimum window sizes resources are defined with the suffix 'Breakpoint' but it's used as 'SnapPoint' in the code. Since VisualStateManager doesn't throw any exceptions  it's hard to catch.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cef1216-cac2-23c6-b76e-d1e4b565f508
* Version Independent ID: 6f27fa70-da48-85e6-ce25-b50bf8b4c309
* Content: [Create adaptive layouts tutorial - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-adaptive-layout)
* Content Source: [windows-apps-src/design/basics/xaml-basics-adaptive-layout.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-adaptive-layout.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@bkaankose, thanks for pointing this out. The doc has been fixed.
