### ISSUE TITLE
Javascript UWP template outdated

### ISSUE THREAD

**Issue by angelazhangmsft** [MicrosoftDocs/windows-uwp#2857]
In Step 1, I can't find the Javascript UWP template in Visual Studio 2019 when creating a new project. From searching online, it seems this template isn't supported in Visual Studio 2019 anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d0fe742-3735-ab27-d638-dc19ee2481ce
* Version Independent ID: cdb363a8-c8f0-ac1d-b6ca-7727d125fdf5
* Content: [Walkthrough of creating a C# or Visual Basic Windows Runtime component, and calling it from JavaScript - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript)
* Content Source: [windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @angelazhangmsft, and thanks for filing this issue. That's right, that project template isn't supported by VS2019. I'm in the process of adding the following info to the topic:

> [!NOTE]
> Universal Windows Platform (UWP) projects using JavaScript are not supported in Visual Studio 2019. See [JavaScript and TypeScript in Visual Studio 2019](https://docs.microsoft.com/visualstudio/javascript/javascript-in-vs-2019#projects). To follow along with this topic, we recommend that you use Visual Studio 2017. See [JavaScript in Visual Studio 2017](https://docs.microsoft.com/visualstudio/javascript/javascript-in-vs-2017).

And I've made a note to track that change and I'll ensure that it goes live. I'll go ahead and close the issue.

-Steve
