### ISSUE TITLE
Links 404 in "What's Next" section

### ISSUE THREAD

**Issue by maggiechen** [MicrosoftDocs/windows-uwp#2858]
In this section:
https://docs.microsoft.com/en-us/windows/apps/get-started/get-set-up#whats-next
The two links [Choose your platform ](https://docs.microsoft.com/en-us/windows/desktop/apps/choose-your-platform.md) and [Start coding UWP apps](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-uwp-apps.md) lead to 404 pages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1da8b1-9339-84d0-847f-f4e3a98ba9bd
* Version Independent ID: 004e55ff-9cfe-0fb2-69c0-64e2787a8f8a
* Content: [Get set up - Windows applications](https://docs.microsoft.com/en-us/windows/apps/get-started/get-set-up)
* Content Source: [hub/apps/get-started/get-set-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/get-set-up.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for reporting this, I have corrected the links!
-john
