### ISSUE TITLE
Links to the source code is not working

### ISSUE THREAD

**Issue by laphir** [MicrosoftDocs/windows-uwp#2859]
Links to the source code is not working.
e.g. In this page, https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp, click on HelloWindowsDesktop.cpp. Links of other source files are not working as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896fef0f-20c1-4191-4f05-b330bc02e820
* Version Independent ID: c58a8006-f1f3-4345-d5fb-205b4c782320
* Content: [Host a standard WinRT XAML control in a C++ Win32 app using XAML Islands - Windows applications](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp)
* Content Source: [hub/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-standard-control-with-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this. The product team that created the samples refactored their code a while back, and that resulted in this broken link. I have fixed the link.

**Comment by laphir** [comment]
Wow, Microsoft, it's so fast!  Thank you!

2020년 12월 15일 (화) 오후 12:02, McLean Schofield <notifications@github.com>님이
작성:
