### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/windows-uwp#2864]
On this page, in the section "Related Articles" there is a link with the text "Drag and drop" and url `https://docs.microsoft.com/en-us/windows/uwp/app-to-app/drag-and-drop` that results in a 404.

I am guessing it should be `https://docs.microsoft.com/en-us/windows/uwp/design/input/drag-and-drop`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ddb9c6-9984-109d-72a7-8c88b6aa1438
* Version Independent ID: 3bfca085-7e62-2b2c-47ce-902a237423b4
* Content: [Collections and lists - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/lists)
* Content Source: [windows-apps-src/design/controls-and-patterns/lists.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/lists.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Link is fixed in #2867
