### ISSUE TITLE
We're debugging the issue with him

### ISSUE THREAD

**Issue by Dour420** [MicrosoftDocs/windows-uwp#2869]
We're debugging the issue with him

__Originally posted by @crutkas in https://github.com/microsoft/PowerToys/issues/4000#issuecomment-637855715__

**Comment by crutkas** [comment]
we can close this out.  this was linked via a closed item.

**Comment by Taneeda** [comment]
and where is my topic addressed now?

https://github.com/microsoft/PowerToys/issues/4000#issuecomment-747294259
