### ISSUE TITLE
header

### ISSUE THREAD

**Issue by hossamrashad** [MicrosoftDocs/windows-uwp#2874]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Design toolkits and samples for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#samples)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported.
