### ISSUE TITLE
Consider updating the YAML template with the more recent NuGetToolInstaller@1 task

### ISSUE THREAD

**Issue by MagnusJohansson** [MicrosoftDocs/windows-uwp#2882]
It seems that the YAML sample in the section
"Set up an automated build
 This template includes the basic configuration to build your UWP project:"

Is using the `NuGetToolInstaller@0` task , which causes this error:

Starting: NuGetToolInstaller
...
"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/msbuild.exe" /version /nologo
**ERR:Invalid Version: 16.8.2.56705**
Finishing: NuGetToolInstaller

However, by using a more recent task; `NuGetToolInstaller@1` this error does not appear.

Consider updating the sample YAML on this page with the more recent `NuGetToolInstaller@1`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this. I have updated the task reference to `NuGetToolInstaller@1`.
