### ISSUE TITLE
Link to obtain Client ID and Secret is broken

### ISSUE THREAD

**Issue by Xeeynamo** [MicrosoftDocs/windows-uwp#2883]
The link to obtain the Client ID and Client Secret from the devcenter returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0229b7-46a8-8fe9-4fc6-4a9274451c10
* Version Independent ID: bbb1fe01-7693-a156-0951-1022be63e5fa
* Content: [Create and manage submissions - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services)
* Content Source: [windows-apps-src/monetize/create-and-manage-submissions-using-windows-store-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/create-and-manage-submissions-using-windows-store-services.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by MatchaMatch** [comment]
Hi there - the link has been updated and now points to the Partner Center. Thanks for bringing this to our attention!
