### ISSUE TITLE
Dead Link on Webpage: Start coding UWP apps

### ISSUE THREAD

**Issue by shazbots** [MicrosoftDocs/windows-uwp#2885]
On the webpage: https://docs.microsoft.com/en-us/windows/apps/get-started/get-set-up
When I click on [What's Next] >> [Start coding UWP apps], it takes me to: https://docs.microsoft.com/en-us/windows/uwp/get-started/create-uwp-apps.md
I see a 404 error there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1da8b1-9339-84d0-847f-f4e3a98ba9bd
* Version Independent ID: 004e55ff-9cfe-0fb2-69c0-64e2787a8f8a
* Content: [Get set up - Windows applications](https://docs.microsoft.com/en-us/windows/apps/get-started/get-set-up)
* Content Source: [hub/apps/get-started/get-set-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/get-set-up.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for reporting this, I have corrected the link!
-john
