### ISSUE TITLE
[PowerToys][Link confusion]

### ISSUE THREAD

**Issue by just1a-person** [MicrosoftDocs/windows-uwp#2888]
## Repro steps
- Click here:

   ![Docs image](https://user-images.githubusercontent.com/75578443/103168971-f8e75280-485d-11eb-8992-e543e284f5af.png)
- That will lead to me to here:
    ![Wiki page](https://user-images.githubusercontent.com/75578443/103168990-1a483e80-485e-11eb-9006-4ae68c08483c.png)
- Clicking on that will lead me to where I started

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/keyboard-manager#feedback)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mattwojo** [comment]
Thanks @itsme-alan! There was a bit of mis-communication re: whether these blocked shortcuts would be listed in the product repo notes or the docs... just got it straightened out and moved into the docs though. You can see the resolution PR here: https://github.com/MicrosoftDocs/windows-uwp/commit/1a997d7e0100e58886150f9fba33d7b205f41df1 
..and the live doc with the blocked keys listed in the note here: https://docs.microsoft.com/en-us/windows/powertoys/keyboard-manager
