### ISSUE TITLE
Additional notes for Setting the machine name

### ISSUE THREAD

**Issue by mcalasa** [MicrosoftDocs/windows-uwp#2889]
Hello, 
Under 'Setting the machine name' it would be useful if the following was added to 'Setting the machine name':

1. Can an example for the URI parameter section be added? For example maybe add something like this: /api/os/machinename?name=[BASE_64_ENCODED_NAME].  I understood URI Parameters to mean /api/os/machinename/[BASE_64_ENCODED_NAME] but I was incorrect to assume that.  
2. Also after setting the machine name can a note be added that the device may need to be rebooted for the name change to take effect?  

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606c1247-47ba-a3fd-3abc-c072336bf019
* Version Independent ID: 729ff3d9-ebe0-bf23-605c-1ea1b0f2d3bd
* Content: [Device Portal core API reference - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @mcalasa - the URI parameter construct is a well known spec and it wouldn't make sense to add your requested clarification to this single entry in a single topic amongst many that reference them throughout. 

Closing for age. If you still feel this is a concern, please open a new issue.
