### ISSUE TITLE
Error in glyph table

### ISSUE THREAD

**Issue by deakjahn** [MicrosoftDocs/windows-uwp#2892]
[Enter feedback here]

F87D SpellingSerbian row has an obvious error (missing codepoint, wrong placement of name).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 Assets icons - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi @deakjahn , is the issue you're experiencing due to the rendering of the table? On desktop, I'm seeing this and I'm curious if it's different on your end.

![image](https://user-images.githubusercontent.com/55564399/103597061-25314d80-4eb4-11eb-9c25-56df50295884.png)

**Comment by deakjahn** [comment]
Somebody fixed it? :-)) I saw it with "SpellingSerbian" in the first column (in place of the codepoint) and the second column empty. Repeatedly, not just a temporary glitch. Pity I didn't make a screenshot. But it's OK now.

**Comment by hkhmsft** [comment]
Awesome, glad to know it's resolved on your end.
