### ISSUE TITLE
Suggested solution creates unwanted tooltips

### ISSUE THREAD

**Issue by deakjahn** [MicrosoftDocs/windows-uwp#2894]
The code solution (the keyboard accelerators) suggested on the page creates annoying GoBack tooltips all over the application window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db3df4b-39b3-74ae-6cea-ffe2b3f52df3
* Version Independent ID: f75fe3ae-e7ed-1441-3cc5-5c59bf9cbde2
* Content: [Navigation history and backwards navigation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@deakjahn, thanks for pointing this out. <edited>

**Comment by deakjahn** [comment]
@jwmsft And what should I refer to if I don't have a _Back_ button but a `NavigationView`? If I refer to that, I still get the tooltips, rather logically.

Also, while you're at it, you might want to reformat it to the newer

      var AltLeft = new KeyboardAccelerator {
        Key = VirtualKey.Left,
        Modifiers = VirtualKeyModifiers.Menu,
        ScopeOwner = NavView, // or whatever
      };
      AltLeft.Invoked += BackInvoked;
      KeyboardAccelerators.Add(AltLeft);

format.

**Comment by jwmsft** [comment]
I tried the [code in the NavigationView article](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/navigationview#code-example), and the NavigationView handled it correctly without setting ScopeOwner. Using that example code, the tooltip showed up only on the NavigationView's back arrow. Have you tried that example code?

**Comment by deakjahn** [comment]
In the `Loaded` handler? No, I haven't tried earlier but yes, it seems to work.

**Comment by jwmsft** [comment]
@deakjahn, your question prompted me to do a thorough review of the article, and I found several problems. I've rewritten it to demonstrate the preferred way to handle back navigation. I've also updated the code in the NavigationView article. Thanks.
