### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by eg1010** [MicrosoftDocs/windows-uwp#2895]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1da8b1-9339-84d0-847f-f4e3a98ba9bd
* Version Independent ID: 004e55ff-9cfe-0fb2-69c0-64e2787a8f8a
* Content: [Get set up - Windows applications](https://docs.microsoft.com/en-us/windows/apps/get-started/get-set-up)
* Content Source: [hub/apps/get-started/get-set-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/get-set-up.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by eg1010** [comment]
The page: https://docs.microsoft.com/en-us/windows/apps/get-started/get-set-up
Has a hyperlink under "Start coding UWP apps" that results in a 404 - Page Not Found.

**Comment by GrantMeStrength** [comment]
Thanks for reporting this, I have corrected the link.
-john
