### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by tatapuchi** [MicrosoftDocs/windows-uwp#2897]
It would be helpful if you could provide minimal sample projects for AppWindow and ApplicationView

**Comment by jwmsft** [comment]
Hi, sorry for the late reply. The [Show multiple views with AppWindow](https://docs.microsoft.com/windows/uwp/design/layout/app-window) page and related ApplicationView page have sample code that you can copy and paste into VisualStudio.

We also have sample projects available on GitHub: [AppWindow sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/AppWindow) and [ApplicationView sample](https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Platform%20Sample/Windows%208.1%20Store%20app%20samples/99866-Windows%208.1%20Store%20app%20samples/Application%20Views).

Hopefully these resources help.
