### ISSUE TITLE
AttributeError: module 'pygame' has no attribute 'Quit'

### ISSUE THREAD

**Issue by machinehistories** [MicrosoftDocs/windows-uwp#2899]
[In the tutorial it is written 
if event.type == pygame.Quit: sys.exit()
but I got an AttributeError: module 'pygame' has no attribute 'Quit'
It worked when written as follows
if event.type == pygame.quit: sys.exit()
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56d5dd2-6677-fb21-03d2-b9ea94e2b9a8
* Version Independent ID: 973324bd-74b0-8589-0f36-2d4ab1583208
* Content: [Get started with using Python on Windows for beginners](https://docs.microsoft.com/en-us/windows/python/beginners)
* Content Source: [hub/python/beginners.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/beginners.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hmmm.... this sample still seems to be working fine for me. @machinehistories - Could you check to make sure your file isn't named pygame.py and you don't have a folder named pygame.

http://stackoverflow.com/questions/19912810/pygame-attribute-init
http://stackoverflow.com/questions/28231200/i-keep-getting-the-error-module-object-has-no-attribute-init

**Comment by mattwojo** [comment]
Here's another StackO post with someone having a similar issue with not finding the 'Quit' attribute. If you check that your file isn't named pygame.py and your folder isn't named pygame, then maybe try some of the fixes mentioned here (though it doesn't seem to be clearly resolved): https://stackoverflow.com/questions/65637456/pygame-missing-quit-module

**Comment by mattwojo** [comment]
Closing. Please feel welcome to reopen if there is anything that requires an update to the docs or if you run into further issues. Thanks for the feedback! :)
