### ISSUE TITLE
Update UWP gaming content for Visual Studio 2017

### ISSUE THREAD

**Issue by PoulChapman** [MicrosoftDocs/windows-uwp#290]
Please update this section for Visual Studio 2017

https://docs.microsoft.com/en-us/windows/uwp/gaming/e2e

**Comment by ginami** [comment]
Thank you @PoulChapman for this feedback.

@joannaleecy, can you follow up on this? Thank you!

**Comment by joannaleecy** [comment]
@PoulChapman @ginami  thanks for the message. I will include this change into the next update. :)

**Comment by mijacobs** [comment]
@joannaleecy Should this be updated for VS 2019?
