### ISSUE TITLE
Broken link -- 404

### ISSUE THREAD

**Issue by twhall-umich** [MicrosoftDocs/windows-uwp#2900]
Broken link -- 404:

In https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-mr

"Updating your existing universal app for Hololens"
https://developer.microsoft.com/windows/mixed-reality/updating_your_existing_universal_app_for_hololens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7a3a77-0b4b-387c-fe07-1c13c1bbd2d0
* Version Independent ID: 7fbaf386-4594-d23c-d360-30a5816c36c4
* Content: [Designing for Mixed Reality - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-mr)
* Content Source: [windows-apps-src/design/devices/designing-for-MR.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/devices/designing-for-MR.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Thanks! Links found and updated. Going live soon. Thanks for reporting!
