### ISSUE TITLE
Missing Info

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2901]
I couldn't run the "python3" command on powershell, since I didn't not install Python from Microsoft Store. So I made the following changes:

**1.** I changed the command call in the first part tenth header as follows:

```powershell

python .\list-directory-contents.py

```
**2.** I changed the command call in the first part eleventh header as follows:

```powershell 

python .\list-directory-contents.py > food-directory.txt 

```

![Python  1](https://user-images.githubusercontent.com/57282885/104323728-92b62d00-54f7-11eb-862c-a7ed0cfbbf10.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cef0cd5-f116-1e35-c1ab-385063aac0b7
* Version Independent ID: a53f5975-623f-c1c0-faa1-c0b7c4d3324e
* Content: [Scripting and automation with Python on Windows](https://docs.microsoft.com/en-us/windows/python/scripting)
* Content Source: [hub/python/scripting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/scripting.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Awesome! Glad you were able to figure this out. I'll look into to adding your solution as a note in the article for other folks who may not be able to install Python from the Store. Thanks!

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1233
