### ISSUE TITLE
Remap keys

### ISSUE THREAD

**Issue by Caterat** [MicrosoftDocs/windows-uwp#2903]
[I read:
Launch the Remap Keyboard settings window by selecting Remap a Key
Launch the Remap Shortcuts settings window by selecting the Remap a shortcut
But where do I find Remap a Key and Remap a shortcut? There is no explanation]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
I'm not sure this is the correct way to ask PowerToys questions (the GitHub repo is probably best) but I'm assigning Matt who owns this content.

**Comment by mattwojo** [comment]
Hi @Caterat - Thanks for posting this question. The "Remap a key" and "Remap a shortcut" buttons are in the Keyboard Manager tab of the PowerToys Settings. To launch PowerToys Settings, you can search for PowerToys in your Windows menu (lower-left icon) or find where the PowerToys icon shows that it's running in your task manager (probably in the hidden icons on the right) and right-click to see the option to open settings. 
I'll update the doc to be more explicit about opening PowerToys Settings. 
Thanks again.

**Comment by mattwojo** [comment]
![image](https://user-images.githubusercontent.com/7566797/104773055-4c481480-5729-11eb-9a18-944b38165a5e.png)

**Comment by mattwojo** [comment]
Adding this call out to the doc: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1237

Thanks again. 👍
