### ISSUE TITLE
Typo in the description of an error code 0x803F6102

### ISSUE THREAD

**Issue by nisb** [MicrosoftDocs/windows-uwp#2907]
The present description for error code 0x803F6102:
The specified add-on could not be found. The add-on may no longer be available in the Store, or your might have provided the wrong Store ID for the add-on.

Proposed description:
The specified add-on could not be found. The add-on may no longer be available in the Store, or **you** might have provided **a** wrong Store ID for the add-on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7acb58af-680c-17bc-2233-4ef5b629fc54
* Version Independent ID: 3208ab40-b3a8-d0cb-ec96-fe0a54bae300
* Content: [Error codes for Store operations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/error-codes-for-store-operations)
* Content Source: [windows-apps-src/monetize/error-codes-for-store-operations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/error-codes-for-store-operations.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Thank you, corrected.
