### ISSUE TITLE
The EF on UWP  link is wrong.

### ISSUE THREAD

**Issue by Iamnvincible** [MicrosoftDocs/windows-uwp#2910]
The link in this line

> To try it out, see Getting started with EF Core on Universal Windows Platform (UWP) with a New Database.
**https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started**

is not **REALLY** linked to a UWP tutorial.

In fact it is redirected to
 **https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback @Iamnvincible . It seems that the original UWP article was since redirected to this newer general EF Core article. I went ahead and clarified the link description to avoid any confusion. Thanks.
