### ISSUE TITLE
Links are broken.

### ISSUE THREAD

**Issue by hckim0911** [MicrosoftDocs/windows-uwp#2911]
[Enter feedback here]

Some links on this page are broken.
When I access them, 404 pages come out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0552daf5-cead-a1cd-c15a-d35ad32259e3
* Version Independent ID: 038857ac-c7b7-beef-14c1-aca52915afd3
* Content: [Developer Mode features and debugging - Windows applications](https://docs.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging)
* Content Source: [hub/apps/get-started/developer-mode-features-and-debugging.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/developer-mode-features-and-debugging.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for the heads-up! I've corrected the links. Keep letting us know when you find broken links! :-)
