### ISSUE TITLE
How to receive notification when user changes the state of a subscription in Microsoft Store?

### ISSUE THREAD

**Issue by Chris1-Fu** [MicrosoftDocs/windows-uwp#2912]
I have tried to find the method (e.g. Server to Server on ios) to handle the subscriptions status of the users, but it seems no any way to  receive notification when user changes the state of a subscription (e.g. turn on/off autorenew, cancel the subscription).

Is it possible to receive these notifications?

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there.
