### ISSUE TITLE
Need to describe how to provide icons

### ISSUE THREAD

**Issue by vskotatko** [MicrosoftDocs/windows-uwp#2913]
Overall, this page is well written. However, nowhere does it describe how to provide the icons referenced in the examples. Either explain it on this page or provide a link to an explanation elsewhere. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c464d2-7b2b-8313-a694-39ef91ece212
* Version Independent ID: fd7b2a74-f196-fb8a-cf0c-7b8c42e4cade
* Content: [Command bar - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars)
* Content Source: [windows-apps-src/design/controls-and-patterns/app-bars.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/app-bars.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. I've added some clarification and a link to the [AppBarButton](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.appbarbutton?view=winrt-19041) class, which has more information and examples of adding icons.
