### ISSUE TITLE
Invalid link to Youtube

### ISSUE THREAD

**Issue by msftpetergu** [MicrosoftDocs/windows-uwp#2914]
All four links pointing to Youtube are invalid. "The playlist does not exist." the page said.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ade8bd6-7a05-1a6a-ea2f-b77798d4607d
* Version Independent ID: 6a2c0366-7b16-0bf2-f809-6521c3936886
* Content: [What's New in Windows 10, build 18362 - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-18362)
* Content Source: [windows-apps-src/whats-new/windows-10-build-18362.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-18362.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by ghost** [comment]
As far as I understand, the playlists on the [Microsoft Developer](https://www.youtube.com/c/MicrosoftDeveloper) page on YouTube have been updated or have had an indexing issue. Therefore playlist queries are being overriden. So I manually scanned the available playlists: [Microsoft Developer's all playlists on YouTube](https://www.youtube.com/c/MicrosoftDeveloper/playlists?view=1). 

The One Dev Question playlists in the [videos section](https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-18362#videos) are as follows:

* [One Dev Question with Raymond Chen](https://www.youtube.com/watch?v=teV0gjCacug&list=PLlrxD0HtieHge3_8Dm48C0Ns61I6bHThc)
* [One Dev Question with Larry Osterman](https://www.youtube.com/watch?v=_34CokLwodE&list=PLlrxD0HtieHhDTjMijDOd0BSJcpSFabfE)
* [One Dev Question - Visual Studio Code (Chris Heilmann)](https://www.youtube.com/watch?v=cYRn5ONWAqo&list=PLlrxD0HtieHjQX77y-0sWH9IZBTmv1tTx)
* [Building Progressive Web Apps to Extend Existing Web Apps in Windows and Microsoft](https://www.youtube.com/watch?v=ks3CYvPBO2k&ab_channel=MicrosoftDeveloper)

**Comment by QuinnRadich** [comment]
Sercan, many thanks for finding those updated playlists. I've fixed the links in this article to point to those new correct locations, and the page should be updated shortly.
