### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by bigQY** [MicrosoftDocs/windows-uwp#2915]
[Enter feedback here]
Providing a detailed open source project may help developers understand these APIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98de0162-dc53-a39d-0bba-e7f9b1662519
* Version Independent ID: fd54c26c-d272-89c4-3f55-1c3ba5ab5c6a
* Content: [Windows Hello and unlocking with companion devices - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/security/companion-device-unlock)
* Content Source: [windows-apps-src/security/companion-device-unlock.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/companion-device-unlock.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. This API has been deprecated, so we won't be adding any examples or making other changes to these docs. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
