### ISSUE TITLE
Desktop App Installs API: Product Ids difficult to find in Installs report

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2917]
The documentation indicates the product ID required for this API can be found in the URL of the Installs report. While this is true, where to find the URL is not clear. It's not until you mouse of over a link, that you notice the url and the embedded product id. 

A screenshot or clearer explanation on how the product ids can be found, is needed here. This is causing unnecessary delays in the setup and use of this API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 574103c4-4289-4a65-3a53-bb1c49010b23
* Version Independent ID: 50a9ebff-98b8-e926-5290-7957922385d8
* Content: [Get desktop application installs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-desktop-app-installs)
* Content Source: [windows-apps-src/monetize/get-desktop-app-installs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-desktop-app-installs.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Thank you, text has been updated.
