### ISSUE TITLE
Please Clarify the Effects of Enabling Organizational Licensing and Allowing Volume Acquisition in the Business and Education Stores

### ISSUE THREAD

**Issue by mthomason** [MicrosoftDocs/windows-uwp#2918]
### What does allowing Organizational Licensing mean?

1. An organization can purchase a license (one-and-only-one) for the list price.  Once owned by that organization, they can assign that one volume license to any users in their company without additional charge?  _In this case, the organizational license is a one time fee for a **companywide license**._
2. An organization can purchase a desired number of licenses (one-to-many licenses) at a multiple of the list price, and assign the license to one user for each license purchased. _In this case, the "organizational license" option permits companies to acquire **reassignable-user-licenses**._

### Example
If I publish a "paid application," for a price of $4.99 USD, what are the effects of enabling organizational licensing and allowing volume acquisition?

**Effect in the _Microsoft Store_ is Clear**
_In the Microsoft Store, every user that wants to acquire the application must pay $4.99.  That's clear and intuitive.  But, in the Microsoft Store for Business and the Microsoft Store for Education, what is the effect of allowing Organizational Licensing?_

**Effect in the _Microsoft Store for Business_ is Ambiguous**
_I can't determine which outcome is expected._
1. The organization gets to acquire unlimited use of the application from the MS Store for Business for a onetime fee of $4.99. They can distribute it to anyone inside their organization without paying anything more than $4.99.
2. The organization gets to purchase one-or-many licenses for their users; they then assign the license to their one-to-many users.  If the organization decides to buy 100 licenses, they would pay $499.00 for those licenses.  They assign them to specific users.  If a user is no longer using the license, they can re-assign the license to another user?

### The Difference is Needed to Determine  a Vendors List Pricing
The way a publisher should price their software is not clear.  I can't find the answer in this document, or any other.  If I choose to allow organizational licensing, or volume acquisition (the terms seem to be used interchangeably in the documentation), am I pricing a _company-managed-user-license_ or a _companywide-license-for-all-users_?  In my example, should assume that the company will pay $4.99 for each user they want to access the software?  Or, should I charge a larger fee, assuming that all users at the company will have access to the software.

To put it into programming terms, does organizational licensing effect the customers price using a O(1) function or a O(n) function?

Thanks and Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad7be45-44d1-9ebe-4731-bdc64abb2127
* Version Independent ID: 9b9197c3-1301-3405-b700-36fa3698cca9
* Content: [Organizational licensing options - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/organizational-licensing)
* Content Source: [windows-apps-src/publish/organizational-licensing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/organizational-licensing.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
