### ISSUE TITLE
Windows 8.1 reference

### ISSUE THREAD

**Issue by SimonBiggs** [MicrosoftDocs/windows-uwp#2920]
At the following link:

https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development#developer-mode-features

The following is written:

> Developer Mode replaces the Windows 8.1 requirements for a developer license.

Is there still supposed to be references to Windows 8.1 here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb82418-b583-7023-f2e3-c3dca7d3245c
* Version Independent ID: 0a65ac0a-9884-52a8-6485-c2825b1fb4d9
* Content: [Enable your device for development - Windows applications](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development)
* Content Source: [hub/apps/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by QuinnRadich** [comment]
This is intended, yes. In case developers have experience only with previous versions of Windows or are operating on outdated information, this page needs to emphasize that this is a change from previous behavior.
