### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2921]
## Broken Link

The [PWA Features](http://stage.docs.phonegap.com/tutorials/stockpile/911-pwa-features/) link in the [Adobe PhoneGap section](https://docs.microsoft.com/en-us/windows/android/pwa#adobe-phonegap) in the [document](https://docs.microsoft.com/en-us/windows/android/pwa) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0871c51-df56-1e27-b56b-cbc902bdc5ae
* Version Independent ID: c108f0e5-dd13-c10b-8376-6289b0e64519
* Content: [PWA approach to Android development on Windows](https://docs.microsoft.com/en-us/windows/android/pwa)
* Content Source: [hub/android/pwa.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/pwa.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Interesting! Thanks for filing this issue @sercansebetci -- it looks like Adobe is ending their support of PhoneGap: https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c

I'll update this section to reflect the change. Thanks again!

**Comment by mattwojo** [comment]
Just filed a PR to reflect the discontinuation of PhoneGap support in this doc: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1248

**Comment by ghost** [comment]
I opened a new thread on this [issue](https://github.com/MicrosoftDocs/windows-uwp/issues/2922). Thank you for your interest.
