### ISSUE TITLE
About The Reference To PhoneGap

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2922]
## About The Reference To [PhoneGap](https://phonegap.com/)

PhoneGap announced on August 11, 2020 that development for PhoneGap and PhoneGap Build products will end on October 1, 2020. 

## Alternatives

PhoneGap offers other alternatives for applications that carry the PWA feature: 

- [Monaca](https://monaca.io/)
- [Framework7](https://framework7.io/)
- [NativeScript](https://nativescript.org/)
-  [Ionic Capacitor](https://capacitorjs.com/)
-  [Progressive Web Apps](https://web.dev/progressive-web-apps/)

## Conclusion and Recommendations

I find it inconvenient to be cited in the document as PhoneGap has completed its lifetime. Alternatives to PhoneGap can be evaluated.

## Additional Resources

* [Update for Customers Using PhoneGap and PhoneGap Build](https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c)
* [End of Service for Adobe PhoneGap](https://helpx.adobe.com/experience-manager/kb/adobe-phonegap-end-of-service.html#:~:text=Adobe%20is%20discontinuing%20PhoneGap%2C%20PhoneGap,blog%20post%20for%20more%20information.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0871c51-df56-1e27-b56b-cbc902bdc5ae
* Version Independent ID: c108f0e5-dd13-c10b-8376-6289b0e64519
* Content: [PWA approach to Android development on Windows](https://docs.microsoft.com/en-us/windows/android/pwa)
* Content Source: [hub/android/pwa.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/pwa.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Yes - I just read the blog announcement an updated to reflect the support being dropped. Thanks again. 
https://github.com/MicrosoftDocs/windows-uwp/commit/99f5544d9642c87a16e3bd21f76c2fcbc97c20d2
