### ISSUE TITLE
"If the ANSI code page is configured for UTF-8, -A APIs operate in UTF-8" - far too sweeping (i.e., wrong)

### ISSUE THREAD

**Issue by david-bakin** [MicrosoftDocs/windows-uwp#2923]
This statement is (currently, Windows 10 10.0.19042.746) _far_ too inclusive, and thus, it is wrong.

Just to name one API (set) that does _not_ "operate in UTF-8": `Find{First,Next}FileA`.  It returns file name (components) in some _non_ UTF-8 encoding _even if_ the process code pages is set to UTF-8 as described on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a28119a-77f2-160c-a4f1-f90ef9153423
* Version Independent ID: 28b24e82-f0ef-cceb-2136-f8dbfabfcadc
* Content: [Use the Windows UTF-8 code page - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page)
* Content Source: [windows-apps-src/design/globalizing/use-utf8-code-page.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/use-utf8-code-page.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @david-bakin - topic has been revised to be less absolute.
