### ISSUE TITLE
SPX media tool?

### ISSUE THREAD

**Issue by pb5050** [MicrosoftDocs/windows-uwp#2925]
[Enter feedback here]

is there not a way to download windows media for refreshing windows with SPX???  SUrface pro X 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c920a34-495e-ae99-365a-f6bc0afa2052
* Version Independent ID: 1e3c088d-3ca5-7f26-b1f6-23d9c97918e7
* Content: [Windows 10 on ARM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm)
* Content Source: [windows-apps-src/porting/apps-on-arm.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by pb5050** [comment]
I CANT find anything just a vhdx file i have no idea use3 this

**Comment by pb5050** [comment]
i mean there is no iso....
