### ISSUE TITLE
refresh_token missing from initial access token generation response

### ISSUE THREAD

**Issue by DonkeyOatie** [MicrosoftDocs/windows-uwp#2927]
We are attempting to use the purchases and collections API.  We are generating our access token (server side) as documented [here](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow#service-to-service-access-token-response) using the `oauth2/tokens` endpoint with the purchases audience URI.

We can generate the first access token and the response is as documented.  However, further down the page there is a link to the documentation for refreshing the access token, which goes to [here](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-oauth-code#refreshing-the-access-tokens).  This requires us to already have a `refresh_token`, but there is not one on the initial response, which looks as follows

```
{
  "token_type": "Bearer",
  "expires_in": "3599",
  "ext_expires_in": "3599",
  "expires_on": "1611571126",
  "not_before": "1611567226",
  "resource": "https://onestore.microsoft.com/b2b/keys/create/purchase",
  "access_token": "REDACTED"
}
```

As a work around, I am generating a new access token each time the previous one expires.  I have the following questions

1.  Should there be a `refresh_token` on the initial response?
2. Is there any reason not to generate a totally new access token each time, and ignore the idea of a refresh token completely?
3. Am I missing a step somewhere that would give me a `refresh_token`?

**Comment by CameronGoodwin** [comment]
I think that you might be looking at the wrong article.  The one you linked to is for OAuth 2.0 which would be web login access tokens where the user signs in with their Microsoft Account to your web service.  This is different than the Access Tokens for the purchase and collections API's (aka UserStoreID, UserCollectionsID, UserPurchaseID).

The document and endpoint to refresh those tokens is actually located here:
https://docs.microsoft.com/en-us/windows/uwp/monetize/renew-a-windows-store-id-key

**Comment by DonkeyOatie** [comment]
HI Cameron, thanks for the super quick response!

We are currently on step 3 of this page 

https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-3

In the final paragraph of the section titled "Create the tokens" you have the following sentence 

> After your access token expires, you can refresh it by following the instructions here

The here link points to this page https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-oauth-code#refreshing-the-access-tokens which is where it talks about `refresh_tokens`.  

I understand once we get to the next step (the b2b key) this will have to be renewed every 90 days (which I believe is what the link your provided is pointing to).  We are not at that step yet unfortunately.

**Comment by CameronGoodwin** [comment]
Ok! Thanks for pointing at the link there, that is the problem.   The link is wrong.  The article that I linked above is the correct one for these Collections / Purchase service to service auth tokens.  I will ask them to update the documentation to fix this link.  

So your refresh request should actually look like this for Collections:

```
POST https://collections.mp.microsoft.com/v8.0/b2b/keys/renew HTTP/1.1
Content-Length: 2774
Content-Type: application/json
Host: collections.mp.microsoft.com

{
    "serviceTicket": "eyJ0eXAiOiJKV1QiLCJhb...",
    "Key": "eyJ0eXAiOiJKV1QiLCJhbG..."
}
```

**Comment by DonkeyOatie** [comment]
Thanks for confirming the docs are incorrect, that’s helpful

It’s useful to know how to renew the store id keys for the collections and purchase endpoints

However, my question is about how to renew the Azure AD access token, is there an endpoint for this, or should we just call the initial endpoint again?

**Comment by CameronGoodwin** [comment]
Oh thanks for the clarification. For your service token (The one generated against &resource=https://onestore.microsoft.com) just create a new one with a new call.  :)

**Comment by DonkeyOatie** [comment]
awesome, thanks for all the help @CameronGoodwin.  Glad we got to the bottom of this.  I am happy that my issue is solved but I won't close the issue incase you want to use it to track the document changes required.

Thanks again,  Nathan

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
