### ISSUE TITLE
Nuget package needed

### ISSUE THREAD

**Issue by rcohn** [MicrosoftDocs/windows-uwp#2928]
To get this program to build and run, had to install the Nuget package: Microsoft.Windows.CppWinRT, v2.0.210122.3

So you might want to add something about the C++/WinRT support needed.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rcohn, and thanks for filing this issue. To confirm, I just created a new **Windows Console Application (C++/WinRT)** project, as per the topic, and the version that you mention of that NuGet package *is* added automatically. It wouldn't be added for a non-C++/WinRT project type, for example the regular Console App. And the second Note in the topic links to the info for setting up Visual Studio for C++/WinRT development.

Everything looks good, so I'll close the issue, but you can still reply in case I'm overlooking something.

Thanks!
Steve
