### ISSUE TITLE
Update for .net 5

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/windows-uwp#2938]
Please acknowledge the existence of .net 5 and clarify then if it should be used in stead of .net core 3.1.

Update: A giant warning that this does not work with .net 5 and is no longer recommended would maybe be better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7ec471-9257-39ba-173b-eb7973f4c360
* Version Independent ID: 3e07d5f0-8b19-2ef4-dc2a-48659f42c12e
* Content: [Host a custom WinRT XAML control in a WPF app using XAML Islands - Windows applications](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I have added a note to the overview section of this article (and the other XAML Island articles that cover .NET scenarios) to explicitly clarify that .NET 5 is not yet supported for XAML Islands. This doc update should be live in the next few hours.
