### ISSUE TITLE
Help with above code

### ISSUE THREAD

**Issue by MattSA-01** [MicrosoftDocs/windows-uwp#2941]
[Enter feedback here]

I am having difficulties with above code. The following is my code in a C++/CX Blank App project:

`void CS_C__CX_D2D_SurfaceImageSource::MainPage::Button_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e)
{
	SurfaceImageSource^ surfaceImageSource = ref new SurfaceImageSource(400, 300);
	MyDxImage->Source = surfaceImageSource;
	// The following is taken from:https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop
	ComPtr<ISurfaceImageSourceNativeWithD2D> m_sisNativeWithD2D;
	IInspectable* sisInspectable = (IInspectable*) reinterpret_cast<IInspectable*>(surfaceImageSource);
	sisInspectable->QueryInterface(__uuidof(ISurfaceImageSourceNativeWithD2D), (void**)&m_sisNativeWithD2D);
	// Creates a device that represents a virtual adapter; it is used to create resources.
	ComPtr<ID3D11Device> m_d3dDevice;
	// The ID3D11DeviceContext represents a device context which generates rendering commands.
	ComPtr<ID3D11DeviceContext> m_d3dContext;
	// The ID2D1Device represents a resource domain whose objects and device contexts can be used together. 
	ComPtr<ID2D1Device> m_d2dDevice;
	UINT creationFlags = D3D11_CREATE_DEVICE_BGRA_SUPPORT;
	D3D_FEATURE_LEVEL featureLevels[] = {
		D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_1, D3D_FEATURE_LEVEL_10_0,
		D3D_FEATURE_LEVEL_9_3, D3D_FEATURE_LEVEL_9_2, D3D_FEATURE_LEVEL_9_1 };
	D3D_FEATURE_LEVEL featureLevel; //= D3D_FEATURE_LEVEL_11_1;
	// The following creates the DXGI device
	D3D11CreateDevice(NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, creationFlags, featureLevels, ARRAYSIZE(featureLevels),
		D3D11_SDK_VERSION, &m_d3dDevice, NULL, &m_d3dContext);
	// An IDXGIDevice interface implements a derived class for DXGI objects that produce image data.
	ComPtr<IDXGIDevice> dxgiDevice;
	m_d3dDevice.As(&dxgiDevice);
	// A multithread interface accesses multithread settings and can obly be used if the thread-safe layer is turned on.
	ComPtr<ID3D10Multithread> d3dMultiThread;
	m_d3dDevice->QueryInterface(__uuidof(ID3D10Multithread), (void**)&d3dMultiThread);
	d3dMultiThread->SetMultithreadProtected(TRUE);
	// THE TUTORIAL INCLUDES THE FOLLOWING STATEMENT. HOWEVER, m_dxgiDevice IS NOT DECLARED ANYWHERE IN THE //TUTORIAL.:
	// D2D1CreateDevice(m_dxgiDevice.Get(), NULL, &m_d2dDevice.
	// IT SEEMED LOGICAL TO REPLACE WITH THE IDXGIDEVICE ABOVE:
	D2D1CreateDevice(dxgiDevice.Get(), NULL, &m_d2dDevice);
	m_sisNativeWithD2D->SetDevice(m_d2dDevice.Get());

	// Represents a set of state and command bufgfers that are used to render to a target.
	ComPtr<ID2D1DeviceContext> drawingContext;

	// THIS IS CREATED FOR THE FOLLOWING BEGINDRAW() METHOD.
	RECT updateRect;
	updateRect.left = 0;
	updateRect.top = 0;
	updateRect.right = 400;
	updateRect.bottom = 400;
	ComPtr<IDXGISurface> surface;
	POINT offset;

	// AT THIS POINT THE CODE IN THE TUTORIAL USES AN m_sisNative OBJECT THAT WAS NOT DECLARED ANYWHERE IN
	// THE TUTORIAL. IT SEEMED TO MAKE SENSE TO USE THE m_sisNativeWithD2D OBJECT. HOWEVER, THE BEGINDRAW()
	// DOCUMENTATION FOR THIS TYPE HAS A DIFFERENT SIGNATURE THAN WHAT IS REVEALED WHEN HOBVERING OVER 
        // THE BEGINDRAW() METHOD BELOW. I TRIED TO PROVIDE THE FOLLOWING FUNCTION CALL WITH THE CORRECT 
        // ARGUMENTS, BUT CANT BE SURE.
	m_sisNativeWithD2D->BeginDraw(updateRect, __uuidof(drawingContext), &drawingContext, &offset);
	drawingContext->Clear(D2D1::ColorF(D2D1::ColorF::White));
	m_sisNativeWithD2D->EndDraw();
	ImageBrush^ brush = ref new ImageBrush();
	brush->ImageSource = surfaceImageSource;
	// WHEN I COMPILE AND RUN I RECIEVE AN EXCEOPTION I THINK COMES FROM THE drawingContext->Clear STATEMENT 
        // ABOVE. THE ERROR OUTPUT IS AS FOLLOWS:
	// Exception thrown : read access violation. this was nullptr.
	// IN THE d2d1.h HEADER FILE.
}`

I do not know how to fix the undeclared items (m_dxgiDevice and m_sisNative). I replaced these with the dxgiDevice and m_sisNativeWithD2D objects that were declared in the tutorial. I also do not know if the arguments in the BeginDraw() method are right. I also do not know how to fix the exception thrown by the Clear() call in the d2d1.h header file. 

Can someone please help me clear up this code? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b263a91c-cfc3-2457-196f-ab9c74b14a5f
* Version Independent ID: bc2cd244-bd4d-b294-c787-12fb2a2ad373
* Content: [DirectX and XAML interop - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop#feedback)
* Content Source: [windows-apps-src/gaming/directx-and-xaml-interop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/directx-and-xaml-interop.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @MattSA-01, and thanks for filing this issue. It looks like there are a few issues with the example code in this topic.

As you say, some variables are used without being explained. Also, the code is in C++/CX, and that has now been superseded by [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/).

I think that I should port the code in this topic to C++/WinRT, and try to fill in any pieces that are currently missing from it. So my priority will be to try and arrive at a C++/WinRT version of the code that's easier to follow, and contains all the pieces needed to make it work. After that, for folks still using C++/CX, it might then be easier to use the updated code to fill in the pieces in the C++/CX version that are not so clear.

-Steve

**Comment by MattSA-01** [comment]
That would be great. I was able to get a working version up and running in C++/CX. But I do know that C++/RT is the current implementation of C++. I know C++/CX is UWP and for my purposes this will work for now. I do not think I will have much of a problem porting the code myself. But if you would like to port and post for others , it is probably a good idea.

**Comment by stevewhims** [comment]
Sounds good. I've recorded a work item in my backlog for this, and I'll get to it as soon as I can (I need to liaise with the feature team, too, about exactly how they'd like to handle the changes). So I'll close this issue so that we don't track it twice. My work item has a link to this item so that I can return here and update it when I'm done with the work.

Thanks again!
Steve

**Comment by stevewhims** [comment]
Hi, @MattSA-01, this topic is now updated (sorry it's taken so long for it to rise to the top of my backlog). All the code examples are now in C++/WinRT, and they're self-contained and complete (meaning that all the variables used are declared and defined).

If you do still want to do this with C++/CX then it should be straightforward (now that the code examples are self-contained and complete) to port the C++/WinRT back to C++/CX. But if I were you, I'd first follow along with the code examples, as shown, in a C++/WinRT project. Once you're familiar with them, and you can see that they build and run, it should be easier then to port them back to C++/CX.

I've also added links to the sample apps that use each of the three methods described in the topic.,

Thanks again!
Steve

**Comment by MattSA-01** [comment]
Thanks for the info. I will most certainly check it out.

Matt Armshaw

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
