### ISSUE TITLE
Runtime pin muxing documentation still outdated

### ISSUE THREAD

**Issue by Googulator** [MicrosoftDocs/windows-uwp#2942]
Since ACPI 6.2, an equivalent of the vendor-specific MsftFunctionConfig() macro has been added, under the name PinFunction(), with an almost identical API (an extra optional parameter was added before VendorData). From my testing, this new standard macro seems to be supported and treated as an equivalent of MsftFunctionConfig in recent Insider builds.

It would be great to have this documented, with information on what minimal Windows version is the new macro available.

A previous issue (#1751) with the same content was closed saying that the "pull requests mentioned" in that issue fixed this. No pull requests were ever mentioned in that issue's thread, and the documentation in question is still missing references to the standard way of managing pin muxing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a2e04a4-8907-8373-6d08-d7bf0db92e44
* Version Independent ID: 1505bdc2-54ab-1650-ca96-c1df5b482d18
* Content: [Enable usermode access to GPIO, I2C, and SPI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-usermode-access#feedback)
* Content Source: [windows-apps-src/devices-sensors/enable-usermode-access.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/enable-usermode-access.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
