### ISSUE TITLE
Missing Closing Tag

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/windows-uwp#2944]
In the example code block of the _Adjust the UI layout_ section, the final </VisualStateManager.VisualStatedGroups> is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed62e90-9a85-e295-69ac-7af08123e024
* Version Independent ID: b740841d-6530-d774-0f68-dcd356f9adb5
* Content: [Create a 'Hello, World!' app using C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cppwinrt)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cppwinrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cppwinrt.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This issue has been fixed for some time, it seems. Apologies on the late response to this issue, but the recognized problem has been solved. Thanks for submitting this.
