### ISSUE TITLE
DualApiPartition attribute is unreliable

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/windows-uwp#2947]
This page describes using the DualApiPartition as an indicator of WinRT APIs that work in an unpackaged Desktop app. But we expect that that attribute has both false positives and false negatives. We shouldn't recommend using that as a guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909f1773-1e55-eb5a-206f-b32ce6f9dd9d
* Version Independent ID: 24ea5c87-1c21-884d-f05f-833bbd894ba9
* Content: [Windows Runtime APIs available to a packaged desktop app (Desktop Bridge) - Windows applications](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The old guidance about DualApiPartition has been removed from this article. It has been revised to provide an up-to-date guidance about WinRT APIs that aren't supported in desktop apps
