### ISSUE TITLE
Update to ListDetailsView once Windows Community Toolkit 7.0 ships

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#2949]
Once we ship our upcoming Windows Community Toolkit 7.0 release in the next few weeks, we'll need to update the page to the new naming schema of ListDetailsView, see Toolkit issue [here](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3606).

Wanted to file this now for tracking while I was here. Not sure who owns some of the auxiliary content pointed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd4b0df-4564-2c87-4ed5-ea40bde54918
* Version Independent ID: f8caabee-0fa1-e02b-11b0-79d0cfd8b973
* Content: [Master/details - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/master-details)
* Content Source: [windows-apps-src/design/controls-and-patterns/master-details.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/master-details.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks @michael-hawker, this update has been made.

**Comment by michael-hawker** [comment]
Thanks @jwmsft, looks like a couple of the samples still use the old name linked to below, so I'll open issues on those repos about updating names.
