### ISSUE TITLE
Missing example content

### ISSUE THREAD

**Issue by drpritch** [MicrosoftDocs/windows-uwp#2954]
In this section:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/flipview#specify-the-look-of-the-items

it concludes with the text `Here's what the layout defined by the data template looks like.`

However, the visual depiction is missing, and instead there's just the placeholder text `Flip view data template.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba6bc61-ac42-754f-7410-56e4a0c64a8e
* Version Independent ID: 53e11f76-e089-090e-1a8c-b53c6c9c9a1d
* Content: [Guidelines for flip view controls - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/flipview)
* Content Source: [windows-apps-src/design/controls-and-patterns/flipview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/flipview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The missing image has been added.
