### ISSUE TITLE
Setting the theme of the application during execution just doesn't affect a page

### ISSUE THREAD

**Issue by srjheam** [MicrosoftDocs/windows-uwp#2957]
I have the following code to changing my theme (the same used by [Xaml-Controls-Gallery](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/Helper/ThemeHelper.cs#L54-L60)):
```c-sharp
if (Window.Current.Content is FrameworkElement rootElement)
{
    rootElement.RequestedTheme = value;
}
```

But changing the theme like this or directly in the page's constructor (`this.RequestedTheme = desiredTheme;`) just doesn't affect the theme of that specific page, that page follows the `App.Current.RequestedTheme` (which can only be changed when opening the app).

![XiQjUSjtXD](https://user-images.githubusercontent.com/58143641/107167313-5a3f2d00-6997-11eb-98c1-4827811df2cd.gif)

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. Unfortunately, the scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there.
