### ISSUE TITLE
E877  does not match the shown Glyph?

### ISSUE THREAD

**Issue by groovykool** [MicrosoftDocs/windows-uwp#2959]
E877  does not match the shown Glyph?

The Glyph for E877 shown in a UWP App does not match the Glyph shown on this page?
The Glyph shown in UWP looks like a smartphone with wavy lines on each side.

Which is correct?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60025def-004a-97b9-be6e-a2678e0b4461
* Version Independent ID: 51e386c5-e9cf-f900-ba27-1479709f8186
* Content: [Segoe MDL2 Assets icons - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font?source=docs)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
This page has been updated based on the latest version of Segoe MDL2 Assets, and the images match now. Thanks for logging this issue.
