### ISSUE TITLE
Can't follow this procedure

### ISSUE THREAD

**Issue by StanLackey** [MicrosoftDocs/windows-uwp#2960]
I'm trying to add the   (open angle bracket) XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /    (close angle bracket)
line but the directions don't say which file.  I tried several candidates but I only get errors.

Trying to use Visual Studio to create apps is the most exasperating thing I have ever done.  I tried using MFC, UPF and now WinUI and all I can find are tutorials that don't work, books that are hopelessly out of date, and grossly incomplete documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532b04ea-7927-f97a-1121-b8feac6df957
* Version Independent ID: e3cf5c39-5efa-aaea-3ac3-8c4ffa50e960
* Content: [Getting started with the Windows UI library - WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)
* Content Source: [hub/apps/winui/winui2/getting-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui2/getting-started.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
See Step 4 (the parent step to the instruction you reference): 

Add the Windows UI (WinUI) Theme Resources to your **App.xaml** resources. There are two ways to do this, depending on whether you have additional application resources.

**Comment by StanLackey** [comment]
I was trying to do #4.  The instructions do not say what file to add it into, that is, where Application.Resources resides - should I add something somewhere, or do I edit an existing file.  I tried adding it in to App.xaml in various ways and whatever I tried always threw an error.
Note: the Microsoft.UI.Xaml was the only one that came up, Microsoft.UI.Xaml.Core.Direct did not appear in the list.


________________________________

**Comment by Karl-Bridge-Microsoft** [comment]
Step 4 specifies to add the code to the **App.xaml** file, as I highlighted in bold (using one of the two ways listed). 

The Microsoft.UI.Xaml.Core.Direct package doesn't appear if you don't have the "Show pre-releases" checkbox checked. See step 3. I don't believe this is necessary, but won't hurt anything.

**Comment by StanLackey** [comment]
Here's the code if that snippet is just added:

<Application
    x:Class="App3.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App3">

</Application>

<Application>
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
</Application>


Here are the errors:

[cid:7a15d60e-0246-4f6a-8e1e-31670ce1a6fb]


If I try something like this:

<Application
    x:Class="App3.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App3">

    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>

</Application>

it still gets this error:

[cid:9cd89064-4956-4216-abf6-d86a22888b22]

________________________________

**Comment by Karl-Bridge-Microsoft** [comment]
You can't have duplicate <Application...> elements, so your second snippet is the correct way. I'm not sure why there is a xmlns:local="using:App3" declaration. Did you add that? Try removing that.

I think this topic is assuming some basic familiarity with XAML and Windows app development. Perhaps it could do with some clarifications here and there. I'll see what I can do to improve that experience.

If you have more feedback on how the docs can be improved, please open issues or PRs for those.

Otherwise, try stackoverflow for help and support with your specific errors and general development issues/questions. 

Thanks

**Comment by StanLackey** [comment]
The wizard inserted the xmlns:local="using:App3" declaration.  The project built OK with it in, prior to me inserting the  <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />  stuff.

________________________________

**Comment by StanLackey** [comment]
Now I'm getting errors that it can't open the app store.  Why would it try to open the app store ?!  I do not want to open the app store, I want to write a stand-alone program on my PC.

This is hopeless.

________________________________
