### ISSUE TITLE
need to reopen #2960

### ISSUE THREAD

**Issue by StanLackey** [MicrosoftDocs/windows-uwp#2963]
The reply does not solve the problem.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @StanLackey - I updated the steps in the topic to be more clear. If you have suggestions on how the topic can be improved further, please open an issue or PR with those suggestions.

As you don't have doc updates, but instead require customer support, I suggest https://stackoverflow.com/questions as a forum to get answers to your general UWP development questions. You can also try https://docs.microsoft.com/en-us/answers/index.html. With both, you can provide examples of your code and dev environment configuration to get help.
