### ISSUE TITLE
renames from .doc to .docx won't open in Word

### ISSUE THREAD

**Issue by Singletonian** [MicrosoftDocs/windows-uwp#2973]
I renamed an old folder of documents from a while back; the rename worked but the files (from .doc to .docx) will not open in Word.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
Please file the issue at with our template and more detailed repro steps. I also don’t think you and rename a doc file to a docx  they are actually different file types. 

https://github.com/microsoft/PowerToys/issues/new?assignees=&labels=Issue-Bug%2CTriage-Needed&template=bug_report.md&title=

**Comment by mattwojo** [comment]
Agree - I believe that just renaming doc to docx can cause some unwelcome issues. There's a thread about it here: https://community.spiceworks.com/topic/288515-mass-convert-docx-to-doc

Closing this is it's not related to a PowerToys docs update.
