### ISSUE TITLE
Null value is not valid for subType parameter

### ISSUE THREAD

**Issue by datvm** [MicrosoftDocs/windows-uwp#2974]
Both on this page and the [API ref](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.codecquery.findallasync?view=winrt-19041#Windows_Media_Core_CodecQuery_FindAllAsync_Windows_Media_Core_CodecKind_Windows_Media_Core_CodecCategory_System_String_) say that

> Specify empty string or null for the subtype value to return codecs for all subtypes.

> To specify that all codecs of the specified kind and category should be returned, regardless of what media subtypes are supported, specify an empty string ("") or null for this parameter.

This is wrong. If I put a `null` there, I receive an exception:

> System.ArgumentNullException: 'Value cannot be null.'

It can be fixed by simply changing it to empty string (""). Not sure if I need to submit this issue on that doc page as well.

Off-topic, but [I am having a crash following this article](https://stackoverflow.com/questions/66253538/codecquery-findallasync-crashes-through-try-catch-when-querying-audio-codecs-wit), if you can tell me who I should get help from, would be very appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b06da90-d230-5445-9347-c7c8c5faa71c
* Version Independent ID: ba46d16d-3528-25d9-52d3-4a32f4158637
* Content: [Query for installed codecs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/codec-query)
* Content Source: [windows-apps-src/audio-video-camera/codec-query.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/codec-query.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hi! Thanks a lot for pointing out the error in the docs about null value being unsupported. We've updated the docs to state that only empty string will return all of the codecs (it should be live on the site within ~24 hours). As to your ongoing issue, I just created an empty app with the sample code in the page and I am unable to repro your issue. Have you tried testing the sample code in just an empty test app? It might help to determine if there's a problem with your tools or OS installation or if there's some other aspect of your app that is causing the issue. The fact that the error is "not implemented" is stranger to me than if it returned some more obscure error. 

The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks again for helping to improve our documentation!
