### ISSUE TITLE
Microsoft don't follow their own advice?

### ISSUE THREAD

**Issue by cornelius-dol** [MicrosoftDocs/windows-uwp#2977]
The UWP docs state, explicitly, "Do make it obvious when your window is active or inactive." Yet not one single UWP in Windows 10 shows the active title bar background color as configured in Settings. Even when "Personalization > Colors > Show Accent Color on ... > Title bars and window borders" is set.

**Comment by hkhmsft** [comment]
Hi @lawrence-dol , sorry that you're experiencing this. Unfortunately, our docs team here doesn't have the ability to resolve your current issue. You can raise this product issue over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) and gauge the community of experts and Microsoft engineers. Hope you can get an answer there. Thanks.
