### ISSUE TITLE
Why is Microsoft responding to user reviews for my app?

### ISSUE THREAD

**Issue by kinex** [MicrosoftDocs/windows-uwp#2980]
While checking users reviews for my app I noticed by accident a reply who was not written by me. The reply was written in Dutch which I cannot even speak so I am 100% sure I have not written it.  

Here is the exact reply:
_Hallo [user name], we stellen uw feedback op prijs. De geweldige manier om de app / game te verbeteren is om contact op te nemen met de ontwikkelaar die uw feedback kan gebruiken voor verbetering. Bedankt._

So there is nothing bad in the reply. But the problem is that from my understanding I should be the only person who can reply to user reviews for my app.

I am raising the issue here because Microsoft Developer Support failed to resolve the issue. They claim the reply has been written from my account which is impossible unless someone from Microsoft accesses my account which would be even more serious.

So if this normal (which I doubt), you should document it here. Otherwise, I request you to tell me full details why this happened, who did it and how do you prevent this from happening in future? I am quite sure someone from Microsoft Customer support has exceeded his/her rights. You should find that person and tell him/her stop doing that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179cbc73-e5ec-0ecd-b3d8-968ee593905c
* Version Independent ID: 4b0e61f6-8b6a-fc8f-91bd-792ab97fef53
* Content: [Respond to customer reviews - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/respond-to-customer-reviews)
* Content Source: [windows-apps-src/publish/respond-to-customer-reviews.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/respond-to-customer-reviews.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi @kinex , sorry that you're experiencing this. Unfortunately, our docs team here doesn't have the ability to resolve your current issue. You can raise this issue over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) and gauge both the community and Microsoft engineers. Hope you can get an answer there. Thanks.
