### ISSUE TITLE
Undefined Dispose()

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/windows-uwp#2984]
Dispose() in OnMediaStreamSourceSampleRequested() is undefined.
I suspect it should be Cleanup().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971295ef-cd07-fd9c-e5df-2c6e0e4c25fc
* Version Independent ID: c1d6f2f7-f971-3bd4-8fb7-f30d113a752f
* Content: [Screen capture to video - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture-video)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture-video.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture-video.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for letting us know about this error in the code. Dispose was defined in the sample project as calling Stop and then Cleanup. Rather than add this helper method into the article, I replaced the call to Dispose with calls to Stop and Cleanup.
