### ISSUE TITLE
Typo in FancyZones

### ISSUE THREAD

**Issue by mechagumi** [MicrosoftDocs/windows-uwp#2985]
Below, **FancyZones** is the correct word.

- Fブランコ Yzones
- Fて Yzones
- F・ Yzones

![image](https://user-images.githubusercontent.com/30904774/109391364-056d5180-795a-11eb-8e13-27f343cc0664.png)
![image](https://user-images.githubusercontent.com/30904774/109391406-3e0d2b00-795a-11eb-8164-5835f6951efb.png)
![image](https://user-images.githubusercontent.com/30904774/109391449-790f5e80-795a-11eb-87dc-c7910fa47b5b.png)
![image](https://user-images.githubusercontent.com/30904774/109391477-a6f4a300-795a-11eb-9439-e088268c20bb.png)

Below, **FancyZone** is the correct word.

- F・ yzone
- Fare yzone

![image](https://user-images.githubusercontent.com/30904774/109391378-22098980-795a-11eb-8cdf-7a34e98398b3.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [Windows 10 用の Powertoy Fブランコ Yzones ユーティリティ](https://docs.microsoft.com/ja-jp/windows/powertoys/fancyzones#feedback)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mattwojo** [comment]
Thank you @mechagumi. I just filed a pull request to fix this issue. Waiting for the translation team to merge.

**Comment by mattwojo** [comment]
Merged live: https://github.com/MicrosoftDocs/windows-uwp.ja-jp/pull/151

Thanks again. Closing.
