### ISSUE TITLE
Property Misspelling 

### ISSUE THREAD

**Issue by wdupree** [MicrosoftDocs/windows-uwp#2986]
// Do not enable the CompletionGroup until after all downloads are created.
downloader.CompletinGroup.Enable();

should be:

// Do not enable the CompletionGroup until after all downloads are created.
downloader.CompletionGroup.Enable();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be69d7e-349a-eddc-6cfa-115c2714bc3e
* Version Independent ID: 71ba81db-c429-133a-50b3-060fab53c2e6
* Content: [Background transfers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/networking/background-transfers)
* Content Source: [windows-apps-src/networking/background-transfers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/background-transfers.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, and thanks for filing this issue. The fix is now live.

Thanks!
Steve
