### ISSUE TITLE
Provide a way to implement the Microsoft Store Services api consumption using MSAL library

### ISSUE THREAD

**Issue by MarcoEnxuto** [MicrosoftDocs/windows-uwp#2987]
This explanation provides only one way to create a client to invoke MSS API.
It would be interesting to have a how to based on this article: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-call-api?tabs=aspnetcore.

To create tokens, this uses the v1 endpoint. Also, it points to an older page of AAD.

After some digging, i found out the resource parameter is replaced by scope, in a v2.0 Oauth specification. So, to acquire the token i need to pass the following resource. Scope=https://onestore.microsoft.com/.default. This is made using the raw request format using http. Once i get the access_token, i pass it back to the client. You should update this page to use the most recent implementation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#access-tokens)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by MarcoEnxuto** [comment]
By using dependency injection, i found a way to invoke Microsoft Identity in order to obtain a token to pass to the client.
Tokens must have the scope assigned with audience URI pretended.
Via DI, you can GetAccessTokenForAppAsync(scope,tenant) using the interface TokenAcquisition.

**Comment by MarcoEnxuto** [comment]
Hi guys, another issue arised. This endpoint https://collections.mp.microsoft.com/v7.0/beneficiaries/me/keys, that is used by the SDK to generate the Store Id Key requires the appdacr with value =1. So, this means i have to use a secret prior to this call, and then pass it to the client. I would like to use certificates because of the obvious reasons.

**Comment by MarcoEnxuto** [comment]
Hi guys, another issue arised. This endpoint https://collections.mp.microsoft.com/v7.0/beneficiaries/me/keys, that is used by the SDK to generate the Store Id Key requires the appdacr with value =1. So, this means i have to use a secret prior to this call, and then pass it to the client. I would like to use certificates because of the obvious reasons. This happens because the collections endpoint requires appidacr parameter, which is used in v1.0 tokens. More info here: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by MarcoEnxuto** [comment]
Mr. @hickeys, are aware of this issue? Thank you.

**Comment by MarcoEnxuto** [comment]
Hi there, now news right?

**Comment by MarcoEnxuto** [comment]
Hi @stevewhims, does anyone looking into this? Thanks.

**Comment by stevewhims** [comment]
Hi, @MarcoEnxuto, and I apologize that this issues hasn't yet been acknowledged on our side. I've gone ahead just now and sent an internal email to @hickeys just to raise awareness about this issue.

Thanks for your patience!
Steve

**Comment by MarcoEnxuto** [comment]
Hi @stevewhims, any update on this?

**Comment by stevewhims** [comment]
Hi, @MarcoEnxuto. I've sent additional internal email to the assignee of this issue.

Thanks for your patience!

**Comment by hickeys** [comment]
Hi @MarcoEnxuto Sorry about the delay in responding to this issue. Reviewing the history here, it seems like there are two issues. 

First, you'd like a new how-to article based on [this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-call-api?tabs=aspnetcore). Can you elaborate a little? If the page you referenced already shows the techniques you're interested in, what could we add with a new how-to article? What sort of content would you like to see in this article?

Second, you've found a bug in the code snippet related to changes in the oauth v2 spec. It looks like you've proposed a fix already, thank you!

There also might be a third issue regarding the keys API. Can you clarify?

Thanks,
Shawn

**Comment by MarcoEnxuto** [comment]
Hi @hickeys thanks for the reply. Unfortunately, github doesn't notify me on replies. I guess it was why you didn't reply on short notice.

So, regarding my question, i found out the implementation. And it's done on my side.
My only concern now is regarding this comment. 
https://github.com/MicrosoftDocs/windows-uwp/issues/2987#issuecomment-792050424
I would like to use certificates instead of secrets regarding these requests... but i guess is a limitation of the endpoint. https://collections.mp.microsoft.com/v7.0/beneficiaries/me/keys, 


Also, today, i went to the docs to check for some properties, and i found that someone implemented a library for Microsoft Store Services. Good Job implementing this @CameronGoodwin.
Either way, i already implemented a library for myself 6 months ago which is identical to this one.

**Comment by CameronGoodwin** [comment]
Thanks @MarcoEnxuto .  I have some updates for the library in a PR right now.  I was looking at using the MSAL library for the library during this update, but chose not to and instead just update the one call to get the Access Tokens to AAD 2.0 model so it would be more readable and portable to other languages if needed.

**Comment by MarcoEnxuto** [comment]
You're welcome @CameronGoodwin .
I'll transition to your library as soon i have both issues resolved.
Using MSAL, and using certificates instead of secrets.
Thank you all.

**Comment by MarcoEnxuto** [comment]
Hi @hickeys, it's been 4 months since my last reply. Got any news?

**Comment by MarcoEnxuto** [comment]
I'm closing this issue because the problem is related to a different section of the API.
