### ISSUE TITLE
More context and less rarefied language

### ISSUE THREAD

**Issue by sketch34** [MicrosoftDocs/windows-uwp#2988]
> "The simplest scenario is where you're implementing a Windows Runtime interface for local consumption."

> "If your type is packaged in a Windows Runtime component for consumption from an application, then it needs to be a runtime class."

It's not clear what either of these sentences mean. Please describe the terms used more thoroughly, with more examples. "local consumption" vs. "consumption from an application", I have no idea what this distinction means. If you want to keep the main body of the docs very precise / technical then perhaps consider having break out boxes that describe things in a more contextualized, verbose and pragmatic fashion, aimed at quickly ramping up devs who may be experienced but not familiar with the Windows abstractions used. Having now learned dozens different APIs, languages and frameworks my experience has been that this approach leads to the most rapid ramp up and dev adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5961a97-ba23-0707-1a86-807084a97b31
* Version Independent ID: 5c1c753b-fe4e-0d58-f623-f7d43c166277
* Content: [Author APIs with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-apis.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @sketch34, and thanks for filing this issue. I'm working on publishing a fix, and these are the changes I'll be making.

## If you're *not* authoring a runtime class

The simplest scenario is where your type is implementing a Windows Runtime interface, and you'll be consuming that type within the same app. In that case, your type doesn't need to be a runtime class; just an ordinary C++ class.

## If you're authoring a runtime class in a Windows Runtime component

If your type is packaged in a Windows Runtime component for consumption from another binary (the other binary is usually an application), then your type needs to be a runtime class.

I'll return here and close this issue once those changes are live.

Thanks again!
Steve

**Comment by stevewhims** [comment]
That change is live now. Closing. Thank you!
