### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#2989]
In the section Fiddler, can you be more descriptive about point #2 and #3 please?

- Add a rule for the AuthHost as this is what is generating the outbound traffic.
- Add a firewall rule for incoming traffic to Fiddler.

Adding screenshots will help enormously. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeaa90b2-0b6c-2047-66d2-3a2b8a53498a
* Version Independent ID: e6c93e71-af9e-7941-32c7-1e4ee79a14d4
* Content: [Web authentication broker - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/security/web-authentication-broker)
* Content Source: [windows-apps-src/security/web-authentication-broker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/web-authentication-broker.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I've added a link to the fiddler docs, which should be more comprehensive and helpful than an image and a few sentences added to this doc.
