### ISSUE TITLE
Help Page Display maps with 2D, 3D, and Streetside views formatting messed up.

### ISSUE THREAD

**Issue by cilliemalan** [MicrosoftDocs/windows-uwp#2992]
The formatting at the top of the page is messed up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42f3002-697a-b046-29c1-65eb5b16a5c8
* Version Independent ID: a7efc33e-4d38-c3e4-0078-6ef706c767bf
* Content: [Display maps with 2D, 3D, and Streetside views - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/display-maps)
* Content Source: [windows-apps-src/maps-and-location/display-maps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/maps-and-location/display-maps.md)
* Product: **uwp**
* Technology: **people-and-places**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for catching this. There was some malformed html on the page. I removed it, and the page looks correct now in my internal preview. The changes should be published shortly.
