### ISSUE TITLE
skuID on the request description should be skuId

### ISSUE THREAD

**Issue by MarcoEnxuto** [MicrosoftDocs/windows-uwp#2993]
Looks like there's a typo here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea910a17-224b-95a9-5baa-b119a9362764
* Version Independent ID: 407c87b4-7506-8b83-e646-012cc13948a6
* Content: [Query for products - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products)
* Content Source: [windows-apps-src/monetize/query-for-products.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/query-for-products.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Thank you for reporting this error. The capitalization has been fixed.
