### ISSUE TITLE
Needed to Add "Public Static" to DependencyProperty

### ISSUE THREAD

**Issue by dseacrest** [MicrosoftDocs/windows-uwp#2994]
Need to add "public static" to the DependencyProperty in Control or else it won't work on multiple instances.

public static DependencyProperty LabelProperty = DependencyProperty.Register(
    nameof(Label), 
    typeof(string),
    typeof(BgLabelControl), 
    new PropertyMetadata(default(string)));

**Comment by hkhmsft** [comment]
Hi, @dseacrest can you clarify which doc this is referring to?

**Comment by jwmsft** [comment]
I checked the [dependency property docs](https://docs.microsoft.com/windows/uwp/xaml-platform/dependency-properties-overview) and couldn't find an instance of this that didn't have 'public static'.
