### ISSUE TITLE
Windows Insider Builds

### ISSUE THREAD

**Issue by parithon** [MicrosoftDocs/windows-uwp#2996]
Does winget still require windows insider builds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Yes, just checked. The docs are up to date - https://docs.microsoft.com/en-us/windows/package-manager/winget/#install-winget

**Comment by GrantMeStrength** [comment]
Update: After further checking, winget is part of Insiders but can be installed on non-Insiders. Hope that helps!
