### ISSUE TITLE
Typo 'FancyZones'

### ISSUE THREAD

**Issue by yoichinak** [MicrosoftDocs/windows-uwp#3001]
> Powertoy を使用した管理モードのサポート
> 影響を受ける Powertoy ユーティリティ
> Fブランコ Yzones

Same as #2985

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 99bd5eaf-0982-6fe8-09d2-17e4373886bb
* Version Independent ID: 5e66eda4-be07-4afd-7187-3e4d896f7861
* Content: [Windows 10 用の Powertoy 管理者モード](https://docs.microsoft.com/ja-jp/windows/powertoys/administrator)
* Content Source: [hub/powertoys/administrator.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/hub/powertoys/administrator.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mattwojo** [comment]
Fix: https://github.com/MicrosoftDocs/windows-uwp.ja-jp/pull/153

Thank you!!! :)
