### ISSUE TITLE
Typo 'FancyZones'

### ISSUE THREAD

**Issue by yoichinak** [MicrosoftDocs/windows-uwp#3002]
> 既知の問題
> F・ Yzones とショートカットガイドで動作しない再マップ

Same as #2985

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [Windows 10 用の Powertoy キーボードマネージャーユーティリティ](https://docs.microsoft.com/ja-jp/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by mattwojo** [comment]
Fix: https://github.com/MicrosoftDocs/windows-uwp.ja-jp/pull/152
