### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/windows-uwp#3003]
Last link "Remove" links to the wrong page. 

in "The platform never removes items from the FutureAccessList for you. When you reach the 1000-item limit, you can't add another until you make room with the **Remove** method."

Should link to https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist.remove?view=winrt-19041

But links to https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemmostrecentlyusedlist.remove
Notice the **storageitemmostrecentlyusedlist** part.

Thanks!

Marvin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea426a20-ab2c-38a1-2394-f0c45b7f07a6
* Version Independent ID: da36c626-4a6f-bd65-ca6e-fa2e97aeb7a9
* Content: [Track recently used files and folders - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders)
* Content Source: [windows-apps-src/files/how-to-track-recently-used-files-and-folders.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/how-to-track-recently-used-files-and-folders.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for pointing this out. I've fixed the link and the changes should be live within a day.
