### ISSUE TITLE
allow mapping function keys to frequently used strings (email address, addresses, etc.)

### ISSUE THREAD

**Issue by sanjivsharma** [MicrosoftDocs/windows-uwp#3004]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
hi @sanjivsharma, please file this request over at https://github.com/microsoft/PowerToys/issues/new?assignees=&labels=Triage-Needed&template=feature_request.md&title= 

We have a template that needs additional information as well so i can't easily transfer the issue from here to there.

**Comment by GrantMeStrength** [comment]
hi @sanjivsharma, if you have issues please feel free to re-open this bug and we can look again. Thanks!
