### ISSUE TITLE
broadFileSystemAccess unavailable on IoT Core

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windows-uwp#3005]
Might be worth a mention that broadFileSystemAccess is not supported on Windows 10 IoT Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b665f33-4a40-510a-86d3-019ba9c79c44
* Version Independent ID: df96e262-813d-9143-9d91-a29c49a01b4f
* Content: [File access permissions - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
