### ISSUE TITLE
Bad Link on Webpage

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/windows-uwp#3015]
The link to 'Visual Studio support for C++/WinRT' is invalid. The invalid link is: https://docs.microsoft.com/en-us/windows/uwp/intro-to-using-cpp-with-winrt.md#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package

This webpage does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa02bcc-0841-3108-8f7e-47abbe6850a1
* Version Independent ID: 91c62675-45a3-5cc6-7d4a-55fbf511ad8e
* Content: [Set up the game project - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure#create-a-new-project-in-visual-studio)
* Content Source: [windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Robert-Tortorelli, and thanks for filing this issue. I have a fix in the works, that should be live within 24 hours.

Thanks again!
Steve
