### ISSUE TITLE
PowerToys FancyZones - New Feature - PPTX Viewer in FancyZ

### ISSUE THREAD

**Issue by Littmeg** [MicrosoftDocs/windows-uwp#3016]
Hi,

I have difficulty to run my presentations from home office as i wish.
PowerPoint force presenter-view to be run in full screen. If i try to run PowerPoint with view in frame so i can show my video, whiteboard and so on at the same time in split-screen/teams, i loos the ability to have presenter-view. This is a big problem in these time when we have constant home office and need to do more than just pptx on the presentation.

I need to have the presenter-view on my second screen and split-screen view tilt pptx on the screen shared in meeting tools.

My thoughts is that the magic in the tool PowerToys FancyZones can help with this. If the FancyZones get the ability to set one of the frames as an second/third monitor. This will then bee an virtual emulated monitor living in a frame-mode in PowerToys FancyZones.

I hope someone can help me to get this feature, as presentations are quite the challenges in the time of corona...

https://github.com/microsoft/PowerToys

Best regards
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones#feedback)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
https://github.com/microsoft/PowerToys/issues/279 is our tracking issue.  Thanks!

**Comment by Littmeg** [comment]
I think it is very unfortunate that the challenge is closed, as this is a real challenge. For those who say that this is not a big problem as it only applies to those with ultra wide screens, this is not true!
In these corona times when we have all been put in the home office and have a lot of meetings online, the way we hold the meetings also changes. I have a strong need to present myself in the window while I can run a pptx presentation in full screen / presenter mode with my notes available. This is not possible today! That is, a big problem in relation to how to present and hold meetings.
I hope someone opens up and raises this issue and creates a function that gives us this opportunity!

Regards,
Chris
Frustrated user of pptx
