### ISSUE TITLE
Custom Audio does not work as indicted in the docs

### ISSUE THREAD

**Issue by Jcardif** [MicrosoftDocs/windows-uwp#3017]
I tried implementing custom audio however for the locally deployed app it does not work.  My windows version is 20H2. The toast is displayed however it is silent no audio is played. 
The code is as below

```Csharp
            // Construct the content
            var contentBuilder = new ToastContentBuilder()
                .AddToastActivationInfo("app-defined-string", ToastActivationType.Foreground)
                .AddText(titleText)
                .AddText("Some text here")
                // Profile (app logo override) image
                .AddAppLogoOverride(logoOverrideUri, ToastGenericAppLogoCrop.Circle);

            // If we're running on Desktop before Version 1511, do NOT include custom audio
            // since it was not supported until Version 1511, and would result in a silent toast.

            var supportsCustomAudio = !(AnalyticsInfo.VersionInfo.DeviceFamily.Equals("Windows.Desktop")
                                         && !ApiInformation.IsApiContractPresent(
                                             "Windows.Foundation.UniversalApiContract", 2));

            if (supportsCustomAudio)
            {
                contentBuilder.AddAudio(new Uri("ms-appx:///Assets/Audio/ToastNotificationSound.wav"));
            }

            // Send the toast
            contentBuilder.Show();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfdc821a-c9bb-b8fb-3819-8d99c6ee7b03
* Version Independent ID: c32c183c-8a50-1444-fb68-c0b46d6805f2
* Content: [Custom audio on toasts - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/custom-audio-on-toasts)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/custom-audio-on-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/custom-audio-on-toasts.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi, @Jcardif thanks for submitting your issue. I'm thinking you could get an answer over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). The community of Microsoft engineers and experts might help troubleshoot your issue. If there's a specific doc change needed, feel free to re-open this Issue so we can work to incorporate the changes. Thanks.
