### ISSUE TITLE
Consuming WinRT APIs page references console app

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3021]
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis

This page shows how to consume a WinRT API from a console project.
This however gives a false sense of security that you can use _any_ WinRT type from an unpackaged app. Only Windows types can be consumed in this manner. Custom types cannot, as they require the package identity to resolve the custom WinRT class registration.

There should be a link to the Desktop Bridge project, and a disclaimer that "File->New Console project" apps have this restriction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbed06f8-9ce1-f057-e391-80ab68ccdfc0
* Version Independent ID: 565fb22e-e508-4bfb-84d8-bba71032498d
* Content: [Consume APIs with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-apis.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @asklar, I've added that info to the topic (at the top, in the **Important** block). I'll close this issue, but let me know if the topic needs more work.

Thanks!
Steve
