### ISSUE TITLE
Windows desktop forms is not compatible with this API

### ISSUE THREAD

**Issue by berrywing012** [MicrosoftDocs/windows-uwp#3022]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1d9bcc-262c-d083-fec6-c49b6bc5acd5
* Version Independent ID: deb61f0f-885e-8fc2-48b8-8908c28ffc56
* Content: [Basic photo, video, and audio capture with MediaCapture - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-mediacapture)
* Content Source: [windows-apps-src/audio-video-camera/basic-photo-video-and-audio-capture-with-MediaCapture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/basic-photo-video-and-audio-capture-with-MediaCapture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
There is no specific question about documentation here, so let me just point you to a few resources:

[Call Windows Runtime APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance)
[Windows Runtime APIs available to desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)
