### ISSUE TITLE
Mismatched Version Requirements

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#3024]
Text says 1809 but image still shows 1803...

![image](https://user-images.githubusercontent.com/24302614/112193619-4ce7a600-8bc5-11eb-83d2-c2114824c2f8.png)

Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6a5c75-6cdc-a97f-df50-938ac5534e28
* Version Independent ID: e7195fca-7687-4296-6aa8-638ce198d549
* Content: [Get started with WinUI 3 for desktop apps - WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop)
* Content Source: [hub/apps/winui/winui3/get-started-winui3-for-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/get-started-winui3-for-desktop.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. The image has been updated to match the text.
