### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hanseuljun** [MicrosoftDocs/windows-uwp#3027]
[Enter feedback here]
At https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure

There are two Windows::ApplicationModel::CoreCoreApplicationView, which are supposed to be Windows::ApplicationModel::Core::CoreApplicationView.

The difference is CoreCoreApplicationView -> Core::CoreApplicationView

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa02bcc-0841-3108-8f7e-47abbe6850a1
* Version Independent ID: 91c62675-45a3-5cc6-7d4a-55fbf511ad8e
* Content: [Set up the game project - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure)
* Content Source: [windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @hanseuljun, and thanks for spotting those typos. I've published fixes for them now.

Thanks again!
Steve
