### ISSUE TITLE
Wrong component.

### ISSUE THREAD

**Issue by DkmS1953** [MicrosoftDocs/windows-uwp#3031]
[Введите отзыв здесь]
C++ (v142) Universal Windows Platform tools  In VS 2019 16.10 doesn't exist

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 55c42ca2-ba72-2e63-ced6-190a10bc7c48
* Version Independent ID: 35e48d73-1c81-72f4-722e-ddd2cb4e3adf
* Content: [Project Reunion](https://docs.microsoft.com/ru-ru/windows/apps/project-reunion/#set-up-your-development-environment)
* Content Source: [hub/apps/project-reunion/index.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/hub/apps/project-reunion/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. In the Visual Studio installation dialog, the "C++ (v142) Universal Windows Platform tools" component that this instruction refers to is listed in the **Installation details** pane on the right side of the dialog, under the **Universal Windows Platform development** section. I revised the instructions to make this more clear.

**Comment by DkmS1953** [comment]
Thank you.
Without clarification, it is almost impossible to know where to look for
components to install.
🤗

Wbr, Dyakov K.M.



пт, 26 мар. 2021 г. в 20:19, McLean Schofield ***@***.***>:
