### ISSUE TITLE
The Italian title should be "Muto per le videoconferenze (anteprima)"

### ISSUE THREAD

**Issue by albertopasqualetto** [MicrosoftDocs/windows-uwp#3039]
[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: a4b22118-da48-5b54-9afa-00e372e3c4c4
* Version Independent ID: a14d3309-a07e-d9b4-9fd6-c17fbe1f93e2
* Content: [Utilità di silenziamento video Conference PowerToy per Windows 10](https://docs.microsoft.com/it-it/windows/powertoys/video-conference-mute)
* Content Source: [hub/powertoys/video-conference-mute.md](https://github.com/MicrosoftDocs/windows-uwp.it-it/blob/live/hub/powertoys/video-conference-mute.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thank you for submitting this correction. Unfortunately at this time, we have no way of updating individual topics in languages other than English. I will keep a record of this so if the situation changes, we can submit it. thanks!
