### ISSUE TITLE
vault.FindAllByResource(resourceName); throws exception if resource is not found. Example does not reflect this behavior

### ISSUE THREAD

**Issue by SvenLauterbach** [MicrosoftDocs/windows-uwp#3045]
Hi,

The example from this page seems a little bit buggy.

```csharp
var credentialList = vault.FindAllByResource(resourceName);
```

According to the [documentation ](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.passwordvault.findallbyresource?view=winrt-19041) `FindAllByResource` throws an exception:

> The resource to be searched for. If a match does not exist, an exception will throw.

This means, that the `else`block is never reached:

```csharp
var loginCredential = GetCredentialFromLocker();

if (loginCredential != null)
{
    // There is a credential stored in the locker.
    // Populate the Password property of the credential
    // for automatic login.
    loginCredential.RetrievePassword();
}
else
{
    // There is no credential stored in the locker.
    // Display UI to get user credentials.
    loginCredential = GetLoginCredentialUI();
}
```

The exception should be catched by `GetCredentialFromLocker` and than return `null`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350b7fbc-954c-be69-79b1-e0c121f16070
* Version Independent ID: bc24d4ba-c7fc-bd38-5455-37486de1af80
* Content: [Credential locker - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/security/credential-locker)
* Content Source: [windows-apps-src/security/credential-locker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/credential-locker.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Great catch. This was updated recently so I believe this issue has been resolved.
