### ISSUE TITLE
I cannot validate developer mode

### ISSUE THREAD

**Issue by Sakitakazawa** [MicrosoftDocs/windows-uwp#3048]
[I tried to validate developer mode but I cannot chose that choice. Do I need administrator privileges?? Is my pc surveillanced by administrator?? please help me....]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3bb82418-b583-7023-f2e3-c3dca7d3245c
* Version Independent ID: 0a65ac0a-9884-52a8-6485-c2825b1fb4d9
* Content: [デバイスを開発用に有効にする - Windows applications](https://docs.microsoft.com/ja-jp/windows/apps/get-started/enable-your-device-for-development?OCID=WinClient_Ver1703_Settings_DevMode)
* Content Source: [hub/apps/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/hub/apps/get-started/enable-your-device-for-development.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there!
