### ISSUE TITLE
build error in example -  environment variable 'OUT_DIR' not defined

### ISSUE THREAD

**Issue by GraemePBell** [MicrosoftDocs/windows-uwp#3049]
Hi, after following the instructions in this article I get the error message below. I have the latest toolchain (as of 040/04/31) and "hello_world" builds just fine.

Graeme

--------------------------------------------------------------------------------------------------------------------
I   Compiling bindings v0.1.0 (C:\Users\uname\source\rust\rss_reader\bindings)
error: environment variable `OUT_DIR` not defined
 --> bindings\src\lib.rs:2:1
  |
2 | ::windows::include_bindings!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `bindings`

--------------------------------------------------------------------------------------------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @GraemePBell.

> In VS Code, right-click the bindings folder, and click New File. Type in the name build.rs, and press Enter.

If you right-clicked the bindings/src folder instead, then that'd account for the error you're seeing. If your build.rs is in bindings/src instead of bindings, then just move it there.

-Steve

**Comment by GraemePBell** [comment]
Thanks Steve, your suggestion worked. 

I note that windows.web.syndication.SyndicationClient is not in the windows crate 0.7.0, so the example won't work with the latest crate, but version in the article is fine - I like Rust's easy versioning.

Graeme
