### ISSUE TITLE
More clarity needed for Nuget.org package source requirement

### ISSUE THREAD

**Issue by NeelAPatel** [MicrosoftDocs/windows-uwp#3052]
The bullet point about having nuget.org as a source should be a bit more specific/detailed. While the link helps, it was not obvious enough that we need "https://api.nuget.org/v3/index.json" as the source URL, since it wasn't stated anywhere except in the codeblock.

I found it a bit challenging as I am new to using Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42aa9e2a-5cad-de4e-529e-661e3744159b
* Version Independent ID: 1b8ececa-8e30-ad26-7229-059f62f7868b
* Content: [Get started with Project Reunion](https://docs.microsoft.com/en-us/windows/apps/project-reunion/get-started-with-project-reunion#set-up-your-development-environment)
* Content Source: [hub/apps/project-reunion/get-started-with-project-reunion.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/project-reunion/get-started-with-project-reunion.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback! I just published some revisions to this step in the article to clarify where in Visual Studio you can go to confirm this setting. These changes should be visible on the live docs site in the next hour or so.
