### ISSUE TITLE
[LOC]Back-Translation "Windows ターミナル"→"Windows Terminal"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#3056]
ja-jp:"https://docs.microsoft.com/ja-jp/windows/apps/whats-new/latest-doc-updates"
![latest-doc-updates_j](https://user-images.githubusercontent.com/40815708/114006440-66624080-989b-11eb-9e48-82af9c4840a7.png)

en-us:"https://docs.microsoft.com/en-us/windows/apps/whats-new/latest-doc-updates"
![latest-doc-updates_e](https://user-images.githubusercontent.com/40815708/114006465-6bbf8b00-989b-11eb-8c11-fbe3091a2b5c.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6bdb5007-8cda-76f2-6ba3-b198d7c2c9f4
* Version Independent ID: cb299507-7c92-53ee-4b45-a0ef14384f96
* Content: [Windows 開発者向けドキュメントの最新の更新 - Windows applications](https://docs.microsoft.com/ja-jp/windows/apps/whats-new/latest-doc-updates)
* Content Source: [hub/apps/whats-new/latest-doc-updates.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/hub/apps/whats-new/latest-doc-updates.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Apologies for the lengthy delay on this issue. I've commited a fix, which should eventually make its way into the localized pages.
