### ISSUE TITLE
Broken link https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/

### ISSUE THREAD

**Issue by russcam** [MicrosoftDocs/windows-uwp#3061]
The link in the passage

> Rust for Windows benefits from the polished toolchain that Rust developers enjoy. But if having the entire Windows API at your fingertips seems a little daunting, there's also [Rust documentation for the Windows API](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/).

is broken and returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf3f708-e517-41c8-0033-5e737e58cbd6
* Version Independent ID: a143550c-f85f-5b35-2fa4-0bcc243cac1d
* Content: [Rust for Windows, and the *windows* crate](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows)
* Content Source: [hub/dev-environment/rust/rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rust-for-windows.md)
* Product: **dev-environment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @russcam, I've published a fix to that.

-Steve
