### ISSUE TITLE
CPUSets Example Broken Link

### ISSUE THREAD

**Issue by pbrubaker** [MicrosoftDocs/windows-uwp#3062]
The link to the CPUSets sample by ATG is broken.

"CPUSets sample provided by ATG"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10f186a9-8802-b9e2-e128-4c201f8c7ff0
* Version Independent ID: 9db06ed9-3558-c22b-d4d1-16b14984677d
* Content: [CPUSets for game development - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/cpusets-games)
* Content Source: [windows-apps-src/xbox-apps/cpusets-games.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/cpusets-games.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by MatchaMatch** [comment]
Thanks for bringing this to our attention! The link has been updated - you should see this change published soon.
