### ISSUE TITLE
latest status of Windows 10 X?

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftDocs/windows-uwp#3063]
- **is there some document I can look to understand what's the limitation of Win32 Apps over Win10 X?**
- **what's the road map of win10 X?**
- **is there SDK or SDK documents that I as a Windows developer can take a look at?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67ddde4e-dbc5-18bf-937c-705a6e664c4c
* Version Independent ID: b9e6ec70-84a7-12f9-f5c6-49bb76074434
* Content: [Windows 10X Developer FAQ - Windows applications](https://docs.microsoft.com/en-us/windows/apps/10x/faq#feedback)
* Content Source: [hub/apps/10x/faq.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/10x/faq.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by johnnylq** [comment]
also looking farward to the Win10X status update.

**Comment by QuinnRadich** [comment]
This is a stale issue, as Windows 10X has been effectively replaced by Windows 11 and the Windows App SDK. Thus, closing it out.
