### ISSUE TITLE
IDL examples lack syntax highlighting

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#3064]
All the examples for C++/WinRT, starting with this introduction page lack syntax highlighting for the IDL code, which makes it unwelcoming for newbies trying to learn the platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed62e90-9a85-e295-69ac-7af08123e024
* Version Independent ID: b740841d-6530-d774-0f68-dcd356f9adb5
* Content: [Create a 'Hello, World!' app using C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cppwinrt)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cppwinrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cppwinrt.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This is, unfortunately, a current docs platform limitation and not something we can directly interact with. The back-end docs team might address this in the future, but for now it's not something we can fix. Apologies.
