### ISSUE TITLE
In french, paragraph title "Comment cela fonctionne-t-il dans le capot" should be "Comment cela fonctionne-t-il sous le capot"

### ISSUE THREAD

**Issue by willofr** [MicrosoftDocs/windows-uwp#3065]
The French translation of the paragraph title https://docs.microsoft.com/fr-fr/windows/powertoys/video-conference-mute#how-does-this-work-under-the-hood should be "Comment cela fonctionne-t-il **sous** le capot"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a4b22118-da48-5b54-9afa-00e372e3c4c4
* Version Independent ID: a14d3309-a07e-d9b4-9fd6-c17fbe1f93e2
* Content: [Utilitaire de désactivation de la vidéoconférence PowerToys pour Windows 10](https://docs.microsoft.com/fr-fr/windows/powertoys/video-conference-mute#how-does-this-work-under-the-hood)
* Content Source: [hub/powertoys/video-conference-mute.md](https://github.com/MicrosoftDocs/windows-uwp.fr-fr/blob/live/hub/powertoys/video-conference-mute.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
@mattwojo if this is a translation issue, why is it assigned to me

**Comment by mattwojo** [comment]
@crutkas - Any PRs or Issues for the PowerToys content will be auto-assigned to you. I have an email thread with the Loc team about how to handle translation issues. It sounds like the "Edit" button has been removed from localized doc pages.

**Comment by crutkas** [comment]
assigning to matt as this is a translation issue for FR.  Not a core docs issue for PT.

**Comment by mattwojo** [comment]
Ugh... Thank you for this translation update @willofr. I've been working with our localization team to try to better understand what's happening behind the scenes and how to publish fixes like the one you have offered here. Unfortunately, my take-away is that this PowerToys content is being machine translated and there isn't currently a mechanism in place to replace that machine translation with corrected translations from the user community (like the one you've offered here). It sounds like it would just be overwritten any time there is an update to the doc by the auto-generated machine translation. I have to own that I am not a machine translation expert and don't fully understand how that system works, but there isn't currently anything that I can do with your contribution here. :( So I'm closing this issue. I do want you to know that it inspired a lot of conversation and I'm continuing to push for some sort of fix that would allow for this sort of correction of mis-translated docs. 
Thanks again for filing this.
