### ISSUE TITLE
ERROR: No acceptable C compiler found! Please update the instructions to address this.

### ISSUE THREAD

**Issue by joe-oli** [MicrosoftDocs/windows-uwp#3069]
I was following the instructions on this page:
https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2

Failed on the crucial step: It appears instructions did not mention anything about C / C++ compiler prerequisites; If this is indeed the case, instructions need to be updated !

$ nvm install --lts
Installing latest LTS version.
Downloading and installing node v14.16.1...
Downloading https://nodejs.org/dist/v14.16.1/node-v14.16.1-linux-x64.tar.xz...
################################################################################################################# 100.0%Computing checksum with sha256sum
Checksums matched!
mv: cannot move '/home/<username>/.nvm/.cache/bin/node-v14.16.1-linux-x64/files/lib' to '/home/<username>/.nvm/versions/node/v14.16.1/lib': Permission denied
Binary download failed, trying source.
Detected that you have 4 CPU core(s)
Running with 3 threads to speed up the build
Downloading https://nodejs.org/dist/v14.16.1/node-v14.16.1.tar.xz...
################################################################################################################# 100.0%Computing checksum with sha256sum
Checksums matched!
$>./configure --prefix=/home/<username>/.nvm/versions/node/v14.16.1 <
Node.js configure: Found Python 3.8.5...
WARNING: failed to autodetect C++ compiler version (CXX=g++)
WARNING: failed to autodetect C compiler version (CC=gcc)
ERROR: No acceptable C compiler found!

       Please make sure you have a C compiler installed on your system and/or
       consider adjusting the CC environment variable if you installed
       it in a non-standard prefix.
nvm: install v14.16.1 failed!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up Node.js on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @joe-oli - Sorry for my delay on this. I did a bit of research.. installing a C or C++ compiler is not a part of the typical NodeJS installation on WSL 2, so I'm not exactly clear on what happened here.. but it looks like you may want to try installing the build-essential package. It's a a reference for all the packages needed to compile an Ubuntu/Debian package. 

Try this command and see if it addresses your issue:
`sudo apt-get install build-essential`

Here's a reference: https://stackoverflow.com/questions/3329355/how-to-compile-install-node-jscould-not-configure-a-cxx-compiler-ubuntu/5659811
