### ISSUE TITLE
Clarify the reference to the 'DirectX 11 App (Universal Windows) template'

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/windows-uwp#3071]
This page states, "Now let's look at the rest of the files that come with the **DirectX 11 App (Universal Windows) template**."
However, this is the first and only mention of the '**DirectX 11 App (Universal Windows) template**' on this page. I assume it's a reference to the fact that **Simple3DGameDX** (which _is_ mentioned on this page) is based on the DirectX 11 App (Universal Windows) template.

This page would be improved by either explaining this relationship, or by stating "Now let's look at the rest of the files that come with **Simple3DGameDX**."

  Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa02bcc-0841-3108-8f7e-47abbe6850a1
* Version Independent ID: 91c62675-45a3-5cc6-7d4a-55fbf511ad8e
* Content: [Set up the game project - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure#review-and-update-the-packageappxmanifest-file)
* Content Source: [windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Robert-Tortorelli! Yes, I did mean Simple3DGameDX there. I've published a fix.

Thanks again!
Steve

**Comment by Robert-Tortorelli** [comment]
Thank you Steve!

  Robert
