### ISSUE TITLE
Mode 'admin'

### ISSUE THREAD

**Issue by Brunonix** [MicrosoftDocs/windows-uwp#3075]
Bonjour

le programme 'PowerToys' précise qu'il faut que al session soit en mode administrateur ! Mais mon compte EST un compte d'administrateur ! Je ne comprends pas pourquoi, les options sont grisées de ce fait ! 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [Utilitaire de l’Explorateur de fichiers PowerToys pour Windows 10](https://docs.microsoft.com/fr-fr/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-uwp.fr-fr/blob/live/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
> Hello

> the 'PowerToys' program specifies that the session must be in administrator mode! But my account IS an administrator account! I don't understand why, the options are greyed out because of this!

Is PT itself running under admin? Only elevated processes can tweak what is needed. In settings->general tab, just relaunch as admin.

**Comment by crutkas** [comment]
please file an issue over at https://github.com/microsoft/PowerToys/issues/new?assignees=&labels=Issue-Bug%2CTriage-Needed&template=bug_report.yml if you are having an issue still
