### ISSUE TITLE
PoverRename translation mistake

### ISSUE THREAD

**Issue by LeftTwixWand** [MicrosoftDocs/windows-uwp#3077]
There is a mistake. Поверренаме - is incorrect machine translation. It will be better to use the default "PoverRename" name.

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [Средство PowerToy Поверренаме Utility для Windows 10](https://docs.microsoft.com/ru-ru/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
Please use https://github.com/microsoft/PowerToys/issues/new?assignees=&labels=Issue-Bug%2CArea-Localization%2CIssue-Translation%2CTriage-Needed&template=translation_issue.yml to file translation issues. This is for docs only. Thanks!

This template provides all our needed info for this type of issue.

**Comment by crutkas** [comment]
sorry, i was mistaken.  I thought this was an app issue, not a docs issue.

**Comment by LeftTwixWand** [comment]
> sorry, i was mistaken. I thought this was an app issue, not a docs issue.

It's ok))

**Comment by mattwojo** [comment]
I believe that I've _finally_ figured out how to correct this issue: https://docs.microsoft.com/ru-ru/windows/powertoys/powerrename

Thank you @LeftTwixWand!
