### ISSUE TITLE
Outdated content

### ISSUE THREAD

**Issue by donid** [MicrosoftDocs/windows-uwp#3078]
This page is outdated - it refers to the old 0.1.0 manifest format, which has been replaced with the 1.0.0 format in March 2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657479f-c0b7-6358-c7d0-0402215edaa5
* Version Independent ID: 8976699b-cdba-5206-bdb0-8a0875acfe45
* Content: [Create your package manifest](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Ccompschema)
* Content Source: [hub/package-manager/package/manifest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/manifest.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Thanks for the report.  This was fixed in May.
