### ISSUE TITLE
Note for `Remap a shortcut to a single key` is wrong

### ISSUE THREAD

**Issue by noraa-junker** [MicrosoftDocs/windows-uwp#3080]
See microsoft/powertoys#10974

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/keyboard-manager#remap-a-shortcut-to-a-single-key)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
this was resolved
