### ISSUE TITLE
Make it clear that when you use Rust in Windows, that a Visual Studio license is required 

### ISSUE THREAD

**Issue by samsmithnz** [MicrosoftDocs/windows-uwp#3081]
The Build Tools, a prerequisite for Rust on Windows require a Visual Studio license. This is not mentioned anywhere in the docs, but should be made clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by byjrack** [comment]
Another option would be to split the MSVC toolchain via rustup talking to the Visual Studio license requirements while suggesting the stable-x86_64-pc-windows-gnu toolchain for those without a valid Visual Studio license.  Just helps users who are investigating from infringing on the commercial terms though they may still some open source process for the underlying mingw bits.

**Comment by stevewhims** [comment]
Thank you, both, I'm looking into this.

-Steve

**Comment by stevewhims** [comment]
Hi, does this topic shed any light on the steps and requirements?

https://code.visualstudio.com/docs/cpp/config-msvc

Many thanks!
Steve

**Comment by samsmithnz** [comment]
We understand the requirements - but what isn't clear is that the build tools require a license. These docs should reflect that. I'll follow up directly on Teams to share more details.

**Comment by byjrack** [comment]
It wasn't the install instructions that were the problem, but more the fine print in the Note around the need for a commercial license even if you were not planning on using any VS product.  Some of our associates may not have an Ent/Pro license without going through procurement so since there is no gate like with other MSDN downloads infringing on the terms is quite easy.

**Comment by stevewhims** [comment]
UPDATE: I've added a note saying "Use of the Microsoft C++ Build Tools, or Visual Studio Build Tools, requires a valid Visual Studio license (either Community, Pro, or Enterprise)."
