### ISSUE TITLE
Push Notification Power Saver settings missing

### ISSUE THREAD

**Issue by PatGet** [MicrosoftDocs/windows-uwp#3083]
Hi there,
the settings mentioned under https://www.c-sharpcorner.com/UploadFile/81b528/disable-push-notification-using-battery-saver-mode-settings973/ are not available on any machien i got my hands on. What happend to them and do they have some kind of Group policy so i coud set them globaly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1500dd-1909-34d6-d67a-8ae2dc5393db
* Version Independent ID: 490fe0f3-6dbf-93a6-e0c0-c3ea51f5cbd3
* Content: [Windows Push Notification Services (WNS) overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview#push-notifications-and-battery-saver)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there!

**Comment by PatGet** [comment]
Ok, i might not get my specific answers here but it also seems that you did not look into this topic. There is either a Bug in Windows or a bug in the docs.
Those settings do not exist anymore.
