### ISSUE TITLE
ms-settings:display-advanced doesn't link to "Advanced display settings"

### ISSUE THREAD

**Issue by mooons** [MicrosoftDocs/windows-uwp#3084]
In the page https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#system

```
ms-settings:display-advanced (only available on devices that support advanced display options)
```
this incorrectly links to "Advanced scaling settings", while "Advanced display settings" does NOT have a shortcut to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by alvinashcraft** [comment]
I have submitted product feedback to the team about this linking. It does not seem correct, as you say. When I try the same link on my Windows 11 build, the display-advanced brings up the Display settings page, not Advanced Display settings.
#assign:alvinashcraft

**Comment by alvinashcraft** [comment]
Thanks again for submitting your feedback. An internal work item has been created for our engineering team based on my Windows feedback item to resolve this issue in an upcoming Windows release. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
