### ISSUE TITLE
Broken link to "Microsoft Speech SDK, version 5.1"

### ISSUE THREAD

**Issue by bjanders** [MicrosoftDocs/windows-uwp#3086]
The link "Microsoft Speech SDK, version 5.1" on the page "Speech, voice, and conversation in Windows 10" points to https://www.microsoft.com/download/details.aspx?id=10121, which does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5532269-6b52-2288-ddf1-8c2e8d52e2db
* Version Independent ID: 9106566d-48f5-25fa-67d6-978ac385dff9
* Content: [Speech, voice, and conversation in Windows 10 - Windows applications](https://docs.microsoft.com/en-us/windows/apps/speech)
* Content Source: [hub/apps/speech.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/speech.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by bjanders** [comment]
The links "Microsoft Speech Platform - Software Development Kit (SDK) (Version 11)" and "Microsoft Speech Application Software Development Kit (SASDK) Version 1.0" are also broken. Maybe there's more?

**Comment by Karl-Bridge-Microsoft** [comment]
@bjanders - thanks for letting us know about this issue! I've reached out to our download service team to find out what happened to the downloads and what we need to do to rectify the issue. I'll update this issue as I get more info.

**Comment by Karl-Bridge-Microsoft** [comment]
Downloads have been reinstated and links work again.
