### ISSUE TITLE
Power Toys still does not run nor any default shortcut key works

### ISSUE THREAD

**Issue by DeerSpotter** [MicrosoftDocs/windows-uwp#3088]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c39e7c8-7ab6-3297-1554-d7ef10d46894
* Version Independent ID: 021ad68a-284a-fd90-4404-463f08301b04
* Content: [PowerToys Shortcut Guide utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/shortcut-guide)
* Content Source: [hub/powertoys/shortcut-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/shortcut-guide.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by crutkas** [comment]
@DeerSpotter please file a bug with a "report bug" zip at https://github.com/microsoft/PowerToys/issues/new?assignees=&labels=Issue-Bug%2CTriage-Needed&template=bug_report.yml

**Comment by hkhmsft** [comment]
Thanks for providing the link to the PowerToys repo, @crutkas. Closing this issue for now.
