### ISSUE TITLE
This page should make a difference between packaged and unpackaged apps

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#3092]
More APIs are supported in packaged apps than in unpackaged ones, because they have a proper package identity (one example is `StartupTask`, which only works when packaged). This detail should be mentioned, and a list of APIs only supported in packaged apps should be provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909f1773-1e55-eb5a-206f-b32ce6f9dd9d
* Version Independent ID: 24ea5c87-1c21-884d-f05f-833bbd894ba9
* Content: [Windows Runtime APIs not supported in desktop apps - Windows applications](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. The list of types that require package identity was inadvertently omitted when we recently revised this article, and I just brought that list back into the article. The Windows engineering teams will expand this article as they gather more details about the supported WinRT APIs.
