### ISSUE TITLE
What happens if you try to activate Developer Mode, and the Xbox says it needs an update that never comes?

### ISSUE THREAD

**Issue by bisdavid** [MicrosoftDocs/windows-uwp#3093]
I'm trying to activate the Developer Mode on my Xbox.  I have my partner account, got the code for Activation, and the XBox accepted it.  However, it now says "Almost done. The Xbox needs an update to complete the activation. Come back to this app after the update."   However, the update never arrives.  I've gone into the Settings/System/Update and confirmed that there is no update available, but I can't proceed.

Help please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb57bfe-69f7-e1d0-cd63-d28360727985
* Version Independent ID: ece8efc3-9422-0103-3ed7-94e8427fcb7c
* Content: [Xbox One Developer Mode activation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by hkhmsft** [comment]
Hi @bisdavid , could you try submitting your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? Unfortunately, this feedback channel covers specific documentation fixes so I'm thinking you can get a better answer over in Q&A. Hope this helps and thanks for taking the time to submit your feedback.
