### ISSUE TITLE
Save-As not respecting SuggestedFileName

### ISSUE THREAD

**Issue by steelejoe** [MicrosoftDocs/windows-uwp#3100]
The behavior I see currently on Windows 10 Pro 20H2 with Visual Studio 2019 16.9.4 is that when I have an existing StorageFile that I pass to the FileSavePicker and I set the SuggestedFileName (as suggested here) that name is ignored. It would be great to see an example here of that workflow - i.e. saving an existing file to the same folder with a different suggested name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a77b7740-cd43-eb63-30d3-1f319955f083
* Version Independent ID: 1d74738a-6949-c97c-ed01-0841aa0f643d
* Content: [Save a file with a picker - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-save-a-file-with-a-picker)
* Content Source: [windows-apps-src/files/quickstart-save-a-file-with-a-picker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-save-a-file-with-a-picker.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
I tested this passing in a StorageFile using the latest VS and Windows builds, and all seems working as expected.

 private async void Button_Click(object sender, RoutedEventArgs e)
        {
            Windows.Storage.StorageFile myfile = null;
            await SaveStuff(myfile);
        }
 
        private static async Task SaveStuff(Windows.Storage.StorageFile file)
        {
            var savePicker = new Windows.Storage.Pickers.FileSavePicker();
            savePicker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.DocumentsLibrary;
            savePicker.FileTypeChoices.Add("Plain text", new List<string>() { ".txt" });
            savePicker.SuggestedFileName = "yeah new doc";
 
            file = await savePicker.PickSaveFileAsync();
            if (file != null)
            {
                // Prevent updates to the remote version of the file until
                // we finish making changes and call CompleteUpdatesAsync.
                Windows.Storage.CachedFileManager.DeferUpdates(file);
                // write to file
                await Windows.Storage.FileIO.WriteTextAsync(file, "file contents");
                // Let Windows know that we're finished changing the file so
                // the other app can update the remote version of the file.
                // Completing updates may require Windows to ask for user input.
                Windows.Storage.Provider.FileUpdateStatus status =
                    await Windows.Storage.CachedFileManager.CompleteUpdatesAsync(file);
                if (status == Windows.Storage.Provider.FileUpdateStatus.Complete)
                {
                    //this.textBlock.Text = "File " + file.Name + " was saved.";
                }
                else
                {
                    //this.textBlock.Text = "File " + file.Name + " couldn't be saved.";
                }
            }
            else
            {
                // this.textBlock.Text = "Operation cancelled.";
            }
        }
    }
}
