### ISSUE TITLE
文档翻译错误

### ISSUE THREAD

**Issue by 493505110** [MicrosoftDocs/windows-uwp#3101]
![image](https://user-images.githubusercontent.com/29498336/117104163-3fb9fb80-adae-11eb-858a-47ecacf81487.png)

此处“Scoop”不应该翻译

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [安装 PowerToys](https://docs.microsoft.com/zh-cn/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by 493505110** [comment]
see [PR#33](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/pull/33)

**Comment by crutkas** [comment]
@mattwojo ping on this.

**Comment by mattwojo** [comment]
I believe that I've figured out how to correct this mistranslation now.
Thank you @493505110 

https://docs.microsoft.com/zh-cn/windows/powertoys/install
