### ISSUE TITLE
 Windows Insider SDKs link is broken

### ISSUE THREAD

**Issue by aek-frl** [MicrosoftDocs/windows-uwp#3102]
[Enter feedback here]
 Windows Insider SDKs link leads to "page cannot be found"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ad11f6-c110-d5f8-6a13-dd9bbc972fb2
* Version Independent ID: e079a5eb-e883-1078-d59b-81586ea2d3e8
* Content: [Experimental APIs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/whats-new/experimental-apis)
* Content Source: [windows-apps-src/whats-new/experimental-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/experimental-apis.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for your patience on this issue. I think it may have been a temporary issue on the page being linked to? Currently, the link is working for me, though unless you're a member of the Windows Insider Program it mainly just contains a link to learn more / sign up about the program.

As the link appears to work, closing this issue.
