### ISSUE TITLE
version of Python is unclear, it says 3.9 and 3.7

### ISSUE THREAD

**Issue by hackett808** [MicrosoftDocs/windows-uwp#3104]
The recommended version of Python is unclear, it says 3.9 and 3.7. Which one is it?  Is there a reason not to be using 3.9?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56d5dd2-6677-fb21-03d2-b9ea94e2b9a8
* Version Independent ID: 973324bd-74b0-8589-0f36-2d4ab1583208
* Content: [Python on Windows 10 for beginners](https://docs.microsoft.com/en-us/windows/python/beginners)
* Content Source: [hub/python/beginners.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/beginners.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Great catch @hackett808 -- thanks for pointing this out!
No, there is no reason not to use v3.9 to my knowledge. I've just not been on top of updating the version numbers. Generally, I recommend using whatever the most recently available version is unless you're working on an existing project in which you may want to match the version # that it was created with to avoid update conflicts.

I'll get the docs updated to reflect this and thanks again!

**Comment by mattwojo** [comment]
Resolved this versioning issue in https://github.com/MicrosoftDocs/windows-uwp/commit/6caa935bd17df5d634365651cdb35b0c31506dae
