### ISSUE TITLE
Why does this page specify Python 3.7?

### ISSUE THREAD

**Issue by BurtHarris** [MicrosoftDocs/windows-uwp#3109]
The page on setup of Python for scripting specifically says to install Python 3.7, but 3.9 is the latest.   If this is intentional, some explanation should be included.

Also, some explanation of app execution aliases should be included so that if using the "python" command doesn't run the expected version of python, or doesn't work at all, someone following these instructions will know where to look to select a different version (e.g. add/remove programs.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cef0cd5-f116-1e35-c1ab-385063aac0b7
* Version Independent ID: a53f5975-623f-c1c0-faa1-c0b7c4d3324e
* Content: [Using Python for scripting and automation](https://docs.microsoft.com/en-us/windows/python/scripting)
* Content Source: [hub/python/scripting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/scripting.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for raising this issue @BurtHarris! Clearly this is out of date -- I'll update to remove the 3.7 recommendation and that's a great recommendation to add more info about what to do if the `python` command doesn't work. We do include this in the FAQs: https://docs.microsoft.com/en-us/windows/python/faqs#what-is-py-exe-  ...but agree that it could be helpful to add a note with a better explanation. I'll take a crack at it and link my update to see what you think.

**Comment by mattwojo** [comment]
Resolved: https://github.com/MicrosoftDocs/windows-uwp/commit/fd7e1e2c95f1c1b9652ed5b7a57cd77176a70974#diff-2dea4ccbb24d57751d789ee915a4837c41c078c113485d31f5338dae6ab8e38c
