### ISSUE TITLE
Missing "Chat Message Access" device Capability

### ISSUE THREAD

**Issue by timkeo** [MicrosoftDocs/windows-uwp#3110]
The basic "chat" capability is missing from this page.
It's included in this doc page: https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-device-capabilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#device-capabilities)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Great catch, and thanks for submitting this to us. I added the missing capability for the general `chat` capability to the general-use capabilities section, immediately before the existing "Read Blocked Messages" capability.
