### ISSUE TITLE
App manifest and identity is way too complicated.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#3111]
I'm at college, and so I don't have a lot of time to do assignments. I've tried using C++/WinRT to do a simple database project in the console. But when I ran the project, It's crashing because the app doesn't have identity. UWP Community Discord members helped me, by linking to this page...

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps

I've copied the AppxManifest.xml file over from that page. And made some obvious edits (this is already several steps too far) but I don't know if this is going to work, there's so much of this doesn't make any sense to me. It's a huge amount of extra knowledge required. 

Now I'm told to run a command line app MakeAppx.exe  .. ahm, WTH! _ Command line tools?

This is all way too complicated, I just want to be working on my assignment. This is all friction, I haven't actually done any programming since last night, because of this barrier. I don't have time for this rubbish. How do you expect new programmers, students and universities to adopt this stuff. Anybody will look at this and their eyes will glaze over, because none of this is required for console apps using standard C++ libraries and legacy systems.

You seriously need to fix all this so that WinRT/UWP security is automated in Visual Studio. We need to be able to write a program and press Build/Run and then send the exe and files in an email and trust that the application will run on a school computer - a network that will certainly not have UWP workloads installed, that will probably have developer mode disabled.

I'm going to have to revert to legacy console for this assignment and every assignment for the next year, it's so disappointing, but I don't have a choice, the extra workload you pile on top of making simple apps is just incredible.

Can this stuff even run on a university computer, do I know my lecturer can just double click the exe and it will run? Even after I spend hours upon hours digesting all this extra material that is irrelevant to learning C++ and irrelevant to my assignment specification. Much of which I still won't understand beyond perhaps finding the fraught pathway to simply make it run.

Please, make this stuff easy. You're just making it more and more complicated to do Windows programming. No wonder python is so popular.

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us, and I'm sorry you're encountering these issues. 

The instructions in this article are specifically for somewhat advanced/niche scenarios where an app developer can't (or doesn't want to) package their desktop app using MSIX, but their app still needs package identity. In this scenario, developers can create a *sparse package* to still grant package identity to their app without having building a full MSIX package for their app. 

Unless you have a specific reason to not want to package your app using MSIX, you can leverage a much simpler process that uses support integrated directly into Visual Studio: add a Windows Application Packaging Project to your solution, add a reference to your app project in that packaging project, and then build as usual. For more details, see [this article](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net#setup-the-windows-application-packaging-project-in-your-solution).

I hope this helps.
