### ISSUE TITLE
For AdaptiveImage, the AlternateText not showing up

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/windows-uwp#3112]
**Question**: Why my following code for a Tile on windows 10 start menu shows the image, but when I hover over the image it does not show the [Alternate Text][1]. What I may be missing here, and how can we make it work?

**Code**:

    public void TileTest()
    {
        TileContent content = new TileContent()
        {
            Visual = new TileVisual()
            {
                TileWide = new TileBinding()
                {
    
                    Content = new TileBindingContentAdaptive()
                    {
                        Children =
                        {
                            new AdaptiveGroup()
                            {
                                Children =
                                {
                                    new AdaptiveSubgroup()
                                    {
                                        HintWeight = 2,
                                        Children =
                                        {
                                            new AdaptiveImage()
                                            {
                                                Source = "Images/MyImages/Test.png",
                                                AlternateText = "Test alternative text"
                                            }
                                        }
                                    }
                                }
                            },
                        }
                    }
                }
            }
        };
    
        TileNotification notification = new TileNotification(content.GetXml());
        TileUpdateManager.CreateTileUpdaterForApplication().Update(notification);
    }

**Remark**: It may not matter, but just in case: I'm using a [Packaged WPF app][2] that is calling UWP/WinRT APIs - using `VS2019 - ver 16.9` and `.NET5` on `Windows 10 Pro - ver 2004`.

  [1]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.notifications.adaptiveimage.alternatetext?view=win-comm-toolkit-dotnet-stable
  [2]: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
