### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Howard20181** [MicrosoftDocs/windows-uwp#3115]
第一个备注中的第3行

`Fn在大多数情况下，) (函数) 密钥不能重新 (映射。 F1 - F12 F13 - F24 可以映射 (和) 密钥。`

括号和翻译错误

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [适用于 Windows 10 的 PowerToys 键盘管理器实用工具](https://docs.microsoft.com/zh-cn/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @crutkas
* Microsoft Alias: **crutkas**

**Comment by Howard20181** [comment]
https://github.com/MicrosoftDocs/windows-uwp.zh-cn/pull/34
https://github.com/Howard20181/windows-uwp.zh-cn/commit/d62185dc851edd5eb1a8b926a9c8802550767653

**Comment by mattwojo** [comment]
Thank you for pointing out this error @Howard20181. Unfortunately this content is machine-translated and I don't currently have a means for making this correction. :(
