### ISSUE TITLE
Request for Removal of Personal Image

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3116]
I would like to request for a replacement picture on this document for this screenshot taken during teams meeting for the following reasons:
- I did not work on the Video conferring tool.
- I was not at my best when that image was taken, i had just woken up and it does not look good.

I don't have to be there on the replacement picture since I did not work on the tool.

Thanks for this!!

 https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/video-conference-mute.md

**Comment by mattwojo** [comment]
Done! :)

https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1532

https://docs.microsoft.com/en-us/windows/powertoys/video-conference-mute
