### ISSUE TITLE
Incorrect div alignment

### ISSUE THREAD

**Issue by bagatka** [MicrosoftDocs/windows-uwp#3120]
# Issue with HTML alignment

There is a problem with HTML element alignment

## Screenshots

**Chrome** Version 90.0.4430.212 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/45293863/118361148-adc2a780-b592-11eb-8d5c-be2f95018a17.png)

**Edge** Version 92.0.884.2 (Official build) dev (64-bit)
![image](https://user-images.githubusercontent.com/45293863/118361223-0e51e480-b593-11eb-8747-9ad809cb3b81.png)

## Details

As I can see, the problem div is:

**div id="affixed-right-container" class="doc-outline position-fixed is-vertically-scrollable"**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5873bf21-4560-102a-a9c8-2ad4e425be49
* Version Independent ID: dea02fb9-f0a7-739d-2926-f92d6d973026
* Content: [Windows 10 game development guide - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/e2e)
* Content Source: [windows-apps-src/gaming/e2e.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/e2e.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @bagatka, I'll investigate this.

-Steve

**Comment by stevewhims** [comment]
I've fixed the rendering issue. I can only infer there was a change in the back-end rendering, because this was rendering fine a while ago. However, I found the single line of content that the renderer didn't like, and changed it.

Thanks!
Steve
