### ISSUE TITLE
Adobe Illustrator image asset templates

### ISSUE THREAD

**Issue by jaymichaud** [MicrosoftDocs/windows-uwp#3121]
[Various](https://blogs.windows.com/windowsdeveloper/2015/10/23/windows-10-uwp-app-templates-for-adobe-photoshop/) [sources](https://www.manuelmeyer.net/2015/10/universal-windows-platform-uwp-design-templates/) mention a set of UWP image asset templates for Adobe Illustrator. Under the **Tools** heading on this page, there is only a Photoshop download, but the Wayback Machine indicates that there [used to be an Illustrator download](https://web.archive.org/web/20190301000000*/https://dev.windows.com/en-us/design/assets) as well in 2019 and earlier. [Related documentation](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos#generating-all-assets-at-once) suggests that vector artwork like Illustrator files works best. Why isn't an Illustrator download still kept up to date and available? Is it possible to get the same quality with Photoshop source image files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Design toolkits and samples for Windows apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hickeys** [comment]
We no longer maintain the Illustrator templates. They were taken down because they were so far out of date with our new UI technologies.
