### ISSUE TITLE
Should call out need for VSIX package

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#3126]
I feel like most getting started docs call out the requirements, which instead here are listed in the introduction.

Installing the VSIX extension is vital to getting started with C++/WinRT as otherwise it doesn't show-up in Visual Studio.

It'd be great to see a pointer here to the Introduction page or calling out the VSIX here and in the overview as well as it's literally the first thing you need to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @michael-hawker, and thanks for filing this issue. The "pointer to the introduction page" is there below the first heading ("A C++/WinRT quick-start"). There's a Note, which begins "For info about setting up Visual Studio for C++/WinRT development—including installing and using the C++/WinRT Visual Studio Extension (VSIX) and the NuGet package (which together provide project template and build support)—see Visual Studio support for C++/WinRT."

I'll go ahead and close the issue, but you can still comment (in case I've made a mistake).

Thanks again!
Steve

**Comment by michael-hawker** [comment]
Thanks @stevewhims, I somehow missed it. Wonder if it's because there's the bigger block of note above it?

**Comment by stevewhims** [comment]
Sounds good, I've moved the Note to the top and made it Important.

Thanks!
Steve
