### ISSUE TITLE
Questions about the wording under 'The GameMain::Run method'

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/windows-uwp#3129]
Regarding the section 'The GameMain::Run method':

1. Should "When your game has focus" be changed to "When your game has focus, is unsnapped, or is resized sufficiently large"? This change, if correct,  would make the author's intent more clear.

2. Regarding the phrase "When the game is not visible, suspended, nor snapped":
    a. What does the word "visible" mean in this context? It is not used in the surrounding text. Instead, "focus", "snapping" and "resizing" are discussed.

    b. GameMain::Run code shown on the webpage uses the variable m_visible, however there is no use of the word "focus" (or variable m_haveFocus, which is used elsewhere in GameMain.cpp), or the word "snap". I understand the code is correct, however it would be helpful to explain how the code shown (and the use of the word "visible" and variable m_visible) relates to focus and snap events, given the discussion of focus and snap on the webpage.

  Thank you,
    Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f3ce549-20ef-7dd6-4d01-b51517013dcb
* Version Independent ID: 95bf84a2-267d-6bc7-00db-0d08e51599e8
* Content: [Define the game's UWP app framework - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--building-the-games-uwp-app-framework#the-gamemainrun-method)
* Content Source: [windows-apps-src/gaming/tutorial--building-the-games-uwp-app-framework.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--building-the-games-uwp-app-framework.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Robert-Tortorelli. To do the investigation and correction work here, I've created an internal work item for myself on my backlog. Since I'm tracking that work internally, I'll temporarily close this issue now and reopen it once I start the work (in the future), and report back here when that's done.

-Steve

**Comment by Robert-Tortorelli** [comment]
Thank you Steve.
  Robert

**Comment by stevewhims** [comment]
Hi, @Robert-Tortorelli. I've published updates to the topic that explain more clearly what the game's logic is doing.

For the first item in your list, the wording should have been around visibility, and not focus. But essentially I updated the two paragraphs immediately before the code example (in the section "The GameMain::Run method") and I added another paragraph. So you can see my changes in the 3 paragraphs immediately before that code example.

Thanks!
Steve

**Comment by Robert-Tortorelli** [comment]
Hi Steve,
Your updates greatly improve readability. Thank you again!

  Regards,
    Robert
