### ISSUE TITLE
Guidance for Configuring .NET Native a bit off

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#3130]
In the configuring section here: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt#configure-for-windows-10-fall-creators-update-100-build-16299

There's a step about trying to determine version numbers from a folder. However, the folder specified isn't the one that it actually tries to import from...

i.e. it says to look in this folder:

DotNetNativeSharedLibary | %ProgramFiles(x86)%\Microsoft SDKs\UWPNuGetPackages\Microsoft.Net.Native.SharedLibrary | 2.2.8-rel-29512-01
-- | -- | --

Which doesn't exist (they all have a `-<arch>` at the end on my system), the imports instead look at:

```xml
  <Import Condition="'$(WindowsTargetPlatformMinVersion)' &gt;= '10.0.16299.0'" Project="$(NugetPath)\runtime.win10-x86.Microsoft.Net.Native.SharedLibrary\$(DotNetNativeSharedLibary)\build\runtime.win10-x86.Microsoft.Net.Native.SharedLibrary.props" />
  <Import Condition="'$(WindowsTargetPlatformMinVersion)' &gt;= '10.0.16299.0'" Project="$(NugetPath)\runtime.win10-x64.Microsoft.Net.Native.SharedLibrary\$(DotNetNativeSharedLibary)\build\runtime.win10-x64.Microsoft.Net.Native.SharedLibrary.props" />
  <Import Condition="'$(WindowsTargetPlatformMinVersion)' &gt;= '10.0.16299.0'" Project="$(NugetPath)\runtime.win10-arm.Microsoft.Net.Native.SharedLibrary\$(DotNetNativeSharedLibary)\build\runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.props" />
```

Which you can see start with `runtime.win10-<arch>.Microsoft.Net.Native.SharedLibrary`.

The `Microsoft.Net.Native.SharedLibrary-<arch>` folders didn't have a similar looking version number to the provided example; however, the `runtime.win10-<arch>.Microsoft.Net.Native.SharedLibrary` folders did. Using that number allowed me to load and compile; otherwise, the project wouldn't load back again as it couldn't find the files needed.

It's also unclear if I have to also reference other nuget packages how those should be resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca2fb23f-7644-1b8d-6b34-cf65c0e0fb9a
* Version Independent ID: 13f2c20d-8a38-7466-105d-0d868f2cd507
* Content: [Authoring a C# Windows Runtime component for use from a C++/WinRT app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt#configure-for-windows-10-fall-creators-update-100-build-16299)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @michael-hawker, I'm investigating the issue.

-Steve

**Comment by stevewhims** [comment]
**UPDATE**: We have some info in our email thread now, so I'll work my way through that info, internalize it, and update the topic, when I get chance. To that end I've created myself a work item on my backlog. So I'll close this GitHub issue for the time being (so that we're not tracking the work twice), and I'll come back here and reopen the issue once I'm working on it.

Thanks!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: The PR to update the topic is complete right now; the changes should be live within 24 hours (and probably a lot sooner than that).

-Steve
