### ISSUE TITLE
Broken link in conditional XAML namespace

### ISSUE THREAD

**Issue by angelazhangmsft** [MicrosoftDocs/windows-uwp#3131]
Link is broken:

https://schemas.microsoft.com/winfx/2006/xaml/presentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3271c1ba-afb1-a77a-1dfc-f441f18dbf3f
* Version Independent ID: 8f0d1919-07c2-f12e-c3c5-e5a9f164d52e
* Content: [Conditional XAML - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml#feedback)
* Content Source: [windows-apps-src/debug-test-perf/conditional-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/conditional-xaml.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! Fixed.
