### ISSUE TITLE
Documentation seems to state that UWP XAML label UI behaves in a way that it doesn't behave

### ISSUE THREAD

**Issue by guybark** [MicrosoftDocs/windows-uwp#3138]
[Enter feedback here]
On this page, the documentation states: "If you use this pattern, when the user clicks the label, the focus moves to the associated control and assistive technologies can use the label text as the accessible name for the form field." I'm really not clear what that statement's describing. The LabeledBy approach is used to set a control's UIA Name property, and as far as I know, it's not related to clicking on the visual label that's located nearby. Typically the UI element referenced by LabeledBy is a TextBlock, and that's not interactable. I've never seen the action of clicking on it having any effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58e91f4-3217-dc9d-4c9a-a5c1be56673f
* Version Independent ID: 957fb065-e223-b686-beaa-c96727b90b29
* Content: [Expose basic accessibility information - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/basic-accessibility-information#labels-and-labeledby)
* Content Source: [windows-apps-src/design/accessibility/basic-accessibility-information.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/basic-accessibility-information.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @guybark - thanks for the feedback. Sorry for the lag in addressing it. The topic has been updated.
