### ISSUE TITLE
xaml-basics-ui.md Part 4: Modify the item container style

### ISSUE THREAD

**Issue by binaryfunt** [MicrosoftDocs/windows-uwp#314]
I'm not sure what's going on when I follow the instructions at [Part 4 of XAML-basics-ui.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-ui.md#part-4-modify-the-item-container-style).

> 1. In Document Outline, right-click ImageGridView. On the context menu, select Edit Additional Templates > Edit Generated Item Container (ItemContainerStyle) > Edit a Copy.... The Create Resource dialog opens.
> 1. In the dialog, change the Name (key) value to ImageGridView_DefaultItemContainerStyle, then click OK.

Instead of getting

    <Style x:Key="ImageGridView_DefaultItemContainerStyle" TargetType="GridViewItem">
        <Setter Property="FontFamily" Value="{ThemeResource ContentControlThemeFontFamily}"/>
        <Setter Property="FontSize" Value="{ThemeResource ControlContentThemeFontSize}"/>
        <Setter Property="Background" Value="{ThemeResource GridViewItemBackground}"/>
        <Setter Property="Foreground" Value="{ThemeResource GridViewItemForeground}"/>
        
    </Style>

I instead get

    <Style x:Key="ImageGridView_DefaultItemContainerStyle" TargetType="GridView">
        <Setter Property="Padding" Value="0,0,0,10"/>
        <Setter Property="IsTabStop" Value="False"/>
        <Setter Property="TabNavigation" Value="Once"/>
        <Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Disabled"/>
        
    </Style>

Note the `TargetType` is `GridView` instead of the `GridViewItem` that the instructions say it will be.

When I start debugging, an uncaught exception occurs. This also happens if I delete all the Setters and just have `<Style x:Key="ImageGridView_DefaultItemContainerStyle" TargetType="GridView"/>`. Changing the `TargetType` to `GridViewItem` makes it work.

I don't know if the instructions are wrong or if it is a problem in Visual Studio?

**Comment by binaryfunt** [comment]
**Visual Studio Info**

Microsoft Visual Studio Community 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA353

Visual C# 2017   00369-60000-00001-AA353

Application Insights Tools for Visual Studio Package   8.10.01106.1

ASP.NET and Web Tools 2017   15.0.31129.0

Common Azure Tools   1.10

JavaScript Language Service   2.0

JavaScript Project System   2.0

JavaScript UWP Project System   2.0

Microsoft JVM Debugger   1.0

Microsoft MI-Based Debugger   1.0

Microsoft Visual Studio VC Package   1.0

NuGet Package Manager   4.5.0

TypeScript Tools   15.5.11025.1

Visual Studio Code Debug Adapter Host Package   1.0

Visual Studio Tools for Universal Windows Apps   15.0.27130.2036

**Comment by ginami** [comment]
Thanks @binaryfunt for bringing this to our attention. @jwmsft can you address this question?

**Comment by jwmsft** [comment]
I tested the steps, and they worked as written.

If the Style's TargetType was GridView, it looks like you might have selected *Edit Template* from the context menu. This will create a GridView style and set it as the `Style` on the grid view.

Instead, be sure to select *Edit Additional Templates > Edit Generated Item Container (ItemContainerStyle)*. This will create a GridViewItem style and set it as the `ItemContainerStyle` on the grid view.

**Comment by binaryfunt** [comment]
I'm pretty sure I was clicking ItemContainerStyle. Regardless, I can no longer reproduce. I'm now on

Version 15.6.1
VisualStudio.15.Release/15.6.1+27428.2002
Microsoft .NET Framework
Version 4.7.02556

Application Insights Tools for Visual Studio Package   8.11.10212.1

ASP.NET and Web Tools 2017   15.0.40214.0

C# Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019

Visual Basic Tools   2.7.0-beta3-62620-07. Commit Hash: e873e69306527a0424e97af2985370556f474019

Visual Studio Tools for Universal Windows Apps   15.0.27428.01

**Comment by jwmsft** [comment]
Glad it's working now. Thanks for the VS info.
