### ISSUE TITLE
Powertory copyright of commerce using

### ISSUE THREAD

**Issue by neozhang200926** [MicrosoftDocs/windows-uwp#3140]
Can enterprise users use it for free forever？
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @neozhang200926 - There is license info in the PowerToys product repo, here:
https://github.com/microsoft/PowerToys

It is a MIT license OSS project:  
https://github.com/microsoft/PowerToys/blob/master/LICENSE
