### ISSUE TITLE
Example of disabled accelerator is wrong

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/windows-uwp#3141]
This text:
"If a control is disabled, the associated accelerator is also disabled. In the following example, because the IsEnabled property of the ListView is set to false, the associated Control+A accelerator can't be invoked."

Is not true, as the following example does not have a disabled ListView. Instead, in the next example the KeyboardAccelerator is disabled explicitly. 

Please update example or description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d15a60b-7f90-38b9-18a2-a4437628e67a
* Version Independent ID: cb3c6a7a-c3df-1599-fe25-681ae66e0f49
* Content: [Keyboard accelerators - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @Marv51 - I believe the code snippets have been updated to address this issue.
