### ISSUE TITLE
Confusing page image explanation

### ISSUE THREAD

**Issue by Elderry** [MicrosoftDocs/windows-uwp#3148]
At the end of the page, [List with update](https://docs.microsoft.com/en-us/windows/package-manager/winget/list#list-with-update) section, it claims:
> In the image below, you will notice the preview version of Terminal has an update available.

and here is the image mentioned: ![image](https://user-images.githubusercontent.com/1892221/120054639-a9eb5680-c063-11eb-8cac-1a37ab9dea44.png)
I can only see **one** version number for preview version of terminal, with no available update version displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcd2ee1-04fd-c7be-adee-72faa345ebb7
* Version Independent ID: a44a4676-c56a-712a-eba2-11e5335c6764
* Content: [list Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/list)
* Content Source: [hub/package-manager/winget/list.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/list.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Yikes!  Thanks for pointing this out.  I will update right away.

**Comment by KevinLaMS** [comment]
An update has been pushed.  Thanks for your patience.

**Comment by KevinLaMS** [comment]
An update has been pushed. Thanks for your patience.
