### ISSUE TITLE
Local toast notification needs C++/WinRT content

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3149]
There are a number of problems with this page:
1. the C++ examples are for C++/CX, we should be discouraging its use and instead point people to C++/WinRT
2. it uses the Windows Community Toolkit nuget package which is C# and therefore doesn't interop well with C++

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2d683e-48f7-2884-5b47-7189b89feee0
* Version Independent ID: d5850926-5624-91ab-60b5-4393ad06f469
* Content: [Send a local toast notification from a C++ UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-cpp-uwp)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-cpp-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-cpp-uwp.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
