### ISSUE TITLE
Value of `eventCount` field

### ISSUE THREAD

**Issue by artemshadrunov** [MicrosoftDocs/windows-uwp#3150]
Hello!

First of all, thank you for the very useful article!
I have question about meaning of the value of `eventCount` field that represented in example in the article. According to description `eventCount` is `The number of events that are attributed to this error for the specified aggregation level.` and I thought that it can be only integer. Like 3 errors per day\week\etc. But as I can see in your example it is not. The same thing I can see in my own data. And it's a little bit confusing because I can't imagine how can be 2 and a half of an error per day 😄

So, can you explain me the meaning of this `"eventCount": 0.0012422360248447205` please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790006f7-ccf8-2ad9-a10f-9346a2c93c3e
* Version Independent ID: 3aa1b8a8-c2a2-4857-e1cc-a75fc04839c8
* Content: [Get error reporting data for your desktop application - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-desktop-application-error-reporting-data#response-example)
* Content Source: [windows-apps-src/monetize/get-desktop-application-error-reporting-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-desktop-application-error-reporting-data.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by artemshadrunov** [comment]
Any movements here?

**Comment by hickeys** [comment]
My suspicion is that there's some averaging going on somewhere (e.g. one event per month = 0.25 events per week) That... doesn't really seem like what you'd expect though. I've emailed the engineering team to get some official clarification

**Comment by hickeys** [comment]
I was sort of correct. These values are being calculated based on bucketing aggregated errors and then averaging them based on... well I'm not quite sure. The takeaway from my conversation with the engineers is that this is a good indication of the error count even if it doesn't technically make sense. I'm going to apply 1.756 closes to this issue.

**Comment by artemshadrunov** [comment]
Well 0.42 of thanks for this answer 😀
