### ISSUE TITLE
Broken Link: Reveal Highlight

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3152]
All the links that point to the page 'Reveal Highlight' are apparently broken. The URL as indexed by Google is `https://docs.microsoft.com/en-us/windows/uwp/style/reveal`. But when one tries to open this link, we are redirected to `https://docs.microsoft.com/en-us/windows/uwp/design/style/`. I also tried it another way: I visited the page 'Reveal Focus', and then I tried visiting the 'Reveal Highlight' page from the See Also section. But the same thing happened again.

Apparently, the page has been removed. I have no idea whether it was done intentionally or by mistake.

**Comment by alvinashcraft** [comment]
#reassign:alvinashcraft

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. The Reveal Highlight feature has been removed, and we are removing references to it in our documentation. The docs for this Reveal Focus page have been updated and merged to our internal repo, and the changes should be visible on the public page soon. 

This Issue will be marked as Closed, but we will monitor any replies that come afterwards. Many thanks!
#please-close
