### ISSUE TITLE
How to see if update is available

### ISSUE THREAD

**Issue by DarthPjotr** [MicrosoftDocs/windows-uwp#3153]
You state that you can see if an update is available, but I do not see any difference. What am I supposed to look at? Is there a way to list the updates only by a filter or query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcd2ee1-04fd-c7be-adee-72faa345ebb7
* Version Independent ID: a44a4676-c56a-712a-eba2-11e5335c6764
* Content: [list Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/list)
* Content Source: [hub/package-manager/winget/list.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/list.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Thanks for the query.  
If there are no updates for your app, then there will not be an update listed.  I will update the docs to mention this.
 
![image](https://user-images.githubusercontent.com/2146880/120698453-f1a71f00-c463-11eb-8f0d-6c4e5432f3a7.png)

If there are no know updates, then list will not show the available.
![image](https://user-images.githubusercontent.com/2146880/120698669-3468f700-c464-11eb-8a3b-eab62b95b500.png)

Yes, you can filter as well. Please see how I filtered on PowerBi in the second example.

**Comment by KevinLaMS** [comment]
I noticed your issue with the image not including the update. I will make that fix.

**Comment by KevinLaMS** [comment]
An update has been pushed.  Thanks for your patience.

**Comment by KevinLaMS** [comment]
An update has been pushed. Thanks for your patience.
