### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by MOrlassino** [MicrosoftDocs/windows-uwp#3155]
[Enter feedback here]
Spelling mistake... Is currently -> "...either a binary excutable (binary for short)...", Should be -> "... executable ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f7d168-6f67-5eec-1acb-92251b259b4d
* Version Independent ID: 87ea4a7b-9bb8-995f-5044-280bd25e9a7c
* Content: [Overview of developing on Windows with Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/overview)
* Content Source: [hub/dev-environment/rust/overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/overview.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @MOrlassino! I've published a fix to that typo now.

-Steve
