### ISSUE TITLE
Update "Brokered Windows Runtime components for a side-loaded UWP app" to work in VS 2019

### ISSUE THREAD

**Issue by mavaa** [MicrosoftDocs/windows-uwp#3158]
[Enter feedback here]

This article needs an update to be compatible with VS 2019:

The following text:

```
Step 1: Create a new class library in Visual Studio. Make sure to create the project using the Class Library template, and not the Windows Runtime Component template.
```

Please make it clear what kind of Class Library should be created - .NET Framework, Core, Universal Windows, other?

In addition, the postbuild script for "Step 4" does not seem to work, I tried the VS 2017 one. If I chose the wrong Class library type (.NET Core), that might be why it didn't work for me.

Finally, the "Brokered WinRT Component Project Templates for Windows 10 and VS 2015" linked under resources are also incompatible with VS 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035dc258-0b10-81fb-fbdc-2c046280e915
* Version Independent ID: 1b56528b-3f98-0ccd-c95a-4e6cd1f15879
* Content: [Brokered Windows Runtime components for a side-loaded UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/brokered-windows-runtime-components-for-side-loaded-windows-store-apps)
* Content Source: [windows-apps-src/winrt-components/brokered-windows-runtime-components-for-side-loaded-windows-store-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/brokered-windows-runtime-components-for-side-loaded-windows-store-apps.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mavaa, and thanks for filing this issue. Yes, the topic does look out of date and in need of both updating and adding more clarity. I've created a backlog work item for myself (with a link to this issue) to review the topic and possibly get updated info from the feature team. Once that work item reaches the front of my queue, I'll return here and reactivate this issue and report my progress. Until then, to avoid tracking the work in two places, I'll temporarily close this issue.

Thanks again!
Steve
