### ISSUE TITLE
Dead links to win32 speech SDK's

### ISSUE THREAD

**Issue by WouterVanNifterick** [MicrosoftDocs/windows-uwp#3162]
[Enter feedback here]
The links to the win32 SDK's point to a microsoft site, but they're 404 dead...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5532269-6b52-2288-ddf1-8c2e8d52e2db
* Version Independent ID: 9106566d-48f5-25fa-67d6-978ac385dff9
* Content: [Speech, voice, and conversation in Windows 10 - Windows applications](https://docs.microsoft.com/en-us/windows/apps/speech)
* Content Source: [hub/apps/speech.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/speech.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @WouterVanNifterick - sorry for the delay. These downloads have been reactivated and the links work again.
