### ISSUE TITLE
Example from "Set access key scope" appears to be wrong.

### ISSUE THREAD

**Issue by fmokren** [MicrosoftDocs/windows-uwp#3163]
The example XAML shows the "Favorite" AppBarToggleButton access key is "V", but the image shows it as "T".

Likewise the XAML has "T" for the secondary command "Setting", but the image shows "S".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80f24bef-6dfe-9b8b-e6aa-5582f231e28a
* Version Independent ID: f910182d-b917-121c-fc81-e39139f5faa3
* Content: [Access keys design guidelines - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys)
* Content Source: [windows-apps-src/design/input/access-keys.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/access-keys.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic revised to correct issue.
