### ISSUE TITLE
Dead documentation links in section "Showing a message box"

### ISSUE THREAD

**Issue by ts-62020** [MicrosoftDocs/windows-uwp#3166]
There are dead links in the paragraph

> And finally add code to call the MessageBoxA function (also see MessageBoxA in the Rust documentation for the Windows API, which includes a link to MESSAGEBOX_STYLE).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @ts-62020. I've updated the links to point to the new destination urls.

-Steve
