### ISSUE TITLE
casing of field names in examples is wrong

### ISSUE THREAD

**Issue by donid** [MicrosoftDocs/windows-uwp#3167]
The given examples result in errors during Manifest-Validation:
"PackageURL" and other URL fields in the examples should be "PackageUrl" (PascalCased)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657479f-c0b7-6358-c7d0-0402215edaa5
* Version Independent ID: 8976699b-cdba-5206-bdb0-8a0875acfe45
* Content: [Create your package manifest](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example)
* Content Source: [hub/package-manager/package/manifest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/manifest.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Thanks for the report.  I will queue up a change.
