### ISSUE TITLE
Talk, talk, talk

### ISSUE THREAD

**Issue by LenYates** [MicrosoftDocs/windows-uwp#3171]
I would like to start a "flight group".  Your page has an abundance of words to help me know what a flight group is.  Ok, so now I want to start one.  Where do I click?  So many of your web pages are like this.  Tons of talk, but when I'm ready to do it, where is the "door"?  There isn't one!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17105757-d0a7-1427-6461-0c98f1a6ffa2
* Version Independent ID: e6f704bd-5b5e-d601-81bd-c92e1301bdd8
* Content: [Package flights - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights)
* Content Source: [windows-apps-src/publish/package-flights.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/package-flights.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
The document has been updated:

**Create a new package flight**

After you have published a submission for your app, you'll see a Package flights section on the App overview page. Click New package flight to get started.

If you haven't created any known user groups yet, you'll be prompted to create one before you can proceed. For more info, see [Create known user groups](https://learn.microsoft.com/en-us/windows/apps/publish/create-known-user-groups). You can create a new known user group directly from this page by selecting Create a flight group.

On the package flight creation page, you'll need to enter a name for your flight and specify at least one flight group. Once you've done so, select Create flight. You won't be able to change these details later (though if you're not happy with what you've entered, you can delete this flight and create a new one to use instead).
