### ISSUE TITLE
Documentation of Chinese(Especially PowerToys)Needed

### ISSUE THREAD

**Issue by Raspberry-Monster** [MicrosoftDocs/windows-uwp#3172]
As far as I know, the translation of documentations for Universal Windows Programs is still using machine-translated version. And it is well-known that there will be some words get mis-translate. PowerToys is one of the most popular Microsoft-provided programs in China because it can make works on Windows 10 more efficient. But if there are some mis-translated words, it may be difficult for some user to get help. And there is no Chinese-translated repository for it. So please set-up a repository to let it  gets translated by volunteers. Thank you.

**Comment by mattwojo** [comment]
Thank you for the suggestion @Raspberry-Monster. I know that the machine translation is not great. Unfortunately I don't currently have support or capacity for setting up a volunteer-translation repo. *However, these docs are open-source so I believe that anyone can fork and translate. It woudn't show up on the docs.microsoft.com site (and we don't currently have support for reviewing volunteer translations to publish them there), but it would be available via markdown preview in the forked repo. Just an idea.
