### ISSUE TITLE
Missing requirements details

### ISSUE THREAD

**Issue by nlsdg** [MicrosoftDocs/windows-uwp#3173]
In section 1.2.3 the last sentence ends with "subject to the following requirements:".
But there are no requirements listed. Not directly in the text, and not by following sub-sections. It just continues with section 1.3

The requirements should be added or linked, or the "subject to the following requirements:' part of the sentence removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c65b220-a04b-e8a2-e1bc-0a9415194609
* Version Independent ID: 9c06f7b6-9a94-3206-2cf5-e497965fd881
* Content: [Windows Package Manager repository policies](https://docs.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies)
* Content Source: [hub/package-manager/package/windows-package-manager-policies.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/windows-package-manager-policies.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Thanks for the report.  I will investigate.

**Comment by KevinLaMS** [comment]
Sentence removed
