### ISSUE TITLE
RSS Reader Tutorial

### ISSUE THREAD

**Issue by whoiskevinrich** [MicrosoftDocs/windows-uwp#3174]
Please provide link for referenced codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @whoiskevinrich. I'm not sure what you mean by "referenced codes". Could you quote (or somehow describe) the part of the topic that you're thinking of that's wrong? And what you'd expect to see there instead?

Are you referring to the source code examples there, by any chance?

Many thanks,
Steve

**Comment by whoiskevinrich** [comment]
Yes, there are some inline code examples, but it would be helpful to see the context of the entire project.

**Comment by stevewhims** [comment]
Thanks, @whoiskevinrich. The topic is designed so that you follow the steps and build the project. Once you've followed along with the topic, followed the steps I mean, then you'll have the context of the entire project.

Many thanks!
Steve
