### ISSUE TITLE
Which app is causing this message

### ISSUE THREAD

**Issue by skibum42** [MicrosoftDocs/windows-uwp#3176]
While this page is a good explanation of how to run PowerToys when other apps are running in admin mode, it would be useful to know which app is causing the blocking.  I suspect malware is running and PowerToys might be the ideal way to identify the process that I'm looking for.  Just a suggestion for an enhancement to make PowerToys more useful.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bd5eaf-0982-6fe8-09d2-17e4373886bb
* Version Independent ID: 5e66eda4-be07-4afd-7187-3e4d896f7861
* Content: [PowerToys administrator mode for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/administrator)
* Content Source: [hub/powertoys/administrator.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/administrator.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @skibum42. I'm sure that I'm completely clear on what you're asking for, but it sounds more like a feature request than a doc update, so I'm going to close this and point you toward the PowerToys product repo if you'd like to file a feature request issue there: https://github.com/microsoft/PowerToys/issues

Or if you're interested in contributing to creating such a feature, here's a link to ways to contibute: https://docs.microsoft.com/en-us/windows/powertoys/#contribute-to-powertoys-open-source

Thanks again!
