### ISSUE TITLE
Diagram is not visible when using dark theme browser setting 

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/windows-uwp#3177]
The following diagram is not visible when using the dark theme browser setting:
![image](https://user-images.githubusercontent.com/18313964/122314267-bcbbb300-cecc-11eb-8988-d1743b034e39.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8132995-4d33-d547-f743-37cd3b3f15c4
* Version Independent ID: 19465bc3-648d-6576-ea62-5b23b50531d5
* Content: [Best practices for writing to files - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/best-practices-for-writing-to-files)
* Content Source: [windows-apps-src/files/best-practices-for-writing-to-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/best-practices-for-writing-to-files.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Our bad. Working on fixing it.

**Comment by GrantMeStrength** [comment]
Image updated. Thanks!
