### ISSUE TITLE
Circuitous link in doc

### ISSUE THREAD

**Issue by kartva** [MicrosoftDocs/windows-uwp#3179]
In the [`Related Topics`](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/printing-and-scanning) section, there is a bullet point which mentions [`Design guidelines for printing`](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/printing-and-scanning) but infact redirects to the same page which is being viewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e545d9a-54ef-3427-32c3-a9eb80f9c822
* Version Independent ID: 1e10a34c-6b31-14bb-a8f3-e9cf4f75aa3a
* Content: [Printing and scanning - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/printing-and-scanning)
* Content Source: [windows-apps-src/devices-sensors/printing-and-scanning.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/printing-and-scanning.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for letting us know. Link has been deleted.
