### ISSUE TITLE
worse articles are from you guys. nothing is working here

### ISSUE THREAD

**Issue by navid-farjad** [MicrosoftDocs/windows-uwp#3185]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1603df77-580d-a332-ace4-10c4b6f1484b
* Version Independent ID: 7f70b8d6-5146-f327-86c8-9c17acbcac23
* Content: [Associate Azure Active Directory with your Partner Center account - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-partner-center)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-partner-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-partner-center.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for this feedback. Can you be a little more specific? What parts of the page are not working for you?

**Comment by hickeys** [comment]
Closing this issue. Please reopen if you'd like to describe your issue a little more.
