### ISSUE TITLE
More examples on sending toast notifications from Win32 apps

### ISSUE THREAD

**Issue by suzukieng** [MicrosoftDocs/windows-uwp#3186]
Hi Microsoft,

I've successfully used your guide to send toast notifications from a Win32 DLL loaded into a Java application and invoked via JNA. I realize it's probably a bit of an unusual setup but it's an existing application and so far it works.
What I'm missing from the guide are scheduled notifications, adding tags to notifications, and setting the expiration time on a notification.

As I'm unfamiliar with native Win32 C++ / COM development this is non-trivial for me, and also the API seems to be slightly different (e.g. notifier->Show() returns an HRESULT but in C# it returns the toast to which a tag and expiration time can be added).

Is there perhaps additional documentation or sample code on how to achieve this?

Kind Regards
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74f1f732-1dc0-a940-e85b-7559d268f09e
* Version Independent ID: f563b790-3236-3f2a-1f02-a46b47ee469c
* Content: [Send a local toast notification from Win32 C++ WRL apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#step-8-handling-activation)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by sebkur** [comment]
>I've successfully used your guide to send toast notifications from a Win32 DLL loaded into a Java application and invoked via JNA.

@suzukieng I'm looking for exactly that. I found https://github.com/ootime/jWinToast but it seems like a rather complicated approach, so I'm wondering if you could share your solution?

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
