### ISSUE TITLE
MediaFrame processing: Which devices applicaple/not applicable?

### ISSUE THREAD

**Issue by cwule** [MicrosoftDocs/windows-uwp#3188]
While the documentation of the whole MediaFrame processing is great and easy to follow, I believe there are currently mainly two up-to-date Microsoft devices where this API is useful for retrieving depth frames (Azure Kinect and Hololens 2), however it seems that it cannot be actually used at least for one of them, the Hololens 2. It would be helpful to state known compatible/not compatible devices in the documentation. That would prevent frustration if users try it out only to find out it does not actually work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db4165a7-748e-e566-3b38-21ad71a76489
* Version Independent ID: d8762b7e-22b0-cfd6-25b0-5e2a68cdea9f
* Content: [Process media frames with MediaFrameReader - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-media-frames-with-mediaframereader)
* Content Source: [windows-apps-src/audio-video-camera/process-media-frames-with-mediaframereader.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/process-media-frames-with-mediaframereader.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Sorry I don't have a better answer, but the camera feature team has stated that they are actively working on this feature right now and don't have information on current devices that support the feature. They did suggest that if it's not working on Hololens 2, that you might want to seek HoloLens 2 support. I.e. It might be a Hololens bug and not an issue with the Windows SDK API. 

I would recommend searching and/or posting over on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).
