### ISSUE TITLE
pip doesn't work in WSL2

### ISSUE THREAD

**Issue by robert-dzikowski** [MicrosoftDocs/windows-uwp#3189]
I use WSL2 (Ubuntu 20.04 LTS) in Windows 10.
pip doesn't work, pip -V works, but pip list or pip3 list hangs.

**Comment by mattwojo** [comment]
Hmm. Thanks for raising this @robert-dzikowski. I'm going to point you to the product repo issues, as it looks like there is already a thread related to this: https://github.com/microsoft/WSL/issues/4020

Currently, it looks like there's a few different issues that it could be, but nothing that would require a documentation update. Please re-open this issue if it is looking like it would be beneficial for me to add something about this to the docs.
