### ISSUE TITLE
End of support is the same as the release date...

### ISSUE THREAD

**Issue by AdamantiumKiwi** [MicrosoftDocs/windows-uwp#3190]
Release date for 0.8.0 = 6/24/2021
End of support date for 0.8.0 = 6/24/2021
Surely not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d1132c-974a-7dbc-6c46-2ebbc47e9944
* Version Independent ID: 732091d2-ebcd-dc09-7ed1-ac339ecf834d
* Content: [Windows App SDK release channels - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/release-channels)
* Content Source: [hub/apps/windows-app-sdk/release-channels.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/release-channels.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by mcleanbyron** [comment]
Thank you for reporting this. The correct end of support date for that release is 6/24/2022. We have updated the article.
