### ISSUE TITLE
Layering and Elevation links are not working

### ISSUE THREAD

**Issue by vgromfeld** [MicrosoftDocs/windows-uwp#3197]
None of the Layering and Elevation links are working in this page.
They should all link to https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/layering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ed6c4c-dc18-1e28-c4b2-4df28a8a16af
* Version Independent ID: f29fe81d-d026-9f73-943a-f56708022042
* Content: [Mica material - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/style/mica)
* Content Source: [hub/apps/design/style/mica.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/style/mica.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The links are fixed.
