### ISSUE TITLE
Localize your WinUI desktop app Is GUI-based not XML file-based

### ISSUE THREAD

**Issue by davework26** [MicrosoftDocs/windows-uwp#3198]
The results of carrying out the instructions in the section "Localize your WinUI desktop app" do not correspond those in the document. The instructions are out of date with VS 2019.

The document refers to opening the file package.appxmanifest to edit the XML contents. In VS 2019, opening this file results in displaying a GUI screen with multiple tabs, rather than an editable XML file.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?tabs=desktop-csharp)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
@anawishnoff

**Comment by anawishnoff** [comment]
Hi @davework26, I see the confusion here. In VS 2019 if you right click on the package.appxmanifest file and select "View Code", it will open the editable XML file. The instructions in this doc specify to open the file in a text editor because the default behavior of opening this file in VS 2019 presents you with a GUI editor as you described.

**Comment by davework26** [comment]
Hi Ana,

Thanks for the clarification – I’ve reread the document and noticed the text editor requirement. Is there anything you want me to do now (e.g. close the issue)?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by hkhmsft** [comment]
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback!
