### ISSUE TITLE
winget install parameter missing

### ISSUE THREAD

**Issue by michha** [MicrosoftDocs/windows-uwp#3199]
winget install documentation ([live link](https://docs.microsoft.com/en-us/windows/package-manager/winget/install)) misses the parameters
- --scope
- --locale
- --force

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73bd6478-de0f-6aa9-fb31-0818abdb7f68
* Version Independent ID: f5ff6ecd-0231-d438-7301-6eb20863ec50
* Content: [install Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/install)
* Content Source: [hub/package-manager/winget/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/install.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by KevinLaMS** [comment]
Checked the page.  This has been resolved.

**Comment by KevinLaMS** [comment]
The install page covers these issues.
