### ISSUE TITLE
Mistake in "The quick brown fox ..."

### ISSUE THREAD

**Issue by seb-giroux** [MicrosoftDocs/windows-uwp#3200]
The first image should say "The quick brown fox jumps over the lazy dog", otherwise you're missing the "s" ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94d411c-212f-d301-5ed2-4b5cb3e9b897
* Version Independent ID: bc4d9a15-03d1-cbc4-1dff-0d44dd1c2b35
* Content: [Typography in Windows 11 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/typography)
* Content Source: [hub/apps/design/signature-experiences/typography.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/signature-experiences/typography.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
To be fair, the fox may have jumped over the lazy dogs. Either way, you have a point. 

I've emailed the designers and I'll update the image once they send me something.

**Comment by Jay-o-Way** [comment]
Either that, or "the quick brown fox jumped over the lazy dog's back"

**Comment by hickeys** [comment]
The designers agree that we should update this image, but it's relatively low priority. It's being tracked internally so I'm going to close this issue even though I haven't actually updated the image. Not really the resolution anyone was hoping for, but there's only so much I can do.
