### ISSUE TITLE
please add x64 emulation information

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/windows-uwp#3204]
[Enter feedback here]
now that 64-bit emulation is included in Windows on Arm, it would be great to have this page cover the equivalent x64 details alongside x86

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db13c025-79fe-c653-0af6-21de3e222904
* Version Independent ID: ce11f952-23ff-420b-b8fd-0159b7171d69
* Content: [How x86 and ARM32 emulation work on ARM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm-x86-emulation)
* Content Source: [windows-apps-src/porting/apps-on-arm-x86-emulation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm-x86-emulation.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
Apologies for the long delay in attending to this issue. The Content url above is out of date (the content must have been moved, so the url 404s).

-Steve
