### ISSUE TITLE
Link in paragraph 404

### ISSUE THREAD

**Issue by elixrrr** [MicrosoftDocs/windows-uwp#3206]
Next: Fluent Design System
If you'd like to learn about the principles behind Fluent Design (Microsoft's design system) and see more features you can incorporate into your UWP app, continue on to <Fluent Design System>.

Link for Fluent Design System does not work for some reason 

https://docs.microsoft.com/en-us/hub/apps/design/index

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c27bacf-0508-e222-a748-d6a9737c0f23
* Version Independent ID: 18eeb376-c078-9672-3d14-bf7f35ceb8aa
* Content: [Introduction to Windows app design (Windows apps) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/basics/design-and-ui-intro)
* Content Source: [hub/apps/design/basics/design-and-ui-intro.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/basics/design-and-ui-intro.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The link is fixed.
