### ISSUE TITLE
`Download the XAML Controls Gallery sample` Link does not work

### ISSUE THREAD

**Issue by EddyHaigh** [MicrosoftDocs/windows-uwp#3207]
`Download the XAML Controls Gallery sample` Link does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64559e01-a1bb-7417-1261-d4c1e16d07c8
* Version Independent ID: 105e0a73-9844-6ebd-41c4-2f4c4c5811bb
* Content: [Design toolkits and samples for Windows apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/downloads/#want-more-code)
* Content Source: [hub/apps/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/downloads/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The link is fixed.
