### ISSUE TITLE
Sample code issues

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/windows-uwp#3208]
It states "...and we won't be showing the using statements or the definition of the class scope again in the snippets until we show the final code" and then there is no final code section, the usings are not shown again.

In the MeasureOverride code there is a returnSize variable declared that isn't used. 

The code for LimitUnboundedSize has a comment that starts with "This method is called only if one of the availableSize..." but as far as I can tell it is always called regardless of what availableSize is set to.

In the Refinement section the property is declared as UseSquareCells but then is later referred to by the name UseOppositeRCRatio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cda75f7-1ca1-75c6-87dc-842172f6c6d6
* Version Independent ID: 739f61da-913f-2a16-50a4-3607de40ed9d
* Content: [BoxPanel, an example custom panel (Windows apps) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/layout/boxpanel-example-custom-panel)
* Content Source: [hub/apps/design/layout/boxpanel-example-custom-panel.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/layout/boxpanel-example-custom-panel.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for the feedback. The issues you describe suggest that there used to be a link to a complete sample at the end of this article, but that at some point the link was removed. My suspicion is that the sample was moved, resulting in a broken link, and then eventually the broken link was removed too.

The best fix would be to restore the link and leave the page as-is. Unfortunately, a quick search didn't turn up the sample. I'm going to leave this open while I continue to search.

**Comment by hickeys** [comment]
I have been unable to locate the sample. I've cleaned up the snippets as best I can based on your feedback. If you think more changes are required, please reopen this issue.
