### ISSUE TITLE
Not possible to restore old shortcut guide hotkey? (hold win key to open, release to close)

### ISSUE THREAD

**Issue by aminomancer** [MicrosoftDocs/windows-uwp#3210]
I preferred the previous way to open the shortcut guide. If I was unsure what to press I'd just naturally end up holding the win key anyway so this felt very useful. I mean, think about this — what's the point in memorizing a specific 3-key combination to open a menu whose sole purpose is to show you all the key combinations that you couldn't memorize? If I was likely to remember such a hotkey I wouldn't need a shortcut guide in the first place.

As it stands, if I'm trying to remember which key I need to press, I'm way more likely to just press a couple keys until I get it right than press some specific hotkey just to open the shortcut guide, then hit escape and press a whole other key combination to do what I was actually trying to do. The whole genius of the old hotkey was I could hold the win key, see what I needed to press, then just press the key. If the key was "E" then I wouldn't have to let go of the win key, I could just hold it until the guide appears, then press "E" and the key would still work.

I know I can still hold the win key for most of the shortcuts listed in the guide, but it requires me to hold win key, press and release shift + slash, then press another key. Which is enormously more complicated than what I used to do. I have already tried to simplify it by removing the shift key from the combination. Even bound to win + slash it's so convoluted I don't think I'll ever use it.

I assume there must be some good reason this was changed. Why get rid of such an ingenious key binding if it doesn't somehow break something? Maybe there's a specific key combination that doesn't work if you're holding down the win key, or if the shortcut guide is open. Nevertheless, it would be useful to at least get the *option* back, for those of us who would rather break some aspects of the shortcut guide than to just never use it at all in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c39e7c8-7ab6-3297-1554-d7ef10d46894
* Version Independent ID: 021ad68a-284a-fd90-4404-463f08301b04
* Content: [PowerToys Shortcut Guide utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/shortcut-guide#feedback)
* Content Source: [hub/powertoys/shortcut-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/shortcut-guide.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Timarzi** [comment]
I reached this page when trying to find out why the shortcut change, and agree with the comment above. I liked the long Windows shortcut better if we can have that, please.

**Comment by killEGOs** [comment]
I completely agree with this post as well. I LOVED the old way of just holding the "win" key for the shortcut guide... Was so useful. If possibly, please bring that option available again.

**Comment by ghost** [comment]
Can't agree more.

**Comment by mattwojo** [comment]
I need to redirect this issue to the PowerToys product repo: https://github.com/microsoft/PowerToys/issues/
This repo is specific to the docs and making sure that we've got everything documented correctly, whereas this particular issue/request would be a change in the product.... so you'll need to get the issue in front of the folks who do the development.
It looks like there's a related issue here: https://github.com/microsoft/PowerToys/issues/12179 ...not sure if you want to add on to that or start a new issue as this isn't really about a bug, rather a preference for how the command is handled. 
If this does result in a change, please re-open this issue so that I can update the docs. 
Thanks @aminomancer / all!

**Comment by mattwojo** [comment]
Looks like the product team is tracking this issue here: [Rethink how we handle shortcut guide 0.41 change of behavior for Winkey · Issue #11963 · microsoft/PowerToys (github.com)](https://github.com/microsoft/PowerToys/issues/11963)
