### ISSUE TITLE
Add more info on adding components

### ISSUE THREAD

**Issue by kenmorse** [MicrosoftDocs/windows-uwp#3212]
Would be great to see a bit more of the "getting started" type info for this WinUI 3 document. Specifically adding components (the template starts with a single button) would be very useful, especially since the environment doesn't include access to the XAML Design view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3 Project Reunion 0.5 (March 2021) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#winui-3-controls-gallery)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @kenmorse - thanks for the suggestion. You're looking at an archived topic there. The latest release docs are available at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel. 

We have a couple of other existing topics that might help with your issue (https://docs.microsoft.com/en-us/windows/apps/get-started/build-apps-for-windows, https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-build-basic-winui3-app).

We'll be addressing a number of content issues and TOC reorgs over the coming months. So stay tuned!
