### ISSUE TITLE
Wrong link for Segoe UI font download

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/windows-uwp#3213]
The link for Segoe UI download is the same as that for Segoe UI Variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64559e01-a1bb-7417-1261-d4c1e16d07c8
* Version Independent ID: 105e0a73-9844-6ebd-41c4-2f4c4c5811bb
* Content: [Design toolkits and samples for Windows apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/downloads/)
* Content Source: [hub/apps/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Mancerrss** [comment]
Can we also get, official static font downloads for all of weights and variants of Segoe UI Variable.
For us designers that uses design tools, that doesn't support Variable fonts yet? E.g. Figma.

Maybe make it a different named Family too, like "Segoe UI Variable Static" so we can install both the Variable fonts, and Static fonts, on our machines, and use both for both design tools that supports Variable fonts, and not.

**Comment by hickeys** [comment]
The font links were updated several weeks ago. I'll forward your recommendation to the design team, but in the meantime you could make your recommendation in the official feedback tracking system. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product feedback.

**Comment by hickeys** [comment]
@Mancerrss 

Just to follow up - the design team uses Segoe UI Variable in figma all the time and does not experience these issues. When I asked them about your comment, they said that this may have been a problem with an earlier version of the font, and you should try with the latest version [here](https://docs.microsoft.com/en-us/windows/apps/design/downloads/#fonts)
