### ISSUE TITLE
typo's (sort of)

### ISSUE THREAD

**Issue by richsalz** [MicrosoftDocs/windows-uwp#3216]
Windows::Win32::UI::WindowsAndMessaging::*,  The "UI::" is missing.
 MessageBoxA(None, "Text", "Caption", MB_OK);  Dont put "MESSAGEBOX::" before MB_OK

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @richsalz, I've published a fix just now.

-Steve

**Comment by richsalz** [comment]
Thanks!  It's been years since I'vce used what used to be called DevStudio (NT4 days).  Using VSCode with rust is awesome!
