### ISSUE TITLE
No link to explain how to obtain access to run background tasks

### ISSUE THREAD

**Issue by Globe51** [MicrosoftDocs/windows-uwp#3221]
Thanks to the single process model added in the Anniversary Update, adding background tasks is fairly simple. In your main app's code, after you have obtained the user's access to Notification Listener and **_obtained access to run background_** tasks, simply register a new background task, and set the UserNotificationChangedTrigger using the Toast notification kind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1305c1a2-d0b1-6210-4ced-78a42ef19521
* Version Independent ID: ff5e9d03-1763-b501-2541-91abab2b7d9a
* Content: [Notification listener - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/notification-listener.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/notification-listener.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Thanks for your suggestion. I've added explicit links to UserNotificationListener.Current.RequestAccessAsync and BackgroundExecutionManager.RequestAccessAsync.
