### ISSUE TITLE
Page not found for some links

### ISSUE THREAD

**Issue by tqa236** [MicrosoftDocs/windows-uwp#3222]
[Enter feedback here]

There are several links on https://docs.microsoft.com/en-us/windows/package-manager/winget/ that are dead. I can find the links below:

- require elevation
- elevate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mcleanbyron** [comment]
Thanks for reporting these broken links. They have been fixed on the live docs site.
