### ISSUE TITLE
Z-depth and shadow page missing Windows version

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3223]
Page says:

> Starting with Windows, if the app targets the Windows App SDK or later, the Receivers collection is ignored. However there will be no errors and the shadow continues to function.

Unclear which Windows version and which App SDK version this refers to :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35259e62-aa6e-5b97-e994-a904981f6e2c
* Version Independent ID: b9c48be0-de81-3d1d-ebb1-6163ecfc751b
* Content: [Z-depth and shadow for Windows apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/layout/depth-shadow#themeshadow-in-other-elements)
* Content Source: [hub/apps/design/layout/depth-shadow.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/layout/depth-shadow.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for raising this issue. The missing version numbers have been added to the doc.
