### ISSUE TITLE
Lack of Information on Using non-standard Accelerator Keys

### ISSUE THREAD

**Issue by ClintMayers** [MicrosoftDocs/windows-uwp#3225]
I'd like to use the arrow key, such as KeyboardAccelerator Key="&#x2192;".  Yet, there is no mention anywhere how to do this.  THis is the logical location to find it, yet shocked there isn't a single mention of it.  I have produced a video editor in my application, and would like to use common video editing shortcuts, such as, forward and backward arrows on the keyboard to step forward and back.  The spacebar, luckily is automatically mapped to the play and stop actions.  Yet, after hours of research and trying to find a logical solution, I'm stumped.  It seems logical to make mention of this in this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed663aa-9b56-8083-42e7-b5f5462e7293
* Version Independent ID: 7bb5af5e-b1cf-1c52-2c15-d3672b6531cd
* Content: [Keyboard accelerators - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/keyboard-accelerators#custom-keyboard-accelerator-behavior)
* Content Source: [hub/apps/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/keyboard-accelerators.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
hi @ClintMayers - arrow keys by themselves are not keyboard accelerators, they're typically used for keyboard navigation. If you want to override that functionality, review https://docs.microsoft.com/en-us/windows/apps/design/input/keyboard-events#overriding-keyboard-events-and-behavior and let me know if that helps. The reason the spacebar works to start/stop is that it invokes the action of the button that has focus. I suspect that if you have focus on one of your skip back/forward buttons and press the spacebar, that button will be invoked and not stop/start. Not sure how your video editor and media transport controls have been constructed though.

**Comment by ClintMayers** [comment]
**Thanks Karl,** that information is helpful and I will put it to use.  Appreciate the quick response.  **However, I did find an easy solution, and you CAN use the arrow keys inside the Key="".**  I just had to find your format of doing so, and I did.  There just isn't a mention of how to on this page.  You just replace the Key="" value to an enumerated string value from the list of Virtual Keys that I found at this Microsoft Link: https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkey?view=winrt-20348.  For example, we can do this: Key="Left" and Key="Right" and it works as I suspected it should!  It was extremely simple, and works as I expected.  Yet, it was not easy to find in Microsoft documentation.  I still love the code version you sent, as well, and think that should also be mentioned on this help page.  I suggest testing updating the information on this page to demonstrate the use of non-standard accelerators.  Logically, it makes sense that all keyboard actions should able to be captured by the app when in focus.  Why would they selectively mask alphanumerics and F keys?

**Comment by Karl-Bridge-Microsoft** [comment]
I'll see if i can get the topic updated. Thanks for engaging and helping us improve the docs!
