### ISSUE TITLE
thannnks

### ISSUE THREAD

**Issue by hohuutuan85** [MicrosoftDocs/windows-uwp#3226]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a2fe05-0bf3-05c1-7577-ee5dc1dd1dc3
* Version Independent ID: 5a442cf5-885f-418a-9091-fe0be3754d16
* Content: [Accessibility overview - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/accessibility/accessibility-overview)
* Content Source: [hub/apps/design/accessibility/accessibility-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/accessibility/accessibility-overview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported
