### ISSUE TITLE
What will happen to Fancy Zones when Windows 11 ships?

### ISSUE THREAD

**Issue by cfischer69** [MicrosoftDocs/windows-uwp#3229]
[Enter feedback here]
Fancy Zones has become one of the most critical tools in my daily workflow. While I was happy to see snap sets (or whatever they are calling it) in the Windows 11 announcement, I immediately felt that sinking feeling that it was going to be a much weaker version of Fancy Zones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by dedavis6797** [comment]
Hi @cfischer69, FancyZones will continue to be available after Windows 11 ships. PowerToys is still highly committed to expanding the range of functionality and flexibility offered by FancyZones for our advanced power users. As such, there are currently no plans to remove or deprecate the utility.
