### ISSUE TITLE
Get Set up Broken Link

### ISSUE THREAD

**Issue by raisircl** [MicrosoftDocs/windows-uwp#3230]
[Enter feedback here]
To download the tools you need to start creating UWP apps, see **Get set up**, and then write your first app.

When click on Get Set Up this link is broken : https://docs.microsoft.com/en-us/windows/apps/get-set-up
![broken-link-report](https://user-images.githubusercontent.com/40299912/125029071-b3c29980-e0a6-11eb-9ff9-b10f690b80da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcd2e7e-612d-29de-6b94-3bed0b772b16
* Version Independent ID: cf067679-95df-f7d2-17ec-d15cc18c0b4b
* Content: [What's a Universal Windows Platform (UWP) app? - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide#feedback)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This broken link has been fixed. Thank you for the heads-up.
