### ISSUE TITLE
Other success return codes and how to handle them?

### ISSUE THREAD

**Issue by billyrayxbox** [MicrosoftDocs/windows-uwp#3235]
In a recent issue, it appears that there are other 2** codes that can be returned by the API call (e.g. 204) that should be treated as success.

Please document all of the "success" codes and how client code should react to these.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88c05ee-343d-365a-742c-d7dceaa6d885
* Version Independent ID: f87ef3c0-b4ec-c113-8944-feb17f19f691
* Content: [Report consumable products as fulfilled - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/report-consumable-products-as-fulfilled)
* Content Source: [windows-apps-src/monetize/report-consumable-products-as-fulfilled.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/report-consumable-products-as-fulfilled.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Are these codes that you are actually receiving from the API, or just potential responses based on the HTTP spec?

**Comment by hickeys** [comment]
I'm going to close this since my question has not been answered. Please don't read into this too much. If this is still a problem, please do not hesitate to reopen.
