### ISSUE TITLE
UAP version error when creating new project?

### ISSUE THREAD

**Issue by GuildOfCalamity** [MicrosoftDocs/windows-uwp#3237]
Does anyone else get this warning? I also notice that the XAML designer will not show itself in the IDE (doesn't render the form).
![WinUI](https://user-images.githubusercontent.com/81915293/125367958-3b2e3800-e347-11eb-9ec2-0d21e1337a41.png)

**Comment by GuildOfCalamity** [comment]
When trying to resolve the issues using Nuget it just creates more problems...
![UAP_error](https://user-images.githubusercontent.com/81915293/125531248-b1146217-fcb8-4e2d-803d-2a930894c348.png)

**Comment by mcleanbyron** [comment]
It sounds like you're running into a problem with creating a new WinUI project using Project Reunion (now called the Windows App SDK). Unfortunately, this repo is for gathering feedback/issues about the Windows developer documentation. To report problems with the Windows App SDK, please use this repository: https://github.com/microsoft/WindowsAppSDK/issues.
