### ISSUE TITLE
Run as Administrator not retained after reboot

### ISSUE THREAD

**Issue by rigman** [MicrosoftDocs/windows-uwp#3239]
[Enter feedback here]
Every time I reboot I have to authorize "Run as Administrator" again. Needed for the new Awake module. How about info on fixing admin mode so it stays set thru a reboot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bd5eaf-0982-6fe8-09d2-17e4373886bb
* Version Independent ID: 5e66eda4-be07-4afd-7187-3e4d896f7861
* Content: [PowerToys administrator mode for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/administrator)
* Content Source: [hub/powertoys/administrator.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/administrator.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing this issue @rigman, but I'm going to redirect you to file it in the PowerToys product repo: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+is%3Aopen+awake 
This repo is for issues specific to the documentation of the product, for anything related to updates to PowerToys features, the product repo is going to be the place to go. :)
