### ISSUE TITLE
Machine learning: CNTK generates CNTKv2 models that aren't supported by WinML

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/windows-uwp#324]
Using Fast-RCNN to do some object detection/localization (https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN#train-on-your-own-data), recommended via the Train AI Model (https://docs.microsoft.com/en-us/windows/uwp/machine-learning/train-ai-model) and I discovered it spits out a model in CNTKv2 format, which isn't supported by WinML or conversion tools.

A note about Microsoft not supporting their own CNTKv2 format might be relevant on the Conversion Samples page at a minimum (https://docs.microsoft.com/en-us/windows/uwp/machine-learning/conversion-samples).

**Comment by serenaz** [comment]
CNTK to ONNX: https://github.com/onnx/tutorials/blob/master/tutorials/CntkOnnxExport.ipynb

**Comment by serenaz** [comment]
Thanks for raising the issue! We'll update our docs on how you can use conversion tools to obtain an ONNX model to use with Windows ML.

**Comment by riverar** [comment]
Thanks @serenaz, this doesn't work for many CNTK models (filed a separate bug for this https://github.com/Microsoft/CNTK/issues/3033)
