### ISSUE TITLE
Dragging start/end events aren't named properly and are not linked to

### ISSUE THREAD

**Issue by hawkerm** [MicrosoftDocs/windows-uwp#3240]
The start event should be [DragStarting](https://docs.microsoft.com/uwp/api/windows.ui.xaml.uielement.dragstarting) not **DragStarted**
The end event should be [DropCompleted](https://docs.microsoft.com/uwp/api/windows.ui.xaml.uielement.dropcompleted) not **DragCompleted**

These are misnamed throughout the article including the overview list, the "construct a data package" section.

They should also link to the api docs and be part of the see also list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9af0cc9-303c-c649-71dc-d9a9fbe616ae
* Version Independent ID: 3fce579b-5c5b-c393-1669-7ef3927a43d3
* Content: [Drag and drop - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/drag-and-drop)
* Content Source: [hub/apps/design/input/drag-and-drop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/drag-and-drop.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hawkerm** [comment]
I don't think the DropCompleted method is required for your own data package as stated in the instructions (at least as part of the package part, you'd still want it to remove the source item). You use the `Drop` event to receive the data package constructed by the `DragStarting` event.

It'd be handy if the Construct a data package section showed how to construct a package to show a complete example in the same article, since the Drop event shows how to process one.

It'd also be important to call out that if this is happening within something like ListView that you have to use the `DragItemsStarting` and `DragItemsCompleted` events instead of the `DragStarting` and `DropCompleted` events (as those are being fired on the child item, but you're usually trying to register to the events on the ListView itself).

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @hawkerm - the topic has been updated.
