### ISSUE TITLE
Need more small C++/WinRT examples

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3242]
@stevewhims 
I have migrated the examples in the the first six chapters of Programming Windows 6th Edition (MS Press, 2013) from C++/CX to C++/WinRT and all except one in the seventh chapter (async) and am happy to share these to help others. The migrated chapter seven async examples use winrt::resume_foreground and discard the return value. I am now blocked as I can not find C++/WinRT MessageDialog examples anywhere that have the equivalent of C++/CX cancellation_token_source.

**Comment by stevewhims** [comment]
Hi, @MRahilly. Would you be able to share the example here (or just as much of it as necessary to show the pattern in which the cancellation_token_source is being used)? I'm guessing the example shows the MessageDialog but is capable of canceling the dialog from within the program. But it'd help to actually see the example.

Thanks!
Steve

**Comment by ghost** [comment]
Hi Steven, The relevant C++/CX code example with cancellation_token_source follows:

(MainPage.xaml.cpp)
#include "pch.h"                            // includes ppltasks.h
#include "MainPage.xaml.h"

using namespace HowToCancelAsync;

using namespace Concurrency;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::UI;
using namespace Windows::UI::Core;
using namespace Windows::UI::Popups;
using namespace Windows::UI::Xaml;
using namespace Windows::UI::Xaml::Controls;
using namespace Windows::UI::Xaml::Controls::Primitives;
using namespace Windows::UI::Xaml::Data;
using namespace Windows::UI::Xaml::Input;
using namespace Windows::UI::Xaml::Media;
using namespace Windows::UI::Xaml::Navigation;

MainPage::MainPage()
{
    InitializeComponent();
}

void MainPage::OnButtonClick(Object^ sender, RoutedEventArgs^ args)
{
    MessageDialog^ msgdlg = ref new MessageDialog("Choose a color", "How To Cancel Async");
    msgdlg->Commands->Append(ref new UICommand("Red", nullptr, Colors::Red));
    msgdlg->Commands->Append(ref new UICommand("Green", nullptr, Colors::Green));
    msgdlg->Commands->Append(ref new UICommand("Blue", nullptr, Colors::Blue));

    // Start a five-second timer
    TimeSpan timeSpan;
    timeSpan.Duration = 50000000;   // 5 seconds

    DispatcherTimer^ timer = ref new DispatcherTimer();
    timer->Interval = timeSpan;
    timer->Tick += ref new EventHandler<Object^>(this, &MainPage::OnTimerTick);
    timer->Start();

    // Show the MessageDialog
    cancellationTokenSource = cancellation_token_source();
    task<IUICommand^> showTask = create_task(msgdlg->ShowAsync(), cancellationTokenSource.get_token());
    showTask.then([this, timer](task<IUICommand^> thisTask)
    {
        IUICommand^ command = nullptr;

        try
        {
            command = thisTask.get();
        }
        catch (task_canceled)
        {
            // The exception in this case will be task_canceled
        }

        // Stop the timer
        timer->Stop();

        // If the operation wasn't cancelled, use the value
        if (command != nullptr)
        {
            // Get the Color value and set the background brush
            Color clr = (Color)command->Id;
            contentGrid->Background = ref new SolidColorBrush(clr);
        }
    });
}

void MainPage::OnTimerTick(Object^ sender, Object^ args)
{
    cancellationTokenSource.cancel();
}

(pch.h)
#pragma once

#include <collection.h>
#include "App.xaml.h"
#include "ppltasks.h"

(MainPage.xaml.h)
#pragma once

#include "MainPage.g.h"

namespace HowToCancelAsync
{
    public ref class MainPage sealed
    {
    private:
        Concurrency::cancellation_token_source cancellationTokenSource;

    public:
        MainPage();

    private:
        void OnButtonClick(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ args);
        void OnTimerTick(Platform::Object^ sender, Platform::Object^ args);
    };
}

(MainPage.xaml)
<Page
    x:Class="HowToCancelAsync.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:HowToCancelAsync"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Name="contentGrid"
          Background="{StaticResource ApplicationPageBackgroundThemeBrush}">

        <Button Content="Show me a MessageDialog!"
                HorizontalAlignment="Center"
                VerticalAlignment="Center"
                Click="OnButtonClick" />
        
    </Grid>
</Page>

Thanks,
Marcus

**Comment by stevewhims** [comment]
Thanks, @MRahilly. I've created a backlog work item for myself, and I'll get to that when I'm able. Once I start work on that work item, I'll return here and reopen this issue (my work item has a link to this issue, so they're linked). But in the meanwhile (so I'm not tracking it twice), I'll go ahead and close the issue.

Thanks!
Steve
