### ISSUE TITLE
Input Method Editors (IME): insufficient information

### ISSUE THREAD

**Issue by David263** [MicrosoftDocs/windows-uwp#3245]
I added a Chinese keyboard layout, opened Notepad, right-clicked on the client area, and opened the IME by choosing its menu item. I don't see anything special happening. I found this page by searching, but its explanation is so general as to be useless. It contains no explanation or links for how to use a specific IME.

Can I use the IME just with Notepad and no other application? This page doesn't seem to say. The bulk of this page is meant for systems software developers, but that fact is not reflected in the title.

Just feedback for you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85acc99c-209f-ae03-feb4-7e9216c348ea
* Version Independent ID: 4e757734-c506-3c46-0b57-9d53d0886eac
* Content: [Input Method Editors (IME) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/input-method-editors)
* Content Source: [hub/apps/design/input/input-method-editors.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/input-method-editors.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @David263 - thanks for the feedback. The topic you refer to is a Windows developer doc. For SEO (and general usability), we have to limit the character count of our titles and ensure we use as many feature keywords as possible. 

I did a quick search and found this topic for you: https://support.microsoft.com/en-us/windows/microsoft-traditional-chinese-ime-ef596ca5-aff7-4272-b34b-0ac7c2631a38.

I also suggest you try the Product Feedback button at the bottom of the topic to get additional help (https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose).

**Comment by David263** [comment]
That link describes Bofomopo IME, which seems very different from the Pinyin input that was installed with the Chinese keyboard. Plus there is a bug: when I type "ma", it fails to show a choice of characters!

Very frustrating and strange.
