### ISSUE TITLE
Screen capture at the render FPS

### ISSUE THREAD

**Issue by LagradOst** [MicrosoftDocs/windows-uwp#3246]
Right now the screen capture is capped at the monitor FPS, but there is no reason why it should be. If the screen capture captures the whole screen then it makes sense to deliver what the monitor sees. However if you chose a single window like a game, it will still capture at the monitor hz even if the game is running at 20fps or 350fps. (code taken from the example https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture) If you only record one specific window then why not use the image buffer for that application?

I want to be able to capture at a high framerate (above the monitor hz) in fullscreen and the current API dont support it as far as I know.

**Comment by drewbatgit** [comment]
Hello, thanks for your question. Github issues in this repo are used specifically for tracking issues in the documentation. For product feedback, such to lobbying for a feature change or a new feature, making a suggestion, or asking a product question, you should create a post on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). You can also get to the Q&A site by clicking on the "This product" button in the feedback section on each page in the documentation.
