### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by j-fulbright** [MicrosoftDocs/windows-uwp#3247]
The documentation on this page has the word "parody" when it should be "parity"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c767b191-f5b0-a650-c560-f9b51aa5d550
* Version Independent ID: 8ba705d4-396f-975e-5d3a-a01ee97cfd8a
* Content: [Install Vue.js on WSL](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/vue-on-wsl)
* Content Source: [hub/dev-environment/javascript/vue-on-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/vue-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks! Resolved. :) https://github.com/MicrosoftDocs/windows-uwp/issues/3247
