### ISSUE TITLE
Really useful pointer event sample code

### ISSUE THREAD

**Issue by rcohn** [MicrosoftDocs/windows-uwp#3249]
It took a while to find it (especially since all the code samples were moved from their original locations), but glad I persisted.

My biggest objection is that I must build a UWP app to use this pointer API (or so I believe - thought it would be supported in WinUI3).

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2FsZWFkZXIvdG9vbGtpdC03L2Rlc2lnbi9pbnB1dC9oYW5kbGUtcG9pbnRlci1pbnB1dC5odG1s
* Version Independent ID: L2FsZWFkZXIvdG9vbGtpdC03L2Rlc2lnbi9pbnB1dC9oYW5kbGUtcG9pbnRlci1pbnB1dC5odG1s
* Content: [Handle pointer input - UWP applications](https://docstaging.z5.web.core.windows.net/aleader/toolkit-7/design/input/handle-pointer-input.html)
* Content Source: [windows-apps-src/design/input/handle-pointer-input.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/handle-pointer-input.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback. Pointer APIs are being rolled out to WinUI 3. See the pointer APIs at https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input?view=winui-3.0.
