### ISSUE TITLE
WinUI 3 page should point to Windows App SDK 0.8+

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3251]
The current content discusses Reunion 0.5, it should be updated to point to the latest release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3 Project Reunion 0.5 (March 2021) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @asklar - I've made a number of updates to the WinUI overview docs to address some of the issues that arose from a minor re-org of the docs we completed for the 0.8 release. This issue should be resolved now. Please let me know if not.

**Comment by asklar** [comment]
awesome thanks a lot @Karl-Bridge-Microsoft !
