### ISSUE TITLE
Please describe how to use toast APIs without the Toolkit

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#3252]
I've struggled to find any good documentation about how to use the notification APIs. I keep hitting helper methods defined in the toolkit. I do not want to take a dependency just to make a toast.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ab94cb-c334-e72e-ef0b-0d792c6b1d7a
* Version Independent ID: c5547751-b359-002a-7d5c-4b52dad6e0bd
* Content: [Toast content - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=builder-syntax)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for creating this issue. Your concerns are echoed in another issue, [#3253](https://github.com/MicrosoftDocs/windows-uwp/issues/3253). I've already engaged the engineering team based on that issue, so I'm closing this one as a duplicate even though yours was technically created first.
