### ISSUE TITLE
C++ UWP toast page needs a C++/WinRT example and to not use the WCT

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#3253]
C++/CX is deprecated, so this page needs to have C++/WinRT examples. Additionally it makes uses of the WCT's content builder, which is managed so incurs a heavy cost simply to build a toast notification, which is going to be undesired by most C++ programmers (especially if the WCT ends up being the sole reason that the .NET runtime is loaded)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea9883f-3b5b-69ed-d772-d6ecd54164f9
* Version Independent ID: 7bd75325-9310-18f2-7691-477f68dbfbaf
* Content: [Send a local toast notification from a C++ UWP app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast-cpp-uwp)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/send-local-toast-cpp-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/send-local-toast-cpp-uwp.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.

**Comment by sylveon** [comment]
Extremely disappointing. The migration to this new system regresses the amount of transparency/visibility that GitHub Issues had.
