### ISSUE TITLE
What's the step to submit win32 app to Microsoft Store

### ISSUE THREAD

**Issue by yxw0407** [MicrosoftDocs/windows-uwp#3254]
[Enter feedback here]

Hello,

I've learned that the latest Windows 11 will supports traditional win32 app in Microsoft Store.

Anyone know the steps to submit win32 app to Microsoft Store? What's the requirements about the win32 app when submit it to Microsoft Store?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7af353-84a6-f6ce-bc15-29e9c287fcba
* Version Independent ID: c8b77986-819d-9f66-fe36-d5e976c667fb
* Content: [Submit your MSI or EXE app to the Microsoft Store - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/overview)
* Content Source: [windows-apps-src/publish/msiexe/overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/msiexe/overview.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by hickeys** [comment]
The page you were on when you filed this issue contains the answers to your questions. Are there specific questions that you feel were not answered by the documentation?
