### ISSUE TITLE
Project XamlControlsGallery does not build. - VS 2019 Preview 3.0

### ISSUE THREAD

**Issue by LeslieMurphy** [MicrosoftDocs/windows-uwp#3255]
[Enter feedback here]

Project will not build in VS 2019 16.11.0 Preview 3.0  with VSIX Project Reunion 0.8.1.47772797 installed.

Error		Could not read the Windows SDK's Platform.xml	XamlControlsGallery.DesktopWap	

Error	MSB3073	The command ""C:\Users\xxx\.nuget\packages\microsoft.windows.cswinrt\1.2.5\cswinrt.exe" @"obj\generatedcswinrt.rsp"" exited with code 1.	XamlControlsGallery.DesktopWap	

MSB3774	Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.18362.0".	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [WinUI 3 Project Reunion 0.5 (March 2021) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#winui-3-controls-gallery)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @LeslieMurphy - thanks for reporting this. From the link provided, it looks like you might be working with an older version of the Windows App SDK. I suggest reviewing the documentation for the latest release at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel.

If that doesn't help, it looks like an issue better reported directly in the sample repo itself. Please log this issue at https://github.com/microsoft/Xaml-Controls-Gallery/issues and the team or community should be able to help. If a doc update is required, please open another issue on the doc with more details. 

Thanks!

**Comment by LeslieMurphy** [comment]
Thanks.  Will try again and then report against the repo.

It is confusing that Windows App SDK is installed as a VSIX instead of a NuGet package.  Not clear to me why that is!  I am on the latest version 0.8.1.47772797
