### ISSUE TITLE
Qeustion about toolkit tabs

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftDocs/windows-uwp#3257]
I am using c# 
.net 6 

And i want the tabs in de bar where the close and minimize buttons are is that possible

**Comment by jarno9981** [comment]
Good example is msedge  it got they tabs at they bair top

**Comment by GrantMeStrength** [comment]
hi! This is the feedback system for issues in the developer documentation. I don't think this is a documentation issue.

For general feedback : https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332

For asking questions: https://docs.microsoft.com/en-us/answers/index.html

Please let me know if there is developer documentation issues I can help with, thank you!
