### ISSUE TITLE
Please also document how to do this _without_ the toolkit

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#3258]
I'd prefer the windows docs describing how to use the Windows APIs without the toolkit. Put the toolkit specific version in the toolkit area, and just add a paragraph that refers to that doc, and then continue actually documenting the WinRT APIs. I haven't been able to find good documentation and examples of how to use the built-in notification APIs that _doesn't_ include installing the toolkit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ed23e0-a30d-9880-a17d-5f914cbb8fb3
* Version Independent ID: 9785bf14-244d-6e96-3390-424fefa8811b
* Content: [Custom audio on toasts - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/custom-audio-on-toasts.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.

**Comment by dotMorten** [comment]
@drewbatgit do you have a link to where this (terrible) decision was announced and who we should be talking to to try and get this reversed? This has been by far the best thing you’ve ever done with your documentation and I can’t for the love of all understand why you’d stop doing this. And the link to the Q&A site… have you actually looked at that? That’s not a replacement for logging issues with doc or addressing them.
