### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by mm1nIPOVdDsu** [MicrosoftDocs/windows-uwp#3261]
In the section located here:

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps#package-external-location

There is a slight grammar/oopsie in the last sentence. 

"During the install process for your app or the first time your apps,..."

I think this is supposed to read something like "...or the time time your app runs" -Or- "...the first time your apps launch" 

Either way, its all old English to me. Ugh, Beowulf.

**Comment by GrantMeStrength** [comment]
His spirit was sad, restless and ready for death—his fate drawing near, which would seek out the old warrior to find the hoard of his soul, and to sever the tie of his life with his body. Also, I fixed the typo - thank you!
