### ISSUE TITLE
Underlying values of DWM_WINDOW_CORNER_PREFERENCE and its enumeration

### ISSUE THREAD

**Issue by emoacht** [MicrosoftDocs/windows-uwp#3262]
Please provide the underlying values of DWM_WINDOW_CORNER_PREFERENCE and its enumeration; DWMWCP_DEFAULT, DWMWCP_DONOTROUND, DWMWCP_ROUND and DWMWCP_ROUNDSMALL so that we can call DwmSetWindowAttribute function with those values by P/Invoke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cd4ed11-b246-94af-c310-514326282eaf
* Version Independent ID: 5a1dbf05-790d-525b-bcc6-01857c1687de
* Content: [Apply rounded corners in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners)
* Content Source: [hub/apps/desktop/modernize/apply-rounded-corners.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/apply-rounded-corners.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Pololot64** [comment]
This would be very helpful 👍

**Comment by mikhailovalex** [comment]
DWM_WINDOW_CORNER_PREFERENCE  is 33
DWMWCP_DEFAULT	 0
DWMWCP_DONOTROUND	1
DWMWCP_ROUND	2
DWMWCP_ROUNDSMALL	3

**Comment by jwmsft** [comment]
Documentation has been updated and linked.
