### ISSUE TITLE
minimal Visual Studio components for Rust

### ISSUE THREAD

**Issue by cataggar** [MicrosoftDocs/windows-uwp#3266]
I think some Visual Studio users may be interested in the minimal components needed to get Rust set up. I think those components can be installed by launching Visual Studio Installer and importing a .vsconfig file.

In https://github.com/rust-lang/rustup/issues/1462#issuecomment-888684432, I suggested creating a `visual-cpp-build-tools.vsconfig` with:
``` json
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
  ]
}
```

Can the Visual Studio Installer take a URL? cc @heaths 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @cataggar, I'm just wondering whether this technique is definitely correct, and vetted. I ask because of the "I **think** those components can", and the query about whether or not VS Installer can take a url.

Since this is an internal MS query, how do you feel about creating a PR containing the (correct, and vetted) changes that you'd like to see made to this topic? :) For info/instructions, please see: https://review.docs.microsoft.com/en-us/windows-authoring-guide/quickstart?branch=main.

Many thanks!
Steve

**Comment by heaths** [comment]
It takes a URL for the channel manifest and you can pass `--add <component>`, but a .vsconfig file is supported, yes. I designed it to be rooted in a repo (in hindsight, we should've spec'd/supported it more like a .gitignore file that can work at multiple levels) and we added support for it ~15.7.

See https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio for more command line options. For example,

```powershell
# defaults to the Enterprise product for whatever channel you downloaded, but any could be selected instead.
vs_enterprise.exe --installPath C:\DevStudio --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -add Microsoft.VisualStudio.Component.VC.Redist.14.Latest
```

One thing to note is that while workload and component IDs aren't supposed to change, it has and will likely happen again. It's not often but, IIRC, these component IDs have been stable.

**Comment by cataggar** [comment]
Thanks @heaths! I've committed a `visual-cpp-build-tools.vsconfig` to a repo with setup instructions. Thanks for the links @stevewhims. Hopefully, the docs can be updated when/if it gets vetted.
