### ISSUE TITLE
where are all the themed color names?

### ISSUE THREAD

**Issue by lovettchris** [MicrosoftDocs/windows-uwp#3267]
This page is lacking [https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-theme-resources](https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-theme-resources) a list of all themed colors.

I had to search around for ages until I found this page: 
http://metro.excastle.com/xaml-system-brushes

docs.microsoft.com needs to provide this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd8bc4b-e32e-08d4-0fc0-8566f94859e1
* Version Independent ID: 4fab2e81-3001-d296-5db4-7cb39038e18f
* Content: [XAML theme resources - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-theme-resources)
* Content Source: [hub/apps/design/style/xaml-theme-resources.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/style/xaml-theme-resources.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for this suggestion. I'm checking with the design team about the feasibility of maintaining a list like this.

**Comment by hickeys** [comment]
The complete list is contained in `generic.xaml`, and the path to find that file is already listed in the page. Providing the entire list would be duplicative.
