### ISSUE TITLE
Both C# examples appear identical??

### ISSUE THREAD

**Issue by sparkrod** [MicrosoftDocs/windows-uwp#3269]
There are two C# examples on this page that appear identical and I am unsure what the difference is meant to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ed3306f-fb9a-0be1-b372-4a073bb3e57c
* Version Independent ID: fddfcca6-819d-e48a-9ab2-d12ab56ba796
* Content: [Keep the UI thread responsive - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/keep-the-ui-thread-responsive)
* Content Source: [windows-apps-src/debug-test-perf/keep-the-ui-thread-responsive.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/keep-the-ui-thread-responsive.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @sparkrod - thanks for pointing this out. The topic has been updated.
