### ISSUE TITLE
Discrepancy between TabIndex descriptions

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#3270]
The Keyboard Accessibility page says:

> Whether you adjust TabIndex values or use the default order, these rules apply:
>
> UI elements with TabIndex equal to 0 are added to the tab order based on declaration order in XAML or child collections.
> UI elements with TabIndex greater than 0 are added to the tab order based on the TabIndex value.
> UI elements with TabIndex less than 0 are added to the tab order and appear before any zero value. This potentially differs from HTML's handling of its tabindex attribute (and negative tabindex was not supported in older HTML specifications).

This implies that the default TabIndex is 0.

However, the documentation for [Control.TabIndex](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.tabindex) says the default value is int.MaxValue. 

Testing with a barebones C#/UWP app bears out that the default is in fact int.MaxValue. Given following XAML:

```
    <StackPanel Background="#333">
        <StackPanel Background="#FF33FF">
            <Button>A</Button>
            <Button TabIndex="2147483647">B</Button>
            <Button>C</Button>
        </StackPanel>
        <StackPanel Background="#33FFFF">
            <Button TabIndex="1">D</Button>
            <Button TabIndex="1">E</Button>
            <Button TabIndex="0">F</Button>
        </StackPanel>
    </StackPanel>
```
produces a tab order of:

1. F
2. D
3. E
4. A
5. B
6. C

Unfortunately this also means that, barring overriding TabIndex on every control in an application to "0", there's no way to move a single element to the end of the tab order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16560446-8342-2f27-97e7-e9f28393b12d
* Version Independent ID: bb0c90ed-70ee-3a50-5f99-9a77aec4e473
* Content: [Keyboard accessibility - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/accessibility/keyboard-accessibility)
* Content Source: [hub/apps/design/accessibility/keyboard-accessibility.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/accessibility/keyboard-accessibility.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @aschultz - I contacted the feature team about this and they have confirmed your findings that the default value (when tab index is not set) is int.MaxValue. 

They suggested that you file a feature request issue on the https://github.com/microsoft/microsoft-ui-xaml/issues repo for adding elements programmatically to the end of the tab order. This appears to be a gap in our support.

Meanwhile, I'm looking at updating the Keyboard accessibility topic.

**Comment by Karl-Bridge-Microsoft** [comment]
topic updated
