### ISSUE TITLE
ms-settings app network URI

### ISSUE THREAD

**Issue by littlefooch** [MicrosoftDocs/windows-uwp#3275]
Is there a URI which can be used to trigger the network 'reset now' button?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. Apologize for the delayed response, but the scope of our feedback channel here on GitHub covers specific documentation fixes. Do you mind redirecting the question to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). The should offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there.
