### ISSUE TITLE
Broken link in to XamlParseException

### ISSUE THREAD

**Issue by angelazhangmsft** [MicrosoftDocs/windows-uwp#3276]
Under "Unsupported Scenarios", the link to XAMLParseException is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0ad28b1-258a-a6f6-afcb-17b63ddbcb8b
* Version Independent ID: 8a444f1b-661b-8527-6d06-8c75fa48fb26
* Content: [Version adaptive code - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-code#feedback)
* Content Source: [windows-apps-src/debug-test-perf/version-adaptive-code.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/version-adaptive-code.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @angelazhangmsft - the link has been fixed
