### ISSUE TITLE
External dead link

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/windows-uwp#3277]
Hello,

The link to the _Epson ESC/POS FAQ_ is dead.
This link might be the new one ? https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b8a35b-4b8e-1ee5-b817-cdcb952480c0
* Version Independent ID: 1b7ded88-34d8-a7cc-c2c8-4693a2c7e43e
* Content: [Epson ESC/POS with formatting - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/epson-esc-pos-with-formatting)
* Content Source: [windows-apps-src/devices-sensors/epson-esc-pos-with-formatting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/epson-esc-pos-with-formatting.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @nicolassaleron - link has been revised.
