### ISSUE TITLE
Latest updates doc has broken Developing with Rust on Windows link

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/windows-uwp#3279]
I wasn't sure what page that should be pointing to, so can't submit a PR.

Affected page: https://docs.microsoft.com/en-us/windows/apps/whats-new/latest-doc-updates
Bad link: https://docs.microsoft.com/en-us/windows/rust/rust-on-windows/

@GrantMeStrength 👋

**Comment by GrantMeStrength** [comment]
Thank you - fixed and going live asap!
