### ISSUE TITLE
"Put the navigation pane in [overlay mode]. " What is this?

### ISSUE THREAD

**Issue by colhountech** [MicrosoftDocs/windows-uwp#3280]
"Put the navigation pane in overlay mode to conserve screen space."
I can't find a reference to 'overlay mode', it would be useful to explain this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744c0c15-6f2d-a7df-cf7f-e1c0096dc921
* Version Independent ID: 9908453f-430a-3f7a-db4e-4805df55faac
* Content: [Screen sizes and break points for responsive design - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design)
* Content Source: [hub/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@colhountech, thanks for contacting us about this confusing content. The terms used in this doc are out-of-date and don't map clearly to the current states used by NavigationView. I've submitted an update to make the doc more clear.

"Overlay mode" is referring to [NavigationView.PaneDisplayMode](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.navigationview.panedisplaymode) being set to `LeftMinimal` as described in the [NavigationView](https://docs.microsoft.com/windows/apps/design/controls/navigationview#display-modes) article.

**Comment by colhountech** [comment]
Great! that makes a lot more sense.
