### ISSUE TITLE
Broken link to web apis from main web dev page

### ISSUE THREAD

**Issue by jeffsuth** [MicrosoftDocs/windows-uwp#3282]
Regarding file: windows-uwp/blob/docs/hub/web/index.md (https://docs.microsoft.com/en-us/windows/web/)

In top paragraph, the link is incorrect in the following sentence:
"For a list of APIs, see APIs for web development."

Link points to:
    https://docs.microsoft.com/en-us/apis.md
    (/apis.md)

Link should point to:
    https://docs.microsoft.com/en-us/windows/web/apis
    (./apis.md?)

**Comment by GrantMeStrength** [comment]
Thanks! All fixed!
