### ISSUE TITLE
Adoble XD Design Toolkit for UWP is not posted in the site

### ISSUE THREAD

**Issue by uniquegeeko** [MicrosoftDocs/windows-uwp#3284]
Hi! The Adobe's XD kits website, [Link Here](https://www.adobe.com/products/xd/features/ui-kits.html#panel-3) has the ad board for Microsoft UWP Platform kits for XD.  When you click the link on the page "**Get the kit**", it navigates to the "**Design toolkits and samples for Windows apps**" site, which this is the github repos for it [link here](https://docs.microsoft.com/en-us/windows/apps/design/downloads/).  However, the Adobe XD toolkit it is not posted under the section "**Design Toolkits**", there is only the link to the file for figma toolkit available. When will the toolkit be posted? Thanks! Screen shot below:

 
![image](https://user-images.githubusercontent.com/88475307/128466415-9d3f3902-db04-42d3-a880-5033071f37b9.png)

**Comment by hickeys** [comment]
Thank you for this feedback. We are aware of this issue, and working to restore the Xd download. Unfortunately, I don't have a timetable to share at this point.
