### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Jimmy20040819** [MicrosoftDocs/windows-uwp#3286]
[Powertoys seems not working under the windows 11 22000.120 co_release ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [PowerToys File Explorer utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @Jimmy20040819. I'm going to close this and redirect you to the [PowerToys product repo](https://github.com/microsoft/PowerToys/issues/) (this one is just for issues relating to updating the documentation).  It looks like someone has already filed a bug there on Windows 11 22000.120: https://github.com/microsoft/PowerToys/issues/12707  Please consider adding on -- the more moment that an issue has, the higher priority the team will be able to assign it.
