### ISSUE TITLE
Update WACK docs for running from cmdline

### ISSUE THREAD

**Issue by angelazhangmsft** [MicrosoftDocs/windows-uwp#3287]
We are using WACK to verify WindowsAppSDK samples, and went through some of these docs to figure out how to use it. I am using Windows SDK version 10.0.19041.0.

- I think the default path should be: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\ 
instead of Program Files\Windows Kits\... Not sure if that is a change based on the Windows SDK version?
- It would help to mention that WACK must be run from an *admin* command prompt 
- It would also help to have example command line commands that show how to set the reportoutputpath

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea36edd-22d6-7d1e-73c3-63d8f276d679
* Version Independent ID: a50a03aa-e89d-55da-43ba-b23155b9bbaf
* Content: [Windows App Certification Kit - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit#validate-your-windows-app-using-the-windows-app-certification-kit-from-a-command-line)
* Content Source: [windows-apps-src/debug-test-perf/windows-app-certification-kit.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/windows-app-certification-kit.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@angelazhangmsft - thanks for the feedback. I have updates for your first two points ready, but can you provide anything for your third "reportoutputpath" request? There are two examples already, so I'm not sure what you feel is missing.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @angelazhangmsft - I updated the topic to address your first two suggestions. If you have examples you'd like to add to the topic please provide them in a new issue or, preferably, edit the doc and submit a PR. Thanks!
