### ISSUE TITLE
Time, Date, and Calendar Picker for MS Office Tools

### ISSUE THREAD

**Issue by BlueBearOne** [MicrosoftDocs/windows-uwp#3290]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3be216a-e7ef-93e2-18ca-fe8a578beee3
* Version Independent ID: 0b476c25-be9a-5b68-82e3-88873fdbcfad
* Content: [Time picker - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/controls/time-picker)
* Content Source: [hub/apps/design/controls/time-picker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/controls/time-picker.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by BlueBearOne** [comment]
So sorry.  I'm new on here and thought that button was a bookmark.  My apology.  Now that I'm here though...what I'm REALLY looking for is a way to let me people enter a Start Time and an End Time.  Then have MS Word auto populate another cell with a number of billable units.  For every 15 minutes, they can bill 1 unit.  So if they bill 30 minutes, they can bill 2 units.  If they bill 60 minutes, they can bill 4 units, if they bill 69 minutes or even 74 minutes...still only 4 units.  If they bill 75 minutes, then they can bill 5 units.,  This is important because there are often errors on this part of the form if entered manually.  Especially as the day wears on.  Do you know if anything like that exists?

Thank you so much for your excellent work.  I greatly appreciate it as well as any insights you can give me.  Thanks so much!

**Comment by jwmsft** [comment]
Hi, thanks for your question. Unfortunately, the controls documented here are only for Windows UWP apps. They can't be used in MS Office apps. 
For more information about office apps, please see the [Office Developer documentation](https://docs.microsoft.com/office/dev/add-ins/), or you could post your question to [Microsoft Q&A](https://docs.microsoft.com/answers/index.html).

**Comment by BlueBearOne** [comment]
Thank you Jim!  I greatly appreciate that pointer.  You saved me a lot of time.  I will do that.  Take care!

Stuart Ryan
