### ISSUE TITLE
separate listings for driver binding

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/windows-uwp#3291]
[What to do if app has a driver binding which means users will get different version of the same app but with different features depending on the driver they have installed. At the moment there is no way to have different listings, is MSFT planning to add such feature ?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8731a612-b63e-55c4-b7d7-58c9e4b92448
* Version Independent ID: 1fc9f5e5-2b51-0b59-2419-ae428d98d737
* Content: [Create app Store listings - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-app-store-listings)
* Content Source: [windows-apps-src/publish/create-app-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-app-store-listings.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
