### ISSUE TITLE
Link for "Windows App SDK" broken

### ISSUE THREAD

**Issue by DeanBilotti** [MicrosoftDocs/windows-uwp#3296]
The link for "Windows App SDK" under the "Related links for WinUI 3" is broken and ends up at a 404.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea32f1f-67e6-12f4-7aa0-602184a377fd
* Version Independent ID: 3adf7079-1ead-0e1a-0af9-7de72d30117f
* Content: [Windows UI Library (WinUI) - Windows apps](https://docs.microsoft.com/en-gb/windows/apps/winui/)
* Content Source: [hub/apps/winui/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @DeanBilotti - the links should be fixed shortly.
