### ISSUE TITLE
Please provide a working sample

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#330]
Followed as-is, this NavigationView code example produces over 90 compiler errors, warnings and messages. Please provide a working sample code, so that it can be really useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#code-example)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for raising the issue! We've fixed the code example, and changes should be published by tomorrow.
