### ISSUE TITLE
The email alias to support partner center is undeliverable.

### ISSUE THREAD

**Issue by mosunchao** [MicrosoftDocs/windows-uwp#3300]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98fb27a9-dc14-fcfb-0d54-f2c2640fecda
* Version Independent ID: 5e306b46-4e3f-81c3-b80f-397d575d0374
* Content: [Generate preinstall packages for OEMs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/generate-preinstall-packages-for-oems)
* Content Source: [windows-apps-src/publish/generate-preinstall-packages-for-oems.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/generate-preinstall-packages-for-oems.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
No actionable details.
