### ISSUE TITLE
Missing shaders code

### ISSUE THREAD

**Issue by Odepax** [MicrosoftDocs/windows-uwp#3310]
The code for the shaders seems to be missing, on this page and others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be6c66f-f293-7d52-fcf0-7b92fd7e186d
* Version Independent ID: 90f82e24-ba77-f382-95e2-b2aa8f9cbbe0
* Content: [Use depth and effects on primitives - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/using-depth-and-effects-on-primitives)
* Content Source: [windows-apps-src/gaming/using-depth-and-effects-on-primitives.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/using-depth-and-effects-on-primitives.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Odepax. Yes, these topics seem to be incomplete, and out of date (they're using C++/CX).

I've created a work item on my backlog to decide what to do with this content; either update it to C++/WinRT and make sure it's complete (HLSL and all), or else remove it if we already cover this same ground better elsewhere. So as not to track the work in two places, I'll close this issue, but I'll come back and update it when I get around to my backlog work item.

Thanks again!
Steve
