### ISSUE TITLE
C++ (v142) Universal Windows Platform tools not listed 

### ISSUE THREAD

**Issue by MuratTopcu** [MicrosoftDocs/windows-uwp#3312]
Visual studio 2022 Preview 3.1 has 141 and 143 but 142 doesn't show up 

![Ekran görüntüsü 2021-08-20 142307](https://user-images.githubusercontent.com/2551727/130226161-06c20cea-3658-4b3f-843c-3e3955d1715d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment#required-workloads-and-components)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by MuratTopcu** [comment]
Preview 4.0 same :(

![resim](https://user-images.githubusercontent.com/2551727/133406952-8177eb9f-ab00-46b8-81d8-f52fc9e48372.png)

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. We have updated this article to specify the v143 toolset if you're installing Visual Studio 2022. These changes should be on the live docs site later today.
