### ISSUE TITLE
Installing pip and venv

### ISSUE THREAD

**Issue by vijaynyaya** [MicrosoftDocs/windows-uwp#3313]
[Enter feedback here]
This was my first time interacting with and setting up UNIX. So, after checking that I am on lastest version of Python and Ubuntu, I was getting error "package python3-pip not available". So turns out I needed to run "sudo apt-get update". You should mention this in the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b92f5-7f7f-cc94-64b9-69462979fe0f
* Version Independent ID: 5096d0ec-24fc-23ae-b2ec-aa21acf273d5
* Content: [Web development with Python on Windows](https://docs.microsoft.com/en-us/windows/python/web-frameworks)
* Content Source: [hub/python/web-frameworks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/web-frameworks.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Sorry to hear that you had trouble with the install @Vijaynyaya!
Updating is mentioned in the doc that you point to -- it's in the "Install Windows Subsystem for Linux" section. The Linux distros update so often, that we always recommend it after installing. I can add another reminder in the pip install section though. 
![image](https://user-images.githubusercontent.com/7566797/136599390-04a45a0f-d0d8-4693-8321-265b95f50809.png)
