### ISSUE TITLE
Corrupted glyph names in Segoe MDL2 assets icon page

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3314]
There are a number of these, notice the question diamond character:
![image](https://user-images.githubusercontent.com/22989529/130376730-885aec03-73b5-44d4-9b4b-a47e80bfcecc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d37086-12a4-7e39-bfed-1d7faaebed3e
* Version Independent ID: 52ddf580-e52d-cb51-9602-d733a58b21bc
* Content: [Segoe MDL2 Assets icons - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font)
* Content Source: [hub/apps/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/style/segoe-ui-symbol-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Good catch. I removed the characters. Thanks a lot 👍
