### ISSUE TITLE
Microsoft PowerToys: Windows 10 - Feature Suggestions

### ISSUE THREAD

**Issue by Ranger-Z** [MicrosoftDocs/windows-uwp#3317]
While this [page ](https://docs.microsoft.com/en-us/windows/powertoys/)has a section "Contribute to Power Toys" it focuses on how to write a contribution with, unless I am missing something, no actual way to submit a suggestion from the page.

So here I am.  

Windows 10 natively has no ability to configure a camera's settings so that these settings then default into video applications, specifically MS Teams (Which states they do not manage the camera, only use the windows camera), but also Zoom and Skype.  I am not suggesting anything radical, just basic crop, zoom and rotate functionality for conferencing.  There are plenty of $30+ solutions with color, blur, backgrounds, titles, etc.  I am advocating for very simple features to frame a better picture.

Use Case 1:  HD webcams do not enhance a typical video conference, indeed they add more superfluous background content to the left and right sides.  
Solution 1 - Crop the sides
Solution 2 - Rotate and zoom for portrait

Use Case 2: Internal Webcams (laptops and all in ones) are not always optimally pointed at the user, and may be considered fixed due to the devices screen angle.  It may not be able to optimally feature the user (ie off center).  The ability to crop would offer some improvement to the users picture.

This could be implemented as either an override to standard sttings or as a virtual cam.  I think an override would be best, eliminating the need for a user to select the virtual camera in a given application, and thus making it "just work".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Ranger-Z** [comment]
While this page has a section "Contribute to Power Toys" it focuses on how to write a contribution with, unless I am missing something, no actual way to submit a suggestion.

So here I am.  

Windows 10 has no ability to configure a camera's settings so that these settings then default into video applications, specifically MS Teams (Which states they do not manage the camera, only use the windows camera), but also Zoom and Skype.  I am not suggesting anything radical, just basic crop, zoom and rotate functionality for conferencing.  There are plenty of $30+ solutions with color, blur, backgrounds, titles, etc.  I am advocating for very simple features to frame a better picture.

Use Case 1:  HD webcams do not enhance a typical video conference, indeed they add more superfluous background content to the left and right sides.  
Solution 1 - Crop the sides
Solution 2 - Rotate and zoom for portrait

Use Case 2: Internal Webcams (laptops and all in ones) are not always optimally pointed at the user, and may be considered fixed due to the devices screen angle.  It may not be able to optimally feature the user (ie off center).  The ability to crop would offer some improvement to the users picture.

This could be implemented as either an override to standard sttings or as a virtual cam.  I think an override would be best, eliminating the need for a user to select the virtual camera in a given application, and thus making it "just work".

**Comment by mattwojo** [comment]
Hi @Ranger-Z -- Love this feature suggestions for PowerToys. This isn't quite the right place for it though as this repo is specific focused on feedback related to documentaiton updates or improvements. Please file your suggestion in the PowerToys product repo where the developers who build these features will see it, here's the link: https://github.com/microsoft/PowerToys/issues/new/choose

![image](https://user-images.githubusercontent.com/7566797/132425571-e2616b77-6a88-4fea-ae7f-b7fe676fa4d5.png)


I did a quick search in the existing issues and didn't find that anyone has already requested it (though I may have missed it if you want to search again). Closing this, but please let me know if you need any help getting this request filed in the other repo.

**Comment by Ranger-Z** [comment]
Matt

Thanks for the followup.  I will review and submit an idea, but I am not clear on how to find the original request I submitted for reference.  I tried search for my requests but got nothing.  Can you help please?

So, I guess regarding documentation, I will suggest that with this as my starting point, I was unable to get to where you linked.  This may just be my lack of familiarity with git.hub (it's really a mystery to me, is there a Git.hub for Dummies manual?),  but there is discussion on other aspects of wring requests, just I could not figure out where to properly go to submit the idea.

Thanks

BR

Steven Zallen
 

    On Tuesday, September 7, 2021, 8:14:12 PM EDT, Matt Wojciakowski ***@***.***> wrote:  
 
 


Hi @Ranger-Z -- Love this feature suggestions for PowerToys. This isn't quite the right place for it though as this repo is specific focused on feedback related to documentaiton updates or improvements. Please file your suggestion in the PowerToys product repo where the developers who build these features will see it, here's the link: Build software better, together


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 65 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |






I did a quick search in the existing issues and didn't find that anyone has already requested it (though I may have missed it if you want to search again). Closing this, but please let me know if you need any help getting this request filed in the other repo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ranger-Z** [comment]
Hi

I got the link fro here.  All set with the old request, though honestly not clear why Icould not somehow search ifor it with my name or the number.

NBD

Steven Zallen


 

    On Tuesday, September 7, 2021, 8:14:12 PM EDT, Matt Wojciakowski ***@***.***> wrote:  
 
 


Closed #3317.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
