### ISSUE TITLE
Too many characters in character literal

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#332]
ContentFrame.Navigated += 'On_Navigated'; raises CS1012.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#code-example)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by ghost** [comment]
this error is raised because the single quotes in On_Navigated.

Changing it to double quotes raises CS0029 (Cannot implicitly convert type 'string' to 'Windows.UI.Xaml.Navigation.NavigatedEventHandler'), though.

**Comment by serenaz** [comment]
Thanks for opening the issue! We've just fixed the code example, and changes should be published by tomorrow.
