### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jgedri** [MicrosoftDocs/windows-uwp#3325]
I'm a bit confused. In order to install the SDK, do I download it, build it and *then* add the NuGet package? Then why did I download the SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?tabs=desktop-csharp)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us with your feedback about the docs. 

Generally speaking, you need to install the Visual Studio extension for the Windows App SDK if you want to create new apps using one of the WinUI 3 project templates provided by the Windows App SDK. This process is documented in [Create your first WinUI 3 app](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app) (the article you commented on). 

If you just want to use features of the Windows App SDK in an existing app project (for example, a .NET desktop project or C++ native desktop project), then you can just install the NuGet package directly in your project without having to install the full Visual Studio extension for the Windows App SDK. This process is covered [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/get-started#use-the-windows-app-sdk-in-an-existing-project).

I'm not seeing any references to the NuGet package in [Create your first WinUI 3 app](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app). If you're still unclear about how to proceed with the docs, please reopen this issue and clarify which instructions you're referring to that involve installing the NuGet package for the Windows App SDK. Thanks in advance.
