### ISSUE TITLE
Streaming MediaPlayerElement Audio into AudioGraph

### ISSUE THREAD

**Issue by eliphatfs** [MicrosoftDocs/windows-uwp#3327]
AudioGraph offers a powerful organization of audio effects, while MediaPlayerElement enables smooth playback of video and audio files. However, it seems that I cannot apply audio effects with AudioGraph from MediaPlayerElement; there is a video frame server mode for media player element, but not an audio frame server. Synchronization issues may arise if I handle video and audio separately.

P.S. I know audio effects may be applied directly on MediaPlayer, but it will be much nicer to have some of the capabilities of AudioGraph.

**Comment by drewbatgit** [comment]
Hello, adding audio capabilities to the MediaPlayer's frame server mode does sound like an interesting feature. The issues in this repo are specifically for requesting updates to the documentation. [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
