### ISSUE TITLE
The element 'Capabilities' has invalid child element 'Capability'

### ISSUE THREAD

**Issue by Japollack** [MicrosoftDocs/windows-uwp#3330]
I have this Package.appxmanifest:
```
<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:uap3="http://schemas.microsoft.com/appx/manifest/uap/windows10/3"
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  IgnorableNamespaces="uap mp uap3 rescap">

  <!-- truncated -->

  <Capabilities>
    <rescap:Capability Name="broadFileSystemAccess" />
    <rescap:Capability Name="confirmAppClose" />
    <Capability Name="internetClient" />
    <!-- truncated -->
  </Capabilities>
</Package>
```

The _<rescap:Capability_ is underline and a warning is generated:

> The element 'Capabilities' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' has invalid child element 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities'.
> 
> List of possible elements expected: 
> 'CapabilityChoice' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10/3' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10/4' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10/6' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10/7' as well as 
> 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10/2' as well as 
> 'CustomCapabilityChoice' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' as well as 
> 'CustomCapability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10/4' as well as 'Dev....	MyApp	D:\MyApp\Package.appxmanifest	76

Even if I removed the _<rescap:Capability Name="broadFileSystemAccess" />_ then the next line will get the warning.
The documentation does not clarify this.

PS. I do not plan to distribute it through the Store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#special-and-restricted-capabilities)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I can reproduce this warning, and it appears to be a known issue with the way the underlying schema is parsed by Visual Studio. According to the response from the engineering team in [Warning for rescap: Capability in App Manifest file](https://developercommunity.visualstudio.com/t/warning-for-rescap-capability-in-app-manifest-file/49561), this issue has not met the priority bar to fix. You should be able to successfully build your project and can ignore this warning. 

Do note that rescap: capabilities are *restricted capabilities*, and make sure you've read the information [here](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities) to understand the contexts in which they may be used.
