### ISSUE TITLE
The links to download the Speed Platform SDK (11) and Speech SDK (5.1) are broken.

### ISSUE THREAD

**Issue by mnissl** [MicrosoftDocs/windows-uwp#3334]
The links to download the Speed Platform SDK (11) and Speech SDK (5.1) are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5532269-6b52-2288-ddf1-8c2e8d52e2db
* Version Independent ID: 9106566d-48f5-25fa-67d6-978ac385dff9
* Content: [Speech, voice, and conversation in Windows 10 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/develop/speech)
* Content Source: [hub/apps/develop/speech.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/develop/speech.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @mnissl. The downloads have been reinstated and the links should work again.
