### ISSUE TITLE
Japanese Translation "Node.jis --> Node.js" 

### ISSUE THREAD

**Issue by Neko7sora** [MicrosoftDocs/windows-uwp#3335]
ja-jp: https://docs.microsoft.com/ja-jp/windows/dev-environment/javascript/nodejs-on-wsl
![image](https://user-images.githubusercontent.com/75793267/132026230-445d7766-b3f0-44e6-bca4-af1f596e5e85.png)
![image](https://user-images.githubusercontent.com/75793267/132026324-5cfb3660-8313-41cf-a0c8-e1bd70a26011.png)

**Comment by Neko7sora** [comment]
The Japanese repository is not public, so I created an issue.
ja-jp:
![image](https://user-images.githubusercontent.com/75793267/132027697-1200b81f-9728-4bb3-8c63-a0e851f17f97.png)
en-us:
![image](https://user-images.githubusercontent.com/75793267/132027773-92384df3-c48d-465d-8aa4-b8ae728ef5e8.png)

**Comment by GrantMeStrength** [comment]
Assigned to loc team, issue #598393

**Comment by GrantMeStrength** [comment]
Thank you for reporting this!

**Comment by GrantMeStrength** [comment]
This has been corrected.

**Comment by naruya** [comment]
Same issue faced again... :sob:

<img width="320" alt="スクリーンショット 2024-08-03 234801" src="https://github.com/user-attachments/assets/d0f7108a-a90a-4b56-8d71-b3ded7d7f8e1"> <img width="320" alt="スクリーンショット 2024-08-03 234157" src="https://github.com/user-attachments/assets/6c321463-ab24-4f81-a15e-974ffbe3a147">
