### ISSUE TITLE
obsolete IP exclusion list ?

### ISSUE THREAD

**Issue by manfredczujan** [MicrosoftDocs/windows-uwp#3337]
Hi MS Team,

I'm working on a connection issue regarding WPN to UWP app.
Today i found the following issues, which are not alligned with your attached document (
 the document is called:  Windows Notification Service (WNS) VIP and IP Ranges

Today my app got pushes from:  20.199.120.85
And the channel link is ending to: 20.199.121.23

Both adresses are NOT in the above mentioned document.
Pls. can you clarify this issue ?
br
Manfred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc21ecc9-8e17-f8af-0b18-84640a75ed7c
* Version Independent ID: 5cd94071-e41d-a308-d268-0a568dcd59f8
* Content: [Adding WNS Traffic to the Firewall Allowlist - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/firewall-allowlist-config)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/firewall-allowlist-config.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/firewall-allowlist-config.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
