### ISSUE TITLE
Old screenshot (shows Project Reunion)

### ISSUE THREAD

**Issue by LyalinDotCom** [MicrosoftDocs/windows-uwp#3338]
[Enter feedback here]

I think we should update the screenshot to show Windows App SDK in the screenshot instead of Project Reunion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. This article has been updated, and the relevant section no longer has a screenshot. We may re-introduce updated screenshots in an upcoming doc update.
