### ISSUE TITLE
Provide more information about input and output binding

### ISSUE THREAD

**Issue by leeprtc** [MicrosoftDocs/windows-uwp#334]
Please provide more information about how binding of inputs and outputs to the model work so one can better debug binding issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd018cd-e51b-b15b-3460-8ff4a4a83f3b
* Version Independent ID: 4f95e997-6554-9384-5f57-a193e4c85bf8
* Content: [Get started with Windows Machine Learning - UWP app developer | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started)
* Content Source: [windows-apps-src/machine-learning/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/get-started.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for raising the issue @leeprtc ! Can you please clarify your problems with binding so we can provide more specific information?

**Comment by leeprtc** [comment]
Right now, if you get binding errors, it is somewhat hard to figure out what the issue is. If there is more information on how binding works, it will be easier to debug.

**Comment by serenaz** [comment]
Ok, are you using the automatic code generation with mlgen or within Visual Studio? Are you encountering problems with the Get Started MNIST sample, or another model?

**Comment by leeprtc** [comment]
I'm using mlgen with another model. Just to be clear, my request for more info about how binding works is not necessarily for this page. Rather it is for Windows ML documentation in general.

The Visual Studio automatic code generation does not seem to work for me as when I add the onnx file to my project, nothing happens. I used Visual Studio 15.7 Preview 1 and had Insider Preview SDK Build 17110 installed.

**Comment by serenaz** [comment]
OK, we're working on providing more information about binding.

As for the automatic code generation, you'll need to check off the optional Windows 10 Insider Preview SDK (11710) in the Visual Studio Installer. We've updated the docs to clarify.
