### ISSUE TITLE
GitHub links still point to "ProjectReunion"

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#3340]
The numerous links to the GitHub project all point to the old code-name. They should be updated to point to the Windows App SDK github directly instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b0cc3d-3662-21c9-ec5f-9793616ea5fc
* Version Independent ID: 96289e4e-417b-28b9-8f1c-d561e3afab22
* Content: [Build desktop Windows apps with the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/)
* Content Source: [hub/apps/windows-app-sdk/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/index.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. These links have now been updated to point directly to the latest GitHub repo URL.
