### ISSUE TITLE
There are 2 rows with the same Settings page under System

### ISSUE THREAD

**Issue by adriancuadrado** [MicrosoftDocs/windows-uwp#3343]
There are 2 rows with the same Settings page under *System*:
* Display: ms-settings:display
* Display: ms-settings:screenrotation
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Sorry, I can't quite see what you mean. It's possible an error has been corrected already, or I'm just missing it?
If it's still wrong please re-open this issue, thanks!
