### ISSUE TITLE
Check version when using scoop

### ISSUE THREAD

**Issue by antonburger** [MicrosoftDocs/windows-uwp#3345]
The version on scoop at time of writing is 0.21.1, released more than a year ago now and much older than current at 0.45.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @antonburger - Please file an issue in the [Scoop repo on GitHub](https://github.com/lukesampson/scoop/issues). Unfortunately Scoop is a 3rd party tool that we don't have control over updating.
