### ISSUE TITLE
How are the docs being translated to other languages?

### ISSUE THREAD

**Issue by stefanov-stefan** [MicrosoftDocs/windows-uwp#3351]
Hey folks,

I have a question - how are the docs being translated to other languages - here is an example of german article: https://docs.microsoft.com/de-de/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel

In the repo I only see MD files in English? Or is it some automated translation?

**Comment by GrantMeStrength** [comment]
Hi -

Most topics are translated by a ML system, but some are done by hand. There is no repo that is accessible containing German (or any language other than English).

The URL you shared contains de-de, which means your browser gets this translated version. You can adjust settings to always see English if you prefer.

If you need to make a specific correction to German content, please create another issue with feedback on that topic and it can be passed to the localization team.

thanks!

-john
