### ISSUE TITLE
Change Windows.UI.Colors.... to Microsoft.UI.Colors....

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/windows-uwp#3356]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae136ba2-802e-2a6b-5a97-90dd6738a1b0
* Version Independent ID: edb07b26-18bc-651f-ca82-ea00137abc7b
* Content: [Title bar customization - Windows apps](https://docs.microsoft.com/en-gb/windows/apps/design/shell/title-bar)
* Content Source: [hub/apps/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/title-bar.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jwmsft** [comment]
Should be Microsoft.UI.Colors for WinUI 3/Windows App SDK, and Windows.UI.Colors for WinUI 2. I didn't find an issue with this in the doc.
