### ISSUE TITLE
It does not work, strange error

### ISSUE THREAD

**Issue by MoawwizAhmed** [MicrosoftDocs/windows-uwp#336]
I tried using this method and i had added winmd and windows.runtime.windowsruntime.dll using this link,https://blogs.windows.com/buildingapps/2017/01/25/calling-windows-10-apis-desktop-application/  
, i need to use the graphics library for brightness override and it requires systemManagement capability but as soon as i add packaging project , the solution will not build , it does not display the error , on warning on capabilities. squiggly on systemmanagement or <rescap:Capability Name="runFullTrust" />. I need help .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f4864c-3cf6-a957-dd26-c16cb4a3015e
* Version Independent ID: c9543586-cf91-3c13-50e0-1837cf4138a4
* Content: [Package an app by using Visual Studio (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by MoawwizAhmed** [comment]
i am using it for Wpf project .

**Comment by MoawwizAhmed** [comment]
anyone?

**Comment by normesta** [comment]
Hello. Please have a look at the guidance in this topic - https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance. It contains guidance about what sort of references you'll need to have to call Windows 10 APIs.

**Comment by MoawwizAhmed** [comment]
Thanks for your help, now packaging project works on my other projects, but the project that i want to use it for has to use a dll file that is built on c++, and i am still getting errors on that project when i build packaging project. Is there anything that i can do ?

**Comment by normesta** [comment]
Hello - this stack post looks like it might help with this issue - https://stackoverflow.com/questions/48754557/packaging-winforms-application-along-with-native-dll.

**Comment by MoawwizAhmed** [comment]
I will try that , thanks.
