### ISSUE TITLE
This page answered my questions

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/windows-uwp#3364]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc48efcd-ad3f-1b01-6a6a-a6865b4b7624
* Version Independent ID: 84184d50-3c9b-cce9-6007-3ef2e954cdf5
* Content: [Load images and assets tailored for scale, theme, high contrast, and others - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/images-tailored-for-scale-theme-contrast)
* Content Source: [windows-apps-src/app-resources/images-tailored-for-scale-theme-contrast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/images-tailored-for-scale-theme-contrast.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks!
