### ISSUE TITLE
Page is unclear about native ARM64 win32 apps

### ISSUE THREAD

**Issue by BreeceW** [MicrosoftDocs/windows-uwp#3366]
This page seems to imply that only UWP apps can be natively run on ARM64, and win32 apps must be emulated. As far as I know, compiling and running native ARM64 win32 apps is a fully supported scenario, so it would be helpful if this page could clarify the current state of ARM64 win32 apps under the “Win32 apps” heading. It would also be helpful to know if there any special requirements for ARM64 win32 apps, for example, to run unsigned ARM64 win32 binaries, does the device need to be in developer mode?

While I am fairly sure ARM64 win32 apps are a supported thing, it is not clear if ARM32 win32 [or even UWP at this point] apps are. Clarifying that might be helpful, as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c920a34-495e-ae99-365a-f6bc0afa2052
* Version Independent ID: 1e3c088d-3ca5-7f26-b1f6-23d9c97918e7
* Content: [Windows on ARM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm)
* Content Source: [windows-apps-src/porting/apps-on-arm.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I just merged @Jaiganeshkumaran's PR that clarifies this point. Thanks to both of you for noticing and fixing the issue.
