### ISSUE TITLE
Something wrong with the markdown table

### ISSUE THREAD

**Issue by charlespetzold** [MicrosoftDocs/windows-uwp#337]
I'm seeing the vertical bars, headers, dashes, and contents of the markdown table on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b317978e-12a2-09ab-ca25-33835878d538
* Version Independent ID: c654c9f0-4813-8b88-e2fc-4636612fba36
* Content: [Windows Runtime components - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/index)
* Content Source: [windows-apps-src/winrt-components/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/index.md)
* Service: **unspecified**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by TylerMSFT** [comment]
Hi Charles,
I have a fix. It should be live by Monday (the next time we push to live)
