### ISSUE TITLE
.NET Use case for node.js frontend builds?

### ISSUE THREAD

**Issue by appymedia** [MicrosoftDocs/windows-uwp#3370]
Would it be a good idea to point out there are some valid professional reasons you would still want to use Node and frontend build tools etc in Windows vs WSL?

I'm working on a .NET Core Razor Pages based project on Windows and would like to use Node for frontend build tools and packaging.  Things like compiling SCSS, minifying JS and maybe a little Webpack usage for pulling in and bundling in community JS bits and pieces to help with my Razer Pages.

I came to this page expecting some validation of use cases on Windows for projects like mine but left wondering what exactly the best practise is?

Reading through the Microsoft documentation if you use node.js in anyway that's professional you should use WSL.  Trouble is that becomes nearly impossible to manage in a .NET type project like mine in an IDE etc.

I'm also thinking just how would Blazor web developers handle JS pieces they need to pull in and package up etc, WSL again seems tricky at best to use alongside.  I'm guessing everybody is currently using a native Windows install of node.js which again is another very valid 'professional' use case.

I've looked at the node.js repo and as expected Windows is down as a Tier 1 OS with support on par with Linux and MacOS etc.  Totally understand why using it on WSL is better in a lot of ways.  If I was building an isolated React frontend I'd reach for WSL for instance.

I'm just trying to point out there are valid professional use cases and the docs currently cause confusion (to me anyway :))

Here's some of the pages that might need clarification...

https://docs.microsoft.com/en-us/windows/dev-environment/javascript/windows-or-wsl
https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl
https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows

There's some more in the React and Vue getting started areas as well.

Many thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08e8c321-52c2-f80d-1004-274547ca362e
* Version Independent ID: 943bb38d-635e-2772-d61e-5e85f301d259
* Content: [Should I install on Windows or Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/windows-or-wsl)
* Content Source: [hub/dev-environment/javascript/windows-or-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/windows-or-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Well... this is an embarrassingly slow reply, but this issue got buried among all of the other feedback. That said, I'm finally combing through old issues and agree with you that the guidance to use Node on WSL for "professional" use isn't accurate. I've removed the Windows vs WSL guidance as I actually don't think it's helpful any longer. Both Windows and Linux (or WSL) have professional uses for NodeJS and I don't think we actually need to offer guidance on which to use... it will mostly depend on individual circumstances and preferences. Anyhow, here's the commit where I removed all of that guidance: https://github.com/MicrosoftDocs/windows-dev-docs/commit/2197bc6ffeb413324b55e52d2e1ac29c2f555ea2
Closing this issue and thanks for filing it. (and sorry again it took so long to resolve!)

**Comment by appymedia** [comment]
No problem, glad to see the updates 👍

**Comment by k-ode** [comment]
Isn't the section `Use Windows Subsystem for Linux for production` also outdated?

* Node.js has Tier 1 support for running on Windows & Windows Server, same as Linux
* The iisnode repository is owned by Azure
* Azure supports Nodejs apps on Windows Servers
* Needing to host a Node.js app on a Windows Server is less of an edge case now with popular frontend frameworks
  like Next.js and Remix
