### ISSUE TITLE
purchasePriceLocalAmount	Description seems wrong

### ISSUE THREAD

**Issue by TS-MSFT** [MicrosoftDocs/windows-uwp#3372]
[Enter feedback here]
pruchasePriceLocalAmount is described as "The tax amount applied to the add-on." when it should be something related to displaying the price in the local currency?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103adf9b-5330-faf8-5eb8-064df638a936
* Version Independent ID: 890ae043-82aa-d0d6-0837-8dc84c60dd1c
* Content: [Get add-on acquisitions data for your games and apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/add-on-acquisitions-data#feedback)
* Content Source: [windows-apps-src/monetize/add-on-acquisitions-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/add-on-acquisitions-data.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for the report. I've made this change. Expect it to be published by the end of the day.
