### ISSUE TITLE
Invalid link form LayoutCycleException 

### ISSUE THREAD

**Issue by vgromfeld** [MicrosoftDocs/windows-uwp#3373]
In 
> These loops cause a condition where a valid layout can't be created and the system can throw a LayoutCycleException if the loop is not recoverable.

The `LayoutCycleException` link  is opening the [XamlParseException documentation](https://docs.microsoft.com/en-us/dotnet/api/windows.ui.xaml.markup.xamlparseexception?view=dotnet-uwp-10.0&preserve-view=true) instead of the [LayoutCycleException documentation](https://docs.microsoft.com/en-us/dotnet/api/windows.ui.xaml.layoutcycleexception?view=dotnet-uwp-10.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61212330-2782-b5c0-4880-365e819ea4cd
* Version Independent ID: 2e758efb-bf2f-a1dc-ea2f-06e0b5472984
* Content: [XAML custom panels overview - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/layout/custom-panels-overview)
* Content Source: [hub/apps/design/layout/custom-panels-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/layout/custom-panels-overview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The link is fixed.
