### ISSUE TITLE
The page has invalid markdowns.

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#338]
See screenshot ![invalid areas](https://user-images.githubusercontent.com/1608424/37526005-ba49dec4-2904-11e8-8ba4-5cd645f44223.png)

**Comment by ginami** [comment]
Hi @ArchieCoder -- what page are you referring to? Thank you!

**Comment by ArchieCoder** [comment]
Hi @ginami https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services#code-examples

**Comment by ginami** [comment]
Thanks! @mcleanbyron, can you please respond?

**Comment by mcleanbyron** [comment]
Thanks for reporting this problem. This was caused by a recent infrastructure change to a new Markdown parser used for our docs, and I have already fixed this problem in the latest published version of the article (as of 3/16/18).
