### ISSUE TITLE
using static PInvoke.User32; is needed for Apps.xaml.cs

### ISSUE THREAD

**Issue by Gucchiy** [MicrosoftDocs/windows-uwp#3382]
[Enter feedback here]
"using static PInvoke.User32;" is needed for calling Win32 APIs.
Beginners may be able not to build / execute the sample because of lacking the using directive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 053e4864-ba80-e65e-a7d3-694ce86ca102
* Version Independent ID: 618fd334-462f-ae7c-8eb9-2e1a8bef685c
* Content: [Build a C# .NET 5 app with WinUI 3 and Win32 interop - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-winui3-app-with-basic-interop)
* Content Source: [hub/apps/winui/winui3/desktop-winui3-app-with-basic-interop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/desktop-winui3-app-with-basic-interop.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for pointing out this oversight. Topic has been revised.
