### ISSUE TITLE
Non-working Link in section "Update Existing Apps"

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3383]
In this page, section "Update Existing Apps", the bullet that begins with the link "Install the Windows App SDK NuGet package" leads to a 404-Page Not found when that link is clicked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25fcf332-0c1b-7c10-406d-bfd5f6eef952
* Version Independent ID: d2b12b06-f936-204b-1be7-9ca844ceff43
* Content: [Overview of app development options - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/?tabs=winui3)
* Content Source: [hub/apps/get-started/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for letting us know. This link has been fixed - it should point to https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project.
