### ISSUE TITLE
DWMWA_WINDOW_CORNER_RADIUS not in Windows 11 SDK

### ISSUE THREAD

**Issue by peter-frentrup** [MicrosoftDocs/windows-uwp#3387]
The Last examples mentions `DWMWA_WINDOW_CORNER_RADIUS` to read the current corner radius with DwmGetWindowAttribute. However, that constant is not part of the Windows 11 SDK (10.0.22000.0, dwmapi.h). 

Please provide the value of `DWMWA_WINDOW_CORNER_RADIUS`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cd4ed11-b246-94af-c310-514326282eaf
* Version Independent ID: 5a1dbf05-790d-525b-bcc6-01857c1687de
* Content: [Apply rounded corners in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners)
* Content Source: [hub/apps/desktop/modernize/apply-rounded-corners.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/apply-rounded-corners.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This documentation was written while the feature was in preview and `DWMWA_WINDOW_CORNER_RADIUS` did not make the final SDK release. The example was removed in this commit: https://github.com/MicrosoftDocs/windows-dev-docs/commit/37a3707658734f1b8a2ec23fde241a13290e3d00
