### ISSUE TITLE
OpenCV for UWP libraries are abandoned

### ISSUE THREAD

**Issue by oleksandr-bilyk** [MicrosoftDocs/windows-uwp#339]
Here you are using "OpenCV.Win.Core" and other nuggets last published in 2016 year and their Project URL is abandoned: https://github.com/cvwin/cvwin
There are problems with all MSDN articles about UWP + 'C++/CX' + OpenCV. 
Look at related issues below:
1. ""OpenCVExample/CPP" sample depends on abandoned "Microsoft/opencv" repository" - https://github.com/Microsoft/Windows-iotcore-samples/issues/119
2. "Microsoft you should support OpenCV!!!" - https://github.com/Microsoft/opencv/issues/82
3. "VS Git clone doesnt' download nested folders" - https://developercommunity.visualstudio.com/content/problem/214893/vs-git-clone-doesnt-download-nested-folders.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46cb9af7-d8dc-cc44-dbb2-d2b097f604ee
* Version Independent ID: cc2d4d5d-2698-299b-1e71-dae2a984f95b
* Content: [Process bitmaps with OpenCV - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-software-bitmaps-with-opencv)
* Content Source: [windows-apps-src/audio-video-camera/process-software-bitmaps-with-opencv.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/process-software-bitmaps-with-opencv.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbatgit**

**Comment by laurenhughes** [comment]
I've updated the page to reflect that the packages are out of date, but still available. The current guidance for this scenario is to continue using the OpenCV.Win.x packages to create an OpenCV helper. 

Updates will be published tomorrow. Thanks for pointing this out!
