### ISSUE TITLE
Possibly incorrect information about Visual C++ Runtime

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftDocs/windows-uwp#3390]
The article states that 'If your application is not packaged in an MSIX package for deployment, the computer must have the Visual C++ Runtime installed.', however, this seems incorrect. On all machines I have tested on, XAML islands work absolutely fine, including a completely new Windows 10 1909 virtual machine that wasn't even connected to the internet (I also checked Apps & Features and it didn't show any Visual C++ Runtime installed)  - I tested multiple .Net Framework apps that used the XamlHost Nuget package and XAML islands worked just fine, and that was just running the executable, no installation so no prerequisites were automatically installed or anything like that.

Also, some components in Windows 10 and 11 use XAML Islands by default (Such as magnifier) without needing to install anything extra.

It seems to me that either the correct version of Visual C++ Runtime comes as part of Windows 10 or XAML islands do not require it. If this information could be clarified, that would be great as I would like to make sure any required prerequisites either come with Windows 10, or can be installed as part of my apps' installers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d29a354-62d8-f881-7338-71a2fe60644e
* Version Independent ID: 234b48b4-9c6c-db8b-626c-0bd98d7a63a7
* Content: [Host WinRT XAML controls in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands)
* Content Source: [hub/apps/desktop/modernize/xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/xaml-islands.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
@marb2000 can you confirm?

**Comment by marb2000** [comment]
I think Windows 10/11 and Windows Server 2016 come with the Visual C++ Redistributable installed. But not sure if It comes within all the Windows 10 SKUs.
