### ISSUE TITLE
Some misleading points in comparison between WinUI 3 and 2

### ISSUE THREAD

**Issue by BreeceW** [MicrosoftDocs/windows-uwp#3393]
The docs for “Comparison of WinUI 3 and WinUI 2” could leave some readers with a false impression of WinUI.

_“WinUI 2 cannot be used to build desktop/Win32 Windows apps.”_ There are several win32 apps using WinUI 2, such as Windows Terminal and PowerToys and a few non-Microsoft apps. XAML Islands should be mentioned here.

_“Part of WinUI 2 ships within the operating system itself”_ This is more of a nitpick, but as far as I am aware, the Windows.UI.Xaml APIs are completely independent of WinUI 2, work without WinUI 2, and none of WinUI 2 is really in the OS.

_“WinUI 2 supports C# and .NET Native apps only.”_ This is problematic because as far as I am aware, VB.NET is still supported, and more importantly, C++ (i.e. not .NET) is supported. (Also, I was under the impression that not compiling .NET Native was a supported scenario, just not for Microsoft Store deployment.) It then says “WinUI 3 supports C# and .NET 5 for desktop apps,” which does not preclude the possibility of C++ being supported, but it should be expanded to list all the support languages for WinUI 3. I am also not clear if VB.NET support is dropped in WinUI 3, so it would be pertinent to note this if so.

_“WinUI 2 supports the WebView control”_ (in contrast with WinUI 3 supporting WebView2). It may be relevant to mention that WinUI 2 has the WebView2 control as well in its pre-releases.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea32f1f-67e6-12f4-7aa0-602184a377fd
* Version Independent ID: 3adf7079-1ead-0e1a-0af9-7de72d30117f
* Content: [Windows UI Library (WinUI) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/)
* Content Source: [hub/apps/winui/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by BreeceW** [comment]
Would be resolved by #3395

**Comment by Karl-Bridge-Microsoft** [comment]
https://github.com/MicrosoftDocs/windows-uwp/pull/3395 merged.
