### ISSUE TITLE
Clarify differences between WinUI 3 and WPF (and win32)

### ISSUE THREAD

**Issue by BreeceW** [MicrosoftDocs/windows-uwp#3394]
One very common phenomenon I see among Windows developers on forums, Q&A sites, and chatrooms is a shockingly pervasive and perplexing conflation of WinUI 3 and WPF. Some developers seem to have an impression that they are the same, are compatible, or are in some way related in a non-superficial manner. I think it would be beneficial for this and/or some other introductory pages to clarify the differences and that they are distinct products.

I also think there is a large amount of confusion around what “UWP” and “win32” and even “WPF” refer to, which make having conversations about WinUI 3 very difficult. The docs need to do a better job explaining, front and center, what the difference between these terms are, especially as they can mean different things in different contexts (e.g. “is UWP/win32 an app model? Or an API?”). I don’t think describing “win32” as “desktop” is necessarily sufficient, as many of us have been making our desktop apps in UWP just fine for years. It also seems like some developers think WPF is an app model (in this case not sandboxed), so they conclude that because WinUI 3 is also not sandboxed, it must be WPF somehow.

I think it would help the adoption of WinUI 3 to have a very clear and accurate description of what these terms mean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea32f1f-67e6-12f4-7aa0-602184a377fd
* Version Independent ID: 3adf7079-1ead-0e1a-0af9-7de72d30117f
* Content: [Windows UI Library (WinUI) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/#feedback)
* Content Source: [hub/apps/winui/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
The WinUI and WinApp SDK content has been updated significantly over the last few months.

Please open a new issue with details if you still find any shortcomings wrt how the WinApp SDK is differentiated from legacy technologies.
