### ISSUE TITLE
Touch target user study information

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3398]
I'd love to see more information about user testing that was done for these touch targets. Particularly on what results were found or what we should expect from users when moving from a 40x40 to a 32x32 touch target size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3772a500-d048-2c68-cd90-8dd308f8e1cd
* Version Independent ID: 9587d690-aef5-7d98-4572-4a889ac836e6
* Content: [Targeting - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/guidelines-for-targeting)
* Content Source: [hub/apps/design/input/guidelines-for-targeting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/guidelines-for-targeting.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the request, @sproketz. We're currently underway with a reorg of our design docs. I'm not sure this is detail the design team would publish, but we'll include it if they request.
