### ISSUE TITLE
Checkboxes don't render in table.

### ISSUE THREAD

**Issue by milazzom** [MicrosoftDocs/windows-uwp#340]
Readers of the documentation see ':heavy_check_mark:' instead of a rendered check mark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a43e99-2699-6568-6d37-6fe72286ae3c
* Version Independent ID: dfe8c8e7-a573-32e0-cb6c-efbdadc9b00f
* Content: [Extend your app with services, extensions, and packages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/extend-your-app-with-services-extensions-packages)
* Content Source: [windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi, this is a known issue that should be fixed in a day or two.
