### ISSUE TITLE
Small Spelling Mistake

### ISSUE THREAD

**Issue by RyanGroom** [MicrosoftDocs/windows-uwp#3403]
[Enter feedback here]
URL: https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version
Wrong Spelling: This verion of Windows 10 was released in October 2017.
Correction: Change "verion" to "version"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd1ff7f3-d77d-b7bd-8dfa-7f25cb0b5239
* Version Independent ID: 71e57b3b-b25f-0299-2cbc-f895a98c685d
* Content: [Choose a UWP version - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version)
* Content Source: [windows-apps-src/updates-and-versions/choose-a-uwp-version.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/updates-and-versions/choose-a-uwp-version.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for the report. I've made this fix; it should be live by the end of the day
