### ISSUE TITLE
How to test purchasing an app several times by the same user

### ISSUE THREAD

**Issue by Brett208** [MicrosoftDocs/windows-uwp#341]
Hello,

I have a game leveraging UWP that has a free trial portion (demo) where the rest of the game is only available after purchasing. I need to test the purchase code and understand that I must submit the app for certification before testing using the Windows.Services.Store code.

I would like to test purchasing the game a couple of times using my own account before going through the trouble of sending it to Beta testers. Is there a way for me to test it a couple of times on my own (IE purchase it and then have my account forget that I purchased it)? I didn't see it explained in the article.

Thanks,
Brett

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e4f08b-3a66-b4d8-292a-99dec9e65145
* Version Independent ID: a612ada5-d632-aa87-3c58-457c9decacb3
* Content: [Beta testing and targeted distribution - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/beta-testing-and-targeted-distribution)
* Content Source: [windows-apps-src/publish/beta-testing-and-targeted-distribution.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/beta-testing-and-targeted-distribution.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for your question. Unfortunately there is no way for the same Microsoft account to "unpurchase" an item once it's been purchased, so if you wanted to test the purchase action multiple times, you'd need to use a different Microsoft account every time. We'll be updating this topic soon and will add info to make that clear. More about testing trials and in-app purchases is described at https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#testing.
