### ISSUE TITLE
Microsoft.Windows.CsWinRT nuget package missing keywords and also doesn't install correctly.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#3410]
In the walkthrough you say "Search for the Microsoft.Windows.CsWinRT NuGet package and install the latest version."

So I searched for C#/WinRT and C# WinRT and I didn't find anything. Even searching for WinRT I only see the C++ package. I think you need to check your keywords or something. In the end I found it by looking for the exact package name.

Secondly, Installing the package produced 2 errors:

Error 1
Windows Metadata not provided or detected.  See https://github.com/microsoft/CsWinRT/tree/master/nuget/readme.md	...\Microsoft.Windows.CsWinRT.targets 83

Error 2
MSB3073	The command ""C:\Users\...\microsoft.windows.cswinrt\1.3.5\cswinrt.exe" @"D:\Projects\...\ApplicationXaml (Package)\obj\x64\Debug\Generated Files\cswinrt.rsp"" exited with code 1.	ApplicationXaml (Package)	C:\Users\...\Microsoft.Windows.CsWinRT.targets	115	

How are we meant to proceed?

The package is now visible under Project / Dependencies / Packages but the Nuget Package Manager shows it not installed. Repeating the install doesn't help and produces the same errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40b34b2-1bc9-25ed-b91e-cee68bc9edc1
* Version Independent ID: ecfcea0e-cad5-f4c7-6ab2-6970d4e8adcb
* Content: [Walkthrough to Generate a C# projection from a C++/WinRT component and distribute as a NuGet package for .NET 5+ applications - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by angelazhangmsft** [comment]
@Gavin-Williams, thanks for the feedback. We can add a nuspec keyword for "C#/WinRT" with the next release - I also would expect a search for "C#/WinRT" to find the package.

- For Error 1: if you set your `TargetFramework` to a specific Windows SDK version, e.g. `net5.0-windows10.0.19041.0`, this will automatically set the property `CsWinRTWindowsMetadata`. More info on that error in [these docs](https://docs.microsoft.com/windows/uwp/csharp-winrt/#common-errors-and-troubleshooting).
- For Error 2: It seems like the CsWinRT package is installed in a packaging project *ApplicationXaml (Package)*. Would you be able to confirm whether it is installed in the main app/library project or in a packaging project?

**Comment by Gavin-Williams** [comment]
At first I couldn't find the nuget package so I used package manager console to install it - but when I didn't see it installed, I guess because it had installed into the packaging project instead of the Library wrapper project, I went and worked out how to find it and install it with the nuget packager. So I had it both in the package project and the wrapper library project.

Your comment led me to realize what has happened and I've removed the CsWinRT package from the package project. Leaving it in the wrapper project. That removes error 2. 

However, regarding your suggestion to set the TargetFramework to a specific SDK version, what do you mean? I don't have that option. I have the TargetFramework set to .NET 5.0. The only other options are .Net Core versions. Is this another case where I have to edit something manually? EDIT: OK, yep, I haven't finished the walkthrough, I see that it does talk about what you're suggesting. Let me work through what it says and it might resolve the issue. I just stopped when it seemed like I had veered off the course.

So, now I have more problems. In the tutorial, in the section **Edit the project file to execute C#/WinRT** it says add this to the projection project sheet...

```
<PropertyGroup>
  <CsWinRTIncludes>SimpleMathComponent</CsWinRTIncludes>
  <CsWinRTGeneratedFilesDir>$(OutDir)</CsWinRTGeneratedFilesDir>
</PropertyGroup>
```
But Visual Studio wont let me do it. I paste it, and save is grayed out. And if I close the property sheet, the edit is lost. The csproj file is in a constant edited state with an asterisk.

Restarting VS fixed that issue and I managed to update the csproj to contain <Platforms>x64</Platforms> but now my projection project is reporting a blue asterisk

```
There is no project configuration matching the active solution configuration...
```
I'm targeting x64, so I removed any configuration for AnyCPU but I still have the blue asterisk.

So I went through and activated all the dropdowns in configuration manager - without editing anything - and bizarrely, that caused the blue asterisk to go away. 

After I got to the section where I can build the projection and nuget package. It failed. I assume because since I'm not following the tutorial exactly, my namespace and project names don't match, so I have errors. The walkthrough doesn't seem to disambiguate which strings are related to namespace and which are related to project name.  For example, I've brought in a project called Graphics but the walkthrough suggests I calls one project GraphicsProjection and the other GraphicsComponent. I don't know what that means for the project output. What will the library be called for example? I don't think I want my nuget package being called GraphicsProjection.

There are also two errors...
```
CS0234	The type or namespace name 'Xaml' does not exist in the namespace 'Windows.UI' (are you missing an assembly reference?)	GraphicsProjection	D:\GraphicsProjects\_build\x64\Release\GraphicsProjection\bin\Graphics.cs	154
```
So I renamed the project from GraphicsComponent to Graphics to align the namespace and project name. And I had to go through the .nuspec file and manually update strings and I can only assume I have to manually update the project reference in GraphicsProjection.csproj because it didn't update (this is fun) But I get the same errors.

This is all really wrong. I think you need to scrap this whole procedure and replace it with an automated procedure. All you're doing by having people follow all these steps is introduce complexity and points of failure. Maybe you could add a project context menu item for runtime components : Generate C# Wrapper - I reckon that would be heaps easier and quicker.

Please tell me that come next month, this will all go away, and we will have an easy way to create C# wrappers.

**Comment by Gavin-Williams** [comment]
I've renamed folders and updated strings throughout the csproj and nuspec files. But I'm left with this..
```
NU1104	Unable to find project 'D:\Projects\...\Graphics\GraphicsComponent.vcxproj'. Check that the project reference is valid and that the project file exists.	GraphicsProjection
```

I just can't help but wonder what I'm doing at this stage. I'm hours into this procedure and I can't get it to work. What was wrong with the previous system and the one before that where we just added a reference to the project?

Edit: After rebuilding the C++ project separately and then checking paths AGAIN and then rebuilding the solution, I seemed to have sorted out the project references. I'm now left with these errors...
```
CS0234	The type or namespace name 'Xaml' does not exist in the namespace 'Windows.UI' (are you missing an assembly reference?)	GraphicsProjection	D:\...Graphics.cs	154	Active
```
![Xaml NS Missing](https://user-images.githubusercontent.com/4374176/137948707-7ea453d0-8181-48a3-a0bc-ad52773abe90.PNG)

**Comment by angelazhangmsft** [comment]
@Gavin-Williams - a few things:

- NuGet package name and project names are up to the developer. The walkthrough is a specific example and there are no restrictions on the project naming. If it helps, we can add a note in the docs to clarify this. The nuspec is also an example and would need to be customized for each component.
- Could you describe what your scenario is/what dependencies your component has? We currently do not officially support `Windows.UI.Xaml` projections (only WinUI3/`Microsoft.UI.Xaml`). We should probably add a note on this limitation in the docs as well.
- I agree there are gaps in the developer experience with generating C#/.NET 5 projections. You should be able to reference the C# projection/library project from your app, but will need to add a C#/WinRT package reference in your app as well. I would file specific issues/see if they first exist in the [CsWinRT repo](https://github.com/microsoft/CsWinRT) to get a better answer.

**Comment by Gavin-Williams** [comment]
OK. I brought this component over from a UWP application I suppose. Well it was a Win32 app but I think it had UWP code in it. If that's causing a problem I can pull out the UWP code, it's just for Window/Swapchain construction.

Actually, I just searched for Windows.UI.Xaml in my component and it's not found. Where would CsWinRT be getting that from?

In the components references ... Windows.UI.Xaml.Core.Direct.XamlDirectContract but I don't know why that's there, it must be part of the project setup. It's a Universal Windows project because it's compatible with both UWP and desktop. But I don't use Xaml, Here are the exported functions for setting the window:

````     
void SetWindow(int64 window, int width, int height);
void SetWindow(CoreWindow window, int width, int height);

**Comment by angelazhangmsft** [comment]
It looks like [Windows.UI.Xaml.BindableAttribute](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Data.BindableAttribute?view=winrt-22000) is being used in the component based on the screenshot above. Are any of the types defined in the C++ component .idl files attributed with `[bindable]`, as shown in the docs linked here?

Do you require any of the component's types to be bindable?

**Comment by Gavin-Williams** [comment]
No, I don't need anything to be bindable - I don't even know what that does - something about connecting member data between a UI visual and backing data I think. I haven't done much with Xaml. I've mostly used handmade UI for the few smaller game projects I've done. And when I've used Xaml, I've kept it pretty simple.

It looks like the ViewModel template item brings in Bindable - which isn't needed. Using the ViewModel template item is the only existing way to create a runtime class, even though runtime classes are not ViewModels (this is a separate issue),

**Comment by Gavin-Williams** [comment]
Removing [bindable] resolves that issue. Now I fall back on another path issue:
```
Could not find a part of the path 'D:\Projects\Engine&Graphics\EngineGraphicsProjects\_build\x64\Debug\GraphicsComponent\bin\Graphics'.	PGraphicsProjection	C:\Program Files\dotnet\sdk\5.0.402\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	
```
I have no idea where this path is generated from. When I look at the actual folder structure it appears to be:

.../x64/Debug/GraphcisComponent/bin/GraphicsComponent/ 

But I just don't know what this is related to.

Edit: Hangon, it looks like it's building now.

**Comment by Gavin-Williams** [comment]
What is this looking for?

    
    <PackTask PackItem="$(PackProjectInputFile)"
    
   I'm getting a can't find path error.
   
   Edit: I've failed to get this solution working - so I've scrapped it after a week. I've reassembled a new solution. Again, it doesn't work. I've filed a new issue.

**Comment by stevewhims** [comment]
Thanks, @Gavin-Williams, I'll go ahead and respond to the new issue.

Thanks!
Steve
