### ISSUE TITLE
Error 404 link on page

### ISSUE THREAD

**Issue by carsonsaldanha** [MicrosoftDocs/windows-uwp#3414]
The "Tutorial: Create a user interface" hyperlink under the "Next steps" section leads to an error 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81742f59-6053-20f6-5847-7e47550946a8
* Version Independent ID: 1fbe9264-9a2b-3c38-08d4-bbdadee1d767
* Content: [Create your first app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/your-first-app)
* Content Source: [windows-apps-src/get-started/your-first-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/your-first-app.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thank you for your patience on this issue.

The link has been redirected to point at a more recent tutorial, as the previous one was indeed removed.
