### ISSUE TITLE
Add note to install adb

### ISSUE THREAD

**Issue by ssnacks** [MicrosoftDocs/windows-uwp#3416]
I thought from the description that adb was installed with the Windows Subsystem for Android but I had to install it myself. I suggest adding a note that the Android platform tools need to be installed separately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Just added a note and link to install. Thanks for the contribution @ssnacks. :)
