### ISSUE TITLE
How to get

### ISSUE THREAD

**Issue by wevve** [MicrosoftDocs/windows-uwp#3418]
[在此处输入反馈]

How to get
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/zh-cn/windows/android/wsa/#test-and-debug)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @wevve - I may not be clear on what question you're asking, but to try Windows Subsystem for Android, you will need follow the "Set up your development environment" instructions in this document. https://docs.microsoft.com/windows/android/wsa/#set-up-your-development-environment  

This includes:

- Installing a Windows Insider build
- Installing the Amazon Appstore via the Microsoft Store 
- Installing an Android mobile app via the Amazon Appstore
