### ISSUE TITLE
Windows Subsystem for Android(TM) can not run

### ISSUE THREAD

**Issue by nozero2** [MicrosoftDocs/windows-uwp#3419]
[Enter feedback here]
Version=1
EventType=MoBEX
EventTime=132793622485680266
ReportType=2
Consent=1
UploadTime=132793622489586454
ReportStatus=268435456
ReportIdentifier=db0f9c3e-f477-4fa3-8152-43e4e603dbbb
IntegratorReportIdentifier=435be8d1-b93c-4d9a-92d2-0115d959771c
Wow64Host=34404
NsAppName=praid:App
OriginalFilename=WsaClient.exe
AppSessionGuid=0000317c-0001-0006-0ab8-a69718c7d701
TargetAppId=U:MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe!App
TargetAppVer=1.7.32815.0_x64_!2021//10//08:07:18:38!0!WsaClient.exe
BootId=4294967295
ServiceSplit=2249772376
TargetAsId=716
UserImpactVector=808452912
IsFatal=1
EtwNonCollectReason=4
Response.BucketId=36a1cfc2f1b3140616d4e6418f6608cf
Response.BucketTable=5
Response.LegacyBucketId=1645192933150165199
Response.type=4
Sig[0].Name=程序包全名
Sig[0].Value=MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe
Sig[1].Name=应用程序名
Sig[1].Value=praid:App
Sig[2].Name=应用程序版本
Sig[2].Value=1.7.32815.0
Sig[3].Name=应用程序时间戳
Sig[3].Value=615ff0ce
Sig[4].Name=故障模块名称
Sig[4].Value=ucrtbase.dll
Sig[5].Name=故障模块版本
Sig[5].Value=10.0.22000.1
Sig[6].Name=故障模块时间戳
Sig[6].Value=00e78ce9
Sig[7].Name=异常偏移
Sig[7].Value=000000000007dd7e
Sig[8].Name=异常代码
Sig[8].Value=c0000409
Sig[9].Name=异常数据
Sig[9].Value=0000000000000007
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=10.0.22000.2.0.0.256.48
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=126f
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=126f9f3befaef7906915d14a9d96b47f
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=3a81
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=3a8151dc853be953ed104481f4e6c62e
UI[2]=C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
LoadedModule[0]=C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\USER32.dll
LoadedModule[5]=C:\WINDOWS\System32\win32u.dll
LoadedModule[6]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[7]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[8]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[9]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[10]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[11]=C:\WINDOWS\System32\shcore.dll
LoadedModule[12]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[13]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[14]=C:\WINDOWS\System32\sechost.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\VirtDisk.dll
LoadedModule[17]=C:\WINDOWS\System32\combase.dll
LoadedModule[18]=C:\WINDOWS\SYSTEM32\XINPUT1_4.dll
LoadedModule[19]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[20]=C:\WINDOWS\System32\ole32.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll
LoadedModule[22]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[23]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[25]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\FLTLIB.DLL
LoadedModule[27]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_9d947278b86cc467\COMCTL32.dll
LoadedModule[28]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[30]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[31]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[33]=C:\WINDOWS\SYSTEM32\icu.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\CoreMessaging.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
LoadedModule[36]=C:\WINDOWS\SYSTEM32\d3d11.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
LoadedModule[38]=C:\WINDOWS\SYSTEM32\MFPlat.DLL
LoadedModule[39]=C:\WINDOWS\SYSTEM32\MF.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\MSWSOCK.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\MFSENSORGROUP.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\d2d1.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[44]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe\MSVCP140.dll
LoadedModule[45]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe\CONCRT140.dll
LoadedModule[46]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe\VCRUNTIME140_1.dll
LoadedModule[47]=C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe\VCRUNTIME140.dll
LoadedModule[48]=C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe\gfxstream_backend.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\AVRT.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
LoadedModule[55]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\MFCORE.DLL
LoadedModule[57]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[58]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\inputhost.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[61]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[62]=C:\Windows\System32\Windows.Storage.ApplicationData.dll
LoadedModule[63]=C:\Windows\System32\twinapi.appcore.dll
LoadedModule[64]=C:\Windows\System32\WinTypes.dll
LoadedModule[65]=C:\Windows\System32\dcomp.dll
LoadedModule[66]=C:\Windows\System32\Windows.ApplicationModel.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[69]=C:\WINDOWS\system32\mssprxy.dll
LoadedModule[70]=C:\Windows\System32\Windows.UI.dll
LoadedModule[71]=C:\Windows\System32\CapabilityAccessManagerClient.dll
LoadedModule[72]=C:\Windows\System32\usermgrproxy.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\usermgrcli.dll
LoadedModule[74]=C:\Windows\System32\Windows.Media.Devices.dll
LoadedModule[75]=C:\Windows\System32\Geolocation.dll
LoadedModule[76]=C:\Windows\System32\BiWinrt.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\daxexec.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\container.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\windows.staterepositoryclient.dll
LoadedModule[81]=C:\WINDOWS\SYSTEM32\capauthz.dll
LoadedModule[82]=C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
LoadedModule[83]=C:\Windows\System32\iertutil.dll
LoadedModule[84]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[85]=C:\Windows\System32\MrmCoreR.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\UMPDC.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[89]=C:\Windows\System32\profapi.dll
LoadedModule[90]=C:\ProgramData\Microsoft\Windows\AppRepository\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe\PackagedCom\WsaProxy\WsaProxy.dll
LoadedModule[91]=C:\Windows\System32\bcp47mrm.dll
LoadedModule[92]=C:\Windows\System32\Windows.UI.Immersive.dll
LoadedModule[93]=C:\WINDOWS\system32\windowscodecs.dll
LoadedModule[94]=C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\igd10iumd64.dll
LoadedModule[96]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[97]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[98]=C:\WINDOWS\SYSTEM32\igdusc64.dll
LoadedModule[99]=C:\Windows\System32\Windows.UI.Xaml.dll
LoadedModule[100]=C:\WINDOWS\SYSTEM32\textinputframework.dll
LoadedModule[101]=C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
LoadedModule[102]=C:\WINDOWS\system32\baiduWubiTSF.dll
LoadedModule[103]=C:\WINDOWS\system32\VERSION.dll
LoadedModule[104]=C:\Program Files (x86)\Baidu\BaiduWubi\1.2.0.66\uipWubix64.dll
LoadedModule[105]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[106]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[107]=C:\WINDOWS\SYSTEM32\dbghelp.dll
LoadedModule[108]=C:\WINDOWS\SYSTEM32\MSIMG32.dll
LoadedModule[109]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.22000.282_none_ce81670012fd6ff0\gdiplus.dll
LoadedModule[110]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[111]=C:\Program Files (x86)\Baidu\BaiduWubi\1.2.0.66\imefreetypex64.dll
LoadedModule[112]=C:\WINDOWS\SYSTEM32\dbgcore.DLL
LoadedModule[113]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[114]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[115]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[116]=C:\WINDOWS\system32\c_g18030.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22000
OsInfo[3].Key=ubr
OsInfo[3].Value=282
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=2052
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221319979
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22000.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16270
OsInfo[19].Key=svolsz
OsInfo[19].Value=125
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=210604
OsInfo[22].Key=bldtm
OsInfo[22].Value=1628
OsInfo[23].Key=bldbrch
OsInfo[23].Value=co_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22000.282.amd64fre.co_release.210604-1628
OsInfo[30].Key=buildflightid
OsInfo[30].Value=d17bb8ce-ce3f-41af-9df3-89e522b03da4
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=FX:12085A48
OsInfo[34].Key=fconid
OsInfo[34].Value=25704915,1,2,1
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
FriendlyEventName=已停止工作
ConsentKey=MoBEX
AppName=Windows Subsystem for Android(TM)
AppPath=C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.7.32815.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=B1B484552D3F1C961420ACACFCE3B5AE
MetadataHash=-997064446

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by MxMaster3** [comment]
I have the exact same error message being logged.
Opening the dmp file in WinDbg also produces this -
*** WARNING: Unable to verify checksum for gfxstream_backend.dll
ucrtbase!abort+0x4e:
00007fff`bea4dd7e cd29            int     29h

**Comment by MxMaster3** [comment]
After extensive testing, I found this error was being caused by graphics card that is not currently compatible with WSA. In my case it was a Nvidia 9800GT. Disabling this card and using the built-in Intel graphics allowed the WSA to fully load.

**Comment by mattwojo** [comment]
Thanks for sharing this feedback @cislone. 
We can only address feedback issues that require an update to the documentation here --- specific errors like this are better filed as a "product feedback" issue, please file with Feedback Hub: https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app

The graphics card compatibility issues is a really interesting discovery.  Thanks for sharing @MxMaster3! @hamza-usmani for awareness.
