### ISSUE TITLE
Side-loading

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/windows-uwp#342]
It might be helpful to add a topic on side-loading a manually-signed package for testing purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a92bb7ba-dc1f-611d-1e70-11af24430aa6
* Version Independent ID: 18cd627e-e660-3b61-c8f4-11ede5ae2bf3
* Content: [Manual app packaging - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/manual-packaging-root)
* Content Source: [windows-apps-src/packaging/manual-packaging-root.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/manual-packaging-root.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
Thanks for the feedback! I agree that a dedicated side-loading topic would help. I'll follow up internally.
