### ISSUE TITLE
Inaccurate claim re ubuntu's node version on apt-get

### ISSUE THREAD

**Issue by AlexJeffcott** [MicrosoftDocs/windows-uwp#3421]
`For example, the version of Node that can be installed with Ubuntu's apt-get command is currently outdated`

This strongly implies that you cannot use apt-get to install an up-to-date version of node. Indeed, the default for `sudo apt-get install nodejs` is currently node 10, I believe, which might well seem ancient in the js world.

It further implies that the "solution" is sth like nvm or similar.

While this is indeed a route that many would like to take and certainly has some advantages, it seems more transparent and correct to at least mention that you can:

```
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -  
sudo apt-get install -y nodejs
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Great suggestion. Thanks @AlexJeffcott! I've got a list of updates to the JS get-started docs and have added this to include. Appreciate the contribution.
