### ISSUE TITLE
Recommended content for getting started with WinUI 2 guide shows 2.5 release notes instead of most recent release notes.

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/windows-uwp#3424]
When scrolling to the end of the "Getting started with WinUI 2" guide, the WinUI 2.5 release notes are linked even though there are more recent release notes available:

![Screenshot of "recommended content" which shows the WinUI 2.5 release notes](https://user-images.githubusercontent.com/16122379/138529263-22f5264e-706c-4c84-915a-452f93050f88.png)

I think it would be better to show the most recent release notes there instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532b04ea-7927-f97a-1121-b8feac6df957
* Version Independent ID: e3cf5c39-5efa-aaea-3ac3-8c4ffa50e960
* Content: [Getting started with the Windows UI library - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)
* Content Source: [hub/apps/winui/winui2/getting-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui2/getting-started.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @chingucoding. Unfortunately, this section is automated and not editable by a writer. However, the current doc does have more up to date links.
