### ISSUE TITLE
Cannot connect to windows subsystem for android from another windows pc

### ISSUE THREAD

**Issue by MathewLC** [MicrosoftDocs/windows-uwp#3426]
Connecting to android subsystem with adb from the same device work but follow the [doc instructions](https://docs.microsoft.com/en-us/windows/android/wsa/#connect-to-a-test-device) to connect from another device in the network won't work even thought I used the host machine ip and make it visible across the network.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @MathewLC - Sorry you're having trouble. I'm wondering if it may depend what version of the Android SDK Platform Tools you're running...? https://developer.android.com/studio/releases/platform-tools  Maybe try updating to the latest release and see if that makes a difference..?

 The Android dev docs about adb point out some differences based on what version of Android is being run, I'm not quite savvy enough on the inner workings of WSA to know whether this makes a difference in using adb to debug or not. Here's the info in the adb doc: https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+
and https://developer.android.com/studio/command-line/adb#wireless. 
Have you tried the Android Connection Assistant? https://developer.android.com/studio/run/device#assistant

@hamza-usmani - Can you help?

**Comment by MathewLC** [comment]
Actually I can confirm now that with the windows update this bug was fixed. Thank you for the assist.
