### ISSUE TITLE
Contents of MenuItemTemplate get placed inside a NavigationViewItem's ContentPresenter

### ISSUE THREAD

**Issue by binaryfunt** [MicrosoftDocs/windows-uwp#343]
See [this StackOverflow question](https://stackoverflow.com/questions/49255333/using-navigationview-with-mvvm-icon-property-cannot-be-bound) for details. It means you cannot bind the `Icon` property of the `NavgationViewItem`. This behaviour is unexpected and should be mentioned.

In my opinion, the behaviour should be changed so that the contents of `MenuItemTemplate` can be a custom control, which could be a `NavigationViewItem` if you wanted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
The behavior is being changed exactly :)

**Comment by SuperJMN** [comment]
@serenaz What do you mean? is it already changed? Which build? how is this solved? Thanks :)

**Comment by LanceMcCarthy** [comment]
Hi @serenaz! 

Can you provide more info on which SDK the behavior will be changed in? Is this expected in the upcoming Spring Creator's Update?

Thanks!

**Comment by serenaz** [comment]
Hi! Sorry, I was under the impression that the change was coming in the spring update, but was just informed that it's not coming until the fall :/ In the meantime, would recommend the StackOverflow solution.

**Comment by SuperJMN** [comment]
@serenaz could you, please, post an example on how to get the desired result without the workaround that @binaryfunt posted on StackOverflow? 

Thanks in advance

**Comment by weitzhandler** [comment]
Issue still exists.
The issue is very easy to reproduce:
- Create a `NavigtionView` and set inline `NavigationViewItem`s to it.
- Run it and observe the icon displaying and hiding according to screen

Now instead of inline items, use `NavigationView.MenuItemTemplate`:

```xml
<NavigationView.MenuItemTemplate>
  <DataTemplate>
    <NavigationViewItem Icon="{Binding Icon}"/>
  </DataTemplate>
</NavigationView.MenuItemTemplate>
```

When rendered, the `NavigationViewItem` is no longer responsive to the screen size or the navigation view mode.
This issue shouldn't have been closed.

**Comment by weitzhandler** [comment]
Please reopen this issue.
The error issue still persists.

**Comment by sharpninja** [comment]
> Please reopen this issue.
> The error issue still persists.

Can confirm, exists in WinUI 3.

**Comment by Karl-Bridge-Microsoft** [comment]
Wdkbot doesn’t like your meddling with assignments! 😊

**Comment by hkhmsft** [comment]
If still relevant, please file this on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html). Unfortunately, the scope of this feedback channel covers specific doc fixes. The community of experts and Microsoft engineers can provide timely answers to your broader technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by sharpninja** [comment]
> Unfortunately, the scope of this feedback channel covers specific doc fixes.

Does this mean that the behavior in WinUI now matches that described by the page?

**Comment by hkhmsft** [comment]
@jwmsft @anawishnoff for visibility. Any pending doc updates we can make to clarify the above issue?

**Comment by anawishnoff** [comment]
If this is an issue/bug with the NavigationView control itself, I'd recommend someone [file a bug on the main WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose). I'm not sure where the issue is on the [NavigationView doc itself](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview), could you elaborate there?
