### ISSUE TITLE
VS2022 code prediction api is offering me invalid code suggestions that won't compile

### ISSUE THREAD

**Issue by logany-hi** [MicrosoftDocs/windows-uwp#3432]
in an asp.net core web project which I built in VS2019 (because it's still smarter to use current frameworks for more than testing development), I'm attempting a bool conversion from ViewData but the api is offering me code that passes a property on my model as the `out` parameter for the TryParse:

`public class IndexModel : PageModel
{
    public bool Result { get; set; }

    public async Task<IActionResult> OnGetAsync()
    {
        if (ViewData["Result"] is not null)
        {
            bool.TryParse(ViewData["Result"].ToString(), out bool result);
        }
    }
}`

This would be correct but the AI api to recommend the completion of the code fills in `out this.Result);` which can't compile because properties can't be used as the target for out parameters.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope you can get an answer there.
