### ISSUE TITLE
Reorganize UWP and desktop docs

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/windows-uwp#3434]
The new develop category under desktop development has pages with links to APIs in various forms (WinRT, Win32 and .NET) as well as WindowsAppSDK. This is a good step in merging the docs into a single place however unlike Win32 and .NET APIs which are under their own sections, guideline pages for WinRT APIs are located under the UWP section. While some of the APIs are UWP specific, a lot of them are consumable from desktop apps as well and have nothing to do specifically with UWP however the current organization misleads the developer. Consider moving all of them that are not specific to UWP under the desktop category itself. Win32 and .NET APIs listed can remain in the same place.

<img width="356" alt="Screenshot 2021-10-25 at 20 40 57" src="https://user-images.githubusercontent.com/45227503/138722062-a50a31b1-7319-4fad-a598-f9a460422c75.png">

For example, this section should be moved here and content should be enhanced to add info for desktop apps if needed.
<img width="362" alt="Screenshot 2021-10-25 at 20 41 45" src="https://user-images.githubusercontent.com/45227503/138722131-e832eef2-c9bf-49fa-b879-addbcc59e55e.png">
 
While APIs that are specific to UWP or UWP XAML will not be moved, example
<img width="350" alt="Screenshot 2021-10-25 at 20 42 56" src="https://user-images.githubusercontent.com/45227503/138722380-e37d83ea-46e6-46ce-934c-a3bc8d4fbe7a.png">

Currently the desktop section seems to be mainly a docs for WindowsAppSDK. In my opinion it should also have the non-UWP WinRT stuff.

Also the publish section should also be under the desktop section and not UWP:
<img width="399" alt="Screenshot 2021-10-25 at 20 47 19" src="https://user-images.githubusercontent.com/45227503/138723266-c5fab5c4-4db3-49ec-a257-79dedde63509.png">

**Comment by GrantMeStrength** [comment]
Hello! Thank you for providing your feedback. I appreciate you taking the time to contact us. I can tell you we are deep into a substantial re-organization of our content in time for Build this yes. Please have a look at our docs in late May, as we hope we'll address these and other issues. Thank you! -John
