### ISSUE TITLE
remapping on one input language

### ISSUE THREAD

**Issue by seniorsirjoe** [MicrosoftDocs/windows-uwp#3435]
The keyboard on the Portuguese language does not have a key for the interrogation sign(?). How can I address this problem?-
The problem stems from the fact that Portuguese keyboards have an extra key that in the usual English keyboards is the long shift key. In the Portuguese keyboards the shift key is short (like the other keys) so there is room for a (?) key.
I need a lolution for this. Even buying a Portuguese language keyboard is not possible here because it is not offered. (I live in Tokyo)
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by dedavis6797** [comment]
Hi @seniorsirjoe, thanks for reporting this! The mappings can be changed to support your keyboard layout. In the PowerToys settings menu for Shortcut Guide, you'll notice that the actual activation shortcut is `Win + Shift + /`, which on English keyboards is equivalent to `Win + ?`. If you click the edit button, you can change the mapping to whatever combination is most convenient for you.

![image](https://user-images.githubusercontent.com/61330599/138936535-ddd09af9-21c0-4dfb-a5c4-a1bda57fb72a.png)

**Comment by mattwojo** [comment]
@seniorsirjoe -- Closing this issue as it doesn't appear to require an update to the docs, but please feel welcome to repost it in the PowerToys product repo for discussion if you think this could be better handled in the product in some way that may help.
*If you believe this does require an update to the documentation, please re-open with some context for what you'd like to see in the docs. Thanks for sharing your feedback with us!
