### ISSUE TITLE
Please add descriptions of VB Windows Desktop templates

### ISSUE THREAD

**Issue by Nukepayload2** [MicrosoftDocs/windows-uwp#3440]
As a developer of .NET control libraries, I don't want to see VB.NET templates hidden in official docs. It's bad for sales of our WPF and Windows Forms products, especially in the Japanese market.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f23a59a-337a-b688-8b92-91938bc1744c
* Version Independent ID: 409cda2c-293d-78f0-aa6c-6fa8fdb7b18b
* Content: [Visual Studio project and item templates for Windows apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/visual-studio-templates)
* Content Source: [hub/apps/desktop/visual-studio-templates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/visual-studio-templates.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing this issue. I'll investigate and report back when I know more.

-Steve

**Comment by stevewhims** [comment]
Hello! Thanks for filing this issue, and sorry for the delay in getting back to you!

I made enquiries about the languages that we prioritize in the documentation, and our policy is that we focus on C# and C++/WinRT in the docs.

I'll go ahead and close the issue, but you can still leave comments on it.

Many thanks!
-Steve
