### ISSUE TITLE
Support for parameters?

### ISSUE THREAD

**Issue by alexrest** [MicrosoftDocs/windows-uwp#3444]
Is it possible to filter a URL based on a parameter it contains? Similar to how [iOS 13 and later](https://developer.apple.com/documentation/bundleresources/applinks/details/components) does? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e251da-3cab-4aa0-2915-21189cf71bef
* Version Independent ID: b244b311-a0e5-185d-df82-1dadf3fe6416
* Content: [Enable apps for websites using app URI handlers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking#associate-your-app-and-website-with-a-json-file)
* Content Source: [windows-apps-src/launch-resume/web-to-app-linking.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/web-to-app-linking.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
I don't believe so. This is our docs page and it doesn't mention it.

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app

I would suggest you go to the Q&A Forum and ask your question again there.

-john
