### ISSUE TITLE
Typo in "Using the bootrapper API" section title

### ISSUE THREAD

**Issue by saul-mtz** [MicrosoftDocs/windows-uwp#3445]
As the title says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26da09-9179-baaf-aed1-7517970e2c55
* Version Independent ID: 5bd80518-4de2-e7f0-d17a-678acae32aa6
* Content: [Reference the Windows App SDK framework package at run time - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/reference-framework-package-run-time)
* Content Source: [hub/apps/windows-app-sdk/reference-framework-package-run-time.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/reference-framework-package-run-time.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @saul-mtz! I've fixed that, and it's live now.

FYI, there's also open authoring, as described here (it's an internal site): [Quickstart—contribute to Windows developer content](https://review.docs.microsoft.com/windows-authoring-guide/quickstart?branch=main).

Thanks again!
-Steve
