### ISSUE TITLE
Disambiguate winget

### ISSUE THREAD

**Issue by JimMoyle** [MicrosoftDocs/windows-uwp#3447]
The winget line as shown in this doc gives the following result:

Multiple packages found matching input criteria. Please refine the input.
Name                Id                  Source
-----------------------------------------------
Microsoft PowerToys XP89DCGQ3K6VLD      msstore
PowerToys (Preview) Microsoft.PowerToys winget

To disambiguate the winget package I believe the line should be:

WinGet install Microsoft.PowerToys

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
This issue is addressed in https://github.com/microsoft/PowerToys/issues/13579.

**Comment by franky920920** [comment]
@mattwojo I think this issue is resolved with #3455

**Comment by mattwojo** [comment]
Thanks @franky920920 and @JimMoyle --- yes, this issue is resolved with https://github.com/MicrosoftDocs/windows-uwp/pull/3455/files
