### ISSUE TITLE
Find My Mouse feature needs refining

### ISSUE THREAD

**Issue by VulcanTourist** [MicrosoftDocs/windows-uwp#3452]
First, this new Find My Mouse feature *should not* have been enabled by default, catching distracted people not closely following development lately by surprise... and not in a good way.  I had to discover it entirely by accident while I was playing a Steam survival game, when accidentally tapping [Ctrl] twice during the game activated this mystifying lightened circle around the targeting reticle ***in the game***.

Second, as I not-so-subtlely hinted above, the Game Mode option, which is also active by default, ***does not work*** when the mode fails to recognize that the focused process is in fact a game.  Please don't implement that option at all unless you can further generalize it to work for all games.  Alternative suggestion: check the active Power Profile; if the current profile is High Performance or similar, it's probably a better bet than the unreliable Game Mode that a game is being played.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba175f26-82e2-2f00-7562-924faa57c143
* Version Independent ID: ba175f26-82e2-2f00-7562-924faa57c143
* Content: [PowerToys Mouse utilities for Windows](https://docs.microsoft.com/en-us/windows/powertoys/mouse-utilities)
* Content Source: [hub/powertoys/mouse-utilities.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/mouse-utilities.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
I think this issue should be filed in the PowerToys repo since this is not related to the docs.
The linked issue for this: https://github.com/microsoft/PowerToys/issues/14071 https://github.com/microsoft/PowerToys/issues/14307

**Comment by VulcanTourist** [comment]
I apologize for somehow thinking I was standing in the right spot to post my suggestion.  Clearly I was not, whatever the cause of my confusion.  Sorry!
