### ISSUE TITLE
XAML Controls Gallery links to Expander "Guidelines", which is... a 404.

### ISSUE THREAD

**Issue by DHowett** [MicrosoftDocs/windows-uwp#3458]
<img width="143" alt="image" src="https://user-images.githubusercontent.com/189190/140104496-cef9782c-307c-4a65-becd-56400ff3c8f9.png">

Guidelines links to https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/expander, which doesn't exist.
Users are insufficiently "guided."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3a93846-82b4-7363-8d3a-7f299e09d0ba
* Version Independent ID: 0347e98d-bafd-d80d-7ca4-ae77016c582d
* Content: [Windows Controls and patterns - Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/controls/)
* Content Source: [hub/apps/design/controls/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/controls/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by GrantMeStrength** [comment]
Thanks for reporting this!

Link is currently:

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/expander

Link should be

https://docs.microsoft.com/en-us/windows/apps/design/controls/expander

Investigating the best way to get this fixed.

**Comment by GrantMeStrength** [comment]
I have looked at the latest source code of the Xaml Control gallery, and I cannot see this old link being used.
I hope this means the link has already been updated. I will close the issue - if I missed the broken, please feel free to re-open it and let me know, thanks! -john
