### ISSUE TITLE
No dictionary entry causes NavigationViewSample to freeze and die

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#346]
As this code hasn't reference to SettingsPage, it causes the sample app to crash:
```
Dictionary<Type, string> lookup = new Dictionary<Type, string>()
    {
        {typeof(HomePage), "home"},
        {typeof(AppsPage), "apps"},
        {typeof(GamesPage), "games"},
        {typeof(MusicPage), "music"},
        {typeof(MyContentPage), "content"}    
    };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Good catch! We're updating with the correct code:
```
if (ContentFrame.SourcePageType == typeof(SettingsPage))
{
   NavView.SelectedItem = NavView.SettingsItem as NavigationViewItem;
}
```
