### ISSUE TITLE
Broken link under 2nd para in ‘Design you app’ section

### ISSUE THREAD

**Issue by bkwdesign** [MicrosoftDocs/windows-uwp#3461]
Look for link in this text:

See the Introduction to Universal Windows Platform (UWP) apps for designers for information on designing UWP apps that delight your users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcd2e7e-612d-29de-6b94-3bed0b772b16
* Version Independent ID: cf067679-95df-f7d2-17ec-d15cc18c0b4b
* Content: [What's a Universal Windows Platform (UWP) app? - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by GrantMeStrength** [comment]
Thanks for reporting. Topic has been updated.
