### ISSUE TITLE
Note that using WinRT APIs is unrelated to OutputType

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/windows-uwp#3463]
The examples for adding WinRT support to .NET project all use examples where OutputType is WinExe. 

It might be worth noting that OutputType isn't related to using WinRT apis - libraries and console apps can also consume the WinRT apis. 

This is also useful because because a user might thing WinExe means 'Windows Specific exe', and copy the PropertyGroup (rather than 'Windows GUI application'). In that scenario, if a user calls `dotnet run` on a console app, with the output type set to `WinExe`, the terminal will appear to hang. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Call Windows Runtime APIs in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @iUnknwn, I'll investigate.

-Steve

**Comment by stevewhims** [comment]
I've updated the topic in line with your suggestion.

I'll go ahead and close the issue.

Thanks again!
-Steve
