### ISSUE TITLE
WASDK Docs Must be hosted in another repository

### ISSUE THREAD

**Issue by ghost1372** [MicrosoftDocs/windows-uwp#3465]
I noticed that the WindowsAppSDK documentation is hosted in this repository, But isn't WASDK different from UWP? So why are they both hosted in the UWP repository?
Wouldn't it be better to change the name of this repository to something more comprehensive, or to host WASDK documentation in a separate repository?

**Comment by GrantMeStrength** [comment]
Yes, the repo is renamed and we're in the process of sorting it all out. As you can imagine, with so many topics and links this is not a trivial thing. But we are working on it.
