### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by surferjeff** [MicrosoftDocs/windows-uwp#3467]
The link for **Partner Center apps and games page** doesn't take me to an apps and games page.  It takes me to https://partner.microsoft.com/en-us/dashboard/directory which has no button or link resembling **Create a new app**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc1e1bb5-35db-85ec-3645-c253337f6e7d
* Version Independent ID: 829f2c99-0eae-7de5-e9bf-a6512746f3b8
* Content: [Create your PWA app by reserving a new name - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/pwa/create-your-app-by-reserving-a-name)
* Content Source: [windows-apps-src/publish/pwa/create-your-app-by-reserving-a-name.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/pwa/create-your-app-by-reserving-a-name.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks. I think this is a better link: https://docs.microsoft.com/en-us/gaming/xbox-live/get-started/setup-partner-center/live-setup-partner-center-partners and I will make the change.
