### ISSUE TITLE
Optimize your app performance should say app's

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3469]
![image](https://user-images.githubusercontent.com/22989529/140789029-3cae7e54-029b-407c-a978-661c093b47c7.png)

this should say Optimize your app's performance, not Optimize your app performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 766e2058-93f1-2b18-4b47-2e1a0b3ff101
* Version Independent ID: 766e2058-93f1-2b18-4b47-2e1a0b3ff101
* Content: [Windows app performance overview - Windows apps](https://docs.microsoft.com/en-us/windows/apps/performance/)
* Content Source: [hub/apps/performance/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/performance/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hmm... seems these two options mean slightly different things.

"Optimize your app performance" is more general - as in the performance of apps that you tend to write or optimizing the system performance for the app.
"Optimize your app's performance" is more specific to the performance of one targeted app that belongs to you.
I'd argue that the original (#1) is more appropriate to frame this content.

Thoughts?

**Comment by mattwojo** [comment]
Going to close this -- not because I'm 100% on disagreeing wtih the possessive format, but because apostrophes can be a bit wonky in our yaml toc format. 
Thanks for filing this though @asklar! Led to some good conversation. Please keep contributing! :)
