### ISSUE TITLE
When will this control be available ?

### ISSUE THREAD

**Issue by JD-V** [MicrosoftDocs/windows-uwp#347]
The document at https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview says that this control is  in prerelease state, It would be helpful if anybody tell me about the targeted release date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba995b-8bf3-407c-7b87-015d22d813f1
* Version Independent ID: 52c553b6-e94d-2810-4123-8ee215b002bf
* Content: [Tree view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view#is-this-the-right-control)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Anything marked as 'prerelease' in the docs is in the latest Windows Insider SDK, and will be in the next update of Windows. For the latest SDK release info, see the [Windows Developer blog](https://blogs.windows.com/buildingapps). For the latest Windows release info, see the [Windows 10 blog](https://blogs.windows.com/windowsexperience).
