### ISSUE TITLE
The title of this page incorrectly references UWP apps

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/windows-uwp#3476]
When I load this doc page in the browser (specifically Edge) I see that the browser title for the page is "Microsoft Teams JavaScript client SDK Preview - UWP applications | Microsoft Docs"

I don't think the "UWP applications" bit should be in there since there's nothing about the content (as far as I can tell) that is specific to UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2912d7b4-0d21-546d-254f-b971821cb8f8
* Version Independent ID: 2912d7b4-0d21-546d-254f-b971821cb8f8
* Content: [Microsoft Teams JavaScript client SDK Preview - UWP applications](https://review.docs.microsoft.com/en-us/windows/uwp/m365-apps/using-teams-client-sdk-preview?branch=pr-en-us-2017&tabs=command-palette-code#apis-organized-into-capabilities)
* Content Source: [windows-apps-src/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/m365-apps/using-teams-client-sdk-preview.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for the feedback.
You are correct, this is not ideal but is a consequence of how our repo is organized. it's on our list to correct this asap!
