### ISSUE TITLE
Walkthrough failing for .Net 6

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#3479]
When I tried following this walkthrough using .Net 6, and the sample projects as specified. SimpleMathComponent wouldn't build

Build started...
1>------ Build started: Project: SimpleMathComponent, Configuration: Debug x64 ------
1>64 bit MIDLRT Processing D:\Projects - Tests\C# Projection Test\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathComponent\SimpleMath.idl
1>SimpleMath.idl
1>64 bit MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt\winrtbase.idl
1>winrtbase.idl
1>64 bit MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\winrt\midlbase.idl
1>midlbase.idl
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.ai.machinelearning.machinelearningcontract\3.0.0.0\windows.ai.machinelearning.machinelearningcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract\2.0.0.0\windows.ai.machinelearning.preview.machinelearningpreviewcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.applicationmodel.calls.background.callsbackgroundcontract\2.0.0.0\windows.applicationmodel.calls.background.callsbackgroundcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.applicationmodel.calls.callsphonecontract\5.0.0.0\windows.applicationmodel.calls.callsphonecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.applicationmodel.calls.callsvoipcontract\4.0.0.0\windows.applicationmodel.calls.callsvoipcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.applicationmodel.communicationblocking.communicationblockingcontract\2.0.0.0\windows.applicationmodel.communicationblocking.communicationblockingcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.applicationmodel.socialinfo.socialinfocontract\2.0.0.0\windows.applicationmodel.socialinfo.socialinfocontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.applicationmodel.startuptaskcontract\3.0.0.0\windows.applicationmodel.startuptaskcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.devices.custom.customdevicecontract\1.0.0.0\windows.devices.custom.customdevicecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.devices.deviceslowlevelcontract\3.0.0.0\windows.devices.deviceslowlevelcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.devices.printers.printerscontract\1.0.0.0\windows.devices.printers.printerscontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.devices.smartcards.smartcardbackgroundtriggercontract\3.0.0.0\windows.devices.smartcards.smartcardbackgroundtriggercontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.devices.smartcards.smartcardemulatorcontract\6.0.0.0\windows.devices.smartcards.smartcardemulatorcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.foundation.foundationcontract\4.0.0.0\windows.foundation.foundationcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.foundation.universalapicontract\10.0.0.0\windows.foundation.universalapicontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.gaming.xboxlive.storageapicontract\1.0.0.0\windows.gaming.xboxlive.storageapicontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.graphics.printing3d.printing3dcontract\4.0.0.0\windows.graphics.printing3d.printing3dcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.networking.connectivity.wwancontract\2.0.0.0\windows.networking.connectivity.wwancontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.networking.sockets.controlchanneltriggercontract\3.0.0.0\windows.networking.sockets.controlchanneltriggercontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.security.isolation.isolatedwindowsenvironmentcontract\2.0.0.0\windows.security.isolation.isolatedwindowsenvironmentcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.services.maps.guidancecontract\3.0.0.0\windows.services.maps.guidancecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.services.maps.localsearchcontract\4.0.0.0\windows.services.maps.localsearchcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.services.store.storecontract\4.0.0.0\windows.services.store.storecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.services.targetedcontent.targetedcontentcontract\1.0.0.0\windows.services.targetedcontent.targetedcontentcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.storage.provider.cloudfilescontract\4.0.0.0\windows.storage.provider.cloudfilescontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.system.profile.profilehardwaretokencontract\1.0.0.0\windows.system.profile.profilehardwaretokencontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.system.profile.profilesharedmodecontract\2.0.0.0\windows.system.profile.profilesharedmodecontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract\3.0.0.0\windows.system.profile.systemmanufacturers.systemmanufacturerscontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.system.systemmanagementcontract\7.0.0.0\windows.system.systemmanagementcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract\1.0.0.0\windows.ui.viewmanagement.viewmanagementviewscalingcontract.winmd
1>Processing WinMD c:\program files (x86)\windows kits\10\references\10.0.19041.0\windows.ui.xaml.core.direct.xamldirectcontract\2.0.0.0\windows.ui.xaml.core.direct.xamldirectcontract.winmd
1>MDMERGE : error MDM2025: The input directory or file D:\Projects - Tests\C  is not valid.
1>Microsoft(R) Metadata Merge Utility Version 10.0.49.
1>
1>
1>D:\Projects - Tests\C# Projection Test\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\packages\Microsoft.Windows.CppWinRT.2.0.200703.9\build\native\Microsoft.Windows.CppWinRT.targets(468,9): error MSB3073: The command "mdmerge @"D:\Projects - Tests\C# Projection Test\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Debug\SimpleMathComponent\obj\mdmerge.rsp"" exited with code 2.
1>Done building project "SimpleMathComponent.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

So I renamed the folder 'C# Project Test' to 'CSProjectionTest' but when I reloaded the solution VS is showing a brown bar and red cross above the tabs with the following error message

> Current solution contains incorrect configurations mappings

So I've opened the Configuration Manager and everything looks correct to me...

SimpleMathComponent 
    Debug x64
    Release x64
SimpleMathProjection 
    Debug x64
    Release x64
    
Edit: However, ignoring the error, I built the project again and it succeeded.

Further, trying to build the solution fails with the following errors...

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not read the Windows SDK's Platform.xml at C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\10.0.22000.0\Platform.xml	SimpleMathProjection	D:\Projects - Tests\CSProjectionTest\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathProjection\EXEC	1	

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\cswinrt.exe" @"D:\Projects - Tests\CSProjectionTest\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Release\SimpleMathProjection\bin\cswinrt.rsp"" exited with code 1.	SimpleMathProjection	C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\build\Microsoft.Windows.CsWinRT.targets	115	

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1112	The runtime pack for Microsoft.Windows.SDK.NET.Ref was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'any'.	SimpleMathProjection	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	427	
****

Here's my SimpleMathProjection.nuspec file
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>SimpleMathComponent</id>
    <version>0.1.0-prerelease</version>
    <authors>Contoso Math Inc.</authors>
    <description>A simple component with basic math operations</description>
    <dependencies>
      <group targetFramework="net6.0-windows10.0.22000.0" />
    </dependencies>
  </metadata>
  <files>
    <!--Support .NET Core 3, UAP, .NET Framework 4.6, .NET 5, C++ -->
    <!--Architecture-netural assemblies-->
    <file src="..\..\_build\x64\Debug\SimpleMathProjection\bin\SimpleMathProjection.dll" target="lib\net6.0-windows10.0.22000.0\SimpleMathProjection.dll" />
    <!--Architecture-specific implementation DLLs should be copied into RID-relative folders-->
    <file src="..\..\_build\x64\Debug\SimpleMathComponent\bin\SimpleMathComponent\SimpleMathComponent.dll" target="runtimes\win10-x64\native\SimpleMathComponent.dll" />
  </files>
</package>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40b34b2-1bc9-25ed-b91e-cee68bc9edc1
* Version Independent ID: ecfcea0e-cad5-f4c7-6ab2-6970d4e8adcb
* Content: [Make a C# projection from a C++/WinRT component, distribute as a NuGet for .NET 5+ apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by Gavin-Williams** [comment]
So coming back to this today, I cleaned the solution, rebuilt the solution

> Build started...
========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

And error list:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not read the Windows SDK's Platform.xml at C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\10.0.22000.0\Platform.xml	SimpleMathProjection	D:\Projects - Tests\CSProjectionTest\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathProjection\EXEC	1	

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\cswinrt.exe" @"D:\Projects - Tests\CSProjectionTest\CsWinRT-master\CsWinRT-master\src\Samples\Net5ProjectionSample\_build\x64\Release\SimpleMathProjection\bin\cswinrt.rsp"" exited with code 1.	SimpleMathProjection	C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\build\Microsoft.Windows.CsWinRT.targets	115	

I don't know where the third error went, I didn't change anything from last night.

**Comment by stevewhims** [comment]
Thanks, @Gavin-Williams, I'm making enquiries about expected support.

-Steve

**Comment by Gavin-Williams** [comment]
I just want to point out that I did stray slightly from the walkthrough in two ways - (1) I used .Net 6 instead of 5 and (2) I removed the lines in the nuspec file which coded for dependencies on .net framework / core / uwp.

I'm pretty weak with 'dev ops' or whatever all this manual prep work is called - I've been spoiled by learning to develop with UWP over the past few years, which makes everything so damn easy. With UWP it's just about the code usually, all the tooling is magical. So apologies for stumbling over what is probably straight forward for regular C++ dev's.

To me, that first error looks like it's saying that the Windows SDK isn't supporting UWP. I'm wondering if the sample project somehow hard codes support for the 4 platforms (UWP, Core, Framework, 5). The second error just above, I would interpret that as simply the tool failing because of the previous error.

**Comment by angelazhangmsft** [comment]
@Gavin-Williams, using .NET 6 vs .NET 5 should not cause any new issues here. Are both your C++/WinRT and C# projects targeting the 10.0.22000 SDK? It seems from the output above that the C++/WinRT project might be targeting 10.0.19041.0. Is the `TargetFramework` property in your csproj `net6.0-windows10.0.22000.0`?

Could you also confirm what version of VS you are using? If there's a repro we can look at, that would make it easier to determine the issue.

**Comment by Gavin-Williams** [comment]
@angelazhangmsft I'm using VS2022.

I updated SimpleMathComponent properties:
Target Platform Version -> 10.0.20348.0
Platform Toolset -> Visual Studio 2022 (v143)

I checked SimpleMathProjection.csproj and TargetFramework = net6.0-windows10.0.22000.0
I checked SimpleMathProjection.nuspec and <group targetFramework = "net6.0-windows10.0.22000.0"

This path exists:
> C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\10.0.20348.0\

But the error shows that the tool is trying to read this path:
> C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\10.0.22000.0\

I've updated the target framework here and there to be net6.0-windows10.0.20348.0. The project still builds and now when I build the solution, those errors have gone away. Now I have this error..

> NU5019	File not found: '..\..\_build\x64\Debug\SimpleMathProjection\bin\SimpleMathProjection.dll'.	SimpleMathProjection	C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	

OK. I missed an entry in one of those xml files, it was off screen to the right. Solution build has succeeded without any errors. 

Now I'll try to consume it.

**Comment by angelazhangmsft** [comment]
@Gavin-Williams, it looks like you don't have the Windows 10.0.22000.0 SDK installed. You can install it [here](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/), or alternatively target the 10.0.20348.0 SDK.

For the NU5019 error, it might be because you are build Release and not Debug. You will need to change the nuspec accordingly and check the location of the SimpleMathProjection.dll output.

**Comment by Gavin-Williams** [comment]
Where is the DLL (SimpleMathProjection.dll) meant to be? I don't see it. And where is the nuget package that is meant to be generated?

**Comment by Gavin-Williams** [comment]
When I'm trying to consume the runtime class, in Program.cs, SimpleMathComponent could not be found. I think this line in the docs for SampleConsoleApp.csproj is wrong.

>../../CppWinRTProjectionSample/SimpleMathProjection/nuget

This is the folder path ...

> D:\Projects - Tests\CSProjectionTest\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathProjection\nuget

So I've updated SampleConsoleApp.csproj to be:

```
    <RestoreSources>
      https://api.nuget.org/v3/index.json;
      ../../Net5ProjectionSample/SimpleMathProjection/nuget
    </RestoreSources>
```

And in that folder I see 1 file - SimpleMathProjection.nuspec - is that right? I don't think that's right either, because I have another error 

> NU1101	Unable to find package SimpleMathComponent. No packages exist with this id in source(s): D:\Projects - Tests\CSProjectionTest\CsWinRT-master\src\Samples\Net5ProjectionSample\SimpleMathProjection\nuget, nuget.org	SampleConsoleApp	D:\Projects - Tests\CSProjectionTest\CsWinRT-master\src\Samples\Net5ProjectionSample\SampleConsoleApp\SampleConsoleApp\SampleConsoleApp.csproj	1

**Comment by angelazhangmsft** [comment]
This line is restoring the source/folder where the nupkg is generated (by the SimpleMathProjection project).

It looks like there was no nupkg produced by the SimpleMathProjection project. You should see a NuGet package file in the folder called `SimpleMathComponent.0.1.0-prerelease.nupkg`. The console app references this package to consume the component.

**Comment by mbfaust19** [comment]
awesome trying itnow @angelazhangmsft

**Comment by Gavin-Williams** [comment]
So going back to the CppWinRTComponentProjectionSample, I thought it was working, but now when I try to build the solution I get the error I saw earlier ...
> NU5019	File not found: '..\..\_build\x64\Debug\SimpleMathProjection\bin\SimpleMathProjection.dll'.	SimpleMathProjection	C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	221	

When I look in the bin folder there, I see a ref folder and a cswinrt.rsp file. There is no dll. I can see a dll in the corresponding release folder! But I'm building in Debug mode, so I have no idea why that's happening.

I'm also seeing the brown error strip again - Current solution contains incorrect configurations mappings. I don't see how, I only have x64 configured.

**Comment by Gavin-Williams** [comment]
I checked configuration again - switching around between release and debug. Now I have 2 errors

> Path 'D:\Projects - Tests\CSProjectionTest\Net5ProjectionSample\_build\x64\Debug\SimpleMathComponent\bin\SimpleMathComponent\SimpleMathComponent.winmd' is not a file or directory	SimpleMathProjection	D:\Projects - Tests\CSProjectionTest\Net5ProjectionSample\SimpleMathProjection\EXEC	1	

> MSB3073	The command ""C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\cswinrt.exe" @"D:\Projects - Tests\CSProjectionTest\Net5ProjectionSample\_build\x64\Debug\SimpleMathProjection\bin\cswinrt.rsp"" exited with code 1.	SimpleMathProjection	C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\build\Microsoft.Windows.CsWinRT.targets	115	

But now I have files in _build/x64/Debug/SimpleMathComponent/bin/SimpleMathComponent/
SimpleMathComponent.dll
...
SimpleMathComponent.winmd

So doesn't that contradict what the error message is saying!

Here's a a link to the zipped solution if it helps...

https://1drv.ms/u/s!AhbcRtciy6_0jctxSx3gO1-giIVLwg?e=ZeGmvn

**Comment by Gavin-Williams** [comment]
I haven't fixed this project yet - I'll go through the walkthrough one more time. Maybe I missed something.

**Comment by stevewhims** [comment]
I went through the steps today, this time using Visual Studio 2022 and .NET 6. Of course, tweaks to the steps are necessary for those bits, but I did manage to complete it successfully. So I then updated the topic to focus primarily on Visual Studio 2022 and .NET 6 (since those are now GA), while still supporting VS2019 and .NET 5.

After those changes were published, I made sure that I hadn't missed anything by going through the steps an additional time. And, again, I was able to complete the tutorial successfully.

So if I follow the steps as they are currently, it works for me.

I'll go ahead and close, but please create a new issue if there's anything wrong with the steps as they are now.

Thanks!
Steve
