### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#348]
Hello,

When there is a lot of code like the page above, it would be more convenient if the code would be in a sample project that can be downloaded via a ZIP file.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12703330-b5a0-8523-3a89-c630c8514fb2
* Version Independent ID: 56f77244-5342-d30a-7ee4-ba062f5b86a5
* Content: [C# sample - submissions for apps, add-ons, and flights - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/csharp-code-examples-for-the-windows-store-submission-api)
* Content Source: [windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. The engineering team that owns this code sample is aware of this request and is already considering future options for improving how they deliver this sample.
