### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by bioya1redfish** [MicrosoftDocs/windows-uwp#3480]
QUESTION - I have written a PASSWORD manager in JAVA, which runs on Windows. I don't want $ for it; just want to publish it. Can I do this? THANKS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354f0d4-e417-7896-6230-a5d7eee0fa97
* Version Independent ID: f544086d-b6f2-7e59-b099-b690eecb91ff
* Content: [App submissions - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-submissions)
* Content Source: [windows-apps-src/publish/app-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-submissions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Yes it is: https://learn.microsoft.com/en-us/windows/uwp/monetize/java-code-examples-for-the-windows-store-submission-api
