### ISSUE TITLE
typo? at Manage app windows "window"<--->"this"

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/windows-uwp#3482]
[Enter feedback here]
The last C# sample of https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview;
The "(window)" in the line of "IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(window);" might be "(this)".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2621305-73dc-26eb-cbd7-ed48c7bc0534
* Version Independent ID: e18ea4cd-0750-0207-e2f8-c97ff97de697
* Content: [Manage app windows (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview)
* Content Source: [hub/apps/windows-app-sdk/windowing/windowing-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/windowing/windowing-overview.md)
* Product: **reunion**
* Technology: **windowing**
* GitHub Login: @rkarman
* Microsoft Alias: **rokarman**

**Comment by eduardobragaxz** [comment]
Yep, needs to be fixed. Wouldn't make it work if I didn't see the GitHub button to come here. So thank you! You helped me.

**Comment by MUJaCHe66** [comment]
Still needs to be fixed.

**Comment by rkarman** [comment]
Thank you for bringing this to my attention. The snippet was lifted from the WinUI sample, in which the window is defined. This is being addressed in PR #3332
