### ISSUE TITLE
C++ Examples would be greatly appreciated...

### ISSUE THREAD

**Issue by timmarriott** [MicrosoftDocs/windows-uwp#3484]
C++ Examples would be very helpful.  Especially when Name Spaces are nowhere to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b65398-4a76-529e-e55d-24a710022b32
* Version Independent ID: 37b65398-4a76-529e-e55d-24a710022b32
* Content: [User interface migration (including WinUI 3) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3#messagedialog-and-pickers)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Ah, yes, if you scroll up to the top of the topic, over on the right you'll see Save, Feedback, Edit, Share. To the left of those 4 you'll probably see some language other than C++/WinRT. If you select C++/WinRT there, then all the code examples in the topic will switch to C++/WinRT.

Thanks!
Steve
