### ISSUE TITLE
Example Usage Office 365

### ISSUE THREAD

**Issue by MatthiasDE** [MicrosoftDocs/windows-uwp#3485]
I guess one of the most common use cases is to install e.g. in enterprise but also in families the Office 365 package. Due to the fact that with search "365" or "word" there are no suitable results I would recommend or request to include the example to install the Office applications via winget also.

Or at least it would be nice to figure out if that is possible. Maybe also Microsoft could else include that apps in their repo - i would hardly go for a community package for a microsoft product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73bd6478-de0f-6aa9-fb31-0818abdb7f68
* Version Independent ID: f5ff6ecd-0231-d438-7301-6eb20863ec50
* Content: [install Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/install)
* Content Source: [hub/package-manager/winget/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/install.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Looks as though this has been resolved in https://github.com/microsoft/winget-cli/discussions/1876
