### ISSUE TITLE
Example crashes

### ISSUE THREAD

**Issue by GitTyler** [MicrosoftDocs/windows-uwp#3488]
Example crashes on await RandomAccessStream.CopyAsync(memStream, fileStream);
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf40397b-367e-ea99-9019-391cd86c221a
* Version Independent ID: fd1eb02e-f989-17ed-0829-41c275d281b6
* Content: [Create, edit, and save bitmap images - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/imaging)
* Content Source: [windows-apps-src/audio-video-camera/imaging.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/imaging.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This is a very old issue, but I tested the sample code and it works correctly. For developer support, go to [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/)
