### ISSUE TITLE
I can't start the wsa system

### ISSUE THREAD

**Issue by WorldEdit-Git** [MicrosoftDocs/windows-uwp#3489]
![20211114143110](https://user-images.githubusercontent.com/61828397/141670324-6b1f6137-7497-4ce3-91f0-cad3e996e12e.png)

**Comment by mattwojo** [comment]
We can only address feedback issues that require an update to the documentation here --- specific errors like this are a "product feedback" issue, please file them with Feedback Hub: https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app
