### ISSUE TITLE
Back Button Requested

### ISSUE THREAD

**Issue by ReiVaX1508** [MicrosoftDocs/windows-uwp#349]
Hi;

I try you're solution, but the BackButtonRequested doesn't work !!
Have you got a solution for.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
The BackRequested property was introduced in the Windows 10 SDK - Build 17110 or later. You can download the latest SDK here: https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

We'll update the documentation to clarify. Thanks for raising the issue @ReiVaX1508!
