### ISSUE TITLE
 [!NOTE] markdown tag

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#350]
Hello,

There is a markdown tag in this page (Ctrl-F to find it).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9423b752-97bd-fea6-48f6-7161674c5970
* Version Independent ID: 470ef0cd-dd0a-6c75-6c18-503e9dfb6d73
* Content: [Manage add-on submissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-add-on-submissions)
* Content Source: [windows-apps-src/monetize/manage-add-on-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/manage-add-on-submissions.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. This is one of several Markdown issues that crept into the docs when we transitioned over to a new parser last week. This fix should be published to the article on our live site on March 20.
