### ISSUE TITLE
Single-project MSIX ... Extension still required?

### ISSUE THREAD

**Issue by suchja** [MicrosoftDocs/windows-uwp#3500]
I was following this desdription to prepare VS2022 to develop a WinUI 3 app (C# packaged) like described [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-packaged-csharp).

After installing the described components and creating the project (without changing anything) it was not possible to check the `deploy` checkbox (it was disabled) in *Configuration manager*. This resulted in an error when starting to debug the packaged app.

After installing the *Single-project MSIX Packaging Tools for VS 2022 (preview)* Extension (I installed Version 0.9.10.2111041) I could check the `deploy` checkbox and also debug the packaged app.

Is there something missing in this description or is it a bug in the Windows App SDK? I checked their issues, but couldn't find something relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by stevewhims** [comment]
Hi, @suchja, thanks for filing this issue, and apologies for the delay in getting back to you.

I'll investigate, and see what I can find out.

-Steve

**Comment by stevewhims** [comment]
So, @suchja, you don't need to check the Deploy box if you have:

•	VS2022
•	AppSDK 1.0 (as the topic stipulates)
•	any language
•	single-project or two-project templates

But you mention that if you didn't check it, then you had a runtime error when you debugged. Was that when you pressed F5, or CTRL+F5, or both? Also, in what ways did you configuration differ from the list above?

Thanks!
-Steve

**Comment by stevewhims** [comment]
Closing.
