### ISSUE TITLE
Lacking info on how do build and package single-project MSIX using CI

### ISSUE THREAD

**Issue by devlead** [MicrosoftDocs/windows-uwp#3501]
There's currently very little information on how to automate the process of creating packages

Similar too:
https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7126fd1c-81c6-89d6-9c67-b62687636a5e
* Version Independent ID: e25cbc91-dad5-3bf8-e407-c711ae7d9419
* Content: [Package and deploy - Windows apps](https://docs.microsoft.com/en-us/windows/apps/package-and-deploy/#apps-that-use-the-windows-app-sdk)
* Content Source: [hub/apps/package-and-deploy/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/package-and-deploy/index.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @devlead, I'll investigate.

-Steve

**Comment by stevewhims** [comment]
@devlead, if you're still blocked on the info, please see [How can I build and package a packaged single-project MSIX app in command line? #1835](https://github.com/microsoft/WindowsAppSDK/discussions/1835).

I'm looking for a good place in the docs to add this info.

Thanks!
Steve

**Comment by stevewhims** [comment]
FYI, the content is now live here: [Automate building and packaging your single-project MSIX app](https://docs.microsoft.com/windows/apps/windows-app-sdk/single-project-msix#automate-building-and-packaging-your-single-project-msix-app).

Thanks!
-Steve
