### ISSUE TITLE
Document need for Visual C++ Redistributable on clients

### ISSUE THREAD

**Issue by devlead** [MicrosoftDocs/windows-uwp#3502]
It should be documented that the Visual C++ Redistributable is needed to be installed on client beyond the Microsoft.WindowsAppRuntime.Redist.

https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
| Architecture | Link | Notes |
|--|:-:|--|
| ARM64 | [https://aka.ms/vs/17/release/vc_redist.arm64.exe](https://aka.ms/vs/17/release/vc_redist.arm64.exe) | Permalink for latest supported ARM64 version |
| X86 | [https://aka.ms/vs/17/release/vc_redist.x86.exe](https://aka.ms/vs/17/release/vc_redist.x86.exe) | Permalink for latest supported x86 version |
| X64 | [https://aka.ms/vs/17/release/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe) | Permalink for latest supported x64 version. |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c85908-b97b-91a8-af9a-231785991bf7
* Version Independent ID: a4838116-3cb0-b97e-5065-934f7e4aadbe
* Content: [Deployment architecture for the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deployment-architecture)
* Content Source: [hub/apps/windows-app-sdk/deployment-architecture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/deployment-architecture.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by stevewhims** [comment]
Thanks, @devlead, I'm investigating!

-Steve

**Comment by stevewhims** [comment]
Thanks again, @devlead, I've published an update to the topic.

-Steve
