### ISSUE TITLE
KeyboardInput -> InputKeyboardSource [desktop-to-uwp-supported-api.md]

### ISSUE THREAD

**Issue by WelterDevelopment** [MicrosoftDocs/windows-uwp#3503]
The Information provided in https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md (respectively https://docs.microsoft.com/de-de/windows/apps/desktop/modernize/desktop-to-uwp-supported-api) seems to be outdated. In WinAppSDK 1.0 the KeyboardInput class was apparently renamed to InputKeyboardSource.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for spotting this. Doc has been updated.
