### ISSUE TITLE
Video capture example that doesn't depend on SharpDX.

### ISSUE THREAD

**Issue by bitbound** [MicrosoftDocs/windows-uwp#3506]
Since SharpDX is archived and no longer maintained, it would be nice to have an example of how to do desktop video capture without it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971295ef-cd07-fd9c-e5df-2c6e0e4c25fc
* Version Independent ID: c1d6f2f7-f971-3bd4-8fb7-f30d113a752f
* Content: [Screen capture to video - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture-video)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture-video.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture-video.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
SharpDX is still the recommended library for this scenario, even though it is no longer maintained.
