### ISSUE TITLE
Find My Mouse - Should ignore when Control key is used with something else

### ISSUE THREAD

**Issue by R-Norman** [MicrosoftDocs/windows-uwp#3507]
I use Visual Studio and SSMS all day and often use shortcuts which involve hitting CTRL multiple times as a modifier to other keys.
Most common is to comment or uncomment code (CTRL-K, CTRL-C or CTRL-K, CTRL-U)
Every time I use these shortcuts, the Find My Mouse feature is activated.

This feature really should only activate when hitting CTRL twice without hitting another key in-between the two presses.

I like the feature since I use multiple monitors but its a but jarring to see it popup every time I comment out some code ;)

Thanks

**Comment by Jay-o-Way** [comment]
This is an issue for PowerToys,not for the docs. To answer your question: you can now also shake the mouse to trigger.

**Comment by mattwojo** [comment]
Closing as this doesn't relate to a documentation update. Please consider filing on the PowerToys product repo or adding on to one of the related existing issues: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+is%3Aopen+find+my+mouse
