### ISSUE TITLE
An example would be great for the non-recommended async usage in work-item handlers 

### ISSUE THREAD

**Issue by istvan-pal-shapr3d** [MicrosoftDocs/windows-uwp#3516]
It would be great to see some example code for this "Don't" part [here](https://docs.microsoft.com/en-us/windows/uwp/threading-async/best-practices-for-using-the-thread-pool):
> When you use work-item handlers that use the async keyword, be aware that the thread pool work item may be set to the complete state before all of the code in the handler has executed. Code following an await keyword within the handler may execute after the work item has been set to the complete state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46e1daf8-329e-bc6e-084e-bab6fbd702e4
* Version Independent ID: 0aea54fe-7e61-5918-eda5-cb9d11f43ecd
* Content: [Best practices for using the thread pool - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/threading-async/best-practices-for-using-the-thread-pool)
* Content Source: [windows-apps-src/threading-async/best-practices-for-using-the-thread-pool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/threading-async/best-practices-for-using-the-thread-pool.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Sorry for the extremely late response to your issue. This is a difficult concept to demonstrate because it is something that *may* happen under arbitrary circumstances. Though this issue is closed, please treat this thread as an open thread for follow-ups.
