### ISSUE TITLE
Icon resource

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#352]
Hi,

Would it be possible to define the file sizes and file formats supported by the Icon resource please?

https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-add-on-submissions#icon-object

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9423b752-97bd-fea6-48f6-7161674c5970
* Version Independent ID: 470ef0cd-dd0a-6c75-6c18-503e9dfb6d73
* Content: [Manage add-on submissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-add-on-submissions#icon-object)
* Content Source: [windows-apps-src/monetize/manage-add-on-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/manage-add-on-submissions.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. Icons must be a 300 x 300 .png file for an add-on submission using the API. This requirements is the same as for [add-on submissions using Dev Center](https://docs.microsoft.com/en-us/windows/uwp/publish/create-add-on-store-listings#icon). I have updated this section of the API article to clarify this detail, and those changes should be live in the article on 3/20.
