### ISSUE TITLE
Does the SxS manifest go in the package or not?

### ISSUE THREAD

**Issue by dhoehna** [MicrosoftDocs/windows-uwp#3523]
Does the SxS manifest need to be in the package as well?

From the instructions it looks like
1. Make a package with make sppx
2. sign it with sign tool
3. Make a SxS manifest and keep it next to your executable.

Is that the correct way of doing things, or does the SxS needs to be packages with the exe as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf28a713-4e81-45e0-a3c7-0274ba6b2e85
* Version Independent ID: 19dd0436-a27d-8e50-5e7b-06c8fcd49a3f
* Content: [Grant identity to non-packaged desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps)
* Content Source: [hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @dhoehna! No, the SxS manifest does not need to be in the package. At a minimum, you can create it in NotePad, edit it, and then just store it in the same folder as the exe. Although, it might be better to include it in your project and have it copied to the same folder as the exe during build.

Thanks!
Steve

**Comment by dhoehna** [comment]
Cool.  Thank you.
