### ISSUE TITLE
GetUserSpecificSystemId doesn't exist

### ISSUE THREAD

**Issue by camnewnham** [MicrosoftDocs/windows-uwp#3528]
Under the "User System ID" capability it states:
> This capability is required to access the GetUserSpecificSystemId API in the Windows.System.Profile.SystemIdentification class.

This should refer to `GetSystemIdForUser(User)` as `GetUserSpecificSystemId` doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This issue has been fixed. The new URL for this page is: https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
