### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by bojanpopadic** [MicrosoftDocs/windows-uwp#353]
Shoul mediaProtectionManager.properties be replaced with mediaProtectionManager.Properties ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a22a9033-20fd-4a18-50f8-4a0c81f15c6e
* Version Independent ID: 4112b52c-17d1-cf0d-b5e5-c183e49d297b
* Content: [PlayReady DRM - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/playready-client-sdk)
* Content Source: [windows-apps-src/audio-video-camera/playready-client-sdk.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/playready-client-sdk.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this code error. This has been fixed in the documentation source and will appear on the live site tomorrow.
