### ISSUE TITLE
"Install PowerToys" page says that Windows Package Manager is in Preview

### ISSUE THREAD

**Issue by florelis** [MicrosoftDocs/windows-uwp#3532]
One of the options for installing is "Install with Windows Package Manager (Preview)", but winget is no longer in preview :)

Also, the first step in those instructions is
"Download PowerToys from Windows Package Manager."
but it probably was meant to be "Download winget"? Which shouldn't be needed anymore as I believe winget is pre-installed now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @lechacon - Thanks for this feedback! You're totally right -- we need to remove this preview tag! (There is still a [preview version of package manager ](https://docs.microsoft.com/windows/package-manager/winget/#preview-developers-only) available, but it's no longer required for installing powertoys!)

You're also right about that first step needing an update -- I'll get those in and link the commit once it churns through the publishing system. Thanks again!!
