### ISSUE TITLE
This Document Is No Good

### ISSUE THREAD

**Issue by MGParisi** [MicrosoftDocs/windows-uwp#3535]
None of this is available on my Product Center.  I've tried multiple accounts, including a microsoft enabled account.  And not one of them allows me the option of creating a "New Product".  The link simply doesn't exist.  And I see no other ways around this.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0a6489-50c7-af46-241a-272719fc2404
* Version Independent ID: 889d635c-2cb5-ce4c-2917-8e2a342106c2
* Content: [Create your app by reserving a name - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-your-app-by-reserving-a-name)
* Content Source: [windows-apps-src/publish/create-your-app-by-reserving-a-name.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-your-app-by-reserving-a-name.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by MGParisi** [comment]
In addition to the above document beign poor, these also do not mention any way to add these things.  And no reason why any of this is missing is provided.  This is very poor documentation.
https://docs.microsoft.com/en-us/windows/uwp/publish/partner-center-workspaces

**Comment by GrantMeStrength** [comment]
The account you use must be a registered developer account, not just a standard M365 account.

https://developer.microsoft.com/en-us/microsoft-store/register/
