### ISSUE TITLE
Document Is Incomplete

### ISSUE THREAD

**Issue by MGParisi** [MicrosoftDocs/windows-uwp#3536]
This is another, incomplete document.  I follow the steps on it, and the first step tells me to click on a link that isn't there.  I've tried this with multiple accounts, and even created a new account for this.  None of them work.

Please fix, and provide resources on what I need to do to add a product to the Microsoft Store.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47213237-5d66-e7ed-c616-0b6023be4c61
* Version Independent ID: 47213237-5d66-e7ed-c616-0b6023be4c61
* Content: [Partner Center workspaces - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/partner-center-workspaces)
* Content Source: [windows-apps-src/publish/partner-center-workspaces.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/partner-center-workspaces.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Please make sure you have registered as a developer.
https://developer.microsoft.com/en-us/microsoft-store/register/
