### ISSUE TITLE
Max supported version 17763?

### ISSUE THREAD

**Issue by duanqn** [MicrosoftDocs/windows-uwp#3541]
This page says the maximum supported Windows version is 17763. Out of date?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5c526bd-ce23-18ae-0e75-a847ec3f9930
* Version Independent ID: 79f86879-5c54-014f-d4ff-d40d75e32dc0
* Content: [App package requirements - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-package-requirements)
* Content Source: [windows-apps-src/publish/app-package-requirements.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-package-requirements.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Documentation has been updated.
