### ISSUE TITLE
C# sample for AppWindow in WinUI 3 won't compile

### ISSUE THREAD

**Issue by jfranki** [MicrosoftDocs/windows-uwp#3547]
`IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(window);`

should be:

`IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);`

Also, I find the choice of the variable name `m_appWindow` quite surprising because does not follow any Microsoft naming convention. `_appWindow` or `appWindow` would be a name that anyone expects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2621305-73dc-26eb-cbd7-ed48c7bc0534
* Version Independent ID: e18ea4cd-0750-0207-e2f8-c97ff97de697
* Content: [Manage app windows (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview)
* Content Source: [hub/apps/windows-app-sdk/windowing/windowing-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/windowing/windowing-overview.md)
* Product: **reunion**
* Technology: **windowing**
* GitHub Login: @rkarman
* Microsoft Alias: **rokarman**

**Comment by rkarman** [comment]
Thank you for bringing this to my attention. The snippet was lifted from the WinUI sample, in which the window is defined. This is being addressed in PR #3332
