### ISSUE TITLE
Step 4. -- Improve documentation steps | Install nvm, node.js, and npm

### ISSUE THREAD

**Issue by fabiobo2005** [MicrosoftDocs/windows-uwp#3548]
Document: windows-uwp/hub/dev-environment/javascript/nodejs-on-wsl.md
Title: Install nvm, node.js, and npm
Step: 4

**Change below statement from:**
To verify installation, enter: `command -v nvm` ...this should return 'nvm', if you receive 'command not found' or no response at all, close your current terminal, reopen it, and try again. Learn more in the nvm github repo.

**To:**
To verify installation, enter: `source ~/.bashrc` for **Bash** or ` source ~/.zshrc` for **ZShell**  and then test your **NVM** using `command -v nvm` ...this should return 'nvm', if you receive 'command not found' or no response at all, close your current terminal, reopen it, and try again. Learn more in the nvm github repo.

I´ve assessed run source ~/.bashrc on 3 different laptop machine and in all then it worked, same as close and reopen terminal, but it is no practical and in the botton line it does same as source ~/.bashrc after install.sh update it.

thanks,
Fabio Oliveira

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Pointed to the NVM repo that has more info about checking the version. (in https://github.com/MicrosoftDocs/windows-dev-docs/commit/2197bc6ffeb413324b55e52d2e1ac29c2f555ea2) Closing this issue. Thanks for filing it!
