### ISSUE TITLE
Misleading image?

### ISSUE THREAD

**Issue by nCastle1** [MicrosoftDocs/windows-uwp#3549]
The image at the top of the document suggests that WinUI 3 is supported on Xbox, but all I've heard is that it is not:

- https://www.theregister.com/2021/07/02/uwp_microsoft_winui3/
- https://github.com/microsoft/WindowsAppSDK/issues/829
- https://www.thurrott.com/dev/258377/microsoft-officially-deprecates-uwp

Can WinUI 3 target UWP on Xbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [Windows UI Library (WinUI) 3 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No, WinUI 3 is not supported in UWP. The image has been removed. Unfortunately, we don't have good replacement at this time.
