### ISSUE TITLE
test

### ISSUE THREAD

**Issue by swpark7** [MicrosoftDocs/windows-uwp#355]
tests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d900fedd-cc5a-bb92-0294-f11bea2b2b48
* Version Independent ID: ce6cc004-d532-20e7-5f04-a66c93a8ce3c
* Content: [Enterprise - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/enterprise/index)
* Content Source: [windows-apps-src/enterprise/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/enterprise/index.md)
* Service: **unspecified**
* GitHub Login: @awkoren
* Microsoft Alias: **alkoren**

**Comment by ginami** [comment]
Hi @swpark7--I closed your first feedback test, and I'm going to close this one as well. Please let us know if you have any documentation-specific feedback.
