### ISSUE TITLE
C# sample is incomplete

### ISSUE THREAD

**Issue by ms162223** [MicrosoftDocs/windows-uwp#3550]
The C# sample code for this page "https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview" doesn't work because "window" is never defined.

Look at this line of code in you C# sample to see the problem:
"IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(window);"

Finding the current window when working in a "Window App SDK" project is looking impossible since "Window.Current" always retuns null.  This article was a glimmer of hope. Please help fan the flame and update the sample with a working solution when possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2621305-73dc-26eb-cbd7-ed48c7bc0534
* Version Independent ID: e18ea4cd-0750-0207-e2f8-c97ff97de697
* Content: [Manage app windows (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview)
* Content Source: [hub/apps/windows-app-sdk/windowing/windowing-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/windowing/windowing-overview.md)
* Product: **reunion**
* Technology: **windowing**
* GitHub Login: @rkarman
* Microsoft Alias: **rokarman**

**Comment by rkarman** [comment]
Thanks for catching this! The code snipped in the doc was lifted from the WinUI sample which has the window defined, I will update the docs to use "this" instead, which should make it "drop-in" ready for projects not based on the sample project.

**Comment by rkarman** [comment]
This is being addressed in PR #3332
