### ISSUE TITLE
 Rust documentation for the Windows API link broken

### ISSUE THREAD

**Issue by Kmschr** [MicrosoftDocs/windows-uwp#3554]
Link in https://docs.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows#rust-documentation-for-the-windows-api 

 https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/ is returning 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf3f708-e517-41c8-0033-5e737e58cbd6
* Version Independent ID: a143550c-f85f-5b35-2fa4-0bcc243cac1d
* Content: [Rust for Windows, and the windows crate](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows)
* Content Source: [hub/dev-environment/rust/rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Kmschr! I've fixed the links in the repo's default branch. It's now just a matter of waiting until those changes go live (which will happen either this week or probably early next week). So I'll go ahead and close now.

Many thanks!
-Steve
