### ISSUE TITLE
Fix links in https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/settings-learning-track.md

### ISSUE THREAD

**Issue by anovik** [MicrosoftDocs/windows-uwp#3564]
Almost all the links in this [doc](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/settings-learning-track.md) are invalid and give 404 error

**Comment by QuinnRadich** [comment]
This error was a transient issue that affected links within our docs platform, and not a problem with the page itself. Closing this issue, as links currently work fine.
