### ISSUE TITLE
Visual Studio extension not needed

### ISSUE THREAD

**Issue by curia-damiano** [MicrosoftDocs/windows-uwp#3567]
In the prerequisites, it is listed the Visual Studio extension "C++/WinRT VSIX extension, which gives you C++/WinRT project templates in Visual Studio."
This extension is available only for VS2019 e not VS2022.
But more important, it is not needed, as only the NuGet package is used.

So this extension is not a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40b34b2-1bc9-25ed-b91e-cee68bc9edc1
* Version Independent ID: ecfcea0e-cad5-f4c7-6ab2-6970d4e8adcb
* Content: [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET 5 and later apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for raising this issue, @curia-damiano. I've published a fix now.

-Steve
