### ISSUE TITLE
Multilingual App Toolkit for Visual Studio 2022

### ISSUE THREAD

**Issue by skykharkov** [MicrosoftDocs/windows-uwp#3569]
Any news about Multilingual App Toolkit for Visual Studio 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91476ebf-8385-e698-7bdf-08481be7cf21
* Version Independent ID: 91476ebf-8385-e698-7bdf-08481be7cf21
* Content: [Multilingual App Toolkit Editor - Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads)
* Content Source: [hub/apps/design/globalizing/multilingual-app-toolkit-editor-downloads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/globalizing/multilingual-app-toolkit-editor-downloads.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by ollie-dev** [comment]
Missing it, too... some news / plans to fix are highly appreciated.

**Comment by Karl-Bridge-Microsoft** [comment]
Sorry no.

As this feedback is not specifically about the documentation, but rather a product request. Please click the product feedback link at the bottom of the topic.
