### ISSUE TITLE
Ratings 2

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3570]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1d045b-7d92-acd8-0df5-d1d53992febb
* Version Independent ID: 22c56721-c08c-fd8f-b940-92b834233f74
* Content: [Age ratings - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/age-ratings)
* Content Source: [windows-apps-src/publish/age-ratings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/age-ratings.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
No details provided.
