### ISSUE TITLE
Error in Developer Mode settings doc

### ISSUE THREAD

**Issue by angelazhangmsft** [MicrosoftDocs/windows-uwp#3572]
"In this case, it's common for the organization to enforce a policy that disables the UWP apps setting, as shown previously in the image of the settings page."

The image in the article doesn't show a "UWP apps setting"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0552daf5-cead-a1cd-c15a-d35ad32259e3
* Version Independent ID: 038857ac-c7b7-beef-14c1-aca52915afd3
* Content: [Developer Mode features and debugging - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging#feedback)
* Content Source: [hub/apps/get-started/developer-mode-features-and-debugging.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/developer-mode-features-and-debugging.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for bringing this to our attention - we removed the previous image when we added the disclaimer about Sideloading being a feature only on older versions of Windows 10, but did not update the wording. The inaccurate statement has now been removed.
