### ISSUE TITLE
windows 10 apps on M1 apple 

### ISSUE THREAD

**Issue by mohammadnb82** [MicrosoftDocs/windows-uwp#3574]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eca30ef6-08de-0729-e7ee-db07d50510f3
* Version Independent ID: 8a5fda0a-ba51-6234-420c-03d04f518211
* Content: [Program Compatibility Troubleshooter on ARM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm-program-compat-troubleshooter#toggling-emulation-settings)
* Content Source: [windows-apps-src/porting/apps-on-arm-program-compat-troubleshooter.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm-program-compat-troubleshooter.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
The topic seems to have moved here: https://learn.microsoft.com/windows/arm/apps-on-arm-program-compat-troubleshooter.

Assigning the writer-owner of that topic.
