### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#358]
CompositionLight = spotlight;
should be
CompositionLight = spotLight;
with capital 'L'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fdc6530-eaae-642e-9068-e8598f2a1a55
* Version Independent ID: 6c6aee24-3150-5b15-4216-74b3a08aa3eb
* Content: [lighting - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/composition/lighting)
* Content Source: [windows-apps-src/composition/lighting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/lighting.md)
* Service: **unspecified**
* GitHub Login: @JEBishop
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This is fixed. Thanks for letting us know about it.

**Comment by coolguy301** [comment]
```
return typeof(FancyPointerTrackerLight).FullName;

```

should be 

```
return typeof(FancyOrangeSpotLight).FullName;
```
