### ISSUE TITLE
VB6 API

### ISSUE THREAD

**Issue by NeoTechni** [MicrosoftDocs/windows-uwp#3581]
I have a program to manage all game controllers connected to a PC and I'd like to add support for the surface dial, but it's written in VB6

is there a way to use this in that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf1d9b03-0aee-c779-b2b7-c0d354cf8b37
* Version Independent ID: 7bbb638c-48df-75ab-49f4-82c7f6cb60cd
* Content: [Support the Surface Dial (and other wheel devices) in your Windows app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/radialcontroller-walkthrough)
* Content Source: [hub/apps/design/input/radialcontroller-walkthrough.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/radialcontroller-walkthrough.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
You could try vb.net in a UWP application. As far as I know, there is no VB6 translation library for UWP applications.

**Comment by NeoTechni** [comment]
That's a terrible solution. Rebuilding the entire program is not an option, and I've made VB.net companion programs that do one thing for a VB6 program that does a dozen things, and the VB.net program is both tens of times larger and takes up 60 MB of RAM despite doing a ton less. It's a massive waste of resources/performance.
