### ISSUE TITLE
Use as a steering wheel

### ISSUE THREAD

**Issue by NeoTechni** [MicrosoftDocs/windows-uwp#3583]
since it has force feedback, itd be nice to use this for racing games as a racing wheel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf1d9b03-0aee-c779-b2b7-c0d354cf8b37
* Version Independent ID: 7bbb638c-48df-75ab-49f4-82c7f6cb60cd
* Content: [Support the Surface Dial (and other wheel devices) in your Windows app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/radialcontroller-walkthrough)
* Content Source: [hub/apps/design/input/radialcontroller-walkthrough.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/radialcontroller-walkthrough.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported.

**Comment by NeoTechni** [comment]
Correct, it's a request.
