### ISSUE TITLE
Access Denied when installing nvm in windows

### ISSUE THREAD

**Issue by marcoandre1** [MicrosoftDocs/windows-uwp#3584]
Just wanted to point out that I had an `Access Denied` error message when trying to set my nvm version with `nvm use <version>` at step 9. We can easily google it and find that the problem is that we need to run PowerShell as an Administrator as suggested in this issue <https://stackoverflow.com/questions/50563188/access-denied-issue-with-nvm-in-windows-10> but it would be appreciated if this was indicated somewhere in the tutorial. 

Also, is it possible to run this without admin rights? Might add a notice if it's not possible.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hmm... I believe it depends on your security settings, but I'll do some testing. In the meantime, adding the elevated admin permissions is a good suggestion. Sorry for the trouble -- adding it now.

**Comment by mattwojo** [comment]
Added a note: https://github.com/MicrosoftDocs/windows-uwp/commit/fe086354fbe18f56616e6992c61097797767ade2
