### ISSUE TITLE
App ID URI

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#359]
I had to contact support regarding the definition of "App ID URI", there was not even sure what it is. It turns out that it is a "URL". It is confusing that the other setting is called "Reply URL" with the word URL and the other one is "URI".

It will help other developers if an example of an App ID URI would be written here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf973bd-e0d9-19b0-ad24-e09a83d3a2a9
* Version Independent ID: 25d0bdd2-0487-6742-b4bd-abc1e3ee6be8
* Content: [Add users, groups, and Azure AD applications to your Dev Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications#azure-ad-applications)
* Content Source: [windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for your feedback. I've added a link to another topic that has more info about the App ID URI, including examples (https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications#changing-the-application-registration-to-support-multi-tenant).
