### ISSUE TITLE
Confusion about VSIX installation

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#3593]
I don't understand why the Windows App SDK VSIX is installed via download links on this page, rather from the Manage Extensions dialog within Visual Studio 2022. 

Also, I don't understand why, when I do look at the Manage Extensions dialog in VS2022 -- I search for Windows App SDK, and the only entry says "Windows App SDK (Experimental) [Preview]." It is marked version 1.0.0.50489432. 

This makes no sense, since this page talks about two different channels: Experimental, and Preview. Why is the entry in the dialog box labeled as BOTH (Experiemental) [Preview]. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by ghost** [comment]
Screen capture attached...which is it, "Experimental", or "Preview"? And why isn't the App SDK  VSIX available by the usual means?

![Screenshot 2021-12-29 211545](https://user-images.githubusercontent.com/16345333/147723553-7f6b0631-3200-4250-a8e1-d30d8970c1cb.png)

**Comment by stevewhims** [comment]
Hi, @jcb9000, and thanks for enquiring about this.

The documentation is correct. The VS2019 VSIXes are on the Download Center (and show up in Extensions > Manage Extensions). The VS2022 VSIXes are available in a different way (through a standalone download).

If/when the state of where downloads live (and how to obtain/install them) changes, we'll keep the documentation up to date.

The feedback channel you're using here (**Send feedback about** \> **This page**) is for feedback about the documentation in this topic itself, as published. For example, if the content is incorrect or incomplete.

For questions (or requests for help) regarding a specific product or scenario (including how it's designed), one option is to click **Send feedback about** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all).

About the Windows App SDK specifically: to provide feedback, or to report other issues, add your feedback to an existing issue or file a new issue on the [WindowsAppSDK GitHub repo](https://github.com/microsoft/WindowsAppSDK/issues/new/choose).

Thanks!
-Steve
