### ISSUE TITLE
FancyZones consistently opening windows on wrong monitor. Explicitly set default monitor?

### ISSUE THREAD

**Issue by MattariOnline** [MicrosoftDocs/windows-uwp#3596]
First off, I love PowerToys, especially FancyZones - I use them daily, both at work and home.

However I've noticed frequently (both with the experimental "active monitor" toggle on and off) that Windows tend to open on the wrong monitor. To emphasize the lack of user error, I've actually opened messages from Outlook, snapped them specifically in a zone on my primary monitor.
Next time I go to open a message, it still opens somewhere on my second monitor which I typically keep turned off.

Because of this, I need to find it, hover over the Window's preview in the taskbar, right click, move, tap an arrow key, and drag it from the second monitor onto the first.

Now while I'm sure there are probably workarounds, some of which I'd rather not use like trying to disable it for some programs (I want my main Outlook to still snap), it would actually be far more beneficial if I could just say "Always open windows on display 1." I'm sure likewise, it would be helpful if someone has 2, 3, 4 or more monitors for them to say "Always open on display 3" or 4, etc.

I should also add that I keep my mouse on the correct monitor, open the window from the correct monitor, etc and still tend to get it actually opening on the wrong monitor.

Is there any way this might be considered, or if nothing else, look into why the program consistently opens on the wrong monitor?
Thanks so much for reading and any/all help with this. Devs, you are God's gift to mankind and to Windows' betterment. Thank you for your hard work, and have a fantastic new year!

**Comment by mattwojo** [comment]
Just took another look at this and realized this is a product update request -- there's already a few associated issues in the PowerToys product repo:
https://github.com/microsoft/PowerToys/issues/17129
https://github.com/microsoft/PowerToys/issues/17863
https://github.com/microsoft/PowerToys/issues/10535

Please consider adding on to one of these issues and upvoting. I can only help with documentation updates in this /MicrosoftDocs/ repo. The PowerToys devs more closely monitor and respond to: https://github.com/microsoft/PowerToys/issues

Closing.
