### ISSUE TITLE
Broken link on "Get started with Windows 10 apps"

### ISSUE THREAD

**Issue by nrkirby** [MicrosoftDocs/windows-uwp#3597]
The UI Basics link is broken

![image](https://user-images.githubusercontent.com/6445534/147888618-e5643c32-8f27-4633-98c8-5d5488f9bfef.png)

![image](https://user-images.githubusercontent.com/6445534/147888625-15a8fe9b-bd15-4db8-b5e8-69783ed01d5a.png)

The broken URL is: https://docs.microsoft.com/en-us/windows/apps/design/basics/xaml-basics-ui

**Comment by QuinnRadich** [comment]
We've replaced this link with a new link to more recently updated content. Thanks for bringing this issue to our attention.
