### ISSUE TITLE
Broken images on Flyout page

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/windows-uwp#360]
Some linked images are not displayed, only this is shown:
```
![Example of a dialog](images/dialogs/dialog_RS2_delete_file.png)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4822fcb-d3c5-06b1-10dd-dd56cc08df75
* Version Independent ID: e9b087b2-602b-1a3b-94ab-81489829510e
* Content: [Dialogs and flyouts - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
I just posted a fix, thank you for calling this to our attention!
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs
