### ISSUE TITLE
Content spacing is confusing

### ISSUE THREAD

**Issue by alejo4000** [MicrosoftDocs/windows-uwp#3603]
The spacing between the pictures and their corresponding text, vs between each list item is confusing. The large gap between the image with its corresponding text vs the next list item below it is too small, it makes it difficult to discern which text goes with which item.

![image](https://user-images.githubusercontent.com/26553342/148106825-65a433d6-c8b5-4348-b8c0-c779ccde6a2a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 914945e9-d1c8-82b8-bd25-707a08dcadbe
* Version Independent ID: fd60f56c-9371-b4a7-f274-8795605db089
* Content: [Design and code for Windows apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/)
* Content Source: [hub/apps/design/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback. Topic has been updated and layout adjusted.
