### ISSUE TITLE
UWP on Xbox One page does not mention requirement to maintain active presence in the Store

### ISSUE THREAD

**Issue by nlebeck** [MicrosoftDocs/windows-uwp#3604]
The UWP on Xbox One page says "you don't have to be part of a developer program to experiment, create, and test games or apps on Xbox. All you need is a developer account in Partner Center." This description suggests that using a developer account to develop for Xbox is appropriate for hobbyist developers who are tinkering with Xbox development but have no plans to publish games. 

However, Microsoft has started disabling the developer accounts of hobbyist users (including me) who do not "have an active presence in the Store," claiming that not publishing to the Store violates the Code of Conduct. If this enforcement action was not a mistake, then the documentation should emphasize that publishing to the Store is a requirement for maintaining a developer account, and that developing for UWP on Xbox One is not appropriate for hobbyist developers who just want to experiment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d516726d-7d23-56fa-a909-7636fc7937f6
* Version Independent ID: be2dd62f-b812-2c3c-dec1-ae35bfadf1a3
* Content: [UWP on Xbox One - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/)
* Content Source: [windows-apps-src/xbox-apps/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/index.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by nlebeck** [comment]
Based on [this Twitter thread](https://twitter.com/jronald/status/1478856796097835008), it sounds like the disabling of developer accounts may indeed have been a mistake. If that is the case, and there is no requirement to maintain an active Store presence in order to have a developer account, then the current documentation is fine, and it makes sense to close out this issue.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the update! Closing Issue. Please reopen if still a concern.
