### ISSUE TITLE
Is this page current with respect to Visual Studio 2022?

### ISSUE THREAD

**Issue by PaulDempsey-ms** [MicrosoftDocs/windows-uwp#3606]
Is this page current with respect to Visual Studio 2022, or is there an update to MAT. I would expect that since VS 2022 is 64 bit, then extensions would need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91476ebf-8385-e698-7bdf-08481be7cf21
* Version Independent ID: 91476ebf-8385-e698-7bdf-08481be7cf21
* Content: [Multilingual App Toolkit Editor - Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads)
* Content Source: [hub/apps/design/globalizing/multilingual-app-toolkit-editor-downloads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/globalizing/multilingual-app-toolkit-editor-downloads.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Yes, the topic was revised for 2022.
