### ISSUE TITLE
 The instructions for installing Power Toys from GiHup do not work. There is no menu labelled Assets!!!!

### ISSUE THREAD

**Issue by beisenbe** [MicrosoftDocs/windows-uwp#3609]
The instructions for installing Power Toys from GiHup do not work. There is no menu labelled Assets!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
@beisenbe You can see the Assets menu there and the installer below in https://aka.ms/installpowertoys. Please see if this helps!
![Screen Shot 2022-01-13 at 9 59 51 AM](https://user-images.githubusercontent.com/11349917/149252492-85883e0e-2f01-445a-8598-68f607ef58e4.png)
