### ISSUE TITLE
What about ClickOnce deployed apps?

### ISSUE THREAD

**Issue by evolve700** [MicrosoftDocs/windows-uwp#361]
This article is missing information about software being deployed through ClickOnce. I'm currently facing the problem that my ClickOnce deployed app cannot show notifications. Apparently the reason seems to be that ClickOnce only creates .appref-ms shortcuts in the Startmenu but no .lnk Shortcuts. However, it is impractical for a ClickOnce application to also create a .lnk shortcut as that would circumvent the ClickOnce Updater when launching the application.

What is required in order to get toast notifications working with ClickOnce apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53415734-dd31-7cf0-a82e-02566ed82396
* Version Independent ID: e5f82c08-6c9f-c628-9a45-5df000239ae4
* Content: [Send a local toast notification from desktop C# apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Service: **unspecified**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Hey @evolve700, thanks for letting us know about this issue! We'll investigate ClickOnce over the next two weeks and get back to you with an answer.

Thank you!
Andrew

**Comment by evolve700** [comment]
Thank you, @anbare. I've been trying to understand a bit more what the problem is and I think it boils down to getting the AUMID that the ClickOnce Framework/Installer assigns to the deployed application. This is exactly where I'm stuck at at the moment. Since I'm in a C# desktop application I tried P/Invoking some native methods in shell32.dll/kernel32.dll.

In shell32.dll:
```
[DllImport(@"shell32.dll", SetLastError = true)]
private static extern int GetCurrentProcessExplicitAppUserModelID([MarshalAs(UnmanagedType.LPWStr)] StringBuilder appId);
```
The function call returns S_OK = 0 but the StringBuilder is filled with "??". Sadly, this return value is not documented anywhere. What is documented however is that GetCurrentProcessExplicitAppUserModelID apparently requires SetCurrentProcessExplicitAppUserModelID to have been called previously. I don't do this explicitly, hence this might be the reason why it does not work. On the other hand, it might be that the ClickOnce Framework does it for me.

In kernel32.dll I tried
```
[DllImport("kernel32.dll", SetLastError = true)]
private static extern int GetApplicationUserModelId(IntPtr hProcess, ref uint appModelIdLength, [MarshalAs(UnmanagedType.LPWStr)] StringBuilder appId);
``` 
but this returns APPMODEL_ERROR_NO_APPLICATION = 15703 and hence the StringBuilder is empty.

I've been able to display the actual AUMID in the Windows Explorer using the method described [here](https://jcutrer.com/howto/windows/find-aumid). This AUMID can be found in the registry in a subfolder of HKCU\Software\Classes\Software\Microsoft\Windows\CurrentVersion\Deployment\SideBySide\2.0\PackageMetadata\ but the subfolder is named like a GUID, so again there seems to be no apparent way to find the AUMID reliably.

**Comment by andrewleader** [comment]
Can you not just statically know your AUMID? Or does the installer control your AUMID and you don't have one single AUMID?

For most apps, like Office for example, they always have the AUMID of `Microsoft.Office`, and they simply use that same string in both their installer and in their app code.

**Comment by evolve700** [comment]
A colleague of mine suggested something similar. However, to cite the MSDN article about [Application User Model IDs](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459.aspx):
> An example of this situation is the ClickOnce framework, which properly assigns AppUserModelIDs on behalf of the applications that it manages. As in all such environments, applications deployed and managed by ClickOnce **should not*** assign explicit AppUserModelIDs themselves, because doing so will conflict with the AppUserModelIDs assigned by ClickOnce and lead to unexpected results.

**Comment by andrewleader** [comment]
Ah. In this case, calling the `RegisterAumidAndComServer` method in the Compat library is NOT assigning the AUMID for the app. It's simply ensuring that the AUMID gets passed to the notification APIs when sending a toast.

The notification APIs can't automatically inherit your AUMID for classic Win32 apps, which is why you have to specify it.

So don't worry, you're not assigning the AUMID twice. You're simply providing "This is my AUMID, which matches my previously assigned AUMID".

So go ahead and follow the steps in the docs and simply use the same AUMID and you should be good!

```csharp
DesktopNotificationManagerCompat.RegisterAumidAndComServer<MyNotificationActivator>(
"YourCompany.YourApp"
);
```

Please close this issue if that worked! Thanks! I'll still work on adding a ClickOnce example to the doc but your issue should be resolved I believe!

**Comment by evolve700** [comment]
Thank you. I managed to get it working.
Still looking Forward to your update of the article regarding ClickOnce.

**Comment by Omarkth** [comment]
Hey @andrewleader, any update regarding the ClickOnce example?? 

@evolve700 can you tell us more about how did you get it to work?

**Comment by andrewleader** [comment]
Thanks for the interest in ClickOnce, Omarkth. I've let the new PM owner of these docs know about the interest in ClickOnce, we'll look at where this fits in our documentation prioritization. If anyone else needs help with ClickOnce too, let us know so that we know it's important!

**Comment by thoraj** [comment]
I do not have any concrete technical questions right now. I'm researching how we can show notifications in apps delivered through the ClickOnce mechanism and through VDI/XenApp.

I'm not sure if I'm reading this thread correctly; is it possible to display notifications in apps delivered through ClickOnce?

**Comment by andrewleader** [comment]
It definitely should be possible. All that's needed is a Start menu shortcut with some additional properties specified, I imagine ClickOnce has a way to specify those (but I personally haven't researched it).

**Comment by Lechus** [comment]
To get appid for clickonce deployed app:
https://www.devexpress.com/Support/Center/Question/Details/T613322/xaf-text-notification-using-toasts-in-winforms-apps-deployed-through-click-once-not

It works for me.
