### ISSUE TITLE
VERY GOOD IDEA

### ISSUE THREAD

**Issue by kizerkizer** [MicrosoftDocs/windows-uwp#3611]
This is amazing. Just allow people to "install" the PWAs as if they were games to the Xbox's game library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9158604a-9765-b436-0e7f-546db0cdbe24
* Version Independent ID: 545bda0f-621b-145f-5d21-1a09ecf44ae5
* Content: [HTML game development on Xbox - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/development-lanes-html)
* Content Source: [windows-apps-src/xbox-apps/development-lanes-html.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/development-lanes-html.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No issue reported.
