### ISSUE TITLE
Sample Code Error?

### ISSUE THREAD

**Issue by farinjini** [MicrosoftDocs/windows-uwp#3612]
[Enter feedback here]
In the C# example on IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(window); didn't work for me on VS 2022. The error message was "The name 'window' does not exist in the currrent context".
To get it to work, I changed 'window' to 'this': IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2621305-73dc-26eb-cbd7-ed48c7bc0534
* Version Independent ID: e18ea4cd-0750-0207-e2f8-c97ff97de697
* Content: [Manage app windows (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview)
* Content Source: [hub/apps/windows-app-sdk/windowing/windowing-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/windowing/windowing-overview.md)
* Product: **reunion**
* Technology: **windowing**
* GitHub Login: @rkarman
* Microsoft Alias: **rokarman**

**Comment by rkarman** [comment]
Thank you for bringing this to my attention. The snippet was lifted from the WinUI sample, in which the window is defined. This is being addressed in PR #3332
