### ISSUE TITLE
add an exception for "win+d" for "Always on top" utility

### ISSUE THREAD

**Issue by MarHHM** [MicrosoftDocs/windows-uwp#3613]
Thanks for the great utility..

I have a suggestion to add a feature to choose whether to exclude the pinned window from being minimized at "show desktop (win+d)"..

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Version Independent ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Content: [PowerToys Always on Top utility for Windows](https://docs.microsoft.com/de-de/windows/powertoys/always-on-top)
* Content Source: [hub/powertoys/always-on-top.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/always-on-top.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
@MarHHM Thanks for your suggestion.
This repo is just for the docs, for enhancements to the PowerToys itself, please file the issue [here](https://github.com/microsoft/PowerToys/issues/new/choose) in the Microsoft/PowerToys repo. 
Thank you!

**Comment by crutkas** [comment]
What @franky920920 said :)
