### ISSUE TITLE
Link to Windows App SDK extension for Visual Studio (VSIX) downloads extension for VS 2019

### ISSUE THREAD

**Issue by wieslawsoltes** [MicrosoftDocs/windows-uwp#3616]
Link https://aka.ms/windowsappsdk/stable-vsix-2022-cs downloads WindowsAppSDK.Cs.Extension.Dev17.Standalone.vsix

https://docs.microsoft.com/pl-pl/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022

**Comment by Karl-Bridge-Microsoft** [comment]
That URI specifies the version # not the product name, they are not equivalent (see https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview).
