### ISSUE TITLE
Feedback of always on top function

### ISSUE THREAD

**Issue by irisariuan** [MicrosoftDocs/windows-uwp#3618]
In windows 11, the border is a rectangle, which didn't match the round border of windows 11, hope that somebody can fix this, cuz it looks really ugly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Version Independent ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Content: [PowerToys Always on Top utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/always-on-top)
* Content Source: [hub/powertoys/always-on-top.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/always-on-top.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
Thanks for your suggestion.
This repo is just for the docs, for enhancements to the PowerToys itself, please file the issue [here](https://github.com/microsoft/PowerToys/issues/new/choose) in the Microsoft/PowerToys repo. 
Besides, there is an open issue for this https://github.com/microsoft/PowerToys/issues/15284
Thank you!

**Comment by crutkas** [comment]
What @franky920920 said :)
