### ISSUE TITLE
Example how to use WinRT UI APIs from WinForms/WPF wrong

### ISSUE THREAD

**Issue by georg-jung** [MicrosoftDocs/windows-uwp#3619]
In <https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md#c-net-5-and-later>:

> In the call to ```GetWindowHandle(this)```, the object you pass must be a Window (either a WinUI 3 Window, a WPF Window, or a WinForms Window). In the example below

This seems to be wrong.

When calling it from a WinForms form, it throws:

> System.ArgumentException: "Source object type is not a projected type and does not inherit from a projected type. Arg_ParamName_Name"

I think correct would be something like:

	// Get the current window's HWND by passing in a reference to the Window object
	// For WinUI
	var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
	// For WPF
	var hwnd = new WindowInteropHelper(this).EnsureHandle();
	// For WinForms
	var hwnd = this.Handle;

I'd open a PR but I'm not too sure if I understand this completely right. Also, I did test the WinForms variant but not the WPF variant. I took the WPF variant from <https://nicksnettravels.builttoroam.com/windows-app-sdk-preview-2/>. That post incorrectly states that the WPF variant works for WinForms too, which it doesn't.

1. I'm rather sure this Doc is wrong in the described way. I'd be great to have this corrected. On one hand because it seems to be just wrong what's written their, on the other hand because it seems to be "the" place you find when reasearching how to use WinRT UI (MessageDialog/Pickers/etc) APIs from WinForms and that's actually a great feature that's probably known by not too many WinForms devs.
2. In the bigger picture it might be beneficial to have an API that works as described in the Doc, a one fits all function "give me a hwnd, I have a WinForms/WPF/WinUI window". Maybe its not too easy to do though (Take a dependency on all frameworks? Implement the same member in each framework?). Where to file this issue?
3. In the bigger picture I think using the new UI elements like MessageDialog etc. is a great opportunity and I feel it's quite hard to find quality information on how to do this. I also guess that not to many WinForms/WPF devs know how to do this. One reason might be the lack (please point me in the right direction if I'm wrong) of good Getting Started guides etc. Having a doc that provides an easy straight forward working example for WinForms/WPF would be great, i.e.:

		// For WinForms
		var hwnd = this.Handle;

		var messageDialog = new MessageDialog("Test");
		// Add commands and set their callbacks
		messageDialog.Commands.Add(new UICommand(
			"Try again",
			x => DoSomeTryAgain()));
		messageDialog.Commands.Add(new UICommand(
			"Close",
			x => DoSomeClose()));

		// Set the command that will be invoked by default
		messageDialog.DefaultCommandIndex = 0;

		// Set the command to be invoked when escape is pressed
		messageDialog.CancelCommandIndex = 1;

		// Associate the HWND with the file picker
		WinRT.Interop.InitializeWithWindow.Initialize(messageDialog, hwnd);

		// Show the message dialog
		await messageDialog.ShowAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909f1773-1e55-eb5a-206f-b32ce6f9dd9d
* Version Independent ID: 24ea5c87-1c21-884d-f05f-833bbd894ba9
* Content: [Windows Runtime APIs not supported in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api?tabs=csharp)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @georg-jung. I believe that the correct info is this:

WPF

For WPF, the appropriate method for retrieving the window handle is [WindowInteropHelper.Handle](https://docs.microsoft.com/dotnet/api/system.windows.interop.windowinterophelper.handle).

WinForms

For Windows Forms, the appropriate method is [NativeWindow.Handle](https://docs.microsoft.com/dotnet/api/system.windows.forms.nativewindow.handle).

But I'll continue to investigate and verify, and I'll update the topic once I'm certain.

-Steve

**Comment by georg-jung** [comment]
Great, thanks.

**Comment by stevewhims** [comment]
Hi, @georg-jung. I believe that all the necessary info is now published in these topics:

[Retrieve a window handle (HWND)](https://docs.microsoft.com/windows/apps/develop/ui-input/retrieve-hwnd)
[Display WinRT UI objects that depend on CoreWindow](https://docs.microsoft.com/windows/apps/develop/ui-input/display-ui-objects)

-Steve
