### ISSUE TITLE
What resampling algorithm is used?

### ISSUE THREAD

**Issue by cguinnup** [MicrosoftDocs/windows-uwp#3625]
I'd like to know what image resampling algorithm(s) are used when resizing with PowerToys Image Resizer. I cannot find this information documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 954b70f9-e75f-ef96-8c25-7f75b355afe7
* Version Independent ID: 393934c9-4dd3-50c2-719a-e48b724a77a0
* Content: [PowerToys Image Resizer utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/image-resizer)
* Content Source: [hub/powertoys/image-resizer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/image-resizer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
Please refer to the repo https://github.com/microsoft/PowerToys/ for the source code and its issues. Thanks!

**Comment by crutkas** [comment]
Depends but use .NET to do the adjustments.
https://github.com/microsoft/PowerToys/blob/main/src/modules/imageresizer/ui/Models/ResizeOperation.cs
