### ISSUE TITLE
There is no mention of how to delete / remove a zone

### ISSUE THREAD

**Issue by pauby** [MicrosoftDocs/windows-uwp#3626]
After several suggestions [[1](https://github.com/microsoft/PowerToys/issues/581)] [[2](https://github.com/microsoft/PowerToys/issues/9670)] to document how to delete or remove a zone, it's still not clear on how that is done. The documentation on this page mentions the word `delete` once (and it's about deleting text) and the word `remove` is not mentioned at all.

The documentation needs to be updated to make it absolutely clear that:

* There is no command / option to delete / remove a zone,
* Instead, zones should be merged to bring them together (for example if you have a three column layout and want a two column layout then merge two zones together and resize them).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones#creating-a-custom-layout)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
@mattwojo Resolved with #3631

**Comment by crutkas** [comment]
With grid layouts, you merge, you don't delete.  The change in text is updated now as well.

**Comment by crutkas** [comment]
@mattwojo, can we close this out?

**Comment by mattwojo** [comment]
Closing. Thanks for raising this issue @pauby.
