### ISSUE TITLE
Instructions for creating an unpackaged WinUI 3 app are broken

### ISSUE THREAD

**Issue by smaillet** [MicrosoftDocs/windows-uwp#3627]
This documentation is broken, the instructions for an unpackaged app imply this is simple and straightforward - but they don't actually work. (There really should be a project template for this stuff so we don't need to mess with any of this!)

Step 6 suggests you can just run&build, however that results in runtime errors (Apparently even before the first line of Main() is executed, which is VERY surprising!)
`Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll`

No amount of searching has found a solution to this. 

Step 6 includes a reference to "Additional Deployment information" but the links there are even more chaotic and vague (I'm not deploying the app, I just want to build it and run/debug it locally. Like we could always do before we got all the .NET Core an WinAppSDK cruft. [Used to be much simpler])

Step 7 goes on to mention some "bootstrapper API" but I haven't the foggiest clue what that's for or why it should be needed. Besides I can't get to step 7 because step 6 doesn't work (and if it did, I don't know why I'd need a step 7). Furthermore step 7 starts with an incomplete sentence (and lower case to boot!) it appears there isn't supposed to be a step 7 but it's supposed to continue the additional text at the end of step 6. (Though putting that much stuff after "build and run" doesn't make any sense, since Build&Run is the end goal of the exercise - what's with all the rest of that stuff?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create a new project that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-csharp#feedback)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by stevewhims** [comment]
Sorry for the delay in responding.

I updated and simplified this topic today. Between this topic and [Install tools for the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment), I believe things are now correct and up to date.

-Steve
