### ISSUE TITLE
Feature request: ability assign hotkey to toggle between left/right-handed mouse

### ISSUE THREAD

**Issue by elemequil** [MicrosoftDocs/windows-uwp#3629]
The ability assign hotkey to toggle between left/right-handed mouse would be very convenient for:

- Lefties and righties who share a computer.
- Righties who are learning to become lefties (for brain and physical training/therapy purposes), or vice versa.

If this became a standard Windows feature without the need to install PowerToys, lefties would instantly be able to leftify any mouse-operated PC at the stroke of a hotkey. 

Pressing a hotkey is inherently ambidextrous, whereas navigating the menus to the primary mouse button settings is somewhat awkward and confusing when you have to do it with mismatched hand and mouse.

**Comment by mattwojo** [comment]
Interesting suggestion @elemequil! These repo issues are for documentation updates though - you should file this on the PowerToys product repo here: https://github.com/microsoft/PowerToys/issues/new/choose 

Looks like there are already a few related issues there:
https://github.com/microsoft/PowerToys/issues/9008
https://github.com/microsoft/PowerToys/issues/15980
https://github.com/microsoft/PowerToys/issues/1475

May be worth adding thoughts and/or upvoting some of those issues as well to encourage attention from the contributors to new PowerToys features.
