### ISSUE TITLE
Contradicting information about Segoe Fluent Icons font

### ISSUE THREAD

**Issue by johnnygerard** [MicrosoftDocs/windows-uwp#3632]
Quoted from [Icon list](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#icon-list):

> the Segoe Fluent Icons font includes many more icons than we can show here

> The following tables display all Segoe Fluent Icons glyphs

It seems to me that all glyphs are listed. Can this be confirmed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e1f4b4-3d25-c08c-e3b0-12011d3bba0f
* Version Independent ID: 3b140070-493f-0b2c-f7c4-3fb89192d2d0
* Content: [Segoe Fluent Icons font - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font)
* Content Source: [hub/apps/design/style/segoe-fluent-icons-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/style/segoe-fluent-icons-font.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Jay-o-Way** [comment]
I think the shown icons are more like advised ones. The font indeed has many more, including deprecated ones.

**Comment by johnnygerard** [comment]
Thanks for that answer.

**Comment by Jay-o-Way** [comment]
I'm sure there are people who have a much better answer though...
