### ISSUE TITLE
Add note to PowerToys in mac to windows doc

### ISSUE THREAD

**Issue by noraa-junker** [MicrosoftDocs/windows-uwp#3637]
In the keyboard shortcut section add a note that you can remap shortcuts with PowerToys.

I see this many times on twitter, that mac users remap shortcuts with Keyboard Manager to keep their mac shortcuts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f358aa09-2544-b312-d819-ef7006b30e6f
* Version Independent ID: 26a38565-5fa5-8867-4eb6-c7c8a7293b47
* Content: [Moving from Mac (Unix) to Windows](https://docs.microsoft.com/en-us/windows/dev-environment/mac-to-windows)
* Content Source: [hub/dev-environment/mac-to-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/mac-to-windows.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by noraa-junker** [comment]
I would like to create a PR for this, if you agree with this.

**Comment by mattwojo** [comment]
YES! I think this is a GREAT idea to add a link to this page. Happy to accept a PR from you or add it myself if you'd prefer. Thanks @Aaron-Junker!

**Comment by noraa-junker** [comment]
> YES! I think this is a GREAT idea to add a link to this page. Happy to accept a PR from you or add it myself if you'd prefer. Thanks @Aaron-Junker! 

I'll do it. Expect the PR this week.

I'm glad that I'm able to improve the Windows docs.

**Comment by mattwojo** [comment]
Thanks Aaron! I'll be out of office for the rest of the week, but will look for it next week.

**Comment by noraa-junker** [comment]
PR merged
