### ISSUE TITLE
Delete twitter contest page

### ISSUE THREAD

**Issue by noraa-junker** [MicrosoftDocs/windows-uwp#3638]
The contest ended, so this can get deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58ac67e-268a-6517-de95-13cdd283d249
* Version Independent ID: 4ae5124c-6a53-37c9-aade-cf22dfba8418
* Content: [Docs contribution twitter contest](https://docs.microsoft.com/en-us/windows/twitter-contest)
* Content Source: [hub/twitter-contest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/twitter-contest.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by noraa-junker** [comment]
I would like to create a PR for this, if you agree with this.

**Comment by mattwojo** [comment]
I set that page up and we can totally delete it. Please feel welcome to create a PR to do so -- thanks again Aaron!

**Comment by noraa-junker** [comment]
PR merged
