### ISSUE TITLE
Bad table formatting

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/windows-uwp#364]
Table formatting for this document is broken.  Looks good on Gitbub, but broken on the docs site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ab644-ee7d-3dec-cd0f-cbb1e4d8b6ac
* Version Independent ID: 97eecc36-8e2e-d4c7-1ecb-948e0846bda5
* Content: [Device Portal core API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Service: **unspecified**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by QuinnRadich** [comment]
Closing this issue, as the problem has been fixed.
