### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DerekFrench** [MicrosoftDocs/windows-uwp#3643]
The link in the Note section at the top takes you to a Not Found page.

https://developer.microsoft.com/en-us/games/xbox/docs/gdk/provisioning-role

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb57bfe-69f7-e1d0-cd63-d28360727985
* Version Independent ID: ece8efc3-9422-0103-3ed7-94e8427fcb7c
* Content: [Xbox One Developer Mode activation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by Karl-Bridge-Microsoft** [comment]
Link is working now. Maybe just a glitch.

**Comment by DerekFrench** [comment]
I am clicking on the above link right now

https://developer.microsoft.com/en-us/games/xbox/docs/gdk/provisioning-role

![MSSite-ProvisioningRole](https://user-images.githubusercontent.com/61522565/151599333-ad98e179-592c-45b7-98b4-45f59c36b9e9.png)

and it always takes me to 

https://developer.microsoft.com/en-us/games/xbox/docs/gdk/en-us/Home/Error

![MSSite-ProvisioningRole-Error](https://user-images.githubusercontent.com/61522565/151599390-f81c50a1-e1fc-4ef0-8311-c9a223db7313.png)

Derek

**Comment by Karl-Bridge-Microsoft** [comment]
The note specifies "If you're a managed partner". Could that be the issue?

<img width="590" alt="image" src="https://user-images.githubusercontent.com/12849639/151600425-e58f755b-d5f1-4e0d-9088-05070c289e2c.png">

**Comment by DerekFrench** [comment]
We are a managed partner, and I am desperate to read how to get our dev kit activated.

**Comment by Karl-Bridge-Microsoft** [comment]
Are you logged in with an associated account? Have you contacted the xbox team directly? Sounds like you might need product team support.
