### ISSUE TITLE
Application Data container serialization

### ISSUE THREAD

**Issue by knightmeister** [MicrosoftDocs/windows-uwp#3644]
The page says the following:

> The following data types can be used with settings: integers, doubles, floats, chars, strings, Points, DateTimes, **and more.**

The "and more" part is vague.

What is the requirement for being supported? Primitive type? Structs? ISerializable?

API documentation needs to be precise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69786f43-9821-73c8-f6c8-7b725f4b85c0
* Version Independent ID: 1c8acb2c-fec1-ceab-7a99-26f4a2394de0
* Content: [Save and load settings in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/settings-learning-track)
* Content Source: [windows-apps-src/get-started/settings-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/settings-learning-track.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by knightmeister** [comment]
DateTime is not supported, attempting to set one in code results in the following error:

```
onecore\base\appmodel\statemanager\apiset\lib\statemanager.cpp(1482)\kernelbase.dll!00007FFC4AC445A5: (caller: 00007FFC4AC02259) ReturnHr(1) tid(2d30) 80070057 The parameter is incorrect.
    Msg:[IsValueTypeInRange 39] 
onecore\base\appmodel\statemanager\apiset\lib\statemanager.cpp(1499)\kernelbase.dll!00007FFC4AC44514: (caller: 00007FFC290A4F57) LogHr(1) tid(2d30) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFC4ABC4F69 (KernelBase.dll) in Aproneers.App.Windows.exe: WinRT originate error - 0x80070057 : 'Error trying to write application data container value'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFC4C4AC363: (caller: 00007FFC4C4B6049) ReturnHr(1) tid(2d30) 8007007E The specified module could not be found.
onecoreuap\base\appmodel\statemanager\winrt\lib\windows.storage.applicationdatacontainersettings.server.cpp(728)\Windows.Storage.ApplicationData.dll!00007FFC290A4FDD: (caller: 00007FFC290A42B8) ReturnHr(2) tid(2d30) 80070057 The parameter is incorrect.
    Msg:[WriteStateContainerValue LastSyncTime 39] 
onecoreuap\base\appmodel\statemanager\winrt\lib\windows.storage.applicationdatacontainersettings.server.cpp(412)\Windows.Storage.ApplicationData.dll!00007FFC290A4324: (caller: 00007FFB238551C8) ReturnHr(3) tid(2d30) 80070057 The parameter is incorrect.
    Msg:[InternalInsertValue LastSyncTime] 
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll

```
This documentation needs to be revisited with an accurate description of what is supported.

**Comment by knightmeister** [comment]
Last comment.

https://docs.microsoft.com/en-us/windows/win32/winrt/base-data-types

[This page](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localsettings?view=winrt-22000#windows-storage-applicationdata-localsettings) says the above data types are supported

>The Windows Runtime data types are supported for app settings.

**Comment by QuinnRadich** [comment]
This page isn't... exactly an API documentation page, more of a introductory walkthrough to the concept. The intent is that users can explore the linked API docs on each individual method to gain a better understanding of the individual bits and pieces.

That being said, I think you are right that this page needs a direct link to the list of supported basic data types, which I'm adding in.
