### ISSUE TITLE
The name 'GetProducts' does not exist in the current context.

### ISSUE THREAD

**Issue by RichardWR12** [MicrosoftDocs/windows-uwp#3645]
Hello, 

I followed all the steps mentioned in this guide, even added and updated some code passages which were not mentioned.
Eventually I ended up with the following message when debugging:
"The name 'GetProducts' does not exist in the current context."
How can I solve that problem?

Kind Regards 
Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92140a3c-b33d-6aa7-a904-d03c8122fbdf
* Version Independent ID: 90a33ee7-ec4a-2bcc-b776-530a1c3014fd
* Content: [Use a SQL Server database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases)
* Content Source: [windows-apps-src/data-access/sql-server-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sql-server-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by alvinashcraft** [comment]
Hello! Thanks for reaching out about the issue you're having with this walkthrough. Where did you create the GetProducts method in your project? The [Retrieve Products](https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases#retrieve-products-from-the-sql-server-database) section of the article doesn't explicitly state where to create the method. I believe that to work property, GetProducts() should be placed in the MainPage.xaml.cs code file.

Please let me know if this resolves your problem. If it does, I will update that section in the walkthrough.

**Comment by alvinashcraft** [comment]
The changes to make this walkthrough more clear have been committed and the updated page should be available later today. Please reach out if you have any questions or issues. Thanks for your contribution!
