### ISSUE TITLE
Love the Tool but please request to fix the windows bug!

### ISSUE THREAD

**Issue by abubkurian** [MicrosoftDocs/windows-uwp#3651]
Ok so the tool works as expected but once the keyboard manager is enabled and setup for say a shortcut, that's it, the trackpad gestures for three finger and four finger taps gets disabled. I don't know how on earth that happens. Swipes are fine, I am so glad two finger taps work, but it's annoying that windows forces their stupid alt+F4 shortcut or if you change it the trackpad doesn't work anymore.
I don't know if Powertoy can fix this issue, because I had similar problem when I use AutoHotKey also. Also this happens in windows 11 only I think. AHK was fine in windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by franky920920** [comment]
This is the repository for the docs. For the product itself, please file your issue [here](https://github.com/microsoft/PowerToys/issues/new/choose) in the Microsoft/PowerToys repo.

**Comment by mattwojo** [comment]
Thanks for filing @abubkurian, but echoing franky920920, it would be better to file this issue in the PowerToys product repo at:   https://github.com/microsoft/PowerToys/issues/

They can let you know whether there are ways to address the alt+F4 shortcut or trackpad issues with PowerToys or determine whether there should be any sort of update to the tool or request to update the OS.
