### ISSUE TITLE
URL for adaptive layout tutorial in UWP is 404

### ISSUE THREAD

**Issue by JustAPhrog** [MicrosoftDocs/windows-uwp#3652]
I've found that link for [adaptive layout tutorial](https://docs.microsoft.com/en-us/windows/apps/design/basics/xaml-basics-adaptive-layout) is not working - page is 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cdac50-e6d8-f11f-e1d7-efbf1ca83f4f
* Version Independent ID: 1f68766f-de08-460d-0b2e-396318967816
* Content: [Learning track - Construct and configure a form - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/construct-form-learning-track#feedback)
* Content Source: [windows-apps-src/get-started/construct-form-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/construct-form-learning-track.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
I've gone ahead and removed this link from the learning track, as the content no longer exists in its original form. Thanks for bringing this issue to our attention.
