### ISSUE TITLE
VB code?

### ISSUE THREAD

**Issue by HeraldOfOmega** [MicrosoftDocs/windows-uwp#3653]
So where is all the VB sample code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae136ba2-802e-2a6b-5a97-90dd6738a1b0
* Version Independent ID: edb07b26-18bc-651f-ca82-ea00137abc7b
* Content: [Title bar customization - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/title-bar#simple-color-customization)
* Content Source: [hub/apps/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/title-bar.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Hi - Unfortunately VB is not where we have decided to allocate our resources at this time. We're focusing on C#, and WinRT/C++ at the present.
