### ISSUE TITLE
Typo in Introduction to C++/WinRT page

### ISSUE THREAD

**Issue by Syul968** [MicrosoftDocs/windows-uwp#3659]
Dup "the" in sentence:
> to use the the Windows namespaces headers mentioned above, [...]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8af8fb2-9234-d647-a68a-c7e1b3cc51d9
* Version Independent ID: 052b6e7e-0d39-a713-a481-d721ef9bc59d
* Content: [Introduction to C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Syul968. I found 17 other instances of "the the" across the same repo. I've fixed them all in my current branch, I'll be merging that tomorrow, so all these fixes will be live very soon.

-Steve
