### ISSUE TITLE
link to HoloLens specific APIs on this page would help navigation

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/windows-uwp#366]
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-hololens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deaa22ed-9e69-2068-1793-8417d40a4f7c
* Version Independent ID: 34296d5a-4c99-2d82-4be8-0a398e79ec74
* Content: [Device Portal for HoloLens - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-hololens)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-hololens.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-hololens.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Thanks for the feedback, StephenHodgson,
I've added a link in the See also section of the doc in question.
