### ISSUE TITLE
'adaptive layout tutorial' link is daed.

### ISSUE THREAD

**Issue by umbria** [MicrosoftDocs/windows-uwp#3662]
[Enter feedback here]
The link below is dead.
This is not a tutorial. If you want one, see our [adaptive layout tutorial](https://docs.microsoft.com/en-
us/windows/apps/design/basics/xaml-basics-adaptive-layout)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cdac50-e6d8-f11f-e1d7-efbf1ca83f4f
* Version Independent ID: 1f68766f-de08-460d-0b2e-396318967816
* Content: [Learning track - Construct and configure a form - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/construct-form-learning-track)
* Content Source: [windows-apps-src/get-started/construct-form-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/construct-form-learning-track.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
I've gone ahead and removed this link from the learning track, as the content no longer exists in its original form. Thanks for bringing this issue to our attention.
