### ISSUE TITLE
Deadlink in new windowing doc

### ISSUE THREAD

**Issue by roxk** [MicrosoftDocs/windows-uwp#3666]
https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/develop/title-bar.md has a link to WASDK windowing migration, and the link https://docs.microsoft.com/en-us/windows-app-sdk/migrate-to-windows-app-sdk/guides/windowing.md returns 400.

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The link is fixed now.
