### ISSUE TITLE
STAThreadAttribute doesn't work for aync Main in the demo code and use .GetAwaiter().GetResult() to replace the async function.

### ISSUE THREAD

**Issue by imechZhangLY** [MicrosoftDocs/windows-uwp#3667]
In the demo code, `[global::System.STAThreadAttribute]` is ignored, and running `Thread.CurrentThread.GetApartmentState()` returns `MTA` in the async main function. I think the demo code should use `.GetAwaiter().GetResult()` to replace `async Task<int> Main(string[] args)`.
```
#if DISABLE_XAML_GENERATED_MAIN
public static class Program
{
    [global::System.Runtime.InteropServices.DllImport("Microsoft.ui.xaml.dll")]
    private static extern void XamlCheckProcessRequirements();

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler", " 1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.STAThreadAttribute]
    // Replaces the standard App.g.i.cs.
    // We must declare Main to be async, as we want to await 
    // another async function call.
    static int Main(string[] args)
    {
        XamlCheckProcessRequirements();

        global::WinRT.ComWrappersSupport.InitializeComWrappers();

        bool this_is_the_first_instance = true;

        // If this is the first instance launched, then register it as the "main" instance.
        // If this isn't the first instance launched, then "main" will already be registered,
        // so retrieve it.
        var mainInstance = Microsoft.Windows.AppLifecycle.AppInstance.FindOrRegisterForKey("main");

        // If the instance that's executing the OnLaunched handler right now
        // isn't the "main" instance.
        if (!mainInstance.IsCurrent)
        {
            this_is_the_first_instance = false;

            // Redirect the activation (and args) to the "main" instance, and exit.
            var activatedEventArgs =
                Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs();
            mainInstance.RedirectActivationToAsync(activatedEventArgs)..GetAwaiter().GetResult();
        }

        if (this_is_the_first_instance)
        {
            global::Microsoft.UI.Xaml.Application.Start((p) =>
            {
                var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
                global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
                new App();
            });
        }

        return 0;
    }
}
#endif
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c675e4ec-a22b-c54d-e1d6-1eaa408180b9
* Version Independent ID: c675e4ec-a22b-c54d-e1d6-1eaa408180b9
* Content: [Application lifecycle functionality migration - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @imechZhangLY. Yes, the code example here had gotten out of sync with the original sample app, which is here: https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/Samples/AppLifecycle/Instancing/cs-winui-packaged/CsWinUiDesktopInstancing/CsWinUiDesktopInstancing/Program.cs.

So I fixed that and now they're in sync.

The code still uses [STAThread] on main, though (and it does work now that main is no longer async).

Thanks!
-Steve
