### ISSUE TITLE
What's the Microsoft Store URL to use when adding this app to Intune?

### ISSUE THREAD

**Issue by SebMcCayen** [MicrosoftDocs/windows-uwp#3668]
Hi,

I'm trying to add this as an "Microsoft Store App" in Intune but I can't manage to find the Appstore URL.
I can only find the aka.ms/installpowertoys and aka.ms/getPowertoys-URL so far.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-gb/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @SebMcCayen - I'm going to point you to the PowerToys repo to file this issue. > https://github.com/microsoft/PowerToys/issues
That's where the community of developers who work on PT are most active and likely to have the best answer for you. This repo is just for documentation updates.
