### ISSUE TITLE
Two broken links under "Win32 Platform" in document "Speech, voice, and conversation in Windows 11 and Windows 10"

### ISSUE THREAD

**Issue by dargilco** [MicrosoftDocs/windows-uwp#3669]
The two links under "Win32 Platform" are broken:

[Microsoft Speech Platform - Software Development Kit (SDK) (Version 11)](https://www.microsoft.com/download/details.aspx?id=27226)

[Microsoft Speech SDK, version 5.1](https://www.microsoft.com/download/details.aspx?id=10121)

Thanks,

Darren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5532269-6b52-2288-ddf1-8c2e8d52e2db
* Version Independent ID: 9106566d-48f5-25fa-67d6-978ac385dff9
* Content: [Speech, voice, and conversation in Windows 11 and Windows 10 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/develop/speech)
* Content Source: [hub/apps/develop/speech.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/develop/speech.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @dargilco. The downloads have been reinstated and links should work again.
