### ISSUE TITLE
How to specify Arguments with ampersand?

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/windows-uwp#3671]
I got this:
```
System.Reflection.MissingRuntimeArtifactException: 
'Cannot retrieve a MethodInfo for this delegate because the method it targeted 
(System.ServiceModel.Syndication.SyndicationFeedFormatter.DefaultUriParser(XmlUriData, Uri&)) 
was not enabled for metadata using the Dynamic attribute.
 For more information, please visit http://go.microsoft.com/fwlink/?LinkID=616868'
```

So I put this (into rd.xml):
```
	<Type Name="System.ServiceModel.Syndication.SyndicationFeedFormatter">
	<MethodInstantiation Name="DefaultUriParser" Arguments="XmlUriData, Uri&amp;" Dynamic="Required" />
	</Type>
```

 But it ends with:
```
xxx\My Project\Default.rd.xml(28): warning : ILTransform : warning ILT0027: Unparsed text in generic arguments 'XmlUriData, Uri&'.
```

How I should write this?
(runtime error occurs only in Release compilation, not Debug).

I would not open this Issue for my own problem; I just think that this documentation page should have information how to represent arguments like this (general info).

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f49cf8b-4877-3e00-1b29-9f6e43b9a460
* Version Independent ID: a4ce4164-c7f3-ecd5-7000-b8aa5f386b97
* Content: [&lt;MethodInstantiation&gt; Element (.NET Native) - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/methodinstantiation-element-net-native)
* Content Source: [windows-apps-src/dotnet-native/methodinstantiation-element-net-native.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/dotnet-native/methodinstantiation-element-net-native.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @pkar70! I'm investigating this, and I'll get back to you when I have some info.

-Steve

**Comment by pkar70** [comment]
By the way, why System.Reflection.MissingRuntimeArtifactException doesn't simply print exact lines to be added to *.rd.xml...

**Comment by stevewhims** [comment]
Hi, @pkar70. I've added info to the [Remarks](https://docs.microsoft.com/windows/uwp/dotnet-native/methodinstantiation-element-net-native#remarks) section of this topic that should answer your question. Specifically, it details how to use the MissingMetadataException troubleshooter. I suspect that the MissingMetadataException troubleshooter exists so that the exception doesn't need to include the exact details.

Thanks!
Steve

**Comment by pkar70** [comment]
Troubleshooter says `Arguments="Uri uri&"` - but ILTransform says that this is wrong. Changing it to &amp; also doesn't help.
