### ISSUE TITLE
Modern Notification Abuse

### ISSUE THREAD

**Issue by ListsOfArrays** [MicrosoftDocs/windows-uwp#3675]
The [Notifications (Design basics)](https://docs.microsoft.com/en-us/windows/win32/uxguide/mess-notif) has much-needed examples on how to not do notifications. Please bring back most of the content from the 32 guidelines to the UWP guidelines in order to inform developers on what not to do.

Advertising using notifications (_cough cough_ the Suggestions app does this by default) should be a big-no-no on the Toast UX Guidance page.
The "Notifications Hall of Shame" would help future developers on Windows 11 to know not to do these things. I think the Suggestions team thinks they're being helpful by using notifications... but this type of usage should be discouraged or outright banned for internal MSFT projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247f926a-204f-f054-f78b-7310bbd2ab15
* Version Independent ID: ec286242-7c1e-a1a0-341e-15a78c6a57b7
* Content: [Toast UX Guidance - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-ux-guidance)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/toast-ux-guidance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/toast-ux-guidance.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
