### ISSUE TITLE
Forwarding references and reference collapsing 

### ISSUE THREAD

**Issue by jannarc** [MicrosoftDocs/windows-uwp#3676]
I think there might be a mistake in "Forwarding references" section on this page. 

> Passing an rvalue causes the forwarding reference to become _Ty&& &&, which collapses to the rvalue reference _Ty&&.

A rvalue will be deduced as a non-reference type hence reference collapsing shouldn't occur in this case.

From _Effective Modern C++_ (page 197): 

> When an lvalue is passed as an argument, T is deduced to be an lvalue reference. When an rvalue is passed, T is deduced to be a non-reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339317c-7463-d28c-c34e-b1f20791bcdf
* Version Independent ID: acb6ecae-3986-b31a-53f5-875367c2f855
* Content: [Value categories, and references to them - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/cpp-value-categories)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/cpp-value-categories.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/cpp-value-categories.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @jannarc. I've published a change to that effect.

-Steve
