### ISSUE TITLE
Error: The Amazon Appstore is not currently available in your country.

### ISSUE THREAD

**Issue by iwalker2000** [MicrosoftDocs/windows-uwp#3679]
[Enter feedback here]
There is no any mention about Amazon Appstore is still locked for US region users only (as it was on previous version on this page). Really disappointed with this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for pointing this out @iwalker2000. I added a note about it back into this doc: https://github.com/MicrosoftDocs/windows-uwp/commit/ccee6e62c1ff0058dab09cf6ad7b37c8b72dd488

Hopefully the supported regions for running WSA will expand soon as the feature continues to be developed.
