### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by VagueGit** [MicrosoftDocs/windows-uwp#368]
It's important to know how current documentation is. Does Microsoft globalize date formats in docs? Was this document produced on 8 February, as Americans understand dates, or on 2 August as Everyone in the Whole World Except Americans  understands dates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458ed4d-a3d3-77d2-0b67-d692734e9604
* Version Independent ID: acd1f086-3d42-fc03-3836-d537efa7e082
* Content: [Printing and scanning - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/printing-and-scanning)
* Content Source: [windows-apps-src/devices-sensors/printing-and-scanning.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/printing-and-scanning.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Hi VagueGit,
We do globalize the date formats as they appear on the docs.microsoft.com frontend (so you should see the standard format for your locale), but in the content files themselves we enter the dates in month/day/year format.
