### ISSUE TITLE
this doesn't work at all with VS2022

### ISSUE THREAD

**Issue by TommyNorthAL** [MicrosoftDocs/windows-uwp#3680]
this is what is in MainPage.xaml to start:
<Page
    x:Class="HelloWorldCppWinRT.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:HelloWorldCppWinRT"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>

    </Grid>
</Page>
if you paste in the text given in step 1 to create the form, it just blurs with errors.
Doesn't recognize any of the symbols.
I followed the instructions to create the project, I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed62e90-9a85-e295-69ac-7af08123e024
* Version Independent ID: b740841d-6530-d774-0f68-dcd356f9adb5
* Content: [Create a 'Hello, World!' app using C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cppwinrt)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cppwinrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cppwinrt.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @TommyNorthAL - The MainPage.xaml file created in a new Blank App (C++/WinRT) template project, does not contain a <grid> element. Looks like you might've missed a step or two.

Make sure you've got your dev environment set up correctly and follow the steps as outlined.

Here's the initial code you should see for which step one asks you to replace the <stackpanel></stackpanel> element:

<Page
    x:Class="HelloWorldCppWinRT.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:HelloWorldCppWinRT"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="ClickHandler">Click Me</Button>
    </StackPanel>
</Page>
