### ISSUE TITLE
Not open source

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#3683]
This page incorrectly claims that WinUI 3 is open source. It is not, and there are currently no official plans to open source it (those plans were retracted)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [Windows UI Library (WinUI) 3 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Various references revised for clarity and grammar.
