### ISSUE TITLE
SharpDX is deprecated.  This dependency needs to be removed. 

### ISSUE THREAD

**Issue by fengfranklu** [MicrosoftDocs/windows-uwp#3687]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 971295ef-cd07-fd9c-e5df-2c6e0e4c25fc
* Version Independent ID: c1d6f2f7-f971-3bd4-8fb7-f30d113a752f
* Content: [Screen capture to video - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture-video)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture-video.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture-video.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your comment. I reached out to the GraphicsCapture feature team about this issue and their position on this is that the SharpDX library, while deprecated, is just a wrapper around DirectX APIs that aren't changing, so it's a stable solution even though the library is no longer supported. Also, they have found that while there are other libraries that can be used for capturing video with GraphicsCapture, those libraries do not perform as well as SharpDX. So, for now, the plan is to continue to recommend this as the best solution for UWP apps. The guidance for this scenario will likely be updated in the future for apps built with the Windows App SDK.
