### ISSUE TITLE
Preview Pane shrinks after clicking on certain pdf's

### ISSUE THREAD

**Issue by BobTryber** [MicrosoftDocs/windows-uwp#3689]
Certain PDF's, e.g. those that are secured from changing / saving in adobe, if clicked on in file explorer (not even opened) will cause any other PDFs after that first previous click to be shown shrunk down to approximately 1 inch by 2 inches in upper left corner of preview area, with scroll bars for scrolling left-right or up-down.  The only way to get the full size preview back is to close the file explorer window and reopen another file explorer window, and now the non-secure files show full size again until a secure PDF is clicked on again.  Note, other files like word documents still show full size.  Also, any other file explore windows still show normal size PDF previews.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [PowerToys File Explorer add-ons utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing @BobTryber. This sounds more like a bug with the actual File Explorer feature on PowerToys than an update to the docs. I'm going to close the issue here and ask that you file it in the PowerToys product repo at: https://github.com/microsoft/PowerToys/issues

Thanks for bringing this to awareness!
