### ISSUE TITLE
Can you explain how does "first WinUI 3 project" works?

### ISSUE THREAD

**Issue by vermahim** [MicrosoftDocs/windows-uwp#3690]
[Enter feedback here]
I want to start building desktop apps. I tried reading (and re-reading) the docs. But it was a complete waste of time.  
I could not find any explanation of how does the "first WinUI 3 project" works. What is the program's entry point? What are the main APIs? Which API is responsible for the button, window, etc.?

Are there any video tutorials about a hello world WinUI 3 app in c++ ? 

I tried downloading the sample also, but it doesn't compile :(
Very bad experience. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 project - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by stevewhims** [comment]
Hi, @vermahim, and thanks for filing this issue. I've added a new section to the topic ("A look at the code in the project template"). Does that cover the things you're interested in?

I don't have a video of a "Hello, World!" C++/WinRT WinUI 3 app. But this topic is essentially that.

Was it a sample app that you downloaded that didn't compile? If you could get me the url of that sample app, then I can investigate. Or do you mean that you followed along with this tutorial and it didn't work?

Thanks again!
-Steve
