### ISSUE TITLE
Unpackaged winappsdk app needs supportedOS 

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3691]
We should document the fusion manifest requirements for unpackaged winappsdk apps. Currently if you don't add a supportedOS entry, you get win8 behavior (and app will later crash trying in some switchbranch code)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a490a57-1f12-5646-2906-dca6ead89518
* Version Independent ID: 7ea6aaad-bf8d-2a2e-3012-11e8e2ebe917
* Content: [Advanced tutorial - Build and deploy an unpackaged app that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=cpp)
* Content Source: [hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by asklar** [comment]
The required snippet (inside the `assembly` element) is:
```xml
	<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
		<application>
			<!--This Id value indicates the application supports Windows 10 functionality -->
			<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
		</application>
	</compatibility>
```

**Comment by stevewhims** [comment]
Investigating.

**Comment by stevewhims** [comment]
Sorry for the delay in getting back to this! I've added the new section [Declare OS compatibility in your application manifest](https://docs.microsoft.com/windows/apps/windows-app-sdk/use-windows-app-sdk-run-time#declare-os-compatibility-in-your-application-manifest). You can get to that topic from the other related topics that I know of, so anyone following links and reading around the subject will find this info.

**Comment by asklar** [comment]
thanks @stevewhims!
