### ISSUE TITLE
MddBootstrapInitialize docs should talk about the installer

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3692]
I could find a way to file feedback for the api page but:

The documentation for MddBootstrapInitialize ([link](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/win32/mddbootstrap/nf-mddbootstrap-mddbootstrapinitialize)) does not mention the DDLM package or link to the prerequisite / installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26da09-9179-baaf-aed1-7517970e2c55
* Version Independent ID: 5bd80518-4de2-e7f0-d17a-678acae32aa6
* Content: [Reference the Windows App SDK framework package at run time - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/reference-framework-package-run-time)
* Content Source: [hub/apps/windows-app-sdk/reference-framework-package-run-time.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/reference-framework-package-run-time.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
I have a change on its way out to the live site (and you have another PR pending, with conflicts against my change), so I'll go ahead and close this.

Thanks!
Steve
