### ISSUE TITLE
Add section on mouse pointer crosshair.

### ISSUE THREAD

**Issue by debater-coder** [MicrosoftDocs/windows-uwp#3693]
Add section on mouse pointer crosshair.
![image](https://user-images.githubusercontent.com/52619668/155954496-3d8ebc20-20c4-4ecb-bb6e-5ef6379f9b06.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba175f26-82e2-2f00-7562-924faa57c143
* Version Independent ID: ba175f26-82e2-2f00-7562-924faa57c143
* Content: [PowerToys Mouse utilities for Windows](https://docs.microsoft.com/en-us/windows/powertoys/mouse-utilities)
* Content Source: [hub/powertoys/mouse-utilities.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/mouse-utilities.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@debater-coder - It looks like this work is represented in https://github.com/MicrosoftDocs/windows-uwp/pull/3775

**Comment by crutkas** [comment]
Matt is correct, https://github.com/MicrosoftDocs/windows-uwp/pull/3775/files#diff-969cf00d9d5d46afed501571e0d21bddb5175ee611ce621a56ce2dbc41af84dbR41 has the section

we are also tracking this via https://github.com/microsoft/PowerToys/issues/17268.  I do believe we can close this as PT repository is tracking the issue

**Comment by crutkas** [comment]
Actually, i was incorrect on this, looks like the PR is missing cross hair, we are still tracking this on our end
