### ISSUE TITLE
PowerRename with Ctrl+Alt+(Num)

### ISSUE THREAD

**Issue by M1812M** [MicrosoftDocs/windows-uwp#3698]
In the PowerRename window I am not able to put in the letter "\" on my german keyboard layout. Non of the Ctrl+Alt+(Number) combinations are working. But Ctrl+Alt+E -> "€" is working.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://docs.microsoft.com/en-au/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
This issue should be in the PowerToys repository. Please search there for issues that already exist and deal with the same thing. (there are many) If there are none, then you can create a new issue. Please share as much relevant info as possible then.

**Comment by Jay-o-Way** [comment]
Looks like https://github.com/microsoft/PowerToys/issues/14099

**Comment by mattwojo** [comment]
Closing this out as Jay points out the issue already exists in the product repo. That's the best place for this to be addressed. Thanks for filing!
