### ISSUE TITLE
Clarify how to list available updates

### ISSUE THREAD

**Issue by mmangelsdorf** [MicrosoftDocs/windows-uwp#3700]
Add a hint to the _List with update_ section that it's possible to list all available updates with `winget upgrade` (without any arguments).

Proposed text:

> If you want to list all apps with available updates use `winget upgrade` (without any arguments).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcd2ee1-04fd-c7be-adee-72faa345ebb7
* Version Independent ID: a44a4676-c56a-712a-eba2-11e5335c6764
* Content: [list Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/list)
* Content Source: [hub/package-manager/winget/list.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/list.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Great recommendation - I'll get it added. Thanks @Merlin2001 !

**Comment by mattwojo** [comment]
Added your note recommendation. https://github.com/MicrosoftDocs/windows-uwp-pr/pull/2439
Thank you for the contribution Merlin2001!
