### ISSUE TITLE
WinGet installation instruction is broken

### ISSUE THREAD

**Issue by slonopotamus** [MicrosoftDocs/windows-uwp#3706]
Docs say that I should install App Installer from Microsoft Store if I'm using Windows older than 11. I'm using Windows 10 21H2.

However, Microsoft Store page for App Installer is missing install button:

![image](https://user-images.githubusercontent.com/92637/157303719-abdfec30-aedc-4204-a0b7-29162e8a79af.png)

So, I don't understand how I am supposed to install App Installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-us/windows/package-manager/winget/#install-winget)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Hey @slonopotamus - Are you sure that you don't already have the App Installer? Usually this is why the 'Get' button wouldn't show up. Could you try opening PowerShell and entering: winget --version to see whether it may already be there?

**Comment by mattwojo** [comment]
You can also check to see if you have App Installer by opening PowerShell and entering:
`Get-AppxPackage microsoft.desktopappinstaller`
You will see "Status: OK" at the bottom if you have it as well as a version # for App Installer... the version # should be greater than 1.11.11451. If it's not, following the instructions here: https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting#executing-winget-doesnt-display-help

**Comment by slonopotamus** [comment]
> Hey @slonopotamus - Are you sure that you don't already have the App Installer? Usually this is why the 'Get' button wouldn't show up. Could you try opening PowerShell and entering: winget --version to see whether it may already be there?

Yes, it turned out that

1. App Installer is already installed (it looks like that it comes pre-installed in modern Windows 10 builds?)
2. I cannot even uninstall it through Microsoft Store

![image](https://user-images.githubusercontent.com/92637/161701063-4c2ff8b1-54bc-4344-991b-cc1d263a5c19.png)


Anyway, this isn't documented and Microsoft Store UI is extremely unhelpful. It could clearly state on app page that app is already installed.

UPD: I've checked several random Windows 10 PCs nearby (including my employer's and personal devices of my family members). All of them already have App Installer in the same state. It is pre-installed, cannot be removed and Microsoft Store page is missing "install" button.

**Comment by mattwojo** [comment]
I'll make an update to that winget install page to try to make this a bit more clear. Yes, from what I understand App Installer is included with all modern Windows 10 builds (but may not have been in some early builds). I don't have the ability to update the Store description, but will try to find the right person and shoot them a mail to see if they could add that App Installer is typically included in Windows by default to the description.

**Comment by mattwojo** [comment]
Update was included in: https://github.com/MicrosoftDocs/windows-uwp/commit/5688dbd2ab20808c6e181932f9874b8c51606b69

Closing this out. Please reopen if you feel that the docs need any further clarification. Thanks for the contribution and bringing this to our attention!
