### ISSUE TITLE
Error. This app will not work on your device.

### ISSUE THREAD

**Issue by alexanderdp** [MicrosoftDocs/windows-uwp#3707]
Regards to: "Windows Subsystem for Android" and "Amazon Appstore for Windows"

My computer meets and exceeds all minimum and recommended requirements (HP, Intel i7 x64, 16gb ram, 1tb SSD). My computer has Hyper-V, Virtual Machine Platform and Windows Hypervisor Platform installed and enabled. It has been added to the Windows Insider program. Windows 11 (Win 11 Pro 21H2 version 22000.527 with feature experience pack 1000.22000.527.0) and the Windows Store (version 22202.1402.2.0) are updated. and  It has been rebooted/restarted (turned it off and on). The power cord is connected and it has internet access. I am located in Florida.

The only thing that pops up from time to time in the "Required items" is: "Notes: Only available to Windows 11 Customers in the US".
This comes and goes depending on the reboot, but the error (This app will not work on your device.) is always the same/present.

This error has impleaded the install for over 2 weeks. 

Any thoughts?

**Comment by mattwojo** [comment]
@hamza-usmani -- Do you have any suggestions?

**Comment by dpaulino** [comment]
Hi @alexanderdp I'm an engineer on the Microsoft Store team. Would be great to get a feedback hub report from you regarding this issue. Can you do the following:
- Launch feedback hub and report a new issue
- Add an appropriate title, and in the description list out your exact reproduction steps (e.g. open store > go to amazon appstore page > scroll down view requirements... etc)
- Direct the report to Microsoft Store > other issues
- For the "Add more details" section, can you please click "Recreate my problem", start the recording, then repeat the exact steps that you listed in the description. 
- Submit the feedback
- After submission, please reply back with the share URL for your report. 

Thanks!

**Comment by mattwojo** [comment]
Sounds like this issue does not require an update to the documentation and has been transitioned to Feedback Hub, so I'm closing it out. If I'm mistaken and there is an update needed to the WSA doc, please feel welcome to reopen. 
Thanks for contributing and bringing this to awareness!
