### ISSUE TITLE
Sandbox environment

### ISSUE THREAD

**Issue by 4026** [MicrosoftDocs/windows-uwp#371]
Is there a sandbox environment available for this API with which we can make free purchases in our app and test our integration of querying and fulfilling them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bdee9e-2095-4423-62c5-0beb5520dfd3
* Version Independent ID: fad19d6f-2fa3-ff54-925a-020fe65cadbc
* Content: [Manage product entitlements from a service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Unfortunately, there is currently no sandbox available for this purpose. The engineering team is aware of this feature request.
