### ISSUE TITLE
WebManagement.exe not found in Windows 11

### ISSUE THREAD

**Issue by MacDknife** [MicrosoftDocs/windows-uwp#3711]
Hi!
This page most probably works fine for Windows 10, but when I try to use this in Windows 11, I find that when I get to using the "WebManagement.exe" service instructions, the "WebManagement.exe" does not seem to exist in Windows 11. I cannot locate a corresponding service either...
: P
/Errol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c07ba9-8f4f-c051-c945-16742c7fe409
* Version Independent ID: 61c4da19-8278-4764-05a4-000653932b83
* Content: [Provision Windows Device Portal with a custom SSL certificate - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-ssl)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-ssl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-ssl.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
You must run from an elevated command prompt. Run webmanagement.exe /help to get in-context help.

WebManagement.exe is located in a not identifiable folder and is a Windows core system file. The program is not visible.

You can also find the service listed in Task Manager, under the "Services" tab.

**Comment by MacDknife** [comment]
Sorry, no go in Windows 11:

 



 

: P

/Errol

 

 

 

 

Från: KB ***@***.***> 
Skickat: den 25 mars 2022 18:13
Till: MicrosoftDocs/windows-uwp ***@***.***>
Kopia: Errol Jacoby ***@***.***>; Author ***@***.***>
Ämne: Re: [MicrosoftDocs/windows-uwp] WebManagement.exe not found in Windows 11 (Issue #3711)

 

You must run from an elevated command prompt. Run webmanagement.exe /help to get in-context help.

WebManagement.exe is located in a not identifiable folder and is a Windows core system file. The program is not visible.

You can also find the service listed in Task Manager, under the "Services" tab.

**Comment by MacDknife** [comment]
I just realised now that I had sent an image of trying the command in PowerShell/Terminal, but I get the same result in CMD:



 

Sorry!

: P

/Errol

 

Från: KB ***@***.***> 
Skickat: den 25 mars 2022 18:13
Till: MicrosoftDocs/windows-uwp ***@***.***>
Kopia: Errol Jacoby ***@***.***>; Author ***@***.***>
Ämne: Re: [MicrosoftDocs/windows-uwp] WebManagement.exe not found in Windows 11 (Issue #3711)

 

You must run from an elevated command prompt. Run webmanagement.exe /help to get in-context help.

WebManagement.exe is located in a not identifiable folder and is a Windows core system file. The program is not visible.

You can also find the service listed in Task Manager, under the "Services" tab.
