### ISSUE TITLE
Documentation details

### ISSUE THREAD

**Issue by KryptykHermit** [MicrosoftDocs/windows-uwp#3713]
I love the product and was looking to use Awake to keep machines active during imaging, as our Dell machines go to sleep even when we disable modern stand-by.  I had some questions/concerns about Awake specifically when using the CLI as the documentation is (in my opinion) lacking detail.

There is reference to a **_settings.json_** file but no information on how to create it, where the file is located if created by the app, or what the contents of the file should/could look like.

I enabled the options via the GUI and then looked in %APPDATA% (Roaming and Local) and the Program Files\PowerToys folder for this file and did not see it.

The other smaller issue is it would be nice to have an example of the CLI command line switched in place.
Do I use **_--display-on=true_** or **_--display-on true_** or **_--display-on:true_**?
An example would really help clear the air on how to use the CLI, and maybe a settings.json file example to with it.

Thank you for the great utilities, your time working on them, and your time reading this!  Respect the work!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20e555a-65ad-82e7-e1c0-f6577c1322b2
* Version Independent ID: 29236a0e-82e8-92d7-a5fb-12a9a777bcc2
* Content: [PowerToys Awake utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/awake)
* Content Source: [hub/powertoys/awake.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/awake.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by crutkas** [comment]
@KryptykHermit All three arg syntaxes are value actually ;)  I just validated quickly via the app itself

settings.json is aimed only at the powertoys settings app.  It is generated by it and lives in your appdata PowerToys folder. You could MDM deploy said file as well if you wanted to for other's machines.  

C:\Users\crutkas\AppData\Local\Microsoft\PowerToys\Awake\settings.json is the the location

**Comment by mattwojo** [comment]
Thanks for filing @KryptykHermit and @crutkas for validating the syntax and addressing the question. Currently it seems that this does not require a docs update, so I'm going to close the issue, but please feel welcome to re-open if this is not the case and let me know what sort of update would be helpful.
