### ISSUE TITLE
Please document WindowsAppSdkBootstrapInitialize opt out project property

### ISSUE THREAD

**Issue by Scottj1s** [MicrosoftDocs/windows-uwp#3714]
[Enter feedback here]
Can we also document the WindowsAppSdkBootstrapInitialize project property, which can be defined to opt out of the module initialization logic that is otherwise provided for calling the bootstrap initialization function:
https://github.com/microsoft/WindowsAppSDK/search?q=WindowsAppSdkBootstrapInitialize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb26da09-9179-baaf-aed1-7517970e2c55
* Version Independent ID: 5bd80518-4de2-e7f0-d17a-678acae32aa6
* Content: [Reference the Windows App SDK framework package at run time - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/reference-framework-package-run-time)
* Content Source: [hub/apps/windows-app-sdk/reference-framework-package-run-time.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/reference-framework-package-run-time.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
It looks like that info should go in "Behind the scenes". I've put it there, but let me know if it should go elsewhere.
