### ISSUE TITLE
Toast Example Step #1 Doesn't Work

### ISSUE THREAD

**Issue by BPowell76** [MicrosoftDocs/windows-uwp#3715]
With NuGet Windows.Toolkit.Uwp.Notifications version 7.1.2 and a target framework of net6.0-windows, Show() is not available in the ToastContentBuilder class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11bc1ceb-510e-22c9-1f7a-a421ae52901b
* Version Independent ID: 0efae90c-e517-b54d-8e81-ebbd69d2270d
* Content: [Send a local toast notification from C# apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/send-local-toast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/send-local-toast.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jeremiahjordanisaacson** [comment]
Agreed. It's broken.

When you fix it, please make sure to test it on Linux and Mac OS.

**Comment by rgwood** [comment]
I think this is covered by the comment:

`// Not seeing the Show() method? Make sure you have version 7.0, and if you're using .NET 6 (or later), then your TFM must be net6.0-windows10.0.17763.0 or greater`

You need to be targeting a Windows TFM of a specific version (`net6.0-windows10.0.17763.0` or greater).

**Comment by jeremiahjordanisaacson** [comment]
That wasn’t it either. Tried.

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
