### ISSUE TITLE
Clarify what is needed for single packaging

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#3718]
Doc currently says:

> Windows App SDK 0.8 and C# version of 1.0 Preview 3: You must install the single-project MSIX packaging tools extension separately.

Then with a list of VSIX installers. It sounds like if you're not on Preview 3 any longer, it isn't needed, but I'm finding it is. Could this phrasing be updated to be more clear around what is needed with VS2022 and WinAppSDK1.0 final?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0401c948-1dda-c819-ee88-902ac6fcbbd9
* Version Independent ID: c1748244-0f46-8dec-a88e-020f12d9a387
* Content: [Package your app using single-project MSIX - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp#provide-feedback)
* Content Source: [hub/apps/windows-app-sdk/single-project-msix.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/single-project-msix.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @dotMorten! I'll investigate.

-Steve

**Comment by stevewhims** [comment]
So, the single-project MSIX packaging tools are *always* needed if you want to work with single project solutions. The tools are usually bundled with the Windows App SDK VSIX. But the exception is if you're on the versions mentioned in the topic. In those cases you need to install the single-project MSIX packaging tools explicitly.

I've added this clarification to the topic.

Thanks!
-Steve

**Comment by dotMorten** [comment]
There is no windows app Sdk vsix any longer. Project templates ship with VS2022 now but doesn’t (for whatever reason) install the single project vsix.
And installing templates doesn’t mean you couldn’t just clone a sample and open it since the Sdk is shipped via nuget and not VS. single project packaged apps using v1.0.0 WILL fail to run without the extension
