### ISSUE TITLE
I think the Java Home Path is wrong

### ISSUE THREAD

**Issue by suleymancetiner81** [MicrosoftDocs/windows-uwp#3721]
I think the Java Home Path is wrong. The correct one is JAVA_HOME: C:\Program Files\Android\Android Studio\jre\bin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1a8b54-1913-1721-4a8d-2fd3ce3d300d
* Version Independent ID: e39706ca-3548-03e8-672f-9e7d5bff92ae
* Content: [React Native for Android development on Windows](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/react-native-for-android#feedback)
* Content Source: [hub/dev-environment/javascript/react-native-for-android.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/react-native-for-android.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by mattwojo** [comment]
Thank you @suleymancetiner81! Corrected! https://github.com/MicrosoftDocs/windows-uwp/commit/989a8a2dcfa1d61b304c313da1cc206400a90f08
