### ISSUE TITLE
Purchase order

### ISSUE THREAD

**Issue by 4026** [MicrosoftDocs/windows-uwp#373]
Can we rely on the list of items in the response being returned in any particular order? For instance, will the most recent purchases always be returned first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b95f043-9483-170e-3aef-fa675bfc0fb7
* Version Independent ID: 819f2b1e-a55b-7b05-bf54-111eed1a9916
* Content: [Query for products - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products)
* Content Source: [windows-apps-src/monetize/query-for-products.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/query-for-products.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
According to the engineering team that owns this service, no order is guaranteed in the response data. To determine the more recent purchases, you can use the acquiredDate field.
