### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by onadebi** [MicrosoftDocs/windows-uwp#3730]
[
"You will also to have an Android phone..."
This should be "You will also need to have an Android phone..."
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5835d670-bb0f-1f70-5ca3-118343cce487
* Version Independent ID: fd9788d6-6c38-cc25-7790-1095a1f46067
* Content: [Create Android app with Xamarin.Android](https://docs.microsoft.com/en-us/windows/android/xamarin-android)
* Content Source: [hub/android/xamarin-android.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/xamarin-android.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mattwojo** [comment]
Thanks @onadebi. Fixed: https://github.com/MicrosoftDocs/windows-uwp/commit/7125cebd6aad4e2f92d6c145eff0a3a30a6810e0

**Comment by onadebi** [comment]
> Thanks @onadebi. Fixed: [7125ceb](https://github.com/MicrosoftDocs/windows-uwp/commit/7125cebd6aad4e2f92d6c145eff0a3a30a6810e0)

You're welcome.
