### ISSUE TITLE
InjectedInputPenInfo.Pressure generates an input with a max pressure of only 0.25

### ISSUE THREAD

**Issue by HugoRomat** [MicrosoftDocs/windows-uwp#3734]
<Copy Pasting the following issue to reopen the topic, as after 2 years this is still no resolved: https://github.com/MicrosoftDocs/windows-uwp/issues/2106>

Setting the Windows.UI.Input.Preview.Injection.InjectedInputPenInfo.Pressure property to 1 generates a pen input with a pressure of 0.25. This value scales, so if Pressure is set to 0.5, the generated input will have a pressure of 0.125.

Setting Pressure above 1 seems to cause the InputInjector to stop generating inputs, so it's not possible to get generated pen input with pressure higher than 0.25 by setting the Pressure property greater than 1.

Additionally, the documentation for InjectedInputPenInfo.Pressure states:

The pen contact force exerted on the digitizer surface, normalized to a range between 0 and 1024. The default is 0.

However, this is not correct, as pressure does not take values greater than 1.

**Comment by alkeryn** [comment]
hey man, has this issue ever been fixed ?

**Comment by Karl-Bridge-Microsoft** [comment]
I've pinged my contacts on the feature team again. Waiting for a response...

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @HugoRomat  / @alkeryn - An OS bug has been filed and a fix is in the works for an upcoming release. 

As I mentioned in 2106, you could try (and maybe you did) the product feedback link at the bottom of the topic. I can only address doc issues.
