### ISSUE TITLE
Preview R markdown (Rmd) files?

### ISSUE THREAD

**Issue by stephendavidgregory** [MicrosoftDocs/windows-uwp#3735]
Hello. Thanks for the nice add-on. Is there any way or plan to extend the markdown viewer to view other types of Markdown files, such as R markdown files (https://rmarkdown.rstudio.com/)? Thanks, Stephen

**Comment by mattwojo** [comment]
@stephendavidgregory - Could you give us more context here in regard to what you're requesting? Is this in regard to the PowerToys File Explorer Add-ons? https://docs.microsoft.com/en-us/windows/powertoys/file-explorer

If so, please open this issue on the PowerToys product repo: https://github.com/microsoft/PowerToys/issues  They will be better able to field your question there.

I'm closing this issue, but if mistaken about the context for your issue, please feel welcome to reopen it!
