### ISSUE TITLE
Documentation referred to which no longer exists in the described format

### ISSUE THREAD

**Issue by danmartinez** [MicrosoftDocs/windows-uwp#3736]
Given the current documentation format, the recommendations provided for determining the details of an event delegate on [Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events) are no longer applicable. Please see the Note block beginning "For any given event..." for the content in question.

The relevant portion of the doc page was rooted in the discussion here: [issue-416430085](https://github.com/MicrosoftDocs/winrt-api/issues/955#issue-416430085). 

This was very useful and helpful advice. However, the api docs no longer format the code atop delegate doc pages the same way.

A similar form of this issue was raised here: [issue-608685630](https://github.com/MicrosoftDocs/windows-uwp/issues/2401#issue-608685630). That issue was subsequently closed in advance of an eventual fix, however, the disconnect still seems to exist.

Aside from clarifying the affected section, I humbly suggest that any additional remarks or example code here could be helpful (maybe something with TypedEventHandler, or another example with a different IAsync* delegate?). I would think it'd be easy for people to get tripped up here. Thanks for your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a5d7765-efa0-3077-7c2c-5e9b8341a340
* Version Independent ID: 4e73db08-5398-9416-d20e-0680ceb5e429
* Content: [Handle events by using delegates in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/handle-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/handle-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @danmartinez. "That issue was subsequently closed in advance of an eventual fix, however, the disconnect still seems to exist." Yes, the fix is still pending, but it seems to be getting closer.

Thanks!
-Steve
