### ISSUE TITLE
Can Regex Capturing Groups be used with PowerRename?

### ISSUE THREAD

**Issue by johnerbes** [MicrosoftDocs/windows-uwp#3746]
This is both a question and feedback.
I am new to PowerRename.
I had been using the File and Replace (FAR) utility by Olivier Wehner for bulk renaming of files in the past.
That utility allows the use of regular expression Capturing Groups in the Find field.

In the FAR Find field I could enter a regular expression with capturing groups such as:   The_Daily_Herald_(\w+)__(\w+)_(\d+)__(\d+)_	
and in the Replace field, enter a regular expression such as:   \4-\2-\3 The Daily Herald

Using these Find and Replace expressions, the FAR utility would then take a selected file name such as:  The_Daily_Herald_Tue__Feb_13__1905_.jpg  and rename it to: 1905-02-13 The Daily Herald.jpg

My question is, can Capturing Groups be used with PowerRename?
If so, what expression is used to recall the matched substrings?
Is it [1], [2], [3], etc.  or is it $1, $2, $3, etc. ?
The FAR utility uses \1, \2, \3 etc. for recalling capturing group substrings as can be seen from the example above.

My feedback, if capturing groups can be used, would be for you to add a few examples on the PowerToys PowerRename documentation page.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
This issue should be in the PowerToys repository.

**Comment by Jay-o-Way** [comment]
The answer to your question is under the header "Matching and variable examples". It's `$`.

**Comment by mattwojo** [comment]
Thanks for filing this @johnerbes. As Jay-o-Way mentions above, this question is better directed to the PowerToys product repo, here: https://github.com/microsoft/PowerToys/issues
If you believe that the PowerToys docs should be updated to reflect this information, please feel welcome to reopen this issue and/or file a PR.
