### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by frostfire45** [MicrosoftDocs/windows-uwp#375]
In the app.xml code behind file. It looks like your missing some information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab5201c-d8c8-1804-a225-4420f66d77ea
* Version Independent ID: 2d217eac-b2cd-553a-970f-32bb043fc353
* Content: [Navigation history and backwards navigation (Windows apps) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Are you referring to the call to On_BackRequested()? If so, it's defined in the code above in MainPage.xaml.cs. You can define it in app.xaml code-behind if you would like it to handle system-level BackRequested events.

**Comment by Blame4** [comment]
Ok, I know get current frame is easy in C#, but C++/Winrt is not so. I'm stuck.

**Comment by serenaz** [comment]
@stevewhims Perhaps you can help translate this code for C++/WinRT?

**Comment by stevewhims** [comment]
To address these questions, as @serenaz says, you can define the On_BackRequested function either in your Page class or in your App class. For the C++/WinRT question, within about 24 hours from now I expect this topic to refresh to show C++/WinRT code examples (which show the use of On_BackRequested in both places). Until then, here's how you get the Frame in the App class in C++/WinRT (in your OnLaunched function):

Windows::UI::Core::SystemNavigationManager::GetForCurrentView().BackRequested({ this, &App::App_BackRequested });
Frame rootFrame{ nullptr };
auto content = Window::Current().Content();
if (content)
{
    rootFrame = content.try_as<Frame>();
}
rootFrame.PointerPressed({ this, &App::On_PointerPressed });

And in the Page class, it's just a case of accessing the Page::Frame() property accessor function like this:

if (Frame().CanGoBack())
{
    Frame().GoBack();
    return true;
}
return false;
