### ISSUE TITLE
muxc prefix on the RatingControl in sample code

### ISSUE THREAD

**Issue by Spatacoli** [MicrosoftDocs/windows-uwp#3754]
In the section on [Replace the Placeholder Text with Real Data](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winiu3#replace-the-placeholder-text-with-real-data), the fourth step has the `RatingControl` with a "muxc" prefix (`<muxc:RatingControl ...`).  This is in contrast to the RatingControl that was placed into the template in step 4 of [Add a Data Template](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winiu3#add-a-data-template) which does not have a XAML Prefix. Could you normalize this as it may cause confusion for readers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 647e2e32-82dd-7e71-7a7f-de8550ec8c54
* Version Independent ID: 647e2e32-82dd-7e71-7a7f-de8550ec8c54
* Content: [Tutorial—Create a simple photo viewer with WinUI 3 (C#) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winiu3)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winiu3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/simple-photo-viewer-winiu3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Spatacoli. That fix is now live.

-Steve
