### ISSUE TITLE
Notification mirroring in obsolete

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/windows-uwp#3762]
What does it mean that Notification mirroring in obsolete (at least, in contents tree, 'notification mirroring' is under 'obsolete' node)?
Does it mean that ToastNotification.Mirroring  is ignored by Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13060550-f9ec-1106-d343-7ec59a6e38f6
* Version Independent ID: 239d0c99-1f5e-7713-0c7d-e110f4e05859
* Content: [Notification mirroring - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-mirroring)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/notification-mirroring.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/notification-mirroring.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
