### ISSUE TITLE
Unknown function

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/windows-uwp#3763]
What is this function returning from this call to it? var downloader = new BackgroundDownloader(); Going to see if I can find it in the Universal Windows sample library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e91192-6529-0f47-1708-834fbbf67019
* Version Independent ID: 3d32d441-7d71-82f6-8f75-7bf0cb67088b
* Content: [Media items, playlists, and tracks - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-playback-with-mediasource)
* Content Source: [windows-apps-src/audio-video-camera/media-playback-with-mediasource.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/media-playback-with-mediasource.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This function is returning a [BackgroundDownloader](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.BackgroundTransfer.BackgroundDownloader?view=winrt-22000). This reference page includes an example of its usage.
