### ISSUE TITLE
[PowerToys Run page] Translation at many points incorrect

### ISSUE THREAD

**Issue by htcfreek** [MicrosoftDocs/windows-uwp#3766]
The German translation of the PT Run docs page is at many points
- not good (incorrect German words used).
- incorrect and changes meaning.
- contains incorrect hyperlinks where the incorrect word is used as hyperlink title.

Listing all or opening different issues would take to much time.

@mattwojo 
I going to open a new PR tomorrow where I change some englisch text parts and hopefully improve the translation with this changes. Is there a way to add some comments for translation system where we can't change wording because it refers to wordings within the application?

**Comment by Jay-o-Way** [comment]
> Is there a way to add some comments for translation system where we can't change wording because it refers to wordings within the application?

That would probably be the section at the top:
`no-loc: [PowerToys, Windows, File Explorer, PowerToys Run, WindowWalker]
`

**Comment by htcfreek** [comment]
> > Is there a way to add some comments for translation system where we can't change wording because it refers to wordings within the application?
> 
> That would probably be the section at the top:
> `no-loc: [PowerToys, Windows, File Explorer, PowerToys Run, WindowWalker]
> `

But this indicates to not translate and I like to say "plz translate as xyz and not as abc".

**Comment by mattwojo** [comment]
Unfortunately most of the translations are all machine-generated now, so I don't believe that we have the ability to say "translate as xyz and not abc" unless we file a special request with the localization team. If it's something very essential, I can look in to how to go about this, but from the looks of the PR so far, it seems you're finding ways around the issue. 
Thank you for contributing this work @htcfreek!!

**Comment by mattwojo** [comment]
PR: https://github.com/MicrosoftDocs/windows-uwp/pull/3768

**Comment by htcfreek** [comment]
@mattwojo 
There is one thing I can't fix: The link name of `command line parameter` is incorrect in German translation. It is the phrase that means `, the` instead of the word for `command line parameters`.

**Comment by mattwojo** [comment]
Hmm...  I'm not exactly sure how to handle that, @htcfreek... looks like "command line parameter" is linked... so possibly reducing confusion via the ability to visit the link and have more context (?), but we could also try putting `command line parameter` inside code ticks... I believe that anything in code ticks should not be translated. (Though to be honest, I haven't personally tested this recently.)
I'm closing this issue as we just merged PR: https://github.com/MicrosoftDocs/windows-uwp/pull/3768
...but if you'd like to try an experiment with adding code ticks to that phrase to see if it resolves the translation issue, I'm totally game - just open this issue back up and I can put them in and link it to check once the machine translation rolls out.
