### ISSUE TITLE
collapsed state

### ISSUE THREAD

**Issue by Feanor1986** [MicrosoftDocs/windows-uwp#3767]
Здравствуйте! Ребята, встройте пожалуйста возможность вводить приложение в свёрнутое состояние при нажатии на кнопку закрытия, как было сделано в приложении spotify

**Comment by Karl-Bridge-Microsoft** [comment]
Translation: Hello! Guys, please embed the ability to enter the application into a minimized state when you click on the close button, as was done in the spotify application

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @Feanor1986.

As this feedback is not specifically about the documentation, but rather about the product, please consider posting at https://docs.microsoft.com/en-us/answers/topics/windows-app-sdk.html.

Closing issue as no doc updates are required.
