### ISSUE TITLE
Diagram suggests WinUI 3 supports UWP

### ISSUE THREAD

**Issue by danroth27** [MicrosoftDocs/windows-uwp#3769]
The diagram on this page seems to suggest WinUI 3 supports UWP, but I believe WinUI 3 is now desktop apps only and UWP support was dropped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [Windows UI Library (WinUI) 3 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@danroth27 - thanks for pointing that out! As we don't have a replacement image at this time, I've removed the existing image from the topic.
