### ISSUE TITLE
Windows App SDK: Link to C++ extension (VSIX) downloads the C# extension

### ISSUE THREAD

**Issue by wroyca** [MicrosoftDocs/windows-uwp#3772]
The link to download the [Visual Studio 2022 Extension (C++)](https://aka.ms/windowsappsdk/1.0/1.0.2/vsix-2022-cpp) downloads the C# extension

![Screenshot 2022-04-10 164634](https://user-images.githubusercontent.com/91024200/162639084-77ad43f7-9877-4a83-b4c8-1b8e7522c8ba.png)

**Comment by stevewhims** [comment]
Thanks, @wroyca. Looks like that's been fixed now.

Thanks again!
-Steve
