### ISSUE TITLE
Useless Documentation

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/windows-uwp#3774]
This page is essentially useless to anyone who doesn't already know how to use ms-appx, URI schemes, etc. 

It desperately needs some real-world simple examples of how to do stuff, to put the reference material in context.

For example, I am trying to figure out how to reference a resource dictionary defined in a separate assembly. After reviewing this page, I still have absolutely no clue how to do this. Maybe it's down after hundreds of lines of technical reference material. In which case, please educate the author about why "burying the lead" is not a good thing to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b411f9-df8b-a848-4d4c-dcbbf7fa8151
* Version Independent ID: b4ccaa0c-0b99-a79d-f30d-12e5276ca063
* Content: [URI schemes - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/uri-schemes)
* Content Source: [windows-apps-src/app-resources/uri-schemes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/uri-schemes.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Hi -

Sorry that this doc isn't as helpful to you as it could be. Providing more scene-setting docs to introduce concepts is on our list of things to do, and I'll create a work item to track this request. In the meantime, it's possible that the content here might be useful to you: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-app-with-uri

The Microsoft Q&A Forum is also a good place to ask specific questions and get some assistance.

Sorry I can't help more.

-John

**Comment by markolbert** [comment]
Hi John, love your user name :)

FWIW, the issue is that ms-appx: supports the following pseudo-path construct:

```
<ResourceDictionary Source="ms-appx:///J4JSoftware.GPSCommon/converters/Converters.xaml"/>
```

where the "path" root is a project referenced in the current project where App.xaml is being declared.

Unfortunately, the Visual Studio intelligent hinter isn't aware of this, and only offers paths relative to the root of the current project, ignoring the possibility that you could reference stuff in other referenced projects.

This leads the ignorant user (e.g., me) to randomly try alternative "roots" until stumbling across the answer. 

I've filed a bug report with the VS developers. But updating the documentation to explain how you can reference stuff in other referenced projects would be helpful (if it's already in the docs I missed it).

**Comment by markolbert** [comment]
Hi John,

Not sure if you’ll get the update I just posted on the issue, with some specific recommendations, because it’s closed. So I’m sending you this email to let you know I posted new material there.

-          Mark
