### ISSUE TITLE
crash and can't open same games like Brwal Stars , CLASH OF CLANS 

### ISSUE THREAD

**Issue by IG-BADAL** [MicrosoftDocs/windows-uwp#3776]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-gb/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing this issue @IG-BADAL. This sounds more like a support issue... whereas this repo is specifically for updates needed to the docs. I'll investigate to see what I can find out about this though and report back.

**Comment by GrantMeStrength** [comment]
I'm sorry, we're not able to assist in this instance. I would reach out to the publishers of these games directly to help troubleshoot your problem.
