### ISSUE TITLE
can't open the same games

### ISSUE THREAD

**Issue by IG-BADAL** [MicrosoftDocs/windows-uwp#3777]
[Enter feedback here]
  CRASH and can't open the same games like Brawl stars and Clash of clans pls fix this issue

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-gb/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Closing as this issue appears to have been filed twice. Duplicate: https://github.com/MicrosoftDocs/windows-uwp/issues/3776
