### ISSUE TITLE
Broken link makes it difficult to find out when behavior changed.

### ISSUE THREAD

**Issue by feerrenrut** [MicrosoftDocs/windows-uwp#3778]
Broken link:
Under heading "A deeper dive into winrt::resume_foreground"
`[C++/WinRT 2.0](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/newsnews#news-and-changes-in-cwinrt-20),`
Should be:
`[C++/WinRT 2.0](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/news#news-and-changes-in-cwinrt-20),`

Note `/newsnews#` becomes `/news#`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [Advanced concurrency and asynchrony with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @feerrenrut! I've fixed that now.

-Steve
