### ISSUE TITLE
WinUI 3 Install documentation incorrectly states templates are available via VS Installer

### ISSUE THREAD

**Issue by YardGnomeNinja** [MicrosoftDocs/windows-uwp#3782]
`.NET Desktop Development for C# app development

    Then in the Installation details pane of the installation dialog, select Windows App SDK C# Templates (at the bottom of the list).`

The selection 'Windows App SDK C# Templates' does not appear in the list of installation details for '.NET Desktop Development for C#'.

As such, I am unable to create a WinUI 3 application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b#required-workloads-and-components)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @YardGnomeNinja. The info you quote is on the tab labeled "Visual Studio 2022 version 17.1 and later". Are you using the Visual Studio Installer with Visual Studio 2022 version 17.1 or later? If not, then see the info in the tab labeled "Other Visual Studio versions".

If the tab labeling was the issue, then please let me know. The tabs can be easy to miss.

Thanks!
Steve

**Comment by YardGnomeNinja** [comment]
Sorry for the bother. I thought I was on 17.2. Turns out it was 17.0.2. I hope to learn to read someday. Thanks!
