### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Buildsoftwaresphere** [MicrosoftDocs/windows-uwp#3786]
[Great content @Accessibility in the Store, Windows app as accessible in the Microsoft Store.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3fff7b-b5b3-f7a3-1834-9171e74510e5
* Version Independent ID: 03fabfcb-902e-3e15-924a-9072e4eb556b
* Content: [Accessibility in the Store - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/accessibility/accessibility-in-the-store)
* Content Source: [hub/apps/design/accessibility/accessibility-in-the-store.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/accessibility/accessibility-in-the-store.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No issue reported.
