### ISSUE TITLE
Contradicting Info

### ISSUE THREAD

**Issue by abhigupta** [MicrosoftDocs/windows-uwp#379]
The breakpoints information here directly contradicts the info on the Overview page!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ef13333-20dd-0d5d-0680-196e1e74ad2f
* Version Independent ID: 995f19c1-7c3d-cee6-d1dc-5ce36054e2c0
* Content: [Screen sizes and break points for responsive design - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/screen-sizes-and-breakpoints-for-responsive-design#feedback)
* Content Source: [windows-apps-src/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by serenaz** [comment]
Thanks for raising the issue! You're right - the correct breakpoints are at 640px and 1080px, like this article states. We'll update the overview with the correct information.
