### ISSUE TITLE
Incorrect xaml for red heart example

### ISSUE THREAD

**Issue by nelons** [MicrosoftDocs/windows-uwp#3796]
Hi,

The XAML for the red heart with the black border under the "Layering and Mirroring" section is incorrect. The sample on the page will display the heart with a red border, followed by the black heart on top of it.

The "Glyph" properties need swapping around so the heart fill symbol in red is drawn first, and then the heart with black border on top. The correct XAML would be:

```
<Grid>
    <FontIcon FontFamily="Segoe Fluent Icons" Glyph="&#xEB52;" Foreground="#C72335" />
    <FontIcon FontFamily="Segoe Fluent Icons" Glyph="&#xEB51;" />
</Grid>
```

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e1f4b4-3d25-c08c-e3b0-12011d3bba0f
* Version Independent ID: 3b140070-493f-0b2c-f7c4-3fb89192d2d0
* Content: [Segoe Fluent Icons font - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font)
* Content Source: [hub/apps/design/style/segoe-fluent-icons-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/style/segoe-fluent-icons-font.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Jay-o-Way** [comment]
Please put the suggested XAML in a code block. It's invisible now.

**Comment by nelons** [comment]
Apologies for missing the notification. I've updated the code as requested.

**Comment by jwmsft** [comment]
Thanks. Code example was updated.
