### ISSUE TITLE
Docs issue results in &mdash; appearing on ~1000 pages instead of —

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/windows-uwp#3801]
As per the title, [according to Google](https://www.google.com/search?q=%22%26mdash%3B%22+site%3Adocs.microsoft.com) there are approximately ~1000 Docs pages that display `&mdash;` instead of — (em dash / long dash).

Microsoft Docs doesn't appear to have a repo for site-wide issues, so since at least 1 windows-uwp page shows this issue I'm reporting it here.

https://docs.microsoft.com/windows/apps/windows-app-sdk/deploy-packaged-apps

![Screenshot 2022-04-29 065226](https://user-images.githubusercontent.com/5379488/165931242-00ace59c-41bf-4e78-9a0f-664c7ca0f38d.jpg)

@Karl-Bridge-Microsoft Mentioning you since you managed to get the last issue I found like this resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a217efe3-f428-499b-7344-4579bc7d8229
* Version Independent ID: 87ac66f6-50b4-9b72-b4dc-8936148e0593
* Content: [Windows App SDK deployment guide for MSIX-packaged apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-packaged-apps)
* Content Source: [hub/apps/windows-app-sdk/deploy-packaged-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/deploy-packaged-apps.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by GrantMeStrength** [comment]
Thank you! It looks like a mass search-and-replace added these a little aggressively. I'm going to fix them up.
