### ISSUE TITLE
Windows App SDK GetWindowHandle code is incorrect

### ISSUE THREAD

**Issue by taoyouh** [MicrosoftDocs/windows-uwp#3804]
In the section "MessageDialog, and Pickers", the document says we can use `WinRT.Interop.WindowNative.GetWindowHandle(this)` to get the window handle, where `this` is an instance of `App`. However this call will raise an exception:

```
System.InvalidCastException:“Specified cast is not valid.”
```

The method should be called on the `MainWindow` but not the `App`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b65398-4a76-529e-e55d-24a710022b32
* Version Independent ID: 37b65398-4a76-529e-e55d-24a710022b32
* Content: [User interface migration (including WinUI 3) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for letting us know, @taoyouh. Sorry about the coding error there. I've published a fix to that now.

Thanks again!
-Steve
