### ISSUE TITLE
Is the "Move from iOS to UWP" guidance still relevant and correct?

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/windows-uwp#3805]
"For example, a completed or nearly completed game that is heavily dependent on OpenGL or Cocos2D is an ideal candidate for the [Windows Bridge for iOS](https://github.com/microsoft/WinObjC)" doesn't seem to acknowledge that it hasn't seen a commit in over two years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa0e6aa5-8ba4-dadf-9562-ec8a6aba2ba1
* Version Independent ID: 89ce0f9c-7fbd-c6f8-b886-ab766706f755
* Content: [Move from iOS to UWP - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/ios-to-uwp-root)
* Content Source: [windows-apps-src/porting/ios-to-uwp-root.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/ios-to-uwp-root.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
This content is very outdated and needs removed now. Thanks for the reminder!
-John

**Comment by Poopooracoocoo** [comment]
Straight up removed, huh. Kinda sad tbh

**Comment by GrantMeStrength** [comment]
Yes, makes me sad too - it was the first content I wrote when I moved to this team a long time ago. 
Our recommended approach now is of course .NET MAUI.
