### ISSUE TITLE
Dead link to store.

### ISSUE THREAD

**Issue by petertiedemann** [MicrosoftDocs/windows-uwp#3806]
Dead link to store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by GrantMeStrength** [comment]
Broken link. Assigned to doc owner.

**Comment by mattwojo** [comment]
Hmm.. Store link seems fine. Maybe it was a temporary outage? @petertiedemann - closing as I'm unable to replicate the issue, but please reopen if you find that the link is still broken for you.
Thanks for brining this to our attention.

**Comment by petertiedemann** [comment]
> Hmm.. Store link seems fine. Maybe it was a temporary outage? @petertiedemann - closing as I'm unable to replicate the issue, but please reopen if you find that the link is still broken for you.
> Thanks for brining this to our attention.

Must have been, it seems fine now. Sorry for raising an issue over nothing.

**Comment by mattwojo** [comment]
No worries at all!  Would MUCH rather you raise the issue and let us know... thanks again Peter!
