### ISSUE TITLE
What about making the DataAccessLibrary project a build dependency of the UWP project?

### ISSUE THREAD

**Issue by binaryfunt** [MicrosoftDocs/windows-uwp#381]
I had made a mistake in a SQL query in my `DataAccess.cs` class, and corrected it. But when I was clicking start debugging to run my UWP app, I was still getting the same SQLite error message no matter what I changed.

I fixed this by right clicking on my UWP project in the Solution Explorer, then clicking Build Dependencies > Project Build Order..., and in the dialog, ticking DataAccessLibrary.

Perhaps it would be a good idea to add a line in the doc about adding that build dependency, otherwise it could leave people scratching their heads when changing the DataAccess class has no effect.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hello - Thank you for the feedback. Sorry for the trouble this caused. To that end, I went through the process just now (VS 2017 with min version Fall creators) added reference to data access library, built and ran debugger. The dependency is auto added so I can't seem to repo the issue of a broken dependency reference. That said, if adding reference to dependent assemblies is broken, this is a pretty significant bug in VS so I'll watch for more feedback on similar issues. I'm really hoping that this is an isolated issue. If it isn't, and we receive more notes about this, we'll have to log a bug with VS and likely end up adding notes like these to any place in our docs where we refer to dependent assemblies. Thank you for sharing this issue!
