### ISSUE TITLE
Mason

### ISSUE THREAD

**Issue by Masonta1976** [MicrosoftDocs/windows-uwp#3810]
An integer is a number without decimal points. Maybe you have a decimal here. Try Math.floor(...) or Math.round(...) and see whether that fixes it.

**Comment by GrantMeStrength** [comment]
Hi - is this comment related to a specific topic we could improve? thanks! 
-John

**Comment by GrantMeStrength** [comment]
Please recreate the issue if it's still a problem. Thanks!
