### ISSUE TITLE
The Command "sudo apt install python3-pip" isn't Working in WSL2 

### ISSUE THREAD

**Issue by sangramz** [MicrosoftDocs/windows-uwp#3814]
[I tried goind about the documentation. It works for Ubuntu 18 in WSl, But not for Ubuntu 20.04 at WSL2,]

Following errors are shown:
```
 _sudo apt install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pip' has no installation candidate_
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b92f5-7f7f-cc94-64b9-69462979fe0f
* Version Independent ID: 5096d0ec-24fc-23ae-b2ec-aa21acf273d5
* Content: [Web development with Python on Windows](https://docs.microsoft.com/en-us/windows/python/web-frameworks)
* Content Source: [hub/python/web-frameworks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/web-frameworks.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@craigloewen-msft -- Any guesses as to what the issue may be here? $PATH issue?

**Comment by mattwojo** [comment]
Hey @sangramz - I just took another look at this and found this StackO post: https://stackoverflow.com/questions/62317653/how-to-install-python3-pip-on-ubuntu-20-04

Have you tried running `sudo apt update` just to be sure that you've got the latest from Ubuntu-20.04?

**Comment by mattwojo** [comment]
I just tried running `sudo apt install python3-pip` on a fresh install after running `sudo apt update` and it seemed to install without issue.

**Comment by mattwojo** [comment]
Closing. Please re-open if you find that there is an issue here that should be clarified in the docs. Thanks for contributing!
