### ISSUE TITLE
Fluent Design 404

### ISSUE THREAD

**Issue by Jaren8r** [MicrosoftDocs/windows-uwp#3819]
The fluent design hyperlink under the WinUI 3 section goes to https://docs.microsoft.com/en-us/design/fluent/, which is a 404 page. It should probably go to https://www.microsoft.com/design/fluent/#/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2607ab3-0ec2-00bd-f8a8-cf2f57fe258f
* Version Independent ID: c2607ab3-0ec2-00bd-f8a8-cf2f57fe258f
* Content: [Windows developer glossary - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/windows-developer-glossary)
* Content Source: [hub/apps/get-started/windows-developer-glossary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/windows-developer-glossary.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @MatchaMatch
* Microsoft Alias: **mikben**

**Comment by GrantMeStrength** [comment]
Broken link.

**Comment by Karl-Bridge-Microsoft** [comment]
The links are working again. Thanks for letting us know.
