### ISSUE TITLE
Problem with refreshing updated programs

### ISSUE THREAD

**Issue by ecjb1969** [MicrosoftDocs/windows-uwp#3821]
[Enter feedback here]

When using winget upgrade --all, packages appear to upgrade successfully (mostly), but rerunning winget upgrade does not show that the program version changed.

Sample output of "winget upgrade"...

`PS C:\Windows\System32> winget upgrade
Name                                                 Id                            Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
R for Windows                                        RProject.R                    4.1.0          4.2.0          winget
R for Windows                                        RProject.R                    4.1.3          4.2.0          winget
Rtools                                               RProject.Rtools               4.0            4.2            winget
TechPowerUp GPU-Z                                    TechPowerUp.GPU-Z             2.44.0         2.46.0         winget
Windows Assessment and Deployment Kit Windows Prein… Microsoft.ADKPEAddon          10.1.19041.1   10.1.22000.1   winget
VNC Viewer                                           RealVNC.VNCViewer             6.21.406.44671 6.22.315.46706 winget
Microsoft .NET SDK                                   Microsoft.dotnet              5.4.622.11901  6.2.222.17207  winget
GOG GALAXY                                           GOG.Galaxy                    Unknown        2.0.49.1       winget
Microsoft Teams                                      Microsoft.Teams               1.4.0.2781     1.5.00.9163    winget
Oracle VM VirtualBox                                 Oracle.VirtualBox             6.1.28         6.1.32         winget
Microsoft Visual Studio Code                         Microsoft.VisualStudioCode    1.66.1         1.67.0         winget
Python 3                                             Python.Python.3               3.7.8150.0     3.10.4150.0    winget
Python 3                                             Python.Python.3               3.9.4150.0     3.10.4150.0    winget
Windows Assessment and Deployment Kit                Microsoft.WindowsADK          10.1.19041.1   10.1.22000.1   winget
Microsoft .NET SDK                                   Microsoft.dotnet              6.1.322.12413  6.2.222.17207  winget
VLC media player                                     VideoLAN.VLC                  3.0.17.0       3.0.17.4       winget
VLC media player                                     VideoLAN.VLC                  3.0.17.0       3.0.17.4       winget
Wireshark                                            WiresharkFoundation.Wireshark 3.6.3.0        3.6.5.0        winget
Microsoft Visual Studio Code                         Microsoft.VisualStudioCode    1.65.2         1.67.0         winget
Microsoft .NET SDK                                   Microsoft.dotnet              5.2.1222.11809 6.2.222.17207  winget
20 upgrades available.
PS C:\Windows\System32> winget --version
v1.2.10941
PS C:\Windows\System32>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf54ba9-53bd-e5d0-3b5a-e5b003f356d9
* Version Independent ID: ed2c403c-7bba-9647-fb5c-da556cb93a6b
* Content: [upgrade Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/upgrade)
* Content Source: [hub/package-manager/winget/upgrade.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/upgrade.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by GrantMeStrength** [comment]
Not a doc bug. Assigning to PM owner.

**Comment by crutkas** [comment]
This is either Kevin or demitrius for WinGet not PowerToys

**Comment by denelon** [comment]
@ecjb1969,

There are a couple of different things going on here. I believe the main one you are seeing is a package "upgrade" may be installing a newer version of the package "Side-By-Side", and not a true upgrade. When this happens, the older version is still present on the system so running `winget upgrade` still shows the older installed version and the newer available version even though the newer one is already installed. 

We have:
* https://github.com/microsoft/winget-cli/issues/1075 

The more "broad" generic issue is:
* https://github.com/microsoft/winget-cli/issues/752

**Comment by mattwojo** [comment]
It sounds like this issue is not requiring an update to the docs, but please reopen if this is not the case - @ecjb1969 / @denelon 

And thanks for contributing Eric!
