### ISSUE TITLE
Can't remove resizer while in FancyZone editor with a mouse

### ISSUE THREAD

**Issue by victoriacheng15** [MicrosoftDocs/windows-uwp#3822]
I made some mistakes when I was trying to set up zones, but I couldn't delete the unwanted zone. I looked at the pop-up window (screenshot below), it looks great for people who prefer to use the keyboard to manage zones and resizers. However, I had to figure out how to delete resizer with a mouse. I read the FancyZone  doc, and it doesn't have any explanations on how to do so. Maybe, the doc could add a short clip or screenshots to show how to delete the resizer with a mouse?

![image](https://user-images.githubusercontent.com/35031228/167863775-d6ae0b47-1c14-45ce-ba61-f9fa2931bc8e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by GrantMeStrength** [comment]
Opportunity to enhance documentation.

**Comment by mattwojo** [comment]
@crutkas - Thoughts on adding this additional explainer to the docs?

**Comment by crutkas** [comment]
we do directly call this out.  You don't delete zones for grid based layouts, you merge them to another.  Maybe we do "To merge/delete zones"?

> To merge zones: select a zone and hold the left mouse button and drag the mouse until multiple zones are selected, release the button and a popup menu will show up. Click "Merge" and they will become one big zone. This is how a zone would be deleted, by merging it into another zone.

https://docs.microsoft.com/en-us/windows/powertoys/fancyzones#creating-a-custom-layout

**Comment by victoriacheng15** [comment]
I played around a bit, and now I see what you mean. I was looking for the keyword `delete` and didn't realize that merge zones do the same thing. I believe `To merge/delete zones` would be clear to show readers that you can manage zones.

**Comment by mattwojo** [comment]
Looks like this update was added in https://github.com/MicrosoftDocs/windows-uwp/pull/3836 

Thanks @Jay-o-Way for adding and @victoriacheng15 for contributing the issue / suggestion!

Closing.
