### ISSUE TITLE
Is there an ms-settings: schema URI for the "main" Bluetooth & devices page?

### ISSUE THREAD

**Issue by andyqp** [MicrosoftDocs/windows-uwp#3823]
Is there an ms-settings: schema URI for the "main" **Bluetooth & devices** page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this. There doesn't appear to be a URI available to navigate directly to the "Bluetooth & devices" settings page. The ms-settings:bluetooth URI goes to "Bluetooth & devices > Devices". I searched the Windows registry and didn't find any other URIs registered to get to that parent page. My suggestion would be to use the **Feedback Hub** app to submit a **feature request** to add a URI to get there. (Or see if there's an existing feedback item you can upvote.)

Alternatively, the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
