### ISSUE TITLE
Not applicable for VS 2022

### ISSUE THREAD

**Issue by rhkavli** [MicrosoftDocs/windows-uwp#3824]
There is no template for a console app for C++/WinRT (UWP) in VS 2022.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e739c976-323f-bdf7-14a4-9b2d4872c62c
* Version Independent ID: c580c6b6-dc0d-296e-ffbd-0d866b34779f
* Content: [Create a Universal Windows Platform console app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp)
* Content Source: [windows-apps-src/launch-resume/console-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/console-uwp.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thank you for your feedback. I am checking with the team to determine if VS 2022 support is planned for the templates. I will circle back when I have more information.

**Comment by alvinashcraft** [comment]
I have confirmed with the team that VS 2022 is not going to be supported for these templates. I updated the page to add a note about this. It should be live soon. Thanks again for your suggestion.
