### ISSUE TITLE
Clarify necessary workloads

### ISSUE THREAD

**Issue by JVimes** [MicrosoftDocs/windows-uwp#3828]
I found this section hard to read and it also made me think I need all three workloads (not the case):

> - On the Workloads tab of the installation dialog, select:
>   - Universal Windows Platform development
>     - Then in the Installation details pane of the installation dialog for that workload, make sure C++ (v143) Universal Windows Platform tools is selected.
>   - .NET Desktop Development for C# app development
>     - Then in the Installation details pane of the installation dialog, select Windows App SDK C# Templates (at the bottom of the list).
>   - Desktop development with C++ for C++ app development
>     - Then in the Installation details pane of the installation dialog, select Windows App SDK C++ Templates (at the bottom of the list).

Suggest updating it to something like this:

> - On the Workloads tab of the installation dialog, select as appropriate:
>   - For UWP app development select "Universal Windows Platform development"
>     - Then in the Installation details pane of the installation dialog for that workload, make sure C++ (v143) Universal Windows Platform tools is selected.
>   - For C# app development select ".NET desktop development"
>     - Then in the Installation details pane of the installation dialog, select Windows App SDK C# Templates (at the bottom of the list).
>   - For C++ app development select "Desktop development with C++"
>     - Then in the Installation details pane of the installation dialog, select Windows App SDK C++ Templates (at the bottom of the list).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c95c3c2-b81a-5682-5187-9f1328f17cf5
* Version Independent ID: 1a4d4425-689e-4d3a-1248-a1dd5789d285
* Content: [Install tools for the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b)
* Content Source: [hub/apps/windows-app-sdk/set-up-your-development-environment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Good idea, @JVimes. I've published that fix to this topic and the other topic that contains similar content.

-Steve
