### ISSUE TITLE
Page title is broken in recommended sections

### ISSUE THREAD

**Issue by y2k04** [MicrosoftDocs/windows-uwp#3829]
![image](https://user-images.githubusercontent.com/29883287/168182281-fd6a5e3d-3ee2-49d8-b5bb-d0925fc30e9c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial—Create a simple photo viewer with WinUI 3 (C#) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by y2k04** [comment]
It can be seen here: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/winui-project-templates-in-visual-studio

**Comment by stevewhims** [comment]
Thanks, @y2k04. I've removed the html entity from the YAML description of the topic. It's likely that that was causing the issue.

-Steve
