### ISSUE TITLE
TextBox input doesn't work inside a flyout.

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/windows-uwp#383]
I have an AppBarButton with the flyout assigned, and inside the flyout I have multiple text boxes. These aren't editable inside the flyout, even though other things like check boxes work. How do we make these editable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4822fcb-d3c5-06b1-10dd-dd56cc08df75
* Version Independent ID: e9b087b2-602b-1a3b-94ab-81489829510e
* Content: [Dialogs and flyouts - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs#is-this-the-right-control)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Seems to be answered here, but that should be part of the documentation: https://stackoverflow.com/questions/39096758/cant-enter-enter-text-in-textbox-control-inside-flyout

**Comment by mijacobs** [comment]
I'll add it to the doc.

**Comment by jevansaks** [comment]
@andrewleader this is more of a feature request. We've been discussing adding the WPF "focus scopes" feature to XAML and this would be something that would benefit from that work. You could file this as a feature request on https://github.com/microsoft/microsoft-ui-xaml.

**Comment by andrewleader** [comment]
Thanks @jevansaks, I think I was trying to do this for a demo project at work, don't remember what for specifically. So I'm no longer blocked as I'm not working on that anymore. It'd be a nice feature to have, but I have no current application for it.
