### ISSUE TITLE
Update interop_helpers.h with null check, conversions for String, Guid

### ISSUE THREAD

**Issue by Scottj1s** [MicrosoftDocs/windows-uwp#3831]
interop_helpers.h was borrowed from CxUtils.h, which has since grown to include support for string and guid conversion.  Also the generic from_cx doesn't include a null check.

```
    template <typename T>
    T to_cx(winrt::Windows::Foundation::IUnknown const& from)
    {
        return safe_cast<T>(reinterpret_cast<Platform::Object^>(winrt::get_abi(from)));
    }

    template <typename T>
    T from_cx(Platform::Object^ from)
    {
        T to{ nullptr };

        if (from != nullptr)
        {
            winrt::check_hresult(reinterpret_cast<::IUnknown*>(from)->QueryInterface(winrt::guid_of<T>(), winrt::put_abi(to)));
        }

        return to;
    }

    inline Platform::String^ to_cx(winrt::hstring const& from)
    {
        return reinterpret_cast<Platform::String^&>(const_cast<winrt::hstring&>(from));
    }

    inline winrt::hstring from_cx(Platform::String^ const& from)
    {
        return reinterpret_cast<winrt::hstring&>(const_cast<Platform::String^&>(from));
    }

    inline Platform::Guid to_cx(winrt::guid const& from)
    {
        return reinterpret_cast<Platform::Guid&>(const_cast<winrt::guid&>(from));
    }

    inline winrt::guid from_cx(Platform::Guid const& from)
    {
        return reinterpret_cast<winrt::guid&>(const_cast<Platform::Guid&>(from));
    }

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e79918f-ced1-2809-d280-501e85ade810
* Version Independent ID: 950b6e6a-f809-1c7a-5bcb-b8919c978110
* Content: [Interop between C++/WinRT and C++/CX - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/interop-winrt-cx?source=docs)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/interop-winrt-cx.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/interop-winrt-cx.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Sorry for the delay: I just published the updates. One thing, the existing content had `T^ to_cx`; and the code above has `T to_cx` (without the hat). I had to put the hat back in to get the example project walkthrough to work; hope that's ok.

-Steve
