### ISSUE TITLE
where is the download link?

### ISSUE THREAD

**Issue by worldor** [MicrosoftDocs/windows-uwp#3835]
[Enter feedback here]
where is the download link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b0cc3d-3662-21c9-ec5f-9793616ea5fc
* Version Independent ID: 96289e4e-417b-28b9-8f1c-d561e3afab22
* Content: [Build desktop Windows apps with the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/)
* Content Source: [hub/apps/windows-app-sdk/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/index.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @worldor, and thanks for filing this issue. I'm not immediately seeing the problem with the topic. Is there a link missing from the topic? Or is there a link present that's not working? Note that there are several things that one can download for the Windows App SDK (downloads for development; downloads for runtime); and more than one version of those various things.

Many thanks!
-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this one for now. But please reopen it and/or respond with info if you have it.

Many thanks!
-Steve
