### ISSUE TITLE
Re-write docs according to MD reference / Authoring Pack

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/windows-uwp#3837]
@mattwojo brought the Docs Authoring Pack and https://docs.microsoft.com/contribute/markdown-reference to my attention. The docs however, seem to be written long before these reference/rules/guidelines. Up to this day, people write like what's already there, not what reference says. I think we all need to sync here...

I would like to check (all?!) the docs to see if they comply. I'm aware this is going to take time and will involve many, **many** files. Needs to be done in parts. Common (broken) rules:

- **Do not style links or headers**
- Do not use `code` for text that is not code
- Do not use \<HTML>

CC: @Karl-Bridge-Microsoft @jwmsft

## General issues
- [ ] sub-text under an image: use _italic_ with or without `>` quote style?
- [ ] Every now and then a XAML example uses deprecated MDL2 icon codes:
   - [ ] _radialcontroller-walkthrough_ line 226: `\xE1E3`
- [x] "vs" vs. "versus" vs. Visual Studio
- [x] many pages use multiple (often 3) `<span>` elements as an anchor for headers. NOT reccommended.  → **I will remove them!**
   ``` html
       <span id="Assistive_technology_support_in_apps_that_support_XAML___Microsoft_DirectX_interop"/>
       <span id="assistive_technology_support_in_apps_that_support_xaml___microsoft_directx_interop"/>
       <span id="ASSISTIVE_TECHNOLOGY_SUPPORT_IN_APPS_THAT_SUPPORT_XAML___MICROSOFT_DIRECTX_INTEROP"/>
   ```
- [x] "Get the Windows UI Library" appears in many pages, so it **should** be used with an `[!include]` file: https://docs.microsoft.com/en-us/contribute/markdown-reference#included-markdown-files
- [x] "Examples" (next to "xaml-controls-gallery-app-icon") appears in many pages, so it **should** be used with an `[!include]` file
  - "Examples" have explicit-HTML `<table>`
  - Somebody typed `<th>...<th>` and it's a p.i.t.a. to replace them all.
- [x] minor thing - keep this redundancy? → no
![image](https://user-images.githubusercontent.com/65828559/168582009-b9fd001e-1c9a-4cb4-b80e-16ed2e64be57.png)

## Specific issues
- [ ] Empty/broken links:
  - [ ] _accessibility-overview.md_ `[Design for accessibility]()`
  - [ ] _radialcontroller-walkthrough.md_ has broken links under # "API reference"
  - [ ] _windows-wheel-interactions.md_ has an iframe to a YouTube video that is "private": https://www.youtube-nocookie.com/embed/WMklcdzcNcU
  - [x] _breadcrumbbar.md_ `[ItemsSource]()`
- [ ] _item-containers-templates.md_ # "Brushes": much HTML
- [ ] convert html `<table>` to MD
  - [ ] _lists.md_ # "Related articles" (multiple) and # "Globalization":
  - [ ] _touchpad-interactions.md_ # "Language"
  - [ ] and many more

**Comment by Jay-o-Way** [comment]
Getting ahead of myself - too fast - and falling on my face. 😣
Need help @mattwojo @Karl-Bridge-Microsoft @jwmsft @QuinnRadich

**Comment by mattwojo** [comment]
Hi @Jay-o-Way - Yes, I think you are discovering some of the complexities involved in working with a HUGE amount of docs, many of which have been around a very long time. As you call out... many of the docs have indeed been "written long before these reference/rules/guidelines." 

The expectation has been to keep the older, existing docs readable/usable, but not necessarily going back to bring everything up to date with the current (and continually evolving) rules and guidelines. Occasionally there will be an effort to go back and clean up something essential, like links, if needed... but an effort to completely bring _everything_ up to the current guidance may be a bit ambitious.

Applaud your effort... and if you're feeling inspired to take a crack, I don't think anyone will stand in your way... but in general, I would say that we have focused on maintaining guidelines for only the more modern and/or highly trafficked docs.

If you have a particular question, please feel welcome to post... but there are going to be certain rules that I anticipate will just need to be broken on some of the older docs. (Particularly in regard to using <HTML> as an example).

Thanks again for all of the ways you've been contributing!!!

**Comment by Karl-Bridge-Microsoft** [comment]
@Jay-o-Way - It sounds like you're considering a significant contribution! Please keep each PR to a manageable size and, preferably, within a single folder. We have PR automation that assigns the writer associated with the content within the PR (often based on folder), so multiple writers across many files can result in some confusion and delay triage/completion.

**Comment by Jay-o-Way** [comment]
Okay, let's break things down. This really felt like diving head-first, from a diving board, into a swimming pool without checking if there was any water in it. And there wasn't. 🤕

> Applaud your effort... and if you're feeling inspired to take a crack, I don't think anyone will stand in your way...

Thanks, that's good to know.

> If you have a particular question, please feel welcome to post... but there are going to be certain rules that I anticipate will just need to be broken on some of the older docs. (Particularly in regard to using html as an example).

I actually have! They're in the issue ⬆

Besides those: I pinged @Karl-Bridge-Microsoft and @jwmsft because the other day I had this HUGE list of **merge conflicts** regarding the "WinUI 2 Gallery" text in "that html table". Am I correct to assume that you have seen my (couple of) comments in [your commit](https://github.com/MicrosoftDocs/windows-uwp/commit/ae80d90f47b53c561eefe797c673d05e37e0ef17) ? It would really help if somebody could answer those questions, _before_ working on this again. How to prevent with (or deal with) this in the future?

> Please keep each PR to a manageable size and, preferably, within a single folder.

Understandable. But **how deep** - as in directory - should I do this? I think that, If I can create a PR for literally every single folder, the number of PRs is going to be HUGE just the same... I made a [List of MD docs](https://github.com/MicrosoftDocs/windows-uwp/files/8741246/List.of.MD.docs.docx) with some numbers.

Any more do's and don'ts?

**Comment by Karl-Bridge-Microsoft** [comment]
@Jay-o-Way - re. folders: the smaller the chunk of files, the easier it is for a writer to triage. This includes the scope of the change you're suggesting, such as html->md, adding includes, and so on. Too many issues across files in a PR could result in merge conflicts, delays, or even full rejection due to limits in how we can vet your suggestions. Have a look at historic PRs to see the typical file counts.

Due to the sheer number of Windows docs across repos, the specific set of docs in your PR/Issue might not actually be a priority and can languish.

Also, be aware that your update to one file might actually cascade into a number of related files. This can also result in your PR being rejected and a private one initiated in its place.

If your contributions are large and, as a result, take significant time for you to assemble, merge conflicts are to be expected considering the frequency of internal/private updates to the docs.

**Comment by Jay-o-Way** [comment]
I've started from scratch now. This time I'm keeping everything offline until I think I'm done. ~Then I'll create "targeted" commits (and PRs) for folders.~

I want to use the following in .md files in the `\design\controls` folder:

```md
(...)
[!INCLUDE [Get the Windows UI Library](../includes/get-windows-ui-library-corners.md)]
(...)
```
and the content of that file is:
```md
## Get the Windows UI Library

:::row:::
   :::column:::
      :::image type="icon" source="../images/winui-logo-64x64.png" border="false":::
   :::column-end:::
   :::column span="3":::
      This control requires the Windows UI Library, a NuGet package that contains new controls and UI features for Windows apps. For more info, including installation instructions, see [Windows UI Library](/uwp/toolkits/winui/). Windows UI Library 2.2 or later includes a new template for this control that uses rounded corners. For more info, see [Corner radius](../style/rounded-corner.md).
   :::column-end:::
:::row-end:::
```

And then towards the end of the pages:
```md
(...)
[!INCLUDE [Examples (WinUI Gallery and/or GitHub)](../includes/examples.md)]

## Related articles (...)
```
and the content of that file is:
```md
## Examples

:::row:::
    :::column span="":::
        ![WinUI Gallery](../images/xaml-controls-gallery-app-icon-sm.png)
    :::column-end:::
    :::column span="2":::
        If you have the [WinUI 2 Gallery](winui2gallery:) or [WinUI 3 Gallery](winui3gallery:) app installed, click on its name to open the app. See all the XAML controls in an interactive format.
        - [Get the WinUI 2 Gallery app (Microsoft Store)](https://apps.microsoft.com/store/detail/winui-2-gallery/9MSVH128X2ZT)
        - [Get the WinUI 3 Gallery app (Microsoft Store)](https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC)
        - [Get the source code (GitHub)](https://github.com/Microsoft/WinUI-Gallery)
    :::column-end:::
:::row-end:::
```

@Karl-Bridge-Microsoft how is that second one compared to the changes I've seen in your commit? It mentions both v2 and v3 and without HTML :)

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Jay-o-Way - thanks for the effort, but this is an example of an update that affects far too many files across repos. We use this block (or similar) in both UWP and WinUI/Windows App SDK repos. We've also recently made global changes to accommodate a major update to the apps themselves. This will be a PR that I expect will get rejected in favor of an internal solution based on writer priorities.

**Comment by Jay-o-Way** [comment]
In this case, these _include_ blocks only are used inside the `\design\controls\` folder. So, this should only be about 80 files, they are all closely related/similar and this seems quite manageable to me?

**Comment by jwmsft** [comment]
Hi @Jay-o-Way, I don't mean to discourage your contributions, but we have some significant re-working of the entire \design\controls\ section that has been waiting for the update to the WinUI controls gallery. Now that the controls gallery update has just gone live, we'll start pushing our updates to the controls docs this week (after Build activity settles down). We probably won't be able to accept any incoming PRs until we have this update out, and the docs will need to be re-assessed after that due to the scope of the changes.

**Comment by Jay-o-Way** [comment]
Hm, how do I create a PR for a certain folder? If I commit to a branch, they all end up in the same PR. Does that mean I have to create a different branch for each folder?

(edit) I only see one possibility:

1. Make sure I have the latest version of all files and put them aside in a zip, or copy to a different location.
2. Reset the branch to current state.
3. Create a new, targeted branch.
4. Copy/overwrite the files within that scope.
5. GitHub Desktop sees changes - create a commit.
6. Create a pr for the same scope.

Repeat step 3 to 6 for everything single scope...

**Comment by Jay-o-Way** [comment]
I have put all (and only) the MD files in a ZIP file: [windows-uwp (md files).zip](https://github.com/MicrosoftDocs/windows-uwp/files/8771385/windows-uwp.md.files.zip)

I hope some of you are willing to have a look at what I did and maybe they can help me along, or maybe they can use these files  to apply these changes in the best manner. (thinking about targeted commits, prs, merge conflicts etc. etc.)
I really did put effort into this.

**Comment by jwmsft** [comment]
> Hm, how do I create a PR for a certain folder? If I commit to a branch, they all end up in the same PR. Does that mean I have to create a different branch for each folder?
> 
> (edit) I only see one possibility:
> 
> 1. Make sure I have the latest version of all files and put them aside in a zip, or copy to a different location.
> 2. Reset the branch to current state.
> 3. Create a new, targeted branch.
> 4. Copy/overwrite the files within that scope.
> 5. GitHub Desktop sees changes - create a commit.
> 6. Create a pr for the same scope.
> 
> Repeat step 3 to 6 for everything single scope...

Changes for each folder would need to be in separate branches to result in separate PRs. However, the process for that is to just create each new branch from the `main` branch, then create a PR for each branch back into the `main` branch. There should be no need to save copies of files in a different location. As long as you don't edit the same file in more than one branch, there shouldn't be any conflicts between the PRs/branches.

**Comment by jwmsft** [comment]
> I have put all (and only) the MD files in a ZIP file: [windows-uwp (md files).zip](https://github.com/MicrosoftDocs/windows-uwp/files/8771385/windows-uwp.md.files.zip)
> 
> I hope some of you are willing to have a look at what I did and maybe they can help me along, or maybe they can use these files to apply these changes in the best manner. (thinking about targeted commits, prs, merge conflicts etc. etc.) I really did put effort into this.

Thanks for the zip file and the work you put in. We'll incorporate as much as possible into upcoming revisions to these docs.

**Comment by Jay-o-Way** [comment]
> However, the process for that is to just create each new branch from the `main` branch, then create a PR for each branch back into the `main` branch. There should be no need to save copies of files in a different location. As long as you don't edit the same file in more than one branch, there shouldn't be any conflicts between the PRs/branches.

Hm, okay, I need to try this to understand it. Thing is: in VS Code I can do a Find-and-replace for many files/folders at once. That's efficient (which is very necessary in this scale) but that does mean changes are made inside many folders at once.


> Thanks for the zip file and the work you put in. We'll incorporate as much as possible into upcoming revisions to these docs.

Thanks 🖤 As I said: im gonna leave it up to you guys now :)

**Comment by Karl-Bridge-Microsoft** [comment]
Under internal review.

**Comment by michelsciortino** [comment]
The YouTube video linked in [windows-wheel-interactions doc](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/windows-wheel-interactions.md) is still private.

**Comment by Karl-Bridge-Microsoft** [comment]
> The YouTube video linked in [windows-wheel-interactions doc](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/windows-wheel-interactions.md) is still private.

Thanks. Video links have been deleted.
