### ISSUE TITLE
AsyncStatus is always started if IAsyncAction already completed before calling wait_for

### ISSUE THREAD

**Issue by minjiew88** [MicrosoftDocs/windows-uwp#3839]
[Enter feedback here]
Hi,
I have one question about this sample:
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#asynchronous-timeouts-made-easy

int main()
{
    IAsyncAction async = ...
 
/* Question: here
if the IAsyncAction already finished before async.wait_for(5s) was called, how to handle this scenario? 
For example:
 IAsyncAction async finished in 1ms. But async.wait_for(5s) called after 2ms later. Then the function will still wait for 5s as designed? 
*/
    if (async.wait_for(5s) == AsyncStatus::Completed)
    {
        puts("done");
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [Advanced concurrency and asynchrony with C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency-2#asynchronous-timeouts-made-easy)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @minjiew88, **wait_for** waits synchronously for the action to complete, *or* for the specified timeout. In that code example, it waits 5 seconds at the most (but waits less than that long if the asynchronous operation completes before that).

-Steve
