### ISSUE TITLE
Check if notifications is disabled but in python

### ISSUE THREAD

**Issue by theAbdoSabbagh** [MicrosoftDocs/windows-uwp#3845]
Is it possible to check whether notifications is disabled (app or overall), so that I can skip the notification and do something else? I would prefer to be able to check before trying to show the notifications rather than checking retrospectively if the notification was shown or not, in python?

**Comment by drewbatgit** [comment]
@Sxvxgee Hi, the github issues in the documentation repos are solely intended for feedback specifically related to documentation. For developer support, I suggest you open an issue on the [Microsoft Q & A site](https://docs.microsoft.com/en-us/answers/products/) where support engineers can help you with your question.
