### ISSUE TITLE
MS never gives what promises

### ISSUE THREAD

**Issue by vassiliospallis** [MicrosoftDocs/windows-uwp#3846]
"The Amazon Appstore on Windows (a requirement for running Android apps on Windows 11) is currently only available in the US."
Yes, but when you advertised Windows 11, you didn't mention this small detail....
Only US? Why?
What's the problem to have it worldwide?
So, Windows 11 is out for about 8 months and Android apps still not working unless: 

1. You live in US.
2. You change the region to US.
3. You apply for a Windows Insider.
4. Betas betas betas (Beta Amazon AppStore, Beta Android Subsystem) for years.

You should be ashamed...
Just for once, give something you promise, completed.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by infinitepower18** [comment]
If I'm not mistaken you don't need to be an insider to install the subsystem. But yes the region setting must be US to download it.

**Comment by infinitepower18** [comment]
Latest update, they plan to make WSA and Amazon Appstore available in France, Germany, Italy, Japan, and the United Kingdom, by the end of this year https://blogs.windows.com/windowsdeveloper/2022/05/24/microsoft-store-grows-with-the-developer-community/

**Comment by mattwojo** [comment]
@vassiliospallis / @infinitepower18 - Yes, currently the Amazon Appstore on Windows is still a Beta program in the testing phases. As mentioned above, there are plans to continue rolling out availability more broadly as the program continues towards a General Availability release, but I have not heard a date for that yet.
I'm closing this issue as it doesn't appear to require an update to the documentation, but if you would like to stay up to date on when the Amazon App Store on Windows will be available in various regions of the world, as well as other updates on the program, like when it will reach General Availability, you can sign up to receive notifications on this page: https://developer.amazon.com/apps-and-games/appstore-on-windows-11
