### ISSUE TITLE
Content rating if webview is used!

### ISSUE THREAD

**Issue by j-xpro** [MicrosoftDocs/windows-uwp#385]
If I am using webview in my app, for allowing users to download files. Basically capturing URLs! Do I need to tick yes for the question "Is the app a web browser or search engine"? Note I am not navigating any links to the webview rather than the default browser, user opens the webview control with its own consent!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c961b56-658b-039e-818b-5457cd10f793
* Version Independent ID: f19fe42a-ec37-f8ec-9e48-a468c9df4e82
* Content: [Age ratings - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/age-ratings)
* Content Source: [windows-apps-src/publish/age-ratings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/age-ratings.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
To get more info that helps you understand how to answer this question (or any question), click the info icon next to that question (from within the questionnaire). I'll make a note of that in this topic.
