### ISSUE TITLE
Run Android app with bluetooth on windows 11

### ISSUE THREAD

**Issue by salitbl** [MicrosoftDocs/windows-uwp#3851]
Hi , 
I am trying to run android app on win 11 with Windows Subsystem for Android.
My app using connection to ble device (Not Audio device).
I am starting to scan ble devices and app is going to bluetooth setting in windows.
Is Windows Subsystem for Android supporting connection and communication with bluetooth device (Not Audio device)?
Thank you,
Salit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/#test-and-debug)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@hamza-usmani -- Do you know the answer to this question?

**Comment by hamza-usmani** [comment]
Hi, currently in Windows Subsystem for Android bluetooth functionality such as scanning for BLE devices is not supported.

**Comment by mattwojo** [comment]
Added a note about this: https://github.com/MicrosoftDocs/windows-uwp/commit/077f275d07234c6ac5585e9805a8dc656495130f

Closing. Thanks for bringing this to attention.

**Comment by salitbl** [comment]
@[hamza-usmani](https://github.com/hamza-usmani) Do you know if scanning for BLE devices will be supporting in  Windows Subsystem for Android?
 if yes, when it will be available ?

**Comment by salitbl** [comment]
Do you know if scanning for BLE devices will be supporting in Windows Subsystem for Android?
