### ISSUE TITLE
cmdline parameter values

### ISSUE THREAD

**Issue by MikeLippUnity** [MicrosoftDocs/windows-uwp#3853]
Please provide example of an actual cmdline parameter being used. Not sure if there is a space or '=' after the switch, before the value (or either?)

Not sure which to use from documentation:
a) PowerToys.Awake.exe --time-limit 36000
b) PowerToys.Awake.exe --time-limit=36000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20e555a-65ad-82e7-e1c0-f6577c1322b2
* Version Independent ID: 29236a0e-82e8-92d7-a5fb-12a9a777bcc2
* Content: [PowerToys Awake utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/awake)
* Content Source: [hub/powertoys/awake.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/awake.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@Jay-o-Way - is this something that you can help with? :)

**Comment by Jay-o-Way** [comment]
Good question. Passing on to @dend.

**Comment by dend** [comment]
@Jay-o-Way @mattwojo hello friends. I can help with this request later this week.

**Comment by mattwojo** [comment]
Thanks @dend! I'm available to make updates if you prefer -- just need clarity on the correct format in question.

**Comment by mattwojo** [comment]
Thanks for raising this question @MikeLippUnity -- apologies for the slow response. Just confirmed that both of the values for time limit that you asked about are valid. I've just submitted a PR to add this to the Awake documentation.
