### ISSUE TITLE
wsl2-ubuntu-nodejs

### ISSUE THREAD

**Issue by mohamad-rai** [MicrosoftDocs/windows-uwp#3862]
I installed nvm as you recommended to use nodejs. everything was fine in installation and work with nodejs but there was a problem in my project. I'm using `dotenv` package in some of my scripts; something like this `dotenv -e .env -- npx prisma migrate dev` and get `exec format error` on `dotenv`.

also, you recommend installing nodejs only on windows or only on wsl but to fix my problem, I installed it on both of them to be able to run that command I mentioned above, otherwise, it didn't work in ubuntu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#feedback)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing this @mohamad-rai! I'm not quite clear on the issue or what you're proposing as the fix.  Is this the same issues as https://github.com/microsoft/WSL/issues/8151? 
I'm wondering if your use of the `dotenv` package goes a bit beyond the scope of this getting started with Node content... just trying to better understand how I might update the docs here to help other users. Are you suggesting that the docs recommend installing nodejs on both Windows and WSL... and is that only in the case of using the dotenv package? Are you suggesting that we add a note specific to the dotenv package? 
Or should we keep this issue focused to the dotenv and wsl repos for a fix?

Any further clarification is appreciated! Thanks again for filing.
