### ISSUE TITLE
Inside .NET Native (Channel 9 Video) link is broken.

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#3863]
The link to "Inside .NET Native (Channel 9 Video)" no longer works.

Most likely caused by the shutdown of Channel 9, although it would be nice for the Windows developer community to recover the video into Microsoft Learn and fix the broken link to the new location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf92aac8-cd71-d8f4-1a97-9ca935590849
* Version Independent ID: f7ea40a6-3af2-39e4-7a74-3080977c1a66
* Content: [.NET Native and Compilation - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/net-native-and-compilation)
* Content Source: [windows-apps-src/dotnet-native/net-native-and-compilation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/dotnet-native/net-native-and-compilation.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @pjmlp, I've removed that bit of text (the link was removed some time in the past, leaving only text). Only videos made since 2017 have been preserved; this one was 3 years prior to that.

-Steve
