### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by VigneshVoid** [MicrosoftDocs/windows-uwp#3866]
![image](https://user-images.githubusercontent.com/17567708/171341214-df76423d-94c5-48af-a63b-5a465a830265.png)

https://github.com/microsoft/WinUI-Gallery/tree/main/XamlControlsGallery/ControlPagesSampleCode/SystemBackdrops
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65803f08-867d-f4f8-0d32-53217e8640fa
* Version Independent ID: f0a73317-3de2-aa13-e0a8-0517a4ca52be
* Content: [Preview release channel for the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#version-11-preview-3-110-preview3)
* Content Source: [hub/apps/windows-app-sdk/preview-channel.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/preview-channel.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! Link has been updated.
