### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by lxgdark** [MicrosoftDocs/windows-uwp#387]
A huge part of the articles began to appear in English, although they have a version in Russian!
I ask you to correct this.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f9a5cd25-def9-18f4-71f4-ecdfa83d03d6
* Version Independent ID: acfde4a4-e53b-0adb-d1fc-179f9c055553
* Content: [Store and retrieve settings and other app data - UWP app developer](https://docs.microsoft.com/ru-ru/windows/uwp/design/app-settings/store-and-retrieve-app-data)
* Content Source: [windows-apps-src/design/app-settings/store-and-retrieve-app-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/app-settings/store-and-retrieve-app-data.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by ginami** [comment]
Thank you @lxgdark for your feedback! I'm checking on the status of the Russian version and I will let you know what I find out.

**Comment by mijacobs** [comment]
Hi @lxgdark, currently, the site navigation menu is translated to Russian, but the article contents are not. We've passed your feedback on to our localization team.
