### ISSUE TITLE
Page shows reference to .net5, which is out of support.  Should be updated to .net6

### ISSUE THREAD

**Issue by JesseCol** [MicrosoftDocs/windows-uwp#3871]
This page shows a reference to .net5, which I believe is out of support.  Can we change this to .net6?

Also I believe the screenshots are using VS2019.  Can we update them to VS2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 project - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you! The reference is in that image, right? The content of that image was redundant (and not searchable), so to make the topic more economical to maintain, I removed the image, and added more context to the (searchable) syntax. I did the same thing to another topic that was using the same image. This way we won't need to keep updating topics every time the supported version of .NET changes.

Speaking of economy, I'll circle back in future to update the other screenshots here (if the VS UI has changed) when there's bandwidth to do so. In the meantime, feel free to use the open authoring system described here: https://review.docs.microsoft.com/windows-authoring-guide/quickstart?branch=main.

-Steve
