### ISSUE TITLE
WinUI 2 / 3 / WinAppSDK reorg broken links, regressions

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/windows-uwp#3872]
From [Twitter](https://twitter.com/WindowsDocs/status/1532392168584646657):
> To reflect how [#WinUI](https://twitter.com/hashtag/WinUI?src=hashtag_click) and the [#WindowsAppSDK](https://twitter.com/hashtag/WindowsAppSDK?src=hashtag_click) have evolved, we've decoupled the WinUI3 and WinUI2 API docs and merged WinUI3 into the [#WinAppSDK](https://twitter.com/hashtag/WinAppSDK?src=hashtag_click) docs. Let us know what you think.

This change--I couldn't immediately find the commit in the commit log--has broken all the "equivalent class" interior links throughout the docset(s). This is a big regression and makes finding useful WinUI documentation much more difficult.

Steps to reproduce:
1. Open https://docs.microsoft.com/uwp/api/windows.ui.xaml.visualstatemanager?view=winrt-22621
2. Click `Equivalent WinUI class: Microsoft.UI.Xaml.VisualStateManager` link
3. Observe 404

cc: @asklar @stevewhims @Karl-Bridge-Microsoft

**Comment by MattBDev** [comment]
Now I know why I was getting so many 404 errors.

**Comment by riverar** [comment]
@Karl-Bridge-Microsoft @asklar @stevewhims Would be great to at least get an ack. on this highly visible issue.

**Comment by Karl-Bridge-Microsoft** [comment]
@riverar - thanks for following up on this. We’re trying to resolve a few expected and unexpected issues with this migration. Stay tuned.

**Comment by riverar** [comment]
@Karl-Bridge-Microsoft @stevewhims Is this something we can bump the priority for? Or revert and revisit later? This continues to impact production docs, broken links everywhere.

**Comment by Karl-Bridge-Microsoft** [comment]
@riverar - sorry, no revert.

Unfortunately, our doc build pipeline is broken at the moment, which is stopping us from pushing docs with updated links.

**Comment by Karl-Bridge-Microsoft** [comment]
These broken link issues should be fully resolved. Please open a new issue if you're still encountering broken links.

Thanks.
