### ISSUE TITLE
Need clarification on settings in custom-layouts.json (ex zones-settings.json) file

### ISSUE THREAD

**Issue by Korb** [MicrosoftDocs/windows-uwp#3875]
Currently, after creating a grid of two columns and three rows in the layout editor, the following entry appears in the file:

```
      "type": "grid",
      "info": {
        "rows": 3,
        "columns": 2,
        "rows-percentage": [
          3444,
          3445,
          3111
        ],
        "columns-percentage": [
          4943,
          5057
        ],
        "cell-child-map": [
          [
            0,
            3
          ],
          [
            1,
            4
          ],
          [
            2,
            5
          ]
        ],
```
This is puzzling because "**percentage**" in the case of screen division assumes a range from 0 to 100. Manually changing the values ​​to 0 and 50 / 50 and 100 / 50 and 50 for columns and similar triads for rows led to the creation of small zones in the left top corner of the screen. A comment directly in this file or in the help system would be helpful.

Upd. if too large values are entered, the FancyZones module does not work, and launching the editor causes the following error (russian):

> Ошибка анализа данных редактора. Произошла ошибка при анализе настраиваемых макетов.

When entering values with the % symbol, an error is displayed:

> Ошибка анализа данных редактора.
> '%' is an invalid end of a number. Expected a delimiter.
> Path: S.custom-Iayouts[0].info | LineNumber: 10 | BytePositionlnLine: 12.

**Comment by mattwojo** [comment]
Thanks for filing @Korb, but this does not appear to be an issue with the documentation, but rather that it may be a but within FancyZones. Could you please file this issue in the PowerToys product repo here? > https://github.com/microsoft/PowerToys/issues/new/choose

Closing the issue from the MicrosoftDocs repo, but please reopen if I'm mistaken and this is indeed a matter of updating the documentation. 

Thank you for contributing!

**Comment by crutkas** [comment]
Directly editing the json, while possible, is not something we encourage.  As of now, it is not something we would directly document as we could break it from release to release.
