### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/windows-uwp#3877]
the link is broken at

> be part of the [Microsoft Affiliate Program](https://www.microsoftaffiliates.com/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784ae922-b4ec-4e0e-78a9-d529f9ae8dda
* Version Independent ID: bc000ff6-d301-45c2-3c57-3961612081f4
* Content: [Microsoft Store marketing guidelines for apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-marketing-guidelines)
* Content Source: [windows-apps-src/publish/app-marketing-guidelines.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-marketing-guidelines.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Links have been corrected, thank you.
