### ISSUE TITLE
multiple app packages for windows 10 should have same capabilities?

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#388]
when uploading my uwp app packages to the store, if I want to have multiple packages lets say a package for each sdk and each device family seperately. 
e.g

**creators update :** Desktop package, mobile package, hololens, xbox.

**Fall creators update**: Desktop package, mobile package, hololens, xbox.

so for example my app wants to target latest 3 SDKs and 4 device families, so now I want to upload **4x3 = 7** app packages to the store.

Now my question is why do I need to have same capabilities and resources for all these packages? because the reason I have seperate packages for each device family and each sdk is because some of those packages will need **different capabilities** and also might have different resources, so can I have them different or do I need to have them exactly the same?

Source : https://docs.microsoft.com/en-us/windows/uwp/publish/app-package-requirements

Source Text :

If your app has more than one package, these app manifest elements must be the same in each package (**per targeted OS**):

- Package/Capabilities

- Package/Dependencies

- Package/Resources

>This **per targeted OS** confuses me, does it mean same capabilities etc for all windows 10 os versions? or can I have same resources for all device family packages on one windows 10 OS version? and have different resources for other OS ( sdk) version of windows 10? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c1313b6-1ee4-549c-d939-2f4580a8c561
* Version Independent ID: db5c3eee-28d5-c527-9bfe-3c4e5f2f0b6f
* Content: [App package requirements - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/app-package-requirements)
* Content Source: [windows-apps-src/publish/app-package-requirements.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-package-requirements.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I'm sorry it's taken a while to respond. It's actually not a requirement that these elements be the same with different packages such as in your example. You should be able to upload packages that have different capabilities, resources, etc. in that scenario. If we detect any problems with your packages, we'll show validation errors/warnings so you can address the issues. I am still confirming the exact details for the requirements and will update this page soon - I'll close out this issue once that has been done.

**Comment by JnHs** [comment]
Confirming that we've updated this topic and the text you had asked about no longer appears, as it is no longer a requirement - Thanks for bringing this up.
