### ISSUE TITLE
Following the instructions for unpackaged WinUi 3 App does not produce a runable program

### ISSUE THREAD

**Issue by katdti** [MicrosoftDocs/windows-uwp#3885]
See more information her:
   https://developercommunity.visualstudio.com/t/Create-Your-First-WinUi-3-App-Sample-No/10071607

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 (Windows App SDK) project - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @katdti, and sorry for the delay in responding. I've been investigating the issue, and here's the latest thing I've tried/discovered:

1. I uninstalled all Windows App SDK VSIXes and runtimes.
2. I downloaded and ran the 1.1.2 installer (which installs runtimes and VSIXes). That's the latest stable version of the Windows App SDK.
3. Then I followed along with the **Non-MSIX-packaged** section of this topic. I followed it for a C# and a C++ project.

Upon creating each new project, the project was initially targeting 1.0.3 (even though I ran the 1.1.2 installer). And then, yes, I do get runtime exceptions with both projects. However, if I manually retarget/update the NuGet packages that the projects are referencing to 1.1.2, then the projects run as expected.

So I've added that extra info to the topic about retargeting (if necessary). I'll close this issue now. If there are still issues with the topic, then feel free to create a new issue.

Thanks!
-Steve
