### ISSUE TITLE
"Install PowerShell using Winget" doesn't work

### ISSUE THREAD

**Issue by davetapley** [MicrosoftDocs/windows-uwp#3889]
_Probably_  issue with `winget`, but cross-posting here just in case, see: https://github.com/microsoft/winget-cli/issues/1826#issuecomment-1158239573

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Thanks @davetapley. Can you clarify... is this the version of PowerShell that you are seeking to install?
![image](https://user-images.githubusercontent.com/7566797/174352409-01cd9a50-2dba-4834-8212-945fd1477eb5.png)

**Comment by davetapley** [comment]
Aha, I see the problem. [The docs](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#winget) say to use `Microsoft.PowerShell`, but that gives `No package found matching input criteria`.

@mattwojo using just `powershell` as you showed works ✅

**Comment by davetapley** [comment]
Also I just realized I opened this on the wrong repo!
