### ISSUE TITLE
None of third party uri schemes are working in windows mixed reality cliff house. 

### ISSUE THREAD

**Issue by Cka3** [MicrosoftDocs/windows-uwp#389]
When trying to launch any link from my app with uri like discort:// or other 'uri'(registered in system) it says that there is no app for that (it works just fine on desktop, but not in cliff house).
For 'reserved'  uri  like ms-chat, mailto, ms-people: and so on it works just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a571d8-0fc8-74d6-52d8-53d72acbff46
* Version Independent ID: b15dea61-6c14-e7b0-0c2b-671772963a90
* Content: [Reserved file and URI scheme names - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/reserved-uri-scheme-names)
* Content Source: [windows-apps-src/launch-resume/reserved-uri-scheme-names.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/reserved-uri-scheme-names.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by GrantMeStrength** [comment]
Assigning to Matt, who has some contacts in the MR team.

**Comment by mattwojo** [comment]
@Cka3 -- Apologies for the long delay on addressing this issue! Slipped through the cracks and I'm just seeing it for the first time. Could you confirm whether this is still an issue that you are encountering?  If so, I'll see if I can find someone on the mixed reality team to help address.

**Comment by mattwojo** [comment]
Also going to close this issue in the current repo and will move to https://github.com/MicrosoftDocs/mixed-reality/issues if it is still persisting. 
Thanks and so sorry that we weren't able to address this right away.
