### ISSUE TITLE
TV Episodes

### ISSUE THREAD

**Issue by treeofshabadoo** [MicrosoftDocs/windows-uwp#3896]
I can't use the powerRename function to rename TV show episodes because of the space and the Brackets it adds to enumerations. Can you please add a check box to leave that out. I just want normal enumeration.

**Comment by Jay-o-Way** [comment]
Thanks for the message, but this repository is about the documentation. Head over to https://github.com/microsoft/PowerToys to create an issue there.

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. Not a doc issue.
