### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by KasperHoldum** [MicrosoftDocs/windows-uwp#390]
"DeviceInformation devInfo = deviceInformationCollection[midiOutPortListBox.SelectedIndex];"
While going over input devices it refers to the 'midiOutPortListBox'. I believe this shoudl be 'midiInPortListBox'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi#feedback)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this error. This has now been corrected.
