### ISSUE TITLE
Is there a code somewhere

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/windows-uwp#3901]
Things on this page get confusing mostly with the names of each product. I'm not sure what this article seems to consider the service project to be. It is contained in an app to run in proc but I think the containing app is referred to as the service which it's not. Making it worse the article describes getting the package family name from the package manifest fie in the service project but the project type this article calls to create for the service doesn't have a manifest file. So I'm assuming the package family name you need is of the containing UWP project through which you'll make the call?

-
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edde9dbc-6e04-69cf-206e-123792666abf
* Version Independent ID: 9894e78f-3270-9485-4769-11050669b805
* Content: [Create and consume an app service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Closing this and handling your question in the other [issue](https://github.com/MicrosoftDocs/windows-dev-docs/issues/3902) you opened for this page.
