### ISSUE TITLE
Cannot start react native for windows following instructions

### ISSUE THREAD

**Issue by sikora507** [MicrosoftDocs/windows-uwp#3906]
Cannot start react native for windows following instructions

`npx react-native init <projectName> --template react-native@^0.68.0`
This should fix it.
Currently there's a newer prerelease version which seems to be broken. You need to manually specify template.
https://microsoft.github.io/react-native-windows/docs/getting-started

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334f14ad-5cb9-8894-44e7-2edb79b1bde1
* Version Independent ID: c66e9e5f-96b6-d2ad-ecbc-7ff6363da7e6
* Content: [React Native for Windows desktop app development](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/react-native-for-windows)
* Content Source: [hub/dev-environment/javascript/react-native-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/react-native-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This issue has been around a long time, so the React versions have all changed since it was opened. We don't want to refer to specific versions in the docs because it is difficult to maintain. We did add a line about how to specify a version and linked to the React Native doc version list.
