### ISSUE TITLE
appUriHandlers and ShellExecuteEx

### ISSUE THREAD

**Issue by madaster97** [MicrosoftDocs/windows-uwp#3908]
Hi there, I was wondering if someone could clarify what this section is trying to say, referring to setting up an http(s) app URI handler:
> This feature works whenever your app is a UWP app launched with [LaunchUriAsync](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchuriasync) or a Windows desktop app launched with [ShellExecuteEx](https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shellexecuteexa). If the URL corresponds to a registered App URI handler, the app will be launched instead of the browser.

Is this saying that both UWP and Windows Desktop apps can be launched in this way? 

If so, is there any documentation on how a Windows desktop app can register for one of these schemes? I've been trying to build an app this way using [Tauri](https://github.com/tauri-apps/tauri) but am very stuck.

Thanks,
Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e251da-3cab-4aa0-2915-21189cf71bef
* Version Independent ID: b244b311-a0e5-185d-df82-1dadf3fe6416
* Content: [Enable apps for websites using app URI handlers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking)
* Content Source: [windows-apps-src/launch-resume/web-to-app-linking.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/web-to-app-linking.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by madaster97** [comment]
Hi @alvinashcraft - say you self assigned to this. Do you have any ideas or references I could look at for this?

Thanks!
Adam

**Comment by alvinashcraft** [comment]
Hi Adam @madaster97,

I self-assigned this when I saw it came in for one of the topics that I own. Sorry I haven't replied sooner.

The information in this topic is specific to UWP apps. There are some things you can do to launch any EXE with a custom URI scheme in Windows, but it's not officially supported or documented here. I did some searching just now for solutions to launch an EXE with a custom URI scheme and found results that provide example registry entries to do this. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) also offer timely answers to a multitude of technical questions in the UWP area and may be able to provide some answers here.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation.

**Comment by madaster97** [comment]
Thanks Alvin @alvinashcraft , here's the link:
https://docs.microsoft.com/en-us/answers/questions/947043/https-appurihandler-for-shellexecuteex-application.html

I'll re-open this or submit a PR if there's anything to report from over there.
