### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by themark712** [MicrosoftDocs/windows-uwp#3911]
Doesn't work. Nice try Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5835d670-bb0f-1f70-5ca3-118343cce487
* Version Independent ID: fd9788d6-6c38-cc25-7790-1095a1f46067
* Content: [Create Android app with Xamarin.Android](https://docs.microsoft.com/en-us/windows/android/xamarin-android)
* Content Source: [hub/android/xamarin-android.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/xamarin-android.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
It looks like there's no actionable feedback here, so I'll go ahead and close the issue. Please open a new issue if you have specific feedback about the documentation that you'd like us to address. For creating new apps for Android, we'd recommend trying the new .NET Android project type, replacing Xamarin.Android. https://visualstudio.microsoft.com/vs/android/
