### ISSUE TITLE
Windows app icon article is missing from TOC

### ISSUE THREAD

**Issue by adegeo** [MicrosoftDocs/windows-uwp#3912]
This article isn't in the docset TOC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e654b00d-a948-3f1b-1ad0-9da4f25bb17a
* Version Independent ID: defdfc1d-ee32-9b63-e62e-cd6f9619a8c0
* Content: [App icons and logos - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/style/app-icons-and-logos)
* Content Source: [hub/apps/design/style/app-icons-and-logos.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/style/app-icons-and-logos.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Thraka** [comment]
I just ran into this article again during research and it's still not in the TOC 😁

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @adegeo - this topic was removed from the TOC in a related TOC/feature reorg (https://github.com/MicrosoftDocs/windows-dev-docs-pr/pull/2514/files). 

Because of this, I believe this topic should be deleted from the doc set and a redirect added. I'll complete this today.
