### ISSUE TITLE
 1.1.2 release notes missing 

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#3913]
v1.1.2 landed yesterday but there are no release notes for it.
Cc @gabbybilka 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59ede3ef-13f3-4f3f-6121-68ffca257563
* Version Independent ID: e8c46a28-876c-bd67-3ab7-18294f5d068c
* Content: [Stable channel release notes for the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-11)
* Content Source: [hub/apps/windows-app-sdk/stable-channel.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/stable-channel.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @gabbybilka
* Microsoft Alias: **gabilka**

**Comment by stevewhims** [comment]
Thanks, @dotMorten, they're there now.

-Steve
