### ISSUE TITLE
Update What's New section

### ISSUE THREAD

**Issue by themerror** [MicrosoftDocs/windows-uwp#3917]
Hello.
In [What's New for developers in Windows 11](https://docs.microsoft.com/en-gb/windows/apps/whats-new/windows-11-build-22000), there are a few new WinRT APIs, whose link was in UWP section, such as [BluetoothLEConnectionParameters Class](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothleconnectionparameters?view=winrt-22621). So I suppose that Microsft should also add these kind of change to UWP docs to create a complete, unified experience.
Thanks.

**Comment by QuinnRadich** [comment]
The UWP "What's New" section reflects the historic additions to the platform in each release of Windows 10. While UWP apps can still utilize the new WinRT API surface changes if they target newer versions of the Windows SDK, we're not going to backport content from the Windows 11 "what's new" section over to that previous location - that creates duplicated sections in the docs, and might wind up causing more problems than it hopes to solve. We're keeping everything in a single location for now.

Thank you.
