### ISSUE TITLE
Generating Preinstall Package Instructions are Incorrect

### ISSUE THREAD

**Issue by scout208** [MicrosoftDocs/windows-uwp#392]
In the dev center dashboard, there is no **Request packages for OS preinstallation** section. 

![image](https://user-images.githubusercontent.com/9426329/37937498-8f15f508-311f-11e8-8782-c181747a3022.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b506ce7-3862-d621-921e-4efa2adca41c
* Version Independent ID: cdcd4735-43ae-1eb7-5e83-e3e889c27631
* Content: [Generate preinstall packages for OEMs - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/generate-preinstall-packages-for-oems)
* Content Source: [windows-apps-src/publish/generate-preinstall-packages-for-oems.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/generate-preinstall-packages-for-oems.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
This section should be present if your account has the appropriate permissions. If you're not seeing it, please email partnerops@microsoft.com.
