### ISSUE TITLE
distribute the msix package

### ISSUE THREAD

**Issue by dchillman123** [MicrosoftDocs/windows-uwp#3920]
A link on how to distribute the misx would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba9095f-57b4-267d-8896-5375c68b01ee
* Version Independent ID: 514d7e51-6f16-8199-aabf-26ee901a6ed3
* Content: [Use XAML Islands to host a UWP XAML control in a C# WPF app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @dchillman123, and thanks for filing this issue. In this topic, and in 4 others, I've added a link to [Manage your MSIX deployment](https://docs.microsoft.com/windows/msix/desktop/managing-your-msix-deployment-overview).

Thanks!
-Steve
