### ISSUE TITLE
Winget is not installed on Windows 11 by default, I have windows 11 and its not here..

### ISSUE THREAD

**Issue by chadleywilson** [MicrosoftDocs/windows-uwp#3921]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://docs.microsoft.com/en-gb/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
It's there -- may just not be where you're looking for it? 
Try opening PowerShell and entering `winget --version`.
Winget is included in something called "App Installer" in Windows 11. You can also check to see if you have App Installer by opening PowerShell and entering: `Get-AppxPackage microsoft.desktopappinstaller`
You will see "Status: OK" at the bottom if you have it as well as a version # for App Installer... the version # should be greater than 1.11.11451. If it's not, following the instructions here: https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting#executing-winget-doesnt-display-help

Closing. Duplicate issue of https://github.com/MicrosoftDocs/windows-uwp/issues/3706
