### ISSUE TITLE
Necessary steps are missing in the page about adding WASDK to an existing project.

### ISSUE THREAD

**Issue by dhoehna** [MicrosoftDocs/windows-uwp#3922]
This page does not mention a few key items needed in a project.  This causes a project to fail either at compile time or runtime and diagnosing the issue is difficult.

DUPE OF THIS ISSUE IS HERE: [See Here](https://github.com/microsoft/WindowsAppSDK/issues/2675)

What is missing is
    1. CppWInRt package needs to be installed.
    2. `PackageDependency` to the framework package needs to be added.

If the CppWinrt package isn't installed the compiler can't find any windows app sdk headers.

If the package dependency isn't added to the manifest, developers hit a "Class not registered" error when using a windows app sdk component.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3c25ae7-3c9f-3193-7968-dec170aedcf2
* Version Independent ID: d55e2acd-b7ee-7cbf-cccb-aebc828cb714
* Content: [Use the Windows App SDK in an existing project - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project)
* Content Source: [hub/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
I made a few changes to the docs (as we discussed, directing folks to the right places depending on whether they want a WinUI 3 project or not). And I also addressed this issue, adding a short "Further info" section to this topic.

But I feel like this tactical update is temporary, until I understand more about the scenarios in which that dynamic dependency is needed. I've left the section hopefully helpful for those who run into it (by mentioning the error message), but intentionally vague for those who won't (by not mentioning the exact repro steps, which I don't yet know). Perhaps we can continue the discussion internally until we can enhance the info here in due course.

Thanks!
-Steve
