### ISSUE TITLE
This Intro to RUST on Windows is really working!

### ISSUE THREAD

**Issue by Serge-Faehrlich** [MicrosoftDocs/windows-uwp#3923]
Great job guys.

In contrast to other intros to get to the first RUST project, this one really works.
(Other MSFT intros to setup RUST env failed)
//HEINZ
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Serge-Faehrlich!

-Steve
