### ISSUE TITLE
Missing step about removing WinUI SDK reference.

### ISSUE THREAD

**Issue by dhoehna** [MicrosoftDocs/windows-uwp#3924]
[See this bug here](https://github.com/microsoft/WindowsAppSDK/issues/2671)

Setting `WindowsPackageType` to `none` gives two cryptic errors

    1. `"Visual C++ 2015-2019 Runtime for Universal Windows Platform Apps v14.0" which targets platform "UAP"`
    2. `Project "AppLifeCycleTest" targets platform "Windows", but references SDK "Visual C++ 2015-2019 UWP Desktop Runtime for native apps v14.0" which targets platform "UAP"`

The solution to remove these errors is to Include <WinUISDKReferences>false</WinUISDKReferences> in the .*proj file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a490a57-1f12-5646-2906-dca6ead89518
* Version Independent ID: 7ea6aaad-bf8d-2a2e-3012-11e8e2ebe917
* Content: [Tutorial—Use the bootstrapper API in a non-MSIX-packaged app that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=csharp)
* Content Source: [hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @dhoehna. I've published a change to the [Tutorial](https://docs.microsoft.com/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment) topic. The note might have implied that setting `<WindowsPackageType>None</WindowsPackageType>` is all you have to do. But there's a bit more to it, so I've made it clearer that you really have to follow the link to [Create your first WinUI 3 project](https://docs.microsoft.com/windows/apps/winui/winui3/create-your-first-winui3-app).

I then went to [Create your first WinUI 3 project](https://docs.microsoft.com/windows/apps/winui/winui3/create-your-first-winui3-app), and followed the steps again with a C# and a C++/WinRT project, but I didn't see the error messages you mention.

If there is an issue with the steps on that other topic, it'd be great if you could leave feedback on that one (or mail me direct) with more details: which steps, what language (C# or C++), stuff like that.

Thanks!
-Steve

**Comment by dhoehna** [comment]
Spoke offline.

IDE: VS 2022 Enterprise.  I'm guessing this'll show up for all editions of VS2022.  Haven't tried with VS 2019.
Project: C++ console application.  

I haven't tried this with C#.
