### ISSUE TITLE
Drawing floating icons/widgets not supported by WSA

### ISSUE THREAD

**Issue by fedes1to** [MicrosoftDocs/windows-uwp#3926]
Drawing floating icons/widgets not supported by WSA, tried with many different applications.

Permission to draw in other apps is pointless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing this @lbertitoyt. I think this is a bit specific to call out in this doc, but would be really helpful feedback for the WSA dev team. Would you mind filing it in Windows Feedback Hub?
>> Select Windows key + F to launch Feedback Hub and Use the category **Apps > Windows Subsystem for Android™️**. Provide as many details as possible regarding the issue. 

Thanks! Closing this issue on the docs.
