### ISSUE TITLE
Forget to add ":" to Arguments="----AppNotificationActivated", which lead to register failed.

### ISSUE THREAD

**Issue by wei111333** [MicrosoftDocs/windows-uwp#3927]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0e5014-68c8-fb33-bf35-117c7b217c56
* Version Independent ID: 0c0e5014-68c8-fb33-bf35-117c7b217c56
* Content: [Quickstart App notifications in the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs)
* Content Source: [hub/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @vaheeshta
* Microsoft Alias: **vmehrshahi**

**Comment by vaheeshta** [comment]
Great catch! Fixed [here](https://github.com/MicrosoftDocs/windows-uwp/commit/3ab675212d79522c403d70f594c53aa0925bd5d9).
