### ISSUE TITLE
How can this stuff be done for Javascript/HTML apps?

### ISSUE THREAD

**Issue by samjross** [MicrosoftDocs/windows-uwp#393]
The article doesn't explain how to access or use these APIs from Javascript/HTML apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8f3945-fed8-9d31-b718-6d17593dba18
* Version Independent ID: 174db112-dc0f-1f75-84d2-fc7668e2171a
* Content: [Download and install package updates for your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates?f=255&MSPPError=-2147217396#mandatory-dashboard)
* Content Source: [windows-apps-src/packaging/self-install-package-updates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/self-install-package-updates.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you for your feedback. The same APIs mentioned in the article are available for JavaScript apps and (apart from JavaScript-specific syntax) the APIs are used in the same manner.
