### ISSUE TITLE
Video is marked private and doesn't display

### ISSUE THREAD

**Issue by jlukosky** [MicrosoftDocs/windows-uwp#3934]
The video under "Run accessibility testing tools" doesn't display. Instead, there's a message from YouTube: "This video is private"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7311500-9e32-4558-8108-728a9dfbff8a
* Version Independent ID: c466a80f-93b9-b58b-317d-72217a17e5b6
* Content: [Accessibility testing - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/accessibility/accessibility-testing)
* Content Source: [hub/apps/design/accessibility/accessibility-testing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/accessibility/accessibility-testing.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @jlukosky - topic has been updated and video link revised.
