### ISSUE TITLE
a typo? in "desktop-winui3-app-with-basic-interop.md"

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/windows-uwp#3939]
Hi!
In very basic document, "desktop-winui3-app-with-basic-interop.md";
In "Code" section, "4."
it says;
"In the MainWindow.xaml.cs code-behind file, add the using static PInvoke.User32; directive."
but I think it should be;
"In the App.xaml.cs code-behind file, add the using static PInvoke.User32; directive."
because the method SetWindowDetails() where hwnd is consumed is located App.xaml.cs.
Do I misunderstanding?

**Comment by stevewhims** [comment]
Thanks, @vmx17. Yes it looks like you need PInvoke.User32 to call functions such as SetWindowPos. So I've moved that sentence.

Thanks!
-Steve
