### ISSUE TITLE
Please add examples of what versionTag value should be...

### ISSUE THREAD

**Issue by rtischer8277** [MicrosoftDocs/windows-uwp#3942]
...including error codes that will occur if versionTag is incorrect. Also, where in VS's Nuget does one get the versionTag? or number? I tried **1.1.2** and got **80070057 The parameter is incorrect**. Also tried **10.0.25158-preview** which is my installed **Microsoft.Windows.SDK.BuildTools** but got **80070057 The parameter is incorrect**. Leaving *versionTag* blank gets you **80070491 There was no match for the specified key in the index**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a490a57-1f12-5646-2906-dca6ead89518
* Version Independent ID: 7ea6aaad-bf8d-2a2e-3012-11e8e2ebe917
* Content: [Tutorial—Use the bootstrapper API in a non-MSIX-packaged app that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=csharp)
* Content Source: [hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rtischer8277. There's a link in this topic (in Step 5 of the C# instructions) to "the Bootstrapper API". That takes you to a topic named "Use the Windows App SDK runtime for non-MSIX-packaged apps", when then takes you to the topic for the MddBootstrapInitialize function. That topic has more info, and examples, about its parameters, and it also contains a link to a topic documenting Bootstrapper API constants.

-Steve
