### ISSUE TITLE
[Typo] Missing Closing Parenthesis Breaks Markdown Link 

### ISSUE THREAD

**Issue by AnthonyCxx** [MicrosoftDocs/windows-uwp#3944]
Document: [Windows > App > Desktop > Design > Commanding Basics](https://docs.microsoft.com/en-us/windows/apps/design/basics/commanding-basics)
Subsection: [Place Commands on the Right Surface](https://docs.microsoft.com/en-us/windows/apps/design/basics/commanding-basics#place-commands-on-the-right-surface)

Under [_Place Commands on the Right Surface_](https://docs.microsoft.com/en-us/windows/apps/design/basics/commanding-basics#place-commands-on-the-right-surface), the link to _Command Bars and Menu Bars_ is missing a closing parenthesis, which breaks the link. The link is currently `[Command bars](../controls/command-bar.md`, but needs to be `[Command bars](../controls/command-bar.md)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7cfa35-53c5-af40-3c5a-4f31f6930d3f
* Version Independent ID: 148c533c-0606-99ac-4d97-36cba7e23f66
* Content: [Commanding basics - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/basics/commanding-basics)
* Content Source: [hub/apps/design/basics/commanding-basics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/basics/commanding-basics.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
The link is fixed.
