### ISSUE TITLE
How to access toast actions like buttons?

### ISSUE THREAD

**Issue by forderud** [MicrosoftDocs/windows-uwp#3945]
https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener provides a great starting point for programmatic access of toast notifications. However, the API surface for toast notifications seem rather limited. I'm only able to access the title and main text content, but not "actions" like buttons and similar.

Would it be possible to extend the documentation to also cover how to access toast actions like buttons?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1305c1a2-d0b1-6210-4ced-78a42ef19521
* Version Independent ID: ff5e9d03-1763-b501-2541-91abab2b7d9a
* Content: [Notification listener - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/notification-listener.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/notification-listener.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
