### ISSUE TITLE
Feedback forum is closed

### ISSUE THREAD

**Issue by infinitepower18** [MicrosoftDocs/windows-uwp#3946]
The [link](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore) given right before the table of contents points to a closed forum.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/44692189/179514452-79c5b5d9-ff74-4bd1-8252-595ee83f7a18.png">
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e47bfea-cf8e-d716-9880-6c15c31fcbdf
* Version Independent ID: ba95989d-2cb0-1644-7b38-24b2eab3b8c7
* Content: [Microsoft Store Policies - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/store-policies)
* Content Source: [windows-apps-src/publish/store-policies.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/store-policies.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Thanks for reporting this. The link has been updated to point to: https://docs.microsoft.com/en-us/answers/topics/partner-center-general.html
