### ISSUE TITLE
URL referrer / source

### ISSUE THREAD

**Issue by electro-logic** [MicrosoftDocs/windows-uwp#3947]
Do you have a referrer / source parameter that can be used to track the link in the partner dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f30bb9-d11a-1865-2d17-9c56cfc3e641
* Version Independent ID: ded22236-86fd-f4eb-f517-f3dd1005dc98
* Content: [Using ms-windows-store URIs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-store-app)
* Content Source: [windows-apps-src/launch-resume/launch-store-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-store-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to ask about this and we sincerely apologize for the delayed response. I asked some folks who work on Store documentation, and they do not believe this is available. However, if you would like to engage community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
