### ISSUE TITLE
mis spelled capability

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/windows-uwp#3950]
It seems that the capability listed on this page, packageWriteRedirectionCompat**i**bilityShim, must be spelled packageWriteRedirectionCompat**a**bilityShim for package creation using makemsix to work.  Yeah, the doc spells it like most people, but it isn't what is needed.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this. It's been updated in the source and should be live on the site within a few minutes.

**Comment by TimMangan** [comment]
Oops.   It looks like I am mistaken, it was a different coding error.  Please disregard!
