### ISSUE TITLE
Update Rust examples to use the latest "windows" crate

### ISSUE THREAD

**Issue by joshuamegnauth54** [MicrosoftDocs/windows-uwp#3953]
The current revision of [RSS reader tutorial (Rust for Windows with VS Code)](https://github.com/MicrosoftDocs/windows-uwp/blob/7d5eda5ccd6645de974b101a345fbb12bf4c0beb/hub/dev-environment/rust/rss-reader-rust-for-windows.md) uses a very old version of [windows-rs](https://github.com/microsoft/windows-rs/).

While this is totally fine, newer versions of the crate uses Cargo features and overall looks cleaner because it precludes build.rs

Cargo.toml snippet with the latest crate for the RSS example:
```toml
[dependencies.windows]
version = "0.39"
features = [
    "Foundation_Collections",
    "Web_Syndication",
]
```
And the RSS code which remains mostly the same besides the imports and the w! macro:
```rust
use windows::{
    core::{w, Result},
    Foundation::Uri,
    Web::Syndication::SyndicationClient,
};

fn main() -> Result<()> {
    let uri = Uri::CreateUri(w!("https://blogs.windows.com/feed"))?;
    let client = SyndicationClient::new()?;
    let feed = client.RetrieveFeedAsync(&uri)?.get()?;

    for item in feed.Items()? {
        println!("{}", item.Title()?.Text()?);
    }

    Ok(())
}
```
And the MessageBoxA example:
```rust
use windows::{
    s,
    Win32::UI::WindowsAndMessaging::{MessageBoxA, MB_OK},
};

fn main() {
    unsafe {
        MessageBoxA(None, s!("Text"), s!("Caption"), MB_OK);
    }
}
```

**Comment by mattwojo** [comment]
@stevewhims - Can you help with this?

**Comment by stevewhims** [comment]
Thanks for the heads up. I've created a work item for myself (on my backlog) to take a look at this. That work item contains a link to this GitHub issue, so I'll go ahead and close this issue for now (so that I'm not tracking the work in two places), and I'll reopen this issue when I get to my work item.

Thanks again!
Steve

**Comment by Paul-Dempsey** [comment]
@stevewhims, @mattwojo   -- It's now December (nearly six months later) and a fix has still not been published. I'm willing to update the article to fix this issue, but I'd need you to re-open this issue so that my PR can address it, - thanks.

**Comment by stevewhims** [comment]
> @stevewhims, @mattwojo -- It's now December (nearly six months later) and a fix has still not been published. I'm willing to update the article to fix this issue, but I'd need you to re-open this issue so that my PR can address it, - thanks.

Thanks, Paul! If you're able to correct the topic via a pull request, that'd be great.

Thank you!
-Steve

**Comment by Paul-Dempsey** [comment]
Thank you, @stevewhims! cloning the repo now...
