### ISSUE TITLE
System Access Violation when exiting "using" statement

### ISSUE THREAD

**Issue by dchillman123** [MicrosoftDocs/windows-uwp#3955]
When closing the application I get an exception on the "using" statement of the Program class of the WPF application  - Any idea if where I am going wrong?

`public class Program
    {
        [System.STAThreadAttribute()]
        public static void Main()
        {
            using (new UWPMapperApp.App())
            {
                WpfMapper.App app = new WpfMapper.App();
                app.InitializeComponent();
                app.Run();
            }  *** exception occurs here
        }
    }
}`

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7ec471-9257-39ba-173b-eb7973f4c360
* Version Independent ID: 3e07d5f0-8b19-2ef4-dc2a-48659f42c12e
* Content: [Host a custom WinRT XAML control in a WPF app using XAML Islands - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @dchillman123 - as this isn't a doc issue, try posting your question at https://docs.microsoft.com/en-us/answers/index.html.

Thanks
