### ISSUE TITLE
Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.'

### ISSUE THREAD

**Issue by aprykhus** [MicrosoftDocs/windows-uwp#3958]
After following the steps in the section titled **Replace the placeholder text with real data** and running the project it threw XamlParseException. There was no mention in the remaining steps that ItemTemplate in GridView needed to be updated to {StaticResource ImageGridView_DefaultItemTemplate}.

It was set to {StaticResource ImageGridView_ItemTemplate} causing the exception.

StaticResource ImageGridView_ItemTemplate
to
StaticResource ImageGridView_DefaultItemTemplate

Fixed code snippet
```
        <GridView x:Name="ImageGridView"
                  ItemTemplate="{StaticResource ImageGridView_DefaultItemTemplate}"
                  ItemContainerStyle="{StaticResource ImageGridView_ItemContainerStyle}"
                  ItemsPanel="{StaticResource ImageGridView_ItemsPanelTemplate}"
                  ContainerContentChanging="ImageGridView_ContainerContentChanging"
                  ItemsSource="{x:Bind Images}">
        </GridView>
```

You should add a note that you'll need to update the GridView - ItemTemplate after updating DataTemplate x:Key in step 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial--Create a simple photo viewer with WinUI 3 (C#) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @aprykhus! The problem was that the x:Key is *not* meant to change. That step is about adding an x:DataType value to the template, It's *not* intended to be about changing the x:Key. So I've fixed that mistake, and now the x:Key is the same as it was before.

-Steve
