### ISSUE TITLE
Large misformatted blocks of text

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/windows-uwp#3968]
Large multiparagraph blocks of text in this article are formatted as links, although it is obvious that they should not be. Start scrolling from the top and you'll see them because they are colored blue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 885efab8-5111-d158-7674-0bc3b2fc99fc
* Version Independent ID: 6f56386c-a5b7-8be3-514b-9aed190edf17
* Content: [Windows Information Protection (WIP) developer guide - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/enterprise/wip-dev-guide)
* Content Source: [windows-apps-src/enterprise/wip-dev-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/enterprise/wip-dev-guide.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Hah, that's quite the bug. Sorry for the delay, fix going out shortly.
