### ISSUE TITLE
InputInjector.sample c++

### ISSUE THREAD

**Issue by PACALA-BA** [MicrosoftDocs/windows-uwp#3972]
[Enter feedback here]
Hi, missing C++ SAMPLE, thanks
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3134b68b-ba59-426d-db7c-5c9a029d77b9
* Version Independent ID: f3e212bb-0e58-7665-3a24-9d899b446f69
* Content: [Simulate user input through input injection - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/input/input-injection)
* Content Source: [hub/apps/design/input/input-injection.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/input/input-injection.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thank you! We're doing our best to add C++ snippets throughout the docs.
