### ISSUE TITLE
Mouse Utilities PowerToys Page – Broken URLs

### ISSUE THREAD

**Issue by MichaelFoss** [MicrosoftDocs/windows-uwp#3975]
[Enter feedback here]

At the top of the [Mouse Utilities PowerToys page](https://docs.microsoft.com/en-us/windows/powertoys/mouse-utilities), the shortcut links to the individual PowerToys identified on this page navigate to 404s. Update the URLs of the anchor tags such that they point to hash tags instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba175f26-82e2-2f00-7562-924faa57c143
* Version Independent ID: ba175f26-82e2-2f00-7562-924faa57c143
* Content: [PowerToys Mouse utilities for Windows](https://docs.microsoft.com/en-us/windows/powertoys/mouse-utilities)
* Content Source: [hub/powertoys/mouse-utilities.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/mouse-utilities.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for bringing this to attention @MichaelFoss! Just fixed in https://github.com/MicrosoftDocs/windows-uwp/commit/472498b9db48ab6270be8b94075331954d5811d1.
