### ISSUE TITLE
"The located assembly's manifest definition does not match the assembly reference. " exception raised

### ISSUE THREAD

**Issue by kezhangMS** [MicrosoftDocs/windows-uwp#3977]
[Enter feedback here]
It will report "0x80131040 : The located assembly's manifest definition does not match the assembly reference." exception at this line:
winrt::SampleComponent::Example myExample;

VS: Microsoft Visual Studio Enterprise 2022 (64-bit) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca2fb23f-7644-1b8d-6b34-cf65c0e0fb9a
* Version Independent ID: 13f2c20d-8a38-7466-105d-0d868f2cd507
* Content: [Authoring a C# Windows Runtime component for use from a C++/WinRT app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/use-csharp-component-from-cpp-winrt.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kezhangMS, and thanks for filing this issue. I followed along with the tutorial, and I don't get any issue with that line of code, either at compile time or at run time. I don't know whether it makes any difference, but did you set the Application Minimum Version of the WRC project as indicated in the tutorial? I can't think what else might be causing the issue, except perhaps using different project templates from the ones indicated. In any case the instructions in the tutorial appear to be correct.

Thanks!
-Steve
