### ISSUE TITLE
xmlns code is different on different doc pages

### ISSUE THREAD

**Issue by vt-pongrass** [MicrosoftDocs/windows-uwp#3979]
Hi, at the bottom of the page is some code to add a namespace reference to the XAML

xmlns:muxc="using:Microsoft.UI.Xaml.Controls"

but another page <https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp> asks for this code to be used:

xmlns:winui="using:Microsoft.UI.Xaml.Controls"

so could you clarify (on either of the pages) as to which is the correct one to use? I'm new to this so I don't really understand what this is doing but I think that it should be one or the other (unless you really need to have two different codes for different reasons?!?)

edit: it looks like this only affects the element used later on in the same XAML file to instantiate a control from the Microsoft.UI.Xaml.Controls library so my apologies for not understanding this (I'm still new to using these controls).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532b04ea-7927-f97a-1121-b8feac6df957
* Version Independent ID: e3cf5c39-5efa-aaea-3ac3-8c4ffa50e960
* Content: [Getting started with the Windows UI library - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started#additional-steps-for-a-cwinrt-project)
* Content Source: [hub/apps/winui/winui2/getting-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui2/getting-started.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Those are just namespace qualifiers. See https://en.wikipedia.org/wiki/XML_namespace.
