### ISSUE TITLE
Please edit.

### ISSUE THREAD

**Issue by kase-sanwa** [MicrosoftDocs/windows-uwp#3984]
[Enter feedback here]
I spent 3 h for showing image on Win11 / 10 desktop notification due to inccuracy and shortage.
1. 'ToastGenericAppLogoCrop' class doesn't exist on 7.1.2. Should use 'ToastGenericAppLogoCrop'.
2. Should be added === Http images are only supported in UWP/MSIX/sparse apps that have the internet capability in their manifest. desktop non-MSIX/sparse apps do not support http images; you must download the image to your local app data and reference it locally. === (from [doc-github](Http images are only supported in UWP/MSIX/sparse apps that have the internet capability in their manifest. desktop non-MSIX/sparse apps do not support http images; you must download the image to your local app data and reference it locally.)) And on usinig local image file, use `new Uri("xxx", , UriKind.Absolute)`. Relative path doesn't work.

This page shows 2022/07 as updated date, so many people read as latest official document about Microsoft.Toolkit.Uwp.Notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ab94cb-c334-e72e-ef0b-0d792c6b1d7a
* Version Independent ID: c5547751-b359-002a-7d5c-4b52dad6e0bd
* Content: [Toast content - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=builder-syntax)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Sorry for the enormous delay in addressing this issue. Testing the current code example against 7.1.3 works as expected. The note about http images has been added to the page.
