### ISSUE TITLE
MS Photos launch URI of `ms-photos:viewer?fileName={filename}` does not appear to work.

### ISSUE THREAD

**Issue by bitbound** [MicrosoftDocs/windows-uwp#3988]
The provided example of using `ms-photos:viewer?fileName={filename}` does not appear to work.  It opens the Photos app, but it doesn't open the provided file.  I tried putting quotes around the file path (although it had no spaces), but that didn't work either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae2608d3-38b8-2404-d138-1ba17772e72c
* Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
* Content: [Launch the default app for a URI - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app)
* Content Source: [windows-apps-src/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-default-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. I tested several of these URIs for the Photos app, and none of them appear to work with the new version of the app. They only launch the app to the default page. So, it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback. You can also use the Feedback app in Windows to provide feedback about the Photos app. That will open a bug with the engineering team to follow up on.

**Comment by alvinashcraft** [comment]
Also, please follow up here if the product team indicates that support for these URIs is being removed in the new version of the app, and I will update the docs to reflect that. I will continue to monitor this issue for any updates.
