### ISSUE TITLE
The embedded video is marked private on this page

### ISSUE THREAD

**Issue by jennifer-nejad** [MicrosoftDocs/windows-uwp#3990]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c161a2e-d9f4-466f-5a63-5e25648a1779
* Version Independent ID: 6032f644-b69d-622f-73df-bacebdfc4509
* Content: [Create a multi-instance Universal Windows App - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback. I went ahead and created an internal work item to resolve this doc bug. I found the updated embed URL for the video and merged a PR to fix the page. The changes should be live today.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
