### ISSUE TITLE
URI for a settings page is missing

### ISSUE THREAD

**Issue by makerBasse** [MicrosoftDocs/windows-uwp#3992]
In the list of settings pages and URIs there is no listing for the page "Bluetooth & devices".
Both "ms-settings:bluetooth" and "ms-settings:connecteddevices" will open "Bluetooth & devices > Devices" 

I dont know if there is no URI for this page or it is missing from the list.
But a URI for this page would be very usefull now that this page have direct buttons to connect to a specific bluetooth device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. These URIs were recently updated after consulting the product team's internal documentation. So, it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback. You can also use the Feedback Hub in Windows to file a bug report with the team.
