### ISSUE TITLE
References to depreciated packages.

### ISSUE THREAD

**Issue by nitrospaz** [MicrosoftDocs/windows-uwp#3997]
Hi, I was trying to follow along with this tutorial but it is referencing packages that have been depreciated and replaced with EFCore. Specifically Microsoft.Data.Sqlite.Core.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/36904927/184570774-fa19b0a8-31f7-4670-8df3-b5f735c344aa.png">

I have all kinds of errors in the build and im not sure if its because of this package or something else. Someone should probably go through and update this tutorial. I would do it but I'm still trying to figure out how this works lol.

Thanks for all you do, I really appreciate the Microsoft Docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @nitrospaz. Thank you for raising this issue. I went ahead and created an internal work item to review & update the tutorial and resolve this doc bug. The entire tutorial could use a refresh, along with updated screenshots. We're also in the process of analyzing our UWP content and determining which parts should have WinUI counterparts. The data access content seems like a good candidate to me. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
