### ISSUE TITLE
Suggested Documentation Changes

### ISSUE THREAD

**Issue by jlinstrum** [MicrosoftDocs/windows-uwp#400]
Two documentation changes suggested:

1. Nowhere on the page is it mentioned that this API change dates to the Fall Creators update. It is mentioned in the class documentation, but it seems that it should be mentioned here as well - like right at the top.
2. ListView is sealed, so the example of overriding the OnKeyboardAcceleratorInvoked method is invalid. This is particularly sad for me because I would love to override that method. (Or was the class changed in Fall Creators Update to not be sealed?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Service: **unspecified**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @jlinstrum, thanks for the feedback! As Windows evolves over time (esp. with semi-annual updates), the number of version qualifications per topic would quickly become cumbersome. You should assume the topic addresses the most recent version of Windows (as you point out, the API topic addresses this version issue). WRT your second point, the code snippet you point out is an example of a custom control derived from ListView.
