### ISSUE TITLE
Powertoys download link is broken

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4006]
The link to the Powertoys store download page is broken 

![image](https://user-images.githubusercontent.com/35784165/186039167-f30d3578-32f2-4335-82d8-4832ee6fa055.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@crutkas - Any idea what's up with this PowerToys Store link?
Confirmed it's broken for me as well and that I am running the latest Win11 general release build.
Store install link is: https://aka.ms/getPowertoys

**Comment by crutkas** [comment]
weird, maybe a cache issue store
?  i saw the issue but resolves now.
