### ISSUE TITLE
Missing WinUI Project Templates

### ISSUE THREAD

**Issue by wmfoley** [MicrosoftDocs/windows-uwp#4007]
I can't seem to find the WinUI 3 template mentioned here, **_Blank App (WinUI in UWP)_**, it's also mentioned in a WinUI 3 book I'm reading. I've installed the WinUI workloads as instructed (VS 2022) but still can't find this template. I'm following a tutorial in a WinUI 3 book that calls for a Control Library (WinUI in Desktop) template that I can't find - objective is to build a library of user controls for a WinUI 3 project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c44686a3-a403-405b-9539-e1f0339f147d
* Version Independent ID: 8ba10426-a5e6-5c41-61ef-12afda831883
* Content: [Build XAML controls with C# - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-csharp-winui-3)
* Content Source: [hub/apps/winui/winui3/xaml-templated-controls-csharp-winui-3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/xaml-templated-controls-csharp-winui-3.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, thanks for catching this! The Blank App (WinUI in UWP) project is no longer supported. The article has been updated to recommend the use of the "Blank App, Packaged (WinUI 3 in Desktop)" template for this scenario.
