### ISSUE TITLE
Designer links not working

### ISSUE THREAD

**Issue by Jester98x** [MicrosoftDocs/windows-uwp#401]
The Speech and Cortana design guideline links result in a 404 page being shown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d052f44-c6b2-5ca6-d2ef-825ca48cc31d
* Version Independent ID: 08a0d91f-1b8c-1b30-801d-3457dba0afff
* Content: [Cortana interactions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/cortana-interactions)
* Content Source: [windows-apps-src/design/input/cortana-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/cortana-interactions.md)
* Service: **unspecified**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the head's up! Links have been fixed and should be live soon.
