### ISSUE TITLE
Typo in Step 6

### ISSUE THREAD

**Issue by erangaperera** [MicrosoftDocs/windows-uwp#4011]
[Enter feedback here]

There is a typo in Step 6. 
"Step 6: Build and run the qpp" 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c2ab3c-221d-41a1-c145-2614a44cd2c4
* Version Independent ID: 27647b64-5700-e15c-3e90-f6dd5afe73e8
* Content: [Auto-launching with AutoPlay - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/auto-launching-with-autoplay)
* Content Source: [windows-apps-src/launch-resume/auto-launching-with-autoplay.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/auto-launching-with-autoplay.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback. I went ahead and created an internal work item to resolve this doc bug. The changes have been merged and should be visible shortly, so I will go ahead and close this. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
