### ISSUE TITLE
NVM URL can be master*

### ISSUE THREAD

**Issue by ttambow** [MicrosoftDocs/windows-uwp#4017]
[Enter feedback here]
Specify current/master tree of install.sh file, vs the explicit release file:

https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @tambow44! Updated the doc with your link. :)

**Comment by ttambow** [comment]
No you haven't ![image](https://user-images.githubusercontent.com/29732094/189479086-bfbfd286-8d81-4f4d-874b-be4b296a813e.png)
