### ISSUE TITLE
CPU requirements

### ISSUE THREAD

**Issue by samirgunic** [MicrosoftDocs/windows-uwp#402]
Could you please be more verbose about hardware-assisted virtualization?

> Hardware-assisted virtualization

Specifically, is Intel VT-x a requirement? Would AMD-V be enough?

> Second Level Address Translation (SLAT)

Would AMD's Rapid Virtualization Indexing work just as well as Intel's Extended Page Table?

> Hardware-based Data Execution Prevention (DEP)

Would AMD's Enhanced Virus Protection (EVP) work just as well as Intel's Execute Disable (XD)?

My experience is that these things often work well with Intel CPUs but not with those of AMD. Simply because AMD's technology is never implemented in the software, even though it's an equally good solution as that of Intel CPUs.

You should replace the word "BIOS" with "CPU" as these are all mainly CPU requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66be8b10-da19-046c-e430-e5b9fdd5f7d9
* Version Independent ID: 74663841-8af1-30d2-2d2c-7d5abfc7955a
* Content: [Test with the Microsoft Emulator for Windows 10 Mobile - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/test-with-the-emulator)
* Content Source: [windows-apps-src/debug-test-perf/test-with-the-emulator.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/test-with-the-emulator.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Hi samirgunic, I've forwarded your questions to a PM with deeper knowledge of the Mobile Emulator, and I will relay his answers here when I receive them.

**Comment by PatrickFarley** [comment]
Hi again,

As you can see, I've added a link in the docs where you can check your system's compatibility for hardware-assisted virtualization, and I've clarified the CPU/BIOS relationship. 

As for your specific questions:
- The emulator should work on both Intel VT-x and AMD.
- Yes, EVP is expected to work as well.

**Comment by samirgunic** [comment]
If the emulator is based on Hyper-V then it should work with both Intel and AMD processors.

Sadly the Hardware-Assisted Virtualization Detection Tool is not compatible with Windows 10. It has not been updated for almost 10 years now.

![detector tool](https://user-images.githubusercontent.com/3742529/42243057-59aaa762-7f10-11e8-85a6-5757ef9092cb.png)

For AMD processors, there is an old detection tool that still works with Windows 10.

> This utility checks your system’s compatibility with Microsoft Hyper-V and AMD processors. The utility has been updated to check and report on AMD’s Rapid Virtualization Indexing (RVI) feature that provides the necessary Second Level Address Translation (SLAT) support for Hyper-V.

It can be downloaded from AMD Support website. Click [here](http://download.amd.com/techdownloads/AMD-VwithRVI_Hyper-V_CompatibilityUtility.zip) for a direct download link.

For Intel processors, there is the Intel Processor Identification Utility. For a list of supported Windows versions and download links, click [here](https://downloadcenter.intel.com/download/7838).

I think this can be broken down a bit, as it is really a two-part question. Does my processor support this? Is it enabled? Enabling is done in the BIOS or UEFI, while support is built into the processor (or not). You can enable hardware assisted virtualization in the BIOS, but you most definitely cannot enable specifics of it such as RVI (AMD) or EPT (Intel) which is required for Hyper-V (SLAT).

**Comment by samirgunic** [comment]
[Coreinfo](https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo) may be used as a replacement for HAVDT, and it is Windows 10 compatible. Coreinfo is part of Sysinternals utilities suite. It can display information related to virtualization by a simple command.

`Coreinfo.exe -v`

The output will look something like this. This shows an Intel processor example.

    HYPERVISOR      -       Hypervisor is present
    VMX             *       Supports Intel hardware-assisted virtualization
    EPT             *       Supports Intel extended page tables (SLAT)

Hyper-V should be disabled when you run the command and you need to run it as admin.
