### ISSUE TITLE
Changelog is not up-to-date

### ISSUE THREAD

**Issue by norbertwell** [MicrosoftDocs/windows-uwp#4021]
[Enter feedback here]
Missing the actual 2207.40000.8 and many changelogs from the past.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Version Independent ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Content: [Windows Subsystem for Android™️ Release Notes](https://docs.microsoft.com/en-us/windows/android/wsa/release-notes)
* Content Source: [hub/android/wsa/release-notes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/release-notes.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for raising this issue @norbertwell! Connected with the PM and just got the updated release notes in: https://github.com/MicrosoftDocs/windows-dev-docs/commit/93e0224cd269c5b9ea616600d29bffe7f0de1a61
