### ISSUE TITLE
Release notes have not been kept up to date

### ISSUE THREAD

**Issue by libbaz** [MicrosoftDocs/windows-uwp#4024]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Version Independent ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Content: [Windows Subsystem for Android™️ Release Notes](https://docs.microsoft.com/en-us/windows/android/wsa/release-notes)
* Content Source: [hub/android/wsa/release-notes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/release-notes.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@hamza-usmani -- Do you have updated release notes to add?

**Comment by hamza-usmani** [comment]
@mattwojo PR has been submitted

**Comment by mattwojo** [comment]
Thanks for raising this issue @libbaz. 
Got the update in: https://github.com/MicrosoftDocs/windows-dev-docs/commit/93e0224cd269c5b9ea616600d29bffe7f0de1a61
