### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/windows-uwp#4029]
there is a broken link at
"For a complete list and descriptions of items in a manifest, see the [manifest specification](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657479f-c0b7-6358-c7d0-0402215edaa5
* Version Independent ID: 8976699b-cdba-5206-bdb0-8a0875acfe45
* Content: [Create your package manifest](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example)
* Content Source: [hub/package-manager/package/manifest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/package/manifest.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Thanks for bringing this to our attention @birbilis. I'm investigating and have reached out to the PMs. I'll add an update once I've fixed this issue. Thanks again.

**Comment by kdpuvvadi** [comment]
@mattwojo looks like this is correct link is https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema

Problem is manifest schema is located in the [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) but doc assumes it's located at  [microsoft/winget-cli](https://github.com/microsoft/winget-cli)

Source: https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/package/manifest.md#manifest-contents

Do you want me to open a pr to fix the link?

**Comment by mattwojo** [comment]
Thanks @kdpuvvadi!  The PM responded with these two links as well:
https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md
https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0

This all looks like information worth including in the docs, so I'm setting aside some time to do a bit of a read-through and update to ensure that all of the relevant info and links are included.

**Comment by mattwojo** [comment]
Took me a bit, but got this update in: https://github.com/MicrosoftDocs/windows-dev-docs/commit/dfeb79d6a19efc0c30783e5ed79d93a2de54d76f

Thank you @birbilis for bringing this issue to my attention! And thanks @kdpuvvadi for contributing as well.
