### ISSUE TITLE
Background for Toast Notification by Buttons

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#403]
How can we trigger a background task for the new Toast Notification to show and the current Toast Notification to disappear using the ToastButtons?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e53518-2be9-4aee-b7f2-05e5a42b08d9
* Version Independent ID: 0759bb55-622c-9a7e-3015-1a54f5e67db9
* Content: [Toast with pending update activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-pending-update)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-pending-update.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-pending-update.md)
* Service: **unspecified**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Hi superkid, can you explain your scenario a bit more? I'm failing to understand what you're asking for.

Do you want clicking one of the buttons to cause the notification to disappear and a new one to appear?

Or without any user interaction, do you want the current toast to disappear and a new one to appear?

**Comment by dongle-the-gadget** [comment]
Get the action and switch to another toast notification.

**Comment by andrewleader** [comment]
Isn't that exactly what's shown [in the article](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-pending-update)? The article includes a full code sample too.

**Comment by ginami** [comment]
Hi @superkid200 --closing this issue. Let us know if you have any more questions. Thank you!
