### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by DevX-Cipher** [MicrosoftDocs/windows-uwp#4031]
hi im just asking a question about ms-settings:appsfeatures i was wondering if you could tell me how to moves files and folders to a different location please

**Comment by mattwojo** [comment]
Hi @modz2014 - We may need a bit more context for what you're asking / trying to do. You can move files and folders using Windows File Explorer: https://www.thewindowsclub.com/move-files-and-folders-in-windows-10

Is this what you're asking?

**Comment by DevX-Cipher** [comment]
Nar after how this moves apps that's are installed to a selected drive

**Comment by mattwojo** [comment]
@modz2014 - ahh, so you are trying to move apps? 
This may help: https://answers.microsoft.com/en-us/windows/forum/all/how-to-move-installed-apps-from-one-drive-to/a74a68c3-37f6-4eb7-9477-a89a96ca41bc

I'm going to close this issue as it does not pertain to an update needed in our docs.microsoft.com content. If you have further questions, please try our Q&A forum: https://docs.microsoft.com/answers/products/ or https://support.microsoft.com/

**Comment by DevX-Cipher** [comment]
I'm after creating my own app to move them curious how the built app works for windows
