### ISSUE TITLE
documentation needs to describe how to select from alternate accented keys in the overlay

### ISSUE THREAD

**Issue by malcook** [MicrosoftDocs/windows-uwp#4035]
documentation needs to describe how to select from alternate accented keys in the overlay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Version Independent ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Content: [PowerToys Quick Accent utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/quick-accent)
* Content Source: [hub/powertoys/quick-accent.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Looking into this. Thanks for raising the issue.

**Comment by crutkas** [comment]
So ask is using action key to move between, correct?

**Comment by crutkas** [comment]
PR created

**Comment by Jay-o-Way** [comment]
@malcook Is this still an issue with the latest version? (I think it's good now)

**Comment by alvinashcraft** [comment]
This looks good to me now with the PR from Clint merged.

Thanks for taking the time to let us know about this, @malcook. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
