### ISSUE TITLE
Input method bias is not documented

### ISSUE THREAD

**Issue by ForgotMyCode** [MicrosoftDocs/windows-uwp#4036]
The text retrieved from the text extractor tool seems to be based on keyboard language settings in the system, which is quite 
important but it is not documented for users.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Version Independent ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Content: [PowerToys Text Extractor utility for Windows](https://docs.microsoft.com/cs-cz/windows/powertoys/text-extractor)
* Content Source: [hub/powertoys/text-extractor.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Looking into this. Thanks for raising the issue.

**Comment by Jay-o-Way** [comment]
@ForgotMyCode the OCR language pack dependency is quite explained in the mean time. Is this still an issue with the latest version?

CC @mattwojo

**Comment by Jay-o-Way** [comment]
> @ForgotMyCode the OCR language pack dependency is quite explained in the mean time. Is this still an issue with the latest version?

CC @mattwojo

**Comment by ForgotMyCode** [comment]
> @ForgotMyCode the OCR language pack dependency is quite explained in the mean time. Is this still an issue with the latest version?
> 
> CC @mattwojo

Not an issue anymore.
