### ISSUE TITLE
Couldn't complete MainWindow.xaml.cs code in sample in SimplePhotos

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/windows-uwp#4038]
When I start to learn this tutorial, many error appear at  MainWindow.xaml.cs. Please fix these errors in order to build the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial--Create a simple photo viewer with WinUI 3 (C#) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3?source=docs)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you, @ahidaka! I'll investigate.

-Steve

**Comment by stevewhims** [comment]
Hi, @ahidaka. I followed along with every step of the tutorial again just now, and everything worked as expected. I didn't get any errors.

There are only certain points within the tutorial where you should try to build the project. Building at any other time is not recommended. These are the point in the tutorial where you can build:

1. After "Add a GridView control" > Step 3.
1. You can build after "The ImageFileInfo model", even though the tutorial doesn't say so.
1. After "Define and populate a property for a collection of images" > Step 3.
1. After "Add a data template" > Step 4.
1. After "Edit the item container's style" > Step 2.
1. After "Experimenting with layout" > Step 2.
1. After "Edit the items panel template" > Step 2.
1. You can build after "Replace the placeholder image with a photo", even though the tutorial doesn't say so.
1. After "Replace the placeholder text with real data" > Step 4.
1. After "Bind the GridView to the Images collection" > Step 2.

Are you trying to build at one of the points above, and the build is failing? If so, which number in the list above is it failing at?

We could try to diagnose what's going wrong, what the errors are, what you code looks like. But it might just be easier and quicker to restart the tutorial and go very slowly and carefully, inserting the code at just the right places. For example, if you insert a new class member inside the namespace {} scope, but not inside the class {} scope then that won't work. The code listings do give you indications as to where you need to add the code. Also be on the lookout for `using` keywords that include types in certain namespaces.

Thanks!
-Steve

**Comment by stevewhims** [comment]
Closing this issue, as there doesn't seem to be action to take.

Thanks!
-Steve
