### ISSUE TITLE
Quick Accent - Hungrian accent characters

### ISSUE THREAD

**Issue by Tomaszon** [MicrosoftDocs/windows-uwp#4039]
Hello guys!

This Quick Accent feature is my new favorite one.
However, I miss some accent characters that would be cool to be included.
These are: 
  ő, Ő (similar to the included õ, Õ)
  ű, Ű (similar to the included ū, Ū)
These characters used in Hungarian language, if that is important.

Thanks :)

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Version Independent ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Content: [PowerToys Quick Accent utility for Windows](https://docs.microsoft.com/hu-hu/windows/powertoys/quick-accent)
* Content Source: [hub/powertoys/quick-accent.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @Tomaszon!  This is the documentation repo though -- could you please move your suggestions over into the PowerToys product repo? > https://github.com/microsoft/PowerToys/issues/new/choose

That's where the development team is actively working. I just try to keep the docs maintained. :)
