### ISSUE TITLE
Registration form doesn't have options for hobbyists

### ISSUE THREAD

**Issue by dizzi90** [MicrosoftDocs/windows-uwp#404]
If you are just a hobbyist and don't have a company the form to sign up asks a lot of inappropriate questions.
Like business address and approver.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a5c98-ba0b-38a0-d86e-2d5df4745d1a
* Version Independent ID: 643673cc-0b57-86f6-e00d-13aad2ef8d20
* Content: [Opening a developer account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
These questions are only asked if you choose the Company account type. The Individual account type is more appropriate if you don't have a business - you won't need to provide this info.
