### ISSUE TITLE
Doc missing most important element

### ISSUE THREAD

**Issue by umop-apisdn69** [MicrosoftDocs/windows-uwp#4044]
This doc fails completely in the most important mission:  To document how the product works and is used.  No mention whatever of what the control buttons DO.  The lasso icon (and of course the X to close) are the only ones that are remotely intuitive.  Plus, minus, and pipe make things happen, but the differences are not immediately apparent.  This is a tool, not an exploration video game.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51f06fdf-c629-78d6-7740-ad6162cda4b8
* Version Independent ID: 51f06fdf-c629-78d6-7740-ad6162cda4b8
* Content: [PowerToys Screen ruler utility for Windows](https://docs.microsoft.com/en-us/windows/powertoys/screen-ruler)
* Content Source: [hub/powertoys/screen-ruler.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/screen-ruler.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version? /needinfo

**Comment by umop-apisdn69** [comment]
It seems pretty good now.  Though it's hard for me to say how much it's updated vs how much it's just conceptually "soaked in" to me.  Tldr: The help and the tooltips seem sufficient to me now.

It's not a tool I have frequent use for, so some of my reaction may have been unfamiliarity. - And perhaps sleep deficit?   It initially struck me as pretty confusing behavior. And I didn't immediately  "get" the + - |  icon symbolism, though in retrospect they seem totally obvious now. Instead of thinking graphically, I was thinking arithmetically at first.  Plus?  Minus?  What the heck?!    ;-)

Thanks for the response and updates!
