### ISSUE TITLE
Stubs Not Generated

### ISSUE THREAD

**Issue by pdoyle500** [MicrosoftDocs/windows-uwp#4045]
Following the code example in visual studio 2022 does not generate the desired stubs.  

Then, the cppwinrt.exe tool is run to generate source code files to support you in authoring and consuming your runtime class. These files include stubs to get you started implementing the BookSku runtime class that you declared in your IDL. Those stubs are \Bookstore\Bookstore\Generated Files\sources\BookSku.h and BookSku.cpp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47016328-dadb-a583-bba5-f60b907861f4
* Version Independent ID: 8d21db48-d9f0-91ae-d25c-762b2b2f9cb2
* Content: [XAML controls; bind to a C++/WinRT property - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @pdoyle500, and thanks for filing this issue.

I just tested the tutorial again (with Visual Studio 2022 17.3.4), and the stubs are generated. When you right-click the project node and click **Open Folder in File Explorer**, that takes you to the `\Bookstore\Bookstore\` folder. Then navigate into the `\Generated Files\sources\` folder, and you'll find the stub files there.

I'd also confirm that you're creating a **Blank App (C++/WinRT)** project.

Thanks!
-Steve

**Comment by pdoyle500** [comment]
Will try again.  Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
