### ISSUE TITLE
Custom range for POINTER_INFO structure (more than 1024 pressure levels and arbitrary dpi).

### ISSUE THREAD

**Issue by alkeryn** [MicrosoftDocs/windows-uwp#4046]
So we can inject input with InjectSyntheticPointerInput the issue is that it relies on the POINTER_INFO structure, and that structure has the following issues:

Pressure levels is limited to 1024, which is low.
the pointer position is defined using ptPixelLocation which are 2 i32, the issue is that it is limited to the screen resolution
so you are wasting the accuracy of highdpi tablets.

is there a way to inject pointer inputs with more than 1024 pressure levels and for example floats for pixel position or just a range that goes from let's say 0 to 32000 or something like that without writting a driver ?

with linux uinput you can define arbitrary ranges for your input injection.

thanks !

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue. Unfortunately, this feedback channel covers specific documentation fixes and not broader product feedback or questions. 

I suggest you direct your question/feedback to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) where a community of experts and Microsoft engineers can provide answers to your technical questions. If you do create a Microsoft Q&A thread, I'd appreciate if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.
