### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/windows-uwp#4048]
there's a broken link at:

"To help author manifest files, we have provided a YAMLCreate.ps1 powershell script located in the Tools folder on the [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs/Tools)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d657479f-c0b7-6358-c7d0-0402215edaa5
* Version Independent ID: 8976699b-cdba-5206-bdb0-8a0875acfe45
* Content: [Create your package manifest](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#using-the-yamlcreateps1)
* Content Source: [hub/package-manager/package/manifest.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/package/manifest.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by birbilis** [comment]
correct link seems to be
https://github.com/microsoft/winget-pkgs/tree/master/Tools

however since the text says "Windows Package Manager Community Repository" the link should probably be (for the url to be consistent semantically with what the link text writes) up to "winget-pkgs" (the user can then navigate to the Tools folder easily from there).

**Comment by mattwojo** [comment]
Another good catch! Thanks @birbilis. Fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/61f9d5437bbd43781d40a182884a3acefefce135
