### ISSUE TITLE
Videos are private and unviewable on "Accessibility in Windows 11 and Windows 10 - Windows apps"

### ISSUE THREAD

**Issue by jlukosky** [MicrosoftDocs/windows-uwp#4049]
## Issue
When viewing the page at [Accessibility in Windows 11 and Windows 10 - Windows apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/apps/develop/accessibility) three videos do not display. Instead they display the message: "This video is private". Those videos are for these items:

- Designing Windows accessibility features
- Windows 10 accessibility features empower everyone
- Making the mouse pointers easier to see

## Preview
![image](https://user-images.githubusercontent.com/6210178/190668322-a91bf98b-af99-4951-899b-16f2a1bdfa62.png)

## Expected

The three videos will display previews and be able to be viewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c611201-543d-0dba-54ba-ebf351b6cad0
* Version Independent ID: 5a4827fa-32b1-22b2-9eea-71b4144ae1d0
* Content: [Accessibility in Windows 11 and Windows 10 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/develop/accessibility)
* Content Source: [hub/apps/develop/accessibility.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/accessibility.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @jlukosky - links to vids have been updated
