### ISSUE TITLE
Enums only to be used for Windows 8.1

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#405]
AllowedMayUseActiveRealTimeConnectivity and AllowedWithAlwaysOnRealTimeConnectivity is not allowed for UWP apps - Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2136305d-9655-315a-0e2f-cdfeff173207
* Version Independent ID: e0b4b4fc-2acd-39be-2380-fb730a288a7e
* Content: [Update a live tile from a background task - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/update-a-live-tile-from-a-background-task#debug-the-background-task)
* Content Source: [windows-apps-src/launch-resume/update-a-live-tile-from-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/update-a-live-tile-from-a-background-task.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by dongle-the-gadget** [comment]
This documentation is supposed to be used only in the Windows 8.1. Can Microsoft Docs move this documentation to Previous Version and update this documentation so it will work with Windows 10?

**Comment by hkhmsft** [comment]
Closing this issue as there have been changes merged since: https://github.com/MicrosoftDocs/windows-uwp/pull/2290. Many thanks @superkid200 !
