### ISSUE TITLE
All content should be specific to the chosen language

### ISSUE THREAD

**Issue by fatichar** [MicrosoftDocs/windows-uwp#4054]
When C# is selected as the laguage, the page still shows many sections like "If you are using c++/WinRT". That seems unnecessary, and makes it a bit difficult to find C# specific content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9882c8-2945-54d0-c418-72e5464229da
* Version Independent ID: debb8633-d2f4-bd60-7ddd-0e39d080e0f5
* Content: [Data binding overview - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart)
* Content Source: [windows-apps-src/data-binding/data-binding-quickstart.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/data-binding/data-binding-quickstart.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
I will log an internal work item with our engineering team. There is currently no way to change anything except the code snippet when the language selection changes.
