### ISSUE TITLE
The page recommends WSL 2 and yet WSL 2 does not have WWW access by default

### ISSUE THREAD

**Issue by zielot** [MicrosoftDocs/windows-uwp#4055]
How exactly am I supposed to run `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash` if there is no connection to the internet??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@zielot - Sorry, I'm not sure that I'm quite understanding the issue. WSL does have access to the internet. The exception may be if it's blocked by an internal firewall (?).

**Comment by zielot** [comment]
@mattwojo - No, WSL2 does _not_ have access to the internet by default. As per Microsoft documentation (my own emphasis; backed by my own recent experience):
>When using a WSL 1 distribution, if your computer was set up to be accessed by your LAN, then applications run in WSL could be accessed on your LAN as well.
>_This isn't the default case in WSL 2._
https://learn.microsoft.com/en-us/windows/wsl/networking
Unless I missed something, this default WSL 2 install that lacks any bridging nor NAT makes it virtually impossible to install applications from the internet without sophisticated configuration. The configuration mentioned in the above link, for example, only works if you know which port to forward - which may be the case if you are trying to expose your networked application running in WSL 2 to your local machine or network.

**Comment by mattwojo** [comment]
Hey @zielot - Maybe it would help to explain what you're trying to accomplish with WSL?

Perhaps there is a firewall issue blocking your Linux distributions running on WSL2 from accessing the internet? > https://learn.microsoft.com/windows/wsl/faq#why-do-i-not-have-internet-access-from-wsl-

Are you tring to connect to the internet or to a private LAN? 

If you're just looking to install/download software on a Linux distribution (running via WSL2), you can use a package manager (like `sudo apt install <x>`) or you can install and use cURL if what you want to download something that isn't available in a package (`sudo apt install curl` and then `curl -O https://<url>`).

Does that help?

**Comment by zielot** [comment]
Hey there @mattwojo - I appreciate your persistence in getting this issue resolved. 

I was trying to set up a node environment in my WSL2 instance on latest version of Windows 10 and I ran into issues when I tried to connect to any network web server outside of my company's internal network. I had had a similar prior experience using WSL2 but not WSL1 using the otherwise identical configuration - same PC, OS, company network - so I had assumed that the issue was with WSL2. In addition, I recall reading posts about earlier versions of WSL2 that did not use NAT out of the box. 

After some trial and error or perhaps stumbling upon a StackOverflow post I learned that if I disconnected from my VPN I was able to reach the Internet web servers I needed. Since I did not need access to any resources on my company's network this turned out to be an acceptable work-around. We use Cisco's [AnyConnect](https://www.cisco.com/c/en/us/support/security/anyconnect-secure-mobility-client-v4-x/model.html) VPN client to connect to our internal network from outside of the network. 

~ Justin

**Comment by mattwojo** [comment]
So glad to hear that you've found a resolution @zielot! Thank you for following up to let me know how it was resolved and closing the issue. I'll have to do some considering of whether there are ways I could better highlight this potential issue of being blocked by internal company VPNs in the docs for other who may run into the same thing.
