### ISSUE TITLE
Lifesaver! ★ ★ ★ ★ ★ 

### ISSUE THREAD

**Issue by s1ju** [MicrosoftDocs/windows-uwp#4058]
IMO, this is the most useful function within PowerToys. Excellent tool.   ★ ★ ★ ★ ★

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Version Independent ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Content: [PowerToys Text Extractor utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor)
* Content Source: [hub/powertoys/text-extractor.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thank you @s1ju! I will pass along your feedback and appreciate to the devs who worked on this.
