### ISSUE TITLE
PowerToys - Shortcuts need updating for new controls

### ISSUE THREAD

**Issue by SteveGoodman** [MicrosoftDocs/windows-uwp#4059]
The shorts cuts are:

- Windows ruler are win + shift + m
- Text Extractor are win + shift + t

Current doc says win + shift + t for ruler and nothing for text extraction.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
@mattwojo Looks like they're both good now

**Comment by alvinashcraft** [comment]
Thanks, @Jay-o-Way. These do look correct now. I'm closing this issue. Feel free to circle back if something doesn't look right.
