### ISSUE TITLE
Hiding windowsupdate-optionalupdates hides all windows update panel not only optional updates

### ISSUE THREAD

**Issue by damienvanrobaeys** [MicrosoftDocs/windows-uwp#4060]
Hi,
If I want to hide the optional updates part from Windows Update panel, it will not only hide optional updates but all Windows Update panel.

The URI to use is the following one: windowsupdate-optionalupdates
I try with CSP and catalog settings as below:
hide:windowsupdate-optionalupdates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#ms-settings-uri-scheme-reference)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. I don't think these URIs support hiding features, but you can as the experts at Q&A. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
