### ISSUE TITLE
Remove internal error code name

### ISSUE THREAD

**Issue by binarycrusader** [MicrosoftDocs/windows-uwp#4061]
Please remove the text "CBS_E_INVALID_WINDOWS_UPDATE_COUNT" from this page and only keep the numeric error code 0x800f0950. The name is internal-only and subject to change. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e87ddd8-58a2-529e-f025-49725b438ede
* Version Independent ID: e4df5ecb-472c-2f59-6139-69c55b99cd56
* Content: [Windows Device Portal for Desktop - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-desktop?source=docs)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-desktop.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/debug-test-perf/device-portal-desktop.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
String deleted
