### ISSUE TITLE
Select accent order

### ISSUE THREAD

**Issue by bloodanwar** [MicrosoftDocs/windows-uwp#4062]
In some languages there are some prefered accents, or some that are the most used. If your most used accent is the last one there is realy no point in using this tool. For that reason and in favor of more productivity, there should be a setting to change what is the order in wich the accents are shown.

**Comment by mattwojo** [comment]
Thanks @bloodanwar. Functionality issues like this are addressed in the PowerToys product repo -- try taking a look through the issues related to Accents to see if there's once addressing what you've brought up here: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+accents If not, please feel welcome to open a new issue there. This particular repo is specific to updates needed to the documentation.
