### ISSUE TITLE
The video in the doc is marked as private

### ISSUE THREAD

**Issue by yanancai** [MicrosoftDocs/windows-uwp#4064]
The UWP console video in this doc is marked as private and cannot be played. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e739c976-323f-bdf7-14a4-9b2d4872c62c
* Version Independent ID: c580c6b6-dc0d-296e-ffbd-0d866b34779f
* Content: [Create a Universal Windows Platform console app - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp)
* Content Source: [windows-apps-src/launch-resume/console-uwp.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/launch-resume/console-uwp.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi. Thank you for letting us know about this video. The same thing happened earlier this year, and we had to update the URL of the video. I will fix it soon!

**Comment by alvinashcraft** [comment]
Hi @yanancai. Thanks again for bringing this to our attention. I've checked in the fix for the missing embedded video, and it should be visible on the live site later today. Have a great day!

**Comment by yanancai** [comment]
> Hi @yanancai. Thanks again for bringing this to our attention. I've checked in the fix for the missing embedded video, and it should be visible on the live site later today. Have a great day!

Thank you!!
