### ISSUE TITLE
Incorrect shortcut

### ISSUE THREAD

**Issue by DavidSinden** [MicrosoftDocs/windows-uwp#4066]
On this page, you show the shortcut for Screen Ruler as Win-Shift-T, but on the detail page it's Win-Shift-M. The latter is the correct code.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://learn.microsoft.com/en-gb/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for bringing this to our awareness @DavidSinden. Closing as this is a duplicate, but will add #4059 to my to-do list.
