### ISSUE TITLE
Changes in Windows Widgets page

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4067]
Change widger providers for widget providers 

The document states "Currently, widget providers can be implemented using a Win32 desktop app" but the Win32 app must be a packaged Win32 app

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a3cfc62-c807-1cb9-684b-6246d45f0819
* Version Independent ID: 7a3cfc62-c807-1cb9-684b-6246d45f0819
* Content: [Windows Widgets - Windows apps](https://review.learn.microsoft.com/en-us/windows/apps/design/widgets/?branch=pr-en-us-2886)
* Content Source: [hub/apps/design/widgets/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/widgets/index.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I've updated the text to refer to "packaged Win32 desktop app". I sent a message to an ongoing thread about PWAs to ask if the reference to PWA providers needs to be removed entirely for the preview release.
