### ISSUE TITLE
Comments on the Widget Design Fundamentals page

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4068]
What is "the container style" that is talked about in this paragraph? Also, should And start with a capital A, is the period before it coming from the abbreviation of pixels into px or is it a different sentence?

> "For widgets that use the container style [TBD Link](https://review.learn.microsoft.com/en-us/windows/apps/design/widgets/tbd), the gutter between each element is 4px. And the containers should touch the edges of the margins."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61986cd3-ee4b-32a6-9a85-315fa978429e
* Version Independent ID: 61986cd3-ee4b-32a6-9a85-315fa978429e
* Content: [Widget design fundamentals - Windows apps](https://review.learn.microsoft.com/en-us/windows/apps/design/widgets/widgets-design-fundamentals?branch=pr-en-us-2886)
* Content Source: [hub/apps/design/widgets/widgets-design-fundamentals.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/widgets/widgets-design-fundamentals.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The text was updated for the preview release, but the weird sentence structure was still there. It's fixed now "For widgets that use containers, the gutter between each element is 4px, and the containers should touch the edges of the margins. "
