### ISSUE TITLE
Create a widget template with the Adaptive Card Designer is incomplete

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4069]
This page is incomplete

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8479e0a-e2db-64ea-5184-ce11980fc95a
* Version Independent ID: f8479e0a-e2db-64ea-5184-ce11980fc95a
* Content: [Create a widget template with the Adaptive Card Designer - Windows apps](https://review.learn.microsoft.com/en-us/windows/apps/design/widgets/widgets-create-a-template?branch=pr-en-us-2886)
* Content Source: [hub/apps/design/widgets/widgets-create-a-template.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/widgets/widgets-create-a-template.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This page was completed just before the preview release.
