### ISSUE TITLE
Should this page be renamed to Widget Providers

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4070]
The interface to be implemented in code is called IWidgetProvider but in this document it's referred as Widget Service Provider, is there a reason for this name difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 969a13d0-8194-7c66-5194-02c695b14abd
* Version Independent ID: 969a13d0-8194-7c66-5194-02c695b14abd
* Content: [Widget service providers - Windows apps](https://review.learn.microsoft.com/en-us/windows/apps/develop/widgets/widget-service-providers?branch=pr-en-us-2886)
* Content Source: [hub/apps/develop/widgets/widget-service-providers.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/widget-service-providers.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Yes, I think the term just drifted from widget service provider to widget provider. I've updated to the page to be "Widget providers"
