### ISSUE TITLE
General corrections for this document

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4071]
The Widgets Library is released as part of WinAppSDK, either installing WinAppSDK should be a pre-requisite or a step. 

As previously mentioned, this title is wrong "Add a reference to the Windows widgets NuGet package"

Is there a chance to add an extra json payload to show how different sizes may work when OnWidgetContextChanged has been called? otherwise the sample implementation showcases a method that does nothing

In the Activate and Deactivate sample code section, add an empty line between both methods and there's an extra empty line in the Deactivate method

Typo CompatWidgetInfo should be CompactWidgetInfo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d81a1eb-10f9-caf2-7457-48df84ca543e
* Version Independent ID: 1d81a1eb-10f9-caf2-7457-48df84ca543e
* Content: [Implement a widget provider in a win32 app - Windows apps](https://review.learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-win32?branch=pr-en-us-2886)
* Content Source: [hub/apps/develop/widgets/implement-widget-provider-win32.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/implement-widget-provider-win32.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
* Adding a reference to the WinAppSDK NuGet is included in a step.
* Updated the section title to "Add references to the Windows App SDK and Windows Implementation Library NuGet packages"
* I'm going to hold off on updating the sample JSON. We will be revisiting the sample code for GA and I'll consider this change, but I don't think the sample needs to illustrate every feature, and we don't want to encourage people to send separate sizes in separate payloads just to use this callback. It might be that we add a sample to the API reference page for OnWidgetContextChanged.
* Spacing has been adjusted for Activate Deactivate
* Typo is fixed.
