### ISSUE TITLE
Blog post link leads to 404

### ISSUE THREAD

**Issue by gabbybilka** [MicrosoftDocs/windows-uwp#4073]
The blog post link in the Samples section directs to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf28a713-4e81-45e0-a3c7-0274ba6b2e85
* Version Independent ID: 19dd0436-a27d-8e50-5e7b-06c8fcd49a3f
* Content: [Grant identity to unpackaged desktop apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps#sparse-packages)
* Content Source: [hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, the fix is now live. :)
