### ISSUE TITLE
MIssing release notes

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#4075]
I just installed Win11 22H2 and then installed WSA.
In about it states this is version "2208.40000.4.0", but I don't see any release notes for this version.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Version Independent ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Content: [Windows Subsystem for Android™️ Release Notes](https://learn.microsoft.com/en-us/windows/android/wsa/release-notes)
* Content Source: [hub/android/wsa/release-notes.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/release-notes.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @dotMorten. Just added these release notes in https://github.com/MicrosoftDocs/windows-dev-docs-pr/pull/3018 and investigating whether we can get these release notes in quicker.

**Comment by dotMorten** [comment]
Thanks I can't see that PR though so will have to wait :)

**Comment by mattwojo** [comment]
Oops - sorry! Here's the public repo version: https://github.com/MicrosoftDocs/windows-dev-docs/commit/917b35b21ad34ed3830d80bc8cb780337eef8b43
it's on the live site now too: https://learn.microsoft.com/en-us/windows/android/wsa/release-notes#build-22084000040
