### ISSUE TITLE
Quick Accent inadequate coverage

### ISSUE THREAD

**Issue by RDHWalker** [MicrosoftDocs/windows-uwp#4076]
The selection of accents available in the PowerToys "Quick Accent" feature is currently inadequate, and seems to cover only a sub-set of the languages of Western Europe. There is no full support for the languages used in Wales, Iceland, the Baltic states, or any of Eastern Europe. Let alone Vietnamese. Making Windows more international-friendly is a worthy cause, so I wonder whether this effort can be improved?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Version Independent ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Content: [PowerToys Quick Accent utility for Windows](https://learn.microsoft.com/en-gb/windows/powertoys/quick-accent)
* Content Source: [hub/powertoys/quick-accent.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by derekschinke** [comment]
yeah, tried to use it to type in Polish, and immediately found it doesn't cover the majority of the diacritics featured in the language.

**Comment by Jay-o-Way** [comment]
FYI: this subject is (still) in progress. Maybe @damienleroy can clarify?

**Comment by damienleroy** [comment]
Hello, indeed this is in progress. Diacritics are not implemented all at once. People can contribute to new languages, or ask to implement what they want.
Please also know there is no plan for no-Latin based characters.
Therefore we are trying our best, but it is not exclude some characters can be missed. In that case don't hesitate to create an issue for that.

**Comment by Jay-o-Way** [comment]
FYI @mattwojo

**Comment by mattwojo** [comment]
Thank you all! Closing as there does not seem to be an update needed to the documentation here. If you would like to file an issue or contribute an update to add further accent support, please do so in the PowerToys product repo, here: https://github.com/microsoft/PowerToys/issues
