### ISSUE TITLE
Imaginary keys in French

### ISSUE THREAD

**Issue by gt-novelt** [MicrosoftDocs/windows-uwp#4079]
The french translation doesn't make any sense:
![image](https://user-images.githubusercontent.com/37072369/194010309-0cc5f567-07bc-4ca7-a774-d0907a55139a.png)
Should be
- <kbd>⊞ Win</kbd>+<kbd>Shift</kbd>+<kbd>Q</kbd>
- <kbd>⊞ Win</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>
- <kbd>⊞ Win</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4b22118-da48-5b54-9afa-00e372e3c4c4
* Version Independent ID: a14d3309-a07e-d9b4-9fd6-c17fbe1f93e2
* Content: [PowerToys Video Conference Mute utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/video-conference-mute)
* Content Source: [hub/powertoys/video-conference-mute.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/video-conference-mute.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
https://en.wiktionary.org/wiki/shift#Noun -> 3.

**Comment by mattwojo** [comment]
Hmm... investigating how to request an update to this translation. Thanks for bringing this to our attention.

**Comment by mattwojo** [comment]
Adding "Shift" to the no-Loc list so that it will not be (incorrectly) translated. It will take a while for this change to be reflected on the live site due to the localization pipeline.

**Comment by Jay-o-Way** [comment]
> Adding "Shift" to the no-Loc list

Can also be done "in-line" https://learn.microsoft.com/contribute/markdown-reference#non-localized-strings

**Comment by Jay-o-Way** [comment]
> Adding \"Shift\" to the no-Loc list so that it will not be (incorrectly) translated

@mattwojo not sure if it will work like I think it will, but I assume you realize that "shift" is still both a noun and a verb; which _should_ be translated in other context?
