### ISSUE TITLE
Do settings in PowerToy remains if I close the app (even close system tray)

### ISSUE THREAD

**Issue by cndhng** [MicrosoftDocs/windows-uwp#4088]
I am sorry but I couldn't find it anywhere the question. I hope it is okay to ask here. Thank you very much

**Comment by jaimecbernardo** [comment]
Hi, Settings in PowerToys are supposed to be saved even if you close the Settings Windows / PowerToys. Are you having issues with it? The PowerToys repo is the right place to open issues in that case: https://github.com/microsoft/PowerToys/
Hope this helps.

**Comment by cndhng** [comment]
Hi I still can't figure out the way to completely close the app without customized settings working.

**Comment by mattwojo** [comment]
It seems that this doesn't require an update to documentation, so closing here. For issues related to the PowerToys Settings functionality, please file in the product repo here: https://github.com/microsoft/PowerToys/
