### ISSUE TITLE
How to lookup x:Key value in code-behind

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#4089]
Haven't been able to find in the docs yet how to get an object instance's `x:Key` attribute value in code-behind.

e.g. I have a resource dictionary object or a reference to a style. How do I get it's `x:Key` attribute value from a reference to the object at runtime.

This would similarly apply to `x:Name` I believe as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac0dab82-8246-2391-e0c4-e6404c8fb207
* Version Independent ID: 0898f58b-862b-5e20-21c1-34a9f3f31a2c
* Content: [xKey attribute - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-key-attribute)
* Content Source: [windows-apps-src/xaml-platform/x-key-attribute.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/xaml-platform/x-key-attribute.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
The resource dictionary is an IDictionary (with some extras). So just like an IDictionary there's no built-in way to find an item's key.

So 

```xml
    <ResourceDictionary>
        <x:String x:Key="Hello">World</x:String>
    </ResourceDictionary>
```
is equivalent to

```cs
    var dictionary = new Dictionary<object,object>();
    dictionary["Hello"] = "World";
```

**Comment by michael-hawker** [comment]
@MikeHillberg someone else told me the same thing, I guess I wasn't clear here. This is in the case where I don't have a reference to the resource dictionary itself. I have the object within it or am in a templated control.

I want to be able to get the x:Key value defined on my instance. E.g.

```xml
<ResourceDictionary>
    <Style x:Key="SomeStyle" ... />
 </ResourceDictionary>
 ```

Now in my code, I have an instance reference to the `Style`, how do I get the `x:Key` associated with it if I don't have a reference to the `ResourceDictionary`? It seems like that's not possible?

----

The other scenario is in a control. If I have the following defined:

```xml
<ResourceDictionary>
     <x:Double x:Key="TemplatedControlMaxWidth">500</x:Double>

    <Style x:Key="TemplatedControlStyle" ...>
        <Style.Setters>
            <Setter Target="MaxWidth" Value="{StaticResource TemplatedControlMaxWidth}"/>
        </Style.Setters>
        ...
    </Style>
 </ResourceDictionary>
 ```

Now, let's say in the code-behind for the templated control I wanted to get the resource value for `TemplatedControlMaxWidth` defined by the containing control's `ResourceDictionary`, how can I do that?

It's not part of the control's resources, and if I walk up, unless the developer has overridden it, then I can't get the value either, right?

**Comment by MikeHillberg** [comment]
Right, it's not possible. It's just like in this code, given "World", you can't find "Hello":

```cs
    var dictionary = new Dictionary<object,object>();
    dictionary["Hello"] = "World";
```

Xaml markup doesn't create a _runtime_ notion of a tree. Sometimes it creates objects that have tree-ness, for example Button has a Parent property, but that's a particular case for elements not markup in general:

```xml
<Grid>
    <Button />
</Grid>
```

The reason the `{StaticResource}` reference can find resources is that markup does have a _load time_ tree; the reference is resolved by walking up the stack that exists during parse.
