### ISSUE TITLE
Bluetooth RFCOMM Corrections

### ISSUE THREAD

**Issue by djaus2** [MicrosoftDocs/windows-uwp#409]
Re:
https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/send-or-receive-files-with-rfcomm
I have code corrections for this page. There are quite a few to get it to the compilation stage.
I also have a working version of the app on GitHub.

Q 1: Should I proceed to make the code corrections on the page?
Q 2: Can I some how link to my GitHub project or can it be absorbed into the UWP Samples?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @djaus2 - I was reviewing old issues and found this one assigned to me in October of last year. I see that you opened it much earlier than that. Please let me know if you updated the topic with your code corrections already. If not, please feel free to edit the topic and submit a PR for me to review. Thanks!

**Comment by Karl-Bridge-Microsoft** [comment]
Hi again @djaus2 - I reviewed PRs for this topic and noticed that https://github.com/MicrosoftDocs/windows-uwp/commit/2184f79affcc88acad1d66413350c1dff0086377#diff-22efa8a62afd7fff3e6fac692bdf28af addressed a lot of code updates, so I suspect your issues have been resolved. I'll close this issue, but please submit a PR with any other updates you might have. Thanks!
