### ISSUE TITLE
error when using winget command

### ISSUE THREAD

**Issue by ryanNewcodeer123** [MicrosoftDocs/windows-uwp#4090]
Hi, I just want to use a widget to install a package on Powershell. But when I typed winget it said: 

winget: The term 'Winget' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the way is correct and try again.
At line:1 char:1
+ winget
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---

 what should I do? 
 I am using Windows 11 Home Version 2H2 and have already installed the app installer.

thanks so much.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6165305c-791a-4807-5f2f-7d080d176a9f
* Version Independent ID: 9cc8d841-e2e5-37e0-ccff-03da404f04be
* Content: [Debugging and troubleshooting issues with the winget tool](https://learn.microsoft.com/en-us/windows/package-manager/winget/troubleshooting)
* Content Source: [hub/package-manager/winget/troubleshooting.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/troubleshooting.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Guessing you've resolved this issue by now. This is likely just related to an update needed on the Windows version installed on your machine. I don't believe there is any required update to the WinGet documentation, so closing this issue. Please re-open if this is not the case.
