### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Bibase** [MicrosoftDocs/windows-uwp#4095]
The image size is given twice but differs, 600 by 320 and 620 by 300

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0fe87b-78e1-64a6-a7ed-51d8a6373a5d
* Version Independent ID: 71898667-5572-11bb-f53c-0d1ebc77511d
* Content: [Display a splash screen for more time - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/create-a-customized-splash-screen)
* Content Source: [windows-apps-src/launch-resume/create-a-customized-splash-screen.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/launch-resume/create-a-customized-splash-screen.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for raising this issue. I will correct the one that states 600x320. The correct size is 620x300. I will also remove the outdated reference to VS 2015. This applies to all VS versions, up to VS 2022. I will circle back and close this issue when the changes are merged.

**Comment by alvinashcraft** [comment]
This fix has been merged and should be visible on the live site later today. Thanks again for your contribution!
