### ISSUE TITLE
Lower links do not work

### ISSUE THREAD

**Issue by sanjayssk** [MicrosoftDocs/windows-uwp#4097]
The lower section's links are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06f54870-f12b-d72f-3899-a188bba87627
* Version Independent ID: 06f54870-f12b-d72f-3899-a188bba87627
* Content: [Publish your app in the Microsoft Store - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/overview?pivots=store-installer-msix)
* Content Source: [hub/apps/publish/publish-your-app/overview.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/overview.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
Links have been corrected, thank you.
