### ISSUE TITLE
I could not able to install it for hindi

### ISSUE THREAD

**Issue by Vikuzu** [MicrosoftDocs/windows-uwp#4098]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Version Independent ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Content: [PowerToys Text Extractor utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor)
* Content Source: [hub/powertoys/text-extractor.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. What do you mean exactly? And what steps have you performed in order to achieve it?

**Comment by alvinashcraft** [comment]
Hello @Vikuzu. Could you provide some additional details about your issue? Is this an issue in the documentation, or a problem that you're having with the product? Any product issues can be opened in the [PowerToys repo](https://github.com/microsoft/PowerToys/issues). Thank you!

**Comment by alvinashcraft** [comment]
Hi @Vikuzu. We haven't heard anything back about this. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. If this is about the PowerToys product, you can leave feedback [here](https://github.com/microsoft/PowerToys/issues). Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
