### ISSUE TITLE
PRI size limitation

### ISSUE THREAD

**Issue by m4verick** [MicrosoftDocs/windows-uwp#410]
hello guys, can we know the PRI size limitation, since we have corrupted 5 MB PRI files contains of 28k file ? Because when we submit to microsoft cert, it returns this message : 

"The resources.pri in the package was corrupted so encryption failed (error PRI222: 0xdef0000f - Unspecified error occurred)"

Can we have solution in here ? Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a023f8d6-a789-862b-6b1c-40fab5ef83f5
* Version Independent ID: b32d828c-3bf4-b942-00be-a59a71799bc4
* Content: [Resource Management System - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/app-resources/resource-management-system#feedback)
* Content Source: [windows-apps-src/app-resources/resource-management-system.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/resource-management-system.md)
* Service: **unspecified**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, Frederik, the size limit on a PRI file is 64 kilobytes (I've updated the topic with that info). If issues persist with a file below that limit then contacting support is advisable: https://support.microsoft.com/contactus/. Alternatively, the developer community is available, and responsive: https://developercommunity.visualstudio.com. Thanks for pointing out the missing info, I appreciate that! -Steve

**Comment by m4verick** [comment]
hi, Steve. Thanks for your answer. But we already try to have 800KB of PRI files and it's OK for submission.
So I wonder, do you know what's mean of this error message : The resources.pri in the package was corrupted so encryption failed (error PRI222: 0xdef0000f - Unspecified error occurred)

Do you have any possibilities, what needs to check for that kind of error ? 

Really2 appreciate your response, Steve.

**Comment by stevewhims** [comment]
One scenario in which you can hit that error message is when you dump a schema-free resource pack without specifying the main file. A schema-free resource pack is one that was created with the omitSchemaFromResourcePacks switch in the PRI config file. To dump a schema-free resource pack, use the switch `/es <main_package_PRI_file>` with makepri.exe. However, if you're running into the error message for a different reason, then Microsoft support would need to take a look at your files (https://support.microsoft.com/contactus/).

**Comment by stevewhims** [comment]
@m4verick, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Comment by avakhrushev** [comment]
>the size limit on a PRI file is 64 kilobytes

What is the source on that? 64kb sounds like way to little to be of practical use.
Just like m4verick, I seem to have no issues with .pri file sizes in megabytes range. It looks more like it's the number of resource names that might be capped at 64k?
