### ISSUE TITLE
Maintaining access to user data when migrating from UWP to WinUI 3

### ISSUE THREAD

**Issue by mikegoatly** [MicrosoftDocs/windows-uwp#4101]
Is there any guidance on migrating a user's app data when migrating from UWP to WinUI 3? 

When upgrading to WinUI 3, from what I can see app data is no longer loaded from the same location (i.e. `\AppData\Local\Packages\PACKAGENAME\LocalState`) - how should developers go about performing a seamless upgrade so that a user's data is unaffected when the app is upgraded?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d50fa20-7181-81ae-b98e-5fef477f099a
* Version Independent ID: 9d50fa20-7181-81ae-b98e-5fef477f099a
* Content: [What is supported when migrating from UWP to WinUI 3 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mikegoatly, that's a great question. I'll pass this suggestion along to the product team for migration guidance.

Since I don't have any recommendations to add to the docs (around migrating users' app data). I'll close this issue. If/when such guidance reaches me, I'll publish it.

Thanks again!
-Steve

**Comment by mikegoatly** [comment]
Thanks @stevewhims - hopefully the product team can offer some insights
