### ISSUE TITLE
Non-Existent References to "MainPage"

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4102]
Page says

> Open MainPage.xaml, which contains the XAML markup for our main UI page.

There is no MainPage.xaml in the Project Solution

Page says

> Also, add the following include directive to MainPage.h

There is no MainPage.h in the Project Solution

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7aad2d1a-fe9c-04ed-2fae-545f071c1f46
* Version Independent ID: f8d878ef-1d8d-9b12-5ac9-f7b936916fea
* Content: [Build XAML controls with C++/WinRT - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3)
* Content Source: [hub/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/xaml-templated-controls-cppwinrt-winui-3.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this. The pages have been updated to use MainWindow instead of MainPage to match the current templates.
