### ISSUE TITLE
Windows App Store Availability

### ISSUE THREAD

**Issue by levdoescode** [MicrosoftDocs/windows-uwp#4104]
Hello, it seems PowerToys is not available in the Windows App Store, the link opens up the store but doesn't show the page for PowerToys and searching for it in the store doesn't find it either.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
The link opens `https://apps.microsoft.com/store/detail/microsoft-powertoys/XP89DCGQ3K6VLD`, so it works now

**Comment by mattwojo** [comment]
Confirmed. Closing. If you continue to see an issue, please reopen.
