### ISSUE TITLE
Widgets link in feature table leads to 404

### ISSUE THREAD

**Issue by gabbybilka** [MicrosoftDocs/windows-uwp#4109]
@drewbatgit 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/20007011/198116747-4fd77a00-89d5-4043-8ca5-c006f9d8ce21.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67d1132c-974a-7dbc-6c46-2ebbc47e9944
* Version Independent ID: 732091d2-ebcd-dc09-7ed1-ac339ecf834d
* Content: [Windows App SDK release channels - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel)
* Content Source: [hub/apps/windows-app-sdk/release-channels.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/release-channels.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by Karl-Bridge-Microsoft** [comment]
Link fixed
