### ISSUE TITLE
Design Software + More Robust

### ISSUE THREAD

**Issue by ahainen** [MicrosoftDocs/windows-uwp#411]
Searching for icons on this page is super frustrating. I have to guess what the icon name is, I would much rather prefer if the icons had tags. (Obviously they need a unique icon name, but tags would help as well). Also, getting these icons into Sketch (OSX) is a total pain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by ahainen** [comment]
What other info/details can I provide for this? I can do a screen recording of the paint points if needed.

**Comment by mijacobs** [comment]
Hi Ahainen, 
There are certainly a lot of icons and I agree they can be difficult to browse. Could you provide some examples of the tags you're thinking of? Regarding getting the icons into Sketch--you can now download the Segoe MDL2 font from our design downloads page: https://docs.microsoft.com/en-us/windows/uwp/design/downloads/

**Comment by ahainen** [comment]
Here's a more in depth example of the problem: https://youtu.be/RzohF-Wbdy8

**Comment by ahainen** [comment]
Anything on this? "No news" is totally fine, just curious.

**Comment by mijacobs** [comment]
Hi @ahainen, my apologies for the delayed response! I shared your feedback with the typography team and they agree that the experience could be improved. Short, term, I started working with them to get the list updated. I just emailed them to check on the status.

**Comment by mijacobs** [comment]
I heard back from the toolkits team--they've watched your video and are investigating ways to improve the font experience in Sketch.

**Comment by ahainen** [comment]
Just checking in on this

**Comment by ghost** [comment]
I fully support Andrew.

MDL is already very voluminous in terms of the number of specific icons that are used only in Windows, it’s time for the team to think about creating an icon manager with tags, search and convenient copying of icons. To avoid the bulkiness of the manager, they need to be further divided into places where they are used: taskbar, titlebar, toolbar, etc.

**Comment by mijacobs** [comment]
From the feature team: 

The issue with Mac and Sketch relates to icons and Unicode Private use area. There is no fallback for PUA even on Windows. I’m not sure why this works for some icons and not others. The user should contact Sketch to discuss lack of support for PUA icons.
Some of our icons are available as svg through Fabric. https://uifabricicons.azurewebsites.net/ while that will help with Sketch issues, it doesn’t help anyone with keywording.

Because of the limitations of markdown, there's not a practical way to improve the browsing experience on this page.
