### ISSUE TITLE
Worthless

### ISSUE THREAD

**Issue by crussell9635** [MicrosoftDocs/windows-uwp#4112]
I cannot install Dropbox Screen Capture app.  I learned from this page I must set the Developer Mode "on" in Windows 11.  

Unfortunately, the steps described on this page needed to do this are incorrect.  My "Developer Mode" setting options are greyed out and cannot be turned on.  15 minutes of my time I will never get back.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb82418-b583-7023-f2e3-c3dca7d3245c
* Version Independent ID: 0a65ac0a-9884-52a8-6485-c2825b1fb4d9
* Content: [Enable your device for development - Windows apps](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development?OCID=WinClient_Ver1703_Settings_DevMode)
* Content Source: [hub/apps/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/enable-your-device-for-development.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
This page contains a note making it clear that you require administrator access to activate Developer Mode. Based on what you describe, I think that's the issue you ran into here. I'm sorry that you've encountered this trouble, but I don't think any doc changes are required here.
