### ISSUE TITLE
I cannot see how to set the price of my application.

### ISSUE THREAD

**Issue by conmol** [MicrosoftDocs/windows-uwp#4119]
After weeks of trying, I can't figure out how to set the price for my application, which is in the MSI EXE category. Specifically, application is an EXE built using the MFC framework and the installer is an EXE file.

I have found no way to submit a price. Perhaps this is because I selected more than one market, i.e., more than one country?

I must be missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2d5e61b-9914-b516-c450-2d97550bd880
* Version Independent ID: e2d5e61b-9914-b516-c450-2d97550bd880
* Content: [Set app pricing and availability - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/price-and-availability?pivots=store-installer-msix&source=recommendations)
* Content Source: [hub/apps/publish/publish-your-app/price-and-availability.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/price-and-availability.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Xangis** [comment]
I too submitted an EXE installer app, and although I set the pricing to paid, I was unable to set a price before the app was published. This feature is just *missing*. Please implement this. I had to delist my app after going through the entire submission approval process because there was no way to set a price for it.

There is a related post in the developer support forum:
https://learn.microsoft.com/en-us/answers/questions/1146836/one-time-payment

**Comment by GrantMeStrength** [comment]
Docs have been updated. https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/schedule-pricing-changes?pivots=store-installer-msi-exe

**Comment by lastlink** [comment]
the answer is that they are only supported for MSIX apps and not MSI apps. MSI pricing is only a note and doesn't let you use the microsoft billing mechanism. See https://learn.microsoft.com/en-us/answers/questions/1259571/how-do-i-set-the-price-of-a-windows-app-in-the-mic. The docs on https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/msi/set-app-pricing for MSI should probably be updated with a note on this. https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/msix/schedule-pricing-changes looks correct.
