### ISSUE TITLE
Invalid PowerShell Install Example

### ISSUE THREAD

**Issue by bedales-stsmith** [MicrosoftDocs/windows-uwp#4124]
The provided PowerShell installation example is not recognized when executed.
`winget-install Microsoft.PowerToys --source winget`

Removing the hyphen works correctly.
`winget install Microsoft.PowerToys --source winget`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
@mattwojo Looks like this has been updated in the mean time

**Comment by mattwojo** [comment]
Resolved. Please feel welcome to re-open if you continue to see any issues.
