### ISSUE TITLE
content error 

### ISSUE THREAD

**Issue by jeffbuzz** [MicrosoftDocs/windows-uwp#4125]
`winget-install Microsoft.PowerToys --source winget`

should read

`winget install Microsoft.PowerToys --source winget`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Good catch. Thanks @jeffbuzz!

**Comment by mattwojo** [comment]
Fixed in: https://github.com/MicrosoftDocs/windows-dev-docs/commit/a55427f43b64380220cbde389bfc0f17e6b4c4d6
