### ISSUE TITLE
NVM not prescribed for shared develper boxes or build servers with multiple build agents

### ISSUE THREAD

**Issue by vbjay** [MicrosoftDocs/windows-uwp#4127]
NVM works by using a symbolic link.  The problem is the link is pointed to a user's app data folder.  So if user x runs ```nvm use lts``` they will point node for the whole box to their app data folder.  If user y runs node or npm they will be directed to run files under x's user account and in the case of ```npm -g``` they will be modifying x's files which by default is not allowed.  So nvm is only prescribed for one developer box.  This goes for build servers too.  If two build agents on same vm/box, they can compete and cause odd behavior in the builds.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for pointing this out @vbjay! I'm adding a warning note to the doc to help raise awareness of this issue. Really appreciate the contribution! <3

**Comment by mattwojo** [comment]
Commit with your update > https://github.com/MicrosoftDocs/windows-dev-docs/commit/85819734ddc1b96ad74e6ab715faae28f07c4767

Closing as resolved. Thanks again!
