### ISSUE TITLE
No option for UWP ?

### ISSUE THREAD

**Issue by Shadolio** [MicrosoftDocs/windows-uwp#4130]
So UWP Apps cannot be Widget Providers ? 😢 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 969a13d0-8194-7c66-5194-02c695b14abd
* Version Independent ID: 969a13d0-8194-7c66-5194-02c695b14abd
* Content: [Widget providers - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/widgets/widget-providers)
* Content Source: [hub/apps/develop/widgets/widget-providers.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/widget-providers.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@Shadolio  No, sorry. UWP apps aren't supported at this time. I will +1 the request to the feature team so that it can inform their decisions about future support for UWP.
