### ISSUE TITLE
Run-time error in "Create a new project for an unpackaged C# or C++ WinUI 3 desktop app"

### ISSUE THREAD

**Issue by petr-larin** [MicrosoftDocs/windows-uwp#4132]
I follow the tutorial
**Create a new project for an unpackaged C# or C++ WinUI 3 desktop app**

It compiles just fine, but when I run it, it throws an unhandled exception and calls abort().

At the same time, the tutorial 
**Packaged: Create a new project for a packaged C# or C++ WinUI 3 desktop app**

compiles and runs fine.

Here's a screen shot from the former:

![in_debug](https://user-images.githubusercontent.com/113700952/200360047-698c1eb1-986b-434e-a0fe-21b82d90e9c5.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 (Windows App SDK) project - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @petr-larin, I'm investigating.

-Steve

**Comment by petr-larin** [comment]
After upgrading to VS 17.4.0 and WindowsAppSDK 1.2.221109.1 the issue is gone.

**Comment by stevewhims** [comment]
Thanks, @petr-larin! I'm glad that that resolved it. That is exactly what the SME said, too:

"There is a known issue that using unpackaged apps will not install the required runtime (when running from within VS). Windows App SDK version 1.2 was released last week, so I would update the app to 1.2, install the 1.2 runtime and see if the issue persists."

Thanks again!
-Steve
