### ISSUE TITLE
"Send a local toast notification from a C# app - Windows apps" - Missing instruction about BuiltInComInteropSupport?

### ISSUE THREAD

**Issue by jon-freed** [MicrosoftDocs/windows-uwp#4136]
The simple example in "Step 2: Send a toast" did not work for me until I edited my project .csproj file's `PropertyGroup` section and added `<BuiltInComInteropSupport>true</BuiltInComInteropSupport>`.  (I learned about that through the answer at https://stackoverflow.com/a/69200541/4270771.)

Until I made that edit, I saw an exception like the following:  `toast failed initializing notifications notsupportedexception built-in com has been disabled via a feature switch`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11bc1ceb-510e-22c9-1f7a-a421ae52901b
* Version Independent ID: 0efae90c-e517-b54d-8e81-ebbd69d2270d
* Content: [Send a local toast notification from a C# app - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/send-local-toast.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/shell/tiles-and-notifications/send-local-toast.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
