### ISSUE TITLE
Naming convention for input/output nodes

### ISSUE THREAD

**Issue by sharmaa5** [MicrosoftDocs/windows-uwp#414]
Is there any restriction on the node names for graph inputs and outputs? Trying to load pre-trained onnx models from [ONNX tutorials assets](https://github.com/onnx/tutorials/tree/master/tutorials/assets) (squeezenet.onnx, super_resolution.onnx) into WinML samples. But the input and output nodes have numeric names ("1", "27" etc) which causes issues in the corresponding Windows ML generated code (error CS1519: Invalid token '1' in class, struct, or interface member declaration). If WinML requires node names to start with an alphabet, is there a tool to edit pre-trained onnx models in order to rename the nodes?

**Comment by serenaz** [comment]
ONNX requires “All names MUST adhere to C identifier syntax rules”: https://github.com/onnx/onnx/blob/master/docs/IR.md 

Currently, you can't edit the names, but we're working on it! 

In the meantime, you can try using the models from the ONNX model zoo at https://github.com/onnx/models. The Squeezenet there seems to meet the naming requirement.
