### ISSUE TITLE
The article was helpful

### ISSUE THREAD

**Issue by JovinMtl** [MicrosoftDocs/windows-uwp#4141]
[Enter feedback here]
Thank you for this concise article. it helped me to install VueJs. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d64d47d9-2d0d-ba67-a99b-e296fac36861
* Version Independent ID: dd7e91a2-1bed-337f-a2be-ebf8cb0b071d
* Content: [Install Vue.js directly on Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/vue-on-windows)
* Content Source: [hub/dev-environment/javascript/vue-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/vue-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for the nice feedback @JovinMtl!
