### ISSUE TITLE
Error in the proposed shortcut for the screen ruler...

### ISSUE THREAD

**Issue by huotg01** [MicrosoftDocs/windows-uwp#4142]
Hi.

The documentation on the page proposes to use the shortcut Shift+Window+T to launch the screen ruler.
It should be SHIFT+Window+M

![image](https://user-images.githubusercontent.com/3483165/201482557-14401c8c-003d-4972-a3bf-1d6e37c60427.png)

Gaston

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/?source=recommendations)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @huotg01!
Fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/e5fb47d38857d8ad63f6eef45ed062d5e55d247c
