### ISSUE TITLE
Deploy checkbox is disabled, application doesn't compile

### ISSUE THREAD

**Issue by TimKadyrov** [MicrosoftDocs/windows-uwp#4147]
Created new blank WinUI Blank App with Packaging project (WinUI in Desktop), followed the guide at very end in Configuration Manager tickbox 'Deploy' is disabled for any active configuration.
Also, cannot run application got:
System.DllNotFoundException: 'Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0401c948-1dda-c819-ee88-902ac6fcbbd9
* Version Independent ID: c1748244-0f46-8dec-a88e-020f12d9a387
* Content: [Package your app using single-project MSIX - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp)
* Content Source: [hub/apps/windows-app-sdk/single-project-msix.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/single-project-msix.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @TimKadyrov. I'm investigating.

-Steve

**Comment by stevewhims** [comment]
Just an update. It seems that adding `<EnableMsixTooling>true</EnableMsixTooling>` is necessary. There was also a missing step around setting the asset files to Content.

I've fixed those issues in the topic, so it should be good now.

Thanks!
-Steve
