### ISSUE TITLE
Eyedropper does not facilitate capture and subsequent use of HDR/WCG colors

### ISSUE THREAD

**Issue by cgrobb** [MicrosoftDocs/windows-uwp#4148]
The eyedropper tool does not facilitate capture and subsequent use of HDR/WCG colors which are becoming pervasive (e.g. games/game design). To the extent it won't continue to work with HDR/WCG, that limitation should be noted on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10d36d20-6ec9-415f-0c79-7cedae3afd99
* Version Independent ID: fa8782b8-bba2-8be8-3472-d8876dfa8713
* Content: [PowerToys Color Picker utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/color-picker)
* Content Source: [hub/powertoys/color-picker.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/color-picker.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @cgrobb. I added this limitation to the documentation. (see https://github.com/MicrosoftDocs/windows-dev-docs/commit/e340acfbdf2eb7ea2767be176ba16eac46e07e4f)

You can also consider adding a request for this support to be added to the tool in the PowerToys product repo here: https://github.com/microsoft/PowerToys/issues

Thanks for this contribution!
