### ISSUE TITLE
Troubleshoot debugging

### ISSUE THREAD

**Issue by luskan** [MicrosoftDocs/windows-uwp#415]
My AppServiceProvider was a C++ project, to make OnRequestReceived breakpoints trigger I had to change in AppServiceProvider properties->Debugging->Debugger Type to "Managed and Native" (initially it was only Native).

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - UWP app developer](https://docs.microsoft.com/pl-pl/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by eliotcowley** [comment]
Hi @luskan, sorry for the delay on this. I was able to make the **OnRequestReceived** breakpoint trigger in my C++ **AppServicesProvider** project while the **Debugger Type** was still set to **Native Only**. Can you confirm that you made sure to: 

1. Set **Launch Application** to **No**. 
2. Set the **AppServicesProvider** project as the start-up project. 
3. Run it from Visual Studio. 
4. Run the client app from the start menu.

Thanks!

**Comment by eliotcowley** [comment]
Closing due to lack of response. @luskan please feel free to re-open if you're still having this issue.
