### ISSUE TITLE
Incorrect X-WNS-Type

### ISSUE THREAD

**Issue by aqibbanday** [MicrosoftDocs/windows-uwp#4150]
instead of toast it should be "wns/toast"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b81f1e6-4945-60eb-76bf-0f60d68ba480
* Version Independent ID: 41f4799e-83ba-f0a8-43ae-770f8f0edb3e
* Content: [Quickstart Push notifications in the Windows App SDK - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push-notifications/push-quickstart)
* Content Source: [hub/apps/windows-app-sdk/notifications/push-notifications/push-quickstart.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/notifications/push-notifications/push-quickstart.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
@aqibbanday Thank you for catching this. The page has being updated with the fix.
