### ISSUE TITLE
Webpage title issue

### ISSUE THREAD

**Issue by victorroz** [MicrosoftDocs/windows-uwp#4155]
Title of the webpage is coming up as **_and Headings - Windows apps | Microsoft Learn_** instead of **_Landmarks and Headings - Windows apps | Microsoft Learn_**. After inspecting the page code, I can see that the latter is written, yet **_Landmark_** is not showing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 974392c3-8d61-6360-84ff-afe1b96120e7
* Version Independent ID: 95418e2f-976b-f52b-5629-ad605c3bafc7
* Content: [Landmarks and Headings - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/accessibility/landmarks-and-headings)
* Content Source: [hub/apps/design/accessibility/landmarks-and-headings.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/accessibility/landmarks-and-headings.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Might be a brief rendering glitch. Title does not contain formatting that would cause this and I can't repro issue. Closing, but feel free to reopen if you continue to encounter the issue.
