### ISSUE TITLE
The "build!" macro no longer exists in the windows-rs crate

### ISSUE THREAD

**Issue by jaymichaud** [MicrosoftDocs/windows-uwp#4158]
The guidance in this tutorial is out of date because the "build!" macro no longer exists in the windows-rs crate. I was able to find that it was removed on 2021-11-17 in [pull request 1338](https://github.com/microsoft/windows-rs/pull/1338), commit [962020a7c634843a8bf442c217de87967c30973e](https://github.com/microsoft/windows-rs/pull/1338/commits/962020a7c634843a8bf442c217de87967c30973e). The replacement macro from that commit, "build_legacy!", is also missing in the most recent version of the windows-rs crate (v0.43.0), but I didn't track down when that was removed.

This tutorial does specify to use v0.9.1 of the windows-rs crate; however, if users want to use a more recent version, then the tutorial's guidance is no longer valid. Would you please rewrite the tutorial to provide instructions based on the current version of the windows-rs crate?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://learn.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jaymichaud, and thanks for filing this issue. I have a work item on my backlog for this update, and I'll get to that when I get chance. I've added a link from that work item to this issue so that I can update this issue in due course. Meanwhile, so as not to track the work in multiple places, I'll close this issue.

Thanks!
-Steve
