### ISSUE TITLE
Docs should not recommend to install certificates in the Trusted Root Certificate authorities

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/windows-uwp#416]
There is a note in /windows/uwp/packaging/packaging-uwp-apps saying:

>... you will need to install the signing certificate to the Trusted Root Certification Authorities store on the device ..

This should be not recommended as it has another security implications, instead we should suggest to install in the Trusted People or Trusted Publishers.

The link to "Install Test Certificates" goes to a page in the Hardware dev center, that could be intimidating for application developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1c88d-24b1-0eda-b458-105db02dca36
* Version Independent ID: c5d1634a-0ead-f68a-e5be-89acf0eef0a6
* Content: [Packaging UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
Thanks, Rido. I'll make the updates!
