### ISSUE TITLE
Time and date direct activation should be changed from `)` to `(`

### ISSUE THREAD

**Issue by Eragra3** [MicrosoftDocs/windows-uwp#4164]
Time and date plugin shows `)` (closing parenthesis) character as direct activation command.
On my machine it seems to be `(` (opening parenthesis).

Maybe it got changed in newer version of PowerToys?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b951899-69ca-9057-f799-14491e1b0a74
* Version Independent ID: 18e0202f-3e91-a5b9-62f2-6cd40e5661a8
* Content: [PowerToys Run utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/run)
* Content Source: [hub/powertoys/run.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
`(` was changed because it had too many conflicts. @Eragra3 what version are you using?

@mattwojo In other words: **Docs are correct.**
![image](https://user-images.githubusercontent.com/65828559/204415652-a50edfb8-d003-40cd-bff3-b47743cb80a7.png)

**Comment by Jay-o-Way** [comment]
See

- #3957
- https://github.com/microsoft/PowerToys/issues/18490
- https://github.com/microsoft/PowerToys/pull/19593

We've included a message at https://learn.microsoft.com/windows/powertoys/run#direct-activation-commands for this exact situation.

**Comment by Eragra3** [comment]
@Jay-o-Way Hi, sorry I didn't respond earlier.
That's interesting, because it's still `(` for me. I am using latest version
![obraz](https://user-images.githubusercontent.com/9082983/213536600-a865c86c-bdec-4bf1-8f7d-a2a66ee03cc2.png)
And this is what I get
![obraz](https://user-images.githubusercontent.com/9082983/213536967-6c47b42e-8e7e-43a7-b67e-ee142ca0dec7.png)


I have mixed region settings, you can see it shows results in polish, I don't know if that's why.
Also I have used PowerToys for quite long time, so maybe something is lingering from previous versions.

**Comment by Jay-o-Way** [comment]
@Eragra3 probably: the setting was kept from the older settings for the app. Actively changing existing "keywords" was probably too disruptive.

**Comment by Eragra3** [comment]
Cool, that's ok.
Seems a little bit confusing these settings don't migrate by default, but it's not really a problem for me.

Do you want me to reinstall to confirm?
I think we can close the issue otherwise.

**Comment by Jay-o-Way** [comment]
@mattwojo Would you like to close this issue and pr 4231 please?
