### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MATHEESHA2** [MicrosoftDocs/windows-uwp#4165]
[Good but not comfatable]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdcd2ee1-04fd-c7be-adee-72faa345ebb7
* Version Independent ID: a44a4676-c56a-712a-eba2-11e5335c6764
* Content: [list Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/list)
* Content Source: [hub/package-manager/winget/list.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/list.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Hi @DARKEMPIRESL -- I will need more information about what the actual issue here is in order to resolve this.
