### ISSUE TITLE
Issue using location DeviceCapability 

### ISSUE THREAD

**Issue by pipearias2** [MicrosoftDocs/windows-uwp#4169]
Hello,

I'm currently working on a windows desktop application, and I'm trying to get the location, but I think this documentation is outdated

this is the image in the microsoft.com

![image](https://user-images.githubusercontent.com/17144376/204449056-04e1498f-6ff3-46ea-99e8-5495caef020e.png)

but when i use it, this message appers.

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE014: error de validación del manifiesto de la aplicación: El manifiesto de la aplicación debe ser válido de acuerdo con el esquema: Línea 54, Columna 6, Motivo: De acuerdo con el modelo de contenido del elemento principal '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Capabilities', el contenido del elemento '{http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities}Capability' no es el previsto.
Se esperaba: {http://schemas.microsoft.com/appx/manifest/foundation/windows10}DeviceCapability.	MonitoringApp			

I've searched a lot to find a solution but I haven't succeeded, the last thing I tried was to use this configuration in the manifest

	<DeviceCapability Name="location">
		<Device Id="any">
			<Function Type="name:test"/>
		</Device>
	</DeviceCapability>

but didn't work.

the error always appears when I try to run the application

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39d8d43b-2a27-ee3a-eb4b-f03b84ef898c
* Version Independent ID: 5ba294d8-3af3-1a6a-f1a4-94161b3d3f80
* Content: [Get the user's location - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/maps-and-location/get-location#troubleshoot-your-app)
* Content Source: [uwp/maps-and-location/get-location.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/maps-and-location/get-location.md)
* Product: **uwp**
* Technology: **people-and-places**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
That is the correct syntax. I just tried it out myself and it worked correctly. I'm not sure what's causing the error you're seeing. I'm sure you've already seen it, but [this StackOverflow page](https://stackoverflow.com/questions/31889514/error-registration-of-the-app-failed) has some suggestions.
