### ISSUE TITLE
Acquisitions V2 no longer accepts ageGroup or xboxTitleIdHex as valid groupBy parameters

### ISSUE THREAD

**Issue by lenaguerrero** [MicrosoftDocs/windows-uwp#4171]
Requests to the `https://manage.devcenter.microsoft.com/v1.0/my/analytics/acquisitions` endpoint appear to no longer accept `ageGroup` or `xboxTitleIdHex` as values for the `groupBy` parameter and return an internal server error if those values are provided.

![image](https://user-images.githubusercontent.com/24362129/211621692-fcbb82d3-0204-4b3c-a8af-b03c9bc8c1d4.png)
(Image updated Jan 01, 2023 since it mistakenly captured orderBy instead of groupBy)

Both values are listed in the documentation as valid. Requests with these values were working as expected until December 1st, 2022 (or potentially a day or two earlier). An example request url and the resulting response body are below using the ageGroup value. The response is the same when including the xboxTitleIdHex parameter.

```
https://manage.devcenter.microsoft.com/v1.0/my/analytics/acquisitions?applicationId=[redacted]&startDate=11%2F1%2F2022&endDate=11%2F30%2F2022&aggregationLevel=day&orderby=date&groupby=applicationName%2CacquisitionType%2CstoreClient%2Cgender%2Cmarket%2CosVersion%2CpaymentInstrumentType%2CsandboxId%2CdeviceType%2CageGroup
```

```
{
  error: "Http request failed with error code 'InternalServerError'. Request url: https://pacedataservice.trafficmanager.net/api/Acquisitions/acquisitionsv2?applicationId=[redacted]&startDate=11%2F1%2F2022&endDate=11%2F30%2F2022&aggregationLevel=day&$orderby=date&groupby=applicationName%2CacquisitionType%2CstoreClient%2Cgender%2Cmarket%2CosVersion%2CpaymentInstrumentType%2CsandboxId%2CdeviceType%2CageGroup, error response content: No property or field 'ageGroup' exists in type 'AcquisitionV2'"
}
```

Edit Jan 1, 2023: The document details below appear to be inaccurate. The Content in question is located at [https://learn.microsoft.com/en-us/windows/uwp/monetize/acquisitions-data](https://learn.microsoft.com/en-us/windows/uwp/monetize/acquisitions-data) not the legacy API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3829d4a4-d77f-f2d0-82e2-0b5c6c0d0713
* Version Independent ID: 63ef4a74-29cc-f5cd-57cb-a9cfbe7c7b7d
* Content: [Get app acquisitions - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/monetize/get-app-acquisitions?source=docs)
* Content Source: [uwp/monetize/get-app-acquisitions.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/monetize/get-app-acquisitions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thank you. I've reached out to see if there was a change around that time. I'll update this document (the one mentioned in your Jan 1 edit) once I hear back.

**Comment by hickeys** [comment]
I've pinged the team and added a few more store people. I'll update this once they reply.

**Comment by hickeys** [comment]
Update: It seems these parameters have been renamed, at least for the `/v1.0/my/analytics/acquisitions` API. The new names are `age` and `xboxTitleId`.

The doc for `/v1.0/my/analytics/acquisitions` has been updated, but the docs for other similar APIs have not been updated. (e.g.  [the doc for](https://learn.microsoft.com/windows/uwp/monetize/get-app-acquisitions) `/v1.0/my/analytics/appacquisitions` still uses ageGroup according to the docs).

I'm continuing to investigate with the store team to find out if any other APIs were changed. In the meantime, it seems like you should be able to update your failing calls to use the new parameter names. Please reply back if you continue to get 500 errors.

@lenaguerrero

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
