### ISSUE TITLE
WNS raw notifications are not received if the payload is empty

### ISSUE THREAD

**Issue by jakraft** [MicrosoftDocs/windows-uwp#4173]
The WNS docs indicate that you can send a raw notification with any payload as long as the payload is less than 5KB in size:

![image](https://user-images.githubusercontent.com/52800741/205388873-2c0c7c13-c561-4ff3-9d70-d7ad6dc0dde8.png)

In practice, I've found that WNS will accept a notification request with an empty payload, however, the registered device never receives the notification. The notification is successfully received if the payload is not empty. Is this expected behavior? If so, can the docs please be updated to reflect the non-empty payload requirement?

Link to relevant docs: https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/raw-notification-overview#creating-a-raw-notification

**Comment by drewbatgit** [comment]
Thank you for catching this! I confirmed with the feature team that the payload can't be an empty string and we've updated this line in the docs to make that clear.
