### ISSUE TITLE
Keymap logger bugs or conflict with Remap key and Remap shortcut

### ISSUE THREAD

**Issue by liamneesangamer** [MicrosoftDocs/windows-uwp#4176]
I set Remap Key =>

F8  =>  F10

and then, I set Remap Shortcut

Ctrl + F8 => Ctrl + F4,

In this case Ctrl + F8 is working, but remap key F8 is not working.

I tried this same case with different keys, result are same, not working

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message.
1. This repository is for the MS documentation. PowerToys has a different repository where this issue should have been posted.
2. You remap F8 to F10, that means if you press <kbd>F8</kbd> on the keyboard, it gets translated to F10. According to your info, it does exactly what it's supposed to do. Ergo: no issue. Maybe the intention is swapped?

**Comment by mattwojo** [comment]
Echoing what Jay posted above - this sounds more like an issue to post in the product repo than an update needed in the documentation. 
Please repost at: https://github.com/microsoft/PowerToys/issues

Closing here. Thank you!
