### ISSUE TITLE
Do not get the second dialog box after error  "Cannot start debugging because no launch configuration has been provided"

### ISSUE THREAD

**Issue by tcwillis2** [MicrosoftDocs/windows-uwp#4177]
In Hello World tutorial, step 5 I get the expected message "Cannot start debugging because no launch configuration has been provided".  But after clicking OK, I do not see the second dialog box mentioned in the Note.

5.   Now let's try running the app under the debugger. Put a breakpoint on line 2, and click Run > Start Debugging (or press F5). There are also Debug and Run commands embedded inside the text editor.

 Note
When you run an app under the CodeLLDB extension and debugger for the first time, you'll see a dialog box saying "Cannot start debugging because no launch configuration has been provided". Click OK to see a second dialog box saying "Cargo.toml has been detected in this workspace. Would you like to generate launch configurations for its targets?". Click Yes. Then close the launch.json file and begin debugging again.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://learn.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tcwillis2, and thanks for filing this issue.

I'm sorry that the tutorial isn't going as expected. I just ran through all the steps in that topic, and I *am* getting the second dialog. I had to actually delete `cargo.toml` from the project before I could repro the case where that second dialog doesn't appear. You definitely have a `cargo.toml` in your project, right?

Thanks!
-Steve

**Comment by tcwillis2** [comment]
Steve,

Thanks for responding so quickly.  I am learning RUST and setting up VS Code,  but I have programmed off/on since 1976.    I attached my folder with example code I got from O’Reilly  “Programing Rust” 2nd Edition”.

by Jim Blandy, Jason Orendorff, and Leonora F.S. Tindall
Copyright © 2021 Jim Blandy, Leonora F.S. Tindall, Jason
Orendorff. All rights reserved.
Printed in the United States of America.
Published by O’Reilly Media, Inc., 1005 Gravenstein
Highway North, Sebastopol, CA 95472.

***@***.***

***@***.***
Thanks,
Tom Willis

**Comment by stevewhims** [comment]
Thanks, @tcwillis2. It does look like this documentation is correct. I tried this series of topics again on a different machine, and everything worked as expected (including the error messages we were talking about here).

I'll go ahead and close the issue, since the docs look good.

Thanks!
-Steve
