### ISSUE TITLE
file locksmith not working

### ISSUE THREAD

**Issue by Pistachio145** [MicrosoftDocs/windows-uwp#4179]
[Enter feedback here]
when i try to use the file locksmith it just doesnt show up
its turned on, idk
also i got it on the microsoft store

![image](https://user-images.githubusercontent.com/113586382/205818906-a2902421-ff3b-47b0-9bab-60ea97241845.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Version Independent ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Content: [PowerToys File Locksmith utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith)
* Content Source: [hub/powertoys/file-locksmith.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-locksmith.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Pistachio145** [comment]
btw idk what the mattwojo is it told me not to edit it so i didnt

**Comment by mattwojo** [comment]
Make sure that PowerToys is open/running and that "Enable File Locksmith" is enabled.
Then open Windows File Explorer, select a file, right-click that file and you will likely need to select "Show more options" (shift + 
F10) in order to get the expanded menu list that includes  "What's using this file?", which will open File Locksmith.

**Comment by mattwojo** [comment]
![file-locksmith-gif](https://user-images.githubusercontent.com/7566797/206063204-80341ddd-5730-49c0-adea-f95bd4ae2e3a.gif)

**Comment by mattwojo** [comment]
I updated the documentation to include the "Show more options" step and hopefully reduce confusion for others running into this same issue. > https://github.com/MicrosoftDocs/windows-dev-docs/commit/0bf70e109f70f2d76d6b81df914f6d01c889086d

Thank you for contributing this @Pistachio145. Happy File Locksmith-ing. Closing.
