### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by HectorSVC** [MicrosoftDocs/windows-uwp#418]
MNISTModel model = MISTModel.CreateMNISTModel(modelFile); should be MNISTModel model = MNISTModel.CreateMNISTModel(modelFile); Missed 'N' in MISTModel.CreateMNISTModel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2a2373-e2eb-6293-0692-35496c764316
* Version Independent ID: 31bf9697-e7e8-35cd-20c3-f0499ed84919
* Content: [Integrate a model into your app with Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/integrate-model)
* Content Source: [windows-apps-src/machine-learning/integrate-model.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/integrate-model.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for the catch! Will fix.
