### ISSUE TITLE
Foreldrar Jóns 

### ISSUE THREAD

**Issue by SMG82** [MicrosoftDocs/windows-uwp#4187]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61e341b7-e840-246c-f045-94a40347aa87
* Version Independent ID: 61e341b7-e840-246c-f045-94a40347aa87
* Content: [Analyze app performance - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/analytics)
* Content Source: [hub/apps/publish/analytics.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/analytics.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No issue reported.
