### ISSUE TITLE
Adding Content-Type header to raw notification causes "unknown error"

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/windows-uwp#419]
FWIW, I am trying to use a template to generate a raw notification for WNS platforms.  If I follow the directions above;

`The HTTP Content-Type header must be set to "application/octet-stream".`

It errors out on the notification hub side.  No real error message.  Found that one by trial and error.  Leave it out and the template generates a raw payload just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e59851-bded-5e3e-2fcb-8614fb7611a2
* Version Independent ID: 3811caa8-dbc0-55b6-8d01-f08fb86b38e0
* Content: [Raw notification overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/raw-notification-overview)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/raw-notification-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/raw-notification-overview.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@andrewleader Do you have any suggestions?

**Comment by andrewleader** [comment]
Not sure, I'll ask the WNS and Notification Hub teams and report back with the findings!

**Comment by antlhuede** [comment]
has anyone figured this out?

**Comment by FerOsorio** [comment]
this should do the trick.

var x = new HttpRequestMessage(HttpMethod.Post, channelUri.Uri)
            {
                Content = new StringContent(
                    content: "yourstuff", 
                    encoding: System.Text.Encoding.UTF8, 
                    mediaType: "application/octet-stream");
            };

x.Content.Headers.ContentType.CharSet = "";
