### ISSUE TITLE
404 page not found on URL going to the MS Store Content Policy page.

### ISSUE THREAD

**Issue by ShinraCorpMixer** [MicrosoftDocs/windows-uwp#4190]
The URL link that goes to the content policies page for the 18+ Age Rating, is giving a 404 error. It's currently leading to this URL: https://learn.microsoft.com/en-us/uwp/publish/store-policies.md

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bac33878-35ad-1414-173d-55b3de32f8ba
* Version Independent ID: bac33878-35ad-1414-173d-55b3de32f8ba
* Content: [Age ratings for MSI and EXE apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/age-ratings?pivots=store-installer-msi-exe)
* Content Source: [hub/apps/publish/publish-your-app/age-ratings.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/age-ratings.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
That link has been replaced. Thanks for reporting it.
