### ISSUE TITLE
Missing information about the pain points to migrate from C++/CX to C++/WinRT

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#4191]
In the section "How hard is it to migrate UWP apps to Windows App SDK / WinUI 3?", the cost of complete rewrite requested to C++ developers to migrate from C++/CX into C++/WinRT, with a complete different programming approach and lack of VS tooling support, has been completly ignored.

It should be clarified that this requires a complete rewrite for C++ developers that bought into developing UWP applications with C++/CX.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c39c683-77bb-e879-905c-47d12078f45b
* Version Independent ID: 3c39c683-77bb-e879-905c-47d12078f45b
* Content: [Windows developer FAQ](https://learn.microsoft.com/en-gb/windows/apps/get-started/windows-developer-faq)
* Content Source: [hub/apps/get-started/windows-developer-faq.yml](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/windows-developer-faq.yml)
* Product: **uwp**
* GitHub Login: @MatchaMatch
* Microsoft Alias: **mikben**

**Comment by stevewhims** [comment]
Thanks, @pjmlp! Yes, that content was assuming that the source code is either C# or C++/WInRT.

You're right that for migrating a C++/CX UWP app, that's going to involve porting code. So I've just completed a pull-request to update that topic with that additional info (and link to our guidance around porting from C++/CX to C++/WinRT).

Right now our publishing pipeline isn't publishing as often as it usually does (we're working to remedy that). But in any case I expect this change to show up on the live site within a day or two. We'll keep monitoring the publishing status anyway.

-Steve
