### ISSUE TITLE
Download PDF does not download complete document

### ISSUE THREAD

**Issue by sailesh-ramayanam** [MicrosoftDocs/windows-uwp#420]
Download PDF link at the bottom is downloading only partial content. All the pages after 674 are blank. Also, it will be great if we have a printable version of the page we are viewing, instead of having to download the entire document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9fdf72e-8eaa-1e01-9b9c-d1c5e506117d
* Version Independent ID: 45f0e7ae-662c-29fb-8171-9674f7bbde15
* Content: [Data binding overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart#feedback)
* Content Source: [windows-apps-src/data-binding/data-binding-quickstart.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/data-binding-quickstart.md)
* Service: **unspecified**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by dend** [comment]
Thanks for the report! We are investigating this internally to make sure it's addressed ASAP. cc: @dastaffo

**Comment by stevewhims** [comment]
Hi, @sailesh-ramayanam, thanks for filing this issue. It looks like the blank pages problem has been resolved. I also acknowledge your feature request, that has been noted. I'll close this issue now.

Thanks!
~Steve
