### ISSUE TITLE
hey when i tried to uninstall my vm using winget but couldnt it says couldnt find package and i tried to get the id of it but it said "couldnt find package heres a ss"

### ISSUE THREAD

**Issue by Forgeuser** [MicrosoftDocs/windows-uwp#4200]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e38a4717-5dc9-ceaa-f023-ba7bf7657b71
* Version Independent ID: d81c530e-f9ad-612f-1c56-0114d9097124
* Content: [uninstall Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/uninstall)
* Content Source: [hub/package-manager/winget/uninstall.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/uninstall.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by Forgeuser** [comment]
i cant upload my image but i think someone understands]

**Comment by mattwojo** [comment]
Hey @Forgeuser -- Could you clarify your question a bit more? Installing / uninstalling a VM with package manager isn't really possible. Do you mean that you're trying to install/uninstall winget (windows package manager) on a VM instance?

**Comment by RYDELLRYDE** [comment]
#4203

**Comment by mattwojo** [comment]
Closing this issue as there are no clear documentation updates associated. Please feel welcome to re-open with more clarification on the ask. Thanks for filing!
