### ISSUE TITLE
Hotkey for "Moving focus between zones"

### ISSUE THREAD

**Issue by h2oicsaba** [MicrosoftDocs/windows-uwp#4201]
The ⊞ Win+left, ⊞ Win+right, ⊞ Win+up, and ⊞ Win+down hotkeys for moving windows are very useful, but also, I want to move my focus "between zones" using only the keyboard.  (This can be done only using the mouse and clicking a window int that zone)
This new hotkey is supposed to work in the same manner using the arrows.  let's say ALT+arrows  
The purpose of moving the focus is to use another "hotkey" especially the "Switch between windows in the current zone".
This new hotkey is needed because maybe I have overlapped windows in front of the next area so pointing with the mouse is difficult, and slow.  And also, I want to make the whole process, (switching to a new zone and selecting a window in it), using only the keyboard.        
**The new hotkey feature: **
Moves focus between zones (showing the zone highlighted margins) and when is released it brings up the top window of the current zone. Also points the mouse on the middle of the zone.

Thanks. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Sounds like a good idea @h2oicsaba, but this repo is just for keeping documentation up to date. For feature requests like this, please check the issues in the PowerToys product repo to see if anyone has already filed a similar request: https://github.com/microsoft/PowerToys/issues
If you don't see a similar request to thumbs up and express support for, select "New issue" and add your request. 
Closing the issue here in the docs repo. 
Cheers!

**Comment by h2oicsaba** [comment]
Ah, sorry I missed the zone. You can delete it . And the next one too . 
bye Cs.
