### ISSUE TITLE
Add Desktop Extesions for UWP Project doesn't specify version

### ISSUE THREAD

**Issue by hawkerm** [MicrosoftDocs/windows-uwp#4206]
The "Add Desktop Extensions to the UWP Project" section doesn't specify what version of the extension to add:

https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extend#add-desktop-extensions-to-the-uwp-project

There's at least two different versions:

![image](https://user-images.githubusercontent.com/8959496/208374057-099f3bca-a441-4861-9219-c648e9a78ec5.png)

Does it matter which is to be used? Does it have to match the min/target of the application itself? If I install the 19041 in my app that has a min target of 16299 would that work or do I need the 16299 one (if there is one)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48168c03-36df-a7cb-baeb-49bd31589260
* Version Independent ID: 7a17333c-9eee-d327-73aa-49fdbc2f4de2
* Content: [Extend your app with Windows UI and components - Windows apps](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extend)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-extend.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-extend.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @hawkerm. For info about how to choose a version, see [Extension SDKs, and how to reference them](https://learn.microsoft.com/uwp/extension-sdks/device-families-overview#extension-sdks-and-how-to-reference-them).

I'll update the topic with a link to that info.

Thanks!
-Steve
