### ISSUE TITLE
Typo in C++/WinRT naming.

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#4207]
> Developers who love C++, can use WinRT/C++ to create apps in familiar ways.

It is called C++/WinRT.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 140bbb12-00af-4ffd-3513-f5c06ca28a1e
* Version Independent ID: d440e328-19e8-0206-0267-9be47d59e280
* Content: [What's New for Developers in Windows 11 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/whats-new/windows-11-build-22000)
* Content Source: [hub/apps/whats-new/windows-11-build-22000.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/whats-new/windows-11-build-22000.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
So it is. Thanks for filing this issue, fix coming shortly.
