### ISSUE TITLE
Multi instance: about time!

### ISSUE THREAD

**Issue by stamminator** [MicrosoftDocs/windows-uwp#421]
The lack of multi-instance apps in UWP has been the single biggest factor preventing me from taking it seriously as a mature, production-ready platform. The amount of frustration I've experienced from not being able to have two side-by-side windows of, say, the Windows 10 Settings app, has been considerable. This feature is a huge win.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9554b9f2-2f49-1833-1143-0103c18c37c8
* Version Independent ID: ef28f9ce-bd72-0435-6238-95d574eabee1
* Content: [Create a multi-instance Universal Windows App - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Glad you like it.
