### ISSUE TITLE
No "keep screen on" option

### ISSUE THREAD

**Issue by bwirt** [MicrosoftDocs/windows-uwp#4210]
[Enter feedback here]
Docs say there is a "keep screen on" option.  This doesn't exist in the latest version (v0.65.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a20e555a-65ad-82e7-e1c0-f6577c1322b2
* Version Independent ID: 29236a0e-82e8-92d7-a5fb-12a9a777bcc2
* Content: [PowerToys Awake utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/awake)
* Content Source: [hub/powertoys/awake.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/awake.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by bwirt** [comment]
To clarify, I am using the GUI, not the CLI.

**Comment by Jay-o-Way** [comment]
Got a screenshot of the settings? :)

**Comment by bwirt** [comment]
> Got a screenshot of the settings? :)

![image](https://user-images.githubusercontent.com/12990036/213518536-c038abe0-3d93-4842-a17c-fc6b0005e3fa.png)

Compare to docs linked above, "Keep Screen on" section.

**Comment by Jay-o-Way** [comment]
That's because the current selection ("Keep using power plan") is actually a passive state, therefore the setting for the screen is hidden. I agree it's confusing. Select a different mode and see what happens :)

**Comment by bwirt** [comment]
> That's because the current selection ("Keep using power plan") is actually a passive state, therefore the setting for the screen is hidden. I agree it's confusing. Select a different mode and see what happens :)

It's working fine, the documentation just confused me at first.

**Comment by Jay-o-Way** [comment]
It says
> This feature only works if Awake is running in one of the two Keep awake state.

now, does that suffice?

**Comment by bwirt** [comment]
> It says
> 
> > This feature only works if Awake is running in one of the two Keep awake state.
> 
> now, does that suffice?

Sure, but I was thinking the screenshot should be updated and the section "Keep Screen On" removed.
