### ISSUE TITLE
Update instructions for installing Winget in Sandbox to install latest version

### ISSUE THREAD

**Issue by elisimpson** [MicrosoftDocs/windows-uwp#4211]
https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox

The instructions here install a very old version of Winget which doesn't support all the recent features. Please update the instructions to install the latest version and necessary dependencies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by glawrence** [comment]
I have raised https://github.com/MicrosoftDocs/windows-dev-docs/issues/4315 which I realise duplicates this one, but I also created PR https://github.com/MicrosoftDocs/windows-dev-docs/pull/4264 which fixes this

**Comment by mattwojo** [comment]
Thank you @elisimpson .  This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec
