### ISSUE TITLE
winget command-line tool is not bundled in modern versions of Windows 10 contrary to what documentation says

### ISSUE THREAD

**Issue by vvavrychuk** [MicrosoftDocs/windows-uwp#4212]
https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md#install-winget says

> Windows Package Manager winget command-line tool is bundled with Windows 11 and modern versions of Windows 10 by default as the App Installer.

I have updated to latest version of Windows 10: version 22H2 (OS Build 19045.2364).

But, typing `winget` in PowerShell says the term is not recognized.

**Comment by zivkan** [comment]
In my experience it's also not bundled with Windows 11.
