### ISSUE TITLE
Keep screen & programs awake

### ISSUE THREAD

**Issue by riaand55** [MicrosoftDocs/windows-uwp#4216]
MouseJiggle cycles through your screens when away and keeps your Screens, Microsoft Teams, Skype, Games & Outlook active & green. You can get it from https://www.mousejiggle.org. It will prevent screen locking until you switch it off or close your notebook/desktop or shut down.

It measures 60 seconds of inactivity on your PC & then kicks in programmatically moving the screens whether they are on 1 or more displays. (It moves the screens like Microsoft Teams & Outlook back to their original positions as well) This is done with a random timer every 60 to 90 seconds. It happens so fast you cannot see it. When you get back to your computer & use the keyboard it stops & just emits a low level screen awake as to not interfere with your work when you are working from home. At work you can switch it off or responsibly lock your screen

The great thing is it supports all your connected screens, which makes it the best mouse jiggler & a cut above the rest.

It is a great productivity utility as it sits in the taskbar out of your way
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a20e555a-65ad-82e7-e1c0-f6577c1322b2
* Version Independent ID: 29236a0e-82e8-92d7-a5fb-12a9a777bcc2
* Content: [PowerToys Awake utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/awake)
* Content Source: [hub/powertoys/awake.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/awake.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Paul-Dempsey** [comment]
Unless i'm missing something, this appears to be an advertisement, and not a docs issue.

**Comment by Jay-o-Way** [comment]
@mattwojo

**Comment by alvinashcraft** [comment]
It looks like there's no actionable feedback here, so I'll go ahead and close the issue. Please open a new issue if you have feedback about the documentation that you'd like us to address.
