### ISSUE TITLE
Insider Preview SDK. -  Link not working 

### ISSUE THREAD

**Issue by ganesh-darandale** [MicrosoftDocs/windows-uwp#4217]
Link not working 
![image](https://user-images.githubusercontent.com/72141466/210774736-222df13f-615b-422c-b7d0-9739153b0a50.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cd4ed11-b246-94af-c310-514326282eaf
* Version Independent ID: 5a1dbf05-790d-525b-bcc6-01857c1687de
* Content: [Apply rounded corners in desktop apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners)
* Content Source: [hub/apps/desktop/modernize/apply-rounded-corners.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/apply-rounded-corners.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this issue. I've updated the doc to remove the broken link since the API is no longer pre-release.
