### ISSUE TITLE
Organizational licensing options link is dead

### ISSUE THREAD

**Issue by kdotdk** [MicrosoftDocs/windows-uwp#4220]
The "[Organizational licensing options](https://learn.microsoft.com/en-us/uwp/publish/organizational-licensing)." on the page is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2d5e61b-9914-b516-c450-2d97550bd880
* Version Independent ID: e2d5e61b-9914-b516-c450-2d97550bd880
* Content: [Set app pricing and availability - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/price-and-availability?pivots=store-installer-msix)
* Content Source: [hub/apps/publish/publish-your-app/price-and-availability.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/price-and-availability.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It seems to be working now. There was a period of transition while many store docs were being moved within the docs repo. The moves were done over several phases, and some phases temporarily introduced broken links. I suspect this link was one of those.

Thanks for reporting it all the same though!
