### ISSUE TITLE
Allowing disconnected (offline) licensing after Store for Business is retired

### ISSUE THREAD

**Issue by kdotdk** [MicrosoftDocs/windows-uwp#4221]
The section "Allowing disconnected (offline) licensing" describes how to do this in "Microsoft Store for Business".
But "Microsoft Store for Business" is retired.
- How is the same be achieved in "Microsoft Store"?
- Are there any limitation to which countries an paid app can be offered to?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bdd43f2-1c92-2601-3dba-2a381fb0e496
* Version Independent ID: 8bdd43f2-1c92-2601-3dba-2a381fb0e496
* Content: [Organizational licensing options - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/organizational-licensing)
* Content Source: [hub/apps/publish/organizational-licensing.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/organizational-licensing.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The option should be available to apps in the regular Microsoft Store.

Regarding country-based limitations on paid apps, please see [this page](https://learn.microsoft.com/windows/apps/publish/publish-your-app/market-selection)
