### ISSUE TITLE
Windows Dev Center content pack for Power BI

### ISSUE THREAD

**Issue by bacabrother** [MicrosoftDocs/windows-uwp#4223]
[Enter feedback here]

The Windows Dev Center content pack for Power BI section is deprecated, can't connect to power bi that way anymore, links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61e341b7-e840-246c-f045-94a40347aa87
* Version Independent ID: 61e341b7-e840-246c-f045-94a40347aa87
* Content: [Analyze app performance - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/analytics)
* Content Source: [hub/apps/publish/analytics.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/analytics.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thank you. I've contacted the store team for guidance. I'll update the page once I hear back.

**Comment by GrantMeStrength** [comment]
Links have been corrected.
