### ISSUE TITLE
InfoBadge is not available in WinUI 3 yet but the doc says otherwise

### ISSUE THREAD

**Issue by AndrewKeepCoding** [MicrosoftDocs/windows-uwp#4224]
As you can see in this  issue (microsoft/microsoft-ui-xaml#7001), ``InfoBadge`` is not available in WinUI 3 yet. But the [doc](https://learn.microsoft.com/en-us/windows/apps/design/controls/info-badge#:~:text=The%20information%20and%20examples%20in%20this%20article%20are%20optimized%20for%20apps%20that%20use%20the%20Windows%20App%20SDK%20and%20WinUI%203%2C%20but%20are%20generally%20applicable%20to%20UWP%20apps%20that%20use%20WinUI%202.%20See%20the%20UWP%20API%20reference%20for%20platform%20specific%20information%20and%20examples.) is written as it's already available making users confused.

**Comment by jwmsft** [comment]
[InfoBadge for WinUI3](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.infobadge?view=windows-app-sdk-1.2) was released in the [Windows App SDK 1.2](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#winui-3). If you're not seeing it in your project, make sure you've updated to the latest release.

**Comment by AndrewKeepCoding** [comment]
I don't know how I missed this. Sorry for the trouble.
