### ISSUE TITLE
Can I do this with a WinForms app?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/windows-uwp#4228]
I have a WinForms app that I'd like to package using single-project MSIX. Is that possible? The docs say Win UI 3 apps, but I'm not sure what that really means. Is there a NuGet package or property I set to make it a WinUI app?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0401c948-1dda-c819-ee88-902ac6fcbbd9
* Version Independent ID: c1748244-0f46-8dec-a88e-020f12d9a387
* Content: [Package your app using single-project MSIX - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?source=recommendations&tabs=csharp)
* Content Source: [hub/apps/windows-app-sdk/single-project-msix.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/single-project-msix.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @MisinformedDNA, and thanks for filing this issue. Single-project MSIX is all about a specific project template in Visual Studio, and that project template is expressly for WinUI 3 apps (not for any other kind of desktop app). As for what a WinUI 3 app is, see the info below. For desktop apps that aren't WinUI3 apps, also see the info below for guidance around the kind of packaging project to add to your solution.

I've updated the topic with the following paragraph, which includes links to more info.

"Single-project MSIX is a feature that lets you build a packaged WinUI 3 desktop app without the need for a separate packaging project. A WinUI 3 app is one that uses the [Windows UI Library (WinUI) 3](https://learn.microsoft.com/windows/apps/winui/winui3/) framework for its user interface (UI); and it uses the Windows App SDK. To package a desktop app that's *not* a WinUI 3 app, see [Set up your desktop application for MSIX packaging in Visual Studio](https://learn.microsoft.com/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)."

Thanks!
-Steve
