### ISSUE TITLE
Not full instruction!

### ISSUE THREAD

**Issue by kosbar** [MicrosoftDocs/windows-uwp#4233]
The instructions do not mention that the Microsoft.Windows.CsWinRT package needs to be added to the C# library, the example is absolutely not working without it!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e032742-49f2-63e0-8d8f-d7b69836fbc0
* Version Independent ID: 9e032742-49f2-63e0-8d8f-d7b69836fbc0
* Content: [Walkthrough—Create a C#/WinRT component, and consume it from C++/WinRT - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/create-windows-runtime-component-cswinrt#consume-the-component-from-a-cwinrt-app)
* Content Source: [hub/apps/develop/platform/csharp-winrt/create-windows-runtime-component-cswinrt.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/platform/csharp-winrt/create-windows-runtime-component-cswinrt.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kosbar! Step 2 in the section "Create a simple Windows Runtime Component using C#/WinRT" talks about installing the Microsoft.Windows.CsWinRT NuGet package in the Windows Runtime Component project.

I'll close the issue, but please reopen, or comment, if necessary.

Thanks!
-Steve
