### ISSUE TITLE
What is Verification Protecting

### ISSUE THREAD

**Issue by Nei1-H** [MicrosoftDocs/windows-uwp#4239]
[Enter feedback here]
Your verification made me lose why I wanted to comment. Since there is no money involved why not skip the verification?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Version Independent ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Content: [PowerToys Text Extractor utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor#supported-languages)
* Content Source: [hub/powertoys/text-extractor.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Hi, @Nei1-H
I'm sorry, but I have no idea what you mean by verification. Can you explain?
Also, this repo is about the documentation on MS Learn.

**Comment by Nei1-H** [comment]
By verification I meant a message from MS pops up and says they are going to e-mai me a numeric code at one of my old, very old e-mail accounts. They never actually e-mail anything. I discovered that if I scroll down a bit my outlook password is sufficient. The whole process is idiotic not counting e-mailing to an obsolete account and not e-mailing anything.
