### ISSUE TITLE
Small correction needed in the command.

### ISSUE THREAD

**Issue by prmadhes-msft** [MicrosoftDocs/windows-uwp#4241]
There is a small correction needed in the command below:
 
In the command, seems like dot “.” is missing between Microsoft  &  DesktopAppInstaller_8wekyb3d8bbwe , as the last line is throwing error “path not found”
 
$ProgressPreference='Silent'
Invoke-WebRequest -Uri [https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fwinget-cli%2Freleases%2Fdownload%2Fv1.3.2691%2FMicrosoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle&data=05%7C01%7CPradeep.Madheshiya%40microsoft.com%7C650ea4bcc553465c19f508dafb0e8e24%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638098337247141312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XvPr3Bc23Ql3SvOb6CTgLSiI%2BgJ9%2BZaBBzRsGZSO%2FcU%3D&reserved=0) -OutFile .\MicrosoftDesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri [https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FMicrosoft.VCLibs.x64.14.00.Desktop.appx&data=05%7C01%7CPradeep.Madheshiya%40microsoft.com%7C650ea4bcc553465c19f508dafb0e8e24%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638098337247141312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UVcksc4bl4Ll%2BiOU3ZN6BIoKHYWjG77g0ff06wj08dA%3D&reserved=0) -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage **Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Thank you @prmadhes-msft .  This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec
