### ISSUE TITLE
Add link to related document that goes into more detail on localization

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#425]
https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest

Looks like an older document is linked to currently, but it's not clear that it's important to read that one instead with the content listed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50575d3e-9e00-16ef-3e35-5db6cc2fd34a
* Version Independent ID: ce579cba-2e10-b92c-604f-0e7f3c5e8f6b
* Content: [xUid directive - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-uid-directive)
* Content Source: [windows-apps-src/xaml-platform/x-uid-directive.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/x-uid-directive.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by chigy** [comment]
@ptorr-msft

**Comment by ptorr-msft** [comment]
@michael-hawker, can you please be more specific? Which particular doc is old? What needs to be clearer?

**Comment by michael-hawker** [comment]
It may have been fixed, I believe this link:

> For more info on how to use x:Uid and resource files together, see _**Localize strings in your UI and app package manifest.**_

Went somewhere else before.

I was just also commenting that there should be a 'Related Topics' to call that linke more prominently too, since the main article goes into more detail about setting up the x:Uid system in your app.

**Comment by jevansaks** [comment]
@michael-hawker I'm confused about what you would like updated? Is there a link you think should be in the Related Topics section? If so, which one?

**Comment by michael-hawker** [comment]
Sorry missed this comment before.

@jevansaks I was saying that there should be a `Related Topics` section like most other docs have that also has a copy of this link as it's an important related doc for understanding.
