### ISSUE TITLE
What does -q do?

### ISSUE THREAD

**Issue by dcarapic** [MicrosoftDocs/windows-uwp#4252]
It would be nice to actually state what -q does or what is the specification for the 'query'.
Also some options do not work with others (such as --accept-package-agreements with --all) which could also be explained here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf54ba9-53bd-e5d0-3b5a-e5b003f356d9
* Version Independent ID: ed2c403c-7bba-9647-fb5c-da556cb93a6b
* Content: [upgrade Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade)
* Content Source: [hub/package-manager/winget/upgrade.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/upgrade.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Added an explanation for the -q query flag in https://github.com/MicrosoftDocs/windows-dev-docs-pr/pull/2520/files
Closing this issue. Thanks for filing!
