### ISSUE TITLE
A variable (storeId)  is declared in function definition but a hardcoded variable (addOnStoreId) is used in the function body.

### ISSUE THREAD

**Issue by StavrosD** [MicrosoftDocs/windows-uwp#4254]
A "storeId" variable is declared in function definition but a hardcoded variable (addOnStoreId) is used in the function body. 

The hardcoded variable should be removed and the "storeId" variable should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e3c83d2-e3e6-57bb-30d9-80b5951231bb
* Version Independent ID: 38735b82-278a-8ae5-12b4-eb376f30d7cd
* Content: [Enable consumable add-on purchases - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/monetize/enable-consumable-add-on-purchases)
* Content Source: [uwp/monetize/enable-consumable-add-on-purchases.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/monetize/enable-consumable-add-on-purchases.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reporting this. I've just checked in a fix. Should be published soon.
