### ISSUE TITLE
Can't reproduce code in the Media Players article

### ISSUE THREAD

**Issue by eduardobragaxz** [MicrosoftDocs/windows-uwp#4259]
In the section "Keep the device's screen active" the C# code isn't reproducible. I can't tell if there's something missing or it's a bug within WinUI 3. Doing what the example shows gives me error "CS0123: No overload for MediaPlayerElement_CurrentStateChanged matches delegate TypedEventHandler<MediaPlaybackSession, object>".

If there's indeed code missing, it would be great if you guys could fix it. If not, I'll open an issue on the WinUI repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3340c536-9bb2-2a35-6f15-f9a80cd10d52
* Version Independent ID: 8e225d67-4171-0aae-03df-dd781adbe6c4
* Content: [Media players - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/controls/media-playback)
* Content Source: [hub/apps/design/controls/media-playback.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/controls/media-playback.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@eduardobragaxz, we'll actually be publishing the WinUI3 updates to the Media players doc later today. The code currently in the "Keep the device's screen active" section is not applicable for WinUI3 and will be updated. In the meantime, here's the correct code for a WinUI3 app. Hope this helps.

```
    public sealed partial class MainWindow : Window
    {
        public DisplayRequest appDisplayRequest = null;
        private DispatcherQueue dispatcherQueue = DispatcherQueue.GetForCurrentThread();
        // using Microsoft.UI.Dispatching;

        public MainWindow()
        {
            this.InitializeComponent();

            mediaPlayerElement.MediaPlayer.PlaybackSession.PlaybackStateChanged += PlaybackSession_PlaybackStateChanged;
        }

        private void PlaybackSession_PlaybackStateChanged(MediaPlaybackSession sender, object args)
        {
            MediaPlaybackSession playbackSession = sender as MediaPlaybackSession;
            if (playbackSession != null && playbackSession.NaturalVideoHeight != 0)
            {
                if (playbackSession.PlaybackState == MediaPlaybackState.Playing)
                {
                    if (appDisplayRequest is null)
                    {
                        dispatcherQueue.TryEnqueue(DispatcherQueuePriority.Normal, () =>
                        {
                            appDisplayRequest = new DisplayRequest();
                            appDisplayRequest.RequestActive();
                        });
                    }
                }
                else // PlaybackState is Buffering, None, Opening, or Paused.
                {
                    if (appDisplayRequest is not null)
                    {
                        appDisplayRequest.RequestRelease();
                        appDisplayRequest = null;
                    }
                }
            }
        }
    }
```

**Comment by eduardobragaxz** [comment]
Thanks, @jwmsft.
