### ISSUE TITLE
Challenge links are broken.

### ISSUE THREAD

**Issue by ganeshmahajan1985** [MicrosoftDocs/windows-uwp#426]
Challenge links are broken, need to fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c640c640-4004-c313-c066-3d47c634778e
* Version Independent ID: b5c02659-7241-996a-8408-9fba83a755f1
* Content: [Support ink in your UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/ink-walkthrough)
* Content Source: [windows-apps-src/design/input/ink-walkthrough.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/ink-walkthrough.md)
* Service: **unspecified**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for letting us know about these. The links have been fixed and should be live soon.
