### ISSUE TITLE
Missing information about product type and product Id and 

### ISSUE THREAD

**Issue by hallahanbill** [MicrosoftDocs/windows-uwp#4261]
[Enter feedback here]
The page at the following link has a link for "productId" a bit less than halfway down the page.

Manage add-ons
https://learn.microsoft.com/en-us/windows/uwp/monetize/manage-add-ons

The "productId" entry in the table has the text:

"The product ID of the add-on. This is the ID that was provided by the developer when the add-on was created. For more information, see Set your product type and product ID."

"Set your product type and product ID" is the text for the link

That link leads to the page:

Create app store listings
https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/create-app-store-listing?pivots=store-installer-add-on

There is noting there about setting the product type or the product Id.

I do know how to set the product type, that's well documented in several places.

----------------------------------------

Specifically, I wish to look at a sample product Id, to see if I can have spaces in the Id, or if it has some restrictions in form.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07dc5582-999a-a880-1a02-986dc11e2152
* Version Independent ID: 07dc5582-999a-a880-1a02-986dc11e2152
* Content: [Create app store listings - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/create-app-store-listing?pivots=store-installer-add-on)
* Content Source: [hub/apps/publish/publish-your-app/create-app-store-listing.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/create-app-store-listing.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Great catch; thank you! I've fixed the link. It should have pointed [here](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/create-app-submission?pivots=store-installer-add-on#product-id)
