### ISSUE TITLE
AppxPackage file name does not match in example. 

### ISSUE THREAD

**Issue by Braingears** [MicrosoftDocs/windows-uwp#4265]
In the example:
```
$ProgressPreference='Silent'
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\MicrosoftDesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
```

The file name `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle` does not match. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by glawrence** [comment]
I have raised https://github.com/MicrosoftDocs/windows-dev-docs/issues/4315 which I realise duplicates this one, but I also created PR https://github.com/MicrosoftDocs/windows-dev-docs/pull/4264 which fixes this

**Comment by mattwojo** [comment]
Thank you @Braingears.  This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec
