### ISSUE TITLE
Request: for "Quick accent" tool, also offer the special characters in Hebrew of Niqqud (similar to vowels in English)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MicrosoftDocs/windows-uwp#4267]
As the title says.
Niqqud is like vowels in English, but they are optional and they are added in/around the letter, usually as dots (Niqqud=putting a dot).

https://en.wikipedia.org/wiki/Niqqud

Please offer them there too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
@AndroidDeveloperLB Hello and thanks for your message. This repo is about the documentation on MS Learn. This request would be better placed in the PowerToys repository. See (for example) issue https://github.com/microsoft/PowerToys/issues/20317
@damienleroy Is this within the scope of Quick Accent?

**Comment by AndroidDeveloperLB** [comment]
@Jay-o-Way You are correct. I have no idea how I got here. Here:
https://github.com/microsoft/PowerToys/issues/24409
