### ISSUE TITLE
"Interface not registered" exception when following the doc to pin a WPF app in the task bar

### ISSUE THREAD

**Issue by aries-zhang** [MicrosoftDocs/windows-uwp#4271]
By following this doc https://learn.microsoft.com/en-us/windows/apps/design/shell/pin-to-taskbar and try to set up "Pin To Task Bar" feature in a WPF app, I've got an error shown in the following screenshot.
Is this API available in WPF Apps?

```
System.Exception: 'Interface not registered (Exception from HRESULT: 0x80040155)' 
```

![image](https://user-images.githubusercontent.com/11416717/215679526-012808dd-279c-4286-989f-5d3cf0301b7f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb8b8e9-b4f9-f29a-716c-444862748494
* Version Independent ID: e8020aed-5714-e4e8-4f2f-55844a8ee5a4
* Content: [Pin your app to the taskbar - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/shell/pin-to-taskbar)
* Content Source: [hub/apps/design/shell/pin-to-taskbar.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/shell/pin-to-taskbar.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Correct. TaskbarManager is a UWP class. Additionally, the article states that you must be targeting a specific version of Windows, namely, build 16299 or greater. WPF does not target specific Windows versions in this way.
