### ISSUE TITLE
Update docs to showcase that WinUI3 is not open source

### ISSUE THREAD

**Issue by Daltz333** [MicrosoftDocs/windows-uwp#4273]
WinUI3 is not open source and the reference should be updated.

![image](https://user-images.githubusercontent.com/10674555/215864224-7db29687-9fe2-4664-afdb-1b014137938c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea32f1f-67e6-12f4-7aa0-602184a377fd
* Version Independent ID: 3adf7079-1ead-0e1a-0af9-7de72d30117f
* Content: [Windows UI Library (WinUI) - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/)
* Content Source: [hub/apps/winui/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the suggestion, @Daltz333. Doc has been updated.
