### ISSUE TITLE
Using Awake from command line confusion.

### ISSUE THREAD

**Issue by 4k3or3et** [MicrosoftDocs/windows-uwp#4288]
Hi All,

I have been trying for an hour now how to use Awake from command line to keep my screen on. Whataever I am trying to follow from the documentation here on GitHub, nothing works. Can anyone please give an simple example how to keep screen on indefinately using C:\Program Files\PowerToys\modules\Awake\PowerToys.Awake.exe ?

**Comment by mattwojo** [comment]
Hey @4k3or3et - Sorry you had trouble with PowerToys Awake. You should be able to enable it by opening PowerToys and following the instructions here: https://learn.microsoft.com/en-us/windows/powertoys/awake#settings
It doesn't appear that this issue requires an update to the documentation, so closing, but please feel welcome to re-open if this is not the case.
