### ISSUE TITLE
Does MSI/EXE support Private audience?

### ISSUE THREAD

**Issue by guliteb** [MicrosoftDocs/windows-uwp#4289]
Under 'MSIX', I can find 'Private audience'. But under 'MSI/EXE', I cannot find. Does MSI/EXE support Private audience?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b19bd2a3-5d4b-7d24-80e2-8e56f916cba2
* Version Independent ID: b19bd2a3-5d4b-7d24-80e2-8e56f916cba2
* Content: [Choose visibility options - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/visibility-options?pivots=store-installer-msix#audience)
* Content Source: [hub/apps/publish/publish-your-app/visibility-options.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/visibility-options.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It does not. Each version of each page is specific to the installer/package type and what features are supported by that type.
