### ISSUE TITLE
Question about Windows ML 

### ISSUE THREAD

**Issue by fujunwei** [MicrosoftDocs/windows-uwp#429]
The [documentation](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/) only guide how to use Windows Machine Learning with model, are there higher level APIs such as [Mac Vision](https://developer.apple.com/documentation/vision?language=objc) that recognize face  without loading extra model.

Thanks.

**Comment by serenaz** [comment]
Currently, Windows ML does not have higher level vision APIs, but you might be interested in FaceDetector:
https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/detect-and-track-faces-in-an-image
