### ISSUE TITLE
[Settings Sync] is a deprecated link/extension. 

### ISSUE THREAD

**Issue by taleleuma** [MicrosoftDocs/windows-uwp#4291]
Following link has been mentioned on this page:
[Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)

It's a deprecated link/extension. Pl modify the document with new link or new extension?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
This extension link was removed. Thanks for filing this issue.
