### ISSUE TITLE
Instructions don't work for Winget in Windows Sandbox

### ISSUE THREAD

**Issue by hostmatic** [MicrosoftDocs/windows-uwp#4294]
Get the following error:
Add-AppxPackage : Cannot find path
'C:\Users\WDAGUtilityAccount\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle' because it does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by glawrence** [comment]
I have raised #4315 which I realise duplicates this one, but I also created PR #4264 which fixes this

**Comment by mattwojo** [comment]
Thank you @hostmatic .  This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec
