### ISSUE TITLE
Incorrect docs for installing WinGet in Windows Sandbox

### ISSUE THREAD

**Issue by PDeets** [MicrosoftDocs/windows-uwp#4299]
There is a PowerShell snippet at https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox for installing WinGet in Windows Sandbox. This PowerShell snippet does not work.

The first problem is that during the download, it sets "-OutFile" to "MicrosoftDesktopAppInstaller_8wekyb3d8bbwe.msixbundle", but then later, it tries to install it as "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle". (There is a missing period in the "-OutFile" switch.)

The second issue is that it doesn't download all the required framework packages. "Microsoft.VCLibs.x64.14.00.Desktop.appx" isn't sufficient. When I try to install, I get this error:

Windows cannot install package Microsoft.DesktopAppInstaller_1.18.2691.0_arm64__8wekyb3d8bbwe because this package
depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.7" published by
"CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or ARM64 processor
architecture and minimum version 7.2109.13004.0, along with this package to install.

(I am using an ARM64 machine, so the "arm64" in the error message is expected.)

The docs need to include the download and install of "Microsoft.UI.Xaml.2.7" as well since Microsoft.DesktopAppInstaller depends on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by glawrence** [comment]
I have raised https://github.com/MicrosoftDocs/windows-dev-docs/issues/4315 which I realise duplicates this one, but I also created PR https://github.com/MicrosoftDocs/windows-dev-docs/pull/4264 which fixes this

**Comment by mattwojo** [comment]
Thank you @PDeets.  This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec
