### ISSUE TITLE
Get pricepoint information

### ISSUE THREAD

**Issue by 4026** [MicrosoftDocs/windows-uwp#430]
Is there any way for the server making this call to determine the pricepoint (and currency) at which the customer purchased a given product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b95f043-9483-170e-3aef-fa675bfc0fb7
* Version Independent ID: 819f2b1e-a55b-7b05-bf54-111eed1a9916
* Content: [Query for products - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products)
* Content Source: [windows-apps-src/monetize/query-for-products.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/query-for-products.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I have confirmed with the engineering team that there is currently no way to get the price and currency information for the customer purchase using this API.
