### ISSUE TITLE
This sample application is broken with certain inputs (e.g., blog feed as of 2-13-2023)

### ISSUE THREAD

**Issue by Davi-Gray** [MicrosoftDocs/windows-uwp#4301]
The sample app on this page loops through the syndication feed at [https://blogs.windows.com/feed] - which, when it happens to include the trademark character '™' (U+2122), breaks the console output (because, I speculate but have not investigated in depth, the ostream and the character encoding disagree in some fundamental manner).
(The character in question is part of the title for the blog post [https://blogs.windows.com/windows-insider/2023/02/09/update-to-windows-subsystem-for-android-on-windows-11-february-2023/].)
This is annoying and could cause problems to developers trying to figure out why WinRT seems broken (when, really, it has nothing to do with WinRT). Worse yet, at least as far as QA is concerned, this problem is only occasionally replicable, because the contents of the feed will change over time.

Hope this helps.

--
Davi Gray

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae018a1-a3ab-037a-2df7-354677971ff9
* Version Independent ID: 95ff0a4f-48c7-4962-93b3-538ab5ec458f
* Content: [Get started with C++/WinRT - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [uwp/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Davi-Gray! I've published a fix to the code. If other similar inputs cause failures, then we can work around them as they arise.

Thanks!
-Steve
