### ISSUE TITLE
Spacing error in sub-section title

### ISSUE THREAD

**Issue by mirachadha22** [MicrosoftDocs/windows-uwp#4302]
The sub-section header "Examples of compact sizing" currently reads as "Examples ofcompact sizing".

The particular subsection in question is [here](https://learn.microsoft.com/en-us/windows/apps/design/style/spacing#examples-ofcompact-sizing).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd97967f-d2b4-41fc-6510-3dc14686f426
* Version Independent ID: 983454ed-a605-6411-0e42-cd956088abf5
* Content: [Spacing and Sizes - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/style/spacing)
* Content Source: [hub/apps/design/style/spacing.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/style/spacing.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I was trying to make the header itself compact?

I just checked in a fix for this. Should be published shortly.
