### ISSUE TITLE
WSL 2 and hot reloading issue

### ISSUE THREAD

**Issue by lurco** [MicrosoftDocs/windows-uwp#4303]
[Enter feedback here]
The issue with this article is that is suggests using React in a WSL 2 which is unfortunately unfeasiable for the time being, as hot reloading does not work when editing the project in Windows IDE. Untill this issue is fixed, you either have to install node etc. through Powershell on Windows or use WSL1 (which is a hustle).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89f5b5f4-c9f6-2618-5711-554436d4592c
* Version Independent ID: d37910a5-4903-81a7-7450-b827cd7ddfbe
* Content: [Install React on Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-on-wsl?source=recommendations)
* Content Source: [hub/dev-environment/javascript/react-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/react-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by craigloewen-msft** [comment]
Hi Lurco, our recommendation here is to use VS Code Remote as your IDE, or use an IDE that has WSL integration to use it with the Linux file system. This will give you hot reloading (And make your compile a lot faster).
