### ISSUE TITLE
Missing information about the behaviour of subdomain in wns channel URI

### ISSUE THREAD

**Issue by abhisheky-zop** [MicrosoftDocs/windows-uwp#4305]
Documentation is not clear on whether the sub-domain for the push channel URI has the possibility of change. Or we can expect it to be same for the current application.

It says we need to check for the domain notify.windows.com, however the behaviour of sub domain is still ambiguous.

 Is it safe for application to assume the channel URI will belong to the same sub-domain always ?

**Comment by drewbatgit** [comment]
The sub-domain of push channel URI is subject to change. Currently they are tied with WNS prod environments. If WNS’s geo topology is changed or prod environments were added/removed/replaced, the channel url for the same device could be changed as well.

The notify.windows.com domain shouldn’t be changed. We recommend customers to take no assumption on subdomains.
