### ISSUE TITLE
Missing shortcut(-s?) in Shortcut Guide 

### ISSUE THREAD

**Issue by Mahnas92** [MicrosoftDocs/windows-uwp#4306]
Hi

Shortcut for Windows + P is missing.
Also, some example or indication on what kind of "Corner Case" is missing, I am a power user after all, tell me what kind of corner case and let me decide on the spot, instead of inspiring fear of the unknown and letting me avoid using Win key for activation out of "fear".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c39e7c8-7ab6-3297-1554-d7ef10d46894
* Version Independent ID: 021ad68a-284a-fd90-4404-463f08301b04
* Content: [PowerToys Shortcut Guide utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/shortcut-guide)
* Content Source: [hub/powertoys/shortcut-guide.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/shortcut-guide.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message.
This request would be better placed in the PowerToys repository. This repo is about the documentation on MS Learn. See issue https://github.com/microsoft/PowerToys/issues/179
CC @mattwojo
Having that said, I can say that Shortcut Guide has not been receiving any real updates for a long time - unfortunately. But, some day...

**Comment by mattwojo** [comment]
Thanks for filing this @Mahnas92 and for responding @Jay-o-Way. It looks like this does not (yet) require an update to the docs as Win + P is not yet supported... but looks like it's in the works, thanks for the link to that issue Jay. In the meantime, if you have any "corner cases" that you're aware of and feel should be specifically identified in the docs, @Mahnas92, please feel welcome to reopen this issue and point them out.
