### ISSUE TITLE
Step 1 doesn't work

### ISSUE THREAD

**Issue by BBerndog** [MicrosoftDocs/windows-uwp#4309]
Step 1: Launch a web browser, navigate to ... and select Sign up.

When selecting sign up using my MS account all I get is Not Authorized and no explanation why.

It'd be nice if the article addressed that issue and how to resolve. it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1454e7-b65d-5cce-834a-d2b6bb57bbc7
* Version Independent ID: 3e1454e7-b65d-5cce-834a-d2b6bb57bbc7
* Content: [Open a developer account in Partner Center - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/open-a-developer-account)
* Content Source: [hub/apps/publish/partner-center/open-a-developer-account.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/open-a-developer-account.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@BBerndog Internal Microsoft accounts work differently. This documentation is intended for external users, or internal users using their own personal PC accounts.
