### ISSUE TITLE
Example is missing critical context

### ISSUE THREAD

**Issue by alexmarshall132** [MicrosoftDocs/windows-uwp#431]
The example above on how to use extended sessions is missing critical context. Where should this code be run ? App.xaml.cs ? Somewhere else ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f08a1cd-54da-9647-5f88-12ff5dcd9bab
* Version Independent ID: 1de44f88-2e90-cc63-9707-b415be120237
* Content: [Run in the background indefinitely - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly)
* Content Source: [windows-apps-src/launch-resume/run-in-the-background-indefinetly.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-in-the-background-indefinetly.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
