### ISSUE TITLE
missing O+Breve with quick accent

### ISSUE THREAD

**Issue by aronvandepol** [MicrosoftDocs/windows-uwp#4310]
For romanising Korean into Revised McCune-Reischauer often characters with a breve are used. Finally using this tool i am able to type these easily on windows, ŭ / ă etc.  but the o with breve (Ŏ ŏ) is missing when using the selection screen for O. Could you add this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Version Independent ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Content: [PowerToys Quick Accent utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/quick-accent)
* Content Source: [hub/powertoys/quick-accent.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. This repo is about the documentation on MS Learn. This request would be better placed in the [PowerToys repository](https://github.com/microsoft/PowerToys/issues).

**Comment by Jay-o-Way** [comment]
@mattwojo

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but as @Jay-o-Way suggested, you can create an issue in the [PowerToys repo](https://github.com/microsoft/PowerToys/issues).

If you do create an issue, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation, if necessary. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
