### ISSUE TITLE
Update PowerShell script to install Winget in Windows Sandbox

### ISSUE THREAD

**Issue by glawrence** [MicrosoftDocs/windows-uwp#4315]
The original script actually contained a typo. I have created #4264 to fix this, as well as get the latest Winget and install the required dependencies. I believe the PR is ready to merge, it just needs someone to approve and merge. If I have done something wrong or it needs improving then please let me know.

**Comment by mattwojo** [comment]
Thank you @glawrence . This issue was fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ca90ce0471458f85af6dc789200b263affcfd8ec
