### ISSUE TITLE
Windows.System.LauncherOptions doesn't implement IInitializeWithWindow on RS5(10.0.17763 Build 17763)

### ISSUE THREAD

**Issue by Manohar-Gunturu** [MicrosoftDocs/windows-uwp#4317]
[Enter feedback here]

Casting Windows.System.LauncherOptions to IInitializeWithWindow on Win10 RS5(10.0.17763 Build 17763) version fails with WinRT originate error - 0x80004002 : 'No such interface supported', but works fine on Win10 Vb(20H1).

But documentation says that Windows.System.LauncherOptions implements IInitializeWithWindow.
![image](https://user-images.githubusercontent.com/6416138/222026391-432266a1-1fc8-4e21-97e2-c6e11217db36.png)

Could be helpful if documentation gives more information on OS version support.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33db1089-cdfe-70c9-1eea-153a2aa8c70b
* Version Independent ID: 33db1089-cdfe-70c9-1eea-153a2aa8c70b
* Content: [Display WinRT UI objects that depend on CoreWindow - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/display-ui-objects)
* Content Source: [hub/apps/develop/ui-input/display-ui-objects.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/ui-input/display-ui-objects.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Manohar-Gunturu! And I got your email (via Michael) at the same time. :) The fix is now published. And it looks like this is the only place in the docs where we talk about querying for that iface from that type.

Thanks!
-Steve
