### ISSUE TITLE
Unable to set the AccessKey and KeyTipPlacementMode for the Settings NavigationMenuItem object

### ISSUE THREAD

**Issue by dyyMsft** [MicrosoftDocs/windows-uwp#432]
How can I set the AccessKey and KeyTipPlacementMode for the Settings NavigationMenuItem object in XAML? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Unfortunately, I don't think you can :(
