### ISSUE TITLE
Spelling error under app icon perspectives

### ISSUE THREAD

**Issue by Odyssey28** [MicrosoftDocs/windows-uwp#4321]
Under Perspectives, "The icons on the left are fairly simple; perspective is not recommended, but **my** be appropriate here."

I'm assuming it's supposed to be "may".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e32b9e2c-045c-bab0-4565-a9100c038f45
* Version Independent ID: e32b9e2c-045c-bab0-4565-a9100c038f45
* Content: [Design guidelines for Windows app icons - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-design)
* Content Source: [hub/apps/design/style/iconography/app-icon-design.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/style/iconography/app-icon-design.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just merged a fix for this. Thanks for reporting it!
