### ISSUE TITLE
SVG preview background color

### ISSUE THREAD

**Issue by pixelgrease** [MicrosoftDocs/windows-uwp#4326]
Is it possible to change baqckground for SVG preview?

I have a folder full of transparent SVG images with white shapes and I cannot see any of them in the preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [PowerToys File Explorer add-ons utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
It is not possible.

**Comment by mattwojo** [comment]
Closing. Thanks for filing this @pixelgrease and for addressing the question @Jay-o-Way. I'll add a note in the docs.
