### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by saad1z** [MicrosoftDocs/windows-uwp#4330]
[Enter feedback here]
Hello

This is a suggestion for PowerToys Rename feature. It would be great if i could a certain text to all the files in one go.

E.g:

File A and File B

File A1 and File B1

This would help me a lot!!!!!!1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @saad1z  - This repo is focused on PowerToys documentation. For feature requests like this, please file it on the PowerToys product development repo here: https://github.com/microsoft/PowerToys/issues

It looks like there may already be some related requests open: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+is%3Aopen+rename ...if any of them align with what you're wanting, just give them a +1 / thumbs up and comment with any additional info that you may have to offer. The more info and support for a request that the contributors see, the more likely it is to get pushed forward. 
Thanks!
