### ISSUE TITLE
Mistake in abbreviation on the page.

### ISSUE THREAD

**Issue by MariiaPampurina** [MicrosoftDocs/windows-uwp#4336]
I noticed a small error on the page https://learn.microsoft.com/en-us/windows/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design in the table "Breakpoints" in column "Breakpoints" and by line "Large" need must be specified "1080px" instead of "1008ps" .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 744c0c15-6f2d-a7df-cf7f-e1c0096dc921
* Version Independent ID: 9908453f-430a-3f7a-db4e-4805df55faac
* Content: [Screen sizes and break points for responsive design - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design)
* Content Source: [hub/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for catching this issue. The page has been corrected.
