### ISSUE TITLE
Are the contribution guidelines up to date?

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/windows-uwp#4347]
The [contribution guidelines](https://github.com/MicrosoftDocs/windows-dev-docs/blob/fd90154b0a80bdeac6b3de2310926c9669a73039/CONTRIBUTING.md) mention the UWP documentation, however this repository also contains information around other Windows Development and might cause confusion. If this is indeed not intentional, I can create a PR for this.

**Comment by mattwojo** [comment]
Thanks for pointing this out @chingucoding! You're right - that Readme is really out of date. I'm working on updating it now. In the meantime, you can find more current info on contributing here: https://learn.microsoft.com/contribute/

**Comment by mattwojo** [comment]
Updated that Readme: https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/CONTRIBUTING.md 
Thanks again @chingucoding. Closing this issue.
