### ISSUE TITLE
Missing 'Reveal' definition

### ISSUE THREAD

**Issue by reddvid** [MicrosoftDocs/windows-uwp#435]
My bad - but no, the docs never mentioned this was Prerelease API 1803. 
Disregard my issue.

I added this on my app which targets 16299, but an error shows that FocusVisualKind does not contain a definition for Reveal...
Am I missing an SDK or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf80b3e-ce8c-b3bd-c87a-5d8ddc0f2b92
* Version Independent ID: 9a7d0b0f-e373-1e50-ab9f-69ec00e21dc4
* Content: [Reveal focus - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal-focus)
* Content Source: [windows-apps-src/design/style/reveal-focus.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/reveal-focus.md)
* Service: **unspecified**
* GitHub Login: @cphilippona
* Microsoft Alias: **mijacobs**

**Comment by Skittles2519** [comment]
I tried the same thing and got the same error. I'm guessing we need to wait until the Spring Creators Update with the new SDK

**Comment by mijacobs** [comment]
This feature is part of an upcoming update that will RTM later this month. If you'd like to use the feature now, you can join the Windows Insider Program and get the pre-release OS and SDK:
https://insider.windows.com/en-us/ 
(Btw, we're working on improving the docs to make these sort of OS/SDK requirements more clear--thank you for filing an issue!)
