### ISSUE TITLE
Not updated with latest versions of WindowsAppSDK/WinUI3

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#4354]
Seems like this table shows info based on the 1.0 release, but there's an upcoming 1.3 release for the Windows App SDK, this doc should be updated to reflect the current capabilities.

FYI @chigy @bpulliam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d50fa20-7181-81ae-b98e-5fef477f099a
* Version Independent ID: 9d50fa20-7181-81ae-b98e-5fef477f099a
* Content: [What is supported when migrating from UWP to WinUI 3 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @michael-hawker! I've started an email thread to get the info so that I can update the topic (copied you on that). I'll use that thread to track the work, so I can close this (unless you think we need it open).

Thanks again! :)
-Steve

**Comment by stevewhims** [comment]
UPDATE: I've updated the topic with the latest support status. I also grouped and sorted the table for easier reading.
