### ISSUE TITLE
The `AppxPackageSigningEnabled` doesn't work anymore

### ISSUE THREAD

**Issue by ramondeklein** [MicrosoftDocs/windows-uwp#4356]
The package signing as described in [Configure package signing](https://learn.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps#configure-package-signing) doesn't work anymore. It used to work fine until March 2023, but it started to fail since that time with the following error:
```
APPX1103: Failed to sign ..., because of SignTool Error: The /p option requires the /f option
```
Both `PackageCertificateKeyFile` and `PackageCertificatePassword` are set like described:
```
   - task: DownloadSecureFile@1
     displayName: 'Download Windows code-signing certificate'
     name: signingCert
     inputs:
       secureFile: 'uwp-publisher-certificate.pfx'
   - task: VSBuild@1
     displayName: 'Build Windows UWP application'
     inputs:
       platform: 'x86'
       solutionFile: 'csharp/**/*.sln'
       configuration: 'Release-UWP'
       msbuildArgs: '/p:AppxPackageDir="$(build.artifactStagingDirectory)"
                     /p:AppxBundlePlatforms="x86|x64|ARM"
                     /p:AppxBundle=Always
                     /p:UapAppxPackageBuildMode=StoreUpload
                     /p:UapAppxPackageBuildMode=CI
                     /p:AppxPackageSigningEnabled=true
                     /p:PackageCertificateThumbprint="" 
                     /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)"
                     /p:PackageCertificatePassword="$(UwpPublisherCertificatePassword)"'
```

I checked the secure files and library and it seems the file and password are still there. It seems that the `SignAppxPackages` in `Microsoft.AppxPackage.Targets` has been updated somehow or the `Microsoft.Build.AppxPackage.dll` is changed. It seems it invokes `signtool.exe` incorrectly.

Note that this issue is also addressed in https://developercommunity.visualstudio.com/t/-SignTool-Error:-The-p-option-requires-/10307294?viewtype=all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
* Content Source: [uwp/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by bansalsushant** [comment]
Hi @ramondeklein!

Thanks for raising this issue. This issue has been fixed and is in preview as of now. It will be released in the coming week.
