### ISSUE TITLE
Run this on Azure DataScience VM?

### ISSUE THREAD

**Issue by tja2000** [MicrosoftDocs/windows-uwp#436]
Did anyone manage to run this app on the data science VM from Azure? I installed the updated SDK 17125, but still get the error 'Error CS0234	The type or namespace name 'AI' does not exist in the namespace 'Windows' (are you missing an assembly reference?)	MNIST_Demo	
'

talking about this app: https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started

Thierry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd018cd-e51b-b15b-3460-8ff4a4a83f3b
* Version Independent ID: 4f95e997-6554-9384-5f57-a193e4c85bf8
* Content: [Get started with Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started)
* Content Source: [windows-apps-src/machine-learning/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/get-started.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Hi! The sample targets Build 17110. Have you tried changing the project's target version to your build?

**Comment by tja2000** [comment]
Hi Serena, where can I set this? I am an R and Python dev, not very confortable in Visual Studio.
Thanks!

**Comment by tja2000** [comment]
Ok, moving step by step, this is the error I get now when deploying: 
DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.17125.0 or higher. You currently are running version 10.0.14393.2068. Please update your OS, or change your deployment target to a device with the appropriate version.	MNIST_Demo

**Comment by serenaz** [comment]
To change your deployment target in Visual Studio, go to Properties under the project solution. In the Application tab, you can set the Target version.

**Comment by tja2000** [comment]
I set this, but the deploy does not work. Build is ok though.
![image](https://user-images.githubusercontent.com/11030714/38664948-5e3582e0-3e3b-11e8-8e2b-43ea70b2194c.png)

**Comment by tja2000** [comment]
Ok, after many many tries I gave up on the server and launched an Windows 10 on Azure, installed insiders build and VS2017 Preview + the SDK. Build an Deploy are ok. I can run the app, draw a number but when I click on Recognize I get an error in the code:
System.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MNIST_Demo.Helper.<CropAndDisplayInputImageAsync>d__2.MoveNext() in C:\DEV\Windows-Machine-Learning-master\Samples\UWP\MNIST_GetStarted\src\Helper.cs:line 55
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MNIST_Demo.Helper.<GetHandWrittenImage>d__1.MoveNext() in C:\DEV\Windows-Machine-Learning-master\Samples\UWP\MNIST_GetStarted\src\Helper.cs:line 29
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MNIST_Demo.MainPage.<recognizeButton_Click>d__7.MoveNext() in C:\DEV\Windows-Machine-Learning-master\Samples\UWP\MNIST_GetStarted\src\MainPage.xaml.cs:line 58

**Comment by serenaz** [comment]
The MNIST_GetStarted sample is meant to be completed alongside the [Get started with Windows ML ](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started) tutorial. You need to implement the method for the "Recognize" button to work, as described in the tutorial. If you'd like to run a completed sample, use the completed MNIST sample in the same folder (Windows-Machine-Learning-master\Samples\UWP\MNIST).

**Comment by tja2000** [comment]
Can you re-open this please? I did all that, completed the code and even ran the example that is pre-configured. But neither of the two work. I completely removed all VS installations and all .net framework, re-installed but no success. The SqeezeNetObjectDetection sample doesn't work either.

**Comment by serenaz** [comment]
Ok! Let's investigate. To run the samples, you need 1) Windows 10 Build 17110 or higher, and 2) SDK Build 17110 or higher. Do you have both?

https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

**Comment by tja2000** [comment]
here you are:
![image](https://user-images.githubusercontent.com/11030714/38696337-282bd4e8-3e8f-11e8-8329-0b981ddfd3ca.png)

**Comment by serenaz** [comment]
OK, what version of VS do you have? What kind of errors are you getting now?

**Comment by tja2000** [comment]
VS: 
![image](https://user-images.githubusercontent.com/11030714/38697191-97c379ee-3e91-11e8-8de0-c467e3117bbc.png)

Error: 
![image](https://user-images.githubusercontent.com/11030714/38697236-b29c1474-3e91-11e8-9cef-f8fe599f59fe.png)

Exception thrown: 'System.NotImplementedException' in System.Private.CoreLib.ni.dll
An exception of type 'System.NotImplementedException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code.

**Comment by serenaz** [comment]
In Step 6 of the tutorial, did you instantiate the input?

`private MNISTModelInput ModelInput = new MNISTModelInput();`

https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started#6-load-bind-and-evaluate-the-model

**Comment by tja2000** [comment]
Yes. I did. I have the same error in the sample file with the completed code. I think it is something much deeper, like a wrong library is loaded from a previous version or so.

**Comment by tja2000** [comment]
This is the line where the error occurs when stepping through the code:  
await inputVideoFrame.CopyToAsync(cropped_vf, cropBounds, null);

**Comment by serenaz** [comment]
Hmm. That's odd. Since this has to do with the sample code, I'd recommend raising an issue in the samples repo: https://github.com/Microsoft/Windows-Machine-Learning

Hopefully they can help!

**Comment by tja2000** [comment]
Yep, will do. Thanks for the help !!!
BTW: I did all this on a VM in Azure, maybe it has something to do with video on virtual machines?

**Comment by serenaz** [comment]
Sure! You can also raise an issue for Azure VMs: https://github.com/MicrosoftDocs/azure-docs
