### ISSUE TITLE
Windows Widget implementation article is misleading - it makes you create a console app that shows a console window when showing widgets

### ISSUE THREAD

**Issue by xyzzer-msft** [MicrosoftDocs/windows-uwp#4362]
For the main article documenting how to create a widget - it makes you waste time creating one that results in a console window showing in Windows Terminal whenever you show the widgets board. As I understand - widgets should be added to existing windowed or headless app and that part should definitely be included in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d81a1eb-10f9-caf2-7457-48df84ca543e
* Version Independent ID: 1d81a1eb-10f9-caf2-7457-48df84ca543e
* Content: [Implement a widget provider in a win32 app (C++/WinRT) - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-win32?source=docs)
* Content Source: [hub/apps/develop/widgets/implement-widget-provider-win32.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/implement-widget-provider-win32.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for the feedback. The how-to creates a console app to make debugging easier for people getting started with Windows widgets. But we have updated the guidance to include instructions for converting the resulting app from a console app to a Windows app so that the console doesn't show.
