### ISSUE TITLE
Make sure you strip the whitespace between tags

### ISSUE THREAD

**Issue by ntrf** [MicrosoftDocs/windows-uwp#437]
Examples are formatted, real Recipts are not. If you try to verify XML signature with whitespace preserved, it can fail validation, depending on the language and library used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d2904b-93c3-1b6d-307d-8ee17a8210e7
* Version Independent ID: 90c6af9f-fc0b-febc-f031-d57f5c34d862
* Content: [Use receipts to verify product purchases - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/use-receipts-to-verify-product-purchases#receipt-descriptions)
* Content Source: [windows-apps-src/monetize/use-receipts-to-verify-product-purchases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/use-receipts-to-verify-product-purchases.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you for your feedback. I have added notes before each of the receipt examples in this article to clarify that real receipts do not have whitespace between the XML elements. These notes should be published to the live article in a day or two.
