### ISSUE TITLE
Explanation of settings.json for PowerToys Awake utility

### ISSUE THREAD

**Issue by dwaq** [MicrosoftDocs/windows-uwp#4371]
This page explains the use of `settings.json` configuration file, but does not provide the file location. It is located at `%HomePath%\AppData\Local\Microsoft\PowerToys\Awake\`.

The "Keep awake temporarily" options can be adjusted by modifying the `"tray_times"` value which is an array consisting of human readable name and the duration, in seconds, to stay awake. For example: `"tray_times":{"8 hours":28800}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a20e555a-65ad-82e7-e1c0-f6577c1322b2
* Version Independent ID: 29236a0e-82e8-92d7-a5fb-12a9a777bcc2
* Content: [PowerToys Awake utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/awake)
* Content Source: [hub/powertoys/awake.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/awake.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
FYI @dend

**Comment by mattwojo** [comment]
Thanks @dwaq ! Added this note to the PowerToys Awake document in https://github.com/MicrosoftDocs/windows-dev-docs/commit/5a2c487a6d7e8fab3b1998c94a197491578483dc
