### ISSUE TITLE
Sample code in this page were not in language seleted

### ISSUE THREAD

**Issue by jules-ai** [MicrosoftDocs/windows-uwp#4373]
When I select "C++/WinRT" this page still shows code samples only in C#

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7851642e-6037-0053-8fa0-e90b6773d309
* Version Independent ID: 7851642e-6037-0053-8fa0-e90b6773d309
* Content: [Data binding in depth - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/data-binding/data-binding-in-depth)
* Content Source: [hub/apps/develop/data-binding/data-binding-in-depth.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/data-binding/data-binding-in-depth.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for contacting us about this issue. I large number of documentation pages only have code samples in one language. The system is designed to show that sample when other languages are selected instead of removing the section.
