### ISSUE TITLE
Idea new Fesutures?

### ISSUE THREAD

**Issue by smartservis** [MicrosoftDocs/windows-uwp#4377]
Hello 
Are you using text shortcuts on iOS or using aText, FastKeys, Typinator, on Windows?
Text teplote is a good idea to PowerToys
Type thx and system write Thank You 
Or: “mail” - johnmarkmc@bussinessmail.com
“Bn” - bank number IBAN:XX00020023003038
And mamy mamy more 😀

**Comment by smartservis** [comment]
Why cloced? This is idea for PowerToys

**Comment by mattwojo** [comment]
@smartservis -- I'm unclear on what idea you're recommending and don't feel comfortable with the "bank number" included. If you would like to suggest an idea for PowerToys, you can do so here: https://github.com/microsoft/PowerToys/issues
First search the open issues to see if someone has already recommended the idea.. if so, give a thumbs up and comment to show your support and shared interest. If not, select "New issue" and fill in the details requested. Please do not include any information that could be interpreted as personal or private or the post will automatically be closed.

**Comment by smartservis** [comment]
there is an example number of IBAN does not exist.
Dzenkujem
