### ISSUE TITLE
Link to windows app sdk is broken

### ISSUE THREAD

**Issue by dunstantom** [MicrosoftDocs/windows-uwp#4378]
Url is: https://learn.microsoft.com/en-us/windows-app-sdk/set-up-your-development-environment
Leads to 404

**Comment by stevewhims** [comment]
Thanks, @dunstantom. I found that incorrect url on https://learn.microsoft.com/windows/apps/get-started/enable-your-device-for-development, and I fixed it there. I didn't find it anywhere else, but please let us know if you find more (and which topic the broken url lives on).

Thanks!
-Steve
