### ISSUE TITLE
Where is link to Partner Center

### ISSUE THREAD

**Issue by KodiStudios** [MicrosoftDocs/windows-uwp#4380]
Current instructions state:

```Cmd
Follow the following steps to reserve your app's name:
1. Sign in to Partner Center.
```

But where is the link to this `Partner Center`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2e595ca-9d04-63e4-5967-13e6b822ddb7
* Version Independent ID: c2e595ca-9d04-63e4-5967-13e6b822ddb7
* Content: [Reserve your app's name - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/reserve-your-apps-name)
* Content Source: [hub/apps/publish/publish-your-app/reserve-your-apps-name.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/reserve-your-apps-name.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for logging this issue. I've added a link to the page. It should be published in the next few minutes.
