### ISSUE TITLE
using segoe fluent fonts

### ISSUE THREAD

**Issue by mboedigh** [MicrosoftDocs/windows-uwp#4384]
First Sorry, this is a user question created with a mis-click and I don't see how to delete it. 

I created an WinUI 3 App using a c# template. I'm trying to use an AppBarToggleButton with Icon="Record", but the Icon is not included. The app (both xaml and code behind) appear to be using the older Segoe MDL2 fonts and I can't find how to tell my program to use Segoe Fluent fonts. I tried setting FontFamily in xaml
`<AppBarToggleButton x:Name="PlayPauseButton" IsThreeState="True"  Icon="Record" Click="PlayPauseButton_Click" FontFamily="Segoe Fluent Icons"/>`

I also tried adding:
```
        <SymbolIcon Symbol="GlobalNavigationButton"/>
        <FontIcon FontFamily="Segoe Fluent Icons" Glyph="&#xE700;"/>
```
In all cases Intellisense says Record in an "Invalid Property Value".  I have a similar problem using code behind to set the icon `PlayPauseButton.Icon = new SymbolIcon(Symbol.Record);`
If I navigate to the definition of `Symbol`, Visual studio brings me to decompiled file with a comment that says it is Segoe MDL2 Assets. How can I change this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e1f4b4-3d25-c08c-e3b0-12011d3bba0f
* Version Independent ID: 3b140070-493f-0b2c-f7c4-3fb89192d2d0
* Content: [Segoe Fluent Icons font - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font)
* Content Source: [hub/apps/design/style/segoe-fluent-icons-font.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/style/segoe-fluent-icons-font.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Jay-o-Way** [comment]
Good point. Have a look at https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.symbol?view=winrt-22621

1. The SymbolIcon set is only a _limited_ set, "Record" does not seem to be included
2. SymbolIcon still uses MDL2 font and deprecated codes in the background; see https://github.com/MicrosoftDocs/winrt-api/issues/2363

**Comment by Jay-o-Way** [comment]
**SymbolIcon** is practically deprecated. See https://github.com/microsoft/microsoft-ui-xaml/issues/5887#issuecomment-1642824614
Use a **FontIcon**.
