### ISSUE TITLE
Unable to use Micrsoft.Data.SQLite

### ISSUE THREAD

**Issue by mysorian** [MicrosoftDocs/windows-uwp#439]
Data is not one of the options. Both the DataAccessLibrary and UWPDataTest have these references:
Microsoft.Data.Sqlite
SQLitePCLRaw.bundle_winsqlite3 and
Microsoft.NETCore.UniversalWindowsPlatform

---The Options for Microsoft via drop-down are, CSharp, VisualBasic and Win32
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#use-data)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thanks Mysorian. Can you please clarify where you are expecting to see the term "Data" or object name "Data" in your project? Thank you.

**Comment by mysorian** [comment]
When I try to insert the using Microsoft.Data.SQLite;

**Comment by normesta** [comment]
Hi Mysorian. So to clarify, when you add the using statement "using Microsoft.Data.Sqlite" to the top of your DataAccessLibrary file, that statement gives you an error of some kind? Can you please tell me what that error is?

Thank you.

**Comment by mysorian** [comment]
Actually after repeating two times, I gave up. I shall revisit and let you know. Thanks for responding.

**Comment by mysorian** [comment]
Finally got around to the point where I faced the error.
Details here:
[http://hodentek.blogspot.com/2018/04/on-connecting-to-sqlite-from-uwp-app.html](url)

**Comment by normesta** [comment]
Hi mysorian - Is your project targeting the most recent version of the publically released windows SDK? If so, are you following the steps described in the "The minimum version of your project targets the Fall Creators Update" section? Would you be willing to share your project?

**Comment by mysorian** [comment]
![uwpdatatestpost_12](https://user-images.githubusercontent.com/5265734/38772767-4ba745f0-3fda-11e8-9d44-a9fc0fa0066d.png)
![uwpdatatestpost_13](https://user-images.githubusercontent.com/5265734/38772769-4fee5bd0-3fda-11e8-8abc-8bcc48eb07fe.png)
I can zip and send project's folder. I might have done something wrong.

**Comment by mysorian** [comment]
Is there a workaround for this problem? The error is:
Error	CS0246	The type or namespace name 'DataAccessLibrary' could not be found (are you missing a using directive or an assembly reference?)

**Comment by normesta** [comment]
Hi mysorian - you'll need to add a project reference to the DataAccessLibrary project from your UWP project. You'll also need to add a using statement to the top of the file where you use the DataAccessLibrary namespace.

**Comment by normesta** [comment]
Closing. Please open a new issue if you find something inaccurate in the doc. Thank you.
