### ISSUE TITLE
The code example to dim title bar text is incorrect

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/windows-uwp#4390]
Currently, the code to dim the title bar when the window is unfocused is incorrect. The system colours "window text" and "grey text" used by the example haven't been adapted to accommodate dark mode and thus will be unreadable. Setting opacity is probably a better method but I'm not sure about the opacity value Microsoft recommends using for dimming the title bar text. Could you please clarify and document that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83eb07b8-55ba-97a5-3cb4-69ae39fe31cd
* Version Independent ID: 83eb07b8-55ba-97a5-3cb4-69ae39fe31cd
* Content: [Title bar customization - Windows apps](https://learn.microsoft.com/en-gb/windows/apps/develop/title-bar?tabs=wasdk#dos-and-donts)
* Content Source: [hub/apps/develop/title-bar.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/title-bar.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for catching that the code shown to use UISettings doesn't correctly support dark mode. Instead, the code should look up the appropriate Brush resource, like this:

```
if (args.WindowActivationState == CoreWindowActivationState.Deactivated)
{
    AppTitleTextBlock.Foreground =
        (SolidColorBrush)App.Current.Resources["TextFillColorDisabledBrush"];
}
else
{
     AppTitleTextBlock.Foreground =
         (SolidColorBrush)App.Current.Resources["TextFillColorPrimaryBrush"];
}
```

The documentation will be updated shortly.
