### ISSUE TITLE
Compilation error on setting the Source() of the image from SurfaceImageSource

### ISSUE THREAD

**Issue by ThierryCam** [MicrosoftDocs/windows-uwp#4396]
At this line : 
theImage().Source(surfaceImageSource);

I have this error: 

Error (active) E0304 no instance of overloaded function "winrt::Microsoft::UI::Xaml::Controls::Image::Source" matches the argument list

Source() is expecting ImageSource and didn't find a way to convert from SurfaceImageSource

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b263a91c-cfc3-2457-196f-ab9c74b14a5f
* Version Independent ID: bc2cd244-bd4d-b294-c787-12fb2a2ad373
* Content: [DirectX and XAML interop - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop)
* Content Source: [uwp/gaming/directx-and-xaml-interop.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/gaming/directx-and-xaml-interop.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @ThierryCam. The error message mentions a type in the Microsoft::UI::Xaml::(etc.) namespace. This topic talks about "your Universal Windows Platform (UWP) game or app", so it expects you to be using Windows::UI::Xaml::(etc.). I suspect that's the disconnect.

I've added a bit more info to the top of the topic to make it clear that it's about UWP types. I don't have info about interop between DirectX and types in Microsoft::UI::Xaml::(etc.). I did try it a long time ago with inconclusive results. To the best of my knowledge, it's not yet supported.

Thanks!
-Steve

**Comment by joelspadin** [comment]
I got the sample to build simply by swapping out
```cpp
#include <windows.ui.xaml.media.dxinterop.h>
#include <winrt/Windows.UI.Xaml.Media.Imaging.h>

using namespace Windows::UI::Xaml::Media::Imaging;
```
for
```cpp
#include <microsoft.ui.xaml.media.dxinterop.h>
#include <winrt/Microsoft.UI.Xaml.Media.Imaging.h>

using namespace Microsoft::UI::Xaml::Media::Imaging;
```
