### ISSUE TITLE
ms-settings:quietmomentsgame : Blocking Notifications Win11 22H2

### ISSUE THREAD

**Issue by AnupShetty10** [MicrosoftDocs/windows-uwp#4397]
[Enter feedback here]
Disabling ms-settings:quietmomentsgame also disables "Notification settings" in Windows. We are seeing this behavior since last update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#gaming)
* Content Source: [uwp/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like feedback, about the product. This page is about launching Windows settings pages from your app. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback.
