### ISSUE TITLE
Article references a non-existent video

### ISSUE THREAD

**Issue by ejm554** [MicrosoftDocs/windows-uwp#4399]
The article includes this sentence:

> _This video provides a brief introduction on how to prepare your app for the world: Introduction to globalization and localization._

However, no video can be found on the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2e682a3-ccde-c14c-e602-c0e49ecfd95c
* Version Independent ID: df49510e-582a-758e-0ffa-9af9f30613cf
* Content: [Globalization and localization - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/globalizing-portal)
* Content Source: [hub/apps/design/globalizing/globalizing-portal.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/globalizing/globalizing-portal.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! The link has been fixed.
