### ISSUE TITLE
PDF is incomplete

### ISSUE THREAD

**Issue by bapcyk** [MicrosoftDocs/windows-uwp#440]
I download PDF. It's very big. Fine. But most pages are empty (blank). For example, I clicked on "Nav View" and opened page is blank. I tried it with Edge and Opera - the same. But it will be super good to have such PDF. Dear Microsoft Team, please fix PDF.

**Comment by mcleblanc** [comment]
Thanks for reporting this. This is a known issue that we are currently investigating internally and are working to make sure is addressed as soon as possible.

**Comment by mijacobs** [comment]
The PDF has been fixed.
