### ISSUE TITLE
pathetic

### ISSUE THREAD

**Issue by syedrashid47** [MicrosoftDocs/windows-uwp#4404]
pathetic, 
I want to know the name of the person that decided that we are going to use rounded corners and not allow an option to remove this. so pathetic. 

this is what happens when you do designing on a 40 inch screen for a product that is usually viewed in 15 inch screens, 
again, Pathetic

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c458089f-9da5-9c1a-964b-01531e977fea
* Version Independent ID: e300d17f-fb88-409a-ecfb-b7b7c6cad0a2
* Content: [Geometry in Windows 11 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/signature-experiences/geometry)
* Content Source: [hub/apps/design/signature-experiences/geometry.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/signature-experiences/geometry.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thank you for your feedback. Because no document updates are required, I'm going to close this issue.
