### ISSUE TITLE
Starting windows photos app with an uri (file) to open and display the arrow buttons

### ISSUE THREAD

**Issue by popy2k14** [MicrosoftDocs/windows-uwp#4406]
The example: "ms-photos:viewer?fileName=c:\users\userName\Pictures\image.jpg"  does not work!
It just opens the photos app with all photos instead of the given one.

I want to use this to open an photo from an third party file manager (FreeCommander XE donor) and use the keyboard keys and/or arrow buttons to navigatr throught all photos in that folder.

Can you please check/correct the wrong documentation?

PS.: i am on newest Windows 11 22H2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae2608d3-38b8-2404-d138-1ba17772e72c
* Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
* Content: [Launch the default app for a URI - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#photos-app-uri-scheme)
* Content Source: [uwp/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-default-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
It's possible that the updated Photos app broke something with these URIs. I'll check with the product team to see if we need to differentiate between Windows 10 and the latest Windows 11 app. Thanks for bringing this to our attention.

**Comment by popy2k14** [comment]
Thanks for coming back on this.
This issue was also present in Windows 10 with the old app.
Here is a thread from the Windows 10 beginning back in 2015 which is discussing the issue: https://freecommander.com/forum/viewtopic.php?t=6998&sid=67b012976e1951a9ae51aba1bdb45d96

The main issue is that when any other file manager is opening an picture througth shell interface or cmd line:

start "" C:\Test\Test,.png

Just this picture is shown and you have not the possibility to cycle througth all the pictures in that folder (with buttons or keyboard). When you double click the same file in "exploter" you can cycle througth all the pictures.

That was the main issue.
People was searching for workarounds and tried the documented URI thing above.

So please also tell the main issue to your team.

thx

**Comment by alvinashcraft** [comment]
Thanks for the additional details, @popy2k14. I'll take this info to the product team as well. If you want to also submit your feedback to them, there's a submit feedback buttom for "This Product" at the bottom of the docs page. That's for sending issues related to the product instead of about the docs. It seems like this could be a product issue and not a problem with the documentation. I'll keep this issue open until I hear back from the team though.

**Comment by popy2k14** [comment]
Thx for communicating this with the team.
Hope to hear from you soon, since this is an old bug since 2015 :-)

I have added the feedback, like you suggested: https://learn.microsoft.com/en-us/answers/questions/1276156/photos-app-doesnt-show-all-images-in-folder-when-s

**Comment by alvinashcraft** [comment]
Thanks for filing that feedback and linking it here. This is definitely a product issue that will need to be resolved before I can make any changes to the documentation. Once they've addressed the issue or changed the behavior, they'll circle back with me if any changes need to be documented. I hope they get this resolved soon.

**Comment by zggtest** [comment]
> Thanks for filing that feedback and linking it here. This is definitely a product issue that will need to be resolved before I can make any changes to the documentation. Once they've addressed the issue or changed the behavior, they'll circle back with me if any changes need to be documented. I hope they get this resolved soon.

HI： This issue has been resolved ？ Hope replay. Thanks

**Comment by zggtest** [comment]
> The example: "ms-photos:viewer?fileName=c:\users\userName\Pictures\image.jpg" does not work! It just opens the photos app with all photos instead of the given one.
> 
> I want to use this to open an photo from an third party file manager (FreeCommander XE donor) and use the keyboard keys and/or arrow buttons to navigatr throught all photos in that folder.
> 
> Can you please check/correct the wrong documentation?
> 
> PS.: i am on newest Windows 11 22H2
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: ae2608d3-38b8-2404-d138-1ba17772e72c
> * Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
> * Content: [Launch the default app for a URI - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#photos-app-uri-scheme)
> * Content Source: [uwp/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-default-app.md)
> * Product: **uwp**
> * Technology: **processes-and-threading**
> * GitHub Login: @alvinashcraft
> * Microsoft Alias: **aashcraft**
#


> The example: "ms-photos:viewer?fileName=c:\users\userName\Pictures\image.jpg" does not work! It just opens the photos app with all photos instead of the given one.
> 
> I want to use this to open an photo from an third party file manager (FreeCommander XE donor) and use the keyboard keys and/or arrow buttons to navigatr throught all photos in that folder.
> 
> Can you please check/correct the wrong documentation?
> 
> PS.: i am on newest Windows 11 22H2
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: ae2608d3-38b8-2404-d138-1ba17772e72c
> * Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
> * Content: [Launch the default app for a URI - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#photos-app-uri-scheme)
> * Content Source: [uwp/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-default-app.md)
> * Product: **uwp**
> * Technology: **processes-and-threading**
> * GitHub Login: @alvinashcraft
> * Microsoft Alias: **aashcraft**

Have you solved it there? 

> The example: "ms-photos:viewer?fileName=c:\users\userName\Pictures\image.jpg" does not work! It just opens the photos app with all photos instead of the given one.
> 
> I want to use this to open an photo from an third party file manager (FreeCommander XE donor) and use the keyboard keys and/or arrow buttons to navigatr throught all photos in that folder.
> 
> Can you please check/correct the wrong documentation?
> 
> PS.: i am on newest Windows 11 22H2
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: ae2608d3-38b8-2404-d138-1ba17772e72c
> * Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
> * Content: [Launch the default app for a URI - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#photos-app-uri-scheme)
> * Content Source: [uwp/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-default-app.md)
> * Product: **uwp**
> * Technology: **processes-and-threading**
> * GitHub Login: @alvinashcraft
> * Microsoft Alias: **aashcraft**



> The example: "ms-photos:viewer?fileName=c:\users\userName\Pictures\image.jpg" does not work! It just opens the photos app with all photos instead of the given one.
> 
> I want to use this to open an photo from an third party file manager (FreeCommander XE donor) and use the keyboard keys and/or arrow buttons to navigatr throught all photos in that folder.
> 
> Can you please check/correct the wrong documentation?
> 
> PS.: i am on newest Windows 11 22H2
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: ae2608d3-38b8-2404-d138-1ba17772e72c
> * Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
> * Content: [Launch the default app for a URI - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#photos-app-uri-scheme)
> * Content Source: [uwp/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-default-app.md)
> * Product: **uwp**
> * Technology: **processes-and-threading**
> * GitHub Login: @alvinashcraft
> * Microsoft Alias: **aashcraft**

Have you sloved it?  I can make it
