### ISSUE TITLE
Activating toast notifications from desktop apps documentation is hard to understand

### ISSUE THREAD

**Issue by dgsasha** [MicrosoftDocs/windows-uwp#4409]
This might just be me, but I'm having a really hard time understanding the following paragraph.

> For packaged apps, just send toast notifications like a UWP app would. When the user clicks on your toast, your app will be command-line launched with the launch args that you specified in the toast.

This doesn't seem to work, is there any examples of this I can look at or anywhere else I can read more about it? I can send notifications just fine, but the app doesn't get launched when the buttons on the toast or the toast is clicked. I'm using 'foreground' activation type, and I'm creating the toast notifier for another app in the same package, using its AUMID . My app is written in python using the winsdk library, which I know isn't officially supported but I doubt this is an issue with the library. I know my app isn't really sending notifications in the ideal way, but I think this part of the documentation could be elaborated on some more. Also here's the xml I'm using to create the toast in case I'm doing something wrong there.

```python
xml_string = f'''
<toast
    duration="long"
    scenario="reminder"
    displayTimestamp="{self._timestamp_to_rfc(reminder['timestamp'])}"
    launch="--action=notification-clicked">
    <visual>
        <binding template="ToastGeneric">
            <text>{reminder['title']}</text>
            <text>{reminder['description']}</text>
        </binding>
    </visual>
    <actions>
        <action
            content="{COMPLETE_BTN_TEXT}"
            arguments="--action=reminder-completed --params={reminder_id}"
            activationType="foreground"/>
    </actions>
</toast>
'''
``` 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86f9e5c8-e788-3c78-ca66-720db63686eb
* Version Independent ID: 514bb56e-770c-7392-c1a6-0bd988679415
* Content: [Activating toast notifications from desktop apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-desktop-apps#alternative-option---no-com--stub-clsid)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/toast-desktop-apps.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/shell/tiles-and-notifications/toast-desktop-apps.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
