### ISSUE TITLE
Panasonic FZ F1 zxing camera not working once integrated barcode scanner(Point of service) started

### ISSUE THREAD

**Issue by abhinavsk90** [MicrosoftDocs/windows-uwp#441]
Hi,

I have a requirement of scanning barcode both through the camera as well as the integrated barcode. our current scenario is when we open the zxing camera and close it and then start the integrated barcode then zxing camera stops working.

I am using the sample of barcode scanner : https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BarcodeScanner

and zxing : https://github.com/Redth/ZXing.Net.Mobile/tree/master/Samples/WindowsUniversal/Sample.WindowsUniversal

Code: // after successful creation, claim the scanner for exclusive use and enable it so that data received events are received.
                claimedScanner = await scanner.ClaimScannerAsync();

after claimedScanner initialized, zxing camera is not opening. Seems POS is utilizing some camera resource which should not supposed to be as both are different units.

Same scenario is working as expected in Honeywell CT50. 

Please let us know if any solution .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a103dc81-d687-98bc-45fa-1e5641facee2
* Version Independent ID: 8dd905f2-f0de-4aab-63ae-d05f2ec7fec9
* Content: [POS device support - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-device-support#feedback)
* Content Source: [windows-apps-src/devices-sensors/pos-device-support.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/pos-device-support.md)
* Service: **unspecified**
* GitHub Login: @muhsinking
* Microsoft Alias: **jken**

**Comment by abhinavschneider** [comment]
@GrantMeStrength Do you have any update on this.

**Comment by GrantMeStrength** [comment]
I'm following up with the dev team.

**Comment by GrantMeStrength** [comment]
Good news: RS4 that will add camera barcode support to our stack and will eliminate the need to use ZXing separately.
 
As for the crash, we would need details about the issue.  Please publish the question to the UWP App Dev forum here:  https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=wpdevelop

**Comment by TerryWarwick** [comment]
@abhinavski90, the issue that you have encountered is unique to the Panasonic FZ-F1 mobile handheld device and its barcode scanner driver.  Please work with Panasonic on a resolution.

The support that has been built into Windows 10 Spring 2018 release for Camera Barcode Scanner supports Windows desktop platform.  Please refer to https://aka.ms/camerabarcode for additional information.

**Comment by GrantMeStrength** [comment]
I'm closing this issue. Feel free to reopen if you do not think it is resolved. Thanks!
