### ISSUE TITLE
There is no video link in the document

### ISSUE THREAD

**Issue by adolfdaniel** [MicrosoftDocs/windows-uwp#4410]
The document says to watch the video, but I couldn't find the link for the video to watch.

Section: https://learn.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#video
```
Watch the following video for an overview of how to implement in-app purchases in your app using the [Windows.Services.Store](https://learn.microsoft.com/en-us/uwp/api/windows.services.store) namespace.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45e80e2c-f648-2232-eda5-dbf60ed3c45f
* Version Independent ID: d3341110-0411-f7df-3191-a700d5a814f4
* Content: [In-app purchases and trials - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials?source=docs#video)
* Content Source: [uwp/monetize/in-app-purchases-and-trials.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/monetize/in-app-purchases-and-trials.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Thanks for bringing this to our attention. Unfortunately the video is now out of date and was removed. Until a new video has been  created, I'm going to remove this link. -John
