### ISSUE TITLE
With MS Store going away, how can we redirect url:ms-windows-store-deskext to Company Portal? 

### ISSUE THREAD

**Issue by kenheshka** [MicrosoftDocs/windows-uwp#4417]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8f30bb9-d11a-1865-2d17-9c56cfc3e641
* Version Independent ID: ded22236-86fd-f4eb-f517-f3dd1005dc98
* Content: [Using ms-windows-store URIs - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-store-app)
* Content Source: [uwp/launch-resume/launch-store-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/launch-resume/launch-store-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth your pursuing this as a question/feedback about the product. You got here by clicking **Send feedback about > This page** at the bottom of the documentation page. If instead you click **Send feedback about > This product**, then you'll be taken to the right channel to leave product questions/feedback.
