### ISSUE TITLE
Get HTTP 403 when using https://blogs.windows.com/feed/

### ISSUE THREAD

**Issue by yots** [MicrosoftDocs/windows-uwp#4418]
A Request to https://blogs.windows.com/feed/ is blocked by server with error code 403. This is unfortune when you just try to test if your rust setup is working and the copy/paste example is not working out of the box.

![Code_Hh8WtEK5kE](https://github.com/MicrosoftDocs/windows-dev-docs/assets/161147/588c39d5-7e34-4848-9e6d-d448073c2b23)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://learn.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @yots. I'm investigating. Meanwhile if you change the RSS url in the source code to `https://blog.rust-lang.org/feed.xml`, then that works.

-Steve

**Comment by stevewhims** [comment]
UPDATE: After a discussion internally, some folks showed me how to fix the code sample. So I've reverted the change above, and added some code to set a user-agent header (which is necessary for *some* RSS feeds). The code works now.

-Steve
