### ISSUE TITLE
A slight correction suggestion on Microsoft's Learn Page entitled "Get started with native Android development on Windows"

### ISSUE THREAD

**Issue by davidsiburian** [MicrosoftDocs/windows-uwp#4419]
[Enter feedback here]

Hello, I found a word that missed an 'e' letter on a word 'therefor' found in sentence "Lower API levels are older and therefore generally support more devices, but higher API levels are newer and therefor provide more features." in "Minimum API Level" subsection. Can you please fix it? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20bef3a8-5e79-dbac-4e45-f81ebf635d1a
* Version Independent ID: 9dae467e-4ba3-c30a-fe47-203a992838ff
* Content: [Native Android development on Windows](https://learn.microsoft.com/en-us/windows/android/native-android)
* Content Source: [hub/android/native-android.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/native-android.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Anglemmj7** [comment]
@microsoft-github-policy-service terminate
