### ISSUE TITLE
The PowerShell Command does not work in the latest version of PowerShell 

### ISSUE THREAD

**Issue by xuemind** [MicrosoftDocs/windows-uwp#4420]
Please update the instruction works in the latest PowerShell 7.3.4.

In PowerShell 7.3.4, the following error message when I executed the following commands. But they work correctly in old version of *Windows PowerShell"

```
❯ [Windows.Media.Ocr.OcrEngine, Windows.Foundation, ContentType = WindowsRuntime]
InvalidOperation: Unable to find type [Windows.Media.Ocr.OcrEngine,Windows.Foundation, ContentType=WindowsRuntime].
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Version Independent ID: 0badd1c2-7821-cc2f-cec0-9913a5e16eb1
* Content: [PowerToys Text Extractor utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/text-extractor#supported-languages)
* Content Source: [hub/powertoys/text-extractor.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by alvinashcraft** [comment]
The commands only work in Windows PowerShell. I just re-verified with the latest PowerShell 7.4.0 that they do not work there. The current documentation does state that Windows PowerShell must be used:

`# Please use Windows PowerShell, not PowerShell 7 as these aren't .NET Core libraries`
