### ISSUE TITLE
doc

### ISSUE THREAD

**Issue by Anglemmj7** [MicrosoftDocs/windows-uwp#4421]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68c07ba9-8f4f-c051-c945-16742c7fe409
* Version Independent ID: 61c4da19-8278-4764-05a4-000653932b83
* Content: [Provision Windows Device Portal with a custom SSL certificate - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-ssl)
* Content Source: [uwp/debug-test-perf/device-portal-ssl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/debug-test-perf/device-portal-ssl.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No Issue reported.
