### ISSUE TITLE
WinUI2 or WinUi3

### ISSUE THREAD

**Issue by PerArneS68** [MicrosoftDocs/windows-uwp#4428]
All namespaces and header files are ..."Windows...." which is typical for WinUI2 not "Microsoft...." which is typical for WinUI3, please be consistent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed1f2938-5c3d-4440-cd57-e16bb09ae56e
* Version Independent ID: 91e93356-de27-dfde-9508-3284ffdd4c69
* Content: [Draw shapes - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/controls/shapes)
* Content Source: [hub/apps/design/controls/shapes.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/controls/shapes.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This article has been corrected. Thanks.
