### ISSUE TITLE
Model converted from CoreML with winmltools cannot be loaded

### ISSUE THREAD

**Issue by BenPYeh** [MicrosoftDocs/windows-uwp#443]
Converted a model into onnx format from coreml that takes in an image, but this model cannot be loaded.

    return cntk_py.Function.load(str(model), device, format.value)
RuntimeError: Failed to load the model.

[CALL STACK]
    > CNTK::TrainingParameterSchedule<double>::  GetMinibatchSize
    - CNTK::  XavierInitializer
    - CNTK::Function::  Load
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyFunction_SetAnnotations
    - PyObject_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc (x2)

I think it's because the model does not have all four required dimensions, NCHW, just CHW. Is there a workaround for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c28f709-f39f-51e1-dbd6-049496ec9b8d
* Version Independent ID: b2a668cf-c3b8-2236-2f6c-0e876f4393a0
* Content: [Convert existing ML models to ONNX - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/conversion-samples)
* Content Source: [windows-apps-src/machine-learning/conversion-samples.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/conversion-samples.md)
* Service: **unspecified**
* GitHub Login: @wschin
* Microsoft Alias: **wechi**

**Comment by wschin** [comment]
Hello, is it possible for you to share your CoreML model with us? I don't quite understand what does "NCHW" and "CHW" means because neural networks  converted from CoreML may have a 4-D input dimension (if it's an image).

**Comment by ginami** [comment]
Closing this issue--let us know if you have further questions. Thank you!
