### ISSUE TITLE
Inclusion of Image compressor

### ISSUE THREAD

**Issue by Mxcoded** [MicrosoftDocs/windows-uwp#4430]
What if this can also include image compressor without lossing quality this will save a lot of space and it could encourage storing small image files in onedrive

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. First, this repository is about the documentation. Head over to https://github.com/microsoft/PowerToys/issues and look for an existing issue about this subject.

**Comment by alvinashcraft** [comment]
Hi @Mxcoded. Like @Jay-o-Way says, this feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
