### ISSUE TITLE
No consistent code examples. Some in C++, some in C#.

### ISSUE THREAD

**Issue by pbruins84** [MicrosoftDocs/windows-uwp#4431]
Some of the code examples on this page are only in C++, and some are only in C#. Why not both languages, like the rest of the examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0e5014-68c8-fb33-bf35-117c7b217c56
* Version Independent ID: 0c0e5014-68c8-fb33-bf35-117c7b217c56
* Content: [Quickstart App notifications in the Windows App SDK - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs)
* Content Source: [hub/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @vaheeshta
* Microsoft Alias: **vmehrshahi**

**Comment by vaheeshta** [comment]
@loneursid @drewbatgit

**Comment by drewbatgit** [comment]
@pbruins84 Thanks for the feedback, and I agree that this is an issue. We are currently working on re-creating this page entirely. The new page will have C# and C++ code sample tabs. It will also work standalone from empty project to working app rather than using snippets from the github code sample that don't work in isolation. This is part of a larger reorganization of the app notifications content, so I don't have an ETA for when these updates will be live. But they are in progress.

**Comment by johngagefaulkner** [comment]
> @pbruins84 Thanks for the feedback, and I agree that this is an issue. We are currently working on re-creating this page entirely. The new page will have C# and C++ code sample tabs. It will also work standalone from empty project to working app rather than using snippets from the github code sample that don't work in isolation. This is part of a larger reorganization of the app notifications content, so I don't have an ETA for when these updates will be live. But they are in progress.

This is great news! I can't tell you how many times I'd wanted to use sample code from either the WinUI 2 or WinUI 3 Gallery apps only to later find that I was missing a large amount of context and that code wouldn't actually function despite being advertised as a "copy-paste-go" solution.

**Comment by drewbatgit** [comment]
Sorry for the delay in getting these code samples updated. This is still planned work, but it has just been deprioritized against other work. It is planned to restart this effort in the coming months. As we transition to a new feedback system, we are closing all outstanding issues, but this issue will continue to be tracked internally.
