### ISSUE TITLE
Dev drive feature not available on build 23451

### ISSUE THREAD

**Issue by Lutra-Fs** [MicrosoftDocs/windows-uwp#4435]
Hi in https://learn.microsoft.com/en-US/windows/dev-drive/ It states that this feature requires Windows 11 dev channel. I am in dev channel build 23451, but I don't see any settings for dev drive. is that available now? if not, when will it be available?

**Comment by alexrp** [comment]
FWIW:

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/44076/1cc040c3-a590-48ac-b33a-d7cb62d0e83f)
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/44076/179350c1-89bd-4564-9776-a117eda0f4de)

**Comment by Lutra-Fs** [comment]
Seems like available later this week in the blog post?

**Comment by alexrp** [comment]
Good catch! I read about Dev Drive in the Build 2023 Book of News. Searching then led me to the docs here, which had no mention of the release timing.

**Comment by Lutra-Fs** [comment]
Closed, I think Microsoft publish the new one now
