### ISSUE TITLE
Improved PowerShell code to install Winget in Sandbox

### ISSUE THREAD

**Issue by MrDRamos** [MicrosoftDocs/windows-uwp#4436]
Improved sample PowerShell code to provide more feedback and install to temp file to temp folder:
<#>
.SYNOPSIS
Install winget on Windows Sandbox
Windows Sandbox provides a lightweight desktop environment to safely run applications in isolation.
Software installed inside the Windows Sandbox environment remains "sandboxed" and runs separately 
from the host machine. Windows Sandbox does not include winget, nor the Microsoft Store app, 
so you will need to download the latest winget package from the winget releases page on GitHub.

.NOTES
Ref: https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox
#>
function Install-WinGet()
{
    if (Get-Command 'winget.exe' -ErrorAction Ignore)
    {
        Write-Host "Winget is already installed"
        return
    }
    $progressPreference = 'silentlyContinue'
    $latestWingetMsixBundleUri = $(Invoke-RestMethod https://api.github.com/repos/microsoft/winget-cli/releases/latest).assets.browser_download_url | Where-Object {$_.EndsWith(".msixbundle")}
    $WingetPkgFile = "$Env:tmp\" + $latestWingetMsixBundleUri.Split("/")[-1]
    $VcLibsPkgFile = "$Env:tmp\" + 'Microsoft.VCLibs.x64.14.00.Desktop.appx'
    Write-Host "Downloading Winget to: $WingetPkgFile"
    Invoke-WebRequest -Uri $latestWingetMsixBundleUri -OutFile $WingetPkgFile
    Write-Host "Downloading VcLibs to: $VcLibsPkgFile"
    Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile $VcLibsPkgFile
    Write-Host "Installing VcLibs dependency"
    Add-AppxPackage $VcLibsPkgFile
    Write-Host "Installing Winget"
    Add-AppxPackage $WingetPkgFile
    Write-Host "Completed Winget install"
}

Install-WinGet

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
The install instructions for WinGet in Windows Sandbox are up-to-date with the latest versions included in the script thanks to this recent update: https://github.com/MicrosoftDocs/windows-dev-docs/commit/cac9dab23803c52be58476538dc44ea9d6cda031.
Resolving this issue. Thanks for filing.
