### ISSUE TITLE
Enabling winget configuration settings snippet is wrong

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/windows-uwp#4437]
The correct way to enable this feature as of right now is to add the following to the settings json of winget:

```
    "experimentalFeatures": {
        "configuration": true
    }
```

The docs however suggest adding the following which won't work:

```
"experimentalFeatures": {
       "WinGet configuration": true
   }
```

I would love to fix this but I can't seem to find the file for this page :/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Version Independent ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Content: [WinGet Configuration](https://learn.microsoft.com/en-us/windows/package-manager/configuration/)
* Content Source: [hub/package-manager/configuration/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/configuration/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Good catch! Thanks. Sorry you couldn't file a PR -- the repo wasn't synced briefly because we had so much content going out related to Build announcements. It's back to normal now though. I've got a fix in already for this and it should be live momentarily. Thanks again @chingucoding!

**Comment by marcelwgn** [comment]
Closing since this is fixed now.
