### ISSUE TITLE
Describe what ReFS settings are optimized

### ISSUE THREAD

**Issue by ecki** [MicrosoftDocs/windows-uwp#4438]
On this page it is mentioned ReFS is used for performance. But other than the trusted mode it does not mention any reasons for that claim. Is the ReFS of a devdrive tweaked with special parameters? I used ReFS before, will the performance (besides the filter excludes) be comparable?

> targeted file system optimizations

what are those?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **uwp**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @ecki -- Scott Hanselman has posted a video performance testing DevDrive that you may find helpful: https://www.youtube.com/watch?v=UW8yKWX8YAA&t=328s You can also find more info about how ReFS is optimized for performance at https://learn.microsoft.com/en-us/windows-server/storage/refs/refs-overview#performance

I don't currently see anything that requires a specific update to the Dev Drive docs, so am closing this issue, but if you have something specific that you'd like to see updated, please re-open.

Thanks!!

**Comment by ecki** [comment]
Well, I think it would still important to answer the following questions:

- is ReFS for small files faster than NTFS (no)
- Is the DevDrive Wizard creating filesystem parameters different from ReFs defaults (I think no)

I think also Scott’s test shown, that there is „only“ an advantage when defender is used (or other filters), the drive is trusted and async scanning on. That’s nice and all, but not what’s claimed in the doc.

my initial reason to search the docs was to find out if my older refs partition can be optimized with parameters, and the doc does not help me with that (in fact it unhelpful claims it can without giving details).

**Comment by Montago** [comment]
> I think also Scott’s test shown, that there is „only“ an advantage when defender is used (or other filters), the drive is trusted and async scanning on. That’s nice and all, but not what’s claimed in the doc.

I bet that 'disabling' defender (antivirus) on NTFS would have similar impact...

**Comment by ecki** [comment]
> I bet that 'disabling' defender (antivirus) on NTFS would have similar impact...

Agreed, I expect NTFS to be faster because less overhead.
