### ISSUE TITLE
Config sample is incorrect

### ISSUE THREAD

**Issue by chrisbues** [MicrosoftDocs/windows-uwp#4439]
This snippet:
"experimentalFeatures": {
       "WinGet configuration": true
   }

Should be:

"experimentalFeatures": {
       "configuration": true
   }

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Version Independent ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Content: [WinGet Configuration](https://learn.microsoft.com/en-us/windows/package-manager/configuration/#enable-the-winget-configuration-experimental-configuration-preview-feature)
* Content Source: [hub/package-manager/configuration/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/configuration/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by hoopsomuah** [comment]
See #4437

**Comment by mattwojo** [comment]
Looks like this issue has been resolved. Thanks for filing!
