### ISSUE TITLE
Pretty sure the JSON example showing how to enable the "configuration" experimental feature is incorrect

### ISSUE THREAD

**Issue by gregboyko** [MicrosoftDocs/windows-uwp#4440]
The example JSON currently reads says to add this to your winget settings configuraiton file:

"experimentalFeatures": {
       "WinGet configuration": true
   }

I believe the correct JSON to add is this:

"experimentalFeatures": {
       "configuration": true
   }

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Version Independent ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Content: [WinGet Configuration](https://learn.microsoft.com/en-us/windows/package-manager/configuration/#enable-the-winget-configuration-experimental-configuration-preview-feature)
* Content Source: [hub/package-manager/configuration/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/configuration/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by hoopsomuah** [comment]
I can confirm that this is correct. see: https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#configuration

**Comment by hoopsomuah** [comment]
Same as #4437
