### ISSUE TITLE
Change language in runtime on Windows App SDK

### ISSUE THREAD

**Issue by lucasvinicode** [MicrosoftDocs/windows-uwp#4445]
I need to change a language at runtime from the Resource.resw files, in the Windows App SDK, any examples?

**Comment by Karl-Bridge-Microsoft** [comment]
Without knowing what you've already browsed, you might want to start with https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest and look the various "resources" samples at https://learn.microsoft.com/en-us/samples/browse/?terms=resources&products=windows.
