### ISSUE TITLE
App Does Not Run When published as Self-contained

### ISSUE THREAD

**Issue by jimddavis** [MicrosoftDocs/windows-uwp#4448]
When published as a Self-contained with <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained> added to the project's properties, the app does not run.  The GetItemsAsync() method fails.

It would be nice if you could complete this example by showing how to publish it so it could be run on another computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial--Create a simple photo viewer with WinUI 3 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3?tabs=cs)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jimddavis, and thanks for filing this issue.

I took the C++ version of the simple photo viewer sample app from the topic, and then I followed along with the steps in [Windows App SDK deployment guide for self-contained apps](https://learn.microsoft.com/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps). There are more steps described there than setting WindowsAppSDKSelfContained; and there are different additional steps depending whether the app is C# or C++.

Having followed both topics, the app ran as expected. I'd suggest reviewing [Windows App SDK deployment guide for self-contained apps](https://learn.microsoft.com/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps) for all the details, and the links to the project and props files that show how to correctly configure a project for self-contained deployment.

Thanks!
-Steve
