### ISSUE TITLE
Dev Container cannot be opened from VSCode in Dev Drive

### ISSUE THREAD

**Issue by Mikoshiba-Kyu** [MicrosoftDocs/windows-uwp#4449]
In the project folder, there is a .devcontainer directory in which devcontainer.json is located.
When this project is opened in VSCode, it can be opened as a Container by the VSCode extension "Dev Containers".

Normally, it works fine, but when this project folder is placed in Dev Drive, the following error occurs and it does not work.

The error message displayed is as follows.
* The `h:\` directory in the error message is the Dev Drive I created.

```
Command failed:
C:\Users\xxxxxxxx\AppData\Local\Programs\Microsoft VS Code\Code.exe
--ms-enable-electron-run-as-node c:\Users\xxxxxxxx\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js up
--user-data-folder c:\Users\xxxxxxxx\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data
--container-session-data-folder /tmp/devcontainers-bccede9c-b094-4dc5-80bd-4a9e8b2f56961685063681615
--workspace-folder h:\devcontainer\test --workspace-mount-consistency cached
--id-label devcontainer.local_folder=h:\devcontainer\test
--id-label devcontainer.config_file=h:\devcontainer\test\.devcontainer\devcontainer.json
--log-level debug
--log-format json
--config h:\devcontainer\test\.devcontainer\devcontainer.json
--default-user-env-probe loginInteractiveShell
--mount type=volume,source=vscode,target=/vscode,external=true
--skip-post-create
--update-remote-user-uid-default on
--mount-workspace-git-root true
```

**Comment by vishalrajofficial** [comment]
Hi there! I'm in need of assistance with setting up the dev drive. Can you lend a hand?
My Telegram ID is @vishalraj4.
Looking forward to hearing from you soon. Thank you!

**Comment by Mikoshiba-Kyu** [comment]
Sorry. I opened the time and tried it and it works fine. I'm not sure what caused it.
