### ISSUE TITLE
nvs path is not persistent

### ISSUE THREAD

**Issue by kdpuvvadi** [MicrosoftDocs/windows-uwp#4452]
`nvs` for managing `node` versions sets the path of selected version but it's not persisting after shell closing or reopening. 

## Steps to reproduce:

- Installing `nvs`:  `winget install jasongin.nvs`
- Installing `node`: `nvs add 18.16.0`
- Using installed version: `nvs use 18.16.0`
- Check node version: `node --version`
- Restart the shell, check node version. Getting error

```
node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

## Fix 

To solve this issue while upstream  fix is being developed, add entry to the powershell profile

`nvs use node/16.20.0/x64`

We can add warning in the doc to warn the users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@denelon - Note for config
