### ISSUE TITLE
Event handler doesn't work

### ISSUE THREAD

**Issue by Shivam7-1** [MicrosoftDocs/windows-uwp#4454]
issue with this code https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/security/code/token-broker/MainPage.xaml.cs
Description: Currently, the code includes a `SignOutButton_Click` event handler, but it doesn't perform the sign-out functionality.

**Comment by alvinashcraft** [comment]
Merged the PR, and I'm creating a work item to update the sample to remove the use of RoamingSettings. Thanks for your contribution!
