### ISSUE TITLE
Prerequisite Visual Studio Version is incorrect.

### ISSUE THREAD

**Issue by scottparkes** [MicrosoftDocs/windows-uwp#4456]
Under Prerequisites the documentation states "Visual Studio 2017 or later".

I think this should be 2022 or later? 
- The prereqs state "Make sure to add the component for C++ (v143)" - this version is not available in the VS2019 installer.
- The steps require "set the target .NET version to 6.0" - this is not available in VS2019

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5a3713-5a3b-6cde-b947-cffc226ae1d2
* Version Independent ID: 2f5a3713-5a3b-6cde-b947-cffc226ae1d2
* Content: [Implement a widget provider in a C# Windows App - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-cs)
* Content Source: [hub/apps/develop/widgets/implement-widget-provider-cs.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/implement-widget-provider-cs.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I spoke with the feature team and while it theoretically is possible to get VS2019 set up to work with this feature, they agreed that the requirements should be updated to Visual Studio 2022 or later. Thanks for helping to improve the docs!
