### ISSUE TITLE
Dev drive prerequisites should list Hyper-V

### ISSUE THREAD

**Issue by Malfrador** [MicrosoftDocs/windows-uwp#4457]
Dev drives can only be created if the Hyper-V feature is installed and enabled. If Hyper-V is disabled, the Dev Drive and VHD options will not show up in the Settings app.
As such, Hyper-V should be listed in the documentation as a prerequisite. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **uwp**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @Malfrador - Thanks for filing this issue. I checked in with the dev team to be sure, but Hyper-V is *not* a requirement for creating a Dev Drive. I'm not sure what has happened in your use-case, but if you're able to experiment a bit more and share more details, I'm happy to look further into it with you. 
We confirmed that Dev Drives can be created on the Home version of Windows (which doesn't support Hyper-V) and spun up a VM, disabled Hyper-V in Settings, and were still able to create a Dev Drive... so I'm closing this issue as the team feels confident that this is not a prereq. Please feel welcome to reply with my details or reopen if you find that we're wrong about this. Thanks again, Matt

**Comment by mattwojo** [comment]
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/7566797/39b56162-849d-4d8e-8b3f-7f3a4c92b35b)

**Comment by Malfrador** [comment]
Hey @mattwojo and thanks for the quick reply. I just disabled Hyper-V as well, and my Dev Drive is still working fine and I can create new ones as well. So yeah, this can be closed.
I guess I experienced an issue similar to [this dev home one](https://github.com/microsoft/devhome/issues/933#issuecomment-1570912790), and my (second) reboot to enable Hyper-V also made the option show up despite it and Hyper-V being unrelated.

**Comment by mattwojo** [comment]
@Malfrador - Thanks for the follow up! I see Adam's post about this issue coming up during first logon, so glad to see the dev team is aware. I'm just the docs guy 😜, so any fixes are out of my hands, but it does raise the question of whether I should get something added about this in a note to save others any confusion. I'll check in with the dev team and get their thoughts. Thanks again.
