### ISSUE TITLE
cant read text in dark and high contrats mode

### ISSUE THREAD

**Issue by hlawal92** [MicrosoftDocs/windows-uwp#4461]
not sure why but cant read text in dark and high contrats mode on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @hlawal92 - Sorry you're having trouble reading text with these modes. I just checked on my machine and both dark mode and high contrast seem to be working fine. Could you please retry and share a screenshot if you're still experiencing issues? Is it only for this PowerRename page or are other learn.microsoft.com pages experiencing the same issue?

**Comment by mattwojo** [comment]
Closing pending any further info provided. Please feel welcome to re-open if you find that this issue continues and believe it to be an error of the system and not the local environment.
