### ISSUE TITLE
Use [include] in docs

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/windows-uwp#4465]
You guys should totally think about using `[!include ...]` in the markdown for things that are repeated through pages. For example the Examples / NextStepButton which opens WinUI 3 Gallery.

It would prevent mess-ups like this:
![Screenshot_20230530-180409.png](https://github.com/MicrosoftDocs/windows-dev-docs/assets/65828559/cbcc4495-7d22-4d86-896b-815caa83d1ad)

https://learn.microsoft.com/en-us/contribute/markdown-reference#included-markdown-files

**Comment by Jay-o-Way** [comment]
@Karl-Bridge-Microsoft and @jwmsft this is something mentioned and attempted in #3837
FYI @Court72

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @Jay-o-Way. We're definitely trying to incorporate includes wherever we can and as time/resources permit. Closing as no specific topics are identified.

**Comment by Jay-o-Way** [comment]
>  no specific topics are identified.

@Karl-Bridge-Microsoft I'm not sure I follow. Shown example would be a good thing to start with...
Actually, I've tried to, once in the past, when formatting /cleaning up the docs. So if you want (me) to work on this, let me know.
