### ISSUE TITLE
THE ÆŒint Root¬ 

### ISSUE THREAD

**Issue by RootOfJessey** [MicrosoftDocs/windows-uwp#447]
Emanual= God with you since 1981

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74326439-db5c-8033-995f-2c187328c50c
* Version Independent ID: f1ff558e-ff40-94ec-1a8f-a07da61366a1
* Content: [Create your app by reserving a name - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/create-your-app-by-reserving-a-name#create-your-app-by-reserving-a-new-name)
* Content Source: [windows-apps-src/publish/create-your-app-by-reserving-a-name.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-your-app-by-reserving-a-name.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @RootOfJessey. Please let us know if you have any feedback on our documentation. Thank you!
