### ISSUE TITLE
Where do you get the RESW files from

### ISSUE THREAD

**Issue by damichab** [MicrosoftDocs/windows-uwp#4477]
This page does not explain just WHERE to get the resw files from. When I add files I only get an option for resx files. 

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/6d324379-3278-4c47-a3d5-7d7070d1373c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f354ce8d-e4be-4974-eb8a-67d7a59efce4
* Version Independent ID: bf779ef7-e6de-fc16-5446-2e3581fdbaa4
* Content: [Localize strings in your UI and app package manifest - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#create-a-resources-file-resw-and-put-your-strings-in-it)
* Content Source: [uwp/app-resources/localize-strings-ui-manifest.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/app-resources/localize-strings-ui-manifest.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by damichab** [comment]
Also noting the following comment...

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/ac290d48-61ac-4154-b355-d7224a164fed)


I am using a custom system where I have all language strings in custom cs files and associated images in their own Resources.resx file. By testing the startup langage of the user, I load in the correct files and this is working rather well.

For this example, following the instructions here, I have set the installer Package.appxmanifest file to two languages (I am up to 84, but for this test, 2 seems more than appropiate)

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/5dd29f5d-aeff-442d-839d-607dd0d0937d)

In the AppPackages's bin folder, I see

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/46011707-4555-4b62-bd2a-9dea60bddfb4)

Compiling etc and then uploading it to the MS Partner Center, I see the following (ver 11.4..1.0 being the package in question)

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/1af76e97-60a3-479f-aeb2-76da5e1c9f7e)

As I see it from these instructions, I should be seeing both "English (United Kingdon)" which is there, as well as "Afrikaans" which is not.

At my wits end here.  Nothing seems to be working.

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/d4241773-c905-4e30-95c1-c100b33ffca7)

**Comment by damichab** [comment]
My appologies, the second comment was for this page...

https://learn.microsoft.com/en-us/windows/apps/design/globalizing/manage-language-and-region#app-manifest-language-list

**Comment by alvinashcraft** [comment]
Hi @damichab. Regarding your original question, you can add a RESW file by selecting Add-->New Item, choose `XAML` on the tree on the left, and you should see `Resources File (.resw)` in the list of items.

**Comment by alvinashcraft** [comment]
I updated the page to be more specific about how to create the .resw file. I also updated a similar WinUI/Windows App SDK page on localization. Those changes will be merged and live sometime today.

**Comment by alvinashcraft** [comment]
@damichab, regarding your second issue in the comments... Can you verify the contents of the AppxManifest.xml file that is generated in the build output? According to the docs, these contents should match what languages are seen in the Store. Maybe this isn't matching the Package.appxmanifest for some reason.

**Comment by damichab** [comment]
Hi @alvinashcraft I have since discovered that I can right click on the UWP Installer project to creat the resw file the cut/paste to my C# project. Maybe because I am using win forms that is why I am not seeing it for the project. 

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/9f9fce21-8310-4f75-867b-a5c6fb415607)

I did match the resw files, at least the two test files I ended up creating (en.gb and af) - still nothing.  

I have removed the test resw files and back to using just the resx files. I have just run a couple of tests, this being the code used...

Package.appxmifest:

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/4aeab27e-bb1b-45a0-b516-d22edd579fab)

AppxManifest.xml:
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/8154a238-d37c-486c-b809-9dd5fba0ef0e)

resx files used:
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/91f08067-91b0-4707-ba16-7797bb630216)

MS Partner results once uploading the package to store (pretty much the same results as when I was testing with resw files):
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/46388020/5a27fd99-dfc9-447a-a7b0-d4d32782b993)




Some quick questions if I may...

My reading of the instructions, if you use language codes in Package.appxmainifest (as opposed to `<Resource Language="x-generate" />`), my take on the written instructions is that you do not need resource files at all for languages to appear in the store.  This would be considered a "Custom build". Is this right?

Notwithstanding first question, is there something magical about resw files that work in showing store languages that is simply ignored with resx files? Do you have to use resw files?

For what it is worth, my resx files are full of language specific pictures and a single language specific string - all used. 


I thank you for your time - much appreciated.

**Comment by damichab** [comment]
the bracketed (as opposed to ...) was supposed to also contain Resource Language=`<Resource Language="x-generate" />
`

It was auto-taken out!!

**Comment by alvinashcraft** [comment]
Hi @damichab. The format of resx files and resw files is identical. The one difference is that resw files only support strings and file paths. You can't embed binaries (like images) into the resource file. So, I think using resx should be fine because you're seeing the output you're expecting for each language.

I think if you leave `<Resource Language="x-generate" />` in the Package.appmanifest, it should create your language specific output based on which resource files are present in your project. That is the behavior I saw when I ported this UWP documentation to Windows App SDK/WinUI.

For your issue with the Store, I think it might be a good idea to engage the support folks over in the forums.  The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding the Store and UWP packaging. If you do create a thread over at Microsoft Q&A, I would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. If they do indicate that one of the steps here should be different, we'll get the docs updated. Thanks!

**Comment by damichab** [comment]
Hi @alvinashcraft. 

Appologies for the late response. I have asked the question on the Microsoft Q&A you suggested...

[https://learn.microsoft.com/en-us/answers/questions/1316336/languages-not-registering-as-languages-supported-i](https://learn.microsoft.com/en-us/answers/questions/1316336/languages-not-registering-as-languages-supported-i)

Cheers,
David.
