### ISSUE TITLE
Dev Disk

### ISSUE THREAD

**Issue by DH-Zhang769** [MicrosoftDocs/windows-uwp#4479]
Hello, dear developers.I would like to know what is the difference between Dev Disk and mounting VHD files with other software.

**Comment by mattwojo** [comment]
Hi @DH-Zhang769 - The issues filed in this repo pertain to specific documentation updates or corrections. Closing as it sounds like this does not require an update to the docs. You can learn all about what Dev Drive has to offer here: https://learn.microsoft.com/windows/dev-drive/ or via this presentation at Build: https://www.youtube.com/watch?v=NrAoYfGQAwI&t=516s
