### ISSUE TITLE
can not access certain websites

### ISSUE THREAD

**Issue by chequered** [MicrosoftDocs/windows-uwp#448]
when I try to play msp or roblox on bing it gave me an error saying "INET_E_RESOURCE_NOT_FOUND". And I find it very weird because ive  never experienced this up until a few weeks ago, and also when I go on any other browser it says "DNS_PROBE_FINISHED_NXDOMAIN". Another weird thing is that I only have this problem on my computer and all the other computers ive used had no problem at all. I tried doing solutions that are on the internet and it just doesn't work, as if it cant be fixed in any way but I know there's a solution somewhere. I tried contacting the msp game and they had no clue what was going on. I tried flushing my dns server, tried doing the "88888844" solution and the list goes on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443bc235-c1bd-4f01-f758-14575db6dbb6
* Version Independent ID: 9b2b7af4-870a-d423-f0d7-2f7a680d38cc
* Content: [Launch Feedback Hub from your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/launch-feedback-hub-from-your-app#feedback)
* Content Source: [windows-apps-src/monetize/launch-feedback-hub-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/launch-feedback-hub-from-your-app.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Hello - I'm sorry you're encountering an issue, but the problem you're investigating appears to be unrelated to this documentation article. Please see [https://developer.microsoft.com/en-us/windows/support](https://developer.microsoft.com/en-us/windows/support) to review your support options and a list of forums where you might be able to get assistance.
