### ISSUE TITLE
RE: Assigning keys based on which keyboard is used, possible direction to look into.

### ISSUE THREAD

**Issue by Sorjal** [MicrosoftDocs/windows-uwp#4481]
While I'm not sure if this will provide a possible solution to developing this or not, I figured it best to leave it here just in case. Razer's Synapse software (currently Synapse 3) essentially does this function. Without Synapse running, their game keypad's keys are assigned default values with what appears to be a default keyboard driver. Once the program is running, those keys can be remapped to other assignments while the keyboard's keys remain untouched. This may be an instance of the program using both the key pressed and the device that key was pressed on. This may not be the case at all, but in case it is I hope this helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager#keys-that-cannot-be-remapped)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @Sorjal - Thanks for filing this issue, but this is not the right place as the focus of this repo is specific docs updates. Could you please re-file on the PowerToys product repo? There's a few issues already open related to Razer's Synapse, so may be worth a quick look to see if it makes sense to add to an existing or open something new: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+Synapse+

Thanks again!
