### ISSUE TITLE
This page gave a great overview of PowerToys

### ISSUE THREAD

**Issue by jtooker** [MicrosoftDocs/windows-uwp#4485]
This page gave a great overview of what PowerToys can do.  The video was especially helpful as a companion to the page itself.

(This is not an issue - just positive feedback).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06e00ed6-a50f-1bf1-af7b-81879cb0338e
* Version Independent ID: 7209e902-f8ec-2f25-a0e5-d557e6e18687
* Content: [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/)
* Content Source: [hub/powertoys/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/index.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Glad you found it helpful!
