### ISSUE TITLE
Keys Remap Issue

### ISSUE THREAD

**Issue by folliejester** [MicrosoftDocs/windows-uwp#4486]
i used power toys to change my keyboard layout from qwerty to azerty. and now xbox gamebar chat in overlay doesnt respond when i type a z q w keys.

**Comment by mattwojo** [comment]
Thanks for filing this issue @folliejester . This particular repo is only for issues with the documentation, however. For a feature update issue like this, please use the PowerToys product repo. It looks like there are already some related issues open... here's a link: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+xbox+gamebar
