### ISSUE TITLE
XAML is Misspelled

### ISSUE THREAD

**Issue by TheFanatr** [MicrosoftDocs/windows-uwp#449]
Just above [this section](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal#full-template-example), `XAML` is misspelled as `XAMl`. Just CTRL-F `XAMl` with match case on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f69aa0-1dbc-0506-638e-96e3fae70969
* Version Independent ID: 0e55a6a7-d379-868e-4858-20a779524b46
* Content: [Reveal highlight - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal#full-template-example)
* Content Source: [windows-apps-src/design/style/reveal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/reveal.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thank you! I checked in a fix; it'll go live with our RS4 docs.

**Comment by jeanmarc3** [comment]
It all works great on desktop, but not quite for mobile... Testing with emulator "Mobile Emulator 10.0.15063.0 WVGA 4 inch 512MB", my app crashes with error:

"Exception	{Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.
Cannot find a Resource with the Name/Key ButtonRevealBackground [Line: 18 Position: 37]}	System.Exception {Windows.UI.Xaml.Markup.XamlParseException}"

Any pointers on how to address this?  If reveal requires a higher target version, how do you handle styles with different versions?  Thx

**Comment by mijacobs** [comment]
Thanks for reaching out! Please check out our article on Conditional XAML: https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-XAML

**Comment by jeanmarc3** [comment]
Thanks for the quick response Mike.  I am sure this would work, but I have opted to drop Mobile support for the time being.  Reason being there is apparently no mobile emulator for Windows 10 build 16299 or later.  I hope Microsoft will either come back to mobile, or make x86 or x64 work on the new devices (like Andromeda?)
