### ISSUE TITLE
Mouse Jump Documentation

### ISSUE THREAD

**Issue by MeekMark** [MicrosoftDocs/windows-uwp#4494]
On the Mouse Jump documentation web page https://learn.microsoft.com/en-us/windows/powertoys/mouse-utilities, there is just a GIF image, but no description of ... how to make the Mouse Jump.  And in the Power Toys Settings, there is just an enable/disable toggle, and ability to change the Activation shortcut.

I have 3 monitors so seems like this could be handy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba175f26-82e2-2f00-7562-924faa57c143
* Version Independent ID: ba175f26-82e2-2f00-7562-924faa57c143
* Content: [PowerToys Mouse utilities for Windows](https://learn.microsoft.com/en-us/windows/powertoys/mouse-utilities)
* Content Source: [hub/powertoys/mouse-utilities.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/mouse-utilities.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
There's some text now?

**Comment by MeekMark** [comment]
Okay, there is a brief description and a GIF.  My confusion was that my PC eats up the "Windows" key, and so with the default activation shortcut, the Mouse Jump didn't activate.  Once I set the shortcut to Alt-Shift-H, it became obvious how to use it!  Thanks.
