### ISSUE TITLE
500 error fetching subscriptions that should maybe be a different error code

### ISSUE THREAD

**Issue by pnico** [MicrosoftDocs/windows-uwp#4495]
Normally when a service returns a 500 error we backoff and retry, but this one seems to happen every time with certain purchase ids, so maybe it should really be a 404 or similar instead (sorry I had trouble formatting this as it contains invalid escape sequences):

{"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown internal server error: System.NullReferenceException: Object reference not set to an instance of an object.\\\\   at Microsoft.MarketplaceServices.PurchaseService.PurchaseFD.Controllers.V8.B2BRecurrenceControllerV8.PostRecurrenceQueryAsyncInternal(B2BRecurrenceQueryRequestV8 request) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Controllers\\V8\\B2BRecurrenceControllerV8.cs:line 129\\\\   at Microsoft.MarketplaceServices.PurchaseService.PurchaseFD.Controllers.V8.B2BRecurrenceControllerV8.PostRecurrenceQueryAsync(B2BRecurrenceQueryRequestV8 request) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Controllers\\V8\\B2BRecurrenceControllerV8.cs:line 120\\\\   at lambda_method558(Closure , Object )\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\\\\--- End of stack trace from previous location ---\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\\\\--- End of stack trace from previous location ---\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\\\\   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\\\\   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\\\\   at Microsoft.MarketplaceServices.PurchaseServiceFD.Middleware.GLSBasedReverseProxyMiddleware.InvokeAsync(HttpContext httpContext) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Middleware\\GLSBasedReverseProxyMiddleware.cs:line 215\\\\   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\\\\   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\\\\   at Microsoft.MarketplaceServices.PurchaseService.ToolboxAuthorizationMiddleware.InvokeAsync(HttpContext context) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Middleware\\ToolboxAuthorizationMiddleware.cs:line 49\\\\   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\\\\   at Microsoft.MarketplaceServices.PurchaseService.LoggingContextBaggageMiddleware.Invoke(HttpContext context) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Middleware\\LoggingContextBaggageMiddleware.cs:line 37\\\\   at Microsoft.MarketplaceServicesCore.ServiceCore.TestHeaderMiddleware.InvokeAsync(HttpContext context)\\\\   at Microsoft.MarketplaceServices.PurchaseService.PurchaseTestHeaderMiddleware.InvokeAsync(HttpContext context) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Middleware\\PurchaseTestHeaderMiddleware.cs:line 119\\\\   at Microsoft.MarketplaceServicesCore.ServiceCore.ConnectionDrainingMiddleware.InvokeAsync(HttpContext context)\\\\   at Microsoft.MarketplaceServices.PurchaseService.OperationMetadataMiddleware.Invoke(HttpContext context) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Middleware\\OperationMetadataMiddleware.cs:line 115\\\\   at Microsoft.MarketplaceServices.PurchaseService.Startup.PurchaseServiceBootStrapper.<>c.<<AddAdditionalHostConfiguration>b__5_2>d.MoveNext() in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Startup\\PurchaseServiceBootStrapper.cs:line 162\\\\--- End of stack trace from previous location ---\\\\   at Microsoft.MarketplaceServicesCore.ServiceCore.InstrumentationMiddleware.InvokeAsync(HttpContext context)\\\\   at Microsoft.MarketplaceServices.PurchaseService.UnhandledExceptionConversionMiddleware.InvokeAsync(HttpContext context) in C:\\__w\\1\\s\\Purchase\\src\\PurchaseServiceFD\\Middleware\\UnhandledExceptionConversionMiddleware.cs:line 59"},"message":"An internal server error occurred while processing the operation.","source":"PurchaseFD"}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9625f407-7adf-256d-fa24-2d96c7c86f51
* Version Independent ID: 07159310-27c7-3eb2-761f-42798740c9a1
* Content: [Get subscriptions for a user - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/monetize/get-subscriptions-for-a-user)
* Content Source: [uwp/monetize/get-subscriptions-for-a-user.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/monetize/get-subscriptions-for-a-user.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
