### ISSUE TITLE
Updating ActiveCodePage documentation to reflect GDI doesn't support it at the moment

### ISSUE THREAD

**Issue by shiyaoll** [MicrosoftDocs/windows-uwp#4496]
Hi team,

We would like to inform customers that GDI currently doesn’t support ActiveCodePage, we propose adding the text to the location as following:
Adding text as a Note under https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#set-a-process-code-page-to-utf-8 at the end of the section.
And text content as below:
GDI doesn’t currently provide support for per process ActiveCodePage, instead GDI will default to the active system codepage. In order for customer apps to render UTF-8 text via GDI, go to Region – Administrative – Change system locale – Region Settings. And check “Beta: Use Unicode UTF-8 for worldwide language support”. Customer
will need to reboot the machine for the changes to take effect.

**Comment by stevewhims** [comment]
Thanks, @shiyaoll. I'm investigating. Btw, it sounds like you're in the GDI product team, is that correct?

-Steve

**Comment by shiyaoll** [comment]
Hi Steve, yes, I'm from the GRFX team working on GDI and related stuff. There is an existing email thread on this and I've just cc'd you.

Thanks,
Shiyao

**Comment by shiyaoll** [comment]
Communicated offline with Steve. The doc has been updated and everything looks good. Closing issue.
Thanks so much for the help!

**Comment by nmoreaud** [comment]
@shiyaoll Do you know if GDI support for ActiveCodePage is planned?
Does GDI+ or Direct2D work better with UTF-8?

**Comment by NicolasM-Forsk** [comment]
@shiyaoll Is there any update on this subject?

**Comment by NicolasM-Forsk** [comment]
@shiyaoll Is there any update on this subject?

**Comment by nmoreaud** [comment]
@shiyaoll Is there any update on this subject?
