### ISSUE TITLE
Link to WinUI website links back to the documentation

### ISSUE THREAD

**Issue by Vivelin** [MicrosoftDocs/windows-uwp#4497]
> Website: The [WinUI website](https://aka.ms/winui) has product comparisons, explains the various advantages of WinUI, and provides ways to stay engaged with the product and the product team.

In this paragraph, the link titled 'WinUI website' links to https://aka.ms/winui, which in turn links back to the docs page I was on. I imagine it is supposed to link elsewhere, maybe <https://microsoft.github.io/microsoft-ui-xaml/>?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49f58672-73e9-87bb-d7f0-8d67b6878e20
* Version Independent ID: 94fc53da-622a-93c8-a4c8-4faaf7e442b8
* Content: [Windows UI Library (WinUI) 3 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/)
* Content Source: [hub/apps/winui/winui3/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/index.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! This should be fixed now.
