### ISSUE TITLE
Where is documents for .NET 6 and WPF with WinUI 3?

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/windows-uwp#4499]
ITNOA

as you says in https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32 

> The set of WPF and WinForms controls found here are only designed to work with .NET Core 3.1, not .NET 5 and above. These controls are using the XAML Islands Windows 10 APIs included within the Windows 10 OS which won't be improved anymore.

> WinUI 3's XAML Islands is the path forward to these .NET apps that want to use .NET 5 and WinUI. WinUI 3's XAML Islands are still in development, and we recommend reviewing the [WinUI 3 roadmap](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) to get the latest updates. This repository will be archived once WinUI 3's XAML Islands is released.

But in your documents we cannot find any documentation about WinUI 3 XAML Islands, where is this documents? please add links to this documents

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d29a354-62d8-f881-7338-71a2fe60644e
* Version Independent ID: 234b48b4-9c6c-db8b-626c-0bd98d7a63a7
* Content: [Host WinRT XAML controls in desktop apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands)
* Content Source: [hub/apps/desktop/modernize/xaml-islands.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/xaml-islands.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by alvinashcraft** [comment]
Hi @soroshsabz. Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Our documentation covers Windows developer features and APIs that have been released. The XAML Islands feature for WinUI 3 has not been released yet, and there is no current estimate for when it will be available. When this feature becomes available, we will have documentation ready for Windows developers to use. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!

**Comment by soroshsabz** [comment]
@alvinashcraft But as you can see in https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md

Microsoft says `XAML Islands` available for WinUI 3 as as experimental feature from Windows App SDK 0.8
(June 2021)

**Comment by alvinashcraft** [comment]
Thanks, @soroshsabz. We don't document Windows App SDK experimental features on Microsoft Learn docs. Once this feature is part of a stable release, we will have the documentation to go with the feature.
