### ISSUE TITLE
Combining with elements in other namespaces

### ISSUE THREAD

**Issue by BioTurboNick** [MicrosoftDocs/windows-uwp#450]
How does this syntax work with elements in other namespaces? For example, I have a Behavior that hooks an event that is not defined in API version < 5. The behavior object itself is defined in a namespace. e.g. icore:EventTriggerBehavior. Is it possible to combine these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4adf9e3-46b9-732a-7659-07d34a9ff469
* Version Independent ID: 0dd55994-fed9-6d25-38c8-85e1ee2322ff
* Content: [Conditional XAML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml#use-ifelse-conditions)
* Content Source: [windows-apps-src/debug-test-perf/conditional-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/conditional-xaml.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MrCSharp22** [comment]
Here is how I managed to do it with my UserControl:
The control was in namespace: ```Holla.Controls```
the conditional XAML namespace is: ```xmlns:contractLevel5NotPresent="using:Holla.Controls?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 5)"```

This will make Visual Studio complain about the format but it works as expected.

Hope this helps
