### ISSUE TITLE
Allow File Locksmith being selected from new Windows 11 context menu

### ISSUE THREAD

**Issue by akamienski** [MicrosoftDocs/windows-uwp#4502]
PowerToys is a very useful toolkit to have, especially with PowerRename and File Locksmith, yet first one can be selected from old and new context menu of W11, but latter only in old one. Why not both for File Locksmith as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Version Independent ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Content: [PowerToys File Locksmith utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith)
* Content Source: [hub/powertoys/file-locksmith.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-locksmith.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right channel to get an answer to your question. The community of experts and Microsoft Engineers over in the [PowerToys repository](https://github.com/microsoft/PowerToys/issues) can handle any product-specific feedback or issues.

If you do create an over there, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation if changes are made. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by akamienski** [comment]
[link](https://github.com/microsoft/PowerToys/issues/27441)
