### ISSUE TITLE
Export/Import WinGet - outdated schema link

### ISSUE THREAD

**Issue by dylmye** [MicrosoftDocs/windows-uwp#4504]
Both the export command and import command page link to outdated versions of the JSON Schema for the import file in the section titled "JSON Schema":

https://aka.ms/winget-packages.schema.1.0.json
It should link to https://aka.ms/winget-packages.schema.2.0.json

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f80382c-4258-8725-6c9c-3e7b8aba3231
* Version Independent ID: 2db8e29c-7359-fa4e-3713-74a66aff169b
* Content: [export Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/export)
* Content Source: [hub/package-manager/winget/export.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/export.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Thanks for filing this issue @dylmye. The export doc points to https://github.com/microsoft/winget-cli/tree/master/schemas/JSON/packages. I chose this link so that the user could choose which schema version they want. I updated the import doc as well.
