### ISSUE TITLE
distinguish devices

### ISSUE THREAD

**Issue by mkq** [MicrosoftDocs/windows-uwp#4505]
[Enter feedback here]
> We are not aware of an API where we can see the input and which device it came from.

[LuaMacros](https://github.com/me2d13/luamacros) is somehow able to do that. Its predecessor [HidMacros](https://github.com/me2d13/hidmacros), too, if I recall correctly.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
Ping @crutkas ?

**Comment by Jay-o-Way** [comment]
Ping @crutkas ?

**Comment by crutkas** [comment]
Close as not a doc issue

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.

**Comment by mkq** [comment]
There is already a PowerToys issue https://github.com/microsoft/PowerToys/issues/1460 (which also mentions LuaMacros).

But IMHO this is still a documentation issue: "We are not aware of an **API** where we can see the input and which device it came from" (emphasis mine) may be right. But 1460 shows that PowerToys devs are aware of a way (maybe hack? I haven't read much of that PowerToys issue).

The average user probably doesn't know or care whether PowerToys achieves something via a proper API or otherwise. It would be more useful for the docs to reference and summarize the state of 1460.
