### ISSUE TITLE
keyboard key binds

### ISSUE THREAD

**Issue by purpley8** [MicrosoftDocs/windows-uwp#4506]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f358aa09-2544-b312-d819-ef7006b30e6f
* Version Independent ID: 26a38565-5fa5-8867-4eb6-c7c8a7293b47
* Content: [Moving from Mac (Unix) to Windows](https://learn.microsoft.com/en-us/windows/dev-environment/mac-to-windows#keyboard-shortcuts)
* Content Source: [hub/dev-environment/mac-to-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/mac-to-windows.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
I'll need more details about this issue and whether it requires any documentation updates. Closing, but please feel welcome to reopen and add more details if you feel an update to this doc is needed.
