### ISSUE TITLE
Peek is causing Explorer.exe to hang and become unresponsive.

### ISSUE THREAD

**Issue by bandaid** [MicrosoftDocs/windows-uwp#4508]
Peek is causing Explorer.exe to hang and become unresponsive. 

Disabling Peek resolves the issue.

Edition	Windows 10 Home
Version	22H2
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

Power Toys
0.70.1

**Comment by mattwojo** [comment]
Thanks for filing this issue @bandaid. This particular repo is only for issues with the documentation, however. For a product bug  like this, please use the PowerToys product repo. Here's a link: https://github.com/microsoft/PowerToys/issues/new/choose

**Comment by bandaid** [comment]
Interesting. I have no idea how this got posted here. Maybe misclicked a link.
