### ISSUE TITLE
Code sample for adding <Extensions> doesn't show where to add that

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/windows-uwp#451]
In the section for adding the extension to the app manifest, the docs say "Find the Extension element that defines the project as an app service and names its parent project."

However, a brand new app with a fresh app manifest does NOT have an `<Extensions`> element! So the docs don't tell you where to actually put it.

Additionally, after you discover on your own that it goes inside the `<Application>` element, you then discover that the `uap3` namespace isn't defined, so you have to find out how to define that yourself too!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065ca9c3-23b0-73c5-7708-a5d89362b4df
* Version Independent ID: a77a93f6-4c57-795e-fff8-5f26aadd8905
* Content: [Communicate with a remote app service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/communicate-with-a-remote-app-service)
* Content Source: [windows-apps-src/launch-resume/communicate-with-a-remote-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/communicate-with-a-remote-app-service.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Hi anbare, 
Thank you for your feedback, I've updated the docs to better cover the brand-new-app scenario.
