### ISSUE TITLE
Default Browser Bookmarks to Show up on PowerToys Run

### ISSUE THREAD

**Issue by Handarand** [MicrosoftDocs/windows-uwp#4512]
PT Run is awesome! But another functionality that it's lacking is being able to search through your default browser's bookmarks. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b951899-69ca-9057-f799-14491e1b0a74
* Version Independent ID: 18e0202f-3e91-a5b9-62f2-6cd40e5661a8
* Content: [PowerToys Run utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/run)
* Content Source: [hub/powertoys/run.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing this issue @Handarand. This particular repo is only for issues with the documentation, however. For a feature update suggestion like this, please use the PowerToys product repo. It looks like there are already several related issues open... here's a link: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+run+bookmarks
