### ISSUE TITLE
Build XAML controls with C# Documentation doesn't use static Dependency Property

### ISSUE THREAD

**Issue by larezelliot** [MicrosoftDocs/windows-uwp#4514]
In the [documentation example](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-csharp-winui-3), the DependencyProperty used is not declared as static. I was having TemplateBinding errors where the data was not properly bound to the custom control. 

I solved it by making the Dependency Property static. Following what I saw in the [Dependency Property Documentation](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyproperty?view=winrt-22621) "You should expose this object as an accessible static read-only property in your class"

It would be nice to update the documentation so it shows that the Dependency Property is static in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c44686a3-a403-405b-9539-e1f0339f147d
* Version Independent ID: 8ba10426-a5e6-5c41-61ef-12afda831883
* Content: [Build XAML controls with C# - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-csharp-winui-3)
* Content Source: [hub/apps/winui/winui3/xaml-templated-controls-csharp-winui-3.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/xaml-templated-controls-csharp-winui-3.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this. The example code has been updated.
