### ISSUE TITLE
Can I do this without using the Microsoft Store

### ISSUE THREAD

**Issue by SkipPerkins** [MicrosoftDocs/windows-uwp#4516]
I appreciate the person who wrote this, but is there a way to do this without using the Microsoft store? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by denelon** [comment]
@SkipPerkins there are a few ways to do this, but there are several caveats. We do have https://aka.ms/getwinget pointing to the latest stable release, and we have https://aka.ms/getwingetpreview pointing to the latest preview release. These both should work when the Microsoft Store is available, but without the licensing service one would also need the license file. We do have one available at the GitHub releases page. 

There are also the dependencies on the VC Runtime and UI.Xaml for the App Installer (this is how WinGet is distributed). You could try the preview PowerShell cmdlet Repair-WinGetPackageManager inside the Microsoft.WinGet.Client preview module.

**Comment by mattwojo** [comment]
Currently this issue does not require an update to the WinGet docs, so closing. For further discussion on manually installing Windows Package Manager apart from Microsoft Store, please see https://github.com/microsoft/winget-cli/issues.
