### ISSUE TITLE
Always on screen "Run Utility" Suggestion

### ISSUE THREAD

**Issue by Elvensbane** [MicrosoftDocs/windows-uwp#4519]
It would be nice to get a feature to keep this search bar always available on the desktop. It's incredibly useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b951899-69ca-9057-f799-14491e1b0a74
* Version Independent ID: 18e0202f-3e91-a5b9-62f2-6cd40e5661a8
* Content: [PowerToys Run utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/run)
* Content Source: [hub/powertoys/run.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather feedback about the product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth your time pursuing this as a feature suggestion for the product. You can do this by visiting the [PowerToys product repository](https://github.com/microsoft/PowerToys/issues) to leave product questions/feedback as a new issue. Thanks you!
