### ISSUE TITLE
winget GitHub link is broker

### ISSUE THREAD

**Issue by hdouglassjr** [MicrosoftDocs/windows-uwp#4524]
[WinGet Configuration repo on GitHub](https://github.com/Microsoft/winget-dsc). link is broken on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Version Independent ID: e0e0aecd-b61c-26ae-9bfb-24606f41e9da
* Content: [WinGet Configuration](https://learn.microsoft.com/en-us/windows/package-manager/configuration/)
* Content Source: [hub/package-manager/configuration/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/configuration/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Got the link updated. Thanks for bringing this to my attention @hdouglassjr! New link should be live in the next ~15 min.
