### ISSUE TITLE
fuck u github

### ISSUE THREAD

**Issue by BenyaminBarany** [MicrosoftDocs/windows-uwp#4525]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: decc7cd4-b6e8-8b96-aabf-381edea0c61f
* Version Independent ID: db5d2cb5-0caa-c87d-a738-702302171d0d
* Content: [Install JavaScript frameworks on Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/)
* Content Source: [hub/dev-environment/javascript/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/index.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by BenyaminBarany** [comment]
fuck u github fuck u just that

**Comment by BenyaminBarany** [comment]
finaly sonthing worked here great, now fuck you more github

**Comment by Karl-Bridge-Microsoft** [comment]
no issue reported
