### ISSUE TITLE
1.4 preview 1 release notes missing critical info

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#4527]
Please update the release notes to include actual information about the new features, instead of just a list of new API members. Usually you describe new functional areas in the release notes beyond just the API list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65803f08-867d-f4f8-0d32-53217e8640fa
* Version Independent ID: f0a73317-3de2-aa13-e0a8-0517a4ca52be
* Content: [Preview release channel for the Windows App SDK - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#version-14-preview-1-140-preview1)
* Content Source: [hub/apps/windows-app-sdk/preview-channel.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/preview-channel.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@duncanmacmichael, can you help with this?

**Comment by duncanmacmichael** [comment]
Yes, of course. Thanks for the feedback, @dotMorten. I'm working on getting that info right now and will update the docs as soon as I have it.

**Comment by duncanmacmichael** [comment]
Thanks for your patience @dotMorten. The release notes have been updated to be more descriptive of what's new in the 1.4-preview1 release: https://aka.ms/windowsappsdk/1.4/1.4-preview1/release-notes

**Comment by Karl-Bridge-Microsoft** [comment]
@dotMorten - closing issue as feature team has addressed the issue.
