### ISSUE TITLE
can't opt back in to subsystem for android insider after previously having opted out!

### ISSUE THREAD

**Issue by haniobaid** [MicrosoftDocs/windows-uwp#4528]
I had previously opted in then out of the subsystem for android insider track (there was an issue I couldn't resolve), and unfortunately now that I want to opt in again (I found the solution to that issue), it looks like the previous opt out is overriding the new opt in request.

Is there any way to remove the opt out?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e611135-e472-e8a7-a048-7dd38e0f7a6a
* Version Independent ID: 9e611135-e472-e8a7-a048-7dd38e0f7a6a
* Content: [Windows Subsystem for Android™️ Preview Program](https://learn.microsoft.com/en-us/windows/android/wsa/preview-program)
* Content Source: [hub/android/wsa/preview-program.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/preview-program.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @hamza-usmani
* Microsoft Alias: **mousma**

**Comment by mattwojo** [comment]
Unfortunately, Microsoft is ending support for the Windows Subsystem for Android program. See the announcement in the doc here: https://learn.microsoft.com/windows/android/wsa/
