### ISSUE TITLE
Is this page "Install React directly on Windows" or "Install React directly in WSL"?

### ISSUE THREAD

**Issue by vikumbha-outlook** [MicrosoftDocs/windows-uwp#4529]
[Enter feedback here]

Although the page title is "Install React directly on Windows" Prerequisite section is all about installing things in WSL. I think that is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34e0f433-2330-7203-4baf-2038644976d2
* Version Independent ID: cd2b0a17-21c5-3594-a38b-326b74be8ff0
* Content: [Install React on Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-on-windows)
* Content Source: [hub/dev-environment/javascript/react-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/react-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by vimode** [comment]
The React related docs are definitely due for an upgrade.

Related issue #3630

**Comment by mattwojo** [comment]
Fixed this in https://github.com/MicrosoftDocs/windows-dev-docs/commit/2197bc6ffeb413324b55e52d2e1ac29c2f555ea2. Thanks for filing!
