### ISSUE TITLE
Request: just as we have keyboard manager, also have mouse manager

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MicrosoftDocs/windows-uwp#4533]
We could set what each mouse button would do per app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like feedback about the product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a suggestion for the product. You can leave product questions/feedback on the [PowerToys GitHub repository](https://github.com/microsoft/PowerToys/issues). Thank you!

**Comment by AndroidDeveloperLB** [comment]
@alvinashcraft Thank you. 
The reason I reached here is from the link. I don't remember how.
