### ISSUE TITLE
Live Unit Test on Dev Drive

### ISSUE THREAD

**Issue by lgp1985** [MicrosoftDocs/windows-uwp#4535]
Please add the requirement to have [Live Unit Testing](https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2022) workspace root moved to a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/), you'll need to enable `Windows Projected File System` via the command below:
```Shell
fsutil devdrv setfiltersallowed PrjFlt
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by WilliamAntonRohm** [comment]
Related to MicrosoftDocs/visualstudio-docs/issues/9446

**Comment by mattwojo** [comment]
Done: https://github.com/MicrosoftDocs/windows-dev-docs/commit/fa0f98c18c547eb030bd26af17fe95ded14514f7
Thanks for bringing this to our attention @lgp1985!
