### ISSUE TITLE
What to do when there's problem with winget?

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/windows-uwp#4538]
What to do when there's problem with winget?  Is winget officially supported by Microsoft since the doc page in microsoft.com?  That means we have to contact Microsoft support in case of issue?

It's very unclear on this point.

**Comment by mattwojo** [comment]
Hi @cheesecracker - WinGet is the command line interface (CLI) for Windows Package Manager, so it's a part of Windows. What sort of support are you looking for? There isn't dedicated IT support that I'm aware of. We have a troubleshooting page, here: https://learn.microsoft.com/windows/package-manager/winget/troubleshooting and we have a training here: https://learn.microsoft.com/en-us/training/modules/explore-windows-package-manager-tool/?WT.mc_id=AZ-MVP-5004737

Issues with WinGet are typically posted and discussed on the WinGet CLI repo here: https://github.com/microsoft/winget-cli/issues
