### ISSUE TITLE
Powertoys Awake behavior with a reboot and without being logged in

### ISSUE THREAD

**Issue by Eegee** [MicrosoftDocs/windows-uwp#4539]
It is unclear to me if Awake's option Indefinitely survives manual or scheduled reboots (i.e. persists) and if a user needs to be logged in or not for it to work.
I am assuming now it only works when a user is logged in but in my opinion it would be helpful if this is explained in the documentation.
I will try to find out by myself in the meantime. To be sure I will probably use the CLI to schedule a task at startup without a user being logged in, or something alike, to get the Indefinite behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a20e555a-65ad-82e7-e1c0-f6577c1322b2
* Version Independent ID: 29236a0e-82e8-92d7-a5fb-12a9a777bcc2
* Content: [PowerToys Awake utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/awake)
* Content Source: [hub/powertoys/awake.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/awake.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. PowerToys Awake can only function when it's active, in other words when it's called upon. This can be via PowerToys Settings, directly the exe or maybe even a schedule, but there has to be a trigger.
Ping @dend @crutkas

**Comment by crutkas** [comment]
It has to be user invoked or via CLI.  It does not survivor reboot. Wouldn’t just the power settings in windows handle this for you?

**Comment by Eegee** [comment]
> Wouldn’t just the power settings in windows handle this for you?

Yes they would indeed, I did do that first. I only rather wanted to do it another way without needing to change the relevant settings of the active power plan. 

'User invoked' and 'when called upon' were good keywords, thank you two for the explanations. If something like that could be added to the docs page in just a sentence or two that would be great I think.

**Comment by alvinashcraft** [comment]
I've tweaked the docs to mention the utility not surviving a computer restart (PR is linked above). Thanks for the feedback!
