### ISSUE TITLE
Send File as Client example has errors, everywhere. (Suggested fix included)

### ISSUE THREAD

**Issue by DamianSuess** [MicrosoftDocs/windows-uwp#454]
**Environment:** UWP 10.0 build 10586

The code snip under, "_Send a file as a client_" provides a lot of errors. This isn't suitable for a novice individual to reference this and slap in the code. Thank you for providing the example. However, please state which UWP versions this supports, and what libraries need to be referenced and/or included via ``using`` statements.

By doing the changes in the "rewrite" section, it works for me. However, if you find that your provided answer is still correct, please state which UWP environment it is attempting to support to assist in clearing up user confusion.

Below is an example of the documentation incorrectly defining the namespace. There's a lot more such as, ``reader.Uint32();`` doesn't even exist, Enums which are named wrong, and a function that is using ``await`` when it's not an ``async`` & will fail because not all paths return a result.
```
  // Example uses:
  private Windows.Devices.Bluetooth.RfcommDeviceService _service;
  
  // When it should be:
  private Windows.Devices.Bluetooth.Rfcomm.RfcommDeviceService _service;
```

## Here's a rewrite:

Required using statements:
```
using System;
using System.Threading.Tasks;
using Windows.Devices.Bluetooth.Rfcomm;
using Windows.Networking.Sockets;
using Windows.Storage.Streams;
```

Class Code:

```
namespace XenoInc.TestBluetooth.UWP.Services.Bluetooth
{
  public class BluetoothServiceBase
  {
    private const uint MINIMUM_SERVICE_VERSION = 200;

    // This App relies on CRC32 checking available in version 2.0 of the service.
    private const uint SERVICE_VERSION_ATTRIBUTE_ID = 0x0300;

    private const byte SERVICE_VERSION_ATTRIBUTE_TYPE = 0x0A;

    private Windows.Devices.Bluetooth.Rfcomm.RfcommDeviceService _service;
    private Windows.Networking.Sockets.StreamSocket _socket;

    public async void InitializeConnection()
    {
      try
      {
        var services = await Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(
          RfcommDeviceService.GetDeviceSelector(RfcommServiceId.ObexObjectPush));

        if (services.Count > 0)
        {
          // Initialize the target Bluetooth BR device
          var service = await RfcommDeviceService.FromIdAsync(services[0].Id);

          // Check that the service meets this App's minimum requirement
          //if (SupportsProtection(service) && IsCompatibleVersion(service))
          _service = service;
          _socket = new StreamSocket();
          await _socket.ConnectAsync(
            _service.ConnectionHostName,
            _service.ConnectionServiceName,
            SocketProtectionLevel.BluetoothEncryptionAllowNullAuthentication);
        }

        //var defDevice = RfcommDeviceService.GetDeviceSelector(RfcommServiceId.SerialPort);
        //DeviceInformationCollection deviceInfoSet = await DeviceInformation.FindAllAsync(defDevice);
        //var numDevices = deviceInfoSet.Count();
      }
      catch (Exception ex)
      {
      }
    }

    private async Task<bool> IsCompatibleVersion(RfcommDeviceService service)
    {
      var attributes = await service.GetSdpRawAttributesAsync(Windows.Devices.Bluetooth.BluetoothCacheMode.Uncached);
      var attribute = attributes[SERVICE_VERSION_ATTRIBUTE_ID];
      var reader = DataReader.FromBuffer(attribute);

      // The first byte contains the attribute' s type
      byte attributeType = reader.ReadByte();
      if (attributeType == SERVICE_VERSION_ATTRIBUTE_TYPE)
      {
        // The remainder is the data
        uint version = reader.ReadUInt32();
        return version >= MINIMUM_SERVICE_VERSION;
      }
      return false;
    }

    // This App requires a connection that is encrypted but does not care about
    // whether its authenticated.
    private bool SupportsProtection(RfcommDeviceService service)
    {
      switch (service.ProtectionLevel)
      {
        case SocketProtectionLevel.PlainSocket:
          if ((service.MaxProtectionLevel == SocketProtectionLevel.BluetoothEncryptionWithAuthentication)
              || (service.MaxProtectionLevel == SocketProtectionLevel.BluetoothEncryptionAllowNullAuthentication))
          {
            // The connection can be upgraded when opening the socket so the
            // App may offer UI here to notify the user that Windows may
            // prompt for a PIN exchange.
            return true;
          }
          else
          {
            // The connection cannot be upgraded so an App may offer UI here
            // to explain why a connection won't be made.
            return false;
          }
        case SocketProtectionLevel.BluetoothEncryptionWithAuthentication:
          return true;

        case SocketProtectionLevel.BluetoothEncryptionAllowNullAuthentication:
          return true;
      }
      return false;
    }
  }
}
```

Thank you for the nice example!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e22cfcd-37c0-ca84-f54f-979de1ab1d93
* Version Independent ID: 02e66d17-145b-e7aa-0ed0-129fde52ef23
* Content: [Bluetooth RFCOMM - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/send-or-receive-files-with-rfcomm)
* Content Source: [windows-apps-src/devices-sensors/send-or-receive-files-with-rfcomm.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/send-or-receive-files-with-rfcomm.md)
* Service: **unspecified**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DamianSuess - Reviewing some older issues and noticed this one assigned to me in October 2019. The topic code was updated significantly in https://github.com/MicrosoftDocs/windows-uwp-pr/commit/2184f79affcc88acad1d66413350c1dff0086377#diff-22efa8a62afd7fff3e6fac692bdf28af. I've made another minor update today. Please review if you'd like and feel free to update the topic and issue a PR with any changes you'd like to see.

**Comment by DamianSuess** [comment]
@Karl-Bridge-Microsoft, thank you for the feedback. Unfortunately, the link is no longer accessible to review it. I appreciate that you took the time to look into this.
