### ISSUE TITLE
Rename .NET Core to .NET

### ISSUE THREAD

**Issue by sander1095** [MicrosoftDocs/windows-uwp#4541]
.NET Core is EOL and the new name is simply ".NET"

**Comment by alvinashcraft** [comment]
Hi @sander1095. Thanks for raising this issue. I fixed the items you mentioned, plus several other locations in this repo where a simple .NET Core to .NET change was enough. There are some other topics where making the change will be more complicated. I've created a list of those so we can address them in the future. The changes should be live today.

**Comment by sander1095** [comment]
Hi @alvinashcraft . Im glad to hear you fixed it, but my PR that I created for this is still open
