### ISSUE TITLE
Error installing nvm for WSL

### ISSUE THREAD

**Issue by austinledbetter** [MicrosoftDocs/windows-uwp#4545]
I have WSL Ubuntu installed, and I have NVM for Windows installed from https://github.com/coreybutler/nvm-windows .

When I ran the command to install NVM for WSL, I got the error below.  I tried closing and reopening the terminal, but it still did not find the nvm command.  Any idea how to fix it?

Here is full output from the WSL terminal - 

`wsluser@machine:~$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15916  100 15916    0     0  55009      0 --:--:-- --:--:-- --:--:-- 55072
=> Downloading nvm from git to '/home/wsluser/.nvm'
=> Cloning into '/home/wsluser/.nvm'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (361/361), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 361 (delta 40), reused 168 (delta 28), pack-reused 0
Receiving objects: 100% (361/361), 221.43 KiB | 1.94 MiB/s, done.
Resolving deltas: 100% (40/40), done.
* (HEAD detached at FETCH_HEAD)
  master
=> Compressing and cleaning up git repository

=> Appending nvm source string to /home/wsluser/.bashrc
=> Appending bash_completion source string to /home/wsluser/.bashrc
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '\\wsl.localhost\Ubuntu\mnt\c\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
wsluser@machine:~$ command -v nvm
wsluser@machine:~$ which node
wsluser@machine:~$ which nvm
wsluser@machine:~$`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by austinledbetter** [comment]
When I run the install.sh command again, it shows this output, indicating that it did add files and test to .bashrc already - 

`wsluser@machine:~$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15916  100 15916    0     0  95608      0 --:--:-- --:--:-- --:--:-- 95879
=> nvm is already installed in /home/wsluser/.nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /home/wsluser/.bashrc
=> bash_completion source string already in /home/wsluser/.bashrc
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '\\wsl.localhost\Ubuntu\mnt\c\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
wsluser@machine:~$ which nvm
wsluser@machine:~$`

**Comment by austinledbetter** [comment]
I found a solution by removing the Windows version of nodejs from the PATH variable for my WSL terminal.

I had to edit the /home/wsluser/.bashrc file to add these lines:

`# set PATH to PATH without the nodejs path

result=$(echo $PATH | sed 's;/mnt/c/Program Files/nodejs:;;g')

PATH=$result`

The next time I ran the command, I did not get an error: 

`wsluser@machinename:~$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15916  100 15916    0     0  61592      0 --:--:-- --:--:-- --:--:-- 61689
=> nvm is already installed in /home/wsluser/.nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /home/wsluser/.bashrc
=> bash_completion source string already in /home/wsluser/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
wsluser@machinename:~$ command -v nvm
nvm
wsluser@machinename:~$`

**Comment by vimode** [comment]
@austinledbetter  I am glad you figured it out eventually. 

I have nvm for windows and for WSL and it works fine, I didn't have to remove nodejs or nvm from PATH in Windows to make it work. 

By removing from PATH does your nvm and node  for Windows work fine?

**Comment by austinledbetter** [comment]
nvm and npm still appear to work on the Windows side.  I installed and ran grunt for some unit tests, and I ran an npm bundle webpack process successfully.

I am not sure why it would work for you and and not for me with the normal paths.  I read on one article somewhere that it could be because I had spaces in the path to the npm-cli.js file.  At least there is a workaround for it!

For reference, this is my path in Windows - 
`C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\WindowsPowerShell\Scripts;C:\Program Files\Docker\Docker\resources\bin;C:\Users\austin.ledbetter\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Users\austin.ledbetter\AppData\Local\Microsoft\WindowsApps;C:\Users\austin.ledbetter\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\austin.ledbetter\AppData\Local\Programs\Git\cmd;C:\Users\austin.ledbetter\.dotnet\tools;C:\Users\austin.ledbetter\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin`

And this is my path in WSL, minus the nodejs path - 
`/home/wsluser/.nvm/versions/node/v12.22.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/WindowsPowerShell/Scripts:/Docker/host/bin:/mnt/c/Users/austin.ledbetter/AppData/Roaming/nvm:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files (x86)/Microsoft SQL Server/160/DTS/Binn/:/mnt/c/Program Files/Azure Data Studio/bin:/mnt/c/Users/austin.ledbetter/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/austin.ledbetter/AppData/Roaming/nvm:/mnt/c/Users/austin.ledbetter/AppData/Local/Programs/Git/cmd:/mnt/c/Users/austin.ledbetter/.dotnet/tools:/mnt/c/Users/austin.ledbetter/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin`

**Comment by mattwojo** [comment]
Thanks for filing this issue and sharing your progress! Sounds like this doesn't require an update to the doc, but please re-open if that is not the case.
