### ISSUE TITLE
no illustration of how to add extension to files lacking extension

### ISSUE THREAD

**Issue by ebscoles-gcc** [MicrosoftDocs/windows-uwp#4547]
This is a really basic use-case & AFAICS it's totally missing from the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by Jay-o-Way** [comment]
Please check again. It's literally there.
#NotAnIssue

**Comment by alvinashcraft** [comment]
I see it documented too, when I search the page for "extension". This feels resolved, so I'm closing the issue.
