### ISSUE TITLE
error 404 wrong link to the win2D page on the graphics overview page

### ISSUE THREAD

**Issue by mtoons** [MicrosoftDocs/windows-uwp#4549]
The links to win2D in the topic "https://learn.microsoft.com/en-us/windows/apps/develop/graphics#win2d" return error code 404.

A possible solution is to link to use this link instead "https://learn.microsoft.com/en-us/windows/apps/develop/win2d/".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7cacf6-1ed4-da17-7186-c4e98a08fec9
* Version Independent ID: 1b7cacf6-1ed4-da17-7186-c4e98a08fec9
* Content: [Graphics - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/graphics)
* Content Source: [hub/apps/develop/graphics.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/graphics.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you! I have a fix on its way out to the live site. Should be there soon.

-Steve
