### ISSUE TITLE
Code does not retrieve redButtonStyle from resource dictionary

### ISSUE THREAD

**Issue by mysorian** [MicrosoftDocs/windows-uwp#455]
The code is on this url:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references

This line of code does not retrieve the style. 
 Style redButtonStyle = (Style)this.Resources["redButtonStyle"];

I have myButtonStyle instead of redButtonStyle and the Visual Studio 2017 Community suggests this modification.  Note the redButtonStyle code is suggested by intellisense but does not throw exception.
 Style myButtonStyle = (Style)Resources["myButtonStyle"];

The documentation can be improved by proper color coding.

![resbuttonstyle](https://user-images.githubusercontent.com/5265734/38774310-c6c480a0-4001-11e8-85df-f43ea8a037cc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6822f33-819b-ae6f-95cd-04861fa46dca
* Version Independent ID: 12e5988d-2aa1-0284-4f75-3b0cfb17177c
* Content: [ResourceDictionary and XAML resource references - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references)
* Content Source: [windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi @mysorian , if you change the code from redButtonStyle to myButtonStyle, you'll also need to change the Style Key in the resources section. If you change the key to this, `x:Key="myButtonStyle"`, it should work.
