### ISSUE TITLE
Bluetooth device capability and Windows radio control access

### ISSUE THREAD

**Issue by msftradford** [MicrosoftDocs/windows-uwp#4553]
It is unclear to me how the Bluetooth device capability relates to the Windows radio control access settings. For example, I can completely disable Windows radio control access (via Windows Settings on an HL2 or desktop) and still receive Bluetooth advertisements. Is there a way to toggle access to Bluetooth advertisements after app install or does it only depend on if the Bluetooth device capability exists in the appxmanifest? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb68dee1-01d8-94cf-976a-5dd31d408f4d
* Version Independent ID: 1deea8b5-5241-c349-0d17-3a6a55187e58
* Content: [Bluetooth developer FAQ](https://learn.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth-dev-faq)
* Content Source: [uwp/devices-sensors/bluetooth-dev-faq.yml](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/devices-sensors/bluetooth-dev-faq.yml)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Hi - please reach out to the docs team directly if this is still an issue. Thanks!
