### ISSUE TITLE
Restricted capability uiAccess is missing

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/windows-uwp#4559]
Apparently, there is a restricted capability 'uiAccess' in the AppXManifest that is needed when an application executable has an application manifest (internal or external) with uiaccess = "true".

This capability is missing from the list.  A review of internal documentation to update this page is probably warranted, as there may be more capabilities that have been defined over the years.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [uwp/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@TimMangan I've added an entry for the uiAccess capability.
