### ISSUE TITLE
How can i use  bindingdata to set image source from my Assets (and not use symbol icon)?

### ISSUE THREAD

**Issue by Sbebo** [MicrosoftDocs/windows-uwp#456]
I have two questions for this example:
1. How can i use bindingdata to set image source from my Assets (and not use symbol icon)?
2. And how can I open a new page (this.Frame.Navigate(typeof(Pages.MyPage) form item of listview?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9fdf72e-8eaa-1e01-9b9c-d1c5e506117d
* Version Independent ID: 45f0e7ae-662c-29fb-8171-9674f7bbde15
* Content: [Data binding overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart)
* Content Source: [windows-apps-src/data-binding/data-binding-quickstart.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/data-binding-quickstart.md)
* Service: **unspecified**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by jevansaks** [comment]
These questions are more suited for StackOverflow.com. I recommend posting there with the winrt-xaml tag. https://stackoverflow.com/questions/tagged/winrt-xaml.
