### ISSUE TITLE
time and date plugin information is incorrect

### ISSUE THREAD

**Issue by blonkm** [MicrosoftDocs/windows-uwp#4562]
The time and date explanation shows to use ")", but it should be "("

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b951899-69ca-9057-f799-14491e1b0a74
* Version Independent ID: 18e0202f-3e91-a5b9-62f2-6cd40e5661a8
* Content: [PowerToys Run utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/run)
* Content Source: [hub/powertoys/run.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by Jay-o-Way** [comment]
No. It was `(` by default a long time ago. That would conflict with math stuff - like `(2+2)*5` - so the default was changed to `)`. The value in your settings is a remnant of the old days.
#NotAnIssue

**Comment by alvinashcraft** [comment]
This looks correct to me too. Thanks, @Jay-o-Way. I'm closing this issue.
