### ISSUE TITLE
Documentation broken in german translation

### ISSUE THREAD

**Issue by floh96** [MicrosoftDocs/windows-uwp#4563]
See screenshot some options are not displayed correct in the german translation.
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/49693964/fde69a6a-9d6b-4219-b256-0d8e5f1abebb)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf54ba9-53bd-e5d0-3b5a-e5b003f356d9
* Version Independent ID: ed2c403c-7bba-9647-fb5c-da556cb93a6b
* Content: [upgrade Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade)
* Content Source: [hub/package-manager/winget/upgrade.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/upgrade.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Unfortunately we have to rely on machine translation for these docs, so the only way that I currently have to make correction is by adding product names into a "Do not translate" metadata tag, unless I file a high-priority fix request. 
Can you offer an idea of what's wrong exactly in the translation? How severely do you feel that this impacts a German-speakers ability to use winget?  Thank you for taking time to raise this issue.

**Comment by floh96** [comment]
@mattwojo the translation is not wrong but some command options are not displayed correct.
See https://learn.microsoft.com/de-de/windows/package-manager/winget/upgrade for the option --custom for example the following text is displayed:
`<bpt xmlns="urn:oasis:names:tc:xliff:document:1.2" id="1">&lt;strong&gt;</bpt>--custom<ept xmlns="urn:oasis:names:tc:xliff:document:1.2" id="1">&lt;/strong&gt;</ept>`

**Comment by mattwojo** [comment]
Ahh -- I see what you mean. Thanks for raising this issue. I'll reach out to our localization team to let them know about the issue with the translation system.

**Comment by mattwojo** [comment]
Looks like it's not just the German translation, but all translations... and it's happening wherever there is a markdown table... but only on a few lines. Very WEIRD... we are investigating.

**Comment by Jay-o-Way** [comment]
Maybe invalid properties in the tags?

> <bpt>	The <bpt> (Begin paired tag) element contains zero, one or more <sub> elements. It is used to delimit the beginning of a paired sequence of native codes. Each <bpt> has a corresponding <ept> element within the segment.

> Mandatory attributes: i.
Optional attributes: type and x.


> <ept>	The <ept> (End paired tag) element contains zero, one or more <sub> elements. It is used to delimit the end of a paired sequence of native codes. Each <ept> element has a corresponding<bpt> element within the segment.

> Mandatory attributes: i.
Optional attribute: none.

**Comment by mattwojo** [comment]
Just heard back from our Localization team and they were able to implement a fix for this formatting issue. Looks like the page is rendering correctly now. Thank you for bringing this to our attention @floh96!
https://learn.microsoft.com/de-de/windows/package-manager/winget/upgrade#options

Please reopen if it seems this fix has not resolved the issue.
