### ISSUE TITLE
Clarify "desktop"

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/windows-uwp#4566]
Hi, it mentions "desktop" in this article. It would be worth clarifying if it works or does not work on other "desktops" such as Windows365, RDC, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [uwp/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@dombat, thanks for calling this out. This page was authored during the Windows Phone era, so in this case it's not even referring to the "desktop", as-in the thing you see when all windows are minimized. I updated the content to refer to "Windows desktops", which hopefully will help to clarify.
