### ISSUE TITLE
(s)

### ISSUE THREAD

**Issue by ohseongkooi** [MicrosoftDocs/windows-uwp#457]
hfdztj

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bee5a5b-7ae7-90e9-b3ad-8213a0f5ef3a
* Version Independent ID: 521a353f-2668-a0aa-026c-2938b8096b46
* Content: [Get set up - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/get-started/get-set-up?ocid=TipsApp_Ver2_GetReady_Setup#see-also)
* Content Source: [windows-apps-src/get-started/get-set-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/get-set-up.md)
* Service: **unspecified**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by ginami** [comment]
Hi @ohseongkooi. Please let us know if you have any feedback on our documentation. Thanks!
