### ISSUE TITLE
how do I make a window "forget" last known zone?

### ISSUE THREAD

**Issue by ThatGuyAgain42** [MicrosoftDocs/windows-uwp#4570]
I love the feature "Move newly created windows to the last known zone" however, when moving an application to a monitor without zones and closing it, upon reopening the application it will snap to the previous monitor. 

I would like to suggest an implementation to fix this problem wherein windows that leave a monitor's zones "forget" their "last known zone" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @ThatGuyAgain42. Thanks for your suggestion. This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback. Cheers!
