### ISSUE TITLE
Add Autoupdate instructions

### ISSUE THREAD

**Issue by TuningJohn** [MicrosoftDocs/windows-uwp#4571]
I expected to see instructions on how to have PowerToys autoupdate. I am currently having to manually update each time there is a change and want to know how to make it autoupdate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/install)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @TuningJohn. Thanks for your question/suggestion. It's not currently possible to have PowerToys auto-update. It will automatically download the latest update and notify you when it's ready to be installed (as the docs indicate). There is an open issue in the PowerToys repo with the same suggestion. If you have any comments you would like to add, you can add them [here](https://github.com/microsoft/PowerToys/issues/27651).

**Comment by valentijnscholten** [comment]
In my opinion it shouldn't be called auto update if it doesn't actually perform automatic updates, see #5155
