### ISSUE TITLE
Xaml support was removed from the crate

### ISSUE THREAD

**Issue by erde74** [MicrosoftDocs/windows-uwp#4575]
[Enter feedback here]
The Documentation is outdated the Xaml support was removed see commit [b8d83c2](https://github.com/microsoft/windows-rs/commit/b8d83c2a620a683702c2d486d9f9d09f4b88b1f6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf3f708-e517-41c8-0033-5e737e58cbd6
* Version Independent ID: a143550c-f85f-5b35-2fa4-0bcc243cac1d
* Content: [Rust for Windows, and the windows crate](https://learn.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows)
* Content Source: [hub/dev-environment/rust/rust-for-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/rust/rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the heads up, that's been edited now. :)

-Steve
