### ISSUE TITLE
Please elaborate, what happens for the end-user if an updated MSI is uploaded to Microsoft Store

### ISSUE THREAD

**Issue by JoergAtGithub** [MicrosoftDocs/windows-uwp#4577]
(If you select the "MSI or EXE" tab), this page contains the sentence` The Store allows existing users to install app updates through the Store, if your installer supports it. ` which is not understandable to me.
1.) Please elaborate what `if your installer supports it` means:

- Which features must my MSI package implement?
- How to test my MSI package if it supports it?

2.) What happens if I replace the MSI file with an updated version:

- Will the updated package will be offered end-users in the Microsoft Store for manual update installation?
- Will the end-user get a notification or do I've to send a notification manual using the Partner Center?
- Our MSI app requires Admin permissions - whom will the MSI app update be offered, only Admins, or all users? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd03e633-e47b-0a69-6164-e9f5000521c0
* Version Independent ID: dd03e633-e47b-0a69-6164-e9f5000521c0
* Content: [Publish update to your app on the Store - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/publish-update-to-your-app-on-store)
* Content Source: [hub/apps/publish/publish-your-app/publish-update-to-your-app-on-store.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/publish-update-to-your-app-on-store.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by stevewhims** [comment]
Thanks! I'm investigating. :)

-Steve

**Comment by stevewhims** [comment]
Just an update: This particular documentation section was recently updated by a product team subject-matter expert to add more details. Please check whether the current content helps with your query. I'll close this issue, but please reopen it if necessary.

Thanks!
-Steve
