### ISSUE TITLE
Thumbnail icon preview -> 3MF file support

### ISSUE THREAD

**Issue by RandomGgames** [MicrosoftDocs/windows-uwp#4579]
Being able to preview 3MF files would be useful I feel, as they are widely used like STLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [PowerToys File Explorer add-ons utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by RandomGgames** [comment]
This might be the wrong place, but I want to suggest that powertoys support 3mf file icon previews, not just STLs for 3d objects. If this is the wrong place, please let me know where I can suggest.

**Comment by alvinashcraft** [comment]
Hi @RandomGgames. Thanks for your suggestion. You can pursue this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback. Cheers!
