### ISSUE TITLE
memory mapped files

### ISSUE THREAD

**Issue by adrianstephens** [MicrosoftDocs/windows-uwp#458]
How do you create memory-mapped files in UWP? Even if it is a separate API I still think it would be worth mentioning here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b36404b8-4385-81d9-2ee8-486f0a55fc37
* Version Independent ID: 7b6ce4df-6ab2-3aa6-059f-b38aa9ea8062
* Content: [Create, write, and read a file - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
@adrianstephens, Thanks for your question! UWP apps are not currently allowed to use file mapping APIs.

**Comment by bryaan** [comment]
@laurenhughes Is there any word on whether this kind of IPC is to be allowed at some point?  I have no doubt companies are choosing to not use UWP precisely for these restrictions.  If all we are doing is a desktop app is there a way to bypass?

**Comment by laurenhughes** [comment]
@bryaan, UWP support for Memory Mapped Files in some capacity is being considered by the product team. I'll pass your feedback along to the team as well! I don't believe there is a way to bypass the restriction even if your UWP app is only targeting desktop since it's a platform limitation.

**Comment by bryaan** [comment]
Actually I think I found a way though BrokeredProxy but have not tried it yet.  The platform limitation is one of security but not capability.  It's understandable on mobile but not on Desktop.  Many people want to build Desktop only, side-loaded is fine, apps using UWP, but those limits turn them away.  Hope it's just a matter of time before the team gets green-light to allow full IPC, or at least for memory-mapped files.
Thanks!

**Comment by soumyamahunt** [comment]
Is memory mapped files still not supported??

**Comment by soumyamahunt** [comment]
Creating MMF is supported in UWP, but you have to declare `codeGeneration` capability in your manifest. While the [capability documentation](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#:~:text=Capabilities%20are%20used%20by%20UWP%20apps%20as%20well,by%20declaring%20capabilities%20in%20your%20app%27s%20package%20manifest.) mentions that, the MMF documentation doesn't mention it which causes confusion. Also, you can use your existing dotnet code for MMF as the support has been declared [while back](https://github.com/dotnet/corefx/commit/68949506e38203500c768fd2debbff73c0304b26).
