### ISSUE TITLE
Available in the Beta channel

### ISSUE THREAD

**Issue by aelij** [MicrosoftDocs/windows-uwp#4580]
According to [this post](https://blogs.windows.com/windows-insider/2023/08/02/announcing-windows-11-insider-preview-build-22621-2129-and-22631-2129/) Dev Drive should be available on the Beta channel as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Dev Drive is now generally available in Windows 11, Build # 10.0.22621.2338 or later. 

https://support.microsoft.com/en-us/windows/windows-update-faq-8a903416-6f45-0718-f5c7-375e92dddeb2
