### ISSUE TITLE
Link to extermal website leads to paywall

### ISSUE THREAD

**Issue by SilverNetiX** [MicrosoftDocs/windows-uwp#4584]
The link to "Regex tutorial — A quick cheatsheet by examples"
leads to a paywalled website https://medium.com/factory-mind/regex-tutorial-a-simple-cheatsheet-by-examples-649dc1c3f285.

please use an alternative website that dont require registration to read the complete documentation.

thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://learn.microsoft.com/en-gb/windows/powertoys/powerrename#regular-expressions)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @SilverNetiX. Thanks for pointing this out. I removed the link and replaced it with a link to another RegEx tutorial site. This one is free to use for anyone. I just merged the changes, and they should go live soon!
