### ISSUE TITLE
File format list needed

### ISSUE THREAD

**Issue by jedimmel** [MicrosoftDocs/windows-uwp#4585]
Why not provide list of file formats it previews? That would actually make this page useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4995a8-5af9-bcfd-86f2-912c5674b95d
* Version Independent ID: 1c4995a8-5af9-bcfd-86f2-912c5674b95d
* Content: [PowerToys Peek utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/peek)
* Content Source: [hub/powertoys/peek.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/peek.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thank you for raising this issue. The team feels that the list is too extensive to reasonably present it in the documentation and keep it in sync with the application. Users who are interested in finding out which file types are supported can search [the list](https://github.com/microsoft/PowerToys/blob/main/src/common/FilePreviewCommon/Assets/Monaco/monaco_languages.json) in the source repo.
