### ISSUE TITLE
Recommended Node.js Extension Pack is deprecated

### ISSUE THREAD

**Issue by gitkompiler** [MicrosoftDocs/windows-uwp#4589]
The recommended Node.js Extension Pack in this article is apparently deprecated.
Searching for the extension in VS Code has it greyed out with an exclamation symbol and message is:
This extension is deprecated as it is no longer being maintained

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hmm - I see what you're talking about. Thanks for pointing this out. 
It appears to still work even though it's deprecated and no longer being supported. I'll investigate whether there is another extension that Node devs recommend. Otherwise, I may just remove this section completely as extensions aren't really necessary.

**Comment by mattwojo** [comment]
I believe the owner of the NodeJS extension pack updated it: https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack ...so leaving it linked in the doc for now and resolving this issue. Thanks for filing!
