### ISSUE TITLE
Outdated Store Icon?

### ISSUE THREAD

**Issue by sam9116** [MicrosoftDocs/windows-uwp#459]
you might want to... like? Update it?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c479e308-a9e4-8ab4-ada9-b9d6720580b1
* Version Independent ID: 9b204f22-b4cc-fb8d-24b7-f0d4a69f9e4e
* Content: [Publish your packaged desktop app to a Windows store or sideload it onto one or more devices. - UWP app developer](https://docs.microsoft.com/en-ca/windows/uwp/porting/desktop-to-uwp-distribute)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-distribute.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-distribute.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you. Yes the icon has changed. The image is of little value to the doc, so I've checked in a change to remove it entirely but that change won't likely appear until later this month when we refresh our content for the new release of the SDK.

Thx Again!
