### ISSUE TITLE
git bash

### ISSUE THREAD

**Issue by Frankie-cha** [MicrosoftDocs/windows-uwp#4592]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73bd6478-de0f-6aa9-fb31-0818abdb7f68
* Version Independent ID: f5ff6ecd-0231-d438-7301-6eb20863ec50
* Content: [install Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/install?source=recommendations)
* Content Source: [hub/package-manager/winget/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/install.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@Frankie-cha - I'm closing this issue as it doesn't include a description, but if there is an issue here that you believe requires an update to the winget install documentation, please re-open the issue and add a description. Thank you!
