### ISSUE TITLE
How about OnBackgroundActivated

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/windows-uwp#4598]
How nicely you have just let-out 'OnBackgroundActivated' of migration and just did not mention any info how to work with that.

If that is not possible just say in right there instead of just not saying anything.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c675e4ec-a22b-c54d-e1d6-1eaa408180b9
* Version Independent ID: c675e4ec-a22b-c54d-e1d6-1eaa408180b9
* Content: [Application lifecycle functionality migration - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle)
* Content Source: [hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @KWodarczyk. I've added this info to the topic: "Also see the Background tasks row in the table in the [What's supported when migrating from UWP to WinUI 3](https://learn.microsoft.com/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported) topic."

-Steve
