### ISSUE TITLE
Please always provide examples in both c++ and c#

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/windows-uwp#4599]
As in the title
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d56a3de-3af1-6b72-ab58-c4cecf7b7dc7
* Version Independent ID: ef4aff1b-9f9c-2300-34c8-dff5e54aceb6
* Content: [Rich activation with the app lifecycle API (Windows App SDK) - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation)
* Content Source: [hub/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation.md)
* Product: **reunion**
* Technology: **app-lifecycle**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
Thanks, @KWodarczyk. We can't *always* "provide code examples in both C# and C++". But we try to do it when it most matters. By default, code examples are in C# (an exception to that would be if the topic is specifically about C++). And then certain code examples are ported to C++ alongside the C# version.

-Steve
