### ISSUE TITLE
Custom device picker: deviceWatcher.Start() is missing?

### ISSUE THREAD

**Issue by szblajos** [MicrosoftDocs/windows-uwp#460]
As I see, it is missing a deviceWatcher.Start() at the end of the startWatcherButton_Click event handler function in the custom device picker section.
Without calling the Start() function, the code will not enumerate any devices. Sorry if I missed something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22d65d08-0084-406d-4dbc-117be58bcb84
* Version Independent ID: 084af94a-ff11-fe11-8c07-47eaefa33b4f
* Content: [Media casting - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-casting)
* Content Source: [windows-apps-src/audio-video-camera/media-casting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/media-casting.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this error. This bug has been fixed in the content source and will be published live with the next doc release.
