### ISSUE TITLE
Is psd support planned?

### ISSUE THREAD

**Issue by pokipoi** [MicrosoftDocs/windows-uwp#4602]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4995a8-5af9-bcfd-86f2-912c5674b95d
* Version Independent ID: 1c4995a8-5af9-bcfd-86f2-912c5674b95d
* Content: [PowerToys Peek utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/peek)
* Content Source: [hub/powertoys/peek.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/peek.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by pokipoi** [comment]
that i can uninstall the quicklook

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
