### ISSUE TITLE
Cannot Locate or Extract .65 MSI file

### ISSUE THREAD

**Issue by Russ-McClelland** [MicrosoftDocs/windows-uwp#4603]
The instructions for extracting the MSI file do not work for Wix4, nor do the other sections for extracting an MSI file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329db15d-6ba6-3603-e8e2-e48762d25431
* Version Independent ID: 56ad7882-244e-d3d6-efe6-ec5d38ffd394
* Content: [Install PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/install#extracting-the-msi-from-the-bundle)
* Content Source: [hub/powertoys/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/install.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @Russ-McClelland. The documentation states that extracting the MSI does not work with Wix4. Wix3 is required, and it's linked in that section. Does it work for you with Wix3?

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. It seems like the behavior is documented correctly. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
