### ISSUE TITLE
Arm64_RUNTIME_FUNCTION should be ARM64_RUNTIME_FUNCTION

### ISSUE THREAD

**Issue by kobykahane** [MicrosoftDocs/windows-uwp#4604]
The actual name of the structure type as declared in winnt.h is ARM64_RUNTIME_FUNCTION, but the declaration of `FunctionTable[1]` incorrectly says Arm64_RUNTIME_FUNCTION.

Also, Am64EC should be Arm64EC.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5954bc97-3070-17c6-18c1-5c66da90a213
* Version Independent ID: 5954bc97-3070-17c6-18c1-5c66da90a213
* Content: [Understanding Arm64EC ABI and assembly code](https://learn.microsoft.com/en-us/windows/arm/arm64ec-abi)
* Content Source: [landing/arm-docs/arm64ec-abi.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/landing/arm-docs/arm64ec-abi.md)
* Product: **windows**
* Technology: **arm**
* GitHub Login: @pmsjt
* Microsoft Alias: **pedrot**

**Comment by pmsjt** [comment]
Thanks @kobykahane. I just merged a change with the fix for the two typos you pointed out. Should be live in a couple of days 🤞.

**Comment by kobykahane** [comment]
Thanks @pmsjt. I now also notice that `Arm64EC_CUSTOM_ENTRY_THUNK` should be `ARM64EC_CUSTOM_ENTRY_THUNK` (it's a macro obtained through ksarm64.h). And there's also `_Arm64EC_` that should be `_ARM64EC_`. Probably worth reviewing the entire page.

**Comment by pmsjt** [comment]
Alright. Seems as all the fixes are live now.

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/windows-dev-docs/commit/821e1cf88a60e496678040bcc7beddbc2b457272
