### ISSUE TITLE
connection timed out error always when trying to install nvm using curl

### ISSUE THREAD

**Issue by abhijeetgauravm** [MicrosoftDocs/windows-uwp#4606]
abhijeetgauravm@LAPTOP-008GS74O:~$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (7) Failed to connect to [raw.githubusercontent.com](http://raw.githubusercontent.com/) port 443: Connection timed out

i have tried it many time also but connection timed out error come when i use $ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash    for installing nvm in my wsl even i try with wget but wont able to install nvm.
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/65087356/730b34c2-a1ad-4486-bdbd-38edb2aa828c)
Even i have very good internet connection.
[Enter feedback here]
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/65087356/6b39d248-0c6b-419b-a632-bdd7f77c2349)
Not able to install nvm through this command in my wsl. I tried many times.

  **Update: After running these command in my wsl i am able to install nvm through curl
 sudo rm /etc/resolv.conf
 sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
 sudo bash -c 'echo "[network]" > /etc/wsl.conf'
 sudo bash -c 'echo "generateResolvConf = false" >> /etc/wsl.conf'
 sudo chattr +i /etc/resolv.conf**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
This may be related to your internet connection (?)... just testing installing nvm using the curl script and it works. Sorry you're having trouble. Closing this issue as it doesn't appear to require an update to the doc, but please reopen if you find that is not the case.
