### ISSUE TITLE
Please clarify how to call base implementation of overridable methods.

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/windows-uwp#4608]
This page shows an example of calling the base implementation with `base_type::GoToStateCore`, but this pattern should be called out explicitly, probably in its own little section/paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8a199ae-561b-98b6-8cf0-101aedbfe599
* Version Independent ID: a8091c04-868d-51aa-f4d1-207c5c795235
* Content: [XAML custom (templated) controls with C++/WinRT - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl#implementing-overridable-methods-such-as-measureoverride-and-onapplytemplate)
* Content Source: [uwp/cpp-and-winrt-apis/xaml-cust-ctrl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/cpp-and-winrt-apis/xaml-cust-ctrl.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Note to self: For context, see email thread "Re: Calling XAML base methods in C++/WinRT".

**Comment by stevewhims** [comment]
Thanks, @DefaultRyan. I've moved that example to a new topic, and added this new section to that new topic:

https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/base-type#calling-your-base-type

Does that look ok? Please let me know if that needs any edits, and I'll be happy to make them.

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close, optimistically, but we can re-open, or (better) continue the discussion in email, if necessary. :)

-Steve
