### ISSUE TITLE
Mismatched image and text

### ISSUE THREAD

**Issue by pierrebai** [MicrosoftDocs/windows-uwp#461]
In the "Choosing between toggle switch and check box" section, the image talks about kitchen light but the text talk about turning wireless on and off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26382be5-2112-2fe1-cabe-acde81edbba7
* Version Independent ID: b800fb91-9f50-4af2-ed59-d343b54d5f83
* Content: [Guidelines for toggle switch controls - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles)
* Content Source: [windows-apps-src/design/controls-and-patterns/toggles.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/toggles.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for raising the issue! Will update so that image and text match.
