### ISSUE TITLE
I could not find this page on my dashboard

### ISSUE THREAD

**Issue by raymondlee915** [MicrosoftDocs/windows-uwp#462]
Hi there, I published my apps for SharePoint store, and I really could not see this page anywhere, I search out all the pages in Seller dashboard. Any idea what the problem is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b80a63-ba2e-ea74-83d3-c63fa1d4904f
* Version Independent ID: 5e8b56c6-a964-1d5d-c040-55254e582da8
* Content: [Payout summary - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Hi there - I'm sorry it's taken so long to respond. I'm not sure why you aren't seeing your payout info for Seller Dashboard, so I would suggest opening a support request. Visit http://go.microsoft.com/fwlink/?LinkId=272975, choose category “App Analytics and commerce” and subcategory “Questions about payout", then choose your contact method (email or phone call).
