### ISSUE TITLE
windows quick look or peek 

### ISSUE THREAD

**Issue by Dexterisham** [MicrosoftDocs/windows-uwp#4620]
the whole peek window flickers while   using it

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
