### ISSUE TITLE
instructions to launch Registry Preview are out of date or incomplete

### ISSUE THREAD

**Issue by AlisterH** [MicrosoftDocs/windows-uwp#4623]
When I right-click on a .reg file there is no option to "Show more options"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4916d5a-cb72-75b4-9909-aaccbbfb9832
* Version Independent ID: f4916d5a-cb72-75b4-9909-aaccbbfb9832
* Content: [PowerToys Registry Preview for Windows](https://learn.microsoft.com/en-gb/windows/powertoys/registry-preview)
* Content Source: [hub/powertoys/registry-preview.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/registry-preview.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @AlisterH. What version of Windows are you using? In Windows 11 with the 23H2 update applied, I see "Show more options" at the bottom of the context menu when right-clicking a .reg file.

**Comment by AlisterH** [comment]
Windows 10 22H2

**Comment by alvinashcraft** [comment]
It looks like the instructions are only written for Windows 11, which has the "Show more options" option in the context menu. I'll add a note about using the utility in Windows 10.

**Comment by Jay-o-Way** [comment]
Sounds like an easy fix, no?

**Comment by alvinashcraft** [comment]
Thanks, @Jay-o-Way for submitting a PR to address this issue. It's merged and should be live soon.

Thanks @AlisterH for bringing this to our attention.
