### ISSUE TITLE
winget upgrade --uninstall-previous - what if not included?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/windows-uwp#4627]
Please elaborate what's the behavior when not specifying the `--uninstall-previous` flag in the upgrade command, will there be two side-by-side versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf54ba9-53bd-e5d0-3b5a-e5b003f356d9
* Version Independent ID: ed2c403c-7bba-9647-fb5c-da556cb93a6b
* Content: [upgrade Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade)
* Content Source: [hub/package-manager/winget/upgrade.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/upgrade.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by denelon** [comment]
It depends on the individual package.

Some installers are designed to install new versions "side-by-side". If the manifest specifies "uninstallPrevious" then WinGet will uninstall the previous version before installing the new version.

Adding "--uninstall-previous" on the CLI tells WinGet to uninstall the previous version regardless of what is in the manifest.

If the manifest does not have "uninstallPrevious" and you do not specify "--uninstall-previous" in the CLI, then the installer will be run and you will get the default behavior for the installer.

**Comment by weitzhandler** [comment]
Thank you for the explanation. Might be worth including the this in the docs.
Should I PR?

**Comment by mattwojo** [comment]
Thank you for the offer @weitzhandler -- agree that this is worth adding to the docs. It sounds like @ryfu-msft already has these updates in the works.
