### ISSUE TITLE
No instructions to *disable* native debug visualization for C++/WinRT

### ISSUE THREAD

**Issue by adrianstephens** [MicrosoftDocs/windows-uwp#4629]
I do not use C++/WinRT; I use my own language projection that I prefer (and predates the official one).
But now I cannot inspect my variables in the local or watch windows because something is intercepting them and displaying '<Refresh to view properties>'
I'd like to disable whatever is doing this so I can display my variables the way I want.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2847134-e649-eb27-cb63-2e36e84d77c2
* Version Independent ID: 35538df1-c70f-fbbc-9988-a95efbfbc2af
* Content: [Visual Studio native debug visualization for C++/WinRT - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/natvis)
* Content Source: [uwp/cpp-and-winrt-apis/natvis.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/cpp-and-winrt-apis/natvis.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @adrianstephens, and sorry for the delay in responding. We're thinking that the simplest solution is for you to remove the **C++/WinRT templates and visualizer for VS2022** Visual Studio extension (VSIX).

Thanks!
-Steve
