### ISSUE TITLE
Additional information on Binding and Tensors

### ISSUE THREAD

**Issue by morehavoc** [MicrosoftDocs/windows-uwp#463]
I am attempting to load the tiny_yolov2 model from the onnx zoo but I don't understand how to create the appropriate sized output array/tensor.  The code generation tool creates an output called "grid" that is an IList<double> but the documentation for the model (and what is listed in OutputFeatures) describes an array of size 1x125x13x13.  I have not been able to figure out how to create a variable that the bind() method will accept for the output.  All I get is the following error:

The binding is incomplete or does not match the input/output description. (Exception from HRESULT: 0x88900002)

It would be awesome if you could include some more complex samples and/or some more documentation on how to build proper variables for binding, in particular, high dimension Tensors as described by TensorVariableDescriptorPreview.

Really cool stuff, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2a2373-e2eb-6293-0692-35496c764316
* Version Independent ID: 31bf9697-e7e8-35cd-20c3-f0499ed84919
* Content: [Integrate a model into your app with Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/integrate-model)
* Content Source: [windows-apps-src/machine-learning/integrate-model.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/integrate-model.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Hi! Have you tried creating input/output variables that exactly match the generated Input/output classes? A tensor type, regardless of its dimension, is mapped to IList<data type> on Windows runtime.

**Comment by morehavoc** [comment]
Hi!  The code generation tool creates this default output class (I edited names to make it more usable):
```
public sealed class TinyYoloModelOutput
{
        public IList<double> grid { get; set; }
        public TinyYoloModelOutput()
        {
            this.grid = new List<double>();
        }
}
```

Which seems to match the output object (There is only one) that is of DataType "Double" and ModelFeatureKind "Tensor" with a shape of [1, 125, 13, 13].

So on first glance, it seems like what is generated should work, but I get an error thrown when I do the following binding: `binding.Bind("grid", output.grid);`

The error is always the same, and is thrown from the output binding, not on the input binding.  `The binding is incomplete or does not match the input/output description. (Exception from HRESULT: 0x88900002)`

Here is the complete code, with a little bit of debug/error code added to it as I was testing:
```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.AI.MachineLearning.Preview;
using System.Linq;

// d224f87054234871a169eda0b7463d86

namespace YOLOApp1.ML2
{
    public sealed class TinyYoloModelInput
	{
        public VideoFrame image { get; set; }
    }

    public sealed class TinyYoloModelOutput
	{
        public IList<double> grid { get; set; }
        public TinyYoloModelOutput()
        {
            this.grid = new List<double>();
        }
    }

    public sealed class TinyYoloModel
	{
        private LearningModelPreview learningModel;
        public static async Task<TinyYoloModel> CreateTinyYoloModel(StorageFile file)
        {
            LearningModelPreview learningModel = await LearningModelPreview.LoadModelFromStorageFileAsync(file);
           TinyYoloModel model = new TinyYoloModel();
            model.learningModel = learningModel;
	    var outputs = learningModel.Description.OutputFeatures.ToList();
	    var shape = (outputs.First() as TensorVariableDescriptorPreview).Shape.ToList();
	    return model;
        }
        public async Task<TinyYoloModelOutput> EvaluateAsync(TinyYoloModelInput input) 
        {
			try
			{
				TinyYoloModelOutput output = new TinyYoloModelOutput();
				LearningModelBindingPreview binding = new LearningModelBindingPreview(learningModel);
				binding.Bind("image", input.image);
				binding.Bind("grid", output.grid);
				LearningModelEvaluationResultPreview evalResult = await learningModel.EvaluateAsync(binding, string.Empty);
				return output;
			}
			catch(Exception e)
			{
				throw e;
			}
        }
    }
}
```

**Comment by serenaz** [comment]
Was `binding.Bind("grid", output.grid);` from the generated code?

I don't think you need to explicitly bind the output. EvaluateAsync returns the output. Try:

`TinyYoloModelOutput output = learningModel.EvaluateAsync(input);`

**Comment by morehavoc** [comment]
Yes, the binding for the output was part of the generated code.

I took the output binding out.  The learningModel is of type `LearningModelPreview` so the ExecuteAsync method is defined as: `public IAsyncOperation<LearningModelEvaluationResultPreview> EvaluateAsync(LearningModelBindingPreview binding, string correlationId);`

It looks like that `LearningModelEvaluationResultPreview` class should have output on it, if the Evalulate would run, but EvaluateAsync still takes a binding object.  When I run it without binding the output, I get the same error, this time thrown by the `await learningModel.EvaluateAsync(binding, string.empty)` line.  The code looks like this now:
```
public async Task<TinyYoloModelOutput> EvaluateAsync(TinyYoloModelInput input) {
			try
			{
				TinyYoloModelOutput output = new TinyYoloModelOutput();
				LearningModelBindingPreview binding = new LearningModelBindingPreview(learningModel);
				binding.Bind("image", input.image);
				LearningModelEvaluationResultPreview evalResult = await learningModel.EvaluateAsync(binding, string.Empty);
				return output;
			}
			catch(Exception e)
			{
				throw e;
			}
        }
```

`The binding is incomplete or does not match the input/output description. (Exception from HRESULT: 0x88900002)`

Does that mean that the input binding is bad, or that the output is requried to be bound (the `IsRequired` Flag is true in the `TensorVariableDescriptorPreview` for the output)?

I then saw in the documentation that the EvaluateAsync method that the generated code is using doesn't even seem to be there: https://docs.microsoft.com/en-us/uwp/api/windows.ai.machinelearning.preview.learningmodelpreview

So, I tried `EvaluateFeaturesAsync`, which takes a `Dictionary<string, object>`, but I get the same error.

**Comment by serenaz** [comment]
Are you calling these wrapper classes from another code file in your app? The generated code should (hopefully) not need to be modified, and acts as an interface to interact with the model in your app. In your app's main code, something like this should work (let me know if you're getting the same error?):

```csharp
StorageFile modelFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri($"ms-appx:///Assets/tiny_yolov2.onnx"));
TinyYoloModel model = TinyYoloModel.CreateTinyYoloModel(modelFile);
TinyYoloModelInput ModelInput = new TinyYoloModelInput();
ModelInput.image = //get image here
TinyYoloModelOutput ModelOutput = model.EvaluateAsync(ModelInput);
```

**Comment by morehavoc** [comment]
Thanks for your help with this!

Yes, I am calling these from elsewhere, but started getting that error and the only documentation I could find was about instantiating dictionaries so I started making changes trying different data types.

I created a brand new solution and added the existing item tiny_yolov2.onnx to Assets to generate a fresh set of wrapper classes.  I tried to make this version as simple as possible, and I didn't edit the generated wrapper classes at all (not even to rename them).  I am calling the code like this:
```c#
public async void LoadModel()
{
	StorageFile modelFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri($"ms-appx:///Assets/tiny_yolov2.onnx"));
	this._model = await D224f87054234871a169eda0b7463d86Model.CreateD224f87054234871a169eda0b7463d86Model(modelFile);


	D224f87054234871a169eda0b7463d86ModelInput ModelInput = new D224f87054234871a169eda0b7463d86ModelInput();
	var imageFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri($"ms-appx:///Assets/DogScaled.jpg"));

	SoftwareBitmap softwareBitmap;
	using (IRandomAccessStream imageStream = await imageFile.OpenAsync(FileAccessMode.Read))
	{
		BitmapDecoder decoder = await BitmapDecoder.CreateAsync(imageStream);

		// Get the SoftwareBitmap representation of the file in BGRA8 format
		softwareBitmap = await decoder.GetSoftwareBitmapAsync();
		softwareBitmap = SoftwareBitmap.Convert(softwareBitmap, BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied);
	}
	VideoFrame inputImage = VideoFrame.CreateWithSoftwareBitmap(softwareBitmap);
	ModelInput.image = inputImage;
	D224f87054234871a169eda0b7463d86ModelOutput ModelOutput = await this._model.EvaluateAsync(ModelInput);
}
```

I don't know if this is important, but I manually resized the image so that it was 416x416 so that I didn't have to include the resize code here (again, I'm not sure I even need to resize the image).

I get the same error message, which originates on the line `binding.Bind("grid", output.grid)`: `The binding is incomplete or does not match the input/output description. (Exception from HRESULT: 0x88900002)`

I could zip up the enture UWP solution if that would help.

The generated tiny_yolov2.cs file:
```c#
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.AI.MachineLearning.Preview;

// d224f87054234871a169eda0b7463d86

namespace YoloApp2
{
    public sealed class D224f87054234871a169eda0b7463d86ModelInput
    {
        public VideoFrame image { get; set; }
    }

    public sealed class D224f87054234871a169eda0b7463d86ModelOutput
    {
        public IList<double> grid { get; set; }
        public D224f87054234871a169eda0b7463d86ModelOutput()
        {
            this.grid = new List<double>();
        }
    }

    public sealed class D224f87054234871a169eda0b7463d86Model
    {
        private LearningModelPreview learningModel;
        public static async Task<D224f87054234871a169eda0b7463d86Model> CreateD224f87054234871a169eda0b7463d86Model(StorageFile file)
        {
            LearningModelPreview learningModel = await LearningModelPreview.LoadModelFromStorageFileAsync(file);
            D224f87054234871a169eda0b7463d86Model model = new D224f87054234871a169eda0b7463d86Model();
            model.learningModel = learningModel;
            return model;
        }
        public async Task<D224f87054234871a169eda0b7463d86ModelOutput> EvaluateAsync(D224f87054234871a169eda0b7463d86ModelInput input) {
            D224f87054234871a169eda0b7463d86ModelOutput output = new D224f87054234871a169eda0b7463d86ModelOutput();
            LearningModelBindingPreview binding = new LearningModelBindingPreview(learningModel);
            binding.Bind("image", input.image);
            binding.Bind("grid", output.grid);
            LearningModelEvaluationResultPreview evalResult = await learningModel.EvaluateAsync(binding, string.Empty);
            return output;
        }
    }
}
```

**Comment by serenaz** [comment]
It appears that Windows.AI.MachineLearning.Preview does not currently support the `double` data type, which is probably the reason for the binding error. You can try using a model that uses a `float` data type - we'll try to get the ONNX model zoo to update this model!

**Comment by morehavoc** [comment]
Ok, thanks for your help.

**Comment by mx-iao** [comment]
Hi @morehavoc, we have updated the [ONNX model](https://github.com/onnx/models/tree/master/tiny_yolov2) to output to type `float`

**Comment by morehavoc** [comment]
Hi @serenaz, thanks!  I see the ticket over at the Onnx model zoo now.  I just created a fresh app to test it and I got a new error.  The good news is that it now has a Float data type, so that all looks good.  However, the previous version of the model had an output size of `[1, 125, 13, 13]` but this new one has `[-1, 125, 13, 13]`. (note the leading -1)

The actual error that I'm getting is this: `The size of the buffer provided for a bound variable is invalid. (Exception from HRESULT: 0x88900004)`

I would appreciate any help you could provide.  If you think this is a model issue, I'll move over to the ONNX models repo.

**Comment by serenaz** [comment]
We're investigating the issue from both the ONNX and WinML sides  - will let you know once we resolve the issue!

**Comment by sathiyasankar** [comment]
Hi @Serenaz, Do you have any update on this issue?

**Comment by JeffBrand** [comment]
Hitting the same issue.... would be nice to get an update.
