### ISSUE TITLE
Missing expression after unary operator

### ISSUE THREAD

**Issue by BlackLucife** [MicrosoftDocs/windows-uwp#4632]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf54ba9-53bd-e5d0-3b5a-e5b003f356d9
* Version Independent ID: ed2c403c-7bba-9647-fb5c-da556cb93a6b
* Content: [upgrade Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/upgrade)
* Content Source: [hub/package-manager/winget/upgrade.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/upgrade.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by denelon** [comment]
@BlackLucife can you provide some additional details?

**Comment by mattwojo** [comment]
Closing as no further info has been provided.
