### ISSUE TITLE
Quick Accent doesn't have Greek letters anymore

### ISSUE THREAD

**Issue by masterrite** [MicrosoftDocs/windows-uwp#4638]
I updated to PowerToys 0.74.0 and I found that Quick Accent doesn't have Greek letters anymore. I work in a research lab and I have to use Greek letters often. It used to be really convenient. Please add Greek back. Thank you

**Comment by alvinashcraft** [comment]
Hi @masterrite. This should be resolved with PowerToys 0.74.1. If it doesn't resolve your issue, you can open an issue with the product's repository. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
