### ISSUE TITLE
The code on this page is incomplete

### ISSUE THREAD

**Issue by mysorian** [MicrosoftDocs/windows-uwp#464]
Accessing resources in the Framework Elements example (Page, Border) is incomplete. The TextBox or any other control is not in XAML and in Xaml.cs as noted here:
http://hodentekhelp.blogspot.com/2018/04/uwp-how-do-you-access-page-resources-by_16.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6822f33-819b-ae6f-95cd-04861fa46dca
* Version Independent ID: 12e5988d-2aa1-0284-4f75-3b0cfb17177c
* Content: [ResourceDictionary and XAML resource references - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references)
* Content Source: [windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
> The TextBox or any other control is not in XAML and in Xaml.cs

Sorry, can you be more specific? How does the blog post relate to the doc article?
