### ISSUE TITLE
need help not working, thx

### ISSUE THREAD

**Issue by Harleybarley305gmailcom** [MicrosoftDocs/windows-uwp#4640]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 672f603e-cc47-9fb6-14d4-43f327b74ebb
* Version Independent ID: 672f603e-cc47-9fb6-14d4-43f327b74ebb
* Content: [Dev Home extensions](https://learn.microsoft.com/en-us/windows/dev-home/extensions)
* Content Source: [hub/dev-home/extensions.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/extensions.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@Harleybarley305gmailcom - Closing as these issues are intended to be used for updating documentation. Please see the Windows DevHome product repo: [https://github.com/microsoft/devhome/issues](https://github.com/microsoft/devhome/issues) to report a bug related to using Dev Home. They will need more details about what isn't working.
