### ISSUE TITLE
Use cases?

### ISSUE THREAD

**Issue by RichSPK** [MicrosoftDocs/windows-uwp#4641]
Is Crop And Lock useful when sharing your screen in Teams meetings so your shared screen isn't too small to read?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Version Independent ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Content: [PowerToys Crop And Lock for Windows](https://learn.microsoft.com/en-us/windows/powertoys/crop-and-lock)
* Content Source: [hub/powertoys/crop-and-lock.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/crop-and-lock.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @RichSPK. Thanks for your question. While there's no zoom built into the Crop And Lock feature, it could be useful for creating a window that contains only a part of another application and share that cropped window in Teams. You could then use the built-in Magnifier Tool in Windows to zoom in/out. I've created an internal work item to add some use cases to this topic in the docs. 

While I'm closing this issue, I will continue to monitor the comments for any additional thoughts or questions you may have. Thanks again!
