### ISSUE TITLE
If formatting the pc what will happen to the dev drive?

### ISSUE THREAD

**Issue by AliDadfar09** [MicrosoftDocs/windows-uwp#4644]
Hello,
I someone could please let me know, what would happen if i formatted my pc with a dev drive?

**Comment by mattwojo** [comment]
Hi @AliDadfar09 - Clean installing a machine (pc) while keeping the Dev Drive would be the same as moving the Dev Drive to a different machine. You would detach the Dev Drive, which would also detach the associated security filters and make the drive "untrusted"... so when re-mount the Dev Drive, it would be treated as an ordinary storage volume without special filter attach policies to speed up performance until you update the Dev Drive to a "trusted" status again... just as though you were attaching it to an entirely new machine. See [How do I designate a Dev Drive as trusted?](https://learn.microsoft.com/windows/dev-drive/#how-do-i-designate-a-dev-drive-as-trusted).
Does that answer your question?

**Comment by AliDadfar09** [comment]
Thanks @mattwojo I really appreciate your help. 😁
