### ISSUE TITLE
Bring Back Previous Features

### ISSUE THREAD

**Issue by Berlichu** [MicrosoftDocs/windows-uwp#4645]
Why remove a ton of things that were useful, like the diacritics, Greek letters, and mathematical symbols? Bring those back, while also having the new features too. Greek letters and diacritics were especially useful for me, as I engage in endeavors involving languages, and quickly accessing Greek letters and using diacritics has always been handy. So, I'd like if they were brought back.

**Comment by mattwojo** [comment]
@Berlichu -- We need a bit more context for what you're referring to here. Is this about PowerToys Quick Accent? https://learn.microsoft.com/windows/powertoys/quick-accent

**Comment by alvinashcraft** [comment]
Hi @Berlichu. It sounds like you're referring to PowerToys Quick Accent. They released a fix for this issue in **PowerToys 0.74.1** this week. Here's a [link](https://github.com/microsoft/PowerToys/issues/28785) to an issue filed against the product that was resolved this week.

If this is not about Quick Accent, please re-open and provide more info. Thanks!

**Comment by Berlichu** [comment]
> @Berlichu -- We need a bit more context for what you're referring to here. Is this about PowerToys Quick Accent? https://learn.microsoft.com/windows/powertoys/quick-accent

Yes, forgot to mention that.

**Comment by Berlichu** [comment]
> Hi @Berlichu. It sounds like you're referring to PowerToys Quick Accent. They released a fix for this issue in **PowerToys 0.74.1** this week. Here's a [link](https://github.com/microsoft/PowerToys/issues/28785) to an issue filed against the product that was resolved this week.
> 
> If this is not about Quick Accent, please re-open and provide more info. Thanks!

Thanks for understanding, and for the fix.
