### ISSUE TITLE
Useful to link to download instructions

### ISSUE THREAD

**Issue by ikjordan** [MicrosoftDocs/windows-uwp#4647]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Version Independent ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Content: [PowerToys File Locksmith utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith)
* Content Source: [hub/powertoys/file-locksmith.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-locksmith.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks, @ikjordan. I added two "see also" links to the bottom of the page to link to the PowerToys overview and PowerToys install pages. The PR should be live shortly.
