### ISSUE TITLE
Gradle (.gradle) Cache in Storing package cache on Dev Drive section

### ISSUE THREAD

**Issue by GerGerApex1** [MicrosoftDocs/windows-uwp#4654]
since maven have an entry for maven (.m2) cache why not also have gradle?
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by mattwojo** [comment]
Thanks for filing this issue! Added Gradle - Resolved in https://github.com/MicrosoftDocs/windows-dev-docs/pull/4858
