### ISSUE TITLE
Npm cache (NodeJS) folder on Windows may also be `%LocalAppData%\npm-cache`

### ISSUE THREAD

**Issue by RickyLin** [MicrosoftDocs/windows-uwp#4655]
> If you have already installed NodeJS on your machine, move the contents of `%AppData%\npm-cache` to this directory.

On my computer, it's not `%AppData%\npm-cache` but `%LocalAppData%\npm-cache`, probably it's good to mention this folder as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for contributing this issue @RickyLin! I added that directory location for NPM to the doc in https://github.com/MicrosoftDocs/windows-dev-docs/commit/0a053fc99d2eeadc2f5b15c87e989b49f73bf26b.
