### ISSUE TITLE
Feature Request: `winget install "the first one"`

### ISSUE THREAD

**Issue by simeydk** [MicrosoftDocs/windows-uwp#4656]
This is a feature request. Here's my story:

This is a common "sharp edge" I encounter that I wish could have a nicer UX:

```
PS C:\Users\satya> winget install office
Multiple packages found matching input criteria. Please refine the input.
Name                              Id               Source
----------------------------------------------------------
Microsoft 365 (Office)            9WZDNCRD29V9     msstore
Microsoft 365 Apps for enterprise Microsoft.Office winget
```

At this point, I now need to go copy or retype something more specific based on the output above. 

However, I would love to now be given a TUI to press up/down to select one of the options, or be able to follow this up with some variation of `winget install --prev 1` or something of the like, rather than having to reach for my mouse to now go and select and copy an Id.

Would this be possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73bd6478-de0f-6aa9-fb31-0818abdb7f68
* Version Independent ID: f5ff6ecd-0231-d438-7301-6eb20863ec50
* Content: [install Command](https://learn.microsoft.com/en-us/windows/package-manager/winget/install)
* Content Source: [hub/package-manager/winget/install.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/install.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @simeydk - I apologize for my slow reply here! I'm just getting caught up on my backlog of issues. Unfortunately, I'm not much help with this one as it's more of a product feature request than a doc update. Could you please re-file this request in the WinGet product repo here: https://github.com/microsoft/winget-cli/issues
