### ISSUE TITLE
VM Properties lists the API level for Android subsystem at 32 when it should be 33 since the Android Subsystem runs Android 13.   ---

### ISSUE THREAD

**Issue by meek2100** [MicrosoftDocs/windows-uwp#4659]
VM Properties lists the API level for Android subsystem at 32 when it should be 33 since the Android Subsystem runs Android 13.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://learn.microsoft.com/en-us/windows/android/wsa/)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @meek2100! Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/798ff7dc794fea2f3e09c47ea105df3e7a14649f
