### ISSUE TITLE
Required Title property should be called out with a Warning block

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#4662]
In this section:

https://learn.microsoft.com/en-us/windows/uwp/app-to-app/share-data#set-properties

It's easy to miss the line at the end (it should be put in a warning/note type block/callout):

> All properties except the title are optional. The title property is mandatory and must be set.

If `Title` is not set, then the Share UI displays a generic (unhelpful) message:

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/24302614/2d9519ef-6ca4-4a79-9c19-91b7135dc4bf)

> Try that again - We couldn't show you all the ways you could share.

The docs should more clearly call this out in a warning block or something (whatever style dictates). Though it'd also be nice if the APIs had reported an error or a better diagnostic message for the developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dc81a22-489f-8bee-4440-425a5855ff45
* Version Independent ID: f7c7dd9d-c138-659b-9be7-8ac9946e3400
* Content: [Share data - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/app-to-app/share-data)
* Content Source: [uwp/app-to-app/share-data.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/app-to-app/share-data.md)
* Product: **uwp**
* Technology: **communication**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks, @michael-hawker. I wrapped that line in a warning block like you suggested. The changes are merged and should be reflected on the live site shortly.
