### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by thecosmicmuffet** [MicrosoftDocs/windows-uwp#4663]
"Declare a package to be an extension
A package identifies itself as a package extension by declaring the **<uap17:PackageExtensionHost>** element in its Package.appxmanifest file. The following example shows an example package declaring itself as an extension"

The text appears to be a copy paste of the host instructions further up, and incorrectly says that the extension should declare itself a PackageExtensionHost. In the code, the correct capability appears to be "<uap17:PackageExtension Name="com.microsoft.ai.aiexplorer.model" 
           Id="power" 
           DisplayName="x^y" 
           PublicFolder="Public"
		   Description="Exponent"> "

**Comment by drewbatgit** [comment]
@thecosmicmuffet Thanks for catching this! The fix has been made.
