### ISSUE TITLE
Segoe Fluent Icons not up to date

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4666]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e1f4b4-3d25-c08c-e3b0-12011d3bba0f
* Version Independent ID: 3b140070-493f-0b2c-f7c4-3fb89192d2d0
* Content: [Segoe Fluent Icons font - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font)
* Content Source: [hub/apps/design/style/segoe-fluent-icons-font.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/style/segoe-fluent-icons-font.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Jay-o-Way** [comment]
Enter feedback please
