### ISSUE TITLE
DevDrive pane does not tell me why I cannot create DevDrive

### ISSUE THREAD

**Issue by KevinLaMS** [MicrosoftDocs/windows-uwp#4667]
Running Dev Home in Azure VM and tried to create a Dev Drive
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/2146880/13bf44a9-a76a-432f-8faf-30f73a569338)

As you can see, I filled in all the pieces yet could not create the drive. It gives me no feedback on what I need to do or if it simply is not supported.

kevin

**Comment by mattwojo** [comment]
@KevinLaMS - Thanks for filing this issue. It sounds lie this may be related to the VM size being too small. Closing as we are discussing via email and creating a DevOps product bug. Will reassess whether this should be noted in an FAQ in the docs.
