### ISSUE TITLE
Which category covers HoloLens? (IoT x86 or Mobile) ?

### ISSUE THREAD

**Issue by danilogr** [MicrosoftDocs/windows-uwp#467]
What are the basic codecs that one should expect HoloLens to support? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181085f-2eaa-6eb5-06fd-52c3a98f7467
* Version Independent ID: 240818b0-d509-bbcf-f485-7ca0ba55f0f6
* Content: [Supported codecs - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/supported-codecs)
* Content Source: [windows-apps-src/audio-video-camera/supported-codecs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/supported-codecs.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
HI there, sorry for the extremely delayed response to this issue. I have reached out to the Hololens team to see if they can provide a list of codecs that they support out of the box, but they have been slow in providing a response. I would suggest that you may be able to get a response by posing this question in the Hololens documentation repo. 

https://github.com/MicrosoftDocs/Hololens
