### ISSUE TITLE
Cannot find the Create Dev Drive option inside Storage > Disks & Volumes

### ISSUE THREAD

**Issue by DeLiKoO** [MicrosoftDocs/windows-uwp#4670]
Hello !
I've been updating to 22H2 build 2428 and trying to setup a Dev Drive with no luck
On my setup, the option is missing from Disks & Volumes
As I've seen another GitHub issue mentionning it, I tried to enable Hyper-V + reboot with no effect
Do someone know if I also need to enable the "Containers" feature ? Is it something else ?

Please see the attached screen capture (please pardon my french)
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/67643809/9bf09449-3448-4862-936d-1b0f3b3a0465)

**Comment by mattwojo** [comment]
Hi @DeLiKoO - First, I'm sorry that you've run into this trouble after updating. Second, I'm still getting caught up on responding to these issues, so apologies for the delay. Has your issue resolved? 

I see in this blog that there was an additional Windows update patch to try if Dev Drive wasn't appearing: https://devblogs.microsoft.com/engineering-at-microsoft/dev-drive-is-now-available/

I'm thinking that this was a temporary update issue and not something that I should be adding to a documentation update, so I'm closing this issue, but if you find that not to be the case, please re-open. 

Also happy to try to help if you're still experiencing trouble, just share more details about what version you're running and we can try to get to the bottom of it. Thanks again.
