### ISSUE TITLE
Vague framework star rating system

### ISSUE THREAD

**Issue by EddyHaigh** [MicrosoftDocs/windows-uwp#4672]
The star rating for enterprise and consumer apps is vague and needs an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4f71cb-6d3d-beec-7f5a-e9f7de83245e
* Version Independent ID: 0f4f71cb-6d3d-beec-7f5a-e9f7de83245e
* Content: [Windows app development - options and features - Windows apps](https://learn.microsoft.com/en-gb/windows/apps/get-started/dev-options)
* Content Source: [hub/apps/get-started/dev-options.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/dev-options.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by dotMorten** [comment]
I'd also be really curious what causes one framework to get 2 stars, and another 5. What would I be losing out on if I choose the 2-star framework?
Also it's not clear to me how consumer and enterprise apps really differ in this context, beyond the target-audience. I want to build equally good apps regardless of whether my users are consumer or B2B.

**Comment by alvinashcraft** [comment]
I think we're going to remove these two rows and find a better way to communicate the differences between the frameworks. This page is meant to be a comparison without providing recommendations, and the ratings rows are working against that goal.

**Comment by dotMorten** [comment]
@alvinashcraft I mean I appreciate the honesty here... it does beg the question why WinUI isn't going for getting 5 stars here, but I guess that's a question for the sdk team, not the doc itself.

**Comment by alvinashcraft** [comment]
I did remove them, and I'll think of some additional features to compare instead. The table fits better on the screen now too.
