### ISSUE TITLE
dev

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4674]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acdf7266-5a5a-10a9-25bc-94f01b3e5d0a
* Version Independent ID: acdf7266-5a5a-10a9-25bc-94f01b3e5d0a
* Content: [Dev Home for Windows Developers](https://learn.microsoft.com/en-in/windows/dev-home/#dev-home-dashboard-widgets)
* Content Source: [hub/dev-home/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported.
