### ISSUE TITLE
مساعده لي في فتح هاتفي المغلق القفل 

### ISSUE THREAD

**Issue by firasdlke** [MicrosoftDocs/windows-uwp#4676]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 06f54870-f12b-d72f-3899-a188bba87627
* Version Independent ID: 06f54870-f12b-d72f-3899-a188bba87627
* Content: [Publish your app in the Microsoft Store - Windows apps](https://learn.microsoft.com/ar-sa/windows/apps/publish/publish-your-app/overview)
* Content Source: [hub/apps/publish/publish-your-app/overview.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/overview.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by firasdlke** [comment]
> 
> [اكتب ملاحظاتك هنا]
> 
> 
> ---
> #### تفاصيل المستند
> 
> ⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*
> 
> * ID: 06f54870-f12b-d72f-3899-a188bba87627
> * Version Independent ID: 06f54870-f12b-d72f-3899-a188bba87627
> * Content: [Publish your app in the Microsoft Store - Windows apps](https://learn.microsoft.com/ar-sa/windows/apps/publish/publish-your-app/overview)
> * Content Source: [hub/apps/publish/publish-your-app/overview.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/overview.md)
> * Product: **reunion**
> * Technology: **apps**
> * GitHub Login: @GrantMeStrength
> * Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
No comment found in the text. Please re-open with more details if you are reporting a documentation issue.
