### ISSUE TITLE
dev drive unclear bullet text, subject of sentence is unclear, etc.

### ISSUE THREAD

**Issue by diablodale** [MicrosoftDocs/windows-uwp#4679]
On
https://learn.microsoft.com/en-us/windows/dev-drive/#what-scenarios-are-unsupported-by-dev-drive-what-are-the-limitations
the 2nd bullet
> When creating a VHD hosted by a fixed disk, it is not safe to copy the VHD, move it to a different machine, and then return to using it as a Dev Drive.

1. The first clause has no clarity on what that vhd *is*. Is it any random VHD? Is it a VHD-based dev drive? Much context is missing.
2. What is the process that you are warning? Can't move a VHD or dev drive without doihgn several steps like taking it offline or disabling or removing, etc.
3. That last clause suggests that something (VHD?) was a dev drive but that was never established prior. So this clause is incorrect or unclear.
4. Finally, rework the entire sentence to not use a (in)dependent clause at the beginning. It adds to the ambiguity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for filing this issue @diablodale. I rewrote the sentence about moving a VHD, hopefully improving the clarity.

**Comment by diablodale** [comment]
Please link the PR so I can review your updates, to complete the "circle"
