### ISSUE TITLE
The App development frameworks table is confusing

### ISSUE THREAD

**Issue by mattleibow** [MicrosoftDocs/windows-uwp#4681]
Is the sandbox row/feature good or bad? Right now it looks like sandbox is good, and the ones without it are bad?
But also, this does not support the things that do support BOTH scenarios - WinUI, and by extension MAUI - support AppConatiner AND just a folder/unpackaged/exe.

Maybe the row should be split into 2?

* Supports Sandbox
* Supports non-sandbox (whatever we call it these days... "normal" mode?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4f71cb-6d3d-beec-7f5a-e9f7de83245e
* Version Independent ID: 0f4f71cb-6d3d-beec-7f5a-e9f7de83245e
* Content: [Windows app development - options and features - Windows apps](https://learn.microsoft.com/en-us/windows/apps/get-started/dev-options#app-development-frameworks)
* Content Source: [hub/apps/get-started/dev-options.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/dev-options.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by BethMassi** [comment]
We should also add Blazor Hybrid to this doc. 

_Update table:_ 

Feature: Blazor Hybrid
Language: C#
UI Language: Razor
UI designer: no
UI debugging: Hot reload (https://learn.microsoft.com/en-us/aspnet/core/test/hot-reload)
Fluent Design: check
.NET: .NET MAUI, WPF, Winforms
Windows App SDK: check (via MAUI) https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code
Great for touch: check 
Cross-platform: check (via MAUI)
Xbox/HoloLens: no-check
Sandboxing: no-check
Currently supported: check
Recieving updates: check
Roadmap: GitHub https://aka.ms/aspnet/roadmap

Learn more about each of these options:

_Add to list_ -  Blazor Hybrid Apps: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid

**Comment by mattleibow** [comment]
Also saw this: 

 - https://learn.microsoft.com/en-us/windows/msix/msix-container#configure-a-winui-3-project-for-appcontainer
 - https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes

**Comment by alvinashcraft** [comment]
> Also saw this:
> 
> * https://learn.microsoft.com/en-us/windows/msix/msix-container#configure-a-winui-3-project-for-appcontainer
> * https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes

I left out anything about any packaged Win32/Desktop apps running with trustLevel set to AppContainer to achieve sandboxing because I don't think it currently works. I heard it's going to be fixed in an upcoming release. When I try to follow the steps in the first link you provided, I get an error when VS tries to deploy/run the project:

`DEP0700: Registration of the app failed. [0x80080204] error 0x80080204: App manifest validation error: Line 26, Column 6, Reason: The element specified requires "runFullTrust" capability.`

**Comment by alvinashcraft** [comment]
> We should also add Blazor Hybrid to this doc.
> 
> _Update table:_
> 
> Feature: Blazor Hybrid Language: C# UI Language: Razor UI designer: no UI debugging: Hot reload (https://learn.microsoft.com/en-us/aspnet/core/test/hot-reload) Fluent Design: check .NET: .NET MAUI, WPF, Winforms Windows App SDK: check (via MAUI) https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code Great for touch: check Cross-platform: check (via MAUI) Xbox/HoloLens: no-check Sandboxing: no-check Currently supported: check Recieving updates: check Roadmap: GitHub https://aka.ms/aspnet/roadmap
> 
> Learn more about each of these options:
> 
> _Add to list_ - Blazor Hybrid Apps: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid

Thanks, Beth. That's a great idea. I'll get a PR together to add Blazor Hybrid.

**Comment by jaigak** [comment]
I think this page should not include all the wrapper frameworks because then you will have to include everything (why not have more popular frameworks like Qt in there?). Instead, it makes more sense to only include official options and then maybe mention cross-platform options in a separate list and specify how they are related to the official option (eg: MAUI wraps WinUI 3 on Windows).

**Comment by jaigak** [comment]
Another thing is that only UWP supporting AppContainer is highly misleading. It is more like UWP forces AppContainer while others don't.

**Comment by alvinashcraft** [comment]
Thanks for everyone's feedback. We're going to leave the options as they are for the moment and gather additional input from the product teams and the community. Some rows like the AppContainer/Sandboxing might need more nuanced options like Required/Supported/Not Available, but we're attempting to keep this page as a simple and objective list of features. More details can be added on other pages like the [Overview of dev options](https://learn.microsoft.com/en-us/windows/apps/get-started/) or on dividual product docs pages which are linked from here below the table.

I'm creating an internal work item to continue updates to this page based on all the feedback.
