### ISSUE TITLE
Update json example in docs with raw string literal from C#11

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#4682]
C#11 introduced raw string literals: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/raw-string

This allows for directly embedding quoted content within a C# string, useful for XML and JSON payloads.

There are two places in the doc where JSON payloads are referenced in C# code:

https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-cs#declare-widget-template-json-strings
https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-cs#implement-iwidgetprovider2

These should be updated to use raw string literals so that JSON can be easily copied to/from the article for use in other tools or replaced with the developers own payload instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5a3713-5a3b-6cde-b947-cffc226ae1d2
* Version Independent ID: 2f5a3713-5a3b-6cde-b947-cffc226ae1d2
* Content: [Implement a widget provider in a C# Windows App - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-cs)
* Content Source: [hub/apps/develop/widgets/implement-widget-provider-cs.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/implement-widget-provider-cs.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I've updated this page to use C# 11 raw string literals.
