### ISSUE TITLE
Time and date activation command

### ISSUE THREAD

**Issue by djsmith** [MicrosoftDocs/windows-uwp#4683]
This page shows the _Time and date_ activation command as being `)` but I believe it is `(`.

I'm running PowerToys version 0.74.1 and I don't believe I modified the _Direct activation command_ for the _Time and Date_ plugin.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b951899-69ca-9057-f799-14491e1b0a74
* Version Independent ID: 18e0202f-3e91-a5b9-62f2-6cd40e5661a8
* Content: [PowerToys Run utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/run)
* Content Source: [hub/powertoys/run.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by Jay-o-Way** [comment]
Nope. We've had many of the exact same comments. A long time ago, it _was_ `(`, but that conflicts when trying to do math. For example: `(5+11)*pi` or anything like that. Therefore, the _default_ character was changed to `)`, but the settings of previous installations did not actively change. That would be too aggressive.

**Comment by Jay-o-Way** [comment]
There's a reason for the warning, nearby this list
