### ISSUE TITLE
Change C++/CX to C++/Winrt

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#4687]
This page gives an example that uses C++/CX, which is of little help to those of us who are trying to use C++/WinRT.  Please update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b0077ac-da13-5f5e-09f5-c017a982b149
* Version Independent ID: 9b0077ac-da13-5f5e-09f5-c017a982b149
* Content: [Hello Win2D World - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/win2d/hellowin2dworld)
* Content Source: [hub/apps/develop/win2d/hellowin2dworld.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/win2d/hellowin2dworld.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks! I've added C++/WinRT code.

-Steve
