### ISSUE TITLE
Example fails to run.

### ISSUE THREAD

**Issue by yinhx3** [MicrosoftDocs/windows-uwp#4689]
[Enter feedback here]
Example fails to run, because the Window object doesn't have Resource property in WinUI3.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87a67999-cbcd-4306-ad58-3dac043ae523
* Version Independent ID: 87a67999-cbcd-4306-ad58-3dac043ae523
* Content: [Bind hierarchical data and create a master/details view with Windows App SDK - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/data-binding/bind-to-hierarchical-data-and-create-a-master-details-view)
* Content Source: [hub/apps/develop/data-binding/bind-to-hierarchical-data-and-create-a-master-details-view.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/data-binding/bind-to-hierarchical-data-and-create-a-master-details-view.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thank you for bringing this to our attention. The code and markup has been updated to run as expected.
