### ISSUE TITLE
Trained onnx file not usable.

### ISSUE THREAD

**Issue by RongBo74** [MicrosoftDocs/windows-uwp#469]
The trained result onnx file is 390KB, much larger than the file in Samples\UMP\MNIST_GetStarted\src\Assets\ . And the auto generated cs file has different ModelInput layout: public float Input3 { get; set; }, which is different from the original: public VideoFrame Input3 {get; set;}. And LearningModelPreview.LoadModelFromStorageFileAsync(***) loading the 390KB onnx file seems to crash. Please, any help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f15512d-f277-ce9e-3577-4bb4e5d53de5
* Version Independent ID: 89121bbd-97ed-1818-0471-40eb13003715
* Content: [How to train a model for Windows ML in Visual Studio - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/train-ai-model#feedback)
* Content Source: [windows-apps-src/machine-learning/train-ai-model.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/train-ai-model.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
We've updated the tutorial and script to generate a correctly formatted ONNX file. Please let us know if there are still issues!

**Comment by brong-nvidia** [comment]
The update solves the problem. Thx.

**Comment by RongBo74** [comment]
The update solves the problem. Thx.
