### ISSUE TITLE
developer settings broken

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [MicrosoftDocs/windows-uwp#4691]
when i try to open it it just closes and opens and wont let me click again to open it

**Comment by Karl-Bridge-Microsoft** [comment]
Need more info.

**Comment by GrantMeStrength** [comment]
Hi - can you tell us a little more? Where are you trying to open developer settings from?
As this is probably not a documentation issue, I'm going to close this issue, but if you had more information feel free to re-open it, or visit Microsoft Q&A and ask there.
Thanks, -John
