### ISSUE TITLE
Article References two Deprecated VSCode plugins

### ISSUE THREAD

**Issue by sitting-duck** [MicrosoftDocs/windows-uwp#4696]
[Enter feedback here]
Hey there, there are two plugins for VSCode referenced on this documentation page that are now deprecated. 

Here is the section where I found the references to two out of date VSCode Extensions, 
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/1289702/378c4ff0-512a-420f-a257-ac345b9b4c8a)

Settings Sync, I went and checked the extensions in VSCode and I can see that that plugin is now deprecated (see screenshot)
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/1289702/c91a18b4-f740-4430-894a-44d477584470)

Debugger for Chrome is also now deprecated. (see screenshot)
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/1289702/1088eb90-0b7f-4814-8511-906da3c35252)

These extensions seem like "nice to have" features, so either just removing these out of date sections or updating the doc to reference a more up to date plugin should be sufficient. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for contributing this issue! These were removed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/bc7f5d7dafddfdb2a492a0bfbe61f776d66da61d
