### ISSUE TITLE
Move C++/WinRT Documentation to Win App SDK

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#4699]
I'd love to see the entirety of the C++/WinRT documentation moved from UWP to Windows App SDK.  It's an easy port, right? ;-)  It's not obvious, but this page (https://learn.microsoft.com/en-us/windows/apps/get-started) implies that WinApp SDK is the future, so it would be nice to have as much help as I can get to move in that direction.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69a5ba76-77cf-1233-2903-fd3c34b5044c
* Version Independent ID: 163d07f1-7860-cd16-a572-ff429cdf7008
* Content: [C++/WinRT - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/)
* Content Source: [uwp/cpp-and-winrt-apis/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/cpp-and-winrt-apis/index.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @dr-eck. I've added a work item to my backlog to see about adding WinUI 3 (Windows App SDK) content up to parity with the UWP content currently in the C++/WinRT docs. I don't know exactly when I'll make a start on that, nor when it'll be done (it'll be significant work item). In any case, so as not to track it twice, I'll go ahead and close this issue.

Meanwhile, also see https://learn.microsoft.com/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/migrate-to-windows-app-sdk-ovw.

Thanks again! :)
-Steve

**Comment by dr-eck** [comment]
Hi Steve,

               Thanks for adding this to your backlog.  How do I “follow” you so I am alerted when you update any of the C++/WinRT documentation?

 

Steve Eckhardt
