### ISSUE TITLE
Invalid variable order

### ISSUE THREAD

**Issue by marticliment** [MicrosoftDocs/windows-uwp#4701]
When the WidgetProvider() class constructor definition is given, the variables widgetId and widgetName are swapped. This results in unrendered widgets when the widget provider is killed and started again by an already existing widget.

How it shows on the documentation:
```
// WidgetProvider.cs

public WidgetProvider()
{
    var runningWidgets = WidgetManager.GetDefault().GetWidgetInfos();

    foreach (var widgetInfo in runningWidgets)
    {
        var widgetContext = widgetInfo.WidgetContext;
        var widgetId = widgetContext.Id;
        var widgetName = widgetContext.DefinitionId;
        var customState = widgetInfo.CustomState;
        if (!RunningWidgets.ContainsKey(widgetId))
        {
            CompactWidgetInfo runningWidgetInfo = new CompactWidgetInfo() { widgetId = widgetName, widgetName = widgetId };
            try
            {
                // If we had any save state (in this case we might have some state saved for Counting widget)
                // convert string to required type if needed.
                int count = Convert.ToInt32(customState.ToString());
                runningWidgetInfo.customState = count;
            }
            catch
            {

            }
            RunningWidgets[widgetId] = runningWidgetInfo;
        }
    }
}

```

How it should be:

```
// WidgetProvider.cs

public WidgetProvider()
...
            CompactWidgetInfo runningWidgetInfo = new CompactWidgetInfo() { widgetId = widgetId, widgetName = widgetName };
...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5a3713-5a3b-6cde-b947-cffc226ae1d2
* Version Independent ID: 2f5a3713-5a3b-6cde-b947-cffc226ae1d2
* Content: [Implement a widget provider in a C# Windows App - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-cs)
* Content Source: [hub/apps/develop/widgets/implement-widget-provider-cs.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/implement-widget-provider-cs.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this! It has now been fixed.
