### ISSUE TITLE
Python for web

### ISSUE THREAD

**Issue by felicienmukamba** [MicrosoftDocs/windows-uwp#4702]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 733b92f5-7f7f-cc94-64b9-69462979fe0f
* Version Independent ID: 5096d0ec-24fc-23ae-b2ec-aa21acf273d5
* Content: [Web development with Python on Windows](https://learn.microsoft.com/en-us/windows/python/web-frameworks#hello-world-tutorial-for-django)
* Content Source: [hub/python/web-frameworks.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/python/web-frameworks.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported.

**Comment by felicienmukamba** [comment]
Thank you
