### ISSUE TITLE
Document criteria to decide Dev Drive setup option

### ISSUE THREAD

**Issue by Danielku15** [MicrosoftDocs/windows-uwp#4704]
https://learn.microsoft.com/en-gb/windows/dev-drive/#set-up-options lists various options on how to setup a dev drive. It would be great to know if there are certain impacts in the different options. 

I would assume that a VHD is slower than having a partition on a physical disk directly? Is this true and if yes, are there some performance metrics available? I (and I guess other devs) want to be able to decide whether it is worth investing the effort to repartition their drive to get a performance boost. 

From a gut feeling VHD has the option of being more portable at the cost of a worse performance. Also VHD has the benefit that it can be a dynamically sized volume while a physical partition is fixed. 

I could not find any good article or reference pointing out the difference between the options.

**Comment by AdamBraden** [comment]
There is nothing unique about Dev Drives when considering VHDs vs physical disks. VHD/VHDXs have overhead associated with them and the impact of that is dependent upon the device and host drive.

@mattwojo - recommend closing this issue.

**Comment by Danielku15** [comment]
I think most devs will first ever touch local VHD/VHDX mounting for actual use as part of dev-drives. I agree that VHD/VHDX overheads might not be special to dev drives, but documenting exactly these overheads as part of the dev drives documentation should be still considered. 

It doesn't matter much if the information is added directly to the dev drives or there is just a link/reference to another docs page as long the information is covered somewhere. 

Dev Drives are advertised as a major perf boost for developers, but not touching the performance impact of VHFX results in confusion or worse: performance degredation.

**Comment by mattwojo** [comment]
Thanks for contributing these thoughts @Danielku15. I've added a section about "How to choose between using a disk partition or VHD" to the Dev Drive doc: https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
