### ISSUE TITLE
.Net 3.5?

### ISSUE THREAD

**Issue by TaylorTWBrown** [MicrosoftDocs/windows-uwp#471]
Hey, so one things that's not clear in this document...

I have a Win32 application that depends on .NET framework version 3.5. Can I still pack these up?

Thanks,
Taylor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c403f296-ed93-2625-e414-f009194bf118
* Version Independent ID: aa0212c4-481c-7eaf-233d-c5b3f286d004
* Content: [Package an app using the Desktop App Converter (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter#command-reference)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-run-desktop-app-converter.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-run-desktop-app-converter.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hi TaylorTWBrown Thank you for your comment. The best beginning point is to review this article: [Prepare to Package an App ](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare). The first bullet in that article is the following:
"You need to make sure your app runs on .NET 4.6.2. You cannot require or redistribute versions earlier than 4.6.2. This is the version of .NET that shipped in the Windows 10 Anniversary Update. Verifying your app works on this version will ensure that your app will continue to be compatible with future updates of Windows 10. If your app targets the .NET Framework 4.0 or later, it is expected to run on .NET 4.6.2 but you should still test it." 
Sounds like it might be a good idea for us to add a link to this article near the top of the desktop app converter topic for visibility.

**Comment by normesta** [comment]
Added notes to the top of each packaging topic. Should appear live along with the content refresh this May.
