### ISSUE TITLE
240 UWP Samples versus 17 Windows App SDK???

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#4712]
The .NET Upgrade Assistant makes it easy to migrate apps from UWP to Windows App SDK, right?  When will the 240 UWP samples be migrated?  What I'd really like is to see the C++/CX versions migrated to C++/WinRT, but I'm not aware of an Assistant for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 106b8e66-730a-c48d-b547-42ebd9af8ab6
* Version Independent ID: f396349e-2083-b623-82bc-2372e9d33d18
* Content: [Sample applications for Windows development - Windows apps](https://learn.microsoft.com/en-us/windows/apps/get-started/samples)
* Content Source: [hub/apps/get-started/samples.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/samples.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @MatchaMatch
* Microsoft Alias: **mikben**

**Comment by stevewhims** [comment]
Thanks, @dr-eck. This is something that's on our radar. It's a long-term enough work item that I'm not sure this is the best place to track it (plus, this repo isn't the one that contains the actual samples).

It might not be a bad idea to file an issue against the actual sample apps repo: https://github.com/microsoft/Windows-universal-samples/issues.

I'll close this one meanwhile.

Thanks again!
-Steve
