### ISSUE TITLE
download link for the PowerToys.admx

### ISSUE THREAD

**Issue by MikeGuiz** [MicrosoftDocs/windows-uwp#4713]
Could you please provide a download link for the PowerToys.admx & adml files?  I am not able to find them anywhere, also not finding them locally.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79525a35-1bad-f8e8-530f-e897e3630159
* Version Independent ID: 79525a35-1bad-f8e8-530f-e897e3630159
* Content: [PowerToys Group Policy](https://learn.microsoft.com/en-us/windows/powertoys/grouppolicy)
* Content Source: [hub/powertoys/grouppolicy.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/grouppolicy.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @MikeGuiz. The way to get these files is documented in the "Download" section of the PowerToys Group Policy docs page. They are in a zip file with each PowerToys release. Thanks for your question!
