### ISSUE TITLE
Determine all available features of Dev Home showing the trailer

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/windows-uwp#4714]
ITNOA

In the Dev Home trailer Microsoft shows many features, but in real world, some few features exist, so please add page to determine, which feature exist and witch feature does not exist and help user to how to use these features

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b9172a-8e15-23aa-ac78-bea94db0da55
* Version Independent ID: c86dfa40-aa1b-6fa7-a918-a49b8b2a0605
* Content: [Setup a development environment on Windows](https://learn.microsoft.com/en-us/windows/dev-environment/)
* Content Source: [hub/dev-environment/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/index.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Windows Dev Home features are all listed and explained in the documentation here: https://learn.microsoft.com/en-us/windows/dev-home/  There will be some features marked as "Experimental" that may come and go, but will be listed in the Dev Home release notes if you want to track their history.
