### ISSUE TITLE
Page recommends deprecated extension, Node.js Extension Pack

### ISSUE THREAD

**Issue by superfamousdog** [MicrosoftDocs/windows-uwp#4715]
The steps on this page for nvm and node installation are very helpful, however, it recommends a deprecated extension, Node.js Extension Pack.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 745b8a68-b43b-83d2-54b6-32b3d2a35491
* Version Independent ID: 599d0cee-8710-86ef-8093-fe1b08e4aa90
* Content: [Set up NodeJS on native Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows)
* Content Source: [hub/dev-environment/javascript/nodejs-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for contributing this issue! This was removed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/bc7f5d7dafddfdb2a492a0bfbe61f776d66da61d
