### ISSUE TITLE
Script generates recursive environment variable for Maven packages directory

### ISSUE THREAD

**Issue by bent-rasmussen** [MicrosoftDocs/windows-uwp#4718]
I guess this[1]:

`setx /M MAVEN_OPTS "-Dmaven.repo.local=D:\packages\maven %MAVEN_OPTS%"`

should be that:

`setx /M MAVEN_OPTS "-Dmaven.repo.local=D:\packages\maven"`

[1] Proof:

```
mvm -v
Error: Could not find or load main class %MAVEN_OPTS%
Caused by: java.lang.ClassNotFoundException: %MAVEN_OPTS%
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by AdamBraden** [comment]
@mattwojo - the issue is correct, Remove the extra %Maven_Opts%

**Comment by mattwojo** [comment]
Thanks for pointing out this issue @bent-rasmussen!
Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
