### ISSUE TITLE
Restarting the computer was required to see the changed global-packages folder value

### ISSUE THREAD

**Issue by erhanalankus** [MicrosoftDocs/windows-uwp#4725]
On this page:
https://learn.microsoft.com/en-us/windows/dev-drive/#storing-package-cache-on-dev-drive

I did this:
> Set a global environment variable NUGET_PACKAGES to that path. For example: setx /M NUGET_PACKAGES D:\<username>\.nuget\packages

Then, this:
> To verify the global-packages folder, run the dotnet nuget locals command: dotnet nuget locals global-packages --list

The result of this command didn't show the changed value until I restarted my computer. Maybe a note about it should be added there.

**Comment by AdamBraden** [comment]
@mattwojo - can we add a statement at the end of the "Storing..." section that states:

After changing your environment variables, you may need to either restart all open console windows or reboot the device, to get the new values.

**Comment by mattwojo** [comment]
Thanks @erhanalankus for this issue and for the recommended fix, Adam. 
Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
