### ISSUE TITLE
Remapping ¨+U

### ISSUE THREAD

**Issue by MasterVargen** [MicrosoftDocs/windows-uwp#4728]
Hi

I want to remap ¨and U to make Ü this isn't a feature yet and would be nice to have. I don´t know how many have the same use case but right now only win crtl and alt can map to many keys which the ü need. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback. Thanks for using PowerToys!
