### ISSUE TITLE
node.js extension pack from wade anderson is depreciated

### ISSUE THREAD

**Issue by indelible-seven** [MicrosoftDocs/windows-uwp#4729]
node.js extension pack from wade anderson is depreciated

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/129323638/fcb2476d-b787-4926-bed4-5d0c513208f3)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for contributing this issue! This was removed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/bc7f5d7dafddfdb2a492a0bfbe61f776d66da61d
