### ISSUE TITLE
Typo on packageWriteRedirectionCompatabilityShim 

### ISSUE THREAD

**Issue by TimMangan** [MicrosoftDocs/windows-uwp#4730]
packageWriteRedirectionCompatabilityShim  should be packageWriteRedirectionCompatibilityShim 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [uwp/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Amazing catch! This is now fixed.
