### ISSUE TITLE
Using the wrong package

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4731]
[Enter feedback here]
In order to use SQLite you need to install Microsoft.Data.Sqlite.Core.
But if you follow along this doesn't work and keeps bugging with the follow error 'You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().'.
In order to fix that prefer to use Microsoft.Data.Sqlite, this handles SQLitePCL.raw.SetProvider() and SQLitePCL.Batteries.Init() automatically.
(Big thanks to the UWP community for pointing this out)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 579860c8-b50a-80e9-d873-4540c2215b70
* Version Independent ID: 579860c8-b50a-80e9-d873-4540c2215b70
* Content: [Use a SQLite database in a Windows app - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/data-access/sqlite-data-access)
* Content Source: [hub/apps/develop/data-access/sqlite-data-access.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/data-access/sqlite-data-access.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for the feedback. The topic has been updated to reference the correct SQLite package. The PR has been merged and should be live soon.
