### ISSUE TITLE
Can't find Developer settings

### ISSUE THREAD

**Issue by kcbina** [MicrosoftDocs/windows-uwp#4734]
Sorry, I would like to ask why the Developer settings option cannot be found in the gear in my global administrator account.
Do I need to open any permissions or make any settings?
Which operations will make Developer settings option appear?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6f89da-a783-15ab-6a76-c7fa8a61498c
* Version Independent ID: 7f6f89da-a783-15ab-6a76-c7fa8a61498c
* Content: [Manage Azure AD applications in your Partner Center account - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/manage-azure-ad-applications-in-partner-center)
* Content Source: [hub/apps/publish/partner-center/manage-azure-ad-applications-in-partner-center.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/manage-azure-ad-applications-in-partner-center.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by JulCsc** [comment]
Resolved in https://github.com/MicrosoftDocs/windows-dev-docs-pr/pull/3939 by Saloni Bhansali
#please-close
