### ISSUE TITLE
Doesn't have instructions to install without Windows Store

### ISSUE THREAD

**Issue by jeffsdata** [MicrosoftDocs/windows-uwp#4736]
I dont have windows store. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98654069-5528-4f98-7218-a803bee0a532
* Version Independent ID: b49c32ea-2efa-b090-7123-87c31d10279b
* Content: [Use the winget tool to install and manage applications](https://learn.microsoft.com/en-us/windows/package-manager/winget/)
* Content Source: [hub/package-manager/winget/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @jeffsdata - WinGet should be included with your Windows installation be default, but if you're not finding that to be the case, it is installed and run using Windows App Installer. You can get App Installer without the Microsoft Store here: https://learn.microsoft.com/en-us/windows/msix/app-installer/install-update-app-installer
