### ISSUE TITLE
Verb missing from sentence

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/windows-uwp#4741]
Hello,

a verb is missing from this sentence: "The ObservableProperty attribute on the name private field **will a Name property** for the class with the proper INotifyPropertyChanged implementation. "

Is it 'add' or 'implement'?

Kind regard,
Anne H, QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebd638a3-0daf-2b8c-24a2-57b5dcca1fa6
* Version Independent ID: ebd638a3-0daf-2b8c-24a2-57b5dcca1fa6
* Content: [Tutorial--Create a .NET MAUI app with C# Markup and the Community Toolkit - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-dotnet-maui/tutorial-csharp-ui-maui-toolkit)
* Content Source: [hub/apps/windows-dotnet-maui/tutorial-csharp-ui-maui-toolkit.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-dotnet-maui/tutorial-csharp-ui-maui-toolkit.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for raising this issue. A fix for the error has been merged and should be live soon. Cheers!
