### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by Trubador** [MicrosoftDocs/windows-uwp#4742]
The Dev Home tool is really nice, please keep expanding it to handle more custom requirements. 😀

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til learn.microsoft.com ➟ GitHub-problemlinkning.*

* ID: e94338ac-d3a8-011e-4cf9-fc4a9f60de35
* Version Independent ID: e94338ac-d3a8-011e-4cf9-fc4a9f60de35
* Content: [Set up your Windows development environment with Dev Home](https://learn.microsoft.com/da-dk/windows/dev-home/setup)
* Content Source: [hub/dev-home/setup.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/setup.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @Trubador. The dev team is definitely putting in time to improve and expand Dev Home capabilities. You can see some of what's in the works on the Dev Home product GitHub repo: https://github.com/microsoft/devhome ...looking at the Issues and PRs you can see what folks are working on... and contribute if you're interested. I'll pass along the thanks to that team.
