### ISSUE TITLE
Update request: How to build a hello world app

### ISSUE THREAD

**Issue by Hatsuna-Miku** [MicrosoftDocs/windows-uwp#4747]
Want C++ Version of this tutorial, also need api reference links

**Comment by GrantMeStrength** [comment]
Thanks for your comment!

Here is the Hello World: https://learn.microsoft.com/cpp/build/vscpp-step-2-build?view=msvc-170
Here are the API references: https://learn.microsoft.com/windows/win32/apiindex/api-index-portal

-John
