### ISSUE TITLE
Crop and Lock needs info about exitting Lock state

### ISSUE THREAD

**Issue by schroef** [MicrosoftDocs/windows-uwp#4748]
Its quite a handy feature, what im missing in de info page is how to exit this mode. There is nothing written about the [X] in the top right corner will exit the mode

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Version Independent ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Content: [PowerToys Crop And Lock for Windows](https://learn.microsoft.com/en-us/windows/powertoys/crop-and-lock)
* Content Source: [hub/powertoys/crop-and-lock.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/crop-and-lock.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for the feedback. I've updated the documentation with info about:

1. Canceling the crop selection
2. Closing the cropped window to restore the original

The changes have been merged and should be live soon.
