### ISSUE TITLE
Why in the world!!!???? So many  errrrrrssssss!!

### ISSUE THREAD

**Issue by Xternality711** [MicrosoftDocs/windows-uwp#4749]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4995a8-5af9-bcfd-86f2-912c5674b95d
* Version Independent ID: 1c4995a8-5af9-bcfd-86f2-912c5674b95d
* Content: [PowerToys Peek utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/peek)
* Content Source: [hub/powertoys/peek.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/peek.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario (I've double-checked this documentation page for any erors), over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.

If this feedback is about the docs, please let me know, and I can re-open the issue and add your specific feedback to improve the page.
