### ISSUE TITLE
can I set TargetNullValue using x:bind, ThemeResource or StaticResource?

### ISSUE THREAD

**Issue by HppZ** [MicrosoftDocs/windows-uwp#475]
TargetNullValue = {x:bind path} ; TargetNullValue = {ThemeResource  key} ; 
 TargetNullValue = {StaticResourcekey}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27806783-e079-576b-6477-103b3582a7b4
* Version Independent ID: 6f94ae4c-9946-712a-53f9-4ea26a0b025c
* Content: [xBind markup extension - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#event-binding)
* Content Source: [windows-apps-src/xaml-platform/x-bind-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/x-bind-markup-extension.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by KWodarczyk** [comment]
why was this closed ?
