### ISSUE TITLE
Shortcut spelled wrong in How To Use section (shorcut)

### ISSUE THREAD

**Issue by sweet1227** [MicrosoftDocs/windows-uwp#4753]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Version Independent ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Content: [PowerToys Crop And Lock for Windows](https://learn.microsoft.com/en-us/windows/powertoys/crop-and-lock)
* Content Source: [hub/powertoys/crop-and-lock.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/crop-and-lock.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for reporting this issue. I've merged a fix, and it should be live shortly.
