### ISSUE TITLE
win doc'sds docs

### ISSUE THREAD

**Issue by whiplash696** [MicrosoftDocs/windows-uwp#4758]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bac33878-35ad-1414-173d-55b3de32f8ba
* Version Independent ID: bac33878-35ad-1414-173d-55b3de32f8ba
* Content: [Age ratings for MSI and EXE apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/age-ratings?pivots=store-installer-msix)
* Content Source: [hub/apps/publish/publish-your-app/age-ratings.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/age-ratings.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported. Closing.
