### ISSUE TITLE
company account capabilities are more than 3

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#476]
following are some other capabilities which require a company account.
1. closeAppRequest
2. broadFileAccess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2099ff76-43d5-98fd-d8bc-66ccdc14c4fe
* Version Independent ID: 1c3f3863-5413-d58b-a0e5-81a6da6bccf2
* Content: [Account types, locations, and fees - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
We no longer limit capability requests to company accounts (for any restricted capabilities). Note that this doesn't mean every request will be approved. For more about the capability approval request process, see https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#special-and-restricted-capabilities

**Comment by touseefbsb** [comment]
@JnHs I recently requested an access to broadFileAccess from dev center support, and they informed me that I have an individual account hence I cannot request this capability, if you are saying that I am eligible for this capability access, then please can you clarify why I was rejected? because the reason they told me was only this one reason : "I don't have a company account"

**Comment by JnHs** [comment]
You should go ahead and submit a request (using the new process as described in the topic above). Your request will be evaluated when you submit your app, even if it is from an individual account.

**Comment by touseefbsb** [comment]
following line from the docs link you provided is misleading I think

>If your app declares any special and restricted capabilities, you'll need to receive approval before they can be published to the Store. 

@JnHs  does it mean first I should submit the request for capability and then I should make my package submission to the store from dev dashboard? and during certification my capability request will also be analyzed?

**Comment by JnHs** [comment]
The approval must happen before the app can be published, but you make the request in the dashboard during the submission process; after you upload your packages, if Dev Center detects that  any restricted capabilities are used, you'll need to provide details on the Submission options page to request permission to use them. You no longer have to submit a request to the support team in advance of your submission. I'll update that wording to make that clearer, thanks for your feedback!

**Comment by touseefbsb** [comment]
@JnHs  ok thanks for the clarification as well. but I think if we can get approval before we start coding out app that can be better because if I spend months on creating the app and then get rejected at time of submission that means I wasted a lot of months. I wish there can be a system where I can get approved with my idea to use a capability before I start coding, and at the time of submission the store can verify whether my app uses the capability in the way which I requested before.

**Comment by JnHs** [comment]
@touseefbsb Thanks for your patience while I looked into this. You can still request approval in advance if you prefer (for instance to help with the scenario you describe above). To do so, visit https://developer.microsoft.com/windows/support, select Issue Type "Applications" and Subcategory "Other", then submit your request, describing which capability you're planning to use and how your app will use it. I'll make a note of this in the help content as well!

**Comment by touseefbsb** [comment]
@JnHs thankyou for the response I will submit my request :)

**Comment by touseefbsb** [comment]
btw there is no Applications issue type there, do u mean "Windows Desktop Application Development ( Windows 10 SDK )" ? there is a App submission issue type under "Dashboard issues" btw which has a sub category of **others**

**Comment by JnHs** [comment]
Thanks @touseefbsb for noticing that - I was looking at some outdated info. You can choose **Dashboard issue/App submission.**
