### ISSUE TITLE
Use Locksmith in the network

### ISSUE THREAD

**Issue by Pixel-Minions** [MicrosoftDocs/windows-uwp#4765]
It would be amazing if I could run this file and find who in the network is using the file and the processes that keep the files open.

Best,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Version Independent ID: 4aa0101c-da3b-4681-8646-bfbbc6dba4e4
* Content: [PowerToys File Locksmith utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith)
* Content Source: [hub/powertoys/file-locksmith.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-locksmith.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
