### ISSUE TITLE
okokok

### ISSUE THREAD

**Issue by reyz5** [MicrosoftDocs/windows-uwp#4766]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d630c4ab-af0f-c5d0-bdbc-c81bed913638
* Version Independent ID: 840a9c1c-3a7b-3387-a0d8-f25df4d6f60f
* Content: [Xbox Live Page (Dev Home) - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/xbox-apps/devhome-live)
* Content Source: [uwp/xbox-apps/devhome-live.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/xbox-apps/devhome-live.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported. Closing.
