### ISSUE TITLE
1000063488 (1280×800)

### ISSUE THREAD

**Issue by firasdlke** [MicrosoftDocs/windows-uwp#4767]
![unnamed.jpg](https://github.com/MicrosoftDocs/windows-dev-docs/assets/141883862/0f9b2c28-f0f9-4601-b584-ca73b5032b23)

**Comment by firasdlke** [comment]
> ![unnamed.jpg](https://github.com/MicrosoftDocs/windows-dev-docs/assets/141883862/0f9b2c28-f0f9-4601-b584-ca73b5032b23)
> 
>

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported. Closing.
