### ISSUE TITLE
Does not indicate you must be local admin

### ISSUE THREAD

**Issue by jgriff500** [MicrosoftDocs/windows-uwp#4768]
Page does not indicate you must be logged in as local admin.   There is no UAC prompt or option to run as admin, so if you are not local admin (1) Create a Dev drive option does not exist and (2) if you attempt to simply create a VHD, you get an access denied error message.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Added this to the Prereqs. Thanks @jgriff500.
Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
