### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by duhlman** [MicrosoftDocs/windows-uwp#477]
"RefreshReuested" should be "RefreshRe**q**uested"
Refreshing
When the user releases the visualiser past the threshold, it's in the Refreshing state.
When this state is entered, the RefreshReuested event is raised. This is the signal to start the app's content refresh. The event args (RefreshRequestedEventArgs) contain a Deferral object, which you should take a handle to in the event handler. Then, you should mark the deferral as completed when your code to perform the refresh has completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72402dbb-b344-ad50-4c8d-7a36e00e59e3
* Version Independent ID: 1176d342-0cfd-3c26-a71b-7f0c69a0e511
* Content: [Pull-to-refresh - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/pull-to-refresh)
* Content Source: [windows-apps-src/design/controls-and-patterns/pull-to-refresh.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/pull-to-refresh.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Fixed. Thanks for reporting the error.
