### ISSUE TITLE
Cannot figure out how to upload app to Microsoft App Store

### ISSUE THREAD

**Issue by geroge-d** [MicrosoftDocs/windows-uwp#4770]
[Enter feedback here]
Hi 
I have tried server times to set package url,but all failed. The error is below:
Package url: https://swc.snapemoji.net/1.0/master_poker.msix

Error:
Package URL should begin with https:// and should point to a versioned, downloadable package.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Version Independent ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Content: [Upload app packages - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/upload-app-packages?pivots=store-installer-msi-exe)
* Content Source: [hub/apps/publish/publish-your-app/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/upload-app-packages.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Sorry for the delay in responding but this issue was not documentation related. I hope it's been resolved by now.
In the future, the Microsoft Q&A Forum is a much better place to ask these kinds of questions. Again, sorry.

**Comment by Kingflint** [comment]
were you able to fix it, having the same issue
