### ISSUE TITLE
Self-referencing Additional Resource

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/windows-uwp#4772]
This page has three items listed under Additional Resources. Item #2 of 3 is a self-referencing link back to the same page. It should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90e6a3e5-1d5a-358d-60c5-0a6bed89e729
* Version Independent ID: 8e95d16d-aa68-38c2-ac75-008f76b767a7
* Content: [Add Windows Defender exceptions for Android](https://learn.microsoft.com/en-us/windows/android/defender-settings)
* Content Source: [hub/android/defender-settings.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/defender-settings.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @ChristopherBenson! I agree -- removed. :)
