### ISSUE TITLE
extra cloud space

### ISSUE THREAD

**Issue by JJtzitzo-33** [MicrosoftDocs/windows-uwp#4773]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e94338ac-d3a8-011e-4cf9-fc4a9f60de35
* Version Independent ID: e94338ac-d3a8-011e-4cf9-fc4a9f60de35
* Content: [Set up your Windows development environment with Dev Home](https://learn.microsoft.com/en-gb/windows/dev-home/setup#clone-a-github-repo-and-store-it-on-a-dev-drive)
* Content Source: [hub/dev-home/setup.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/setup.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
No actual issue is listed here. Closing.
