### ISSUE TITLE
Lacks clarity, hard to understand, typos

### ISSUE THREAD

**Issue by jess-rod** [MicrosoftDocs/windows-uwp#4776]
> The 6 month period begins when you generate the first promotional code is created and lasts for 6 months regardless of whether or not you set an earlier expiration date on the codes.
> Any codes created during an existing six-month period will be count toward the number of codes generated within that period, even if they will expire after the period ends (For example, if you generate a code on the last day of the six-month window, it will be will be still be valid for a full 6 months from its creation.)

It needs better copywriting. It contains many errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9cc8a8-0396-e184-f559-c7fd51169dc3
* Version Independent ID: 4a9cc8a8-0396-e184-f559-c7fd51169dc3
* Content: [Generate promotional codes - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/generate-promotional-codes)
* Content Source: [hub/apps/publish/generate-promotional-codes.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/generate-promotional-codes.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Corrected grammar, typos and incorrectly escaped links.
