### ISSUE TITLE
C++/WinRT Version, Please

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#4785]
Some of the concepts on this page have no obvious C++/WinRT translation.  I'd really appreciate it if  you would add C++/WinRT code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd2206a7-becd-770f-14f0-6471d416868a
* Version Independent ID: fd2206a7-becd-770f-14f0-6471d416868a
* Content: [Build a simple Win2D app - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/win2d/quick-start)
* Content Source: [hub/apps/develop/win2d/quick-start.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/win2d/quick-start.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @dr-eck. I'll put this on my backlog (so I'll close this issue), but be aware that providing code examples in C# is the first priority. Then, usually if the scenario would especially benefit from it, we try to provide a C++/WinRT version also. For example, the [Win2D "Hello, World!" quickstart](https://learn.microsoft.com/windows/apps/develop/win2d/hellowin2dworld) (the topic immediately before this one) does have a C++/WinRT version.

However, that wouldn't be good ROI for every code example. Many of them are quite mechanical to port to C++. So for those cases, we have resources such as the [C++/WinRT](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/) content in general, and then the [Porting the Clipboard sample to C++/WinRT from C#—a case study](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp) and [Move to C++/WinRT from C#](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp) topics in particular.

So I'll close this issue for now.

-Steve
