### ISSUE TITLE
Windows 10 install winget instructions don't actually work

### ISSUE THREAD

**Issue by penalvch** [MicrosoftDocs/windows-uwp#4787]
Hi,

I did a fresh reinstall of Windows 10 x64 22H2, logged in, and intended to have winget usable. However, when following the official instructions in:
https://learn.microsoft.com/en-us/windows/package-manager/winget/

they consistently do not work as per below, even if one restarts multiple times.

```
PS C:\Windows\system32> Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe -verbose
VERBOSE: Performing the operation "Register package" on target "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe".
VERBOSE: Operation completed for: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
```

```
 winget search powertoys
winget : The term 'winget' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winget search powertoys
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Environment:
```
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3803
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3803
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/115644052/8017b195-f52c-43bf-b8e5-e92b68b2b51f)

WORKAROUND: Manually install winget via:
```
$wingetfile=-join("$env:windir\temp\",'Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle')
$wingeturi='https://github.com/microsoft/winget-cli/releases/download/v1.6.3421/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'
$null=invoke-webrequest -uri $wingeturi -outfile $wingetfile
$null=add-appxpackage -path $wingetfile
$null=remove-item -path $wingetfile
winget
Windows Package Manager v1.6.3421
Copyright (c) Microsoft Corporation. All rights reserved.

The winget command line utility enables installing applications and other packages from the command line.

usage: winget  [<command>] [<options>]

The following commands are available:
  install    Installs the given package
  show       Shows information about a package
  source     Manage sources of packages
  search     Find and show basic info of packages
  list       Display installed packages
  upgrade    Shows and performs available upgrades
  uninstall  Uninstalls the given package
  hash       Helper to hash installer files
  validate   Validates a manifest file
  settings   Open settings or set administrator settings
  features   Shows the status of experimental features
  export     Exports a list of the installed packages
  import     Installs all the packages in a file
  pin        Manage package pins
  configure  Configures the system into a desired state
  download   Downloads the installer from a given package

For more details on a specific command, pass it the help argument. [-?]

The following options are available:
  -v,--version              Display the version of the tool
  --info                    Display general info of the tool
  -?,--help                 Shows help about the selected command
  --wait                    Prompts the user to press any key before exiting
  --logs,--open-logs        Open the default logs location
  --verbose,--verbose-logs  Enables verbose logging for winget
  --disable-interactivity   Disable interactive prompts

More help can be found at: https://aka.ms/winget-command-help
```

**Comment by mattwojo** [comment]
@denelon - Any idea what the issue may be here?  The App Installer and WinGet should be included in a fresh install of Windows 10 x64 22H2, yes?

@penalvch Are you sure that you were logged in? (May be too late to check now that you've done a manual install..?)

"The winget tool will not be available until you have logged into Windows as a user for the first time, triggering Microsoft Store to register Windows Package Manager as part of an asynchronous process. If you have recently logged in as a user for the first time and find that winget is not yet available, you can open PowerShell and enter the following command to request this winget registration: Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe."

**Comment by penalvch** [comment]
> @denelon - Any idea what the issue may be here? The App Installer and WinGet should be included in a fresh install of Windows 10 x64 22H2, yes?
> 
> @penalvch Are you sure that you were logged in? (May be too late to check now that you've done a manual install..?)
> 
> "The winget tool will not be available until you have logged into Windows as a user for the first time, triggering Microsoft Store to register Windows Package Manager as part of an asynchronous process. If you have recently logged in as a user for the first time and find that winget is not yet available, you can open PowerShell and enter the following command to request this winget registration: Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe."

Hi, @mattwojo, thanks for the review!

Yes, I'm sure I was logged in as I had applied updates prior to originally reporting, and restarted.

Further, I ran the suggested command verbatim as per my original comment with the verbose flag passed. Not sure the root cuase but the workaround worked out.
