### ISSUE TITLE
support more codecs?

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#479]
are there any plans to support more codecs as per : https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/19248226-codecs-for-uwp-media-element

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181085f-2eaa-6eb5-06fd-52c3a98f7467
* Version Independent ID: 240818b0-d509-bbcf-f485-7ca0ba55f0f6
* Content: [Supported codecs - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/supported-codecs)
* Content Source: [windows-apps-src/audio-video-camera/supported-codecs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/supported-codecs.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by touseefbsb** [comment]
@ginami , @drewbatgit  any update on this? is this issue being investigated? or can we expect it to be implemented?

**Comment by drewbatgit** [comment]
The feature teams use customer feedback when they plan updates to the platform, but we don't discuss plans for future releases publicly. I will forward your request on to the team.
