### ISSUE TITLE
microsoft / PowerToys - Is there an API for Powertoys to intergrade  into Chat GPT for PDF automation ?

### ISSUE THREAD

**Issue by AutoUnity** [MicrosoftDocs/windows-uwp#4798]
I use Power toys / Text Extractor  locally on desktop and I am trying to figure out how to set up an API for Text Extractor to intergrade  into Chat GPT, Google docs and Google sheets for PDF automation instead of doing it manually. Please can anyone help and or assist with this request?

**Comment by crutkas** [comment]
Please file the issue on PowerToys repository, not the docs repository. Https://github.com/microsoft/powertoys.

**Comment by alvinashcraft** [comment]
Thanks, Clint. @AutoUnity, if you create an issue on the PowerToys repo, you can link it back here if you like.  This feels resolved, so I'm closing the issue, but we'll continue to monitor any replies.
