### ISSUE TITLE
Unable to add another github account

### ISSUE THREAD

**Issue by malhous** [MicrosoftDocs/windows-uwp#4808]
I would like to have more than 1 github account inside my DevHome, however I'm receiving the below error as soon as I try to sign-in to my github account:

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/141725980/25e58108-e2e9-4b67-bfe0-3054e91633e4)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acdf7266-5a5a-10a9-25bc-94f01b3e5d0a
* Version Independent ID: acdf7266-5a5a-10a9-25bc-94f01b3e5d0a
* Content: [Dev Home for Windows Developers](https://learn.microsoft.com/en-us/windows/dev-home/)
* Content Source: [hub/dev-home/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @malhous - Yes, this is a known issue and there are duplicate requests for this support on the Dev Home GitHub extension repo. I just heard from the development team that they have recently been unblocked and work to add support for multiple GitHub accounts is in progress.  > https://github.com/microsoft/devhomegithubextension/issues/276

In the meantime, this was a helpful prompt for me to add a note about the tool only supporting a single GitHub account currently to the documentation. Just added the note > https://github.com/MicrosoftDocs/windows-dev-docs/commit/b382c1f3913c049918f08640ccbd401ac7df5608

Thanks again for filing this issue.
