### ISSUE TITLE
Suggestion - Random Pixel Alignment

### ISSUE THREAD

**Issue by AfterTh0ught** [MicrosoftDocs/windows-uwp#4809]
**What:** Have a button that randomly adjust the size of the snapping windows by +- 10px (maybe adjustable amount).

**Reason:** snapping windows is one of the main causes of oled burn in on windows systems. Having the snapping adjust where it snaps by a little amount everytime would move that line down your screen by a few pixels and hopefully saving your display a little bit

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
