### ISSUE TITLE
Image thumbnail supports windows lacks.

### ISSUE THREAD

**Issue by fiendish55** [MicrosoftDocs/windows-uwp#4813]
[Enter feedback here]
Please add .tga, .dds, and other mainstream image format thumbnail supports which windows lacks :(

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [PowerToys File Explorer add-ons utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like feedback about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
