### ISSUE TITLE
Will a VHD file created for use as a Dev Drive be encrypted when the drive storing it is BitLocker enabled?

### ISSUE THREAD

**Issue by benmccallum** [MicrosoftDocs/windows-uwp#4816]
Sorry upfront, I'm 95% sure this is the case... but when creating the Dev Drive VHD file sitting on say, your C: drive, if the C: drive is BitLocker encrypted, is the VHD file by virtue also encrypted? Just wary of source code being unencrypted, but if it's resting on the C drive really, it'd be encrypted, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by benmccallum** [comment]
Decide to create a new Dev Drive from unallocated space to just avoid the uncertainty altogether, and will enable bitlocker on that separately. Reason being, we're going to be using drata monitoring soon which I was worried would see the "Dev Drive" mounted as not using BitLocker and report it as a violation.

Still interested in the answer for above though, cheers.

**Comment by mattwojo** [comment]
Thanks for this question @benmccallum. Yes - a Dev Drive VHD sitting on a Bitlocker encrypted volume is encrypted. (The VHD will not have Bitlocker enabled itself as that would cause double encryption, but the contents will be encrypted on the hosting volume).

I'll add an FAQ about this to the docs for broader awareness.

**Comment by mattwojo** [comment]
FAQ on this added in: https://github.com/MicrosoftDocs/windows-dev-docs/commit/86c28c663813c21222277fd2b665324fe0a8f243
Closing. Thanks again Ben.

**Comment by benmccallum** [comment]
Thanks so much for clarifying @mattwojo, and in the docs too, that's great!
