### ISSUE TITLE
What Admin Privilages are running? Get Power Toys to tell me

### ISSUE THREAD

**Issue by TheBlackRoom** [MicrosoftDocs/windows-uwp#4817]
Update done to v0.77.0 and rebooted Win11 after it updated, now I get a notification at boot titled "AlwaysOnTop" has detected an application with Admin privilages (I see this is a new check to this version).

This is all great, but if PowerToys can detect that, is there any chance it could actually tell me what that application is?! i.e. Power Toys had no issue with my installations before (nothing new installed) and I have no way amongst everything running to work out what "AlwaysOnTop" is worried about - if Power Toys is clever enough to know, then perhaps it could also tell me what it's found.

I realise I can set PowerToys to run in Admin mode itself, but it would be useful if I could see what it's worried about - some guidance would be useful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99bd5eaf-0982-6fe8-09d2-17e4373886bb
* Version Independent ID: 5e66eda4-be07-4afd-7187-3e4d896f7861
* Content: [PowerToys administrator mode for Windows](https://learn.microsoft.com/en-gb/windows/powertoys/administrator)
* Content Source: [hub/powertoys/administrator.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/administrator.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
