### ISSUE TITLE
PowerToys Run IS BECOMING UGLIER WITH EVERY UPDATE!

### ISSUE THREAD

**Issue by Dansking54** [MicrosoftDocs/windows-uwp#4818]
[ I'm outraged by the ugliness of the tool that used to be the pride of PowerToys. I don't even feel like doing the updates that come out, even though it's the tool I use the most in my daily life. It now looks like a big ugly rectangle in the middle of my screen.

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/97561780/9eb41a62-8485-4e11-8137-5dc32e691122)

I want to go back to the basic version or have a function to change the theme of PowerToys Run!]

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/97561780/4b6c5421-fc15-4154-b34c-2b951db557be)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b951899-69ca-9057-f799-14491e1b0a74
* Version Independent ID: 18e0202f-3e91-a5b9-62f2-6cd40e5661a8
* Content: [PowerToys Run utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/run)
* Content Source: [hub/powertoys/run.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like feedback about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
