### ISSUE TITLE
Part 3: Add a DataTemplate to display your data

### ISSUE THREAD

**Issue by bbnguyenbb** [MicrosoftDocs/windows-uwp#482]
it's not fair. why are you demo but you used tool "telerik" company (<telerikInput:RadRating....). perhaprs, programmer of microsoft have not ability to create demo by tool visual studio???? Or Microsoft want programmer buy telerik tool???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc1c132-3cfa-1a08-0726-214110c8d23d
* Version Independent ID: 7ddf3871-c4a1-ae0a-9c03-25ccf4934cf2
* Content: [Create a user interface tutorial - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-ui#feedback)
* Content Source: [windows-apps-src/design/basics/xaml-basics-ui.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-ui.md)
* Service: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by BurtonPage** [comment]
@bbnguyenbb ,
Those telerik controls are open source:  https://github.com/telerik/UI-For-UWP

**Comment by jevansaks** [comment]
Looks like this sample is using Telerik for RatingControl, the sample should be updated to use the platform's native RatingControl now anyway.

@KarlErickson  can you help update the sample?

**Comment by jwmsft** [comment]
This sample has been updated to use the WinUI rating control.
