### ISSUE TITLE
swift.org

### ISSUE THREAD

**Issue by avuntolo** [MicrosoftDocs/windows-uwp#4829]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b884a25-4155-ac22-67b1-afb6d81d9751
* Version Independent ID: 2b7bd115-a4d9-17c7-0e21-6d23a0774af6
* Content: [Submit packages to Windows Package Manager](https://learn.microsoft.com/en-us/windows/package-manager/package/)
* Content Source: [hub/package-manager/package/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/package/index.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@avuntolo - Closing this issue as there is no description. If you would like to add a description explaining the issue, please feel welcome to reopen it.
