### ISSUE TITLE
Make a seperate design guidelines documentation

### ISSUE THREAD

**Issue by Mancerrss** [MicrosoftDocs/windows-uwp#483]
Here's the thing you guys confusing or merging a design guidelines documentation to developer documentation. You guys gotta seperate them in order to make both sides working and happy. Cmon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e4eb9-1481-e2ae-3922-26799d2e6dbd
* Version Independent ID: 4ac739fa-45fc-651e-4c3e-fa77941655e3
* Content: [Fluent Design System for UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/fluent-design-system/?utm_source=t.co&utm_medium=referral)
* Content Source: [windows-apps-src/design/fluent-design-system/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/fluent-design-system/index.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for the feedback, @Mancerrss! In the Windows 8 and 8.1 timeframe, our design and developer documentation was separate, and we received feedback that that was confusing: We would have two articles covering the same concept/feature from different perspectives,developers were landing and design pages, designers were landing on developer pages. 

We're continually updating our documentation to make it easier to find and use--we'll consider your feedback as work on our next iteration of Fluent Design guidelines.
