### ISSUE TITLE
Media player docs should include list of supported text formats

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#4830]
The documentation for the UWP media APIs are lacking information about what formats are supported for text tracks (like subtitles), either when loaded via **TimedTextSource** or when listed in HLS and DASH adaptive streaming manifests, and any conditions for their use or features that are or are not supported.

Examples of format types: WebVTT, TTML, IMSC, SRT

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 770616aa-f26a-4e26-03ac-2f2061702e21
* Version Independent ID: 7be0a48f-1ab5-77c1-d9e6-0f0abcbda165
* Content: [Supported codecs - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/supported-codecs)
* Content Source: [uwp/audio-video-camera/supported-codecs.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/audio-video-camera/supported-codecs.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for the feedback. We have added supported timed text formats to this Supported Codes page.
