### ISSUE TITLE
Objet

### ISSUE THREAD

**Issue by Jadenlike** [MicrosoftDocs/windows-uwp#4832]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90e6a3e5-1d5a-358d-60c5-0a6bed89e729
* Version Independent ID: 8e95d16d-aa68-38c2-ac75-008f76b767a7
* Content: [Add Windows Defender exceptions for Android](https://learn.microsoft.com/en-us/windows/android/defender-settings#exclusions-to-consider-for-android-development)
* Content Source: [hub/android/defender-settings.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/defender-settings.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @Jadenlike - Closing this issue as there's no description, but if you're actually seeing something that should be updated in this documentation, please feel welcome to re-open and add a description of the issue you've found.
