### ISSUE TITLE
Release notes since June 1, 2023?

### ISSUE THREAD

**Issue by ramit-2343113** [MicrosoftDocs/windows-uwp#4834]
Where can I find release notes for WSA releases since  June 1, 2023. Is this page or product not being maintained any longer?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Version Independent ID: 865063ea-60f4-de74-20e8-77abe9ce0fc6
* Content: [Windows Subsystem for Android™️ Release Notes](https://learn.microsoft.com/en-us/windows/android/wsa/release-notes)
* Content Source: [hub/android/wsa/release-notes.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/release-notes.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Checked with the product team for Windows Subsystem for Android and was told that they are still in a planning phase, but will announce more details and release notes when there is more to share. So sounds like there aren't any further notes to share right now.

**Comment by ramit-2343113** [comment]
@mattwojo  Does that mean Build 2304.40000.3.0 released on June 1, 2023 was the last official GA release of WSA, and there have not been official GA releases since then? 
I see newer version available when installing Amazon Store, is that a preview version?
