### ISSUE TITLE
Before setting up a Dev Drive, ensure that the prerequisites are met.

### ISSUE THREAD

**Issue by GustavBrock** [MicrosoftDocs/windows-uwp#4835]
Well, sure, but nowhere are these listed ...

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til learn.microsoft.com ➟ GitHub-problemlinkning.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/da-dk/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
https://learn.microsoft.com/windows/dev-drive/#prerequisites
