### ISSUE TITLE
add other activation keys

### ISSUE THREAD

**Issue by nfb1** [MicrosoftDocs/windows-uwp#4836]
First, thanks for this PowerToy. I love it.

But, I have to turn this off before playing a game. Please add the option to have this activate with the key of the user's choosing, instead of such a small selection of activator keys. Or maybe there is another fix for this.

Here's why:
I don't like using the Arrows to activate - they are too far from the home position of my fingers on the keys while I'm typing, and it only makes sense to me to hit the arrow keys with my right hand (crossing hands is too weird if I'm typing an accented O or I). 
So instead I use Spacebar, because it feels natural and is in the middle so I can use either hand.
BUT, this means that it frequently activates while I am playing a game - the most common keybindings for movement being WASD and Jump as Spacebar - and then I get movement errors that are sometimes tricky to resolve.
For example I might be moving left by holding down A, then need to jump by pressing spacebar, QuickAccent kicks in and I'm stuck moving left because the game never got a keyUp event on the A key, just on Ä. I have the same problem with S/ẞ. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Version Independent ID: affbed27-28f0-71c2-5a82-b12922b5b3c2
* Content: [PowerToys Quick Accent utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/quick-accent)
* Content Source: [hub/powertoys/quick-accent.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
