### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by CTI-Tim** [MicrosoftDocs/windows-uwp#4837]
there is no selection for WinUI in vs2022, and no packages called WinUI are available.  These instructions are a dead end in the first 3 sentences.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 (Windows App SDK) project - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Service: **windows-app-sdk**
* Sub-service: **winui-conceptual**
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
If the dev environment is set up, and everything installed (as described in the topic), then the following is correct:

"In the New Project dialog's drop-down filters, select C#/C++, Windows, and WinUI, respectively."

The only wrinkle that I notice is that the case of "WinUI" has now changed to "winui". So I'll go ahead and update that in the topic.

Thanks!
-Steve
