### ISSUE TITLE
GetFolderAsync doesn't return

### ISSUE THREAD

**Issue by AlexiyOrlov** [MicrosoftDocs/windows-uwp#4838]
The line with `await appInstalledFolder.GetFolderAsync("Assets\\Samples");` isn't completing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial--Create a simple photo viewer with WinUI 3 - Windows apps](https://learn.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3?tabs=cs)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Service: **windows-app-sdk**
* Sub-service: **get-started**
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @AlexiyOrlov. I just followed along with tutorial again to test it, and that line of code is working fine. I would just check that you've followed all of the details. Often the name of the project you create is important (the tutorial indicates what to name it); and in this case certainly the way you add the Samples folder to the project is important. Things like that. Whatever the steps say, it's important to follow them. That's all I can think of: the topic doesn't appear to need any edits.

Thanks!
-Steve
