### ISSUE TITLE
Creating and incrementing stats

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#484]
The docs mentions "for stats of type SUM, you can send incremental updates." How do we specify the type of a stat and where in the API is the type available?

Also, one of the other pages mentions that only Feature Stats need to be created in Dev Center ahead of time. Will calling set_stat create a stat if it doesn't exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bc388d-6b0d-d201-19a9-4055cb14ef88
* Version Independent ID: aa039e5c-9126-265c-773e-9db63471e6fd
* Content: [Updating Stats 2017 - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/leaderboards-and-stats-2017/player-stats-updating)
* Content Source: [windows-apps-src/xbox-live/leaderboards-and-stats-2017/player-stats-updating.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/leaderboards-and-stats-2017/player-stats-updating.md)
* Service: **unspecified**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Hello ashultz, 
Still trying to get confirmation on your first question, but to answer your second question, calling set_stat will create a stat even if it is not configured on Dev Center. Dev Center stats are created ahead of time to create Leaderboards like those scene in the GameHub for a title.

**Comment by aablackm** [comment]
the "for stats of type SUM" piece was removed as it is an artifact from Stats 2013 and is not true or relevant to the subject matter of this article. Thank you for your feedback.
