### ISSUE TITLE
Description for new Windows on Arm emulation settings are missing

### ISSUE THREAD

**Issue by reflectronic** [MicrosoftDocs/windows-uwp#4845]
Windows 11 provides new emulation settings for Windows on Arm that are not described in the documentation.
<img src="https://github.com/MicrosoftDocs/windows-dev-docs/assets/27514983/d42d27fd-40c1-4dc9-a2d3-112658dbd270" width="315" />

Technical descriptions of the following options are missing:
- Hide x64 emulation capability
- Additional lightweight emulation protections
- Disable JIT optimization
- Disable floating point optimization

Describing these options in greater detail will help developers troubleshoot compatibility issues with Windows on Arm.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaeae508-9f9e-0393-e223-2d9e37acc2f8
* Version Independent ID: aaeae508-9f9e-0393-e223-2d9e37acc2f8
* Content: [Program Compatibility Troubleshooter on Arm](https://learn.microsoft.com/en-us/windows/arm/apps-on-arm-program-compat-troubleshooter)
* Content Source: [landing/arm-docs/apps-on-arm-program-compat-troubleshooter.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/landing/arm-docs/apps-on-arm-program-compat-troubleshooter.md)
* Service: **windows**
* Sub-service: **arm**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for raising this issue @reflectronic! I was able to connect with the PM and get some descriptions -- added them in https://github.com/MicrosoftDocs/windows-dev-docs/commit/be7a0cf7c21b9cd73876c64e4fdaff97becb22b3
