### ISSUE TITLE
Mouse Without Borders Color Status Legend

### ISSUE THREAD

**Issue by drakonien** [MicrosoftDocs/windows-uwp#4847]
It would be very useful to have a color legend for the connection status as presented in the devices borders:

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/18159615/c84aca83-f2ca-4216-90d3-f1124a76da01)

Something like:
- Green: connected
- Blue: connecting
- Yellow: disconnected
- Red: error
- Pink: ???

It would be nice if it's available also in the application.

**Comment by alvinashcraft** [comment]
Hi @drakonien. We added a [table with the colors](https://learn.microsoft.com/en-us/windows/powertoys/mouse-without-borders#status-colors) this week. Does this address your needs in the docs? 

If you want to suggest adding the info to the app too, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.

**Comment by drakonien** [comment]
> Hi @drakonien. We added a [table with the colors](https://learn.microsoft.com/en-us/windows/powertoys/mouse-without-borders#status-colors) this week. Does this address your needs in the docs?
> 
> If you want to suggest adding the info to the app too, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.

Thanks @alvinashcraft this sure address my issue 👍 
Only, and as a suggestion, it would be nice to make the doc a bit more "user friendly" by showing the actual color, something like:

- Yellow: `#FFFF00`
- Blue: `#FFA500`...

As seen in [github supported color models](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#supported-color-models).

I'll try to go to the PowerToys repository to create an issue there to request to have this in the app.

Thanks!
