### ISSUE TITLE
Shortcut outdated? Different than CTRL SHIFT V?

### ISSUE THREAD

**Issue by jfrischUCM** [MicrosoftDocs/windows-uwp#4848]
The page says CTRL + Win + Alt + V but powertoys is showing shortcut is Win + Ctrl + V. Is this page outdated?
Also, can there be a mention of the difference between this and Ctrl + Shift + V that is in Windows, perhaps how it works system wide while there maybe different behavior with the two methods in Excel or something (I don't know if there's any difference)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf8fcb35-1258-f544-401d-49b7db8a333a
* Version Independent ID: bf8fcb35-1258-f544-401d-49b7db8a333a
* Content: [PowerToys Paste as Plain Text for Windows](https://learn.microsoft.com/en-us/windows/powertoys/paste-as-plain-text)
* Content Source: [hub/powertoys/paste-as-plain-text.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/paste-as-plain-text.md)
* Service: **dev-environment**
* Sub-service: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The docs page has been replaced by the Advanced Paste topic. I believe that the shortcut listed on that page matches the current default in the product. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
