### ISSUE TITLE
Add callout for using these apis from Win32 and limitations when needing admin

### ISSUE THREAD

**Issue by AdamBraden** [MicrosoftDocs/windows-uwp#4849]
This page should have a note about using these picker apis from Win32/WinUI/WinAppSDK apps, as they do not support elevation. The docs should add a comment similar to this:

https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker?view=winrt-22621#in-a-desktop-app-that-requires-elevation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f98368cc-a7d2-6770-7c8f-3cb2f500676f
* Version Independent ID: 88e3393d-38a9-5737-89e2-85543d52dbfa
* Content: [Open files and folders with a picker - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers)
* Content Source: [uwp/files/quickstart-using-file-and-folder-pickers.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/files/quickstart-using-file-and-folder-pickers.md)
* Service: **uwp**
* Sub-service: **data-and-files**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks, @AdamBraden. I'll get this page updated.

**Comment by alvinashcraft** [comment]
@AdamBraden - Quick question, on the FileSavePicker reference topic that you linked to, should the warning just above that section discussing "snapped" apps be updated to indicate that's for Windows 8.x apps only? Or does that error also happen with UWP apps on Win 10/11 when you dock them to one side of a screen?

**Comment by alvinashcraft** [comment]
The UWP topics on file/folder pickers have been updated with notes about elevated apps with a link to the example you pointed out. Let me know your thoughts about the warning on that FileSavePicker page. I can create another PR if changes are needed there.

**Comment by AdamBraden** [comment]
I wasn't aware of the snapping issue. Seems like a bug that the original owners of pickers didn't want to fix. Not sure if the WinAppSDK team or whomever is works on snapping should take a look.
