### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#485]
"The Format is the data format of the stat. Options include Integer, Decimal, Percentage, Short timespan, Long timespan and String."

The XSAPI C++ API only supports integer, float, and string types. Can you elaborate on how the different data types are supposed to be set and how they will show up in a leaderboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5d4eb6-be1e-90fc-a9c2-d580b3dcf0ee
* Version Independent ID: 58f13eb8-09d9-d15e-7b9a-30576d157189
* Content: [Featured stats and leaderboards 2017 - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/configure-xbl/dev-center/featured-stats-and-leaderboards)
* Content Source: [windows-apps-src/xbox-live/configure-xbl/dev-center/featured-stats-and-leaderboards.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/configure-xbl/dev-center/featured-stats-and-leaderboards.md)
* Service: **unspecified**
* GitHub Login: @shrutimundra
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Each Format option will display some information pertaining to the acceptable values or formatting under the drop down when selected. 
Integer, Short Timespan, Long Timespan, and Percentages stats all take integer values,
Decimal stats take float values,
and String stats take string values.

**Comment by aablackm** [comment]
Article has been updated to include some formatting information. Closing Issue.
