### ISSUE TITLE
Why not install programs on Dev Drive

### ISSUE THREAD

**Issue by Neme12** [MicrosoftDocs/windows-uwp#4850]
The Dev Drive docs (https://learn.microsoft.com/en-us/windows/dev-drive/) says this:

> Dev Drive is **not** intended to store developer tools, such as:
> - Visual Studio
> - MSBuild
> - .NET SDK
> - Windows SDK, etc.

But it doesn't explain why. Why not? What's the problem with installing Visual Studio, or other programs, on a Dev Drive?

**Comment by mattwojo** [comment]
Hey @Neme12 -- Don't want you to think we're ignoring this issue. It's a good one and there's an internal discussion thread going about it... unpacking some of the original reasons for recommending that tools like VS, SDKs, etc. are not stored on Dev Drive (which is quite complicated based on the snippets I've heard so far) and re-assessing whether that should still be the recommendation as Dev Drive continues to develop. I'll report back (and update the docs) once there is more clarity achieved. Thanks for raising this issue.

**Comment by Neme12** [comment]
I have had Visual Studio on my dev drive for quite some time and haven't had any issues with it 🤷‍♀️ I'm just curious what those original reasons were.

**Comment by Neme12** [comment]
BTW, it would be nice to mention the required filter that needs to be added - WinSetupMon - right after the sentence "We also recommend that you consider redirecting %TEMP% and %TMP% envvars to Dev Drive.". I know that it's mentioned in the filters section, but it would be nice to mention it next to the recommendation to redirect these variables as well. I had these set to my dev drive based on the recommendation and only noticed that I need to set this filter on when I do that much later when I was curious about what these filters do and read the table of them.

**Comment by AdamBraden** [comment]
Original reasons were to be cautious in rolling out a new feature. Developer can move their tools, SDKs, and binaries onto a Dev Drive - assuming they've done appropriate analysis of their security posture and are ok with async scanning of those binaries. 

@mattwojo - please update this section as follows:

remove the "Dev Drive is not intended..." section and replace it with:

Considerations for installing developer tools and SDKs on Dev Drive
Often developer tools and SDKs are installed to either an administrator or per-user location. These locations provide certain security and isolation guarantees on Windows and impact Microsoft Defender behavior. However many tools do allow the user a choice of where to install, including a Dev Drive. Before installing developer tools on a Dev Drive, we recommend assessing the tradeoffs of the system and async scanning to ensure it meets the required security posture for your device and organization. You may choose whether or not to create an admin or per-user folder on Dev Drive, as well as validate that Microsoft Defender Performance Mode (eg: async scanning) meets your requirements for binaries.

**Comment by mattwojo** [comment]
Thanks for raising this issue @Neme12!
And for investigating the resolution, Adam.
I updated the recommendations to include these considerations for installing tools and SDKs on a Dev Drive.
Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
