### ISSUE TITLE
Process Name Table is Missing Process Names

### ISSUE THREAD

**Issue by ekk88d** [MicrosoftDocs/windows-uwp#4857]
The [Process Name Table](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager#:~:text=Application-,Process%20name,-Microsoft%20Edge) mistakenly lists Executable Names rather than Process Names. This muddies the water, as programs' Executable Names are not the same as Process Names.

For the Keyboard Manager to recognize an app, its [FAQ entry](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager) describes that the user should enter the _Process Name_ in the final remap field.

Ex: `chrome.exe` in the linked table reads as a _Process Name_. However, that's the _Executable File's Name_. The actual Process Name should simply be input for remapping as `chrome`. Maybe Keyboard Manager recognizes both Executable File and Process Name, but this FAQ entry conflates the two types and needs to distinguish — or just replace the Executable Names with their actual Process Names.

Thanks for continuing to develop PowerToys. It's indispensable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7635bf3-62fb-b9b7-7a2c-286dc108ab17
* Version Independent ID: 890589e7-751b-9a0e-bda9-c7b1aa3f5102
* Content: [PowerToys Keyboard Manager utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager)
* Content Source: [hub/powertoys/keyboard-manager.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md)
* Service: **dev-environment**
* Sub-service: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback. I went ahead and created an internal work item to address your suggestions. The wording for these processes is different in different places. `tasklist` call it "Image Name" and includes the `.exe`. `Get-Process` calls it process name but doesn't display the `.exe` in the column. It's hard to drill down to the this image/process/exe name in Task Manager for some processes. So, I left the names that work in the column and updated the header to indicate that this is how they're listed in `tasklist`. I also added a note after the table about these differences. The PR has bee merged and should be live shortly.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
