### ISSUE TITLE
installing react js

### ISSUE THREAD

**Issue by amkynx** [MicrosoftDocs/windows-uwp#4859]
problem installing react js

---
#### Document Details
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/112457462/11f89ffe-78c7-462f-9349-f83c3ab386cc)

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34e0f433-2330-7203-4baf-2038644976d2
* Version Independent ID: cd2b0a17-21c5-3594-a38b-326b74be8ff0
* Content: [Install React on Windows](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-on-windows)
* Content Source: [hub/dev-environment/javascript/react-on-windows.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/react-on-windows.md)
* Service: **dev-environment**
* Sub-service: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@amkynx - I'm not sure what the issue is, but if you uncover it, please reopen this to share how the documentation should be updated. Thank you!
