### ISSUE TITLE
Obvious Chinese Grammar Issues in the Translated Content

### ISSUE THREAD

**Issue by narukeu** [MicrosoftDocs/windows-uwp#4861]
### Type of issue

Typo

### Feedback

Content: The "Remarks"（备注） section of this article fundamentally deviates from Chinese grammar. I hope it can be improved.
![279CFF4BFB4C989B3C3B00B016EB888A](https://github.com/MicrosoftDocs/windows-dev-docs/assets/127817147/4257783e-1825-4ce5-8cf5-7049d2375871)

### Page URL

https://learn.microsoft.com/zh-cn/windows/dev-environment/javascript/react-on-windows

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/react-on-windows.md

### Author

@mattwojo

### Document Id

cd2b0a17-21c5-3594-a38b-326b74be8ff0

**Comment by narukeu** [comment]
The content I translated can be used as a reference:
npx 是 npm 用来代替全局安装来执行包的包运行器。它基本上会为 React 创建一个临时安装,这样每一个新项目都能使用 React 的最新版本(而不是你进行全局安装时的当前版本)。使用 NPX 包运行器来执行包也可以帮助减少在机器上安装大量包导致的污染。

**Comment by GrantMeStrength** [comment]
Reaching out to Localization team.

**Comment by GrantMeStrength** [comment]
As per Loc team, a new bug has been created (950181). Thank you for submitting this.
