### ISSUE TITLE
[Powertoys][Keyboard Manager] Incorrect table in doc

### ISSUE THREAD

**Issue by NewtonChutney** [MicrosoftDocs/windows-uwp#4862]
### Type of issue

Typo

### Feedback

Hello,
In the docs, which link from https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md#remapping-shortcuts, the shortcuts in the table are in reverse to what has been described in the paragraph above and in the picture.
Please correct these entries.

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. Just to be sure, can you specify the shortcuts?

**Comment by Jay-o-Way** [comment]
Small, but fair point. I can pick this up.

**Comment by Jay-o-Way** [comment]
FYI @stefansjfw the image is incorrect

**Comment by stefansjfw** [comment]
🤦 Good catch! Are you still willing to pick this up? :)
