### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by WillVanKeulen** [MicrosoftDocs/windows-uwp#487]
The ms shortlink to the xbl uwp tools (https://aka.ms/xboxliveuwptools) is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5925eaf6-146d-3190-891e-897ed00d7830
* Version Independent ID: 74e206d6-93b8-d668-93e7-19140a4ba49e
* Content: [Development tools for Xbox Live - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/tools/tools)
* Content Source: [windows-apps-src/xbox-live/tools/tools.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/tools/tools.md)
* Service: **unspecified**
* GitHub Login: @staceyhaffner
* Microsoft Alias: **kevinasg**

**Comment by KevinAsgari** [comment]
Thank you for reporting the broken link.  I forwarded the information to the team, and they have fixed the issue, so you should be able to once again download the tools.
