### ISSUE TITLE
Finnish language is missing in the list

### ISSUE THREAD

**Issue by sbrahul** [MicrosoftDocs/windows-uwp#4871]
### Type of issue

Missing information

### Feedback

"Finnish" is missing in the available character set documentation page even though the latest version (v0.78.0) has it in the drop down list in the settings.

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/quick-accent

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md

### Author

@alvinashcraft

### Document Id

affbed27-28f0-71c2-5a82-b12922b5b3c2

**Comment by alvinashcraft** [comment]
Finnish has been added to the list in the docs now. Thanks for raising this issue!
