### ISSUE TITLE
Categories and subcategories options for app properties no more has the "Games" option

### ISSUE THREAD

**Issue by radu-dnl-caphyon** [MicrosoftDocs/windows-uwp#4872]
### Type of issue

Outdated article

### Feedback

When trying to upload an MSIX app (a game app) into Microsoft Store the "Games" option is no more available under "Category" app property.

I think your below user guide article may be outdated.

[https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/categories-and-subcategories?pivots=store-installer-msix](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/categories-and-subcategories?pivots=store-installer-msix)

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/categories-and-subcategories?pivots=store-installer-msix

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/categories-and-subcategories.md

### Author

@GrantMeStrength

### Document Id

cbdc6571-5003-60e7-9652-dff0fad08378

**Comment by GrantMeStrength** [comment]
Thank you for reporting this!

The ‘Game’ category has been removed from the MSIX apps properties page and it has been added under the Game product. The docs are currently being updated.
