### ISSUE TITLE
Typo (I think)

### ISSUE THREAD

**Issue by Jymms** [MicrosoftDocs/windows-uwp#4873]
### Type of issue

Typo

### Feedback

I think "people.Where ..." when you are creating TempFiltered should be People.Where...  I'm not testing it in code behind so I'm not sure.  

Also using MVVM ObservableCollection<Person> PeopleFiltered = new ObservableCollection<Person>(People); gives an error or (People) So I just ran the filter method with a empty string

sidebar question: wouldn't PeopleFiltered.ClearAll() then adding all from TempFiltered be faster? 

### Page URL

https://learn.microsoft.com/en-us/windows/apps/design/controls/listview-filtering

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/controls/listview-filtering.md

### Author

@jwmsft

### Document Id

3163221d-fe4c-84f0-895c-0366f4c72263

**Comment by jwmsft** [comment]
Thanks for the feedback. `people.Where` was indeed a typo, and it's been corrected. The original author of the article and code is no longer available, so I've created a work item to do a complete review of the article and code when scheduling allows. I suspect you're correct about `PeopleFiltered.ClearAll` being faster.
