### ISSUE TITLE
1

### ISSUE THREAD

**Issue by t-user7** [MicrosoftDocs/windows-uwp#4875]
### Type of issue

Other (describe below)

### Feedback

Don't know 

### Page URL

https://learn.microsoft.com/es-es/windows/apps/get-started/sign-up

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/sign-up.md

### Author

@QuinnRadich

### Document Id

e990aa35-b577-3586-c4dd-8b78aaf6e64e

**Comment by Karl-Bridge-Microsoft** [comment]
no issue reported
