### ISSUE TITLE
Setting NUGET_PACKAGES breaks dotnet tools

### ISSUE THREAD

**Issue by kevkov** [MicrosoftDocs/windows-uwp#4877]
### Type of issue

Code doesn't work

### Feedback

There is an issue for this here https://github.com/dotnet/sdk/issues/15306. The documentation should the warn the user about this and hopefully provide a work around. Unfortunately, it does reduce the utility of having a dev drive to a significant extent.

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/#storing-package-cache-on-dev-drive

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by AdamBraden** [comment]
@mattwojo - please add a known issue regarding the dotnet tools issue referred to above.

**Comment by mattwojo** [comment]
Added a note about this known issue for awareness under the Nuget package cache recommendations. 
Thanks for raising this issue @kevkov! And for investigating with the .NET team, Adam.
Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
