### ISSUE TITLE
Will search and feed providers be available outside the EEA for orginizations?

### ISSUE THREAD

**Issue by upintheairsheep** [MicrosoftDocs/windows-uwp#4878]
### Type of issue

Missing information

### Feedback

Will custom search and feed providers be editable for organizations outside the EEA using Group Policy Manager? For example, a business or school in the US having Google set as the default search engine. Additionally, will orginizations outside the EEA be able to set Web Search from Microsoft Bing and Microsoft Edge as uninstallable or uninstall them themselves? 

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/search/search-providers

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/search/search-providers.md

### Author

@drewbatgit

### Document Id

c6d5b252-f5c3-2500-1f7c-c3f201c8eff3

**Comment by drewbatgit** [comment]
@upintheairsheep I'm sorry, but I can't comment on future plans for these features. If there are any changes to the availability in the future it will be noted in the docs.
