### ISSUE TITLE
Add comparison information

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#488]
Are the only differences between Connected Storage and Title Storage that CS is robust to network and power issues while TS supports global per-title readonly data in addition to per-user data?

Also, there's an API in XSAPI for Title Storage. Is there an equivalent for Connected Storage that could be used by a Win32/Centennial game?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6ffe6c5-3134-163d-00b2-86a67e17a1ea
* Version Independent ID: d000afcc-4e7a-a4eb-b632-f2985bad8ad9
* Content: [Xbox Live Storage Platform - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/storage-platform/storage-platform)
* Content Source: [windows-apps-src/xbox-live/storage-platform/storage-platform.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/storage-platform/storage-platform.md)
* Service: **unspecified**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by KevinAsgari** [comment]
@aablackm

**Comment by aablackm** [comment]
Yes, that is the main difference between Connected and Title Storage. Connected Storage is specifically targeted towards enabling continuous play between two devices. 

Connected Storage is currently contained separately in the Xbox Live Extension which you can download at http://aka.ms/xblextsdk

The API is documented in the xblesdk.chm file included with the ZIP file.

**Comment by aablackm** [comment]
Document has been updated with more comparison information. Closing this Issue.
