### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by bolvardev666** [MicrosoftDocs/windows-uwp#4880]
### Type of issue

Typo

### Feedback

**必需的工作负载和组件** 栏下Visual Stdio 2022版本17.1及更高版本中
> 对于使用 Windows 应用 SDK 的 C# 应用开发，请选择“使用 C++ 的桌面开发”

应为: 对于使用 Windows 应用 SDK 的 C++ 应用开发，请选择“使用 C++ 的桌面开发”

### Page URL

https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=cs-vs-enterprise%2Ccpp-vs-community%2Cvs-2022-17-1-a%2Cvs-2022-17-1-b

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md

### Author

@stevewhims

### Document Id

1a4d4425-689e-4d3a-1248-a1dd5789d285

**Comment by stevewhims** [comment]
Thank you! We're investigating.

**Comment by stevewhims** [comment]
I've raised this issue with the team that does the translation. So they'll be able to track it. So I'll close this. :)

Thanks again!
-Steve
