### ISSUE TITLE
Unable to install winget into Windows Sandbox

### ISSUE THREAD

**Issue by padlock780** [MicrosoftDocs/windows-uwp#4882]
### Type of issue

Code doesn't work

### Feedback

`$progressPreference = 'silentlyContinue'
Write-Information "Downloading WinGet and its dependencies..."
Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx -OutFile Microsoft.UI.Xaml.2.7.x64.appx
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.UI.Xaml.2.7.x64.appx
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle`

Microsoft.UI.Xaml.2.8 is requried by Microsoft.DesktopAppInstaller using Windows Sandbox on Windows 11 22H2 February 2024 CU.

Using this command does not fix the issue.

`Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.5/Microsoft.UI.Xaml.2.8.x64.appx -OutFile Microsoft.UI.Xaml.2.8.x64.appx`

Error Recieved

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.22.10582.0_x64__8wekyb3d8bbwe because this package depends 
on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.8" published by "CN=Microsoft 
Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and 
minimum version 8.2310.30001.0, along with this package to install.
NOTE: For additional information, look for [ActivityId] 3f76b5c0-6a60-0006-ea62-773f606ada01 in the Event Log or use the 
command line Get-AppPackageLog -ActivityID 3f76b5c0-6a60-0006-ea62-773f606ada01
At line:7 char:1
+ Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\WDAGUt...bbwe.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

```

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md

### Author

@mattwojo

### Document Id

b49c32ea-2efa-b090-7123-87c31d10279b

**Comment by mattwojo** [comment]
Hey @padlock780 - Thanks for filing this issue. I just heard from the WinGet PM that there is a new dependency due to a new version of the UI.Xaml framework release for WinGet 1.7. The PR to fix the PowerShell module is in progress:
https://github.com/microsoft/winget-cli/pull/4218
Once the fix is merged and we are able to test and ensure that the WinGet installation works properly in Windows Sandbox, we will update the doc to reflect the new install script. 
I will post updates here as I receive them and we will hopefully have this issue resolved within the next few days.

**Comment by mattwojo** [comment]
Hey @padlock780 -- I believe this issue is resolved by https://github.com/MicrosoftDocs/windows-dev-docs/commit/cac9dab23803c52be58476538dc44ea9d6cda031, but if you find this not to be the case, please re-open this issue. <3
