### ISSUE TITLE
Sample instructions need to be updated

### ISSUE THREAD

**Issue by sharad-sharma-msft** [MicrosoftDocs/windows-uwp#4884]
### Type of issue

Code doesn't work

### Feedback

Project '..\ExampleWidgetProvider\ExampleWidgetProvider.csproj' targets 'net6.0-windows10.0.22621.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.5.1'.	ExampleWidgetProviderPackage

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-cs

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/implement-widget-provider-cs.md

### Author

@drewbatgit

### Document Id

2f5a3713-5a3b-6cde-b947-cffc226ae1d2

**Comment by sharad-sharma-msft** [comment]
I am trying to work on a FHL project and this is blocking me.

**Comment by drewbatgit** [comment]
@sharad-sharma-msft I recently updated the how-to code to use some C# 11 features, which required me to update the example to target .NET 8.0. In the process of doing the update, I walked through all of the steps and was able to build and deploy successfully. I've followed up in email. If you are still blocked you can follow up with me on that thread.
