### ISSUE TITLE
All the Characters in Quick Accent utility

### ISSUE THREAD

**Issue by X-shoucheng** [MicrosoftDocs/windows-uwp#4886]
### Type of issue

Other (describe below)

### Feedback

I like Quick Accent utility very much and I want it be better for using.
Can I get a table of every keys corresponding to the characters in every character sets. That way I can know which characters are available to type.
Can I use more than one character sets, not only one sets or all sets.
I would appreciate it very much if you can achieve it.

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message.

> Can I get a table of every keys corresponding to the characters in every character sets. That way I can know which characters are available to type.

The PowerToys are still very much under construction and additions are still made. Not a bad idea though, but I wonder how and where would be the best solution... Maybe @damienleroy has an idea?

> Can I use more than one character sets, not only one sets or all sets.

This is being discussed in issue https://github.com/microsoft/PowerToys/issues/21261

**Comment by X-shoucheng** [comment]
More characters are available in Quick Accent. I hope the table including all characters can be made.

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as feedback about the product. If you visit the [PT issue](https://github.com/microsoft/PowerToys/issues/21261) that @Jay-o-Way reference, then you'll be able to discuss this product idea further. Thanks!
