### ISSUE TITLE
[Suggestion] Unclear about encoding of name parameter in the URL( set machine name REST)

### ISSUE THREAD

**Issue by VitorX** [MicrosoftDocs/windows-uwp#489]
We need to encode it using base64 encoding or it will throw HTTP 500 error. Suggest modify the the document to make it more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ab644-ee7d-3dec-cd0f-cbb1e4d8b6ac
* Version Independent ID: 97eecc36-8e2e-d4c7-1ecb-948e0846bda5
* Content: [Device Portal core API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core#os-information)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Service: **unspecified**
* GitHub Login: @muhsinking
* Microsoft Alias: **jken**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @VitorX. The topic has been updated.
