### ISSUE TITLE
Hibernate

### ISSUE THREAD

**Issue by boscom** [MicrosoftDocs/windows-uwp#4894]
### Type of issue

Typo

### Feedback

Scenario: PowerToys Awake is set for 3 hours, and Windows is set to hibernate when lid is closed. What happens if I close the lid at hour # 2? Will PowerToys Awake prevent the laptop from hibernating? Or will the laptop hibernate?

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/awake

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/awake.md

### Author

@alvinashcraft

### Document Id

29236a0e-82e8-92d7-a5fb-12a9a777bcc2

**Comment by alvinashcraft** [comment]
Thanks for your feedback. I don't believe the utility will prevent any user-initiated actions, like closing the lid to hibernate or selecting Hibernate from the shutdown menu in Windows. I will add a note to the documentation.

**Comment by Jay-o-Way** [comment]
@SamChaps

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. I've updated the topic to indicate that user-initiated actions like hibernating your computer or manually putting it to sleep are not prevented by this utility. The changes should be live soon. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
