### ISSUE TITLE
Rethink Deprecation of WSA

### ISSUE THREAD

**Issue by mikelor** [MicrosoftDocs/windows-uwp#4895]
### Type of issue

Missing information

### Feedback

Seriously, what is the motivation behind this deprecation. Windows Subsystem for Android works so well for my inner dev loop with mobile and C#.  With this step, I'm beginning to rethink the relevance of Windows and Microsoft in my tech stack.

Please rethink this decision.

### Page URL

https://learn.microsoft.com/en-gb/windows/android/wsa/?ranMID=24542&ranEAID=kXQk6*ivFEQ&ranSiteID=kXQk6.ivFEQ-eegWVcFF.OQsnedaC.tDkA&epi=kXQk6.ivFEQ-eegWVcFF.OQsnedaC.tDkA&irgwc=1&OCID=AIDcmm549zy227_aff_7593_1243925&tduid=(ir__gkldqm3cw0kfdkuxjgyp2x6zc32x9bgbxs6ntw9h00)(7593)(1243925)(kXQk6.ivFEQ-eegWVcFF.OQsnedaC.tDkA)()&irclickid=_gkldqm3cw0kfdkuxjgyp2x6zc32x9bgbxs6ntw9h00

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/index.md

### Author

@mattwojo

### Document Id

31f9a801-c5b5-94e7-41b9-1b2b4a1d27de

**Comment by mattwojo** [comment]
Unfortunately I just handle the documentation and can't speak to the business decision or motivations and everything that I know went into the announcement. Doesn't look like this requires a doc update, so closing, but I did pass this along to the stakeholders that I know of for their awareness.
