### ISSUE TITLE
Defender exclusions

### ISSUE THREAD

**Issue by FristVoid** [MicrosoftDocs/windows-uwp#4897]
### Type of issue

Other (describe below)

### Feedback

Correct me if I am wrong, but doesn't defender run under system, so %userprofile% would never match?  In addition is it a good idea to mention folder exclusions in user writable folders?  

### Page URL

https://learn.microsoft.com/en-us/windows/android/defender-settings#exclusions-to-consider-for-android-development

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/defender-settings.md

### Author

@mattwojo

### Document Id

8e95d16d-aa68-38c2-ac75-008f76b767a7

**Comment by mattwojo** [comment]
Great call-out! Thank you @FristVoid! 
Updating the guidance on this page now.

**Comment by mattwojo** [comment]
You can see the updates here: https://learn.microsoft.com/en-us/windows/android/defender-settings#exclusions-to-consider-for-android-development  Please reopen this issue and let me know if anything doesn't look quite right. Thanks again for bringing this to our attention!
