### ISSUE TITLE
this fails certification in the store

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#490]
certification fails with api supported test in the store by using this tutorial with following error : 
API sqlite3_win32_set_directory in winsqlite3.dll is not supported for this application type. SQLitePCLRaw.provider.winsqlite3.dll calls this API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by bricelam** [comment]
Also reported here: ericsink/SQLitePCL.raw#198

**Comment by normesta** [comment]
Closing this issue as the link that Bricelam provides above captures the blocking issue. It's sounding like a solution is in the works that will unblock store submission hopefully by RS5.
