### ISSUE TITLE
Missing spaces in Russian document version

### ISSUE THREAD

**Issue by kawaiianxiety** [MicrosoftDocs/windows-uwp#4907]
### Type of issue

Typo

### Feedback

Hi! I noticed that there's some missing spaces.
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/71761423/97ff88fa-f284-4b3f-9dac-68bdf5e67b54)

### Page URL

https://learn.microsoft.com/ru-ru/windows/powertoys/image-resizer

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/image-resizer.md

### Author

@alvinashcraft

### Document Id

393934c9-4dd3-50c2-719a-e48b724a77a0

**Comment by GrantMeStrength** [comment]
Thank you. Bug filed with localization team.
