### ISSUE TITLE
Fixed size is recommended for efficiency but windows recommends Dynamically expanding

### ISSUE THREAD

**Issue by jimSampica** [MicrosoftDocs/windows-uwp#4908]
### Type of issue

Other (describe below)

### Feedback

Under heading "Create new VHD" and bullet point "Disk type" it states...

> Disk type:
> - Fixed size - This virtual hard disk file is allocated to the maximum size when created (Recommended for efficiency)
> - Dynamically expanding - Grows to maximum size as data is written

However on windows when creating the dev drive it states "Dynamically expanding (recommended)". Which option is the recommended configuration for Dev drives?

![Screenshot 2024-03-14 184829](https://github.com/MicrosoftDocs/windows-dev-docs/assets/2416676/d0356872-4b61-4b83-94ed-5e42f9a52a4e)

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by ofthelit** [comment]
https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/images/dev-drive-create-vhd-options.png

The screenshot does not match the text. This contradiction confused me.
The document should still tell why one would use the fixed size option.

**Comment by mattwojo** [comment]
Fixed in https://github.com/MicrosoftDocs/windows-dev-docs/commit/740dd8debc0ef816144590d20888fe55bb08df94
