### ISSUE TITLE
How to cancel a job using async keyword?

### ISSUE THREAD

**Issue by kevin-jing** [MicrosoftDocs/windows-uwp#491]
When you use work-item handlers that use the async keyword, be aware that the thread pool work item may be set to the complete state before all of the code in the handler has executed. Code following an await keyword within the handler may execute after the work item has been set to the complete state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c61d982-89b3-bbb9-f1da-b16c3c219560
* Version Independent ID: 44f86b1f-1d04-74f4-61fe-c48c13eff8df
* Content: [Best practices for using the thread pool - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/threading-async/best-practices-for-using-the-thread-pool)
* Content Source: [windows-apps-src/threading-async/best-practices-for-using-the-thread-pool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/threading-async/best-practices-for-using-the-thread-pool.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you for reaching out to the doc team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation. You may have success posting your question to the forums described on the following page where other developers and Microsoft engineers can be found: https://developer.microsoft.com/en-us/windows/support. Thank you for reaching out to us.
