### ISSUE TITLE
Pivot: deprecated or not?

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/windows-uwp#4910]
### Type of issue

Outdated article

### Feedback

Please let us know what the latest info is about the Pivot control. Is it deprecated or not? Note that https://github.com/microsoft/microsoft-ui-xaml/issues/5102 mentions
> The Pivot control has been added back in and can now be used in any WinUI 3 app.

https://learn.microsoft.com/windows/apps/design/controls/pivot is for sure out of date, so please update that page too.

**Comment by Jay-o-Way** [comment]
Answered in https://github.com/microsoft/WinUI-Gallery/pull/1508#issuecomment-2013992248

**Comment by jwmsft** [comment]
The [Pivot documentation](https://learn.microsoft.com/windows/apps/design/controls/pivot#is-this-the-right-control) is updated with the latest guidance.

To be clear, Pivot is "_not recommended_", but it is not "_deprecated_". While these terms are sometimes used to mean the same thing in casual conversation, they're not the same. In order for us to say in the docs that a control or API is deprecated, it's source code needs to be updated with the 'deprecated' attribute, which causes a warning in Visual Studio. The bar to officially deprecate a control or API is fairly high, so it rarely happens.
