### ISSUE TITLE
Conflicting info in Create new VHD section for Dev Drive

### ISSUE THREAD

**Issue by vinod-unny-eit** [MicrosoftDocs/windows-uwp#4914]
### Type of issue

Other (describe below)

### Feedback

There are 2 pieces of conflicting information in the "Create new VHD" section for Dev Drives.

1. The VHDX option says "supports virtual disks up to 64 TB". However, the screenshot below says "supports virtual disk up to 2040 GB" for the same option.
2. Under "Disk Type", the text says "Recommended" for the "Dynamically expanding" option, while the screenshot shows the "Fixed size" option to be the recommended one.

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by mattwojo** [comment]
Thanks @vinod-unny-eit. #2 was resolved here: https://github.com/MicrosoftDocs/windows-dev-docs/commit/d1e11a591ffa5e44d5a7242b5ecd9a246ff1569f

I'm working on getting some clarification regarding #1 and will add an update as soon as I have a clear answer.

**Comment by mattwojo** [comment]
The Dev Drive creation user interface has been updated to fix these issues and is rolling out over the various build updates. The fixed user interface will look like the screenshot below. The VHDX format supports a max of 64 TB and the VHD format supports up to 2040 GB. The recommended disk format is Dynamically expanding.
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/7566797/f2880afa-4b60-4942-b01f-319d80d11be6)

Fix is on it's way in to the docs.
