### ISSUE TITLE
Getting Started steps are throwing error

### ISSUE THREAD

**Issue by naveennooka** [MicrosoftDocs/windows-uwp#4919]
### Type of issue

Missing information

### Feedback

<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>

This tag doesnt work when user selects the target framework as .NET 8 and above. It instead should be
<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>

### Page URL

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/wpf-plus-winappsdk

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/wpf-plus-winappsdk.md

### Author

@stevewhims

### Document Id

95ab2ce8-6224-551b-da0e-9e869a1a15a7

**Comment by stevewhims** [comment]
Thank you! I've updated the topic.

-Steve
