### ISSUE TITLE
Is that possible to cancel a work item before it's completed?

### ISSUE THREAD

**Issue by kevin-jing** [MicrosoftDocs/windows-uwp#492]
When necessary, call the Cancel method to stop the periodic work item from repeating. If the work item is running when the periodic timer is cancelled it is allowed to complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1e890-2428-d972-1b2b-da2decc62818
* Version Independent ID: 61b93a78-68b1-c27b-74af-a758a47fb07e
* Content: [Create a periodic work item - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/threading-async/create-a-periodic-work-item)
* Content Source: [windows-apps-src/threading-async/create-a-periodic-work-item.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/threading-async/create-a-periodic-work-item.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hello - Thanks for reaching out to us. I'm unaware of any way to cancel work item that is already running. If you discover a way to do this, please share and I'll update the doc - or - feel free to issue us a pull request directly. You may have success posting your question to the forums described on the following page where other developers and Microsoft engineers can be found: https://developer.microsoft.com/en-us/windows/support. Thank you for reaching out to us.
