### ISSUE TITLE
Problem with Arabic OCR using PowerToys Text Extractor

### ISSUE THREAD

**Issue by Moskitoz** [MicrosoftDocs/windows-uwp#4922]
### Type of issue

Missing information

### Feedback

Hello, I've a Problem with Arabic OCR using PowerToys Text Extractor

 have 2 pc

computer A connected to the internet
computer B not connected to the internet

PowerToys on computer A works fine with ARABIC OCR
PowerToys on computer B don't works fine with ARABIC OCR

I've copy the files from computer A to computer B

c:\windows\OCR\*

en_US
ar-SA

but still when using the text-extractor on Arabic text with different fonts still five me symbols any solution please to make the computer B offline make it capture ARABIC OCR? using offline mode?

note: Arabic language is added on both computer

I mean both computer I can read and write on them Arabic language

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/text-extractor

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md

### Author

@alvinashcraft

### Document Id

0badd1c2-7821-cc2f-cec0-9913a5e16eb1

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
