### ISSUE TITLE
Incorrectly recommending 'Dynamically expanding' disk type for DevDrive

### ISSUE THREAD

**Issue by ghhv** [MicrosoftDocs/windows-uwp#4924]
### Type of issue

Typo

### Feedback

The page is incorrectly recommending this which conflicts with pic and at bottom it says this is an unsupported setup.

Disk type:
Fixed size - This virtual hard disk file is allocated to the maximum size when created
Dynamically expanding - Grows to maximum size as data is written **(Recommended)**

### Page URL

https://learn.microsoft.com/en-gb/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by mattwojo** [comment]
Sorry for the confusion @ghhv. The recommendation changed and this screenshot needs to be updated. Previously, the team had recommended selecting a fixed size VHD for hosting a Dev Drive, but later updated to recommending a Dynamically expanding type. I believe what you're seeing in the Unsupported Scenarios section is: 

> Using Dev Drive on [Dynamic Disks](https://learn.microsoft.com/en-us/windows/win32/fileio/basic-and-dynamic-disks#dynamic-disks) is unsupported.

This refers to "Dynamic Disks" which is different than a Dynamically expanding VHD... yes, confusing. :( 

The primary thing to know is just that the VHD type you're selecting in Windows Settings when creating a Dev Drive determines whether the VHD is "fixed" to a specific maximum size or "dynamically expanding" to whatever size data you store on your Dev Drive.

I will get the screenshot updated now. Thanks for filing this issue.

**Comment by mattwojo** [comment]
https://github.com/MicrosoftDocs/windows-dev-docs/commit/ea4d8d4b1e319d9fad4e177eb9578005a209ae57
Resolved
