### ISSUE TITLE
使用powertoys的 fileRename  我想在所有的文件前面统一增加前缀文本该怎么操作？

### ISSUE THREAD

**Issue by xx791117** [MicrosoftDocs/windows-uwp#4927]
### Type of issue

Typo

### Feedback

例如 文件 01.doc    02.doc    03.doc        我想变为  test-01.doc     test-02.doc   test-03.doc 这该怎么操作？？

### Page URL

https://learn.microsoft.com/zh-cn/windows/powertoys/powerrename

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md

### Author

@alvinashcraft

### Document Id

0be1b400-5349-7dd9-43d2-abd3a91884a6

**Comment by ooooo-create** [comment]
https://learn.microsoft.com/zh-cn/windows/powertoys/powerrename#examples-of-regular-expressions
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/106524776/a6acd849-f5ab-48b2-b8bd-52f4eb3b3e1c)
Hi, is this what you're looking for?

(.*)  
test-$1

**Comment by alvinashcraft** [comment]
This feels resolved, so I'll go ahead and close the issue. Please open a new issue if you have feedback about the documentation that you'd like us to address.
