### ISSUE TITLE
How to do work first then wait 60 sec?

### ISSUE THREAD

**Issue by kevin-jing** [MicrosoftDocs/windows-uwp#493]
It works like wait > work > wait ...
How to work like work > wait > work ...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1e890-2428-d972-1b2b-da2decc62818
* Version Independent ID: 61b93a78-68b1-c27b-74af-a758a47fb07e
* Content: [Create a periodic work item - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/threading-async/create-a-periodic-work-item)
* Content Source: [windows-apps-src/threading-async/create-a-periodic-work-item.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/threading-async/create-a-periodic-work-item.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hello. There's nothing built into the ThreadPoolTimer that facilitates this order. Perhaps perform the task in code (or via a call) just before setting up the periodic work item? You may have success posting your question to the forums described on the following page where other developers and Microsoft engineers can be found: https://developer.microsoft.com/en-us/windows/support. Thank you for reaching out to us.
