### ISSUE TITLE
PowerToys DSC docs: Page layout broken (Note blocks & Plugin table)

### ISSUE THREAD

**Issue by htcfreek** [MicrosoftDocs/windows-uwp#4932]
### Type of issue

Typo

### Feedback

- All Note blocks missing the ! in the definition. [It must be `!Note`.)
- The table for the PowerToysRun Plugin settings is broken.

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/dsc-configure

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/dsc-configure.md

### Author

@alvinashcraft

### Document Id

e6fa3694-8809-7d66-6e77-5be3c59af509

**Comment by htcfreek** [comment]
cc: @alvinashcraft, @ethanfangg , @jaimecbernardo

**Comment by jaimecbernardo** [comment]
Opened a PR with the fix: https://github.com/MicrosoftDocs/windows-dev-docs/pull/4933
Thanks for the call out @htcfreek !
