### ISSUE TITLE
Color picker is not working on outlook (Microsoft 365 ?)

### ISSUE THREAD

**Issue by jmgroud** [MicrosoftDocs/windows-uwp#4938]
### Type of issue

Missing information

### Feedback

With Outlook (Microsoft 365 on Windows 11)
Color picker not working (not supported)
What for?

### Page URL

https://learn.microsoft.com/fr-fr/windows/powertoys/color-picker

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/color-picker.md

### Author

@alvinashcraft

### Document Id

fa8782b8-bba2-8be8-3472-d8876dfa8713

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
