### ISSUE TITLE
no  actualiza repositorios

### ISSUE THREAD

**Issue by Alxmalaga** [MicrosoftDocs/windows-uwp#4939]
### Type of issue

Code doesn't work

### Feedback

not working

### Page URL

https://learn.microsoft.com/es-es/windows/dev-home/#dev-home-dashboard-widgets

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/index.md

### Author

@mattwojo

### Document Id

acdf7266-5a5a-10a9-25bc-94f01b3e5d0a

**Comment by mattwojo** [comment]
Please provide more information on what code you are finding that does not work in this documentation and reopen this issue.
