### ISSUE TITLE
is someone payed-by-the-line of code?

### ISSUE THREAD

**Issue by jtorjo** [MicrosoftDocs/windows-uwp#494]
String migrateMessage =
            "Would you like to migrate your data from the previous version of this app?";
        DialogResult migrateResult = MessageBox.Show
            (migrateMessage, "Data Migration", MessageBoxButtons.YesNo);
        if (migrateResult.Equals(DialogResult.Yes))

Are you kidding me? You have to create a temp variable for the message caption, and then use "uninstallResult.Equals" ? The code looks horrible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c479e308-a9e4-8ab4-ada9-b9d6720580b1
* Version Independent ID: 9b204f22-b4cc-fb8d-24b7-f0d4a69f9e4e
* Content: [Publish your packaged desktop app to a Windows store or sideload it onto one or more devices. - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-distribute)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-distribute.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-distribute.md)
* Service: **unspecified**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thx for the suggestion! The code's been updated.
