### ISSUE TITLE
Manage Store listing , I am unable to import listing with an error "The main logo (1:1 box art) is mandatory" 

### ISSUE THREAD

**Issue by xramm57** [MicrosoftDocs/windows-uwp#4940]
### Type of issue

Other (describe below)

### Feedback

When I am in last step, in Manage Store listing step , I am unable to import listing with the below errors, even though I have entered inside the  .csv file 1:1as  .png image and screenshot image as .png which meets the standards from import listing for resolution and file type.

Screenshots,Turkish (Turkey),At least one screenshot is mandatory.
StoreLogos1,Turkish (Turkey),The main logo (1:1 box art) is mandatory.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/import-and-export-store-listings

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/import-and-export-store-listings.md

### Author

@GrantMeStrength

### Document Id

951ae6f2-b0fe-1472-8795-2b55bf0ee181

**Comment by GrantMeStrength** [comment]
Investigating

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
