### ISSUE TITLE
`sr` listed as supported language, gives error `0x80070057`

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/windows-uwp#4943]
### Type of issue

Missing information

### Feedback

Following doc:

* <https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/supported-languages#list-of-supported-languages>

Lists `sr` as a valid language code. But adding `<Resource Language="sr" />` to `AppxManifest.xml` gives error `0x80070057` saying:

`App installation failed with error message: 8bitSolutionsLLC.bitwardendesktop_2024.3.2.0_x64__h4e712dmw3xyy : error 0x80070057 : Cannot register the 8bitSolutionsLLC.bitwardendesktop_2024.3.2.0_x64__h4e712dmw3xyy package because the specified resource language 'sr' is not a valid language. (0x80070057)`

This happened with Bitwarden recently:

* <https://github.com/bitwarden/clients/issues/8653>

Either the doc is wrong, or Appx installation does not adhere to what the doc says.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/supported-languages#list-of-supported-languages

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/supported-languages.md

### Author

@GrantMeStrength

### Document Id

a47179f9-f284-5d60-7141-9c7a6b1c52e1

**Comment by BlueRain-debug** [comment]
I didn't find sr in the list, and iirc you need to use at least "sr-latn" or "sr-cyrl" to distinguish between Latin and Cyrillic.

**Comment by GrantMeStrength** [comment]
Investigating

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
