### ISSUE TITLE
Please allow key remapping in specific apps, now only shortcut keys can be remapped

### ISSUE THREAD

**Issue by ThreeAurora** [MicrosoftDocs/windows-uwp#4949]
### Type of issue

Typo

### Feedback

Currently only specific apps are allowed to remap shortcut keys, not keys.

I hope to add this function

### Page URL

https://learn.microsoft.com/zh-cn/windows/powertoys/keyboard-manager#keys-that-cannot-be-remapped

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md

### Author

@alvinashcraft

### Document Id

890589e7-751b-9a0e-bda9-c7b1aa3f5102

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
