### ISSUE TITLE
Power Rename isn't 'Resize with Power Rename'

### ISSUE THREAD

**Issue by markweatherill99** [MicrosoftDocs/windows-uwp#4953]
### Type of issue

Typo

### Feedback

To access Power Rename, one doesn't select 'Resize with Power Rename'. A spurious 'Resize with ' has crept in!

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/powerrename

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md

### Author

@alvinashcraft

### Document Id

0be1b400-5349-7dd9-43d2-abd3a91884a6

**Comment by Jay-o-Way** [comment]
@markweatherill99 what version of PowerToys you using?

**Comment by markweatherill99** [comment]
I'm using v0.80.1.

**Comment by Jay-o-Way** [comment]
The entry had changed in the past, to show the difference with the normal "rename". Can you show what it looks like for you?

**Comment by markweatherill99** [comment]
if I follow the link at 'Page URL' in my original post, it leads me to the document that includes the text 'Resize with PowerRename', which I think should say 'Rename with PowerRename', which is what the context menu has.

**Comment by Jay-o-Way** [comment]
Ohhhhh I see!

**Comment by Jay-o-Way** [comment]
JSYK @niels9001
