### ISSUE TITLE
Microsoft store isn't safe

### ISSUE THREAD

**Issue by Mostafat64** [MicrosoftDocs/windows-uwp#4954]
### Type of issue

Other (describe below)

### Feedback

Microsoft store ISN'T SAFE, Yeah that's right ,,, Because it doesn't scan apps that been created by companies or websites,, to be more specific there's App called paladinvpn exists in Microsoft store, it's Trojan Proxy server Virus , its super Severe and could cause a lot of damage to PC users as it Takes personal data to the scammer who made The app (paladinvpn) and use it to steal people accounts , money...etc ,,, so therefore Microsoft store isn't safe as it should be , 

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/why-distribute-through-store

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/why-distribute-through-store.md

### Author

@GrantMeStrength

### Document Id

bf9d9ba4-3402-dde0-ace6-2e5c6826b379

**Comment by Paladin-VPN** [comment]
We're puzzled as to why our free VPN service is being singled out, while others like BrightVPN.com, Hola.org, and Urban-VPN.com are considered acceptable and aren't mentioned in your post, despite having a larger user base than PaladinVPN. PaladinVPN transparently explains on its website and during installation why the service is free, as detailed in the review on [VPNCentral](https://vpncentral.com/paladin-vpn-review/).

Furthermore, the Honeygain.com app allows users to utilize your IP address and bandwidth in exchange for a small revenue share. Again it seems we are being unfairly targeted to damage our business.

**Comment by Mostafat64** [comment]
I download paladinvpn from Microsoft store suddenly my windows defender detect 4 viruses when I launched Paladinvpn,,, one virus name was Detected: TrojanProxy:Win32/Acapaladat.A ,,,, look at the name of the virus it's kinda have the same letters of paladinvpn = paladat ,,,,, Also my windows defender have considered the viruses as severe ,,, so There's no doubt that Paladinvpn is virus Spreader ,,, Also I haven't spoke about other companies because I never tried them yet , so no one is targeting you ,

**Comment by Mostafat64** [comment]
> We're puzzled as to why our free VPN service is being singled out, while others like BrightVPN.com, Hola.org, and Urban-VPN.com are considered acceptable and aren't mentioned in your post, despite having a larger user base than PaladinVPN. PaladinVPN transparently explains on its website and during installation why the service is free, as detailed in the review on [VPNCentral](https://vpncentral.com/paladin-vpn-review/).
> 
> Furthermore, the Honeygain.com app allows users to utilize your IP address and bandwidth in exchange for a small revenue share. Again it seems we are being unfairly targeted to damage our business.

Ĺ

**Comment by Mostafat64** [comment]
Will will will ,,, I was right about Paladinvpn , as the website Paladinvpn.com was Seized by FBI and 3 other agencies , and the creator of this evil program was arrested in USA ,,,, great Job and I hope all hackers get the same .
