### ISSUE TITLE
Submission Issue

### ISSUE THREAD

**Issue by startatrix** [MicrosoftDocs/windows-uwp#4955]
### Type of issue

Missing information

### Feedback

There needs to be more information about how to publish app to the store. A good video of a step by step would be nice. I found that the process is not well described. For example I am trying to submit an app with Trial settings. A link to the profile area would be good when you get errors about the tax profile setup. Once I made all my Tax profile changes and submitted to Microsoft for verification, I am still getting "You need to update your tax and payout information before you can charge money" error and the submit button is disabled. I checked only to see I can get an answer but it looks like it's a problem with the portal . 
I found the same issue that I am experiencing here. https://learn.microsoft.com/en-us/answers/questions/573551/bank-and-tax-profiles-validated-but-still-get-you?comment=question#newest-question-comment

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/app-certification-process

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/app-certification-process.md

### Author

@GrantMeStrength

### Document Id

4e55fb53-7eb0-d5ef-e32f-e558461d6e88

**Comment by GrantMeStrength** [comment]
Thank you. I will pass this information directly to the Store team. I know they are updating all the docs all the time.
-john

**Comment by david-mazzeo** [comment]
Did you ever find a solution to this issue? I'm experiencing it now and I can't find any solutions whatsoever - plus trying to get in contact with Microsoft has been a waste of time.
