### ISSUE TITLE
MS Forms signup link is closed

### ISSUE THREAD

**Issue by IsaacHatton** [MicrosoftDocs/windows-uwp#4960]
### Type of issue

Other (describe below)

### Feedback

The signup button doesn't work and the opt-out link doesn't work either for me.

Sign up links to this: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRxmldwLByptEu0fsWe3hlg1UNjYyVlFWV0UwTFk4U1dUQktOMzIyWFE4Qy4u
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/74068072/74bf7eac-41f4-441d-a716-8245c27ddc3c)

### Page URL

https://learn.microsoft.com/en-us/windows/android/wsa/preview-program

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/preview-program.md

### Author

@hamza-usmani

### Document Id

9e611135-e472-e8a7-a048-7dd38e0f7a6a

**Comment by mattwojo** [comment]
Hi @IsaacHatton - Yes, unfortunately, the Windows Subsystem for Android program has been discontinued.
