### ISSUE TITLE
BODCAST

### ISSUE THREAD

**Issue by RR3DDD** [MicrosoftDocs/windows-uwp#4962]
### Type of issue

Typo

### Feedback

I

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/age-ratings?pivots=store-installer-add-on

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/age-ratings.md

### Author

@GrantMeStrength

### Document Id

bac33878-35ad-1414-173d-55b3de32f8ba

**Comment by leonardocardenuto** [comment]
Be more specific on the feedback ,please. I was unable to spot the typo.

**Comment by GrantMeStrength** [comment]
Thanks for submitting an issue! I couldn't find a typo. If I missed it (it has recently been updated) please provide more details, thank you!
