### ISSUE TITLE
PowerRename: not showing up in right-click menu

### ISSUE THREAD

**Issue by etfovac** [MicrosoftDocs/windows-uwp#4963]
### Type of issue

Code doesn't work

### Feedback

![2024-04-22_214102](https://github.com/MicrosoftDocs/windows-dev-docs/assets/27641233/3e32abc5-10ab-4dce-a534-e834c330fea3)
![2024-04-22_214202](https://github.com/MicrosoftDocs/windows-dev-docs/assets/27641233/0c72c260-4bc3-40f2-8ae2-f914cb13961d)

### Page URL

https://learn.microsoft.com/en-gb/windows/powertoys/powerrename

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md

### Author

@alvinashcraft

### Document Id

0be1b400-5349-7dd9-43d2-abd3a91884a6

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. This repository is actually about the documentation, not intended for bugs. Having that said, there are a number of existing reports about this issue, for example https://github.com/microsoft/PowerToys/issues/31547

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. You should check out the link that @Jay-o-Way shared in the previous comment. Thanks!
