### ISSUE TITLE
No information on "How to view available dev drives?"

### ISSUE THREAD

**Issue by sriharshamadala** [MicrosoftDocs/windows-uwp#4964]
### Type of issue

Missing information

### Feedback

I have used "new vhd" way to setup my dev drive. after several days I logged in and I couldn't recall where my vhdx file was located.  As a result, I couldn't start my dev drive. Is there a way to (1) auto-mount this VHD so that I can always see my dev drive or (2) in the dev drive settings UI, show the list of such VHDX that were used to setup dev drives.  

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by AdamBraden** [comment]
The dev drive should be automounted. We are aware of a bug in this area and are working to get it serviced. More information about Dev Drive VHDs can be found in Dev Home under Windows Customizations->Dev Drive Insights. 

When a dev drive is mounted but you forgot where its located, you can use the following:

- DISKPART and the "list vdisk" command to show the full path to the vhdx.
- Powershell and "Get-Disk | Select-Object FriendlyName,Location"

For reference - currently if a dev drive vhd becomes dismounted, and the user re-mounts it via File Explorer, DiskMgmt, or powershell, that will not set the automount capability. Currently automount is only supported through the Settings app UI under Disks & Volumes. We are working to plug this feature gap on those other tools.

**Comment by mattwojo** [comment]
Thanks for contributing this issue @sriharshamadala.
And for the recommended methods for finding a drive, Adam! 
I added a section to the FAQs: "How can I find a Dev Drive that I created and lost track of?" with these methods listed.
Updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
