### ISSUE TITLE
Windows Package Manager Enterprise Management Docs

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/windows-uwp#4967]
### Type of issue

Missing information

### Feedback

There aren't any links here. Just links to the root Intune page when mentioning GPOs. Would love some direct links :)

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/#windows-package-manager-for-enterprise-security

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/index.md

### Author

@mattwojo

### Document Id

805fc71b-6b54-3b09-95ef-4254de5e0036

**Comment by mattwojo** [comment]
@johnjohnjohn87 -- Could you share a little more about what sort of links you are interested in? What is the scenario that you're looking for more guidance on?
