### ISSUE TITLE
there is no REG_BOOL

### ISSUE THREAD

**Issue by MCIglo** [MicrosoftDocs/windows-uwp#4968]
### Type of issue

Typo

### Feedback

https://learn.microsoft.com/en-us/windows/apps/develop/settings/settings-windows-11#personalization---start---recommendations
This should be a REG_DWORD, not a REG_BOOL

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/settings/settings-windows-11#personalization---start---recommendations

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/settings/settings-windows-11.md

### Author

@stevewhims

### Document Id

8cf6ba7b-0028-7226-dc6c-8366a83eabeb

**Comment by stevewhims** [comment]
Thanks, I have an update on its way out to the live site.

-Steve

**Comment by SteveL-MSFT** [comment]
@stevewhims this page https://learn.microsoft.com/en-us/windows/apps/develop/settings/settings-common still shows REG_BOOL and should be REG_DWORD
