### ISSUE TITLE
https://aka.ms/xboxliveuwptools link is broken.

### ISSUE THREAD

**Issue by NotorietyRed** [MicrosoftDocs/windows-uwp#497]
The standalone tools link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35971a80-8b95-9201-2133-bfa4e4cddeca
* Version Independent ID: 2e574f12-313c-b28d-863d-46d3054a27de
* Content: [Xbox Live Account Tool - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/tools/xbox-live-account-tool)
* Content Source: [windows-apps-src/xbox-live/tools/xbox-live-account-tool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/tools/xbox-live-account-tool.md)
* Service: **unspecified**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by KevinAsgari** [comment]
Thanks for reporting this!  I've alerted the team that owns the tool, and they're investigating.

**Comment by NotorietyRed** [comment]
No problem, thank you.

**Comment by KevinAsgari** [comment]
Looks like they fixed the issue now, you should be able to download the tools again.
