### ISSUE TITLE
Grand theft auto V

### ISSUE THREAD

**Issue by Denvio1** [MicrosoftDocs/windows-uwp#4975]
### Type of issue

Code doesn't work

### Feedback

Like this videogame

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/age-ratings?pivots=store-installer-msix

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/age-ratings.md

### Author

@GrantMeStrength

### Document Id

bac33878-35ad-1414-173d-55b3de32f8ba

**Comment by GrantMeStrength** [comment]
I'm not sure exactly what issue you are reporting, but this page was recently updated so hopefully resolved your issue.
If not, please re-open or create a new issue. Thanks!
