### ISSUE TITLE
555

### ISSUE THREAD

**Issue by hercules03l** [MicrosoftDocs/windows-uwp#4976]
### Type of issue

Typo

### Feedback

dwewrt35fef

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/age-ratings?pivots=store-installer-msix

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/age-ratings.md

### Author

@GrantMeStrength

### Document Id

bac33878-35ad-1414-173d-55b3de32f8ba

**Comment by leonardocardenuto** [comment]
I could not identify the typo , can you point it out , please?
