### ISSUE TITLE
Some type ramp examples are invisible with dark theme

### ISSUE THREAD

**Issue by jolleekin** [MicrosoftDocs/windows-uwp#4978]
### Type of issue

Other (describe below)

### Feedback

Some type ramp examples are invisible with dark theme
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/5405376/6475caad-3866-4663-ac6d-38949579405a)

### Page URL

https://learn.microsoft.com/en-us/windows/apps/design/signature-experiences/typography#type-ramp

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/signature-experiences/typography.md

### Author

@jwmsft

### Document Id

bc4d9a15-03d1-cbc4-1dff-0d44dd1c2b35

**Comment by jwmsft** [comment]
Fixed by #4979. Thanks!
