### ISSUE TITLE
BluetoothLEDevice dispose

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/windows-uwp#498]
Please, document proper dispose mechanism. Use case:
1. Scan LE device, create it, subscribe to notification, dispose it `bleDevice.Dispose()`.
2. Scan again and the scan ignores the device. See also https://stackoverflow.com/questions/47702584 and others complains on the web.
Questions:
- Is is necessary to unsubscribe? 
- Should the services and sessions be destroyed, too?
- Is is necessary to call `GC.Collect()`?

Please, add a paragraph with a reliable code for proper disconnect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f89409a-b108-603f-9279-c59f5ae5d188
* Version Independent ID: 5bd07919-59ac-4fca-b997-a472ae24bfb1
* Content: [Bluetooth GATT Client - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client#connecting-to-the-device)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Service: **unspecified**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @xmedeko - Sorry for the excessive delay in responding to this issue. I've contacted the feature team for help and have created an internal work item to track progress on a doc update as I get more info. 

Here is the initial response from the feature team:

1) It's a design goal that you cannot control the connect/disconnect, so applications cannot impact each other and applications can't impact the host.

2) The reason you cannot discover if we report disconnected is unlikely related, the following tool can generate traces:

[busiotools/bluetooth/tracing at master · microsoft/busiotools (github.com)](https://github.com/Microsoft/busiotools/tree/master/bluetooth/tracing)

IF we say the device is disconnected, and you can't discover it, there is another issue you are facing, if you provide the traces we can look.

Submit feedback in Feedback Hub with repro traces, of it working, then not working, and share the feedback link.  Or post logs to something like onedrive or dropbox for us to download. 

Another option is the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) who might be able to provide answers to your questions.

If you get more info/details there that you think might be helpful for the docs, please reply to this issue with a link to the Q&A thread.
