### ISSUE TITLE
In the Chinese version of the document, there is a place where C# should be C++. 

### ISSUE THREAD

**Issue by ZKBL** [MicrosoftDocs/windows-uwp#4980]
### Type of issue

Typo

### Feedback

下图中红框位置应该是
  **对于使用 Windows 应用 SDK 的 C++ 应用开发**
![图片](https://github.com/MicrosoftDocs/windows-dev-docs/assets/18417140/3993aea3-691c-43ff-8564-1d54d8860aad)

### Page URL

https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=cs-vs-community%2Ccpp-vs-community%2Cvs-2022-17-1-a%2Cvs-2022-17-1-b

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md

### Author

@stevewhims

### Document Id

1a4d4425-689e-4d3a-1248-a1dd5789d285

**Comment by stevewhims** [comment]
Thanks for the heads up; the localization team are aware of this issue.

-Steve
