### ISSUE TITLE
fsddwqsa

### ISSUE THREAD

**Issue by BendeYt** [MicrosoftDocs/windows-uwp#4988]
### Type of issue

Other (describe below)

### Feedback

fsdasadasaxcsaxdwafdsadsdfdfcvjhsdıochuıdfojosjvnıoerghboeıd

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/age-ratings?pivots=store-installer-msix

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/age-ratings.md

### Author

@GrantMeStrength

### Document Id

bac33878-35ad-1414-173d-55b3de32f8ba

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No actionable feedback provided.
