### ISSUE TITLE
Explain BluetoothLEDevice.ConnectionStatus 

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/windows-uwp#499]
The paragraph "Connecting to the device" has the code `await BluetoothLEDevice.FromIdAsync(deviceInfo.Id)`. But after that, the `ConnectionStatus` is ` Disconnected`. Please, describe, what the `ConnectionStatus` is and when it becomes `Connected`.

See also https://github.com/MicrosoftDocs/winrt-api/issues/325

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f89409a-b108-603f-9279-c59f5ae5d188
* Version Independent ID: 5bd07919-59ac-4fca-b997-a472ae24bfb1
* Content: [Bluetooth GATT Client - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client#connecting-to-the-device)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Service: **unspecified**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been updated with qualification from the API topic.
