### ISSUE TITLE
Missing information about alternative AVs and AppLocker

### ISSUE THREAD

**Issue by fredrikeriksson** [MicrosoftDocs/windows-uwp#4997]
### Type of issue

Missing information

### Feedback

# Alternative Antivirus
At work we are currently using an AV other than Microsoft Defender.
It would be nice to have a FAQ section clarifying wether the Performance Mode is exclusive for Microsoft Defender or if it CAN at all be applied similarly with other AVs (generally).

# AppLocker
At work we are using AppLocker to prevent execution of executables.
It would be nice to get som information about how to best utilize Dev Drives with App Locker.

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/#storing-package-cache-on-dev-drive

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by mattwojo** [comment]
Performance Mode is exclusively for Microsoft Defender, but I added a section to the FAQs: "Can Dev Drive Performance Mode be applied to Antivirus programs besides Microsoft Defender?" addressing the ability to use an Allow List for security filters that can be adjusted to optimize performance and security checks to your particular scenario based on whatever AV you're using. I also added Windows Defender Application Control (WDAC) the managed installer tracking filter for using with AppLocker: `applockerfltr` to the list of common scenarios for filter settings. 
Hope that's helpful! Thanks for filing this issue @fredrikeriksson!
Updated in  https://github.com/MicrosoftDocs/windows-dev-docs/commit/ddfe90ad006d62c3a900ca85ccc7df3767b6219f
