### ISSUE TITLE
python虚拟环境，例如conda虚拟环境或者virtualenv虚拟环境，是否适合放在dev drive

### ISSUE THREAD

**Issue by Darley-Wey** [MicrosoftDocs/windows-uwp#4998]
### Type of issue

Missing information

### Feedback

python虚拟环境，例如conda虚拟环境或者virtualenv虚拟环境，是否适合放在dev drive

### Page URL

https://learn.microsoft.com/zh-cn/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by mattwojo** [comment]
Chinese to English: "Python virtual environment, such as conda virtual environment or virtualenv virtual environment, is it suitable to be placed on dev drive?"
Looking into an answer for you.

**Comment by mattwojo** [comment]
Just heard back from our Python expert.... Yes - it is suitable to place a conda virtual environment or virtualenv on Windows Dev Drive.
