### ISSUE TITLE
It is not available in some cases.

### ISSUE THREAD

**Issue by yanmuq** [MicrosoftDocs/windows-uwp#5001]
### Type of issue

Other (describe below)

### Feedback

![capture_20240518184617091](https://github.com/MicrosoftDocs/windows-dev-docs/assets/131337804/8943c88c-e667-48ce-8390-c0ffca506146)
When uploading files, the file opening window is not available, such as the window that displays attached images. I really need the quick preview feature in this type of window, and I hope it can be updated to support the use of this feature in such cases.

### Page URL

https://learn.microsoft.com/zh-cn/windows/powertoys/peek

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/peek.md

### Author

@alvinashcraft

### Document Id

1c4995a8-5af9-bcfd-86f2-912c5674b95d

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message.

1. This repository is about the documentation only, not a place to request new features. That would be https://github.com/microsoft/PowerToys
2. (having that said) this is issue https://github.com/microsoft/PowerToys/issues/29591

**Comment by alvinashcraft** [comment]
Hi @yanmuq. Like @Jay-o-Way says, this feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
