### ISSUE TITLE
Person's name bad translation in Spanish 

### ISSUE THREAD

**Issue by gerardog** [MicrosoftDocs/windows-uwp#5007]
### Type of issue

Other (describe below)

### Feedback

So, the english article is correctly displaying my name... Gerardo Grignoli.

But the spanish translation is picking up my Middle name... not sure where is it getting it from, since the markdown file on this repo is correctly spelling my first and last names...

Here is the link https://learn.microsoft.com/es-es/windows/sudo/#additional-functionality
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/3901474/16ea2781-59e2-464c-b36a-91f440666ae8)

### Page URL

https://learn.microsoft.com/es-mx/windows/sudo/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/sudo/index.md

### Author

@mattwojo

### Document Id

40f1371b-567a-8987-ec5b-448b9aa7888e

**Comment by mattwojo** [comment]
Very strange! Sorry for this issue @gerardog and thanks for bringing it to our attention. This documentation is machine translated and, to be honest, I don't totally understand how that works. I'll make our localization team aware and see if I can get a fix in ASAP. *And thanks again for the awesome tool! I personally have started using it and really appreciate it.

**Comment by mattwojo** [comment]
It looks like this fix has resolved the issue, but please reopen if you find this is not the case @gerardog . Thank you!
