### ISSUE TITLE
Document how to add an additional character set to Quick Accent

### ISSUE THREAD

**Issue by cinderbdt** [MicrosoftDocs/windows-uwp#5008]
### Type of issue

Missing information

### Feedback

There is no information on how to add an additional character set.

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/quick-accent

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/quick-accent.md

### Author

@alvinashcraft

### Document Id

affbed27-28f0-71c2-5a82-b12922b5b3c2

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. There is no way to add a character set through the utility. You can request it by filing an issue on the PowerToys repo. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
