### ISSUE TITLE
Update Proxy Support section for WNS

### ISSUE THREAD

**Issue by lettuceDestroyer** [MicrosoftDocs/windows-uwp#5012]
### Type of issue

Missing information

### Feedback

In the documentation it states, that WNS does not offer proxy support. While this might be true I think it would be worth mentioning that it does work in some cases. I was working on a project for a company which had to make Push-Notifications work while using a proxy. After a lot of trial and error and investigations we figured out that, if the proxy settings are set in the web.config, WNS does work.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/firewall-allowlist-config#proxy-support

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/shell/tiles-and-notifications/firewall-allowlist-config.md

### Author

@jwmsft

### Document Id

5cd94071-e41d-a308-d268-0a568dcd59f8

**Comment by drewbatgit** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, where your issue may have already been discussed.
