### ISSUE TITLE
OpenFilePicker example code hangs, never produces picker

### ISSUE THREAD

**Issue by EvanHutnick** [MicrosoftDocs/windows-uwp#502]
When attempting to run the code from 'Pick a single file: complete code listing' via Visual Studio, the application simply hangs and never generates a file picker.  

Tested on Debug/Release, x86/x64, Admin/non admin opening of Visual Studio.  Also gave file picker 'any file type' permission just in case.  Currently on SDK 16299, OS Version 1709 build 17025.1000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea959124-e65c-c9a7-f8df-b1d53c3cd76f
* Version Independent ID: 1b13337f-ac6e-490f-04c9-c7342be5f161
* Content: [Open files and folders with a picker - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers)
* Content Source: [windows-apps-src/files/quickstart-using-file-and-folder-pickers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-using-file-and-folder-pickers.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
I tested this code, and it worked for me. I'm on an Insider Preview build (17655). No special permissions or admin privileges. The code is the same as what's on the page, except I added "Debug.WriteLine" instead of a text box and wrapped it into a method.

```csharp
public async void TestPicker() 
{
    var folderPicker = new Windows.Storage.Pickers.FolderPicker();
    folderPicker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.Desktop;
    folderPicker.FileTypeFilter.Add("*");

    Windows.Storage.StorageFolder folder = await folderPicker.PickSingleFolderAsync();
    if (folder != null)
    {
        // Application now has read/write access to all contents in the picked folder
        // (including other sub-folder contents)
        Windows.Storage.AccessCache.StorageApplicationPermissions.
        FutureAccessList.AddOrReplace("PickedFolderToken", folder);
        Debug.WriteLine(folder.Name);
    }
    else
    {
        Debug.WriteLine("Operation canceled.");
    }
}
```

If you're still having issues with the file picker, I'll file a bug with the product team to investigate. Thanks for bringing this up!

**Comment by swatvel** [comment]
Hi,
Application crashes while using the filepicker in windows immersive devices .

   var picker = new Windows.Storage.Pickers.FileOpenPicker();
        picker.ViewMode = Windows.Storage.Pickers.PickerViewMode.Thumbnail;
        picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.PicturesLibrary;
        picker.FileTypeFilter.Add(".jpg");
        picker.FileTypeFilter.Add(".jpeg");
        picker.FileTypeFilter.Add(".png");
        Debug.Log("File picker initialised");
        Windows.Storage.StorageFile file = await picker.PickSingleFileAsync();
        Debug.Log("picker waiting");
        if (file != null)
        {
            // Application now has read/write access to the picked file
            Debug.Log("Picked photo: " + file.Name);
        }
        else
        {
            Debug.Log("Operation cancelled.");
        }
I am having this code run on  an windows immersive device and the app crashes with this stackttrace : 

Cannot find or open the PDB file.
Exception: Invalid window handle. (Exception from HRESULT: 0x80070578)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Is this specific for windows immersive ? Please help
