### ISSUE TITLE
Code sample missing a namespace directive for CommunityToolkit.Maui.Markup.GridRowsColumns

### ISSUE THREAD

**Issue by ContrastingSounds** [MicrosoftDocs/windows-uwp#5026]
### Type of issue

Code doesn't work

### Feedback

Code doesn't work unless you add the following namespace directive:

`using static CommunityToolkit.Maui.Markup.GridRowsColumns;`

It fails with CS0103 errors for 'Rows', 'Columns', 'Star', 'Stars'

### Page URL

https://learn.microsoft.com/en-us/windows/apps/windows-dotnet-maui/tutorial-csharp-ui-maui-toolkit

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-dotnet-maui/tutorial-csharp-ui-maui-toolkit.md

### Author

@alvinashcraft

### Document Id

ebd638a3-0daf-2b8c-24a2-57b5dcca1fa6

**Comment by alvinashcraft** [comment]
Thanks for calling this out, @ContrastingSounds. I've updated the topic to include the directive. The PR was just merged and should be live shortly. Cheers!
