### ISSUE TITLE
Request targets an app that is not in allowed receiving apps list by WNS.

### ISSUE THREAD

**Issue by michalleptuch** [MicrosoftDocs/windows-uwp#5027]
### Type of issue

Code doesn't work

### Feedback

It's unbelievably tough situation when you change anything without informing developers/clients of your services.
I requested for WNS access for my Windows App SDK app in September 2023, and everything worked fine until the moment I received these logs:

```
2024-05-29 19:16:06.244 +02:00 [WRN] X-WNS-Debug-Trace: BY3PEPF000195A1
2024-05-29 19:16:06.245 +02:00 [WRN] X-WNS-Error-Description: Request targets an app that is not in allowed receiving apps list by WNS.
2024-05-29 19:16:06.245 +02:00 [WRN] X-WNS-Msg-ID: 3CEB16B369BFE024
2024-05-29 19:16:06.245 +02:00 [WRN] WWW-Authenticate: 
```

I couldn't find any helpful information. I figured out you have changed the way of requesting of mapping and (probably) removed existing mappings. My app has not been working for almost two weeks! My clients want me to refund the costs.

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/43097852/8e5d4329-ad34-4428-a712-9ece885b4775)

### Page URL

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push-notifications/push-quickstart

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/notifications/push-notifications/push-quickstart.md

### Author

@Karl-Bridge-Microsoft

### Document Id

41f4799e-83ba-f0a8-43ae-770f8f0edb3e

**Comment by drewbatgit** [comment]
This issue is being tracked internally by the product team so I'm going to close this issue because it doesn't seem like there is a documentation fix for this issue at this time. Feel free to continue to comment on this issue if you feel like there are improvements that we can make to the docs to help with this issue.
