### ISSUE TITLE
Dev Drive Python PIP doesn't work with MSStore python

### ISSUE THREAD

**Issue by ivberg** [MicrosoftDocs/windows-uwp#5028]
### Type of issue

Missing information

### Feedback

Install / use Python from MSStore. Use the config in the doc and it won't work.

E.g.
Pip cache (Python): Create a pip cache directory in your Dev Drive, e.g. D:\packages\pip, then set a global environment variable PIP_CACHE_DIR to that path, e.g. setx /M PIP_CACHE_DIR D:\packages\pip. If you have already restored pip packages and Wheels on your machine, move the contents of %LocalAppData%\pip\Cache to this directory. Learn more in the pip docs: [pip caching](https://pip.pypa.io/en/stable/topics/caching/) and see StackOverflow to [Change directory of pip cache on Linux?](https://stackoverflow.com/questions/64180511/pip-change-directory-of-pip-cache-on-linux).

Instead it seems another env variable might be needed (confirmed it works)
set PYTHONUSERBASE=S:\packages\python

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by zooba** [comment]
The suggestion is just to move the _cache_, not the final install location. We'd suggest creating a virtual environment (see Python's documentation for `venv`) to move the final install location onto your Dev Drive.
