### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by mhamad-99** [MicrosoftDocs/windows-uwp#5034]
### Type of issue

Other (describe below)

### Feedback

hi

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/search

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/search.md

### Author

@mattwojo

### Document Id

77750236-9104-a3aa-89ad-92bbd7e72ed3

**Comment by Karl-Bridge-Microsoft** [comment]
no issue reported
