### ISSUE TITLE
How to remove Project Ironsides?

### ISSUE THREAD

**Issue by DrEsteban** [MicrosoftDocs/windows-uwp#5036]
### Type of issue

Missing information

### Feedback

The doc talks about installing it, but what about removing it?

### Page URL

https://learn.microsoft.com/en-us/windows/dev-home/project-ironsides

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/project-ironsides.md

### Author

@mattwojo

### Document Id

90478dcf-a4bf-eb87-f3f4-7aa6eb3f1242

**Comment by mattwojo** [comment]
There's no way to remove Project Ironsides from Dev Home, as it's a feature that's in development. You can turn it off in Settings > Experimental features. Or you can open Windows Task Manager and terminate the process. Or you can uninstall Dev Home by using the command line -- open PowerShell in Windows Terminal and enter: `Get-AppxPackage -AllUsers -PackageTypeFilter Bundle -Name "*Windows.DevHome*" | Remove-AppxPackage -AllUsers` to remove Dev Home for all users. 

But also, know that Dev Home is being actively developed right now, so there is a dev team working on making it better and PMs that are listening to and reading customer feedback in an effort to make Dev Home into a place that improves workflows... so if you have things that you don't like about it, encourage you to let the development team know what you would ideally like to see... they are collecting and prioritizing issues here: https://github.com/microsoft/devhome/issues
