### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by chcurlet-msft** [MicrosoftDocs/windows-uwp#504]
Should this document still mention the Fall Creators Update? 

Also, for low priority notifications, this document states that "These are cached and not processed until the user gets back to their device." However, a user can have his/her device plugged in, but leave it and have it enter Modern Standby while he/she is gone. Because the device is plugged in, according to the table "Detailed listing of desktop behavior," the notification is still delivered (rather than cached). These seem inconsistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb75ae80-e8a4-1f66-0d77-32109eb85eab
* Version Independent ID: c9155d9b-a1fe-5083-d1b1-a9ebe284049c
* Content: [WNS Notification Priorities - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/wns-notification-priorities)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/WNS-Notification-Priorities.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/WNS-Notification-Priorities.md)
* Service: **unspecified**
* GitHub Login: @adwilso
* Microsoft Alias: **sezhen**

**Comment by adwilso** [comment]
You can drop fall creators update, but it should still mention that not setting the priorities won't block the notification from being sent. Instead the default priority will be applied to the notification

My thinking with saying "These are cached and not processed until the user gets back to their device." is that the user had to return to their device to plug it in. So at the very least they moved it around a bit. 

However I agree the wording is not very clear - something like "These are cached and not processed until the user signs on or plugs their device in" might be better

**Comment by serenaz** [comment]
Thanks for raising the issue! The doc has been updated accordingly :)
