### ISSUE TITLE
[Search Providers] Gleam/Dynamic Content does not appear to function.

### ISSUE THREAD

**Issue by bignutty** [MicrosoftDocs/windows-uwp#5041]
### Type of issue

Other (describe below)

### Feedback

I'm currently working on a custom search provider for windows, but struggle with implementing the gleam endpoint.
I added a DynamicContentEndpoint to my package manifest, but it seems like Windows is never requesting my endpoint. Neither an OPTIONS or a GET request for the gleam endpoint is ever sent to my server, nor does Windows display a gleam.

I'm unsure if this is an issue with incorrect documentation or if third party gleams as a whole are broken/unsupported now (despite the documentation stating they should be available). Is the article outdated or was this functionality simply never launched?

I'm currently running Windows 11 23H2 (22631.3810)

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/search/search-providers

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/search/search-providers.md

### Author

@drewbatgit

### Document Id

c6d5b252-f5c3-2500-1f7c-c3f201c8eff3

**Comment by drewbatgit** [comment]
This issue has been passed along to the feature team, and the documentation will be updated as needed to make sure that the recommendations around the feature are accurate. I'm going to go ahead and close this issue. For further developer support, we recommend posting a question to [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/).
