### ISSUE TITLE
WSA Camera crash when setting 90º rotation inside W11 (black screen and crash)

### ISSUE THREAD

**Issue by wsafan** [MicrosoftDocs/windows-uwp#5043]
### Type of issue

Other (describe below)

### Feedback

I need WSA to be able to take pictures in Portrait (vertical) as if it was a normal phone device. 

The issue is that WSA will only open its camera and take pictures in Landscape (horizontal). 

I found out a solution that may be the trick by rotating Windows 11 Camera privacy settings . 

This works perfectly with Windows 11 internal camera as it respects the ratio and the displayed image takes place in portrait. 

However  as soon as you open WSA and open any android camera it crashes.

A few other things I tried was to use adb commands with developper options inside WSA, but it wont affect the camera orientation

adb shell settings put system accelerometer_rotation 0

adb shell settings put system user_rotation 1 (flip landscape)

adb shell settings put system user_rotation 1 (flip back to portrait)

**Comment by danieltharris** [comment]
Is WSA still being worked on? As far as I was aware it's deprecated and will be EOL in March 2025?

NB: I wish it wasn't personally as it was great for debugging Android MAUI apps from VS 2022 - I'm not even sure whether the typical Android emulators work on a WoA dev machine as there are warnings about hardware acceleration

**Comment by mattwojo** [comment]
Yes - unfortunately WSA is deprecated. The end of support message is in the "Important" note at the top of this doc: https://learn.microsoft.com/windows/android/wsa/
I don't know the full backstory about why, but have heard that it got complicated. There's instructions for debugging Android MAUI apps here: https://learn.microsoft.com/dotnet/maui/android/device/setup?view=net-maui-8.0  I believe that WoA devices will support emulators, but am interested to hear if you're finding that isn't the case.
