### ISSUE TITLE
Registry preview Chinese translation error

### ISSUE THREAD

**Issue by xiaoxiyao** [MicrosoftDocs/windows-uwp#5044]
### Type of issue

Typo

### Feedback

“Registry preview” should be "注册表预览" instead of "注册表预览版"

### Page URL

https://learn.microsoft.com/zh-cn/windows/powertoys/registry-preview

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/registry-preview.md

### Author

@alvinashcraft

### Document Id

f4916d5a-cb72-75b4-9909-aaccbbfb9832

**Comment by GrantMeStrength** [comment]
Thank you for the feedback. The localization bug has been filed (982700).
