### ISSUE TITLE
Remap a shortcut - with Text

### ISSUE THREAD

**Issue by LannyDana** [MicrosoftDocs/windows-uwp#5050]
### Type of issue

Other (describe below)

### Feedback

In "Remap a shortcut" "Action:" setting "Send Text"... is there a way to have more than one line of text?

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md

### Author

@alvinashcraft

### Document Id

890589e7-751b-9a0e-bda9-c7b1aa3f5102

**Comment by alvinashcraft** [comment]
I don't believe there is a way to do this. If you have a specific use case in mind, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback. Thanks!
