### ISSUE TITLE
根本就与实际不符

### ISSUE THREAD

**Issue by onedotone-wei** [MicrosoftDocs/windows-uwp#5054]
### Type of issue

Other (describe below)

### Feedback

根本就与实际不符 [Machine translation: "Totally inconsistent with reality"]

### Page URL

https://learn.microsoft.com/zh-cn/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=cs-vs-community%2Ccpp-vs-community%2Cvs-2022-17-1-a%2Cvs-2022-17-1-b

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/set-up-your-development-environment.md

### Author

@stevewhims

### Document Id

1a4d4425-689e-4d3a-1248-a1dd5789d285

**Comment by stevewhims** [comment]
Thanks, @onedotone-wei! I'll close this issue, since there's not enough detail to take action.

-Steve
