### ISSUE TITLE
i cant activate my windows after last dev update

### ISSUE THREAD

**Issue by RefritoPR** [MicrosoftDocs/windows-uwp#5056]
### Type of issue

Other (describe below)

### Feedback

i was part of the insider program and the developer program i udpated windows last update and now it says i need to activate it. but it wont every help or option says error

### Page URL

https://learn.microsoft.com/en-us/windows/dev-home/?source=recommendations

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/index.md

### Author

@mattwojo

### Document Id

acdf7266-5a5a-10a9-25bc-94f01b3e5d0a

**Comment by mattwojo** [comment]
Oh bummer! Sorry that you're having trouble with it. Are you wanting to stay on an Insiders build or switch to the stable release?

You can install the stable release via Microsoft Store at: https://aka.ms/devhome or you can install via terminal and using Windows Package Manager (winget), the command is: `winget install Microsoft.DevHome` 

I believe that new features for Dev Home are now pushed out via the Experimental features in Settings in the stable Dev Home app, so you don't really get anything extra by being on Windows Insiders for Dev Home.

If that doesn't resolve your issue, please reopen this and let me know what sort of error you're seeing.
