### ISSUE TITLE
Sandeep kumar

### ISSUE THREAD

**Issue by Sandeepkumar070** [MicrosoftDocs/windows-uwp#5066]
### Type of issue

Other (describe below)

### Feedback

Good

### Page URL

https://learn.microsoft.com/en-us/windows/dev-environment/javascript/vue-on-windows

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/vue-on-windows.md

### Author

@mattwojo

### Document Id

dd7e91a2-1bed-337f-a2be-ebf8cb0b071d

**Comment by mattwojo** [comment]
There is no actual issue identified here. Please reopen if you intended to identify an issue and explain the problem that you've found.
