### ISSUE TITLE
The reference link is break

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/windows-uwp#5069]
### Type of issue

Missing information

### Feedback

Reference blogs is 403.

The link is https://blogs.msdn.com/b/shawnhar/archive/2009/11/06/premultiplied-alpha.aspx and https://blogs.msdn.com/b/shawnhar/archive/2009/11/07/premultiplied-alpha-and-image-composition.aspx

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/win2d/premultiplied-alpha

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/win2d/premultiplied-alpha.md

### Author

@stevewhims

### Document Id

6457a4ee-94a6-cef0-3bdf-cc3e07519393

**Comment by stevewhims** [comment]
Thanks, I've fixed those links. 

-Steve
