### ISSUE TITLE
Hot Reload for WInUI 3?

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/windows-uwp#5071]
### Type of issue

Other (describe below)

### Feedback

In the table: at the cross of "WinUI 3" × "UI debugging" we have a link to [Hot Reload](https://learn.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2022). That page, however, tells about WPF and UWP, explicitly not WinUI 3. As we all know, hot reload for WinUI 3 is a hot topic. Does this table need a change? And what about the page on the WPF/UWP tool? 

### Page URL

https://learn.microsoft.com/en-au/windows/apps/get-started/?tabs=cpp-win32%2Cnet-maui

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/index.md

### Author

@QuinnRadich

### Document Id

d2b12b06-f936-204b-1be7-9ca844ceff43

**Comment by Jay-o-Way** [comment]
Hello?

**Comment by jwmsft** [comment]
Hi. The [XAML Hot Reload](https://learn.microsoft.com/visualstudio/xaml-tools/xaml-hot-reload) page was updated in August to specifically mention WinUI 3. Based on this, I don't believe any updates are needed to the table on the get-started page.
