### ISSUE TITLE
Problems with moving %TMP% and %TEMP% to dev drive

### ISSUE THREAD

**Issue by stamminator** [MicrosoftDocs/windows-uwp#5072]
### Type of issue

Other (describe below)

### Feedback

In the description of @shanselman's [video demo of Dev Drives](https://www.youtube.com/watch?v=UW8yKWX8YAA), he warns:

> UPDATE: **DO NOT** move %TEMP% to a DevDrive. It'll work until the next build of Windows and then Windows won't be able to access it on the reboot and it'll rollback. Keep your %TEMP% and %TMP% on NTFS for now.

This is in contrast to the recommendation on this doc page:

> We also recommend that you consider redirecting %TEMP% and %TMP% envvars to Dev Drive.

If there's some instability with moving these envvars, it might be worth amending the docs.

### Page URL

https://learn.microsoft.com/en-us/windows/dev-drive/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md

### Author

@mattwojo

### Document Id

bfda7965-bc34-ab88-fdc9-efef4a5d8a9e

**Comment by mattwojo** [comment]
Thanks for identifying this issue @stamminator! I checked in with the Dev Drive team and they said that it is still recommended to  redirect `%TEMP%` and `%TMP%` environment variables to Dev Drive, but that when Scott originally recorded that video there was less understanding about the dependency on adding the WinSetupMon filter. You will need that for the Windows Update process.

**Comment by mattwojo** [comment]
Bridget also added a note about this in the comments of Scott's video for others awareness. You can find how to add the WindowsSetupMon filter here: https://learn.microsoft.com/en-us/windows/dev-drive/#filters-for-common-scenarios

**Comment by stamminator** [comment]
Thanks @mattwojo! One last question. The docs don't make it clear if just the user-level TMP and TEMP envvars should be pointed to dev drive, or if the system-level TMP and TEMP should also be pointed there. If so, should they be pointed to separate directories on the dev drive, or the same? A bit more clarification here and in the docs would be helpful.
