### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#5078]
### Type of issue

Missing information

### Feedback

![image](https://github.com/user-attachments/assets/b41a97e8-45a2-4d7f-8893-1fb283de6ce9)
![image](https://github.com/user-attachments/assets/33f1103a-c3ee-439a-988e-9a8879ea34ba)

These are just 2 icons that are missing from the public list.
The 2 arrows should be E174 but I don't know the brush one.

Could you look deeper in the icon font and gives us all available icons instead of most of them?

### Page URL

https://learn.microsoft.com/nl-nl/windows/apps/design/style/segoe-fluent-icons-font

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/style/segoe-fluent-icons-font.md

### Author

@jwmsft

### Document Id

3b140070-493f-0b2c-f7c4-3fb89192d2d0

**Comment by PesBandi** [comment]
Hello @Natriss, E0- to E5- icons are deprecated and therefore not in the list. The new E174 (Sort, two arrows) is E8CB. Hope that helps. I still haven't found the brush :(

**Comment by ghost** [comment]
> The new E174 (Sort, two arrows) is E8CB.

That indeed helped. Thank you.
I also didn't know E0 to E5 are all deprecated.

I hope that brush icon is somewhere in the font. I just find it weird it's not included in the list but different Microsoft apps use it.

**Comment by ghost** [comment]
![9371791](https://github.com/user-attachments/assets/772474e4-71e0-4512-81d8-a454a2814179)
This one and also the Microsoft Store Gaming and Arcade icons.

Can't find these three as well.

**Comment by PesBandi** [comment]
@Natriss, do you know any open-source apps that use these icons? That could help me find them.

**Comment by ghost** [comment]
@PesBandi The code one is used in Microsoft Calculator.
I couldn't find it myself yet.
Sadly the other 2 from the Microsoft Store. I have only seen them there yet. I'm not sure if they are also used in the Xbox app.

**Comment by PesBandi** [comment]
Hi, @Natriss, I think I solved it. The icons you are looking for are not a part of Segoe Fluent Icons, but Fluent System Icons. You can find it at [microsoft/fluentui-system-icons](https://github.com/microsoft/fluentui-system-icons). The fonts are in the fonts folder. The brush is F591 and the code thing is F2EF and F2F0.

**Comment by ghost** [comment]
Oh
Weird that Windows doesn't have the Fluent System icons. 

Thank you for your detective work @PesBandi
