### ISSUE TITLE
Unclear wording in 'Learn / Windows / App development / Title bar / Bar / Behaviour'

### ISSUE THREAD

**Issue by jtaylor100** [MicrosoftDocs/windows-uwp#5082]
### Type of issue

Typo

### Feedback

Currently a bullet in this section reads:

> A single-click/tap on any part of the title bar that does not have an interactive element should show the system window menu.

I interpreted this as 'A single left, right or any other type of click/tap' and proceeded to implement this behaviour in my WinUI 3 app, since it wasn't provided by default.

Trying to do this was quite hard with little resources on how to open the system context menu from a dotnet app (Win32 interop was one route). After a while, I noticed that the behaviour is there by default but only for 'right click' on my system (Windows 11 Laptop with mouse).

So my questions are:

- Is the article supposed to say 'right click' plus similar wording to account for tablet input?
- If not, then what is the definition of 'single tap' exactly and perhaps it could be linked to here?

Happy to take on any editing of the docs, with some pointers on the change process.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/design/basics/titlebar-design

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/basics/titlebar-design.md

### Author

@jwmsft

### Document Id

9e651f67-dc74-3946-24fa-d1b6411d0ebf

**Comment by jwmsft** [comment]
@jtaylor100, thanks for opening this issue. The doc should say "right-click/press-and-hold". I've updated it with this correction.
