### ISSUE TITLE
winget命令

### ISSUE THREAD

**Issue by ahua18xt** [MicrosoftDocs/windows-uwp#5083]
### Type of issue

Other (describe below)

### Feedback

C:\Users\8888>winget upgrade
搜索源时失败;结果将不包括在内： msstore
名称                            ID                             版本           可用                 源
---------------------------------------------------------------------------------------------------------
Cloud                           Huawei.HuaweiMobileCloud       11.2.1.304     15.1.0.302           winget
WinRAR 6.21 (64-位)             RARLab.WinRAR                  6.21.0         7.01.0               winget
XSplit Broadcaster              XSplit.Broadcaster             4.4.2304.1201  4.5.2406.1808        winget
小黑盒加速器 1.1.48             Qingfeng.HeyboxAccelerator     1.1.48         1.1.52               winget
HiSuite                         Huawei.HiSuite                 13.0.0.310     14.0.0.320           winget
酷我音乐                        Kuwo.KuwoMusic                 9.2.0.0        9.3.6.0              winget
Microsoft Edge WebView2 Runtime Microsoft.EdgeWebView2Runtime  126.0.2592.113 127.0.2651.74        winget
PyCharm 2024.1                  JetBrains.PyCharm.Professional 2024.1         2024.1.4             winget
QQ音乐                          Tencent.QQMusic                20.5           20.22                winget
搜狗五笔输入法 5.5正式版        Sogou.SogouWBInput             5.5.0.2580     5.5.0.2584           winget
阿里旺旺                        Alibaba.AliIM                  10.01.03C      10.01.07C            winget
Python 3.12.2 (64-bit)          Python.Python.3.12             3.12.2         3.12.4               winget
Microsoft Teams                 Microsoft.Teams                1.0.0.0        24165.1414.2987.41   winget
Microsoft Teams                 Microsoft.Teams.Free           1.0.0.0        24165.1306.2986.9504 winget
14 升级可用。

C:\Users\8888>winget upgrade --all
搜索源时失败: msstore
执行此命令时发生意外错误：
0x8a150044 : 找不到 Rest API 终结点。
                                                                  请指点一下这个问题需要怎么解决！！！

### Page URL

https://learn.microsoft.com/zh-cn/windows/package-manager/winget/upgrade

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/upgrade.md

### Author

@mattwojo

### Document Id

ed2c403c-7bba-9647-fb5c-da556cb93a6b

**Comment by mattwojo** [comment]
Looks like a similar issue to https://github.com/MicrosoftDocs/windows-dev-docs/issues/5092

**Comment by zaochih** [comment]
It's simply a network issue and should fix "automatically". Commonly there's nothing you need to do, just try again minutes later :)

这是一个简单的网络问题，并且应当能够 "自动" 修复。通常情况下，您无需采取任何行动，在数分钟后重试即可 :)

**Comment by mattwojo** [comment]
Closing as this does not appear to require an update to documentation.
关闭，因为这似乎不需要更新文档。
