### ISSUE TITLE
Windows Subsystem for Android Release Notes

### ISSUE THREAD

**Issue by thals1992** [MicrosoftDocs/windows-uwp#5087]
### Type of issue

Missing information

### Feedback

Appears to be missing release notes from quite a few builds including the latest build 2407 for insiders. 

### Page URL

https://learn.microsoft.com/en-us/windows/android/wsa/release-notes

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/release-notes.md

### Author

@mattwojo

### Document Id

865063ea-60f4-de74-20e8-77abe9ce0fc6

**Comment by mattwojo** [comment]
Hey @thals1992 - Support has ended for the Windows Subsystem for Android program and I haven't received any release note updates, but it looks like you can find the 2311 and 2407 release notes in the [WSA GitHub repository Discussions](https://github.com/microsoft/WSA/discussions). I'm adding a link to this in the documentation for others who may be looking -- thanks for pointing out the gap!
