### ISSUE TITLE
Where is DockPanel? 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/windows-uwp#509]
And what is Relative Panel?

When coming to this page or any of the pages in the left nav from a search result or other link, there are very few clues that this is UWP specific and not the WPF flavor of XAML.  Something should be visible at all times to indicate which XAML these docs are for, like making the breadcrumbs sticky, or the left nav having a sticky title for the doc group. 

![image](https://user-images.githubusercontent.com/15381181/39471994-60e0ba86-4d14-11e8-8635-2ed1388aff42.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cecd85-5983-c683-d8ea-6c010b7b2b58
* Version Independent ID: 8a77e197-6c7c-3fcb-7ecf-e52f4a270d2d
* Content: [Responsive layouts with XAML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layouts-with-xaml#feedback)
* Content Source: [windows-apps-src/design/layout/layouts-with-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/layouts-with-xaml.md)
* Service: **unspecified**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by michael-hawker** [comment]
@StingyJack [DockPanel](https://docs.microsoft.com/en-us/windows/uwpcommunitytoolkit/controls/DockPanel) is included in the [UWP Community Toolkit](https://github.com/Microsoft/UWPCommunityToolkit).

**Comment by StingyJack** [comment]
@michael-hawker - its not about the dock panel, specifically. I was trying to find some info for a colleague about the choices available for layout containers and stumbled into this bit of confusion. The doc page doesnt really make it clear this is for a different and less common version of XAML.

**Comment by GrantMeStrength** [comment]
Jim - please decide if a comment or addition is required in the documentation.

**Comment by jwmsft** [comment]
This feedback was given to the Docs engineering team.
