### ISSUE TITLE
Run winget on remote computer

### ISSUE THREAD

**Issue by esierra08** [MicrosoftDocs/windows-uwp#5090]
### Type of issue

Typo

### Feedback

Greetings, I am trying to run Winget on a remote computer from CMD with PSexec to update applications, the remote connection is successful but the winget does not work.

![image](https://github.com/user-attachments/assets/50e2ae81-bfb0-4f1d-b890-d08eafa73dca)

### Page URL

https://learn.microsoft.com/es-es/windows/package-manager/winget/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md

### Author

@mattwojo

### Document Id

b49c32ea-2efa-b090-7123-87c31d10279b

**Comment by mattwojo** [comment]
@esierra08 - I'm sorry you are having trouble with this. I believe this issue would be a better fit to post in the WinGet-CLI product repo (this repo is specific to documentation). I just took a look and searched for "remote + PSexec" and found these related issues: https://github.com/microsoft/winget-cli/issues?q=is%3Aissue+remote+PSexec  If your issue isn't addressed by those, please open a new issue for the Windows Package Manager dev team to help with. 
If this does come back to needing documentation guidance, that team will follow up with me.
