### ISSUE TITLE
键盘管理器里面的重新映射按键不起作用

### ISSUE THREAD

**Issue by tangfantexi** [MicrosoftDocs/windows-uwp#5091]
### Type of issue

Code doesn't work

### Feedback

你好，我在使用工具中-【键盘管理器】-【重新映射快捷键】，设置了将【Alt + F4关闭当前窗口或应用】替换为【Ctrl+Q的按键】，设置后保存，且保持软件一直开启的状态，但按【Ctrl+Q】不行，不知道是不是没有激活，但又如何激活呢，写的说明看不懂。
![1](https://github.com/user-attachments/assets/42727ec3-f5dd-47a7-b50e-fa1c2080c28c)
![2](https://github.com/user-attachments/assets/1e5948b3-3c6d-48a4-8839-821c65df9ed5)

### Page URL

https://learn.microsoft.com/zh-cn/windows/powertoys/keyboard-manager

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/keyboard-manager.md

### Author

@alvinashcraft

### Document Id

890589e7-751b-9a0e-bda9-c7b1aa3f5102

**Comment by mattwojo** [comment]
Chinese > English: "Remapping keys in keyboard manager doesn't work"

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.

**Comment by sunjinmao** [comment]
这个软件很多bug都修补不了

**Comment by yiming2016** [comment]
用管理员身份运行才可以，在常规里面设置。这软件真是的，不能运行不告诉我必须用管理员身份。我在这被卡了三小时到处找答案
