### ISSUE TITLE
Two unclear issues on this subpage

### ISSUE THREAD

**Issue by MsdnUsrSince1994** [MicrosoftDocs/windows-uwp#5096]
### Type of issue

Missing information

### Feedback

**First issue:** The paragraph titled "**Architectures redistributed by the Windows App SDK installer**", last sentence, is vague if the x86 redistributable exe will install the x64 components on an x64 machine and the arm64 components on an arm64 machine.  The word "that" is a dangling pointer which may point either to "x86" or to "x64 or arm64" .

**Second issue:** The entire page is unclear if this applies only to WinRT-style .NET Apps or also to ordinary Win32 apps installed and run in Win32 ways.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/deploy-unpackaged-apps.md

### Author

@stevewhims

### Document Id

afbfb452-8b8e-6cec-80ca-c0905b29ca6b

**Comment by stevewhims** [comment]
Thanks, I've updated that topic now (right at the start of the topic, and in the paragraph that you identify). I think it's clearer in those two respects.

Thanks!
-Steve
