### ISSUE TITLE
我想开发一个自己的Run插件应该怎么做呢

### ISSUE THREAD

**Issue by ljzloser** [MicrosoftDocs/windows-uwp#5097]
### Type of issue

Typo

### Feedback

我想开发一个自己的Run插件应该怎么做呢

### Page URL

https://learn.microsoft.com/zh-cn/windows/powertoys/run

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/run.md

### Author

@alvinashcraft

### Document Id

18e0202f-3e91-a5b9-62f2-6cd40e5661a8

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
