### ISSUE TITLE
Not enough info [TEST[

### ISSUE THREAD

**Issue by eelnivla** [MicrosoftDocs/windows-uwp#5099]
### Type of issue

Missing information

### Feedback

This page needs more info.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/windows-integration/integrate-sharesheet-overview

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/windows-integration/integrate-sharesheet-overview.md

### Author

@stevewhims

### Document Id

f3ddfb51-bbed-2bed-96fe-e1e10a2e1190

**Comment by alvinashcraft** [comment]
What do you mean? What do you feel is missing?
