### ISSUE TITLE
ujujujuzkkzukuzk

### ISSUE THREAD

**Issue by digital-pccc** [MicrosoftDocs/windows-uwp#5104]
### Type of issue

Missing information

### Feedback

uzkzukuzuuzkzukuzkz

### Page URL

https://learn.microsoft.com/de-de/windows/apps/get-started/enable-your-device-for-development

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/enable-your-device-for-development.md

### Author

@QuinnRadich

### Document Id

0a65ac0a-9884-52a8-6485-c2825b1fb4d9

**Comment by Karl-Bridge-Microsoft** [comment]
not actionable
