### ISSUE TITLE
Error in the RemoveWindowsHelloAccountAsync method

### ISSUE THREAD

**Issue by r7dev** [MicrosoftDocs/windows-uwp#5116]
### Type of issue

Code doesn't work

### Feedback

In the Button_Forget_User_Click event, the RemoveWindowsHelloAccountAsync method is asynchronously called. But it is declared a void when it should be a task.

Incorrect: `public static async void RemoveWindowsHelloAccountAsync(UserAccount account)`
Correct: `public static async task RemoveWindowsHelloAccountAsync(UserAccount account)`

### Page URL

https://learn.microsoft.com/pt-br/windows/apps/develop/security/windows-hello-auth-service?source=docs

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/security/windows-hello-auth-service.md

### Author

@alvinashcraft

### Document Id

2c08b5cc-649a-0e8c-997c-32327be1d677

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I went ahead and created a PR to incorporate your suggestions. The change should be live later today, so I will go ahead and close this. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
