### ISSUE TITLE
Global stats

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#512]
Does XBL provide any way to aggregate stats across the entire population and access those global aggregates programmatically? I only see per-user APIs in StatsManager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c72f506-f95a-3fe5-6eac-5a6dcd7eff80
* Version Independent ID: 8395f2f8-7ad8-ea94-84d0-7405399358b3
* Content: [Player Stats - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/leaderboards-and-stats-2017/player-stats)
* Content Source: [windows-apps-src/xbox-live/leaderboards-and-stats-2017/player-stats.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/leaderboards-and-stats-2017/player-stats.md)
* Service: **unspecified**
* GitHub Login: @staceyhaffner
* Microsoft Alias: **kevinasg**

**Comment by KevinAsgari** [comment]
Xbox Live does not provide a way to aggregate stats across multiple users. You would need to maintain the stats in your own cloud service and perform your own aggregation across users.
