### ISSUE TITLE
Windows App SDK Missing Documentation

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#5123]
### Type of issue

Missing information

### Feedback

As a developer, I'm getting the message that I should be moving from UWP to Windows App SDK.  However, there is still far more documentation  for UWP than WinAppSDK.  Compare https://learn.microsoft.com/en-us/windows/uwp/ with https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/  My specific need is to get the C++/WinRT documentation ported over.  If Microsoft wants developers to use a technology, they need to commit the resources necessary to enable developers to do so.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/index.md

### Author

@Karl-Bridge-Microsoft

### Document Id

96289e4e-417b-28b9-8f1c-d561e3afab22

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @dr-eck - we're in the midst of a big doc transition now that involves a number of writers working on migrating relevant docs to WinApp SDK where it makes sense. Thanks for the feedback!
