### ISSUE TITLE
Icona Awake assente nella barra delle applicazioni

### ISSUE THREAD

**Issue by Leo-Artista** [MicrosoftDocs/windows-uwp#5126]
### Type of issue

Other (describe below)

### Feedback

Non appare più l'icona della tazzina "Awake" nella barra delle applicazioni!
![Screenshot 2024-09-05 212513](https://github.com/user-attachments/assets/1c552267-3c67-4f77-8ce2-e178592bfe62)
![Screenshot 2024-09-05 212513](https://github.com/user-attachments/assets/524605a7-8efa-4046-aed4-6054e99dc727)

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/awake

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/awake.md

### Author

@alvinashcraft

### Document Id

29236a0e-82e8-92d7-a5fb-12a9a777bcc2

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
