### ISSUE TITLE
Documentation on Store app images uses wrong label for poster image aspect ratio

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#5127]
### Type of issue

Typo

### Feedback

Poster images are 720w x 1080h or 1440h x 2160h. That is an aspect ratio of 2:3 and is labelled as such in the section "2:3 poster art".

However, the screenshot at the start of the article shows "9:16" for the same image, and the text at the end of the article says "For the best display on Xbox, you must also provide a 9:16 (720 x 1080 or 1440 x 2160 pixels) image". The label of "9:16" is incorrect here -- an image with those dimensions is 2:3.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/msix/screenshots-and-images?pivots=store-installer-msix

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/msix/screenshots-and-images.md

### Author

@GrantMeStrength

### Document Id

bc21d889-f1c6-1753-0abf-2dd916d40bea

**Comment by GrantMeStrength** [comment]
Thank you! Updated the topic and image.
