### ISSUE TITLE
看网络视频卡

### ISSUE THREAD

**Issue by W13455527086ISAVAILABLE** [MicrosoftDocs/windows-uwp#5128]
### Type of issue

Typo

### Feedback

帮助解决

### Page URL

https://learn.microsoft.com/zh-cn/windows/dev-home/setup

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/setup.md

### Author

@mattwojo

### Document Id

e94338ac-d3a8-011e-4cf9-fc4a9f60de35

**Comment by alvinashcraft** [comment]
Assigned @mattwojo, but I don't know whether this is a docs issue or a product/support issue.

**Comment by mattwojo** [comment]
Needs more information to define what issue you have found in this documentation. Closing. Please feel welcome to reopen and include a description of the issue.

需要更多信息来定义您在本文档中发现的问题。关闭。欢迎重新打开并附上问题描述。
