### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Jaime1980** [MicrosoftDocs/windows-uwp#5145]
### Type of issue

Other (describe below)

### Feedback

Me aparece un aviso que dice que una aplicación se ejecuta con privilegios de Administrador y que esto impide que algunas funcionalidades no se ejecuten con normalidad. Espero que esto pueda ayudar a resolver el problema. 
[PowerToysReport_2024-09-27-07-07-30.zip](https://github.com/user-attachments/files/17171717/PowerToysReport_2024-09-27-07-07-30.zip)

### Page URL

https://learn.microsoft.com/es-es/windows/powertoys/administrator

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/administrator.md

### Author

@alvinashcraft

### Document Id

5e66eda4-be07-4afd-7187-3e4d896f7861

**Comment by zaochih** [comment]
![](https://github.com/user-attachments/assets/3fdca381-34d2-49aa-a3f6-3a16c3c5c8a2)  
Your Settings indicates that you have not run PowerToys as administrator yet.

![](https://github.com/user-attachments/assets/2cc6301d-bbc5-419c-998a-a27df32a82ac)  
Please make sure you restarted PowerToys as administrator, or, if you just don't want to see this prompt, untick the second option will help. :)

**Comment by Jaime1980** [comment]
Muchas gracias. :-)

**Comment by zaochih** [comment]
> Muchas gracias. :-)

If my reply solved your question, please don't forget to close this issue! :)

Best,
Caozhi.
