### ISSUE TITLE
Update the UWP (WinRT) documentation to reflect the removal of AC3 decoder

### ISSUE THREAD

**Issue by YexuanXiao** [MicrosoftDocs/windows-uwp#5148]
### Type of issue

Outdated article

### Feedback

According to the [statement](https://support.microsoft.com/en-au/windows/codecs-in-media-player-d5c2cdcd-83a2-4805-abb0-c6888138e456) released in May this year, starting with Windows 11 version 24H2, AC3 decoding will no longer be supported. This issue has been confirmed on my computer, so the [UWP documentation](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/audio-video-camera/supported-codecs.md) needs to be updated to match the current situation.

**Comment by drewbatgit** [comment]
@YexuanXiao Thank you for calling this out. The page has been updated.
