### ISSUE TITLE
Workspace 85.0 windows not ordered correctly in Win11

### ISSUE THREAD

**Issue by ecc450** [MicrosoftDocs/windows-uwp#5149]
### Type of issue

Other (describe below)

### Feedback

This may be specific to File Explorer, but the windows do not consistently open in the correct order, nor are their positions assigned to the correct window. It looks like Workspaces is possibly not differentiating between the instances of File Explorer.

In other words, I'm trying to cascade multiple windows in a specific order, but instead of having Window 1 as the starting point on my Desktop, and the leftmost on my Taskbar, and Window 2 a little below and to the right and next leftmost on my Taskbar, and so on, I get maybe 1, 2, 5, 3, 4 on my Taskbar, with Window 5 as the starting point on my Desktop, and Window 3 a little below and to the right, and so on.

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/workspaces

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/workspaces.md

### Author

@alvinashcraft

### Document Id

8a5f751b-7a87-1d66-e9df-4d6e08cdc62f

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
