### ISSUE TITLE
Unable to compile C++/WinRT code when using clang-cl (LLVM-VS2014 toolset in Visual Studio project properties)

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#515]
```
  In file included from autostart.cpp:1:
  In file included from ./autostart.hpp:3:
  In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\cppwinrt\winrt/Windows.ApplicationModel.h:7:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\cppwinrt\winrt/base.h(65,10): fatal error : 'optional' file not found [c:\Users\Charles\Git\TranslucentTB\TranslucentTB\TranslucentTB.vcxproj]
  #include <optional>
           ^~~~~~~~~~
  1 error generated.
```

:(

After further inspection, it seems that the include path when using clang-cl is different from when using cl, and the one passed to clang-cl does not have `<optional>` anywhere.

BTW one needs to manually add `/std:c++17` in additional options to get past the C++17 warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81237ec1-004e-a6c0-d50b-aed59e80683a
* Version Independent ID: 02def7a7-10ff-b74c-99c6-486dadd35cc8
* Content: [Troubleshooting C++/WinRT issues - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/troubleshooting)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/troubleshooting.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/troubleshooting.md)
* Service: **unspecified**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the info, Charles! I've updated the Troubleshooting and FAQ topics (they'll be live within the next 24 hours) with info about support for LLVM/Clang. We don't support any version of this toolchain, but we do use LLVM 6.0.0 internally, and you can do the same if you follow the instructions I've added to the FAQ topic (even though, as I say, we don't support that). Once the topics are live, you'll find the info on both the Troubleshooting and FAQ topics. Please go ahead and close this issue when you're ready.

**Comment by sylveon** [comment]
Thanks.

Last I've heard, (on https://github.com/Microsoft/cppwinrt before it got archived) cppwinrt had first party support for Clang.

I also have no issues building samples or my own code via the command line with `clang`.

But the problem here is, Visual Studio passes an include path to `clang-cl` (the MSVC-like frontend of Clang, which is also supported natively by VS) that doesn't haves the required headers, such as `<optional>` and `<string_view>`. And trying to jam the MSVC include path which has them to clang-cl results in a lot of spooky red lines. This would probably be more of a Visual Studio issue however. If it is, could you link me to where I can file appropriate feedback?

**Comment by stevewhims** [comment]
Hi, Charles, for Visual Studio issues you could try the Developer Community (https://developercommunity.visualstudio.com), or Visual Studio's User Voice (https://visualstudio.uservoice.com) feedback website. There's also Microsoft Support (https://support.microsoft.com/contactus/). However, it's my understanding that Visual Studio has discontinued its support for the version of Clang that it previously shipped. I regret not being able to offer more assistance with regard to LLVM/Clang support. -Steve

**Comment by sylveon** [comment]
Thanks, I've filled a feature request [here](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/34177036-add-c-17-support-for-the-llvm-vs2014-toolset).
