### ISSUE TITLE
New+ doesn't create file

### ISSUE THREAD

**Issue by pfennig59** [MicrosoftDocs/windows-uwp#5150]
### Type of issue

Other (describe below)

### Feedback

Under Windows 11 I created a few templates, e.g. for *.py, *.js and *.json files. They appear in the New+ subitem menu but no files are created when clicking on any of them.

### Page URL

https://learn.microsoft.com/de-de/windows/powertoys/newplus

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/newplus.md

### Author

@alvinashcraft

### Document Id

e2f0c33e-aad0-50c2-7f56-2fd8e810fd76

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. First, this repository is about documentation. Your issue is about the functioning of a program.
Having that said - Is it possible you might need to refresh Explorer? Does it still happen now? Are you using the latest version of PowerToys? (v0.85.1 now)

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
