### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by daniela2000111** [MicrosoftDocs/windows-uwp#5152]
### Type of issue

Outdated article

### Feedback

bug

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/show

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/show.md

### Author

@mattwojo

### Document Id

fa61a22d-22b9-68d2-4606-ad87499ea358

**Comment by mattwojo** [comment]
CLosing. Feel welcome to reopen if you can include a description of what you have found that should be updated in the Windows Package Manager documentation.
