### ISSUE TITLE
Rephrase auto-update to update-checker

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/windows-uwp#5155]
### Type of issue

Other (describe below)

### Feedback

The documentation speaks of an auto-updater. This suggests auto updates can happen, but they can't. 'Update Checker' would be a more correct name.

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/install

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/install.md

### Author

@alvinashcraft

### Document Id

56ad7882-244e-d3d6-efe6-ec5d38ffd394

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback. I went ahead and created an internal work item to incorporate your suggestions. The PR has been merged and the changes should be live shortly.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
