### ISSUE TITLE
Windows copyright's

### ISSUE THREAD

**Issue by carlos2martinize** [MicrosoftDocs/windows-uwp#5160]
### Type of issue

Typo

### Feedback

I have copyright's to windows wich enables me to access about anything in the internet being windows has one of the largest platform route directory's how is it possible to be a private and standalone machine as you offer? I built GitKraken with my royalty right's wich is a 86.7 billion dollar developer platform that still is.t being reprosented as
mine over identity theft, i also have had military paycheck's stolen from me and hits(death threat's) from the finger pointer mob... I am being a wistle blower on some of this shit... There is Black panther's stealing from me and using my router number and private key! does that make me a rat because im not a black panther, ya to them... im not one of your outlaw's , i go through that again from white people, this world is after other peoples money and that is it... I don't owe anybody but 1 person for a plain ticket home, he even makes me unconfortable because i owe him. Microsoft owes me enough money to last my life time and my grandkids's life times... i am waiting!!!

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/configuration/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/configuration/index.md

### Author

@mattwojo

### Document Id

e0e0aecd-b61c-26ae-9bfb-24606f41e9da

**Comment by mattwojo** [comment]
This issue does not appear to relate to a need to update the package manager documentation. Closing.
