### ISSUE TITLE
Windows (I don't know which version) for android 

### ISSUE THREAD

**Issue by Liomervisxd** [MicrosoftDocs/windows-uwp#5170]
### Type of issue

Typo

### Feedback

**The best windows of android**

### Page URL

https://learn.microsoft.com/es-es/windows/android/emulator

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/emulator.md

### Author

@mattwojo

### Document Id

00c65f36-a194-58d3-3796-ff5868474ff3

**Comment by mattwojo** [comment]
Please don't waste time by opening issues without a clear description. If you have an actual issue to raise regarding this documentation, feel welcome to re-open and explain the issue that you've found.
