### ISSUE TITLE
Option NEW+ gone from context menu

### ISSUE THREAD

**Issue by vinicius-cesar** [MicrosoftDocs/windows-uwp#5171]
### Type of issue

Typo

### Feedback

At first, after updating Power Toys, everything was working fine. Suddenly, even though the feature was activated, it didn't appear in the context menu. I tried deactivating and activating it. I tried uninstalling Power Toys and reinstalling it. It didn't work. Anything I can do?

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/newplus

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/newplus.md

### Author

@alvinashcraft

### Document Id

e2f0c33e-aad0-50c2-7f56-2fd8e810fd76

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. First, this repository is about the documentation, not the actual product. For this, look at the PowerToys repo.

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
