### ISSUE TITLE
text in colour is not extracting...

### ISSUE THREAD

**Issue by arvind9** [MicrosoftDocs/windows-uwp#5175]
### Type of issue

Typo

### Feedback

text in colour is not extracting 

ex: text in green colour is not coping same like some other colours also

### Page URL

https://learn.microsoft.com/en-us/windows/powertoys/text-extractor

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/text-extractor.md

### Author

@alvinashcraft

### Document Id

0badd1c2-7821-cc2f-cec0-9913a5e16eb1

**Comment by Jay-o-Way** [comment]
Hello and thanks for your message. First, this repository is about the documentation, not the actual product. For this, look ar the PowerToys repo.
Second. There is much more specific info needed to be able to adres this issue. A screenshot at minimum.

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
