### ISSUE TITLE
Table column data is mixed up

### ISSUE THREAD

**Issue by aschultz** [MicrosoftDocs/windows-uwp#518]
Other than the first row of each table, the data in each column is shifted to the left.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd246a7e-dc3c-6669-ef6a-ba3e0cf0e968
* Version Independent ID: 8377d0de-5712-355d-cc25-894053ccfbf2
* Content: [Rich Presence configuration - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/social-platform/rich-presence-strings/rich-presence-strings-configuration)
* Content Source: [windows-apps-src/xbox-live/social-platform/rich-presence-strings/rich-presence-strings-configuration.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/social-platform/rich-presence-strings/rich-presence-strings-configuration.md)
* Service: **unspecified**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Thank you for your feedback aschultz! 
The table has been fixed.
