### ISSUE TITLE
in table【选项】incorrect【-r、--recurse、-all】should be【-r、--recurse、--all】

### ISSUE THREAD

**Issue by xianglin2020** [MicrosoftDocs/windows-uwp#5181]
### Type of issue

Typo

### Feedback

https://learn.microsoft.com/zh-cn/windows/package-manager/winget/upgrade#options

in table【选项】incorrect【-r、--recurse、-all】should be【-r、--recurse、--all】

### Page URL

https://learn.microsoft.com/zh-cn/windows/package-manager/winget/upgrade

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/upgrade.md

### Author

@mattwojo

### Document Id

ed2c403c-7bba-9647-fb5c-da556cb93a6b

**Comment by mattwojo** [comment]
Strange issue - thank you for bringing this to our attention. Filed a request with localization team to fix this.
