### ISSUE TITLE
Adding new editor

### ISSUE THREAD

**Issue by callpri** [MicrosoftDocs/windows-uwp#5182]
### Type of issue

Typo

### Feedback

Hi.

I recommend to add new code editor with a good Node.JS support - [Codelobster](https://www.codelobster.com/nodejs.html)

### Page URL

https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md

### Author

@mattwojo

### Document Id

599d0cee-8710-86ef-8093-fe1b08e4aa90

**Comment by mattwojo** [comment]
Thank you for the contribution! However, this isn't a place where we highlight new dev tools.
