### ISSUE TITLE
MDK

### ISSUE THREAD

**Issue by KarimyDawood** [MicrosoftDocs/windows-uwp#5183]
### Type of issue

Code doesn't work

### Feedback

Try to develop a workable and easy to use

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md

### Author

@mattwojo

### Document Id

b49c32ea-2efa-b090-7123-87c31d10279b

**Comment by mattwojo** [comment]
Closing as this sounds like a support issue and doesn't point out any suggested update to the docs. I will reach out to the WinGet PM and we will review to see whether there are any improvements that should be made to this guidance. 
Please feel welcome to reopen if you have specific suggestions for updating this doc.
