### ISSUE TITLE
Not work Always on top mood

### ISSUE THREAD

**Issue by Abdullah3446** [MicrosoftDocs/windows-uwp#5185]
### Type of issue

Other (describe below)

### Feedback

Not work Always on top mood (Win+Ctrl+T) Shortcut Key.

### Page URL

https://learn.microsoft.com/en-gb/windows/powertoys/always-on-top

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/always-on-top.md

### Author

@alvinashcraft

### Document Id

9724cfd6-ee22-bb48-56fe-9797bf29eed6

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the PowerToys product. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as a question or feedback about the product. If you visit the [PowerToys repository](https://github.com/microsoft/PowerToys/issues), then you'll be able to create an issue to leave product questions/feedback.
