### ISSUE TITLE
Typo in the "Controls" Section

### ISSUE THREAD

**Issue by tcouey** [MicrosoftDocs/windows-uwp#519]
For the page at: [https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro](url)

Under the section "**Controls**"
"UWP controls automatically relect the system theme..."

should probably read:

"UWP controls automatically re**f**lect the system theme..."

**Comment by serenaz** [comment]
Thanks for the catch! Will fix :)
