### ISSUE TITLE
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle error within Windows Sandbox

### ISSUE THREAD

**Issue by padlock780** [MicrosoftDocs/windows-uwp#5193]
### Type of issue

Code doesn't work

### Feedback

When Installing winget on Windows Sandbox the following error is given. Using the Powershell code provided. Only occured since the October 2024 Culmative Update on Windows 11 23H2.

I'm not able to find a download to Microsoft.VCLibs.140.00.UWPDesktop .

`Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.24.25180.0_x64__8wekyb3d8bbwe because this package depends 
on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by 
"CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor 
architecture and minimum version 14.0.33728.0, along with this package to install.
NOTE: For additional information, look for [ActivityId] a41da940-2d81-000a-c60d-1ea4812ddb01 in the Event Log or use the 
command line Get-AppPackageLog -ActivityID a41da940-2d81-000a-c60d-1ea4812ddb01
At line:8 char:1
+ Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\WDAGUt...bbwe.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand`

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md

### Author

@mattwojo

### Document Id

b49c32ea-2efa-b090-7123-87c31d10279b

**Comment by AngeloFilaseta** [comment]
I am also experiencing this issue. It should be related to [https://github.com/microsoft/winget-cli/issues/4903](https://github.com/microsoft/winget-cli/issues/4903) and [https://github.com/microsoft/winget-cli/issues/4916](https://github.com/microsoft/winget-cli/issues/4916)

**Comment by Trolldemorted** [comment]
>I am also experiencing this issue. It should be related to https://github.com/microsoft/winget-cli/issues/4903 and https://github.com/microsoft/winget-cli/issues/4916

Thanks for the links - the documented installation flow is still broken, but
```
Install-PackageProvider -Name NuGet -Force | Out-Null
Install-Module -Name Microsoft.WinGet.Client -Force -Repository PSGallery | Out-Null
Repair-WinGetPackageManager -IncludePrerelease
```

works again
