### ISSUE TITLE
Doc Recommended Edits

### ISSUE THREAD

**Issue by RDMacLachlan** [MicrosoftDocs/windows-uwp#5198]
### Type of issue

Typo

### Feedback

* Step 4 doesn't inform the user where to do the filtering. Just provides the values and says filter using this. The picture helps, but could be beneficial to update the verbiage.
* Step 6 Doesn't provide any instructions, this appears to be more of a "Note"
* Step 7 doesn't give any guidance. It just says do this if I want... but do I want to? This is my first app, make it more prescript.
* Step 8 doesn't tell me how to build the app...
* In the "Important" popout, under Unpackaged: Create a new project for an unpackaged C# or C++ WinUI 3 desktop App, there is a typo. "...loading the Windows AppSDK from a packaged with external location" I believe this should be "...from a packaged app with...".

### Page URL

https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md

### Author

@Karl-Bridge-Microsoft

### Document Id

1a90b127-6ad9-a28e-0ee4-16170021b104

**Comment by jwmsft** [comment]
Thanks for the feedback. This page has been updated.
