### ISSUE TITLE
Quick opening of "Regional format"

### ISSUE THREAD

**Issue by kazuser** [MicrosoftDocs/windows-uwp#5199]
### Type of issue

Other (describe below)

### Feedback

Hi there!

![{FA055A5C-6EF2-494D-8BC5-688871695EF9}](https://github.com/user-attachments/assets/5b7259e0-41b7-4ca9-813b-7d359c60cf05)

I can't find the appropriate "[ms-settings:...](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#time-and-language)" to open this particular window — how do I open it?

**Comment by alvinashcraft** [comment]
Hello. It doesn't appear that there is a URI to open that Settings page. I don't have any additional content for your scenario, over and above what's in the documentation. So, it might be worth pursuing this as feedback about Windows. You can use the Feedback app in Windows to request this be added to the operating system in a future release.
