### ISSUE TITLE
This information is old

### ISSUE THREAD

**Issue by tomhog** [MicrosoftDocs/windows-uwp#520]
I've just download Universal Windows SDK version 10.0.14393.0 via Visual Studio Community 2015 and GattServiceProviderResult is no longer available, in fact it seems all Bluetooth LE documentation is out of date.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43664026-c784-e891-bdec-3102f48ade77
* Version Independent ID: 4629d3c4-d850-d456-efe5-ba4c1d61c21b
* Content: [Bluetooth GATT Server - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/devices-sensors/gatt-server)
* Content Source: [windows-apps-src/devices-sensors/gatt-server.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-server.md)
* Service: **unspecified**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. As your feedback doesn't cover specific documentation fixes, I can help redirect you to the right support channel to get an answer to any questions you might have. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding UWP.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
