### ISSUE TITLE
udp

### ISSUE THREAD

**Issue by masumbillal87** [MicrosoftDocs/windows-uwp#5200]
### Type of issue

Code doesn't work

### Feedback

h

### Page URL

https://learn.microsoft.com/en-us/windows/android/defender-settings#exclusions-to-consider-for-android-development

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/defender-settings.md

### Author

@mattwojo

### Document Id

8e95d16d-aa68-38c2-ac75-008f76b767a7

**Comment by mattwojo** [comment]
Please don't waste time opening these with no description.
