### ISSUE TITLE
ペイント３ｄのダウンロード不能

### ISSUE THREAD

**Issue by yamamotokosei51** [MicrosoftDocs/windows-uwp#5208]
### Type of issue

Typo

### Feedback

ペイント３ｄのダウンロードのためにApple Storeにアクセスしたが、ダウンロードするための(アイコン)ボタンが有効にならなかった。

### Page URL

https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/msix/age-ratings

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/msix/age-ratings.md

### Author

@GrantMeStrength

### Document Id

757fb2ca-a752-f484-2a76-bd821546e2a3

**Comment by mattwojo** [comment]
This is not a documentation issue.
