### ISSUE TITLE
اليمن

### ISSUE THREAD

**Issue by aldoeius** [MicrosoftDocs/windows-uwp#5209]
### Type of issue

Typo

### Feedback

اخطاء في تثبيت التحديثات

### Page URL

https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/get-started/enable-your-device-for-development.md

### Author

@QuinnRadich

### Document Id

0a65ac0a-9884-52a8-6485-c2825b1fb4d9

**Comment by mattwojo** [comment]
Not a documentation issue. Install error is a support issue. Closing.
