### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by diogojoaquim** [MicrosoftDocs/windows-uwp#5212]
### Type of issue

Code doesn't work

### Feedback

Email and password 
![IMG_0655](https://github.com/user-attachments/assets/856041c8-c1c4-4f9e-a3d6-4800708554d2)

### Page URL

https://github.com/user-attachments/assets/856041c8-c1c4-4f9e-a3d6-4800708554d2

### Content source URL

https://github.com/user-attachments/assets/856041c8-c1c4-4f9e-a3d6-4800708554d2

### Author

Windows 

### Document Id

Diogo Joaquim

**Comment by mattwojo** [comment]
Please do not use this issue system for spam or we will need to report and block your account.
