### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RushilJalal** [MicrosoftDocs/windows-uwp#5216]
### Type of issue

Other (describe below)

### Feedback

I believe the path for 'For Developers' section in the article should be clearly laid out as `Settings > System > For Developers`.
Current path: 

![image](https://github.com/user-attachments/assets/ec170032-4e4d-439f-9153-ea02adafb495)

### Page URL

https://learn.microsoft.com/en-us/windows/sudo/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/sudo/index.md

### Author

@mattwojo

### Document Id

40f1371b-567a-8987-ec5b-448b9aa7888e

**Comment by mattwojo** [comment]
Good recommendation. Thank you!
Added in https://github.com/MicrosoftDocs/windows-dev-docs-pr/pull/4970

**Comment by RushilJalal** [comment]
@mattwojo I'm sorry but the link doesn't work...
