### ISSUE TITLE
怎么展开折叠的内容？

### ISSUE THREAD

**Issue by KIA404** [MicrosoftDocs/windows-uwp#5219]
### Type of issue

Missing information

### Feedback

输入 **winget list**  命令 展示的信息有些被折叠起来了(如下方图片所展示的)，什么命令可以展开这些折叠

![PixPin_2024-11-23_10-43-27](https://github.com/user-attachments/assets/8822e8b3-7059-40c9-9022-056fbc03d370)

### Page URL

https://learn.microsoft.com/zh-cn/windows/package-manager/winget/list

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/list.md

### Author

@mattwojo

### Document Id

a44a4676-c56a-712a-eba2-11e5335c6764

**Comment by mattwojo** [comment]
`winget list topic` 是命令，但将 `topic` 替换为你要搜索的内容的名称。
