### ISSUE TITLE
manuchari

### ISSUE THREAD

**Issue by manuchariofficial** [MicrosoftDocs/windows-uwp#5220]
### Type of issue

Code doesn't work

### Feedback

.......

### Page URL

https://learn.microsoft.com/en-us/windows/android/wsa/

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/android/wsa/index.md

### Author

manuchari

### Document Id

31f9a801-c5b5-94e7-41b9-1b2b4a1d27de

**Comment by mattwojo** [comment]
Closing. If this is a legitimate issue, please reopen and include a description of what you mean by the code not working.
