### ISSUE TITLE
PALETTEENTRY structure documentation is not in current reference

### ISSUE THREAD

**Issue by peteroupc** [MicrosoftDocs/windows-uwp#5221]
### Type of issue

Other (describe below)

### Feedback

The documentation for the Win32 [`PALETTEENTRY`](https://learn.microsoft.com/en-us/previous-versions//dd162769(v=vs.85)) structure is somehow not in the current Windows GDI reference and the reference for `wingdi.h` , when it should be, and is still found only in the Previous Versions archive.

**Comment by stevewhims** [comment]
Thanks! I've updated https://learn.microsoft.com/windows/win32/api/wingdi/ns-wingdi-paletteentry with the correct info.

In my search results I'm getting the live topic before the archived one. But I updated the info in the live one, just to be more clear/complete.

-Steve
