### ISSUE TITLE
saybo

### ISSUE THREAD

**Issue by sajjadakbarii11** [MicrosoftDocs/windows-uwp#5223]
### Type of issue

Code doesn't work

### Feedback

[Uploading راهنمای گرفتن سایز انگشت (4).pdf…]()

### Page URL

https://learn.microsoft.com/en-us/windows/dev-home/#dev-home-dashboard-widgets

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/index.md

### Author

@mattwojo

### Document Id

acdf7266-5a5a-10a9-25bc-94f01b3e5d0a

**Comment by mattwojo** [comment]
Closing. If you can add a more specific description of what you mean by the code not working in Windows Dev Home, please feel welcome to re-open.
