### ISSUE TITLE
Microsoft 

### ISSUE THREAD

**Issue by lfputnam** [MicrosoftDocs/windows-uwp#5230]
### Type of issue

Missing information

### Feedback

Opening 

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/security/design

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/security/design.md

### Author

@alvinashcraft

### Document Id

b62e3f4d-6141-9051-1d51-dc484a86cd53

**Comment by alvinashcraft** [comment]
It looks like there's no actionable feedback here, so I'll go ahead and close the issue. Please open a new issue if you have feedback about the documentation that you'd like us to address.
