### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by markuszmarkusz** [MicrosoftDocs/windows-uwp#5235]
### Type of issue

Typo

### Feedback

windows 10

### Page URL

https://learn.microsoft.com/hu-hu/windows/dev-home/#dev-home-dashboard-widgets

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-home/index.md

### Author

@mattwojo

### Document Id

acdf7266-5a5a-10a9-25bc-94f01b3e5d0a

**Comment by mattwojo** [comment]
@markuszmarkusz - Closing as this issue doesn't include a description, but please feel welcome to reopen if you've found an issue in this Windows Dev Home documentation.
