### ISSUE TITLE
Always use the same naming of the repo (nvm-windows)

### ISSUE THREAD

**Issue by oakwoodgates** [MicrosoftDocs/windows-uwp#5239]
### Type of issue

Typo

### Feedback

The [article](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows) refers to a repo as `nvm-windows` and `windows-nvm`. The true name of the repo is `nvm-windows` and should be named consistently throughout the article to avoid confusion. 

### Page URL

https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows#alternative-version-managers

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/nodejs-on-windows.md

### Author

@mattwojo

### Document Id

599d0cee-8710-86ef-8093-fe1b08e4aa90

**Comment by mattwojo** [comment]
Thanks for pointing this out. Updated! :)

**Comment by mattwojo** [comment]
Updated in PR 5044
