### ISSUE TITLE
Can we make such thing like publish function available in the Edge Development Toolkit?

### ISSUE THREAD

**Issue by quynguyenhcm** [MicrosoftDocs/windows-uwp#525]
I am converting my Chrome extensions into Edge extensions and see that it is a little bit time consuming to go through the sites to read how to publish to Edge store. Is it something that we can make life be easier by adding Publish button available in the Edge toolkit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33fc727-b228-1c8b-5403-a467fb032e05
* Version Independent ID: df12bfff-2e24-5c0f-1b41-649095bed9c3
* Content: [View app identity details - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/view-app-identity-details#link-to-your-apps-listing)
* Content Source: [windows-apps-src/publish/view-app-identity-details.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/view-app-identity-details.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for sending your feedback, I've passed it along to the team. More about the overall submission process can be found at https://docs.microsoft.com/en-us/windows/uwp/publish/app-submissions.
