### ISSUE TITLE
What's FillSurfaceWithBitmap ?

### ISSUE THREAD

**Issue by nguyen-tam** [MicrosoftDocs/windows-uwp#527]
Seem you missed FillSurfaceWithBitmap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Service: **unspecified**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by nguyen-tam** [comment]
btw, this line is error too : _lastSize = _item.Size; 
too types are different.

**Comment by eliotcowley** [comment]
Hi @nguyen-tam, thanks for bringing this to my attention. It's noted in a comment that `FillSurfaceWithBitmap` is a helper function that's not shown, and after consulting with the feature team we've decided that it's out of scope for this doc. However, [Win2D](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasBitmap.htm) makes it pretty easy to draw a bitmap to the screen. <br/><br/>

As for `_lastSize`, good catch, that should be a `SizeInt32`--I'll update the doc. Thanks!
