### ISSUE TITLE
Bulk Sale Missing

### ISSUE THREAD

**Issue by MariuSteinbach** [MicrosoftDocs/windows-uwp#528]
Hi,

I'm really missing the ability to reduce the price of a add-on, if my customers want wo buy many of them. e.g. if my app was a game and you could by gold, 1 gold costs $2, but 10 gold should only cost $15. i'm using the store-managed add-on and i want to keep it as it is.
atm the only way to achieve this I know, is to order 10 promo codes and do the deal outside of the microsoft store, and that would be a nogo for me.

Please tell me how to do that, or if it is a planned feature or if it will never be possible.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5350137-834c-57b6-d58d-55d0fcbbfc9d
* Version Independent ID: b6daf27e-8a10-763c-c2ac-804721dc79d6
* Content: [Add-on submissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/add-on-submissions)
* Content Source: [windows-apps-src/publish/add-on-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-on-submissions.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I think we do support this scenario. You can create multiple consumable add-ons with different quantities and prices - using your example, one add-on would have quantity 1/price $2, and another would have quantity 10/price $15. See https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-consumable-add-on-purchases and https://docs.microsoft.com/en-us/windows/uwp/publish/set-your-add-on-product-id#consumable for more info on building and submitting consumable add-ons. If I'm misunderstanding your scenario, or if you have additional documentation feedback, please let me know.
