### ISSUE TITLE
About AppInstance.RecommendedInstance

### ISSUE THREAD

**Issue by pnp0a03** [MicrosoftDocs/windows-uwp#529]
Could you show me the detailed scenarios that when the shell will set an instance to AppInstance.RecommendedInstance? "Some scenario" does not make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9554b9f2-2f49-1833-1143-0103c18c37c8
* Version Independent ID: ef28f9ce-bd72-0435-6238-95d574eabee1
* Content: [Create a multi-instance Universal Windows App - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Service: **unspecified**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment]
Hi, @pnp0a03, thanks for raising this issue. I've added a bit more info to the topic, changed the comment, and added a link to the API ref topic for that property. I've also passed along your ask for more information to the product team and I'll await their guidance around whether or what to add to the documentation further. I'll go ahead and update the topic if/when I get that info. Meanwhile I'll close this issue. Thanks again! ~Steve

**Comment by stevewhims** [comment]
Hi, @pnp0a03, it seems that, right now, the shell never sets a non-null value for RecommendedInstance. I'm about to fix the [AppInstance.RecommendedInstance](https://docs.microsoft.com/uwp/api/windows.applicationmodel.appinstance.recommendedinstance) topic to make that clear. That fix should be live by Monday morning.
