### ISSUE TITLE
Dont throw the exception in the code

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/windows-uwp#530]
catch (Exception err)
        {
            switch (err.HResult)
            {
                case unchecked((int)0x88982F81): //WINCODEC_ERR_UNSUPPORTEDOPERATION
                                                 // If the encoder does not support writing a thumbnail, then try again
                                                 // but disable thumbnail generation.
                    encoder.IsThumbnailGenerated = false;
                    break;
                default:
                    throw err;
            }
        }

You can see the code throw the err in `switch` that should rethrow possibility intended.

Suggestion:

                try
                {
                    await encoder.FlushAsync();
                }
                catch (Exception exception)
                {
                    const int WINCODEC_ERR_UNSUPPORTEDOPERATION = unchecked((int) 0x88982F81);

                    switch (exception.HResult)
                    {
                        case WINCODEC_ERR_UNSUPPORTEDOPERATION:
                            // If the encoder does not support writing a thumbnail, then try again
                            // but disable thumbnail generation.
                            encoder.IsThumbnailGenerated = false;
                            break;
                        default:
                            throw;
                    }
                }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a90a712-3f5c-5dac-0d72-c980577ce411
* Version Independent ID: 1fe8d3cb-0b7a-a121-0eaa-9d59ee15a215
* Content: [Create, edit, and save bitmap images - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/imaging)
* Content Source: [windows-apps-src/audio-video-camera/imaging.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/imaging.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
Thank you for the suggestion, @lindexi. I'll get the sample updated!
