### ISSUE TITLE
SIte Layout

### ISSUE THREAD

**Issue by skitzofrenicdev** [MicrosoftDocs/windows-uwp#532]
Very difficult site to navigate  please show more integration examples of the diffrent programs thanks- skitzo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2099ff76-43d5-98fd-d8bc-66ccdc14c4fe
* Version Independent ID: 1c3f3863-5413-d58b-a0e5-81a6da6bccf2
* Content: [Account types, locations, and fees - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees#account-verification)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Service: **unspecified**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Hi there - I'm sorry to hear you're finding the site difficult to navigate. Can you give me an example of a specific area or two where an example would be helpful?

**Comment by JnHs** [comment]
I'm going to close this issue, but if you have specific examples that you'd like to see in the docs, please feel free to submit more feedback.
