### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by oakcool** [MicrosoftDocs/windows-uwp#535]
Learn about commanding takes you to 404 (https://docs.microsoft.com/en-us/windows/uwp/design/commanding-basics/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e4eb9-1481-e2ae-3922-26799d2e6dbd
* Version Independent ID: 4ac739fa-45fc-651e-4c3e-fa77941655e3
* Content: [Fluent Design System for Windows - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/fluent-design-system/index#feedback)
* Content Source: [windows-apps-src/design/fluent-design-system/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/fluent-design-system/index.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by c16u** [comment]
Fixed. My changes are awaiting approval.

**Comment by AdamDavidHill** [comment]
"Learn about navigation" link also broken.

**Comment by mijacobs** [comment]
Fixed the second broken link.
