### ISSUE TITLE
How to use vector icon in WPF application?

### ISSUE THREAD

**Issue by manupstairs** [MicrosoftDocs/windows-uwp#536]
Could you please give reference link for traditional desktop application like WPF?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#feedback)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @manupstairs , 
This documentation is for UWP/WinUI--for WPF docs, please see https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/graphics
