### ISSUE TITLE
Looks beautiful - Think Light and Dark acrylic need to switch

### ISSUE THREAD

**Issue by superjose** [MicrosoftDocs/windows-uwp#538]
This thing is beautiful! I'm glad you're taking the direction you are right now. 

One small thing, close to the beginning, where it says "Acrylic with light theme", and "Acrylic with Dark theme" I think they're swapped! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d06a30bb-6e3a-1912-0a8c-b759b02cf2d9
* Version Independent ID: 1c5ed451-a0b5-105b-b5fd-a4ad1bf1585e
* Content: [Acrylic material - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#feedback)
* Content Source: [windows-apps-src/design/style/acrylic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/acrylic.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by kikisaints** [comment]
Hmm, could you post what you're looking at? I see this on the guidance page:

![image](https://user-images.githubusercontent.com/6964369/58826879-8e751e80-85f6-11e9-97b4-0d4c778d06b9.png)

Which appears correct to me.

**Comment by superjose** [comment]
Yup seems correct. I think it should've been fixed already. 

Thanks!!
