### ISSUE TITLE
API for List of AppIds

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/windows-uwp#539]
Is there an API to list the AppIds for a specific account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4bcabd-95e0-b86f-957b-b0c182cbc2a7
* Version Independent ID: cfe9f591-588e-933f-7436-323ea95bf3ab
* Content: [Access analytics data using Store services - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/access-analytics-data-using-windows-store-services)
* Content Source: [windows-apps-src/monetize/access-analytics-data-using-windows-store-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/access-analytics-data-using-windows-store-services.md)
* Service: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Can you clarify what specifically you are referring to by "AppIds"? The API I'm aware of that most closely fits your scenario is the [https://manage.devcenter.microsoft.com/v1.0/my/applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-all-apps) method in the [submissions API](https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services). This method returns info about all the apps registered to your account, including the Store ID of each app (that is, the unique value that has a format similar to 9NBLGGH4R315 and is used in Store listings). Hopefully this helps.

**Comment by mscherotter** [comment]
That’s what I was looking for – thanks.
