### ISSUE TITLE
System Input Injection restricted capability

### ISSUE THREAD

**Issue by Karl-Bridge-Microsoft** [MicrosoftDocs/windows-uwp#544]
The Name should be <rescap:Capability Name="inputInjectionBrokered" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#feedback)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Service: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by msatranjr** [comment]
Thanks for the feedback. This should be fixed now.
