### ISSUE TITLE
ToastBackgroundTask vs MyToastNotificationActionTrigger

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/windows-uwp#545]
I am wondering why "ToastBackgroundTask " is checked for creating "MyToastNotificationActionTrigger".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a268967-4b29-b53c-10a5-fd42ea97d8c8
* Version Independent ID: a6b72ed5-1cdb-9fe8-d05b-658cc4801c5a
* Content: [Send a local toast notification - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast.md)
* Service: **windows**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Hi @zipswich, can you restate your question? It's unclear what you're asking. Maybe include some code? Thanks!

**Comment by zipswich** [comment]
@anbare 
The following code from the document checks whether "ToastBackgroundTask" has been registered:
```
// If background task is already registered, do nothing
if (BackgroundTaskRegistration.AllTasks.Any(i => i.Value.Name.Equals(taskName)))
    return;
```
If it is not registered, the following code from the document seems to create a background task named "MyToastNotificationActionTrigger":
```
// Otherwise request access
BackgroundAccessStatus status = await BackgroundExecutionManager.RequestAccessAsync();

// Create the background task
BackgroundTaskBuilder builder = new BackgroundTaskBuilder()
{
    Name = "MyToastNotificationActionTrigger",
};
```
 My questions: why does the code check "ToastBackgroundTask" for creating "MyToastNotificationActionTrigger"?
Perhaps I miss some fundamental understanding of how the background task works.

**Comment by andrewleader** [comment]
@zipswich thanks for clarifying.

Background task registrations are persisted by the system. There's no need to re-register a background task that's already registered (for example, if your app was already launched once and registered the background task, there's no reason to register the background task again when you get launched the second time).

Therefore, we check if the background task is already registered.

If the background task is already registered, we're all good, and our app's background task will be fired when the user clicks a background activation button on a toast.

If the background task hasn't been registered yet (first time app has ever launched, or the OS potentially had a critical error and lost registrations), then we need to register the background task so we can receive background toast activations.

Please close this issue if that answers your question! Thank you!

**Comment by zipswich** [comment]
Thank you for the clarification, @anbare 
Actually, I understood the reason for checking and registering as you described.  My question is much simpler than what you tried to explain.  Let me try to ask my question with a bit font styling effect to clarify it:
Why does the code check task
# ToastBackgroundTask
while registering
# MyToastNotificationActionTrigger?

# ToastBackgroundTask
has different spelling than
# MyToastNotificationActionTrigger

These two words also have different lengths.

Let me know if my question is clear.  If not, I will draw a picture to clarify it.  I know that I probably miss something fundamental.

**Comment by andrewleader** [comment]
Oh, apologies, there was a typo in the code example - that's what you were trying to point out!

Indeed, both sections of code should be using the string `"ToastBackgroundTask"`, I've submitted a pull request to fix this, the correct code is below.  The docs should be updated tomorrow. Thank you zipswich!!

```csharp
const string taskName = "ToastBackgroundTask";

// If background task is already registered, do nothing
if (BackgroundTaskRegistration.AllTasks.Any(i => i.Value.Name.Equals(taskName)))
    return;

// Otherwise request access
BackgroundAccessStatus status = await BackgroundExecutionManager.RequestAccessAsync();

// Create the background task
BackgroundTaskBuilder builder = new BackgroundTaskBuilder()
{
    Name = taskName
};

// Assign the toast action trigger
builder.SetTrigger(new ToastNotificationActionTrigger());

// And register the task
BackgroundTaskRegistration registration = builder.Register();
```

**Comment by zipswich** [comment]
Thank you for the clarification, @anbare 
I am not familiar with the background task registering, so I was not sure whether it was a typo or those tasks have constant names.
