### ISSUE TITLE
jjj

### ISSUE THREAD

**Issue by twasil** [MicrosoftDocs/windows-uwp#550]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bcae26a-4045-006c-68cc-7b88a04b3e8b
* Version Independent ID: fa67b90b-34b1-0bdc-2476-32e0a46db93e
* Content: [Package flights - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights#create-a-new-flight-group)
* Content Source: [windows-apps-src/publish/package-flights.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/package-flights.md)
* Service: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @twasil. Let us know if you have any feedback on this page. Thanks!
