### ISSUE TITLE
Page rendering failed at subsection 'Confirmation Dialogs'

### ISSUE THREAD

**Issue by MythreyaK** [MicrosoftDocs/windows-uwp#556]
The text in the section [Confirmation Dialogs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs#confirmation-dialogs-okcancel) is broken, displays the url for the image, a list item as code.<br/> <br/>
![capture](https://user-images.githubusercontent.com/26112391/39956559-af1ea0ba-5600-11e8-934b-29cb5c45db6f.PNG)

**Comment by mijacobs** [comment]
Thank you, @blackbird-98 ! I've checked in a fix--the page will be refreshed tomorrow.
