### ISSUE TITLE
this  is good and alll but...

### ISSUE THREAD

**Issue by XeorgeXeorge** [MicrosoftDocs/windows-uwp#557]
allow us to disable it from code, it just consumes too much vertical space, especially if you already have multiple headers and toolbars on your app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5e1d30-a76e-5f17-2620-31f16118bfc9
* Version Independent ID: 8e90ec0d-7c26-62ed-3189-a14f7a9db0db
* Content: [Designing for Sets - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/design-for-sets)
* Content Source: [windows-apps-src/design/shell/design-for-sets.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/design-for-sets.md)
* Service: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi @moneylow , thanks for the feedback. For product feedback, please use the 'Product feedback' button in the documentation to make sure your ideas get the right people. This idea has been opened on the Developer Feedback site. Here's a link to the open issue if you'd like to vote for it. Thanks.
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/32946712-disable-sets
