### ISSUE TITLE
Closing any Instance crashes the others

### ISSUE THREAD

**Issue by StephenPSA** [MicrosoftDocs/windows-uwp#559]
Note: Running preview build 17666.

Adding the **desktop4:SupportsMultipleInstances="true"** (and xmlns) is simple enough and does allow multiple instances to open. However, closing any instance causes the UI of the others to crash. What am I doing wrong?

**Comment by ginami** [comment]
Hi @StephenPSA, can you tell me what docs page this relates to? Then I can route your question to the correct person. Thank you!

**Comment by StephenPSA** [comment]
Hi @ginami, sorry I did not realize that I had posted this issue in the wrong place until it was too late. Anyway, here's the link (that got me here |--): 
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp
Anyway, thanks for the prompt response and regards,
Stephen

PS I'll leave it to you to route the issue. TIA.
