### ISSUE TITLE
Cannot reference a windows runtime project in UWP

### ISSUE THREAD

**Issue by amoraitis** [MicrosoftDocs/windows-uwp#56]
I think that we should change the documentation of [create-and-register-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-and-register-a-background-task.md), because of a bug causing errors when referencing a windows runtime component project to UWP project

**Comment by TylerMSFT** [comment]
Hi Anastasios,
Can you elaborate a little about what you'd like to see changed?
@amoraitis

**Comment by mattwojo** [comment]
Closing -- @amoraitis please feel welcome to re-open if you are able to add more details on the issue.
