### ISSUE TITLE
Reset the Leaderboard data (Player Stats), from the the Developer Dashboard

### ISSUE THREAD

**Issue by IS-GYG** [MicrosoftDocs/windows-uwp#560]
Hi,
We have successfully implemented the leaderboard feature into our game and it works as intended. But currently the stats are permanent (meaning if the person doesn't run the game again we can't clear the stats). Is there a way to reset all the player stats (there by resting the leaderboard), from the Developer Dashboard. We want to be able to reset the leaderboard at a given interval (like once a week)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c20c8e0a-78d0-ce06-1a62-51a75d46291a
* Version Independent ID: f2fb5f0a-fdbd-6e36-0457-5f03ed730187
* Content: [Add player stats and leaderboards to your Unity project - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/add-stats-and-leaderboards-in-unity)
* Content Source: [windows-apps-src/xbox-live/get-started-with-creators/add-stats-and-leaderboards-in-unity.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/get-started-with-creators/add-stats-and-leaderboards-in-unity.md)
* Service: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Hello YawJatah, 
Unfortunately weekly leaderboard is not a current feature. Stats are permanent at this time and there is no way to clear stats from a leaderboard from the developer dashboard or programatically.
