### ISSUE TITLE
Back Button is not clickable if you go directly to the arrow character

### ISSUE THREAD

**Issue by deltakosh** [MicrosoftDocs/windows-uwp#561]
You cannot click if you hover the arrow in the back button of the navigationview (when used with coreTitleBar.ExtendViewIntoTitleBar)

Video here (you can see that when hovering the character, the buttons are no more active)
[UrzaGatherer 5_13_2018 11_14_16 AM.zip](https://github.com/MicrosoftDocs/windows-uwp/files/1998772/UrzaGatherer.5_13_2018.11_14_16.AM.zip)

Repro:
[App2.zip](https://github.com/MicrosoftDocs/windows-uwp/files/1998773/App2.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#extending-your-app-into-the-title-bar)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by sudarsanyes** [comment]
@deltakosh I face the same issue. The hit-test is not completely visible for any of the elements that span the title bar.

**Comment by deltakosh** [comment]
This is weird because the button is clickable but not were the text is...

**Comment by deltakosh** [comment]
Did you find a workaround?

**Comment by deltakosh** [comment]
Of found the solution but this will have to be in the doc:
```
        <NavigationView IsBackButtonVisible="Visible" IsBackEnabled="True"/>
        <Grid Height="28" x:Name="AppTitleBar" Background="Red" Margin="48,0,0,0" VerticalAlignment="Top">
            <TextBlock Text="MyApp"/>
        </Grid>
```

and then
```
            var coreTitleBar = CoreApplication.GetCurrentView().TitleBar;
            Window.Current.SetTitleBar(AppTitleBar);
            coreTitleBar.ExtendViewIntoTitleBar = true;
```

**Comment by serenaz** [comment]
Thanks for the catch! We'll update the doc to reflect the workaround.
