### ISSUE TITLE
Broken link at the top

### ISSUE THREAD

**Issue by c16u** [MicrosoftDocs/windows-uwp#563]
The "Windows 10 Fall Creators Update - Behavior change" section at the top contains a broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca3c70b-569d-7192-7fd1-0476236d541c
* Version Independent ID: 399e499a-6fbb-2a22-1035-81247b49828f
* Content: [Lists - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/lists#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/lists.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/lists.md)
* Service: **windows**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by jwmsft** [comment]
This link appears to be fixed.
