### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by c16u** [MicrosoftDocs/windows-uwp#564]
There are many broken links in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd894ab6-9b28-956f-fd00-3d60de336045
* Version Independent ID: 5f80b19f-f8a7-4d66-bd46-2ba165f68c0f
* Content: [Menus and context menus - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus)
* Content Source: [windows-apps-src/design/controls-and-patterns/menus.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/menus.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks, @c16u! I approved your merge request.
