### ISSUE TITLE
Outdated Mail App Screenshot

### ISSUE THREAD

**Issue by c16u** [MicrosoftDocs/windows-uwp#565]
The Mail app has undergone design updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd894ab6-9b28-956f-fd00-3d60de336045
* Version Independent ID: 5f80b19f-f8a7-4d66-bd46-2ba165f68c0f
* Content: [Menus and context menus - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus)
* Content Source: [windows-apps-src/design/controls-and-patterns/menus.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/menus.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
I updated the screen shot--it should be in the build tomorrow.
