### ISSUE TITLE
403 HTTP request error in windows 10 drivers reporting API

### ISSUE THREAD

**Issue by joybwang** [MicrosoftDocs/windows-uwp#569]
Hi Team,

We got http request 403 error in windows 10 driver reporting API, starting from May 5th. The reference is
https://docs.microsoft.com/en-us/windows/uwp/monetize/get-error-reporting-data-for-windows-10-drivers

An example:

following is the target url

https://manage.devcenter.microsoft.com/v1.0/my/analytics/driver/failurehits?applicationId=14238080284534159&startDate=04/28/2018&endDate=05/04/2018&groupby=driverName,driverVersion&orderby=date

and this is the returned error message

{u'code': u'Forbidden', u'innererror': {u'source': u'AnalyticsAPI', u'message': u'User UnauthorizedException EC5', u'code': u'Forbidden', u'data': [], u'details': []}, u'source': 'AnalyticsAPI', u'details': [], u'message': u'Access to the requested resource is forbidden.', u'data': []}

Is this a known issue?
(relocate question from Forums, no feedback from there and dev center dashboard support team)

Thanks,
Joy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927bb9e4-3b57-ea5b-c681-2fbbd41c7208
* Version Independent ID: 0a34fc81-cb7f-674c-836e-11502650cb4a
* Content: [Get error reporting data for Windows 10 drivers - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-error-reporting-data-for-windows-10-drivers#feedback)
* Content Source: [windows-apps-src/monetize/get-error-reporting-data-for-windows-10-drivers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-error-reporting-data-for-windows-10-drivers.md)
* Service: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. To clarify, were you previously able to successfully call this API, but only starting on May 5th you starting receiving the 403 error? 

Can you also confirm whether your developer account is part of the [Windows Hardware Dev Center Program ](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-started-with-the-hardware-dashboard), the driver identified by your applicationId parameter is registered to your account, and you have completed the [prerequisites to call this API](https://docs.microsoft.com/en-us/windows/uwp/monetize/access-analytics-data-using-windows-store-services#step-1-complete-prerequisites-for-using-the-microsoft-store-analytics-api) and you have [created an access token](https://docs.microsoft.com/en-us/windows/uwp/monetize/access-analytics-data-using-windows-store-services#step-2-obtain-an-azure-ad-access-token)?

**Comment by joybwang** [comment]
Thanks @mcleanbyron  for the quick reply.
Yes, it used to be working before May 5th, we have completed all the prerequisites and with a valid access token which we also used for windows 7&8.x API, that part is fine, we only got 403 error with windows 10 API.

**Comment by mcleanbyron** [comment]
I reached out to the engineering team that owns this API, and so far it sounds like there is a known service-side issue that may be the cause of the error you are seeing. If this known issue is indeed the cause of the error, the team expects the issue to be fixed in the next couple of days. I'm following up for more details, and will reply back with what I'm able to find out.

**Comment by joybwang** [comment]
Thank you @mcleanbyron

**Comment by joybwang** [comment]
Just verified, this API is working now, thanks @mcleanbyron
