### ISSUE TITLE
Please update and Notify

### ISSUE THREAD

**Issue by Leisvan** [MicrosoftDocs/windows-uwp#571]
Spring Creators Update contains lots of new glyphs. Please document those glyphs and notify when doing it. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for the feedback--the update is in progress.

**Comment by ahainen** [comment]
THIS. This page is a disaster to navigate and use and it's missing so much

**Comment by mijacobs** [comment]
Checking on the updates.

**Comment by jevansaks** [comment]
@ahainen can you elaborate on what's missing? Do you have a more specific suggestion about what could be improved?

**Comment by ahainen** [comment]
> @ahainen can you elaborate on what's missing? Do you have a more specific suggestion about what could be improved?

https://youtu.be/RzohF-Wbdy8

**Comment by judysa** [comment]
It's in our queue to update this. Thanks!

**Comment by judysa** [comment]
It's in our queue to update this. Thanks!

**Comment by ahainen** [comment]
> It's in our queue to update this. Thanks!

https://github.com/MicrosoftDocs/windows-uwp/issues/411

**Comment by mijacobs** [comment]
We published the updated on June 21st. Please re-open if there are items missing.
https://github.com/MicrosoftDocs/windows-uwp/commit/d5667ea32e90acef44f903806aad356813ed5e62#diff-e461a5aa680b93a61bdac9007555bbf6
