### ISSUE TITLE
Windows Media Player required (i.e. will not work with Windows N unless WMP is installed manually)

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/windows-uwp#572]
It might be worth noting that this API requires Windows Media Player to be installed. I had a Windows N version installed and the instructions in this guide did not work until I installed WMP, or tried it on another PC that had the full version of Windows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a1f082e-0af1-9d7a-2e8c-24a028d39f74
* Version Independent ID: aaee3af5-33a7-be92-1de7-d8bcff95c95c
* Content: [Sound - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/sound)
* Content Source: [windows-apps-src/design/style/sound.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/sound.md)
* Service: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
Seems related to microsoft/microsoft-ui-xaml#754. I'll add that to that issue.
