### ISSUE TITLE
Windows Media Player required to be installed (i.e. will not work with Windows N unless WMP is installed manually)

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/windows-uwp#573]
It might be worth noting that this API requires Windows Media Player to be installed. I had a Windows N version installed and the instructions in this guide did not work until I installed WMP, or tried it on another PC that had the full version of Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d5f6e40-85e2-8509-3d8e-655ce275733f
* Version Independent ID: abc38dea-1910-26eb-c989-315223a4025c
* Content: [Play audio and video with MediaPlayer - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer)
* Content Source: [windows-apps-src/audio-video-camera/play-audio-and-video-with-mediaplayer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/play-audio-and-video-with-mediaplayer.md)
* Service: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for identifying this issue and bringing it to our attention! The following note has been added to the article:

"Windows 10 N and Windows 10 KN editions do not include the media features required to use MediaPlayer for playback. These features can be installed manually. For more information, see Media feature pack for Windows 10 N and Windows 10 KN editions."

**Comment by christian-becker-ta** [comment]
How to handle this on developer side?
Currently I don't know which Version of Windows 10 the user has installed. So if they download my app, they can start them, and because they have installed the N Version of Windows 10, the app crashes directly. 

Is there a possibility to check on App_Start event to show a Message to the User with a link to the Media Package? 
 
Greetings
Christian
