### ISSUE TITLE
where is the api for broadFileAccess ?

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#574]
I am trying to create a File Explorer like uwp app, it will be an app like traditional file explorer in windows 10 but it will mainly show only video files, so for that I want to use **BroadFileAccess** capability.
Usually when I use a capability related to FileAccess I have a simple API like **KnownFolders.VideoLibrary** and others like that to get the root folder of that library, but in this case broadfileacccess claims to give access to complete file system which is available to the user, but in the docs there is not a single method or api reference something like**KnownFolders.FileSystem** which can give us the root folder of the file system of the user so we can build apps like file explorer etc. How can I actually go on and use this **broadFileAccess** capability if there is not even a api method to use it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d92df11-eaec-44ea-d130-e84304af9b8f
* Version Independent ID: d8ada2a7-dcea-96cc-210b-5b446ee88cad
* Content: [File access permissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Service: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by mfe-** [comment]
Are you looking for something like: `targetStorageFolder = await StorageFolder.GetFolderFromPathAsync(Path.GetDirectoryName("c:\"));` ? FileSavePicker and FileOpenPicker doesn't provide an api for a custom SuggestedStartLocation. Upvote this feature @ https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/32192203-folderpicker-and-filepicker-with-startup-path

**Comment by touseefbsb** [comment]
no actually I was looking for enumerating all local disk folders in the app.

**Comment by laurenhughes** [comment]
@touseefbsb, I'm not aware of a similar API for broadFileSystemAccess, but I'll pass on your feedback to the product team. Thanks!
