### ISSUE TITLE
only works on Windows 10.0.17110 ?

### ISSUE THREAD

**Issue by pzarzycki** [MicrosoftDocs/windows-uwp#575]
Am I right that it requires AI evaluation components embedded in recent Windows OS release? On my Windows 10.0.16299 when this example is run, it throws the exception: "Requested Windows Runtime type 'Windows.AI.MachineLearning.Preview.LearningModelPreview' is not registered."

Can ONNX models be evaluated with CNTK evaluation libraries available via Nuget?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd018cd-e51b-b15b-3460-8ff4a4a83f3b
* Version Independent ID: 4f95e997-6554-9384-5f57-a193e4c85bf8
* Content: [Get started with Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/get-started)
* Content Source: [windows-apps-src/machine-learning/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/get-started.md)
* Service: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Yep! You'll need the Windows 10 SDK, Build 17110 or higher, as stated in the prerequisites. You can import/export ONNX models to CNTK - see [ONNX tutorials](https://github.com/onnx/tutorials).
