### ISSUE TITLE
Tables are not formatting properly

### ISSUE THREAD

**Issue by rjmurillo** [MicrosoftDocs/windows-uwp#576]
Titles for "Windows 10 release types and cadences" and "Supporting apps in Windows as a service"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c5a46f-6d25-c980-9b45-854ff434f889
* Version Independent ID: 423cdea1-a44e-caaa-7943-757622dd51c5
* Content: [App development for Windows as a service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/application-development-for-windows-as-a-service)
* Content Source: [windows-apps-src/updates-and-versions/application-development-for-windows-as-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/updates-and-versions/application-development-for-windows-as-a-service.md)
* Service: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by pedrolamas** [comment]
Seems that [Windows Phone Silverlight to UWP API mappings](https://docs.microsoft.com/en-us/windows/uwp/porting/wpsl-to-uwp-namespace-and-class-mappings) also suffers from this issue, but [the original](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/wpsl-to-uwp-namespace-and-class-mappings.md) is working fine here in GitHub.

**Comment by QuinnRadich** [comment]
I've fixed the tables in question, in both this page (already live), and the mentioned Silverlight page (live tomorrow). Thanks for the heads-up!
