### ISSUE TITLE
The screenshot for the Consume Windows Runtime Extension field is incorrect

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/windows-uwp#577]
In the step where it says

`In the General settings of the C/C++ settings group, set the Consume Windows Runtime Extension field to Yes(/ZW)`

the following screenshot shows the setting for Enable Minimal Rebuild, rather than Consume Windows Runtime Extension. Looks like the same screenshot was accidently used for two steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6012862f-de3d-cff6-72e1-f2ea8a5db7a4
* Version Independent ID: c1fcafa1-7c75-9e83-de77-3f54f89a24da
* Content: [Enhance your desktop application for Windows 10 - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-enhance.md)
* Service: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you! I've updated the image and it should appear in the content by tomorrow.

**Comment by andrewleader** [comment]
Thanks normesta!!
