### ISSUE TITLE
The path for Visual Studio installation directory is incorrect

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/windows-uwp#578]
In the step where it asks you to add an additional dependency for `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcpackages`, that path is incorrect and doesn't exist unless you have old versions of VS installed.

This should somehow use an environment variable path that doesn't have dependencies on installation directories, since otherwise this makes your project specific to a drive name and installation path.

Docs should be updated with the correct way using the environment variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6012862f-de3d-cff6-72e1-f2ea8a5db7a4
* Version Independent ID: c1fcafa1-7c75-9e83-de77-3f54f89a24da
* Content: [Enhance your desktop application for Windows 10 - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-enhance.md)
* Service: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you! I've updated the path with an environment variable. Please let us know if that path doesn't work for you. Thx!
