### ISSUE TITLE
Highlight https://developer.microsoft.com/en-us/windows/apps/develop in the UWP landing page

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windows-uwp#584]
https://developer.microsoft.com/en-us/windows/apps/develop used to be on the forefront of the UWP page, now it is on the ribbon, even though it would be a better starting point for anyone wanting to develop UWP, please give it a more 'in the front' position on the page

This issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/73

**Comment by jevansaks** [comment]
@Powerhelmsman I can't tell who opened this issue and the linked issue doesn't really have more info. What page do you want a more promoted link for the develop section?
