### ISSUE TITLE
The UWP Hello world event handling run error in runtime

### ISSUE THREAD

**Issue by kira1752** [MicrosoftDocs/windows-uwp#587]
I love to tried UWP development for my next app. So i read this documentation and tried to build it and fortunately it went smoothly.......until i tried to run the UWP app (For event handler section)......Yes it build, but after i clicked the hello world button, its throw an exception like this: 

Unhandled exception at 0x1046E32C (Windows.UI.Xaml.dll) in App1.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x1308F2D0, 0x00000003). occurred

What i supposed to do to make it run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Hi - I'm sorry this happened. I just went through the tutorial with a fresh install of Visual Studio, and did not find any issues. I would recommend that you make sure you are using the latest version of Windows 10, and use the Visual Studio Installer application to Update Visual Studio to the latest version. If it's already up to date, click on More / Repair.
