### ISSUE TITLE
hjkhgf

### ISSUE THREAD

**Issue by JEB174** [MicrosoftDocs/windows-uwp#589]
asdfgh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278d1d4a-391f-3008-e6f6-910be06cd370
* Version Independent ID: 82b6edb4-a6e6-c2f4-d19f-2b274734175b
* Content: [Create a developer account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/sign-up)
* Content Source: [windows-apps-src/get-started/sign-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/sign-up.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by ginami** [comment]
Hi @JEB174--let us know if you have any page-specific feedback. Thanks!
