### ISSUE TITLE
TreeView.SelectedNodes causes System.AccessViolationException

### ISSUE THREAD

**Issue by robloo** [MicrosoftDocs/windows-uwp#590]
Accessing a TreeView's SelectedNodes or SelectedNodes.Count property can catastrophically fail bringing down the app and even the debugger. The TreeView has no root nodes and SelectionMode=Single when the crash happens.

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

This is why WPF is so much more powerful. It is implemented in managed code.

**Comment by predavid-zz** [comment]
Hey @robloo, thanks for reporting the issue. We are looking into it.

**Comment by predavid-zz** [comment]
@jevansaks - wasn't this bug already fixed by Kai. If yes, we can close now.

**Comment by jevansaks** [comment]
Agree, this is fixed. If not please open an issue against https://github.com/Microsoft/microsoft-ui-xaml.
