### ISSUE TITLE
April's windows update broke working code

### ISSUE THREAD

**Issue by maxal1917** [MicrosoftDocs/windows-uwp#594]
Using MVVM pattern, I created menu items using MenuItemSource property. In my "ItemInvoked" event handler I have this code:
            if (args.IsSettingsInvoked)
            {
                var vm = DataContext as AppShellViewModel;
                if (vm != null)
                    vm.SettingsClicked();
            }
            else
            {
                var s = Convert.ToString(args.InvokedItem);
                var menuItem = sender.MenuItems.OfType<NavigationViewItem>().First(x => Convert.ToString(x.Content) == s);
                if (menuItem != null)
                {
                    var command = menuItem.Tag as ICommand;
                    if (command != null)
                        command.Execute(null);
                }
            }
First, it's ugly, but I couldn't find better way of using Command. Second, it used to work prior to Aprils, update, but now MenuItems array is empty, even though UI works. But I cant find menuItem anymore to get to the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by maxal1917** [comment]
I fixed it be going directly to ViewModel instead of sender.MenuItems. But want to bring your attention that this code is broken. And Ideally, I would want to just see same support for Commands that exists everywhere else (like Buttons). Menu Items should have property Command that would be used without me handling ItemInvoked event.

**Comment by serenaz** [comment]
Thanks for the valuable feedback - passing along to the product team!
