### ISSUE TITLE
Specify SDK Version 

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/windows-uwp#595]
Please state which SDK version/Windows Build these changes are available in, if applicable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e5b22d-e803-5c0a-3e82-d08f59919ac5
* Version Independent ID: 85cb8283-4d80-b519-a03b-f3efab4f6d75
* Content: [Host UWP controls in WPF and Windows Forms applications - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls)
* Content Source: [windows-apps-src/xaml-platform/xaml-host-controls.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/xaml-host-controls.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thanks! The XAML Island host control hasn't released yet. The only thing available now is the WebView control which you can by downloading the Microsoft.Toolkit.Uwp.UI.Controls Nuget package. See this page of the Windows Community Toolkit - https://docs.microsoft.com/en-us/windows/uwpcommunitytoolkit/nuget-packages. When we have something available in the SDK, we will most certainly put the required SDK version. Thank you!
