### ISSUE TITLE
Zoom In view Must define GroupStyle

### ISSUE THREAD

**Issue by NicolasG3** [MicrosoftDocs/windows-uwp#597]
It should be stated that Zoom In/Out relation rely on GroupStyle definition in Zoom In view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ec0c3a-902b-1d66-67ce-d9ae831dc6c6
* Version Independent ID: 20926a92-1e40-689e-bee3-a6b341afebf5
* Content: [Semantic zoom - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/semantic-zoom)
* Content Source: [windows-apps-src/design/controls-and-patterns/semantic-zoom.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/semantic-zoom.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by predavid-zz** [comment]
@jwmsft - could you please update this file to address this issue : windows-apps-src/design/controls-and-patterns/semantic-zoom.md?
