### ISSUE TITLE
Misleading information about getting CurrentItemIndex

### ISSUE THREAD

**Issue by ngducnghia** [MicrosoftDocs/windows-uwp#599]
Above stated: "You may want to periodically check for the currently playing item in order to update your UI. Be sure to check the CurrentBreak property for null first. If the property is null, no media break is currently playing."
However I find that I can register to MediaPlayer.BreakManager.CurrentBreak.PlaybackList.CurrentItemChanged event to get notified. Can anyone confirm if we should "periodically check" or "register to event" to update UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a217832e-c04a-ae5a-2c06-2cbb2eb39a95
* Version Independent ID: 92377f46-f3eb-4452-3005-e4dc8d4c4d72
* Content: [Create, schedule, and manage media breaks - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/create-schedule-and-manage-media-breaks)
* Content Source: [windows-apps-src/audio-video-camera/create-schedule-and-manage-media-breaks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/create-schedule-and-manage-media-breaks.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for your feedback. I confirmed with the feature team that polling the CurrentBreak property is unnecessary. This text has been removed from the article.
