### ISSUE TITLE
Documentation for inProcessMediaExtension app capability

### ISSUE THREAD

**Issue by saschanaz** [MicrosoftDocs/windows-uwp#60]
(Moved from [MSDN](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/611f7780-6e5b-4d30-b2df-2fe3198f240c/is-the-permission-inprocessmediaextension-microsoftonly?forum=wpdevelop))

I found that there is an MPEG2 extension for UWP apps. Then I found that the required permission is inProcessMediaExtension, which seems to help creating UWP media extensions which was not possible before. It's an interesting feature but I couldn't find any information about this permission.

Probably this is currently a private restricted capability, so can you please add documentation about it here? https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md

**Comment by msatranjr** [comment]
Thanks for reaching out to us, SaschaNaz! Unfortunately, the capability you referenced is not consumable by a third-party app, even when side-loading. We do not document these types of capabilities.
