### ISSUE TITLE
Verification Status is rejected how to resolve this 

### ISSUE THREAD

**Issue by AdityaSaurabhbxr** [MicrosoftDocs/windows-uwp#601]
In my developer account i am trying a lot but not finding any place for easy option to resolve this If you can help me with this please Help ASAP 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a5c98-ba0b-38a0-d86e-2d5df4745d1a
* Version Independent ID: 643673cc-0b57-86f6-e00d-13aad2ef8d20
* Content: [Opening a developer account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
You'll need to contact support to resolve this. Please open a request at https://developer.microsoft.com/windows/support.
