### ISSUE TITLE
Sign up link broken

### ISSUE THREAD

**Issue by neonguru** [MicrosoftDocs/windows-uwp#603]
http://go.microsoft.com/fwlink/p/?LinkId=615100

That link does not work and is given in many places to sign up for a developer account.
You're not getting sign ups this way...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278d1d4a-391f-3008-e6f6-910be06cd370
* Version Independent ID: 82b6edb4-a6e6-c2f4-d19f-2b274734175b
* Content: [Create a developer account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/sign-up)
* Content Source: [windows-apps-src/get-started/sign-up.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/sign-up.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thank you for the heads-up.

The redirect to the proper sign-up endpoint seems to be unreliable now. I'm investigating the cause, but for the time being I'd advise you to try the link a couple times until it works.

Edit: The redirect issue has been solved, and the sign up link should now work normally.
