### ISSUE TITLE
UWP .appinstaller - “Error in parsing the app package.”

### ISSUE THREAD

**Issue by DavidMhluzi** [MicrosoftDocs/windows-uwp#609]
I get the "Error in parsing the app package" any idea what I could be doing wrong? below is my appinstaller

<?xml version="1.0" encoding="utf-8"?>
<AppInstaller
    xmlns="http://schemas.microsoft.com/appx/appinstaller/2017"
    Version="1.0.0.0" 
    Uri="http://mywebservice.azurewebsites.net/APP_UWP.appinstaller" > 

    <MainBundle 
        Name="MainApp"
        Publisher="CN=EGSolutions"
        Version="1.0.0.0"
        Uri="http://mywebservice.azurewebsites.net/EGClockingXamarin.UWP_1.0.8.0_x86_x64_arm_Debug.appxbundle" />

    <Dependencies>
        <Package Name="Microsoft.NET.CoreRuntime.2.1" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Version="14.0.24605.0" ProcessorArchitecture="x86" Uri="http://foobarbaz.com/Microsoft.NET.CoreRuntime.2.1.appx" />
        <Package Name="Microsoft.VCLibs.ARM.Debug.14.00" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Version="14.0.24605.0" ProcessorArchitecture="x64" Uri="http://foobarbaz.com/Microsoft.VCLibs.ARM.Debug.14.00.appx" />
    </Dependencies>

</AppInstaller>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2254d309-a79d-b6ed-fb4c-73ef689b76ec
* Version Independent ID: 96fa695b-4f0e-4d09-4b26-f7a501a78c9c
* Content: [Installing UWP apps from a web page - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/installing-uwp-apps-web)
* Content Source: [windows-apps-src/packaging/installing-UWP-apps-web.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/installing-UWP-apps-web.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by naruto0089** [comment]
I'm facing the same issue "Error in Parsing the app package."

**Comment by naruto0089** [comment]
@DavidMhluzi Have you made any progress with this error?

**Comment by DavidMhluzi** [comment]
@naruto0089 NO...any progress on your side?

**Comment by naruto0089** [comment]
@DabidMhluzi  Yes, I got this working.  I guess you missed to set MIME types. Check this link: https://docs.microsoft.com/en-us/windows/uwp/packaging/create-appinstallerfile-vs.  
May I know what version and build of Windows 10 you are in ?

**Comment by laurenhughes** [comment]
@DavidMhluzi, were you able to get this working? You may need to install a newer version of Windows 10.

**Comment by hamz250** [comment]
Same isssue For me "Error in Parsing the app package.", I added the MiMe types to my apche server config but with no success.
 any progress ?

**Comment by jashif** [comment]
any idea how to make it work, every time it gives the error in parsing package

i have run the sample app provided in the docs.microsoft.com also 
https://github.com/AppInstaller/MySampleWebApp
that also giving same error

**Comment by jashif** [comment]
i think the issue was with network isolation becz of localhost, when i hosted in azure it worked fine .

**Comment by ghost** [comment]
jashif is correct, 

https://docs.microsoft.com/en-us/windows/uwp/packaging/web-install-iis

Carry out the first 2 actions in Step 8

**Comment by 07c0ff3a590b** [comment]
Run PowerShell Command:
`Add-AppxPackage -path "C:\Path\To\Your\UWP\Package"`

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. If anyone on this thread is still encountering problems with App Installer-related issues, please post your question at the [MSIX Tech Community Forum](https://techcommunity.microsoft.com/t5/msix-deployment/bd-p/MSIX-Deployment). If you have feedback or change requests against the docs, please open another issue against the article or feel free to submit your own pull request change.
