### ISSUE TITLE
Unity UWP connection to SQL Server Hololens

### ISSUE THREAD

**Issue by rafaP** [MicrosoftDocs/windows-uwp#610]
How do i use System.Data.SQLClient in Hololens, from a project in Unity?

It work fine in unity editor but it's not working in Hololens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470286a7-904e-2767-503b-4e6b987a103d
* Version Independent ID: 47a87779-9715-c08f-39d2-fe0566398d78
* Content: [Missing .NET APIs in Unity and UWP - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/missing-dot-net-apis-in-unity-and-uwp)
* Content Source: [windows-apps-src/gaming/missing-dot-net-apis-in-unity-and-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/missing-dot-net-apis-in-unity-and-uwp.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by eliotcowley** [comment]
Hi @rafaP, apologies for the late reply on this. I'll investigate and try to get in touch with the feature team, and get back to you.

**Comment by eliotcowley** [comment]
Hi @rafaP, have you tried compiling with IL2CPP as the scripting backend? This should make all .NET APIs functional in UWP. As noted in the doc, you can change it in **File > Build Settings**, select **Universal Windows Platform**, and then **Player Settings**. Under **Other Settings > Configuration**, open the **Scripting Backend** drop-down, and select **IL2CPP**.

**Comment by rafaP** [comment]
Hello, I already tested it with IL2CCP, but the result is the same.

Cumprimentos, Rafael Pereira



De: Eliot Cowley
Enviado: quinta-feira, 21 de junho, 23:50
Assunto: Re: [MicrosoftDocs/windows-uwp] Unity UWP connection to SQL Server Hololens (#610)
Para: MicrosoftDocs/windows-uwp
Cc: rafaP, Mention


Hi @rafaP<https://github.com/rafaP>, have you tried compiling with IL2CPP as the scripting backend? This should make all .NET APIs functional in UWP. As noted in the doc, you can change it in File > Build Settings, select Universal Windows Platform, and then Player Settings. Under Other Settings > Configuration, open the Scripting Backend drop-down, and select IL2CPP.

**Comment by eliotcowley** [comment]
Unity doesn't actually have support for System.Data.SqlClient by default--I had to manually add the DLL to my project. I did this by searching in the directory where I installed Unity for **System.Data.SqlClient.dll**, then creating a folder in my project called **Plugins** and copying the DLL over. Once I had done that, everything compiled correctly, both in the editor and when I built for UWP. I haven't tested on a HoloLens, but I don't see a reason why it wouldn't work.

If you're still having trouble, I would direct you to the [Unity Community](https://unity3d.com/community?_ga=2.43060005.1227104458.1529945576-396904147.1528494547) or [Windows developer support](https://developer.microsoft.com/en-us/windows/support).

**Comment by rafaP** [comment]
I have done that and it works on Unity editor, but don't work on hololens. I will use services to do this, because it's not working.

Cumprimentos, Rafael Pereira



De: Eliot Cowley
Enviado: segunda-feira, 25 de junho, 18:06
Assunto: Re: [MicrosoftDocs/windows-uwp] Unity UWP connection to SQL Server Hololens (#610)
Para: MicrosoftDocs/windows-uwp
Cc: rafaP, Mention


Unity doesn't actually have support for System.Data.SqlClient by default--I had to manually add the DLL to my project. I did this by searching in the directory where I installed Unity for System.Data.SqlClient.dll, then creating a folder in my project called Plugins and copying the DLL over. Once I had done that, everything compiled correctly, both in the editor and when I built for UWP. I haven't tested on a HoloLens, but I don't see a reason why it wouldn't work.
If you're still having trouble, I would direct you to the Unity Community<https://unity3d.com/community?_ga=2.43060005.1227104458.1529945576-396904147.1528494547> or Windows developer support<https://developer.microsoft.com/en-us/windows/support>.

**Comment by avasqueshololab** [comment]
> How do i use System.Data.SQLClient in Hololens, from a project in Unity?
> 
> It work fine in unity editor but it's not working in Hololens.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 470286a7-904e-2767-503b-4e6b987a103d
> * Version Independent ID: 47a87779-9715-c08f-39d2-fe0566398d78
> * Content: [Missing .NET APIs in Unity and UWP - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/missing-dot-net-apis-in-unity-and-uwp)
> * Content Source: [windows-apps-src/gaming/missing-dot-net-apis-in-unity-and-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/missing-dot-net-apis-in-unity-and-uwp.md)
> * Service: **unspecified**
> * Product: **windows**
> * GitHub Login: @eliotcowley
> * Microsoft Alias: **elcowle**

Do you fix this problem?
