### ISSUE TITLE
IsAccessKeyScope usage

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/windows-uwp#611]
It wasn't entirely clear to me that the element with IsAccessKeyScope set to true actually needs an access key. I thought that as long as the focus is within the container, all access keys within that container have precedence and work. Speaking of which, is there a way to achieve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5947b2-fd1c-dc30-8cf5-9a357d8adf07
* Version Independent ID: a414afeb-51cb-3b63-7820-5d43be6eb84f
* Content: [Access keys design guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys)
* Content Source: [windows-apps-src/design/input/access-keys.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/access-keys.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @SilverSilence, did you try the snippet code in the https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys#set-access-key-scope section?

Using this sample, the secondary access keys are fully accessible just by tabbing to the primary <AppBarButton Icon="Refresh" Label="Refresh" IsAccessKeyScope="True"> element and activating it. The Refresh button does not require an access key to be defined.

If you have an example that doesn't work this way, please provide it here. 

Thanks!
