### ISSUE TITLE
Rewrite article to use C++/WinRT

### ISSUE THREAD

**Issue by reflectronic** [MicrosoftDocs/windows-uwp#613]
I think that would leave a better impression on interested C++ developers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592392b3-226e-4277-4ed3-7f8789ab93de
* Version Independent ID: dc387625-6acb-52bb-ea7e-020af9913d80
* Content: [Create a Hello World app in C++ (Windows 10) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cpp)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by yilmazdurmaz** [comment]
C++/WinRT has just been born with W10 1803. Do not expect a fast transformation to it. And as you can deduct, it applies to newer versions and not all developers would be interested to be stuck like that.

But instead of rewriting, they might include another page for it.

**Comment by GrantMeStrength** [comment]
Thank you. Yes, we have plans to give C++/WinRT the visibility it deserves!
