### ISSUE TITLE
Using DataTemplateSelector

### ISSUE THREAD

**Issue by beatnikthedan** [MicrosoftDocs/windows-uwp#615]
I tried modifying the Item datatemplate like it outlines in the code example which works fine but I need to use a datatemplateselector to change the datatemplate per node since each node is a different object...
It doesn't seem to work because the real datacontext needs to be "Content" not "TreeviewNode".
It also passes  null to the Object param of the datatemplateselector.
Can you show an example or give clarification on how to use a datatemplateselector with treeview?

Here is an example of what I'm doing, I only changed one line to use the ItemTemplateSelector:

```
<Style TargetType="TreeView">
        <Setter Property="IsTabStop" Value="False" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="TreeView">
                    <TreeViewList x:Name="ListControl"
                                      ItemTemplateSelector="{StaticResource CardSelector}"
                                      ItemContainerStyle="{StaticResource TreeViewItemStyle}"
                                      CanDragItems="True"
                                      AllowDrop="True"
                                      CanReorderItems="True">
                        <TreeViewList.ItemContainerTransitions>
                            <TransitionCollection>
                                <ContentThemeTransition />
                                <ReorderThemeTransition />
                                <EntranceThemeTransition IsStaggeringEnabled="False" />
                            </TransitionCollection>
                        </TreeViewList.ItemContainerTransitions>
                    </TreeViewList>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>



```---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba995b-8bf3-407c-7b87-015d22d813f1
* Version Independent ID: 52c553b6-e94d-2810-4123-8ee215b002bf
* Content: [Tree view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by beatnikthedan** [comment]
filled this out from here and from MS documentation site so this is redundant, sorry

**Comment by kswoll** [comment]
Yes, this seems broken to me.  I tried using the example for hierarchical nodes and the data template selector, and using the example code, I end up with a `TreeViewItem` that contains a `TreeViewItem` that results in many problems.  (this is as @beatnikthedan mentioned that it expects the template to be the _content_ and not an instance of `TreeViewItem`)

**Comment by predavid-zz** [comment]
@jwmsft - I understand this is already on you radar to update the code sample in the docs.

**Comment by jwmsft** [comment]
Doc and sample code have been updated to show DataTemplateSelector.
