### ISSUE TITLE
Implement Navigation Between Pages

### ISSUE THREAD

**Issue by kevinb67** [MicrosoftDocs/windows-uwp#616]
You may want to change this instruction to include exactly where to put the tags within Page1.xaml and Page2.xaml and the code within the Page1xaml.cs and Page2.xaml.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be10565a-f999-569f-3314-f1691cfa3d6f
* Version Independent ID: 3e862b52-b135-e9af-5c13-424002f038d8
* Content: [Peer-to-peer navigation between two pages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigate-between-two-pages)
* Content Source: [windows-apps-src/design/basics/navigate-between-two-pages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigate-between-two-pages.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
The tutorial instructions specify where to place the tags within the XAML pages. As for the CS code, you can place the methods anywhere inside the class!
