### ISSUE TITLE
Uninstall API not working as it should

### ISSUE THREAD

**Issue by raksha-git** [MicrosoftDocs/windows-uwp#618]
The rest call for uninstalling an app does not work. Also, it would be great if the API doc is updated with code examples.

DELETE |  /api/app/packagemanager/package

**Comment by ginami** [comment]
Hi @raksha-git--thank you for your feedback. Can you tell me which docs pages you're referring to, so I can route your comments to the correct person? Thank you!

**Comment by ginami** [comment]
Closing this issue for now--let us know if you have further information or questions. Thanks!
