### ISSUE TITLE
Drag and drop link is broken

### ISSUE THREAD

**Issue by Vijay-Nirmal** [MicrosoftDocs/windows-uwp#619]
The link should be https://docs.microsoft.com/en-us/windows/uwp/design/input/drag-and-drop instead of https://msdn.microsoft.com/windows/uwp/app-to-app/drag-and-drop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56871f82-c1f1-f0c7-2a6c-e52b1e555169
* Version Independent ID: 33382558-8133-ffcd-6ed5-e5da44b417de
* Content: [List view and grid view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/listview-and-gridview#drag-and-drop)
* Content Source: [windows-apps-src/design/controls-and-patterns/listview-and-gridview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/listview-and-gridview.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by GrantMeStrength** [comment]
Thanks! Corrected link should go live soon.

**Comment by ScottIsAFool** [comment]
@GrantMeStrength Hi John, the link is still broken, so if a fix was pushed, it's been broken again. Although I can't see any closed or open pull requests, should I open one?

**Comment by jwmsft** [comment]
Both instances of the link are fixed now.
