### ISSUE TITLE
... available?

### ISSUE THREAD

**Issue by Musenginst** [MicrosoftDocs/windows-uwp#620]
I know you guys are working on it but a working sample with XAML etc. would really be welcome at this point. Great stuff BTW, can't wait!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0d8b84-01be-3ee5-d4e3-ac01e505ab2a
* Version Independent ID: b8e7ca9f-e8e7-99dc-f4c7-08d5c32e763c
* Content: [Photo Editor C++/WinRT sample application - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/photo-editor-sample)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/photo-editor-sample.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/photo-editor-sample.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
@Musenginst, sincere apologies for the delay. We're still dotting the "i"s and crossing the "t"s administratively-speaking in order to be ready to release the source code. Meanwhile, there is example code that shows how to use XAML in the following two topics (it's not what you'd call a full sample app, but the code examples do show XAML in action). https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property and https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-collection.

**Comment by Musenginst** [comment]
@stevewhims, thanks a lot for the reply, and I do get it -- delays happen. Thanks also for the references that I've seen and am in the very process of checking out. These are extremely valuable but, like you indicate yourself, probably don't offer the full potential yet of what I genuinely believe we've yet to see not only in terms of XAML  but also in combination with animation, async coroutines, and overall best practices, the whole shebang. You guys have delivered already red hot stuff, and I have some pointers at this stage, but I really would like to see a sample that demonstrates what you guys have fully in your minds (and I believe it'll be tremendously exciting). The combination is more than the facets.

Anyway, thanks for the update, and I'll continue to wait anxiously.

**Comment by stevewhims** [comment]
Thanks so much for your enthusiasm, kind words, and patience, @Musenginst! :) We're super-excited about C++/WinRT, too! Again, thanks!

**Comment by stevewhims** [comment]
Hi, @Musenginst, the sample is now available for download. I've updated the topic with the info and the link to the repo, which is: https://github.com/Microsoft/Windows-appsample-photo-editor. Do you mind if I go ahead and close this issue? Many thanks! Steve

**Comment by Musenginst** [comment]
Thanks, @stevewhims, for the note. I'm thrilled that you guys have uploaded the sample, and please go ahead closing the issue. I'll be downloading the sample tomorrow (or within very few days' time) and if I have any issues or particular praises, I'll post back anyway. 😉

I don't think C++/WinRT has already got the reception/appraisal yet that it deserves, but I have a pet project of mine in mind (visualizing genealogy) to which it might just be perfect, and that I could issue as public, possibly qualifying as a demo. (Don't mean to promise too much though, at this stage it's just a concept.)

**Comment by stevewhims** [comment]
Excellent! I hope your C++/WinRT genealogy project goes well! Thanks again for getting in touch.
