### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Baitula** [MicrosoftDocs/windows-uwp#621]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2099ff76-43d5-98fd-d8bc-66ccdc14c4fe
* Version Independent ID: 1c3f3863-5413-d58b-a0e5-81a6da6bccf2
* Content: [Account types, locations, and fees - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by Baitula** [comment]
Good day

**Comment by Baitula** [comment]
Nice going

**Comment by ginami** [comment]
Hi @Baitula--thanks for your enthusiasm! If you have any feedback on our docs, please let us know. :)
