### ISSUE TITLE
Disable gamepad.

### ISSUE THREAD

**Issue by ZehCastro** [MicrosoftDocs/windows-uwp#622]
How should one setup the registry in order to temporarily disable a gamepad or map its inputs to NOPs?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53564e04-9a78-e495-6607-686634111ab8
* Version Independent ID: 6d4443f3-005f-d506-0e68-7f1f9e7fed23
* Content: [Registry data for game controllers - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/registry-data-for-game-controllers)
* Content Source: [windows-apps-src/gaming/registry-data-for-game-controllers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/registry-data-for-game-controllers.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @eliotcowley
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @ZehCastro, sorry for the late reply. I'll get in touch with the feature team and see if they can help with this.

**Comment by eliotcowley** [comment]
On the [Registry data for game controllers](https://docs.microsoft.com/windows/uwp/gaming/registry-data-for-game-controllers) doc, the first key listed, **Disabled**, will disable the game controller if set to 1. However, this is a very dangerous thing to do, because it disables the game controller for _all_ apps, so you have to remember to remove it. Additionally, this only affects apps that are using [Windows.Gaming.Input](https://docs.microsoft.com/uwp/api/Windows.Gaming.Input), or UWP apps using XInput. A safer way to do this would be to build the functionality into your input system.

Hope this helps--if you need further assistance, [Windows developer support](https://developer.microsoft.com/windows/support) is a good resource.

**Comment by ZehCastro** [comment]
Thanks, that does help.
It would be really helpful to include more examples of setups like this:
`https://docs.microsoft.com/en-us/windows/uwp/gaming/registry-data-for-game-controllers#example-registry-file`

**Comment by eliotcowley** [comment]
Unfortunately, they don't have any other examples to give me. Are you trying to add input support to your game controller? I can put you in touch with someone to help if so.

**Comment by james28909** [comment]
A developer in know that manages multiple other controller/device input projects has taken their time to help me figure out how to disable this for DS4 v1 controllers (ds4 v2 controllers, that have the light bar in the touch pad, don't have the issue of ui navigation input). This will disable v1 ds4 controller input in UWP apps (UI Navigation) like start menu and settings and MS store etc.

The developer that figured it out Is located here - https://steamcommunity.com/id/FirstPlato/ and here - https://forzatools.weebly.com/about.html

the developer is very knowledgeable and manages multiple projects regarding controller/device input and feedback. It is working great for me and works fine and doesn't require you to run a fix every time you reboot. It is a simple reg edit. And I REPEAT IT IS FOR DS4 v1 only (ds4 v2 doesn't have this issue).

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005]
"Disabled"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\Gamepad]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\Gamepad\UINavigation]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\Gamepad\UINavigation\PrimaryUp]
"AxisIndex"=dword:00000012
"Inverted"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\UINavigation]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GameInput\Devices\054C05C400010005\UINavigation\PrimaryUp]
"AxisIndex"=dword:00000012
"Inverted"=dword:00000001
```

just copy paste the code into a .reg file named whatever you want, like "ds4_ui_fix.reg" and run it. Then unpair and reboot and pair and try it out.
