### ISSUE TITLE
OS Version

### ISSUE THREAD

**Issue by kubakista** [MicrosoftDocs/windows-uwp#623]
From which OS version is this API available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42619a31-7175-4a29-98a6-7f6703b8c608
* Version Independent ID: 5a517293-5bd4-5b9f-7fd3-8938d402d5fb
* Content: [Device Portal remote input API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/uwp-remoteinput-api)
* Content Source: [windows-apps-src/xbox-apps/uwp-remoteinput-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/uwp-remoteinput-api.md)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @WilliamsJason

**Comment by kubakista** [comment]
Obviously available from 10.0.17134.3036.

I can establish WebSocket connection, however, I am not sure how to properly send a key.
I suppose I should send these bytes:

- 0x01 - KeyboardKeyCodes
- 0xCC - VK_GAMEPAD_DPAD_DOWN
- 0x01 - down press

but nothing happens.

**Comment by kubakista** [comment]
Problem solved. I was using `SocketMessageType.Utf8` instead of `SocketMessageType.Binary`.

**Comment by asamsonov** [comment]
Hi @kubakista, which port the websocket server is hosting?

**Comment by kubakista** [comment]
Hi, the same as Xbox Device Portal, 11443.
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal

**Comment by asamsonov** [comment]
I have updated the xbox up to 10.0.17134.3036
I turned it into dev mode
I am trying to open websocket connection using wss://console_ip:11443/ext/remoteinput
@kubakista, am I using the correct endpoint?
What library/tool do you use to setup connection and make calls?
