### ISSUE TITLE
mlgen with option CPPCX generates a C++/CX header file. The generated EvaluateAsync function seems to have bug and cause runtime crash.

### ISSUE THREAD

**Issue by brong-nvidia** [MicrosoftDocs/windows-uwp#628]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d3e62d2-0202-94ea-1725-7d00e5cf4360
* Version Independent ID: 5f11f7a5-d404-f904-07a8-81a44a95e5cc
* Content: [Windows ML overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/overview#feedback)
* Content Source: [windows-apps-src/machine-learning/overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/overview.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Hi @brong-nvidia! Are you able to provide more detail about the bug, such as the error message you're getting?

**Comment by brong-nvidia** [comment]
When MNIST_Demo "Recognize" button is pressed, the program exit without message.
The generated code is like this
`        ::Windows::Foundation::IAsyncOperation<CNTKGraphModelOutput^>^ EvaluateAsync(CNTKGraphModelInput^ input)`
`        {`
`            if (this->learningModel == nullptr) throw ref new Platform::InvalidArgumentException();`
`            ::Windows::AI::MachineLearning::Preview::LearningModelBindingPreview^ binding = ref new ::Windows::AI::MachineLearning::Preview::LearningModelBindingPreview(learningModel);`
`            CNTKGraphModelOutput^ output = ref new CNTKGraphModelOutput();`
`            binding->Bind("Input3", input->Input3);`
` `
`            binding->Bind("Plus258_Output_0", output->Plus258_Output_0);`
`            return ::concurrency::create_async([this, &binding, &output] {`
`                ::concurrency::create_task(this->learningModel->EvaluateAsync(binding, L""))`
`                    .then([](Windows::AI::MachineLearning::Preview::LearningModelEvaluationResultPreview^ evalResult) {});`
`                return output;`
`            });`
`        }`

I am not familiar with C#/CX, but I change the code like this to bypass the problem. Perhaps the wait() is the cure.
`		::Windows::Foundation::IAsyncOperation<CNTKGraphModelOutput^>^ EvaluateAsync(CNTKGraphModelInput^ input)`
`		{`
`			if (this->learningModel == nullptr) throw ref new Platform::InvalidArgumentException();`
`			return ::concurrency::create_async(
				[input, this] {`
`				::Windows::AI::MachineLearning::Preview::LearningModelBindingPreview^ binding = ref new ::Windows::AI::MachineLearning::Preview::LearningModelBindingPreview(this->learningModel);`
`				CNTKGraphModelOutput^ output = ref new CNTKGraphModelOutput();`
`				binding->Bind("Input3", input->Input3);`
` `
`				binding->Bind("Plus258_Output_0", output->Plus258_Output_0);`
`				auto taskEvaluate = ::concurrency::create_task(this->learningModel->EvaluateAsync(binding, L""));`
`				taskEvaluate.wait();`
`				return output; }`
`			);`
`		}`

**Comment by serenaz** [comment]
mlgen for CPPCX will be deprecated, but we'll be adding support for C++/WinRT, which should not have this issue.
