### ISSUE TITLE
Broken Link:  Overview of UWP Apps on Xbox One

### ISSUE THREAD

**Issue by FLY1NGSQU1RR3L** [MicrosoftDocs/windows-uwp#629]
This Page:  https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/index
Has as broken link in the "See Also" section for "Overview of UWP apps on Xbox One"
http://go.microsoft.com/fwlink/p/?LinkId=780786

Takes you to a placeholder page with this error:  Sorry, we couldn't find that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc0a5dcc-6984-5f19-7fa7-345e4b5247d3
* Version Independent ID: dfafa9b9-6d06-dcab-b90b-718f4ac04c7f
* Content: [UWP on Xbox One - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/index)
* Content Source: [windows-apps-src/xbox-apps/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/index.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mstahl**

**Comment by bartlannoeye** [comment]
Fixed by 0ba09cc96a137cef54370455a2e3ce2ee5e3a290, can be closed.
