### ISSUE TITLE
GATT Server documentation is outdated

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/windows-uwp#63]
The documentation at windows-uwp/windows-apps-src/devices-sensors/gatt-server.md is not accurate for the release version of the 15063 SDK.

Some property names have changed; the GattUuid class has disappeared and some other things have changed.

**Comment by mtbeaver** [comment]
Thanks for reporting this.  The documentation has been updated to correctly reflect the public API.

**Comment by hansmbakker** [comment]
Can you please also document the limitations of these APIs?

E.g. the hid service being protected was something I didn't know before you told me in #64. Are there any other things to keep in mind?

**Comment by hansmbakker** [comment]
@msatranjr why did you close this? The issue is not resolved; the limitations are not documented yet at e.g. https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-server

**Comment by msatranjr** [comment]
@wind-rider, I apologize for closing this issue without resolving. The documentation should be updated with a list of limitations. Please note that there is a slight delay in getting the change live on the [docs.microsoft.com topic](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-server). However, you can see the change right now by looking at the topic [here](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-server.md):

**Comment by hansmbakker** [comment]
@msatranjr Ok, thank you for updating the docs and for the clarification! :)
