### ISSUE TITLE
set the initial SelectedItem does NOT load the initial item in the content view

### ISSUE THREAD

**Issue by Licantrop0** [MicrosoftDocs/windows-uwp#631]
the code:
    foreach (NavigationViewItemBase item in NavView.MenuItems)
    {
        if (item is NavigationViewItem && item.Tag.ToString() == "home")
        {
            NavView.SelectedItem = item;
            break;
        }
    }
except from having an unnecessary for loop, because you can just do: NavView.SelectedItem = NavView.MenuItems[0];
does not work, because changing the selected item does not raise NavView_ItemInvoked, but rather NavView_SelectionChanged that is not handled anywhere in that code example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#overriding-the-default-adaptive-behavior)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
It's actually by design. The MenuItems could contain other NavigationViewItemBase items, such as separators, so we use the loop for clarity. If your MenuItems change dynamically, it might not be best practice to hard-code numbers. 

The code example handles UI clicks, which trigger ItemInvoked. Not every scenario requires handling SelectionChanged events, but feel free to add your own code!

**Comment by Licantrop0** [comment]
Hi @serenaz I agree that hard coding the initial item could be a potential issue, but the real problem here is that the code example does not display any NavViewItem on startup, as it looks like it should because it sets the selected item in NavView_Loaded

**Comment by serenaz** [comment]
Hmm what SDK do you have? The code example shows a selected item when I run it.
