### ISSUE TITLE
Consider updating to include app services

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/windows-uwp#633]
Windows 10 also includes the very awesome new app service concept. This allows a developer to make a "fleet" of apps that communicate with one another. That's the actual thing I was looking for when I read this page; I wanted to learn how to let my two apps communicate with each other.

This page mostly talks about user-driven app communication. And it would be better if there was a "shout out" to the app service documentation (see link)

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8738c14d-13a4-2b92-8ec0-905e29b608c7
* Version Independent ID: df07b727-06dc-b5f7-8339-723b0047f04a
* Content: [App-to-app communication - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/index?branch=live)
* Content Source: [windows-apps-src/app-to-app/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-to-app/index.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize that it took so long to respond. This is a great suggestion, and I added some pointers to the app services article in the article you commented on.
