### ISSUE TITLE
regarding additional system requirement page

### ISSUE THREAD

**Issue by gmshrikant** [MicrosoftDocs/windows-uwp#634]
regarding your tips
"Your additional system requirements will appear bulleted in your Store listing, so don't add your own bullets." where is "additional system requirements" page ? are you joking. my app process is pending for the same. and i didnot found this option on my dashboard.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2bdac6-993a-9cb5-0d20-d52c1d1970c2
* Version Independent ID: 5e31a6f0-c1bc-624c-ed5d-1e2a7845115a
* Content: [Create app Store listings - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/create-app-store-listings#feedback)
* Content Source: [windows-apps-src/publish/create-app-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-app-store-listings.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
There's not a separate page for "additional system requirements". If you enter any info in the "Additional system requirements" section in the "Store listing" step of your submission, that info will appear as part of the product's listing in the Microsoft Store for customers to see. If this doesn't fully answer your question, please let me know and I'll try to assist further.
