### ISSUE TITLE
Windows Template Studio Master/Detail sample link leads to 404

### ISSUE THREAD

**Issue by scout208** [MicrosoftDocs/windows-uwp#635]
If you try to select the Windows Template Master/Detail sample link near the bottom of the page in the **Get the Sample Code** section it will lead to a 404 Page Not Found page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c08f52-bf03-5e8b-d5f7-f9bdbb7ccc18
* Version Independent ID: b6159596-8168-1f9a-b8a8-343ab41950df
* Content: [Master/details - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/master-details)
* Content Source: [windows-apps-src/design/controls-and-patterns/master-details.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/master-details.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for the catch - it's fixed!
