### ISSUE TITLE
GamepadHome button

### ISSUE THREAD

**Issue by kubakista** [MicrosoftDocs/windows-uwp#636]
Is there a plan to support also GamepadHome button?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42619a31-7175-4a29-98a6-7f6703b8c608
* Version Independent ID: 5a517293-5bd4-5b9f-7fd3-8938d402d5fb
* Content: [Device Portal remote input API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/uwp-remoteinput-api)
* Content Source: [windows-apps-src/xbox-apps/uwp-remoteinput-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/uwp-remoteinput-api.md)
* GitHub Login: @WilliamsJason

**Comment by WilliamsJason** [comment]
Can you give sending the Windows key a try? I believe it will behave the same way:

VK_LWIN  --> 0x5B

**Comment by kubakista** [comment]
It works the same way.

It is just identified as "LeftWindows" virtual key on KeyDown/Up events.
Real "GamepadHome" cannot catch at all.
