### ISSUE TITLE
C++/WinRT: Concurrency & asynch ops doc includes a link to itself under "Related topics"

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/windows-uwp#637]
Relevant doc: [Concurrency and asynchronous operations with C++/WinRT](https://github.com/MicrosoftDocs/windows-uwp/blob/6607be1aa0e6a4895ccbe0d28a3fefabddcadae2/windows-apps-src/cpp-and-winrt-apis/concurrency.md)

This doc page includes a link to itself under "Related topics":

![image](https://user-images.githubusercontent.com/199935/40898043-a669a0b2-6773-11e8-8022-9aaac68bdd65.png)

Adam Comella
Microsoft Corp.

**Comment by stevewhims** [comment]
Thanks, Adam, good catch! I've removed that incorrect link and added 3 good ones to this topic and one other. Thanks again for the heads up! :) ~Steve. These changes should be live within 24 hours, so please close this issue once you're ready.
