### ISSUE TITLE
Windows ML COM APIs samples

### ISSUE THREAD

**Issue by brong-nvidia** [MicrosoftDocs/windows-uwp#638]
[Enter feedback here]
I expect some samples using Windows ML COM APIs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e948ad57-a6ec-1dde-197d-27911d9868e1
* Version Independent ID: c701d6c6-eee2-125a-749f-094475970356
* Content: [Windows ML samples - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/samples)
* Content Source: [windows-apps-src/machine-learning/samples.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/samples.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
The COM APIs are being deprecated in the next release, but we're working on Windows ML samples for C++/WinRT APIs.
