### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/windows-uwp#641]
Is it possible to localize these, like access keys without using XAML? So only in code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @SilverSilence, see https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md#specify-a-keyboard-accelerator.

You can localize accelerators using app resources: https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/prepare-your-app-for-localization.
