### ISSUE TITLE
The resource example is missing Invoked on ExecuteDelete

### ISSUE THREAD

**Issue by davefxy** [MicrosoftDocs/windows-uwp#642]
I believe the resource example is missing Invoked on the ExecuteDelete swipe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18985421-bd32-232a-a541-9857f2f6e328
* Version Independent ID: d4e8b58e-76d5-37c6-c121-c4d92bfcc101
* Content: [Swipe - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/swipe)
* Content Source: [windows-apps-src/design/controls-and-patterns/swipe.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/swipe.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi @davefxy , I believe the code you're looking for is in the XAML & C# code blocks right after the "Handle an invoked swipe command" header.
