### ISSUE TITLE
ES2015 Modules

### ISSUE THREAD

**Issue by AngelMunoz** [MicrosoftDocs/windows-uwp#643]
Hello, is "&lt;script type="module" src="main.js"&gt;&lt;/script&gt;" implemented in UWP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb02728-5f0a-bdc2-ee2d-1053ba6953ac
* Version Independent ID: 1d5b3dcf-db23-eb03-fdba-97ff2384e993
* Content: [Create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-js-uwp)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-js-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-js-uwp.md)
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Hi - thanks for your query.

Yes, this is supported. We’ve supported ES6 modules since EdgeHTML 16 / Fall Creators Update / Build 16299 / RS3

https://developer.microsoft.com/microsoft-edge/platform/status/moduleses6/?q=module

**Comment by AngelMunoz** [comment]
Thanks I must be doing something wrong then, because when I used module syntax for some reason the modules weren't loaded in the VS2017 debugger, But I will look further thank you!

**Comment by GrantMeStrength** [comment]
If you are blocked and can share a code sample, drop me a line: jken@microsoft.com

**Comment by tiagoshibata** [comment]
It doesn't work for me either. The script isn't loaded if `type="module"` is given.

**Comment by AngelMunoz** [comment]
@tiagoshibata be sure to include extensions like `<script type="module" src="./src/file.js"></script>` and also if you have any imports inside `file.js`, be sure these can resolve to a file also, because if those imports fail, your script will also fail, as a debugging tip try to comment imports until you find the guilty one 😝

**Comment by tiagoshibata** [comment]
My imports seem to always fail silently. I have an empty HTML page:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>TSImport</title>
    <link href="css/default.css" rel="stylesheet" />
</head>
<body>
    <div>Content goes here!</div>
    <script src="js/main.js" type="module"></script>
</body>
</html>
```

And two files, `main.ts`:

```typescript
import './imported'
(new Windows.UI.Popups.MessageDialog('Content', 'Dialog')).showAsync();
```

and `imported.ts`, which is an empty file. The include path seems correct (IntelliSense suggests this path and it's successfully transpiled into JS). Nothing happens if I run this project (no exception or message, and breakpoints in main.ts aren't hit). If I comment the `import './imported' line, it works.

Any suggestions?

**Comment by AngelMunoz** [comment]
@tiagoshibata the imports inside js files also need to include the extension and have to include the URL from the root page
`import '/js/imported.js'`, with typescript I haven't really tried but I guess it is a similar case

Also if there are imports inside the imported files that are not resolving, it will also fail silently as far as I have tested

**Comment by tiagoshibata** [comment]
I tried some variations (including `import 'js/imported.js'`) and they fail when transpiling to JS (it checks the import paths when transpiling and shows these as invalid). I'll try `import '/js/imported.js'` when I'm back in the office. I might give up and use plain JS if typescript is not working.

**Comment by AngelMunoz** [comment]
@tiagoshibata here are some samples I was working on, these are basically just boilerplates/templates [Angularjs](https://github.com/AngelMunoz/Angularjs-ES2015-UWP) and [WinJS](https://github.com/AngelMunoz/WinJS-ES2015-UWP)
perhaps these shed some light, also these are just javascript, no typescript sorry ☹️
