### ISSUE TITLE
Static Object Error

### ISSUE THREAD

**Issue by UncleChubby** [MicrosoftDocs/windows-uwp#644]
An object reference is required for the non-static field, method, or property "MediaElement.SetSource(RancomeAccessStream, string)

**Comment by ginami** [comment]
Hi @UncleChubby -- can you give me the URL for the relevant docs page for your feedback? Thank you!

**Comment by ginami** [comment]
Hi @UncleChubby. If you come up with a URL for this feedback, please let me know...I'm closing this issue for now. Thank you!
