### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/windows-uwp#645]
In the localization part, there's a typo in the closing XAML bracket.
Button.KeyAccelerators instead of Button.KeyboardAccelerators

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for finding this! Fixed.
