### ISSUE TITLE
Could you please be more specific about what WinRT and UWP stand for?

### ISSUE THREAD

**Issue by dimizuno** [MicrosoftDocs/windows-uwp#646]
I am very much confused. Are you officially replacing the term "Windows Runtime (WinRT)" with "Universal Windows Platform (UWP)"? There are some parts in the documentation where those terms are used interchangeably. Other article use them as distinct subjects. It looks like you are replacing the term WinRT in your documentation (e.g. the linked article). However, Microsoft developers are still referencing the Windows Runtime in recent videos or articles about topics like the C++/WinRT library for example. Could you please be more specific about what those terms actually stand for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10bcff1-93c7-ce94-87df-ef9d275df31f
* Version Independent ID: f5364ff6-579a-94bc-c75b-8e398f9b9ca1
* Content: [Universal Windows Platform Components and optimizing interop - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-runtime-components-and-optimizing-interop)
* Content Source: [windows-apps-src/debug-test-perf/windows-runtime-components-and-optimizing-interop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/windows-runtime-components-and-optimizing-interop.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
@derdimi, thanks for raising this, and you make a very good point! I've written an extra section about this question here: https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide#how-the-universal-windows-platform-relates-to-windows-runtime-apis. Please let me know whether that helps and/or whether I can add anything further. If it answers the query, then please close the issue when you're ready. Thanks! ~Steve

**Comment by dimizuno** [comment]
Thank you very much. I totally overlooked that last section. It actually confirms my latest assumption about what the difference is. Sorry for the typos, and keep up the good work. :+1:

**Comment by stevewhims** [comment]
Thanks, @derdimi! The section wasn't there before, I added it specially. :) But I forgot to update the "last-updated" date on the topic, so it probably gave the misleading impression that the section was there before, sorry about that! :) ~Steve
