### ISSUE TITLE
SDK Dependencies

### ISSUE THREAD

**Issue by harikvpy** [MicrosoftDocs/windows-uwp#647]
Section 2.3 mentions that Windows Hello apps should match the SDK version with that of the OS where it's deployed. It would've been nice if this was elaborated with its actual implications. For instance, does this imply that in production multiple versions of the app have to be distributed in the installer and and appropriate version chosen depending on the target OS version where it's being installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b178d625-6b36-0bfb-6944-31bd7c2dfef6
* Version Independent ID: 45a7d78c-d23a-9f9a-1b7e-83728a9032f8
* Content: [Windows Hello - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/microsoft-passport)
* Content Source: [windows-apps-src/security/microsoft-passport.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/microsoft-passport.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by hickeys** [comment]
I spoke with the engineering team and this does not seem to be true anymore. I've removed that paragraph; my updates should be published sometime today.
