### ISSUE TITLE
error: com.microsoft.edge.extension is a reserved extension type

### ISSUE THREAD

**Issue by interconverse** [MicrosoftDocs/windows-uwp#648]
After submitting the Extension Submission Form to receive permission to use the extension type nothing happens?  Here is the link provided by your documentation:  https://aka.ms/extension-request.  How long does it take to get permission to use the extension type (appx) so you can complete submission for the app store?  It's been a week.  Publisher account: CN=4A140261-4FA8-45CA-9769-A97C9B5C8CFD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0973c3-07c3-882e-46be-783dc13e575f
* Version Independent ID: 6877aae0-2aab-46f7-dd3a-16dd7d3bf842
* Content: [Resolve submission errors - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/resolve-submission-errors)
* Content Source: [windows-apps-src/publish/resolve-submission-errors.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/resolve-submission-errors.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I will look into this but first, I want to confirm - this is regarding publishing you confirm that you're requesting permission to publish a Microsoft Edge extension - is that correct?

**Comment by interconverse** [comment]
Yes, exactly.Sent via Brendan's cellphoneOn Jun 6, 2018 10:35 AM, JH <notifications@github.com> wrote:I will look into this but first, I want to confirm - this is regarding publishing you confirm that you're requesting permission to publish a Microsoft Edge extension - is that correct?
