### ISSUE TITLE
Target version mapping to available .NET Core/Framework/Standard

### ISSUE THREAD

**Issue by krh3o** [MicrosoftDocs/windows-uwp#651]
Where is the mapping of target version to .NET Core/Framework/Standard? For example, which Windows build will support this API:
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.close
The page says these are supported: .NET Core 2.1, 2.0; .NET Framework 4.7.2, 4.7.1, 4.7, 4.6.2, 4.6.1, 4.6, 4.5.2, 4.5.1, 4.5; .NET Standard 2.0; Xamarin.Android 7.1; Xamarin.iOS 10.8; Xamarin.Mac 3.0.

UWP target version isn't listed. So if I'm looking at an API, how do I know if a UWP target version will support it? Or if I'm looking at a UWP target version, how do I know which APIs are available? That mapping must be somewhere. I think it should be on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b95326-20b5-90f2-d9b2-c6e9fa305dee
* Version Independent ID: b4c6cf4b-5ead-095c-c660-94cb72857ae2
* Content: [Choose a UWP version - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version)
* Content Source: [windows-apps-src/updates-and-versions/choose-a-uwp-version.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/updates-and-versions/choose-a-uwp-version.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
To clarify, are you looking for the sort of information that's on this page?
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies

Or are you looking for specific information on which specific .NET APIs are available on which UWP versions? In that case, this page has information on .NET for UWP:

https://msdn.microsoft.com/en-us/library/windows/apps/xaml/mt185501(d=robot).aspx

And this page has information about which version of .NET Standard are available on which UWP version, which is relevant if you want to create reusable cross-platform libraries:

https://docs.microsoft.com/en-us/dotnet/core/tutorials/libraries

I'll make updates to this page to clarify this story - you're right that this is a good place to consolidate information about these different components. Thank you.

**Comment by krh3o** [comment]
The first link is exactly what I was looking for. Thank you! The other links will be very helpful too.

A lot of searching didn't lead me to those pages, so having a link to them on the "Choose a UWP version" page might be useful to others. Thanks!
