### ISSUE TITLE
Fix missing images

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/windows-uwp#653]
Currently, supposedly (linked) images are not shown. We see the markup syntax instead:

"![desktop to UWP bridge image](images/desktop-to-uwp/adaptive-ui.png)" (below "Reach all Windows devices")
"![Xamarin apps](images/desktop-to-uwp/xamarin-apps.png)" (below "Reach iOS and Android devices")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b431b0-4400-432b-43bd-c35a2dc39fc0
* Version Independent ID: 4c177b4c-2080-e691-f013-4a074f2dc9e2
* Content: [Share code between a desktop app and a UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-migrate)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-migrate.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-migrate.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you for raising this! I've fixed it and it will appear in the build very soon.

**Comment by normesta** [comment]
Ok - images now appear. Thank you!
