### ISSUE TITLE
File opencv_core310.dll has failed the AppContainerCheck check.

### ISSUE THREAD

**Issue by jiinus** [MicrosoftDocs/windows-uwp#654]
I tried to follow this tutorial and it seems to work fine when debugging, but when I try to create a package for Windows Store, Windows App Cert Kit fails saying that "File opencv_core310.dll has failed the AppContainerCheck check." WACK suggests to add linker options, which I added to the OpenCVBridge -project, but that didn't seem to make any difference. Any advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46cb9af7-d8dc-cc44-dbb2-d2b097f604ee
* Version Independent ID: cc2d4d5d-2698-299b-1e71-dae2a984f95b
* Content: [Process bitmaps with OpenCV - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-software-bitmaps-with-opencv)
* Content Source: [windows-apps-src/audio-video-camera/process-software-bitmaps-with-opencv.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/process-software-bitmaps-with-opencv.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
@jiinus, I'd recommend contacting Windows developer support (https://developer.microsoft.com/windows/support) for assistance.
