### ISSUE TITLE
Bad name of element in project file?

### ISSUE THREAD

**Issue by johanlindfors** [MicrosoftDocs/windows-uwp#656]
Documentation claims that a C++/WinRT project requires this:
&lt;CppWinRTProject&gt;true&lt;/CppWinRTProject&gt;
But when examining the actual project files, there are no such element in the file. There is however the following:
&lt;CppWinRTEnabled&gt;true&lt;/CppWinRTEnabled&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf7899f-689a-80c4-2c94-9575f8fc5055
* Version Independent ID: b8873e37-f4cb-de98-46f2-f2eaf01e275d
* Content: [Introduction to C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#sdk-support-for-cwinrt)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
@johanlindfors, yes that's a mistake on my part! Thanks for pointing out the error--I've fixed it and merged with master, so I expect the fix to show up on the live site within the next 24 hours.

**Comment by stevewhims** [comment]
This is fixed now, @johanlindfors. I'll go ahead and close. Thanks again for the heads up on this issue. ~Steve
