### ISSUE TITLE
Disambiguate guideline for App Icons & target-based assets and the use of Logo44x44

### ISSUE THREAD

**Issue by Fuzzel11** [MicrosoftDocs/windows-uwp#659]
At the section _Tile assets in list views_ there are guidelines for icons that are used in e.g. the "**All Apps List**", which are in the _Asset size table_ differently referred to as "**App List Icon**" only by reading the _Asset types_ its possible to connect the two terms to be referring to the same icon type.

There also seems to be some disambiguation about what the target-based assets are based off. At the section _Target-based assets_ an example of plated and unplated icons are given with a base size of 24x24 @ 100% yet further down at the _Asset size tables_, they are said to be based of **Logo44x44**, making it unclear what their real base size is (which also leaves open the question why its base size is 44x44 while having no targetsize of 44x44 listed in the _Asset size table_).
And only again through a thorough look through the _Asset types_ section it's possible to conclude that despite saying being based of **Logo44x44** it's not referring to the **App List Icon** of the same size and it's corresponding guidelines, but apparently merely coincidentally also 44p in square size and using the guidelines shown in the 24x24 example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac89746a-7629-6a95-6c5c-9498a9d7989f
* Version Independent ID: 044558cb-9f69-42df-362c-6c35317c3411
* Content: [Tile and icon assets - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/app-assets#tile-assets-in-list-views)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/app-assets.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/app-assets.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by hickeys** [comment]
This page seems to have been updated since you filed this issue. The content you refer to is no longer on the page. I'm going to close this issue. Please re-open if you feel there is still work to be done.

Thanks,
Shawn
