### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by BYTEzel** [MicrosoftDocs/windows-uwp#660]
The first example of the chapter "https://docs.microsoft.com/en-us/windows/uwp/get-started/fileio-learning-track#write-text-to-a-file" does not work at least with more current UWP builds.
Inserting it into a fresh project, I got a unknown COM error after 
// Open a stream for the selected file 
StorageFile file = await open.PickSingleFileAsync();

Turns out a file filter had to be set, e.g.:
FileOpenPicker open = new FileOpenPicker();
open.FileTypeFilter.Add("*");

After this it works. However, the error message is not particularly helpful as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3473005a-14ea-a674-453a-880c66f769c1
* Version Independent ID: 5439f25f-568b-5b12-d9f6-dd7e0253a927
* Content: [Work with files - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/fileio-learning-track#write-text-to-a-file)
* Content Source: [windows-apps-src/get-started/fileio-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/fileio-learning-track.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi,
I'm not sure which part of this topic you are referring to. There is no code example, in this topic, that matches what you provide:  StorageFile file = await open.PickSingleFileAsync();  Are you referring to another topic?

**Comment by BYTEzel** [comment]
Dear Tyler,

Thank you for your response. Sorry, something went wrong on my side, we can delete this for now.

**Comment by TylerMSFT** [comment]
No problem. Best wishes for your project
