### ISSUE TITLE
math libs

### ISSUE THREAD

**Issue by dr-pain** [MicrosoftDocs/windows-uwp#661]
What does UWP mean for those developers, who produce libs which don`t use WinAPI at all (or use small amount of it)? Where are lot examples in math libs area: netlib, mkl, ipp and etc.
How they may sure that their libs (static and dynamic) "UWP compatible" and customers (who use libs in win applications) will not be affected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88c23e09-bb75-8b8e-0950-cb872194f1aa
* Version Independent ID: b331b47e-2f61-b1b7-b889-1b7fbb0d31ce
* Content: [What's a Universal Windows Platform (UWP) app? - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment]
A library that limits itself to calling APIs that are available on all UWP devices should be UWP-compatible. For more info, see Win32 and COM APIs for UWP apps (https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-and-com-for-uwp-apps). SQLite (https://sqlite.org) is an example of a library that was ported (apparently it took only a matter of days to do so) to work with UWP apps (more info about SQLite and UWP, in case it's interesting, here: https://blogs.windows.com/buildingapps/2017/02/06/using-sqlite-databases-uwp-apps/#5Y4rQxKKJKUJOSZT.97).

**Comment by dr-pain** [comment]
Thank you for answer stevewhims!
My assumptions that it is question of which API is used in library was right.

Is any UWP API checker exist? Or can you point to any other official way to confirm that library is UWP complaint?

Andrey

**Comment by stevewhims** [comment]
Hi, Andrey, I'm afraid I'm not aware of any checker tool of that nature. However, one option is to ask the tools folks, perhaps at the Visual Studio Developer Community (https://developercommunity.visualstudio.com), or even Visual Studio's User Voice (https://visualstudio.uservoice.com) feedback website. Or, there's also Microsoft Support (https://support.microsoft.com/contactus/). Just some possible leads. Sorry that I don't know the answer.

**Comment by dr-pain** [comment]
stevewhims, anyway - thank you for your answers.

**Comment by OmPisit** [comment]
It is just an illusion. Thanks!
