### ISSUE TITLE
Append keyboard accelerator to Button object

### ISSUE THREAD

**Issue by tesar-tech** [MicrosoftDocs/windows-uwp#663]
`For AppBarButton and AppBarToggleButton objects, the keyboard accelerator is appended to the label.` -&gt; That is not true (due to my observation). 
- Keyboard accelerator is append to label in tooltip, not to Label. 
- It also works for Button class and MenuFlyoutItem class

It works for button class, but how can I append keyboard accelerator to existing tooltip in Button since there is no Label property as in AppBarButton?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators#feedback)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! I confirmed most of your findings and I've updated the topic to reflect this.
