### ISSUE TITLE
KeyboardAcceleratorPlacementMode property should be attached to Button

### ISSUE THREAD

**Issue by jlinstrum** [MicrosoftDocs/windows-uwp#665]
When I tried this on my own code, I was able to attach KeyboardAcceleratorPlacementMode property to the "Button" object, not the KeyboardAccelerator object as shown in the code snippet. I don't think the code snippet as shown would actually work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for catching this! I've fixed the snippet.
