### ISSUE TITLE
Content is incomplete for  "How to install Visual Studio so C++/WinRT works"

### ISSUE THREAD

**Issue by andrew7webb** [MicrosoftDocs/windows-uwp#666]
"Visual Studio support for C++/WinRT, and the VSIX" does not mention that you need the "C++ Universal Windows Platform tools" installed.  If you missed that, VS preview complains, creates files, but does not load the solution, so then the user runs into error messages when they try again.

Also, when I ran first time, VS brought up a Settings Dialog with "Sideload Apps" preselected.  It seems you must actually chose developer mode to function in VS.   So either the setting should default that way, or the documentation should prepare the user to change to the correct option.
I applaud the new documentation for C++/WinRT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf7899f-689a-80c4-2c94-9575f8fc5055
* Version Independent ID: b8873e37-f4cb-de98-46f2-f2eaf01e275d
* Content: [Introduction to C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#language-projections)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
@andrew7webb, thanks for the heads up on this missing info! I've just pushed a fix into master, and that should be live within the next 24 hours. Sorry for the omission; thanks for the shout out! :) ~Steve

**Comment by stevewhims** [comment]
The fix is now live. Please close the issue when you're ready. And thanks again for the heads up. ~Steve

**Comment by andrew7webb** [comment]
I did not see this behavior:

“If you haven't already installed it, you'll be prompted within Visual Studio to install the C++ Universal Windows Platform tools whenever you create or open a C++/WinRT, or other C++ UWP, project.”

 

Instead I saw an error, and then figured out I had to use the installer to fetch the C++ Universal Windows Platform tools.

So don’t let the user think they don’t need to install it manually before they create a project.



Universal Windows Platform development



Included

Blend for Visual Studio

.NE T Native and .NET Standard

NuGet package manager

Universal Windows Platform tools

Windows 10 SDK (10.0.17134.0)

 

Optional

USB Device Connectivity

  C++ Universal Windows Platform tools

 

 

Best regards, Andrew

**Comment by stevewhims** [comment]
I see, I've fixed that. Should be live within 24 hours! :)

**Comment by stevewhims** [comment]
@andrew7webb, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
