### ISSUE TITLE
Context question 

### ISSUE THREAD

**Issue by WiproSynnexDS** [MicrosoftDocs/windows-uwp#667]
Under - Which setting should I choose: sideload apps or Developer Mode?
Shouldn't it say "Windows Store Appsis the default setting" rather than "UWP apps is the default setting." ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35d7dc2-a5e9-9f86-7e8a-88e6afe40c99
* Version Independent ID: b57b8c51-e2f6-e5e1-1d93-14f26691bc39
* Content: [Enable your device for development - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Thanks for pointing this out - updates are needed to both the image and the text. They should now both read "Microsoft Store Apps." I'll close this issue when I can confirm the change is live.
