### ISSUE TITLE
Replace msdn link with docs link

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/windows-uwp#669]
The hyperlink for the control [toggle switch] throughout this document (same goes for property hyperlinks such as "IsOn", "OnContent",...) points to the old msdn site. I.e., for [toggel switch], the links points to "https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.toggleswitch.aspx". This should be replaced with the correct UWP docs link: "https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.toggleswitch"

(Please also update the property hyperlinks.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26382be5-2112-2fe1-cabe-acde81edbba7
* Version Independent ID: b800fb91-9f50-4af2-ed59-d343b54d5f83
* Content: [Guidelines for toggle switch controls - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles)
* Content Source: [windows-apps-src/design/controls-and-patterns/toggles.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/toggles.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Hi! The links should automatically redirect to the corresponding docs.microsoft.com pages, but I've gone ahead and updated the links. Should be live soon!
