### ISSUE TITLE
No official documentation on how to create own WebAccountProvider

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/windows-uwp#671]
Cross-reference to https://github.com/Microsoft/Windows-universal-samples/issues/911 since it is related to this Microsoft docs page.

There seems to be no sample how to create and register a custom WebAccountProvider.
There is a presentation from Microsoft Build 2015 that shows the concepts, but

- the code in the appendix is not complete
- the "tokenbroker" sample referenced from the presentation is not available anymore.

I found https://github.com/jaimerodriguez/WebAccountProvider/ but it would be good if that would be polished and maintained in the official Microsoft documentation as there is no other documentation about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c167684-f810-f987-5383-30fd7856a0c6
* Version Independent ID: d482e60b-b261-0db4-1c51-17db205a67d2
* Content: [Web Account Manager - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/web-account-manager#see-also)
* Content Source: [windows-apps-src/security/web-account-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/web-account-manager.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by hansmbakker** [comment]
@ginami @PatrickFarley @jillre @mcleblanc @msatranjr could you please give an update on how things stand? I see you had activity here several times; is there a chance this subject will be documented on Microsoft Docs?

**Comment by hickeys** [comment]
@hansmbakker I've created an internal tracking item in our bug database. That probably isn't the most satisfying resolution, but having this issue tracked there makes it easier to prioritize creating a sample, which will make it easier for me to allocate time to doing this work. Since this item is tracked internally, I'm closing this issue.

Thanks,
Shawn

**Comment by hansmbakker** [comment]
Thank you!

**Comment by hansmbakker** [comment]
@ginami @PatrickFarley @jillre @mcleblanc @msatranjr @hickeys is there any update on this?
