### ISSUE TITLE
Um...

### ISSUE THREAD

**Issue by matthew-dean** [MicrosoftDocs/windows-uwp#674]
This documentation doesn't answer the fundamental question asked in the title: "Where to get the Xbox Development Kit (XDK)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb73f8f9-ff29-d97b-9c25-cc00d362d052
* Version Independent ID: a07657b6-d371-6323-0e39-6829578dcc87
* Content: [Where to get the XDK - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-partner/where-to-get-xdk)
* Content Source: [windows-apps-src/xbox-live/get-started-with-partner/where-to-get-xdk.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/get-started-with-partner/where-to-get-xdk.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Thanks for the heads up! 
The page has been updated with information to lead you to the XDK and how to get it.
