### ISSUE TITLE
HttpClient to http://localhost:5000/ failed

### ISSUE THREAD

**Issue by vandenboreq** [MicrosoftDocs/windows-uwp#675]
Hi,

My problem is quite simple, I would like to interact with an ASP.NET service locally from my UWP application. Only I can not contact him. Do you have any information that there is network isolation?

Thank you all !

**Comment by ginami** [comment]
Hi @vandenboreq--it sounds like this may be a support issue. Or is this information that you expect to appear in a specific page of our documentation? Thank you!

**Comment by vandenboreq** [comment]
Hi @ginami -- I'm sorry, I will put this issue into Stackoverflow ! 
The information is still interesting in your documentation that said. Sorry again.

**Comment by ginami** [comment]
Hi @vandenboreq , no worries! Thank you!
