### ISSUE TITLE
Can't get a Microsoft Store ID key

### ISSUE THREAD

**Issue by MonneOnrust** [MicrosoftDocs/windows-uwp#678]
In step 4, while calling the StoreContext.GetCustomerCollectionsIdAsync method, the second parameter publisherUserId is not optional. And whatever I fill in, I either get an exception or an empty string as a result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bdee9e-2095-4423-62c5-0beb5520dfd3
* Version Independent ID: fad19d6f-2fa3-ff54-925a-020fe65cadbc
* Content: [Manage product entitlements from a service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're running into some problems. A couple of questions for you:
- What exception are you receiving?
- Are you passing in an empty string to the publisherUserId parameter? I'm assuming that by "optional", the article intends to say that you don't have to submit a real value here if you're planning to use this for your scenario, and I can clarify this in the article.
- For the serviceTicket parameter, can you confirm that you are passing an AAD token that you created with the https://onestore.microsoft.com/b2b/keys/create/collections audience URI? (see the details in [step 3](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-3-create-azure-ad-access-tokens)). There are several different audience URIs to use with different AAD tokens in this scenario, and it's important that you used the correct one for the collections API.

**Comment by MonneOnrust** [comment]
Thanks for answering. Here are my answers:

- If I put in null as argument, I get an ArgumentNullException. If I put in an empty string, I get an exception that the value is not valid.

- Whatever value I put in, I never get a valid key back. Always an exception or an empty string.

- I can confirm this.

**Comment by mcleanbyron** [comment]
What exception do you get if you pass in any real string value to the publisherUserId parameter?

I'm reaching out to the engineering team that owns this API to see if they have any details that can help.

**Comment by MonneOnrust** [comment]
I just get an empty string back in that case.


________________________________

**Comment by mcleanbyron** [comment]
To resolve your issue, I recommend that you use one of the developer support options at https://developer.microsoft.com/en-us/windows/support (this repo is for the docs, and isn't an official support channel). The information I have so far indicates that the docs are correct and I know that other developers have used this successfully in the past. However, I'm still following up with the engineering team to confirm and I will update this thread (and the docs as necessary) if I get some information from them that helps clarify things.

**Comment by mcleanbyron** [comment]
Hi there -

**Comment by mcleanbyron** [comment]
Hi there - If you still have access to the code you were trying, can you let me know what string you were passing to the publisherUserId parameter that resulted in getting back an empty string for the Windows Store ID key? I have finally confirmed with the engineering team that developers can't pass null or an empty string to this parameter, but apparently any string should work so they're very interested in knowing what string isn't working for you. In addition, if you could file a feedback bug in Feedback Hub after running your code, that would gather logs that could help with the investigation. 
In the meantime, I'm updating the docs to clarify that this parameter isn't optional and can't be null or an empty string. Thanks!

**Comment by MonneOnrust** [comment]
Hi, getting back the empty string was a fault of my own. I passed in the word 'Bearer' and then the token instead (like in filling an HTTP header) of just the token. I'm sorry for the confusion.

**Comment by mcleanbyron** [comment]
Thanks for the additional info, and I'm glad you were able to resolve the problem on your end.
