### ISSUE TITLE
TreeView Icons

### ISSUE THREAD

**Issue by jpcoates** [MicrosoftDocs/windows-uwp#679]
You say that icons can be added however I cannot find any examples on how to do this. How can this be done? I simply want to have an expanded and collapsed folder at the branch level and my own icon at the child level (level that no longer can be expanded).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba995b-8bf3-407c-7b87-015d22d813f1
* Version Independent ID: 52c553b6-e94d-2810-4123-8ee215b002bf
* Content: [Tree view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Kath118** [comment]
@jpcoates You can add it by creating a model for the template

```
<Page.Resources>
<DataTemplate x:Key="TreeViewItemDataTemplate">
            <Grid Height="44">
                <Image Source="{Binding Content.Image}"/>
                <TextBlock Text="{Binding Content.DisplayName}"/>
            </Grid>
        </DataTemplate>

        <Style TargetType="TreeView">
            <Setter Property="IsTabStop" Value="False" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="TreeView">
                        <TreeViewList x:Name="ListControl"
                                      ItemTemplate="{StaticResource TreeViewItemDataTemplate}"
                                      ItemContainerStyle="{StaticResource TreeViewItemStyle}"
                                      CanDragItems="True"
                                      AllowDrop="True"
                                      CanReorderItems="True">
                            <TreeViewList.ItemContainerTransitions>
                                <TransitionCollection>
                                    <ContentThemeTransition />
                                    <ReorderThemeTransition />
                                    <EntranceThemeTransition IsStaggeringEnabled="False" />
                                </TransitionCollection>
                            </TreeViewList.ItemContainerTransitions>
                        </TreeViewList>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </Page.Resources>
```

**Comment by thomas-yost** [comment]
This is an incomplete example and doesn't work as expected.  It doesn't replace the default image, it adds a new one.  In addition, the example should include code-behind to handle the three image states, open, closed, and no children.

**Comment by thomas-yost** [comment]
I'm seeing an issue with the default icons not working, using the Windows Insider Preview, that may require the same fix for this issue needs.
![treeviewiconissue](https://user-images.githubusercontent.com/28576593/49832345-7bb21900-fd3a-11e8-9399-d08b138a8bbd.png)

**Comment by jevansaks** [comment]
Thanks for reporting this issue! This turned out to be a regression on the OS side that we fixed recently. The fix should be in insider flights soon.

**Comment by thomas-yost** [comment]
This issue should not be closed.  The original complaint has not been addressed.  Three public properties should be added to the control to support specifying custom icons such as this:
![image](https://user-images.githubusercontent.com/28576593/49836821-385ea700-fd48-11e8-8448-07a7afc82c4a.png)

**Comment by YuliKl** [comment]
@thomas-yost this sounds like a feature request for the TreeView control. Now that Xaml controls are open source, the best way to track this request is directly in the [microsoft-ui-xaml](https://github.com/Microsoft/microsoft-ui-xaml) repo. Would you mind opening a new [feature request](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose) there?
