### ISSUE TITLE
Error in Step 4: Set up your MediaCapture initialization settings

### ISSUE THREAD

**Issue by jgilm** [MicrosoftDocs/windows-uwp#680]
The ClaimedBarcodeScanner class does not have a VideoDeviceId property neither does an instance of that class. Also _captureInitSettings.VideoDeviceId is set twice in that code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00c9dfa-5158-6336-70a9-d2ec101a4710
* Version Independent ID: b04ea381-64cd-27ff-1634-bc0a71b47e1f
* Content: [Hosting Preview for Camera Barcode Scanner - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-camerabarcode-hosting-preview)
* Content Source: [windows-apps-src/devices-sensors/pos-camerabarcode-hosting-preview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/pos-camerabarcode-hosting-preview.md)
* Product: **windows**
* GitHub Login: @TerryWarwick
* Microsoft Alias: **jken**

**Comment by TerryWarwick** [comment]
Thank you for the feedback.  Updating Step 4 sample to refer to the correct property of BarcodeScanner.VideoDeviceID and remove the duplication.  You should see this update shortly.
