### ISSUE TITLE
StartSoftwareTiggerAsync() needs to be called

### ISSUE THREAD

**Issue by jgilm** [MicrosoftDocs/windows-uwp#681]
It is not called out here or under Getting Started, however, I was not getting any DataReceived events until ClaimedBarcodeScanner.StartSoftwareTriggerAsync() was called. So now I do .EnableAsync() followed by .StartSoftwareTiggerAsync() and now I am getting DataReceived events. This should be called out somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00c9dfa-5158-6336-70a9-d2ec101a4710
* Version Independent ID: b04ea381-64cd-27ff-1634-bc0a71b47e1f
* Content: [Hosting Preview for Camera Barcode Scanner - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-camerabarcode-hosting-preview)
* Content Source: [windows-apps-src/devices-sensors/pos-camerabarcode-hosting-preview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/pos-camerabarcode-hosting-preview.md)
* Product: **windows**
* GitHub Login: @TerryWarwick
* Microsoft Alias: **jken**

**Comment by TerryWarwick** [comment]
Thank you for the feedback.  Will add step 8 to the Getting Started topic to indicate that you must call StartSoftwareTriggerAsync() to begin scanning.  You should see this update shortly.
