### ISSUE TITLE
Microsoft Store Error Code = 0x80D02017

### ISSUE THREAD

**Issue by Bodie37** [MicrosoftDocs/windows-uwp#682]
Just wanted someone to identify this error code
Microsoft Store -Not Updating Installing
Currently at 23 APPS waiting and getting bigger by the day
Only really noticed it when bought the game online AgeOfEmpires Definitive from Microsoft.
It refuses to install and like all the others refuses to go forward.
I have a good internet connection with no other IT issues
I have a ton of storage free too
Firewalls and Av disabled but still it will not budge
I have tried all the advice and it has changed nothing
Seems my only course now is to start again from scratch and reinstall after wiping the drives
Could try a restore point first and or a backup
Is this due to an update I wonder but when and which one.

Kind regards
M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f44d2980-5a12-3432-cc11-fe720f1ba770
* Version Independent ID: c5e52d67-bc02-cac7-9ca0-fabaaa47efce
* Content: [Error codes for Store operations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/error-codes-for-store-operations)
* Content Source: [windows-apps-src/monetize/error-codes-for-store-operations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/error-codes-for-store-operations.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Hello - I'm sorry you're encountering an issue installing apps/updates from the Store. The article you're commenting on is specifically about error codes that developers might encounter while they implement in-app purchases in their apps, and therefore it is out of scope for the issue you're encountering. For info about support options for Store issues like the one you're encountering, please visit [https://support.microsoft.com/en-us/products/microsoft-store](https://support.microsoft.com/en-us/products/microsoft-store).

**Comment by Bodie37** [comment]
Hello Sir

Thank you
I realise that but just thought it was worth asking as just banging my head
around on this one.

Take care

M
