### ISSUE TITLE
Hard to wrestle with

### ISSUE THREAD

**Issue by alporuban** [MicrosoftDocs/windows-uwp#683]
This facet of UWP needs an overhaul! Please streamline printing in UWP Apps. It's hard to get the content aligned properly while wrestling with Grid Rows and LinkedContainers. Printing via 'Microsoft Print to PDF' creates a perfect version of the document which also prints perfectly. Why not fix this? I currently have to ask the User to Print to PDF because in the App I was unable to get the output of my Page aligned properly - Gaps in the rows; print overflowing on the pages; not printing the entire report. Please fix!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889aad14-fbc7-84a8-a9a2-b08f97cd0f91
* Version Independent ID: 35f86ec0-f670-6724-85ac-349494e63cc0
* Content: [Print from your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app)
* Content Source: [windows-apps-src/devices-sensors/print-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/print-from-your-app.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Hi alporuban,
Thanks for your feedback. I'm going to reach out to some PMs who may have more insight into the issues you're experiencing.

**Comment by PatrickFarley** [comment]
Hi alporuban,
We are going to need some more detailed information about the bugs you're experiencing. Could you give us steps that will reproduce this unexpected layout behavior?

**Comment by mcleblanc** [comment]
Closing this due to the lack of activity. If we get more information, we can reopen this.
