### ISSUE TITLE
Good Explanation

### ISSUE THREAD

**Issue by JaDaar** [MicrosoftDocs/windows-uwp#684]
Usually MS doc is too academic, or has non-real world examples but this was very clear and easy to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83129a11-6821-456a-9fa0-59308e05b73c
* Version Independent ID: 0c95fe98-6605-3026-3224-f76c23557efb
* Content: [Layout panels for Universal Windows Platform (UWP) apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layout-panels)
* Content Source: [windows-apps-src/design/layout/layout-panels.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/layout-panels.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by ginami** [comment]
Hi @JaDaar -- thank you so much for your feedback!
