### ISSUE TITLE
Accelerator with Backspace & Enter

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/windows-uwp#688]
In my application the accelerator that uses VirtualKey.Back doesn't work. Is this intended, or is that Key reserved for other default behaviour? If so, can this be mentioned in the documentation? Also, if I have an accelerator that uses the Enter-Key but the focus is on a button (in the same UI), only the Button Click event is triggered. Can this behaviour be changed somehow, or do I have to override the button's keydown event handler?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @SilverSilence: Back button should be reserved for back stack navigation. You risk confusing your customers If you start changing standard behavior. Same for Enter. Always best to accept the built-in platform behaviors. That said, you can subscribe to the global Window.Current.CoreWindow.KeyDown event to override these behaviors.
