### ISSUE TITLE
Wrong variable

### ISSUE THREAD

**Issue by NPadrutt** [MicrosoftDocs/windows-uwp#689]
There seems to be a wrong variable for the store upload:

$(Build.ArtifactStagingDirectory)\
AppxPackages\MyUWPApp__$(AppxVersion)_x86_x64_ARM_bundle.appxupload

I get an error with that, that there is no package found.  According to the GitHub page it should be:  $(SYSTEM.ARTIFACTSDIRECTORY)\**\*.appxbundle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c024acf3-a58a-74c8-25b1-e5c88c85583a
* Version Independent ID: 81403e1d-947a-1f7d-f4b7-898105abd745
* Content: [Set up automated builds for your UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by NPadrutt** [comment]
I have to correct myself, there was another reason that the package was not found. In the end I used this path declaration:

$(Build.ArtifactStagingDirectory)\AppxPackages\*.appxupload

Also, in my case the identification via the name didn't work, so I had to use the ID.

**Comment by mcleanbyron** [comment]
Sorry for the late response, but it appears that you eventually resolved this issue on your own. Please feel free to reopen this issue if you believe there is still an unresolved problem with the article.
