### ISSUE TITLE
Using Add-on name

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#690]
I want to use the add-on name so it won't mistake to any other add-ons. I think the older Windows.ApplicationModel.Store will help me that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a81e5326-08dd-4558-549e-9854ab651307
* Version Independent ID: f90cf347-0df0-28f1-1752-567815608666
* Content: [Enable in-app purchases of apps and add-ons - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-in-app-purchases-of-apps-and-add-ons#code-example)
* Content Source: [windows-apps-src/monetize/enable-in-app-purchases-of-apps-and-add-ons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/enable-in-app-purchases-of-apps-and-add-ons.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. Please have a read through [this discussion in our docs](https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#how-to-use-product-ids-for-add-ons-in-your-code) if you haven't done so already - I think this directly addresses your concern. Assuming that by "add-on name" you're referring to the [product ID](https://docs.microsoft.com/en-us/windows/uwp/publish/set-your-add-on-product-id#product-id) that you enter in Dev Center for your add-on, this ID is still available via the newer Windows.Services.Store namespace (via StoreProduct.InAppOfferToken) as well as the older Windows.ApplicationModel.Store namespace. However, generally speaking the newer Windows.Services.Store APIs don't rely much on this ID; instead, all of the APIs in this namespace for triggering purchases and other operations use the Store ID of the add-on, which is a unique value generated by Dev Center.
