### ISSUE TITLE
Missing Semi-Colon

### ISSUE THREAD

**Issue by jcapellman** [MicrosoftDocs/windows-uwp#691]
Under the Querying the media libraries section, in the example it is missing a trailing semi-colon on:
queryOption.FolderDepth = FolderDepth.Deep

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17de106b-3ff1-091d-568e-fe80e07469c6
* Version Independent ID: be301fb5-d302-e06d-4bdd-5e857e02c3f2
* Content: [Files and folders in the Music, Pictures, and Videos libraries - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries#feedback)
* Content Source: [windows-apps-src/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
Thanks for the catch! I'll get this updated.
