### ISSUE TITLE
How to pick Videos, Pictures and Musics on another folder not KnownFolder?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/windows-uwp#692]
Thank for your document. I have follow this doc to access KnownFoler.
How to pick Videos, Pictures and Musics on another folder not KnownFolder? (Driver D:\ E:\)
Thank you!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 17de106b-3ff1-091d-568e-fe80e07469c6
* Version Independent ID: be301fb5-d302-e06d-4bdd-5e857e02c3f2
* Content: [Files and folders in the Music, Pictures, and Videos libraries - UWP app developer](https://docs.microsoft.com/vi-vn/windows/uwp/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries#get-a-reference-to-a-library)
* Content Source: [windows-apps-src/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by laurenhughes** [comment]
@nguyenthanhliemfc, UWP apps have some restrictions on how files can be accessed. If you're trying to access a file that's not in the [KnownFolders](https://docs.microsoft.com/uwp/api/Windows.Storage.KnownFolders) list, I'd recommend using the File Picker to open it. See the [Open files and folders with a picker](https://docs.microsoft.com/windows/uwp/files/quickstart-using-file-and-folder-pickers) topic for more info.
