### ISSUE TITLE
This submission failed with error code(s) 5001 . More info about the error(s) can be found here.

### ISSUE THREAD

**Issue by protogrid** [MicrosoftDocs/windows-uwp#693]
After clicking on "here" i got forwarded to: https://docs.microsoft.com/en-us/windows/uwp/publish/resolve-submission-errors.

I can't find any information concerning error 5001 there...

**Comment by JnHs** [comment]
This error occurs when one or more of the packages that you added in the submission is corrupt. You'll need to remove the newly added package(s), rebuild the app in Visual Studio, and upload the newly-created package(s). We'll update the error message to make this clearer, thanks for mentioning it!
