### ISSUE TITLE
Is there a WinJS implementation of swipe?

### ISSUE THREAD

**Issue by pantelisGeo90** [MicrosoftDocs/windows-uwp#695]
I was wondering if there is a WinJS implementation of this fantastic functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18985421-bd32-232a-a541-9857f2f6e328
* Version Independent ID: d4e8b58e-76d5-37c6-c121-c4d92bfcc101
* Content: [Swipe - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/swipe#how-does-swipe-work)
* Content Source: [windows-apps-src/design/controls-and-patterns/swipe.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/swipe.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@pantelisGeo90, no, there is not a WinJS implementation of the swipe controls. Sorry.
