### ISSUE TITLE
Affirmation button position

### ISSUE THREAD

**Issue by cimaja** [MicrosoftDocs/windows-uwp#696]
Have we done user research on the position of the primary/affirmation button. Windows is the only platform to recommend this while MacOS guidelines, iOS guidelines, Material guidelines and other large design system (IBM, Atlassian, Shopify...) are all recommending the opposite, and put the primary action on the right on Desktop and on Mobile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4822fcb-d3c5-06b1-10dd-dd56cc08df75
* Version Independent ID: e9b087b2-602b-1a3b-94ab-81489829510e
* Content: [Dialogs and flyouts - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/dialogs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/dialogs.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
At this point the expectation of "OK" being on the left of the dialog is fairly well cemented across the Windows ecosystem, so that's where this recommendation comes from.
