### ISSUE TITLE
Get Error when adding BookstoreViewModel Property to MainPage.idl

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#697]
This is the error i got when try to add the view model to mainpage.idl and rebuild

Error	MIDL2025	[msg]syntax error [context]: expecting &lt; near "MainViewModel"		

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4db0aab-b906-9dec-381c-ceccc1e90c45
* Version Independent ID: 493a4c50-ffa1-5e32-c757-92306c952887
* Content: [XAML controls; bind to a C++/WinRT property - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JK-IT, you'll need to add the "import "BookstoreViewModel.idl";" to MainPage.idl in order to resolve that error. That import IS in the code listing, but it's not obvious, so I'll make it clearer in the topic. Thanks for the heads up! :) -Steve

**Comment by ghost** [comment]
Thanks @stevewhims, it works for me. And i would like to add a tip that we should declare all classes in the same namespace. The error happenes when i try to fix by declaring a different  namespace.

**Comment by stevewhims** [comment]
Good point, @JK-IT, I've pushed new changes to the topic along the lines you recommend.

**Comment by stevewhims** [comment]
@JK-IT, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
