### ISSUE TITLE
Javascript Version

### ISSUE THREAD

**Issue by AngelMunoz** [MicrosoftDocs/windows-uwp#701]
Will there be a javascript version of this? 
I tried to look for this API with the Visual Studio 2017 intellisense but I was unable to get it
with the Empty AppTemplate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9554b9f2-2f49-1833-1143-0103c18c37c8
* Version Independent ID: ef28f9ce-bd72-0435-6238-95d574eabee1
* Content: [Create a multi-instance Universal Windows App - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi Angel,
Multi-instancing works with Javascript/WWA apps. You'll need the manifest attribute:

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:desktop4="http://schemas.microsoft.com/appx/manifest/desktop/windows10/4"
  IgnorableNamespaces="uap mp desktop4">
…
    <Application 
      Id="App"
      StartPage="index.html"
      desktop4:SupportsMultipleInstances="true">

Multi-instancing redirection does NOT work with WWA.

**Comment by TylerMSFT** [comment]
The commenting system consumed the attribute I tried to paste. See the topic regarding desktop4:SupportsMultipleInstances="true"

**Comment by AngelMunoz** [comment]
Thanks @TylerMSFT , I did try what you said. I'm going to try again and publish a sample repo in case I can't make it work

**Comment by AngelMunoz** [comment]
@TylerMSFT 
I've done the XML part
but most likely what I don't fully get is how to do this part
```cs
 // First, get a list of all running instances of this app.
instances = AppInstance.GetInstances();
// Next, we'll get our rich activation event args.
IActivatedEventArgs activatedArgs = AppInstance.GetActivatedEventArgs();
```
When I try to check on the Javascript version I don't find any information related to Appinstance

on a recent try I even got this warning in the console
![not attaching](https://i.imgur.com/joOQobf.png)
this is a new clean app with the javascript empty template
you can check my repro case here (https://github.com/AngelMunoz/multi-instance-uwp-js-repro)

**Comment by stevewhims** [comment]
Hi, @AngelMunoz, apologies for the delay in responding. This feels like a support issue rather than a documentation issue. I'll pass along your repro case to the product team, and I'll reopen this issue if there turns out to be anything that I can do to improve the docs here.

Some other options: the [Windows developer feedback site](https://wpdev.uservoice.com) is the right place to file a product bug; the [Developer Community](https://developercommunity.visualstudio.com); for issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a product bug or something else.

~Steve

**Comment by AngelMunoz** [comment]
Thanks @stevewhims Should it be noted in the documentation that there doesn't seem to be support for javascript apps yet?

in any case, I will try the other options provided

**Comment by stevewhims** [comment]
If that turns out to be the case, then I'll definitely fix the docs (and/or the failure to support JavaScript will be fixed). I'm sending a link to this issue to the product owners, and I'll await their instructions. Thanks, @AngelMunoz! ~Steve

**Comment by stevewhims** [comment]
Hi, @AngelMunoz, it seems that the answer was actually given in the thread above, although it's very easy to miss, and it didn't make its way into the documentation.

Multi-instancing is supported for JavaScript applications, with the exception of multi-instancing **redirection** (which is NOT supported for JavaScript applications). Therefore, for JavaScript applications, the AppInstance API is not useful, and this explains why it's not working for you. I'll update this topic immediately; the fix should be live within the next 24 hours.

~Steve

**Comment by AngelMunoz** [comment]
ah I see, thank you! I also made a support question here
https://developercommunity.visualstudio.com/content/problem/339674/multi-instance-javascript-uwp-app.html

However would it be too much to ask for a javascript sample? I find it a bit confusing
Thank you for your support @stevewhims !

**Comment by stevewhims** [comment]
AFAIK, we don't plan to add a JavaScript sample at this time. But I'll pass your ask along to the product team. ~Steve

**Comment by AngelMunoz** [comment]
I understand, thank you
