### ISSUE TITLE
`(string)args.InvokedItem)` may not work

### ISSUE THREAD

**Issue by liushigit** [MicrosoftDocs/windows-uwp#702]
`args.InvokedItem` should be a `NavigationViewItemBase` or `NavigationViewItemBase` . Is the cast to `string` feasible? Following is the snippet from the doc.

     var item = sender.MenuItems.OfType&lt;NavigationViewItem&gt;().First(x =&gt; (string)x.Content == (string)args.InvokedItem);
     NavView_Navigate(item as NavigationViewItem);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by Licantrop0** [comment]
Yes, it is feasible as long as the content is actually a string.
Anyway, here a fix that will use the Equals operator to avoid unnecessary casts:
https://github.com/MicrosoftDocs/windows-uwp/pull/705/files
