### ISSUE TITLE
x86 on arm ?

### ISSUE THREAD

**Issue by frednora** [MicrosoftDocs/windows-uwp#703]
Thanks you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9178a8-79f8-e100-a216-a1b28c6879a4
* Version Independent ID: c8c5483f-c303-5b15-544e-a104c4d51303
* Content: [How x86 and ARM32 emulation work on ARM - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm-x86-emulation)
* Content Source: [windows-apps-src/porting/apps-on-arm-x86-emulation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm-x86-emulation.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by ginami** [comment]
Thank YOU, @frednora -- let us know if you have a specific question or comment about this page.
