### ISSUE TITLE
C# code in Recording.cs Getting Error

### ISSUE THREAD

**Issue by kevinb67** [MicrosoftDocs/windows-uwp#704]
I copied the C# code in Recording.cs from the document article as well as the markup language in the MainPage.xaml page. I tried to build and debug the solution and got the following message:

Inconsistent accessibility: property type 'Recording' is less accessible than property 'RecordingViewModel.DefaultRecording'

The problem appears to be in this code:

public class RecordingViewModel
    {
        private Recording defaultRecording = new Recording();
        public Recording DefaultRecording { get { return this.defaultRecording; } }

    }

How can I fix this error? Thanks.   Kevin` B., kdb67@bellsouth.net
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9fdf72e-8eaa-1e01-9b9c-d1c5e506117d
* Version Independent ID: 45f0e7ae-662c-29fb-8171-9674f7bbde15
* Content: [Data binding overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart)
* Content Source: [windows-apps-src/data-binding/data-binding-quickstart.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/data-binding-quickstart.md)
* Product: **windows**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by jwmsft** [comment]
@kevinb67, this error happens if you don't make the Recording class public. By default, when you add a new class file in Visual Studio, it doesn't make the class public, so the code it generates looks like this:

```
class Recording
```

You have to add 'public' to it, as shown in the code in the article:

```
public class Recording
```

That should resolve the error.
