### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by gandarez** [MicrosoftDocs/windows-uwp#707]
Should be: "Tutorial: Create an user interface"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc1c132-3cfa-1a08-0726-214110c8d23d
* Version Independent ID: 7ddf3871-c4a1-ae0a-9c03-25ccf4934cf2
* Content: [Create a user interface tutorial - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-ui#feedback)
* Content Source: [windows-apps-src/design/basics/xaml-basics-ui.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-ui.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@gandarez, thanks for the feedback. In this case, because the 'u' in 'user' makes the sound of the letter 'y', it's actually correct to use 'a' instead of 'an'. Here are some links for more information: https://owl.english.purdue.edu/owl/resource/591/01/
https://www.grammar.com/a-vs-an-when-to-use/
