### ISSUE TITLE
your escape character is showing

### ISSUE THREAD

**Issue by kwiqniss** [MicrosoftDocs/windows-uwp#708]
&lt;folder&gt; should be &lt;folder&gt; in the section for fixing pe header files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c403f296-ed93-2625-e414-f009194bf118
* Version Independent ID: aa0212c4-481c-7eaf-233d-c5b3f286d004
* Content: [Package an app using the Desktop App Converter (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-run-desktop-app-converter.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-run-desktop-app-converter.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you for finding this! I've updated the doc and the change should appear live tomorrow.

**Comment by normesta** [comment]
Ok Fixed now. Closing issue. Thanks again!
