### ISSUE TITLE
Set up the audio feed

### ISSUE THREAD

**Issue by lisaweixu** [MicrosoftDocs/windows-uwp#709]
About "Set up the audio feed", turn on the microphone in the manifest is not enough. Users has to allow the app to access the microphone from 
setting-&gt;privacy-&gt; Choose which apps can access your microphone. 

If the user has not done that, WASAPI audio client gives weird response of format not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b1f9e3-1f19-d3f3-368f-396a1c4f918e
* Version Independent ID: a68fdcb7-a20f-87cb-711a-47254e0b233a
* Content: [Speech recognition - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/speech-recognition#feedback)
* Content Source: [windows-apps-src/design/input/speech-recognition.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/speech-recognition.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @lisaweixu - thanks for the feedback! I've updated the topic to include more detail on your concerns.
