### ISSUE TITLE
code doesn't compile nor run on composition/lighting. 

### ISSUE THREAD

**Issue by crutkas** [MicrosoftDocs/windows-uwp#710]
When using the FancyOrangeSpotLight, it doesn't work on https://docs.microsoft.com/en-us/windows/uwp/composition/lighting.  If i try the doc from https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.xamllight it works.

Near identical code but xamllight doc seems to be functional and the lighting doc doesn't

**Comment by jwmsft** [comment]
@crutkas, thanks for pointing this out. The example on the composition/lighting page has been updated and should be working now.
