### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rchoudhary** [MicrosoftDocs/windows-uwp#711]
`&lt;!—Dictionary2.xaml --&gt;`

should be 

`&lt;!-- Dictionary2.xaml --&gt;`

so that syntax highlighting treats it as a comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6822f33-819b-ae6f-95cd-04861fa46dca
* Version Independent ID: 12e5988d-2aa1-0284-4f75-3b0cfb17177c
* Content: [ResourceDictionary and XAML resource references - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references)
* Content Source: [windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks. This is fixed.
