### ISSUE TITLE
Sample for paired GATT Server

### ISSUE THREAD

**Issue by greyghostbrewery** [MicrosoftDocs/windows-uwp#712]
Can you please provide a sample for a GATT server that requires pairing in order to read/write to its characteristics - or a sample that implements some level of security?  At present it appears there is no security available for GATT servers, as any BLE client can read/write to the published characteristics.

My knowledge of BLE is fairly limited, but it doesn't seem right that you can only create a BLE GATT server where any client within range can access its characteristics.  While this makes sense for certain scenarios, I have a requirement to have a protected GATT server that can be accessed by authorised clients only.

I am aware of the GattProtectionLevel enum, however the documentation on this is almost non-existent and I cannot get anything working unless I use "Plain".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43664026-c784-e891-bdec-3102f48ade77
* Version Independent ID: 4629d3c4-d850-d456-efe5-ba4c1d61c21b
* Content: [Bluetooth GATT Server - UWP app developer](https://docs.microsoft.com/en-au/windows/uwp/devices-sensors/gatt-server)
* Content Source: [windows-apps-src/devices-sensors/gatt-server.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-server.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by greyghostbrewery** [comment]
Is anyone monitoring the comments on this article?

**Comment by mtbeaver** [comment]
When creating a Characteristic or Descriptor, you do set the GattProtectionLevel as you alluded to in your question.  There is a property for both Read and Write permissions for each attribute as well.  Once set, the Bluetooth stack will enforce the requirements on all incoming operations, replying back to the remote device with the appropriate access error code if the link requirements do not match what was specified when the characteristic or descriptor was created.

The properties represent the minimum security level required to perform the operation. We do not have samples available though at this time that demonstrates it.

**Comment by Karl-Bridge-Microsoft** [comment]
Question answered. No samples planned at this time.
