### ISSUE TITLE
Device Family

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#716]
Is RemoteSystemSessionController works with Windows 10 IoT Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98d6519e-4d2e-2fee-0a0b-546d2db8d183
* Version Independent ID: f46543c5-a76f-1a86-12c0-c39d24104dfc
* Content: [Connect devices through remote sessions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/remote-sessions)
* Content Source: [windows-apps-src/launch-resume/remote-sessions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/remote-sessions.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Hi superkid200,
No, Windows 10 IoT Core does not currently support Remote Sessions or other Project Rome features.

**Comment by dongle-the-gadget** [comment]
How about phones?
