### ISSUE TITLE
some docs lost

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windows-uwp#718]
The issue was created by @CaliforniaChao from https://github.com/MicrosoftDocs/feedback/issues/470
At the end of the page, "Encode a metadata stream“ part does not exist. This looks like a un complete document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ff303e3-1cf5-0dee-be29-837bb7c3679b
* Version Independent ID: 12c9a101-4e72-4385-8228-7deb0ad36241
* Content: [Transcode media files - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/transcode-media-files#encode-a-metadata-stream)
* Content Source: [windows-apps-src/audio-video-camera/transcode-media-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/transcode-media-files.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback. Transcoding metadata is not supported for this API, so this section of the documentation has been removed.
