### ISSUE TITLE
Format and details for caution

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/windows-uwp#719]
"Caution  An existing limitation of the Windows Runtime XAML implementation is that you cannot animate your custom attached property."

Isn't it more useful if you put this in a dialog with red background, similar to how info dialogs have a blue one?
"You cannot animate your custom attached property". Does this mean you cannot set it through a style? I tested on my side and this was the case. If this is true, can you add this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369c139c-69a6-8817-5cb2-6e93d64d8cce
* Version Independent ID: 6feed647-1cd1-8971-eb36-f14aaccad151
* Content: [Custom attached properties - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-attached-properties#registering-a-custom-attached-property)
* Content Source: [windows-apps-src/xaml-platform/custom-attached-properties.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/custom-attached-properties.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@julienshepherd, thanks for the feedback. The 'caution' notes in this section were left over from the automated conversion of the old docs to markdown. I've updated them to use the 'warning ' block with the red background.

The note means you can't use a custom attached property in a Storyboard, like you would use in a VisualStateManager. 

You can, however, set it in a Style. The example for [Composition lighting](https://docs.microsoft.com/windows/uwp/composition/lighting) uses a custom attached property. You can modify that example to add a Style resource to the page, like this:
```
    <Page.Resources>
        <Style TargetType="Border" x:Key="OrangeLightStyle">
            <Setter Property="local:OrangeSpotLight.IsTarget" Value="True"/>
        </Style>
    </Page.Resources>
```

Then apply the Style like this:

```
    <Border BorderThickness="4" BorderBrush="PaleGreen" Margin="2"
            Style="{StaticResource OrangeLightStyle}">
        <Rectangle Fill="LightGray" Height="20"/>
    </Border>
```
