### ISSUE TITLE
Minimized application on GraphicsCapturePicker selection does not work as expected

### ISSUE THREAD

**Issue by oliverluethi** [MicrosoftDocs/windows-uwp#720]
Hi there

I'm working with the new GraphicsCapturePicker in our UWP application. We're trying to capture a screenshot from a selected application. 

Code was taken form this sample: [Sample](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)

If the application stays minimized during the selection and capturing process, no canvasBitmap is created.
Is it possible to activate the application on selection to make sure the capturing process is working as expected, or is there any workaround for this?

**Comment by eliotcowley** [comment]
Thanks for the feedback, @oliverluethi. I also noticed that the bitmap is not created when the picked app is minimized, you have to actually have it open. I'll check with the feature team and see what they say.

**Comment by eliotcowley** [comment]
Hi @oliverluethi, unfortunately it looks like there's no workaround for this at the moment. However, this might change in the future, and I'll be sure to update the documentation if it does.
