### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by ibadullah** [MicrosoftDocs/windows-uwp#721]
https://docs.microsoft.com/en-us/api/windows.ui.xaml.media.animation.navigationtransitioninfo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70caee7e-f3f7-a156-a0a2-bc39f304cbdc
* Version Independent ID: 00714360-83d8-554f-e4c2-c66926e270fb
* Content: [Page transitions in UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/motion/page-transitions)
* Content Source: [windows-apps-src/design/motion/page-transitions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/page-transitions.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Fixed - thanks for noticing!
