### ISSUE TITLE
Is there should be use the C++/WinRT instead of the C++/CX for the samples?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-uwp#723]
Hi all,
I want to create the DLL by use the C++/WinRT, but there is only the C++/CX within the topics. Is there should be update the docs by use the C++/WinRT for the topics or where to find the samples about how to create DLL use by the C++/WinRT?

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b317978e-12a2-09ab-ca25-33835878d538
* Version Independent ID: c654c9f0-4813-8b88-e2fc-4636612fba36
* Content: [Windows Runtime components - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/)
* Content Source: [windows-apps-src/winrt-components/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/index.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by techjogger** [comment]
I second this request!

**Comment by stevewhims** [comment]
Hi, @moyanming (and others). Thanks for filing this issue, and I'm very sorry for the extremely long delay in responding to it.

To learn how to create a Windows Runtime component using C++/WinRT, see [Author events in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-events).

I'll go ahead and close this issue, but please reopen if it you feel I'mve close it in error.

Thanks!
Steve
