### ISSUE TITLE
The Back Button code examples don't compile

### ISSUE THREAD

**Issue by JustinMinnaar** [MicrosoftDocs/windows-uwp#727]
It is unclear what your writer intended, as the back button code example does not compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab5201c-d8c8-1804-a225-4420f66d77ea
* Version Independent ID: 2d217eac-b2cd-553a-970f-32bb043fc353
* Content: [Navigation history and backwards navigation (Windows apps) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for raising the issue! `On_BackRequested()`  can handle system-level `BackRequested` events or page-level back button `Click` events, depending on how and where you want to handle backwards navigation. We'll update the code example to clarify.
