### ISSUE TITLE
Efficient article

### ISSUE THREAD

**Issue by EmmanuelDURIN** [MicrosoftDocs/windows-uwp#728]
To be fixed : The await call to RestoreAsync can't be done in an async way in the constructor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d156d985-2791-6521-331c-8d5ac9283f0e
* Version Independent ID: 794ddc4b-6660-8008-29fd-d4b696541b87
* Content: [Display a splash screen for more time - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-a-customized-splash-screen)
* Content Source: [windows-apps-src/launch-resume/create-a-customized-splash-screen.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-a-customized-splash-screen.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here as changes have been made to the doc in question since the creation of the Issue. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
