### ISSUE TITLE
Mistake in tutorial: opposite AdaptiveTrigger behaviour

### ISSUE THREAD

**Issue by csorbakristof** [MicrosoftDocs/windows-uwp#729]
I believe the &lt;AdaptiveTrigger MinWindowWidth="640" /&gt; above sets the layout into a single column exactly in the wrong case: when the window would be wide enough for the original layout.

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 80b47dbb-38b5-9d75-8df2-2300cdc25bb7
* Version Independent ID: b204d881-3ca4-a7bb-87c3-0e91df704637
* Content: [Learning track - Construct and configure a form - UWP app developer](https://docs.microsoft.com/hu-hu/windows/uwp/get-started/construct-form-learning-track)
* Content Source: [windows-apps-src/get-started/construct-form-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/construct-form-learning-track.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
You're correct - the code has since been changed to default to a single column, and adjust to a multi-column layout when the conditions are appropriate.
