### ISSUE TITLE
What does it mean "active license" for an add-on?

### ISSUE THREAD

**Issue by toncho11** [MicrosoftDocs/windows-uwp#730]
Does it mean that the user has already bought the add-on? "active" = "already purchased" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6876f5-833c-935e-2fad-bc1cdb9df995
* Version Independent ID: e13e512a-27f3-f55f-e2bc-2e4e5f101009
* Content: [Get license info for your app and add-ons - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-license-info-for-apps-and-add-ons)
* Content Source: [windows-apps-src/monetize/get-license-info-for-apps-and-add-ons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-license-info-for-apps-and-add-ons.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I confirmed with the engineering team that currently the StoreAppLicense.IsActive property simply means that the app is running with a valid/well-formed license issued from the Store. It doesn't really indicate anything beyond that. For example, even if the current user has an expired trial license, the IsActive property will still return true.
