### ISSUE TITLE
Clarify which platforms/DirectX versions support DirectCompute.

### ISSUE THREAD

**Issue by trojanfoe** [MicrosoftDocs/windows-uwp#731]
I think you need to clarify what platforms and versions of DirectX support DirectCompute.  I believe DirectCompute is not supported on Xbox One UWP apps using DirectX 11, however I am unsure if DirectX 12 on Xbox One supports it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64fd63b-677f-e342-f076-9f8fbd192bc3
* Version Independent ID: 8b4b643a-24b7-1dcc-204e-e0ee4b1e68e8
* Content: [Compute Shader (CS) stage - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/graphics-concepts/compute-shader-stage--cs-)
* Content Source: [windows-apps-src/graphics-concepts/compute-shader-stage--cs-.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/graphics-concepts/compute-shader-stage--cs-.md)
* Product: **windows**
* GitHub Login: @michaelfromredmond
* Microsoft Alias: **mithom**

**Comment by ginami** [comment]
Hi @trojanfoe--thank you for your feedback. I'm working on finding the right author to respond. :)

**Comment by ginami** [comment]
Hi @mtoepke -- can you answer this question? Thank you!

**Comment by maxonk** [comment]
bump

**Comment by mtoepke** [comment]
Hi @trojanfoe ,

Thanks for your question.

UWP on Xbox One apps (non-games) do not support DirectX 12.

UWP on Xbox One apps or games, when using DirectX11, use Feature Level 10.0 without DirectCompute.

UWP on Xbox One games, submitted through the Xbox Live Creators program (or ID@Xbox), support DirectX 12 with Feature Level 12.0 and DirectCompute.

See these articles for more information:
https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/system-resource-allocation
https://blogs.msdn.microsoft.com/chuckw/2017/12/15/directx-and-uwp-on-xbox-one
https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/get-started-with-xbox-live-creators

Thanks!
