### ISSUE TITLE
The docs of the "Author events in C++/WinRT" should be update.

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-uwp#732]
For example:
According to the [Create a Windows Runtime Component (BankAccountWRC)](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events#create-a-windows-runtime-component-bankaccountwrc) , there are no Class.h and Class.cpp after rename the Class.idl to the BankAccountWRC.idl, but there are BankAccountWRC.h and BankAccountWRC.cpp appear.

Is there samples about how to reference the C++/WinRT component from the C# project?

Best regards.
![qq 20180629184600](https://user-images.githubusercontent.com/13234209/42092068-2450e6a0-7bda-11e8-8108-0e752037f966.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf411b4-9c85-5831-c425-a009d47811e7
* Version Independent ID: 3d0dc3b5-a7da-2755-0a9e-599f39a51acd
* Content: [Author events in C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-events.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thank you, @moyanming, I have corrected the errors in the topic and the fix should appear on the live site next week. Thanks for letting me know about the errors! I will also take an action point to add some content somewhere showing how to consume a C++/WinRT Windows Runtime Component from a C# project. Until then, here's how to do it. You reference the winmd from the C# project in exactly the same way that this topic describes how to reference the winmd from a C++/WinRT project. Then, here's some code showing how to exercise the component from XAML markup and C#:

Add a button to MainPage.xaml:
<Button Click="Button_Click"/>

Make your MainPage class look like this (in MainPage.xaml.cs):

    public sealed partial class MainPage : Page
    {
        BankAccountWRC.BankAccount bankAccount = new BankAccountWRC.BankAccount();

        public MainPage()
        {
            this.InitializeComponent();

            bankAccount.AccountIsInDebit += BankAccount_AccountIsInDebit;
        }

        private void BankAccount_AccountIsInDebit(object sender, float e)
        {
            System.Diagnostics.Debug.Assert(e < 0);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            bankAccount.AdjustBalance(-1);
        }
    }

**Comment by stevewhims** [comment]
```xaml
<Button Click="Button_Click"/>
```

**Comment by stevewhims** [comment]
Sorry, the xaml was stripped out by the editor but there it is above. :)

**Comment by moyanming** [comment]
Hi @stevewhims,
Yes, I can consume the C++/WinRT component API from the C# UWP APP by add the reference now, which is the same way as the C++/WinRT Core App project does.

But I found that I need repeat copy of the stubs every time and rebuild after I add new public APIs into the idl file. Or, it is a better way that just copy the defination lines from the stubs, because copy and replace will lose code. It is a little bit complicated.

Any idea about how to port a large nunmber of the C code to the C++/WinRT component? It seems that I must implement a C++ class at least.

Best regards.

**Comment by stevewhims** [comment]
@moyanming, you're right that some work with the stubs is necessary. Copying and replacing a generated stub file into your project is only the right thing to do the first time the stubs are generated. After that, as you say, you'll have implementation code in your project's copy of the stub file, so you won't want to copy and replace at the file level. What's necessary here is, as you say, to copy just the newly-generated class members over from the generated stub file into the copy that's in your project. Basically, each time you change your IDL file (except for the first time), then you'll need to merge what's in the generated stub file with what's in the project copy of that file.

By the way, the IDL file causes a lot of artifacts to be generated for you; more than just the stub h and cpp files. For instance, metadata is generated for you in the winmd file; and the base classes of those stub classes are available in other generated files. For some developers it can be the case that they don't actually need the stub classes (and instead derive your own classes from those base classes); but in most cases the stub classes are convenient to use, and should be.

As for the question about using C code in the implementation of a C++/WinRT component, I think the short answer is yes, you probably should implement a C++ class at least. And that class is going to be the generated proxy class (for example, the struct BankAccount : BankAccountT<BankAccount>, in the events topic). It should be *technically* possible to consume your existing C code from that class, although whether that makes sense from a maintainability and developer productivity point of view you'll have to determine for your particular case. You may choose to just go ahead and port your C code to C++ for reasons of readability, maintainability, efficiency, and so on. The longer answer to the question of C involves the fact that COM (as you know, WinRT is built on top of COM) is essentially a standard about blocks of function pointers, and it's not limited to the C++ language. You *can* (theoretically, although not very practically) implement a COM component in any language, including of course C. But it's laborious. To really leverage the power of C++/WinRT, going with C++, and going with generated stubs from the C++/WinRT toolchain, is going to give you the best efficiency and certainly correctness. Hope this helps! -Steve

**Comment by moyanming** [comment]
Hi @stevewhims , thank you for your recommendation. It is useful to me.
