### ISSUE TITLE
Need more direction on how to FIND the Users page

### ISSUE THREAD

**Issue by CathyMoya** [MicrosoftDocs/windows-uwp#735]
[Enter feedback here]
Hi, step 1 says
From the Users page, select Add users.
But you haven't told me anywhere on that page how to FIND the Users page. Please add more detail. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf973bd-e0d9-19b0-ad24-e09a83d3a2a9
* Version Independent ID: 25d0bdd2-0487-6742-b4bd-abc1e3ee6be8
* Content: [Add users, groups, and Azure AD applications to your Dev Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications)
* Content Source: [windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks - you're right, the specifics on how to find were only included in a separate topic. I've updated this topic to clarify that the Users page is under Account settings (and specified how to get to Account settings in case that is also not clear).

**Comment by CathyMoya** [comment]
Thank you! :-)
