### ISSUE TITLE
Great article

### ISSUE THREAD

**Issue by Leisvan** [MicrosoftDocs/windows-uwp#736]
This is good documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd79400-8154-9a7c-a36e-33077cfa4be9
* Version Independent ID: fafc7523-a98a-fbff-9cc1-ca74a335c3ff
* Content: [Title bar customization - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar)
* Content Source: [windows-apps-src/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/title-bar.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by ginami** [comment]
Thank you so much, @Leisvan!
