### ISSUE TITLE
Missing stuff in Adobe XD UI kit (progress ring and title bar)

### ISSUE THREAD

**Issue by harvinders** [MicrosoftDocs/windows-uwp#737]
- In earlier versions we could see the App Titlebar with minimise, restore and close buttons, it is absent. 
- Also missing is the ProgressRing control.  
- There is no taskbar either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fc7b1d-8b97-598a-f059-093d94972931
* Version Independent ID: 943e9c97-f223-4d3c-730c-a7f20cb04560
* Content: [Design toolkits and samples for UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for the feedback--I've passed it on to the folks who create the toolkits. I'll let you know when an update is ready.

**Comment by epatr** [comment]
The .PDF included with the XD download lists uwpappdesignfeedback@microsoft.com as the email address to use for feedback like this.

**Comment by sguergachi** [comment]
I'm also looking for the Windows 10 title bar in the Adobe XD toolkit

**Comment by mijacobs** [comment]
@sguergachi : By Windows 10 title bar, do you mean the app title bar?

**Comment by sguergachi** [comment]
Yes

- Sammy Guergachi
________________________________

**Comment by Nils-Berghs** [comment]
The virtual keyboards are also missing from the xd file.

**Comment by mijacobs** [comment]
The latest updates should fix these issues, please re-open if that's not the case.
https://docs.microsoft.com/en-us/windows/uwp/design/downloads/
