### ISSUE TITLE
Misleading documentation about node selection.

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/windows-uwp#738]
The phrase
> When selection is enabled, a checkbox is shown

should be

> When multi-selection is enabled, a checkbox is shown

because check boxes are not shown when single selection is enabled.
Currently the SelectedNodes property is not updated in single-select mode either, which it should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba995b-8bf3-407c-7b87-015d22d813f1
* Version Independent ID: 52c553b6-e94d-2810-4123-8ee215b002bf
* Content: [Tree view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view#interacting-with-a-tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by cwey** [comment]
I am guessing this is the same issue I run into. When I set the single selection programmatically, the item in the tree doesn't appear selected.

**Comment by EddieLotter** [comment]
The documentation has been re-worded. I am closing the issue.
