### ISSUE TITLE
missing URI from 1803 update

### ISSUE THREAD

**Issue by DanNCengineer** [MicrosoftDocs/windows-uwp#739]
Missing the URI for the Search options, which include safesearch, cloudsearch, and history settings.  Would be great to include this for image customization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a2ae18-080e-3470-d1c7-ab2990d4da85
* Version Independent ID: 3d0d02af-c1d7-e2e7-ba01-15e0904dc9a6
* Content: [Launch the Windows Settings app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#ms-settings-uri-scheme-reference)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by knicholasa** [comment]
Hi @DanNCengineer, thanks for your feedback. I believe the string you're looking for is "ms-settings:search-permissions". I'll add the URI to the page.

**Comment by DanNCengineer** [comment]
No, it's not.

If I wanted to hide the individual options for the following individual settings related to the search features (such as safesearch, my device history, or couldsearching) , so they didn't appear to the general users, how would I do that?

I'm thinking something like ms-settings:search-safesearch, ms-settings:search-cloudsearch and ms-settings:search-search history.

**Comment by knicholasa** [comment]
Hi @DanNCengineer, unfortunately comments left here are meant for documentation feedback, so I'm unable to provide ongoing technical support. I'll follow up with the team about whether the docs need to be updated based on what you're saying, but in the mean time I'd recommend you consult our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Or, check out the [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
