### ISSUE TITLE
No image text appears in Part 2

### ISSUE THREAD

**Issue by silverace99** [MicrosoftDocs/windows-uwp#741]
Under "Part 2: Add a GridView control using the XAML editor", the only code that is not already part of the downloadable project is: ImageGridView.ItemsSource = Images;

And even after adding that, I do not see any image text as shown in the screenshot. Is this tutorial up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc1c132-3cfa-1a08-0726-214110c8d23d
* Version Independent ID: 7ddf3871-c4a1-ae0a-9c03-25ccf4934cf2
* Content: [Create a user interface tutorial - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-ui)
* Content Source: [windows-apps-src/design/basics/xaml-basics-ui.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-ui.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by cheles** [comment]
App is looking for pictures under "Pictures" folder (C:\Users\username\Pictures). 
If you don't have any picture there, then the no image will be displayed and the app would look like it's blank.

The code responsible for this is: Windows.Storage.StorageFolder picturesFolder = Windows.Storage.KnownFolders.PicturesLibrary;
More here: https://docs.microsoft.com/en-us/uwp/api/windows.storage.storageprovider

If you want to change the Storage Provider, take a look at Windows.Storage namespace https://docs.microsoft.com/en-us/uwp/api/Windows.Storage

**Comment by jwmsft** [comment]
Thanks for the feedback. The tutorial has been updated recently and should be up-to-date.
