### ISSUE TITLE
VisualStateManager code snippet is not correct

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#742]
I think VisualStateManager code snippet is wrong. Here the code I actually use:
        &lt;VisualStateManager.VisualStateGroups&gt;
            &lt;VisualStateGroup&gt;
                &lt;VisualState&gt;
                    &lt;VisualState.StateTriggers&gt;
                        &lt;AdaptiveTrigger MinWindowWidth="0" /&gt;
                    &lt;/VisualState.StateTriggers&gt;

                    &lt;VisualState.Setters&gt;
                        &lt;Setter Target="Associate.(RelativePanel.RightOf)" Value=""/&gt;
                        &lt;Setter Target="Associate.(RelativePanel.Below)" Value="Customer"/&gt;
                        &lt;Setter Target="Save.(RelativePanel.Below)" Value="Associate"/&gt;
                    &lt;/VisualState.Setters&gt;
                &lt;/VisualState&gt;
                &lt;VisualState&gt;
                    &lt;VisualState.StateTriggers&gt;
                        &lt;AdaptiveTrigger MinWindowWidth="640"/&gt;
                    &lt;/VisualState.StateTriggers&gt;
                    &lt;VisualState.Setters&gt;
                        &lt;Setter Target="Associate.(RelativePanel.RightOf)" Value="Customer"/&gt;
                        &lt;Setter Target="Associate.(RelativePanel.Below)" Value=""/&gt;
                        &lt;Setter Target="Save.(RelativePanel.Below)" Value="Associate"/&gt;
                    &lt;/VisualState.Setters&gt;
                &lt;/VisualState&gt;
            &lt;/VisualStateGroup&gt;
        &lt;/VisualStateManager.VisualStateGroups&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b47dbb-38b5-9d75-8df2-2300cdc25bb7
* Version Independent ID: b204d881-3ca4-a7bb-87c3-0e91df704637
* Content: [Learning track - Construct and configure a form - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/construct-form-learning-track#what-do-you-need-to-know)
* Content Source: [windows-apps-src/get-started/construct-form-learning-track.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/construct-form-learning-track.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
The code snippet functions - there's no need to set a Visual State for the app's default state - but you're right in that it does the reverse of expected behavior. I'll clean it up so it behaves in the expected manner.
