### ISSUE TITLE
 The xbox one developer mode activation app

### ISSUE THREAD

**Issue by awabast** [MicrosoftDocs/windows-uwp#744]
The Xbox one developer mode activation app looks good but I haven't used it yet I'm looking forward to using it and seeing what I can come up with,  I'm not rich so I will see if I can afford to pay the fee for it. I really hope that I can afford it,,it looks so awesome I want to make lots of programs and stuff also to be able to help others and fix my Xbox one while I'm doing it first thing I want to do is check out grand theft auto V and see what is going on and why I don't get any trucks from armor guards and why when you invest in the stock market and it only allows for one added stock and why it disappears pretty much immediately also would like to see if I can fix pc's too. If I don't get it this fortnight I'll have to wait till next fortnight until I can afford to pay for it ,,I'd like make things that would probably blow your mind cause I've been playing around with sketchup and blender and unity,,unity is the one that they use for kerbal space program game and a heap of other games as well ,I'm not very good at blender and unity but I'm excellent with sketchup I can draw a 3D anything I tell a lie I'm not very good at doing people and animals they always come out wrong but I can do craft and machines really good if this page was big enough I would post a few pictures of my efforts on sketchup ,,, I really enjoy messing around with stuff I enjoy seeing how it all works and how to manage and operate said things like the DMA app (developer mode activation app) I can't wait until I can start messing around with it and see what I can do to change my Xbox ones attitude towards the game grand theft auto V I wonder what scripting language it uses I hope it's something easy like C# or C/# plus ,you can do those on a note pad on any computer or pc I hope I don't have to do reports on it and send them to wherever because I don't like doing reports constantly it wears me out,I just want to mess around for a while these days and learn at my own pace I don't think that what I've talked about here is asking for too much ,just one little program to help me get so stuff done on my laptop and Xbox one mainly debug the games that I play. So in summary all I'm asking for is the developer mode activation app and nothing else.I just want my game to run right gta (grand theft auto V) also I would love for it to stop signing me out while I play games on the Xbox one it only happens when I'm online when it signs me out but that's not the worst thing that happens to me,I play KSP(Kerbal space program) on my laptop but the game has gotten to big for my little pc and freezes up and stalls for like 1 to 5.5 hours at a time sometimes it crashes all of a sudden the game is about 11 gigabytes which isn't that big but it's rough on the 4 gigabyte ram and the 1.7 Ghz processor which in comparison to other pc's of today it's pretty small and weak . It takes so long for KSP to start up first off it takes 3 to 4 minutes just to load up the screen from a white screen to game screen takes about 30 to 40 minutes to load up the start menu takes a further 16 minutes to load up from the game saves menu to the main game itself where you start off in what is called the kerbal space center, where there is a heap of selections starting with the vab or the vehicle assembly building then you have the mission building the recruitment building and the sph or the space plane hanger and then there's the most important one which is the TS Or the Tracking station where all your other missions are just sitting there waiting for you to come back and complete the stuff that you started before ,you can run more than one mission at a time you can go outside the space ship walk around or fly around in low gravity with your jet pack or if you take a car to another planet or moon you can drive anywhere you want there's no size limit to how big you can build or how many missions you can have all depends on how big is your pc and if you got cool graphics card you can turn up the visuals for kerbal space program and it does look really good when you turn it up on the settings for clouds and dirt and words on the menu screen would be a lot clearer and easier to read you can also see further than if you don't turn on full graphics. If you're no good at math then this is not the game for you ,,,,,,,,,,it makes you think cause you don't get prebuilt craft in this game or not very often ,,the only prebuilt craft that you get is in the vehicle assembly building and the space plane hanger where you can try your luck at flying the some of the worst built craft in the game or you can try your hand at improving them but be careful that you don't screw it up worse than it was in the first place there's cheats if you feel the need for that kind of thing,and there's lots and lots of mods or add-ons everybody should be familiar with add-ons by now,,, there's literally hundreds of mods to change and to choose from every single one of them different from next you can take pictures and video of your efforts put them on Facebook or something like that it's not too bad I tell you these things cause it's an amazing game time taking genius game not impossible to play unless you have a craptop like me and then it makes it hard to play KSP I've played a lot of games in my life but kerbal space program is the one that sucked me in it's just such a wonderful game. I always forget my lights on my craft but always remember to put landing legs on it,,, satellite dishes everywhere tons of fuels made by a amateur and designed by a novice what could go wrong......

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc064e49-5f24-ff80-d511-7f1947fc39da
* Version Independent ID: b8ad47c2-8264-c232-167f-b9ee69d6dce1
* Content: [Xbox One Developer Mode activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **scotmi**

**Comment by awabast** [comment]
I want to be a developer but I have no idea what I'm doing

**Comment by ginami** [comment]
Thanks for your feedback, @awabast.
