### ISSUE TITLE
app service error

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#747]
I copied the code here and it works well, but when I try to make my own, the background task didn't run and send message return Failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by michael-hawker** [comment]
My OpenAsync on the inventoryService on the client is returning failure (AppUnavailable).  Which is odd, as I used this elsewhere and it worked.  So a section on common problems and resolutions could be helpful.

**Comment by dongle-the-gadget** [comment]
I mean AppServiceConnection.SendResponseAsync(ValueSet) return Failture.

**Comment by BestTimeIsNow** [comment]
Can Microsoft comment on backgroundtask registration as it relates to an app service?  Registering, or confirming that the task has been registered, is not noted as needed or not needed anywhere in the app service provider or in the caller.  

Clarification may be helpful for readers who may not be entirely familiar with the requirements around handling background task registrations.

**Comment by eliotcowley** [comment]
Hi all, sorry for the delayed response. There are several questions here, and it's difficult to debug an issue without more info, but if anyone wants to follow-up please comment again with more details about the problem you're having.

@BloominLate I'm not sure what you mean by "background task registration." In the doc, we connect the app service provider to the app service by adding it as a declaration in the provider's app manifest. Then we connect the client app to the provider by giving it the provider's package family name and the app service name. If there's anything else that needs to be done that isn't talked about in the doc, please let me know.

**Comment by eliotcowley** [comment]
Closing due to lack of response. @superkid200 please feel free to re-open if you're still having this issue.
