### ISSUE TITLE
This is an excellent sample. Please translate Petzold 6/e samples also.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#748]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0d8b84-01be-3ee5-d4e3-ac01e505ab2a
* Version Independent ID: b8e7ca9f-e8e7-99dc-f4c7-08d5c32e763c
* Content: [Photo Editor C++/WinRT sample application - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/photo-editor-sample)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/photo-editor-sample.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/photo-editor-sample.md)
* Product: **windows**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **wdg-dev-content**

**Comment by JoshuaPartlow** [comment]
Hi, thank you very much for your interest in this sample and feedback. Our team is working to expand the presence of c++ /WinRT code examples within the documentation, as well as the samples we provide. Hopefully they'll meet your needs, but please do provide additional feedback if they don't or if there are scenarios not covered in the [C++ /WinRT docs](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/) that would be helpful to you.

**Comment by ghost** [comment]
Thanks Joshua. An IValueConverter sample would be great. I was working through Petzold PW6 samples translating these from C++/CX and got stuck on WhatSizeWithBindingConverter. I expect that the solution involves unbox_value or unbox_value_or ignoring  the IValueConverter to/from parameters that are required by .NET. I might need to wait for the XAML compiler to be completed.
