### ISSUE TITLE
i am unable to follow

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/windows-uwp#749]
can't follow these step, where is it?

Go to your Account settings and click Tenants.
Select Associate Azure AD with your Dev Center account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262768e8-ad91-7af3-1541-4f2d2f9de5ba
* Version Independent ID: cc035cc8-ce25-57c4-2d2d-389451442d98
* Content: [Associate Azure Active Directory with your Dev Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-dev-center)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-dev-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-dev-center.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
You must have the Manager role in a Dev Center account in order to associate an Azure AD tenant. If you do, you should be able to see the Tenants page and follow those steps. (Account settings can be found under the gear icon near the upper right corner.)
