### ISSUE TITLE
why can't use company office365 account to register a microsoft dev account?

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/windows-uwp#750]
i saw this error:

You are signed in as peter@quantr.hk. You can’t use your organizational credentials to access the Office Seller Dashboard. To continue, please sign out of Dev Center and then sign in again using the Microsoft account associated with this Dev Center account.

**Comment by ginami** [comment]
Hello @peterremote1980. I'm sorry you're having trouble signing in, but we can't provide help through document issues. Please go to our Windows developer support page for assistance: https://developer.microsoft.com/windows/support
Thank you!
