### ISSUE TITLE
How to animate?

### ISSUE THREAD

**Issue by seanocali** [MicrosoftDocs/windows-uwp#751]
Can this effect be achieved using Composition API?  Setting the Visaul.RotationAxis to X or Y creates something similar except it lacks the 3D skew effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c416f3-66c4-1eec-2c02-579eb90ac111
* Version Independent ID: 9a12bc7d-05d2-52e7-3978-462651a399e9
* Content: [3-D perspective effects for XAML UI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/3-d-perspective-effects#positioning-an-object-1)
* Content Source: [windows-apps-src/design/layout/3-d-perspective-effects.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/3-d-perspective-effects.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stmoy** [comment]
Hi @seanocali - thank you for reaching out. There are several ways to achieve 3d effects using both Xaml APIs and Composition APIs. In Xaml, your options include using PlaneProjection, Transform3D, or the TransformMatrix property. To achieve this effect using Composition, you would need to set the TransformMatrix property on the Visual – setting the Rotation would not be sufficient. If you must use Composition APIs, consider checking out the [PerspectivePanel UserControl sample](https://github.com/microsoft/WindowsCompositionSamples/blob/master/SamplesCommon/SamplesCommon/PerspectivePanel.cs ).

The correct approach depends on what scenario you’re trying to achieve. If you can provide more information, we can help you figure out the correct approach. In general, we don’t recommend that folks drop down to Composition unless necessary.
