### ISSUE TITLE
Missing something...

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#752]
Missing Glyph, so how can we use FontIcon or TextBlock?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @superkid200 , can you elaborate? What glyph is missing? Or do you mean that the font is missing on your system?

**Comment by dongle-the-gadget** [comment]
The table board is missing a important column that shows Glyphs, if this column is missing, it can’t be used for FontIcon.

**Comment by mijacobs** [comment]
@superkid200: Add  "&#x" + the Unicode point + ";" and that will give you a hex value you can use for the FontIcon's glyph. For example, here's how you use Unicode point E700: 
`<FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE700;" />`

**Comment by dongle-the-gadget** [comment]
But ECA5 cannot work.

**Comment by mijacobs** [comment]
But `&#xECA5;` does work:
```
        <CommandBar>
        <AppBarToggleButton Label="FontIcon">
            <AppBarToggleButton.Icon>
                    <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xECA5;" />
            </AppBarToggleButton.Icon>
        </AppBarToggleButton>
        </CommandBar>
```
