### ISSUE TITLE
Unclear API version

### ISSUE THREAD

**Issue by ethansmith91** [MicrosoftDocs/windows-uwp#753]
Please help clarify which API version include this new component

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab995399-9262-ebc0-ec18-2cdc251b3353
* Version Independent ID: 25ff5431-d7f1-deb2-969a-87534990c09c
* Content: [Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/)
* Content Source: [windows-apps-src/machine-learning/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/index.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
These docs reference the [WinML **preview** API](https://docs.microsoft.com/uwp/api/windows.ai.machinelearning.preview) (Windows 10, version 1803 (introduced v10.0.17134)). To use the **latest** [WinML API](https://docs.microsoft.com/uwp/api/windows.ai.machinelearning), we recommend downloading the latest [Windows 10 Insider Preview](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) (introduced v10.0.17709.0).
