### ISSUE TITLE
File Explorer APIS

### ISSUE THREAD

**Issue by raksha-git** [MicrosoftDocs/windows-uwp#754]
I am trying to get files in a specific folder on the device and the document doesnt how to generate the entire REST API call. For example, in the below REST API call what is "path=%5C&_=1530915183866". How does a developer generate that string ? 

http://<ip address>/api/filesystem/apps/files?knownfolderid=LocalAppData&packagefullname=0e6a37bd-6d5b-47b8-837c-c95c7c6e13e9_1.0.0.0_x64__ax326asn60w6a&path=%5C&_=1530915183866

**Comment by ginami** [comment]
HI @raksha-git -- thank you for your feedback. Can you please tell me which doc you were looking at? That will help me find the right person to address your question. Thanks!

**Comment by raksha-git** [comment]
Hello @ginami Here is the documentation I am viewing. 
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core

This is a great place to start but finer details of REST API usage and examples are not covered. I am figuring out the REST API call through Chrome Developer Tools on my Google Chrome Browser (F12). So, request the documentation be more comprehensive for developers to follow and start working with WDP APIs.

**Comment by eliotcowley** [comment]
Hi @raksha-git, are you still having trouble with this? I was able to call into the device portal APIs from a .NET Core C# console app and get a list of items in my Documents folder. Here's the endpoint I used (it's specific to my machine, of course): **https://localhost:50443/api/filesystem/apps/files?knownfoldierid=Documents**. You should be able to get the address of your device from the Settings app.

 According to the documentation, the **path** parameter you mentioned above is "The sub-directory within the folder or package specified". (It's also optional.) From the example you gave above, it's likely a folder within a side-loaded app on the user's machine.

Does this help? I suppose I could give example usages of the API, if that would make things clearer, but it seems to work like any other REST API.

**Comment by eliotcowley** [comment]
Closing due to no response. @raksha-git please feel free to re-open if you have further questions.
