### ISSUE TITLE
Unclear about encoding to access file system

### ISSUE THREAD

**Issue by raksha-git** [MicrosoftDocs/windows-uwp#755]
I am trying to get files in a specific folder on the device and the document doesn't how to generate the entire REST API call. For example, in the below REST API call what is "path=%5C&_=1530915183866". How does a developer generate that string ? 

http://<ip address>/api/filesystem/apps/files?knownfolderid=LocalAppData&packagefullname=0e6a37bd-6d5b-47b8-837c-c95c7c6e13e9_1.0.0.0_x64__ax326asn60w6a&path=%5C&_=1530915183866

**Comment by ginami** [comment]
HI @raksha-git  -- thank you for your feedback. Can you please tell me which doc you were looking at? That will help me find the right person to address your question. Thanks!

**Comment by raksha-git** [comment]
Hello @ginami Here is the documentation I am viewing. 
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core

This is a great place to start but finer details of REST API usage and examples are not covered. I am figuring out the REST API call through Chrome Developer Tools on my Google Chrome Browser (F12). So, request the documentation be more comprehensive for developers to follow and start working with WDP APIs.

**Comment by eliotcowley** [comment]
Closing as duplicate
