### ISSUE TITLE
C++ app example

### ISSUE THREAD

**Issue by resonatevision** [MicrosoftDocs/windows-uwp#756]
Do you have any plans to provide sample C++ apps using WinML? I am having issues loading my ONNX models from file in a C++ app. I am not exactly clear on how to use the StorageFile class in LoadModelFromStorageFileAsync call. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab995399-9262-ebc0-ec18-2cdc251b3353
* Version Independent ID: 25ff5431-d7f1-deb2-969a-87534990c09c
* Content: [Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/)
* Content Source: [windows-apps-src/machine-learning/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/index.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by TheGuardianWolf** [comment]
This may be of help, I'm using this code for breadboard component detection. You can replace the relevant bits with your classes.

```
task<void> Breadboard::initWinML()
    {
        this->mlModel = ref new Breadboard::BreadboardMLModel;
        return create_task(Windows::Storage::StorageFile::GetFileFromApplicationUriAsync(ref new Windows::Foundation::Uri("ms-appx:///Assets/resistor_classifier.onnx"))).then([this](Windows::Storage::StorageFile ^ storageFile) -> Windows::Foundation::IAsyncAction^ {
            return this->mlModel->LoadModelFromStorageFileAsync(storageFile);
        });
    }
```

**Comment by resonatevision** [comment]
@TheGuardianWolf  - Thank you for sharing this. 
Any luck trying it in a non-UWP app?

**Comment by TheGuardianWolf** [comment]
@resonatevision I did some development yesterday on the app in question, the C++ ML does not work due to some issue with the output binding, yet with the equivalent code in C#, it does.

I had to make a WinRT component in C# and link to that from my managed C++.

I think anything that can make use of WinRT components can work.

**Comment by serenaz** [comment]
We're working on a C++ sample for the next release of WinML APIs, as support for C++ is changing slightly.

In the meantime, I'd recommend checking out the latest WinML APIs, which support WinRT/C++
https://docs.microsoft.com/uwp/api/windows.ai.machinelearning
