### ISSUE TITLE
Why is this API so complicated?

### ISSUE THREAD

**Issue by thomasdao** [MicrosoftDocs/windows-uwp#757]
The complexity is just unbelievable. Why do we need to create so many types of tokens, juggling between so many different systems, each token with different kinds of expiry dates, to use in too many APIs? The amount of work to get this reliably done is just HUGE! Look at how Apple did this: they have just one API to verify the receipt with a secret password, and that's all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bdee9e-2095-4423-62c5-0beb5520dfd3
* Version Independent ID: fad19d6f-2fa3-ff54-925a-020fe65cadbc
* Content: [Manage product entitlements from a service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-1)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I have forwarded it to the engineering team that owns this API.
