### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by InnesB** [MicrosoftDocs/windows-uwp#759]
In the first paragraph under the ‘Consistency’ heading, ‘intuitive’ appears as ‘intuative’.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1426ac-9a20-b0a3-0ebd-8ce4b2a50882
* Version Independent ID: 771f2efb-f781-ed49-5ff0-5c95f2bc4868
* Content: [Navigation basics for UWP apps - UWP app developer](https://docs.microsoft.com/en-au/windows/uwp/design/basics/navigation-basics)
* Content Source: [windows-apps-src/design/basics/navigation-basics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-basics.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Fixed - thanks for the catch!
