### ISSUE TITLE
Multi-instance app not working

### ISSUE THREAD

**Issue by Maldus512** [MicrosoftDocs/windows-uwp#760]
I am confused about the documentation. I have an already-functioning UWP App, and I want to allow the possibility to open multiple indipendent instances.
Is adding the "SupportsMultipleInstances" attribute to the app manifest enough for it to work? I did it, but the behaviour is the same as before: trying to open another instance results in the old one getting focus.

**Comment by laurenhughes** [comment]
@Maldus512 You'll also need to add a Program.cs file with a Main() function to handle activation redirection. Check out [Multi-instance activation redirection](https://docs.microsoft.com/windows/uwp/launch-resume/multi-instance-uwp#multi-instance-activation-redirection) for implementation details and a code sample.

**Comment by Maldus512** [comment]
This is interesting to say the least.
As I said, I have added the "SupportsMultipleInstances" attribute to the manifest, and I asked the question precisely because it wasn't working on my PC. Afer installing the app on a second device though (with side loading, not through the store) I realized that I could actually open multiple instances on the other computer. So it appears the app manifest is indeed enough to activate it, and the question now is why it doesn't work on mine.

In fact, I was confused about [that very sample](https://docs.microsoft.com/windows/uwp/launch-resume/multi-instance-uwp#multi-instance-activation-redirection) because I couldn't understand the Program.cs part.
Why does adding that specific file influence the app in any way? Does it have to be called "Program.cs"? Shouldn't it extend some other class?

Anyway, adding it to my project gives some compilation errors. If I insert it verbatim as per the tutorial, without namespaces, I get

``
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0017	Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.	SerialWS	C:\Users\Maldus\Projects\serialWS\SerialWS\Program.cs	17	Active
``

If I add it to my namespace instead, I get

``
Error	CS0101	The namespace 'SerialWS' already contains a definition for 'Program'	SerialWS	C:\Users\Maldus\Projects\serialWS\SerialWS\obj\x86\Debug\App.g.i.cs	18	Active
Error	CS0111	Type 'Program' already defines a member called 'Main' with the same parameter types	SerialWS	C:\Users\Maldus\Projects\serialWS\SerialWS\obj\x86\Debug\App.g.i.cs	22	Active
``

My PC has 16299 build. The one where multi-instance works has a 17134 build.

**Comment by laurenhughes** [comment]
The Program.cs file is to provide a Main() function to handle activating instances of the app before any of the other app code runs. 

Try updating your PC to build 17134. Multi-instancing support was added in Windows 10, version 1803.

**Comment by Maldus512** [comment]
Updating to 17134 fixed the multi-instancing problem, but now I can't run visual studio in Debug mode anymore. A problem for another day, I guess.

Bottom line: yes, the  "SupportsMultipleInstances"  attribute alone is sufficient, provided that your goal is simply to open multiple windows. And to work windows needs to be >= 17134.

Thanks for the support.

**Comment by laurenhughes** [comment]
Glad to hear the multi-instancing issue is somewhat resolved. I'll pass your feedback along to the engineering team so they're aware of this scenario. Thanks again!
