### ISSUE TITLE
how to get bluetooth le device name without connection by using BluetoothLEAdvertisementWatcher

### ISSUE THREAD

**Issue by AlonikiX** [MicrosoftDocs/windows-uwp#767]
Hi, I am learning bluetooth le programming on UWP and don't know how to get the device name without connection. I use `BluetoothLEAdvertisementWatcher`, but the `LocalName` of the received advertisement data is always null. I want to list all bluetooth le devices with specific service uuids, and display their names, how should I achieve this? Thanks.

**Comment by ginami** [comment]
Hi @AlonikiX -- can you tell me which docs page you're referring to? This will help me route your question to the right author. Thank you!

**Comment by AlonikiX** [comment]
There is the link: https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/ble-beacon
I appreciate your help : )

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and spent some time looking into your issue. 

Unfortunately, the BluetoothLEAdvertisementWatcher class doesn't have a LocalName property, so I think I need more details or clarification on your issue.

Due to the age of this issue and the lack of any follow up from you, I'm going to close it at this time. However, though the Issue will be marked as Closed, I will monitor any subsequent replies. Many thanks!

**Comment by GunArm** [comment]
> Unfortunately, the BluetoothLEAdvertisementWatcher class doesn't have a LocalName property, so I think I need more details or clarification on your issue.

He was referring to the watcher.Received event of the watcher, which returns a BluetoothLEAdvertisementReceivedEventArgs arg.  Which has an Advertisement property, which has LocalName property.  

The alternate scan method of DeviceInformation.FindAllAsync returns a collection of DeviceInformation, which has a Name property.  Some BTLE devices have names which are accessible through that Name property.
Doing an ongoing scan with BluetoothLEAdvertisementWatcher, of the devices which would be detected with names using the DeviceInformation method, *some* but not all of them, when found by the watcher, have names under BluetoothLEAdvertisementReceivedEventArgs.Advertisement.LocalName, and some don't.  In particular with BTLE beacons (of which I have 5 in front of me from different vendors), all of these have names which appear doing the DeviceInformation.FindAllAsync but come back with null BluetoothLEAdvertisementReceivedEventArgs.Advertisement.LocalName on the BluetoothLEAdvertisementWatcher.Received event.

It appears that the remaining names can be filled in by changing the watcher.ScanningMode to BluetoothLEScanningMode.Active.  Although you'd want to read about the consequences of this.
