### ISSUE TITLE
Can we get a sample app without Wix or Desktop Bridge?

### ISSUE THREAD

**Issue by santukv** [MicrosoftDocs/windows-uwp#768]
I need to see if we can accomplish without adding new components to my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53415734-dd31-7cf0-a82e-02566ed82396
* Version Independent ID: e5f82c08-6c9f-c628-9a45-5df000239ae4
* Content: [Send a local toast notification from desktop C# apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#step-3-copy-compat-library-code)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **windows**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @santukv,
The article you refer to is specifically for Desktop bridge and win32 scenarios. If your app is a UWP app, you can use the simpler instructions here: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast
