### ISSUE TITLE
Where is it?

### ISSUE THREAD

**Issue by dmitricob** [MicrosoftDocs/windows-uwp#770]
Where i can get this template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbd23f54-34c4-2113-04a2-fdfeeff71880
* Version Independent ID: af53df3c-743d-e076-430c-1bf96c0947a9
* Content: [DirectX game project templates - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/user-interface)
* Content Source: [windows-apps-src/gaming/user-interface.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/user-interface.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mtoepke**

**Comment by ginami** [comment]
Hi @dmitricob -- per the doc, the templates are part of Visual Studio 2015.

**Comment by dmitricob** [comment]
oh Im alredy finde it thx, but is thare some way to use Direct2D (DirectX) throw UWP C#?

**Comment by mtoepke** [comment]
Hi @dmitricob ,

You might want to check out Win2d: https://github.com/Microsoft/Win2D

It provides C# UWP access to Direct2D.

**Comment by ginami** [comment]
Hi @dmitricob -- I'm going to close this issue. Let us know if you have further feedback. Thank you!
