### ISSUE TITLE
Bug in Example Code

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#772]
If the Client app, if the InventoryService fails to connect, it's still initialized, so hitting the button again will cause an exception:

if (status != AppServiceConnectionStatus.Success)
        {
            textBox.Text= "Failed to connect";
            return;
        }

The service should be nulled on error:

if (status != AppServiceConnectionStatus.Success)
                {
                    Result.Text = "Failed to connect";
                    this.inventoryService = null;
                    return;
                }

So that it will try to re-establish a connection the 2nd time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by normesta** [comment]
Thank you for the suggestion! We've added that line of code to the example.
