### ISSUE TITLE
how to get sandbox at runtime?

### ISSUE THREAD

**Issue by XboxNinge** [MicrosoftDocs/windows-uwp#774]
It would be great if this article also explained how to detect which sandbox the title is running in at runtime. This is useful for things like automatically changing matchmaking groups based on dev/cert/retail sandbox, or changing which server to connect to for an online title etc.

Platform:: String^ Microsoft::Xbox::Services::XboxLiveAppConfiguration::Sandbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71e6c19-d933-324c-bf23-09fcc63c3800
* Version Independent ID: 5404fed5-02a6-0a2a-1802-68ba3b97f328
* Content: [Advanced Xbox Live sandboxes - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/advanced-xbox-live-sandboxes#getting-the-access-right)
* Content Source: [windows-apps-src/xbox-live/advanced-xbox-live-sandboxes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/advanced-xbox-live-sandboxes.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by KevinAsgari** [comment]
This is an excellent point.  I will investigate adding a section on programmatically determining the sandbox during runtime.
