### ISSUE TITLE
Add an ItemSource property to TreeView 

### ISSUE THREAD

**Issue by Kath118** [MicrosoftDocs/windows-uwp#775]
Could you please add an item source property to tree view? It's so difficult to binding the source to tree view  from the view model.

**Comment by ginami** [comment]
Hi @Kath118 -- which page are you referring to? This will help me route your request to the correct author. Thank you!

**Comment by Kath118** [comment]
Hi @ginami  This page https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view

**Comment by jwmsft** [comment]
ItemsSource property was added in Windows 10, version 1809 (introduced v10.0.17763.0).
[TreeView.ItemsSource Property](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.treeview.itemssource)
