### ISSUE TITLE
Problem with enumeration in MIDI API

### ISSUE THREAD

**Issue by Dianoya** [MicrosoftDocs/windows-uwp#776]
Many devices are not recognized in the enumeration. This is very bad!
The MME API saw them all. So the problem is not the drivers, but the API. In addition, this is a problem everyone knows about.
As far as I understand, ALL devices KORG and many devices YAMAHA are not determined.

I have 3 MIDI devices. The device "M-Audio MIDISPORT 4x4" was detected normally. "KORG nanoControl" and "KORG M50" are not detected.

The selector string returned by MidiInPort.GetDeviceSelector:
`System.Devices.InterfaceClassGuid:="{504BE32C-CCF6-4D2C-B73F-6F8B3747E22B}" AND System.Devices.InterfaceEnabled:=System.StructuredQueryType.Boolean#True`

The selector string returned by MidiOutPort.GetDeviceSelector:
`System.Devices.InterfaceClassGuid:="{6DC23320-AB33-4CE4-80D4-BBB3EBBF2814}" AND System.Devices.InterfaceEnabled:=System.StructuredQueryType.Boolean#True`

MIDI input devices "M-Audio MIDISPORT 4x4" ID:
`\\?\SWD#MMDEVAPI#MIDII_B8AFC694.P_0001#{504be32c-ccf6-4d2c-b73f-6f8b3747e22b}`
`\\?\SWD#MMDEVAPI#MIDII_B8AFC695.P_0001#{504be32c-ccf6-4d2c-b73f-6f8b3747e22b}`
`\\?\SWD#MMDEVAPI#MIDII_B8AFC696.P_0001#{504be32c-ccf6-4d2c-b73f-6f8b3747e22b}`
`\\?\SWD#MMDEVAPI#MIDII_B8AFC697.P_0001#{504be32c-ccf6-4d2c-b73f-6f8b3747e22b}`

MIDI output devices "M-Audio MIDISPORT 4x4" ID:
`\\?\SWD#MMDEVAPI#MIDII_5484345E.P_0000#{6dc23320-ab33-4ce4-80d4-bbb3ebbf2814}`
`\\?\SWD#MMDEVAPI#MIDII_5484345D.P_0000#{6dc23320-ab33-4ce4-80d4-bbb3ebbf2814}`
`\\?\SWD#MMDEVAPI#MIDII_5484345C.P_0000#{6dc23320-ab33-4ce4-80d4-bbb3ebbf2814}`
`\\?\SWD#MMDEVAPI#MIDII_5484345B.P_0000#{6dc23320-ab33-4ce4-80d4-bbb3ebbf2814}`

MIDI input Bluetooth HiFing ID:
`\\?\SWD#MMDEVAPI#MIDII_96243F30.BLE10#{504be32c-ccf6-4d2c-b73f-6f8b3747e22b}`

MIDI output Bluetooth HiFing ID:
`\\?\SWD#MMDEVAPI#MIDII_96243F31.BLE10#{6dc23320-ab33-4ce4-80d4-bbb3ebbf2814}`

MIDI output "Microsoft GS Wavetable Synth" ID:
`\\?\SWD#MMDEVAPI#MicrosoftGSWavetableSynth#{6dc23320-ab33-4ce4-80d4-bbb3ebbf2814}`

Here are the devices that are not listed. I used the function DeviceInformation.FindAllAsync();

"KORG nanoControl" has such devices ID:
`\\?\USB#VID_0944&PID_010F#6&5a88162&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed}`
`\\?\USB#VID_0944&PID_010F#6&5a88162&0&2#{efb09480-65fb-11d3-92a3-006067603699}`

And it's all!

"KORG M50" has such devices ID:
`\\?\USB#VID_0944&PID_0110#6&5a88162&0&3#{efb09480-65fb-11d3-92a3-006067603699}`
`\\?\USB#VID_0944&PID_0110#6&5a88162&0&3#{a5dcbf10-6530-11d2-901f-00c04fb951ed}`

And it's all!

I think that the system itself does not create the necessary device for enumerate MIDI UWP.
Now I can not use my synthesizer M50 and midi controller nanoControl on the UWP

If you need more information from me, just tell me. I will try to help in the tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
