### ISSUE TITLE
Problem with device names in MIDI API

### ISSUE THREAD

**Issue by Dianoya** [MicrosoftDocs/windows-uwp#777]
I have the device "M-Audio MIDISPORT 4x4". It has 4 input ports and 4 output ports.

That's how they are called for input ports:

> MIDISPORT 4x4 In A (1)
> MIDISPORT 4x4 In B (1)
> MIDISPORT 4x4 In C (1)
> MIDISPORT 4x4 In D (1)

Why is it added at the end (1)? If I switch to another USB port, the front of the name is appended with a digit.

And this is how they are called for output ports:

> MIDI
> MIDI
> MIDI
> MIDI

What is there to understand at all? Is that a "FriendlyName"? :-)

Everyone knows about this problem, is not it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
