### ISSUE TITLE
Microsoft Visio Integration missing

### ISSUE THREAD

**Issue by OneWorld123** [MicrosoftDocs/windows-uwp#779]
Can't use them in Microsoft Visio ;( Apparently Visio 2016 doesn't support private use unicode characters.

 I filed a question at https://superuser.com/questions/1336168/use-segoe-mdl2-assets-and-other-unicode-fonts-with-private-use-characters-in-vis . 

Related: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_visio-mso_win10-mso_2013_release/problems-rendering-segoe-mdl2-assets-in-visio-2013/05afb974-fa65-4d94-9a24-eb3e503a8db7?auth=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@OneWorld123  Thanks for the feedback! I looked through the related links you shared, and it sounds like the issue is with the Visio Application. I'll pass your feedback on to that team.

**Comment by mijacobs** [comment]
@OneWorld123 I found the UserVoice page for Visio--UserVoice is how most of our product teams get feedback. Can you file this issue there?
https://visio.uservoice.com/

**Comment by OneWorld123** [comment]
Done. I hope for the best. https://visio.uservoice.com/forums/229400-visio-on-desktop/suggestions/35021365-private-use-unicode-characters-like-segoe-mdl2-ass
