### ISSUE TITLE
Failed to find the property "Windows.UI.Xaml.Controls.TreeView.RootNodes".

### ISSUE THREAD

**Issue by Kath118** [MicrosoftDocs/windows-uwp#781]
When I create a tree view in the xaml appears the following error:
Failed to find the property "Windows.UI.Xaml.Controls.TreeView.RootNodes".
If I build the project the error disappears but the tree view is not showed.

NETCore: 6.0.1
SDK version: 17134 (1803)
Visual Studio 2017 v15.7.5

**Comment by predavid-zz** [comment]
Please use the latest version of the WinUI Nuget package. It should address the issue.
