### ISSUE TITLE
Problem with DeviceWatcher and port closing.

### ISSUE THREAD

**Issue by Dianoya** [MicrosoftDocs/windows-uwp#783]
Using DeviceWatcher means that when remove a device to which the port was opened, you can safely close it and continue working with the application. In this case, the user has the option to turn on the device again or select another without restarting the application. I understand correctly?

I will describe the problem. There is a device and a port is open for it. I accidentally pulled this device out of the USB. DeviceWatcher said that the device was removed from the system. The application checks that a port has been opened on this device and then closes it. Is everything done right?

The simplest version of the event handler Removed:
```
        private void DeviceWatcher_Removed(DeviceWatcher sender, DeviceInformationUpdate args)
        {
            if (midiInPort != null)
            {
                midiInPort.MessageReceived -= MidiInPort_MessageReceived;
                midiInPort.Dispose();
                midiInPort = null;                
            }
        }
```

But after such another port will not open. And when you close the application, it hangs for 5-7 minutes. I can not do anything about it anymore.

I suspect that after removing the device, the open port is blocked and remains hanging in the system. The port can not be closed any more.

Am I doing something wrong? In the instructions and example this is not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by avazquez-tecss** [comment]
Dear...did you find a solution?

**Comment by Dianoya** [comment]
> Dear...did you find a solution?

Unfortunately not. I stopped practicing MIDI in UWP. :-( Maybe another time ... I always remember about these issues. When I again take up this matter and find a solution, I will definitely write about it! I hope this will be fixed ... in a few years ... :-)

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
