### ISSUE TITLE
It does not work and I get exception messages with no hint on how to resolve them

### ISSUE THREAD

**Issue by DamienDoumer** [MicrosoftDocs/windows-uwp#784]
I am working on a UWP project which I built with Xamarin.Forms and which has a background service project too. 
I follow exactly the steps listed here and when I hit F5, I get ghost exceptions...

Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
Exception thrown at 0x74FF3EF2 (KernelBase.dll) in Expenditures.exe: WinRT originate error - 0x80040154 : 'System.Exception: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()
   at UWPBackgroundServices.ExpenditureReminderBackgroundService.&lt;Register&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;&gt;c.&lt;ThrowAsync&gt;b__6_0(Object state)'.
The thread 0x1da8 has exited with code 0 (0x0).
Exception thrown at 0x74FF3EF2 (KernelBase.dll) in Expenditures.exe: WinRT originate error - 0x80040154 : 'Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))'.
Exception thrown: 'System.Exception' in Microsoft.AppCenter.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
Exception thrown at 0x74FF3EF2 (KernelBase.dll) in Expenditures.exe: WinRT originate error - 0x80040154 : 'System.Exception: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()
   at UWPBackgroundServices.ExpenditureReminderBackgroundService.&lt;Register&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;&gt;c.&lt;ThrowAsync&gt;b__6_0(Object state)'.
The program '[10344] Expenditures.exe' has exited with code 0 (0x0).

Please anyone help. (Hint : the name of my base namespace in the UWP project is Expenditures)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f4864c-3cf6-a957-dd26-c16cb4a3015e
* Version Independent ID: c9543586-cf91-3c13-50e0-1837cf4138a4
* Content: [Package an app by using Visual Studio (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hi Damien - Thank you for posting. Just so I'm clear. You created a UWP project by using Xamarin.Forms and in that project, you added a background task. Did you use the Windows Application Packaging Project template because you also have a win32 application that you want to package along with that UWP application? Including a win32 desktop application would be the only reason to use the guidance in this topic and I didn't see any evidence of that - hence why I ask. Thank you!

**Comment by DamienDoumer** [comment]
Hi, 
It didn't have a Win32 project in it, but for some reason, the normal way of making packages did not complete on my project, so I decided to use this approach but didn't work too. I finally found help with the issue, and the problem wasn't finally related to this article. Sorry I had to close this earlier.
