### ISSUE TITLE
The Bluetooth device closes the port with an error.

### ISSUE THREAD

**Issue by Dianoya** [MicrosoftDocs/windows-uwp#785]
There is a device Bluetooth (HiFing Wireless MIDI Adaptor). The application opens its input port. Then the application closes this port. It's not possible to open another port. And after closing the application, an error occurs:

> Unhandled exception at 0x00007FFC3BC165DF (Windows.Devices.Midi.dll) in RuntimeBroker.exe: 0xC0000005: Access violation when reading at 0x0000016FFB4B3948.

Interestingly, there is no such problem with the output port.

Is it problem with my the device or am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
