### ISSUE TITLE
IUnknown is ambiguous

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#787]
I'm using C++/WinRT and IUnknown is ambiguous. Fully specifying Windows::Foundation::IUnknown fixes that problem, only to give an invalide type conversion for the reinterpret cast.

Also IBufferByteAccess doesnt exist as far as I can tell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bcdf01-14ad-5f98-1ff8-eb01a3d9d70d
* Version Independent ID: 3b93a824-c7f7-7995-e626-3ac9ab4da268
* Content: [Working with Connected Storage buffers - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/storage-platform/connected-storage/connected-storage-using-buffers)
* Content Source: [windows-apps-src/xbox-live/storage-platform/connected-storage/connected-storage-using-buffers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/storage-platform/connected-storage/connected-storage-using-buffers.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Hi Gavin-Williams,

I'm currently looking into this question.

In the meantime I recommend that coding question like this one be asked on one of our developer forums.
If you have managed partner access you can ask on the [Xbox Developer Forum](https://forums.xboxlive.com/).
You can ask other developers working on windows platforms on the [windows platform developer forum](https://social.msdn.microsoft.com/forums/windowsapps/en-us/home?forum=wpdevelop).

**Comment by Gavin-Williams** [comment]
Here's my includes and usings for reference ..

    #include "pch.h"
    #include <winrt/Windows.Graphics.Imaging.h>
    #include <MemoryBuffer.h>
    
    //using namespace winrt;
    using namespace winrt::Windows;
    using namespace winrt::Windows::ApplicationModel::Core;
    using namespace winrt::Windows::Foundation;
    using namespace Windows::Foundation;
    using namespace winrt::Windows::Foundation::Numerics;
    using namespace winrt::Windows::UI;
    using namespace winrt::Windows::UI::Core;
    using namespace winrt::Windows::UI::Composition;
    using namespace winrt::Windows::Graphics::Imaging;

    // and in pch…
    #include "winrt/Windows.ApplicationModel.Core.h"
    #include "winrt/Windows.UI.Core.h"
    #include "winrt/Windows.UI.Composition.h"
    #include "winrt/Windows.UI.Input.h"

The invalid type conversion in my code was because .. types in C++/WinRT are structs and not pointers, I was trying to convert from a BitmapBuffer (struct). So that's my fault and not an issue.

And IBufferByteAccess can be replaced with IMemoryBufferByteAccess in MemoryBuffer.h although then you can't use …
    using namespace winrt; // this breaks compatibility between MemoryBuffer.h and C++/WinRT.

**Comment by aablackm** [comment]
Hello Gavin, I will pass this context along.

**Comment by aablackm** [comment]
Hello Gavin! 
Could you please try using the following include and using statements:
#include "RoBuffer.h"
using namespace Windows::Storage::Streams;

RoBuffer seems resolve an undefined IBufferByteAccess while Windows::Storage::Streams contains the desired definition of IUnknown.
