### ISSUE TITLE
Imaginary messages on devices with multiple ports

### ISSUE THREAD

**Issue by Dianoya** [MicrosoftDocs/windows-uwp#788]
This problem appears in the MessageReceived event handler.

Messages appear that were not sent to the device's input port! For example, we get the message B0 66 40, and the following messages appear in the handler:

```
B0 66 40
B0 00 00
B0 00 00
B0 00 00
B0 00 00
```

And they all have the same time.

And if the device additionally sends active sensing...

I suspect that the problem is due to the presence of several ports on the device or because of incorrect names.

Because the names of the output ports are:
```
MIDI
MIDI
MIDI
MIDI
```

I wrote about the [problem of names here](https://github.com/MicrosoftDocs/windows-uwp/issues/777
).

How can I handle incoming messages with this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
