### ISSUE TITLE
C++ Code Samples, please

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/windows-uwp#789]
I'm using this document to learn UWP.  I expect to use this in combination with DirectX 11.  Prior to this page, all C# code samples had similar samples for C++/CLI.  Could you add them where they are missing, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cecd85-5983-c683-d8ea-6c010b7b2b58
* Version Independent ID: 8a77e197-6c7c-3fcb-7ecf-e52f4a270d2d
* Content: [Responsive layouts with XAML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/layouts-with-xaml)
* Content Source: [windows-apps-src/design/layout/layouts-with-xaml.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/layouts-with-xaml.md)
* Product: **windows**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by Gavin-Williams** [comment]
I agree, all pages should have both C++ and C# examples. It's especially frustrating at the moment, because Microsoft recommend using C++/WinRT over C++/CX but with C++/WinRT being somewhat different and also it seems that there may be coverage issues or differences in C++/WinRT which make it impossible to convert CX code to RT code.

**Comment by sjointer** [comment]
The possibility of issues with C++/WinRT are hinted at in the docs for DirectX and XAML interop [here](https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop).

I guess what threw me a bit was that the early pages in this trail had C# and C++, which gave me some, I guess hope, that I would be able to learn both, and then decide how I wanted to use DirectX later.  Is there a location where I can keep up to date on C++/WinRT issues?

**Comment by stevewhims** [comment]
Hi, @sjointer, and thanks for filing this issue. For a topic that contains C++/CX code, but C++/WinRT isn't also represented, that's a priority to fix. I'm aware of some topics like that in the graphics and gaming content, which I have backlog items to remedy. However, this particular topic DOESN'T have C++/CX code, so its priority is lower. I don't have a work item to go through and add C++/WinRT to topics that don't already have C++/CX in them.

To port C# code examples to C++/WinRT, one suggestion would be for you to study the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) documentation, which contains lots of code examples showing many different techniques for calling Windows Runtime APIs from C++, and it contains a topic specifically about porting from C#. It's likely that you'll learn enough there to convert the C# code here to C++/WinRT. Also, as I say, any topic (across the Windows dev content) that has a C++/CX code example now also has a C++/WinRT code example.

If you find a topic that contains C++/CX code, but C++/WinRT isn't also represented, feel free to leave feedback on that topic, and then I'll know which ones to focus on first.

Thanks!
Steve
