### ISSUE TITLE
Missing info how to access new Windows Settings sections in Creators Update

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/windows-uwp#79]
This page contains links to various sections in the Windows Settings and how to reach them programmatically:
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app
but it was not yet updated to cover new sections and subsections added in Windows 10 Creators Update like **Settings -> Apps**, **Settings -> Gaming** and other.

It would be also helpful to have Uri scheme for accessing single app setting in:
**Settings -> Apps -> Apps & Features -> [My app name]**
so I can navigate user directly from my app to app settings, where the user should be able to **Move the app to another drive**, **Reset app data**, etc.

**Comment by mattwojo** [comment]
Thanks @martinsuchan. I'll ensure that the launch settings team sees this. *Also, if you already have found fixes or updates, please feel welcome to jump in and contribute to the docs with a Pull Request. -Matt

**Comment by TylerMSFT** [comment]
Thanks @martinSuchan. I will be the writer taking care of this. I'll do some research with the teams involved and update this thread when I can proceed.

**Comment by TylerMSFT** [comment]
@martinsuchan, we updated the topic with the input of project management and by looking through some source code. The list should be current now.
