### ISSUE TITLE
How to view featured stats while developing

### ISSUE THREAD

**Issue by v01pe** [MicrosoftDocs/windows-uwp#790]
It seems everything is set up correctly in our sandbox, I see achievements popping up and I can set stats, but the game hub for the game stays empty and there's no way I can see the unlocked achievements and set stats on the system. What is the intended procedure to test this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5d4eb6-be1e-90fc-a9c2-d580b3dcf0ee
* Version Independent ID: 58f13eb8-09d9-d15e-7b9a-30576d157189
* Content: [Featured Stats and leaderboards 2017 - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/configure-xbl/dev-center/featured-stats-and-leaderboards)
* Content Source: [windows-apps-src/xbox-live/configure-xbl/dev-center/featured-stats-and-leaderboards.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/configure-xbl/dev-center/featured-stats-and-leaderboards.md)
* Product: **windows**
* GitHub Login: @shrutimundra
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Hello v01pe,

If you are an Xbox Live Creators Program Developer, unfrotunately there is no way for you to see your GameHub and it's current state while you are developing. 

However for other developers you can see your Gamehub and featured stats by publishing your title to your sandbox. You can publish your title on the Windows Dev Center by pressing the black "Test" Button on the Xbox Services Page. Doing this after your stats are configured and set with values should allow you to see your Featured Stats state. 

For those in the Creators Program who cannot access their GameHub during development, you can still call down the values of Featured Stats with the **stats_manager** APIs **get_stat** to see a single statistic value for a player, or you could call **get_leaderboard** or **get_social_leaderboard** to see stat_values for multiple players at once. 

Hope this helps!

**Comment by v01pe** [comment]
Thanks for your answer!

We're registered in the ID@Xbox program, in which case I guess I should be able to see the stats and achievements showing up in the Gamehub?

We already published the changes from the Xbox Services Page in Dev Center, which made the achievements + the corresponding images viewable on the Xbox dev kit. Still they don't show up on Gamehub.

Thanks for the hint to view the stats through the stats manager API.

Best, Jan

**Comment by aablackm** [comment]
Glad I could help!
Yes, you should be able to see updates to the GameHub as long as you publish your title to a sandbox and then test your title with a device pointing to that same sandbox.

Also as a quck reminder, if you're using Stats 2017 remember to give your stats 5 minutes to flush after setting them.
