### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/windows-uwp#794]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7cfa056-082a-cdc4-d7c8-340f7617cc3c
* Version Independent ID: c560198c-e777-4bdb-55cc-110b11f20df5
* Content: [Introduction to Xbox One tools - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/xbox-apps/introduction-to-xbox-tools)
* Content Source: [windows-apps-src/xbox-apps/introduction-to-xbox-tools.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/introduction-to-xbox-tools.md)
* Product: **windows**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by ginami** [comment]
Hi @Sleeplikelion -- let us know if you have any feedback specific to this doc. Thanks!
