### ISSUE TITLE
Embedded Youtube video does not play

### ISSUE THREAD

**Issue by MsftGreg** [MicrosoftDocs/windows-uwp#795]
"Has been removed by author"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf7899f-689a-80c4-2c94-9575f8fc5055
* Version Independent ID: b8873e37-f4cb-de98-46f2-f2eaf01e275d
* Content: [Introduction to C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @MsftGreg, thanks for bringing this to my attention! I've just merged a fix; I expect that to be live within 24 hours. I've also begun making enquiries internally as to why the URI changed. ~Steve. P.S. I'll go ahead and close this now but please reopen and/or ping me if you have any follow-up.
