### ISSUE TITLE
xbox one x registration

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/windows-uwp#796]
z

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ba4f566-0e94-4460-6258-403561494a24
* Version Independent ID: a6664a24-7ef4-a53b-adc7-3d74e86b8735
* Content: [Developer program overview - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/xbox-live/developer-program-overview#microsoft-partners)
* Content Source: [windows-apps-src/xbox-live/developer-program-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/developer-program-overview.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by ginami** [comment]
Hi @Sleeplikelion -- let us know if you have any feedback on this doc! Thank you!
