### ISSUE TITLE
words like agnostic have no place in a technical document

### ISSUE THREAD

**Issue by Ian-Beard** [MicrosoftDocs/windows-uwp#802]
Please stop using words that you misinterpret one meaning for another that have no contextual meaning to the given subject under discussion. Crystal Clear English at all times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c7fb99-4e21-0e7b-86dd-482b2e7ef52e
* Version Independent ID: a3d9d1d1-7a8d-07b7-a0e4-7b2e0c107f31
* Content: [Visual Layer - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/composition/visual-layer)
* Content Source: [windows-apps-src/composition/visual-layer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/visual-layer.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Solrax** [comment]
Looks correct to me.

https://www.google.com/search?q=agnostic&oq=agnostic  (similar usage on dictionary.com)

adjective
adjective: agnostic
1.
relating to agnostics or agnosticism.
synonyms:	skeptic, doubter, doubting Thomas, cynic; More
antonyms:	believer, theist
(in a nonreligious context) having a doubtful or noncommittal attitude toward something.
"until now I've been fairly agnostic about electoral reform"
**COMPUTING
denoting or relating to hardware or software that is compatible with many types of platforms or operating systems.
"many common file formats (JPEG, MP3, etc.) are platform-agnostic"**
