### ISSUE TITLE
Can't install the retail version of Microsoft.VCLibs.x64.14.00.Desktop.appx

### ISSUE THREAD

**Issue by Ike-Dubaku** [MicrosoftDocs/windows-uwp#806]
I'm using Windows RS4 and VS 2017 15.7.4. After I use the "Windows Application Packaging Project" to convert my desktop app, the install failed with following message. With some investigations, I found there's no problem for debug version. In specific, the retail version "Microsoft.VCLibs.x64.Debug.14.00.Desktop.appx" (14.0.25426.0) failed to install, but the debug version "Microsoft.VCLibs.x64.Debug.14.00.Desktop.appx" (14.0.26428.1) is ok to install. Are there anything I'm missing?

&gt;&gt;&gt;&gt;&gt;&gt;&gt;
Installing app...
Found dependency package(s):
C:\_prog\MSFT\UWPDeskBridgeSample\DeskAp1\WapAp1\AppPackages\WapAp1_1.0.4.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.1
4.00.Desktop.appx
C:\_prog\MSFT\UWPDeskBridgeSample\DeskAp1\WapAp1\AppPackages\WapAp1_1.0.4.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFB, The provided package is already installed, and reinstalla
tion of the package was blocked. Check the AppXDeployment-Server event log for details.

Deployment of package Microsoft.VCLibs.140.00.UWPDesktop_14.0.25426.0_x64__8wekyb3d8bbwe was blocked because the provid
ed package has the same identity as an already-installed package but the contents are different. Increment the version
number of the package to be installed, or remove the old package for every user on the system before installing this pa
ckage.

NOTE: For additional information, look for [ActivityId] b1ab0277-1f60-0003-a392-abb1601fd401 in the Event Log or use th
e command line Get-AppxLog -ActivityID b1ab0277-1f60-0003-a392-abb1601fd401

At C:\_prog\MSFT\UWPDeskBridgeSample\DeskAp1\WapAp1\AppPackages\WapAp1_1.0.4.0_Test\Add-AppDevPackage.ps1:388 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\_prog\MSFT\U..._x64.appxbundle:String) [Add-AppxPackage], PSInvalidO
   perationException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f4864c-3cf6-a957-dd26-c16cb4a3015e
* Version Independent ID: c9543586-cf91-3c13-50e0-1837cf4138a4
* Content: [Package an app by using Visual Studio (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hello - Looping in a member of our engineering team to see if he can offer insight on this.

**Comment by QaisAlLafi** [comment]
Is there any updates on this , we are getting the same issue.

**Comment by rido-min** [comment]
From the logs  provided, looks like you have a more recen versions of the VCLibs framework package. This could happen if you are running an insider version that includes the newer version inbox.

You can try to remove that package with `Remove-AppxPackage` (the -verbose option shows  the dependent applications)

Can you verify the install with a retal version (non insiders) of the OS?

**Comment by MohammadHaroonAbuomar** [comment]
This is reproducible to me on a retail windows in developer mode.

**Comment by mcleanbyron** [comment]
Thanks for taking the time to post here, and I sincerely apologize for the delayed response. This GitHub repo is specifically for reporting documentation bugs. For further technical assistance about MSIX packaging, please see the community of experts and Microsoft engineers over at the [MSIX tech community](https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX).
