### ISSUE TITLE
RE: Handle work item completion

### ISSUE THREAD

**Issue by ChuckVanzant** [MicrosoftDocs/windows-uwp#808]
Your examples in your documentation for "Handle work item completion" are reversed, C# example contains C++ code and vise versa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30045711-217c-3cf5-8b25-462426685c1e
* Version Independent ID: a190b399-6866-bded-2015-ce337f22ea38
* Content: [Submit a work item to the thread pool - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/threading-async/submit-a-work-item-to-the-thread-pool)
* Content Source: [windows-apps-src/threading-async/submit-a-work-item-to-the-thread-pool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/threading-async/submit-a-work-item-to-the-thread-pool.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thanks ChuckVanzant - Looks like we took a pull request that resolved this issue. Thanks for reporting!
