### ISSUE TITLE
Cannot get Keyboard Accerlators to function

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/windows-uwp#809]
I'm attempting to put keyboard accelerators on most of my commands, simply because I like to use them when I know about them.  The problem is, while my menus are working correctly (They are set to throw a "NotImplementedException" at the moment) using access keys and mouse clicks, the accelerators do nothing.

What I've tried:
- make certain there is an assignment to the args parameter, setting the Handled property to true.
- Even though the parameters are different, I'm using the same method name for the KeyboardAccelerator.Invoke as the MenuFlyoutItem.Click event.
- I've redirected both of these methods to a third method where the third method throws NotImplementedException.  Again, clicking or using access keys gets the exception, but the accelerators are doing nothing.

A link to a solution for a similar question which is resolved is all I really need, although if someone answers directly here, I'm certain anyone coming to this page would find it useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by sjointer** [comment]
I forgot to mention: this issue occurs regardless of whether I use one, or two modifier keys.  Most of my accelerators use the Control modifier key.  A few of them use Control and Shift as the modifier key.  Moot point, I suppose, because none of my accelerators are working.

**Comment by sjointer** [comment]
Additionally, I explicitly set "IsEnabled" to "True" on the KeyboardAcelerator tag, but that didn't work either.

**Comment by sjointer** [comment]
I've also tried using unique method names, which shouldn't matter, but this doesn't help either.

**Comment by sjointer** [comment]
I've also tried adding the **ProcessKeyboardAccelerators** event using a method that simply throws **NotImplementedException**, but that method didn't get called when I tried to use the accelerator either/

**Comment by sjointer** [comment]
I've also tried adding the **ProcessKeyboardAccelerators** event to the **Page** element.  That DID call the method and throw the **NotImplementedException**, but the documentation on this page doesn't imply that I need to do that.  I'll go with this for now, but I'd like the correct solution, rather than this workaround.  It seems to me that this workaround isn't correct either, since I will need to have the if-else if structure for all accelerators used in my app.

**Comment by sjointer** [comment]
I looked closer at the exposed properties for the "args" parameter in the Keyboard Accelerator version of the method, and, after a couple of minutes of manipulating the accelerator and trying a few different things, I finally made the keyboard accelerator work and call the correct Keyboard Accelerator method, and not the accelerator method associated with the page itself...but the answer is USELESS! In order to get the Keyboard Accelerator to work, the submenu with the **MenuFlyoutItem** needed to be open in the UI, so I could view the actual accelerator! This cannot possibly be what is expected of a true keyboard accelerator under UWP!

**Comment by Karl-Bridge-Microsoft** [comment]
@sjointer - I have reproduced the same behavior and have reached out to the feature team for more details.

**Comment by marb2000** [comment]
@sjointer, @Karl-Bridge-Microsoft, We are working on fixing this bug for MenuFlyouts. Unfortunately it won't be available until the 19H1 release.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @marb2000. 

@sjointer: Closing issue. Please re-open if 19H1 doesn't address your concerns. Thanks for your feedback!

**Comment by sjointer** [comment]
Fixing the issue is fine with me. I'm patient.

**Comment by Panda-Sharp** [comment]
Hi Guys,

I have a problem that I think is related to this one, I waited to try with latest SDK (18362) to check if it was fixed, but it's still there , here there is my XAML code

 ```
<StackPanel>

        <TextBox Header="TextBox"/>

        <PasswordBox Header="PasswordBox"/>

        <Button Content="Butotn" Click="Button_Click">
            <Button.KeyboardAccelerators>
                <KeyboardAccelerator Key="Enter" />
            </Button.KeyboardAccelerators>
        </Button>

    </StackPanel>
```

when I'm inside the textbox  or the passwordbox and I press enter on the keyboard the click event is not fired.
thanks
