### ISSUE TITLE
Hide UWP app

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#810]
How can I hide the extended UWP app so it won't be established as an app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba89d6c-71c3-4583-8d7f-8db231a96b07
* Version Independent ID: ce5b525b-597c-0859-ed9c-aa3104498b8b
* Content: [Extend your desktop application with Windows UIs and components - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-extend#create-a-background-task)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-extend.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-extend.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by pqcuong99** [comment]
How to hide a UWP app while it's running
