### ISSUE TITLE
Customize NavigationView panel to include image

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/windows-uwp#813]
Can we add large image within menuitems or above menu items.

Question [reference](https://stackoverflow.com/questions/51446728/customize-navigationview-panel-to-include-image-uwp)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Looks like you received an answer on StackOverflow - nice! - so I'm closing the issue.

**Comment by pmahend1** [comment]
@serenaz Can you please update documentation mentioning NavigationMenuitem dimension being defaulted to 40 and how can one customize it?
