### ISSUE TITLE
Compiling Tutorial in Debug mode INSTALLS THE PROGRAM!

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/windows-uwp#814]
I compiled this program sometime over the past couple of days in Debug mode, and then started making small changes to get used to some concepts, both from the Layout panels trail and a couple of other trails I'm reading out of order.

Today, when I opened by Start menu in Windows 10, and scrolled through, I found that the program was considered installed.  It ran independently of Visual Studio 2017 (Community Edition), and acted exactly as the tutorial.

I right-clicked on the item, choose "Uninstall", then opened Visual Studio, and compiled the example again.  BEHOLD!  It was back on the Start Menu for Windows 10 as if I had installed the program!

I found that this wasn't the only one, either.  Other tutorials were also installed, as well as the actual program I want to create and I'm learning UWP/XAML for.

1. How is this messing with the registry?
2. Is there a compile option that doesn't install the program on my local machine every time I compile?
3. When was this introduced, and where is the discussion of this being introduced?
4. Is it true that the program or class library will auto install on compile for other UWP/Managed Class project types?
5. Is it true that programs now auto install on compile for non-UWP/non-managed types?  Will this happen if I write Windows Desktop projects, or C++-family projects?

Auto installing is, frankly, disturbing and a possible security risk, especially for universities that have Windows 10 and are teaching programming using Visual Studio (I used to be a professor).  Okay, I'll go one bit further...this ***IS*** a major security risk!  It's possible to introduce malicious code to a machine simply by compiling managed code on a computer that has been left idle for even a brief period of time!

Please post how to prevent the install or fix Visual Studio 2017/Windows 10 so the auto install doesn't occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be62a3e3-7b89-7fae-01a4-050ac555c568
* Version Independent ID: 603de397-854a-7714-e795-862b8cee9074
* Content: [Use Grid and StackPanel to create a simple weather app. - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/grid-tutorial)
* Content Source: [windows-apps-src/design/layout/grid-tutorial.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/grid-tutorial.md)
* Product: **windows**
* GitHub Login: @muhsinking
* Microsoft Alias: **mukin**

**Comment by GrantMeStrength** [comment]
Hi -

This is totally "by design" behavior, and has been for several years now. There is no security risk.

https://blogs.msdn.microsoft.com/windowsappdev/2012/12/04/designing-a-simple-and-secure-app-package-appx/

-John

**Comment by sjointer** [comment]
I understand that it's by design.

Steps to violate security...and this is just off the top of my head; I haven't actually done this.

- Create a standard user account with no password OR no screen locking
- Install VS 2017
- Write a UWP App that either
    1. contains a WebView that links to a malicious website, OR
    2. contains actual malicious code.
- Compile the app, allowing it to install on my user account (I **assume** that the install is only to the currently logged in account)
- Shut off Visual Studio.
- Run the app from the Start menu.

That should be enough to run malicious code under the account that created the app.  This scenario may seem far fetched, but logging into a machine that doesn't lock and then walking off to talk to friends or hit on the "hot chick" that walked into the computer lab happens regularly on college campuses.

Is there a way to disable this behavior?

**Comment by GrantMeStrength** [comment]
But what you are saying is that if I write malicious code on my own computer through my own choice and run it, then I've malicious code running on my machine. :-)

OK, yes, I get what you are saying and I'm not trying to be flippant, but remember: in order to develop code on a Windows computer you have to switch on Developer Mode, and with that power comes with great responsibility.

Here's my recommendation. If you don't want to run the risk of dangerous code, you could use Visual Studio from within a Virtual Machine. In fact, if you are running development machines in a shared environment I would go so far as to say you **really, really should** look at using VMs, as they will allow you to configure development environments, share them, reset them and not have to worry about malicious code.

Hope this helps. Let me know if I can provide more information.

**Comment by OmPisit** [comment]
I feel like your opinion. The answer is really good. The app itself is also afraid to install in itself. I will not let anyone else install it.
