### ISSUE TITLE
StoreLogo image doesn't displayed on Part3.

### ISSUE THREAD

**Issue by freedom8888** [MicrosoftDocs/windows-uwp#815]
When i use "The final template" of part3, 
StoreLogo.png doesn't displayed.
Xaml of Image control is like below.
&lt;Image x:Name="ItemImage"
           Source="Assets/StoreLogo.png"
           Stretch="Uniform" /&gt;

But when modified Source attribute like below, 
StoreLogo displayed.
Source="/Assets/StoreLogo.png"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc1c132-3cfa-1a08-0726-214110c8d23d
* Version Independent ID: 7ddf3871-c4a1-ae0a-9c03-25ccf4934cf2
* Content: [Create a user interface tutorial - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-ui#)
* Content Source: [windows-apps-src/design/basics/xaml-basics-ui.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-ui.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
The relative path should work. What OS version are you running on?
