### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by pertho396gmail** [MicrosoftDocs/windows-uwp#817]
perthochowdhury45@outlook.com
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5573dd-ecf2-b49d-b853-dfd1a5b3c1f4
* Version Independent ID: 123ad670-6099-ad69-6012-92482586903e
* Content: [Handle file activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-file-activation)
* Content Source: [windows-apps-src/launch-resume/handle-file-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/handle-file-activation.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by pertho396gmail** [comment]
Mr #817

**Comment by ginami** [comment]
Hi @pertho396gmail -- let us know if you have any feedback on out docs. Thanks!
