### ISSUE TITLE
OnProcessKeyboardAccelerators example method error

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/windows-uwp#818]
The method given in the example causes infinite recursion, ending with a StackOverflowException.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e18e09-9873-66b8-65d1-36031d51198d
* Version Independent ID: d8089561-12ca-fcf0-2dc8-3d678cc1f6f2
* Content: [Keyboard accelerators - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators#custom-keyboard-accelerator-behavior)
* Content Source: [windows-apps-src/design/input/keyboard-accelerators.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-accelerators.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@sjointer - I couldn't identify the specific issue you identify as the function called in the example isn't defined in the snippet. That said, I did update the snippet to replace the function call with actual code. Perhaps you were running an insider's version that had a bug. Please reactivate the issue with more detail if you still encounter issues. Thanks for the feedback!
