### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by toncho11** [MicrosoftDocs/windows-uwp#819]
How much time does it take for a single (addon) sale to be reflected in "Current proceeds and payments"?
I see I have an addon sale but one day later I still do not see it reflected in the "Current proceeds and payments"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b80a63-ba2e-ea74-83d3-c63fa1d4904f
* Version Independent ID: 5e8b56c6-a964-1d5d-c040-55254e582da8
* Content: [Payout summary - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I'm sorry for the delay in responding. For most transactions, earnings are posted within a day or two. If you don't see the earnings reflected after 7 days, you should open a request at http://aka.ms/storesupport so that we can investigate.
