### ISSUE TITLE
Three years now and I'm still put off

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/windows-uwp#824]
testing and signing and the whole caboodle is still as confusing and onerous as hell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daac3c60-f91f-4065-d0c5-9ce5c836cb71
* Version Independent ID: 9d897adb-51b9-fbd5-727f-c896d41039dc
* Content: [Test your Windows app for Windows 10 S - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-test-windows-s)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-test-windows-s.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-test-windows-s.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you for the feedback. I'm sorry it's frustrating. Is there something in this specific topic that your finding misleading? Thx!
