### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by Jaykaydre** [MicrosoftDocs/windows-uwp#827]
There are some grammatical error on this page. Example, the flat/lateral definition and the combining structures definition... Many more on this page too...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1426ac-9a20-b0a3-0ebd-8ce4b2a50882
* Version Independent ID: 771f2efb-f781-ed49-5ff0-5c95f2bc4868
* Content: [Navigation basics for UWP apps - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/design/basics/navigation-basics)
* Content Source: [windows-apps-src/design/basics/navigation-basics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-basics.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Fixed - thanks for the catch!
