### ISSUE TITLE
CPU inference with C++  using WinML apps

### ISSUE THREAD

**Issue by mrsabhar** [MicrosoftDocs/windows-uwp#830]
Is there plan to support CPU interface with C++ sample using WinML? I am able to create device with DX12 using CreateEvaluationContext api but currently it binds only to DX12 ? Is there preview doc shows C++ CPU interface (similar to PreferredDeviceKind Property in C#)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab995399-9262-ebc0-ec18-2cdc251b3353
* Version Independent ID: 25ff5431-d7f1-deb2-969a-87534990c09c
* Content: [Windows ML - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/)
* Content Source: [windows-apps-src/machine-learning/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/index.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Yep, you can create a [LearningModelDevice](https://docs.microsoft.com/uwp/api/windows.ai.machinelearning.learningmodeldevice) with a [LearningDeviceKind](https://docs.microsoft.com/uwp/api/windows.ai.machinelearning.learningmodeldevicekind) of type CPU
