### ISSUE TITLE
So....where does a storyboard go?

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/windows-uwp#834]
The documentation would have been much more useful if, the first time you introduce the "storyboard", you provide the recommendation for where they go! As it is, you've got a snippet of XAML that, when pasted into a normal XAML file, will not work at all!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399a8cb7-9752-283a-54a8-00c44e7a747d
* Version Independent ID: 0c212d44-3405-1710-05e4-3e35b0e3fbd6
* Content: [Storyboarded animations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/motion/storyboarded-animations)
* Content Source: [windows-apps-src/design/motion/storyboarded-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/storyboarded-animations.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@PeterSmithRedmond, thanks for the feedback. The 'Defining a storyboard as a resource' section of the article explains more about where to put the storyboard. However, I agree that this should be included with the first code snippet , too. I've submitted an update to provide this context in the first snippet.

**Comment by PeterSmithRedmond** [comment]
While you’re at it – as it turns out, you can’t actually animate everything. For example, you can’t animate the FontSize property of a TextBox ☹

Peter
