### ISSUE TITLE
Typo: RoutedEventArgs => RouteEventArgs 

### ISSUE THREAD

**Issue by Dooskington** [MicrosoftDocs/windows-uwp#835]
In the first code snippet of Step 4, RoutedEventArgs is misspelled as RouteEventArgs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by jwmsft** [comment]
This issue has been fixed.
