### ISSUE TITLE
Desktop App Converter .net failures when installing/converting a Win32 app in a VM, v. 17134

### ISSUE THREAD

**Issue by ddbb2017** [MicrosoftDocs/windows-uwp#836]
Please check SO link for details:
[https://stackoverflow.com/questions/51437203/desktopappconverter-woes-windows-10-v-17134](https://stackoverflow.com/questions/51437203/desktopappconverter-woes-windows-10-v-17134)

**Comment by ginami** [comment]
Hi @ddbb2017 -- it looks like you've got a Microsoft employee helping you via your SO post. Are you posting the issue here because we need to update one of our docs? If so, could you please give me the URL of the related doc?
Thank you!

**Comment by ginami** [comment]
Hi @ddbb2017 -- I'm going to close out this issue. If you have updates for our docs, let us know. Thank you!

**Comment by ddbb2017** [comment]
@ginami no, I'm posting it here so that Microsoft fixes their g-*-dd-*-m UWP converter. I wasted 7 days to convert my app for the Windows store. Don't you think that is the reason why the only thing Windows store has is a crickets sound.

Anyway, that Microsoft employee did nothing. The resolution to this issue is indeed in that SO thread. It was way more simple -- to disable  "Real-time protection" in the "Virus & threat protection settings".

But is it really a fix???
