### ISSUE TITLE
Extra Text in "Asset package" paragraph

### ISSUE THREAD

**Issue by dwcullop** [MicrosoftDocs/windows-uwp#841]
The paragraph that describes "Asset packages" has a nearly duplicate sentence that can be removed:
     
&gt; For example, this might include a collection of pictures in one asset package, and videos in another asset package, both of which are used
&gt; by the app. For example, this might include a collection of pictures in one asset package, and videos in another asset package. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a43e99-2699-6568-6d37-6fe72286ae3c
* Version Independent ID: dfe8c8e7-a573-32e0-cb6c-efbdadc9b00f
* Content: [Extend your app with services, extensions, and packages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/extend-your-app-with-services-extensions-packages)
* Content Source: [windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
