### ISSUE TITLE
'await' operator issue

### ISSUE THREAD

**Issue by juancols** [MicrosoftDocs/windows-uwp#842]
After following the tutorial and hit run, I've got this error message:

" Error CS4033	The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'. "

Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
The code is correct. Once you add an **await** call to a method, you must change the method to be **async** so that it doesn't block waiting for the **await** call. 

If you _don't_ have an **await** call in the method, you don't need to make it an **async** method.

Hope this helps.

**Comment by juancols** [comment]
Thank you Grant, I appreciate your help!
