### ISSUE TITLE
zz

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/windows-uwp#843]
z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc0a5dcc-6984-5f19-7fa7-345e4b5247d3
* Version Independent ID: dfafa9b9-6d06-dcab-b90b-718f4ac04c7f
* Content: [UWP on Xbox One - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/index)
* Content Source: [windows-apps-src/xbox-apps/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/index.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mstahl**

**Comment by ginami** [comment]
hi @Sleeplikelion -- let us know if you have feedback on our docs.
