### ISSUE TITLE
Combining EntranceNavigationTransitionInfo with EntranceThemeTransition

### ISSUE THREAD

**Issue by sjb-sjb** [MicrosoftDocs/windows-uwp#844]
I searched in vain for information on how to customize the EntranceNavigationTransitionInfo. Then I tried this and it worked. 

                <Frame.ContentTransitions>
                    <TransitionCollection>
                        <EntranceThemeTransition
                            FromHorizontalOffset="16"
                            FromVerticalOffset="0"
                            >
                        <EntranceThemeTransition>
                        <NavigationThemeTransition>
                            <SuppressNavigationTransitionInfo/>
                        <NavigationThemeTransition>
                    </TransitionCollection>
                </Frame.ContentTransitions>

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70caee7e-f3f7-a156-a0a2-bc39f304cbdc
* Version Independent ID: 00714360-83d8-554f-e4c2-c66926e270fb
* Content: [Page transitions in UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/motion/page-transitions)
* Content Source: [windows-apps-src/design/motion/page-transitions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/motion/page-transitions.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Thanks for the note! Adding it to the `EntranceNavigationTransitionInfo` API.

**Comment by sjb-sjb** [comment]
@serenaz, recently I found out that the workaround above doesn't work so well. The SuppressNavigationTransitionInfo and the EntranceThemeTransition may not execute in the correct order, resulting in sometimes works, sometimes doesn't! 

One should specify new SuppressNavigationTransitionInfo() in the call to Frame.Navigate, then separately put the EntranceThemeTransition in the content TransitionCollection.

sjb
