### ISSUE TITLE
Publisher Display Name Question

### ISSUE THREAD

**Issue by CraigAtMidmark** [MicrosoftDocs/windows-uwp#845]
Can you change your Publisher Display Name after creating a developer account type?  I don't see this documented anywhere in this post.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a5c98-ba0b-38a0-d86e-2d5df4745d1a
* Version Independent ID: 643673cc-0b57-86f6-e00d-13aad2ef8d20
* Content: [Opening a developer account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account#the-account-signup-process)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Sorry to take so long to respond. You can change this name if you need to. The process is described at https://docs.microsoft.com/windows/uwp/publish/managing-your-profile#contact-info.
