### ISSUE TITLE
Request for Rating causes an error in Windows Store app

### ISSUE THREAD

**Issue by BillCowell** [MicrosoftDocs/windows-uwp#847]
I am adding a request for rating in my app using

bool result = await Windows.System.Launcher.LaunchUriAsync(new Uri("ms-windows-store://review/?ProductId=XXXXXXXXXX"))

The rating dialog opens in Windows Store App but when the user cancels the rating dialog an error message, code  0x80073CFB, is shown in the Windows Store app. Is there a way to avoid this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291dc819-9b43-818a-f839-f69d0a0b432e
* Version Independent ID: d6cfeb3b-dd87-e0df-95a2-8b1d282f24a3
* Content: [Request ratings and reviews for your app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/request-ratings-and-reviews)
* Content Source: [windows-apps-src/monetize/request-ratings-and-reviews.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/request-ratings-and-reviews.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're running into this issue. Just to be clear, are you seeing this error when passing an actual product ID for an app in the Store? I'm not seeing this error with a real product ID.

**Comment by BillCowell** [comment]
Yes, I am passing an actual product ID for an app in the Store. However, trying again this morning after rebooting my PC the issue has gone away and the routine works as expected. Apologies for the false lead.

**Comment by BillCowell** [comment]
Yes, I am passing an actual product ID (9WZDNCRDND5T) for an app in the Store. However, trying again this morning after rebooting my development PC the issue has gone away and the routine works as expected. Apologies for the false lead. And thank you McLean for the quick response.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
