### ISSUE TITLE
Change the trial period on subscription add ons

### ISSUE THREAD

**Issue by hannahpewter** [MicrosoftDocs/windows-uwp#848]
Is there any way I can do this without having to re add a new add on?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df3fc61-cd09-1c65-a2aa-7c6849488688
* Version Independent ID: 63719300-f46f-a232-a5f9-3dfee9206d3a
* Content: [Enter add-on properties - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/publish/enter-add-on-properties)
* Content Source: [windows-apps-src/publish/enter-add-on-properties.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/enter-add-on-properties.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Unfortunately after your add-on is published, you can't change your Free trial selection.
