### ISSUE TITLE
activities 

### ISSUE THREAD

**Issue by Sleeplikelion** [MicrosoftDocs/windows-uwp#853]
nop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03829a62-ce3b-910e-2738-917069fba449
* Version Independent ID: a18b2869-ea37-956f-bdcc-800ac52ae350
* Content: [Getting started - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/getting-started#useful-links)
* Content Source: [windows-apps-src/gaming/getting-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/getting-started.md)
* Product: **windows**
* GitHub Login: @joannaleecy
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @Sleeplikelion -- let us know if you have any docs feedback.
