### ISSUE TITLE
Would like to see a toolkit for Affinity Designer

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/windows-uwp#856]
As a user of Affinity Designer I'd like to have a version of the UI kit for Affinity Designer. It is a nice design program and I believe it is the only serious design program available through the Microsoft Store.

There is a user-created version available at https://github.com/chrisg32/AffinityDesignerUWPAssets but unfortunately that is outdated - it would be great if you could maintain an up-to-date version!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d9fc7b1d-8b97-598a-f059-093d94972931
* Version Independent ID: 943e9c97-f223-4d3c-730c-a7f20cb04560
* Content: [Design toolkits and samples for UWP apps - UWP app developer](https://docs.microsoft.com/nl-nl/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for the feedback, @wind-rider! I've passed your request on to our Design Toolkits team.

**Comment by hansmbakker** [comment]
Thank you!

**Comment by hansmbakker** [comment]
@mijacobs (I changed my GitHub handle) if there is any news to this request, will that be posted somewhere where we can follow it?

**Comment by mijacobs** [comment]
@hansmbakker I heard back from the design team--there aren't any plans to develop a UI toolkit for Affinity Designer at this time. If they do end up creating a toolkit, they'll post it here. They are creating a Figma toolkit (I don't have an ETA yet, but it should be soon).
