### ISSUE TITLE
Only work with included model ??

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#857]
when I run [this sample](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Samples/UWP/MNIST) no err everything look normal but when I change model.onnx with [model from this link ](https://github.com/onnx/models/tree/master/mnist) then boom ![image](https://user-images.githubusercontent.com/7003205/43486699-c4308f82-9529-11e8-8239-a2b6d4c55126.png) so I tried to compare this two model and what I got 
![image](https://user-images.githubusercontent.com/7003205/43486817-0893313e-952a-11e8-81ec-db53528f2665.png) so why this happen is really Microsoft MNIST sample model.onnx file dif from 
zoo model.onnx huh ?

**Comment by serenaz** [comment]
The sample uses Windows.AI.MachineLearning.Preview APIs, which use ONNX v1.0 models. The ONNX model zoo has been updated to v1.2.2. We're updating all the samples to use the new Windows.AI.MachineLearning APIs, which use ONNX v1.2. The samples should be updated by tomorrow!
