### ISSUE TITLE
Fluent Design and JS UWP Apps

### ISSUE THREAD

**Issue by AngelMunoz** [MicrosoftDocs/windows-uwp#859]
Hello, are we ever going to have a JavaScript version of any of this? 
Since WinJS is not being maintained anymore (contrary to what the readme says there are PR that have been siting for months and even the official website now redirects to GitHub)
It would be nice that JavaScript Apps For the UWP Platform had this too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fc7b1d-8b97-598a-f059-093d94972931
* Version Independent ID: 943e9c97-f223-4d3c-730c-a7f20cb04560
* Content: [Design toolkits and samples for UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@AngelMarshall  Thanks for the feedback. I'm not aware of any plans to update WinJS. If you'd like to reach the engineering team implemented Fluent Design for UWP, you can open an issue here:
https://github.com/Microsoft/microsoft-ui-xaml

**Comment by AngelMarshall** [comment]
Hi,

I guess you meant to mention https://github.com/AngelMunoz ?

**Comment by mijacobs** [comment]
Yes, I did--thank you.
