### ISSUE TITLE
"Query for products" & "Get Subscription for a user" return empty json lists?

### ISSUE THREAD

**Issue by cpparkin** [MicrosoftDocs/windows-uwp#860]
Successfully placed purchase using &lt;StroreProduct&gt;.RequestPurchaseAsync();
Can locate active subscription as a "durable add-on" in results of &lt;StoreContext&gt;.GetAppLicenseAsync();
However, when using the REST API, both "Query for products" & "Get Subscription for a user" return an empty json list;
{
    "items": []
}
Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bdee9e-2095-4423-62c5-0beb5520dfd3
* Version Independent ID: fad19d6f-2fa3-ff54-925a-020fe65cadbc
* Content: [Manage product entitlements from a service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Hello - Please use one of the developer support options at [https://developer.microsoft.com/en-us/windows/support](https://developer.microsoft.com/en-us/windows/support) for assistance (this repo is for the docs, and isn't an official support channel). That said, here are a few things you might want to check:
- Make sure you [created two different Azure access tokens with the necessary audience URIs](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#step-3-create-azure-ad-access-tokens) and you are using each token with the correct API call.
- Make sure you created the Microsoft Store ID key in the context of your client app while the user who purchased the subscription is signed in to the Store.
