### ISSUE TITLE
Wrong URL in example for extending subscription

### ISSUE THREAD

**Issue by bezysoftware** [MicrosoftDocs/windows-uwp#861]
It should be https://purchase.mp.microsoft.com/v8.0/b2b/recurrences/{recurrenceId}/change

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6f5f94-6f63-e18a-673c-b8c4fac73dea
* Version Independent ID: c094c841-0477-362a-1070-cedba080f57e
* Content: [Change the billing state of a subscription for a user - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/change-the-billing-state-of-a-subscription-for-a-user)
* Content Source: [windows-apps-src/monetize/change-the-billing-state-of-a-subscription-for-a-user.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/change-the-billing-state-of-a-subscription-for-a-user.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this. I have fixed the request example in the article.
