### ISSUE TITLE
Flaw in the Paginate event handler in the Print feature

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#863]
Hello,

In the event handler of Paginate, my app needs to do some awaitable calls in order to generate the content to print. The issue when the await call is called is the event handler GetPreviewPage is called **before** the Paginate page to be completed.

I can repro this in the Print sample here inserting a await Task.Delay(400) in AddOnePrintPreviewPage.

Would love to know if it is a bug or if I'm missing something.

Thank you

Sébastien
MVP Windows Development

**Comment by jevansaks** [comment]
What documentation page were you having an issue with? Sounds like maybe you're trying to report a product bug.

**Comment by ArchieCoder** [comment]
I found a workaround. The issue can be closed.
