### ISSUE TITLE
Cant show pdf in pdf.js in uwp

### ISSUE THREAD

**Issue by omar201816** [MicrosoftDocs/windows-uwp#865]
Hi.
I've been using pdf.js and a weibiew render to show a pdf or word file in UWP; in Release and Debug mode if it works, but when I generate the .appxbundle and install the application, I get a damaged Access error when trying to move the file from the local storage to the assets folder of the project.

The code to save the pdf:

// create file in public folder
StorageFolder storageFolder = ApplicationData.Current.LocalFolder;
StorageFile sampleFile = await storageFolder.CreateFileAsync (filename, CreationCollisionOption.ReplaceExisting);

// write sring to created file
await FileIO.WriteBytesAsync (sampleFile, bytes);

// get asets folder
StorageFolder appInstalledFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
StorageFolder assetsFolder = await appInstalledFolder.GetFolderAsync ("Assets");

// move file from public folder to assets
await sampleFile.MoveAsync (assetsFolder, filename, NameCollisionOption.ReplaceExisting);
str = sampleFile.Name;
The code for the webview route:

Control.Navigate (new Uri (string.Format ("ms-appx-web: ///Assets/pdfjs/web/viewer.html? File = {0}", string.Format ("ms-appx-web: / // Assets / {0} ", WebUtility.UrlEncode (customWebView.Uri)))));
As I mentioned before, the pdf is seen in release mode and in debugu mode, but when I install the package application it marks me the error of 'access denied'; In the capabilities of my application I have everything that has to do with storage installed in my app. I would like to know how to solve this error.

I have tried to show the PDF without moving it to the Assets folder, but it is not charged at PDF.js.

Do you know the correct way to display the PDF using pdf.js by storing it in a folder that is not in the package, or know any way to display it without using the application by default for the file (with PDF.js I can show pdf and Word documents in some way? (el componente renderiza los archivos word)?

Please, I need your help, I have already implemented the viewfinder on IOS and Android, uwp is the only platform where not I've been able to implement it, I already posted on a forum for Microsoft and there was no response. Already walked all the posts and no response I worked.

Thank you in advance.

**Comment by mikematteson** [comment]
@omar201816 : Thanks for reaching out to the Windows Developer Documentation team. Unfortunately, we don’t have the resources here to offer individual technical advice to the broad array of customers who use the documentation. 

You mentioned that you already posted your question to a forum but received no answers. If you'll provide a link to that post (so we can see which forum it's in), I'll see if I can get some info for you about other places to try to get an answer.
