### ISSUE TITLE
Pane > Left Nav > References don't match the items in the picture

### ISSUE THREAD

**Issue by rbeesley** [MicrosoftDocs/windows-uwp#866]
Menu Button is listed as Nav Items, Nav Items are listed as something else, etc. Seems like Menu Button was attributed as 6 in the list when it should have been 1, and all references which follow are off by one. 0/1 index problem? :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Fixed - thanks for the catch!
