### ISSUE TITLE
Improve discoverability of x:Load

### ISSUE THREAD

**Issue by pingzing** [MicrosoftDocs/windows-uwp#87]
The [x:Load markup extension](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-load-attribute) isn't listed in the sidebar with the other markup extensions. I just learned about its existence today--I'd been using x:DeferLoadStrategy!

Screenshot of the sidebar in question: 
![sidebar](https://cloud.githubusercontent.com/assets/5133649/25964706/6dc961a0-368e-11e7-9192-fd422956b6c3.png)

**Comment by mattwojo** [comment]
Thanks for bringing this to our attention @pingzing!  

@jwmsft -- I just submitted a PR to add this missing attribute to the TOC and listed you as a reviewer: https://cpubwin.visualstudio.com/_git/windows-uwp/pullrequest/1519?_a=overview 

I gave the content a brief sweep and didn't see anything else missing, but may be worth one more look.

**Comment by mattwojo** [comment]
@pingzing -- The page is updated with that x:load link now -- thanks again! Please let us know if you see any other issues or improvement areas.

![image](https://cloud.githubusercontent.com/assets/7566797/26226350/b06659bc-3be0-11e7-9249-1e8dd7265865.png)
