### ISSUE TITLE
How to consume the converted model from CoreML with image input/output?

### ISSUE THREAD

**Issue by JohnMasen** [MicrosoftDocs/windows-uwp#870]
I found this topic mentions that the data buffer should be manipulated before you can use it. however the generated wrap class uses VideoFrame with does not support BGR format( an exception will be thrown if you try to evaluate the model).  any examples for how to consume this kind of model would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c28f709-f39f-51e1-dbd6-049496ec9b8d
* Version Independent ID: b2a668cf-c3b8-2236-2f6c-0e876f4393a0
* Content: [Convert existing ML models to ONNX - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/machine-learning/conversion-samples)
* Content Source: [windows-apps-src/machine-learning/conversion-samples.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/machine-learning/conversion-samples.md)
* Product: **windows**
* GitHub Login: @wschin
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Which API version are you using? [Windows.AI.MachineLearning.ImageFeatureValue](https://docs.microsoft.com/uwp/api/windows.ai.machinelearning.imagefeaturevalue
) should support BGR format.

**Comment by JohnMasen** [comment]
I checked the api you provided, it seems only available on insider preview [Windows 10 Insider Preview (introduced v10.0.17709.0) ]. I'm using the public version under "Windows.AI.MachineLearning.Preview" namespace.

**Comment by eliotcowley** [comment]
Hi @JohnMasen, many apologies for the delay on this. Now that [Windows.AI.MachineLearning](https://docs.microsoft.com/uwp/api/windows.ai.machinelearning) has been fully released publicly, have you tried again with the current APIs? The ones you were using were preview APIs.

**Comment by eliotcowley** [comment]
Closing due to lack of response. @JohnMasen please feel free to re-open if you're still having this issue.
