### ISSUE TITLE
I often meet an error called "REGDB_E_CLASSNOTREG Class not registered"

### ISSUE THREAD

**Issue by cjw1115** [MicrosoftDocs/windows-uwp#873]
this is my model IDL

    namespace BlankApp1
    {
        runtimeclass  Model : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.INotifyPropertyChanged
        {
            Model();
            String Title;
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4db0aab-b906-9dec-381c-ceccc1e90c45
* Version Independent ID: 493a4c50-ffa1-5e32-c757-92306c952887
* Content: [XAML controls; bind to a C++/WinRT property - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @cjw1115, that error can happen if you instantiate a locally-implemented runtime class via the projected type's default constructor. For example, if you declare a field like this:

```cppwinrt
private:
    BlankApp1::Model m_model; // This attempts to call the projected type's default constructor, which won't work if you've declared BlankApp1::Model in the same project, because that type is not registered.
```

Instead, do this:

```cppwinrt
private:
    BlankApp1::Model m_model{ nullptr }; // This calls a special constructor on the projected type, which doesn't attempt to activate the runtime class (hence it needn't be registered).
```

And then assign a value to that field later like this:

 ```cppwinrt
m_model = winrt::make<BlankApp1::implementation::Model>(); // BlankApp1::implementation::Model is the implementation type, but winrt::make returns the projected type. Again, this succeeds without the type needing to be registered.
```

The topic in question shows this same pattern. And the [Troubleshooting](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/troubleshooting) topic indicates other reasons you might be seeing REGDB_E_CLASSNOTREGISTERED.

**Comment by cjw1115** [comment]
It works well after I correct my code as you described. Thanks a lot~

**Comment by stevewhims** [comment]
Great! Thanks, @cjw1115. ~Steve
