### ISSUE TITLE
Package page error

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#875]
I am using Microsoft Partner dashboard and I always see an unknown error.
Error details:
Status: Unknown Error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0098ee34-7905-a879-190b-10f783f638a6
* Version Independent ID: beb7fc7d-233c-5a15-a9a6-ffe86639527c
* Content: [Upload app packages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/upload-app-packages)
* Content Source: [windows-apps-src/publish/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/upload-app-packages.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
It's hard to know what's happening without more info. Which page or area shows this error?

**Comment by JnHs** [comment]
I'm going to close this issue out now - if you still need help with the error you can open a support request at http://aka.ms/storesupport, or if you have additional documentation feedback please let us know!
