### ISSUE TITLE
Typos in code samples (possibly symptomatic of systematic issue?)

### ISSUE THREAD

**Issue by Jace-Samsung** [MicrosoftDocs/windows-uwp#878]
Hi, just thought you might want to update the code samples as a few characters are missing.  There are five instances on this page where a IReadOnlyList is declared incorrectly.
For example, the line:
IReadOnlyList&lt;StorageFilefileList = await picturesFolder.GetFilesAsync();
should be:
IReadOnlyList&lt;StorageFile&gt; fileList = await picturesFolder.GetFilesAsync();

You might want to check that something is not systematically removing the "&gt; " character sequence from the code samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51591798-4020-169a-d74d-c5bd31bb88dc
* Version Independent ID: 65327a75-003c-5642-b4ff-257dbd92e697
* Content: [Enumerate and query files and folders - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-listing-files-and-folders)
* Content Source: [windows-apps-src/files/quickstart-listing-files-and-folders.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-listing-files-and-folders.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by samwhaleIV** [comment]
This seems to be an isolated situation (possibly a failed IDE refactoring?) The C++ on the same page contains directives and vectors with properly matched guillemets (I had to look for this word up for the < and > symbols)

**Comment by jwmsft** [comment]
This issue appears to be fixed.
