### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#879]
I inserted the test application ID and ad unit ID but nothing displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fd9d37-275b-9fd4-1455-345221f197b9
* Version Independent ID: 721e5075-0a0d-e3a2-7c10-d9ac9496a782
* Content: [AdControl in XAML and .NET - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/adcontrol-in-xaml-and--net#release-your-app-with-live-ads)
* Content Source: [windows-apps-src/monetize/adcontrol-in-xaml-and--net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/adcontrol-in-xaml-and--net.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're running into difficulties. I just tested the steps and code in this article again and was able to see a test ad when I ran the app. Can you confirm that you're following all the instructions from the article?

**Comment by mcleanbyron** [comment]
Because there has been no further reply to this issue, I am closing it for now. Please feel free to reopen it if you have more details to share.
