### ISSUE TITLE
IsEnabled="True"

### ISSUE THREAD

**Issue by dmitrymal** [MicrosoftDocs/windows-uwp#880]
I cannot find the IsEnabled property on the AdControl class. This property is not listed here https://docs.microsoft.com/en-us/uwp/api/microsoft.advertising.winrt.ui.adcontrol either.
Am I missing something? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ea0e63-613e-2f74-6343-6d8b766efcad
* Version Independent ID: 130766a9-b725-0797-9cdb-aa8f828a1413
* Content: [XAML and C# troubleshooting guide - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/xaml-and-c-troubleshooting-guide#c)
* Content Source: [windows-apps-src/monetize/xaml-and-c-troubleshooting-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/xaml-and-c-troubleshooting-guide.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Good catch, thanks for reporting this. No IsEnabled property currently exists for AdControl. I have removed those references to it from the article you mentioned, and those doc changes should go live tomorrow.
