### ISSUE TITLE
No Account settings option in gear icon

### ISSUE THREAD

**Issue by Sashwat** [MicrosoftDocs/windows-uwp#883]
I am not able to associate AAD with my dev center account. The link sends me to partner.microsoft.com. I am logged in through the email id by which I created dev center account. But there's no account settings option in gear icon

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262768e8-ad91-7af3-1541-4f2d2f9de5ba
* Version Independent ID: cc035cc8-ce25-57c4-2d2d-389451442d98
* Content: [Associate Azure Active Directory with your Dev Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-dev-center)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-dev-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-dev-center.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
It may be listed as "Developer settings". If so try selecting that, then look for "Tenants". If you don't see it, you may also need to go to your login (name/photo in top right corner), select it, and then select your account name. If this doesn't resolve the issue I would suggest contacting support via http://aka.ms/storesupport.

**Comment by Sashwat** [comment]
Nope, none of those options are there. It doesn't seem like UI is working as per instructions laid out in this doc

**Comment by JnHs** [comment]
Thanks for letting us know. I'll try to confirm the behavior and make any needed updates. In the meantime I'd recommend opening a support request so that you can access the functionality.

**Comment by Sashwat** [comment]
Resolution if anyone runs into this in future -

I had apparently created Dev Center account only for "Azure" via this link - https://partner.microsoft.com/en-us/dashboard/registration?accountProgram=Azure  

Following that link doesn't get "Windows" program associated with your account. You should actually be following this link - https://partner.microsoft.com/en-us/dashboard/registration 

There was no way to fix this from within the dev center as just adding "Windows" program didn't work. Now why does this have to be so confusing - AAD cannot be linked with "Azure" program only "Windows", or why you have to still do these two separately - who knows!
