### ISSUE TITLE
Developers and VS may get confused with namespace Microsoft.UI.Xaml.Controls and Windows.UI.Xaml.Controls

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#885]
Developers may get confused with namespace Microsoft.UI.Xaml.Controls and Windows.UI.Xaml.Controls

In your [samplecode](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#code-example) at first you say need to add a reference to the toolkit: `xmlns:controls="using:Microsoft.UI.Xaml.Controls"`.

But in the following xaml code,
```
<NavigationView x:Name="NavView"
                    SelectionFollowsFocus="Enabled"
                    ItemInvoked="NavView_ItemInvoked"
                    IsSettingsVisible="True"
                    Loaded="NavView_Loaded"
                    BackRequested="NavView_BackRequested"
                    Header="Welcome">
..........
```
Why use NavigationView, not **controls:NavigationView** ???

And in .cs code, you say add a reference to the toolkit: `using MUXC = Microsoft.UI.Xaml.Controls;`
You use
`private void NavView_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)`
not 
**`private void NavView_ItemInvoked(MUXC.NavigationView sender, MUXC.NavigationViewItemInvokedEventArgs args)`**

If using your provided code, developers and VS compiler get confused, and lead to a wrong way.

Hope to revise the doc, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by jwmsft** [comment]
The article has been updated and this issue is addressed.
