### ISSUE TITLE
Missing icons after F624 (e.g. FF09, FF12, FF17, FF35)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windows-uwp#889]
I've noticed when poking around in Chrome's Developer Tools here on the docs site, there are a few uses of several icons that are in the FF's while the icons list ends at F6(24) (both here, and when I check the font in Windows/Word etc.).  Would this be the difference between:

**Segoe UI and Fabric MDL2 icon font**
..and..
**Segoe UI and Fabric MDL2 icon font _(Microsoft Employees)_**

[(from here, under "Fonts")](https://developer.microsoft.com/en-us/fabric#/resources)?

If I could get my hands on that employees-only font... it would make my day (nerd alert 🤠).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 633955d7-89b3-04a5-ad62-4fa860785150
* Version Independent ID: ce94b443-0257-8414-0c12-0490c0bad8b6
* Content: [Segoe MDL2 icon guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)
* Content Source: [windows-apps-src/design/style/segoe-ui-symbol-font.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/segoe-ui-symbol-font.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by jevansaks** [comment]
@chigy are there codepoints in the font that are missing from the documentation?

**Comment by mijacobs** [comment]
Hi @JeremyTBradshaw, 
We recently updated the list so that it reflects all the codepoints that are publicly available.
