### ISSUE TITLE
Cannot see Activation Code

### ISSUE THREAD

**Issue by germanvillarreal** [MicrosoftDocs/windows-uwp#891]
I am not greeted by an activation code when I open the Dev Mode Activation app. Instead I see a Welcome screen with useless info and a link to linkid=760412, I click "Next" and the title on the screen is "Before you Begin" and the same linkid. The linkid takes me to "Getting started with UWP app development on Xbox One"
Step 1 from the 
"Activate Developer Mode on your Xbox One. Download the app, get the activation code, and then enter it into the Manage Xbox One consoles page in your Dev Center account. For more information, see Xbox One Developer Mode activation."

*****
"get activation code" part seems magical, I do not see a code or any references to other setup steps required.
this page also suggests that the activation code will be presented to me upon launching the activation app. that is not the case.
****
My xbox one s is updated and connected to the internet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc064e49-5f24-ff80-d511-7f1947fc39da
* Version Independent ID: b8ad47c2-8264-c232-167f-b9ee69d6dce1
* Content: [Xbox One Developer Mode activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **scotmi**

**Comment by voodooace12** [comment]
Please check

https://developer.microsoft.com/en-us/games/xbox/docs/xdk/provisioning-dev-kit

**Comment by david-pratt** [comment]
This link doesn't work.
