### ISSUE TITLE
The sample code has many errors. Doesn't work.

### ISSUE THREAD

**Issue by christoph-fer** [MicrosoftDocs/windows-uwp#899]
I'm running the code on RS4 build with Windows UI Library with all the necessary namespaces. However, the provided code doesn't work. It's been broken for weeks! Please fix.

Here are the errors:

![image](https://user-images.githubusercontent.com/39899690/44043014-6ccbca3e-9f3f-11e8-873d-d97875775c33.png)

![image](https://user-images.githubusercontent.com/39899690/44042775-ca0fd718-9f3e-11e8-9cca-0f6ef9cf8199.png)

**Comment by ginami** [comment]
Hi @christoph-fer -- looks like this a duplicate issue (same as #898 ?). OK to close? Thank you!

**Comment by ginami** [comment]
Hello @christoph-fer -- closing this for now--let us know if this is a separate issue from #898 . (And if so, what doc are you referring to?) Thank you!
