### ISSUE TITLE
Retrieve availabilityId?

### ISSUE THREAD

**Issue by benjaminfox** [MicrosoftDocs/windows-uwp#900]
To grant free in-app products from our service, we need the IAPs' availabilityIds (as according to [these docs](https://docs.microsoft.com/en-us/windows/uwp/monetize/grant-free-products)). 

Is it possible to retrieve the availabilityId from the Store Services REST API? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfe8cbe9-e515-48f9-95b6-43edb970dd60
* Version Independent ID: fcdc9bdb-173a-f389-ce4e-d206ca5a3a67
* Content: [Get all add-ons - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-all-add-ons)
* Content Source: [windows-apps-src/monetize/get-all-add-ons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-all-add-ons.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your question. I have following up with the engineering team that owns this API, and will update this issue when I know more.

**Comment by mcleanbyron** [comment]
Still investigating, but at this time it appears that there is no way to retrieve this value from one of the public REST APIs. This value is available via the [StoreSku.Availabilities](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storesku.availabilities) property in the Windows SDK, but that is somewhat problematic from a service-oriented workflow so I'm still trying to get more guidance from the engineering team about this overall scenario is expected to work. 

In addition to the availability ID, this REST API also requires the product ID and sku ID for the free product you want to grant. Can you clarify where how you're currently getting these values?

**Comment by benjaminfox** [comment]
Thanks a lot for looking into this. We're currently getting the product, availability, and SKU IDs from [StoreAvailability.StoreId](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storeavailability.storeid), and passing them up to our service so it can do its work. 

Even if these values were just visible in the developer dashboard, that would be helpful (although API access would be awesome!)

**Comment by mcleanbyron** [comment]
Thanks for the additional info. I have confirmed that at this time there are no publicly exposed REST APIs for retrieving these IDs, although this is on the engineering team's roadmap for the future.
