### ISSUE TITLE
Ambiguity in wording

### ISSUE THREAD

**Issue by miketsmith** [MicrosoftDocs/windows-uwp#901]
"Company accounts are a little more expensive, mostly because we take some additional steps to ensure that you are authorized to represent your company and set up the account. Per the Store Policies, a company account is required to publish apps with certain functionality, such as apps that access financial account information or that require authentication to access primary functionality (without using a secure dedicated third party authentication provider)."

This can be taken as the company is required to publish such applications, but I'm assuming that's not the message you're trying to give.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2099ff76-43d5-98fd-d8bc-66ccdc14c4fe
* Version Independent ID: 1c3f3863-5413-d58b-a0e5-81a6da6bccf2
* Content: [Account types, locations, and fees - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees#account-verification)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for pointing that out, makes sense! I've rephrased the sentence to remove that interpretation.
