### ISSUE TITLE
Links on page are missing

### ISSUE THREAD

**Issue by vadobre** [MicrosoftDocs/windows-uwp#902]
Touch - https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions#touch-keyboard
Focus visuals - https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions#focus-visual
UI Navigations - https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions#navigation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538142a-74f2-63fe-5ffc-b205a69f9493
* Version Independent ID: c382db31-6f36-b071-423a-72b61b77aed1
* Content: [Keyboard interactions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions#osk)
* Content Source: [windows-apps-src/design/input/keyboard-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-interactions.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @vadobre. Thanks for the feedback. These links should be fixed now.
