### ISSUE TITLE
Can't reset colors

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#904]
I used the "simple color customization" code example and it worked perfectly. However, I can't reset the colors by setting the properties to null. The title bar is still green. Can someone help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd79400-8154-9a7c-a36e-33077cfa4be9
* Version Independent ID: fafc7523-a98a-fbff-9cc1-ca74a335c3ff
* Content: [Title bar customization - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#full-customization-example)
* Content Source: [windows-apps-src/design/shell/title-bar.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/title-bar.md)
* Product: **windows**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Which properties did you set to null?
