### ISSUE TITLE
Height of Key Tip

### ISSUE THREAD

**Issue by sjb-sjb** [MicrosoftDocs/windows-uwp#905]
How can I reduce the height of the Key Tips? Some of the pictures in this documentation show square Key Tips, but when I use them they are vertical rectangles -- too tall for my application. 

A second request : can you link to a more detailed technical document describing, for example, how to programatically enter or cancel an access key scope (control which scope will be invoked when Alt key is pressed).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5947b2-fd1c-dc30-8cf5-9a357d8adf07
* Version Independent ID: a414afeb-51cb-3b63-7820-5d43be6eb84f
* Content: [Access keys design guidelines - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys#key-tip-style)
* Content Source: [windows-apps-src/design/input/access-keys.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/access-keys.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @sjb-sjb, sorry for the delayed response to this issue. 

See https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.tooltip?view=winrt-19041#control-style-and-template for info on overriding the default tool tip style.

I've created an internal work item to track your second suggestion.
