### ISSUE TITLE
Link to Lionbridge is broken

### ISSUE THREAD

**Issue by bwaldbaum** [MicrosoftDocs/windows-uwp#906]
https://intlapps.lionbridge.com/windows does not navigate to a valid page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe32af9-271f-3e4a-91bc-bffd3f09f886
* Version Independent ID: 3b9e8778-e7bc-3268-1466-881890455a16
* Content: [Use the Multilingual App Toolkit - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-mat)
* Content Source: [windows-apps-src/design/globalizing/use-mat.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/use-mat.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @bwaldbaum, I have merged a fix into master; I expect that to be live within the next 24 hours. Thanks for raising this issue, I have now fixed the link and it should work again. ~Steve

**Comment by stevewhims** [comment]
Hi, @bwaldbaum, the link is fixed now, so I'll go ahead and close this issue. Thanks! ~Steve
