### ISSUE TITLE
Are there some examples to show how to invoke this API?

### ISSUE THREAD

**Issue by stamaimer** [MicrosoftDocs/windows-uwp#908]
Are there some examples to show how to invoke this API? Just show how to use claims to authorize the request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99688f9e-c82e-b3e8-f233-ceb215ac8ce8
* Version Independent ID: 8c4deeaa-3f59-c9e8-b53b-7d8843cc34ea
* Content: [POST (/users/batch/profile/settings) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/xbox-live-rest/uri/profilev2/uri-usersbatchprofilesettingspost)
* Content Source: [windows-apps-src/xbox-live/xbox-live-rest/uri/profileV2/uri-usersbatchprofilesettingspost.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/xbox-live-rest/uri/profileV2/uri-usersbatchprofilesettingspost.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aaron-bond** [comment]
I would like to second this. @stamaimer did you have any luck authenticating and using the API? I've signed up for the dev account and now can't figure out how to use it...

**Comment by stamaimer** [comment]
@aaron-bond You can check this question [How to send requests to Xbox Live Restful API](https://stackoverflow.com/questions/51853445/how-to-send-requests-to-xbox-live-restful-api) on stackoverflow.

**Comment by KevinAsgari** [comment]
You can also check out the source code for the Xbox Live SDK, which just wraps the REST calls. Check out the code for get_user_profiles in https://github.com/Microsoft/xbox-live-api/blob/master/Source/Services/Social/profile_service.cpp

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. It sounds like it is resolved so I am closing.

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
