### ISSUE TITLE
Please clarify lightweight styling in the context of Custom Templated Controls, UserControls and controls dynamically added to the page

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/windows-uwp#909]
I've tried in the forums but been unable to get a clear answer to this question. Does the lightweight styling section above also apply in the same way to Custom Templated Controls and UserControls if the template or user control contains the ThemeResource markup extension. Also, if I add a control to the visual tree, are any ThemeResources within that control or its template guaranteed to be updated (by walking up the visual tree)?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd00996-b747-3d87-6df6-bbeaea8511cd
* Version Independent ID: 469cf671-0064-27f5-13ce-944cf3973d7c
* Content: [XAML styles - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/design/controls-and-patterns/xaml-styles)
* Content Source: [windows-apps-src/design/controls-and-patterns/xaml-styles.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/xaml-styles.md)
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by kikisaints** [comment]
Lightweight styling is basically renamed resources that give you more direct access to control colors both during rest and in a visual state. So, as long as your custom control or template uses ButtonBackground, or ButtonBackgroundPointerOver, etc. somewhere, it will get the appropriate color from our system.

I'm not sure what you mean by your second question - can you give me a markup example of what you're asking?

**Comment by benstevens48** [comment]
I was mainly talking about defining custom ThemeResources and also overriding them in certain sections of the visual tree. In my first point I mainly wanted to clarify the behaviour of UserControls. For some reason in the documentation it says 

> A UserControl that makes a XAML resource reference from its definition scope must be able to support the lookup of that resource within its own definition-scope lookup sequence—that is, it cannot access app resources

Maybe I'm misinterpreting it, but this seems to be incorrect. If I use a ThemeResource inside a UserControl definition scope, then it will pick that up from the App resource dictionary, and it will also pick up any overrides of the ThemeResource defined by its parents in the visual tree where it is used. This is the behaviour I would expect and want, so I just wanted to clarify that this is what is meant to happen. Also I wanted to guarantee this for custom controls as well. (I see no reason these wouldn't behave the same as the built-in ones, except that the resources defined in Gereric.xaml for a project override those in the App resource dictionary, which is fine, but you might expect it to be the other way around).

For my second question, I'm considering a scenario like this
```xaml
<Grid Name="OuterGrid">
<Grid.Resources>
<SolidColorBrush x:Key="MyBrushKey" Color="Blue" />
</Grid.Resources>
<Grid Name="SubGrid">
<Grid.Resources>
<SolidColorBrush x:Key="MyBrushKey" Color="Red" />
</Grid.Resources>
</Grid>
<Rectangle Name="MyRect" Fill="{ThemeResource MyBrushKey}" />
</Grid>
```
If I remove the rectangle from the outer grid at run-time using code, and put it in the sub-grid, is it guaranteed to change from blue to red?

**Comment by hkhmsft** [comment]
If any new actionable items arise, let us know either through a new Issue or directly on this thread. In the meantime, I'll be closing this Issue. Thanks once again for submitting your feedback!
