### ISSUE TITLE
Accessible filter while searching the Microsoft Store

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#911]
Can you tell me how I filter on accessible apps? I don't see an option in the Store app to search on this filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb3c6c0-64d6-db05-68ea-e461dd4d3e38
* Version Independent ID: d435bcaa-b300-2155-3962-9c404e442569
* Content: [Accessibility in the Store - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/accessibility-in-the-store)
* Content Source: [windows-apps-src/design/accessibility/accessibility-in-the-store.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/accessibility-in-the-store.md)
* Product: **windows**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Unfortunately, I don't find such a filter in the Store app. I have submitted this feedback to the Store team.
