### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by killaboy26** [MicrosoftDocs/windows-uwp#912]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b30576-1161-8546-df9f-61de76e39fd1
* Version Independent ID: 7275be4d-3028-fbd3-ba0a-4f09491705e7
* Content: [Data access - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-access/index)
* Content Source: [windows-apps-src/data-access/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/index.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by ginami** [comment]
Hi @killaboy26 -- did you have feedback about the links on this page?
