### ISSUE TITLE
Force Display of Key Tip

### ISSUE THREAD

**Issue by sjb-sjb** [MicrosoftDocs/windows-uwp#913]
How can I force display of the Key TIp? For example in Office applications, if you hold down the ALT key then after a moment the key tips are shown. How can I achieve a similar effect in UWP?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5947b2-fd1c-dc30-8cf5-9a357d8adf07
* Version Independent ID: a414afeb-51cb-3b63-7820-5d43be6eb84f
* Content: [Access keys design guidelines - UWP app developer](https://docs.microsoft.com/en-ca/windows/uwp/design/input/access-keys)
* Content Source: [windows-apps-src/design/input/access-keys.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/access-keys.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
This behavior is supported by the platform. You don't need to do anything in your app.

**Comment by sjb-sjb** [comment]
I don't agree. The platform will display tooltips when you press and then release the Alt key. I want to display tooltips when you press AND HOLD the Alt key (and then I want them to stay displayed when I release the Alt key). This is what Office does but it is not supported out of the box by UWP.
