### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by toncho11** [MicrosoftDocs/windows-uwp#915]
It does not work no matter what I do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd23d59d-59c2-f53c-6f29-cd8a18387d2a
* Version Independent ID: 89d12ebd-03ec-8275-1220-5997cebce7a1
* Content: [Log custom events for Dev Center - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/log-custom-events-for-dev-center)
* Content Source: [windows-apps-src/monetize/log-custom-events-for-dev-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/log-custom-events-for-dev-center.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're encountering a problem. Can you clarify what you mean by "does not work"? Are you saying that you can successfully run the code to log custom event strings, but those custom event strings never show up in the Usage report for your app? If so, can you confirm that your project is associated with an app that is published to Dev Center?

**Comment by toncho11** [comment]
Everything was done correctly. It is just that I am using desktop bridge and a lot other hacking to use the APIs from UWA in my otherwise standard application. It was crashing the application, but other APIs such as IAP from UWA were working correctly. Crash report was not generated. Anyway I found another way to log online data. This is really need in order understand which sales strategy to use.
