### ISSUE TITLE
device 

### ISSUE THREAD

**Issue by zairil** [MicrosoftDocs/windows-uwp#916]
So sweet 

---
#### Butiran Dokumen

⚠ *Jangan edit bahagian ini. Ia diperlukan untuk docs.microsoft.com ➟ Pemautan isu GitHub.*

* ID: f35d7dc2-a5e9-9f86-7e8a-88e6afe40c99
* Version Independent ID: b57b8c51-e2f6-e5e1-1d93-14f26691bc39
* Content: [Enable your device for development - UWP app developer](https://docs.microsoft.com/ms-my/windows/uwp/get-started/enable-your-device-for-development?OCID=WinClient_Ver1703_Settings_DevMode)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by ginami** [comment]
Hi @zairil -- thanks for your feedback!
