### ISSUE TITLE
Describe C++ WinRT as the replacment for C++ CX

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#917]
This might be out of scope for a page like this but it should describe C++ WinRT as the preferred WinRT projection for C++ customers, replacing C++ CX. Maintainers should consider migrating old code when given a chance.

https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt

**Comment by ginami** [comment]
HI @ChrisGuzak -- which page are you referring to? The URL will help me route your feedback to the correct author.

**Comment by ChrisGuzak** [comment]
@ginami I've added the link.

**Comment by ginami** [comment]
Thanks @ChrisGuzak !

**Comment by stevewhims** [comment]
How does this sound (see the markdown below)? I'll close the issue when this is live (PS, the parent topic of the topic in question already says that C++/WinRT is the replacement for C++/CX; but it doesn't hurt to emphasize it another place, too).

C++/WinRT is Microsoft's recommended replacement for the [C++/CX](/cpp/cppcx/visual-c-language-reference-c-cx?branch=live) language projection, and the [Windows Runtime C++ Template Library (WRL)](/cpp/windows/windows-runtime-cpp-template-library-wrl?branch=live). The full list of [topics about C++/WinRT](index.md#topics-about-cwinrt) includes info about both interoperating with, and porting from, C++/CX and WRL.

**Comment by ChrisGuzak** [comment]
looks great.

**Comment by stevewhims** [comment]
Cool, so we're live now with this change. I'll close the issue. Thanks, all! :) ~Steve
