### ISSUE TITLE
As of May 2018 info is incorrect

### ISSUE THREAD

**Issue by PatrickB3** [MicrosoftDocs/windows-uwp#918]
You have to open the package.appxmanifest as XML. There is no view code option.

Add &lt;uap:SupportedUsers&gt;multiple&lt;/uap:SupportedUsers&gt;
to Properties. Step 3 is incorrect and not even valid xml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f975d02c-9e79-a954-b6e8-4f58f077e275
* Version Independent ID: 3cce3d7d-129f-1a61-d588-0726265d26a0
* Content: [Configure Xbox Live in Unity - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/configure-xbox-live-in-unity)
* Content Source: [windows-apps-src/xbox-live/get-started-with-creators/configure-xbox-live-in-unity.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/get-started-with-creators/configure-xbox-live-in-unity.md)
* Product: **windows**
* GitHub Login: @aablackm
* Microsoft Alias: **aablackm**

**Comment by aablackm** [comment]
Thanks for keeping a watchful eye! This article should be updated by noon tomorrow PST.

**Comment by aablackm** [comment]
It's been fixed! This issue will be closed tomorrow if there are no further comments.
