### ISSUE TITLE
Payer of payouts

### ISSUE THREAD

**Issue by martinprikryl** [MicrosoftDocs/windows-uwp#920]
I miss an information on the entity that is payer of payouts for taxation/accounting purposes. Is it US-based Microsoft Corporation (1 Microsoft Way, Redmond, WA 98052)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36abe7f6-20c0-e1ba-d585-9630bcfdcc9f
* Version Independent ID: fd28df55-a61e-4742-37a1-b6691fd5fdf6
* Content: [Getting paid - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/getting-paid-apps)
* Content Source: [windows-apps-src/publish/getting-paid-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/getting-paid-apps.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I am so sorry it took a long time to address this! We have added info on this to https://docs.microsoft.com/en-us/windows/uwp/publish/understand-irs-tax-forms
