### ISSUE TITLE
Please educate others sincerely.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#921]
If you do not think to teach others, do not do it. What to do? Very Happy Do not pity someone he came to know some. The papers you made Link to Post - Back to Top IP: Logged It seems to educate, but it really makes people

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#backwards-navigation)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by ginami** [comment]
Thank you @AomkungNaja for your feedback. If you have specific information you'd like us to include in this doc, please let us know.
