### ISSUE TITLE
Hidden Add-Ons and Store Visibility

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#922]
The docs state that if the add-on is indicated hidden, it still is available within the parent app, but the add-on will not be displayed in the apps product listing. The problem is that add-ons are not displayed in product listings. If they are, can you provide an example? Here's an example of an app with in-app-purchases - the add-ons are not listed in the product listing: https://www.microsoft.com/store/productId/9P50XNT6BC4V

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ed6d16-d542-353e-33e6-e652a0260727
* Version Independent ID: e73daf44-079a-bab0-f38c-a60260b10df3
* Content: [Set add-on pricing and availability - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/set-add-on-pricing-and-availability#markets)
* Content Source: [windows-apps-src/publish/set-add-on-pricing-and-availability.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-add-on-pricing-and-availability.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I'm sorry to take so long to respond. Add-ons are actually not be displayed in the parent product's Store listing. This option simply makes the add-on available to the user from within the app. We are working to update the text used in the submission process and I will update this topic to reflect the new options once that has been done.
