### ISSUE TITLE
Typo in sentence

### ISSUE THREAD

**Issue by sunilab** [MicrosoftDocs/windows-uwp#923]
In the section 'Accent color palette' on accent color chart where it shows the light and dark colors of blue, the row with A on it has an incorrect sentence "Text can be appear in light".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181b91e8-b61c-f32b-f59c-332db130d207
* Version Independent ID: ec8195d3-5847-e003-c8ef-bc3a6dfe069f
* Content: [Color in UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/style/color)
* Content Source: [windows-apps-src/design/style/color.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/color.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by mijacobs** [comment]
Thank you, @Sunilab; I'm updating the article.
