### ISSUE TITLE
Privacy Policy URL

### ISSUE THREAD

**Issue by nielsnhlt** [MicrosoftDocs/windows-uwp#924]
When I create an add-on submission, I am required to indicate whether a privacy policy URL is necessary, and as far as I can see, this can only be done in the 'Properties' section when updating the add-on through the dashboard. Would it be possible to set this property through the API?

Kind regards,
Niels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f651f82-b735-fd29-7dc6-a2422c3b761f
* Version Independent ID: ccb71a5d-7239-b91e-fdb3-55b360d255d1
* Content: [Update an add-on submission - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/update-an-add-on-submission)
* Content Source: [windows-apps-src/monetize/update-an-add-on-submission.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/update-an-add-on-submission.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Currently, the privacy policy property can only be set via the dashboard. Please see the description for the _privacyPolicy_ field [here](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-app-submissions#base-listing-object).

**Comment by nielsnhlt** [comment]
Will this be supported in the future? The problem we're having is that we can create, update, and then commit a submission for a new add-on through the API perfectly fine, but the submission's status will stay on 'CommitStarted' until we set the add-on's privacy policy through the dashboard (not the app's privacy policy mind you).
This effectively means that we can't use the API to create a new add-on.

**Comment by mcleanbyron** [comment]
Yes, this does mean that you must set the add-on's privacy policy in the dashboard before you can complete your first submission via the API. The engineering team that owns this API is well aware of this issue and plans to address it in an upcoming update to the submission API.
