### ISSUE TITLE
Does this mean anyone with Tenant Id, Client Id and Key can submitt app to the AAD account in the windows store?

### ISSUE THREAD

**Issue by botengHY** [MicrosoftDocs/windows-uwp#926]
From this article it seems that the Tenant Id, Client Id and Key are the only things needed to update an App in store, so anyone with the info can submit, without account authentication. Is this secure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf973bd-e0d9-19b0-ad24-e09a83d3a2a9
* Version Independent ID: 25d0bdd2-0487-6742-b4bd-abc1e3ee6be8
* Content: [Add users, groups, and Azure AD applications to your Dev Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications#manage-keys)
* Content Source: [windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
I'm sorry for taking so long to reply. Each Azure AD application must be specifically added as a user to the account, and keys can be removed as needed if there is any issue that someone unintended gets access to a key. Additionally, as noted on the page, to use the REST APIs provided by the Microsoft Store services, you will need to obtain an Azure AD access token that you can use to authenticate the calls to services.
