### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by DragonGeo2** [MicrosoftDocs/windows-uwp#927]
I felt like there was some information missing from this article, so I typed that up in case anyone wanted to add it in there:

IDirect3DDevice9::SetScissorRect is replaced by ID3D11DeviceContext::RSSetScissorRects ( https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-rssetscissorrects )
IDirect3DDevice9::SetViewoprt is replaced by ID3D11DeviceContext::RSSetViewports ( https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-rssetviewports )

IDirect3DDevice9::SetVertexDeclaration is replaced by ID3D11DeviceContext::IASetInputLayout ( https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-iasetinputlayout )
IDirect3DDevice9::SetIndices is replaced by ID3D11DeviceContext::IASetIndexBuffer ( https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-iasetindexbuffer )
IDirect3DDevice9::SetStreamSource is replaced by ID3D11DeviceContext::IASetVertexBuffers ( https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-iasetvertexbuffers )
IDirect3DDevice9::SetRenderTarget is replaced with ID3D11DeviceContext::OMSetRenderTargets ( https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-omsetrendertargets)

IDirect3DDevice9::ShowCursor is replaced with ShowCursor ( https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-showcursor )
IDirect3DDevice9::SetCursorPosition is replaced with SetCursorPos ( https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setcursorpos )
IDirect3DDevice9::SetCursorProperties is replaced with SetCursor ( https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setcursor )

Control of the video card's hardware gamma ramp through IDirect3DDevice9::SetGammaRamp is replaced with IDXGIOutput::SetGammaControl (read more here: https://docs.microsoft.com/en-us/windows/desktop/direct3ddxgi/using-gamma-correction )

IDirect3DDevice9::ProcessVertices is replaced by the Stream-Output functionality of Geometry Shaders ( https://docs.microsoft.com/en-us/windows/desktop/direct3d11/d3d10-graphics-programming-guide-output-stream-stage-getting-started )

The function IDirect3DDevice9::SetClipPlane to set user clip-planes was replaced with either the HLSL SV_ClipDistance vertex shader output semantic ( https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-semantics ) available in VS_4_0 and up, or the new HLSL clipplanes function attribute ( https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/user-clip-planes-on-10level9 )

IDirect3DDevice9::SetPaletteEntries and IDirect3DDevice9::SetCurrentTexturePalette are deprecated. Replace these with a pixel shader that looks up colors in a 256x1 R8G8B8A8 texture instead.

Fixed-function tessellation functions like DrawRectPatch, DrawTriPatch, SetNPatchMode, DeletePatch are deprecated. Replace these with programmable-pipeline SM5.0 Tessellation shaders (if hardware supports tessellation shaders).

IDirect3DDevice9::SetFVF and FVF codes are no longer supported. You should port from D3D8/D3D9 FVF codes to D3D9 Vertex Declarations before porting to D3D11 Input Layouts.

It's probably worth noting that all of the D3DDECLTYPE types that are not directly supported can be emulated fairly efficiently with a small number of bitwise operations at the beginning of a vertex shader in VS_4_0 and up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1f9692-97e1-c137-c785-ae682d089877
* Version Independent ID: 6b2e29e5-178b-bee2-6927-20e202786d33
* Content: [Map DirectX 9 features to DirectX 11 APIs - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/feature-mapping)
* Content Source: [windows-apps-src/gaming/feature-mapping.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/feature-mapping.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mtoepke**

**Comment by stevewhims** [comment]
Hi, @DragonGeo2, and sorry for the very long delay in responding to this issue. I've added this info to the topic, and that's now live.

Thanks again,
Steve
