### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by v01pe** [MicrosoftDocs/windows-uwp#928]
https://docs.microsoft.com/en-us/windows/uwp/gaming/gamepad-and-vibration#run-the-gamepad-vibration-sample
-&gt; link to github in this paragraph is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b66ce5-9518-ec67-4ec6-8fc7cb8293ce
* Version Independent ID: af209d4a-d3b5-d2f0-fdcb-e2ea6797b9f5
* Content: [Gamepad and vibration - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/gamepad-and-vibration#run-the-gamepad-vibration-sample)
* Content Source: [windows-apps-src/gaming/gamepad-and-vibration.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/gamepad-and-vibration.md)
* Product: **windows**
* GitHub Login: @eliotcowley
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @v01pe, thanks for pointing this out! I've fixed the link&mdash;the fix should go live tomorrow.
