### ISSUE TITLE
"Test your Windows app for Windows 10 s" -Is using an Enterprise Policy on PRO really the right way?

### ISSUE THREAD

**Issue by SillyKeith** [MicrosoftDocs/windows-uwp#93]
In my conversations with Scott Anderson scander@microsoft.com about these policy files, there are 2 types; Enterprise and Windows.    The policy files mentioned in this article are Enterprise Policies, and copied to the %windir%\System32\CodeIntegrity directory.   The other type is a Windows Policy and is Windows signed.  This is what Window 10 S uses.  It's WinSiPolicy.p7b and is stored in the EFI boot partition EFI\Microsoft\Boot\WinSiPolicy.p7b  since the enforcement on the signature is done early in the boot.  

If this article audience is only intended for APP developers and not IHV Driver developers, then the article is correct.  But, I believe IHV driver developers may also find their way here and for them, they will need the WinSiPolicy file copied over to the EFI boot partition to properly mirror all the Policies of Windows 10 S.   The WinSiPolicy files can be found here: \\winsect\scratch\ConfigCI\CloudSKUPolicies\Tools

**Comment by mattwojo** [comment]
Hi @SillyKeith -- Could you please add a link to the article you are referencing to help me triage this issue to the correct person?  Thanks! ~Matt

**Comment by SillyKeith** [comment]
There isn’t a link, only Connect postings so far for Microsoft Partners.  If you could email me via your MS alias I can forward you that info.

Keith Kepler
PM, Strategy & Ecosystem (formerly PCE), WDG
Office:   (425) 703-3767
Mobile:  (206) 409-1006
Keith.Kepler@Microsoft.com

**Comment by mattwojo** [comment]
Taking this issue offline and handling internally.
