### ISSUE TITLE
VB Documentation?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#930]
Hi there :), 
I have a game on the Xbox Live market place that I would like to incorporate Leaderboards and Stats, but I don't see any C# or VB documentation on how to go about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bc388d-6b0d-d201-19a9-4055cb14ef88
* Version Independent ID: aa039e5c-9126-265c-773e-9db63471e6fd
* Content: [Updating Stats 2017 - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/leaderboards-and-stats-2017/player-stats-updating)
* Content Source: [windows-apps-src/xbox-live/leaderboards-and-stats-2017/player-stats-updating.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/leaderboards-and-stats-2017/player-stats-updating.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
Hello aaronlevicarrick,
Is your game built with Unity or a UWP title?
If it's built with Unity, you may want to read [Player Stats and Leaderboards in Unity](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/add-stats-and-leaderboards-in-unity)
You will find prefab instructions and script sample code in the same section by reading [The Leaderboard Example Scene](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/setup-leaderboard-example-scene) and [Scripting Leaderboards](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/unity-leaderboard-from-scratch).

**Comment by ghost** [comment]
Aaron thanks for getting back so quick,

It is a uwp game written in vb.

________________________________

**Comment by aablackm** [comment]
Hello Again, 
In your query you asked for C# or VB code examples. 
Would C# code be sufficient for your needs? I ask because while I can't make any promises on turn around time, the turn around time for adding C# code snippets will likely be shorter.

**Comment by ghost** [comment]
C# would be great i can program in both

Sent from my Windows Phone
________________________________

**Comment by aablackm** [comment]
Hello again aaronlevicarrick!

I added the C# equivalent snippets to the code already contained in the article. You should be able to see the changes around 12pm tomorrow. I hope that helps.

**Comment by ghost** [comment]
Thanks a bunch!! You rock, this is a big help

Sent from my Windows Phone
________________________________

**Comment by aablackm** [comment]
I'm glad I could help =)
