### ISSUE TITLE
Packaging using C# packaging project

### ISSUE THREAD

**Issue by yordans** [MicrosoftDocs/windows-uwp#935]
Hello,

I am trying to package a wpf application in a UWP package using the C# packaging project. The problem is that my application has dlls dependencies that are provided with post build events in its output. So when I add a reference to my application in the packaging project, its output only contains the dlls that are generated from the build of the desktop app - all other dlls (from post build events) are ignored. Then I decided to make the same post build events for the packaging project and provide the missing dlls, but unfortunately, they were not considered as well by the packaging process.

Is there a way I can force this dlls to be packaged in the result appx?

**Comment by ginami** [comment]
Hi @yordans -- does this issue relate to a specific page in our docs? This feedback channel is for doc-specific issues, and a URL would help me get your question to the correct author.

**Comment by ginami** [comment]
Hi @yordans -- let us know if you have feedback specifically on our docs. If you need developer support, go to https://developer.microsoft.com/en-us/windows/support. Thank you!
