### ISSUE TITLE
Suggest more clarity in title

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/windows-uwp#937]
Is this documenting the process of refactoring an out-of-process background code base to an in-process code base?  Or is handling a out-of-process background task and forwarding it to an in-process background task?

I know that might seem silly, but in the case of Azure Notifications Hub and action buttons and templates, I have no choice but to send raw notifications and they need to be handled by an out-of-process background task.  The work that needs to be done by my action buttons requires the app itself to handle them (security, etc.)

So I'm trying to response to an out-of-process background task event, but have to perform the functionality inside my running app, possibly in the background.

Also, I can't find the `OnBackgoundActivated` sample, either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17939b8f-6356-dffa-2968-9df0d7be6607
* Version Independent ID: 520af202-2267-aba5-0821-1e91f7e58093
* Content: [Convert an out-of-process background task to an in-process background task - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/convert-out-of-process-background-task)
* Content Source: [windows-apps-src/launch-resume/convert-out-of-process-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/convert-out-of-process-background-task.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by nhwilly** [comment]
Ok, I found an original blog post that seems to suggest this is a refactoring exercise.  You can find it [here](https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/).

**Comment by stevewhims** [comment]
Hi, @nhwilly, thanks for raising this issue. I've changed the title, and added some clarification in the first paragraph. I've also corrected the link that you mention (to OnBackgroundActivated), and I've confirmed that all the links now function, and go to the expected place. I'll go ahead and close the issue, optimistic that it's been addressed, but please re-open it if you'd like more discussion about it. Thanks again! ~Steve
