### ISSUE TITLE
Following links should stay in the computing language of the previous page

### ISSUE THREAD

**Issue by Bluesman74** [MicrosoftDocs/windows-uwp#938]
its seems bad that we end up on a C# page despite this originating page being the Winrt C++ page - https://github.com/MicrosoftDocs/winrt-api/issues/580

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4db0aab-b906-9dec-381c-ceccc1e90c45
* Version Independent ID: 493a4c50-ffa1-5e32-c757-92306c952887
* Content: [XAML controls; bind to a C++/WinRT property - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#add-a-property-of-type-bookstoreviewmodel-to-mainpage)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Bluesman74, thanks for filing the issue. The source topic is a conceptual topic about the C++/WinRT language projection, but the destination topic is a WinRT API reference topic. And reference topics are all language-agnostic (there isn't a notion of a C# API reference topic). If you scroll to the top of any WinRT API reference topic you'll see (in the top-right corner) Feedback, Share, Theme, and Language icons. If you click the Language icon then you'll be able to choose a language (C#, C++/WinRT, etc.) to view the API's syntax block in. The browser remembers your choice for next time. There's no mechanism for overriding that choice (nor setting it to a different default) based on web page navigation; and I don't think that feature would work well in enough cases. In this case if you program primarily in C++/WinRT then I'd recommend choosing that from an API reference topic and then you'll be all set. ~Steve

**Comment by stevewhims** [comment]
@Bluesman74, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
