### ISSUE TITLE
C# Documentation

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#940]
Aaron, thanks for adding c# to the update stats 2017, is there any way you can add it to this page as well, you've been a great help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a8c5cc-e51f-2549-7706-8ab3f8cbb978
* Version Independent ID: 1fd47faa-3bcd-e339-ec87-9f81c95a327b
* Content: [Leaderboards - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/leaderboards-and-stats-2017/leaderboards#how-to-display-leaderboards)
* Content Source: [windows-apps-src/xbox-live/leaderboards-and-stats-2017/leaderboards.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/leaderboards-and-stats-2017/leaderboards.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by aablackm** [comment]
You know, aaronlevicarrick, since you asked so nicely, I think it can be done. Again no promises on turn around time.

**Comment by ghost** [comment]
Thank you so much 😃

Sent from my Windows Phone
________________________________

**Comment by ghost** [comment]
Ps, for all the help you've given me I think I should give you credit in my game. 😎

**Comment by aablackm** [comment]
Just an update aaronlevicarrick, We have not forgotten about you!

**Comment by ghost** [comment]
Hey thanks

**Comment by ghost** [comment]
any eta in sight for this??

**Comment by aablackm** [comment]
Hi aaronlevicarrick! 
Terribly sorry for the wait, but I am targeting this work to be done by the end of the week. 
Thank you for your patience.

**Comment by ghost** [comment]
Thanks Aaron,  :)



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by aablackm** [comment]
Hey @aaronlevicarrick 
Calling an Audible
[Hopefully This Helps](https://imgur.com/gallery/HWagIgJ)
