### ISSUE TITLE
3D Objects Capability Name needs correct capitalization.

### ISSUE THREAD

**Issue by Jace-Samsung** [MicrosoftDocs/windows-uwp#941]
The 3D Objects Capability Name field must match a constant string to compile correctly.  The sample code uses the value "objects3d", but the final 'd' should be capitalized to match the constant "objects3D".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by msatranjr** [comment]
Thanks for the feedback. These changes should be in the doc.
