### ISSUE TITLE
Cannot run app on Windows 10 Mobile

### ISSUE THREAD

**Issue by Stachu270** [MicrosoftDocs/windows-uwp#944]
Hi,

I have Lumia 635 with Windows 10 Mobile ver 1607 compilation: 10.0.14393.2431 installed. I want to test my application on this device. I have developer mode on (of course) and I used Visual Studio 2017 to write code and create a app package. Let me mention that I managed to install this programm on my computer and it works well. 
Package folder consists of i.a. ps1, cer, appxsym, appxbundle files and Dependencies folder with some appx files. So now I want to run this application on my phone. It should be easy, one may think. But this is Microsoft, so yeah...
I copied appxbundle to my phone, clicked, it asked if I want to install. Yes, I said. But nothing happened.
Then I moved a .cer file and installed certificate first. Also nothing happened.
Then I moved also dependencies and first installed certificate (it confirmed that it is installed), then "installed" all dependencies and finally appxbundle. Nothing happened. The installing process proceeds as follows: I press the button, it asks if i want to install, I press Install button, it vanishes and that's it. No progress bar, nothing.
Lastly, after ineffectual search for solution, I tried to install app with the Windows Device Portal. It begins promising with uploading appxbudle and all dependencies to device. But when installing...
"Failure reason: Failed to start deployment. Failure text: A Prerequisite for an install could not be satisfied.
 (0x80073cfd)"
For god's sake. I just want to run "Hello World" application. Why are you making it so difficult (imposiible even).
I liked Windows Phone when everyone made fun of it. But as a developer I must admit that it is probably the worst platform on the market.

Help me fix this (but don't ask if I'm in developer mode! I am!!!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1c88d-24b1-0eda-b458-105db02dca36
* Version Independent ID: c5d1634a-0ead-f68a-e5be-89acf0eef0a6
* Content: [Packaging UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps#feedback)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by tmr4** [comment]
I had a similar problem with my Lumina 650.  For me a required service wasn't starting.  Sorry, I can't remember which one, but I think I found it by searching for an error message I got when trying to connect to my phone.  Once that service was started the app deployed to the phone without problem.

**Comment by tmr4** [comment]
Check if the IPOverUsbSvc service is running.  I can't find the info I used to fix my problem, but it seems that service not running has caused some app deployment issues.

**Comment by Stachu270** [comment]
It turned out it was a version issue. My UWP project was set for minimum version compilation than I have on my device. Changing the minimum version solved the problem and now the application is deploying to the phone.

Thanks @tmr4 for your suggestions.
