### ISSUE TITLE
Windows version number out-of-date

### ISSUE THREAD

**Issue by tca9** [MicrosoftDocs/windows-uwp#947]
In the text, "We highly recommend that new developers and developers writing code for a general audience always use the latest build of Windows (16299). ", the version 16299 *is not* the latest version.  The table at the top refers to the currently latest version as 17134.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b95326-20b5-90f2-d9b2-c6e9fa305dee
* Version Independent ID: b4c6cf4b-5ead-095c-c660-94cb72857ae2
* Content: [Choose a UWP version - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version?ocid=VSClient_VerX_NewProject_version)
* Content Source: [windows-apps-src/updates-and-versions/choose-a-uwp-version.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/updates-and-versions/choose-a-uwp-version.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
Good catch, I'll fix that right up. Thanks.
