### ISSUE TITLE
submissions uploads packages error

### ISSUE THREAD

**Issue by jianboy** [MicrosoftDocs/windows-uwp#948]
this is a DesktopAppConverter app。

and the error is 

```
Invalid package identity name: lyric16 (expected: 2907385AAD3C7.lyric16 )

Invalid package family name: lyric16_1k73am7zks1yj (expected: 2907385AAD3C7.lyric16_bythm6emjq4mr)

Invalid package publisher name: CN=天天有你 (expected: CN=00DC470D-9A91-4F5D-A194-4D2A14249801)
```

**Comment by ginami** [comment]
Hi @jianboy -- does this issue relate to a page in our docs? This feedback channel is for feedback on specific docs; a URL will help me get your question to the correct author.

**Comment by jianboy** [comment]
@ginami hi， I use DesktopAppConverter  to convert my xx.exe. but I submit it to https://developer.microsoft.com . then I have problem. **So where I should get help ?**

**Comment by jianboy** [comment]
I choose the feedback button , it redicet to this project . so I commit my problem. not about uwp-docs

**Comment by jianboy** [comment]
https://docs.microsoft.com/en-us/windows/uwp/publish/upload-app-packages#feedback

the is the doc url, I follow it to do. but still have error . so what should I do ? can you help me ? or can you tell me how to find helper's way?

**Comment by ginami** [comment]
Hi @jianboy -- it sounds like you need to contact developer support: https://developer.microsoft.com/en-us/windows/support.
