### ISSUE TITLE
Can I get a list of windows that can captured?

### ISSUE THREAD

**Issue by CaliforniaChao** [MicrosoftDocs/windows-uwp#949]
I want get a list of all of the windows that can be captured, so that I can put them into a ComboBox or something like that. Is there a function can do this? 
Maybe looks like "DeviceInformation::FindAllAsync(DeviceClass::VideoCapture)"
thanks

**Comment by CaliforniaChao** [comment]
About Screen Capture.
link: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture

**Comment by eliotcowley** [comment]
Hi @CaliforniaChao, currently the screen capture APIs don't have this functionality&mdash;you'll need to use the picker if you want to capture a window. If you just want to get the names of all the open windows, you can do something like [this StackOverflow post](https://stackoverflow.com/questions/7268302/get-the-titles-of-all-open-windows) describes, calling [Process.GetProcesses](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.getprocesses?view=netframework-4.7.2) and then getting the [MainWindowTitle](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.mainwindowtitle?view=netframework-4.7.2) for each process. Hope this helps!
