### ISSUE TITLE
"Xbox Live" sandbox moved to "Device Manager"?

### ISSUE THREAD

**Issue by IQpierce** [MicrosoftDocs/windows-uwp#951]
On some of my windows machines this Device Portal has an "Xbox Live" section, where I can change the XBL sandbox for my machine.

On one of my recently-updated machines, I couldn't find this option. However the "Device Manager" section seems to now have an option to change the "Sandbox", without reference to Xbox Live. (I suppose that's because the Windows Store also uses this sandbox system?)

A note to clarify where this option lives, and/or the fact that it's moved, would be helpful for UWP ID@XBOX developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488cd511-8a4c-8c0d-83a8-c22b6fe46228
* Version Independent ID: 6c723fa9-de64-f757-b32e-dff7e35692d8
* Content: [Device Portal for Windows Desktop - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-desktop)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-desktop.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by eliotcowley** [comment]
Hi @IQpierce, apologies for the delay here, and thanks for the feedback. Are you still seeing this behavior, where on some machines there is an **Xbox Live** section in the Windows Device Portal, but on others there isn't? On both of my machines (Windows 10, version 1809, build 17763) I see the **Xbox Live** section. Perhaps make sure you're up-to-date?

**Comment by eliotcowley** [comment]
Closing due to lack of response. @IQpierce feel free to re-open if you're still having this issue.
