### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Skuldwyrm** [MicrosoftDocs/windows-uwp#952]
Link to https://docs.microsoft.com/windows/uwp/shell/tiles-and-notifications/app-assets#target-based-assets
in the first paragraph of the "(Optional) Add Target-based unplated assets" section is broken (error 404)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4811b3c1-b936-1539-d0a9-3b432d56d422
* Version Independent ID: 44efea7c-bf56-0580-1882-c4023f164eb8
* Content: [Package an app manually (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-manual-conversion)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-manual-conversion.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-manual-conversion.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you for reporting this! We've fixed the broken link.
