### ISSUE TITLE
documentation conflict?

### ISSUE THREAD

**Issue by dingsheng999** [MicrosoftDocs/windows-uwp#953]
https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-consumable-in-app-product-purchases
"that after a successful purchase, a customer cannot purchase the same product again until the app has notified the Store that the previous purchase was successfully fulfilled."
https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-consumable-add-on-purchases
"Store-managed consumable...The user can purchase the add-on as many times as they want (they do not need to consume the items first)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf0df97-9bb8-f8ea-3fed-43ac0d23d7c8
* Version Independent ID: ecd4678d-081b-3c24-6964-fbb30bedf07d
* Content: [Enable consumable in-app product purchases - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-consumable-in-app-product-purchases)
* Content Source: [windows-apps-src/monetize/enable-consumable-in-app-product-purchases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/enable-consumable-in-app-product-purchases.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
These two sections are actually referring to different scenarios.

- The first reference you quoted is an article about using the older Windows.ApplicationModel.Store namespace to implement consumable in-app purchases. This namespace only supports the concept of developer-managed consumables.

- The second reference is from an article about using the newer Windows.Services.Store namespace to implement consumable in-app purchases. This namespace supports both developer-managed consumables and Store-managed consumables, and the section you quoted specifically applies to Store-managed consumabled.

I hope this helps.

**Comment by dingsheng999** [comment]
Thanks a lot McLean for the answer. It really helps.
