### ISSUE TITLE
Ad status

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#954]
In Dev Center, can I see how my ad unit is going? Whether it has an ad, whether is not, whether when it is trying to create an ad?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b08c6292-c94c-2d95-e800-b14d404879f9
* Version Independent ID: 83029484-dc65-6c17-80f3-e75a6bbc6732
* Content: [Display ads in your app with the Microsoft Advertising SDK - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/display-ads-in-your-app#related-topics)
* Content Source: [windows-apps-src/monetize/display-ads-in-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/display-ads-in-your-app.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The [advertising performance report](https://docs.microsoft.com/en-us/windows/uwp/publish/advertising-performance-report) provides metrics for your ad units, including the number of impressions and the fill rate (these appear to be closest to the info you're asking about). This report contains all of the metrics that are currently available for your ad units. I hope this helps!
