### ISSUE TITLE
Ads Not Showing

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#956]
I have a Game on Xbox Live and where my ad should be … it's blank. I can post my code upon request. ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d30c2cc-bf35-ffa8-fde8-c38d18da72cf
* Version Independent ID: 6e877806-26cc-7078-bbeb-351bad62ad7f
* Content: [In-app ads - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/in-app-ads)
* Content Source: [windows-apps-src/publish/in-app-ads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/in-app-ads.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Hi there - sorry to hear about this problem. Please open a support request at http://aka.ms/storesupport so that we can look into this further!
