### ISSUE TITLE
Need to update eventCount to be of type number versus integer

### ISSUE THREAD

**Issue by nmanis** [MicrosoftDocs/windows-uwp#957]
eventCount as shown in sample is not an integer type.  We need to update the documentation to show eventCount to be a number versus integer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 932a110a-fb7f-f65d-8e1c-e1815d14725c
* Version Independent ID: 8f97e378-00cd-1d68-c6f1-69418bd1ffef
* Content: [Get error reporting data for your desktop application - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-desktop-application-error-reporting-data#prerequisites)
* Content Source: [windows-apps-src/monetize/get-desktop-application-error-reporting-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-desktop-application-error-reporting-data.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. I have changed the data type from integer to number in the source file for this article, and this change should be published to our live site in the next 24 hours.
