### ISSUE TITLE
Testing for accessibility with Microsoft tools

### ISSUE THREAD

**Issue by marisolontaneda** [MicrosoftDocs/windows-uwp#958]
Hi,

I'm part of the Keros team, and we're evangelizing the usage of our product for product teams to do accessibility testing. Could you please update your documentation to using Keros primarily? See aka.ms/keros

Thanks,
-Marisol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5dc0055-87d1-6dc5-9628-0c0f383642aa
* Version Independent ID: edb18edc-c836-bb2d-5a74-4b78516a0126
* Content: [Accessibility testing - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/accessibility-testing)
* Content Source: [windows-apps-src/design/accessibility/accessibility-testing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/accessibility-testing.md)
* Product: **windows**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi Marisol, 

Our documentation is for third-party developers. Is Keros available for third parties yet?

 ~ Mark

**Comment by mhopkins-msft** [comment]
Hi Marisol, 

Since, https://aka.ms/keros points to an internal site, I'm assuming you're referring to internal teams. This documentation is not for that audience. Let us know when Keros is available for third party developers.
