### ISSUE TITLE
Is this current version of schema?

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/windows-uwp#960]
What about ToastGenericAttributionText or ToastHeader?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93411d0b-1957-e37c-a598-311e67ec2c83
* Version Independent ID: 363b36fc-5db8-803d-29b2-6bc59c88032a
* Content: [Toast content XML schema - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-xml-schema)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-xml-schema.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-xml-schema.md)
* Product: **windows**
* GitHub Login: @lex
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
@andrewleader

**Comment by andrewleader** [comment]
Hey @pkar70, no, the XML schema page is outdated. The [schema page for the object model](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-schema) is the most up-to-date.

I'll let our new PM owner of this area know about the outdated content! Thanks!

**Comment by hickeys** [comment]
The out-of-date schema doc has been removed and replaced with the up-to-date schema. All links to the old doc have been redirected to the new doc.
