### ISSUE TITLE
Wrong Nuget Package

### ISSUE THREAD

**Issue by ei2kpi** [MicrosoftDocs/windows-uwp#961]
It looks like notifications Nuget package has been renamed to Microsoft.Toolkit.Uwp.Notifications from Windows.UI.Notifications.

Link is here: https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a268967-4b29-b53c-10a5-fd42ea97d8c8
* Version Independent ID: a6b72ed5-1cdb-9fe8-d05b-658cc4801c5a
* Content: [Send a local toast notification - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast.md)
* Product: **windows**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by ei2kpi** [comment]
NVM... I mis-read it! That is the namespace... my bad! Sorry!

**Comment by ginami** [comment]
No worries, @ei2kpi! :)
