### ISSUE TITLE
Should mention the FutureAccessList

### ISSUE THREAD

**Issue by ptorr-msft** [MicrosoftDocs/windows-uwp#963]
This page should mention the [`FutureAccessList`](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.AccessCache.StorageApplicationPermissions) as a feature that lets apps maintain access to a file or folder the user picked with a Picker (or via a Launch activation, etc.). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d92df11-eaec-44ea-d130-e84304af9b8f
* Version Independent ID: d8ada2a7-dcea-96cc-210b-5b446ee88cad
* Content: [File access permissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by hkhmsft** [comment]
It seems the fix was implemented since the creation of this Issue. Marking as Closed.

**Comment by ptorr-msft** [comment]
The doc is not updated. It mentions `FutureAccessList` only in the context of the `Downloads` folder; it should be a top-level piece of information since it applies everywhere. I will suggest an edit.
