### ISSUE TITLE
Mention that broadFilesystemAccess is not necessary to gain ongoing access to files / folders the user already picked

### ISSUE THREAD

**Issue by ptorr-msft** [MicrosoftDocs/windows-uwp#965]
We have seen developers requesting the `broadFilesystemAccess` capability so that they can re-open a file the user previously picked with a `FileOpenPicker` or `FolderPicker`. This is not a good use of the capability, since the application can simply store the `StorageFile` or `StorageFolder` in their [`FutureAccessList`](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.AccessCache.StorageApplicationPermissions) and gain access it to it in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by msatranjr** [comment]
Thanks for the feedback. The topic should be updated now.
