### ISSUE TITLE
Not clickable for Xbox

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/windows-uwp#968]
I've integrated a native ads to test on Xbox One. 
The RegisterAdContainer method works with Desktop (Show some icon at the top of ad container and clickable) but not the Xbox. 
On Xbox (Pointer disabled), The ad requested successfully. After calling RegisterAdContainer, there no icon and visuals like on Desktop and the container is not clickable even when I add buttons to RegisterAdContainer(container, clickableControlsList)

I don't know it's working right or not. Is the impression work fine? Or there will be no impression on Xbox

Please confirm the impressions are working fine with Xbox even when it's not clickable or have some visuals like on Desktop

Thank you,
Linh Nguyen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcaa67dd-aa69-7de2-ee1e-a044a061d03d
* Version Independent ID: 96552e56-6741-cc59-e814-d347f30fe1ac
* Content: [Native ads - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/native-ads#release)
* Content Source: [windows-apps-src/monetize/native-ads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/native-ads.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by linhnddev** [comment]
After some testing and debugging, I guess the RegisterAdContainer create some Tap event (not Click event) to the container and clickable controls. Therefore on Xbox (Pointer disabled) it will not fire event when click on those clickable controls (Tap event only be fired by pointer).

**Comment by liliyashka** [comment]
I get over a million impressions a day for all my apps combined. Native ads on desktop works just fine and I see impressions and request looking good, so is the revenue. But for Native ads on XBOX ONE I get absolute zero impressions. I mean Zero!!! Not even one request or one impressions. Nothing. I doubled checked all my native code and it looks good. While testing my app on my XBOX ONE the native ad loads just fine. It clickable and it loads with no problems. But when deployed to store the app produces no request and or impressions for Native ads even though it loads. As for other ads on XBOX ONE such as banner I get good impressions,request and revenue. So this is strictly Native ads on XBOX ONE only problem. Also this problem is for all my apps and not just one app on XBOX ONE. I have over 10 apps.

**Comment by liliyashka** [comment]
Can anyone confirm that Native Ads for xbox are not supported? I get my native ads for xbox to load and they are clickable but I get zero request and impressions. So Im guessing that they are not supported?

**Comment by linhnddev** [comment]
> Can anyone confirm that Native Ads for xbox are not supported? I get my native ads for xbox to load and they are clickable but I get zero request and impressions. So Im guessing that they are not supported?

I can confirm that the Request/Impressions of Native Ads for Xbox is working fine but the Fill Rate is not good (~ 10%)

**Comment by liliyashka** [comment]
> > Can anyone confirm that Native Ads for xbox are not supported? I get my native ads for xbox to load and they are clickable but I get zero request and impressions. So Im guessing that they are not supported?
> 
> I can confirm that the Request/Impressions of Native Ads for Xbox is working fine but the Fill Rate is not good (~ 10%)

This is very interesting. So when you look at your advertisement info and you click to show xbox one only metrics you get requests and impressions? I get absolute zero!! Not even 1 impression and not even 1 request even though ads load on my xbox and I get over 1 million impressions for Desktop version of the same apps. So same apps gets 1 millions impression but same app for xbox gets zero! Are you sure that you are getting requests and impressions for XBOX native ads?

**Comment by mhopkins-msft** [comment]
Thanks for reaching out to the Microsoft developer documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Windows developer forums](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore%2Cwpsubmit%2Cwppayout%2Cwpdcapp%2Caiaads%2Caiasdk%2Caiamgr%2Cdcefi%2Csapi&filter=alltypes&sort=lastpostdesc) or reaching out to [Windows developer support](http://aka.ms/storesupport).

Again, thanks for reaching out. Best of luck with this issue.
