### ISSUE TITLE
NavigationView MenuButton Foreground

### ISSUE THREAD

**Issue by BillCowell** [MicrosoftDocs/windows-uwp#969]
I can change the foreground color of the NavigationView Items with a Page.Resources section in the page XAML, but the hamburger button stays the same color. I have tried targetting 'Button' and 'PaneToggleButton' but this doesn't work. How can I  change the foreground of the hamburger button (called 'Menu Button' in the article on Navigation View)?

**Comment by ginami** [comment]
HI @BillCowell -- which page in our docs were you referring to? This will help me route your question to the correct author. Thanks!

**Comment by BillCowell** [comment]
Hi Gina,

The page I was referring to was  ‘Navigation View (Preview Version)’ at

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview

My app is loosely based on the example in this page. I have customised the NavigationView  by adding the following code to MainPage.xaml which contains the NavigationView

<Page.Resources>
        <Style TargetType="controls:NavigationViewItem">
            <Setter Property="Foreground" Value="White"/>
        </Style>
        <Style TargetType="Button">
            <Setter Property="Foreground" Value="White"/>
        </Style>
   </Page.Resources>

This changes all the controls except the hamburger button, which I haven’t found a way of accessing. I’m sure it must be easy, but any help would be appreciated. Many thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ginami** [comment]
Thanks @BillCowell !

**Comment by BillCowell** [comment]
No response after 14 days. I would still appreciate an answer. Thank you.

**Comment by jwmsft** [comment]
Hi @BillCowell, thanks for your patience. 
To change all the navigation items and the menu button, you can override the Foreground brushes as shown here.

If you want to change only the menu button, you can override the PaneToggleButtonStyle as shown in the commented code.

```
<controls:NavigationView x:Name="NavView">
    <controls:NavigationView.Resources>
        <SolidColorBrush x:Key="NavigationViewItemForeground" Color="White"/>
        <SolidColorBrush x:Key="NavigationViewItemForegroundPointerOver" Color="Green"/>
        <SolidColorBrush x:Key="NavigationViewItemForegroundPressed" Color="LightGreen"/>
        <SolidColorBrush x:Key="NavigationViewItemForegroundSelected" Color="Red"/>
        <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPointerOver" Color="Blue"/>
        <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPressed" Color="Pink"/>
    </controls:NavigationView.Resources>

    <!--<controls:NavigationView.PaneToggleButtonStyle>
        <Style TargetType="Button" BasedOn="{StaticResource PaneToggleButtonStyle}">
            <Setter Property="Foreground" Value="White"/>
        </Style>
    </controls:NavigationView.PaneToggleButtonStyle>-->
</controls:NavigationView>
```

**Comment by BillCowell** [comment]
That works. Many thanks.

**Comment by TheJimmyJ57** [comment]
Tried this again and the only colors that seem to be overwritten are for the footer ViewItem. Any ideas why?
