### ISSUE TITLE
TPM clear doesnt affect Windows Hello

### ISSUE THREAD

**Issue by pkuntal** [MicrosoftDocs/windows-uwp#971]
Hi,

I am using Windows 10 RS5 17713 build and setup windows hello(finger print and PIN) using my microsoft account, My device contains discrete TPM. 
I did Clear-TPM to clear everything from TPM, but still i can use my registered fingerprint to login.
Does it mean Clear-TPM doesnt clear Windows Hello container from TPM or TPM is not at all used for windows hello even if device is TPM capable?

Regards,
Pooja

**Comment by ginami** [comment]
Hi @pkuntal -- this is a channel for feedback on our docs... it sounds like you need support help? If so, please review our developer support options here: https://developer.microsoft.com/en-us/windows/support. If your question is specific to one of our doc pages, please let me know the URL so I can route your question to the correct author. Thank you!

**Comment by pkuntal** [comment]
Hi Gina,

I am facing issue in ' windows hello and TPM' ..document which I referred
is
https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/how-windows-uses-the-tpm#windows-hello-for-business

Could you please route to relevant group?

Regards,
Pooja

**Comment by ginami** [comment]
Hi @pkuntal -- looks like that doc is in a different repo...I don't have a way to route your question to an author outside my group. Sorry about that! I recommend opening a new issue by adding your question  at the bottom of that TPM page. That should go directly to the author of that page, who can hopefully answer you.
