### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by under3415** [MicrosoftDocs/windows-uwp#974]
Add details about what capabilities need to be declared.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2b0e69-76ea-2572-83e6-6d1edce31965
* Version Independent ID: ed77ce6e-e89f-219d-741a-c2214f136cfa
* Content: [Postpone app suspension with extended execution - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/launch-resume/run-minimized-with-extended-execution)
* Content Source: [windows-apps-src/launch-resume/run-minimized-with-extended-execution.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-minimized-with-extended-execution.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment]
Hi, @under3415, this topic encompasses (and provides links to) several different feature areas and scenarios, some of which require capabilities and some of which don't. It's not clear to me that drawing together the union of all of those capabilities and mentioning them on this topic would be the right thing. If you follow the links to API ref (or other conceptual) topics, then you'll find info on any required capabilities.

Please let me know if there are any specific capabilities that are not correctly documented. I'll leave this issue open for a while. Thanks again! ~Steve
