### ISSUE TITLE
Add capability names for the manifest

### ISSUE THREAD

**Issue by under3415** [MicrosoftDocs/windows-uwp#975]
You forgot to include capability names for the package.appmanifest! You have scenario and usage but not the actual name that needs to be added to the file. Perhaps you expect the GUI to handle this, but Visual Studio 2017 GUI only has a small subset of capabilities, for everything else user needs to edit the manifest in a text editor...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by msatranjr** [comment]
All the names are mentioned clearly in bold under the usage column. Can you further clarify and perhaps give examples of what you expect?
