### ISSUE TITLE
Com server registered, toast not showing in action center

### ISSUE THREAD

**Issue by Gaz83** [MicrosoftDocs/windows-uwp#976]
So in my WPF application I have this

private void Application_Startup(object sender, StartupEventArgs e)
        {
            // Global exception handling  
            Application.Current.DispatcherUnhandledException +=
                new DispatcherUnhandledExceptionEventHandler(AppDispatcherUnhandledException);
            // Register AUMID and COM server (for Desktop Bridge apps, this no-ops)
            DesktopNotificationManagerCompat.RegisterAumidAndComServer<MyNotificationActivator>("avol..tion_bf0a9ac762a9ed29_992faeba6cbf1b42");
            // Register COM server and activator type
            DesktopNotificationManagerCompat.RegisterActivator<MyNotificationActivator>();
         }

I can see the toasts fine but they do not appear in the action center.

At the moment, this is MyNotificationActivator

// The GUID CLSID must be unique to your app. Create a new GUID if copying this code.
    [ClassInterface(ClassInterfaceType.None)]
    [ComSourceInterfaces(typeof(NotificationActivator.INotificationActivationCallback))]
    [Guid("072B6ADA-3E2F-4401-9D11-94B620832C03"), ComVisible(true)]
    public class MyNotificationActivator : NotificationActivator
    {
        public override void OnActivated(string invokedArgs, NotificationUserInput userInput, string appUserModelId)
        {
            // TODO: Handle activation
        }
    }

Oh, and I am using ClickOnceInstall.

**Comment by ginami** [comment]
Hi @Gaz83 --which doc are you referring to? (This will help me route your question to the correct author.) Thank you!

**Comment by Gaz83** [comment]
@ginami 
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop

**Comment by ginami** [comment]
Thanks @Gaz83 !

**Comment by mijacobs** [comment]
@andrewleader Is this something you can answer?

**Comment by andrewleader** [comment]
@Gaz83 did you follow [Step 5](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#step-51-wix-installer), where you add a **Start menu shortcut that has the AUMID and CLSID** property?

We only have WiX instructions, but you'd have to do something similar for ClickOnceInstall. The shortcut has to be in Start for notifications to appear as described in [Step 10](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop#step-10-deploying-and-debugging). Make sure you install your app via the installer so that the shortcut gets created, and make sure the properties on the shortcut are specified and match your AUMID and CLSID.

**Comment by Gaz83** [comment]
From what I read, you can't set the AUMID for a ClickOnce, it does this for you. I managed to find this [https://jcutrer.com/howto/windows/find-aumid](url) and used that in step 5.2. The toast appears so I guess I got this right. I don't know how to set the CLSID on the shortcut with a ClickOnce.

**Comment by ndw6152** [comment]
Hi any update on this issue? I am also trying to implement some Toast notifications through a Win32 app but currently the toast does not show up (I have a different installer than WiX) 
@Gaz83 Were you able to somehow set the CLSID without using WiX?
Also could you let me know what Win10 build version you are running on?

**Comment by Gaz83** [comment]
@ndw6152 I can get the AUMID to get the popup notification to show. You will first need to deploy your application. Once installed, follow this guide to get the AUMID. [https://jcutrer.com/howto/windows/find-aumid](url). You use the AUMID in step 5.2.

On my works computer, I am on Windows 10 build 1803. My toast appears and also appears in action centre but after the toast disappears it goes from the action centre too. I believe this is because I need to set the CLSID on the shortcut, which I cannot do.

**Comment by ndw6152** [comment]
@Gaz83 thanks for the reply. After setting the AUMID I was also able to see the the toast notification. I need to look into ShellLinks to see how I can set the CLSID (it's definitely need to be set in order for the toast to persist in the action center)

**Comment by Lechus** [comment]
ClickOnce - to get your AppId. 
https://www.devexpress.com/Support/Center/Question/Details/T613322/xaf-text-notification-using-toasts-in-winforms-apps-deployed-through-click-once-not
