### ISSUE TITLE
I started out, "How hard could that be?"

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#977]
Fortunately I didn't have to do on my own.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b1f9e3-1f19-d3f3-368f-396a1c4f918e
* Version Independent ID: a68fdcb7-a20f-87cb-711a-47254e0b233a
* Content: [Speech recognition - UWP app developer](https://docs.microsoft.com/en-ca/windows/uwp/design/input/speech-recognition?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification#related-articles)
* Content Source: [windows-apps-src/design/input/speech-recognition.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/speech-recognition.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @jensocan. Closing issue as there is no action item or question.
