### ISSUE TITLE
MS Fluent

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#978]
Fluent design

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fccec470-cfbb-9a8b-91a5-ee51393f1e5e
* Version Independent ID: dbebddc4-57a1-1888-4da6-a798316f4a2a
* Content: [Design basics - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/)
* Content Source: [windows-apps-src/design/basics/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by ginami** [comment]
Hi @rarogpro  -- let us know if you have specific feedback on any of our docs. Thanks!
