### ISSUE TITLE
Incorrect Documentation?

### ISSUE THREAD

**Issue by v-jessmi** [MicrosoftDocs/windows-uwp#980]
I came to this page to find out how to find my IP address while on a HoloLens device and connect to it. I know I can do it through the local USB connection and going to 127.0.0.1:10080 and looking up the system info. However, from the device there is no "Advanced Options" in the Network -&gt; Wifi menu. I actually had to go to the "Hardware properties" menu to find it. I believe I have the latest HoloLens OS so I think this documentation is out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deaa22ed-9e69-2068-1793-8417d40a4f7c
* Version Independent ID: 34296d5a-4c99-2d82-4be8-0a398e79ec74
* Content: [Device Portal for HoloLens - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-hololens)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-hololens.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-hololens.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by eliotcowley** [comment]
Hi @v-jessmi, thanks for catching this! I've updated the doc.
