### ISSUE TITLE
Prevent HoloLens from going to sleep

### ISSUE THREAD

**Issue by kknsy** [MicrosoftDocs/windows-uwp#981]
Prevent HoloLens from going to sleep

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ab644-ee7d-3dec-cd0f-cbb1e4d8b6ac
* Version Independent ID: 97eecc36-8e2e-d4c7-1ecb-948e0846bda5
* Content: [Device Portal core API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core#app-file-explorer)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by ginami** [comment]
Hi @kknsy -- please let us know if you have some specific feedback on our Windows developer docs. Thank you!
