### ISSUE TITLE
IL2CPP from Microsoft

### ISSUE THREAD

**Issue by equalent** [MicrosoftDocs/windows-uwp#983]
.NET Native is a very good tool but it would be even better if you could wrap .NET in pure C++ and make MSBuild convert .NET assemblies to C++ or ASM so developers can build them standalone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de0709f4-087a-4192-01d1-61cc8665b6ba
* Version Independent ID: 1492eb8c-d2c9-55e6-dea8-11d7c057cec1
* Content: [Optimize your .NET Desktop apps with native images - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-r2r)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-r2r.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-r2r.md)
* Product: **windows**
* GitHub Login: @rido-min
* Microsoft Alias: **normesta**

**Comment by jkotas** [comment]
Thank you for your suggestion. Better interop with other languages is definitely on the .NET roadmap, for all platforms, not just UWP. 

https://github.com/dotnet/coreclr/issues/19566, https://github.com/dotnet/corert/pull/5703 or https://github.com/mono/embeddinator-4000 are discussions and prototypes related to this that you may find interesting.

**Comment by mcleanbyron** [comment]
Because this is a general comment/suggestion about .NET and not feedback on the UWP documentation itself, I am closing this issue.
