### ISSUE TITLE
How to publish ACPITABL.dat to BSP or Raspberry Pi device directly

### ISSUE THREAD

**Issue by ChrisSchaller** [MicrosoftDocs/windows-uwp#984]
Using this information I feel confident that I can define the additional GPIO that I have wired up to my processor (based on RaspberryPi) now that I have a ACPITABL.dat, how can I deploy this to a Raspberry Pi or how can I include this in the BSP to deploy to the device? I have gone through the labs on building and deploying a custom BSP but so far I cannot find documentation that links ACPI to the BSP process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563be75d-5703-601b-b1e5-4b4d98be597d
* Version Independent ID: e754993a-b516-93fa-0fd0-4518d00d93aa
* Content: [Enable usermode access to GPIO, I2C, and SPI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-usermode-access#apendix)
* Content Source: [windows-apps-src/devices-sensors/enable-usermode-access.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/enable-usermode-access.md)
* Product: **windows**
* GitHub Login: @jordanrh1
* Microsoft Alias: **wdg-dev-content**

**Comment by jordanrh1** [comment]
Hi Chris, there are two routes:
 - Use the *test only* [acpitabl.dat feature](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enable-usermode-access#compile-and-load-asl-with-acpitabldat) to override the existing rhproxy declaration 
 - Edit the [default ACPI tables](https://github.com/ms-iot/RPi-UEFI/blob/ms-iot/Pi3BoardPkg/AcpiTables/Rhpx.asl) and [rebuild UEFI](https://github.com/ms-iot/RPi-UEFI#building)

**Comment by Karl-Bridge-Microsoft** [comment]
Question answered.
