### ISSUE TITLE
Tinkering with the xbox 

### ISSUE THREAD

**Issue by rickasheye** [MicrosoftDocs/windows-uwp#985]
im a young developer and I would like to tinker with the xbox by debugging my games on xbox but I don't want to pay the fee neither I want to release anything with a price would be able to get an exception or???

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726a5c98-ba0b-38a0-d86e-2d5df4745d1a
* Version Independent ID: 643673cc-0b57-86f6-e00d-13aad2ef8d20
* Content: [Opening a developer account - UWP app developer](https://docs.microsoft.com/en-au/windows/uwp/publish/opening-a-developer-account)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by rickasheye** [comment]
I am willing to release on the store but I don't have too if you don't want me too

**Comment by JnHs** [comment]
You can start developing an Xbox game on a PC first, but when you're ready to use the retail Xbox console as a development console for running test builds etc., you'll need to have a developer account and the one-time registration fee will be required (for an individual developer account this is currently $19 USD). More info on getting started with game development can be found here: https://docs.microsoft.com/en-us/windows/uwp/gaming/getting-started
