### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by batchee7** [MicrosoftDocs/windows-uwp#986]
Clicking "Use opencv with mediaframereader" takes you to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 273d90df-0507-f46a-45c8-05adb560610f
* Version Independent ID: 39d93000-faab-677d-f94a-47d0f80d5fd0
* Content: [Process audio frames with MediaFrameReader - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/process-audio-frames-with-mediaframereader#feedback)
* Content Source: [windows-apps-src/audio-video-camera/process-audio-frames-with-mediaframereader.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/process-audio-frames-with-mediaframereader.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Sorry for the delay in addressing this issue. It appears that this issue has been fixed.
