### ISSUE TITLE
d:DataContext 不生效

### ISSUE THREAD

**Issue by HaoLife** [MicrosoftDocs/windows-uwp#988]
&lt;Page
    x:Class="App2.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="using:App2"
    d:DataContext="{d:DesignInstance Type=vm:MainViewModel,IsDesignTimeCreatable=True}" 
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"&gt;
    &lt;StackPanel&gt;
        &lt;TextBlock Text="{Binding Text}" /&gt;
    &lt;/StackPanel&gt;
&lt;/Page&gt;

我的代码是这样的，但是在Blend上d:DataContext 上的数据并没有生效，一定要使用Page.DataContext 去绑定数据是才可以，还有json模式也无法生效，d:DataContext="{d:DesignData /SampleData/Main.json, Type=vm:MainViewModel}"  ，能提供有效的示例嘛。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51100eeb-4a55-5997-eee8-2ed0047be78f
* Version Independent ID: d9d5ad3b-4932-c02f-bac0-4dd5a9dd48fb
* Content: [Sample data on the design surface, and for prototyping - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/displaying-data-in-the-designer)
* Content Source: [windows-apps-src/data-binding/displaying-data-in-the-designer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/displaying-data-in-the-designer.md)
* Product: **windows**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by HaoLife** [comment]
D:designinstance does not take effect in the UWP, but it can be used in WPF
@mcleblanc

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
