### ISSUE TITLE
 I did not use the ItemInvoked app to work properly.

### ISSUE THREAD

**Issue by OmPisit** [MicrosoftDocs/windows-uwp#989]
public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            InitializeComponent();
        }

        private void AppFrame_Navigated(object sender, NavigationEventArgs e)
        {
            navSample.IsBackEnabled = appFrame.CanGoBack;
            if (appFrame.SourcePageType != typeof(SettingsPage))
            {
                if (appFrame.SourcePageType == typeof(HomePage))
                {
                    navSample.SelectedItem = navSample.MenuItems[0];
                }
                else if (appFrame.SourcePageType == typeof(Page1))
                {
                    navSample.SelectedItem = navSample.MenuItems[2];
                }
                else if (appFrame.SourcePageType == typeof(Page2))
                {
                    navSample.SelectedItem = navSample.MenuItems[3];
                }
                else if (appFrame.SourcePageType == typeof(Page3))
                {
                    navSample.SelectedItem = navSample.MenuItems[4];
                }
            }
            else
            {
                navSample.SelectedItem = navSample.SettingsItem;
            }
        }

        private void Navigationview_Loaded(object sender, RoutedEventArgs e)
        {
            appFrame.Navigate(typeof(HomePage));
        }

        private void NavigationView_SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
        {
            navSample.Header = (args.SelectedItem as NavigationViewItem).Content;

            if (!args.IsSettingsSelected)
            {
                switch ((args.SelectedItem as NavigationViewItem).Tag)
                {
                    case "home":
                        appFrame.Navigate(typeof(HomePage));
                        break;
                    case "sample1":
                        appFrame.Navigate(typeof(Page1));
                        break;
                    case "sample2":
                        appFrame.Navigate(typeof(Page2));
                        break;
                    case "sample3":
                        appFrame.Navigate(typeof(Page3));
                        break;
                    default:
                        break;
                }
            }
            else
            {
                appFrame.Navigate(typeof(SettingsPage));
            }
        }

        private void NavigationView_BackRequested(NavigationView sender, NavigationViewBackRequestedEventArgs args)
        {
            appFrame.GoBack();
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by OmPisit** [comment]
MenuItems [1] is <NavigationViewItemSeparator />.

**Comment by YuliKl** [comment]
@OmPisit, thank you for the code snippet, but can you clarify what issue you've encountered? Is the ItemInvoked event not behaving as you expected?

**Comment by mijacobs** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
