### ISSUE TITLE
Missing links to NavigationView

### ISSUE THREAD

**Issue by rbeesley** [MicrosoftDocs/windows-uwp#990]
In https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#guidelines-for-custom-back-navigation-behavior, there are two relative links to [NavigationView](../controls-and-patterns/navigationview.md) which do not actually link to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab5201c-d8c8-1804-a225-4420f66d77ea
* Version Independent ID: 2d217eac-b2cd-553a-970f-32bb043fc353
* Content: [Navigation history and backwards navigation (Windows apps) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#guidelines-for-custom-back-navigation-behavior)
* Content Source: [windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/navigation-history-and-backwards-navigation.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by jwmsft** [comment]
@rbeesley, thanks for letting us know about this. The links are fixed now.
