### ISSUE TITLE
Fluent design toolkit for Figma?

### ISSUE THREAD

**Issue by Mancerrss** [MicrosoftDocs/windows-uwp#991]
I thought the Fluent design team on Microsoft already using Figma as their primary design tool? I've already heard to some of this too and sees some references of it including this from Figma's recent blog post on their Medium account

From https://blog.figma.com/figma-faster-d1947f9c26ca

> “We were stress-testing the limits of what Figma could do before we adopted it as our team’s primary tool,” Kyle Anderson, Senior Product Designer on the Fluent team, told us.

So where actually the toolkit for Figma? is it internal for now as you guys really stressing Figma before you support it? please release it already, also since it's cloud based, you guys can push easily some changes and updates to all designers using it, without downloading new file again. 

Please don't forgot to not only enable it's dev lookup, let us also clicks do select it without ability to make changes, so we can copy and paste components from your documents from our own documents

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9fc7b1d-8b97-598a-f059-093d94972931
* Version Independent ID: 943e9c97-f223-4d3c-730c-a7f20cb04560
* Content: [Design toolkits and samples for UWP apps - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/design/downloads/)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/downloads/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @Mancerrss,
I'm checking with the design team about the availability of the Figma toolkit; I'll get back to you after I hear back.

**Comment by Mancerrss** [comment]
Thanks. Please release it from now on and just push updates and maintain it from now on

Also I saw some images on your documentation, I know this is damn well is Figma https://docs.microsoft.com/en-gb/windows/uwp/design/style/images/icons/icon-scale.gif

**Comment by mijacobs** [comment]
I heard back from the Design team--the Figma toolkit will be available to the public soon. We'll post instructions on how to get it to our Design Toolkits page.

**Comment by keithnicholson** [comment]
Once I get the toolkit, how do I integrate it into my UWP app?  How do I export correctly to be consumed by my XAML?  I would love a reference or article on this!

Peace,
Keith
