### ISSUE TITLE
Are you seriously recommending Wingdings for more icons?!?

### ISSUE THREAD

**Issue by Mancerrss** [MicrosoftDocs/windows-uwp#992]
&gt; You don't have to use the Segoe MDL2 Assets font--you can use any font the user has installed on their system, such as Wingdings or Webdings.

Cmon. You guys just previously said 

&gt; Don't use an icon if its meaning isn't clear, or if making it clear requires a complex shape.

Conflicting logic in the documentation

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090a5bbe-1b89-c80b-4ad8-a932d38246ab
* Version Independent ID: 5166ef46-fb83-98fb-b852-f16c5ac3ef8e
* Content: [Icons - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/design/style/icons)
* Content Source: [windows-apps-src/design/style/icons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/icons.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by amartens181** [comment]
It's easier to copy/paste if it's local 😉
I'm more concerned that they used "value" for the string name 😒

**Comment by jevansaks** [comment]
You don't have to use these fonts if you don't want to, this is just guidance.
