### ISSUE TITLE
Where's the icon grid guidelines for creating our own icons?

### ISSUE THREAD

**Issue by Mancerrss** [MicrosoftDocs/windows-uwp#994]
Back then when Windows 10 was just released, the Metro transitioned to MDL2 we got a PDF file right in this documentation site for the basics of our lackluster design guidelines, it shows the new 1px thin style Iconography of MDL2, and it even shows it's grid, what shapes to her overlayed as our shape guides and on what grid size we should construct it. 
Where is it now? Please if you know what I'm talking about please bring it back on this page. 

Please show us the icon grid size and guide shapes, when to Pixel compensate or align it, how to properly choose size or shape, shapes and outlines dos and dont's and how to properly safe space and margin it to be geometrically balanced and middle aligned

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090a5bbe-1b89-c80b-4ad8-a932d38246ab
* Version Independent ID: 5166ef46-fb83-98fb-b852-f16c5ac3ef8e
* Content: [Icons - UWP app developer](https://docs.microsoft.com/en-gb/windows/uwp/design/style/icons)
* Content Source: [windows-apps-src/design/style/icons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/icons.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Are you talking about the doc that had illustrations like this? 

![angles](https://user-images.githubusercontent.com/16708640/45644439-942fd180-ba72-11e8-870c-bef12d92d4b6.PNG)

**Comment by Mancerrss** [comment]
Yes that's what I'm talking abouy. Please update your documentation with those too and the proper margins or bounding box or size for each icons. And all the things I asked above too please if you can. 

It'll make designing more easier to understand for us, I able to Master making Material design Iconography first than to understand how to make MDL2/Fluent Iconography bc of the lacking, contradicting and incomplete guidelines. 

It's like you guys at Microsoft design are the only one that can understand your rules and guidelines yourselves

**Comment by Mancerrss** [comment]
Hi again. I found the document. I happend to still have a copy of it. It's last updated in March 2016. I've scanned our design guidelines and there's still so many missing and contradicting guidelines vs that. If this documents and it's rules is still relevant to Fluent desihn, please merge it back to our new online guidelines documentation again

**Comment by mijacobs** [comment]
We've made a lot of updates to our guidelines since that article was release, but you make a good point about the type of guidance it contained. I'll work with our design team to add more of that type of info to this article. Thank you again for the feedback!

**Comment by alexmalk** [comment]
+1, thanks for looking into this Mike!

**Comment by mijacobs** [comment]
We don't have any plans to update this doc with info on how to design icons-the focus of this documentation is how to use existing icons and shapes.
