### ISSUE TITLE
Example does not compile.

### ISSUE THREAD

**Issue by dutley** [MicrosoftDocs/windows-uwp#997]
Multiple Compile errors resulted from compiling the above code most from base.h
Examples follow
c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(2185): error C3861: 'from_abi': identifier not found
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(2185): note: This diagnostic occurred in the compiler generated function 'conditional&lt;_Test,T,_Ty2&gt;::type winrt::impl::as(From *)'
1&gt;        with
1&gt;        [
1&gt;            _Ty2=winrt::com_ptr&lt;T&gt;
1&gt;        ]
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(2209): error C3861: 'from_abi': identifier not found
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(2209): note: This diagnostic occurred in the compiler generated function 'conditional&lt;_Test,T,_Ty2&gt;::type winrt::impl::try_as(From *) noexcept'
1&gt;        with
1&gt;        [
1&gt;            _Ty2=winrt::com_ptr&lt;T&gt;
1&gt;        ]
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(3850): error C3861: 'from_abi': identifier not found
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(3873): note: see reference to class template instantiation 'winrt::weak_ref&lt;T&gt;' being compiled
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(2984): note: see reference to class template instantiation 'winrt::com_ptr&lt;ILanguageExceptionErrorInfo2&gt;' being compiled
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(3054): note: see reference to class template instantiation 'winrt::com_ptr&lt;IRestrictedErrorInfo&gt;' being compiled
1&gt;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.15.26726\include\type_traits(616): note: see reference to class template instantiation 'std::basic_string_view&lt;wchar_t,std::char_traits&lt;wchar_t&gt;&gt;' being compiled
1&gt;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.15.26726\include\xstring(2124): note: see reference to class template instantiation 'std::is_convertible&lt;const _StringViewIsh &,std::basic_string_view&lt;wchar_t,std::char_traits&lt;wchar_t&gt;&gt;&gt;' being compiled
1&gt;        with
1&gt;        [
1&gt;            _StringViewIsh=const wchar_t *
1&gt;        ]
1&gt;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.15.26726\include\xstring(2122): note: see reference to variable template 'const bool conjunction_v&lt;std::is_convertible&lt;wchar_t const * const &,std::basic_string_view&lt;wchar_t,std::char_traits&lt;wchar_t&gt; &gt; &gt;,std::negation&lt;std::is_convertible&lt;wchar_t const * const &,wchar_t const *&gt; &gt; &gt;' being compiled
1&gt;c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.15.26726\include\xstring(2281): note: see reference to alias template instantiation '_Is_string_view_ish&lt;const wchar_t*&gt;' being compiled
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(6308): error C3861: 'to_abi': identifier not found
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17134.0\cppwinrt\winrt\base.h(7189): error C7510: 'get_weak': use of dependent template name must be prefixed with 'template'
1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d376e5-ada9-78e7-a7c6-028c8acd4e14
* Version Independent ID: 84bb5e64-fd06-7561-eea1-206ababc786f
* Content: [Get started with C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @dutley, please see [this frequently-asked question](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq#why-wont-my-new-project-compile-im-using-visual-studio-2017-version-1580-or-higher-and-sdk-version-17134). I'll close this issue, but please reopen it (or create a new one) if you're still blocked. ~Steve
