### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by WiTester** [MicrosoftDocs/windows-uwp#998]
- Exporting Excel spreadsheet as .CSV (Comma delimited) with Unicode (UTF-8) doesn't seem to work and most languages aren't recognised after import. 
- Exporting listings and then importing the exact file with no modifications to a pre-order submission doesn't seem to work - spits out an error.
- Uploading a trailer to a pre-order (bundle) submission doesn't seem to work. The video uploads but then nothing is selectable in the "Choose a trailer to play at the top of your Store listing".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f3b82f-eca4-13e7-91fa-094976277e1b
* Version Independent ID: d600811c-5f35-e818-13de-881d39f41117
* Content: [Import and export Store listings - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/import-and-export-store-listings)
* Content Source: [windows-apps-src/publish/import-and-export-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/import-and-export-store-listings.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for reaching out. Regarding the trailer issue, one possible reason that you wouldn't be able to select a trailer to play at the top is if you have not also included the 16:9 image described here: https://docs.microsoft.com/en-us/windows/uwp/publish/app-screenshots-and-images#windows-10-and-xbox-image-169-super-hero-art
For the other issues (and/or if this doesn't resolve the trailer issue) please open a support request via http://aka.ms/storesupport (or talk to your account manager) so we can troubleshoot further and determine if there are any bugs on our end. I hope we'll be able to resolve these issues quickly!
